### ISSUE TITLE
Understand Data Retrieval Requirements 

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#1]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597097764001) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD
  
Acceptance Criteria:

-  When the team begins building the services to retrieve data, they will know the data elements they need to retrieve and where it resides in the current CAMDBSP database.

- When the team begins to build the services to retrieve data, they will know the formats required for output as directed by the customers from UX Research

**Comment by JorjaComer** [comment]
All issues resolved
