### ISSUE TITLE
Update Vintage Year in AH API 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1001]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to enter filter criteria for vintage year so that my data set is concise 

## Acceptance Criteria
Given that a user has built a query and has not entered filter criteria for vintage year (not required)
When the endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered a single vintage year or multiple vintage years
When the endpoint is executed 
Then the system displays the records that match the criteria 

## Dev Tasks

- [x] Add APIQuery to allowance controller
- [x] Modify paramsDTO to make vintage year optional and multi select
- [x] Modify query builder 

## Context
[Error Message Repo ](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Vintage Year: Optional, multi, Format: YYYY, 1995 or greater
Vintage Year: 
Validate that the date is in the format YYYY
Validate that all years are equal to or greater than 1995
Error Message: TBD Need an error message that asks users to enter date in the YYYY format 

Vintage Year: Optional, multi, Format: YYYY, 1995 or greater
## Testing
Test Case: [TC147](https://cvpcorp.testquality.com/project/11428/plan/20060/test/278041)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC147 passed @tlageman-epa 
https://easey-dev.app.cloud.gov/api/allowance-mgmt/allowances/holdings?page=1&perPage=10

https://easey-dev.app.cloud.gov/api/allowance-mgmt/allowances/holdings?vintageYear=2015|2019


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6ef08a86-862e-49bd-abd9-2d6df25e2eb9)
