### ISSUE TITLE
Update MDM for Program Filter Criteria 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1002]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to see a list of programs so that I can include the correct data in my query. 

## Acceptance Criteria
Given that a user has made a GET request to the MDM programs endpoint
When the request is executed 
Then the system displays all programs 

Given that a user has made a GET request to the MDM programs endpoint with the isActive parameter set as true
When the request is executed 
Then the system displays all active programs 

Given that a user has made a GET request to the MDM programs endpoint with the isActive parameter set as false
When the request is executed 
Then the system displays all inactive programs 

Given that a user has made a GET request to the MDM programs endpoint with the allowanceOnly parameter set as true
When the request is executed 
Then the system displays only allowance programs

Given a user has selected the url
When the url is executed
Then the system will return account type records in JSON format
And for each record will display (in addition to existing values):

- Program Group description
- Ozone indicator 
- Annual indictor 
- Allowance Indicator
- Retired Indicator
- Trading end date 

## Dev Tasks
- [x] Update DTO
- [x] Update ParamsDTO
- [x] Update Program Entity
- [x] Add Program Group Entity
- [x] Update Program Map
- [x] Move query logic from service to repository 
- [x] Update query logic to add additional parameters and fields 
- [x] Update Service
- [x] Update Unit Tests

## Context
Update filter criteria to: 

- return all programs
- return active programs
- return inactive programs
- return allowance only programs 

## Testing
Test Case: [TC139](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277186)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
TC139 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=true
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/18377341-b2fc-4e9c-b062-1b921e0b318f)

https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=false
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/561c6720-3706-4ceb-a4ac-85b5e8fe7b35)

https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?allowanceOnly=true
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/fea6d812-5886-43bf-830c-7fa5ccecf592)

**Comment by david-cvp** [comment]
Reopened ticket - actually seems like OTC and NBP programs are inactive but they dont have a trading end date.

![image](https://user-images.githubusercontent.com/63069273/113881817-c74e2380-978a-11eb-8567-36d73cd6c63d.png)

**Comment by david-cvp** [comment]
Closing this ticket now. There is a problem with the underlying data for programs.

EPA will determine what changes to the database need to occur. CVP will replicate these changes in our dev environment.

Bug ticket #1071 created to track the work
