### ISSUE TITLE
Add license checker to workflows

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1007]
- [ ] To  Be Completed in tandem with [#3615](https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/us-epa-camd/easey-ui/3615)

Implement a package dependency license validation within the CI/CD pipeline to ensure all licenses are compatible with the MIT license and/or on the approved license list. In the devops repo scripts folder there is a validate-license.sh script that will look at all package dependency license and validate them against the approved-licenses.csv in the root of the devops folder. This step should probably go either right before the build or after build if build is required and trigger a failure if there is any dependencies using licenses not on the approved list.

**Comment by MaeganWood64** [comment]
-Bumped out to PI 6 9/23

**Comment by MaeganWood64** [comment]
- To be worked on after CAMPD Prod
