### ISSUE TITLE
QA Check Rule Management 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1011]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as
- User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)
- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
Provide the ability to manage the rules that comprise the QA check engine 

## Context
BRE architectural diagram: https://github.com/US-EPA-CAMD/diagrams/blob/develop/EPA%20CAMD%20BRE%20Check%20Engine.pdf

This functionality will be handled via a UI under the admin console in EASEY In. We will need a role specific to rule management and not accessible to other admin functions 

- Create rule
- Disable/Deactivate/Ignore rule (globally, for all submissions)
- Suppress rule for a specific submission and/or time frame 
- Set severity (e.g. critical/non critical)

**Comment by david-cvp** [comment]
- Styling rule authoring
- Suppress rules (error supression)
- Testing
- UI to view ongoing and previous evaluation job processes (Quartz.net scheduled jobs including static datasets too)
