### ISSUE TITLE
Select data type page responsiveness (retest only)

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1013]
Lowest res. supported 1250 

#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Navigate to CAMPD Custom Data Download page| The page is displayed with:</p><br><ul><br><li>Header, footer, and content according to wireframes and acceptance criteria</li><br><li>Header contains menu and search</li><br><li>Footer contains menu</li><br><li>Option to select emissions, allowance, or compliance data</li><br></ul><br><p>WIREFRAMES:<br /><br><a href="https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/">https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/</a>| Fail |
| 2| Select a data type (such as Emissions) and then click Continue| The filter criteria page is displayed (no content)| Fail |

### Actual Results
Step 1 failed because CAMPD does not match wireframes. At 100% zoom and 1920x1080 resolution, the data type buttons and Continue button are cut off.

![image](https://user-images.githubusercontent.com/63069273/112851284-d6412180-9078-11eb-94c5-2d15216f90ba.png)

#### Wireframes
![image](https://user-images.githubusercontent.com/63069273/112851235-c9243280-9078-11eb-961c-a8e3181e6979.png)

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com defect [D14](https://cvpcorp.testquality.com/project/11428/result/2336489/defect/7580). Do not remove or edit.

**Comment by JanellC** [comment]
TC125 passed
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/41d0acd3-e6bf-4642-a1b5-cf2c639d258e)
