### ISSUE TITLE
CAMPD header EPA logo should be SVG format

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1015]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Navigate to CAMPD Custom Data Download page| The page is displayed with:</p><br><ul><br><li>Header, footer, and content according to wireframes and acceptance criteria</li><br><li>Header contains menu and search</li><br><li>Footer contains menu</li><br><li>Option to select emissions, allowance, or compliance data</li><br></ul><br><p>WIREFRAMES:<br /><br><a href="https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/">https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/</a>| Fail |
| 2| Select a data type (such as Emissions) and then click Continue| The filter criteria page is displayed (no content)| Fail |

### Actual Results
Step 1 failed because CAMPD does not match wireframes. EPA logo should be SVG format, not PNG format.

![image](https://user-images.githubusercontent.com/63069273/112852704-2bc9fe00-907a-11eb-87ff-53e9f91d3373.png)

#### Acceptance Criteria
When a user clicks the "EPA" logo in the primary white header
Then the user should be redirected to https://www.epa.gov/ in a new tab

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com defect [D16](https://cvpcorp.testquality.com/project/11428/result/2336489/defect/7582). Do not remove or edit.

**Comment by JanellC** [comment]
@tlageman-epa Defect D16 resolved. EPA logo is in the SVG format. 

![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_20929.png)
