### ISSUE TITLE
EASEY-IN header EPA logo format & link

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1016]
# 🪳 Bug
EASEY-IN does not match wireframes. EPA logo should be SVG format, not PNG format.
![image](https://user-images.githubusercontent.com/63069273/112852842-4dc38080-907a-11eb-93c2-2f1a2101df86.png)

#### 👍 Acceptance Criteria
When a user clicks the "EPA" logo in the primary blue header
Then the user should be redirected to https://www.epa.gov/ in a new tab

#### 💼 Assets
[epa-logo-white.svg](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/965d3e98-7211-4255-b762-c4176c0fa85e)

**Comment by mosesdeeCVP** [comment]
Test case added [TC164
](https://epacamd.testquality.com/project/11428/plan/19813/test/fullscreen/279872)

**Comment by mosesdeeCVP** [comment]
![1016 EASEY-IN header EPA logo format & link - 1.PNG](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc843357-37e1-42f2-a8d8-19d2bae1d6d9)

**Comment by mosesdeeCVP** [comment]
![1016 EASEY-IN header EPA logo format & link - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f40bbefc-83d8-4460-9126-d0ac13d89b3c)

**Comment by mosesdeeCVP** [comment]
![1016 EASEY-IN header EPA logo format & link - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/afd6791a-fde0-4f11-a887-43f78dc73d7c)

**Comment by mosesdeeCVP** [comment]
Test Passed. Ticket Closed
