### ISSUE TITLE
Informatica data migration of group #2 tables for camdmd schema

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1020]
- [x] Support Informatica as they migrate group two tables to support PI 4 development

CAMDMD SCHEMA
1-ACCOUNT_TYPE_CODE

Please add steps to run the attached [scripts.zip](https://github.com/US-EPA-CAMD/easey-ui/files/6229862/scripts.zip) during the load process. There are 3 scripts. The before.sql needs to run prior to the load to alter and drop the objects the scripts modify and create. The other 2 scripts need to run after the load to put all of the objects back in place.

**Comment by vkdontula** [comment]
Table added to the ETL.  Included pre and post load scripts as well.
