### ISSUE TITLE
Create Active/Inactive Flag for Systems 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1023]
## Acceptance Criteria
See #999 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC131](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/277031)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Case - Passed

**Comment by mosesdeeCVP** [comment]
![1023 Create Active-Inactive Flag for Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/49168555-4f5f-4b03-8df8-6af99fa39a76)
