### ISSUE TITLE
Filter Active and Inactive Components (View) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1024]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to view active and inactive Components, so that I can view all Components assigned to a System. 

## Acceptance Criteria
Given the user is viewing MP systems
when there are **both active and inactive** components
Then the system displays active components only by default 

Given the user is viewing MP systems
when there are **only active** components
Then the system displays active components only 
And the Show Inactive option is not available

Given the user is viewing MP systems
when there are **only inactive** components
Then the system displays inactive components only 
And the Show Inactive option is checked by default

Given the user has navigated to a new section of the MP (ex: methods)
When the new section has **the same** active/inactive selection 
Then system retains the active/inactive selection from the previous section 

Given the user has navigated to a new section of the MP (ex: methods)
When the new section has a **different** active/inactive selection 
Then system updates the active/inactive selection using the logic above 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC204](https://epacamd.testquality.com/project/11428/plan/19812/test/288282)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Show Inactive button unchecked by default
![1024 Filter Active and Inactive Components (View) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5510f33b-1b5f-4d12-b881-22ff84f63bd0)

**Comment by mosesdeeCVP** [comment]
Show Inactive button checked and the inactive methods are visible
![1024 Filter Active and Inactive Components (View) - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c87e3260-d9e6-49af-96a3-99e3fb587aac)

**Comment by mosesdeeCVP** [comment]
There are no active methods, so the Show Inactive button is automatically checked with no option to uncheck it.
![1024 Filter Active and Inactive Components (View) - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e7cda036-7a82-42bb-ad18-02f81c75a0cf)

**Comment by mosesdeeCVP** [comment]
There are no inactive methods so the Show Inactive checkbox does not have an option to check it. 
![1024 Filter Active and Inactive Components (View) - 04.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cab31d3f-7380-43f4-9b61-7b72e026bd2d)

**Comment by mosesdeeCVP** [comment]
There are no records to show and the system lets the user know of this. The Show Inactive checkbox is automatically checked to let the user know that both active and inactive are not available
![1024 Filter Active and Inactive Components (View) - 05.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/162735ea-fe1e-45f2-8530-d801e17b076a)
