### ISSUE TITLE
Prototype UI Design for BRE Rule Authoring (Check Engine)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1025]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

Dive into existing MP check engine and understand its capabilities
Emissions/QA out of scope, just looking into how check engine validates MP data
Worked in conjunction with #900 

Next ticket: Design BRE system
## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by jwhitehead77** [comment]
Meet with ERG and received a spreadsheet of all the MP checks with details regarding categories and order of processing. Have look through existing check engine get familiar with the process and reviewed check specifications.

High Level Architecture
https://github.com/US-EPA-CAMD/diagrams
https://github.com/US-EPA-CAMD/diagrams/blob/develop/EPA%20CAMD%20BRE%20Check%20Engine.pdf

Built preliminary UI for Rule Authoring
https://easey-dev.app.cloud.gov/admin/rules

Built preliminary API for Rule Authoring
https://github.com/US-EPA-CAMD/easey-rules-api

Built preliminary Scheduling & Evaluation process
https://github.com/US-EPA-CAMD/easey-job-scheduler
