### ISSUE TITLE
Create State MDM Endpoint 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1026]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to see a list of valid states so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return states in JSON format
And for each record will display:

- 2 letter postal abbreviation(code)
- State name 
- EPA Region 

## Dev Tasks
- [x] Create State Entity
- [x] Create State DTO
- [x] Create State Repository
- [x] Create State Map
- [x] Create State Service
- [x] Create State Controller
- [x] Create State Module
- [x]  Update routes file and app.module file with stateModule
- [x] Add Unit Tests

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC138](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277185)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
TC138 passed @tlageman-epa @JanellC 

https://easey-dev.app.cloud.gov/api/master-data-mgmt/states

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/a4903a50-014e-4066-a4eb-fe305f0e2cee)
