### ISSUE TITLE
Create Account Type MDM Endpoint 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1027]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to see a list of valid account types so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return account type records in JSON format
And for each record will display:

- Account Type code
- Account type description
- Group Code
- Group description 

## Dev Tasks

- [x] Update routes.ts
- [x] Create Account Type Controller
- [x] Create Account Type DTO
- [x] Create Account Type Code Entity
- [x] Create Account Type Group Code Entity
- [x] Create Account Type Repository
- [x] Create Account Type Map
- [x] Create Account Type Service
- [x] Create Account Type Module
- [x] Update app.module
- [x] Add Unit Tests

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:[ TC145](https://cvpcorp.testquality.com/project/11428/plan/20060/test/278039)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- created AccountType entity
- created AccountTypeGroup entity
- created AccountTypeDTO
- created AccountTypeRepository
- created AccountTypeMap
- created AccountTypesController
- created AccountTypesService
- created AccountTypesModule
- updated routes.ts
- updated app.module
- unit tests for account type
- updated unit test coverage for maps

**Comment by JanellC** [comment]
TC145 passed @tlageman-epa 
https://easey-dev.app.cloud.gov/api/master-data-mgmt/account-types

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0ccbd444-1c8a-4d1c-b8cd-0a6fe13b95fb)
