### ISSUE TITLE
Modify Control Tech MDM Endpoint 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1039]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to see a list of valid control technologies so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return control tech records in JSON format
And for each record will display:

- Control Code
- Control Description
- Control Equip Param Code
- Control Equip Param Description

## Dev Tasks

- [x] Create Control Equip Param Code Entity
- [x] Move query logic from service to repository
- [x] Modify service
- [x] Update Control Tech Map and DTO
- [x] Add Unit Tests

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC144](https://cvpcorp.testquality.com/project/11428/plan/20171/test/278038)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- created ControlEquipParam entity
  - created a relationship with ControlTechnology entity
- updated ControlTechnology entity to account for relationship
- updated ControlTechnologyRepository with new query logic to include ControlEquipParamDescription
- updated service to call getAllControlTechnologies() from the repo
- updated ControlTechnologyDTO
- updated ControlTechnologyMap
- fixed class and file names for consistency
- unit tests
  - updated other MDM endpoint's unit tests to increase test coverage on DTOs
- fixed code smells

**Comment by junie-stigdon** [comment]
## Pull Request
- updated ControlTechnologyRepository to use a leftJoin instead of an innerJoin
- updated ControlTechnologyMap to account for null controlEquipParam values

**Comment by JanellC** [comment]
TC144 passed @tlageman-epa 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b0bfde1c-c96d-44bd-b1c2-c1d09675a130)

**Comment by tlageman-epa** [comment]
@JanellC The table your provided for your check has some errors in it. (e.g. ammonia injection, and other are incorrect) I checked the API myself using swagger and it looks OK. I'm not sure why your table is incorrect, but just wanted to point that out to you.

**Comment by JanellC** [comment]
@tlageman-epa Thanks for brining that to my attention The original screen capture had a filter on it which skewed the results. I updated the screen capture above. It should be accurate now.
