### ISSUE TITLE
Modify develop branch workflow to not deploy on PR

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1042]
Explore options so that a PR does not deploy code to Dev-Int before being merged into develop

**Comment by srinivasaregeti** [comment]
Change the deploy step to look like this in develop-branch.yml

```
      - name: Deploy
        if: github.event_name == 'push'
        run: devops/scripts/deploy.sh
```

**Comment by srinivasaregeti** [comment]
Updated pipeline file in all the repositories where the develop pipeline exists.

**Comment by david-cvp** [comment]
Close out by 4/14 if everything works properly and developers report no issues

**Comment by david-cvp** [comment]
4/12 Jason says looks good
