### ISSUE TITLE
Maintain MP Location Attributes (5.0) and Relationships (3.0) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1052]
Original estimate: 13

**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

-User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed
## Feature Benefit
Provide the ability to view Location Attributes and Relationships for a particular monitoring plan 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1052?planning-poker) with ZenHub @tdavydets @sanleyCVP @dionolympiaCVP @Qb10 @jeffreyaggrey
