### ISSUE TITLE
Bulk Data Files Page 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1058]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want guidance on how to access and navigate the FTP site so that I can conduct analysis 

## Acceptance Criteria

Given that a user has accessed the Bulk Data file page 
When the functionality is displayed 
Then the page renders in accordance with the [wireframes ](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A94&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A18)
AND the web page page content is consistent with the [Bulk Data Files Content](https://teams.microsoft.com/l/file/11DD8C0E-3CCA-4502-B370-64FD61DEF748?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F2-Data%2F3-%20Bulk%20Data%20Files%20Content%20-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) document  

Given that a user has navigated to the CAMPD menu
When bulk data files is selected 
Then the site links to the bulk data files page 

Given that a user has navigated to the data home page 
When the start browsing datasets button is selected 
Then the site links to the bulk data files page 

## Developer notes 

1. During Backlog Refinement on 7/28, it was decided that "done" button on the modal should be right aligned 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/451c9d30-aa69-4031-aec7-bf5fc86153e4)

2. Url, links, meta descriptions, language, etc. should be consistent with the content document 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
The front end dev team and ui designer need to have additional conversations before this ticket can be tackled. Discussions are scheduled to take place by the end of sprint 5.3

Provide a link to the existing FTP static data set site from the new CAMPD 1.0 

[Bulk Data Files Wireframes ](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A94&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A18)

[Bulk Data files dev link ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A56)

[Bulk Data files content document](https://teams.microsoft.com/l/file/11DD8C0E-3CCA-4502-B370-64FD61DEF748?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F2-Data%2F3-%20Bulk%20Data%20Files%20Content%20-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Testing
Test Case: [TC406](https://epacamd.testquality.com/project/11428/plan/21067/test/306549)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC406 failed @tlageman-epa . Changes will be tracked in Bug: Bulk Data Files Page #2173

**Comment by JanellC** [comment]
Bug: Bulk Data Files Page #2173 resolved. This ticket is ready for 508 testing @aprematta
