### ISSUE TITLE
Implement CAMPD Home Page Main Content 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1059]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a CAMPD user I want to see a home page when I first enter the site so that I have a clear indication of how to navigate through the site 

## Acceptance Criteria 
Given that a user has navigated to the CAMPD home page 
When the page renders 
Then it is in accordance with the [wireframes ](https://xd.adobe.com/view/0ce7370c-8097-4130-9db1-ace4aab30cda-59b4/)

Given that a user has accessed the CAMPD home page on a mobile, tablet, desktop, or widescreen device
When the functionality is displayed
Then the CAMPD home page is responsive to different screen sizes (see wireframes for breakpoints) 

Given that a user has selected "home"
When the selection is executed
Then the system links to the CAMPD home page

Given that a user has selected "start your data query" 
When the selection is executed 
Then the system links to the custom data download landing page (select data type page) 

## Context
[wireframes ](https://xd.adobe.com/view/0ce7370c-8097-4130-9db1-ace4aab30cda-59b4/)

Includes blue call out box in sub header area 

Provide a landing page for CAMPD 

selecting "start your data query" will take the user to the custom data download landing page (select data type page)

home will link user to the CAMPD landing page 

## Testing 

Test Case: [TC195](https://cvpcorp.testquality.com/project/11428/plan/20058/test/287303)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@addisgmichael  This is looking good! Few notes:
1) The Pollutants in the CAMPD blurb are not in correct notation. SO2, NOX, CO2 should have the appropriate notation and be subscripts for 2, X and 2 respectively
2) There is a large white space between the 3 boxes (Data, Analysis, Viz) and the footer? ![image.png](https://images.zenhubusercontent.com/5f3fd6e5a36605390ed80be4/267736cf-8e68-4b69-a731-50bd94010098)
3) When you use the Data dropdown to open up the Custom Data Download tool in a new tab (only using ctrl + click) the top half of the homepage disappears. ![image.png](https://images.zenhubusercontent.com/5f3fd6e5a36605390ed80be4/89ee4d34-082d-46a7-807b-f36a9d1502b6)

**Comment by JanellC** [comment]
Hi @tlageman-epa thanks. We spotted these issues and are working on it.

**Comment by JanellC** [comment]
TC195 failed @tlageman-epa . I logged Bug: Implement CAMPD Home Page Main Content #1591 to track the changes

**Comment by JanellC** [comment]
The [CAMPD home page](https://easey-dev.app.cloud.gov/campd/) is ready for 508 testing.
