### ISSUE TITLE
Implement Filter Tags (incl. time period)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1064]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want to see filter tags for time period So that I can view my selection

## Acceptance Criteria
Given that a user has selected filter criteria for time period 
When the criteria is applied 
Then the system displays a filter tag with an option to clear all time period filter tags 

Given that a user has selected a time period 
When then filter tag is displayed 
Then the system displays the parameter in the tag

Given that a user has selected a time period filter tag 
When the tag is selected 
Then the system opens the time period filter panel 

Given that a user has selected to clear a filter tag 
When the filter tag is cleared 
Then the system updates the filter criteria accordingly 

## Context
Populates filter tag on Apply Filter 
if 1 parameter is selected, then show parameter in tag
If more than 1, show number of parameters 
Tags will have a hover functionality to display the list of selections  
Clicking x in tag clear filter
Click on the tag opens filter in panel 
Will provide the option to clear all filters in tag group 

Time period show date range
If operating hours is selected shows separate tag 

Filter Tags do not display until a user applies the selection 
If a user clears out the operating hours filter tag, then the selected time period is retained 
If a user clears out the time period filter tag, then the operating hours filter tag is automatically  cleared out and the time period filter resets to its default state (blank and operating hours only checked) 
If a user changes there data type and data subtype, their previous time period selections aren't retained 

## Testing
Test Case: [TC163](https://cvpcorp.testquality.com/project/11428/plan/20058/test/279664)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC163 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d16df2f9-be9d-4a34-b5a4-44e9db816836)
