### ISSUE TITLE
Retest ONLY: Inactive programs without trading end date

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1071]
Step 4 is resolved by #1482 and #1483 
## Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Perform a GET request to the program endpoint with no parameters</p><br><p><a href="https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs">https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs</a>| API returns all programs </p><br><p>Each record includes:<br /><br>Program code<br /><br>Program description<br /><br>compParameterCode<br /><br>programGroupCode<br /><br>Program Group description<br /><br>Ozone indicator<br /><br>Annual indicator<br /><br>Allowance indicator<br /><br>Retired indicator<br /><br>Trading end date| Pass |
| 2| Perform a GET request to the program endpoint using the "only active programs" parameter</p><br><p><a href="https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=true">https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=true</a>| API returns all active programs| Fail |
| 3| Perform a GET request to the program endpoint using the "only inactive programs" parameter</p><br><p><a href="https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=false">https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=false</a>| API returns all inactive programs| Fail |
| 4| Perform a GET request to the program endpoint using the "only allowance programs" parameter</p><br><p><a href="https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?allowanceUIFilter=true">https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?allowanceUIFilter=true</a>| API returns all allowance programs| Fail |

### Actual Results
When isActive=true, certain programs such as NBP and OTC are shown as active, with no trading end date.

https://easey-dev.app.cloud.gov/api/master-data-mgmt/programs?isActive=true
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/18377341-b2fc-4e9c-b062-1b921e0b318f)

According to AMPD, these programs are inactive.
![image](https://user-images.githubusercontent.com/63069273/113881817-c74e2380-978a-11eb-8567-36d73cd6c63d.png)

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com defect [D17](https://cvpcorp.testquality.com/project/11428/result/2346825/defect/7607). Do not remove or edit.

**Comment by JanellC** [comment]
Defect D17 resolved
