### ISSUE TITLE
Review error message approach and update repo as needed 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1072]
Placeholder for discussion between Jason and Jorja to ensure the error message approach and documentation support reusability 

1. Requirements / error message text
2. Technical approach for handling error messages and maintaining them in code

Monday 4/19 Datateers requirements elicitation 1pm
Add Chris and Junie to meeting

**Comment by JanellC** [comment]
Error message Repo was updated and can be found on MS Teams [here](https://teams.microsoft.com/l/file/E95CEE6E-3EC6-4619-A8C9-CEEA00ECD464?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v2.1.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)
