### ISSUE TITLE
Update hourly, daily, monthly emissions API data elements order  

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1073]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As the EPA I want the Emissions API to return the data elements in the order specified in the requirements so that the APIs are consistent and compliant with requirements 

## Acceptance Criteria
Given that a user has made a GET request to the Hourly Emissions API endpoint 
When the GET request is executed 
Then the system returns the data elements below in the specified order (see hourly emissions data elements) 

Given that a user has made a GET request to the Daily Emissions API endpoint 
When the GET request is executed 
Then the system returns the data elements below in the specified order (see daily emissions data elements) 

Given that a user has made a GET request to the Monthly Emissions API endpoint 
When the GET request is executed 
Then the system returns the data elements below in the specified order (see monthly emissions data elements) 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Due to the way the code was refactored, the emissions APIs are not returning the data elements in the order specified in the requirements.  This ticket serves a reminder to update the data elements. 

**Hourly Emissions data elements return order:** 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
OP_HOUR
OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_MASS_MEASURE_FLG
SO2_RATE
SO2_RATE_MEASURE_FLG
NOX_MASS
NOX_MASS_MEASURE_FLG
NOX_RATE
NOX_RATE_MEASURE_FLG
CO2_MASS
CO2_MASS_MEASURE_FLG
CO2_RATE
CO2_RATE_MEASURE_FLG
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

**Daily Emissions data elements return order :** 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

**Monthly Emissions data elements return order:** 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
YEAR
MONTH
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Do not need to address for JSON file. Will need to address order when we implement CSV. Will specify in CSV tickets.
