### ISSUE TITLE
Create Endpoints for MP Defaults

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1079]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAM API user I want send parameters to the MP defaults API so that I can see results

## Acceptance Criteria
Given that a user has entered a location ID 
When the API end point is executed 
Then the system displays the records that match the criteria (containing data elements below)

## Data Elements 
Parameter
Value
UOM
Purpose
Fuel type
Operating condition
Source of value
Begin time
End time

## Dev Tasks 

- [ ] Create Repo
- [ ] Create DTO
- [ ] Create ParamsDTO
- [ ] Create maps
- [ ] Add QueryBuilderHelper
- [ ] Create entities (defaults)
- [ ] Modify service and controller to return defaults data
- [ ] Unit testsRetrieve emissions defualts by Location ID.

**Comment by JorjaComer** [comment]
OBE handled by other tckets
