### ISSUE TITLE
Create MDM Endpoints for Location Attributes and Relationships Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1082]
Create MDM Endpoints for Location Attributes and Relationships data:

**Location Attributes Data:**

Material Code: Drop-down
Shape Code: Drop-down

Development Notes:
Material Code data is hosted in camdecmpsmd.material_code table
materialCode field maps to material_cd DB attribute
materialCodeDescription field maps to material_cd_description DB attribute

Shape Code data is hosted in camdecmpsmd.shape_code table
shapeCode field maps to shape_cd DB attribute
shapeCodeDescription field maps to shape_cd_description DB attribute

**Comment by mosesdeeCVP** [comment]
![1082 Create MDM Endpoints for Location Attributes and Relationships Data - Material Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3abcd8e1-e998-471f-9d8f-67cba62d54df)

![1082 Create MDM Endpoints for Location Attributes and Relationships Data - Shape Codes.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/123ead90-6338-44d4-8881-e58689953a96)

**Comment by mosesdeeCVP** [comment]
Test Case [TC485](https://epacamd.testquality.com/project/11428/plan/22772/test/314104)

Test Passed
