### ISSUE TITLE
Create MDM Endpoints for Rectangular Duct WAFs Data 

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1083]
Create MDM Endpoints for Rectangular Duct WAFs Data:

WAF Method: dropdown

Reference (Other Fields):

WAF Determination Date: date picker, format mm/dd/yyyy
WAF Start Date: date picker, format mm/dd/yyyy
WAF Start Time: Text, hh
WAF Method Code: dropdown
WAF Value: Text
Number of Test Runs: Text
Number of Traverse Points WAF: Text
Number of Test Ports: Text
Number of Traverse Points Reference: Text
Duct Width: Text
Duct Depth: Text
WAF End Date: date picker, format mm/dd/yyyy
WAF End Time: Text, hh

**Comment by vishnunavuluri** [comment]
Verified. Values for WAF Method Code showing as expected in Swagger:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5e4ec84a-7625-4785-8dd9-f2f4ea11abd7)

**Comment by mosesdeeCVP** [comment]
Test Passed
Test Case: [TC409](https://epacamd.testquality.com/project/11428/plan/22357/test/308080)
