### ISSUE TITLE
Bug: Custom Data Download Select Data SubType

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1085]
## Steps to Reproduce
| Step | Action | Expected | Status |
|-|-|-|-|
| 1 | Navigate to CAMPD Custom Data Download page and select emissions as a data type | Then the filter criteria page is displayed with the option to select a data sub type (Drop down)  The feild should be blank as default  | FAIL |
| 2 | Select data sub type (drop down) | The options are Hourly Emissions, Daily Emissions, Monthly Emissions, Quarterly Emissions, Ozone Season Emissions, Annual Emissions, Facility/Unit Attributes | FAIL |
| 3 | Select hourly emissions as a data sub type and apply the selection | The filter criteria page displays the filters for:   Time Period Program Facility State Unit Type Fuel Type Control Technologies | FAIL |
| 4 | Select filter criteria for each parameter | The filter criteria window(fly out) is displayed for each parameter | PASS |

### Actual Results
**Step 1**
Step 1 failed because the data sub type should be a drop down field and should not have any type in functionality 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f9aef476-4527-4ff8-a2cb-4b2bda694890)

**Step 2**

Step 2 failed because [per the wireframes ](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/325c55e6-63e8-4783-9d56-a5df6e35f739?hints=off)all of the data subtypes should be viewable without a scroll functionality 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/eba7708a-003f-4238-bd8a-37c96cea8421)

**Step 3**

Step 3 failed because:

1. Control Technology is missing ( This may be due to responsiveness. I can see the filter on my large desktop screen but I can not see it on my laptop)

2. State Territory should be formatted as State/ Territory [as per the wireframes ](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/5b729f78-815a-473e-91b9-23380c7cc728?hints=off)
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8f89cf5d-302d-46f3-8b2f-1119fa90049c)

3. According to the [wireframes, ](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/5b729f78-815a-473e-91b9-23380c7cc728?hints=off)all of the filters should be viewable without a scroll functionality 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1bf94ec7-c211-4402-b967-a1a4bcd048ab)

**Comment by david-cvp** [comment]
4/12 Travis agreed to all findings

**Comment by JanellC** [comment]
https://cvpcorp.testquality.com defect [D19](https://cvpcorp.testquality.com/project/11428/result/2350161/defect/7616). Do not remove or edit.
