### ISSUE TITLE
Define the process for GitHub approvals within CI/CD pipeline

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#109]
- [ ] Process documented

**Comment by srinivasaregeti** [comment]
[https://app.zenhub.com/files/287570343/18dc8254-8516-4a3b-b165-ebb398aeb4a8/download](https://app.zenhub.com/files/287570343/18dc8254-8516-4a3b-b165-ebb398aeb4a8/download)
