### ISSUE TITLE
CAMPD UI 508 Accessibility Review

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1098]
- [x] Review CAMPD UI and document 508 accessibility compliance findings
- [x] Create 508 test script for EPA

https://easey-dev.app.cloud.gov/campd/select-data-type

**Comment by aprematta** [comment]
[EPA CAMPD Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6548482/EPA.CAMPD.Accessibility.Report.docx)
[EPA CAMPD Header and Footer Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6548484/EPA.CAMPD.Header.and.Footer.Accessibility.Report.docx)

**Comment by aprematta** [comment]
Adding the Accessibility reports for the main functionality as well as the header and footer

**Comment by aprematta** [comment]
[EPA CAMPD Guided Test Cases.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6548731/EPA.CAMPD.Guided.Test.Cases.docx)

**Comment by aprematta** [comment]
Adding guided test cases for the EPA 508 team
