### ISSUE TITLE
EASEY In Monitoring Plans 508 Accessibility Review

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1099]
- [x] Review EASEY IN Monitoring Plans UI and document 508 accessibility compliance findings
- [x] Create 508 test script for EPA

https://easey-dev.app.cloud.gov/monitoring-plans

**Comment by aprematta** [comment]
[EPA Monitoring Plans Guided Test Cases.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6311542/EPA.Monitoring.Plans.Guided.Test.Cases.docx)

**Comment by aprematta** [comment]
Adding test script document for EPA

**Comment by aprematta** [comment]
[EPA Monitoring Plans Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6313656/EPA.Monitoring.Plans.Accessibility.Report.docx)

**Comment by aprematta** [comment]
[EPA Header and Footer Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6313657/EPA.Header.and.Footer.Accessibility.Report.docx)

**Comment by aprematta** [comment]
Adding audit report for the monitoring plans screens as well as the previous report for the header and footer that came from ticket 856
