### ISSUE TITLE
Select Allowance Holdings Data Sub Type

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1101]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to select a data sub type So that I can limit the data in my query

## Acceptance Criteria
When the filter criteria page is displayed
Then the user has the option to select a data sub type
And the options are :

Given a user has selected allowance holdings sub type
When the user applies the selection
Then the filter criteria is displayed: 

Given a user has selected allowance holdings sub type
When filter criteria is selected
Then the filter criteria window(fly out) is displayed

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
No longer needed
