### ISSUE TITLE
AH: Filter Custom Data Download By Account Type 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1104]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to enter filter criteria for account type so that my dataset includes data for my account type(s)

## Acceptance Criteria
Given that a user has selected a data type and sub type
When the filter criteria page is displayed
Then user has the option to select account type 

Given that a user has selected account type 
When the functionality is displayed
Then the user has the option to select from Facility, Unit, General, Reserve, Surrender, All
And can select one or multiple account types 

Given that a user has applied filter criteria for account type 
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria for account type 
When any account type criteria is cleared
Then the system clears the criteria from the filter

## Context

**Functionality** 
Account Type
check box multi select component 
default blank
Values: Facility, Unit, General, Reserve, Surrender, All
Optional
Multi select
Account type will be listed account type (account code) format

**Filter Tags**
Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter code in tag
Tag will remain fixed width, if parameters text exceeds fixed width, then full name is displayed in hover text/Tool tip
If more than 1, show number of parameters
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group
Tags will have a hover functionality to display the list of selections
Tool tip will show the account type code 

## Testing

Functional Testing 
Test Case: [TC246](https://cvpcorp.testquality.com/project/11428/plan/21361/test/295277)
Tester: @JanellC 

508 Testing 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- refactored ProgramRenderer and UnitCheckboxRenderer to one component: CheckboxRenderer
- updated store:
  - added accountType to initialState
  - added actionsTypes UPDATE_ACCOUNT_TYPE_SELECTION and LOAD_ACCOUNT_TYPES_SUCCESS
  - updated actions/reducers
- added AccountType
  - updated FilterCriteriaPanel as needed
- added getAccountTypes  to filterApi 
- unit tests

**Comment by JanellC** [comment]
TC246 passed @tlageman-epa . Ticket is ready for 508 testing. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b9259119-deaa-4810-82c6-f70e83469ed4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/067ea6c5-f87c-459b-9980-51ec03593bf9)
