### ISSUE TITLE
AH: Filter Custom Data Download By Account (Account Name/ Account Number) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1105]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to enter filter criteria for account so that my dataset includes data for my desired account(s)

## Acceptance Criteria
Given that a user has selected a data type and sub type
When the filter criteria page is displayed
Then user has the option to select account 

Given that a user has selected account 
When the functionality is displayed
Then the results populate in a list 
And are displayed in the Account Name (Account Number) format

Given that a user has selected account
When the functionality is displayed
Then the user can select one or multiple accounts 

Given that a user has selected account 
When the search is executed 
Then the system conducts a contains search on  on all allowance account names

Given that a user has selected account  
When the search is executed and no results are found 
Then the system notifies the user that “No accounts match your search.”

Given that a user has applied filter criteria for account 
When the criteria is applied 
Then the system displays a filter tag 

Given that a user has applied filter criteria for account 
When any account criteria is cleared
Then the system clears the criteria from the filter 

## Context

**Filter Tags**
Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter in tag
Tag will remain fixed width, if parameters text exceeds fixed width, then full name is displayed in hover text/Tool tip
If more than 1, show number of parameters
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group
Tags will have a hover functionality to display the list of selections

**Functionality** 
Account

Account Name
Dynamic search/combo box
Search is a contains search on all allowance account names
Results are displayed in Account Name (Account Number) format
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
Out of scope: If state is already selected, then search is limited to accounts in the selected state
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

Account Number
Dynamic search/combo box
Search is a contains search on all allowance account numbers
Results are displayed in Account Name (Account Number) format
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
Out of scope: If state is already selected, then search is limited to accounts in the selected state
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

## Testing
Functional Testing 
Test Case: [TC248](https://cvpcorp.testquality.com/project/11428/plan/21361/test/295279))
Tester: @JanellC 

508 Testing 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- updated env variable from  REACT_APP_EASEY_ALLOWANCE_API to REACT_APP_EASEY_ACCOUNT_API
- fixed label for FilterTags
- added AccountNameNumber filter component
- updated FilterPanel to include AccountNameNumber
- added actions/reducers as needed
- unit tests

**Comment by JanellC** [comment]
TC248 passed @tlageman-epa . This ticket is ready for 508 testing.
