### ISSUE TITLE
Monthly Time Period Filter

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1114]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I am required to enter filter criteria for time period so that my query is concise

## Acceptance Criteria
Given that a user has selected monthly emissions
When the filter criteria page is displayed
Then the user must select time period (not null)

Given a user has not entered a value for month and year 
When the filter is displayed
Then the ability to apply the filter is disabled

Given a user has entered a time period (not null)
When the user applies the filter
Then the system will ensure that the data is valid

Given a validation has failed
When the error message is displayed
Then the error message is displayed in accordance with the [USWDS validation component
](https://designsystem.digital.gov/components/validation/)

Given that a user has selected time period
When the criteria is entered
Then the system ensures the years are in the YYYY format
And displays error message:  FV-102: Enter year(s) using a comma separated format (ex. 1995, 2000, 2001-2005)

Given that a user has selected time period
When the criteria is entered
Then the system ensures the years are a valid range 
And displays error message:  FV-105: Enter year(s) between 1995 and this year 

Given that a user has selected time period
When the the criteria is entered 
Then the system ensures that multiple years are in a comma delimited list 
And the system displays error message: FV-102: Enter year(s) using a comma separated format (ex. 1995, 2000, 2001-2005)

Given that a user has entered filter criteria for time period
When the criteria is applied 
Then the system displays a filter tag 

Given that a user has applied criteria for time period
When the functionality is displayed
Then the preview data functionality is enabled

## Context

**Error Messages** 

[Error Message Repo ](https://teams.microsoft.com/_#/files/General?threadId=19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype&ctx=channel&context=Coding%2520%2526%2520Error%2520Standards&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FGeneral%252FCoding%2520%2526%2520Error%2520Standards)

**Error Messages:** 

[USWDS validation component ](https://designsystem.digital.gov/components/validation/)

**Month Component** - Month will have a select all option in the header 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8bc88ee7-0a09-48bd-9f47-36be98a2e57d)

**Validation** 

Format: MM/YYYY 
Required
Valid date range: 01/1995 to latest reporting quarter
Multi Select 

Year:
Validate that at least one, value exists for the parameter
Validate that the date is in the format YYYY
Validate that the year is greater than or equal to 1995

Month:
Validate that at least one, value exists for the parameter
Validate that the date is in the format MM (1or 2 digit month code)
Validate that the month is between 1 and 12, error message TBD

**Filter Tags** 

Populates filter tag on Apply Filter
If more than 1, show number of parameters
Tags will have a hover functionality to display the time period selection
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group

Time period tag will display "time period"
Tool tips will display selections 

Filter Tags do not display until a user applies the selection

## Testing
Test Case: [TC207](https://cvpcorp.testquality.com/project/11428/plan/20143/test/291757)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

**WIP: pushing functionality so it does not block other tickets**

- adjusted initial state for timePeriod to include year, month, and quarter
- refactored TimePeriodRender
  - TimePeriodFullDates component
  - TimePeriodYears component
- adjuested TimePeriod to account for year logic
  - (and month/quarterly setup)
  -  added Year format validation

**Comment by junie-stigdon** [comment]
## Pull Request

- added month selection to render
- added quarter selection to render
- made styling tweaks to checkbox labels in CheckBoxGroup
- updated FilterTags to make the appropriate filter for year/month/quarter
- displays the Time Period filter Monthly, Quarterly, Annual, and Ozone subtypes
- added handlers for month and quarter in TimePeriod
- updated validation error messages
- added various helper functions for formating

**Comment by JanellC** [comment]
TC207 failed @tlageman-epa. I logged Bug: Monthly Time Period Filter #1587 to track the changes
