### ISSUE TITLE
Identify resources for Emissions Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#112]
- [ ] Identify resources for emissions data. (Sejal). Will need database access to complete this task. Mo has requested access, request is pending. 2 points

**Comment by sdhawan16** [comment]
Identified Emissions tables: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Tables%20for%20Emissions-EPA%20CAMD_v1.1.pdf

Documentation on tables from the Emissions Reporting Instructions (XML Schema elements mapped to tables): https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Reporting%20Emissions%20Tables-EPA%20CAMD-v1.1.pdf

**Comment by sdhawan16** [comment]
Updated Emissions tables: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Tables%20for%20Emissions-EPA%20CAMD-v1.2.pdf

Updated documentation on tables from Emissions Reporting Instructions (XML Schema elements mapped to tables):
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Reporting%20Instructions%20Emissions%20Tables-EPA%20CAMD-v1.1.pdf

**Comment by sdhawan16** [comment]
Updated link for identified FACT-API Emissions tables: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Tables%20for%20FACT-API%20-%20Emissions%20-%20EPA%20CAMD%20-%20v1.3.pdf
