### ISSUE TITLE
Emissions Data Relationships 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#113]
- [ ]  Identify emissions data relationships in order to build emissions data service

**Comment by sdhawan16** [comment]
Diagram of tables that were mapped out to Emissions XML elements. Parent/child relationships, unique keys, and foreign keys are shown: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Emissions%20XML%20Schema%20Diagram-EPA%20CAMD-v1.0.pdf

**Comment by sdhawan16** [comment]
ERD: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/Emissions%20High%20Level%20Relational%20Diagram-EPA%20CAMD-v1.2.pdf

**Comment by sdhawan16** [comment]
Updated link for FACT-API ERD: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions/ERD%20for%20FACT-API%20-%20Emissions%20-%20EPA%20CAMD%20-%20v1.2.pdf
