### ISSUE TITLE
Monitoring Plan Data Relationships 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#115]
- [x] Identify emissions data relationships in order to build MP data service 
- [x] Review with team

**Comment by SimeraHailu** [comment]
https://teams.microsoft.com/_#/files/Datateers?threadId=19%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype&ctx=channel&context=CAMDBPS-Schema-Data%2520Dictonary&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FDatateers%252FEASEY-OUT%252FCAMDBPS-Schema-Data%2520Dictonary
