### ISSUE TITLE
Identify resources for Facility data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#116]
Identify resources for facility data. Will need database access to complete this task. Mo has requested access, request is pending.

**Comment by junie-stigdon** [comment]
Identified tables:
https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Facilities?csf=1&web=1&e=XasHvJ

**Comment by junie-stigdon** [comment]
Database access was not needed to complete this task. Instead the FACT API PL/SQL procedure files were used to identify resources
