### ISSUE TITLE
Build Custom Component for program and unit characteristics filters (incl. Program filter)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1227]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to enter filter criteria for program so that my customized dataset contains my desired program(s)

## Acceptance Criteria
Given that a user has selected a data type and sub type
When the filter criteria page is displayed
Then user has the option to select program

Given that a user has selected program
When the functionality is displayed
Then the user has the option to select from active and inactive programs (MATS is excluded)
And can select one or multiple programs

Given that a user has applied filter criteria for program
When any program criteria is cleared
Then the system clears the criteria from the filter

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Drop down, default blank
Values: All active and inactive programs (MATS is excluded)
Optional
Multi select
program should be displayed in the program (program code) format 

Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter in tag
Tag will remain fixed width, if parameters text exceeds fixed width, then program code  is displayed in hover text/Tool tip
If more than 1, show number of parameters
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group
Tool tip will display program code 

API Update #1002

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC161 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/279638)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@addisgmichael Thanks for putting this together. I was taking a look at it and noticed a few styling things that I'd like to make sure are aligned with the wireframes designs before this is closed. Please see them [here](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/5b729f78-815a-473e-91b9-23380c7cc728?fullscreen&hints=off)

1. The font is not matching - appears times new roman, not whatever is in the wireframe/matching the filter box labels. Time period, for example, has the appropriate font and is much cleaner. These should be consistent across filters.
2. The size seems rather large, but maybe that is just the font type
3. I know this is meant to be a reusable component that will be used in the Unit Type, fuel, control tech filters as well, but as seen in the wireframe, there is no need to "select all" for each Program grouping (Annual/Ozone, Active/Retired). These should be removed. We will need those for the unit type, fuel, control techs as we discussed together when those filters are addressed. We can discuss that further and have @cvp-alexrobinson provide mockups of that when needed.

Thanks and please let me know asap if you have any questions.

@JanellC @JorjaComer

**Comment by JanellC** [comment]
Hi @tlageman-epa thanks for your message. We are currently working on this.

**Comment by tlageman-epa** [comment]
@addisgmichael @JanellC Just checking on this since addis said he was pushing changes in after DSU. Thanks for removing the select all and changing some of the font but all of the programs in the filter panel appear to be in times new roman still, not matching the appropriate font. Please make sure this addressed. Thanks!

**Comment by addisgmichael** [comment]
> @addisgmichael @JanellC Just checking on this since addis said he was pushing changes in after DSU. Thanks for removing the select all and changing some of the font but all of the programs in the filter panel appear to be in times new roman still, not matching the appropriate font. Please make sure this addressed. Thanks!

@tlageman-epa it looks like the font used for the list of programs in the filter panel is actually "Merriweather" (please see the snippet below). Note that the font specification and all styling updates are taken from the may demo wireframe. Please don't hesitate to let us know of any other concerns you have. Thanks

![image](https://user-images.githubusercontent.com/68253641/117697336-5ab2b400-b190-11eb-8cc6-94b993851d10.png)

**Comment by tlageman-epa** [comment]
Hey @addisgmichael are you saying that the font in the may demo designs filter panels is merriweather? It looks different to me, especially when comparing against the font in the time period filter "Start Date" for example. These fonts should be consistent. Please let me know if I am not being clear, we can hop on a call quick. Thx!

**Comment by addisgmichael** [comment]
@tlageman-epa i see what you mean Travis. Alex was also able to give me more clarity. The font used in time period form labels is sans serif font (Source Sans) while for Program it's serif font (Merriweather). I'll go ahead and update Program to use Source Sans instead.

**Comment by JanellC** [comment]
TC161 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/10c14154-f14b-45e8-938b-64cd005aef53)
