### ISSUE TITLE
Research Spike for Updating MP Sections

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1228]
Expected output: list of tables required to update the following sections, as verified by EPA.
As reference, can look at existing FACT and ECMPS stored procedures.

## Sections
- Methods
  - Method
  - Supplemental Methods
- Systems and Components
  - System Component
    - Analyzer Range
  - System Fuel Flow
- Formulas
- Spans
- Loads
- Defaults
- Qualifications
- Unit Characteristics _(will display if viewing a unit location)_
  - Unit Programs
  - Unit Capacity
  - Unit Control
  - Unit Fuels
- Stack/Pipe Attributes and Relationships _(will display if viewing a stack/pipe location)_
- Rectangular Duct WAFs

**Comment by JorjaComer** [comment]
OBE
