### ISSUE TITLE
Debrief of Research Findings 

### ISSUE THREAD

**Issue by nsameerun** [US-EPA-CAMD/PI-1#1233]

**Comment by david-cvp** [comment]
https://teams.microsoft.com/l/file/15E7322F-0E8C-4E8F-90D2-88137D08DB5C?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FUser%20Research%2FUser%20Research%2FEASEY-In%20User%20Research%20Reports%2FMonitoring%20Plan%20Systems%20UXR%205-3.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:2fb3e3c4e2b84887b99e84c907bf4ff4@thread.skype&messageId=1620075133737&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23
