### ISSUE TITLE
Refactor EASEY-In w/ React USWDS components

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1243]
- USWDS updates for EASEY In 
- Restructure code base and clean up 

Tester:
@mosesdeeCVP

**Comment by david-cvp** [comment]
@tdavydets to add estimate once he dives into the work

**Comment by mosesdeeCVP** [comment]
Test cases run and Passed:

Automated: 
UI_TC117_628_View_System_Details_Components_Modal
UI_TC95_813_Footer_Menu
UI_TC81_541_Implement_active_inactive_filter_logic_for_configurations_locations_and_methods

Manual:
[TC91](https://epacamd.testquality.com/project/11428/plan/19813/run/147162/result/2373264)
[TC92](https://epacamd.testquality.com/project/11428/plan/19813/run/147162/result/2373265)

Ad hoc Testing - Passed

Ticket Closed

**Comment by mosesdeeCVP** [comment]
![1243 Refactor EASEY-In w React USWDS components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/12ee4e66-7dd7-4a83-b238-2dcdab7f4989)
