### ISSUE TITLE
SPIKE: Research adding filter logic to CAMPD custom data download 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1247]
Dependency: Need access to the data base in order to be able to conduct this research. 

Goal: understand LOE to implement logic between all filter criteria for emissions, allowance, and compliance data (e.g. state limits facility) 

Deliverable: A layout of all the options to implement the filter logic and the implications of each option 

Research the ability for the filters to be controlled by time period 

**From Travis - To reiterate, all filters within each data type, subtype must be related. Therefore, for hourly emissions all filters (incl. time period) must relate. For allowance Holdings, all filters must relate, and so on for each data type, subtype.**

**Initial Questions Answered by Datateers PO:** 

1. Do you want the non-available items to show in the dropdown disabled (greyed out and not selectable) or not even be in the list? 

Will discuss internally further and get back to you since you said it is not urgent.

2. Do you want the non-available items to show in the checkbox groups disabled (greyed out and not selectable) or not even be shown? I have seen wireframes where selections are there but greyed out.

Will discuss internally further and get back to you since you said it is not urgent.

3. Is this just for Program, State, Facility, Unit Type, Fuel Type, & Control Tech? I have not looked at any other filter relationships so those would be out of scope at this point. 

We need all filters to be related for each data type/subtype. For example, the filters under the data subtype Account Info, should all be related to each other while the filters under Allowance Holdings should all be related to each other and so on for the remaining data subtypes in Emissions, Allowances and Compliance. What you’ve listed here is only for emissions and excludes Time Period, which should be included.

Request:

Make the filter criteria aware of the data entered into other filter criteria. For example, if program is selected, then facilities a should be limited to facilities that participate in the selected program. If a state is selected, then facilities should be limited to facilities in the selected states. If a facility is selected, then the state should automatically populate to the states associated to the selected facilities. Fuel type, control tech, and unit should be limited based on facility, and vis versa ( limit facility if unit, fuel type, control tech is selected first). This is not a complete list of all the ways that filter criteria should be referential, but can be used as examples for the research. Ideally, filters should update in real time based on current selections , and provide feedback to the user if an invalid selection is made (e.g. selected facility and state combo is not valid). 

### Background: 

From:	Lageman, Travis <Lageman.Travis@epa.gov> on behalf of Lageman, Travis
Sent:	Thursday, April 15, 2021 4:28 PM
To:	janell coleman; Jorja Comer
Cc:	Desantis, Laurel; Ibarra, Michelle; Mo Adeyoju; Stetsyuk, Karina; Gill, Sandeep; Chang, Ming; 
Kuhns, Jason; Heese, Michael
Subject:	Add Filter Logic for CAMPD to Backlog

Hi Jorja & Janell,

We’ve been discussing this peripherally over the last month or so, but we’d like to officially get the filter 
logic requirement in the backlog for CAMPD. This requires the Custom Data Download tool to have logic 
to update the filter criteria dynamically based on the order of filter criteria selected by the user. For 
example, in an hourly emissions query, if a user first selects the ARP program, all other filters adjust and 
only allow options matching the ARP filter. So if a user wanted to subsequently filter on state, the user 
could only choose states belonging to ARP. After this second filter is selected, all the other remaining 
filter criteria would update accordingly. This would happen continuously as additional filters are picked 
in order to ensure users do not build a query that returns no data. 

We’d like to create a ticket in the backlog for the developers to look into this in PI 4 (dev spike if 
necessary) so EPA can understand our options and LOE for this before we implement a solution. This 
does not change our current priority to meet our May demos. Additionally, per the developers earlier 
suggestion, we will continue to develop the hourly emissions filters in the custom data download UI 
without any relationships first to “get them out there”. However, one question we expect to be 
answered after the developers look into this is when should we implement this logic? Does it make 
more sense to implement after we complete the hourly emissions filters before we add in the other data 
types and associated filters (e.g., allowance, compliance data) or just get all the other data types and 
filters out there first and implement logic last? We want to plan ahead and be efficient with our 
approach.

To summarize:

Let’s add a ticket into the backlog for the filter logic requirement and possible options described above 
to visit during PI 4 planning. After the developers are able to look into this and provide options, EPA also 
wants to know when it is most efficient to implement the proposed options in relationship to ongoing 
development. For this reason, we are hoping to get this research done earlier in PI 4 but we can discuss 
further during PI 4 planning due to the prioritization of May demo work.

Thanks and happy to answer any follow up questions.

Best,

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

## Context 

From:	Lageman, Travis <Lageman.Travis@epa.gov> on behalf of Lageman, Travis
Sent:	Wednesday, May 19, 2021 3:58 PM
To:	jasonwhitehead@cvpcorp.com; sejaldhawan@cvpcorp.com; juniesenthilkumar@cvpcorp.com; 
addisgebremichael@cvpcorp.com
Cc:	janell coleman; Jorja Comer; Mo Adeyoju; Ibarra, Michelle; Desantis, Laurel
Subject:	RE: Filter Logic Spike # 1247

Hi Jason & team,

Thanks for the questions. I’ve answered them below in Bold even though we discussed this in 
Refinement. Also, I copied the information from ERG even though you said you had seen it already. Let 
me know if you have any further questions.

Thanks,
Travis

__________________________________

Below is the list of FACT and DIM tables on CAMDPUB that contain the data that are used by the filters 
in the current AMPD application.

ANNUAL_UNIT_DATA and ANNUAL_MONITOR_DATA are also used in conjunction with the FACT and 
DIM tables for emissions query filters.

As an example as to how AMPD combines this data:

There is a materialized view on CAMDDMP (CAMDDM.PROGRAM_YEAR_VW) that is used by the AMPD 
query wizard to determine which years to show for which programs.  

This materialized view combines data from PROGRAM_YEAR_DIM, ANNUAL_UNIT_DATA, 
ANNUAL_MONITOR_DATA, FACILITY_DIM (a CAMDDM table populated as part of the nightly refresh 
that summarizes facility/program/year combinations from UNIT_FACT and PROGRAM_YEAR_DIM), 
ACCOUNT_COMPLIANCE_DIM, and UNIT_COMPLIANCE_DIM.

The results of querying this materialized view includes one row for each OP_YEAR/PRG_CD combination 
for each type of query that the user might be performing (unit emissions, monitor location emissions, 
facility attributes, allowance compliance, ARP NOx compliance).

Mark

UNIT_FACT
OWNER_DISPLAY_FACT
REP_DISPLAY_FACT
PROGRAM_YEAR_DIM
UNIT_PHASE_YEAR_DIM
UNIT_TYPE_YEAR_DIM
CONTROL_YEAR_DIM
FUEL_YEAR_DIM
OP_STATUS_YEAR_DIM
OWNER_YEAR_DIM
REP_YEAR_DIM

ACCOUNT_FACT
ACCOUNT_OWNER_DIM
ACCOUNT_REP_DIM

TRANSACTION_FACT
TRANSACTION_BLOCK_DIM
TRANSACTION_OWNER_DIM

ALLOWANCE_HOLDING_DIM

ACCOUNT_COMPLIANCE_DIM
UNIT_COMPLIANCE_DIM

STATE_ALLOCATION_FACT
BANK_DIM

MONITOR_FACT

CONTACT_FACT

From: jasonwhitehead@cvpcorp.com <jasonwhitehead@cvpcorp.com>  
Sent: Tuesday, May 18, 2021 11:54 AM 
To: Lageman, Travis <Lageman.Travis@epa.gov>; Jorja Comer <jorjacomer@cvpcorp.com>; Heese, 
Michael <Heese.Michael@epa.gov> 
Cc: Stetsyuk, Karina <Stetsyuk.Karina@epa.gov>; Desantis, Laurel <Desantis.Laurel@epa.gov>; Gill, 
Sandeep <Gill.Sandeep@epa.gov>; Mo Adeyoju <moadeyoju@cvpcorp.com>; Ibarra, Michelle 
<Ibarra.Michelle@epa.gov> 
Subject: RE: Filter Logic Spike # 1247

**Comment by jwhitehead77** [comment]
I think we can handle this by modifying the GetFacilities api endpoint to include the Programs, Unit Types, Fuel Types, & Control Tech that are applicable for each facility. The front end UI application can then uses this data to filter the available selections for all filters each time the Apply Filter button is clicked based on the current selections of all filters.
 
**Clarifications:**
1.	Do the non-available items show in the dropdown disabled (greyed out and not selectable) or not even be in the list?
2.	Do the non-available items show in the checkbox groups disabled (greyed out and not selectable) or not shown at all? I have seen wireframes where selections are there but greyed out.
3.	Is this just for Program, State, Facility, Unit Type, Fuel Type, & Control Tech? I have not looked at any other filter relationships so those would be out of scope at this point.

**Tasks Needed**
Need a task to modify the Facilities api to include the Programs, Unit Types, Fuel Types, & Control Tech that are applicable for each facility.
Need a task to add logic to all filters which will filter the available selections based on current selections of all filters when the Apply Filter button is clicked.

**Comment by JanellC** [comment]
@tlageman-epa Research completed. Output can be found on MS teams [here ](https://teams.microsoft.com/l/file/A1E37E8D-432B-4735-AA4C-0961A024CE5D?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pptx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F4-Development%2FFilter%20Criteria%20Research%20Spike.pptx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)
