### ISSUE TITLE
Send multiple quarterly emissions parameters and return data

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1252]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to send filter criteria to the  quarterly emissions API endpoint so that I can see results

## Acceptance Criteria
Given that a user has entered one or more valid values for all the parameters (see parameters below)
When API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more valid values for all the parameters in an upper case or lower case format
When API endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered one or more valid values for all the parameters without white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered one or more valid values for all the parameters with white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria

## Context
Results:
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year > Quarter
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
YEAR
QUARTER
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

# Parameters 
Years: Required, multiple values allowed, 1995-current, Format: YYYY. Allow indiv. Years, ranges, and comma sep. list

Quarters: Required, multiple values allowed, Format: 1,2,3,4,  equal to or less than the last reporting quarter

Facility ID (Oris Code): Optional, multiple values allowed

State: Optional, multiple values allowed, 2 letter postal abbreviation for the 50 states plus Puerto Rico.

Unit Type: Optional, multiple values allowed

Unit Fuel Type: Optional, multiple values allowed, query will filter on both primary and secondary fuel type

Control Technologies: Optional, multiple values allowed

Program: Optional, multiple values allowed, excludes MATS

## Testing
Test Case: [TC183 ](https://cvpcorp.testquality.com/project/11428/plan/20785/test/283782)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by sdhawan16** [comment]
Created PR

Added quarterly emissions endpoint:

- Updated apportioned emissions controller, service and module
- Added quarter unit data repository
- Updated emissions fields and field mappings
- Added quarterly apportioned emissions DTO and paramsDTO
- Added quarter unit data entity and updated unit fact entity with relation
- Added quarterly apportioned emissions map
- Updated query builder
- Added unit tests

**Comment by JanellC** [comment]
TC183 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/quarterly?opYear=2015|2019&opQuarter=1|4


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4cba7265-e8ec-4dcd-b46b-04ad88af6ddb)
