### ISSUE TITLE
Implement filter by keyword to work with Enter key

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1266]
## User Story
As a user, I want to see filter results when executing search with the Enter key.

## Acceptance Criteria
Given a user has entered keyword criteria
When the user selects the keyboard Enter key
Then the system returns filter results.

**Comment by mosesdeeCVP** [comment]
Test Case: [TC259](https://epacamd.testquality.com/project/11428/plan/19352/test/295978)

**Comment by mosesdeeCVP** [comment]
Test Passed
