### ISSUE TITLE
CAMPD Web Page Areas UI Design 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1268]
## Feature Benefit
Begin design/whiteboarding for the other web areas of CAMPD (static datasets page, help, resources, etc.)

## Context
Morning Alex & co,

As I asked in Monday’s PBR meeting, I’d like for us to start using UX/UI weeklys to begin design/whiteboarding with you for the other web areas of CAMPD (static datasets page, help, resources, etc.). Therefore, I’d like for us to put a ticket in to track this. I don’t expect us to actually start this until PI 4 after the Design Library stuff has been squared away since that is the current priority. Plus, we are still trying to organize our initial thoughts on how some of these other areas might exist. Anyways, let’s get that in to the backlog and if there is anything in particular that we should be prepped to answer for you to help in these discussions, please let us know.

Thanks!

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

**Comment by JorjaComer** [comment]
Design will be handled in other epics
