### ISSUE TITLE
Configuration Management 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1269]
## Feature Benefit
Provide the ability to configure/associate units to stacks so that a user can edit/update stacks in a monitoring plan 

Splitting single unit/multiple stack and single unit/multiple pipes

Needs UI design, what roles are able to access this functionality

## Context
[Refer to 5/24 section for config management reqs](https://projects.invisionapp.com/freehand/document/TdahPfbEb)

**Comment by annalbrecht** [comment]
Probably the same as #5995

**Comment by alangmaid** [comment]
Closed because it's a duplicate
