### ISSUE TITLE
Implementation of pagination and filter number of records 

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#127]
## Development Tasks
- [ ] Develop pagination component 

## Acceptance Criteria
Given the user has chosen to view Facilities data
When the page is displayed
Then by default all results are returned

Given the user has chosen to view Facilities data
When the page is displayed
Then the user has the option to limit results displayed on a page at a time to 100, 250, 500, or All
And the default pagination is 100 

Given a user has chosen to limit results displayed on a page 
When the user chooses a limit value
Then the system will limit results displayed on the page based on option selected 

Given table rows exceed the page limit value selected 
When the results are displayed
Then the user will have the option to select additional pages

**Comment by JorjaComer** [comment]
@JorjaComer  will work with BA team to determine how to document this functionality as the requirements for table pagination
