### ISSUE TITLE
Change Allowance API to Account API 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1271]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want the allowance API endpoint to be named Account so that the API has a name that is reflective of the data 

## Acceptance Criteria
Given that a user has navigated to the account API swagger UI page 
When the page is displayed 
Then the page is named "Account Management OpenAPI specification"

Given that a user has made a GET request to the /api/account-mgmt/allowances/holdings endpoint
When the GET request is executed 
Then the system displays the appropriate records 

Given that a user has made a GET request to /api/account-mgmt/allowances/transactions endpoint
When the GET request is executed 
Then the system displays "Hello allowanceTransactions"

## Context
Make API based on account data rather than data type. Re use for other allowance and compliance data types. 

## Testing
Test Case: [TC156](https://cvpcorp.testquality.com/project/11428/plan/20060/test/279361)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC156 passed @tlageman-epa @kstetsyuk 

https://easey-dev.app.cloud.gov/api/account-mgmt/allowances/transactions
https://easey-dev.app.cloud.gov/api/account-mgmt/allowances/holdings?page=1&perPage=10

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/04813965-1508-44fa-95b7-68716d396bb9)
