### ISSUE TITLE
Add CASPAR Ozone Group 3 Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1273]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want  CASPAR G3 program to be available on CAMPD So that I can analyze the data 

## Acceptance Criteria
Given that a user has accessed the custom data download 
When the program filter panel is displayed 
Then the list of programs includes CASPAR G3  (not applicable to annual emissions and compliance (emission based) data ) 

Given that a user has made a GET request to an emissions endpoint with filter criteria for CASPAR G3 (excludes annual emissions) 
When the request is executed 
Then the system returns data 

Given that a user has made a GET request to the facility/ unit attributes endpoint with filter criteria for CASPAR G3 (excludes annual emissions) 
When the request is executed 
Then the system returns data 

Given that a user has made a GET request to the allowance holdings, allowance transactions, and account info endpoint with filter criteria for CASPAR G3
When the request is executed 
Then the system returns data 

Given that a user has made a GET request to the compliance (allowance based) endpoint with filter criteria for CASPAR G3
When the request is executed 
Then the system returns data 

### Development Notes
- update the program MDM so that CASPAR G3 is apart of the excludes parameter
-  CASPAR G3 should display on the custom data download for all sub types except annual emissions and compliance (emission based)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Will need to make updates to account for CASPAR program (new Program ETA 6/29/2021)

applicable to all data sub types except for annual emissions and compliance (emission based)

work includes updating the api and the database

## Testing
Test Case: [TC433](https://epacamd.testquality.com/project/11428/plan/22473/test/309145)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
Putting this here for tracking: It appears CSOSG3 is already included in the Program MDM endpoint.

- However, its complianceUIFilter is returning as FALSE as opposed to TRUE (even though there won't be compliance data until next summer 2022). This is preventing it from showing up in the Allowance Based Compliance Program Filter UI.

- Additionally, the exclude parameter does not have CSOSG3 as an option.

**Comment by JanellC** [comment]
TC433 passed @tlageman-epa
