### ISSUE TITLE
Standalone Log In UI for EASEY In

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1277]
## User Story
As a user, I want to log in to EASEY IN, so that I can access my workspace and edit my facility's data

## Acceptance Criteria
Given the user enters an existing CDX username and password (from #1278)
When the user clicks "log in"
Then the system displays the Monitoring Plans - Facilities page including registered user account information such as first name, last name, and email address

Given the user enters an invalid username or password
When the user clicks "log in"
Then the system displays an error message from the CDX service (such as: unknown user, invalid credential, access denied)

## Context
@AllisonFrancis or @cvp-alexrobinson will need UI design for stand-alone log in page 
Log in page will be a custom look and feel, stand-alone log-in page (not using the CDX log-in). 

For this story, we will proceed without wireframes for a prototype login page

## Testing
Tester: @davidkwartler 
Test Case: [TC160](https://epacamd.testquality.com/project/11428/plan/20465/test/279600)

**Comment by david-cvp** [comment]
TC160 passed @maheese 

https://easey-dev.app.cloud.gov/login

Login page:
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/6dbc2fb7-e12b-4b24-8d46-4bb5d05abd9e)

Validation:
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/1409f9a7-7e44-4e56-a864-f484d5c646c4)

Successful login status:
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/84389b7f-a43a-42d4-bd84-188ef2d1f30a)
