### ISSUE TITLE
Search for Facilities 

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#128]
## Development Tasks
- [ ] Leverage React Table library
- [ ] Develop reusable search component for a data table
- [ ] Modify facilities table component for select ability 

## Acceptance Criteria
Given a user has accessed the facility data
When the data is displayed
Then the user has the ability to search

Given a user chooses to search
When the search criteria is displayed
Then the user may search the facility data by ORIS Code, Facility Name, or State

Given the user has entered search criteria
When the search is performed 
The search matches results based on the most relevant match to the characters entered 

Given at least one result is returned
When the results are displayed
Then the system will provide a way to navigate through results (e.g. scrolling) 

*****NEW AC******

Given no results are returned
When the user views the page 
Then the system will display a message "No results match that search criteria. Please change the criteria and try again."

**Comment by JorjaComer** [comment]
@JorjaComer add as component requirement for searching in a table and no results message
