### ISSUE TITLE
Priority #4 - Implement CDC for all tables in CAMPD Release #1 (Need by Aug EOM)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1281]
All tables listed on the CAMPD Release #1 tab will require change data capture to be implemented to sync data changes between the NCC and cloud.gov on a nightly basis. This will need to be ran after all the nightly jobs that mvoe 7 aggregate data from camdbsp up to camdpub.

Refer to the CAMPD Release #1 tab in the following document...
https://teams.microsoft.com/l/file/7596D4EC-D3C5-4E93-840E-D066AB92736E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTech%2FData%20Migration%2FSchema%20%26%20Tables%20for%20Informatica.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:e3d4667412cc496f87be989d2f8ede67@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23

**Comment by vkdontula** [comment]
CDC ETL jobs are ready and unit tested, I have been running the jobs to ETL data from LOG tables into Staging Database.
