### ISSUE TITLE
CAM API Dev Portal/Documentation 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1282]
## Feature Benefit
(What is this feature's benefit hypothesis? Proposed measurable benefit to the end-user or business)

## Context
Request API key: Button always available in menu. Button will open modal. See Request a Key section of wireframes for modal info. Submit request sends request to Data.gov and displays the results in the modal. Assumption: approval of keys is handled by Data.gov, and outside of the scope of this system 

PI 4: Start to determine requirements (Mike + Travis)

Preliminary design w/ Alex + Allison

PI 5: finalize UI design and implement 

Priority: 

1. Swagger page for each API up to date and available (Must). Accessible via Drupal page 
2. CAM API Home Page (Could)
3. Indiv. API pages (Could)

**Comment by MaeganWood64** [comment]
Discussed with Mike 8/5 Tech Team Planning, deprioritized

**Comment by MaeganWood64** [comment]
**** Closed on EPA request, EPA will be absorbing this work****

would like touch base on the CAM API work. As Mike shared a few weeks ago, EPA will be absorb this work. The intention here was to free up capacity for other work. This means EPA does not need additional CAM APIs UI designs and EPA does not need to plan for the development of the CAM API within the EASEY Suite. As needed, we can always chat more about this at a Tech Team meeting or in our Check-in later on this week.

 

Let me know if you have any questions.

 

Thank you,

 

Michelle Ibarra
