### ISSUE TITLE
508 System Component Needs Header

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1292]
## Required Fix
- [x] RF-14

## Context
Table Headers Missing TH Tags (RF-14)
The table row or column header cells are coded as ordinary data cells.

Use header from other tables 

See [EPA Monitoring Plans Accessibility Report](https://teams.microsoft.com/l/file/0F8647F3-12B8-45CC-8A48-0BB97D48CB4D?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FDesign%2FAccessibility%20and%20Section%20508%2FEPA%20Monitoring%20Plans%20Accessibility%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) for how to fix and additional details.

**Comment by aprematta** [comment]
Confirmed that the table now has visible header cells and coded as TH.
