### ISSUE TITLE
SPIKE: Design Check In/Out Mont Plan Draft 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1300]
## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
[User Process Flows](https://teams.microsoft.com/l/file/1576AB5D-ED1B-4597-A368-C3228BC09C7A?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2F3-Business%20Analysis%2FUser%20Role%20Flows-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

**Comment by karenhwwoo** [comment]
Closed. Per 5/5 backlog refinement mtg, Jason has determined that technical solution will require creating a new schema, set of working tables for draft copy, and supporting API work.
