### ISSUE TITLE
Bug: Update CAMPD Styling 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1311]
## Test Case
[TC146 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/278040)

### Step 1
| Step | Action | Expected | Status |
|-|-|-|-|
| 1 | Navigate to the custom data download dev link | Then the application is displayed in accordance with updated styling guidance (CAMPD May Demo Designs) - font  - links - colors  - other designs   https://xd.adobe.com/view/3bd31746-18a9-4282-82ec-292ad7708767-6e80/screen/72731463-6137-49dc-bbb2-0a3ce6299e00/?fullscreen  | Fail  |

### Actual Results

**EPA Header and Footer, cont.**
Both backgrounds should be white `#FFF`
Header has a 1px border bottom of #D6D7D9
Footer has a 1px border top of #D6D7D9
Footer menu icon open and close should be EPA blue icons and borders with a white background
Footer menu pop-up should be white background and the text should be EPA blue.
See [One EPA Option 4](https://xd.adobe.com/view/08505c73-3291-4c0a-819f-982951ae417f-5d03/screen/59022411-c9c7-48da-96df-d2aad9396010/specs/) for dev specs

**CAMPD Navigation Bar**
Use the attached as the background image, size as "cover", align top center. background-size: cover; background-position: center top; **(see below)** 
Title font should be Merriweather, normal, 30px
Navigation item fonts should be Source Sans, bold, 16px, uppercase
Navigation item dropdown arrows should be the icon in the May Demo Design specs. It's showing as a solid carrot.
The "In" nav item state bottom border color should be the aqua color, called "Info Base" in the specs
Nav items that are dropped down, the carrot should invert indicating that it's collapse-able.
Only Data, Analysis, and Visualization have dropdowns, not Home.
The title and nav items area should take up the same horizontal space as the USWDS banner. See my[ CodePen f](https://codepen.io/cvp-alexrobinson/pen/eYgKdoM)or USWDS grid classes

**Tool Tips** 
Tool tips do not have a hover functionality 

**Filter Panels:** 
Filter panels are a different shade of blue than the wireframes. 

### User Story
Update CAMPD Styling #1119

### Acceptance Criteria
Given a user has accessed the CAMPD application
When the application displayed
Then it is displayed in accordance with updated styling guidance (CAMPD May Demo Designs)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3f8d8e5b-e581-4800-9143-c6f986368c2f)

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D21](https://epacamd.testquality.com/project/11428/result/2379977/defect/7681). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D22](https://epacamd.testquality.com/project/11428/result/2380152/defect/7682). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D23](https://epacamd.testquality.com/project/11428/result/2380152/defect/7683). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D25](https://epacamd.testquality.com/project/11428/result/2383176/defect/7710). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D26](https://epacamd.testquality.com/project/11428/result/2383187/defect/7711). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D27](https://epacamd.testquality.com/project/11428/result/2383198/defect/7712). Do not remove or edit.

**Comment by JorjaComer** [comment]
Per 4.2 planning will address this bug after alignment to USWDS is complete. Will need to re-assess which items in this bug are resolved and outstanding.

**Comment by JorjaComer** [comment]
Add as checklist to responsiveness tickets

**Comment by JorjaComer** [comment]
Issues will be resolved as part of the work for #1460
