### ISSUE TITLE
EASEY IN authorization and facility association

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1315]
Authorize EASEY IN user with CBS role and facility association

Roles:
Data Submit Agent
Data Prepare Agent
Data Review Agent
Responsible Official

**Need to figure out and work with ERG to determine how CBS will interface with CDX/EASEY In**
**@maheese to set up meeting between CVP/ERG**

**Comment by david-cvp** [comment]
Meeting on 5/18 between ERG/EPA/CVP

**Comment by MaeganWood64** [comment]
Need to Reconfer with CDX/CBS

**Comment by MaeganWood64** [comment]
Duplicate Ticket - No Longer Needed
