### ISSUE TITLE
Decorate DTO properties with descriptions and example data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1339]
Mike can provide spreadsheet for CAMPD hourly emissions DTO property descriptions
May need new descriptions for EASEY IN fields

https://teams.microsoft.com/_#/files/General?threadId=19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype&ctx=channel&context=Coding%2520%2526%2520Error%2520Standards&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FGeneral%252FCoding%2520%2526%2520Error%2520Standards

- [ ] Decorate properties with descriptions and example data using NPM package w/ GitHub Packages

Priority:
- [ ] hourly emissions
- [ ] daily emissions 
- [ ] monthly emissions
- [ ] allowance holdings
- [ ] quarterly emissions

Use easey-constants repo for property metadata

Outcome: Swagger pages will display descriptions for each parameter
Response will include description

**Comment by david-cvp** [comment]
May split this by application, each app needs to be decorated

**Comment by jm9900guy** [comment]
Published easey-constants github package to project so that dto properties could be decorated from a shared remote package.
