### ISSUE TITLE
Edit Monitoring Methods Section (no validation)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1344]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As a user, I want to save edits to a Facility's Monitoring Methods.

Acceptance Criteria:
_Given_ the user has selected Methods in the section field
_When_ the user edits a particular method 
_Then_ the system displays the edit modal
_and_ the user can edit the method data 

Given the user has edited method data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the methods table 

Edit end date
Associate a new method to a configuration (start date, end date)

Note: System can save draft with form validation errors.

[Wireframes ](https://xd.adobe.com/view/eb6c3176-9c62-46e0-af54-8be9a2771b7a-be3f/)

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC205](https://epacamd.testquality.com/project/11428/plan/19352/test/288283)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Linked issue is preventing story from being completed. moving to 4.5 for completion after linked issue is resolved.

**Comment by mosesdeeCVP** [comment]
![1344 Edit Monitoring Methods Section (no validation) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4365a443-dedb-4f8c-bf2b-352494024b5f)

**Comment by mosesdeeCVP** [comment]
![1344 Edit Monitoring Methods Section (no validation) - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bddbf491-909d-4347-babf-910b3bd5028f)

**Comment by mosesdeeCVP** [comment]
![1344 Edit Monitoring Methods Section (no validation) - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f1ecf6aa-36ae-49a3-bbbf-15d0326bd9a9)

**Comment by JorjaComer** [comment]
split auditing info into a separate ticket

**Comment by mosesdeeCVP** [comment]
Test Passed
