### ISSUE TITLE
Update Facilities data tables to align with USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1355]
Update the data table display components to align to the USWDS components. Regression test only, no change in functionality or display.

**Comment by karenhwwoo** [comment]
## Testing
Test Plan Run: [TPR170](https://epacamd.testquality.com/project/11428/run/147885/result/2402881) passed
Tester: Karen Woo

**Comment by karenhwwoo** [comment]
## Testing
Test Plan Run: [TPR170](https://epacamd.testquality.com/project/11428/run/147885/result/2402881) passed
Tester: Karen Woo

**Comment by karenhwwoo** [comment]
## Testing
Test Plan Run: [TPR170](https://epacamd.testquality.com/project/11428/run/147885/result/2402881) passed
Tester: Karen Woo
