### ISSUE TITLE
Update Methods/Supp Methods Data tables to align to USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1356]

**Comment by mosesdeeCVP** [comment]
![1356 Update Methods-Supp Methods Data tables to align to USWDS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4c865f20-b15d-4720-95bb-6c01ecb8d5a4)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC56](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/267705) - Passed
