### ISSUE TITLE
Update Systems Data tables to align to USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1357]

**Comment by mosesdeeCVP** [comment]
Test Case: [TC116](https://epacamd.testquality.com/project/11428/plan/19812/test/fullscreen/276363) - Passed

**Comment by mosesdeeCVP** [comment]
![1357 Update Systems Data tables to align to USWDS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0d703a8e-24af-4564-92f7-a2abb1614adb)
