### ISSUE TITLE
Align Header to USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1359]
Update to align with UWDS components. no change in functionality or display. Regression test only. 

## Testing 

Test Case: [ TC125](https://cvpcorp.testquality.com/project/11428/plan/20058/test/276468)
Testser: @JanellC

**Comment by JanellC** [comment]
Regression testing complete. TC125 passed @tlageman-epa 




![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ec3b88c1-cc1d-4f40-bb87-ae951abd28fe)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/29ed07d5-8072-493c-9088-ff7ca8fada03)
