### ISSUE TITLE
Align Footer to USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1360]
Update to align with UWDS components. no change in functionality or display. Regression test only.

## Testing 

Test Case: [ TC125](https://cvpcorp.testquality.com/project/11428/plan/20058/test/276468)
Testser: @JanellC

**Comment by junie-stigdon** [comment]
## Pull Request

- updated footer menu button to use uswds Button component
- updated footer menu to use uswds Menu component
- replaced all menu links to use uswds Link component
  - added menuTopics file for links
- adjusted Menu.scss as needed

**Comment by JanellC** [comment]
Regression testing complete. TC125 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ea5c5f40-82c6-4c58-bbe8-72034f8cb158)
