### ISSUE TITLE
Align Data Tables to React Component 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1361]
- [ ] Update to align with React components.
- [ ] Update table metadata
- [ ] Make a re-usable component 
- [ ] 

 no change in functionality or display. Regression test and 508 test

## Testing 

Regression Testing 
Test Case: [TC178](https://cvpcorp.testquality.com/project/11428/plan/20058/test/283515)
Tester: @JanellC 

508 Testing 
Tester: @aprematta

**Comment by JanellC** [comment]
Completed regression testing @tlageman-epa . I found some issues with the data table. Logged Bug: Align Data Table to React Component #1814 to track changes

**Comment by JanellC** [comment]
Bug: Align Data Table to React Component #1814 is resolved. This ticket is ready for 508 testing @aprematta
