### ISSUE TITLE
Align Filter Criteria to USWDS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1362]
Update to align with UWDS components. no change in functionality or display. Regression test only.

Scope: All filters 

## Testing 

Test Cases: 

Time Period: [TC140 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277187)
Program: [TC161 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/279638)
Facility:  [TC170](https://cvpcorp.testquality.com/project/11428/plan/20058/test/280982)
State: [TC171 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281022)
Fuel Type: [TC172 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281049)
Control Tech: [ TC174 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281867)
Unit Type: [TC175 ](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281868)

Tester: @JanellC

**Comment by JanellC** [comment]
Regression testing completed @tlageman-epa
