### ISSUE TITLE
Change Background color on filter criteria and Buttons

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1366]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the filter criteria, Change button, and Cancel button to have a white background So that they are easier to see on the grey background 

## Acceptance Criteria
Given a user has selected hourly emissions
When filter criteria, Change button, and Cancel button are displayed 
Then they have a white background 

## Context
![image.png](https://images.zenhubusercontent.com/5f43e81185fd5e29963cd2ef/99b812e9-6e62-4e37-aa9c-d080f1bd03dd)

## Testing
Test Case: [TC173](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281863)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- updated uswds global overrides for button--outline and button--outline:hover
- updated FilterCriteriaRender to not override the bg color

**Comment by JanellC** [comment]
TC173 passed @tlageman-epa 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f43f4110-72b5-47ce-bd4b-05d7f1e86ab4)
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dd89ede1-d791-438d-aeec-0e0696bf6830)
