### ISSUE TITLE
Monitoring Plan- Convert stored procedures, views, and functions

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1391]
Original estimate: 40

The following describe the differences between the ECMPS client DB and host DB tables/columns. This will need to be taken into consideration as we convert views, functions, & procedures to Postgres. Host columns will be used where client columns are different.

### **Format: _client_ column --> _postgres_ column**

**CAMD Schema**
- PLANT
  - FACILITY on client
- UNIT
  - blrseq --> boiler_sequence_number
- UNIT_BOILER_TYPE
  - unit_bt_type on client
  - unit_bt_id --> unit_boiler_type_id
- UNIT_OP_STATUS
  - uos_id --> unit_op_status_id
- UNIT_PROGRAM
  - class --> class_cd
  - non_egu_flg --> non_egu_ind
  - app_status --> app_status_cd

**CAMDMD Schema**
- CLASS_CODE
   - class --> class_cd
- EXEMPTION_TYPE_CODE
  - exempt_type_cd --> exemption_type_cd
  - exempt_type_cd_description --> exemption_type_description
- PROGRAM_CODE
  - prg_name --> prg_description

**CAMDECMPS Schema**
- EMISSION_EVALUATION
   - pending_status_cd --> submission_availability_cd
- USED_IDENTIFIER
  - id_key --> idkey
- UNIT_CONTROL
  - orig_ind --> orig_cd
  - seas_ind --> orig_cd
- UNIT_FUEL
  - fuel_cd --> fuel_type
- USED_IDENTIFIER
  - id_key --> idkey

**CAMDECMPSMD Schema**
- CONTROL_CODE
  - control_cd_description --> control_description
  - ce_param --> control_equip_param_cd
- FUEL_GROUP_CODE
  - fuel_group_cd_description --> fuel_group_description
- FUEL_INDICATOR_CODE
  - indicator_code on client
  - indicator_cd --> fuel_indicator_cd
  - indicator_code_description --> fuel_indicator_description

**CAMDECMPSAUX Schema**
- EM_SUBMISSION_ACCESS
  - submission_availability_cd --> sub_availability_cd
- EM_SUBMISSION_ACCESS
  - submission_availability_cd --> sub_availability_cd

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/00b7e756-1721-4d64-be6a-10d379ef60e0/download](https://app.zenhub.com/files/287570343/00b7e756-1721-4d64-be6a-10d379ef60e0/download)

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/f2b3ab72-2813-4234-8fa8-35ec8610b000/download](https://app.zenhub.com/files/287570343/f2b3ab72-2813-4234-8fa8-35ec8610b000/download)
