### ISSUE TITLE
Identify Features for Wire-frames

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#14]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597336981889) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by david-cvp** [comment]
@JorjaComer @MoAdeyoju should we close this epic as invalid and the two issues underneath it, #246 and #247 ???

**Comment by JorjaComer** [comment]
This work was deprioritized based on feedback from EPA. Wireframe and UI design will be handled via tickets attached to each Uber Epics being worked in future PIs.
