### ISSUE TITLE
React coding standards documentation

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#140]
- [ ] Create coding standards document template for Datateers (#141, #142)
- [ ] Research industry standards for React
- [ ] Document coding standards
- [ ] Document styling standards
- [ ] Document best practices
- [ ] Document naming conventions

A/C: 
Document with set of coding standards for the development team uploaded to EPA Sharepoint

**Comment by Qb10** [comment]
Link to document:
https://docs.google.com/document/d/10MxQqitoTj_qosq3KOChFMs_jJKvmnFZwefaQPsGrVY/edit?usp=sharing

**Comment by Qb10** [comment]
Link to updated document:
https://drive.google.com/file/d/1qVDJuVgIW7afSEPQFH3y3HhP0cCCUeBu/view?usp=sharing
