### ISSUE TITLE
JavaScript coding standards documentation

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#141]
- [x] Reference coding standards document template created by Emissioners (#140)
- [x] Research industry standards for JavaScript
- [x] Document coding standards
- [x] Document styling standards
- [x] Document best practices
- [x] Document naming conventions

A/C: 
Document with set of coding standards for the development team uploaded to EPA Sharepoint

**Comment by sdhawan16** [comment]
Continued with industry standards research. Met with Quang and Junie to go over how we want to set up the coding standards template.

**Comment by sdhawan16** [comment]
Completed draft and received feedback during peer review. Will revise document taking into consideration the feedback I received.

**Comment by sdhawan16** [comment]
Submitted for final review

**Comment by sdhawan16** [comment]
Completed standards document: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/General/Coding%20Standards/JavaScript%20Coding%20Standards%20-%20EPA%20CAMD%20-%20v1.2.pdf
