### ISSUE TITLE
Implement public and logged in user views of opening a Facility

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1411]
### Definition of Ready
- [x] Does this meet the INVEST criteria? (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### User Story

As a user, I want to open a Facility, so that I can view its Monitoring Plan.

Acceptance Criteria:
_Given_ the user is not logged in
_When_ the user would like to open a Facility by clicking "Open"
_Then_ the system displays a view only version of the Facility's Monitoring Plan.  
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb) Scenario 1A of public view of the Facilities page. The only available action is the "Open" button.

_Given_ the user is logged in
_When_ the user would like to open a Facility by clicking "Open"
_Then_ the system displays a view only version of the Facility's Monitoring Plan.  
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb) Scenario 2B of logged in view of the Facilities page. The two available actions are "Open" and "Lock".

**Comment by JorjaComer** [comment]
OBE
