### ISSUE TITLE
Access user's Workspace

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1413]
As a user, I want to access my Workspace.

Acceptance Criteria:
_Given_ the user is not logged in
_Then_ the system displays the Monitoring Plans, QA & Certifications, and Emissions official record section
_and_ a vertical bar indicates which part of the official record section the user is viewing in accordance with [USWDS side navigation](https://designsystem.digital.gov/components/side-navigation/)
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb) Wireframe 1A.

_Given_ the user has logged in
_When_ the system displays the Workspace 
_Then_ the user may enter their Workspace for 
Monitoring Plans, QA & Certifications, or Emissions
_and_ bold text indicates which Workspace section the user enters in accordance with [USWDS side navigation](https://designsystem.digital.gov/components/side-navigation/)
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb) Wireframe 2B.

**Comment by mosesdeeCVP** [comment]
![1413 Access user's Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/31834205-5ee1-4a8b-a0c7-3ef3fd33eed7)

**Comment by mosesdeeCVP** [comment]
![1413 Access user's Workspace - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2ab0630f-7702-4667-b0b0-bf08e32e773d)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC187](https://epacamd.testquality.com/project/11428/plan/20792/test/fullscreen/285217)

**Comment by mosesdeeCVP** [comment]
Both Automated and Manual test cases are passing
