### ISSUE TITLE
Display login as modal and logged in view

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1414]
As a user, I want to confirm that I am logged in.

Acceptance Criteria:
_Given_ the user is in the public view 
_When_ the user clicks the "Log In" button
_Then_ the system displays the login as a modal window
_and_ the system displays, "Welcome, [User's first name]"
_and_ the system displays the former "Log In" button to a "Log Out" button
_and_ the system displays the links "Profile" and "Account Management"

See [current login page](https://easey-dev.app.cloud.gov/login) as reference.
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb) Wireframe 2B

**Comment by mosesdeeCVP** [comment]
Test Case: [TC185](https://epacamd.testquality.com/search/test/284805?q=tc185)

**Comment by mosesdeeCVP** [comment]
![1414 Display login as modal and logged in view - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/253fa203-ca0a-43b7-90d7-f91a32751652)

**Comment by mosesdeeCVP** [comment]
![1414 Display login as modal and logged in view - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/321a7722-1e47-4d4e-b2c4-7b4733d9c922)

**Comment by mosesdeeCVP** [comment]
![1414 Display login as modal and logged in view - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/698f9e91-a7ef-48d3-a8e8-693955a1158b)

**Comment by mosesdeeCVP** [comment]
Test case passed - Ticket closed
