### ISSUE TITLE
Check Out a MP configuration (Scenario 2)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1416]
### Definition of Ready
- [x] Does this meet the INVEST criteria? (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### User Story
As an ECMPS editor, I want to check out a specific configuration of a Monitoring Plan. 

Acceptance Criteria:
_Given an editor has selected a facility 
_When the list of configurations for the facility is displayed 
_Then the editor select Open and Check Out for a configuration 

Given an editor has selected Open and Check Out for a configuration on the facilities list 
When a draft does not already exist
Then the system creates draft copy of the MP for the configuration
And displays the mont plan screen
And opens config in new tab 
And displays the Method section by default 
And displays the 1st alphanumeric configuration
And checks out the selected  configuration 
And the system logs the date and user that checked the configuration out 
And shows the option to View/Edit

Given an editor has selected Check Out for a configuration from the configuration tab
When a draft does not already exist
Then the system creates draft copy of the MP for the configuration
And checks out the selected  configuration 
And the system logs the date and user that checked the configuration out
And shows the option to View/Edit

Given an editor has selected Open for a configuration 
When a draft does not already exist
Then the system takes user to mont plan screen
And opens config in new tab
And check out is not selected by default 
And displays the Method section by default 
And displays the 1st alphanumeric configuration

### Context
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb): Scenario 2 6/3 version 

Click open for a particular config
Options, open, open and check out and manage config
Open = takes user to mont plan screen, opens config in new tab, view only, check out is not selected by default (is available if not checked out); If checked out, display who has config checked out, and check out is not available
Open and check out = creates draft copy on MP, takes user to mont plan screen, opens config in new tab, editable, check out is selected by default, config is checked out, facility is locked (no one else can change other parts of the facility data), check in available
Manage config = not active
API will:
Check for existing draft, and create if none exists
Copy MP data for the selected config only into draft

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC198](https://epacamd.testquality.com/project/11428/plan/19352/test/287318)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Case: [TC198](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/287318)

**Comment by mosesdeeCVP** [comment]
![1416 Check Out a MP configuration (Scenario 2) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b4a94613-45e1-41ce-b799-13233e31ae32)

**Comment by mosesdeeCVP** [comment]
https://epacamd.testquality.com defect [D45](https://epacamd.testquality.com/project/11428/result/2424527/defect/7893).

**Comment by mosesdeeCVP** [comment]
The UI does not show the date and user that checked the configuration out
There is no method to check out / check in the user after they click on Open

**Comment by mosesdeeCVP** [comment]
Bug ticket: [1554](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1554)
