### ISSUE TITLE
Check in a Configuration (Scenario 2)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1418]
Definition of Ready

- [x]  Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [x]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [x]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?

User Story
As an ECMPS editor I want to check in my edits so that the draft is updated 

Acceptance Criteria:
_Given_ the user is on the configuration tab 
_When_ the user checks in the configuration with the "Check In" button
_Then the system updates the visual cue of the draft icon in the Facility and configuration tab no longer displays
And the system unlocks Facility and configuration
And logs the date and user of the last check in 

[See wireframes ](https://xd.adobe.com/view/e6ce7aa2-59d8-4800-8b30-f11b2d706c81-b39d/screen/0fd6a3c5-45f1-4de4-a93c-7266e7b90e15/)

Testing
Test Case: [TC215](https://epacamd.testquality.com/project/11428/plan/19352/test/292133)
Tester: @mosesdeeCVP 

Definition of Done

- [x]  Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x]  Has the code been unit tested and peer reviewed?
- [x]  Have the functional tests been executed?
- [x]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x]  Has the user story been accepted by the Product Owner?
- [x]  Is the user story ready to be deployed to the test/staging environments?

**Comment by MoAdeyoju** [comment]
Based on conversation during DSU on 7/2, removed the AC to set the status of the MP. @JorjaComer will discuss with @chrisgitsit

**Comment by mosesdeeCVP** [comment]
![1418 Check in a Configuration (Scenario 2) - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/abcbd8df-adae-40ed-9924-a0a0c2a066fb)

**Comment by mosesdeeCVP** [comment]
![1418 Check in a Configuration (Scenario 2) - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/51ce8ca2-89aa-43f2-8688-e652429dd832)

**Comment by mosesdeeCVP** [comment]
Test Passed
