### ISSUE TITLE
View Locked Facility with Visual Cues

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1419]
Definition of Ready
 

- [x] Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [x]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [x]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?
- [ ] 

User Story
As a ECMPS editor
I want to select a facility to edit
So that I can view the configurations

Acceptance Criteria

_Given_ the user is in their Workspace for MP 
_When_ the user opens a Facility locked by another user
_Then_ the system displays a lock indicator in context with the Facility name 
_and_ displays the user and date for last check out 

Given the user is in their Workspace for MP
When the user opens a monitoring plan locked by another user
Then the system displays the last saved draft copy

Given the user is in their Workspace for MP
When another user has not made nay changes within 30 seconds (in lower environment)
Then the lock is removed for the user viewing the monitoring plan 

Given the user is in their Workspace for MP
When the current user has monitoring plan checked out 
Then system will only one MP, for all facilities, to be checked out at any given time

[See product board scenario 3](https://projects.invisionapp.com/freehand/document/TdahPfbEb) 
Testing
Test Case: [TC250](https://epacamd.testquality.com/project/11428/plan/19352/test/295436)
Tester: @mosesdeeCVP 

Definition of Done

- [x]  Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x]  Has the code been unit tested and peer reviewed?
- [x]  Have the functional tests been executed?
- [x]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x]  Has the user story been accepted by the Product Owner?
- [x]  Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1419 View Locked Facility with Visual Cues - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f6c92339-0a4f-41ac-8841-2462c633c8fd)

![1419 View Locked Facility with Visual Cues - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d37c51a0-29e7-4751-baf1-fbcb41e4f3cb)

![1419 View Locked Facility with Visual Cues - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/13f55b90-7843-4f6e-bf5a-16191d9875c0)

**Comment by mosesdeeCVP** [comment]
Test Passed
