### ISSUE TITLE
TypeScript coding standards documentation

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#142]
- [x] Reference coding standards document template created by Emissioners (#140)
- [x] Research industry standards for TypeScript
- [x] Document coding standards
- [x] Document styling standards
- [x] Document best practices
- [x] Document naming conventions

A/C: 
Document with set of coding standards for the development team uploaded to EPA Sharepoint

**Comment by junie-stigdon** [comment]
Met with Quang and Sejal to discuss standardizing the template format.

**Comment by junie-stigdon** [comment]
Had another meeting with Quang and Sejal to continue refining the template. Also met with Jason to review progress.

**Comment by junie-stigdon** [comment]
Completed peer review. Now working on integrating the feedback I got. 

Edit: Submitted for another review. Pending feedback.

**Comment by junie-stigdon** [comment]
Completed document: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/General/Coding%20Standards/TypeScript%20Coding%20Standards%20-%20EPA%20CAMD%20-%20v1.1.pdf?csf=1&web=1&e=dqgkAV
