### ISSUE TITLE
View Locked Facility's Workspace draft with edits (Scenario 3)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1420]
Definition of Ready
 

- [ ] Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [ ]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [ ]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?

As a user, I want to view the MP of a Facility that has been checked out by another user. 

Acceptance Criteria:
_Given_ the user is in their Workspace for MP 
_When_ the user opens a Facility locked by another user
_Then_ the system displays the last saved draft copy        

[See product board scenario 3](https://projects.invisionapp.com/freehand/document/TdahPfbEb)

Testing
Test Case:
Tester:

Definition of Done
 

- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ]  Has the code been unit tested and peer reviewed?
- [ ]  Have the functional tests been executed?
- [ ]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ]  Has the user story been accepted by the Product Owner?
- [ ]  Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Doing with #1419
