### ISSUE TITLE
Implement inactivity window on locked Facility

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1421]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As a user, I would like to know when my inactivity window will expire.

_Given_ a user has locked a Facility for viewing and editing
_When_ the system has noted 14 minutes and 30 seconds of user inactivity
_Then_ the system will display a 30 second warning
_

Given there has been 14 minutes 30 seconds of inactivity 
When the user does not take an action for 15 minutes
Then the system unlocks the Facility
And checks the configuration back in
And does not save edits 

Given there has been 14 minutes 30 seconds of inactivity 
When the user takes an action before the 15 minute clock expires
Then the system maintains the lock on the Facility
And maintains the check out on the configuration
And restarts the 15 minute window if the user resumes activity.

Message:
It looks like you have been inactive for a while. Save your changes to continue or lose unsaved work in 30 seconds. Click OK.

NOTE: Added the time remaining for screen readers in order to be 508 compliant.

[Error message: EI01](https://teams.microsoft.com/l/file/E95CEE6E-3EC6-4619-A8C9-CEEA00ECD464?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FCoding%20%26%20Error%20Standards%2FError%20Messages-EPA%20CAMD-v2.1.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

activity = open/close window/modal

lower environment time out = 1 min 

lower environment message = 30 seconds 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Case: [TC199](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/287319) . This will be the test case after full Checkout functionality is implemented.

**Comment by mosesdeeCVP** [comment]
Test Case: [TC200](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/287342) - This test case only test the timer functionality alone without the checkout functionality.

**Comment by mosesdeeCVP** [comment]
Test Passed. Ticket closed

**Comment by mosesdeeCVP** [comment]
![1421 Implement inactivity window on locked Facility.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c7d30890-75e3-4b14-9139-d2a845635efc)
