### ISSUE TITLE
Revert to official record

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1422]
As a user, I want to revert to the Facility's official MP record.

_Given_ a user has saved edits
_When_ the user selects the "Revert to official record" link
_Then_ the system discards the edits and returns the Workspace draft to the official record. 

Given a user has checked out a monitoring plan
When a user reverts to official record 
Then status is set to approved

**Comment by Qb10** [comment]
wireframe:
https://xd.adobe.com/view/e6ce7aa2-59d8-4800-8b30-f11b2d706c81-b39d/screen/cd6f1a6f-80e5-4f54-986b-190dd895c5cc/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC308](https://epacamd.testquality.com/project/11428/plan/19352/test/296398)

**Comment by mosesdeeCVP** [comment]
![1422 Revert to official record.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cf1155e9-3eab-4df2-8927-2bb4d64daf15)

**Comment by mosesdeeCVP** [comment]
Test Passed
