### ISSUE TITLE
Bug: Reusable Component Browser Compatibility 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1430]
## Test Case
Program: TC169
Fuel Type: TC172
Control Technology: TC174
Unit Type: TC175 
Priority: : Chrome, Firefox, Edge 

### Actual Results

1. On chrome, the reusable component (program, unit type, unit fuel type, and control technology) makes the user's screen jump when they select a grouping. 

2. On Firefox, the reusable component (program, unit type, unit fuel type, and control technology) makes the user's screen jump and creates additional spacing in the filter panel when the user makes a selection (see below) 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b8a3e935-b633-4c28-8679-0996b8610739)

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D33](https://epacamd.testquality.com/project/11428/result/2406127/defect/7800). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D34](https://epacamd.testquality.com/project/11428/result/2406548/defect/7801). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D35](https://epacamd.testquality.com/project/11428/result/2406105/defect/7802). Do not remove or edit.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D36](https://epacamd.testquality.com/project/11428/result/2391399/defect/7803). Do not remove or edit.

**Comment by JorjaComer** [comment]
Also test #1432 when this is resolved

**Comment by david-cvp** [comment]
Priority order:

Chrome v86
MS Edge v86
Firefox v80
Safari v13

**Comment by JanellC** [comment]
Defects resolved @tlageman-epa
