### ISSUE TITLE
Mid-Fi Wireframe for Opening or Locking a Facility (by 4.4 refinement)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1437]
Create mid-fi wireframe for opening or locking a Facility by a logged in user.

This wireframe will support #1411 (open) and #1345 (lock).

Please see low-fi mockup (PD Board Scenario 2B) for logged in view:
NOTE: Available actions should be "Open" and "Lock"
![image.png](https://images.zenhubusercontent.com/5f4d197dc2ff1e178ac4f6dd/2aef89df-d3d6-433d-855a-bfa2ada162f7)

**Comment by cvp-alexrobinson** [comment]
Here's the XD developer link: https://xd.adobe.com/view/e6ce7aa2-59d8-4800-8b30-f11b2d706c81-b39d/
Tomorrow (6/9), I'll make a few more back-end updates and republish the link to be more developer friendly.
