### ISSUE TITLE
Mid-Fi Wireframe for Checking Out a MP (by 4.4 refinement)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1438]
Create mid-fi wireframe for checking out a MP to view/edit.

This wireframe will support #1416.

Please see low-fi mockup (PD Board Scenario 2C) for view prior to checking out:
![image.png](https://images.zenhubusercontent.com/5f4d197dc2ff1e178ac4f6dd/c7beade8-7bd9-4019-b13d-7db51f91cd09)

**Comment by cvp-alexrobinson** [comment]
Here's the XD developer link: https://xd.adobe.com/view/e6ce7aa2-59d8-4800-8b30-f11b2d706c81-b39d/
Tomorrow (6/9), I'll make a few more back-end updates and republish the link to be more developer friendly.
