### ISSUE TITLE
Check Out a MP configuration with an existing draft

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1439]
### Definition of Ready
- [x] Does this meet the INVEST criteria? (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### User Story
As an ECMPS editor, I want to check out an existing draft of MP configuration so that I can make more changes to it. 

Acceptance Criteria:
_Given the editor is viewing a list of configuration for a facility
_When the editor selects Open and Check Out 
_Then_ the system displays the draft
And opens config in new tab
And displays the XXXX section by default
And displays a list of XXXXXX associated to the configuration
And checks out the selected configuration
Ans locks the facility (no one else can change other parts of the facility data)
And the option to check in is available
And the system logs the date and user that checked the configuration out

Given an editor has selected Open for a configuration
When a draft does not already exist
Then the system takes user to mont plan screen
And opens config in new tab
And check out is not selected by default
And displays the Method section by default
And displays the 1st alphanumeric configuration

Given an editor has selected Check Out for a configuration from the configuration tab
When a draft does not already exist
Then the system creates draft copy of the MP for the configuration
And checks out the selected configuration
And locks the facility (no one else can change other parts of the facility data)
And the option to check in is available
And the system logs the date and user that checked the configuration out
And shows the option to View/Edit

_Given the editor is viewing a list of configuration for a facility
_When one configuration for the facility is checked out 
_Then_ the system prevents any other drafts from being checked out 

### Context
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb): 
Wireframe 2C for view prior to checking out.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
story not needed
