### ISSUE TITLE
Display Checked Out MP Configuration

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1440]
### Definition of Ready
- [x] Does this meet the INVEST criteria? (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### User Story
As a logged in user, I want to confirm that I have checked out a MP configuration.

Acceptance Criteria:
_Given_ the user has selected a MP configuration
_When_ the user enables the "Check Out" toggle display
_Then_ the toggle display changes from "Check Out" to "Check In"
_and_ the MP section actions button changes from "View" to "View/Edit" 
_and_ a draft icon displays in the Facility tab.

### Context
See [PD Board](https://projects.invisionapp.com/freehand/document/TdahPfbEb): 
Wireframe 2D for view after checking out.

**Comment by JorjaComer** [comment]
OBE
