### ISSUE TITLE
Mid-Fi Wireframe for Checked Out MP View (by 4.4 refinement)

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#1441]
Create mid-fi wireframe for the view of a checked out MP.

This wireframe will support #1440.

Please see low-fi mockup (PD Board Scenario 2D) for view after checking out:
![image.png](https://images.zenhubusercontent.com/5f4d197dc2ff1e178ac4f6dd/27f4338b-13bd-4525-b2c9-1471f1d63702)

**Comment by cvp-alexrobinson** [comment]
Here's the XD developer link: https://xd.adobe.com/view/e6ce7aa2-59d8-4800-8b30-f11b2d706c81-b39d/
Tomorrow (6/9), I'll make a few more back-end updates and republish the link to be more developer friendly.
