### ISSUE TITLE
Review login page for accessibility

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1447]
- [x] Review the login modal for accessibility concerns once #1414 is complete

**Comment by aprematta** [comment]
[EPA Login Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6580321/EPA.Login.Accessibility.Report.docx)

**Comment by aprematta** [comment]
Adding login audit report, @karenhwwoo let me know if you want to do a walkthrough of the issues
