### ISSUE TITLE
Facility data relationships

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#145]
- [x]  Identify facility data relationships in order to build facility data service

**Comment by junie-stigdon** [comment]
Tables and ERD can be found here: https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Facilities?csf=1&web=1&e=XasHvJ
