### ISSUE TITLE
Side nav color update

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1450]
- [x] New color for side nav from @cvp-alexrobinson 

### Assets

- https://xd.adobe.com/view/6f123f2f-3eb8-4922-8270-17e2ba234f69-3a41/

![EASEY-In  Workspace  Monitoring Plans.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/062c4e9d-1d3c-4880-a365-83b6408ce7d7)

**Comment by cvp-alexrobinson** [comment]
@Qb10 — New color for sidebar—in the spirit of rapid development—is #f1f1f1 (lightest-gray). Wireframe to reflect that is coming up shortly.

**Comment by cvp-alexrobinson** [comment]
Per @Qb10 's recommendation, we're going with `.bg-base-lightest` (`#f0f0f0`) for the background color, since that's right from the [USWDS color guide](https://designsystem.digital.gov/utilities/color/).

**Comment by mosesdeeCVP** [comment]
Test Case: [TC186](https://epacamd.testquality.com/project/11428/plan/19813/test/fullscreen/285216)

**Comment by mosesdeeCVP** [comment]
![1450 Side nav color update.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e2e871fa-ff76-496b-83c4-eb58a08514c7)

**Comment by mosesdeeCVP** [comment]
Test Passed - Ticket closed
