### ISSUE TITLE
Cancel and Login Error shows during Login process

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1452]
When User logs in, Cancel and Login Error messages show  briefly during log in process.

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/03868951-e3b0-41a3-8246-8375454bf5a6)

- [x] Remove cancel button for spinner
- [x] Resolve issue so no error appears for successful login

Tester: @david-cvp 
@aprematta to perform 508 review of login modal

**Comment by david-cvp** [comment]
Test case passed, bug fixed

 ![bug-fixed.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/5e3f444d-05d7-4a22-bdb4-7b026efd4a6f)

**Comment by david-cvp** [comment]
@aprematta performed a 508 review and confirmed no new issues have been introduced.

FIndings from #1447 still apply
