### ISSUE TITLE
Bug: Preview less than 100 records

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1455]
### Step 1
| Step | Action | Expected | Status |
|-|-|-|-|
| 1 | Navigate to the custom data download and select all required fields except for time period  | The preview data button should be disabled  | Pass |
| 2 | Select all required fields (data type, data sub type, time period) | Then the preview data button is enabled  | Pass |
| 3 | Select preview data button  | 1. Then the system will display total record count  2. Contains all data elements in the correct order with the correct data labels  3. The data table is limited to 100 records and ordered by facility, unit, date, and hour  4. Table contains a scroll functionality to view all rows and columns  5. results are sortable in ascending and descending order (alpha numeric)  | FAIL |

### Actual Results
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b203332c-8e9f-4906-b40a-10f260fa84bc)

results should update dynamically. ex viewing the first 48 out of 48 records

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D38](https://epacamd.testquality.com/project/11428/result/2411690/defect/7821). Do not remove or edit.

**Comment by JorjaComer** [comment]
Linked issue is expected to resolve this bug (scheduled to be complete in 4.4). retest in sprint 4.5

**Comment by JanellC** [comment]
@tlageman-epa Retested this issue in sprint 5.1. The bug was not resolved with aligning the data table to the react component. The results still do not update dynamically. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8550e37f-a730-43a6-a0d2-645513238504)

**Comment by JanellC** [comment]
D38 resolved 
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_23446.png)
