### ISSUE TITLE
Bug: CAMPD Search Functionality 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1456]
## Context 

**Steps to replicate:** 
1. Navigate to CAMPD custom data download https://campd-dev.app.cloud.gov/select-data-type
2. Apply a data type and data subtype 
3. Apply filter criteria 
3. Select menu 
4. Make a search 

When a user makes a search while on the custom data download, the system redirects the user to the custom data download landing page. The system should retain the page a user makes a search on. 

### User Story
#833 

### Acceptance Criteria

Given I have navigated to the custom data download functionality
When the functionality is displayed
Then I have the option to select emissions, allowance, and compliance data

Given the user has selected a data type (emissions, allowance, or compliance)
When they select continue
Then the filter criteria page is displayed (no content)

Given a user has accessed the CAMPD custom data download functionality
When the application is displayed
Then it is displayed with a header

Given a user has accessed the CAMPD custom data download functionality in a lower (non-prod) environment
When the application is displayed
Then the system will indicate this is a sandbox (non-prod) environment

Given the updated header is displayed
When the menu option is chosen
Then the menu bar is displayed
And provides the option to close the menu

Given a user has accessed the EPA header menu
When the menu is displayed
Then the following links are displayed(includes sub topic):

Environmental Topics
Laws & Regulations
About EPA
Given a user has selected a link from the header menu
When a link is selected
Then the system opens the link on the EPA website in a new tab

Given a user has chosen to search the EPA website via the header
When the search is executed
Then the system opens the link on the EPA website in a new tab to view the results

Given the updated footer is implemented
When the footer is displayed
Then it contains the EPA standard menu
And provides the ability to close the menu

Given a user has accessed the EPA menu
When the menu is displayed
Then the system displays the following links:

Accessibility
Privacy
Privacy and Security Notice
Given the menu is displayed
When a link is selected
Then the system opens the link on the EPA website in a new tab (see EPA.gov for links)

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D39](https://epacamd.testquality.com/project/11428/result/2412036/defect/7825). Do not remove or edit.

**Comment by JorjaComer** [comment]
need to associate to header and footer in shared libraries

**Comment by MaeganWood64** [comment]
Tested for Both CAMPD and ECMPS
