### ISSUE TITLE
Update Responsiveness 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1460]
PI 6 Estimate: 13

## Epic Benefit
We want to "provide a usable view of the CAMPD app at all resolutions above 480 px" while ensuring that priority resolutions of 1024 px and above render correctly.

## Context
[Wireframes ](https://xd.adobe.com/view/0d66fc88-4098-434f-a84d-63b15ed6ef9f-5835/flow)

Decision: When fly outs are displayed at a resolution of 1024 or above, then the fly out is closed via the cancel button (back arrow is removed). This diverges from the wire frames, but was agreed to by the team on 7/16.

**Comment by tlageman-epa** [comment]
@JorjaComer Can we modify the language in the requirements to: 

We want to "provide a usable view of the CAMPD app at all resolutions above 480 px" while ensuring that priority resolutions of 1024 px and above render correctly. 

Thanks!

**Comment by JorjaComer** [comment]
@tlageman-epa done!

**Comment by JorjaComer** [comment]
@cvp-alexrobinson @junie-cvp @JanellC 

See updated decision re back arrow

**Comment by JanellC** [comment]
Epic completed
