### ISSUE TITLE
Title Sidebar responsiveness (desktop) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1461]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the side bar  to adjust to my device screen size so that I can build a query on my device

## Acceptance Criteria
Given that a user has accessed the custom data downlead on a desktop (1024 +) 
When the sidebar functionality is displayed 
Then the side bar is displayed in accordance with the wireframes (see context) 

Given that a user has accessed the custom data downlead on a desktop
When the custom data download box is displayed  
Then the box displayed in accordance with the wireframes  (see context) 

## Styling Checklist See #1311 for more info 

**Filter Panels:**

- [x] Filter panels are a different shade of blue than the wireframes.

## Context

this 
Resolution 1024 and up 
[Custom data download content-only responsive screens (dev link) ](https://xd.adobe.com/view/f084825d-086d-452c-9e0a-a97049c65c46-a5d7/)

[Mobile flow for reference ](https://xd.adobe.com/view/ffb58352-f4e5-42ed-8509-cd566b3177e6-aae6/grid) 

The scope of this ticket includes addressing the responsiveness for 

- the side bar (data type section and filters section)
- the custom data download title box
- Change data type section 
- 

## Testing
Test Case:[ TC228](https://cvpcorp.testquality.com/project/11428/plan/21283/test/294610)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC228 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/76a9eb5a-17f9-471e-bbdd-6da27021f304)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/27628ba1-2fc1-4f67-a048-796ced25134a)
