### ISSUE TITLE
Update header responsiveness

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1462]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the header to adjust to my device screen size so that I can build a query on my device

## Acceptance Criteria
Given
When
Then

Styling Checklist See #1311 for more info 

- [ ] Both backgrounds should be white #FFF
- [ ] Footer has a 1px border top of #D6D7D9
- [ ] Footer menu icon open and close should be EPA blue icons and borders with a white background
- [ ] Footer menu pop-up should be white background and the text should be EPA blue.
- [ ] See One EPA Option 4 for dev specs

## Context
[Wireframes ](https://xd.adobe.com/view/0d66fc88-4098-434f-a84d-63b15ed6ef9f-5835/flow/)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Ticket no longer needed
