### ISSUE TITLE
Update filter and filter panels (filter fly out) responsiveness (mobile & tablet breaks) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1465]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the filter panels to adjust to my device screen size so that I can build a query on my device 

## Acceptance Criteria
Given that a user has accessed the custom data download on a mobile or tablet device 
When the functionality is displayed 
Then the filters are displayed in accordance with the wireframes (see context)

Given that a user has accessed the custom data download on a mobile or tablet device 
When the functionality is displayed 
Then the filter panels are displayed in accordance with the wireframes (see context)

## Developer notes 

**UI Updates** 

**Filters**
- The filters button on the helper text 

When a user first enters the cdd the filters button should be disabled until a data type is applied 

The settings icon on the filters should be replaced with a x to clear a single filter after filter criteria has been applied for that single  filter 

For the filters Maintain the clear all button and replace the back arrow with back button . The back button and clear all button will be placed at the bottom of the panel/ below the filters 

The filters screen will have a button at the bottom of the panel to preview data. For preview  data maintain tool tip 

When a user selects the back button on the filters page then they are directed to the helper text page 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1c6b61f1-7bc7-48cd-80ad-eb5425e2ea43)

**Filter panels** 
For the filter panels, remove the back arrow and maintain the cancel button and apply filter button. 

When filters are applied then the filters button on the CDD helper text page should display the number of filters applied . For example, see screen capture below 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/41eb3d99-b513-4e38-b6d5-ea423627ad22)

When a user selects cancel on the filter panels screen then they are directed back to the filters page 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/cc6b3fe9-81f7-4d5d-bf6b-d2e2b15fefea)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
 

[Filters wireframes](https://xd.adobe.com/view/121d4adc-4c31-403c-91c2-2fd3764fa4f3-474e/screen/a59b2aba-032e-402a-b260-e2121589c03c/) - slides 14, 15 

[Filter Panel wireframes](https://xd.adobe.com/view/121d4adc-4c31-403c-91c2-2fd3764fa4f3-474e/screen/4dc9a973-929e-4f66-98aa-e9d2801d36d0/) -slides 16, 17

## Testing
Test Case: [TC229](https://cvpcorp.testquality.com/project/11428/plan/21283/test/294611)
Tester: @JanellC 

508 Testing
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Allison will conduct some research to see if it is recommended to use a x to clear a filter instead of displaying a clear button

**Comment by JanellC** [comment]
TC229 failed @tlageman-epa . Logged Bug: CDD Filters and Data Type Mobile and Tablet Responsiveness #2508 to track the changes

**Comment by JanellC** [comment]
@aprematta This ticket is ready for 508 testing. As apart of this ticket, retest the responsiveness of the data preview on the CDD.
