### ISSUE TITLE
Select Configuration (scenario 2)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1466]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a ECMPS editor
I want to select a facility to edit 
So that I can view the configurations

## Acceptance Criteria
Given a user is in their workspace
When they navigate to the monitoring plan section of the workspace
Then a list of facilities associated to the logged in user is displayed

Given a user is viewing the list of facilities
When the list of facilities is displayed
Then the facilities are displayed alphanumerically in descending order
And the facilities can be sorted in ascending and descending order

Given a user is viewing the list of facilities
When they select a facility
Then the list of configurations associated to that facility is displayed alphanumerically in descending order
And the button to Open (config level) is available
And the button to Open and Check Out (config level) is available
And the button to Manage Configurations (at the selected facility level) is available

## Context
[See screen 5B](https://projects.invisionapp.com/freehand/document/TdahPfbEb)

Story one - active only - 3
If user has logged in, then they are returned to page they logged in from
If user has navigated to the workspace, mont. plan section, they they can see a list of facilities associated to the user
Select facility
Expand facility
View configs associated to facility
Select a config
Buttons are view only, not functional
Open (config level)
Open and check out (config level)
Manage config (at the selected facility level)
Facility can be sorted, ascending, descending
Ordered alphanumerically descending by default
## Testing
Test Case: [TC201](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/287354)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1466 Select Configuration (scenario 2).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8349a182-1fcd-4449-abcb-76a8c85ac09d)

**Comment by mosesdeeCVP** [comment]
Test Case passed
