### ISSUE TITLE
Apportioned Emissions Bulk Data Files Quartz Process

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1472]
## Apportioned Emissions
Create a Quartz Job responsible for determining which datasets need to be generated/regenerated. This job will NOT be responsible for generating the files, instead, this process will schedule multiple instances of the BulkDataFile job that will actually stream the data to S3 storage.

### Implementation Details
In the easey-quartz-scheduler jobs folder create a class called ApportionedEmissionsBulkDataFiles that implements the Quartz IJob interface by implementing the Execute method of the interface.

Create a new uuid/guid value for this parent job process which will be used for all instances of the BulkDataFile as the parent_job_id

Insert a record into the camdaux.job_log as follows...
- job_id = uuid/guid generated above
- job_system = Quartz
- job_class = Bulk Data File
- job_name = Apportioned Emissions
- add_date = current datetime
- start_date = current datetime
- end_date = null
- status_cd = WIP

Use the database view **camdaux.vw_annual_emissions_bulk_files_per_state_to_generate** to execute the following query in order to determine which annual by state files need to be generated/regenerated.
```
CREATE OR REPLACE VIEW camdaux.vw_annual_emissions_bulk_files_per_state_to_generate AS
SELECT rp.calendar_year as year, p.state as state_cd
FROM camdecmps.dm_emissions dme
JOIN camdecmpsmd.reporting_period rp USING (rpt_period_id)
JOIN camdecmps.monitor_plan mp USING (mon_plan_id)
JOIN camd.plant p USING (fac_id)
LEFT JOIN camdecmps.dm_emissions_user dmeu
	ON dme.dm_emissions_id = dmeu.dm_emissions_id
	AND dmeu.dm_emissions_user_cd = 'S3BDF'
WHERE dmeu.dm_emissions_id IS null
GROUP BY rp.calendar_year, p.state
ORDER BY year, state_cd;
```
**Example Results**
![image](https://user-images.githubusercontent.com/66504934/157370023-49254eb8-5a9a-4d3a-8ed2-b0a3b37363bd.png)

Use the database view **camdaux.vw_annual_emissions_bulk_files_per_quarter_to_generate** to execute the following query in order to determine which annual by quarter files need to be generated/regenerated.
```
CREATE OR REPLACE VIEW camdaux.vw_annual_emissions_bulk_files_per_quarter_to_generate AS
SELECT rp.calendar_year as year, rp.quarter, rp.begin_date AS qtr_begin_date, rp.end_date AS qtr_end_date
FROM camdecmps.dm_emissions dme
JOIN camdecmpsmd.reporting_period rp USING (rpt_period_id)
LEFT JOIN camdecmps.dm_emissions_user dmeu
	ON dme.dm_emissions_id = dmeu.dm_emissions_id
	AND dmeu.dm_emissions_user_cd = 'S3BDF'
WHERE dmeu.dm_emissions_id IS null
GROUP BY rp.calendar_year, rp.quarter, rp.begin_date, rp.end_date
ORDER BY year, quarter;
```
**Example Results**
![image](https://user-images.githubusercontent.com/66504934/157370145-a67e1619-5bf3-4b87-b545-58d796bd0607.png)

Using the results from both views above...
- Insert a record into the camdaux.job_log as follows...
  - job_id = generate a new uuid/guid
  - job_system = Quartz
  - job_class = Bulk Data File
  - job_name = <Emissions | MATS>-<Hourly | Daily>-YEAR-<QTR | STATE>
      _Examples: Emissions-Hourly-2021-TX, Emissions-Daily-2021-Q1, MATS-Hourly-2021-FL_
  - add_date = current datetime
  - start_date = null
  - end_date = null
  - status_cd = QUEUED
- Insert a record into the camdaux.bulk_file_log as follows...
  - job_id = same one used to create the job_log record
  - parent_job_id = use the parent_job_id uuid/guid generated earlier at the very beginning
  - data_type = emissions | mats
  - data_subtype = hourly | daily
  - year = year from view results above
  - quarter = quarter from view results above
  - state_cd = state_cd from view results above
- Immediately schedule an instance of the BulkDataFile Quartz Job
- Repeat for each year/quarter and year/state combination for hourly, daily, and MATS hourly emissions data

**Hourly per Year by Quarter (Quarterly)**
- Generate files for each year by quarter from 1995 up to last reported quarter
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/hourly/stream?beginDate={QTR-BEGIN-DATE}&endDate={QTR-END-DATE}
  - fileName=/emissions/hourly/quarter/Emissions-Hourly-{YEAR}-Q{QTR}.csv

**Hourly per Year by State (Annually)**
- Generate files for each year by state from 1995 up to last reported year
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/hourly/stream?beginDate={YEAR}-01-01&endDate={YEAR}-12-31&stateCode={STATE-CD}
  - fileName=/emissions/hourly/state/Emissions-Hourly-{YEAR}-{STATE-CD}.csv

**Data Elements**
The hourly emission files by year and quarter should contain the following data elements. The records will be ordered by facilityId > unitId > date > hour and adhere to the csv data labels in the Master Data Dictionary.  

stateCode  
facilityName   
facilityId  
unitId   
unitType   
associatedStacks   
primaryFuelInfo  
secondaryFuelInfo   
so2ControlInfo  
pmControlInfo   
noxControlInfo  
hgControlInfo 
programCodeInfo   
grossLoad   
steamLoad   
so2Mass   
so2Rate   
noxMass   
noxRate   
co2Mass   
co2Rate   
heatInput  
so2MassMeasureFlg   
so2RateMeasureFlg  
noxMassMeasureFlg   
noxRateMeasureFlg   
co2MassMeasureFlg    
co2RateMeasureFlg   
date    
hour  
opTime

**Daily per Year by Quarter (Quarterly)**
- Generate files for each year by quarter from 1995 up to last reported quarter
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/daily/stream?beginDate={QTR-BEGIN-DATE}&endDate={QTR-END-DATE}
  - fileName=/emissions/daily/quarter/Emissions-Daily-{YEAR}-Q{QTR}.csv

**Daily per Year by State (Annually)**
- Generate files for each year by state from 1995 up to last reported year
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/daily/stream?beginDate={YEAR}-01-01&endDate={YEAR}-12-31&stateCode={STATE-CD}
  - fileName=/emissions/daily/state/Emissions-Daily-{YEAR}-{STATE-CD}.csv

**Data Elements**
The daily emission files by year and quarter should contain the following data elements. The records will be ordered by Facility > Unit > Date and adhere to the csv data labels in the Master Data Dictionary.
 
STATE 
FACILITY_NAME 
ORISPL_CODE 
UNITID 
ASSOC_STACKS 
OP_DATE 
SUM_OP_TIME 
COUNT_OP_TIME 
GLOAD 
SLOAD 
SO2_MASS 
SO2_RATE 
NOX_MASS 
NOX_RATE 
CO2_MASS 
CO2_RATE 
HEAT_INPUT 
PRIMARY_FUEL_INFO 
SECONDARY_FUEL_INFO 
UNIT_TYPE_INFO 
SO2_CONTROL_INFO 
PART_CONTROL_INFO 
NOX_CONTROL_INFO 
HG_CONTROL_INFO 
PRG_CODE_INFO 

**MATS Hourly per Year by Quarter (Quarterly)**
- Generate files for each year by quarter from 2015 up to last reported quarter
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/mats/hourly/stream?beginDate={QTR-BEGIN-DATE}&endDate={QTR-END-DATE}
  - fileName=/emissions/hourly/quarter/MATS-Hourly-{YEAR}-Q{QTR}.csv

**MATS Hourly per Year by State (Annually)**
- Generate files for each year by state from 2015 up to last reported year
- JobData parameters
  - job_id=guid
  - parent_job_id=guid
  - format=csv
  - url=/emissions-mgmt/apportioned/mats/hourly/stream?beginDate={YEAR}-01-01&endDate={YEAR}-12-31&stateCode={STATE-CD}
  - fileName=/emissions/hourly/state/MATS-Hourly-{YEAR}-{STATE-CD}.csv

**Data Elements**
The MATS hourly emission files by year and quarter should contain the following data elements. The records will be ordered by facilityId > unitId > date > hour and adhere to the csv data labels in the Master Data Dictionary.

stateCode 
facilityName 
facilityId 
unitId 
date 
hour 
opTime 
matsGrossLoad 
matsHeatInput 
hgOutputRate 
hgInputRate 
hgMass 
hgMassMeasureFlg 
hclOutputRate 
hclInputRate 
hclMass 
hclMassMeasureFlg 
hfOutputRate 
hfInputRate 
hfMass 
hfMassMeasureFlg 
associatedStacks 
steamLoad 
primaryFuelInfo 
secondaryFuelInfo 
unitType 
so2ControlInfo 
noxControlInfo 
pmControlInfo 
hgControlInfo

### Frequency
- Annually (Year/State): At the end of the 4th quarter reporting period each year with nightly checks for changes/updates
- Quarterly (Year/Quarter): At the end of each quarterly reporting period with nightly checks for changes/updates

### Additional development notes
Database tables to use to determine changes/updates
- camd.plant
- camdecmps.monitor_plan
- camdecmps.dm_emissions
- camdecmps.dm_emissions_user
- camdecmpsmd.reporting_period
- camdecmpsmd.dm_emissions_user_code

dm_emisisons contains one record per submission of emissions data for a specific monitor plan from which we can derive the year, quarter, state, & reporting period each submission pertains to.

dm_emissions_user contains one record per submission of emissions data for a user of the data. User refers to a process that utilizes the data for some purpose and in this case the process generating bulk data files is the user (S3BDF).

**_ATTENTION_**
Once all instances are scheduled create a record in the dm_emissions_user table with the S3BDF process user code for each of the dm_emissions records that match the year/quarter and year/state  combinations from the view resuts above used to determine the files to be generated/regenerated. 

Update job_log for this parent process
- end_date to current datetime
- status_cd to COMPLETE | ERROR
- additional_details can be used for any general or error information

The BulkDataFilesMaintenance Quartz Job will handle individual jobs that get stuck or fail by attempting to rerun them periodically and cleanup successfully completed jobs that have aged and no longer need to be retained.

**Comment by MaeganWood64** [comment]
Waiting on Requirements from Travis
