### ISSUE TITLE
Easey Design System & component library using Storybook

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#1474]
Joshua will discuss overall architecture options for this feature with team.  Ultimately we are going to do the follow:

- Create reusable react components that will be shared via an NPM/Github packages library across multiple platforms.
- These reusable components will have the capability to have customizable data properties in order to set features needed for specific site content requirements (possibly look and feel).
- These reusable components will meet "Section 508" compliance standards. [Refer to 508 report for more information](https://teams.microsoft.com/l/file/F0EA1EC3-02D1-464C-BD16-E41F0F9C843F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FDesign%2FAccessibility%20and%20Section%20508%2FEPA%20Header%20and%20Footer%20Accessibility%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) 

RF-1a, RF-1b, RF-2, RF-3, RF-4, RF-5, RF-6, RF-7a, RF-7b, RF-8 

- Update header responsiveness. See #1462 
- Update header and footer styling and menus [Wireframes](https://xd.adobe.com/view/08505c73-3291-4c0a-819f-982951ae417f-5d03/screen/367f93ca-f627-4e81-9e07-0fc290889acd/) Option 4
- Publish library and update EASEY apps to use the component so it can be tested

Given a user has accessed the EASEY In functionality
When the application is displayed
Then it is displayed with a header

Given a user has accessed the EASEY In functionality in a lower (non-prod) environment
When the application is displayed
Then the system will indicate this is a sandbox (non-prod) environment

Given the updated header is displayed
When the menu option is chosen
Then the menu bar is displayed
And provides the option to close the menu 

Given a user has accessed the EPA header menu
When the menu is displayed
Then the following links are displayed:

Environmental Topics
Laws & Regulations
About EPA
Accessibility
Privacy
Privacy and Security Notice
Given a user has selected a link from the header menu
When a link is selected
Then the system opens the link on the EPA website in a new tab

Given a user has chosen to search the EPA website via the header
When the search is executed
Then the system opens the link on the EPA website in a new tab to view the results

[Product Design board  ](https://projects.invisionapp.com/freehand/document/OcjjU0obK)

![image](https://user-images.githubusercontent.com/67168611/122572303-9d7f6b80-d01b-11eb-992d-2a25144bc1b7.png)

Tester: @mosesdeeCVP and @YefimAbramsonCVP 
Test case:

**Comment by jm9900guy** [comment]
Joshua will discuss overall architecture options for this feature with team.  Ultimately we are going to to do the follow:

- Create reusable react components that will be shared via an NPM/Github packages library across multiple platforms.
- These reusable components will have the capability to have customizable data properties in order to set features needed for specific site content requirements (possibly look and feel).
- These reusable components will meet "Section 508" compliance standards.

**Comment by cvp-alexrobinson** [comment]
@jm9900guy — [EPA Header and Footer (Dev link)](https://xd.adobe.com/view/aa7a4ca1-d935-4224-b377-7b540577f255-ff29/)
Please let me know if there's anything missing or if you need any help with the XD dev link.
