### ISSUE TITLE
Bug: Update Allowance Program filter to include OTC and NBP 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1482]
## Test Case

[TC184](https://cvpcorp.testquality.com/project/11428/plan/20058/test/283783)

## Expected Result:

Allowance Transactions should contain the following programs: ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, NBP, OTC, TXSO2

Account information should contain the following programs: ARP, CSNOX, CSSO2G1, CSSO2G2, TXSO2, CAIRSO2, CAIRNOX, CSOSG1, CSOSG2, CSNOXOS, CAIROS, NBP, OTC

Allowance Holdings: Active programs only: ARP, CSNOX, CSOSG1/2, CSSO2G1/2, TXSO2. 

From  Lageman, Travis
Addis Gebremichael (Guest) looks good thx for taking care of this! janell coleman (Guest) I think we talked about this before but not sure if it is captured in a ticket. There is some adjustment that needs to be made to the Program table in the database and/or Program MDM because OTC and NBP are not being recognized as Allowance programs and therefore are not showing up in the appropriate Program panel filters Addis just fixed. Can we make sure this is captured in a bug/the backlog. I'm out tmrw but we can discuss next week. thx!

### Actual Results

IN CAMPD, allowance transactions and account information are missing the programs NBP and OTC. There may need to be a change in the database or program endpoint to fix this. 

### User Story

As CAMPD user I want to be able to view the filter criteria for facility, state, program, unit type, fuel type, and control technologies for Emissions, Allowance, and Compliance so that I can get data that I need. #1435

### Acceptance Criteria

Given that a user has selected a data type and a data sub type
When the filter criteria page is displayed
Then the filters facility, state, program, unit type, fuel type, and control technologies are displayed, have data, and are interactive

Given that a user has applied filter criteria
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria
When the criteria is cleared
Then the system clears the criteria from the filter

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D41](https://epacamd.testquality.com/project/11428/result/2413233/defect/7839). Do not remove or edit.

**Comment by jwhitehead77** [comment]
Modify MDM Program endpoint to have isActive and exclude filters (remove the allownaceOnly filter) and add 3 new properties emissionsUIFilter (maps to emissions_ui_filter db column), allowanceUIFilter (maps to allowance_ui_filter db column), & complianceUIFilter (maps to compliance_ui_filter db column) to the response.

Modify the UI to filter using the emissionsUIFilter, allowanceUIFilter, & complianceUIFilter properties based on the data type/subtype selected.

Examples:
If user selects any Emission subtypes then only show Programs with emissionsUIFilter = 1 or true
If user selects any Allowance subtypes then only show Programs with allowanceUIFilter = 1 or true
If user selects any compliance subtypes then only show Programs with complianceUIFilter = 1 or true

**Comment by tlageman-epa** [comment]
NBP and OTC programs also need to be added to Allowance Based Compliance Program filter

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D62](https://epacamd.testquality.com/project/11428/result/2413233/defect/8035).

**Comment by JanellC** [comment]
Defect D62 resolved
