### ISSUE TITLE
Bug: Update Compliance (Allowance based) program filter 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1483]
## Test Case
[TC184](https://cvpcorp.testquality.com/project/11428/plan/20058/test/283783)

## Expected Result:
2) Program - In Compliance  Allowance based , the program filter has some programs that are not allowance based. The list of available programs should be both active and retired, but only allowance based.

Compliance Allowance Based should contain the following programs:  ARP, CSNOX, CSOSG1/2, CSSO2G1/2, TXSO2, CSNOXOS

### Actual Results

The program filter for compliance (allowance based) contains too may programs 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6cd65442-7e04-442a-9827-73b8b824f1bf)

### User Story

As CAMPD user I want to be able to view the filter criteria for facility, state, program, unit type, fuel type, and control technologies for Emissions, Allowance, and Compliance so that I can get data that I need. #1435

### Acceptance Criteria

Given that a user has selected a data type and a data sub type
When the filter criteria page is displayed
Then the filters facility, state, program, unit type, fuel type, and control technologies are displayed, have data, and are interactive

Given that a user has applied filter criteria
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria
When the criteria is cleared
Then the system clears the criteria from the filter

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D42](https://epacamd.testquality.com/project/11428/result/2413233/defect/7840). Do not remove or edit.

**Comment by jwhitehead77** [comment]
Modify MDM Program endpoint to have isActive and exclude filters (remove the allownaceOnly filter) and add 3 new properties emissionsUIFilter (maps to emissions_ui_filter db column), allowanceUIFilter (maps to allowance_ui_filter db column), & complianceUIFilter (maps to compliance_ui_filter db column) to the response.

Modify the UI to filter using the emissionsUIFilter, allowanceUIFilter, & complianceUIFilter properties based on the data type/subtype selected.

Examples:
If user selects any Emission subtypes then only show Programs with emissionsUIFilter = 1 or true
If user selects any Allowance subtypes then only show Programs with allowanceUIFilter = 1 or true
If user selects any compliance subtypes then only show Programs with complianceUIFilter = 1 or true

**Comment by JanellC** [comment]
Defect D42 resolved.
