### ISSUE TITLE
Add Fuel Code and Type Code to System Fuel Flows

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1487]
The Fuel Flow code needs to be added to the System Fuel Flows API so that it will appear in the UI 

Type code needs to be added to the System Fuel Flows API so that it will appear in the UI

**Comment by mosesdeeCVP** [comment]
https://epacamd.testquality.com defect [D43](https://epacamd.testquality.com/project/11428/result/2415510/defect/7843). Do not remove or edit.

**Comment by mosesdeeCVP** [comment]
The Fuel Code is not showing the correct data it is showing the Unit of Measure Code instead

**Comment by mosesdeeCVP** [comment]
Original Ticket was: [898](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/898)

**Comment by jwhitehead77** [comment]
@tdavydets this is ready for ui work as api now returns the fuelCode and systemTypeCode

![image](https://user-images.githubusercontent.com/66504934/122301164-ec1af180-cec5-11eb-8ec9-744229ee1f57.png)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC189](https://epacamd.testquality.com/project/11428/plan/20829/test/285616)

**Comment by mosesdeeCVP** [comment]
![1487 Add Fuel Code and Type Code to System Fuel Flows - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2eee0073-5075-4581-a7d9-4b8ed2838ec0)

**Comment by mosesdeeCVP** [comment]
![1487 Add Fuel Code and Type Code to System Fuel Flows - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/63ff6227-fdb2-4c40-b826-0cfefa26b58f)

**Comment by mosesdeeCVP** [comment]
Test Passed
