### ISSUE TITLE
View Inactive Configurations (viewing/editing)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1488]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user
I want view to inactive configurations 
So that I can view all configurations for a facility 

## Acceptance Criteria
Given the user has selected a facility 
When the list of configurations is displayed
Then the system shows a list of active and inactive configurations for the facility 

## Context
[Wireframes ](https://xd.adobe.com/view/d9319bf6-edc3-4488-8aa4-9feff83c0995-8c62/screen/db45774c-f993-4359-a6d9-a8737ec9b094)

## Testing
Test Case: [TC203](https://epacamd.testquality.com/project/11428/plan/19352/test/288277)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1488 View Inactive Configurations (viewing-editing) - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/591d5cca-2ad9-46b5-984d-488c6c0a2986)

**Comment by mosesdeeCVP** [comment]
Test Passed
