### ISSUE TITLE
Update Logged Out View (scenario 1) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1497]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As user with out edit rights 
I want view the monitoring plans associated to my facilities 
So that I can view the last checked in version 

## Acceptance Criteria
Given the user has navigated to the monitoring plan viewer
When the list of facilities is displayed 
Then the system displays all facilities

Given the user is viewing the list of facilities
When a particular facilities is selected
Then the system shows all active configurations for the selected facility 
And the Open button next to all configurations for the facility 

## Context
[See Scenario 1 on the 6/3 version of wireframes ](https://projects.invisionapp.com/freehand/document/TdahPfbEb)
Use out of box components 

Maria navigates to the monitoring plan viewer

The system displays all facilities 

Maria selects Show Configurations next to a particular facility 

The system displays all active configurations associated to the selected facility

## Testing
Test Case: [TC194](https://epacamd.testquality.com/project/11428/plan/19352/test/fullscreen/287254)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1497 Update Logged Out View (scenario 1).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1daae068-88c4-4e7e-b839-24bf54d57f89)

**Comment by mosesdeeCVP** [comment]
Test Case passed
