### ISSUE TITLE
Data Preview Responsiveness (mobile & tablet breaks) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1498]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the data preview to adjust to my device screen size so that I can preview my dataset on my device 

## Acceptance Criteria
Given that a user has previewed their dataset on a mobile or tablet  device 
When the functionality is displayed 
Then the data preview data table is displayed in accordance with the wireframes (see context)

## Development Notes 

- back arrow in the wireframes will be replaced with a back button. The back button will be placed at the top of the page. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
resolution 480 and 640

[Data preview wireframes ](https://xd.adobe.com/view/121d4adc-4c31-403c-91c2-2fd3764fa4f3-474e/screen/ee23fd79-f2ff-4866-9f57-38127f4eb70e/)

## Testing
Test Case: [TC233](https://cvpcorp.testquality.com/project/11428/plan/21283/test/294616)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC233 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/eb82f8c2-d44b-4e08-a069-99ba38709db3)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dc73a26b-b1af-4d7b-ba45-0d48fbf55e23)
