### ISSUE TITLE
Update CAMPD Main Menu Responsiveness

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1499]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the main menu to adjust to my device screen size so that I can build a query on my device

## Acceptance Criteria
Given that a user has accessed the custom data download on a mobile, tablet, desktop, or widescreen device 
When the functionality is displayed 
Then the CAMPD menu is displayed in accordance with the wireframes (see context for links)  

## Styling Checklist 
**CAMPD Navigation Bar**

- [ ] Use the attached as the background image, size as "cover", align top center. background-size: cover; background-position: center top; (see below)
- [ ] Title font should be Merriweather, normal, 30px
- [ ] Navigation item fonts should be Source Sans, bold, 16px, uppercase
- [ ] Navigation item dropdown arrows should be the icon in the May Demo Design specs. It's showing as a solid carrot.
- [ ] The "In" nav item state bottom border color should be the aqua color, called "Info Base" in the specs
- [ ] Nav items that are dropped down, the carrot should invert indicating that it's collapse-able.
- [ ] Only Data, Analysis, and Visualization have dropdowns, not Home.
- [ ] The title and nav items area should take up the same horizontal space as the USWDS banner. See my CodePen for USWDS grid classes

See #1311  for more info 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Scope does not include the child elements 

[CAMPD menu ](https://xd.adobe.com/view/0d66fc88-4098-434f-a84d-63b15ed6ef9f-5835/screen/9458e725-3cbd-4c16-9376-704ee7da3b19/)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Ticket no longer needed. The work is covered in tickets #1524 and #1561
