### ISSUE TITLE
Select Data Type Page Responsiveness (main page)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1500]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the select data type page to adjust to my device screen size so that I can build a query on my device

## Acceptance Criteria
Given that a user has accessed the custom data download select data type page on a mobile, tablet, or desktop device  
When the functionality is displayed 
Then the select data type page is displayed in accordance with the wireframes (see context) 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Custom data download content-only responsive screens (dev link) ](https://xd.adobe.com/view/f084825d-086d-452c-9e0a-a97049c65c46-a5d7/) slides 1,2,3

[Mobile flow for reference ](https://xd.adobe.com/view/ffb58352-f4e5-42ed-8509-cd566b3177e6-aae6/grid) 

## Testing
Test Case: [TC227](https://cvpcorp.testquality.com/project/11428/plan/21283/test/294609)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC227 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/25a5ec41-8d38-4039-bb7d-6e5b865c0002)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/63d55fa3-1b25-43bc-9987-b9b2ca09cbe5)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a38e1eb3-1915-48d0-b97c-aa7979a4e341)
