### ISSUE TITLE
Open Config logged out view (Scenario 1)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1503]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a logged out user
I want open a configuration 
So that I can view it 

## Acceptance Criteria
Given the user is viewing the list of configurations 
When the user selects Open for a configuration 
Then the system opens the selected configuration in a new tab
And the system displays 1st alphanumeric Location and Method Section by default
And the system displays all elements(e.g. System ID) associated with the default section and location 

Given a user is viewing the all elements(e.g. System ID) associated with the configuration
When the user selects View next to the element she wishes to view 
Then the system displays the detailed information for the selected element (e.g. System details modal window) 

Given a user is viewing a configuration
When the user changes a location
Then the system updates the elements displayed for the selected section 

Given a user is viewing a configuration
When the user changes a section
Then the system updates the elements displayed for the selected location 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC202](https://epacamd.testquality.com/project/11428/plan/19352/test/287569)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1503 Open Config logged out view (Scenario 1) - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2b51f607-6ee7-4124-8cc3-67563dabbc86)

**Comment by mosesdeeCVP** [comment]
![1503 Open Config logged out view (Scenario 1) - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/af212e42-6a2c-44bc-85bc-2892ae3b6c0a)

**Comment by mosesdeeCVP** [comment]
Test Passed
