### ISSUE TITLE
SPIKE: Add Wide Screen to UDWDS Library 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1505]
## Context 
Research how to configure wide screen break points. 

Break points that we're including:
  'mobile-lg':      // 480px
  'tablet':         // 640px
  'desktop':        // 1024px
  'widescreen':     // 1400px

**Comment by junie-stigdon** [comment]
Need to import:
$theme-font-path: "~uswds/dist/fonts";
$theme-image-path: "~uswds/dist/img";

And replace the css import with scss. We will be able to override the $theme-utility-breakpoints variable and set the breakpoints needed to true.  

Work tracked on #1551
