### ISSUE TITLE
CAMPD Data Landing Page 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1519]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user  I want to view the data landing page so that I can familiarize myself with the different data tools 

## Acceptance Criteria
Given that a user has navigated to the CAMPD data landing page
When the page renders
Then its is in accordance with [wireframes](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD?node-id=1%3A148&scaling=min-zoom&page-id=1%3A146)

Note: Static Datasets will now be "Bulk Data Files". The first sentence under the blurb should change to "For larger data downloads, bulk data files provide access to prepackaged datasets of...". Call to action label can stay the same.

## Context
Scope includes responsiveness 
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD?node-id=1%3A148&scaling=min-zoom&page-id=1%3A146

Use borderless EPA box style 

## Testing
Test Case: [TC223](https://cvpcorp.testquality.com/project/11428/plan/21067/test/294196)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC223 failed. I logged Bug: CAMPD Data Landing Page #1696 to track the changes @tlageman-epa

**Comment by JanellC** [comment]
[CAMPD Data Landing Page ](https://easey-dev.app.cloud.gov/campd/data) is ready for 508 testing
