### ISSUE TITLE
Update CAMPD Sub Header Menu (responsiveness and menu items)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1524]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the CAMPD sub header menu to adjust to my device screen size so that I can navigate the tool on my device 

## Acceptance Criteria

Given that a user has accessed the CAMPD home page 
When the functionality is displayed 
Then the menu contains home, data, analysis, visualization, CAM API, and Help

Given that a user has accessed the CAMPD home page  on a mobile, tablet, desktop, or widescreen device 
When the functionality is displayed 
Then the CAMPD sub header menu is responsive to different screen sizes and displays in accordance with the wireframes 

## Styling Checklist 
**CAMPD Navigation Bar**

- [x] Use the attached as the background image, size as "cover", align top center. background-size: cover; background-position: center top; (see below)
~• Title font should be Merriweather, normal, 30px~ (not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)
~• Navigation item fonts should be Source Sans, bold, 16px, uppercase~ (not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)
~• Navigation item dropdown arrows should be the icon in the May Demo Design specs. It's showing as a solid carrot.~(not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)
~• The "In" nav item state bottom border color should be the aqua color, called "Info Base" in the specs~ (not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)
- [x] Nav items that are dropped down, the carrot should invert indicating that it's collapse-able. ([see updated design](https://xd.adobe.com/view/b8910f01-91c8-4c94-b079-9243cd0c4632-edc2/specs/) documents –Alex Robinson, 6/25/21)
~• Only Data, Analysis, and Visualization have dropdowns, not Home.~ (not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)
~• The title and nav items area should take up the same horizontal space as the USWDS banner. See my CodePen for USWDS grid classes~ (not relevant any more since we have updated design documents –Alex Robinson, 6/25/21)

See #1311  for more info 

## Context

[Wireframes](https://xd.adobe.com/view/0ce7370c-8097-4130-9db1-ace4aab30cda-59b4/screen/9b3b9ca8-70c4-47a4-81da-3a1810ae49e4/)

## Testing
Test Case:[ TC208](https://cvpcorp.testquality.com/project/11428/plan/21067/test/292118)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC208 failed @tlageman-epa . I logged Bug: Update CAMPD Sub Header Menu (responsiveness and menu items) #1577 to track the issue
