### ISSUE TITLE
Update Tool tips (Post BETA)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1540]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the tool tips to display the appropriate language so that I can have guidance while navigating the application

## Acceptance Criteria
Given
When
Then

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Update filter tool tip to display the appropriate language after the BETA Testing  

CAMPD Tool Tip Prompts

Data Type
• Data type and subtype can be changed at any time.

Filters
• (For beta) Use the filters below to refine your query. The filter criteria will not update based on other criteria selections. If no selections are made in a filter, all data related to that filter will be returned.
• Use the filters below to refine your query. Not applying a filter is equivalent to selecting all for that filter. For more information on each filter, visit the Data Dictionary in the Help menu.

Preview Data
• Preview the first 100 rows of your query here.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
handled by work in other epics
