### ISSUE TITLE
Check Out button and User/Date logged in UI (Scenario 2) 

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1554]
The UI does not show the date and user that checked the configuration out
There is no method to check out / check in the user after they click on Open

This is a potential bug from ticket [1416](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1416)
 Test Case: [TC198](https://epacamd.testquality.com/project/11428/plan/19352/test/287318)

**Comment by mosesdeeCVP** [comment]
![1416 Check Out a MP configuration (Scenario 2) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0240a551-17e8-4fd6-840c-b09ede31faf8)

**Comment by JorjaComer** [comment]
User and date display  will be handled via #1419
