### ISSUE TITLE
Display Bypass Approach Code  in Mont. Methods 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1555]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a ECMPS user 
I want to be able to select a bypass approach code 
So that I can add or edit it 

## Acceptance Criteria
Given a user has accessed monitoring methods 
When bypass approach codes are displayed
Then I can edit an existing
And add a new code

## Context
Bypass Approach Code (BypassApproachCode)
Report the Bypass Approach Code used to calculate emissions for an unmonitored bypass stack
whose method of determining emissions is based on a default value. The Bypass Approach Code
is not required if a bypass stack is directly monitored or valid data are calculated from monitors
at other locations (e.g., at a control device inlet). This code is only applicable for parameters
SO2, NOX, and NOXR with CEM, CEMF23, and NOXR method codes. Report the appropriate
uppercase codes as shown in Table 13:

![image](https://user-images.githubusercontent.com/67168611/123645981-cb6f6780-d7f4-11eb-9d6c-584d03f18d1d.png)

https://www.epa.gov/sites/production/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf

## Testing
Test Case: [TC214](https://epacamd.testquality.com/project/11428/plan/19352/test/292132)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1555 Display Bypass Approach Code in Mont. Methods .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9b1c0498-2fe6-4fad-bf2e-b196503c7395)

**Comment by mosesdeeCVP** [comment]
Test Passed
