### ISSUE TITLE
Display sub. data approach code  in Mont. Methods 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1556]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a ECMPS user 
I want to be able to select a sub. data approach code 
So that I can add or edit it 

## Acceptance Criteria
Given a user has accessed monitoring methods 
When sub. data approach codes are displayed
Then I can edit an existing
And add a new code

## Context
Substitute Data Code (SubstituteDataCode)
Report the Substitute Data Code that designates the methodology used to determine substitute
values during periods of missing data. Leave this field blank when NOX Mass is calculated from
NOX Rate and HI (Method Code NOXR and Parameter Code NOX). Also, leave this field blank
for parameter codes OP, HGRE, HGRH, HCLRE, HCLRH, HFRE, HFRH, SO2RE, SO2RH,
and all LME methods, with the following exception. When using long-term fuel flow as the heat
input methodology for an LME unit, report a Substitute Data Code of MHHI only if it will ever
be necessary to report the unit's maximum rated hourly heat input rate as the heat input rate for
any hour. This may be necessary for either of two reasons: (1) for any hour when burning a
secondary fuel that is not measured by a long-term fuel flow system, or (2) if a unit operated for
only a very short period or used only a very limited amount of fuel during a quarter or reporting
period, so that a tank drop measurement will not yield an accurate estimate of the fuel combusted
during the reporting period. Report the appropriate uppercase code as shown in Table 12:

![image](https://user-images.githubusercontent.com/67168611/123646584-59e3e900-d7f5-11eb-900a-db8b77669396.png)

https://www.epa.gov/sites/production/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf

## Testing
Test Case: [TC213](https://epacamd.testquality.com/project/11428/plan/19352/test/292131)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1556 Display sub. data approach code in Mont. Methods.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1b867ef5-7aa4-4167-9be7-1bf827d209d7)

**Comment by mosesdeeCVP** [comment]
Test Passed
