### ISSUE TITLE
Display Parameter Code  in Mont. Methods 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1557]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a ECMPS user 
I want to be able to select a parameter code 
So that I can add or edit it 

## Acceptance Criteria
Given a user has accessed monitoring methods 
When parameter codes are displayed
Then I can edit an existing
And add a new code

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC212](https://epacamd.testquality.com/project/11428/plan/19352/test/292130)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Passed![1557 Display Parameter Code in Mont. Methods - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/125d19f3-1ffe-40c2-a548-5a0eb85bf9fd)

**Comment by mosesdeeCVP** [comment]
![1557 Display Parameter Code in Mont. Methods - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7e0a6d1-e8ac-46c8-b905-742e4be0da67)

**Comment by mosesdeeCVP** [comment]
![1557 Display Parameter Code in Mont. Methods - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a413e1e3-3646-4345-acc2-677f386a48bb)

**Comment by mosesdeeCVP** [comment]
![1557 Display Parameter Code in Mont. Methods - 04.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ac3d170f-6b52-4870-baeb-f698ba035a3b)
