### ISSUE TITLE
Display Method Code  in Mont. Methods 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1558]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a ECMPS user 
I want to be able to select a method code 
So that I can add or edit it 

## Acceptance Criteria
Given a user has accessed monitoring methods 
When method codes are displayed
Then I can edit an existing
And add a new code 

## Context
Monitoring Method Code (MonitoringMethodCode)
Report the Monitoring Method Code that identifies the methodology employed to monitor the specified parameters at the specified monitoring location. Report the appropriate uppercase code as shown below

![image](https://user-images.githubusercontent.com/67168611/123465812-9b3d8400-d5bc-11eb-8a4f-622b8a7575ce.png)
![image](https://user-images.githubusercontent.com/67168611/123465920-ba3c1600-d5bc-11eb-8938-01ec7a3f2b81.png)

![image](https://user-images.githubusercontent.com/67168611/123466158-012a0b80-d5bd-11eb-8eb2-1bc6bbe6e56a.png)

[Refer to reporting instructions for more information (pg. 29)](https://www.epa.gov/sites/production/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC211](https://epacamd.testquality.com/project/11428/plan/19352/test/292128)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1558 Display Method Code in Mont. Methods - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ab2c4b62-443d-4f2e-a341-6162c597869f)

**Comment by mosesdeeCVP** [comment]
![1558 Display Method Code in Mont. Methods - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5b3c2c0b-8d22-45f6-92a4-5d15f1906191)

**Comment by mosesdeeCVP** [comment]
Test Passed
