### ISSUE TITLE
Add Menu Items to CAMPD Sub Header 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1561]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want view menu items under the  CAMPD sub header So that I can understand how to navigate the site 

## Acceptance Criteria
Given a user has navigated to the CAMPD home page 
When the  sub header menu is displayed 
Then the menu contains home, data, analysis, visualization, CAM API, and Help

Given that a user has selected "home" 
When the selection is executed 
Then the system links to the CAMPD home page 

Given that a user has selected "Data" 
When the selection is executed 
Then the system displays custom data download and bulk data files as sub menu options 

Given that a user has selected custom data download from the data  sub menu options
When the selection is executed
Then the system links to the custom data download landing page (select data type page)

Given that a user has selected "Analysis" 
When the selection is executed 
Then the system displays coming soon as a sub menu option 

Given that a user has selected "Visualization" 
When the selection is executed 
Then the system displays coming soon as a sub menu option 

Given that a user has selected "CAM API" 
When the selection is executed 
Then the system displays coming soon as a sub menu option 

Given that a user has selected "Help" 
When the selection is executed 
Then the system displays the following as sub menu options:

About CAMPD 
Tutorials 
Glossary
FAQs
Related Resources 
Contact Us
Site Map 

## Context
includes responsive break points for child menus at a resolution of 1024 and up
Test child items using ctrl +click 

It was decided during DSU on 7/1 that sub header menu items at mobile and tablet breakpoints are out of scope for this ticket. Another ticket will be added to the backlog. to address this work. 

See [wireframes ](https://xd.adobe.com/view/b8910f01-91c8-4c94-b079-9243cd0c4632-edc2/grid)

## Testing
Test Case: [TC210 ](https://cvpcorp.testquality.com/project/11428/plan/21067/test/292122)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@JanellC @addisgmichael Just in, we want to change name of "Data Dictionary" to "Glossary" based off our easey-baby discussions, internal discussions and referencing the lexicon in our teams channel. Please make sure that is reflected in the submenu work. Thanks!

**Comment by JanellC** [comment]
Hi  @tlageman-epa thank you for the update. I updated the acceptance criteria to reflect this change. Are we changing "static datasets" to "Bulk Data Files" as well?

**Comment by tlageman-epa** [comment]
@JanellC yes!

**Comment by JanellC** [comment]
TC210 failed @tlageman-epa. I logged Bug: Add Menu Items to CAMPD Sub Header #1599 to track the changes.
