### ISSUE TITLE
Refactor CAMPD UI to use easey-design-system components

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1572]
Remove the header/footer components within the CAMPD UI code base, install the easey-design-system shared package and use the shared components

Refer to One EPA header footer changes on[ Invision board](https://projects.invisionapp.com/freehand/document/OcjjU0obK) 

### Acceptance Criteria 

Given that a user has accessed CAMPD
When the functionality is displayed
Then the application contains the version banner 
AND the page content is not cut off by the version banner 

### Developer Notes 

Ensure that the content on all the CAMPD web pages is not cut off by the version banner 

### Test Only 

Given a user has accessed the CAMPD functionality
When the application is displayed
Then it is displayed with a header

Given a user has accessed the CAMPD functionality in a lower (non-prod) environment
When the application is displayed
Then the system will indicate this is a sandbox (non-prod) environment

Given the updated header is displayed
When the menu option is chosen
Then the menu bar is displayed
And provides the option to close the menu 

Given a user has accessed the EPA header menu
When the menu is displayed
Then the following links are displayed:

Environmental Topics
Laws & Regulations
About EPA
Accessibility
Privacy
Privacy and Security Notice

Given a user has selected a link from the header menu
When a link is selected
Then the system opens the link on the EPA website in a new tab

Given a user has chosen to search the EPA website via the header
When the search is executed
Then the system opens the link on the EPA website in a new tab to view the results

Given the menu is displayed
When a link is selected
Then the system opens the link on the EPA website in a new tab (see EPA.gov for links)

## Testing 

Test Case:[ TC480 ](https://epacamd.testquality.com/project/11428/plan/21067/test/313112)
Tester: @JanellC

**Comment by JorjaComer** [comment]
@jm9900guy Updated AC to reflect new header and footer design. 

@MaeganWood64 FYI

**Comment by MaeganWood64** [comment]
Discussions to continue on CAMPD Side. Would like to be a shared component so Travis + Chris can update as they please. Same design as on ECMPS, but discussions of functionality to happen soon.

Do some solutioning to discuss functionality and to control the content on the page

**Comment by JanellC** [comment]
During DSU on 12/3 the team discussed switching the filters on the custom data download over to Material UI as apart of the scope of this ticket.  The EPA requested to have an internal discussion about the Material UI icons before the switch is made. As a result, the work for switching over to material ui icons was removed from the scope of this ticket and added to ticket #2346

**Comment by JanellC** [comment]
TC480 passed @tlageman-epa
