### ISSUE TITLE
Spike: Prep for filter logic discussion 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1579]
## Research Goals 

Prepare to discuss adding filter logic to the custom data download during CAMPD PI5 Product Backlog Refinement on 7/13. 

- Look into the best way to decompose the  filter logic work into backlog items 
- Provide estimates for the backlog items 

## Background 

[Filter Criteria Research Spike.pptx](https://teams.microsoft.com/l/file/A1E37E8D-432B-4735-AA4C-0961A024CE5D?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pptx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F4-Development%2FFilter%20Criteria%20Research%20Spike.pptx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

On Tue, Jun 29, 2021 at 12:36 PM Lageman, Travis <Lageman.Travis@epa.gov> wrote:
Hi All, since this is being cancelled, I wanted to share an update re: Filter Logic research that was presented to us. I think the natural place to discuss this further is during the 7/13 CAMPD backlog refinement but am happy to discuss earlier if needed.
 
Essentially, MOB still wants to pursue Option 1 in the long term. We are planning to probe further during the upcoming Beta test but don’t see any of the other options as viable. In order to get to the December release, however, we are postulating that we begin with having the following logic available (subject to change based on additional user feedback from the beta test):
•	Emissions data types – Time period will be required filter and must be applied before any remaining filter criteria are available to the user. The time period selection will adjust the options available in the remaining filters, but none of the other filters will relate to/update each other. 
•	Allowance/Compliance data types – More to come on this, but essentially we would have some limited UI logic we could implement based on known relationships. For example, If a user chooses general accounts only in the account type filter, it would disable the facility and state filters since we know that general accounts will never have an association with a state or facility. 
 
We would like to talk more about this to ensure that our vision is clear and to hear your feedback, concerns, effort, etc. so it is likely that after the holidays we will schedule these additional conversations in addition to any initial discussion on the 13th.
 
Thanks,
Travis

**Comment by sdhawan16** [comment]
Proposed a 4th option for the filter logic which is a hybrid of options 1 and 3. 

Updated deck including option 4: [Filter Criteria Research Spike V2](https://usepa.sharepoint.com/:p:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7BB43452A3-E6F3-4A21-AC81-4C5466955C38%7D). 
Provides an overview of the work required and the pros and cons of this option, along with an example of how the filtering would work. 

Discussed during planning to go ahead with option 4. Further internal dev team discussions will be required to decompose the work.
