### ISSUE TITLE
Priority #2 - Add Additional tables to MP Beta Release #1 Migration Package (Need by July 19)

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1580]
We need to add the following tables to the MP Beta Release #1 data migration package with CDC enabled

**Schema: CAMDECMPSMD
Tables:**
![image.png](https://images.zenhubusercontent.com/5efd0ad8b52b2bb67d0ab264/b321d271-94cb-4eb9-b6fe-5f729966858f)

**Schema: CAMDECMPS
Tables:**
![image.png](https://images.zenhubusercontent.com/5efd0ad8b52b2bb67d0ab264/2740d753-3d61-446d-b5df-78f280e64b5d)

Refer to the MP Beta Release #1 tab in the following document...
https://teams.microsoft.com/l/file/7596D4EC-D3C5-4E93-840E-D066AB92736E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTech%2FData%20Migration%2FSchema%20%26%20Tables%20for%20Informatica.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:e3d4667412cc496f87be989d2f8ede67@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23

**Comment by vkdontula** [comment]
This is complete.  Data is pulled into Staging db.

**Comment by jwhitehead77** [comment]
@vkdontula can we run the load for these against dev to get the data for these tables into dev as well. If we need to run all tables again to ensure we do not get constraint issues we just need to coordinate a time
