### ISSUE TITLE
Priority #3 - Separate Data Migration Informatica Packages into Release groups (Need by Aug EOM)

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1581]
Currently the data migration packages are group into 2 processes that was based on what was needed for development at the time. Some of this is going to production in Nov/Dec and some is going to a beta env in Nov/Dec so we need to split the processes into 2 packages based on what is needed for each release.

CAMPD Release #1 will go to production Nov/Dec 2021
MP Beta Release #1 will go to a beta env Nov/Dec 2021

For CAMPD Release #1 package please run in the following order...
1) https://github.com/US-EPA-CAMD/devops/blob/master/db/release%201/1-before-load.sql
2) Migrate Data
3) https://github.com/US-EPA-CAMD/devops/blob/master/db/release%201/2-account-type-group-code.sql
4) https://github.com/US-EPA-CAMD/devops/blob/master/db/release%201/3-unit-type-group-code.sql
5) https://github.com/US-EPA-CAMD/devops/blob/master/db/release%201/4-after-load.sql

Refer to the CAMPD Release #1 and MP Beta Release #1 tabs in the following document...
https://teams.microsoft.com/l/file/7596D4EC-D3C5-4E93-840E-D066AB92736E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTech%2FData%20Migration%2FSchema%20%26%20Tables%20for%20Informatica.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:e3d4667412cc496f87be989d2f8ede67@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23

**Comment by vkdontula** [comment]
This is ready in Informatica.
