### ISSUE TITLE
Priority #1 - Load Emissions data from production for CAMPD Beta Testing (Need by July 19)

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1582]
We need to load fresh data from camdpub (production) into the cloud.gov dev and test env for the CAMPD beta testing. Please load all data for the following tables. Please DO NOT load data from the archive tables.

**Schema: CAMDDMW
Tables:**
![image.png](https://images.zenhubusercontent.com/5efd0ad8b52b2bb67d0ab264/6d3c4a25-b78f-4432-a965-2cbfb36e4cbf)

**Comment by vkdontula** [comment]
@jwhitehead77 Please request Dave Greene to grant Informatica account 'Select' permissions to the new tables.

**Comment by vkdontula** [comment]
Jobs have been run to refresh data in these tables in Cloud.gov dev and staging databases from Production DB instance.
