### ISSUE TITLE
Add utility nav to CAMPD menu (1024 +) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1588]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the to use the utility nav so that I can navigate CAMPD and EASEY

## Acceptance Criteria

Given that a user has accessed CAMPD 
When the CAMPD subheader and menu is displayed in a resolution at 1024 or above
Then the functionality is in accordance with the [wireframes ](https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/grid/)

Given the user has accessed a CAMPD page
When a link to a non working page is displayed 
Then the link does not direct the user anywhere 

## Context
https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/grid/

**Links** 
Disable all links EXCEPT home, data landing page, and custom data download page 
Home should link to the CAMPD home page 
Data Home should link to the Data landing page 
Custom Data Download should link to the custom data download landing page (select data type) 

**CAMPD Menu** 
The CAMPD menu should have the following items: Home, Data, Analysis, Visualization. 

Home should link to the CAMPD home page 
Under Data the sub menu items should be : Data Home, Custom Data Download, Bulk Data Files, CAM API
Under Analysis the sub menu items should be : Coming Soon – View and download analyses.
Under Visualization the sub menu items should be : Coming Soon – Visualize and interact with data.

**Utility Nav**  

The utility nav menu should have the following items in the following order: Resources, Help/Support, Regulatory Partners, and Site Map,

Under Resources, the sub menu items should be Glossary, Related Resources
Under Help/Support, the sub menu items should be About CAMPD, Tutorials, FAQs, Contact Us
Under Regulatory Partners, the sub menu items should display "Coming Soon – Information and resources for Regulatory Partners"
Site map has no sub menu items

## Testing
Test Case: [TC224](https://cvpcorp.testquality.com/project/11428/plan/21067/test/294198)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
@ibarra-michelle and @tlageman-epa See updated Context to reflect your latest email.

**Comment by JanellC** [comment]
TC244 passed @tlageman-epa 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3487536b-9374-4c28-a880-d0229bbc4140)

**Comment by JanellC** [comment]
The [CAMPD header](https://easey-dev.app.cloud.gov/campd/) is ready for 508 testing 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ebfefd3e-1481-45b5-bef8-128a78f105d3)
