### ISSUE TITLE
Bug: Implement CAMPD Home Page Main Content 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1591]
## Test Case
[TC195](https://cvpcorp.testquality.com/project/11428/plan/20058/test/287303)

## Steps to Reproduce

| Step | Action  | Expected | Pass/Fail |
|-|-|-|-|
| 1 | Navigate to CAMPD   | The home landing page is displayed in accordance with the wireframe | Fail |

### Actual Results

 Step 1 failed because: 

1. There is a significant amount of white space between the data tools and the footer 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/99c05cf9-3cc3-439a-8e56-fb1ff6eeb16b)

2. The padding between visualization and coming soon is not like the wireframes 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/2e718531-971c-4aa3-94ec-e96663e88e52)

### User Story

As a CAMPD user I want to see a home page when I first enter the site so that I have a clear indication of how to navigate through the site 

Implement CAMPD Home Page Main Content #1059

### Acceptance Criteria
Given that a user has navigated to the CAMPD home page 
When the page renders 
Then it is in accordance with the [wireframes ](https://xd.adobe.com/view/0ce7370c-8097-4130-9db1-ace4aab30cda-59b4/)

Given that a user has accessed the CAMPD home page on a mobile, tablet, desktop, or widescreen device
When the functionality is displayed
Then the CAMPD home page is responsive to different screen sizes (see wireframes for breakpoints) 

Given that a user has selected "home"
When the selection is executed
Then the system links to the CAMPD home page

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D47](https://epacamd.testquality.com/project/11428/result/2430269/defect/7905).

**Comment by JanellC** [comment]
Defect D47 resolved.

**Comment by tlageman-epa** [comment]
@JanellC Just noticed that on the wireframes there was a small mistake. In the data box, there is "CAMD API" when it should be just "CAM API" to be consistent with the subheader menu. Want to identify this so we can fix prior to beta testing. Thx!
