### ISSUE TITLE
UI Design for CAM API Home Page (need by 7/27)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1596]
### Design Assets

- [CAM API design option 1](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=203%3A9&scaling=min-zoom&page-id=203%3A2)
- [CAM API design option 2](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=276%3A940&scaling=min-zoom&page-id=276%3A939)

7/21 -  Reviewed initial design with EPA. Next round of feedback will be delivered to EPA on 7/27. Design finalized on 7/28.

**Comment by maheese** [comment]
@cvp-alexrobinson here's a link to the proposed landing page [content](https://teams.microsoft.com/l/file/B9DE544C-E834-4E09-8880-2FF3BBA54779?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTech%2FAPI%2FDocumentation%2FCAM%20API%20Landing%20Page%20Content.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:e3d4667412cc496f87be989d2f8ede67@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) in Teams.

**Comment by cvp-alexrobinson** [comment]
Thanks, Mike!

**Comment by cvp-alexrobinson** [comment]
@maheese —

Hello,

Here is the first [design draft for the CAM API landing page](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=203%3A9&scaling=min-zoom&page-id=203%3A2). This can be discussed in tomorrow's product design session. Please let me know if you have any questions.

Best,
Alex

CC @JorjaComer @MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@maheese —

Hello,

I sure hope you had a great day! [Here's the revised CAM API landing page](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=203%3A4&scaling=min-zoom&page-id=203%3A2) for your review. You can use your arrow keys to see all available screen sizes. The designs start with mobile and go up to widescreen.

I'm also creating a version with the green EPA box style for "What's New" which I will have for you before the DSU tomorrow (7/28).

Best,
Alex

CC @JorjaComer @MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@maheese — 

[Here is the second CAM API option](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=276%3A940&scaling=min-zoom&page-id=276%3A939) that includes the green (EPA-style Related Info) what's new box. There was a little bit of shift in the style, just because of how that component is styled.

Best,
Alex

**Comment by cvp-alexrobinson** [comment]
@maheese —

Hello,

Here's the [updated prototype link for CAM API](https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=276%3A1185&scaling=min-zoom&page-id=276%3A939&starting-point-node-id=276%3A1185).

Best,
Alex

**Comment by maheese** [comment]
@cvp-alexrobinson that looks great.  I like the new "Relates to ...".  I do have one more request.  Can you use both the acronyms and spell things out in the header like is done for CAMPD and EASEY-IN.

![image](https://user-images.githubusercontent.com/16920772/127868577-26acc369-1ac4-4358-84e7-e11ea70310cf.png)

**Comment by cvp-alexrobinson** [comment]
@maheese -- Updated design with the updated header: https://www.figma.com/proto/pYenfFzGn6iIl4lnA1nXbs/EASEY-Baby-Designs?node-id=276%3A1185&scaling=min-zoom&page-id=276%3A939&starting-point-node-id=276%3A1185
