### ISSUE TITLE
Implement Semantic Release Versioning

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1597]
- Configure all repos and pipelines to use semantic release as a versioning strategy moving forward. 
- Update README to document how to use commitizen and semantic release.

**Comment by MaeganWood64** [comment]
Meeting to be scheduled where @jwhitehead77 will review Commitizen process with DEV team and relevant EPA members

**Comment by MaeganWood64** [comment]
- 12/1 Check in after Jason returns
