### ISSUE TITLE
On Demand update functionality for ECMPS and CAMPD

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1605]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a system admin 
I want to be able to update content on-demand for certain features 
So that I can keep users up to date with the most important and relevant information 

## Acceptance Criteria
Given a system admin has navigated to (XXXX) feature/function 
When they enter in their new content, message, etc 
Then the information will update on the page 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

The EPA wants the ability to be able to update the content in the whats new box at any time. The tech team will look into this. 

- For CAMPD, need the ability to update the whats new box and content on the about page 

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by MaeganWood64** [comment]
Discussions to continue on CAMPD Side. Would like to be a shared component so Travis + Chris can update as they please. Same design as on ECMPS, but discussions of functionality to happen soon.

Do some solutioning to discuss functionality and to control the content on the page
