### ISSUE TITLE
Convert View MP Methods to Mid Fi Designs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1608]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to view MP Methods using the mid fidelity design
So that I have a better experience 

## Acceptance Criteria
Given a user has accessed MP Methods
When it is viewed 
Then it is displayed according to the wireframes 

## Context
https://xd.adobe.com/view/dccab567-3abe-484a-bff7-844d701cd4eb-8999/

## Testing
Test Case: [TC235](https://epacamd.testquality.com/project/11428/plan/21289/test/294696)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1608 Convert View MP Methods to Mid Fi Designs.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4f50da35-f744-4145-9b3a-a2131f562fb7)

**Comment by mosesdeeCVP** [comment]
Test Passed
