### ISSUE TITLE
CAMPD FAQ Page

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1609]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the frequently asked questions page So that I can find commonly asked information about CAMPD  

## Acceptance Criteria
Given that a user has navigated to the FAQ page 
When the functionality is displayed 
Then the page renders in accordance with the wireframes (see context) 
AND the page content is consistent with the [ FAQ content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/6-Content%20Documents/2-Utility%20Menu/2-Help+Support/3-FAQs/FAQs%20Content-%20EPA%20CAMD-v1.011.docx?d=w447173f9455f4fd0a890a94b0c0f696b&csf=1&web=1&e=gPEX39)

Given that a user has selected Help/ support on the utility nav
When FAQs is selected 
Then the system displays the FAQ page 

Given that a user has accessed the tutorials page
When the FAQ link is selected
Then the user is redirected to the FAQ page

## Developer Notes 
Accordions should remain open until a user closes it 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[ FAQ content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/6-Content%20Documents/2-Utility%20Menu/2-Help+Support/3-FAQs/FAQs%20Content-%20EPA%20CAMD-v1.011.docx?d=w447173f9455f4fd0a890a94b0c0f696b&csf=1&web=1&e=gPEX39)

**Wireframes** 
- [FAQs Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=397%3A2656&scaling=contain&page-id=397%3A2503)
- [FAQs Page (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=397%3A2656)

## Testing
Test Case: [TC431 ](https://epacamd.testquality.com/project/11428/plan/21067/test/309143)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC431 failed @tlageman-epa . I logged Bug: CAMPD FAQ Page #2263 to track the changes.

**Comment by JanellC** [comment]
Bug #2263 resolved. This ticket is ready for 508 testing @aprematta
