### ISSUE TITLE
Bug: AE: Filter Custom Data Download By Time Period and enable data preview

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1614]
## Test Case
Test Case: [TC219](https://cvpcorp.testquality.com/project/11428/plan/20918/test/292138)

## Steps to Reproduce

For Annual Emissions, a user should be able to enter 1980, 1985, 1990 or a year greater than or equal to 1995-latest reporting quarter. The component doesn't accept years before 1995. The error message and component need to be updated 

### Actual Results
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/47bcf780-f15f-405e-9896-4312115e1986)

### User Story
As a CAMPD custom data download user I want to enter filter criteria for annual emissions and preview my dataset so that I can conduct analysis 

AE: Filter Custom Data Download By Time Period and enable data preview #1175

### Acceptance Criteria

Given that a user has selected annual emissions 
When the filter criteria page is displayed
Then the user must select time period filter criteria (not null)

Given a user has entered a year
When the user applies the filter
Then the system will ensure that the year is valid

Given that a user has selected time period
When the criteria is entered
Then the system ensures the years are in the YYYY format
And displays error message: FV-102 if not

Given that a user has selected time period
When the criteria is entered
Then the system ensures the years are a valid range
And displays error message: Fv-105 if not

Given a validation has failed
When the error message is displayed
Then the error message is displayed in accordance with the [USWDS validation component
](https://designsystem.digital.gov/components/validation/)

Given that a user has entered filter criteria for time period
When the criteria is applied 
Then the system displays a filter tag 

Given that a user has applied criteria for time period
When the functionality is displayed
Then the preview data functionality is enabled

Given a user has selected time period (as a minimum)
When the user selects the Preview Data button 
Then system returns results that correspond to the filter criteria (for all filter criteria)

**Validations**
Validate that at least one value exists for the parameter
Validate that the year is in the YYYY format
Validate that the year is 1980, 1985, 1990 or greater than or equal to 1995-latest reporting quarter, 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6734fabc-4885-40b2-8d96-c1f736593491)

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D56](https://epacamd.testquality.com/project/11428/result/2431086/defect/7918).

**Comment by mosesdeeCVP** [comment]
![1614 Bug - AE, Filter Custom Data Download By Time Period and enable data preview.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ebb4da38-6e96-4f62-aa79-18fc50d35636)

**Comment by mosesdeeCVP** [comment]
Test Case Passed
