### ISSUE TITLE
Audit for Record Edit

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1618]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view the audit record on a Monitoring Plan, so that I know the user and time when the last updates were made 

## Acceptance Criteria

Given Monitoring Plan data was updated successfully
When the record is checked back-in
Then the system logs the user name (user ID) and date when the last updates were made 
and displays on the screen (Last updated by: User ID, 8/23/2021)

Notes: Last updated information (user ID and the updated Date) on the Monitoring Plan record. It should only show up when the record is not checked Out 

## Context
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/78493fda-1aad-412f-bec9-b45e6a1dbfed)

## Testing
Test Case: [TC495](https://epacamd.testquality.com/project/11428/plan/22924/test/315533)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1618?planning-poker) with ZenHub @jeffreyaggrey

**Comment by sanleyCVP** [comment]
The following APIs need to be updated to also retrieve auditing information: userid, add_date, update_date
api/monitor-plan-mgmt/plans/{planId}
api/monitor-plan-mgmt/plans/{orisCode}/configurations
api/monitor-plan-mgmt/workspace/plans/{orisCode}/configurations

Is the auditing information limited to the workspace section of a Monitoring plan?

**Comment by mosesdeeCVP** [comment]
![1618 Audit for Record Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c9417e59-ab3f-4794-946a-7e9e2988826d)

![1618 Audit for Record Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/665f26ca-1095-435d-b639-e812c5cc5fb2)

**Comment by mosesdeeCVP** [comment]
Test Passed
