### ISSUE TITLE
Update Mobile-lg (480px) Responsiveness Layout Only 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1623]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 480
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC257](https://epacamd.testquality.com/project/11428/plan/21344/test/295827)

**Comment by mosesdeeCVP** [comment]
Any bugs will be resolved by a bug Ticket:
[Mobile-lg (480px) Responsiveness Layout and Content - Bug #1794](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1794)
