### ISSUE TITLE
Update Widescreen (1400+) Responsiveness Layout 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1627]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 1400 or above
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

## Testing
Test Case: [TC242](https://epacamd.testquality.com/project/11428/plan/21344/test/295187)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1627 Update Widescreen (1400+) Responsiveness Layout.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/70f48f1e-da9d-419c-8aed-163192a43308)

**Comment by mosesdeeCVP** [comment]
Test Passed
