### ISSUE TITLE
Convert View MP Components to Mid Fi Designs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1629]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to view MP Methods using the mid fidelity design
So that I have a better experience 

## Acceptance Criteria
Given a user has accessed MP Components
When it is viewed 
Then it is displayed according to the wireframes 

## Context
https://xd.adobe.com/view/dccab567-3abe-484a-bff7-844d701cd4eb-8999/

See [design decision](https://teams.microsoft.com/l/channel/19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype/tab%3A%3A294ddc5d-ebad-483d-b71c-49e1f7886a14?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7) made on 7/14  

Decision: Decision: When modal CTAs are displayed, then all buttons are right aligned. This diverges from mid fi wire frames, but was agreed to by the team on 7/14.

## Testing
Test Case: [TC239](https://epacamd.testquality.com/project/11428/plan/21289/test/294808)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
@mosesdeeCVP @tdavydets @Qb10 @cvp-alexrobinson See updated context in this feature for decision re: button alignment 

cc: @jwhitehead77 @AllisonFrancis

**Comment by mosesdeeCVP** [comment]
![1629 Convert View MP Components to Mid Fi Designs 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4053e8f5-b3ff-479b-85d7-9325653e7cb6)

**Comment by mosesdeeCVP** [comment]
![1629 Convert View MP Components to Mid Fi Designs 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/defb5a61-1d20-4285-ac69-c55ec045f992)

**Comment by mosesdeeCVP** [comment]
Test Passed
