### ISSUE TITLE
Convert Create/Edit MP Methods to Mid Fi Designs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1637]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to create or edit MP Methods using the mid fidelity design
So that I have a better experience 

## Acceptance Criteria
Given a user has accessed MP Methods
When it is edited
Then it is displayed according to the wireframes 

## Context
https://xd.adobe.com/view/df8c27d8-1cff-494d-946d-7c8cf1a2bdc3-8adf/
https://xd.adobe.com/view/eb6c3176-9c62-46e0-af54-8be9a2771b7a-be3f/

## Testing
Test Case: [TC236](https://epacamd.testquality.com/project/11428/plan/21289/test/294699)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1637 Convert Create-Edit MP Methods to Mid Fi Designs.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/127bf17e-8965-454c-b76c-16d092a545ba)

**Comment by mosesdeeCVP** [comment]
Test Passed
