### ISSUE TITLE
Convert View to Mid Fi (Systems )

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1641]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to view MP systems using the mid fidelity design
So that I have a better experience 

## Acceptance Criteria
Given a user has accessed MP Systems
When it is viewed
Then it is displayed according to the wireframes 

## Context
https://xd.adobe.com/view/dccab567-3abe-484a-bff7-844d701cd4eb-8999/

## Testing
Test Case: [TC237](https://epacamd.testquality.com/project/11428/plan/21289/test/294753)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1641 Convert View to Mid Fi (Systems ).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b6009a79-db05-4319-9713-bb6fad584e9d)

**Comment by mosesdeeCVP** [comment]
Test Passed
