### ISSUE TITLE
Convert View to Mid Fi (Fuel Flows )

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1645]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want to view MP Fuel Flows using the mid fidelity design
So that I have a better experience 

## Acceptance Criteria
Given a user has accessed MP Fuel Flows
When it is viewed 
Then it is displayed according to the wireframes 

## Context
https://xd.adobe.com/view/dccab567-3abe-484a-bff7-844d701cd4eb-8999/

## Testing
Test Case: [TC240](https://epacamd.testquality.com/project/11428/plan/21289/test/294809)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1645 Convert View to Mid Fi (Fuel Flows ).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/10d318c4-6250-44f9-88f7-8c63c9815e24)

**Comment by mosesdeeCVP** [comment]
![1645 Convert View to Mid Fi (Fuel Flows ) 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/43009e6d-accd-424e-b48d-446f95bf6649)

**Comment by mosesdeeCVP** [comment]
Test Passed
