### ISSUE TITLE
Make CAMPD menu and utility nav functional at mobile and tablet breakpoints 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1651]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the to use the CAMPD sub header and utility nav on a mobile or tablet device so that I can navigate CAMPD 

## Acceptance Criteria

Given that a user has accessed CAMPD on a mobile or tablet device  
When the CAMPD  menu and utility nav is displayed 
Then the functionality is in accordance with the [wireframes ](https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/grid/)

 ## Development Notes 
The EASEY design system contains a component that will help with the development of the menu and utility nav at mobile and tablet break points : https://us-epa-camd.github.io/easey-design-system

Updated Menu Items: 
CAMPD Menu: Home, Data, Visualization & Analysis  
Utility Nav: Resources, Help/ Support, Regulatory Partners 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/grid/

**CAMPD MENU** (hamburger icon)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/33deb7d3-bc95-44ec-b083-aef5fb3c016e)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0874d568-af1c-4a3a-b68c-d5accdf1136b)

** CAMPD Menu/ Utility NAV  items** (after selecting the hamburger icon) 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/14104664-ab5c-401c-8f5e-0f018907ba91)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ab30acd9-fead-4c37-b73f-bc676fdffe32)

## Testing
Test Case: [TC524](https://epacamd.testquality.com/project/11428/plan/21283/test/321279)
Tester: @JanellC 

**508 Testing:**

Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Hamburger menu functionality should be prioritized for CAMPD v1.0 due to 508 concerns

**Comment by JanellC** [comment]
TC524 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
