### ISSUE TITLE
Add Audit Info to Wireframes (Need by 8/18)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1652]
Need to add audit info ECMPS wireframes

**Comment by cvp-alexrobinson** [comment]
@JorjaComer — 

Here's the audit info added to the mid-fi wires: https://xd.adobe.com/view/ae9b2cd0-fdfd-419a-ae88-e386a882b174-fbc8/screen/d1e66429-9bd7-4d9c-a078-86dd270c2060

**Comment by JorjaComer** [comment]
@cvp-alexrobinson we are only doing user and date, not time 

Given methods data was successfully updated
When the record is saved
Then the system logs the user and date the the method data was updated
and displays in the methods table next to the method updated

**Comment by cvp-alexrobinson** [comment]
@JorjaComer — Thanks for that catch! Design updated
