### ISSUE TITLE
Auto Collapse Menu Items 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1653]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the CAMPD menu and utility nav to have a click out functionality So that the UI is more user friendly 

## Acceptance Criteria
Given that the CAMPD menu drop down is displayed 
When a user clicks outside of the CAMPD menu 
Then the drop down closes 

Given that the CAMPD utility nav drop down is displayed 
When a user clicks outside of the utility nav 
Then the drop down closes 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Discussed during 4.6 planning. Travis has requested that menu items in the header automatically collapse. 

This functionality should not be a 508 issue 

## Testing
Test Case: [TC610](https://epacamd.testquality.com/project/11428/plan/23473/test/328898)
Tester: @JanellC 

508 Testing:
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC610 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
