### ISSUE TITLE
Link to Data Landing Page From Home Page 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1654]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user
I want to go the data landing page from the CAMPD home page 
So that I can learn more about the data available 

## Acceptance Criteria
Given a user is on the CAMPD home page 
When they click on Data 
Then they are directed to the data landing page 

Given that a user has accessed the CAMPD home page 
When functionality is displayed 
Then the notations are in the proper format (CO2, NOX, SO2) 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
![data](https://user-images.githubusercontent.com/67168611/124821153-5a3e5b80-df3c-11eb-9352-cad85044d644.JPG)

## Testing
Test Case: [TC463](https://epacamd.testquality.com/project/11428/plan/21067/test/312304)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC463 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
