### ISSUE TITLE
Add Smoke Tests to CI/CD Pipeline 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1663]
- Setting up required infrastructure to run smoke tests

**Comment by MaeganWood64** [comment]
- More discussions will occur after specific smoke test outlines are defined

**Comment by MaeganWood64** [comment]
Moving to PI backlog to be addressed in I &P

**Comment by JanellC** [comment]
Will work on this during PI 11 I+P sprint

**Comment by mackenzieharwood** [comment]
First Try
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1112

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1137 
yaml file in emcps-ui

https://github.com/US-EPA-CAMD/easey-testing/pull/296
script in easey-testing

**Comment by mackenzieharwood** [comment]
`java.lang.IllegalStateException: The driver executable does not exist: /home/runner/drivers/chromedriver`

Difficulty getting drivers to the right location and executable

https://github.com/US-EPA-CAMD/easey-ecmps-ui/actions/runs/5405392445/jobs/9820879820

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/315
Multiple tests working - need admin access on github to add secrets for creds

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/315

**Comment by mackenzieharwood** [comment]
Pipeline run:
CI: https://github.com/US-EPA-CAMD/easey-testing/actions/runs/5789672682/job/15691186105
Automated Tests: 
https://github.com/US-EPA-CAMD/easey-testing/actions/runs/5789575574
https://automate.browserstack.com/dashboard/v2/builds/065082828c1a74326e99449fa01be7d62b7a2ff7

Don't input any text when running Automated Test pipeline
