### ISSUE TITLE
Set up Automated Regression Test workflow  

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1664]
Requirements: 

- [x] Add environment flag to existing test method 

- [ ] Identify Existing Tests to be included in the workflow 

- [ ]  Add Automated tests to Regression test workflow

- [ ] Schedule to be run in Dev environment on a weekly basis

**Comment by JanellC** [comment]
@MaeganWood64 Provide list to Yefim and then this ticket can be added to in development

**Comment by JanellC** [comment]
Need confirmation on when to run smoke and regression tests in test and beta
