### ISSUE TITLE
Create Reporting Instructions Page(s) 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1667]
User Story:
As an ECMPS user, I want access to the Reporting Instructions and other important documentation so that I can use them for reference

Acceptance Crietria:
Given I am an ECMPS user on the Resources Screen (Accessed from the utility nav toolbar)
When I click on 'View Reporting Instructions' 
Then I see the following options on the Reporting Instructions Screen: 

**Monitoring Plan Reporting Instructions** Download by the name: ECMPS Monitoring Plan Reporting Instructions 2021 Q4 [https://app.zenhub.com/files/287570343/449899ef-7a75-4129-995c-ae4bf2e347bf/download](https://app.zenhub.com/files/287570343/449899ef-7a75-4129-995c-ae4bf2e347bf/download)

**Part 75 Regulations** (Link: https://www.ecfr.gov/current/title-40/chapter-I/subchapter-C/part-75?toc=1)

**e-CFR** (Link: https://www.ecfr.gov/cgi-bin/text-idx?SID=4002e94719ee5632c5970867e3c7e018&mc=true&tpl=/ecfrbrowse/Title40/40cfr75_main_02.tpl)

**MATS** (Link: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=6952010b8924c119705ba2727c050a07&mc=true&n=pt40.16.63&r=PART&ty=HTML#sp40.16.63.uuuuu)

Added to ticket: Fixing the below on the Resources page:

CDX link opens up site in new tab
Tutorials shows "Coming Soon" page

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/bec32cf2-e93b-4d90-94ef-c35a6576c5be/download](https://app.zenhub.com/files/287570343/bec32cf2-e93b-4d90-94ef-c35a6576c5be/download)

**Comment by dionolympiaCVP** [comment]
Added to ticket: Fixing **Additional Resources** links:
- CDX link opens up site in new tab
- Tutorials shows "Coming Soon" page

**Comment by mosesdeeCVP** [comment]
Test Case: [TC504](https://epacamd.testquality.com/project/11428/plan/22924/test/316216)

**Comment by mosesdeeCVP** [comment]
![1667 Create Reporting Instructions Page.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/697d4721-eb3a-4821-b964-e7653d4a3795)

**Comment by mosesdeeCVP** [comment]
Test Passed
