### ISSUE TITLE
Mid Fi Reporting instruction page design (need by 9/13)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1669]

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit —

Here are the links to the Reporting Instructions page for review:

- [Reporting Instructions](https://xd.adobe.com/view/801c2ce1-0148-463c-a70c-781854f276c6-d54f/)
- [Reporting Instructions (dev)](https://xd.adobe.com/view/02d98aac-21f9-4023-ac3f-883a54c174b4-578a/)

**Comment by cvp-alexrobinson** [comment]
Moving edits to the content document. https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?viewid=18eab565%2D03ba%2D4600%2Da594%2D5eb27c0d799a&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2F6%2DContent%20Templates%2F2%2DUtility%20Menu%2F1%2DResources
