### ISSUE TITLE
ECMPS Help/Support - Responsiveness

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1676]
We want to "provide a usable view of ECMPS at all resolutions above 480 px" while ensuring that priority resolutions of 1024 px and above render correctly.

Responsiveness Wireframes: https://xd.adobe.com/view/8eb81d1f-a9de-4d77-a0e3-dfba5fb75b7b-dbeb/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC378](https://epacamd.testquality.com/project/11428/plan/21344/test/303523)

**Comment by mosesdeeCVP** [comment]
Test Passed
