### ISSUE TITLE
Update Design System 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1677]
Review design system and update as needed

### Assets

- [EASEY Design System Release Notes](https://zeroheight.com/37f47ceee/p/81155e-release-notes)

**Comment by cvp-alexrobinson** [comment]
Addition of a much more robust Icons page and made a few other adjustments and revisions. See the [EASEY Design System Release Notes](https://zeroheight.com/37f47ceee/p/81155e-release-notes)

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa @chrisgitsit @maheese @ibarra-michelle 

Hello,

I've made a number of updates and additions to the [EASEY Design System](https://zeroheight.com/37f47ceee/p/81155e-release-notes). Please let me know if you have any questions.

Best,
Alex

CC @JorjaComer @MoAdeyoju
