### ISSUE TITLE
Mid Fi Design for ECMPS Help/Support (need by 8/23)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1679]
Design for ECMPS support and contact page

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit —

Here are the links to the Help/Support page for review:
- [Help/Support](https://xd.adobe.com/view/d6b82d3b-3cdd-4c28-8097-c9613c59d79f-83eb/)
- [Help/Support (dev)](https://xd.adobe.com/view/8eb81d1f-a9de-4d77-a0e3-dfba5fb75b7b-dbeb/)

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit —

Here are the updated screens for the Help/Support page:

- [Help/Support](https://xd.adobe.com/view/d6b82d3b-3cdd-4c28-8097-c9613c59d79f-83eb/)
- [Help/Support (dev)](https://xd.adobe.com/view/8eb81d1f-a9de-4d77-a0e3-dfba5fb75b7b-dbeb/)

Please let me know if you have any questions.
