### ISSUE TITLE
Finish ECMPS Responsiveness 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1680]
Compete the design for ECMPS responsiveness 

### Developer Assets
- [Responsive Screens](https://xd.adobe.com/view/ae9b2cd0-fdfd-419a-ae88-e386a882b174-fbc8/flow)
- [Icons Used](https://xd.adobe.com/view/18fc4a46-25d6-4e9e-879b-612414171b2a-4daf/)
- [Little Menus](https://xd.adobe.com/view/e46682fb-b5f3-44d9-8763-ec5cc4d8c461-b135/)

**Comment by cvp-alexrobinson** [comment]
_ATTN @Qb10 @tdavydets @jwhitehead77_ 

**ECMPS Responsiveness and Layout Updates**
[Here are the screens](https://xd.adobe.com/view/ae9b2cd0-fdfd-419a-ae88-e386a882b174-fbc8/flow) for ECMPS responsiveness.

**Notes**
There are a couple menus introduced in these updated medium-fi wireframes.


![Screen Shot 2021-07-15 at 5.05.41 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/9d545c85-8516-4271-8202-bf5f5d9e05a5)
☝️ The first menu should use the [Utility Menu design pattern from the CAMPD side](https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/)


![Screen Shot 2021-07-15 at 5.05.54 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/d1840ea6-1f4b-42ec-b367-37159d5e20ad)
☝️ The second menu should use the [Main Menu design pattern from the CAMPD side](https://xd.adobe.com/view/02db92b0-4865-4d96-8d4f-e869f53e4d80-5788/)


![Screen Shot 2021-07-15 at 5.09.16 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/9446a2e3-88e4-46f8-ac96-99bb7c5f2c43)
☝️ The other two menus (Profile and Tabs) can use the [new "Little Menu" pattern](https://xd.adobe.com/view/e46682fb-b5f3-44d9-8763-ec5cc4d8c461-b135/)—which I tried to model off of the [React Menu component](https://material-ui.com/components/menus/).

Please let me know if you have any questions.

Best,
Alex

_CC @JorjaComer @MoAdeyoju_
