### ISSUE TITLE
CAMPD About Page Design (need by 8/9)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1681]

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa —

Hello,

Below are the screens for the About CAMPD page designs.
- [About CAMPD](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541)
- [About CAMPD (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541)

CC @JanellC @JorjaComer @MoAdeyoju @addisgmichael
