### ISSUE TITLE
CAMPD Related Resources Design (need by 8/16)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1683]
### Assets
- [Related Resources Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1407&scaling=contain&page-id=392%3A1254)
- [Related Resources Page (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1407)

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa —

Hello,

Here is the link to the CAMPD [Related Resources Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1407&scaling=contain&page-id=392%3A1254). Please note that CVP is still reviewing content, so there may be slight updates to titles and content.

Best,
Alex

CC @MoAdeyoju @JorjaComer @nsameerun @JanellC @addisgmichael
