### ISSUE TITLE
CAMPD FAQ Page Design (need by 8/16)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1684]
### Assets
- [FAQs Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=397%3A2656&scaling=contain&page-id=397%3A2503)
- [FAQs Page (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=397%3A2656)

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa —

Hello,

Here is the link to the CAMPD [FAQs Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=397%3A2656&scaling=contain&page-id=397%3A2503). Please note that CVP is still reviewing content, so there may be slight updates to titles and content.

Best,
Alex

CC @MoAdeyoju @JorjaComer @nsameerun @JanellC @addisgmichael
