### ISSUE TITLE
CAMPD Glossary Page Design (need by 9/13)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1685]

**Comment by AllisonFrancis** [comment]
@tlageman-epa 
Here are the links to the Glossary screens.
[Glossary](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910&scaling=min-zoom&page-id=695%3A2909&starting-point-node-id=695%3A2910)
[Glossary (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910)
Please let me know if you have any questions.
Thanks

**Comment by AllisonFrancis** [comment]
Have made changes that were discussed on 9/13 in wireframes
