### ISSUE TITLE
CAMPD Tutorials Page Design (Need by 9/13)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1686]

**Comment by AllisonFrancis** [comment]
@tlageman-epa
Here are the links to the Tutorial screens.
[Tutorials](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=704%3A4725&scaling=min-zoom&page-id=701%3A3709&starting-point-node-id=704%3A4725)
[Tutorials (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=704%3A4725)
Please let me know if you have any questions.
Thanks

**Comment by AllisonFrancis** [comment]
Have made changes and corrections that were discussed on 9/13 in wireframes
