### ISSUE TITLE
CAMPD Site Map Page (need by 9/13)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1687]

**Comment by AllisonFrancis** [comment]
@tlageman-epa
Here is the link to the Site Map with the latest updates.
[Site Map](https://www.figma.com/proto/oH4mOXuXImz0q1E9qTkz1o/Site-Maps?node-id=247%3A1058&scaling=contain&page-id=247%3A1057)
[Site Map (dev)](https://www.figma.com/file/oH4mOXuXImz0q1E9qTkz1o/Site-Maps?node-id=247%3A1058)
Please let me know if you have any questions.
Thanks
