### ISSUE TITLE
Enter or Update Monitoring Plan Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#169]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

-User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
Enter or update monitoring plan data so that it complies with EPA regulations and can meet submission requirements 

Build out functionality to:
Create Monitoring Plan and enter data
Or, select an existing Monitoring Plan and update data
Then, validate front-end form data

Formatting checks, range checks, completeness checks, data type checks

Dependencies:
Need updated tables imported
UI updates
Requirements 

UI validation

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
[Monitoring Plan Requirements Package](https://teams.microsoft.com/_#/files/unknown?threadId=19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype&ctx=channel&context=Monitoring%2520Plan%2520Requirements%2520Package&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FGeneral%252FAnalysis%252C%2520User%2520Research%2520and%2520Design%252FAnalysis%252FEASEY%2520In%252FMonitoring%2520Plan%2520Requirements%2520Package)

**Comment by karenhwwoo** [comment]
Accommodated in other feature tickets.
