### ISSUE TITLE
Design for Emissions Submission Progress Bar (need By 9/20)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1690]
## Context
Currently displayed on AMPD home and Query page (ECMPS Support page is out of scope for now). Will need to be displayed on CAMPD home and CDD page (at bottom)
Displays # of expected submissions and #completed with a time/date stamp for last update of progress
Bar is displayed on 1st day of reposting period until 7 days after end of reporting period 
Bar will need to pull progress from current ECMPS data until EASEY In goes live in prod 
Per Mike H will implement as shared component (may need to display elsewhere in future). 

**AMPD Emissions Progress Bar** 

![Status bar (002).PNG](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c36c7399-fdc2-49aa-95f9-b002fc2b9fd8)

the requirements for the text would be as shown in the screenshot
-	Year and Quarter of emission submissions
-	% of submissions received
-	The Last updated text

**Comment by JanellC** [comment]
During the tech team product  design meeting on 9/8, the team decided to move this ticket to PI-6. Team will produce hi-fi design for this. Lo-fi is not needed. Conversations about the emissions progress bar will continue to happen during the CAMPD Product Design sessions until the component is implemented.

**Comment by AllisonFrancis** [comment]
Here is the XD link for the discussion of the Submission Progress Bar and Spinner Options for global use.
https://xd.adobe.com/view/604a56eb-2df4-4f57-b9a0-569dc3ea2505-3519/

**Comment by AllisonFrancis** [comment]
Travis said that the progress bar only needs the label and time stamp above. No other language is needed in the ui. 
Jason will work with Travis to get more info from ERG as to where the data lives in the files that were sent to CVP. That data is needed to generate the percentage.
