### ISSUE TITLE
SPIKE: Determine options for other data types filter logic

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1693]
## Research Goals:

both compliance

Dependency: need access to code that is implementing filter logic on AMPD 

## Background: 
Research adding filter logic to Allowance and Compliance data types

**Comment by akaashmanan** [comment]
Waiting on ERG for their code

**Comment by sdhawan16** [comment]
[SPIKE 1693 Filter Logic Emissions Compliance - EPA CAMPD - v1.0.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7001265/SPIKE.1693.Filter.Logic.Emissions.Compliance.-.EPA.CAMPD.-.v1.0.docx)

**Comment by sdhawan16** [comment]
[SPIKE 1693 Filter Logic Emissions Compliance - EPA CAMPD - v1.0.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7001311/SPIKE.1693.Filter.Logic.Emissions.Compliance.-.EPA.CAMPD.-.v1.0.docx)
