### ISSUE TITLE
Design for filter logic warning message

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1695]
- [ ] remove time period
- [ ] change time period
- [ ] Filter criteria updated (needs to be 508 compliant around data updated on screen for user awareness)

## Context 
For Emissions data:

Must select time period before logic will be engaged

Filter logic will narrow filter criteria based on subsequent selections (criteria can still be selected in any order)

Filter criteria update dynamically as selections are made (upon Apply)
the system will delete any non applicable selections
Remove them from the filter lists if a combo box
Grey out in check box lists
Update filter tags

If time period is deleted, then
the system displays a warning message
clears previously selected criteria
*greys out other criteria

If years (in time period) are changed, then
the system displays a warning message (re: years)
clears previously selected criteria
*greys out other criteria

**Comment by JanellC** [comment]
Per backlog refinement on 9/8 this ticket is no longer needed. The team will utilize the warning message from the ECMPS side.
