### ISSUE TITLE
Bug: CAMPD Data Landing Page

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1696]
## Test Case
Test Case: [TC223](https://cvpcorp.testquality.com/project/11428/plan/21067/test/294196)

## Steps to Reproduce
| Step | Action  | Expected | Pass/Fail |
|---|---|---|---|
| 1 | Navigate to CAMPD Data Landing Page  | The main page content is displayed in accordance with the wireframes at the specified resolution | Fail |

### Actual Results

1.The Static Datasets section should be renamed to Bulk Data Files
 

2. The first sentence under Bulk Data Files should change to "For larger data downloads, bulk data files provide access to prepackaged datasets of..."

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/eb6afc65-6a10-4bb6-b9bf-26276ff22ce7)

3. The paragraph CAMPD's data section serves all......should be a paragraph in the class Lead instead of a heading. Refer to [EASEY Design System ](https://zeroheight.com/37f47ceee/p/546f75-typography)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/5af1fc2c-eee3-420c-8e93-423ae4b73197) 

4. Padding between the header and main content is inconsistent with the wireframes. Increase padding by 50% 

CAMPD
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e79c5ef7-195d-4431-9b8c-38bf4dc1e210)
 
Wireframes 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/fe3a44af-90b5-4714-9829-ee54148feb8b)

5. Padding between the footer and main content is inconsistent with the wireframes. Increase padding by 50%. 
 

CAMPD
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e064ac5d-abdb-4a1e-a719-6673c2aa2645)

Wireframes
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/10b0dde9-8a80-4b77-b9dc-99e1ac5a1139)

### User Story
CAMPD Data Landing Page #1519

As a CAMPD user I want to view the data landing page so that I can familiarize myself with the different data tools

### Acceptance Criteria
Given that a user has navigated to the CAMPD data landing page
When the page renders
Then its is in accordance with wireframes

Note: Static Datasets will now be "Bulk Data Files". The first sentence under the blurb should change to "For larger data downloads, bulk data files provide access to prepackaged datasets of...". Call to action label can stay the same.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D57](https://epacamd.testquality.com/project/11428/result/2438385/defect/7963).

**Comment by tlageman-epa** [comment]
@JanellC I know we had discussed this but maybe it wasn't captured in the cards. The "Data" box title on the CAMPD homepage should also link to the Data Landing page. I'm not sure if that can be added here. Thx and let me know if you have any questions.

**Comment by JanellC** [comment]
@tlageman-epa It looks like the work to make "Data" box title on the CAMPD homepage link to the Data landing page is captured in a separate issue.  The ticket " Link to Data Landing Page From Home Page #1654 " addresses this.

**Comment by JanellC** [comment]
Defect D57 resolved
