### ISSUE TITLE
Create MP Defaults Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1698]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want to create MP default data so that I can add a default section

Acceptance Criteria:
Given the user has selected Defaults in the section field
When the system displays an option to Create monitoring defaults data (Create Default)
Then the user is able to enter data for all required fields
And create new monitoring defaults data

Parameter: dropdown
Default Value: Text
Units of Measure: dropdown
Purpose: dropdown
Fuel Code: dropdown
Operating Condition: dropdown
Source of Value: dropdown
Group ID: Text
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, required, format mm/dd/yyyy
End Time: Text, required, format hh

Dev Notes: For all drop-downs, the default display when no value is selected is **-- Select a value --**

Given the user has added monitoring default data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the MP tab

Given the user has added information for a new monitoring default
When the user chooses not to create one (Cancel)
Then the user is navigated back to the MP tab

## Context
[See page 92 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC383](https://epacamd.testquality.com/project/11428/plan/21902/test/303539)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1698?planning-poker) with ZenHub @mosesdeeCVP @jeffreyaggrey @tdavydets @Qb10

**Comment by mosesdeeCVP** [comment]
![1698 Create MP Defaults Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/59010a92-3119-4b96-8b52-711f5e58d9ab)

**Comment by mosesdeeCVP** [comment]
Test Passed
