### ISSUE TITLE
Validate Monitoring Plan Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#170]
Original estimate: 8

## Feature Benefit
Validate monitoring plan data using existing EPA check engine to ensure the data complies with EPA regulations.  

FOR BETA: 

1. Evaluate a monitoring plan with no errors
2. Evaluate a monitoring plan with 1 error in each of the most common categories
3. View the evaluation report
4. Update the status of the monitoring plan 

- 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
[Monitoring Plan Requirements Package](https://teams.microsoft.com/_#/files/unknown?threadId=19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype&ctx=channel&context=Monitoring%2520Plan%2520Requirements%2520Package&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FGeneral%252FAnalysis%252C%2520User%2520Research%2520and%2520Design%252FAnalysis%252FEASEY%2520In%252FMonitoring%2520Plan%2520Requirements%2520Package)

Plan is checked out 
User sends for evaluation
System will evaluate the last set of saved changes, does not need to be checked back in to evaluate 
System calls check engine
System locks whole plan for evaluation (no one can make changes until eval is complete)
Display message that process is in progress
User can cancel 
MP remains checked out/locked while eval process is running (even if 15 min window expires)
When eval completed:
*check MP back in and unlock 
*popup notification eval is complete
*send notification email to user that submitted (includes eval report in the body of the email)
User will need to log in to view eval report from link 
User can view eval report within ECMPS application 
User can export eval report (can be handled via "print to PDF" in browser) from within the application 

Assumptions:
User will have CDX account that includes an email address
ECMPS will be able to consume the email address to send notification email

**Comment by david-cvp** [comment]
Split feature Epic:

Emissioners UI design #369 (estimate: 40)
Form validation #169 (estimate: 20)
Import validation #168 (estimate: 20)
Check engine validation #170 (estimate: 100)
- Build test harness for check engine
- Dwayne is verifying that .NET core check engine is valid
