### ISSUE TITLE
Edit MP Location Attributes Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1703]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to edit MP Location Attributes information so that I can update the data 

Acceptance Criteria:
_Given_ the user has selected **Location Attributes and Relationships** from the sections field
_When_ the user selects Edit
_Then_ the system displays the edit modal
_And_ the user can edit Location Attributes data

Duct Indicator: Radio-button
Bypass Indicator: Radio-button
Ground Elevation: Text
Stack Height: Text
Material Code: Drop-down
Shape Code: Drop-down
Cross Area Flow: Text
Cross Area Stack Exit: Text
Start Date: date picker, format mm/dd/yyyy
End Date: date picker, format mm/dd/yyyy

Given the user has edited Location Attributes data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Location Attributes and Relationships data screen

Notes: Warning message to pop up when a user updates/adds data and closes the modal without saving the updates.
- Edit and Create are only applicable to MP Location Attributes. View is applicable to both Location Attributes and Relationships.

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code/content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[Refer to page 25 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Tester: @mosesdeeCVP 
Test Case: [TC511](https://epacamd.testquality.com/project/11428/plan/22772/test/316519)

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1703 Edit MP Location Attributes Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/81977abe-4cb2-43c2-a5f9-2414e1eb5150)

**Comment by mosesdeeCVP** [comment]
Test Passed
