### ISSUE TITLE
Create MDM Endpoints for Formula Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1704]
Create MDM endpoint for MP Formula Data :

Formula Code: Dropdown

**Comment by mosesdeeCVP** [comment]
Test Case: [TC389](https://epacamd.testquality.com/project/11428/plan/20423/test/303717)

**Comment by mosesdeeCVP** [comment]
![1704 Create MDM Endpoints for Formula Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/242ba3d3-f830-41eb-a9a8-431fb70a903c)

**Comment by mosesdeeCVP** [comment]
Test Passed
