### ISSUE TITLE
Edit MP Formula Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1705]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to edit MP Formula data, so that I can update the data 

Acceptance Criteria:
_Given_ the user has selected Formula from the Sections dropdown
_When_ the user selects Edit
_Then_ the system displays the edit modal
_And_ the user can edit Formula data 

Formula ID: Text
Parameter: Dropdown
Formula Code: Dropdown
Formula: Text  
Start Date: date picker, format mm/dd/yyyy
Start Time: Text, hh
End Date: date picker, format mm/dd/yyyy 
End Time: Text, hh

Given the user has edited Formula data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the landing view for Formula

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Refer to page 62 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC391](https://epacamd.testquality.com/project/11428/plan/20423/test/303732)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Passed
