### ISSUE TITLE
Edit Monitoring Span data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1706]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want to edit the Monitoring span data for non-flow and flow spans so that I can update the data 

Acceptance Criteria:
_Given_ the user selects Span, Range and Formulas from the Sections dropdown
_When_ the user selects Edit
_Then_ the system displays the edit modal
_And_ the user can edit Monitoring span data 

Component Type: dropdown
Span Scale: dropdown
Span Method: dropdown
MEC Value: Text
MPC Value: Text
MPF Value: Text
Span Value: Text
Full Scale Range: Text
Span Units of Measure: dropdown
Scale Transition Point: Text
Default High Range: Text
Flow Span Value: Text
Flow Full Scale Range: Text
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, required, format mm/dd/yyyy
End Time: Text, required, format hh

Dev Notes: For all drop-downs, the default display when no value is selected is **-- Select a value --**

Given the user has edited Monitoring span data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Span homescreen

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[Refer to page 105 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC377](https://epacamd.testquality.com/project/11428/plan/20424/test/303521)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1706?planning-poker) with ZenHub @jeffreyaggrey @mosesdeeCVP @Qb10 @tdavydets

**Comment by mosesdeeCVP** [comment]
A bug was found and a ticket was made [Unable to edit "Scale Transition Point" in Span #2045](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2045)

**Comment by mosesdeeCVP** [comment]
Other than the Bug the test has passed

**Comment by mosesdeeCVP** [comment]
![1706 Edit Monitoring Span data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bd8d3621-bc90-41b8-aac4-4c2aebca0a0b)
![1706 Edit Monitoring Span data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b009c2c7-8012-4548-9d6a-b73cd3d59203)
