### ISSUE TITLE
Create Monitoring Span Data 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1707]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want to create monitoring span data so that I can add non-flow span and flow span data

Acceptance Criteria:
Given the user has selected **Span, Range and Formulas** from the Sections dropdown
When the system displays an option to Create monitoring spans data (Create Span)
Then the user is able to enter data for all required fields
And create new monitoring span data

Component Type: dropdown
Span Scale: dropdown
Span Method: dropdown
MEC Value: Text
MPC Value: Text
MPF Value: Text
Span Value: Text
Full Scale Range: Text
Span Units of Measure: dropdown
Scale Transition Point: Text
Default High Range: Text
Flow Span Value: Text
Flow Full Scale Range: Text
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, required, format mm/dd/yyyy
End Time: Text, required, format hh

Dev Notes: For all drop-downs, the default display when no value is selected is **-- Select a value --**

Given the user has added monitoring span data
When the user chooses to save and close
Then the data is saved 
And the modal closes

Given the user has added information for a new monitoring span
When the user chooses not to create one (Cancel)
Then the user is navigated back to the Span homepage

## Context
Reporting Instructions: [See page 105 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC375](https://epacamd.testquality.com/project/11428/plan/20424/test/303518)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1707 Create Monitoring Span Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f596ea44-0064-41c4-8675-98a7333fd96a)

![1707 Create Monitoring Span Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4faf737e-f346-4e1f-9e2e-6581d21e8282)

**Comment by mosesdeeCVP** [comment]
All steps passed the test excepts that "Scale Transition Point" does not save data. A bug ticket has been made:
[Unable to edit "Scale Transition Point" in Span #2045](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2045)
