### ISSUE TITLE
Create MP Rectangular Duct WAFs Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1708]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create new Rectangular Duct WAFs Data, so that I can add new data 

Acceptance Criteria:
_Given_ the user has selected **Rectangular Duct WAFs Data** from the Sections dropdown
_When_ the user chooses to add a new Rectangular Duct WAFs Data (Create Rectangular Duct WAF)
_Then_ the system displays the create modal
_and_ the user can add new Rectangular Duct WAFs Data

WAF Determination Date: date picker, format mm/dd/yyyy
WAF Start Date: date picker, format mm/dd/yyyy
WAF Start Time: Text, hh
WAF Method: dropdown
WAF Value: Text
Number of Test Runs: Text
Number of Traverse Points WAF: Text
Number of Test Ports: Text
Number of Traverse Points Reference: Text
Duct Width: Text
Duct Depth: Text
WAF End Date: date picker, format mm/dd/yyyy
WAF End Time: Text, hh

Given the user has added Rectangular Duct WAFs Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the landing page for Rectangular Duct WAFs 

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 115 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC415](https://epacamd.testquality.com/project/11428/plan/22357/test/308248)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1708 Create MP Rectangular Duct WAFs Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c3ca5521-d615-47b3-8b52-b7d0fa939c47)

**Comment by mosesdeeCVP** [comment]
Test Passed
