### ISSUE TITLE
Edit Rectangular Duct WAFs Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1709]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to edit Rectangular Duct WAFs data so that I can update the data 

Acceptance Criteria:
_Given_ the user has selected **Rectangular Duct WAFs** from the sections dropdown
_When_ the user selects Edit
_Then_ the system displays the edit modal
_And_ the user can edit Rectangular Duct WAFs data

WAF Determination Date: date picker, format mm/dd/yyyy
WAF Start Date: date picker, format mm/dd/yyyy
WAF Start Time: Text, hh
WAF Method: dropdown
WAF Value: Text
Number of Test Runs: Text
Number of Traverse Points WAF: Text
Number of Test Ports: Text
Number of Traverse Points Reference: Text
Duct Width: Text
Duct Depth: Text
WAF End Date: date picker, format mm/dd/yyyy
WAF End Time: Text, hh

Dev Notes: For all drop-downs, the default display when no value is selected is -- Select a value --

Given the user has edited Rectangular Duct WAFs Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Rectangular Duct WAFs Data landing page

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[Refer to page 115 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC416](https://epacamd.testquality.com/project/11428/plan/22357/test/308424)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1709 Edit Rectangular Duct WAFs Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ff10b488-5c00-4efc-be58-1d804a0658d9)

**Comment by mosesdeeCVP** [comment]
Test Passed
