### ISSUE TITLE
Create MP Load Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1710]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create Monitoring Load data so that I can add new Monitoring Load information

Acceptance Criteria: 
_Given_ the user has selected Loads in the section field
_When_ the system displays an option to Create new Loads data (Create Load)
_Then_ the user is able to enter data for all required fields
And create new Load data

Maximum Load Value: Text
Maximum Load Units of Measure: drop-down
Lower Operation Boundary: Text
Upper Operation Boundary: Text
Normal Level: drop-down (Operating Level Code)
Second Level: drop-down (Operating Level Code)
Second Normal Indicator: Yes/No Radiobutton
Load Analysis Date: date picker, format mm/dd/yyyy
Begin Date: date picker, format mm/dd/yyyy
Begin Time: Text, format hh
End Date: date picker, format mm/dd/yyyy
End Time: Text, format hh

Dev Notes: For all drop-downs, the default display when no value is selected is **-- Select a value --**

Given the user has added MP load data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Loads home screen

Given the user has added information for a new load
When the user chooses not to create one (Cancel)
Then the user is navigated back to the MP tab

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Refer to page 118 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: [TC388](https://epacamd.testquality.com/project/11428/plan/21921/test/303716)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1710 Create MP Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e6961a75-d2b0-401f-9535-5c7c07890749)

**Comment by mosesdeeCVP** [comment]
Test Passed
