### ISSUE TITLE
Edit MP Load Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#1711]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to edit MP Load data so that I can update the data 

Acceptance Criteria:
_Given_ the user has selected Load in the sections field
_When_ the user selects Edit
_Then_ the system displays the edit modal
_And_ the user can edit MP Load data 

Maximum Load Value: Text
Maximum Load Units of Measure: drop-down
Lower Operation Boundary: Text
Upper Operation Boundary: Text
Normal Level: drop-down (Operating Level Code)
Second Level: drop-down (Operating Level Code)
Second Normal Indicator: Yes/No Radiobutton
Load Analysis Date: date picker, format mm/dd/yyyy
Begin Date: date picker, required, format mm/dd/yyyy
Begin Time: Text, required, format hh
End Date: date picker, format mm/dd/yyyy
End Time: Text, format hh

Dev Notes: For all drop-downs, the default display when no value is selected is -- Select a value --

Given the user has edited MP Load data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Loads homescreen

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[Refer to page 118 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

## Testing
Test Case: @mosesdeeCVP 
Tester: [TC387](https://epacamd.testquality.com/project/11428/plan/21921/test/303715)

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1711?planning-poker) with ZenHub @mosesdeeCVP @tdavydets @Qb10 @jeffreyaggrey

**Comment by mosesdeeCVP** [comment]
![1711 Edit MP Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/17f7558b-6848-4fbd-bd9e-6f4ce06eccd4)

**Comment by mosesdeeCVP** [comment]
Test Passed
