### ISSUE TITLE
View MP Unit Capacity Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1722]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production MP Unit Capacity Data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Unit Information** from the Sections dropdown
When the MP Unit Capacity Data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Commercial Operation Date
Operation Date
Boiler/Turbine Type
Boiler/Turbine Begin Date
Boiler/Turbine End Date
Maximum Hourly Heat Input Capacity
Start Date
End Date

Given a user is viewing MP Unit Capacity Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 15): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC446](https://epacamd.testquality.com/project/11428/plan/22363/test/310079)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1722 View MP Unit Capacity Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/949fd8bf-6028-452a-bd89-584ee3af7597)

**Comment by mosesdeeCVP** [comment]
![1722 View MP Unit Capacity Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d6964065-cf1b-4b7b-837c-94ea129304db)

**Comment by mosesdeeCVP** [comment]
Test Passed
