### ISSUE TITLE
Edit Systems data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1733]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As a user, I want to edit a Systems data so that I can update the data 

Acceptance Criteria:
_Given_ the user has selected Systems in the section field
_When_ the user selects Edit
_Then_ the system displays the edit modal
_and_ the user can edit systems data 

System ID: text, required
System Designation: drop down, required - needs MDM endpoint
System Type: drop down, required - needs MDM endpoint
Fuel Type: drop down, required - needs MDM endpoint
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, required, format mm/dd/yyyy
End Time: Text, required, format hh

[Refer to page 50 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

Given the user has edited systems data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the methods table 

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Design Wiki ](https://teams.microsoft.com/l/channel/19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype/tab%3A%3A294ddc5d-ebad-483d-b71c-49e1f7886a14?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

## Testing
Test Case: [TC356](https://epacamd.testquality.com/project/11428/plan/19812/test/299584)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1733 Edit Systems data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b75c6ed-d224-4d76-9f87-55b51075d88b)

**Comment by mosesdeeCVP** [comment]
All is working well excepts that System Type is not currently editable. A ticket will be created for this bug.

**Comment by mosesdeeCVP** [comment]
Bug ticket created:  [Edit System Type in Monitoring Systems #2006](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2006)

**Comment by mosesdeeCVP** [comment]
All steps passed, except that the System Type is not editable. Bug has been created and story is now closed.
