### ISSUE TITLE
SPIKE: Research how to implement Owner/Operator API filter 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1755]
Filter needs to return owner and operators for each data type (Account, holdings, transactions, etc.). Data differs between data types. 

Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Add endpoint to Facilities API to return list of Owner/Operators

From: Lageman, Travis
Sent: Wednesday, June 2, 2021 3:25 PM
To: jasonwhitehead@cvpcorp.com; sejaldhawan@cvpcorp.com; juniesenthilkumar@cvpcorp.com
Cc: Heese, Michael Heese.Michael@epa.gov
Subject: FW: Question about Owner/Operators in database

From: Mark Hayward Mark.Hayward@erg.com
Sent: Saturday, May 15, 2021 10:52 AM
To: Lageman, Travis Lageman.Travis@epa.gov; Ann Albrecht Ann.Albrecht@erg.com
Cc: Stetsyuk, Karina Stetsyuk.Karina@epa.gov; Gill, Sandeep Gill.Sandeep@epa.gov; Desantis, Laurel Desantis.Laurel@epa.gov
Subject: RE: Question about Owner/Operators in database

Travis,

Here is a summary of how AMPD currently populates owner/operator information for the reports.

I have also included details of the tables and data that store the owner/operator information.

Let me know if you have additional questions, or would like to discuss further.

Mark

Account Info
• Includes owners and operators are in separate columns
• Populated from ACCOUNT_OWNER_DIM
Allowance Holdings
• Includes owners and operators in a single column
• Populated from ACCOUNT_FACT.OWN_DISPLAY
o Using ACCOUNT_OWNER_DIM would allow for separation of owners and operators into separate columns
Allowance Transactions
• Includes only owners (separate columns for transferor owners and transferee owners)
• Populated from TRANSACTION_OWNER_DIM
Compliance (allowance based)
• Includes owners and operators in separate columns
• Populated from OWNER_DISPLAY_FACT
Compliance (emissions based)
• Includes owners and operators in separate columns
• Populated from OWNER_YEAR_DIM
Emissions (assuming same for hourly to annual?)
• Includes owners and operators in separate columns
• Populated from OWNER_YEAR_DIM
Facility Attributes
• Includes owners and operators in separate columns
• Populated from OWNER_YEAR_DIM

OWNER_YEAR_DIM:
• Contains individual records for each unique combination of unit+year+owner+type
• Includes all owners/operators active during the year
• Data is used to populate OWNER_DISPLAY_FACT
o Owners in OWN_DISPLAY
o Operators in OPR_DISPLAY
• Includes owners and operators linked to units in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)

ACCOUNT_OWNER_DIM:
• Contains individual records for each unique combination of account+program+owner+type
• Includes all active owners/operators
• Data is used to populate ACCOUNT_FACT.OWN_DISPLAY, including both owners and operators
• For unit accounts
o Includes owners/operators linked to the unit in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
• For facility accounts
o Includes owners/operators linked to any unit at the facility in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
o Only loads program-specific records for programs active for the facility
 Using data from ACCOUNT_PROGRAM_SS (CAMDBSP_CAMDAMS.ACCOUNT_PROGRAM)
• For OTC/NBP accounts that are NOT unit accounts
o Includes owners linked to the account in NTACCT_OWNER_SS (CAMDBSP_CAMDNATS.TACCT_OWNER)
 May be companies or people
• For all other accounts that are NOT unit or facility accounts
o Includes owners linked to the account in ACCOUNT_OWNER_SS (CAMDBSP_CAMDAMS.ACCOUNT_OWNER)
 May be companies or people

TRANSACTION_OWNER_DIM:
• Contains individual records for each unique combination of transaction+program+account+owner+type
• Includes only those owners/operators active on the transaction date
• Data is used to populate TRANSACTION_FACT.BUY_OWN_DISPLAY_NAME and SELL_OWN_DISPLAY_NAME, including ONLY owners
• For unit accounts
o Includes owners linked to the unit in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
• For facility accounts
o Includes owners linked to any unit at the facility in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
• For OTC/NBP accounts that are NOT unit accounts
o Includes owners linked to the account in NTACCT_OWNER_SS (CAMDBSP_CAMDNATS.TACCT_OWNER)
 May be companies or people
• For all other accounts that are NOT unit or facility accounts
o Includes owners linked to the account in ACCOUNT_OWNER_SS (CAMDBSP_CAMDAMS.ACCOUNT_OWNER)
 May be companies or people

From: Lageman, Travis Lageman.Travis@epa.gov
Sent: Wednesday, May 12, 2021 4:48 PM
To: Ann Albrecht Ann.Albrecht@erg.com; Mark Hayward Mark.Hayward@erg.com
Cc: Stetsyuk, Karina Stetsyuk.Karina@epa.gov; Gill, Sandeep Gill.Sandeep@epa.gov; Desantis, Laurel Desantis.Laurel@epa.gov
Subject: Question about Owner/Operators in database

CAUTION: Don't open links or attachments unless you recognize the sender and know they are safe.
Hi Mark and Ann,

In a recent review of data elements/tables in the database, we noticed there are multiple tables with owner/operator info. This gets a little confusing for allowance holdings information. For example, Allowance Holdings returns an “Owner” field but it contains both owner and operators, while all other AMPD datasets appear to have distinct “Owner” and “Operator” fields (although I’m not entirely sure about transactions if they also return just owner info or combine owner/operator and don’t specify that as in the holdings dataset).

Our goal is to use only distinct owner and operator fields in all the datasets we return in the new AMPD as opposed to a joined one like in Allowance Holdings. Could you help me understand the best place to pull this data from for each of the following datasets that contain owner and operator information? I recognize there may be some differences since emissions info is unit based whereas account info/compliance is facility/account based.

Account Info
Allowance Holdings
Allowance Transactions
Compliance (allowance based)
Compliance (emissions based)
Emissions (assuming same for hourly to annual?)
Facility Attributes
It may also be helpful to understand how the relevant owner/operator database tables you identified in the AMPD data dictionary relate to one another since they share a lot of the same owner/operator info, and often have the same data column name but tend to be formatted differently

Database Table Names: ACCOUNT_FACT, ACCOUNT_OWNER_DIM, OWNER_DISPLAY_FACT, OWNER_YEAR_DIM, TRANSACTION_OWNER_DIM, UNIT_COMPLIANCE_DIM, TRANSACTION_FACT
Data Column Names: OWN_DISPLAY, OPR_DISPLAY, BUY_OWN_DISPLAY_NAME, SELL_OWN_DISPLAY_NAME
Hope I made sense and that you can shed some light. Let me know if I can try to clarify further.

Thanks as always! I know you all have a lot with the RCU.

Best,

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

**Comment by sdhawan16** [comment]
Will create 4 different endpoints to return owner/operator info for allowance holdings, allowance transactions, compliance and accounts data. Data will be pulled from ACCOUNT_OWNER_DIM, TRANSACTION_OWNER_DIM, and OWNER_YEAR_DIM. 

Outcome of spike documented below (updated 8/3/21): 

[SPIKE 1755 Owner Operator Outcome - EPA CAMPD - v1.1.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6925711/SPIKE.1755.Owner.Operator.Outcome.-.EPA.CAMPD.-.v1.1.docx)

**Comment by sdhawan16** [comment]
[SPIKE 1755 Owner Operator Outcome - EPA CAMPD - v1.1.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6925698/SPIKE.1755.Owner.Operator.Outcome.-.EPA.CAMPD.-.v1.1.docx)
Updated endpoints
