### ISSUE TITLE
Unit Fuel Filter - EPA report 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1760]
## Required Fix 
| Page/ Screen | Description of Issue  | Test(s) | 508 Standard(s) | WCAG 2.0 Standard(s) |
|---|---|---|---|---|
|     Unit Fuel Filter    |     Coal and Coal (C)   checkboxes may lead to confusion. It may not be clear which to select. A   visual tag for these subgroups such as “All Coal”, “All Gas” might be   clearer.    |     5B, 5C    |     1194.21(l),   1194.22(n)    |     1.3.1, 2.4.6    |

## Context 

Refer to [EASEY July 2021 Test Report](https://teams.microsoft.com/l/file/BCF65D75-C055-4EE0-BBC6-E8800F8B141F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F5-UI%20Design%2F02%20508%20and%20Accessibility%2FEASEY%20July%202021%20Test%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f50fe08a-32a1-4df2-8429-06d778383404)

**Comment by aprematta** [comment]
Passes testing
