### ISSUE TITLE
Filter Tags-EPA report 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1761]
## Required Fix
| Page/ Screen | Description Of Issue  | Test(s) | 508 Standard(s) | WCAG 2.0 Standard(s) |
|---|---|---|---|---|
|     Custom Data   Downloads    |     The filter   elements include controls to both modify a filter or remove it.  The button(s) to modify a filter should   include tagging to indicate that this is the purpose of the button.           See Figure 3    |     6A    |     1194.21(d),   1194.31(a), 1194.31(b)    |     2.4.4, 4.1.2    |

## Context 

Refer to [EASEY July 2021 Test Report](https://teams.microsoft.com/l/file/BCF65D75-C055-4EE0-BBC6-E8800F8B141F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F5-UI%20Design%2F02%20508%20and%20Accessibility%2FEASEY%20July%202021%20Test%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e80f8082-8483-48d7-bb0c-7112e26b2076)

Figure 3: Buttons to refine filters should describe the purpose of the button

**Comment by aprematta** [comment]
Passes testing, all available filters now have the word Modify before it
