### ISSUE TITLE
Select Data Type Page-EPA report 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1762]
## Required Fix 

| Page/ Screen | Description of Issue | Test(s) | 508 Standard(s) | WCAG 2.0 Standard(s) |
|---|---|---|---|---|
|     Select Data Type    |     Top Navigation is   rendered as a background image    |     7C    |     1194.22(a)    |     1.1.1    |

## Context 
Refer to [EASEY July 2021 Test Report](https://teams.microsoft.com/l/file/BCF65D75-C055-4EE0-BBC6-E8800F8B141F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F5-UI%20Design%2F02%20508%20and%20Accessibility%2FEASEY%20July%202021%20Test%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/53ea18c3-471e-4036-9e55-8cbe6fae9b03)

**Comment by junie-stigdon** [comment]
- added bg color to subheader so the text is readable if background img does not load

![image](https://user-images.githubusercontent.com/67165079/129611926-6c859cd7-ba60-4eef-b7d7-0cab396fb8bb.png)

**Comment by aprematta** [comment]
Looks good, this should pass review
