### ISSUE TITLE
Create MP Method

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1766]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As a user, I want to create a Facility's Monitoring Methods so that I can add a new method 

Acceptance Criteria:
_Given_ the user has selected Methods in the section field
_When_ the user selects Create Method
_Then_ the system displays the edit modal
_and_ the user can add method data 

- Parameter: data driven drop down
- Methodology: data driven drop down
- Substitute Data Approach: data driven drop down
- Bypass Approach: data driven drop down
- Start Time and Date: date picker, format mm/dd/yyyy
- End Time and Date: date picker, format HH

[See page 28 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

Given the user has added method data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the methods table 

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Design Wiki ](https://teams.microsoft.com/l/channel/19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype/tab%3A%3A294ddc5d-ebad-483d-b71c-49e1f7886a14?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

## Testing
Test Case: [TC317](https://epacamd.testquality.com/project/11428/plan/19352/test/297325)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1766 Create MP Method.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ec92a2d6-afef-4301-b377-dd98b76bb11a)

**Comment by mosesdeeCVP** [comment]
![1766 Create MP Method 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9dc03c12-efc3-4f3c-ac1c-891e6c1931d4)

**Comment by mosesdeeCVP** [comment]
Test Passed
