### ISSUE TITLE
Edit Analyzer Ranges Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1781]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As a user, I want the ability to edit the Analyzer Range data so that the data available is current

Acceptance Criteria:
Given the user is on the Component editor modal
When the user selects View/Edit for a Range
Then the system displays the **Edit Analyzer Range** modal
and the user can edit data

Range: drop down, required
Dual Range Indicator: Yes/No Radio Button
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, format mm/dd/yyyy
End Time: Text, format hh

[Refer to page 47 for values](https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

Given the user has edited Analyzer Range data
When the user chooses to save and go back
Then the updated data is saved
And the user is navigated back to the Component editor modal

Given the user has edited Analyzer Range data
When the user chooses to Cancel the updates
Then the updates are not saved
And the user is navigated to the Component editor modal

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [x] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Design Wiki ](https://teams.microsoft.com/l/channel/19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype/tab%3A%3A294ddc5d-ebad-483d-b71c-49e1f7886a14?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

## Testing
Test Case: [TC334](https://epacamd.testquality.com/project/11428/plan/21748/test/299059)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
API work done in 5.2. UI still outstanding.

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![1781 Edit Analyzer Ranges Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4e2e459d-e593-444f-a27e-698d864a345d)
