### ISSUE TITLE
Widescreen (1400+) Responsiveness Layout and Content - Bug

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1788]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 1400 or above
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
- Log in button is not the same proportions as the wireframes 
- There is too much padding in the bottom part of the big blue ECMPS header
- Filter by keyword header and the filter box should be side by side instead if one on topo of the other and then they should be on the same level as Select Configuration label
- There should be no space between the Keyword box and the Filter button

Note: The lines in the table to not match the wireframes. They are a bit darker. The carrot v icon is a bit lighter in the dev site.  

![Responsiveness 1400 Dev - 01.jpg](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/91417741-38c1-4be7-98d2-5cf1cdbc203e)

**Comment by mosesdeeCVP** [comment]
The team agreed that the way the dev site it for below the table is currently acceptable. 

![Responsiveness 1400 Dev - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ea949044-bfe0-44d1-be43-232cc8069cc0)

**Comment by mosesdeeCVP** [comment]
Original Tickets:

[Update Widescreen (1400+) Responsiveness Layout #1627
](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1627)

[Update Widescreen (1400+) Responsiveness Content #1633](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1633)

**Comment by JorjaComer** [comment]
Per 5.2 refinement, line color variations are ok.

**Comment by JorjaComer** [comment]
Per 5.2 refinement, the log out button is OOTB and can stay as is

**Comment by mosesdeeCVP** [comment]
Test Cases:
[TC242](https://epacamd.testquality.com/project/11428/plan/21344/test/295187)
[TC243](https://epacamd.testquality.com/project/11428/plan/21344/test/295188)

**Comment by mosesdeeCVP** [comment]
![1788 Widescreen (1400+) Responsiveness Layout and Content - Bug - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/57373dcb-3afe-4e7d-926a-05cf501cb2cb)

![1788 Widescreen (1400+) Responsiveness Layout and Content - Bug - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/65dcc4a7-fadd-40b0-91d7-bf994feb65dc)

**Comment by mosesdeeCVP** [comment]
Test Passed
