### ISSUE TITLE
Desktop-lg (1200px) Responsiveness Layout and Content - Bug

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1789]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 1200 
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
Original Tickets:

[Update Desktop-lg (1200px) Responsiveness Layout #1626](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1626)

[Update Desktop-lg (1200px) Responsiveness Content #1634](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1634)

**Comment by mosesdeeCVP** [comment]
- The padding around the EPA image and the Menu button in the to white border is more than in the wireframes. The Menu button is slightly off center between the top and bottom borders of the white bar. 
- Log in button is not the same proportions as the wireframes
- There is too much padding in big blue ECMPS header, both top and bottom.
- Filter by keyword header and the filter box should be side by side instead if one on topo of the other and then they should be on the same level as Select Configuration label
- There should be no space between the Keyword box and the Filter button

Note: The lines in the table to not match the wireframes. They are a bit darker. The carrot v icon is a bit lighter in the dev site.

![Responsiveness 1200 Dev - 01.jpg](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/16296556-0cbf-461c-9212-ed2479ee30ae)

**Comment by mosesdeeCVP** [comment]
The team agreed that the way the dev site it for below the table is currently acceptable.

![Responsiveness 1200 Dev - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d978c74d-34b6-458c-a96b-9a707dc8561b)

**Comment by JorjaComer** [comment]
Per 5.2 refinement, line color variations are ok.

**Comment by JorjaComer** [comment]
Per 5.2 refinement, the log out button is OOTB and can stay as is

**Comment by mosesdeeCVP** [comment]
Test Cases:
[TC244](https://epacamd.testquality.com/project/11428/plan/21344/test/295189)
[TC252](https://epacamd.testquality.com/project/11428/plan/21344/test/295821)

**Comment by mosesdeeCVP** [comment]
![1789 Desktop-lg (1200px) Responsiveness Layout and Content - Bug - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6275bcaf-da00-4de3-8bac-8410a6be76d7)

**Comment by mosesdeeCVP** [comment]
Test Passed
