### ISSUE TITLE
Desktop (1024px) Responsiveness Layout and Content - Bug

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1791]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 1024
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
Original Tickets:

[Update Desktop (1024px) Responsiveness Layout #1625
](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1625)

[Update Desktop (1024px) Responsiveness Content #1635](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1635)

**Comment by mosesdeeCVP** [comment]
- The padding around the EPA image and the Menu button in the to white border is more than in the wireframes. The Menu button is slightly off center between the top and bottom borders of the white bar.
- Log in button is not the same proportions as the wireframes
- There is too much padding in big blue ECMPS header, both top and bottom. There is too much space between the different labels.
- The gray bar below the blue ECMPS bar should be attached directly to the bottom or it without any white space. The gray bar should also completely fit the screen right to left without white spaces. It should be the same length as the blue bar above it.
- Filter by keyword header and the filter box should be side by side instead if one on top of the other and then they should be on the same level as Select Configuration label
- There should be no space between the Keyword box and the Filter button

Note: The lines in the table to not match the wireframes. They are a bit darker. The carrot v icon is a bit lighter in the dev site.

![Responsiveness 1024 Dev - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/14439fb6-124e-474a-b047-e160db7ea820)

![Responsiveness 1024 Dev - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/31636a8b-7db7-42d8-aab5-138bb8003b81)

**Comment by JorjaComer** [comment]
Per 5.2 refinement, the log out button is OOTB and can stay as is

**Comment by mosesdeeCVP** [comment]
Test Cases:
[TC253](https://epacamd.testquality.com/project/11428/plan/21344/test/295822)
[TC254](https://epacamd.testquality.com/project/11428/plan/21344/test/295823)

**Comment by mosesdeeCVP** [comment]
Test Cases:
[TC255](https://epacamd.testquality.com/project/11428/plan/21344/test/295824)
[TC256](https://epacamd.testquality.com/project/11428/plan/21344/test/295825)

**Comment by mosesdeeCVP** [comment]
![1791 Desktop (1024px) Responsiveness Layout and Content - Bug.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a90c4842-d2b0-43bf-ac89-2b647d088744)

**Comment by mosesdeeCVP** [comment]
Test Passed
