### ISSUE TITLE
Tablet (640px) Responsiveness Layout and Content - Bug

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1792]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 640
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
Original Tickets:

[Update Tablet (640px) Responsiveness Layout #1624](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1624)

[Update Tablet (640px) Responsiveness Content #1636](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1636)

**Comment by mosesdeeCVP** [comment]
- There is too much padding to the bottom of the white bar with the EPA image and Menu button. The Menu button is not level with the EPA image.
- There is too much padding to the bottom of the blue ECMPS bar. To the right of the blue bar there is a lot of space between the log in circle, the carrot and the menu hamburger icon.
- The gray bar that is under the blue ECMPS bar has some white space to the right and left. The bar should extend from end to end.
- The Import a Monitoring Plan button should be level with the Monitoring Plans label

- Select Configuration label should be to the far right with Filter by keyword and the Keyword box and Filter button to its right
   -  The Filter by keyword label should start right above the beginning of the Keyword box
   -   There should be no space between the Keyword box and the Filter button.
- The gray color of the Facility table should extend from end to end of the screen.


- Below the table the Rows per page label is half cut off. The proportioning of the 1-100 out of 2523 label should be adjusted to fit better.

![Responsiveness 640 Dev - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9ab14fe2-18cc-4212-8978-ca46e3cd54b7)

![Responsiveness 640 Dev - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/03dfe4b8-2aca-4e30-9fa3-8df942a06b93)

![Responsiveness 640 Dev - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f2dab5b8-8420-4cdb-b0e0-d2495f6b4cd2)

**Comment by JorjaComer** [comment]
Per 5.2 refinement, the log out button is OOTB and can stay as is and line color is fine

**Comment by mosesdeeCVP** [comment]
![1792 Tablet (640px) Responsiveness Layout and Content - Bug.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f99e4288-82bf-48cc-95dc-6e6fbf7cb5fa)

**Comment by mosesdeeCVP** [comment]
Test Passed
