### ISSUE TITLE
Mobile-lg (480px) Responsiveness Layout and Content - Bug

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1794]
## User Story
As a user 
I want to view ECMPS in a responsive manner 
So that it responds to the screen I an viewing it on 

## Acceptance Criteria
Given a user has accessed ECMPS 
When it is viewed at a screen size at 480
Then it is displayed according to the wireframes 

## Context
[Responsive breakpoints](https://xd.adobe.com/view/9910b28f-8b73-4720-8da5-056fd8de05d5-cc43/flow/)

**Comment by mosesdeeCVP** [comment]
Original Tickets:

[Update Mobile-lg (480px) Responsiveness Layout Only #1623
](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1623)

[Update Mobile-lg (480px) Responsiveness Page Content #1628](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1628)

**Comment by mosesdeeCVP** [comment]
- The padding is too much below the white bar with the EPA image and Menu button. Menu button is not level with the EPA image.
- Spacing is not correct between the log in circle and the v carrot icon and the hamburger menu on the Blue ECMPS bar.
- The ECMPS Menu bar should have a gray background. 
- The Import button should be wider/longer
- The blue Select Configurations button should be centered
- Filter by keyword and the Keyword box/Filter button should be centered. 
- There is no space between the Keyword box and the Filter button
- The gray and white rows of the Facility table should extend from one end to the other of the screen. The v carrot icon and lines are not the sane color as the wireframes.
- The pagination options to the bottom of the Facilities table is not properly centered.

![Responsiveness 480 Dev - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8b120ddc-a34b-4e97-83a9-41ca5172eb4e)

![Responsiveness 480 Dev - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/90951585-4025-4a6d-9041-68ce94e70d31)

![Responsiveness 480 Dev - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e1aa6e13-5f70-483f-b268-9ce4450ae2b1)

**Comment by JorjaComer** [comment]
Per 5.2 refinement,  line color is fine and table alignment is not in scope for this time

**Comment by mosesdeeCVP** [comment]
Test Cases:
[TC257](https://epacamd.testquality.com/project/11428/plan/21344/test/295827)
[TC258](https://epacamd.testquality.com/project/11428/plan/21344/test/295828)

**Comment by mosesdeeCVP** [comment]
![1794 Mobile-lg (480px) Responsiveness Layout and Content - Bug.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fb993e6c-e92c-4fb1-9ae7-c33aaf2ec967)

**Comment by mosesdeeCVP** [comment]
Test Passed
