### ISSUE TITLE
Add No Info to Display Message 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1799]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to see a message when a facility has no configurations
So that I can understand why there is not data to view 

## Acceptance Criteria
Given a user is within any table 
When the selected item/data set has no data to display 
Then the system displays the message "No data currently present." 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [x] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Relevant Facilities: Avon, RG1&2, Silver Gate, and Crosscut.

## Testing
Test Case: [TC314](https://epacamd.testquality.com/project/11428/plan/19352/test/296794)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1799 Add No Info to Display Message.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/64dc2b1f-c7d6-4f28-ab78-454a24cb2e02)

**Comment by mosesdeeCVP** [comment]
Test Passed
