### ISSUE TITLE
Order by ORIS Code 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1800]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want the facility table top be ordered by ORIS code 
So that I can locate facilities in the manner I am used to 

## Acceptance Criteria
Given a user is within the facilities table 
When the table is displayed
Then the default order for the table is my ORIS code in descending numeric order 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC307](https://epacamd.testquality.com/project/11428/plan/19352/test/296287)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1800 Order by ORIS Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bba800a7-b8ef-4bca-9143-350f3557cbc7)

**Comment by mosesdeeCVP** [comment]
Test Passed
