### ISSUE TITLE
Add Existing Component to System 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1802]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to add an existing component to a system
So that I can update the system data 

_Given_ the user has selected a particular system
_When_ the user edits particular component 
_Then_ the system displays the add modal
_and_ the user can enter an component ID (that already exists for a location) to the system 

_Given_ the user has entered an existing component ID to the system 
_When_ the user edits the component data
_Then_ the user can edit the following  

- Component ID (displays as read only)
- Sample Acquisition Method: drop down, required
- Component Type: drop down, required
- Basis Description: drop down, required
- Manufacturer: text
- Model or version: text
- Serial Number: text
- Hg Converter Indicator: yes/no 
- Start Date: date picker, required, format mm/dd/yyyy
- Start Time: Text, required, format hh
- End Date: date picker, required, format mm/dd/yyyy
- End Time: Text, required, format hh

Given the user has added a component
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the methods table 

Given the user has added a component
When the component exists in another location
Then the component data (all data except start/end date) is updated for all locations using that component 

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
[Add Wireframe 
](https://xd.adobe.com/view/59f6eaba-c1fb-4bf7-b602-f939afe54bd7-0ca5/)

## Testing
Test Case: [TC362](https://epacamd.testquality.com/project/11428/plan/19812/test/302372)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1802 Add Existing Component to System - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/593273ff-1982-40df-81d9-f570e0967058)

![1802 Add Existing Component to System - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a98c93be-e3ea-4f21-b6e6-dfa5431e5e94)

**Comment by mosesdeeCVP** [comment]
![1802 Add Existing Component to System - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6c23db6d-5a3f-47ce-b97c-79310dc47195)

**Comment by mosesdeeCVP** [comment]
Test Passed except for minor issues. Bug will be created for it

**Comment by mosesdeeCVP** [comment]
Bug Ticket:

[Add Component flag and Create Component Label#2016](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2016)
