### ISSUE TITLE
Enable Editing Restrictions by Screen Size/Device 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1803]
## Feature Benefit
Limit functionality available to a user based on the size of the device they are accessing the application from. For example, direct users to the desktop site to edit data if screen resolution is below 1024 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by annalbrecht** [comment]
Chris has indicated this can be closed.
