### ISSUE TITLE
Updated Site Map (need by 8/4)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1804]
Update the Site Map for review in the EASEY Baby meeting on 8/4 

### Assets
- [Updated EASEY Sitemap](https://www.figma.com/file/oH4mOXuXImz0q1E9qTkz1o/Site-Maps?node-id=2%3A2)

**Comment by cvp-alexrobinson** [comment]
@JorjaComer @MoAdeyoju —

Hello,

The link is in the issue description. Please let me know if there are any access issues.

Best,
Alex
