### ISSUE TITLE
Update Design to Center Content on CAMPD Basic content pages 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1807]
Center content based on resolution for CAMPD Home page, Data landing page

**Comment by JanellC** [comment]
During backlog refinement on 9/8 the team decided to tackle Center Content on CAMPD #1765 during I+P sprint. The team needs the revised UI design for the CAMPD home page and the Data landing page before I+P sprint.

**Comment by AllisonFrancis** [comment]
@tlageman-epa 

Here are the Home Page and Data home page with items centered.
[CAMPD Data landing](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A148&scaling=min-zoom&page-id=1%3A146)
[CAMPD Data landing (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146)

[CAMPD Home](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=899%3A4278&scaling=min-zoom&page-id=899%3A4086)
[CAMPD Home (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=899%3A4086)
Happy to discuss any questions or concerns during the PD meeting. Thanks

**Comment by AllisonFrancis** [comment]
All CAMPD pages have been updated so that at each breaking point the screens have the same margins and wrap consistently to all the other pages.
