### ISSUE TITLE
Design Auth with CBS 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1809]
- [ ] Review existing contract
- [ ] Formalize new contract
- [ ] Document design/call 
- [ ] Update arch diagram, if needed

**Comment by maheese** [comment]
Here's a sample of [XML response](https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Tech/CDX/AuthenticatedUser.txt) from the exixting auth method.
