### ISSUE TITLE
Account Type Filter - Sprint 5.1 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1815]
## Required Fixes 

- [x] RF -1 

- [x] RF-2

- [x] RF-3

## Context 
See the [508 audit report](https://app.zenhub.com/files/287570343/dc4ea819-5df3-41c0-8860-3bcc2f3e125c/download
)  

| Issue # | Issue Title | Issue Description |
|---|---|---|
| RF-1 | Elements   are not Accessible by Keyboard and Assistive Technology | Elements are present which are actionable by a mouse but not   also actionable with simple keyboard controls (directional arrows, Tab,   Enter, Space Bar). This issue is a violation of Section 508 and WCAG 2.0   Success Criterion 2.1.1. |
| RF-2 | Modal   Dialog has incorrect Focus management | A   modal dialogue appears that does not receive programmatic focus and is not   immediately following that control that caused it to appear and/or focus is   not returned when the dialog is closed. This issue is a violation of Section   508 and WCAG 2.0 Success Criterion 2.4.3 |
| RF-3 | Form   Labels are not descriptive / accurate | There   is a label associated with the form field but the label itself is not   descriptive or accurate. This issue is a violation of WCAG 2.0 Success   Criterion 2.4.6. |

**Comment by aprematta** [comment]
All issues pass, closing ticket
