### ISSUE TITLE
Vintage Year Filter- Sprint 5.1 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1816]
## Required Fix 

- [x] RF-1

- [x] RF-2

- [x] RF-3

## Context 
See audit report: https://app.zenhub.com/files/287570343/b5f6d7a9-91fe-499e-a5b8-5872c6c1e513/download

| Issue # | Issue Title | Issue Description |
|---|---|---|
| RF-1 | Modal   Dialog has incorrect Focus management | A   modal dialogue appears that does not receive programmatic focus and is not   immediately following that control that caused it to appear and/or focus is   not returned when the dialog is closed. This issue is a violation of Section   508 and WCAG 2.0 Success Criterion 2.4.3 |
| RF-2a | Form   Labels are not descriptive / accurate | There   is a label associated with the form field but the label itself is not   descriptive or accurate. This issue is a violation of WCAG 2.0 Success   Criterion 2.4.6. |
| RF-2b | Form   Labels are not descriptive / accurate | There   is a label associated with the form field but the label itself is not   descriptive or accurate. This issue is a violation of WCAG 2.0 Success   Criterion 2.4.6. |
| RF-3 | Color   Contrast is Insufficient  | Color   contrast ratio between text and background is less than 4.5:1. This is a   violation of HHS Guidelines and WCAG 2.0 Success Criterion 1.4.3. |

**Comment by aprematta** [comment]
Passes testing
