### ISSUE TITLE
Account Name/Number Filter-Sprint 5.1 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1818]
## Required Fix 

- [x] RF-1 

- [x] RF-2

- [x] RF-3

## Context 

See audit report : https://app.zenhub.com/files/287570343/b9071897-2670-453d-a6b3-e4fd11e35327/download

| Issue # | Issue Title | Issue Description |
|---|---|---|
| RF-1 | Modal   Dialog has incorrect Focus management | A   modal dialogue appears that does not receive programmatic focus and is not   immediately following that control that caused it to appear and/or focus is   not returned when the dialog is closed. This issue is a violation of Section   508 and WCAG 2.0 Success Criterion 2.4.3 |
| RF-2 | Form   Labels are not descriptive / accurate | There   is a label associated with the form field but the label itself is not   descriptive or accurate. This issue is a violation of WCAG 2.0 Success   Criterion 2.4.6. |
| RF-3 | Elements   will be difficult to control with a keyboard | Elements   are present which are keyboard accessible, but operation will be extremely   difficult for a keyboard user. This issue is a violation of Section 508 and   WCAG 2.0 Success Criterion 2.1.1. |

**Comment by aprematta** [comment]
Passes testing
