### ISSUE TITLE
CAMPD About Page- Dummy Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1819]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to view the About CAMPD page so that I can learn more about CAMPD 

## Acceptance Criteria
Given that a user has navigated to the About CAMPD page 
When the functionality is displayed 
Then the page is displayed in accordance with the[ wireframes ](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541) 
And the page content is consistent with the [content document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBEF116D3-0228-4EDE-B0D0-21C64213462E%7D&file=About%20CAMPD%20Content-%20EPA%20CAMD-v1.01.docx&action=default&mobileredirect=true) 

Given that a user has selected About CAMPD on the utility nav
When the functionality is displayed 
Then the system renders the About CAMPD page 

## Developer Notes 
- The scope of this ticket includes developing the layout of the About Page w/ dummy data for the on- demand content.  On demand content includes the items listed under product updates. However, static content and meta content should be developed as apart of the scope of this ticket. 
- The accordion under release notes should be closed by default
- accordions should remain open until a user closes it 
- Under bug fixes include "Upcoming Features " 

 
### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[About Page content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBEF116D3-0228-4EDE-B0D0-21C64213462E%7D&file=About%20CAMPD%20Content-%20EPA%20CAMD-v1.01.docx&action=default&mobileredirect=true&cid=f26ad070-e08f-4b7b-b01b-6d69092d98dc)

- [About CAMPD](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541)
- [About CAMPD (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541)

## Testing
Test Case: [TC483](https://epacamd.testquality.com/project/11428/plan/21067/test/313116)
Tester: @JanellC 

508 Testing 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During backlog refinement on 8/11 it was decided that this ticket will be postponed until PI 6 so that when development work begins the page can implemented in a way to update dynamically

**Comment by JanellC** [comment]
TC483 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
