### ISSUE TITLE
CAMPD Glossary Page

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1820]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the glossary so that I can understand the data on the website 

## Acceptance Criteria

Given that a user has accessed the CAMPD Glossary page on the utility nav
When the functionality is displayed 
Then the page renders in accordance with the wireframes (see context) 
And is consistent with the [glossary content document ](https://teams.microsoft.com/l/file/4058BC6B-6505-4A9E-87CF-337E8D795E01?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F2-Utility%20Menu%2F1-Resources%2F1-Glossary%2FGlossary%20Content-%20EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) (content, meta tags, etc.) 

Given that a user has selected download glossary (pdf or xlsx)
When the action is executed 
Then the system downloads the glossary in the specified file type 

## Developer Notes 
The glossary File Name should be: 
CAMPD-Glossary.pdf 
CAMPD-Glossary.xlsx

For the pdf file, the glossary will open up in a new tab in the browser 

**As apart of the scope of this ticket: The EPA will have the ability to** 
1. Update the static content on the glossary page 
2. Provide a new glossary 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

 
[glossary content document ](https://teams.microsoft.com/l/file/4058BC6B-6505-4A9E-87CF-337E8D795E01?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F2-Utility%20Menu%2F1-Resources%2F1-Glossary%2FGlossary%20Content-%20EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

**Wireframes** : 
[Glossary](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910&scaling=min-zoom&page-id=695%3A2909&starting-point-node-id=695%3A2910)

[Glossary (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910)

**Glossary File:** 
[CAMPD Glossary PDF ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000B4ABB0EF9635994FA680705355892410&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F3%2DBusiness%20Analysis%2FArtifacts%2FCAMPD%2DGlossary%2Epdf&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F3%2DBusiness%20Analysis%2FArtifacts)

[CAMPD Glossary xlsx ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={CADE0BDB-C3EE-49F6-AAC6-972DF12DD862})

## Testing
Test Case: [TC536](https://epacamd.testquality.com/project/11428/plan/21067/test/322923)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
@jwhitehead77 The CAMPD glossary will be provided via xlsx and pdf file formats 


[Glossary](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910&scaling=min-zoom&page-id=695%3A2909&starting-point-node-id=695%3A2910)

[Glossary (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=695%3A2910)

**Comment by JanellC** [comment]
TC536 passed @tlageman-epa , This ticket is ready for 508 testing @aprematta
