### ISSUE TITLE
CAMPD Related Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1821]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the Related Resources Page So that I can view data tools similar to CAMPD 

## Acceptance Criteria
Given that s user has navigated to CAMPD
When the functionality is displayed 
Then the page renders is accordance with the wireframes (see context) 
And the page content is consistent with [Related Resources Content Document ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={A90DEF68-CB16-4E0A-8D6E-33A43598DA4B})

Given that a user has selected Resources on the utility nav 
When Related Resources is selected 
Then the system displays the Related Resources page  

## Developer Notes 

External Links should open in a new tab

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

 [Related Resources Content Document ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={A90DEF68-CB16-4E0A-8D6E-33A43598DA4B})

**Wireframes**
- [Related Resources Page](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1407&scaling=contain&page-id=392%3A1254)
- [Related Resources Page (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1407) 

## Testing
Test Case: [TC429 ](https://epacamd.testquality.com/project/11428/plan/21067/test/309141)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC429 failed @tlageman-epa. I logged Bug: CAMPD Related Resources #2256 to track the changes

**Comment by JanellC** [comment]
Bug: CAMPD Related Resources #2256 resolved. This ticket is ready for 508 testing @aprematta
