### ISSUE TITLE
CAMPD Tutorials Page

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1822]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the tutorials page So that I can better understand the data on CAMPD 

## Acceptance Criteria
Given that a user has accessed the Tutorials page 
When the functionality is displayed
Then the page renders in accordance with the wireframes (see context)
And is consistent with the [Tutorials content document ](https://teams.microsoft.com/l/file/01A8E4F4-AD0F-468B-902E-FEC4BF46F98A?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F2-Utility%20Menu%2F2-Help%2BSupport%2F2-Tutorials%2FTutorials%20Content-%20EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Given that a user has selected Tutorials on the utility nav
When the functionality is displayed
Then the tutorials page renders in accordance with the wireframes (see context)

## Developer Notes 

External Links should open in a new tab

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Tutorials](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=704%3A4725&scaling=min-zoom&page-id=701%3A3709&starting-point-node-id=704%3A4725)
[Tutorials (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=704%3A4725)
[
Tutorials content document ](https://teams.microsoft.com/l/file/01A8E4F4-AD0F-468B-902E-FEC4BF46F98A?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F2-Utility%20Menu%2F2-Help%2BSupport%2F2-Tutorials%2FTutorials%20Content-%20EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Testing
Test Case: [TC430 ](https://epacamd.testquality.com/project/11428/plan/21067/test/309142)
Tester: @JanellC 

508 Testing; 

Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC430 passed @tlageman-epa . This ticket is ready for 508 testing
