### ISSUE TITLE
Add client only DB columns to Postgres DB tables (MP Beta Release)

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1823]
Need to add the following client columns to each of the tables listed to address the differences between the Check Engine SQL Server client DB tables and the host tables.

**CAMDMD Schema**
- [x] PROGRAM_CODE
  - rue_ind
  - so2_cert_ind
  - nox_cert_ind
  - noxc_cert_ind
  - notes

**CAMDECMPSMD Schema**
- [x] PROCESS_CODE
  - process_cd_name
  - parameter_group_override_cd
  - process_group_cd

**CAMDECMPSAUX Schema**
- [x] CHECK_LOG (create workspace table for this)
- [x] CHECK_SESSION (create workspace table for this)
  - updated_status_flg (default to N)
  - last_updated

**Comment by djw4erg** [comment]
Jason, I believe that we verbally talked about scripts for this ticket,  I believed that we were discussing data scripts, but believe the ticket is for structure changes.  

Should I produce alter table scripts, or just change the tables directly?

**Comment by jwhitehead77** [comment]
Added additional PROGRAM_CODE columns and updated the CAMPD Release #1 before-load & after-load scripts
