### ISSUE TITLE
Check In/Check Out - Rules

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1834]
Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

User Story
As a User
I want Check In/Check Out process for the Monitoring Plans to be streamlined
So that I understand when my updates to the Methods data will be saved and Checked In

## Acceptance Criteria
Given a user checked out a Monitoring Plan
And viewed/updated the Methods data and **Saved** them
When the user closes the Methods tab without **Checking back in**
Then the system automatically checks in the MP with any saved updates

Given a user checked out a Monitoring Plan
And viewed/updated the Methods data and **Saved** them
When the user closes the Browser without **Checking back in**
Then the system automatically checks in the MP with any saved updates

Given a user checked out a Monitoring Plan
And made edits to the Methods data 
When the user cancels the edits/closes the modal
And closes the Methods tab 
Then the system automatically 'checks back in' the MP

Given a user checked out a Monitoring Plan
And made edits to the Methods data
When the user closes the Browser (Chrome/Firefox/Edge.....) without **Saving**
Then the system **checks back in** the MP automatically without saving the updates

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC316](https://epacamd.testquality.com/project/11428/plan/19352/test/297324)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Passed
