### ISSUE TITLE
Convert low effort SQL Server Functions to Postgres

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1841]
Format: Database.Schema.Function

- ECMPS.CheckEM.FormatDateTime
  - [x] WIP by: Anna Y
  - [x] Complete(camdecmpswks.formatdatetime)
- ECMPS.dbo.GetNewDBIDKey
  - [x] WIP by: Anna Y
  - [x] Complete(camdecmpswks.getnewdbidkey)
- ECMPS.dbo.RPT_GetFacilityHeader
  - [x] WIP by: Anna Y
  - [x] Complete(camdecmpswks.RPT_GetFacilityHeader)
- ECMPSAUX.Check.ErrorSuppressionSpec_Gather
  - [x] WIP by: Anna Y
  - [x] Complete(camdecmpsaux.errorsuppressionspec_gather)
- ECMPSAUX.Check.GetNewDBIDKey
  - [x] WIP by: Anna Y
  - [x] Complete(calling camdecmpswks.getnewdbidkey)

**Comment by ayang2017** [comment]
New function dateadd is created. Need to know more to get the function ECMPS.CheckEM.FormatDateTime completed.
