### ISSUE TITLE
Demo UI Updates

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1844]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want UI to be grammatically correct 
So that it is easy to understand 

## Acceptance Criteria
Given a user selected Revert to Official Record
When the message is displayed
Then it reads as "Reverting to Official Record will undo all saved and unsaved changes. This is not recoverable. Do you want to continue?" 

Given a user is viewing a configuration with Supplemental Methods 
When the list of SM is displayed 
Then the create button reads "Create MATS"

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC314](https://epacamd.testquality.com/project/11428/plan/19352/test/296794)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1844 Demo UI Updates - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/560d2520-2b9b-4db2-aaf5-b5a4ee651b7d)

![1844 Demo UI Updates - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/336af342-d214-481c-a37f-d4523ca8ba5f)

**Comment by mosesdeeCVP** [comment]
Test Passed
