### ISSUE TITLE
Convert & Refactor UPDATE_ECMPS_STATUS stored procedure to Postgres

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1860]
ECMPS.dbo.UPDATE_ECMPS_STATUS

**Comment by djw4erg** [comment]
### MP Evaluation

    1.  Delete CHECK_SESSION rows where:
        *   PROCESS_CD = 'MP', 
        *   MON_PLAN_ID = session MON_PLAN_ID,
        *   CHK_SESSION_ID != session CHK_SESSION_ID.
    2.  Update MONITOR_PLAN row for session MON_PLAN_ID by setting NEEDS_EVAL_FLG to 'N', LAST_EVALUATED_DATE to current timestamp, and CHK_SESSION_ID to the session CHK_SESSION_ID.
    3.  When MONITOR_PLAN row exists where MON_PLAN_ID = session MON_PLAN_ID and either UPDATED_STATUS_FLG = 'Y' or SUBMISSION_AVAILABILITY_CD = 'REQUIRE'.
        a.  Select distinct MON_PLAN_ID and RPT_PERIOD_ID from EMISSION_EVALUATION and EM_SUBMISSION_ACCESS for MP where EMISSION_EVALUATION.NEEDS_EVAL_FLG = 'N' and EM_SUBMISSION_ACCESS.SUBMISSION_AVAILABILITY_CD equals "REQUIRE" or "GRANTED".
            *   Call DEL_CALCULATED_EMISSIONS_DATA SP for each MON_PLAN_ID and RPT_PERIOD_ID combination.
                *   Handle if call fails by bailing out of everything.
                *   Used by UES.UpdateSubsequentEmissionsAfterRetrieve
                *   Calls UES.DeleteCalculatedEmissionsData passing the MON_PLAN_ID and RPT_PERIOD_ID in XML.
                    *   Deletes the CHECK_SESSION rows where:
                        *   EMISSION_EVALUATION row exists where:
                            *   CHK_SESSION_ID = CHECK_SESSION.CHK_SESSION_ID
                            *   MON_PLAN_ID = MON_PLAN_ID = session MON_PLAN_ID
                            *   RPT_PERIOD_ID = RPT_PERIOD_ID = session RPT_PERIOD_ID
                    *   Updates EMISSION_EVALUATION row setting NEEDS_EVAL_FLG = 'Y' and CHK_SESSION_ID = null where:
                        *   MON_PLAN_ID = MON_PLAN_ID = session MON_PLAN_ID
                        *   RPT_PERIOD_ID = RPT_PERIOD_ID = session RPT_PERIOD_ID
                    *   Clears calculated values in DAILY_CALIBRATION, DAILY_EMISSION, DAILY_FUEL, DAILY_TEST_SUMMARY, DERIVED_HRLY_VALUE, HRLY_FUEL_FLOW, HRLY_PARAM_FUEL_FLOW, LONG_TERM_FUEL_FLOW, MONITOR_HRLY_VALUE and SUMMARY_VALUE for MP MON_LOC_ID and RPT_PERIOD_ID.
                    *   Deletes DM Emissions for session MON_PLAN_ID and session RPT_PERIOD_ID.
                    *   Calls UES.EmissionsGridRemoveEval, which stripped the error codes from prepopulated tables used in the ECMPS Emission Screens.  This call is no longer needed.
                    *   Used by UES.ProgramParameter and UES.VendorSync.
        b.  Delete CHECK_SESSION rows where:
            *   QA_CERT_EVENT row exists where:
                *   CHK_SESSION_ID = CHECK_SESSION.CHK_SESSION_ID
                *   MON_LOC_ID = MON_LOC_ID for a MONITOR_PLAN_LOCATION where MONITOR_PLAN_LOCATION.MON_PLAN_ID = session MON_PLAN_ID
                *   NEEDS_EVAL_FLG = 'N'
                *   Either SUBMISSION_AVAILABILITY_CD = 'REQUIRE' OR UPDATED_STATUS_FLG = 'Y'
        c.  Update QA_CERT_EVENT rows setting NEEDS_EVAL_FLG = 'Y', CHK_SESSION_ID = null, and UPDATE_DATE = <Current Date & Time> where:
                *   MON_LOC_ID = MON_LOC_ID for a MONITOR_PLAN_LOCATION where MONITOR_PLAN_LOCATION.MON_PLAN_ID = session MON_PLAN_ID
                *   NEEDS_EVAL_FLG = 'N'
                *   Either SUBMISSION_AVAILABILITY_CD = 'REQUIRE' OR UPDATED_STATUS_FLG = 'Y'
        d.  Delete CHECK_SESSION rows where:
            *   TEST_EXTENSION_EXEMPTION row exists where:
                *   CHK_SESSION_ID = CHECK_SESSION.CHK_SESSION_ID
                *   MON_LOC_ID = MON_LOC_ID for a MONITOR_PLAN_LOCATION where MONITOR_PLAN_LOCATION.MON_PLAN_ID = session MON_PLAN_ID
                *   NEEDS_EVAL_FLG = 'N'
                *   Either SUBMISSION_AVAILABILITY_CD = 'REQUIRE' OR UPDATED_STATUS_FLG = 'Y'
        e.  Update TEST_EXTENSION_EXEMPTION rows setting NEEDS_EVAL_FLG = 'Y', CHK_SESSION_ID = null, and UPDATE_DATE = <Current Date & Time> where:
                *   MON_LOC_ID = MON_LOC_ID for a MONITOR_PLAN_LOCATION where MONITOR_PLAN_LOCATION.MON_PLAN_ID = session MON_PLAN_ID
                *   NEEDS_EVAL_FLG = 'N'
                *   Either SUBMISSION_AVAILABILITY_CD = 'REQUIRE' OR UPDATED_STATUS_FLG = 'Y'
        f.  Select TEST_SUM_ID from TEST_SUMMARY for MP where TEST_SUMMARY.NEEDS_EVAL_FLG = 'N'.
            *   Form the TEST_SUM_ID into comma delimted list of no more than 170 ids.
                *   Call DEL_CALCULATED_QA_DATA for each comma delimted TEST_SUM_ID list.
                *   Handle if call fails by bailing out of everything.
                *   Calls UES.DeleteCalculatedQAData passing a list of TEST_SUM_ID.
                    *   Deletes the CHECK_SESSION rows where:
                        *   TEST_SUMMARY row exists where:
                            *   TEST_SUM_ID = exists in the XML list of TEST_SUM_ID,
                    *   Updates TEST_SUMMARY row setting NEEDS_EVAL_FLG = 'Y',  and setting CHK_SESSION_ID, CALC_GP_IND, CALC_TEST_RESULT_CD and CALC_SPAN_VALUE to null where:
                        *   MON_PLAN_ID = MON_PLAN_ID = session MON_PLAN_ID
                        *   RPT_PERIOD_ID = RPT_PERIOD_ID = session RPT_PERIOD_ID
                    *   Clears calculated values in AE_CORRELATION_TEST_RUN, AE_CORRELATION_TEST_SUM, AE_HI_GAS, AE_HI_OIL, CALIBRATION_INJECTION, CYCLE_TIME_INJECTION, CYCLE_TIME_SUMMARY, FLOW_RATA_RUN, FLOW_TO_LOAD_REFERENCE, GFM_CALIBRATION, HG_LME_DEFAULT_TEST_DATA, HG_LME_DEFAULT_TEST_SUMMARY, LINEARITY_SUMMARY, ON_OFF_CAL, RATA, RATA_RUN, RATA_SUMMARY, RATA_TRAVERSE, and UNIT_DEFAULT_TEST.
                    *   Used by UES.ProgramParameter and UES.VendorSync.
                    *   Used by UES.ProgramParameter and UES.VendorSync.

**Comment by djw4erg** [comment]
MP Data Entry:
MP Import:
Error Suppression Retrieve:
Used ID Retrieve:

    For each MP containing an affected location:
    
        1.  Update associated MONITOR_PLAN;
            a.  UPDATED_STATUS_FLG to 'Y' and LAST_UPDATED to Now.
                *   Only for active MP for "MP Data Entry" and "MP Import".
                *   All MP for "Error Suppression Retrieve" and "Used ID Retrieve".
            b.  PENDING_STATUS_CD to 'PENDUP' and UPDATE_DATE to Now when PENDING_STATUS_CD equals 'PENDING'.
                *   Only for active MP for "MP Data Entry" and "MP Import".
                *   All MP for "Error Suppression Retrieve" and "Used ID Retrieve".
            c.  NEEDS_EVAL_FLG to "Y", CHK_SESSION_ID to null and UPDATE_DATE to Now
                *   All MP for "MP Data Entry" and "MP Import".
                *   Only MP with SUBMISSION_AVAILABILITY_CD = "REQUIRE" or UPDATED_STATUS_FLG = "Y" for "Error Suppression Retrieve" and "Used ID Retrieve".
        2.  Delete associated CHECK_SESSION rows where MONITOR_PLAN NEEDS_EVAL_FLG equals "Y" (even when set to "Y" above)
        3.  For each EMISSION_EVALUATION and ESA_SUBMISSION_ACCESS row cobination on MON_PLAN_ID and RPT_PERIOD_ID with matching MON_PLAN_ID and where ESA.SUBMISSION_AVAILABILITY_CD is either "GRANTED" or "REQUIRE".
            a.  Delete CHECK_SESSION rows that match on the EMISSION_EVALUATION CHK_SESSION_ID.
            b.  Update EMISSION_EVALUATION NEEDS_EVAL_FLG to "Y" and CHK_SESSION_ID to null.
            c.  Null calculated columns in emission tables for the MON_LOC_ID associated with the MON)PLAN_ID, and the RPT_PERIOD_ID.
            d.  Delete rows in the set of DM Emissions tables for the MON_PLAN_ID and RPT_PERIOD_ID.
        4.  For each QA_CERT_EVENT or TEST_EXTENSION_EXEMPTION row matching the MON_LOC_ID for the MON_PLAN_ID, and the QA_CERT_EVENT or TEST_EXTENSION_EXEMPTION NEEDS_EVAL_FLG equals "Y" and either SUBMISSION_AVAILABILITY_CD = 'REQUIRE' or UPDATED_STATUS_FLG equals 'Y'.
            a.  Set NEEDS_EVAL_FLG to 'Y', CHK_SESSION_ID to null and UPDATE_DATE to Now.
            b.  Delete CHECK_SESSION rows that match on the QA_CERT_EVENT or TEST_EXTENSION_EXEMPTION CHK_SESSION_ID.
        5.  For each TEST_SUMMARY row outter joined to a QA_SUPP_DATA row where MON_LOC_ID matches the MON_PLAN_ID and TEST_SUMMARY NEEDS_EVAL_FLG equals 'N', and QA_SUPP_DATA is NULL, 'GRANTED' or 'REQUIRE'.
            a.  Delete CHECK_SESSION rows that match on the TEST_SUMMARY TEST_SUM_ID.
            b.  Update TEST_SUMMARY NEEDS_EVAL_FLG to "Y" and CHK_SESSION_ID to null.
            c.  Null calculated columns in QA test tables (including TEST_SUMMARY) for the TEST_SUM_ID.

**Comment by djw4erg** [comment]
MP Loaded (Submission)

    For MONITOR_PLAN matching the the specified MON_PLAN_ID, set:
    
        *   PENDING_STATUS_CD to null.
        *   SUBMISSION_AVAILABILITY_CD to the specified Submission Availability Code.
        *   SUBMISSION_ID to the specified Submission ID
        *   UPDATED_STATUS_FLG to 'N' when PENDING_STATUS_CD does not equal 'PENDUP'.

    For MONITOR_PLAN_COMMENT matching the the specified MON_PLAN_ID, set:
    
        *   PENDING_STATUS_CD to null.
        *   SUBMISSION_AVAILABILITY_CD to the specified Submission Availability Code.
   


MP Failed (Submission)

    For the specified MONITOR_PLAN set PENDING_STATUS_CD to null.


MP Retrieve
MP Supp Retrieve

    For every MONITOR_PLAN associated with MON_LOC_ID contained in the MONITOR_PLAN for the specified MON_PLAN_ID.
    
        1.  Delete any CHECK_SESSION rows with a matching MON_PLAN_ID.
        2.  Set NEEDS_EVAL_FLG to "Y", CHK_SESSION_ID to null and UPDATE_DATE to Now.
        
        For the specified MON_PLAN_ID
        1.  For "MP-Retrieve", set set UPDATED_STATUS_FLG to 'N' and UPDATE_DATE to Now.
        2.  For "MP Supp Retrieve", set SUBMISSION_AVAILABILITY_CD to 'REQUIRE' (possible relic) and UPDATE_DATE to Now.
        
        For any MONITOR_PLAN associated with MON_LOC_ID contained in the MONITOR_PLAN for the specified MON_PLAN_ID, and that has a NULL SUBMISSION_AVAILABILITY_CD.
        1.  Run ECMPS.dbo.UPDATE_MON_PLAN_CONFIGURATION
            *   Update MONITOR_PLAN and MONITOR_PLAN_RERPORTING_FREQ begin and end quarters, and may create the records.
            *   May update MONITOR_PLAN_LOCATION records.
            *   Null SUBMISSION_AVAILABILITY_CD may indicated a new MP on the ECMPS Client, but not on the Host.  The retrieval of MP information and other MP might affect the unsubmitted MP.


MP Submit

    For the specified MON_PLAN_ID:
    
        1.  Set PENDING_STATUS_CD in MONITOR_PLAN to 'PENDING'.
        2.  Set PENDING_STATUS_CD in MONITOR_PLAN_COMMENT to 'PENDING'.

**Comment by djw4erg** [comment]
MP Comment Data Entry
    
    For the updated MONITOR_PLAN_COMMENT
    
        1.  Update athe follwing;
            a.  UPDATED_STATUS_FLG to 'Y' and LAST_UPDATED to Now.
            b.  PENDING_STATUS_CD to 'PENDUP' and UPDATE_DATE to Now when PENDING_STATUS_CD equals 'PENDING'.


MP Comment Retrieve

    For the retrieve MONITOR_PLAN_COMMENT
    
        1. Set SUBMISSION_AVAILABILITY_CD to the specified Submission Availability Code.
