### ISSUE TITLE
2.5.2 Manage RATA Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1883]
## Feature Benefit
Provide the ability to view, edit and create data 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1883?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP
