### ISSUE TITLE
2.2.3 Manage Cycle Time Injection Data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1893]
## Feature Benefit
Provide the ability to view, edit and create data 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by annalbrecht** [comment]
Please verify if this functionality exists. If so, please close this ticket.

**Comment by lgiannini1** [comment]
Confirmed I was able to add, edit, and remove Cycle Time Injection records using ORIS 3, 1,2,CS0AAN Cycle Time test number 5 on dev and test environments.

[QA & Certification _ Export - Barry  (2).json](https://github.com/US-EPA-CAMD/easey-ui/files/14793621/QA.Certification._.Export.-.Barry.2.json)
