### ISSUE TITLE
Manage Emissions Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1899]
Value: Provide the ability to manage administrative functions, such as user, submission windows, etc.

Include Error suppression functions as part of this module when worked

Required for Beta completeness:

- View, edit, and create all Emissions data sections (see diagram below)
- Import (including validations)
- Export
- Validation/Evaluation

**Comment by vishnunavuluri** [comment]
1/17/2023: Duplicate....confirmed with Alex
