### ISSUE TITLE
Prompt for Unsaved Changes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1903]
Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

User Story
As a User
I want to save my edits on a modal
So that I can see the updates

## Acceptance Criteria
Given a user made edits on a modal
When the user selects **Save and Close** 
Then the edits are saved and the modal closes

Given a user made edits on a modal
When the user selects **Cancel** 
Then the modal closes without saving the edits

Given a user made edits on a modal
And doesn't save the edits
When the user closes the modal (X)
Then the system displays a warning message: Closing this window will discard any unsaved changes.

Given a user made edits on a modal
When the user closes the Browser (Chrome/Firefox/Edge.....) without **Saving**
Then the edits are not saved

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC331](https://epacamd.testquality.com/project/11428/plan/19352/test/298302)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![1903 Prompt for Unsaved Changes.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9dd7ef1b-398b-4f9f-b5d7-7a699e04c206)

**Comment by mosesdeeCVP** [comment]
Test passed

**Comment by mosesdeeCVP** [comment]
There is a semi related bug:
[Inactivity timer during edit/create mode #1967](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1967)
