### ISSUE TITLE
Bug: Fix Data Preview Sort for numerical values 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1906]
### Actual Results
The data preview is not accurately sorting on numerical values. This issue is happening because numerical  values in the API endpoints are being returned as text values. This is applicable to all emissions sub types, allowance holdings, and allowance transactions. 

Values listed as null in the db will return as null. 

Values listed as 0 in the db will return as 0. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8f6eafcf-ed9c-4aa4-9385-69c175ddb07e)

Example Schema: 
Numerical values should return as red on swagger 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/06dcf136-2b20-43de-9b4e-02f2ea645e87)

Current Response body: 
Numerical values are returning as green, which indicates that the values are returning as text 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6a55ecf3-e12f-4f28-9304-724f8cc95729)

**Comment by tlageman-epa** [comment]
@JanellC  Can we get clarification on which data types/sub types this ticket is related to. Is this actually for allowance holdings or just emissions? Also, didn't the dev team demo this for allowance transactions yesterday and it was fine? thx!

**Comment by JanellC** [comment]
@tlageman-epa The developers brought this issue to my attention. To my understanding, this ticket is applicable to all the emissions data types and allowance holdings. However we need to have additional conversations about the scope of this ticket during refinement.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D75](https://epacamd.testquality.com/project/11428/result/2472701/defect/8328).

**Comment by JanellC** [comment]
Defect D75 resolved
