### ISSUE TITLE
Standardize ERDs for Emissions, Monitoring Plan, Facilities data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#191]
- [x] Review "read me" document for naming conventions and folder structure
- [x] Modify ERDs for a consistent theme and layout
- [x] Provide 2 versions of all files - raw file (.drawio) and readable (.pdf)
- [x] Review with @jwhitehead77 & @maheese & @j-tafoya & @ntknguyen 

A/C:
All three ERDs (Emissions, MP, Facilities) have a consistent theme and layout 
Read me document exists
2 versions of all files provided

**Comment by sdhawan16** [comment]
Met with Jason and Mo and finalized folder structure and naming conventions. Decided on format we will use to standardize ERDs.

**Comment by sdhawan16** [comment]
Determined how to upload the raw file (.drawio) to teams from diagrams.net
Meeting to review updated and standardized ERDs was scheduled for Wednesday at 4

**Comment by sdhawan16** [comment]
Completed standardized ERDs and uploaded to Teams, Reviewed ERDs with team and as per the feedback we will add Monitor_System_Component to Monitoring plan ERD

**Comment by sdhawan16** [comment]
Updated and standardized ERDs can be found in the Data Relationships folder within the emissions, facilities, and monitoring plan subfolders:  https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships

ReadMe file within the folder details what files are present and where they are located.
