### ISSUE TITLE
Update CAMPD tool tips

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1910]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the tool tips in the filter panels to display information So that I can understand the filters 

## Acceptance Criteria

Given that a user has applied filter criteria for data type and data sub type 
When the functionality is displayed 
Then the filters tool tip displays the appropriate message (see context) 

Given that a user has opened a filter panel that contains a tool tip  
When the filter panel functionality is displayed 
Then the tool tip is active (not grayed out) 

Given that the tool tip functionality is displayed 
When a user hovers over the tool tip 
Then the tool tips displays the appropriate message 

Given that the tool tip message is displayed 
When a user moves their mouse away from the tool tip 
Then the tool tip message disappears 

Given that a user has selected state or unit type 
When the filter panel functionality is displayed  
Then the filter panel does not contain a tool tip 

Given that a user has selected the time period filter for quarterly, monthly, annual emissions, and  facility/ unit attributes
When the filter panel functionality is displayed  
Then the filter panel does not contain a tool tip 

Given that a user has selected the time period filter for quarterly emissions  
When the filter panel functionality is displayed  
Then the appropriate text is displayed next to the check boxes (see context) 

Given that a user has selected the time period filter for hourly emissions 
When the functionality is displayed 
Then a tool tip is displayed by end of the operating hours only text 
AND the tool tip displays the appropriate message ( see context) 

## Developer Notes 
- The scope of this ticket does not include the custom data download landing page since the cdd landing page will be removed . scope includes all data type and sub types
- add language to tool tips in the filter panels 
- update all the tool tips to display with hover
- when a user moves their mouse away from the tool tip the message should disappear 
- The tool tip for operating hours only should be displayed at the end of the text 

## Dev Tasks

- [ ] Add tool tip language 

- [ ] Remove tool tips for state and unit type 

- [ ] Remove time period tool tips for quarterly emissions, monthly emissions, facility/ unit attributes, and annual emissions. 

- [ ] Add an additional tool tip for operating hours only 

- [ ]  For quarterly emissions, add text next to each checkbox selection. 

- [ ] 508 Escape key exits in combo boxes 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

Ticket Retest Only: Time Period Filter- EPA 508 Issue #2039 will be retested as apart of this issue 

## Context

[CAMPD Tool Tip Language Document
](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B6A1FE50E-3181-4B40-B099-0D4731978E04%7D&file=CAMPD%20Tool%20Tips-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

**Quarterly Emissions Check Box Language**
Q1: January 1 – March 31
Q2: April 1 – June 30
Q3: July 1 – September 30
Q4: October 1 – December 31

## Testing
Test Case: [TC482](https://epacamd.testquality.com/project/11428/plan/22258/test/313115)
Tester: @MaeganWood64 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by MaeganWood64** [comment]
@tlageman-epa [TC482](https://epacamd.testquality.com/project/11428/run/154118/result/fullscreen/2622145) Passed

**Comment by JanellC** [comment]
@aprematta This ticket is ready for 508 testing. Retest Only: Time Period Filter- EPA 508 Issue #2039 as apart of this ticket

**Comment by JanellC** [comment]
FYI- @tlageman-epa 
It was specified that the time period tool tip for hourly, daily, and transactions should display " If using the keyboard to navigate the date picker and the escape key does not work, try using the tab key then escape key". However these directions were not 100% accurate. The  time period tool tip for hourly, daily, and transactions were updated to display 'If using the keyboard to navigate the date picker and the escape key does not work, try using the Shift + Tab keys then the escape key'' since this is how a user would get out of the keyboard trap.
