### ISSUE TITLE
ECMPS - 508 Testing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1912]
## Epic Benefit
Issues that require 508 testing  @aprematta 

https://beacon.cvpcorp.com/display/PRAC/Developer

## Context

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
1302 is passed

**Comment by aprematta** [comment]
Testing for 1922 complete, adding audit report [https://app.zenhub.com/files/287570343/c84cab03-f68f-421a-8476-705e237a8283/download](https://app.zenhub.com/files/287570343/c84cab03-f68f-421a-8476-705e237a8283/download)

**Comment by aprematta** [comment]
Testing for 1766 complete, adding audit report [https://app.zenhub.com/files/287570343/acbc942c-ffe7-451e-9c99-34989236c7ab/download](https://app.zenhub.com/files/287570343/acbc942c-ffe7-451e-9c99-34989236c7ab/download)

**Comment by aprematta** [comment]
Testing for 1767 complete, same issues as 1766 but here is it's own audit report[https://app.zenhub.com/files/287570343/78324b09-a2b9-4e41-abef-b61f86d3e1ad/download](https://app.zenhub.com/files/287570343/78324b09-a2b9-4e41-abef-b61f86d3e1ad/download)

**Comment by aprematta** [comment]
Adding an audit report for additional issues found in the test environment that were not yet documented. [https://app.zenhub.com/files/287570343/548b0e09-e79a-4d38-9865-0ad510a33435/download](https://app.zenhub.com/files/287570343/548b0e09-e79a-4d38-9865-0ad510a33435/download)

**Comment by aprematta** [comment]
1180 passes testing

**Comment by aprematta** [comment]
1903 passes testing but there is a known bug between JAWS and Chrome that does not read the alert content. This should be out of scope for us though.

**Comment by aprematta** [comment]
1772 and 1781 have the same issues as 1767, 1766. There are also 2 additional issues documented in this audit [https://app.zenhub.com/files/287570343/7b78219e-9ede-446b-b22f-f53e8b3a5b89/download](https://app.zenhub.com/files/287570343/7b78219e-9ede-446b-b22f-f53e8b3a5b89/download)

**Comment by aprematta** [comment]
1921 testing is complete, adding audit report[https://app.zenhub.com/files/287570343/414cca35-28ac-41b5-8b74-151516562250/download](https://app.zenhub.com/files/287570343/414cca35-28ac-41b5-8b74-151516562250/download)

**Comment by aprematta** [comment]
1513 has passed testing

**Comment by aprematta** [comment]
1964 has a single issue [https://app.zenhub.com/files/287570343/de7c5513-4425-4090-8d4c-f620f691363a/download](https://app.zenhub.com/files/287570343/de7c5513-4425-4090-8d4c-f620f691363a/download)

**Comment by aprematta** [comment]
1924 has 3 issues, adding audit report[https://app.zenhub.com/files/287570343/f8bad95b-8fdc-4603-ab9b-8ff281ee270c/download](https://app.zenhub.com/files/287570343/f8bad95b-8fdc-4603-ab9b-8ff281ee270c/download), these issues also apply to 1923

**Comment by aprematta** [comment]
1774, 1775, 1802, 1776, 1768, 1780 and 1733 all have the same issues as 1767, 1766.

**Comment by aprematta** [comment]
629, 406, 405 have the same issues as stated in RF1 to RF 3 in the 1767 audit in regards to the functionality of the modal when view is selected.

**Comment by aprematta** [comment]
1965 passes

**Comment by aprematta** [comment]
1676 passes

**Comment by aprematta** [comment]
1706, 1707, 1697, 1698, 1711, 1710 have the same issues as1767

**Comment by aprematta** [comment]
1976 passes testing

**Comment by aprematta** [comment]
All 508 fixes tickets pass
