### ISSUE TITLE
Additional data migration/load for MP Beta Release

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1915]
The following tables need to be added to the MP Beta Release data migration package

**CAMDMD Schema**
1-EXEMPTION_TYPE_CODE

**CAMD Schema**
3-UNIT_EXEMPTION

**CAMDECMPSMD Schema**
1-ACCURACY_TEST_METHOD_CODE
1-CALIBRATION_SOURCE_CODE
1-CALIBRATION_STANDARD_CODE
1-CHECK_TYPE_CODE
1-EM_STATUS_CODE
1-EM_SUB_TYPE_CODE
1-ES_MATCH_DATA_TYPE_CODE
1-ES_MATCH_LOC_TYPE_CODE
1-ES_MATCH_TIME_TYPE_CODE
1-ES_REASON_CODE
1-INJECTION_PROTOCOL_CODE
1-MODC_CODE
1-MONITORING_PLAN_STATUS_CODE
1-TEST_BASIS_CODE
1-TEST_REASON_CODE
1-TEST_RESULT_CODE
1-TEST_TYPE_CODE
2-CHECK_CATALOG
2-PARAMETER_UOM
3-CHECK_CATALOG_RESULT
3-RULE_CHECK

**CAMDECMPS Schema**
2-EMISSION_EVALUATION
2-MONITOR_PLAN_COMMENT
3-MONITOR_QUALIFICATION
4-MONITOR_QUALIFICATION_LEE
4-MONITOR_QUALIFICATION_LME
4-MONITOR_QUALIFICATION_PCT
4-TEST_SUMMARY
5-FLOW_TO_LOAD_CHECK
5-FLOW_TO_LOAD_REFERENCE
5-FUEL_FLOWMETER_ACCURACY
5-QA_SUPP_DATA
5-UNIT_DEFAULT_TEST

**CAMDECMPSAUX Schema**
1-APPORTIONMENT
1-CHECK_SESSION
1-EM_SUBMISSION_ACCESS
1-ES_SPEC
1-PROGRAM_PARAMETER
2-APPORTIONMENT_RANGE
2-CHECK_LOG
3-APPORTIONMENT_DATA

Remove the following tables previously included from the data migration package
CAMDECMPS.COMPONENT_OP_SUPP_DATA
CAMDECMPSAUX.SUBMISSION_LOG

**Comment by vkdontula** [comment]
This is ready and refreshed data in both dev and stg instances.
