### ISSUE TITLE
ECMPS FAQs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1921]
ECMPS FAQs Prototype: https://xd.adobe.com/view/3024a3c8-e434-4270-b7dc-7cf464a42621-6577/

[USWDS Compo ](https://designsystem.digital.gov/components/accordion/)

All questions are closed by default
Multiple questions can be open at a time 
FAQ page is accessed via a link in the utility menu under help/support 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

**Comment by JorjaComer** [comment]
@mosesdeeCVP Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1921?planning-poker)

**Comment by JorjaComer** [comment]
@Qb10 @tdavydets Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1921?planning-poker)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC329](https://epacamd.testquality.com/project/11428/plan/19352/test/298193)

**Comment by mosesdeeCVP** [comment]
![1921 ECMPS FAQs.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9c64bcca-ef01-4093-85cc-8917a1d25b88)

**Comment by mosesdeeCVP** [comment]
Test Passed
