### ISSUE TITLE
ECMPS Home/Landing Page

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1922]
ECMPS Home/Landing Page Prototype: https://xd.adobe.com/view/a0d50a31-567b-49f0-9058-e98b42bb3b53-f586/

Log in is functional (from both login button/modal or login box). Log in box is removed and profile is visible  after successful login  
MP/QA/Emissions link are functional 
System banner is out of scope (need to determine how to dynamically update content) 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

**Comment by JorjaComer** [comment]
@mosesdeeCVP @Qb10 @tdavydets Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1922?planning-poker)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC330](https://epacamd.testquality.com/project/11428/plan/19352/test/298194)

**Comment by mosesdeeCVP** [comment]
![1922 ECMPS Home-Landing Page 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fa4755e4-df80-4aa6-a266-ed405ed90090)

**Comment by mosesdeeCVP** [comment]
![1922 ECMPS Home-Landing Page 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/57feacec-fb8e-4268-913d-48150c521d9a)

**Comment by mosesdeeCVP** [comment]
Test Passed
