### ISSUE TITLE
ECMPS Help/Support

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1923]
ECMPS Help/Support Prototype: https://xd.adobe.com/view/d6b82d3b-3cdd-4c28-8097-c9613c59d79f-83eb/

Dev Notes: Currently, the prototype for Contact Us has 'Application' as one of the fields. This is not needed. Please Remove 'Application' from the Contact Us form
- Also, the success message upon Submit will remain static for now

Layout:
- FAQs
- Tutorials

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

**Comment by akaashmanan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1923?planning-poker) with ZenHub @jwhitehead77 @tdavydets @jeffreyaggrey

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1923?planning-poker) with ZenHub @mosesdeeCVP

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1923?planning-poker) with ZenHub @Qb10

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1923?planning-poker) with ZenHub @tdavydets

**Comment by mosesdeeCVP** [comment]
Test Case: [TC358](https://epacamd.testquality.com/project/11428/plan/21815/test/299675)

**Comment by mosesdeeCVP** [comment]
![1923 ECMPS Help-Support - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/35d904c5-f8fe-4cfa-bb55-8ff3083efbe8)
![1923 ECMPS Help-Support - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/238aaee3-ecd0-477c-a48a-a9d3c5c62014)

**Comment by mosesdeeCVP** [comment]
Test Passed
