### ISSUE TITLE
ECMPS Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1924]
ECMPS Resources Prototype: https://xd.adobe.com/view/197b27f8-b125-4ee6-b916-7727dd50ed73-4c28/

CDX URL: https://cdx.epa.gov/

**Updates to the existing prototype:**

Under Additional Resources:
- Add 'Tutorials' (Tutorials page not available yet)
- Remove 'Webfire'

Notes: Tutorials and other clickable options (CDX, etc) are non-functional for now. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1924?planning-poker) with ZenHub @Qb10

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1924?planning-poker) with ZenHub @tdavydets

**Comment by akaashmanan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/1924?planning-poker) with ZenHub @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Case: [TC355](https://epacamd.testquality.com/project/11428/plan/21815/test/299583)

**Comment by mosesdeeCVP** [comment]
![1924 ECMPS Resources.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/98ebe457-9420-4ade-a331-b6b846cab2fc)

**Comment by mosesdeeCVP** [comment]
Test Passed
