### ISSUE TITLE
Data Migration/load of ARCHIVE tables for CAMPD Release #1

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1925]
The following tables need to be added to the CAMPD Release #1 data migration package

**CAMDDMW_ARCH**
1-ANNUAL_UNIT_DATA_A
1-DAY_UNIT_DATA_A
1-HOUR_UNIT_DATA_A
1-MONTH_UNIT_DATA_A
1-OZONE_UNIT_DATA_A
1-QUARTER_UNIT_DATA_A

NOTE: Please only load data for the following years (2016, 2015, 2014, 2013) into the above tables

**Comment by vkdontula** [comment]
This is ready and data has been loaded into Staging database.
