### ISSUE TITLE
Update JSON Properties

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1927]
Update properties in JSON file to reflect current import XML structure. Updates will be made in UI and API.

_JSON properties that are changing to match current XML for screens/data already being consumed by UI_

**AnalyzerRanges**
  componentId -> componentRecordId

**Methods**
  monLocId -> locationId
  methodCode -> monitoringMethodCode
  subDataCode -> substituteDataCode

**MATSMethods**
  monLocId -> locationId
  matsMethodParameterCode -> supplementalMATSParameterCode
  matsMethodCode -> supplementalMATSMonitoringMethodCode

**Components**
  monLocId -> locationId
  componentIdentifier -> componentId
  acquisitionMethodCode -> sampleAcquisitionMethodCode
  hgConverterInd -> hgConverterIndicator

**System Components**
  monLocId -> locationId
  monSysId -> monitoringSystemRecordId
  componentId -> componentRecordId
  componentIdentifier -> componentId
  acquisitionMethodCode -> sampleAcquisitionMethodCode
  hgConverterInd -> hgConverterIndicator

**Systems**
  monLocId -> locationId
  systemIdentifier -> monitoringSystemId

**System Fuel Flows**
  monSysId -> monitoringSystemRecordId
  maxRate -> maximumFuelFlowRate
  sysFuelUomCode -> systemFuelFlowUOMCode
  maxRateSourceCode -> maximumFuelFlowRateSourceCode

**Comment by mosesdeeCVP** [comment]
AnalyzerRanges:
![1927 - 1 - AnalyzerRanges.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dae997c3-0aec-4116-be38-3c131667fe90)

Methods:
![1927 - 2 - Methods.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ed7ae868-422d-4f4a-8a22-a4f9d55c16f6)

MATSMethods:
![1927 - 3 - MATSMethods.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9dacd561-bb60-4636-9641-effc510d77ec)

Components:
![1927 - 4 - Components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1e5222b3-eaec-4daf-bd40-d6bb79dc06e3)

System Components:
![1927 - 5 - System Components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c59acf23-92ee-46d8-a1df-5c76e49b9ac5)

Systems:
![1927 - 6 - Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3a1c01a5-f183-4a80-8c30-49ec44b691bf)

System Fuel Flows:
![1927 - 7 - System Fuel Flows.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1e0d7046-bc15-4e0b-b6f6-d65a3504fa26)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC332](https://epacamd.testquality.com/project/11428/plan/20171/test/299006)

**Comment by mosesdeeCVP** [comment]
Test Passed - Swagger

**Comment by mosesdeeCVP** [comment]
Fuel Flow section is not functioning properly, bug ticket created:
[Fuel Flow - Display Proper Data #1968](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1968)

**Comment by mosesdeeCVP** [comment]
MATS Methods bug ticket:
[Swap Parameter/Methodology for MATS Methods
](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1969)
