### ISSUE TITLE
Revisit data migration options

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#193]
- [x] Determine how to move data from on-premise databases to cloud systems that may be accessed by Team CVP
- [x] Work with folks from NCC, Cloud.gov, to determine available options

A/C:
Determine short-term and longer-term strategy for data migration from NCC to Cloud.gov systems

**Comment by jwhitehead77** [comment]
We are setting up a test using the EPA Informatica system where Informatica will connect to the NCC database as the source and send data to a VM within the NCC that will have established an SSH tunnel connecting to the database in cloud.gov.
