### ISSUE TITLE
Identify required FACT API endpoints for Monitoring Plan Viewer

### ISSUE THREAD

**Issue by SimeraHailu** [US-EPA-CAMD/PI-1#194]
- [x] Meet with @faqir-cvp to determine document template
- [x] Identify endpoints in FACT API that are required to display Monitoring Plan Tab 
 [https://www.epa.gov/airmarkets/monitoring-plans-part-75-sources]

A/C:
Single document of all identified endpoints uploaded to EPA Sharepoint

**Comment by junie-stigdon** [comment]
Split this task up from issue#79

**Comment by junie-stigdon** [comment]
Decided that this work was part of facilities endpoints. Changed the estimate from 3 to 1.

Deliverable for this is the same as issue #79 .
