### ISSUE TITLE
Utilize white space on data preview (resolution 1024 + only) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#1942]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the data preview white space to have instructions so I can understand how to use the tool 

## Acceptance Criteria

Given that a user has accessed the custom data download 
When the functionality is displayed 
Then the user is directed to select a data type and a data sub type ( data type and data sub type will be empty be default) 
AND the page is displayed in accordance with the [wireframes  ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343)

Given that a user has accessed the custom data download 
When filter criteria is applied for data type 
Then the data sub type functionality is enabled 

Given that a user has applied filter criteria for data type and data subtype 
When the functionality is displayed 
Then the apply functionality is enabled 

Given that a user has selected preview data 
When the data table is displayed 
Then the helper texted is removed

Given that data table is displayed 
When the data table is removed 
Then the helper text is displayed in the white space (see context) 

Given that a user has accessed the custom data download 
When the page renders 
Then the content is consistent with the [content document](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={07D28E24-6C3D-432B-B397-9DD1CD50A030}) (content, url, meta tags, etc...) 

## Developer notes 
- **This ticket is for resolution  1024 and above only** 
- Remove the custom data download landing page 
- the data type and data sub type filters should display select by default
- the scope of this ticket includes increasing the padding for the preview data button 

Users can access the custom data download through the CAMPD home page, the CAMPD header, and the data home page. Any buttons or links that link to the custom data download should be updated as needed. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Helper Text:** 

1.	Build a query by choosing a data type and subtype. Click Apply. 
2.	Refine query by using available filters. Selection must be made for required filter. 
3.	Click Preview Data to view data selection. 
4.	Activate the tool tips “?” to reveal helpful tips and info.

[Custom data download Content document ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={07D28E24-6C3D-432B-B397-9DD1CD50A030})

[
CAMPD CDD updates (dev) ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343)

[CAMPD CDD updates ](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1674%3A5177&scaling=min-zoom&page-id=1422%3A4343&starting-point-node-id=1674%3A5177)

## Testing
Test Case: [TC517](https://epacamd.testquality.com/project/11428/plan/22258/test/316897) 
Tester: @JanellC 

508 Testing 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@AllisonFrancis @JanellC A question came up on the designs for mobile/tablet. The mobile/table designs in this ticket do not reflect the changes that will need to be made as captured in the update responsiveness epic. I am assuming that the helper text will be added to designs as laid out in ticket 1615 first link under "Context" [Sidebar Wireframes - slides 4, 5](https://xd.adobe.com/view/f084825d-086d-452c-9e0a-a97049c65c46-a5d7/screen/3773a81b-42a1-450b-874e-b045f6e464d1/). But I just want to make sure all this work flows together. happy to discuss next week to help clear things up.

**Comment by AllisonFrancis** [comment]
@tlageman-epa @JanellC Hi Travis! Yes, this is something that i think needs more discussion. I shouldn't have assumed but i thought screens 4,5, and 6 are showing how the filters panel displays at those sizes. But screens 1,2, and 3 are the screens that will display the helper text. We can get clarification next week. Thanks again

**Comment by JanellC** [comment]
TC517 passed @tlageman-epa. This ticket is ready for 508 testing @aprematta
