### ISSUE TITLE
Design for ECMPS Resources (Need by 8/23)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1945]

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit —

Here are the links to the Resources page for review:

- [Resources](https://xd.adobe.com/view/197b27f8-b125-4ee6-b916-7727dd50ed73-4c28/)
- [Resources (dev)](https://xd.adobe.com/view/6c2fe2a3-0bfc-44cf-b3c7-5b9a53cec701-397c/)

**Comment by cvp-alexrobinson** [comment]
Moving edits to content document: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?viewid=18eab565%2D03ba%2D4600%2Da594%2D5eb27c0d799a&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2F6%2DContent%20Templates%2F2%2DUtility%20Menu%2F1%2DResources
