### ISSUE TITLE
System crashes switching back to Systems in different tab

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#1956]
If the user opens two different configuration tabs and selects Systems in one of them then Methods in the other and then tries to select the tab with Systems in it, the site crashes

Note: Test and confirm if still an issue

**Comment by mosesdeeCVP** [comment]
![1956 System crashes switching back to Systems in different tab.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c29f8648-7c70-4cb0-9528-6f4629f3da10)

**Comment by vishnunavuluri** [comment]
1/23/2023: Working as expected
