### ISSUE TITLE
Create Dropdowns for MP Load Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1963]
Fields for MP Load Data:

Normal Level: drop-down (Operating Level Code)
Second Level: drop-down (Operating Level Code)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC385](https://epacamd.testquality.com/project/11428/plan/21921/test/303713)

**Comment by mosesdeeCVP** [comment]
![1963 Create Dropdowns for MP Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4d569f8f-ec95-49c4-95bf-c5e01be71d5e)

**Comment by mosesdeeCVP** [comment]
Test Passed
