### ISSUE TITLE
ECMPS Resources - Responsiveness

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1965]
We want to "provide a usable view of ECMPS at all resolutions above 480 px" while ensuring that priority resolutions of 1024 px and above render correctly.

Responsiveness Wireframes: https://xd.adobe.com/view/6c2fe2a3-0bfc-44cf-b3c7-5b9a53cec701-397c/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC379](https://epacamd.testquality.com/project/11428/plan/21344/test/303524)

**Comment by mosesdeeCVP** [comment]
Test Passed
