### ISSUE TITLE
ECMPS 508 Testing - Report 1922 Fixes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1978]
Required Fixes:

RF-2: Headings are not properly coded                    
RF-3: Heading Tags Used on regular/ decorative Text
RF-4: Modal Dialog has incorrect Focus management
RF-5: Content for Screen Readers is hidden
RF-6: Duplicate ID values exist
RF-7: ARIA is incorrectly coded
RF-8: Multiple labels are associated to a single form field
from Report https://app.zenhub.com/files/287570343/c84cab03-f68f-421a-8476-705e237a8283/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by aprematta** [comment]
RF 2 through 7 pass. For RF-8 there needs to be an update for the label tags on the modal window. The for attribute of the label must match the id of the input. Update the for attributes to match the new id's of the input. Right now they don't match:

for="username"
id="modal-username" 
for="password"
id="modal-password"

**Comment by dionolympiaCVP** [comment]
labels for RF-8 are now fixed

**Comment by aprematta** [comment]
Change confirmed, testing complete and everything passes
