### ISSUE TITLE
ECMPS 508 Testing - Report 1767 Fixes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1979]
Required Fixes:

RF-1: Heading levels Improperly Structured and/or Skipped
RF-2: Modal Dialog has incorrect Focus management
RF-3: Content for Screen Readers is hidden
RF-4: Form Fields are Mislabeled
RF-5: Label does not match / include the text visually associated with the form field
RF-6: Generic Link/Button Text is Present and has no Context

Encouraged Fixes:

EF-1: Non-actionable Items Have Tab Stops 

from Report https://app.zenhub.com/files/287570343/78324b09-a2b9-4e41-abef-b61f86d3e1ad/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

These fixes are also applicable to issues reported for **1774, 1775, 1802, 1776, 1768, 1780, and 1733**

**Comment by aprematta** [comment]
On the Edit System dialogue, System Compenents and Fuel Flows are at an H4, they should be H3 since previous heading was an H2. Also..... it looks like the Add component and Create new fuel flow buttons are wrapped in H2 tags.....these should be removed since they are buttons, not headings - This is fixed

**Comment by aprematta** [comment]
It looks like RF-4 was not completed for the Add component modal - This is fixed

**Comment by aprematta** [comment]
Same heading issue for create analyzer range, h4 should be a h3 - This is fixed

**Comment by aprematta** [comment]
Supplemental methods modal does not return focus to view/edit link when close is activated - This is fixed

**Comment by dionolympiaCVP** [comment]
Resolved 508 findings stated above.  Ticket is ready for retesting.

**Comment by aprematta** [comment]
No more issues remain, closing ticket
