### ISSUE TITLE
ECMPS 508 Testing - General Fixes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1980]
Required Fixes:

RF-1: Generic Link/Button Text is Present and has no Context
RF-2: Expandable/Collapsible element lacks or has incorrect Role/State
RF-4: Dynamic content does not alert assistive technology when changes occur
RF-5: Visual Focus indicator is Missing
RF-6: Informational Image is Hidden to Assistive Technology
RF-7: Unexpected change with no prior indication when a form selection is made

from Report https://app.zenhub.com/files/287570343/548b0e09-e79a-4d38-9865-0ad510a33435/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by JorjaComer** [comment]
Ticket not completed in 5.6. Moved to 6.1 for completion

**Comment by aprematta** [comment]
RF-1: If you expand the configuration then collapse it again, the aria label reverts back to 'Expand Row'. Example: Initial label is 'Expand Barry', hit expand, label is 'Collapse Barry', hit collapse, label is 'Expand Row'

-----This has been fixed------

**Comment by aprematta** [comment]
RF-4: No change, countdown is still not announced
The initial window is not announced. the countdown is not but we're going to see if EPA is going to fail

**Comment by aprematta** [comment]
RF-6: The alt attribute is only for img tags. For SVG you have to pick one of these design patterns
This has been fixed

**Comment by aprematta** [comment]
RF-8: Still getting text overlap starting at 150% zoom
