### ISSUE TITLE
Determine Next Steps for Content Template (need by 9/8)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1984]
work with Tony D to determine what is needed for content template discussed with Alex. Need to be able to provide next steps to EPA on 9/8 Tech Team PD meeting.

**Comment by AllisonFrancis** [comment]
After discussions on this, we are not planning on doing templates in react. UI designs will be generated per usual, and dev will continue to develop from lo fi and hi fi wireframes.
