### ISSUE TITLE
Additional Data Migration & CDC for CAMPD Release #1

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#1986]
All tables in CAMD and CAMDDMW will need to be added to CDC

**CAMD Schema**
2-GENERATOR
2-UNIT - need to move from MP Beta Release package to CAMPD Release package
3-UNIT_GENERATOR

**CAMDMD Schema**
1-PRIME_MOVER_TYPE_CODE
1-GENERATOR_SOURCE_CODE

**CAMDDMW Schema**
1-OWNER_DISPLAY_FACT

The following fields in the table below contain html <br> due to the way that data is being used on the current AMPD website. However, the new system does not need that so can you please replace the <br> with a comma to create a comma separated list of values in those fields.

**_camddmw.owner_display_fact_**
own_display
opr_display

**_Example:_**
Current value: "Central Power and Light Company (Owner)<br>Sans Power LLC Company (Operator)"
New value: "Central Power and Light Company (Owner),Sans Power LLC Company (Operator)"

**Comment by vkdontula** [comment]
This is complete, loaded data for these tables in both Dev and Stg databases.
