### ISSUE TITLE
Add CASPAR G3

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1993]
## Epic Benefit

PI 6 estimate 2
Provide CASPAR G3 Data via custom data download and API endpoints 

applicable to all data sub types except for annual emissions and compliance (emission based) 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

applicable to all data sub types except for annual emissions and compliance (emission based) 

work includes updating the api and the database

**Comment by JanellC** [comment]
epic completed
