### ISSUE TITLE
ECMPS Contact Us - API Updates

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1995]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I need the ability to submit a query about the application, so I can seek help when needed

ECMPS Contact Us Email: ecmps-beta@camdsupport.com

Note: Dependent on Tech Teams task completion. Tech team shall be working on this ticket in 6.3

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
See #2151 on tech team board

**Comment by vishnunavuluri** [comment]
Contact Us Email
https://easey-dev.app.cloud.gov/quartz/api/triggers/notifications/emails
please set the purpose property to Contact ECMPS Support when using this from the Contact Us
These are protected by an API Key that must be passed in the x-api-key header
