### ISSUE TITLE
ECMPS UI Updates - Utility Nav

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1996]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want ECMPS UI to be updated so that the usability of the application is improved

## Acceptance Criteria
- Remove the login button from below the left menu on ECMPS home page
- Move the Login/Logout on the Utility Nav to the end
- Update the color on the User Profile option (#005EA2 -  Primary in the Design System)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
https://xd.adobe.com/view/c0323c1f-e508-4e16-8551-5f66caf78487-9561/

## Testing
Test Case: [TC398](https://epacamd.testquality.com/project/11428/plan/20792/test/305242)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by sanleyCVP** [comment]
@vishnunavuluri can you please specify the color in which the user initials need to be set to in Acceptance Criteria 3 of the ticket. Moses needs the information for testing

**Comment by mosesdeeCVP** [comment]
![1996 ECMPS UI Updates - Utility Nav.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6d712d11-fd85-4666-bfe8-2e9be10cc4fc)

**Comment by mosesdeeCVP** [comment]
Test Passed
