### ISSUE TITLE
Design Data Retrieval Initial Services

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#2]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597097705951) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD
  
Acceptance Criteria:

- When the customer visits the prototype, they will be able to download the prepackaged datasets for Emissions and Account data (using an API) in the formats elucidated previously.

**Comment by JorjaComer** [comment]
This work has been moved out of PI 1 and the design for this service will be done as part of the user stories that support the Emissions Data epics
