### ISSUE TITLE
Determine Spinner for All CAMD Apps (Need By 9/20)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#2007]
determine which spinner should be used and conditions for specific spinners, if needed.

**Comment by AllisonFrancis** [comment]
Here is the XD link for the discussion of the Submission Progress Bar and Spinner Options for global use.
https://xd.adobe.com/view/604a56eb-2df4-4f57-b9a0-569dc3ea2505-3519/

**Comment by AllisonFrancis** [comment]
Both Travis and Chris agree to use the Blue rotating dot version of the spinner that we currently use. It just needs to be updated for the login page.
