### ISSUE TITLE
ECMPS User Profile Options

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#2008]
- When a user is logged into ECMPS and clicks on the User Profile info, then the system expands the menu to display the following options:

Manage Login (CDX Link: https://cdx.epa.gov/)
Manage Delegations (CBS Link: https://camd.epa.gov/CBS/login/auth)

Note: We don't need a landing page. Just an expanding menu.

**Comment by AllisonFrancis** [comment]
@vishnunavuluri (please share your screen in PD call)
Here is a screen to discuss on Monday. I have addresses several tickets in part in this screen.
https://xd.adobe.com/view/c0323c1f-e508-4e16-8551-5f66caf78487-9561/
-moved the login button into the upper nav bar
-moved the welcome user and login to the right with in the bar
-updated the color of the profile icon to address contrast issue ticket in the backlog
-turned the comments and reports links to buttons and repositioned them to the left
-moved the "last checked out..." text to go above the "check back in" button
-updated the color of the configuration text in grey to meet 508 issue in backlog ticket

**Comment by sanleyCVP** [comment]
@vishnunavuluri should the links open in blank tabs?

The links will open new tabs with the CDX and CBS website login pages

**Comment by vishnunavuluri** [comment]
Test Cases Passed
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/12ad4700-6b65-4edc-9d64-954f10e9bc18)
