### ISSUE TITLE
Increase Code Coverage 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2010]
## Tasks

- [x] Remove USWDS table and related components

## Context 

Increase code coverage to at least 70%

**Comment by addisgmichael** [comment]
After removing uswds table components and adding more test cases, coverage for CAMPD UI is now at 73.5%. 
![image](https://user-images.githubusercontent.com/68253641/136276306-663432a7-5d3f-499d-9322-be8504edfe1e.png)
