### ISSUE TITLE
Bug: ##Typo on Add Component Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2017]
There is a typo on the Create New Component Modal where Modal needs to be updated to Model

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
![2017 Bug - Typo on Add Component Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1d7b805c-dc4f-47b6-aa25-7d1f2a634854)
