### ISSUE TITLE
Filter Custom Data Download By Transaction Type - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2019]
## Required Fix 

- [ ] RF-1

## Context 

See [audit report ]( https://app.zenhub.com/files/287570343/2f60fbc5-1558-455e-8128-3cdf9c7e0e25/download) for additional details and links 

| Issue | Issue Description  | How to Fix  |
|---|---|---|
| RF-1 | There is a label tag present with the form field(s), however it is not properly associated. The for= attribute of the label must match the id= attribute of the input tag. This issue is a violation of Section 508 and of WCAG 2.0 Success Criterion 1.3.1 | Properly associate a form label with all input elements. For further assistance see   Webaim Form Controls   W3 HTML Technique #44 |

## Testing

Tester: @aprematta

**Comment by aprematta** [comment]
This issue has been fixed

**Comment by aprematta** [comment]
This issue has been fixed
