### ISSUE TITLE
MDM Endpoints for MP Default Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2020]
Create MDM Endpoints for:

Operating Condition: dropdown
Source of Value: dropdown

**Comment by mosesdeeCVP** [comment]
Test Case: [TC380](https://epacamd.testquality.com/project/11428/plan/21902/test/303536)

**Comment by mosesdeeCVP** [comment]
![2020 MDM Endpoints for MP Default Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8c5a2ee2-40ef-41c7-8919-9e78f01f4c20)

**Comment by mosesdeeCVP** [comment]
Test Passed
