### ISSUE TITLE
Create MDM Endpoints for Monitor Spans

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2021]
Create MDM Endpoints for:

Span Scale: dropdown
Span Method: dropdown

**Comment by mosesdeeCVP** [comment]
Test Case: [TC374](https://epacamd.testquality.com/project/11428/plan/20424/test/303514)

**Comment by mosesdeeCVP** [comment]
![2021 Create MDM Endpoints for Monitor Spans - Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04069465-7870-4157-85ae-270728db2c5a)

**Comment by mosesdeeCVP** [comment]
![2021 Create MDM Endpoints for Monitor Spans - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/da02b148-7325-4299-8da1-db0faa8bf455)

**Comment by mosesdeeCVP** [comment]
Test Passed
