### ISSUE TITLE
508 Fixes - For Tickets 1772, 1781

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2022]
Required Fixes:

RF-1: The Function of a Button Cannot be Determined
RF-2: Grouped Form Fields Lack Fieldset and Legend

from the Report: https://app.zenhub.com/files/287570343/7b78219e-9ede-446b-b22f-f53e8b3a5b89/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by aprematta** [comment]
Testing complete, both issues fixed in all areas
