### ISSUE TITLE
508 Fixes - For Ticket 1921

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2023]
Required Fixes:

RF-1: Title of page is not accurate or generic
RF-2: Headings are not properly coded
RF-3: Duplicate ID values exist
RF-4: Tab Order of the page is not logical
from the Report https://app.zenhub.com/files/287570343/414cca35-28ac-41b5-8b74-151516562250/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by aprematta** [comment]
Testing complete, all issues resolved
