### ISSUE TITLE
508 Fixes - For Ticket 1964

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2024]
Required Fixes:

RF-1: Grouped Form Fields Lack Fieldset and Legend

from the Report: https://app.zenhub.com/files/287570343/de7c5513-4425-4090-8d4c-f620f691363a/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by aprematta** [comment]
Testing complete, issue was fixed
