### ISSUE TITLE
508 Fixes - For Ticket 1923, 1924

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2025]
Required Fixes:

RF-1: Title of page is not accurate or generic
RF-2: Headings are not properly coded 

from the Report: https://app.zenhub.com/files/287570343/f8bad95b-8fdc-4603-ab9b-8ff281ee270c/download

Developer Notes for 508 Compliance: https://beacon.cvpcorp.com/display/PRAC/Developer

**Comment by aprematta** [comment]
Testing complete, all issues resolved on Resources and Help and Support
