### ISSUE TITLE
Check Engine Check Session Implementation 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2026]
- ECMPS_AUX.Check.CheckSessionInit
  - [x] WIP by: simera
  - [x] Complete
- ECMPS_AUX.dbo.INS_CHECK_SESSION
  - [x] WIP by: simera
  - [x] Complete
- ECMPS_AUX.dbo.sp_GetNextSessionID
  - [x] WIP by: simera
  - [x] Complete

**Comment by SimeraHailu** [comment]
- Omit [dbo].[sp_GetNextSessionID] not used in new check engine 

- Remove WorkspaceSessionInit() & references to DbAuxConnection.GetNextSessionID();

-remove DmEm.UpdateReset in  CheckSessionInit
