### ISSUE TITLE
Remove Default Text from Dropdowns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2032]
Remove text displayed by default (prompting the user to make a selection for the field) right next to some of the data fields available on Create and Edit Modals for:

Selection from Sections dropdown:
- Methods
- Systems

Selection from within Systems:
- Analyzer Range
- System Component
- Fuel Flow

New Text: -- Select a value --
Reference:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/aa29e3c1-6985-4446-a818-426ee85e2e01)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC401](https://epacamd.testquality.com/project/11428/plan/19352/test/305372)

**Comment by mosesdeeCVP** [comment]
Test Passed
