### ISSUE TITLE
ECMPS - MP Comments (need by TBD)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2038]
- View Comments page/screen/window will display the Action History of Comments for that Facility at the selected Configuration Level 
Sample Comments:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/56c0f69b-73cd-483a-a19b-50afe5816fad)

**Steps to access View Comments button:**
- On ECMPS home screen, locate Monitoring Plans from the left hand menu and click on it
- On the Select Configurations screen, pick a Facility, expand and select any one of the Configurations
- On the Configurations page that you just opened, locate 'View Comments' button

**Comment by NadiaJL** [comment]
modal table>columns: monitoring plan, date/time, comments
+/-(only rows with more comments to view) user clicks + to view additional comments, the whole row will expand (+/- is own row to the right of comments column)

**Comment by vishnunavuluri** [comment]
@NJLCVP Here is a sample screenshot from an existing tool for one Configuration:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7e743dcf-0704-413d-9193-8aaa28750d35)

**Comment by NadiaJL** [comment]
@vishnunavuluri & @AllisonFrancis 
Monitoring Plan - View Comments - Desktop 1024
Shared Xd Document link: 
https://xd.adobe.com/view/04b8b6f9-d522-4016-9ac5-a777e8c533fa-51eb/

![MP-View Comments -Bordered table - 1000px.png](https://images.zenhubusercontent.com/620142521e8674037a915879/68921787-aa09-4673-9024-bd2de6dc0b07)
