### ISSUE TITLE
Retest Only: Time Period Filter- EPA 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2039]
## Required Fix 
| Page/ Screen | Description of Issue  | Test(s) | 508 Standard(s)  | WCAG 2.0 Standard(s) |
|---|---|---|---|---|
| Data Tupe> Time Period Filter | Encountered a keyboard trap condition. At Step 7, in 1.1.8 Set Filters, attempted to correct the date with the date picker while navigating via keyboard.  Once the date picker was opened, I used the up-arrow key and arrived at December 26 at which point keyboard navigation became trapped.   See Figure 3  | 4C | 1194.21(a) | 2.1.2 |

## Context 
Retest this issue along with ticket #1910 

[See EASEY September 2021 Test Report ](https://teams.microsoft.com/l/file/B819723F-1C93-4DC1-ACAA-EC3C650CA587?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F5-UI%20Design%2F02%20508%20and%20Accessibility%2FEASEY%20September%202021%20Test%20Report.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Figure 3: Keyboard navigation becomes trapped in calendar picker 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c8c6701d-0872-4557-bbdc-48e226d26b86)

Recommended solution : Suggest logging a bug with the vendor  and putting  instructions for this  issue in the tooltip

**Comment by JanellC** [comment]
This issue will be addressed when the team implements the tool tips for the filter panels in #1910.

**Comment by aprematta** [comment]
Testing complete, tooltips for date picker fields were addressed
