### ISSUE TITLE
ECMPS Monitoring Plan Evaluation - Updates to Prototype (need by 11/8)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2054]
- User clicks 'Evaluate' for a Monitoring Plan
- System calls API and kicks off the job
- Following Status is to be displayed:
Monitoring Plan Needs Evaluation. (Yellow Bar)
Your Monitoring Plan is queued for Evaluation. (Blue Bar)
Monitoring Plan Evaluation in Progress. No updates can be made at this time. (Blue Bar) "Orange?"
Monitoring Plan Evaluated Successfully. (Green Bar)

When eval completed: 
- Check MP back in and unlock the record 
- Notification on the UI about successful completion: 'Monitoring Plan Evaluated Successfully.' 
- Notification email to the user upon completion(includes eval report in the body of the email)
- User will need to log in to view the evaluation report from the link 
- User can view eval report within the ECMPS application 
- User can export eval report (can be handled via "print to PDF" in browser) from within the application 

Confirmations from the PO:
- When evaluating, the record will be checked out automatically by the System if the user hasn't done so already, and multiple MP evaluations at any given time are not feasible at this time
- Cannot provide real-time updates on the progress

**Notes from 11/1/2021:** Update the wireframes to remove the banner and utilize the 'Evaluation Status: Passed' field 
Status of **Passed** and **Passed with Errors** would be a hyperlink to the Monitoring Plan Evaluation Report

**Notes from 11/8/2021:** 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9a8e1a15-5159-48a4-9a52-e1f278e9d208)

**Comment by AllisonFrancis** [comment]
Made updates to Eval Status versions based on 11/8 PD discussion.
