### ISSUE TITLE
Update Sections Dropdown

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2055]
As an ECMPS User, I want the Sections dropdown to be updated, so that the options are displayed accurately.

Acceptance Criteria:

Given the user is on the Configuration tab/screen for a Facility
When the user clicks on the Sections dropdown
Then Span, Formula are displayed separately 
And Location Attributes is updated to **Location Attributes and Relationships**
And **Range**; **Stack/Pipe Information** and **Reporting Frequency** are not options in the drop-down anymore

**Comment by mosesdeeCVP** [comment]
![2055 Update Sections Dropdown.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f1f3ed1b-94b5-4b2a-aff9-555f48645f95)

**Comment by mosesdeeCVP** [comment]
Test Passed
