### ISSUE TITLE
Create MP Formula Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2057]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create a new Formula, so that I can add new data 

Acceptance Criteria:
_Given_ the user has selected **Formula** from the Sections dropdown
_When_ the user chooses to add a new formula (Create Formula)
_Then_ the system displays the create modal
_and_ the user can add new formula data 

Formula ID: Text
Parameter: Dropdown
Formula Code: Dropdown
Formula: Text  
Start Date: date picker, format mm/dd/yyyy
Start Time: Text, hh
End Date: date picker, format mm/dd/yyyy 
End Time: Text, hh

Given the user has added Formula data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the landing page for Formula data

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 62 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC392](https://epacamd.testquality.com/project/11428/plan/20423/test/303733)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2057 Create MP Formula Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0f882784-45cc-4022-8d10-eb21552faf26)
