### ISSUE TITLE
Update Fuel Type to Fuel Code for Systems

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2059]
- Remove **Fuel Type** field for Systems from Create, Edit and View modals
- Add a new field **Fuel Code** to Systems and this field shall be available in Create, View and Edit modals

**Comment by mosesdeeCVP** [comment]
![2059 Update Fuel Type to Fuel Code for Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7f5937d8-2c32-414c-b125-c510f34f55e5)

**Comment by mosesdeeCVP** [comment]
Test Passed: [TC132](https://epacamd.testquality.com/project/11428/plan/19812/test/277032)
