### ISSUE TITLE
Create MDM Endpoints for MP Defaults Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2060]
Create MDM endpoints for the following fields in MP Defaults data:

Purpose: dropdown
Fuel Code: dropdown

**Comment by mosesdeeCVP** [comment]
Test Case: [TC380](https://epacamd.testquality.com/project/11428/plan/21902/test/303536)

**Comment by mosesdeeCVP** [comment]
![2060 Create MDM Endpoints for MP Defaults Data 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93ae63af-6fc3-4102-8f73-3159854f3076)

![2060 Create MDM Endpoints for MP Defaults Data 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2dc39d21-f273-45c1-a89d-7c67554c20d3)

**Comment by mosesdeeCVP** [comment]
Test Passed
