### ISSUE TITLE
Site Map

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2063]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the site map So that I can understand how to navigate the site 

## Acceptance Criteria
Given that a user has accessed the site map
When the functionality is displayed 
Then the page renders in accordance with the wireframes 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Site Map](https://www.figma.com/proto/oH4mOXuXImz0q1E9qTkz1o/Site-Maps?node-id=247%3A1058&scaling=contain&page-id=247%3A1057)

[Site Map (dev)](https://www.figma.com/file/oH4mOXuXImz0q1E9qTkz1o/Site-Maps?node-id=247%3A1058)

Example: https://www.homedepot.com/c/site_map

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
The site map will no longer be included in the first release of CAMPD. See below for additional context. 

From: [12:27 PM] Lageman, Travis on 11/10/2021

Allison Francis (Guest) janell coleman (Guest) I was reviewing EPA's web policies/procedures and noticed that there wasn't anything requiring a site map. After checking with our web guy, I would like to deprioritize this work and not include it in CAMPD 1.0 at this point. It is a "nice to have", so please do not spend any additional time on this and let's adjust the tickets in the backlog. I've shared this with Chris & Michelle also. We can update the header/menu when we make the changes to the home page with the viz/analysis section & what's new box. Thx!

**Comment by tlageman-epa** [comment]
Closing as site map is not required.
