### ISSUE TITLE
Remove Import a MP, Submit and Evaluate from Global View

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2065]
Remove the following options from the Global/Non-logged-in View in ECMPS:

- Import a Monitoring Plan
- Evaluate
- Submit
- Revert to Official Record
- Status Fields for Evaluation and Submission

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5d7e06e9-96bb-4df1-977a-88531e68bd3d)

**Comment by mosesdeeCVP** [comment]
Test Case [TC402](https://epacamd.testquality.com/project/11428/plan/19352/test/305568)

**Comment by mosesdeeCVP** [comment]
![2065 Remove Import a MP, Submit and Evaluate from Global View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bb9033a6-dad5-4ea0-8dc1-153a9a9ee285)

**Comment by mosesdeeCVP** [comment]
Test Passed
