### ISSUE TITLE
Spike: Apply filter logic to allowance transactions 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2067]
## Context 

Research the database query to arrive at the filter logic for allowance transactions

**Comment by sdhawan16** [comment]
Spike Outcome:
[Filter Logic Queries - EPA CAMD - v1.0.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7402392/Filter.Logic.Queries.-.EPA.CAMD.-.v1.0.docx)

SELECT DISTINCT tbd.vintage_year, tf.prg_code, tf.buy_acct_number, tf.sell_acct_number, tf.buy_account_type, tf.sell_account_type, tf.buy_orispl_code, tf.sell_orispl_code, tf.buy_state, tf.sell_state, tf.transaction_type, aodb.own_display as buy_own_display, aods.own_display as sell_own_display
FROM camddmw.transaction_block_dim tbd
JOIN camddmw.transaction_fact tf
  ON tbd.transaction_id = tf.transaction_id
  AND tbd.prg_code = tf.prg_code
LEFT JOIN camddmw.account_owner_dim aodb
  ON tf.buy_acct_number = aodb.account_number
  AND tf.prg_code = aodb.prg_code
LEFT JOIN camddmw.account_owner_dim aods
  ON tf.sell_acct_number = aods.account_number
  AND tf.prg_code = aods.prg_code
WHERE tf.transaction_date BETWEEN '2019-01-01' AND '2020-12-31'

There WHERE condition will change depending on the dates provided

**Comment by sdhawan16** [comment]
Updated Query - 
[Filter Logic Queries - EPA CAMD - v1.4.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7420450/Filter.Logic.Queries.-.EPA.CAMD.-.v1.4.docx)

SELECT DISTINCT tbd.vintage_year, tf.prg_code, tf.buy_acct_number, tf.sell_acct_number, tf.buy_account_type, tf.sell_account_type, tf.buy_orispl_code, tf.sell_orispl_code, tf.buy_state, tf.sell_state, tf.transaction_type, tod.own_display
FROM camddmw.transaction_block_dim tbd
JOIN camddmw.transaction_fact tf
  ON tbd.transaction_id = tf.transaction_id
  AND tbd.prg_code = tf.prg_code
LEFT JOIN camddmw.transaction_owner_dim tod
  ON tf.transaction_id = tod.transaction_id
  AND tf.prg_code = tod.prg_code
WHERE tf.transaction_date BETWEEN '2019-01-01' AND '2020-12-31'

There WHERE condition will change depending on the dates provided
