### ISSUE TITLE
'Continue' button opens Create Component Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2082]
Steps:

- User clicks on **Add Component** from 'View/Edit' modal for System
- On the Add Component modal, when the user clicks Continue without making a selection for 'Select Component by ID or Type', the system opens up the Create Component modal.

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3c2db583-53d1-44ba-b602-e424ffa34f38)

Expected Behavior: Prompt the user to make a selection from 'Select Component by ID or Type' drop-down

The buttons can be renamed 'Add Existing Component' and 'Create New Component'
**Note:** Disable the 'Add Existing Component' option until a user has made a selection for 'Select Component by ID or Type' 
Also add Select a value to the dropdown

**Comment by mosesdeeCVP** [comment]
![Continue button opens Create Component Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bdc06bff-603c-4de8-b088-0767fb515a82)

**Comment by mosesdeeCVP** [comment]
Bug fixed
