### ISSUE TITLE
Testing Only: Highlight Active tabs from the left navigation

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2083]
When a user accesses one of the options from the left navigation, then it is not very obvious which option has been selected.

Options should be highlighted based on what the user is working on 

Reference: https://designsystem.digital.gov/components/side-navigation/

**Comment by mosesdeeCVP** [comment]
![2083 Testing Only- Highlight tabs from the left navigation.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/05330d1f-7113-4152-9e53-fee84f468984)

**Comment by mosesdeeCVP** [comment]
Highlight tabs have been implemented
