### ISSUE TITLE
TASK: Update EASEY Constance shared library

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2087]
Background: through pair programming/ code review  validate that the properties are there, the sample data is there, and that the shared library has been packaged and published to github packages 

Applicable to all data types (emissions, account, compliance) and Datateers MDM endpoints 

**Datateers MDM endpoints:** 
control technologies 
fuel types 
unit types 
programs 
account types 
states 
transaction types 
source categories

**Comment by junie-stigdon** [comment]
npm install @us-epa-camd/easey-constants@0.0.7
