### ISSUE TITLE
508: Update Button Colors and Contrast

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2090]
1. Buttons on the application homepage have the wrong background for Accent Cool, Hover, and Active Properties. 
Reference: 
$eds-accent-cool: #00bde3;
$eds-accent-cool-hover: #28a0cb;
$eds-accent-cool-active: #07648d;

2. Update the font color in the button to #000000 for proper contrast

Locations to be updated:
Home Screen: 
- View Monitoring Plans
- View QA & Certifications
- View Emissions

**Comment by aprematta** [comment]
I'm still getting low contrast of 3.0:1 for the hover state, it needs to be at least 4.5:1
![image.png](https://images.zenhubusercontent.com/5f4e4654f75e20d725e0639d/ae563601-98cf-4881-a776-c40a3f636f29)

**Comment by aprematta** [comment]
Text changed to black and now has a contrast of 7:1, closing ticket
