### ISSUE TITLE
Update system behavior when user selects "--Select a value--" from dropdowns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2100]
As an ECMPS user, I want the system to save my updates accurately when I make selections from a dropdown so that I can choose to leave my selection as "--Select a value--"

Acceptance Criteria:

Given I pick **--Select a value--** from a dropdown on any of the create/edit modals
Or choose not to make a selection from a dropdown on the create/edit modals
When I save my updates
Then the updates should be reflected in the system

Fix: Remove the empty space below **--Select a value--** in the dropdowns

Dev Notes:
Currently, the user cannot save data if a dropdown has the "-- Select a value --" option selected.  The front-end is attempting to send an invalid value to the endpoint ("select").

Fix all of the following dropdowns to assign a null value (empty string) to its corresponding field when the default option is selected:

**Default:**
Parameter
Units of Measure
Purpose
Fuel Code
Operating Condition
Source of Value
 
**Load:**
Maximum Load Units of Measure
Normal Level
Second Level
 
**Method:**
Parameter
Methodology
Substitute Data Approach
Bypass Approach
 
**Span:**
Component Type
Span Scale
Span Method
Span Units of Measure
 
**System:**
System Designation
System Type
Fuel Code (changed from Fuel Type this Sprint)
 
**System Components:**
Sample Acquisition Method
Component Type
Basis Description
 
**Analyzer Range:**
Range

**System Fuel Flow:**
Units of Measure Code
Maximum Fuel Flow Rate Source

**Formula**
Parameter
Formula Code

**Loads**
Maximum Load Units of Measure
Normal Level
Second Level

**Rectangular Duct WAFs**
WAF Method

**Unit Fuels**
Fuel Type
Indicator Code
Dem SO2
Dem GCV

**Unit Controls**
Equipment Parameter Code
Control Code

**Comment by mosesdeeCVP** [comment]
![2100 Update system behavior when user selects --Select a value-- from dropdowns.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/abd7ffc6-b3b2-4334-b092-b50ab271ef58)

**Comment by mosesdeeCVP** [comment]
Test Passed
