### ISSUE TITLE
ECMPS UI Updates - Monitoring Plan Screen Updates

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2102]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want ECMPS UI to be updated so that the usability of the application is improved

## Acceptance Criteria
- When a user has multiple tabs for Configurations open, the color of the Inactive tab should be updated to a darker grey.  Update the color on the locked Configuration tabs to a darker grey ( #Base Dark 565C65)
- Move the 'Last Checked out by' information
- Update 'View Comments' and 'Reports' links to buttons (same as Evaluate and Submit)
- Move the 'View Comments' and 'Reports' buttons next to Check back in
- Remove pagination on any configuration tabs (Defaults, Loads, Spans from the Sections Dropdown)
- Remove Keywords Filter on any configuration tabs (Defaults, Loads, Spans from the Sections Dropdown)
- Move Evaluate and Submit buttons as in the prototype above the Revert to Official Record 
- Update the background for Evaluate and Submit buttons to a darker blue (Blue Base #005EA2)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
https://xd.adobe.com/view/c0323c1f-e508-4e16-8551-5f66caf78487-9561/

## Testing
Test Case: [TC399](https://epacamd.testquality.com/project/11428/plan/19352/test/305361)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2102 ECMPS UI Updates - Monitoring Plan Screen Updates.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/19f17d3c-f79f-4e4d-9ccd-f3851d265afd)

**Comment by mosesdeeCVP** [comment]
Test Passed
