### ISSUE TITLE
Consolidate shared code into a common package

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#2103]
We are amassing quite a it of common code between the api's that is currently being copied and included into the source code for each api. All this code needs to be extracted into a common package that can be shared across all api's.

**Steps & Tasks**
1. Convert existing easey-constants repo to be the easey-common repo
2. Move any possible shared piece of code into the package
3. Build & publish the package to github packages

**Structure & Candidates**
```
@us-epa-camd/easey-common
src/
   constants/ --> _*** any and all shared constants ***_
      error-messages.constants.ts      
      property-metadata.constants.ts
   decorators/
      current-user.decorator.ts --> monitor-plan-api
   enums/ --> _*** any and all shared enums ***_
      state.enum.ts
      unit-type.enum.ts
      ...
   guards/
      auth.guard.ts --> monitor-plan-api
   interceptors/
      json2csv.interceptor.ts --> emissions-api
   logger/
      logger.module.ts --> auth-api
      logger.service.ts --> auth-api
   maps/
      base.map.ts --> any api
   pipes/ --> _*** any and all common pipes ***_
      is-valid-date.pipe.ts
      is-valid-number.pipe.ts
      ...
   utilities/
      parse-token.ts --> monitor-plan-api
```

**Comment by junie-stigdon** [comment]
Notes on shared resources: 

https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/Tech/API/Shared%20Resources/API_Shared_Resources_Notes-EPACAMD-v1.0.xlsx?d=wc0c2d5c1dbc24115bb672c0a0bf086fa&csf=1&web=1&e=UDatO0
