### ISSUE TITLE
Spike: Apply filter logic to compliance (allowance based) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2106]
## Context 

Research the database query to arrive at the filter logic for compliance (allowance based) in order to provide query optimization

**Comment by sdhawan16** [comment]
Spike Outcome:
[Filter Logic Queries - EPA CAMD - v1.0.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7402391/Filter.Logic.Queries.-.EPA.CAMD.-.v1.0.docx)

SELECT DISTINCT acd.op_year, af.prg_code, af.orispl_code, af.state, aod.own_display
FROM camddmw.account_compliance_dim acd
JOIN camddmw.account_fact af
  ON acd.account_number = af.account_number
  AND acd.prg_code = af.prg_code
LEFT JOIN camddmw.account_owner_dim aod
  ON af.account_number = aod.account_number
  AND af.prg_code = aod.prg_code

**Comment by sdhawan16** [comment]
Updated Query - 
[Filter Logic Queries - EPA CAMD - v1.4.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7420440/Filter.Logic.Queries.-.EPA.CAMD.-.v1.4.docx)

SELECT DISTINCT acd.op_year, af.prg_code, af.orispl_code, af.state, oyd.own_display
FROM camddmw.account_compliance_dim acd
JOIN camddmw.account_fact af
  ON acd.account_number = af.account_number
  AND acd.prg_code = af.prg_code
LEFT JOIN camddmw.owner_year_dim oyd
  ON af.unit_id = oyd.unit_id
  AND acd.op_year = oyd.op_year
