### ISSUE TITLE
Manage QA/Certification Test Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#211]
Value: Validates the reliability of Emissions Data collected as part of mandated monitoring 

Note this refers to QA Test data for EASEY In 

Required for Beta completeness:

- View, edit, and create all QA data sections (see diagram below)
- Import (including validations)
- Export
- Validation/Evaluation

[Link to Invision board ](https://projects.invisionapp.com/freehand/document/TdahPfbEb)

[Link to Process Flows ](https://teams.microsoft.com/l/file/A8957212-51A9-477B-9442-8F700A83EE3F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=vsd&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2F3-Business%20Analysis%2FEASEY%20In%20To%20Be%20Process%20Flows-EPA%20CAMD-v2.0.vsd&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

![image](https://user-images.githubusercontent.com/67168611/128561294-6a7f31f7-5510-4c6a-a3b8-91370f0b2cf2.png)

![image](https://user-images.githubusercontent.com/67168611/128565385-392bf4b5-57cf-4425-bc69-568106d0c0a7.png)

![image](https://user-images.githubusercontent.com/67168611/128565426-bc66ce1a-b1cf-45f0-84f2-049bef18d9e0.png)

**Comment by vishnunavuluri** [comment]
-	QA data Check Engine evaluation/validation shall be against the workspace monitoring plan
-	QA data shall be entered into or imported into a set of workspace tables similar to monitoring plan
-	QA data can only be evaluated when there is a clean MP available i.e. MP Evaluation Status = Passed
-	If a monitoring plan has changes then mp has to be evaluated & submitted before QA can be evaluated & submitted or both can be submitted together
-	If changes are made to a monitoring plan after a passing evaluation, then both MP & QA data has to be re-evaluated
-	When evaluating QA data, the monitoring plan has to have a passing eval or you cannot evaluate the QA data

**Comment by annalbrecht** [comment]
At the ECMPS 2.0 ticket refinement meeting held on 2/13/24, Chris instructed us to close Uber Epics.
