### ISSUE TITLE
Bug: Custom Data Download Retains filter criteria after leaving the tool 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2110]
### Actual Results

1. The custom data download is retaining filter criteria if a user applies filter criteria and then navigates to another page on CAMPD. 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/87a10554-9ccd-451a-9044-1bb3e9c7e876)

To replicate the bug: 

1. Navigate to CDD https://easey-dev.app.cloud.gov/campd/select-data-type
2. Select Emissions 
3. Select Hourly Emissions and apply the criteria 
4. Apply filter criteria for time period 
5. Navigate to the CAMPD home page 
6. Navigate to the CDD https://easey-dev.app.cloud.gov/campd/select-data-type
7. Select Emissions 

The system should not retain filter criteria after a use leaves the custom data download. When a user leaves the cdd then the applied filter should be cleared.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D97](https://epacamd.testquality.com/project/11428/result/2513082/defect/9706).

**Comment by MaeganWood64** [comment]
Defect D97 Resolved @tlageman-epa
