### ISSUE TITLE
Address clear all functionality for filter logic 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2113]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the custom data download to update the filters when I clear all the filter tags So that I can create a dataset 

## Acceptance Criteria

Given that the emissions filter logic is engaged
When the clear all functionality is selected    
Then all the filters tags and filters are cleared, the user is required to apply filter criteria for time period first,
AND the optional filters are greyed out until time period criteria is applied

Given that a user has applied filter criteria for an allowance sub type 
When the clear all functionality is selected
Then all the filters tags and filters are cleared 

Given that a user has applied filter criteria for a compliance sub type 
When the clear all functionality is selected
Then all the filters tags and filters are cleared 

Given that a user has applied filter criteria for a data sub type 
When the sub type is changed 
Then all previously selected criteria are cleared 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

The functionality for clear all will not change. The development work in this ticket is geared toward efficiently retrieving data. 

## Testing
Test Case: [TC405](https://epacamd.testquality.com/project/11428/plan/21762/test/306546)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC405 passed @tlageman-epa

**Comment by JanellC** [comment]
This ticket is ready for 508 testing @aprematta

**Comment by aprematta** [comment]
For 2113..... only see 1 potential issue. I'm not sure if it will be flagged on the EPA 508 review or not, kind of 50/50. When clear all is activated, focus goes to the top of the page. I would suggest focus going back to the Time Period button since that is where they would have to start over. Maybe put this as an enhancement now and give higher priority if it comes back on the EPA 508 scan.
