### ISSUE TITLE
Error when using the tab key to navigate

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2116]
The system consistently throws an error when a user uses the tab key on the keyboard to navigate. It seems to occur right after you tab past the Actions header in the tables

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6eefd969-8609-4426-96a6-3e0a150a6c4d)

Developer Notes: When you tab past the Actions header, the code is checking for a sort icon that doesn't exist (it exists for the rest of the columns).

**Comment by aprematta** [comment]
Testing complete, hit all the instances of the table I could find and error did not occur
