### ISSUE TITLE
Create Monitoring Qual LME Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2119]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create new Monitoring Qual LME Data, so that I can add new data 

Acceptance Criteria:
_Given_ the user has selected **Qualifications** from the Sections dropdown
_When_ the user chooses to add a new Qualification for LME (Create Qual LME)
_Then_ the system displays the create modal
_and_ the user can add new LME Qualifications data 

Qualification Data Year: drop-down (Starting 2000 to ending in current year+ 2 years) 
Operating Hours: Text
SO2 Tons: Text
NOx Tons: Text

Given the user has added LME Qualifications data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the landing page for Qualifications data

Warning message to pop-up when a user updates data and closes the modal without saving the updates.

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 129 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC502](https://epacamd.testquality.com/project/11428/plan/22483/test/315949)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2119 Create Monitoring Qual LME Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/28902f03-6614-4a2b-9f6c-c576e3fcfdcc)

**Comment by mosesdeeCVP** [comment]
Test Passed
