### ISSUE TITLE
Create MDM Endpoints for Monitoring Qual Percent Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2120]
Create MDM Endpoints for Monitoring Qual Percent Data:

Year 1 Qualification Data Type Code: drop-down
Year 2 Qualification Data Type Code: drop-down
Year 3 Qualification Data Type Code: drop-down

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/d26cf1d0-2671-47b3-a4ea-94bfdb575a9a)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC436](https://epacamd.testquality.com/project/11428/plan/22483/test/309217)

**Comment by mosesdeeCVP** [comment]
![2120 Create MDM Endpoints for Monitoring Qual Percent Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/eb9763ec-5fc7-4230-b78c-042a22c00de2)

**Comment by mosesdeeCVP** [comment]
Test Passed
