### ISSUE TITLE
Create Monitoring Qual Percent Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2121]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create new Monitoring Qual Percent Data, so that I can add new data 

Acceptance Criteria:
_Given_ the user has selected View/Edit for **Qualifications**
_When_ the user is on the Qualifications modal and chooses to add new Monitoring Qual Percent Data (Create Qual Percent)
_Then_ the system displays the create modal for Qual Percent Data
_and_ the user can add new Monitoring Qual Percent Data

Qualification Year: drop-down (Starting 2002 to ending in current year+ 2 years)
Average Percentage Value: Text
Data Year 1: Qualification Year: drop-down (Starting 2002 to ending in current year+ 2 years)
Year 1 Type Code: drop-down
Year 1 Percentage Value: Text
Data Year 2: Qualification Year: drop-down (Starting 2002 to ending in current year+ 2 years)
Year 2 Type Code: drop-down
Year 2 Percentage Value: Text
Data Year 3: Qualification Year: drop-down (Starting 2002 to ending in current year+ 2 years)
Year 3 Type Code: drop-down
Year 3 Percentage Value: Text

Given the user has added Monitoring Qual Percent Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Qualification data modal

Warning message to pop up when a user updates/adds data and closes the modal without saving the updates.

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 134 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC486](https://epacamd.testquality.com/project/11428/plan/22483/test/314339)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2121 Create Monitoring Qual Percent Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4fdee1f0-086a-49ef-ad06-a6519b8d6054)

**Comment by mosesdeeCVP** [comment]
Test Passed
