### ISSUE TITLE
View Monitoring Qual Percent Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2122]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production Monitoring Qual Percent Data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Qualifications** from the Sections dropdown
When the Monitoring Qual Percent Data is displayed
Then the data is displayed in a single table (see list below for columns and order)

**On the View Qualification Modal:**
Qualification Year
Average Percentage Value
Data Year 1
Data Year 2
Data Year 3

**On the View Qualification Percent Modal:**
Qualification Year
Average Percentage Value
Data Year 1
Year 1 Type Code
Year 1 Percentage Value
Data Year 2
Year 2 Type Code
Year 2 Percentage Value
Data Year 3
Year 3 Type Code
Year 3 Percentage Value

Given a user is viewing Monitoring Qual Percent Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 134): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC447](https://epacamd.testquality.com/project/11428/plan/22483/test/310146)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2122 View Monitoring Qual Percent Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e356d49-94c4-4df5-8b1e-73e3f715dd54)

![2122 View Monitoring Qual Percent Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/151c07c1-8e0c-42e9-8bca-5ddfccff96a3)

**Comment by mosesdeeCVP** [comment]
Test Passed
