### ISSUE TITLE
Create MDM Endpoints for Monitoring Qual LEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2124]
Create MDM Endpoints for Monitoring Qual LEE Data:

Parameter Code: drop-down (previously done)
Qualification Test Type: drop-down
Units of Standard: drop-down (previously done -- subset of Units of Measure codes :"LBTBTU", "LBMBTU", "LBMWH", "LBGWH")

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/7f381006-b25b-4fce-aef1-09e11234fbfb)

GET endpoint for Qualification Test Type

**Comment by mosesdeeCVP** [comment]
Test Case: [TC435](https://epacamd.testquality.com/project/11428/plan/22483/test/309216)

**Comment by mosesdeeCVP** [comment]
![2124 Create MDM Endpoints for Monitoring Qual LEE Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3138dd2b-c9ad-45cb-8784-623f00dd07b5)

**Comment by mosesdeeCVP** [comment]
Test Passed
