### ISSUE TITLE
Create Monitoring Qual LEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2125]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create new Monitoring Qual LEE Data, so that I can add new data 

Acceptance Criteria:
Given the user has selected View/Edit for Qualifications
When the user is on the Qualifications modal and chooses to add new Monitoring Qual LEE Data (Create Qual LEE)
Then the system displays the create modal for Qual LEE Data
and the user can add new Monitoring Qual LEE Data

Qualification Test Date: date picker, format mm/dd/yyyy
Parameter Code: drop-down
Qualification Test Type: drop-down
Potential Annual Hg Mass Emissions: Text
Applicable Emission Standard: Text
Units of Standard: drop-down
Percentage of Emission Standard: text

Given the user has added Monitoring Qual LEE Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Qualification data modal

Warning message to pop up when a user updates/adds data and closes the modal without saving the updates.

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 145 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC491](https://epacamd.testquality.com/project/11428/plan/22483/test/315240)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2125 Create Monitoring Qual LEE Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fa94f269-e827-4092-a5c0-5cd0405c5ccc)

**Comment by mosesdeeCVP** [comment]
Test Passed
