### ISSUE TITLE
Create MDM Endpoints for MP Unit Control Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2129]
Create MDM Endpoints for MP Unit Control Data:

Parameter Code: drop-down
Control Code: drop-down
Original Code: drop-down

**Comment by dionolympiaCVP** [comment]
Parameter Code and Control Code (Control Technologies) are already implemented in the MDM API.
Original Code does not require a dropdown/endpoint (values are 0/1, so will use radio buttons)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/bbbe87ad-e941-40bd-9dde-9e9e1bf70120)

**Comment by vishnunavuluri** [comment]
Verified in Swagger that Parameter Code and Control Code are available as pointed by @dionolympiaCVP 
Updated tickets #2132, #2131 as Original Code: Radio-button
