### ISSUE TITLE
View MP Unit Control Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2130]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production MP Unit Control Data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Unit Information** from the Sections dropdown
When the MP Unit Control Data data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Equipment Parameter Code
Control Code
Original Code
Install Date
Optimization Date
Seasonal Controls Indicator
Retire Date

Given a user is viewing MP Unit Control Data 
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 17): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC419](https://epacamd.testquality.com/project/11428/plan/22363/test/308788)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2130 View MP Unit Control Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9cceff5d-f0bb-4a31-8976-cf5a582f10e0)

![2130 View MP Unit Control Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d6cbda47-4979-41c6-aef6-7ad1e9dc5d1b)

![2130 View MP Unit Control Data - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/97151d28-b575-42f4-98cb-6563afe0ef34)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![2130 View MP Unit Control Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d4384c4d-f340-4718-b9fb-7c53ed09d163)

![2130 View MP Unit Control Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/eb9a3242-e981-4451-9f20-a2e35d06361b)

![2130 View MP Unit Control Data - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d289f6d2-28b9-4b46-90c4-6a0092c9a744)

![2130 View MP Unit Control Data - 4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9b57fa4d-4819-4faa-a725-13696741cb9f)

**Comment by mosesdeeCVP** [comment]
Test Passed
