### ISSUE TITLE
Create MDM Endpoints for MP Unit Fuel Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2133]
Create MDM Endpoints for MP Unit Fuel Data:

Fuel Code: drop-down
Indicator Code: drop-down
Dem GCV (Demonstration Method to Qualify for Monthly Fuel Sampling for GCV): drop-down
Dem SO2 (Demonstration Method to Qualify for Daily or Annual Fuel Sampling for %S (ARP): drop-down

**Comment by mosesdeeCVP** [comment]
![2133 Create MDM Endpoints for MP Unit Fuel Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/804121d5-af14-4aed-a18d-82c0bf3d6c74)

**Comment by mosesdeeCVP** [comment]
Test Case Passed
Test Case: [TC410](https://epacamd.testquality.com/project/11428/plan/22363/test/308122)

**Comment by mosesdeeCVP** [comment]
![2133 Create MDM Endpoints for MP Unit Fuel Data 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8fe6e105-4962-4bdd-946a-46351d917c1e)
