### ISSUE TITLE
View MP Unit Fuel Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2134]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production MP Unit Fuel Data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Unit Information** from the Sections dropdown
When the MP Unit Fuel Data data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Fuel Type
Indicator Code
Ozone Season Indicator
Dem GCV (Demonstration Method to Qualify for Monthly Fuel Sampling for GCV)
Dem SO2 (Demonstration Method to Qualify for Daily or Annual Fuel Sampling for %S (ARP)
Start Date
End Date

Given a user is viewing MP Unit Fuel Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 21): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC418](https://epacamd.testquality.com/project/11428/plan/22363/test/308787)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2134 View MP Unit Fuel Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc0dcb88-c9a8-4555-ab32-862c324c2606)

![2134 View MP Unit Fuel Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/56edf704-5607-4a4c-a416-7246292e919a)

![2134 View MP Unit Fuel Data - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bdfb0c3e-04ab-4eff-aa0d-9b6662d87ee8)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![2134 View MP Unit Fuel Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/15f75e3b-9f78-4290-847d-b37cb7a6e03e)

**Comment by mosesdeeCVP** [comment]
Test Passed
