### ISSUE TITLE
Create MP Unit Fuel Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2136]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

As an ECMPS user, I want the ability to create new MP Unit Fuel Data, so that I can add new data 

Acceptance Criteria:
_Given_ the user has selected **Unit Information** from the Sections dropdown
_When_ the user chooses to add new MP Unit Fuel Data (Create Unit Fuel)
_Then_ the system displays the create modal
_and_ the user can add new MP Unit Fuel Data

Fuel Type: drop-down
Indicator Code: drop-down
Ozone Season Indicator: radio-button
Dem GCV (Demonstration Method to Qualify for Monthly Fuel Sampling for GCV): drop-down
Dem SO2 (Demonstration Method to Qualify for Daily or Annual Fuel Sampling for %S (ARP): drop-down
Start Date: date picker, format mm/dd/yyyy
End Date: date picker, format mm/dd/yyyy

Given the user has added MP Unit Fuel Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the landing page for Unit Information

### Does this Story require 508 Testing?
- [x] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Refer to page 21 from https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC423](https://epacamd.testquality.com/project/11428/plan/22363/test/308834)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2136 Create MP Unit Fuel Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/add1eaa5-b572-47fb-8fb3-af6459c5479e)

**Comment by mosesdeeCVP** [comment]
Test Passed
