### ISSUE TITLE
Modifications to Check Engine Functions & Procedures (Rename & move schemas)

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#2139]
- [] get_facility_info - Rename. Need to update error messages to replace the "Check." schema prefix with "camdecmpswks." schema. Comment out the TEST condition along with QCE, & TEE.
- [] get_report_period_info - Rename. Move to camdecmpswks schema. When referencing tables need to use schema.table convention.
- [] format_date_time - Rename. Change 1st parameter datatype to date
- [] get_initial_values - Move to camdecmpswks & use workspace tables
- [] combined_methods - Rename. Move to camdecmpswks & use workspace tables
- [] mats_method_data_parameter - rename only
- [] mats_combined_method - rename only
- [] location_program_parameter - rename only
- [] unit_program_parameter - rename only
- [] monitor_qualification_lee_parameter - rename only
- [] rpt_get_facility_header - rename only
- [] error_suppression_spec_gather	- rename & move to workspace

**Comment by ayang2017** [comment]
I assume the combined_methods is for camdecmps.checkmpcombinedmethods, so I edit and move to camdecmpswks.combined_methods.  Please confirm.

**Comment by ayang2017** [comment]
Finished.
