### ISSUE TITLE
Wireframes to handle resolution up to 200%

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2141]
Issue: 
Resizing text causes change or loss of content. When text is resized to 200% with either built-in magnification or resizing tools on the site, content is either not resized or becomes unreadable. This is impacting not just the resolution but is a 508 violation as well

**Comment by AllisonFrancis** [comment]
@vishnunavuluri I believe that no updated wireframes/design are needed from me for this ticket. In our call i think the solution discussed will be that for 200% view Dev will use the Tablet view for Desktop and larger. Please confirm and we can close this ticket. Thanks
