### ISSUE TITLE
ECMPS - On Demand Content

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2145]
**Note: this ticket is to track the work (if any) for the ECMPS team to implement the What's New Box on the Home Screen and Banners to add content at the top of the screen on the Global View and the Logged in View (Both separate content) after the tech team has implemented on demand content**

### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to see on-demand content for ECMPS on the global view and in the logged-in view, so that I am informed of any important updates

## Acceptance Criteria
Given I am an ECMPS user 
When I access the ECMPS website
Then I see on-demand content at the top of the screen

Given I am an ECMPS user who logged into ECMPS
When I am on the home screen/landing page
Then I see on-demand content at the top of the screen

### Development Notes
Files to be supported:
- CSV
- Word
- HTML
- PDF
- PPT
- Video
- Excel
- JSON
- url's/hyperlinks

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
@vishnunavuluri I updated the dependency for this to the ticket the tech team is using. In order for the tech team to set up the S3 buckets they need a list of the kinds of files that will be needed (video, PDF, etc.). Please pull that list together and post in the tickets and let Jason know where to find it. Thanks!
