### ISSUE TITLE
Create API Endpoints for MP Unit Control Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2149]
Create API Endpoints for MP Unit Control Data under **Monitor Plan API**:

Add:
GET in public view
GET, POST, PUT in the Workspace

**Comment by mosesdeeCVP** [comment]
Test Case: [TC413](https://epacamd.testquality.com/project/11428/plan/22363/test/308194)

**Comment by mosesdeeCVP** [comment]
GET in public view

![2149 Create API Endpoints for MP Unit Control Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/64a861b2-dff8-4683-84f5-6afb4339e734)

**Comment by mosesdeeCVP** [comment]
GET in the Workspace

![2149 Create API Endpoints for MP Unit Control Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/64ff2216-aaaf-4254-b455-43af99ce20d5)

**Comment by mosesdeeCVP** [comment]
PUT in the Workspace

![2149 Create API Endpoints for MP Unit Control Data - 4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7998c474-3fac-483f-affd-8d19d4bbd3e3)

**Comment by mosesdeeCVP** [comment]
POST in the Workspace

![2149 Create API Endpoints for MP Unit Control Data - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b1d39f2-21fa-457a-9eca-0274e1fca132)

**Comment by mosesdeeCVP** [comment]
Test Passed
