### ISSUE TITLE
Create a Notifications API 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2151]
We need to create a notifications api that will be used to handle any and all types of notifications required by the ECMPS and CAMPD applications in the cloud.gov world. The reason an api is required is that the EPA smtp server will not allow requests unless they are from an EPA on-prem or cloud.gov application. We also need to secure the api (using an api key) to only allow requests from the ECMPS and CAMPD applications.

**High level tasks**
1. Create an easey-notifications-api repo in the us-epa-camd Github org
2. Create a NestJs notifications api (use any existing NestJs api as a template)
3. Create an EmailModule with an EmailController and EmailService
4. Add a POST sendEmail endpoint to the EmailController and EmailService that will send email notifications to the EPA smtp email service

**Endpoint URL**
POST /api/notifications-mgmt/emails
BODY {
  "apiKey": "W2H`Q@:/a[Ms^b^x"cw_}0'l%G7]Zw",
  "toAddress: "ecmps-beta@camdsupport.com",
  "fromAddress: "joeblow@yahoo.com",
  "subject: "Help using application",
  "body": "some really long message with good detail here"
}

**EPA ECMPS Support Emails**
ecmps-beta@camdsupport.com

**EPA CAMPD Support Emails**
campd-support@camdsupport.com

**EPA SMTP Server**
smtp.epa.gov

**Comment by jwhitehead77** [comment]
api was created however we are going to use the Quartz.Net SendMailJob since it will already be used for sedning notifications for the Check Engine Evaluations
