### ISSUE TITLE
Create API Endpoints for Rectangular Duct WAFs Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2152]
Create API Endpoints for Rectangular Duct WAFs Data under ** Monitor Plan ** API:

Add:
GET, POST, PUT in the Workspace

**Comment by mosesdeeCVP** [comment]
![2152 Create API Endpoints for Rectangular Duct WAFs Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d596b0dc-7fc2-4966-9e91-1c03b5b219cc)

![2152 Create API Endpoints for Rectangular Duct WAFs Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b2f1f7fc-8608-4cf6-8ff5-37dd58c3e908)

![2152 Create API Endpoints for Rectangular Duct WAFs Data - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cbbed0ce-cb14-4a66-b414-ebac790bef1f)

**Comment by mosesdeeCVP** [comment]
Test Case [TC412](https://epacamd.testquality.com/project/11428/plan/22357/test/308189)

**Comment by mosesdeeCVP** [comment]
Test Passed
