### ISSUE TITLE
Create API Endpoints for MP Unit Fuel Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2153]
Create API Endpoints for MP Unit Fuel Data under ** Monitor Plan API **:

Add:
GET in public view
GET, POST, PUT in the Workspace

**Comment by mosesdeeCVP** [comment]
GET in public view

![2153 Create API Endpoints for MP Unit Fuel Data - 1 Get Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/62eac228-720e-46bd-8c75-bd0de6e24d42)

**Comment by mosesdeeCVP** [comment]
GET in the Workspace

![2153 Create API Endpoints for MP Unit Fuel Data - 2 Get Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/febcce5c-05f3-4355-9a96-19395bcefa0f)

**Comment by mosesdeeCVP** [comment]
POST in the Workspace

![2153 Create API Endpoints for MP Unit Fuel Data - 3 POST Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fef2489b-e160-4209-a12b-2d92823d2da0)

**Comment by mosesdeeCVP** [comment]
PUT in the Workspace

![2153 Create API Endpoints for MP Unit Fuel Data - 4 PUT Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/92377dda-3ebd-4df5-b2eb-ce515c3f8b9f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC414](https://epacamd.testquality.com/project/11428/plan/22363/test/308195)
Test Passed
