### ISSUE TITLE
Create API Endpoints for MP Unit Capacity Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2154]
Create API Endpoints for MP Unit Control Data under Facilities API:

Add:
GET in public view
GET, POST, PUT in the Workspace

**Comment by mosesdeeCVP** [comment]
![2154 Create API Endpoints for MP Unit Capacity Data - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b73ec813-9c50-4555-8b43-af047740be06)

**Comment by mosesdeeCVP** [comment]
![2154 Create API Endpoints for MP Unit Capacity Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/41c8bfc2-7b38-4e90-aa11-c2c6b8958578)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC440](https://epacamd.testquality.com/project/11428/plan/22363/test/309574)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![2154 Create API Endpoints for MP Unit Capacity Data - GET Public.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/baff5a79-2f90-4db3-982b-c490a392385f)

**Comment by mosesdeeCVP** [comment]
![2154 Create API Endpoints for MP Unit Capacity Data - GET Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8da368b2-8882-49e5-9fe3-48567e67782d)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC440](https://epacamd.testquality.com/project/11428/plan/22363/test/309574)

Test Passed
