### ISSUE TITLE
Testing Only: Utility Nav Links throwing a 404 Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2160]
The options available under the utility navigation are throwing a 404 error

When a user clicks on any of the options available under the utility navigation (Help/Support, Resources etc), system throws a 404 error. Looks like the URL needs to be fixed to include 'ecmps' in it

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d000b831-85dc-484b-9c41-7953c254a98d)

**Comment by mosesdeeCVP** [comment]
Bug has been resolved
