### ISSUE TITLE
Create API Endpoints for Location Attributes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2162]
Add API endpoints for Attributes in Workspace

POST: /api/monitor-plan-mgmt/workspace/locations/{locId}/attributes/
PUT:  /api/monitor-plan-mgmt/workspace/locations/{locId}/attributes/{attribId}

Parameters:
 "ductIndicator"
 "bypassIndicator"
 "groundElevation"
 "stackHeight"
 "materialCode"
 "shapeCode"
 "crossAreaFlow"
 "crossAreaStackExit"
 "beginDate"
 "endDate"

Database table: camdecmpswks.monitor_location_attribute

**Comment by mosesdeeCVP** [comment]
![2162 Create API Endpoints for Location AttributesCreate API Endpoints for Location Attributes - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ecefb936-0ba5-46c6-a127-221873f2172b)

**Comment by mosesdeeCVP** [comment]
![2162 Create API Endpoints for Location AttributesCreate API Endpoints for Location Attributes - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e1514b4c-c91a-4e99-be7c-474c3b552244)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC489](https://epacamd.testquality.com/project/11428/plan/22772/test/315047)

**Comment by mosesdeeCVP** [comment]
Test Passed
