### ISSUE TITLE
TEST ONLY: Evaluating multiple plans at once

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2164]
Queue one plan for Evaluation at a time 
Evaluate multiple plans at a given time 

PriorityL After QA and Emissions

**Comment by mosesdeeCVP** [comment]
![Multiple Evals.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1ae1596d-9f5b-49ef-a5d5-ec8b52381aef)


![Multiple Evals MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f1f7b26d-9677-4be3-bb6c-66bbb9456948)

**Comment by mosesdeeCVP** [comment]
User is able to queue one plan for Evaluation at a time and evaluate multiple plans at a given time
