### ISSUE TITLE
STORY: Filter/Sort for  Data to Download 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#217]
As a user I want to select what data I want so that I can download it. 

[Refer to MVP list for filter criteria](https://teams.microsoft.com/l/entity/0d820ecd-def2-4297-adad-78056cde7c78/_djb2_msteams_prefix_3687621406?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype%22%7D&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

**Comment by JorjaComer** [comment]
@JanellC  Please confirm existing selection criteria

**Comment by JanellC** [comment]
> @JanellC Please confirm existing selection criteria

This seems okay. Should this ticket be more specific? If so, there is more selection criteria to add like select by facility, select by state, & etc.

**Comment by JorjaComer** [comment]
Converted this issue and moved it to the feature above to support the development of the filter/sort UI

**Comment by JorjaComer** [comment]
Story has been split into multiples. No longer needed
