### ISSUE TITLE
Revert to Official Record Not working

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#2179]
When the user clicks on the "Revert to Official Record" button they system does not revert to official record. All of the unofficial record data is still available.

**Comment by jwhitehead77** [comment]
@mosesdeeCVP I was working on some daase stuff and discovered the issue and fixed it so this should be working again. Please make changes to a number of different plans across several facilities and verify that this is good.

**Comment by mosesdeeCVP** [comment]
Bug is resolved
