### ISSUE TITLE
ECMPS 508 Testing - PI 7, PI 8 & PI 9

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2183]
Will contain all ECMPS 508 Testing Results Reports for PI 6 and PI 7

Issues that require 508 testing @aprematta

https://beacon.cvpcorp.com/display/PRAC/Developer

## Context

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
No issues found with 1721

**Comment by aprematta** [comment]
2208 has 2 issues:
1. The name of the data table on the qualifications modal under 'Qualification Percent' is generic: aria-label="Data Table". Should be labelled by the qualification percent text.
2. When you view qualification percent, the back button is labeled aria-label="go back to systems details". I think this is a reference to the Systems section. Should be changed to aria-label="go back to Qualification details"

**Comment by aprematta** [comment]
No issues with 2209

**Comment by aprematta** [comment]
No issues with 1722

**Comment by aprematta** [comment]
2207 has 2 issues:
1. Qualifications is a visual heading but the html has it as a span tag
2. The name of the data table is generic: aria-label="Data Table". Should be labelled by the qualification text.

**Comment by aprematta** [comment]
No issues with 2122

**Comment by aprematta** [comment]
No issues found with 2128

**Comment by aprematta** [comment]
Tested 2123 and 2121, only issue found is that the back button may be mislabeled, the label says
aria-label="go back to systems details"
Think this should be 
aria-label="go back to qualifications details"
