### ISSUE TITLE
Fix Max Rate Source Code Typo

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2189]
Fix **Max Rate Source Codes** & **Units of Measure Codes** should be plural in their URL path's for the MDM API

UI will need to be fixed to reflect these changes

**Comment by mosesdeeCVP** [comment]
![Max Rate Source Codes.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04545ef7-1af6-49ca-9273-a897a24418ee)

**Comment by mosesdeeCVP** [comment]
![Units of Measure Codes.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/585577ca-04c5-4368-875c-50883ae3cdd6)

**Comment by mosesdeeCVP** [comment]
Typo has been fixed
