### ISSUE TITLE
API Endpoints for Monitoring Qual LEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2190]
Add API Endpoints or Monitoring Qual LEE Data:

POST, PUT in workspace

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/3888f214-8ed9-44c2-b2c7-47c98f7a1bb4)

**Comment by mosesdeeCVP** [comment]
![2190 API Endpoints for Monitoring Qual LEE Data - GET Public.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/69161597-6788-4a6f-aec2-d894b02fde08)

**Comment by mosesdeeCVP** [comment]
![2190 API Endpoints for Monitoring Qual LEE Data - GET Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4ea66c68-462b-46e2-ad98-504044d8a77e)

**Comment by mosesdeeCVP** [comment]
![2190 API Endpoints for Monitoring Qual LEE Data - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/29a33b43-a8db-4975-a5e8-b5ed296cea41)

**Comment by mosesdeeCVP** [comment]
![2190 API Endpoints for Monitoring Qual LEE Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/447f6c6b-c75c-4688-90e7-85e0300e53af)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC441](https://epacamd.testquality.com/project/11428/plan/22483/test/309635)

Test Passed
