### ISSUE TITLE
Create API Endpoints for Monitoring Qual Percent Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2191]
Add API Endpoints or Monitoring Qual Percent Data:

POST, PUT in workspace

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/ec81e5b5-da04-4a6b-ba9b-60121c94c680)

**Comment by mosesdeeCVP** [comment]
![2191 Create API Endpoints for Monitoring Qual Percent Data - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/72e27e9c-933c-41ad-b77a-a531bd448928)

**Comment by mosesdeeCVP** [comment]
![2191 Create API Endpoints for Monitoring Qual Percent Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b3797080-f44e-49f9-a198-a75e98a48f5e)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC437](https://epacamd.testquality.com/project/11428/plan/22483/test/309334)

Test Passed
