### ISSUE TITLE
ECMPS UI - Fix EPA Banner

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2192]
As an ECMPS user, I want the ECMPS UI banner to be updated according to the design recommendations so that we have uniformity across EASEY systems.

Spacing is off for the United States Government Banner (Might be a global fix)

https://zeroheight.com/37f47ceee/p/455ab9-usa-banner

**Comment by jwhitehead77** [comment]
@vishnunavuluri please ensure that tickets have all relevant information. This ticket has nothing in it as far as what the spacing should be or any links to a UI design spec that provides this information.
