### ISSUE TITLE
Audit for Monitoring Plan Submission - Global-View

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2193]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view the audit record on a Monitoring Plan in the Global-View, so that I know the user and time who last submitted a Monitoring Plan Record

## Acceptance Criteria
Given Monitoring Plan data was submitted successfully
When a user accesses the respective facility in the Global-View
Then the system displays 'Last submitted by: UserID, 8/23/2021'

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC494](https://epacamd.testquality.com/project/11428/plan/22924/test/315399)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2193 Audit for Monitoring Plan Submission - Global-View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d468e1a8-9226-4b16-be7c-eb3bf492cde8)

**Comment by mosesdeeCVP** [comment]
Test Passed
