### ISSUE TITLE
Selecting and Filtering Monitoring Plan Data When Viewing Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#220]
As a user I want to narrow monitoring plan data so that I can view the particular data I am looking for. 

Will need to develop selectors functions for MP data

**Comment by JorjaComer** [comment]
No longer needed, will be handled as part of MP data requirements

**Comment by david-cvp** [comment]
Labeling as invalid and removing from the epic
