### ISSUE TITLE
View Monitoring Qualifications Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2207]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production Monitoring Qualifications Data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Qualifications** from the Sections dropdown
When Monitoring Qualifications Data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Qualification Type Code
Start Date
End Date

Given a user is viewing Monitoring Qualifications Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 125): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC442](https://epacamd.testquality.com/project/11428/plan/22483/test/309664)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2207 View Monitoring Qualifications Data.PNG](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/baf5f194-2eb2-4c09-b6fb-47d670a3158b)

**Comment by mosesdeeCVP** [comment]
Test Passed
