### ISSUE TITLE
Create MDM Endpoints for Monitoring Qualification Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2210]
Create MDM Endpoints for Monitoring Qualifications Data:

Qualification Type Code: drop-down

**Comment by mosesdeeCVP** [comment]
![2210 Create MDM Endpoints for Monitoring Qualification Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/54b51200-7fa6-45c1-aa05-6c2412a99950)

![2210 Create MDM Endpoints for Monitoring Qualification Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7362f485-a7ca-44f4-9855-7ee20b5b6bad)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC439](https://epacamd.testquality.com/project/11428/plan/22483/test/309546)

**Comment by mosesdeeCVP** [comment]
Test Passed
