### ISSUE TITLE
API Endpoints for Monitoring Qualifications Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2211]
Add API Endpoints or Monitoring Qualifications Data:

POST, PUT in workspace

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/0fab1c4f-8440-4f35-b766-9bbf2d61afcc)

**Comment by mosesdeeCVP** [comment]
![2211 API Endpoints for Monitoring Qualifications Data - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2227b2ca-1b9e-4f0f-a29b-874cab5d2d5d)

**Comment by mosesdeeCVP** [comment]
![2211 API Endpoints for Monitoring Qualifications Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bdac74a8-96b5-4f23-8c89-4bc31aeaa312)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC438](https://epacamd.testquality.com/project/11428/plan/22483/test/309545)

**Comment by mosesdeeCVP** [comment]
Test Passed
