### ISSUE TITLE
OWASP: Change Server's Supported Ciphersuites - Medium

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2245]
URL:  https://campd-stg.app.cloud.gov/static/js/bundle.js 

Entity: campd-stg.app.cloud.gov (Page)

Fix:  Change server's supported ciphersuites 

60 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS 1.2

61 TLS_RSA_WITH_AES_256_CBC_SHA256 TLS 1.2

156 TLS_RSA_WITH_AES_128_GCM_SHA256 TLS 1.2

157 TLS_RSA_WITH_AES_256_GCM_SHA384 TLS 1.2

**Comment by MaeganWood64** [comment]
-Forward to the cloud.gov support email address after looking into issues to remediate

**Comment by tlageman-epa** [comment]
This ticket through 2249 are likely no longer valid having been superseded by more recent scans. Recommend closing.

**Comment by alangmaid** [comment]
legacy issue, no longer valid.
