### ISSUE TITLE
OWASP:  Add Cache Control and Pragma headers to Manifest.json responses - Low

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2246]
URL :https://campd-stg.app.cloud.gov/manifest.json 

Risk: It is possible to gather sensitive information about the web application such as usernames, passwords, machine name and/or
sensitive file locations

Prevent caching of SSL pages by adding "Cache-Control: no-store" and "Pragma: no-cache" headers to their responses.

**Comment by alangmaid** [comment]
legacy issue, no longer valid.
