### ISSUE TITLE
OWASP: Add third party script/link to SRI (Subresource integrity) - Low

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2247]
URL: https://campd-stg.app.cloud.gov/ 

Risk: In case the third-party server is compromised, the content/behavior of the site will change

Causes: SRI (Subresource Integrity) not supported 

Fix: Add to each third-party script/link element support to SRI(Subresource Integrity).

**Comment by alangmaid** [comment]
legacy issue, no longer valid.
