### ISSUE TITLE
OWASP:  Configure Server to use "Content-Security-Policy" Header with secure policy - Low

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2248]
URL: https://campd-stg.app.cloud.gov/ 

Entity: campd-stg.app.cloud.gov (Page) 

Risk: It is possible to gather sensitive information about the web application such as usernames, passwords, machine name and/orsensitive file locations 
It is possible to persuade a naive user to supply sensitive information such as username, password, credit card number, socialsecurity number etc. 

Causes: Insecure web application programming or configuration 

Fix: Config your server to use the "Content-Security-Policy" header with secure policies

**Comment by alangmaid** [comment]
legacy issue, no longer valid.
