### ISSUE TITLE
OWASP: Remove Unnecessary HTTP Response headers in bundle.js -Low

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2249]
URL: https://campd-stg.app.cloud.gov/ 

Entity: bundle.js (Page) 

Risk: It is possible to gather sensitive information about the web application such as usernames, passwords, machine name and/orsensitive file locations 

Causes: Insecure web application programming or configuration

 Fix: Do not allow sensitive information to leak.

**Comment by alangmaid** [comment]
legacy issue, no longer valid.
