### ISSUE TITLE
Design for CAMPD What's New Box (need by 11/15)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2251]
Provide a design for the what's new box on the CAMPD home page.  Utilize the what's new box that ECMPS is using. 

ECMPS What's New Box: https://easey-dev.app.cloud.gov/ecmps

**Comment by JanellC** [comment]
@tlageman-epa Below is the link to the design for Whats New Box on the CAMPD Home Page: 
[Whats New Box ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=899%3A4086)

**Comment by AllisonFrancis** [comment]
[What's New Box](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1608%3A7707&scaling=min-zoom&page-id=899%3A4086&starting-point-node-id=1608%3A7707) was shared with team on 11/15
