### ISSUE TITLE
CAMPD About Page- API call 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2252]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a the CAMPD user I want to see the most update to date content on the About page so that I can learn more about CAMPD

## Acceptance Criteria
Given that a user has navigated to the About CAMPD page 
When the functionality is displayed 
Then the page is displayed in accordance with the[ wireframes ](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541) 
And the page content is consistent with the [content document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBEF116D3-0228-4EDE-B0D0-21C64213462E%7D&file=About%20CAMPD%20Content-%20EPA%20CAMD-v1.01.docx&action=default&mobileredirect=true) 

### Development Notes
- update campd about page url to be consistent with content document 

**- As apart of the scope of this ticket the EPA should be able to** 
Update all of the content on the about page (ex. what is campd, bugs, release notes, etc.....) 

The About CAMPD content will be hosted in a markdown file located in S3. To do this create/update the /dev/campd/help-support/about/index.md file in the easey-content repo and commit the file to push it to S3.
![image](https://user-images.githubusercontent.com/66504934/150198269-7786c1e2-4b2d-47be-ad92-0d5a59cc086e.png)

The Product Updates and Release Notes will be handled by a JSON file located in S3. To do this create/update the /dev/campd/help-support/about/release-notes.json in the easey-content repo and pushed to S3.
![image](https://user-images.githubusercontent.com/66504934/150202742-3533c99c-1331-4d11-a994-18dbd21f0d69.png)
![image](https://user-images.githubusercontent.com/66504934/150202825-a60824a3-aacd-4678-8d5a-d06791fdbded.png)

**_The following code examples will need to be added to the easey-campd-ui code base. Please implement in the same consistent manner that all other api calls have been handled_**

**Example contentApi.js file** 
```
import axios from "axios";
import { handleResponse, handleError } from "./apiUtils";
import config from "../../config";

export const getContent = async (path) => {
  let url = `${config.services.content.uri}${path}`;

  return axios
    .get(url)
    .then(handleResponse)
    .catch((error) => {
      handleError(error);
      throw new Error(error);
    });
};
```

**Example calls to getContent in contentApi.js from within the component usually wrapped in a useEffect**
```
getContent('/campd/help-support/about/index.md').then(resp` => setMainContent(resp.data))
getContent('/campd/help-support/about/release-notes').then(resp => setReleaseNotes(resp.data))
```

**To render markdown**
```
$ yarn add react-markdown remark-gfm --ignore-engines

<ReactMarkdown
          className="main-content"
          children={mainContent}
          remarkPlugins={[remarkGfm]}
          components={{
            a: ({node, ...props}) => <USWDSLink {...props} target="_blank" rel="noopener noreferrer" />
          }}
        />
```

**For the Product Updates and Release Notes remove the hardcoded data and set the const variable  to the result of the getContent call as the data should be in the same format.**
- Product Updates are 1st item in the list and should contain the upcoming features
- Release Notes are items 2...n and should not have upcoming features

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
- [About CAMPD](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541)
- [About CAMPD (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541)

[About page content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBEF116D3-0228-4EDE-B0D0-21C64213462E%7D&file=About%20CAMPD%20Content-%20EPA%20CAMD-v1.01.docx&action=default&mobileredirect=true&cid=7122c16d-2250-4e63-ae4b-8aa6021b8942)

## Testing
Test Case: [TC539](https://epacamd.testquality.com/project/11428/plan/21067/test/323255) 
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
@JanellC I updated the dependency for this to the ticket the tech team is using (see description, can't add dependency for some reason). In order for the tech team to set up the S3 buckets they need a list of the kinds of files that will be needed (video, PDF, etc.). Please pull that list together and post in the tickets and let Jason know where to find it. Thanks!

**Comment by JanellC** [comment]
@jwhitehead77 The scope of this ticket is to populate the Product Updates (ex. bugs, release notes) section of the CAMPD About Page using an API call

- [About CAMPD](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541&scaling=contain&page-id=372%3A540&starting-point-node-id=372%3A541)
- [About CAMPD (dev link)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=372%3A541)

**Comment by jwhitehead77** [comment]
The About CAMPD content will be hosted in a markdown file located in S3. To do this create/update the /dev/campd/help-support/about-campd/index.md file in the easey-content repo and commit the file to push it to S3.
![image](https://user-images.githubusercontent.com/66504934/150198269-7786c1e2-4b2d-47be-ad92-0d5a59cc086e.png)

The Product Updates and Release Notes will be handled by a JSON file located in S3. To do this create/update the /dev/campd/help-support/about-campd/release-notes.json in the easey-content repo and pushed to S3.
![image](https://user-images.githubusercontent.com/66504934/150202742-3533c99c-1331-4d11-a994-18dbd21f0d69.png)
![image](https://user-images.githubusercontent.com/66504934/150202825-a60824a3-aacd-4678-8d5a-d06791fdbded.png)


**_The following code examples will need to be added to the easey-campd-ui code base. Please implement in the same consistent manner that all other api calls have been handled_**

**Example contentApi.js file** 
```
import axios from "axios";
import { handleResponse, handleError } from "./apiUtils";
import config from "../../config";

export const getContent = async (path) => {
  let url = `${config.services.content.uri}${path}`;

  return axios
    .get(url)
    .then(handleResponse)
    .catch((error) => {
      handleError(error);
      throw new Error(error);
    });
};
```

**Example calls to getContent in contentApi.js from within the component usually wrapped in a useEffect**
```
getContent('/campd/help-support/about-campd/index.md').then(resp` => setMainContent(resp.data))
getContent('/campd/help-support/about-campd/release-notes').then(resp => setReleaseNotes(resp.data))
```

**To render markdown**
```
$ yarn add react-markdown remark-gfm --ignore-engines

<ReactMarkdown
          className="main-content"
          children={mainContent}
          remarkPlugins={[remarkGfm]}
          components={{
            a: ({node, ...props}) => <USWDSLink {...props} target="_blank" rel="noopener noreferrer" />
          }}
        />
```

**For the Product Updates and Release Notes remove the hardcoded data and set the const variable  to the result of the getContent call as the data should be in the same format.**
- Product Updates are 1st item in the list and should contain the upcoming features
- Release Notes are items 2...n and should not have upcoming features

**Comment by JanellC** [comment]
TC539 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
