### ISSUE TITLE
Update Related Resources page to contain an exit disclaimer (need by 11/15)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2258]
## Context 
Produce updated wireframes for the related resources page with an exit disclaimer for the  "National Atmospheric Deposition Program" link. the exit disclaimer should be on the right of the link 

janell coleman (Guest) Junie Senthilkumar (Guest) I noticed there was no External Link warning in the Related Resources. Maybe it was missed in the comment in the content document, but we need to have that for any external link that doesn't go to a .gov or .mil website (per this documentation). While the content document indicates several that require an external link warning, after an additional review it would only be for the "National Atmospheric Deposition Program" link. Here is the external link icon in the EPA web style guide (Requires VPN)  Allison Francis (Guest) Let me know if you hae any questions. Thx!

[EPA style guide ](https://www.epa.gov/themes/epa_theme/pattern-lab/?p=components-external-link)

Example on the EPA site 

Allison Francis (Guest)You will see an example of the, "Exit Disclaimer" in the Need Help box here: https://www.epa.gov/compliance/electronic-reporting-pesticide-establishments

**Comment by AllisonFrancis** [comment]
@JanellC  here are the links to the screens where i added this EXIT tag. 
[Related Resources EXIT tag](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1255&scaling=contain&page-id=392%3A1254)
[Related Resources EXIT tag (dev)](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=392%3A1254)
