### ISSUE TITLE
Design Facilities data service

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#226]
- [x] Identify search criteria
- [x] Identify request parameters
- [x] Identify HTTP status codes to return
- [x] Identify appropriate error messages

Assumption: Facilities  end points are identified

**Comment by junie-stigdon** [comment]
Document of endpoints: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/API%20Endpoints/Identified%20API%20Endpoints%20-%20Facilities%20-%20EPA%20CAMD%20-%20v2.1.pdf?csf=1&web=1&e=3l1pqw
