### ISSUE TITLE
MP Evaluation 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2273]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want the ability to evaluate a Monitoring Plan that needs it, so that I understand its readiness for submission

**Note: Update the current monitoring plan endpoints to grab the new field 'eval_status_cd'**

## Acceptance Criteria
Given I am a user logged into ECMPS
When a Monitoring Plan is available for Evaluation **(Evaluation Status = Needs Evaluation)**
Then the Evaluation Status 'Needs Evaluation' is displayed in Yellow
And 'Evaluate' and 'Revert to Official Record' options are available and 'Submit' is NOT available

Given I am a user logged into ECMPS
When a Monitoring Plan is queued for evaluation **(Evaluation Status = In Queue)**
Then the Evaluation Status 'In Queue' is displayed in Blue
And 'Evaluate' 'Submit' and 'Revert to Official Record' options are NOT available

Given I am a user logged into ECMPS
When a Monitoring Plan is being evaluated **(Evaluation Status = In Progress)**
Then the Evaluation Status 'In Progress' is displayed in Blue
And 'Evaluate' 'Submit' and 'Revert to Official Record' options are NOT available

Given I am a user logged into ECMPS
When validation is complete for a Monitoring Plan **(Evaluation Status = Passed)**
Then the Evaluation Status 'Passed' is displayed in Green
And 'Evaluate' option is NOT available 
And 'Submit' and 'Revert to Official Record' options are available

Given I am a user logged into ECMPS
When validation is complete for a Monitoring Plan **(Evaluation Status = Informational Message)**
Then the Evaluation Status 'Informational Message' is displayed in Green
And 'Evaluate' option is NOT available 
And 'Submit' and 'Revert to Official Record' options are available

Given I am a user logged into ECMPS
When validation is complete for a Monitoring Plan with errors **(Evaluation Status = Critical Errors)**
Then the Evaluation Status 'Critical Errors' is displayed in Yellow
And 'Evaluate' and 'Submit' options are NOT available 
And 'Revert to Official Record' option is available

### Development Notes
When a Monitoring Plan is available for Evaluation, then I see the following statuses when I chose to validate it
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6b5dbac9-0741-45ac-b4b4-09f56e7bfe2d)

Prototype: https://xd.adobe.com/view/28b8b774-a061-44ae-9a20-e9f1089de84f-7deb/

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC497](https://epacamd.testquality.com/project/11428/plan/22924/test/315545)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Update from Jason on backend work: 
We have added an eval_status_code table in the camdecmpsmd schema that has the values in the table below.
The monitor_plan table in the workspace has a new column called eval_status_cd which will provide the evaluation status for a monitor plan. This needs to be returned in the get configurations & get monitor plan endpoints shown below.
When the Evaluate button in ECMPS is available (only for "EVAL" status code) and is clicked the UI needs to call the https://easey-dev.app.cloud.gov/quartz/api/triggers/evaluations/monitor-plans endpoint with a POST posting the following data...
   POST DATA => { "monitorPlanId": "02022-614W-168CEAA018EA4CBDAE347BE98F95A548", "userId": "jwhitehead" }
the api should return a successful response with an eval_status_cd of "INQ" for "In Queue" as shown below...
   RESPONSE => { "monitorPlanId": "02022-614W-168CEAA018EA4CBDAE347BE98F95A548", "eval_status_cd": "INQ" }
The Check Engine Evaluation process will update the eval_status_cd field to "WIP" once the evaluation has started and update to either "PASS", "ERR", or "INFO" once completed based on the check sessions severity code result.
We also need to add insert & update triggers to the workspace tables that will set the monitor plan eval_status_cd to "EVAL" any time data is changed in any monitor plan table (WIP as of 11/17)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/caac8d31-a7f5-403e-84f9-548d319afdb0)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/61c83bd7-1a08-4de1-86ec-23b5fa500499)

**Comment by vishnunavuluri** [comment]
@mosesdeeCVP  List of the facilities and plans that have different eval status codes (dummy data) to use until the Check Engine is able to update in real-time

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/bc4bfc67-4df2-4245-8635-300e58ea46de)

**Comment by mosesdeeCVP** [comment]
Needs Evaluation
![2273 MP Evaluation - Needs Eval.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7effd22-9c75-4485-9b14-42df34025026)

**Comment by mosesdeeCVP** [comment]
In Queue
![2273 MP Evaluation - In Queue.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/56489203-5ecc-4f38-9c87-2b2cfd5d23cc)

**Comment by mosesdeeCVP** [comment]
In Progress
![2273 MP Evaluation - In Progress.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e38eb9c-79c6-4dac-b37e-169f31f3ea38)

**Comment by mosesdeeCVP** [comment]
Passed
![2273 MP Evaluation - Passed.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/917837de-9886-4ec0-ba12-8eb6b9c26718)

**Comment by mosesdeeCVP** [comment]
Critical Errors
![2273 MP Evaluation - Critical Errors.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c84a0359-8d60-44c4-a2e8-daa98667cf17)

**Comment by mosesdeeCVP** [comment]
Informational Message
![2273 MP Evaluation - Informational Message.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/752b8b88-3dd3-4fca-8204-efac4f3cce58)

**Comment by mosesdeeCVP** [comment]
Test Passed
