### ISSUE TITLE
Address clear all functionality for filter logic - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2281]
## Context 

Two issues:

•	Test 4.F (2.4.3 – focus order meaning): To maintain the logical focus order the focus should shift to the first filter button as suggested rather than the top of the page

•	Test 5.E (4.1.2 – change notify form):  The user needs to know that the filters were successfully cleared – an aria-alert message, for example, would satisfy this

See #2113 for context

**Comment by aprematta** [comment]
works great, closing issue
