### ISSUE TITLE
Create Facilities  data service Controller and Module (hello world stub)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#229]
## Development Tasks
- [x] Create module
- [x] Create controller
- [x] Create Service

- [x] set up nestjs/swagger in main.ts file

- [x] /facilities
- [x] /facilities/{id}
- [x] /facilities/{id}/contacts
- [x] /facilities/{id}/units
- [x] /facilities/{id}/units/{id}
- [x] /facilities/{id}/monitoring-plans/

## Acceptance Criteria
Returns "hello world" response in Swagger for all end points

**Comment by junie-cvp** [comment]
- [ ] /facilities
- [ ] /facilities/{id}
- [ ] /facilities/{id}/contacts
- [ ] /facilities/{id}/units
- [ ] /facilities/{id}/units/{id}
- [ ] /facilities/{id}/monitoring-plans/

**Comment by junie-stigdon** [comment]
Initialized swagger for nestJS. Sejal and I will now split the work for the controller by each doing 3 endpoints.

**Comment by junie-stigdon** [comment]
Completed adding all 6 endpoints to the controller, along with its swagger decorators. Will need to discuss potentially splitting this card due to known blockers.
