### ISSUE TITLE
Retest Only: Search Menu - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2291]
## Finding 

| Screen | Finding | WCAG 2.0 Standard(s) |
|---|---|---|
| Search Menu | The Search EPA form field is the last to receive keyboard focus in the expanded Menu, but it’s visually the first item: | 2.4.3 |

## Context 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/23b9238e-c2c8-4301-9a73-6961a6d82b81)

**Comment by aprematta** [comment]
Retest complete, this is still an issue

**Comment by JanellC** [comment]
The tech team will work on this issue since it needs to be implemented for CAMPD and ECMPS

**Comment by JanellC** [comment]
The work for this ticket was completed on the emissioners side in ticket #2365. This ticket is to retest that the 508 issue has been fixed in CAMPD

**Comment by aprematta** [comment]
Retest complete, tab and reading order now matches the screen
