### ISSUE TITLE
Modify Auth API to support CBS Integration

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#2292]
Modifications to Auth API to support...
- [x] Login for CBS, ECMPS, & Quartz applications
- [x] CROMERR Signing ceremony for submisisons

*** User Story ***
As an Authenticated ECMPS User, when I have logged in on any EPA service and have a valid session, I would like to remain logged in across any CBS/EPA Product

As an Authenticated ECMPS User, when I have data to submit to the EPA the system ensures that I follow the proper CROMERR Signing ceremony and allows me to sign & submit data

**Notes**
- [ ] modify the Sign-in Method to call the roles and responsibilities API 
- [ ] modify the Auth-Guard to ensure that users are able to modify data that they have access to 

[Link to CDX CROMERR](https://usepa.sharepoint.com/:w:/r/sites/CAMDITLegacyReeng/_layouts/15/Doc.aspx?sourcedoc=%7B3FD24EBD-9B22-4215-8A48-2DD56E1C5974%7D&file=CDX%20CROMERR%20Signing%20Web%20Services.doc&action=edit&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.p2p_ns.undefined)

**Comment by MaeganWood64** [comment]
- Need to determine with Chris to see how we want EPA members to interact with the workspace for beta.

**Comment by MaeganWood64** [comment]
- Bumped to PI 9 to wait for auth integration

**Comment by jwhitehead77** [comment]
OBE

**Comment by JanellC** [comment]
As of 9/22 no updates from the integration meeting. Will close ticket after testing it

**Comment by MaeganWood64** [comment]
Test Only Ticekt
