### ISSUE TITLE
Debug camdecmpswks.check_session_init

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2293]
camdecmpswks.check_session_init(text, text, text, integer, text, text, text, date, date, text).  Insure procedure returns a value like the mssql procedure; while having null values for the following parameters.
- categoryCd 
- reportPeriodId
- testSumId
- qaCertEventId
- testExtensionExemptionId

**Comment by ayang2017** [comment]
It's updated and should work now.
