### ISSUE TITLE
Update Options on ECMPS Screens

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2297]
As an ECMPS user, I need the availability of options in ECMPS updated so that I am aware of what functionality is available for the beta release.

Acceptance Criteria:

Update buttons/options as below:
**Utility Nav Tool Bar:**
Sitemap (Hide this option)
Regulatory Partners (Add hover over text - Coming Soon)

 **ECMPS Home Page/Landing Page:** 
View QA & Certifications (Update the existing text to say - Coming Soon) 
View Emissions (Update the existing text to say - Coming Soon) 

**Global View:**
View Comments  (Add hover over text - Coming Soon)
 
**In the Workspace:** 
Import a Monitoring Plan (Add hover over text - Coming Soon)
View Comments (Add hover over text - Coming Soon)
Submit (Add hover over text - Coming Soon)

Hide the 'Reports' button from the Official View and the Workspace

**Comment by mosesdeeCVP** [comment]
![2219 Update Options on ECMPS Screens - Utility Nav Tool Bar.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fde0e6b8-42cf-4a6f-ac64-1780513f7917)

**Comment by mosesdeeCVP** [comment]
![2219 Update Options on ECMPS Screens - View QA & Certifications.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c1f307f8-499c-4471-8c4a-a92987586478)

![2219 Update Options on ECMPS Screens - View Emissions.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1bd29057-da00-46c7-9ea5-e9bebd431796)

**Comment by mosesdeeCVP** [comment]
![2219 Update Options on ECMPS Screens - View Comments - Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/32950ca3-4890-4b81-ae89-d1bf7c3ef248)

**Comment by mosesdeeCVP** [comment]
![2219 Update Options on ECMPS Screens - Import a Monitoring Plan.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cbabd548-e889-42a6-9903-4c45e145cd43)

![2219 Update Options on ECMPS Screens - View Comments - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/30c5f05d-bb74-474c-95f6-625104dbc50c)

![2219 Update Options on ECMPS Screens - Submit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6858df96-c7cb-4a96-aa34-44108b6f4d83)

**Comment by mosesdeeCVP** [comment]
Test Passed
