### ISSUE TITLE
Link to Data Landing Page From Home Page- 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2299]
## Context 

1 issue found with 1654, when you tab to the data heading, there is no visual indicator that the link has current keyboard focus.

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e884f7b7-22ed-44b6-9fe2-33dbbf4c8481)

**Comment by aprematta** [comment]
Visual indicator is now present, closing the ticket

**Comment by JanellC** [comment]
@tlageman-epa The team had the capacity to pull this ticket into sprint 6.3 the 508 issue is resolved
