### ISSUE TITLE
MP Evaluation Report - Create API Endpoints

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2300]
The endpoint for this API should be

~/api/monitor-plan-mgmt/workspace/plans/{planId}/evaluation-report

The API must return a structure that has the facility information and a collection of evaluation results as follows:

{
 facilityName: string,
 facilityId: numeric,
 state: string,
 countyName: string,
 mpReportResults: [
  {
     unitStackInformation: string,
     severityCode: string,
     categoryCodeDescription: string,
     checkCode: string,
     resultMessage: string,
   }
 ]
}

Developer Notes:
For retrieving facility information we should use exisitng TypeORM entities. With the mon_plan_id passed to the API 
 - Query the Monitor Plan table, and retrieve the fac_id, 
 - With the fac_id, query the Plant table and retrieve facility_name and oris_code and county_cd
  - With the county_cd, query the County Code table, and retrieve the the state_cd and county_name

For retrieving the Evaluation results, call the vw_mp_evaluation_results view and pass the following parameters in the where clause: ccd.process_cd=MP and the cs.mon_plan_id=[mon_plan_id passed to the API]

**Comment by sanleyCVP** [comment]
We need to confirm the DB tables  from which we will pull the data for the report

**Comment by sanleyCVP** [comment]
View details
CREATE OR REPLACE VIEW camdecmpswks.vw_mp_evaluation_results 
AS
select (case 
			when sp.stacK_name <> null then sp.stacK_name 
			else u.unitid 
		end) as unitStackInformation
		,cl.severity_cd as severityCode
		,ccd.category_cd_description as categoryCodeDescription
		,cc.check_type_cd||'-'||cc.check_number||'-'||ccr.check_result as checkCode
		,cl.result_message as resultMessage
from camdecmpswks.check_log cl
	join camdecmpswks.monitor_location ml on cl.mon_loc_id = ml.mon_loc_id
	left join camdecmpswks.stack_pipe sp on ml.stack_pipe_id=sp.stack_pipe_id
	left join camd.unit u on ml.unit_id = u.unit_id
	join camdecmpsmd.check_catalog_result ccr on cl.check_catalog_result_id=ccr.check_catalog_result_id
	join camdecmpsmd.check_catalog cc on ccr.check_catalog_id=cc.check_catalog_id
	join camdecmpsmd.rule_check rc on cc.check_catalog_id=rc.check_catalog_id
	join camdecmpsmd.category_code ccd on rc.category_cd = ccd.category_cd
	join camdecmpswks.check_session cs on cl.chk_session_id = cs.chk_session_id;

**Comment by mosesdeeCVP** [comment]
![2300 MP Evaluation Report - Create API Endpoints.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7289e9a7-6750-45aa-8c27-e6fd185e5c9d)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC513](https://epacamd.testquality.com/project/11428/plan/22924/test/316524)
Test Passed
