### ISSUE TITLE
Spike: Research download not working on the custom data download 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2317]
## Context 

Research why the download functionality is not working on the custom data download 

## Steps to Reproduce

The custom data download is not generating a download for a users customized dataset. This bug is applicable to all data types (emissions, allowance, and compliance data) 

**Steps to Reproduce the bug:** 
1. Navigate to the custom data download 
2. Select a data type and data sub type 
3. Select filter criteria 
4. Select Preview Data 
5. Select download 

The system does not generate a download of the customized data set.

**Comment by junie-stigdon** [comment]
Needed to add "content-dispostion" header to the camdaux.cors tables so it would send that header to the UI. Problem is now resolved, no further action is needed. 

#2328 is retest only
