### ISSUE TITLE
Manage Emissions Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#232]
Value: Provide the ability for power plants to submit emissions data so they can comply with regulations

**Comment by JorjaComer** [comment]
See dependency: Will need the ability to manage submission windows before emissions data submission is complete

**Comment by annalbrecht** [comment]
At the ECMPS 2.0 ticket refinement meeting held on 2/13/24, Chris instructed us to close Uber Epics.
