### ISSUE TITLE
Pre-filter Data - Monitoring Qualification LEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2321]
As an ECMPS user, I want the dropdown options for the Monitoring Qualification LEE data fields to be limited so I can only make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Monitoring Qualification LEE data
When I open a 'Create/Edit' modal
Then the options for the 'Parameter', Qualification Test Type and 'Units of Standard' dropdown fields are limited 

Notes:
1. The 'Parameter Code' options should be limited to: HG, HCL
2. The 'Qualification Test Type' options should be limited to: INITIAL, RETEST
3. The 'Units of Standard' options should be limited to: LBTBTU, LBMBTU, LBMWH, LBGWH
4. Tech team created the view **camdecmpsms.vw_quallee_master_data_relationships**
5. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/9d33cf5b-b2e0-462f-8a83-425c2ac6d5f7/download](https://app.zenhub.com/files/287570343/9d33cf5b-b2e0-462f-8a83-425c2ac6d5f7/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC585](https://epacamd.testquality.com/project/11428/plan/22483/test/327486)

**Comment by mosesdeeCVP** [comment]
![2321 Pre-filter Data - Monitoring Qualification LEE Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dedf4204-380d-4684-9cc1-c43a54d6f3c2)

**Comment by mosesdeeCVP** [comment]
![2321 Pre-filter Data - Monitoring Qualification LEE Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/618e6ab3-fae9-47fa-be24-0d7d390a422c)

**Comment by mosesdeeCVP** [comment]
Test Passed
