### ISSUE TITLE
Pre-filter Data - Monitoring Formula Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2322]
As an ECMPS user, I need the Monitoring Formula data dropdown options to be pre-filtered based on the selection made for Parameter Code, so I only see and can make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Monitoring Formula data
When I open a 'Create/Edit' modal
Then only the 'Parameter' field dropdown is enabled and available for selection, and
When I make a selection for the 'Parameter' (Parameter Code) field dropdown
Then the 'Formula Code' dropdown options are displayed dynamically

Given I change the selection I made for the 'Parameter' (Parameter Code) field
When I access the 'Formula Code' dropdown
Then the dropdown options are refreshed based on my new selection

**Text on the Create/Edit Modal:** You must make a selection for the 'Parameter' field to enable dropdowns for the other fields

Notes:
1. The 'Parameter Code' options should be limited to: CO2, CO2C, CO2M, FC, FD, FGAS, FLOW, FOIL, FW, H2O, HCLRE, HCLRH, HFRE, HFRH, HGRE, HGRH, HI, HIT, NOX, NOXR, OILM, SO2, SO2R, SO2RE, SO2RH
2. Tech team created **camdecmpswks.vw_formula_master_data_relationships**
3. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/f01564d9-1183-4a28-9d54-4d027333e971/download](https://app.zenhub.com/files/287570343/f01564d9-1183-4a28-9d54-4d027333e971/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC553](https://epacamd.testquality.com/project/11428/plan/20423/test/325247)

**Comment by mosesdeeCVP** [comment]
![2323 Pre-filter Data - Monitoring Default Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1494af1e-d3f8-45a1-ad2e-57f4e42a582e)

**Comment by mosesdeeCVP** [comment]
Test Passed
