### ISSUE TITLE
Pre-filter Data - Monitoring Default Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2323]
As an ECMPS user, I need the Monitoring Default data dropdown options to be pre-filtered based on the selection made for Parameter Code, so I only see and can make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Monitoring Default data
When I open a 'Create/Edit' modal
Then only the 'Parameter' field dropdown is enabled and available for selection, and
When I make a selection for the 'Parameter' (Parameter Code) field dropdown
Then the options for the 'Default Purpose Code', 'Fuel Code', 'Units of Measure Code', and 'Default Source Code' dropdown fields are displayed dynamically

Given I change the selection I made for the 'Parameter' (Parameter Code) field
When I access the 'Default Purpose Code', 'Fuel Code', 'Units of Measure Code', and 'Default Source Code' dropdown fields
Then the dropdown options are refreshed based on my new selection

**Text on the Create/Edit Modal:** You must make a selection for the 'Parameter' field to enable dropdowns for the other fields

Notes: 
1. The 'Parameter Code' is the driving field and options should be limited to: CO2N, O2X, CO2R, NOXR, SO2R, MHHI, H2ON, H2OX, CO2X, O2N, SO2X, NOCX, NORX, FLOX, H2O, BWA, MNHI, MNNX, MNOF, MNGF
2. The 'Operating Condition Code' options should always display: A, C, B, P, U regardless of Parameter selection (this field should be loaded with values along with parameter selection)
3. **Tech team created camdecmpswks.vw_defaults_master_data_relationships**;
4. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/ff658cc8-6b4b-4364-ba4a-eebd90ff32ba/download](https://app.zenhub.com/files/287570343/ff658cc8-6b4b-4364-ba4a-eebd90ff32ba/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC555](https://epacamd.testquality.com/project/11428/plan/21902/test/325250)

**Comment by mosesdeeCVP** [comment]
![2323 Pre-filter Data - Monitoring Default Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/20135d96-b224-434a-ae1a-46ea3b096ded)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![2323 Pre-filter Data - Monitoring Default Data 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7b2c2b72-e0e9-48dd-a592-bca3401ed798)

**Comment by mosesdeeCVP** [comment]
Test Passed
