### ISSUE TITLE
Pre-filter Data - Monitoring Load Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2325]
As an ECMPS user, I want the dropdown options for the Monitoring Load data fields to be limited so I can only make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Monitoring Load data
When I open a 'Create/Edit' modal
Then the options for 'Maximum Load Units of Measure' should be limited to 'MW, KLBHR, MMBTUHR'
And the options for 'Normal Level Code' and 'Second Level Code' should be limited to 'L, M, H'

The dropdown field options for Monitoring Load data are independent of each other

Notes:

1. The 'Maximum Load Units of Measure' options should be limited to: MW, KLBHR, MMBTUHR
2. The 'Normal Level' and 'Second Level' options should be limited to: L, M, H
3. Tech team created **camdecmpsmd.vw_load_master_data_relationships**
4. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/e7ae58a5-6cb5-4759-bcf3-59e0233a8870/download](https://app.zenhub.com/files/287570343/e7ae58a5-6cb5-4759-bcf3-59e0233a8870/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC578](https://epacamd.testquality.com/project/11428/plan/21921/test/326172)

**Comment by mosesdeeCVP** [comment]
![2325 Pre-filter Data - Monitoring Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2b4f00d9-2257-4d6f-b33b-cfbd7215e5ad)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Test Passed
