### ISSUE TITLE
ECMPS Contact Us - API Updates

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2329]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I need the ability to submit a query about the application, so I can seek help when needed

Acceptance Criteria:

Given I am an ECMPS user on the Help/Support page
When I submit a Contact Us request
Then a request notification/email is sent to: ecmps-beta@camdsupport.com

I see the success message once the email request is submitted.

Info on the API:

Contact Us Email
https://easey-dev.app.cloud.gov/quartz/api/triggers/notifications/emails
https://easey-dev.app.cloud.gov/quartz/api/swagger/index.html
please set the purpose property to Contact ECMPS Support when using this from the Contact Us
These are protected by an API Key that must be passed in the x-api-key header

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC505](https://epacamd.testquality.com/project/11428/plan/21815/test/316248)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![2329 ECMPS Contact Us - API Updates -1 .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/18d916a6-7383-4e9e-b6ec-b859c5815606)

![2329 ECMPS Contact Us - API Updates - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6cf296b5-f4a7-4296-b69b-84734addeeaf)

**Comment by mosesdeeCVP** [comment]
Test Passed
