### ISSUE TITLE
Manage EASEY In Admin Functions 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#233]
Value: Provide the ability to manage administrative functions, such as user, submission windows, etc. 

Include Error suppression functions as part of this module when worked 

Note: need to confirm with EPA what functions the EPA admins can access within ECMPS. For example, should they be prohibited from seeing workspaces?

**Comment by JorjaComer** [comment]
Removing from PI 4 to reflect the change in direction of the BRE.

**Comment by annalbrecht** [comment]
At the ECMPS 2.0 ticket refinement meeting held on 2/13/24, Chris instructed us to close Uber Epics.
