### ISSUE TITLE
MP Evaluation Report - Populate from API

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2330]
Connect to API in order to populate the MP Evaluation Report

Notes from #2275
1. Ensure the Check Code column can be sorted
2. Add white-space between "Facility Details" banner and "Facility ID (ORISPL)" label

**Comment by mosesdeeCVP** [comment]
![2330 MP Evaluation Report - Populate from API.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5a0e420c-d37a-4c53-afbf-ac62addc743c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC515](https://epacamd.testquality.com/project/11428/plan/22924/test/316536)

**Comment by mosesdeeCVP** [comment]
Test Passed with 1 bug:
When the user clicks on the Print button the formatting of the report does not transfer to the print functionality. 

Bug Ticket: [MP Evaluation Report - Printing Format #2359](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2359)
