### ISSUE TITLE
MP Evaluation - Read Evaluation Status

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2332]
Reading the Evaluation Status in the front end to change the Evaluation Status to In Queue

UI should stay in-sync with the database by refreshing the evaluation status every 30 seconds

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e61a1098-2c6f-42ed-9357-824db51bc85c)

Notes: The Check Engine Evaluation process will update the eval_status_cd field to "WIP" once the evaluation has started and update to either "PASS", "ERR", or "INFO" once completed based on the check sessions severity code result.
We also need to add insert & update triggers to the workspace tables that will set the monitor plan eval_status_cd to "EVAL" any time data is changed in any monitor plan table

**Comment by mosesdeeCVP** [comment]
Critical Errors - ERR
![2332 MP Evaluation - Read Evaluation Status - ERR.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/75b35296-be39-45ed-8328-500c29420e58)

**Comment by mosesdeeCVP** [comment]
Needs Evaluation - EVAL
![2332 MP Evaluation - Read Evaluation Status - EVAL.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/33b53064-01f9-4947-8cd5-c1176f59ed1c)

**Comment by mosesdeeCVP** [comment]
Informational Message - INFO
![2332 MP Evaluation - Read Evaluation Status - INFO.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/94f47c5f-1626-4e0f-911b-405ab41ea2fc)

**Comment by mosesdeeCVP** [comment]
In Queue - INQ
![2332 MP Evaluation - Read Evaluation Status - INQ.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e9dd2393-8092-4f22-92c2-6013c65fd988)

**Comment by mosesdeeCVP** [comment]
Passed - PASS
![2332 MP Evaluation - Read Evaluation Status - PASS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f573c526-8419-466e-9efc-929cd509a584)

**Comment by mosesdeeCVP** [comment]
In Progress - WIP
![2332 MP Evaluation - Read Evaluation Status - WIP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/24a524d3-1378-4e52-8823-b472540e4de7)

**Comment by mosesdeeCVP** [comment]
Worked along with the developer to confirm that the Backend and Front end were working in sync

**Comment by mosesdeeCVP** [comment]
Test Passed
