### ISSUE TITLE
Logout Button Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2337]
The logout button location on the utility nav tool bar is incorrect.

Current Location:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/bd5af5b6-d5b0-4952-8ae5-968efb872da3)

Expected Location:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9101ee21-0273-4a58-ad4b-875642ae730c)

https://xd.adobe.com/view/05b0e234-0db4-4767-9d26-bfbe67442482-50e3/screen/7fc1bf4f-62b4-448c-848e-d62767c69aae

Note: Verify that the tab order is correct once the fix is implemented for 508 compliance

**Comment by mosesdeeCVP** [comment]
![2337 Logout Button Location - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dcad630c-2fdb-4aaf-b47c-1e4fbfaa68a9)

![2337 Logout Button Location - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e0d4198e-c1c1-4349-a20a-da8316e86895)

**Comment by mosesdeeCVP** [comment]
Bug is fixed
