### ISSUE TITLE
Filter by Keyword - Collapse Configurations by Default

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2338]
When a user filters by keyword for a Facility, results are displayed accordingly. If the user changes the keyword and clicks on Filter, the Configurations under the Facility are retained from the previous filter. 

Expected Behavior: Collapse the accordion for the Facility by default when the filter results get displayed

**Steps to replicate:**

- Use any of the values from the 'State' column as a Keyword and Filter
- Review the results displayed
- Use another Keyword, click Filter
 Observations: The results get displayed as per the Keyword used, however, the Configurations under the Facility are retained from the previous filter and only get refreshed once the Facility is collapsed and expanded again.

**Comment by mosesdeeCVP** [comment]
Big fixed
