### ISSUE TITLE
Spike: Monitoring Plan Import Validation 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2340]
- [x]  Identify gaps between JSON Schema and XML Schema Validation 

- [x] Define JSON Schema for Monitoring Plan

- [x]  Report back to user if there are any validation errors 

- [x] Extract QA Check Engine Import Validation logic (Consult w/ Dwayne)

**Comment by SimeraHailu** [comment]
![image.png](https://images.zenhubusercontent.com/5f43c6d36fda384720d2e570/76cebdba-22b6-4ac4-8ec8-d1142f7cdfde)

**Comment by SimeraHailu** [comment]
![image.png](https://images.zenhubusercontent.com/5f43c6d36fda384720d2e570/abd1046e-1396-4b0f-9039-9b0841fcb72e)

**Comment by SimeraHailu** [comment]
https://customervaluepartners-my.sharepoint.com/:u:/r/personal/conradsanley_cvpcorp_com/_layouts/15/doc2.aspx?sourcedoc=%7BA3E2B02B-7247-4810-B612-8A59EAEA4EC3%7D&file=MP%20Import%20Process.vsdx&wdOrigin=OFFICECOM-WEB.MAIN.REC&ct=1643815560219&action=default&mobileredirect=true&cid=589fb919-236a-4f3f-bd49-e7227b0a9d97

**Comment by sanleyCVP** [comment]
Updated Diagram
![image.png](https://images.zenhubusercontent.com/6143891f8447a5585788734a/eacd6434-9adf-4a77-ac40-ca48346dde56)

**Comment by sanleyCVP** [comment]
Should this process be enabled for retired MPs? **No**
Should we allow the import process be triggered at the Mp selection screen? **No. Only on the individual Configuration screen that the user is on**
Is the MP import restricted to one MP per file? or Should the process support import of multiple files at a time? **Yes, we allow the user to import one MP file at a time which shall replace the data for that MP once successfully imported. We won't be supporting multiple file import at this time**
Confirm that Import checks 5,6 and 9 will compare against the Workspace schema **All data comparison happens against the workspace**

**Comment by sanleyCVP** [comment]
The validations performed under the Validate step include (see file attached):
1. Validate that the facility and configuration being imported exist in the Workspace database
2. Validate that the user has permissions to update the selected facility & configuration
2. Validate data consistency within the JSON import file
3. Validate the format of data in the JSON import, and ranges where applicable, using the JSON schema (see #2613)
4. Validate data correctness where applicable using decorators and validation routines. These checks if necessary will validate against the workspace schema 

[https://app.zenhub.com/files/287570343/43bcd1a9-e62c-4828-9990-bca97f460b0e/download](https://app.zenhub.com/files/287570343/43bcd1a9-e62c-4828-9990-bca97f460b0e/download)
