### ISSUE TITLE
Spike and Implementation: Globally Implement San Serif Font

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2342]
List all the screens where we need to update the font in ECMPS

Assessment:
Assess the effort to globally implement the font
Overwrite the EASEY Design System
Global styling of the application to better align the EPA styling guidelines and the USWDS guidelines over EASEY Design recommendations

San Serif Font to be implemented: **Source Sans Pro**

Note: Added implementation effort to the original Spike

**Comment by mosesdeeCVP** [comment]
![2345 Spike and Implementation _ Globally Implement San Serif Font.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d9ec89de-79d0-43ce-a701-174f43551deb)

**Comment by mosesdeeCVP** [comment]
Font has been updated
