### ISSUE TITLE
ECMPS Home Screen - Add Content

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2347]
As an ECMPS User, I need information on application on its home screen so I can use it for reference

Acceptance Criteria:

Given I am a user of ECMPS 
When I am on the home page
Then:

1. I see that the header 'About ECMPS' is renamed to 'About ECMPS 2.0 Beta' and there is content under it

Content:
The Emissions Collection and Monitoring Plan System 2.0 Beta is the new web-based reporting tool 
released in beta form to allow industry users and the public to begin testing and learning the new 
application. The initial application, released in December of 2021, begins with the limited functionality 
of view (no login required) and edit/evaluate (CDX Test login required) of monitoring plan data. 
Subsequent releases throughout 2022 will add import and export functionality and the additional data 
types—QA, certifications, and emissions. Data in the beta is not production data and is only being used 
for testing purposes.
There are two primary goals of the extended beta process. 
1. Allow users to learn the new web-based reporting tool and provide feedback to EPA.
2. Allow EPA time to test and integrate the beta application into the future production environment and 
incorporate user feedback. 
Please subscribe to https://ecmps.blogspot.com/ for additional updates. Have questions or feedback? 
Please contact us at through our Contact Us form (https://easey-dev.app.cloud.gov/ecmps/help-support)
**Testing Note:** Contact Us form shall be a hyperlink to the Contact Us form that opens in a different tab

2. The Lorem Ipsum under Monitoring Plans is updated to:
The monitoring plan describes how a facility (monitoring configuration) monitors its emissions. 
Monitoring plan data define relationships between stacks, pipes, and units, specify locations at a facility 
from which emissions are monitored, and identify systems of monitoring equipment by detailing the 
individual system components. Monitoring plan data also provide operational characteristics and 
qualifications for certain special types of monitoring (e.g., low mass emissions monitoring). Draft beta 
monitoring plan instructions can be found here (https://app.zenhub.com/files/287570343/449899ef-7a75-4129-995c-ae4bf2e347bf/download).
**Testing Note:** 'here' shall be a hyperlink to the Draft Beta Monitoring Plan Reporting Instructions 

3. The Lorem Ipsum under QA and Certifications is updated to:
**This data is not included as part of the initial beta release and will be added with updates in 2022.** 

QA and certification tests are required for all types of monitoring systems. Test extension or exemption 
data indicate variances from prescribed testing requirements or extensions to the normal QA testing 
schedule. QA or certification events (e.g., monitor replacements), as well as data elements for 
submitting an electronic certification application when certifications are required, are submitted when 
there is either diagnostic or recertification testing of specific monitoring systems or components.

4. The Lorem Ipsum under Emissions is updated to:
**This data is not included as part of the initial beta release and will be added with updates in 2022.** 

Emissions data are hourly values for measured parameters, calculated hourly emissions values, 
instrument calibration data, and aggregated summary data. An emissions file contains one calendar 
quarter of hourly and aggregate emissions measurements for a specified unit or group of related units, 
including stacks and pipes. Each unit that is required to submit emissions data for a particular calendar 
quarter must be included in one and only one emissions file for that quarter. Each emissions file should 
contain all relevant operating, daily quality assurance, and emissions data for all units, common stacks, 
multiple stacks, or common pipes that were in a common monitoring configuration for any part of the 
quarter.

- Text in the What's New Box is updated to:
Welcome to the first release of the all new ECMPS 2.0 Beta! To view a list of functionality and how to get 
started go here (hyperlink to quick start guide, webinar release). Have questions or feedback? Please 
contact us through our Contact Us form (https://easey-dev.app.cloud.gov/ecmps/help-support)

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/936c6192-6425-4f75-bec4-e9e4fcad7694/download](https://app.zenhub.com/files/287570343/936c6192-6425-4f75-bec4-e9e4fcad7694/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC514](https://epacamd.testquality.com/project/11428/plan/19352/test/316528)

**Comment by mosesdeeCVP** [comment]
![2347 ECMPS Home Screen - Add Content.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/625fca91-e171-4771-ab5d-4c7cff5ea4bb)

**Comment by mosesdeeCVP** [comment]
Test Passed
