### ISSUE TITLE
Reporting Instructions Screen - Add JSON Format and URL

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2348]
Under Monitoring Plan Reporting Instructions, add:

Monitoring Plan JSON Format
Monitoring Plan - Swagger Page (https://easey-dev.app.cloud.gov/api/monitor-plan-mgmt/swagger/)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC509](https://epacamd.testquality.com/project/11428/plan/22924/test/316511)
Test Passed

**Comment by mosesdeeCVP** [comment]
![2348 Reporting Instructions Screen - Add JSON Format and URL.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a09f39a6-cb19-4473-aefe-bba9559392ee)
