### ISSUE TITLE
CAMPD Contact Us- 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2353]
## Context 

Testing complete for 1933, 2 issues related to the Error/Success messages that display:
1. Error/Success test is at a Heading level 4, based on the page structure they should be at H2 - Datateers specific 
2. The Error/Success messages are not automatically announced to a screen reader when submit is selected, suggest either shifting focus to the messages or putting them in an aria live region.

**Comment by JanellC** [comment]
Issue 2 is an issue on CAMPD and ECMPS. After this ticket is closed, ECMPS will need to update their package of the EASEY Design system in order to see the 508 updates on the application @vishnunavuluri

**Comment by aprematta** [comment]
Retest complete, messages are in a live region and error/success is at an H2
