### ISSUE TITLE
Reusable component for tool tips - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2354]
## Context 

Testing complete for 2282. This is good with keyboard and seemed ok with ANDI, but when I use the screenreaders there are issues. For JAWS, when Tabbing the result is expected. However when navigating with line by line, the tooltip is not picked up at all (this is also known as browse mode). In NVDA, if I tab to it, nothing is announced. In browse mode again it's like nothing exists. I'm thinking the different results are based on the way it's coded. There might not be the best support for a role of tooltip. For the aria assertive.... I don't think this will announce the aria label consistently.....this is more for actual text that will appear on screen in the html. What might work is to change this to a role of img and alter the aria label to include the word tooltip...."tooltip: Data type and subtype can be changed at any time".

**Comment by aprematta** [comment]
Retest complete. Passes all scenarios: Keyboard, ANDI, JAWS when tabbing and browse mode, NVDA when tabbing and browse mode
