### ISSUE TITLE
Retest Only: Custom Data download filter - 508 issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2355]
## Context 

Testing complete for 2231 - issue found when no results are returned for a combobox...such as owner operator. When the filter logic causes no results, if you open the combox it says 'no owners/operators' match your search. However this text is not accessible to a screen reader. This may be a non issue because I believe it was stated the filter button will be disabled in a future sprint, however right now this scenario would be flagged.

**Comment by JanellC** [comment]
Retest ticket when Disable filters that do not contain selectable data #2343 is completed and Bug: Filter logic year and vintage year component #2432 is resolved

**Comment by JanellC** [comment]
@aprematta This ticket is ready for testing

**Comment by aprematta** [comment]
Closing issue, since the filter button is now disabled with no results, you can't get to the inaccessible text.
