### ISSUE TITLE
Spike: Pre-filtering of Data/Restrict dropdown options in ECMPS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2357]
- Solution to filter information in the dropdown lists for different components in the ECMPS UI
- Review DB relationships 
- Determine the necessary API updates
- Consider the needed UI updates

Dev Notes: USe Methods as a starting point

**Comment by sanleyCVP** [comment]
Pending completion of the Reporting Instructions exports and creating the supporting Zen-hub tickets

**Comment by sanleyCVP** [comment]
1. Created and linked all storied related to this implementation
2. Attached the master document that defines all filtering details
[https://app.zenhub.com/files/287570343/4cafa045-abcb-4e70-a600-936aaac01c47/download]
