### ISSUE TITLE
Monitoring Plan Evaluation Report - New Screen

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2360]
## User Story
As an ECMPS user, I want the Monitoring Plan Evaluation Report to open on a separate screen so I can access it by clicking on the link provided in the Monitoring Plan Evaluation email. 

## Acceptance Criteria
Given I am an ECMPS user accessing the MP Evaluation Report
When I click on Evaluation Report link from the Monitoring Plan Evaluation email
Then the MP Evaluation Report opens on a separate screen

https://xd.adobe.com/view/bdf8fe62-0af2-4fbd-8672-0b7959f8bb88-e8ab/

Note (12/14/2021):
- Keep the columns sortable
- Remove hyperlinks on the Check Code data. Keep the color blue for the text

MP Evaluation Report access from the notification email: https://easey-dev.app.cloud.gov/ecmps/workspace/monitoring-plans/02022-614W-168CEAA018
EA4CBDAE347BE98F95A548/evaluation-report/

## Testing
Test Case: [TC519](https://epacamd.testquality.com/project/11428/plan/22924/test/318380)
Tester: @mosesdeeCVP

**Comment by vishnunavuluri** [comment]
Note: Open in a new browser tab and the Report shall not have the navigation options including the utility navbar and the left navigation.

**Comment by dionolympiaCVP** [comment]
For the initial version of this implementation, we will have the report a separate page that will not require login credentials to access and will not have the EPA header.

**Comment by mosesdeeCVP** [comment]
![2360 Monitoring Plan Evaluation Report - New Screen.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c286618e-b93c-48dd-83d1-4f5caac33fd5)

**Comment by mosesdeeCVP** [comment]
Test Passed
