### ISSUE TITLE
Contact Us Page - 508 Issue

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2362]
The Error/Success messages are not automatically announced to a screen reader when submit is selected, suggest either shifting focus to the messages or putting them in an aria live region.

**Comment by vishnunavuluri** [comment]
Dependent on CAMPD Contact Us- 508 Issue #2353

**Comment by aprematta** [comment]
This has been fixed, messages are contained in aria live regions
