### ISSUE TITLE
ECMPS Home Screen Content

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2363]
Updates to the content on the ECMPS Home Screen:

- Italicize the text in paragraph 1 of 'About ECMPS 2.0 Beta'
- Update the color contrast of the hyperlinked text from 4.0:1 to 4.5:1
Color Recommendations:
Accent Cool Button: https://zeroheight.com/37f47ceee/p/44bc08-buttons
Hover: https://zeroheight.com/37f47ceee/p/44bc08-buttons/i/52507572
Active: https://zeroheight.com/37f47ceee/p/44bc08-buttons/i/52507579
- Underline the hyperlinks (Hyperlinks to be the same color as the hyperlink text)

**Comment by mosesdeeCVP** [comment]
Paragraph 1 of 'About ECMPS 2.0 Beta' is Italicized. 

![Italicized.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7aecab90-3ef5-4e29-a94d-1bfb27cf1e44)

**Comment by aprematta** [comment]
Link text now meets contrast and links are underlined......closing ticket
