### ISSUE TITLE
Fix the CDX and CBS Links in Beta Test Env

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2366]
Following fixes to be implemented in ECMPS beta test env:

On the Login Window of ECMPS - Update the hardcoded URLs to env variables for the following:
- **Create an account**
- **Forgot username**
- **Forgot password**

On the user profile menu, the '**Manage Delegations**' CBS link should be shown/hidden based on an env variable that enables this link.

For beta, the login links should forward to the correct pages in the test environment.  The CBS link ('Manage Delegations' in the user profile menu) should not be displayed.

**Comment by mosesdeeCVP** [comment]
Links fixed
