### ISSUE TITLE
Update Prototype - MP Evaluation Report

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2370]
Update the prototype for MP Evaluation Report to reflect the following changes:

- MP Evaluation Report shall open in a separate browser tab
- MP Evaluation Report tab shall NOT have any of the navigation options including the utility nav menu and the left nav
- The Report shall have the EPA logo (Style with Trim): https://www.epa.gov/stylebook/using-epa-seal-and-logo
- Update the button Download PDF to Print to PDF

A sample of current MP Evaluation Report is attached for reference

![Monitoring Plan Evaluation Report.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d261de02-1755-4818-9f2b-5df7d5ca2071)

**Comment by AllisonFrancis** [comment]
Updated report link https://xd.adobe.com/view/bdf8fe62-0af2-4fbd-8672-0b7959f8bb88-e8ab/
