### ISSUE TITLE
Check Engine and Kibana Dashboard

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2371]
Problem: Check Engine errors and details will not be logged in a format that will allow the Kibana dashboard to consume them. However, we can use the container logs within cloud.gov if needed

Impact: It does not impact the frontend user and they will get an email with results even if it fails. However, depending on the error we may not get the full details and may have to look into the container logs and investigate

**Comment by MaeganWood64** [comment]
Closed due to changing events and requirements with the addition of Splunk monitoring system
