### ISSUE TITLE
Fix Broken Unit Tests - PI 6

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2374]
## Context 
- Only for API Work 
- [x] Increase code coverage to at least 70%
- [x] Fix Broken unit tests caused by latest refactoring

**Comment by junie-stigdon** [comment]
Fixed broken unit tests

emissions: https://github.com/US-EPA-CAMD/easey-emissions-api/pull/103
account: https://github.com/US-EPA-CAMD/easey-account-api/pull/59
facilities: https://github.com/US-EPA-CAMD/easey-facilities-api/pull/69
