### ISSUE TITLE
Test CDC in Preparation for CAMPD Release 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2383]
- [x] Wipe data from staging and do a complete reload 

- [x] Truncate the logs so only new changes are reflected 

- [ ] Apply changes to NCC database (ERG) 

- [ ]  Verify changes that changes to the NCC tables are reflected in cloud.gov the next day

**Comment by vkdontula** [comment]
I have truncated and re-loaded Datamart tables in Staging database.  Also, truncated the Log tables in CAMDPUBS staging.  We are ready with ETL jobs for CDC (for Datamart, Emission and CAMDDBSS tables) and Monthly full load for Datamart tables testing.
