### ISSUE TITLE
508: Make Aria Label more clear

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2394]
Issue: An Aria Label exists but the value does not fully describe the functionality

Add to the Aria Label words ' in a new tab' to indicate that content from this menu will open in a new tab. On the Open links in the Actions column on the Select Configurations page

**Locations where the aria-label needs to be updated:**
In Global-View and Workspace:- In the Select Configurations tab: Add aria-label for Open and Open and Check-Out options

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/8bb431ae-f1f5-49ae-8309-55951ede79dd)

**Comment by aprematta** [comment]
Testing complete, no issues found. Checked View only and checked in links
