### ISSUE TITLE
508: Duplicate Table Names

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2395]
Issue: Multiple tables on the same page are named the same

Select Configurations is used for the aria label of the sub-tables. Suggest they be changed to <Facility Name> Configurations

For Select Configurations:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/09e3307e-81e6-400a-b093-2d4edd75def9)

For Facilities: (Update aria-label to 'Select Facility')

For the Configurations under the Facility, add the aria-label 'Select Configuration under the **Facility Name**'
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3d0b4224-9703-4080-9770-8bc32777c77b)

**Comment by dionolympiaCVP** [comment]
Requirements were completed in [Ticket 2265](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2265)

**Comment by JorjaComer** [comment]
@aprematta Can this be closed?

**Comment by aprematta** [comment]
Just took a look, yes the data tables have unique names now
