### ISSUE TITLE
508: Elements not Keyboard Accessible

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2396]
Issue: Elements are present which are actionable by a mouse but not actionable with simple keyboard controls (directional arrows, Tab, Enter, Space Bar). The manage login and delegations links can only be reached via a mouse, the down arrow next to the user initials when logged in can be tabbed to but not expanded.

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9bfe7808-a05e-48a5-984d-c561a8d8e6c5)

Resolution: Make the down arrow next to UserID actionable with keyboard control so it can be expanded to access Manage Login and Manage Delegations options

**Comment by aprematta** [comment]
2 issues found. 
1. Aria hidden is used img id="toggleDropDown" src="/ecmps/images/icons/menu-item-expand.svg" class="margin-top-neg-1 position-relative left-neg-1" aria-hidden="true" 
2. Aria expanded should be used and set to true or false based on whether the subitem is visible or not. See the code for the navigational elements that are similar and to the left of it.

**Comment by aprematta** [comment]
Element is keyboard accessible, going to create another ticket for the other issues
