### ISSUE TITLE
508: Identification of an element across pages is inconsistent

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2397]
The Lefthand links for read-only and editing are named the same. Suggest adding an Aria labeled by to indicate the Workspace links.

Issue: Add aria-label to differentiate between the options under the Global-View and the Workspace

Global-View (Add aria-labels as below):
Monitoring Plans - Global-View
QA & Certifications - Global-View
Emissions - Global-View

Workspace (Add aria-labels as below):
Monitoring Plans - Workspace
QA & Certifications - Workspace
Emissions - Workspace

**Comment by aprematta** [comment]
Aria labels have been properly implemented, closing ticket
