### ISSUE TITLE
508: Visual Headings lack Heading Tags

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2399]
Issue: Text has been visually altered to act as a heading but the text has not been coded as a heading. To Assistive Technology users, this text appears no different than normal paragraph text. 

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0648d2bb-25f4-4659-bef3-be6da2ba9ad8)

In the Configurations tab, visual headings that precede the data tables are coded with span tags, update  the following:

- Defaults
- Formulas
- Loads
- Location Attributes
- Methods
- Qualifications
- Rectangular Duct WAFs
- Spans
- Systems
- Unit Information

Note: Get the header styling info

**Comment by aprematta** [comment]
No issues found
