### ISSUE TITLE
Review GitHub Scanning 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#240]
Review the security scanning options within GitHub and determine if it will meet our needs 

https://github.blog/2020-09-30-code-scanning-is-now-available/

https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

**Comment by srinivasaregeti** [comment]
Added the workflow, however currently the trigger the scan is disabled. By default it runs every night at 3AM.
Further discussion is needed to decide the frequency of the scan.
