### ISSUE TITLE
Fix styling issues in ECMPS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2401]
Note: All the screenshots show the issue in the left image and the expected display in the right image

**1. Fix the alignment of buttons on Modals (Save, Close, etc.)**
- modal - buttons aligned left when they were aligned right, background is grey when it was white, margin/padding changed
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/46b10e95-0f79-49d2-818e-78648594e3ad)
- Check Back In button label aligned to bottom
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9497e2b0-3b41-461e-be3a-5ef5b328c81f)
- buttons & general alignment issues
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/8c33ab06-80f7-404b-b8dc-d94b21b12fd6)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7a6eddff-93a8-408a-b191-91f638d203e7)

**2. Fix styling issues with individual Configuration tabs** 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a822beb7-3d94-48dc-9326-bbc91333fabe)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9de9a174-0ac6-41ac-ba86-8e97320baac0)

**Comment by mosesdeeCVP** [comment]
Light gray Line is missing other issues fixed
![2401 Fix styling issues in ECMPS 1.1 Missing line at the top.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2152528c-8d27-474d-97a5-6425b9f0f85f)

**Comment by mosesdeeCVP** [comment]
Lock icon is fixed. Pencil icon remains slightly off
![2401 Fix styling issues in ECMPS 1.2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dead5462-6e85-4903-ae5b-b84fe5fe76d8)

**Comment by mosesdeeCVP** [comment]
Fixed
![2401 Fix styling issues in ECMPS 1.4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8ea1a429-c802-4967-833d-877f029aff9d)

**Comment by mosesdeeCVP** [comment]
Fixed
![2401 Fix styling issues in ECMPS 2.1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7d83c820-c56b-4172-b9eb-2095e690e047)

![2401 Fix styling issues in ECMPS 2.2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/95e9b7a4-af91-4d39-9980-e2210767654f)

**Comment by mosesdeeCVP** [comment]
Gray Line and Pencil Icon will be fixed with the below Ticket:
[Fix styling issues in ECMPS #2453](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2453)
