### ISSUE TITLE
CAMPD 508 Testing- PI 7

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2412]
## Epic Benefit
Issues that require 508 testing in PI 7   @aprematta 

## Context

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
Testing complete for 2346..... the icons are marked as background and won't be read by a screenreader, I think that's ok because they don't seem to add any additional information to the filters

**Comment by aprematta** [comment]
Testing complete for 1651, multiple issues found:
1. There's an extra tab stop after the hamburger menu icon and before the preview data tooltip, not exactly sure what it is but should be removed.

2. When I expand the hamburger menu, focus should be put on the collapse button and vice versa.

3. The hamburger menu has no state information. (Aria expanded). Code similar to the Menu button.

4. When expanded, only the Home link is keyboard accessible, all the expandable/collapsible elements can only be used with a mouse (data, resources, etc.)

5. The expandable/collapsible elements don't have state information. Code similar to how they are on desktop.

**Comment by aprematta** [comment]
Testing complete for 1498.... the responsiveness seems to be affecting the 508 requirement for the ability to zoom to 200%, when doing so the data table obstructs the filters with no seeming way to dismiss:

![image](https://user-images.githubusercontent.com/67421847/149582348-c1415289-cbc3-46a5-bbeb-cc51b648efc4.png)

**Comment by aprematta** [comment]
No issues found with 2372

**Comment by aprematta** [comment]
Testing complete for 1465....... encountered the following 508 issues:

Activating data type button does not put focus on first focusable element on data type window

Activating Back or Cancel does not put focus back on data type button

Focus is not trapped in the Data Type window when active

Same Issues for the Filter button

The X option to clear the filter without having to open the filter window is not keyboard accessible

Not a 508 violation cause it affects all users, but if I get the following message 'Data Preview  
No results match that search criteria. Please change the criteria and try again.' there is not a way to get back to the filters

**Comment by aprematta** [comment]
No issues found for 2497

**Comment by aprematta** [comment]
Testing complete for 1820.... only issue is that the downloaded PDF is not compliant. Not sure if this is in play or not.

**Comment by aprematta** [comment]
Testing complete for 2252, not sure if it's related but I did a retest of the whole about page. The only issue is that the 'What's new in CAMPD Release 1.0 (May 1, 2022)' heading should be at a H3.....right now it's at a h4 causing an illogical hierarchy. 
**------Now fixed, no more issues for 2252-----------**

**Comment by aprematta** [comment]
Testing complete for 2226, again there are 508 issues with the actual PDF file but other than that there are no issues

**Comment by aprematta** [comment]
Testing for 2488 complete, no issues found

**Comment by aprematta** [comment]
Testing for 2033 complete, the value of the alt tag for the logo is alt="CAMPD Mark".....I think CAMPD Logo would be more clear. 

-------This issue has been fixed----
No remaining issues for 2033

**Comment by aprematta** [comment]
Testing done for 2487, no issues with the new text however aria-hidden="true" is used on the tooltip image in the helper text. 
![image](https://user-images.githubusercontent.com/67421847/151856991-a66da7a3-6872-4e4f-a310-6973f82d20bc.png)

**Comment by aprematta** [comment]
Testing for 2156 complete. The text What's New should be coded at a H2 instead of a DIV. Also, it looks like H2 tags were removed from the visual headings 'Data' and 'Maps & Graphs'

**Comment by aprematta** [comment]
No issues found with 2485

**Comment by aprematta** [comment]
Testing complete for 2565, 2 issues:
1. The message 'Your query exceeds the record limit of 100000. Refine your query to further limit the number of records returned or visit the Bulk Data Files.' disappears when zoomed into 200%
2. The message is not automatically announced to a screen reader, it needs to be in a live region.

**Comment by aprematta** [comment]
Completed testing for 2448, no issues found

**Comment by aprematta** [comment]
Completed testing for 2606, no issues found

**Comment by aprematta** [comment]
Testing for 2635 complete, no issues found

**Comment by aprematta** [comment]
Testing complete for 1653, no issues found

**Comment by aprematta** [comment]
Testing complete for 2516, no issues found

**Comment by aprematta** [comment]
Testing complete for 2636.... no issues found

**Comment by aprematta** [comment]
Testing complete for 2630, no issues found, data caveat was in a live region and announced when displayed

**Comment by aprematta** [comment]
Testing complete for 2695, couple issues found:
1. The current aria label for the checkboxes in the first column just refer to the row number.....for example aria-label="select-row-26" ..... this should reference the file name.
2. The data table lacks a programatic name, add an aria label on the div that contains role=table
3. The state of the sort order is not programatically identified (ascending/descending)
4. Table headers are not associated to data cells because they are coded with the role of 'gridcell' instead of 'cell'

**Comment by aprematta** [comment]
PI has ended
