### ISSUE TITLE
ECMPS: Fix Swagger Link in Reporting Instructions page

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2413]
Update the hardcoded Swagger url on the Reporting Instructions screen (under Resources) to make it an environment variable

Current URL: https://easey-dev.app.cloud.gov/api/monitor-plan-mgmt/swagger/
New URL:      https://api.epa.gov/easey/dev/monitor-plan-mgmt/swagger/

**Comment by mosesdeeCVP** [comment]
Big Fixed
