### ISSUE TITLE
Issue with Inactive Records and Checkbox

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2414]
Issue 1: Show Inactive checkbox should be available when a Configuration has Inactive Records (When a user adds an End Date and Time to a record, it is deemed Inactive) 

Currently, the Inactive Checkbox is always greyed out and not available even when there are Inactive Records

Issue 2: When a record has an End Date and Time added, it should be displayed in the grid by default. It only shows up when a user selects 'Show Inactive'

Reference Records under Escalante (ORIS Code: 87)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c39025c4-cbf8-410e-9595-7687da8e668f)

Issue 3: For some Sections, the Show Inactive button is enabled even when there are no Inactive records available
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7c3331d2-3ac5-4f8a-91de-8e4ad571df7b)

**Comment by mosesdeeCVP** [comment]
Issue Fixed
