### ISSUE TITLE
Refactor ECMPS calls to Master Data API

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2417]
Data from MDM APIs should be called only when components are first loaded.  They should be stored with Redux to minimize the number of calls to the database during a session. The APIs should not be called when there isn't a need for referencing.  When a section is reloaded, we should only have to reload the MP API data (ex: Methods, Defaults, Loads, etc.)

Technical Notes:
When opening a monitor plan tab I see 4 preflight OPTIONS requests followed by 4 GET requests to the same master data endpoint and this is happening for every single master data endpoint being loaded. So just on a single refresh of a monitor plan tab there were over 112 requests.

**Comment by mosesdeeCVP** [comment]
Went over the ticket with the developer. This functionality has been implemented.
