### ISSUE TITLE
Fix styling for Evaluation Status of Informational Message

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2418]
Fix the alignment of the Revert to Official Record and Submit buttons when the Evaluation Status displayed for a MP is 'Informational Message'

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/70c64c75-632b-490c-b10b-896cf4148c7c)

**Comment by mosesdeeCVP** [comment]
Alignment fixed
![2418 Fix styling for Evaluation Status of Informational Message.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c66bd1ee-56d5-429d-9cbf-a6a3a75dce3d)
