### ISSUE TITLE
ECMPS - Issues with editing Sections

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2419]
Note: All the data tables need to be refreshed when any updates are made

**Unit Control:** (Unable to Edit)
- None of the fields are editable
- 'Original Code' and 'Seasonal Controls' Radio buttons should be selected as 'No' by default. However, when we open the modal, none of the options are selected by default
- When you Create new Unit Control data, and select 'Yes' for the Seasonal Controls field, once you save it, the modal displays 'No' instead of 'Yes'. System changes it to the default option without user action (User selection not being saved)

**MATS/Supplemental MATS:** (Unable to Edit)
- None of the dropdowns are editable/updatable

**Loads:** (Unable to Create, able to Edit)

**System Components:** (Unable to Edit)
- Dates update but none of the other fields do

**Comment by mosesdeeCVP** [comment]
Bugs fixed
