### ISSUE TITLE
Pre-filter Data - Monitoring Span Data

### ISSUE THREAD

**Issue by sanleyCVP** [US-EPA-CAMD/PI-1#2423]
As an ECMPS user, I need the Monitoring Span Data dropdown options to be pre-filtered based on the selection made for Component Type Code, so I only see and can make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Monitoring Span data
When I open a 'Create/Edit' modal
Then only the 'Component Type'  field dropdown is available for selection, and
When I make a selection for the 'Component Type' field dropdown
Then the options for the 'Span Scale', 'Span Method', and 'Span Units of Measure' dropdown fields are filtered with only the valid options

Given I change the selection I made for the 'Component Type' field
When I access the 'Span Scale', 'Span Method', and 'Span Units of Measure' dropdown fields 
Then the dropdown options are refreshed based on my new selection

**Text on the Create/Edit Modal:** You must make a selection for the 'Component Type' field to enable dropdowns for the other fields

Notes:

1. The 'Component Type' options should be limited to: CO2, FLOW, HCL, HG, NOX, O2, SO2
2. Tech team created **camdecmpswks.vw_span_master_data_relationships**
3. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/bc9314e4-d38d-472e-bcc8-b785ac06c8a2/download](https://app.zenhub.com/files/287570343/bc9314e4-d38d-472e-bcc8-b785ac06c8a2/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC556](https://epacamd.testquality.com/project/11428/plan/20424/test/325251)

**Comment by mosesdeeCVP** [comment]
![2423 Pre-filter Data - Monitoring Span Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d57bf081-40c2-4dfb-a3d5-34b50999a2d2)

**Comment by mosesdeeCVP** [comment]
Test Passed
