### ISSUE TITLE
Issue with Analyzer Ranges datatable

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2424]
Note: Analyzer Ranges data tables need to be refreshed when any updates are made

**Analyzer Ranges:** (Updates not being saved consistently)
- Unable to edit dropdowns and radio-buttons 
- Information for Start Date and End Date is not available all the time even after saving

**Comment by mosesdeeCVP** [comment]
Tests Passed, bug fixed.
Re ran tests for Analyzer Range. 
[TC334](https://epacamd.testquality.com/project/11428/plan/21748/test/299059)
[TC354](https://epacamd.testquality.com/project/11428/plan/21748/test/299577)
