### ISSUE TITLE
Pre-filter Data - System Fuel Flow Data

### ISSUE THREAD

**Issue by sanleyCVP** [US-EPA-CAMD/PI-1#2426]
As an ECMPS user, I want the dropdown options for System Fuel Flow data fields to be limited so I can only make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to the System Fuel Flow data
When I open a 'Create/Edit' modal
Then the options for the 'Units of Measure Code' should be limited to SCFH, GALHR, BBLHR, M3HR, LBHR, HSCF
And options for 'Max Fuel Rate Source Code' should be URV, UMX

Notes:

1. The 'Units of Measure Code' options should be limited to: SCFH, GALHR, BBLHR, M3HR, LBHR, HSCF
2. Tech team created the view **camdecmpsmd.vw_systemfuel_master_data_relationships** 
3. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/30225c4e-97d9-4255-b4d1-fdf4b868224a/download](https://app.zenhub.com/files/287570343/30225c4e-97d9-4255-b4d1-fdf4b868224a/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC589](https://epacamd.testquality.com/project/11428/plan/20829/test/327645)

**Comment by mosesdeeCVP** [comment]
![2426 Pre-filter Data - System Fuel Flow Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/973b0e7a-5a9d-4b66-8f2d-337a09375472)

**Comment by mosesdeeCVP** [comment]
Test Passed
