### ISSUE TITLE
Pre-filter Data - Unit Fuel Data

### ISSUE THREAD

**Issue by sanleyCVP** [US-EPA-CAMD/PI-1#2428]
As an ECMPS user, I want the dropdown options for the Unit Fuel data fields to be limited so I can only make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Unit Fuel data
When I open a 'Create/Edit' modal
Then the options for the 'Indicator Code' should be limited to 'E, I, P, S'
And the options for the 'Dem GCV' should be limited to 'GHS, GGC, GOC'
And the options for the 'Dem SO2' options should be limited to: SHS, SGC

The dropdown field options for Monitoring Load data are independent of each other

Notes:
1. The 'Indicator Code' options should be limited to: E, I, P, S
2. The 'Dem GCV' options should be limited to: GHS, GGC, GOC
3. The 'Dem SO2' options should be limited to: SHS, SGC
4. Tech team created view **camdecmpsmd.vw_unitfuel_master_data_relationships**
5. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/7adefd96-8ece-45f2-8b03-f2bfdc0c1fc0/download](https://app.zenhub.com/files/287570343/7adefd96-8ece-45f2-8b03-f2bfdc0c1fc0/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC586](https://epacamd.testquality.com/project/11428/plan/22363/test/327487)

**Comment by mosesdeeCVP** [comment]
![2428 Pre-filter Data - Unit Fuel Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6efd3ce0-9155-430e-81a7-295fc44d01e4)

**Comment by mosesdeeCVP** [comment]
![2428 Pre-filter Data - Unit Fuel Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c6850496-fc4a-4217-abc6-fc48e730c506)

**Comment by mosesdeeCVP** [comment]
Test Passed
