### ISSUE TITLE
Pre-filter Data - Unit Control Data

### ISSUE THREAD

**Issue by sanleyCVP** [US-EPA-CAMD/PI-1#2429]
As an ECMPS user, I need the Unit Control data dropdown options to be pre-filtered based on the selection made for Parameter Code, so I only see and can make valid selections

Acceptance Criteria:

Given I am an ECMPS user making updates (Create/Edit) to Unit Control data
When I open a 'Create/Edit' modal
Then only the 'Equipment Parameter Code' field dropdown is enabled and available for selection, and
When I select an option from the 'Equipment Parameter Code' field dropdown
Then the options for the 'Control Code' dropdown field are filtered with only the valid options

Given I change the selection I made for the 'Equipment Parameter Code' field
When I access the 'Control Code' dropdown
Then the dropdown options are refreshed based on my new selection

**For the text on the Modal:**

**Driving Field: Parameter** 
Given I am an ECMPS user
When I open a Create/Edit modal for MP Unit Control Data 
And haven't made any updates yet (No selection for Parameter made)
Then I see the following text displayed in the modal
**_You must make a selection for the 'Parameter' field to enable dropdowns for the other fields_**

Given I am an ECMPS user
When I open a Create/Edit modal for MP Unit Control Data 
And make a selection or change the selection made for the 'Parameter' field
Then I see the following text displayed in the modal
**_Changing the selection for the 'Parameter' field shall update the dropdown options available for the other fields_**

Notes:
1. The 'Equipment Parameter Code' options should be limited to: NOX, SO2, PART, HG, HCL, HF
2. Tech team created **camdecmpsmd.vw_unitcontrol_master_data_relationships**
3. Reference the master list in https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2357

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/ea5946a3-e2b5-4bcc-b8b5-d20683e6cf7e/download](https://app.zenhub.com/files/287570343/ea5946a3-e2b5-4bcc-b8b5-d20683e6cf7e/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC587](https://epacamd.testquality.com/project/11428/plan/22363/test/327639)

**Comment by mosesdeeCVP** [comment]
![2429 Pre-filter Data - Unit Control Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6cbe7c1c-91d1-44ff-8429-0f41cd21ecde)

**Comment by mosesdeeCVP** [comment]
![2429 Pre-filter Data - Unit Control Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e364224e-4a6f-4324-aeaa-70b6a5c7230c)

**Comment by mosesdeeCVP** [comment]
Test Passed
