### ISSUE TITLE
Bug: Filter logic year and vintage year component 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2432]
## Test Case
Test Case: [TC476](https://epacamd.testquality.com/project/11428/plan/21762/test/313084)

Test Case: [TC516](https://epacamd.testquality.com/project/11428/plan/21762/test/316896) 

## Steps to Reproduce

When the compliance year and  vintage year filter tags are removed, the filter logic is not narrowed based on applied criteria. This bug is applicable to the data types that contain the compliance year component and the vintage year component. 

**Compliance Year Component Filter Logic Defect** 
1.  Navigate to the custom data download 
2. Select compliance emissions based 
3. Select owner/ operator 
4.  Apply the following criteria for owner/ operator: AEE 2,llc , AEP Energy Partners INC, AES Ohio Generation, LLC
5.  Open the state filter the following states should display: New York, Ohio, Texas
6. Close that state filter 
7. Open the year filter and apply 2003 as a year 
8. Open the state filter and the state filter should show New York as an option 
9. Remove the year filter tag 
10.Open the state filter 

The state filter continues to show New York as the only option. Since the year filter tag was removed the filter logic should be engaged based on the applied criteria (owner/ operator). New York, Ohio, Texas Should show as available options in the state filter. 

**Vintage Year Component Filter Logic Defect:** 
1. Navigate to the custom data download 
2. Select Allowance holdings 
3. Select owner/ operator 
4. Apply the following criteria for owner/ operator: 21 st securities, 5380 frontier ave energy company llc, abb energy ventures 
5. Open the vintage year filter and apply 1995 as a vintage year ( once applied the facility and state filters are disabled) 
6. Remove the vintage year filter tag 

Once the vintage year filter tag is removed the state and facility filters continue to be disabled. The filter logic should narrow based on the applied criteria (owner/ operator) 

### Actual Results
When the compliance year and  vintage year filter tags are removed, the filter logic is not narrowed based on applied criteria. This bug is applicable to the data types that contain the compliance year component and the vintage year component.

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D95](https://epacamd.testquality.com/project/11428/result/2619809/defect/9638).

**Comment by JanellC** [comment]
https://epacamd.testquality.com defect [D96](https://epacamd.testquality.com/project/11428/result/2622388/defect/9661).

**Comment by MaeganWood64** [comment]
D96 Resolved @tlageman-epa
