### ISSUE TITLE
Beta Feedback: MP Info not showing up

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2433]
The MP data is not showing up for Ocotillo Power Plant GT3

None of the Sections selected for the Location GT3 are showing any data. FACT tool has data for the same

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5a8674e8-7946-4229-8007-3be2a897cb4f)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![2433 Beta Feedback- MP Info not showing up.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b43c7196-11ad-4ff9-ba4f-dbc430a4be3b)
