### ISSUE TITLE
Beta Feedback: Mandate End Date - Time for any applicable modules

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2435]
Steps to Reproduce:
- User opens the Edit modal for Systems (any other section from the list below)
- Updates information and Save and Close without entering a value for the Time (for End Date)
- App saves the updates.

Expected Behavior: The system should restrict a user from saving **ANY** updates when there is an End Date provided but no value added for the Time (for End Date)

Update the logic for the following Modules/Sections:
- Defaults
- Formula
- Loads
- Method
- Mats Methods
- Rectangular Duct WAF
- Spans
- Systems
- System Components
- System Fuel Flows
- Analyzer Ranges

**Comment by mosesdeeCVP** [comment]
Bug fixed
