### ISSUE TITLE
Beta Feedback: Update text on Help/Support 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2436]
On the Help/Support screen – Help support, FAQ, and tutorials all currently show Lorum Ipsum.  

Update these to “Coming Soon”

Text in the Contact us section should be changed to read (Currently Lorem Ipsum): “Please complete the fields below to send an email to ECMPS Beta Support.  You may also send an email directly to ecmps-beta@camdsupport.com."

**Comment by mosesdeeCVP** [comment]
![2436 Beta Feedback- Update text on Help-Support.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c0798509-ba7b-4457-b458-fcf4051afaa2)

**Comment by mosesdeeCVP** [comment]
Text is updated
