### ISSUE TITLE
SPIKE: Identify areas in source code to handle switching between different views. 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2438]
- [ ] Identify in source code all dependencies and values to which they need to be set in order to open/re-open any tabs potentially opened by the user after the screen has loaded.

**Comment by dionolympiaCVP** [comment]
When returning back to the monitoring plans section (after switching from any page)
The "mapStateToProps" is not being triggered to load the data for these variables:

- tabs
- activeTab

![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/531eba17-4da7-409e-9c01-c91d84972d3d)

Therefore, when these variables are referenced in the MonitoringPlanTab component, it throws a null reference exception:

![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/dd35e0fa-f606-40f6-94e9-3259529ba650)

---------------------------

**If we choose to keep track of these tabs and restore them as the user switches between pages/views:**

- We need to keep track of that data in the redux store and load it back in correctly as different pages are loaded
- Also, we will need to CLEAR the redux store of this data immediately when a user logs out. Leaving this data available in a logged out state presents a security vulnerability
- (_HIGHER_ risk and effort)

 
**If we choose to clear the tabs when a different page/section of the site is loaded:**

- we won't have that security risk
- we won't have to implement the redux logic to keep track of tabs and different views
- (_LOWER_ risk and effort)
