### ISSUE TITLE
Update UI and API to return stateCode 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2439]
Datateers are changing the Master Data Dictionary to return stateCode as opposed to the state. Any areas in the UI or any API calls need to be updated to reflect this. 

Development Notes
- The scope of the ticket includes updating the UI to use state code and completing regression testing 

Pages to be Updated 
- 

-

**Comment by dionolympiaCVP** [comment]
branch & PR for the aforementioned ECMPS UI update are created and ready to be merged after facilities API changes are merged (coordinate with Datateers)

**Comment by mosesdeeCVP** [comment]
![2439 Update UI and API to return stateCode.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b2201981-3c91-476d-b2f6-8190a09a8ab0)

**Comment by mosesdeeCVP** [comment]
States are visible on the UI

**Comment by dionolympiaCVP** [comment]
Peer review complete
