### ISSUE TITLE
Refactor error Message Links 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2447]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a User
I want to have the correct error message links appear when calling an API
So that I can understand the root of the error 

## Acceptance Criteria
Given a User makes an incorrect API call
When the API returns a response 
Then the correct link displays 

Given that a user has made a GET request to an API endpoint 
When an invalid value is entered for  state code 
Then the system displays the appropriate error message :  One or more state codes are not valid. Use the two letter postal abbreviation (use TX, not Texas). 

### Development Notes

- update the error messages for facility id and state code 
- Links to be corrected across API Error Message Responses 
- Make sure its using the API Gateway. 
- Update Facilities to Facilities MGmt 

Error Messages: 

State: One or more state codes are not valid. Use the two letter postal abbreviation (use TX, not Texas). 

The following API endpoint error messages need to be updated: 
Emissions: 
hourly
daily 
monthly
quarterly
facility/ unit attributes 
ozone season 
annual  

Account: 
allowance holdings 
allowance transactions 
account info 

Compliance: 
allowance based 
emission based 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC559](https://epacamd.testquality.com/project/11428/plan/20171/test/325975) 
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
@tlageman-epa TC599 failed. Logged Bug: Refactor error Message Links #2651 to track the changes. The bug is currently in development
