### ISSUE TITLE
Enhance Spinners on CAMPD to be 508 compliant 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2448]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the spinner to display when action is processing So that I know the system is loading  

## Acceptance Criteria

Given that an action is processing 
When the spinner is displayed 
Then the user has the option to stop the spinning motion 

Given that the spinner is displayed 
When the user stops the spinning motion 
Then the spinner is replaced with a static image 

Given an action is processing
When the action completes
Then the spinner/ static image disappears

### Development Notes

-As soon as the spinner is displayed, the user will have the option to stop the spinning motion. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

I've noticed slow performance, and often times the spinner doesn't show up for example after hitting "apply" on a filter or clearing a previously applied filter even if it takes longer than 5 sec. Can you confirm when the progress/working spinner is set to display?

[EASEY DESIGN SYSTEM ](https://www.figma.com/file/jLPVDOcuSlfeo85nD6ZJwv/EASEY-Design-System?node-id=318%3A82)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/34ae537b-045b-490c-921e-903969f11a5b)

## Testing
Test Case: [TC527 ](https://epacamd.testquality.com/project/11428/plan/21067/test/321344)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
@JanellC removed dependency. When #2524 is complete the spinners will be updated in the design system and can be used by Datateers.

**Comment by JanellC** [comment]
TC527 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
