### ISSUE TITLE
Spike: Allowance Transactions/ Compliance allowance based Data Preview Inconsistencies 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2449]
## Research 
 
1. Research the allowance transactions owner/ operator filter not showing all of the available owner/ operators  

2. Research the compliance allowance based owner/ operator filter disabling when there is data associated with the filter 

3. If the issue is not related to the database, then the scope of this ticket includes researching the issue with the filter logic on the UI 

## Context 
Steps to Reproduce for allowance transactions: 
1. Navigate to CDD
2. Select Allowance Transactions 
3. Enter Transaction Date: 01/01/2020- 01/02/2020
4. Select Data Preview 
5. Open the owner/ operator filter 

The owner/ operator filter is not displaying all of the owner/ operators values that are in the data preview 

Steps to reproduce for compliance allowance based: 
1. Navigate to CDD
2. Select compliance allowance based 
3. Select a program 
4. Select Preview data 

After a user applies a program the owner/ operator filter is disabled. But when the data table is displayed the data table contains values for owner/ operator. 

1. Navigate to the CDD
2. Select compliance allowance based 
3. Select a year (years 2008 and later) 
4. Select Preview data 

After a user applies a year from 2008- later the owner/ operator filter is disabled. But when the data table is displayed the data table contains values for owner/ operator.

**Comment by sdhawan16** [comment]
Documenting findings/next steps: 
[SPIKE 2449 Data Preview Inconsistencies - EPA CAMPD - v1.0.docx](https://github.com/US-EPA-CAMD/easey-ui/files/7847842/SPIKE.2449.Data.Preview.Inconsistencies.-.EPA.CAMPD.-.v1.0.docx)
