### ISSUE TITLE
 Fix styling issues on the timeout warning window

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2452]
**Fix styling issues on the timeout warning window**
- Also, align the words to the center below the countdown
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0f8fed49-e19c-40ed-a1ae-f7adb440bd57)

**Comment by mosesdeeCVP** [comment]
![2452 Fix styling issues on the timeout warning window.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e88921f-3279-494e-aed3-4ad78d2104a4)

**Comment by mosesdeeCVP** [comment]
Bug fixed
