### ISSUE TITLE
Fix styling issues in ECMPS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2453]
1. Fix the styling issue with the grey line that shows up on Edit/View/Create modals
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/46b10e95-0f79-49d2-818e-78648594e3ad)
2. The Pencil Icon needs to be realigned for proper placement
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9497e2b0-3b41-461e-be3a-5ef5b328c81f)
3. Fix styling for a monitoring plan tab of a checked out facility/configuration
    A. Locked icon is cut off on the left side
    B. Configuration name is place too close to the bottom (would look better with some padding)
    C. Facility name is cut off on the right side
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/665b953e-dc7c-4fa8-8b22-7f868e67687b)

**Comment by mosesdeeCVP** [comment]
Original Ticket:
[Fix styling issues in ECMPS #2401](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2401)

**Comment by mosesdeeCVP** [comment]
![2453 Fix styling issues in ECMPS - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/62b18366-fe3b-4a02-a1ff-c5a14931b0bc)

**Comment by mosesdeeCVP** [comment]
![2453 Fix styling issues in ECMPS - 2 and 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1c1c1fca-3771-4c2d-97ae-f82689c4b445)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
