### ISSUE TITLE
Bug: MP Evaluation Report

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2455]
- Facility ID (ORISPL) is displayed twice in the MP Evaluation Report. Remove the duplicate in the third line

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a05d080c-9d67-43ca-8409-1e9b77a0ec24)

- Facility ID (ORISPL) should be populating the ORIS Code from the backend. It currently displays the fac_ID

**Comment by mosesdeeCVP** [comment]
Bug fixed
![2455 Bug- MP Evaluation Report.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/359cf661-8e3d-40a7-b6a4-b942dc5f4f90)
