### ISSUE TITLE
Identify Wireframes for PI 2

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#246]
- [ ] Meet with UI person and discuss what UI wireframes will likely be needed for PI 2. Determine plan for wireframes.

**Comment by JorjaComer** [comment]
@MoAdeyoju  and @cvp-alexrobinson will further define the work needed to accomplish the goals of this ticket. Will update description as needed.

**Comment by cvp-alexrobinson** [comment]
**Wireframes:**

1. AMPD Prepackaged Data - Criteria Selection Splash Screen
2. AMPD Prepackaged Data - Download Manager (the shopping cart experience)
3. AMPD Data - PI-3 future concept for a single "Data" page that has Prepackaged Data offerings for quick downloads or novice users, as well as the ability to customize data packages for power users (Query).

**Comment by cvp-alexrobinson** [comment]
@karenhwwoo and @chrisgitsit -- Below is a list of the wireframes I'm proposing that I produce for PI 2. Primarily focused on Monitoring Plan Data. I'll lay out the navigation and general layout, then move onto the facilities listing, and finally three unique tab styles under a facility.

**Wireframes to be produced:**

1. EASEY-In Global (Navigation, sub-navigation, overall layout)
2. MPD - Facilities List
3. MPD - Facility - Methods
4. MPD - Facility - Unit Characteristics
5. MPD - Facility - No Data

- [x] Karen Approves
- [ ] Chris Approves

**Comment by karenhwwoo** [comment]
@cvp-alexrobinson, I'm not sure what you mean by MPD - Facility - No Data. Can you please clarify?

**Comment by cvp-alexrobinson** [comment]
@karenhwwoo -- Here's a tab with no data:

![image.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/10dc034a-dd81-42ff-921e-99337663ca2e)

We need a way to present those content areas in a way that informs the user that they're empty, and still allow users to easily add data to those areas. That's why I included it in the proposed wireframes.

**Comment by karenhwwoo** [comment]
@cvp-alexrobinson Ah, now I understand, thanks!

**Comment by JorjaComer** [comment]
This work was deprioritized based on feedback from EPA. Wireframe and UI design will be handled via tickets attached to each Uber Epics being worked in future PIs.
