### ISSUE TITLE
Identify Wireframes for PI 2 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#247]
Meet with UI team to identify what wire frames re needed for PI and determine plan for wire frame completion

**Comment by cvp-alexrobinson** [comment]
**Wireframes:**

1. AMPD Prepackaged Data - Criteria Selection Splash Screen
2. AMPD Prepackaged Data - Download Manager (the shopping cart experience)
3. AMPD Data - PI-3 future concept for a single "Data" page that has Prepackaged Data offerings for quick downloads or novice users, as well as the ability to customize data packages for power users (Query).

**Comment by JorjaComer** [comment]
This work was deprioritized based on feedback from EPA. Wireframe and UI design will be handled via tickets attached to each Uber Epics being worked in future PIs.
