### ISSUE TITLE
Load Filter Criteria for Component Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2472]
Create views that load the data for each dropdown in the module

- [x] Component Type Code

- [x] Sample Acquisition Method 

- [x] Basis Code

**Comment by sanleyCVP** [comment]
I need clarification on how to proceed on linking Component codes to Sample Aquisition Method Codes, as the reporting instructions do not clearly identify the relationship between the codes

**Comment by sanleyCVP** [comment]
We will keep any relationships that currently exist in the DB, and add relationships for the following: 
1. HG
2. BGFF, BOFF, GFFM, OFFM

**Comment by sanleyCVP** [comment]
View can be validated running select * from camdecmpsmd.vw_systemcomponent_master_data_relationships
