### ISSUE TITLE
Design for Aggregation 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2479]
## Context 
 

**Need requirements** 
- Add Aggregation to the custom data download 
- per PI 7 planning aggregation should not be an additional filter option. Should be an option a user can select after they preview their data similar to the download option - will need more discussion 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/881d92e9-f676-4b5e-bfd3-f732dcee3c08)

**Comment by NadiaJL** [comment]
@JanellC, @AllisonFrancis, @tlageman-epa 
Here is the shared Xd document link for Data Subtype Select/Change Data Type-Emissions-Aggregation WFs with the Aggregations filter included on the Data Subtype Select panel.
https://xd.adobe.com/view/523c938e-a55c-4475-8eae-72d4b842cd0e-076f/

**Comment by NadiaJL** [comment]
@JanellC, @AllisonFrancis, @tlageman-epa 
Here is the shared Xd document link for Data Subtype Select/Change Data Type-Emissions-Aggregation WFs with the Aggregations filter included on the Data Subtype Select panel, including the Aggregation dropdown menu, and updated Data type view.

https://xd.adobe.com/view/8f802127-14e0-46b4-9f28-b5a2749c527d-dad3/

**Comment by NadiaJL** [comment]
Alternative UI flow for Aggregation:
Data Subtype Select/Change Data Type-Emissions-Aggregation- Aggregation filter on data preview - desktop 1024

https://xd.adobe.com/view/e348361e-d0b1-4f74-ab20-5d77e3dfc340-b61b/

This option is also designed with screen breaks done as an FYI.
