### ISSUE TITLE
Design for Bulk Data Files 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2480]
## Context

**Need requirements** 
Design bulk data files section on CAMPD 

Low fidelity design on the invision board  : https://projects.invisionapp.com/freehand/document/EbuStHRwK

**Comment by NadiaJL** [comment]
@Janell Coleman & @allisonfrancis @tlageman-epa 
Here are the updated CAMPD Bulk Data WFs with the edits as discussed yesterday, 2/23/22

Figma CAMPD Bulk Data doc/dev inspect:
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=2906%3A5283

Figma CAMPD Bulk Data Prototype / mock-up
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=2906%3A5283&node-id=2956%3A7848&viewport=294%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=2956%3A7848

**Comment by NadiaJL** [comment]
Hi @Janell Coleman & @allisonfrancis & @tlageman-epa, here is the updated CAMPD Bulk Data files WFs, with Moblie & Tablet screen breaks.

Mobile:
Figma file/dev inspect:
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3101%3A25990

Figma interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=29[…]-zoom&starting-point-node-id=3101%3A25990&show-proto-sidebar=1

Tablet:
Figma file/dev inspect:
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=2906%3A5283

Figma interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=29[…]n-zoom&starting-point-node-id=3040%3A8096&show-proto-sidebar=1
