### ISSUE TITLE
Update CAMPD Header 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2485]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the header to display "Maps & Graphs" and " "APIs"" So that I can navigate the site 

## Acceptance Criteria

Given that a user has accessed CAMPD 
When the CAMPD main menu functionality is displayed 
Then the system displays the following items: Home, Data, Maps & Graphs

Given that a user has selected Maps & Graphs
When the drop down is displayed 
Then then system displays: Coming Soon 

Given that a user has selected Data on the CAMPD menu 
When the drop down is displayed 
Then the system displays the following items: Data Home, Custom Data Download, Bulk Data Files,  APIs

Given that a user has selected Data on the CAMPD menu 
When APIs is selected 
Then the user is directed to the following url: https://www.epa.gov/airmarkets/cam-api-portal

Given that a user has navigated to the Data Home Page
When the functionality is displayed
Then the page content is consistent with the [Data Home Page content document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B1680B428-F051-43F5-91B6-6707EC2363F6%7D&file=1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

Given that a user has navigated to the Data Home Page
When Learn more about CAMPD APIs is selected
Then the user is directed to the following URL: https://www.epa.gov/airmarkets/cam-api-portal

Given that a user has accessed the CAMPD home page, Data Home page, or CAMPD About Page
When the meta tag content is displayed (meta description, keywords)
Then the meta content is consistent with the content document (see context)

### Development Notes

1. The CAMPD Main menu items will be: Home, Data, Maps & Graphs
2. The child items for Data will be: Data Home, Custom Data Download, Bulk Data Files, APIs 
3. Utility Nav items will remain the same. Resources, help/support, regulatory partners 
4. Update the cam api section on the data home page to reflect changes in the data home page content document 
5. Update Meta Tag information on the CAMPD home page, Data Home page, or CAMPD About Page. Meta tag information should be consistent with the content documents. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Data Home Page content document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B1680B428-F051-43F5-91B6-6707EC2363F6%7D&file=1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

[CAMPD Home Page Content Document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BD507FF3D-D28C-4C98-9A67-F32C2F79C568%7D&file=CAMPD%20Home%20Page%20Content-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

[CAMPD About Page Content Document 
](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBEF116D3-0228-4EDE-B0D0-21C64213462E%7D&file=About%20CAMPD%20Content-%20EPA%20CAMD-v1.01.docx&action=default&mobileredirect=true)

## Testing
Test Case: [TC540](https://epacamd.testquality.com/project/11428/plan/21067/test/323258) 
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Dependency: 
1. Need confirmation from the EPA that CAM API will be changed to CAMPD apis. 
2. Need link to CAM API portal

**Comment by tlageman-epa** [comment]
@JanellC We discussed and here are the final edits to the a/c for this ticket.

1.  The header menu should be changed from "CAM API" to "APIs"
2.  The "CAM API" box title on the Data Home page should be changed to "APIs"
3.  The "Learn more about CAM API" button should change to "Learn more about CAMPD APIs"

Let me know if you have any questions.

**Comment by JanellC** [comment]
@tlageman-epa I have a couple of follow up questions. See below. 
1. Is the link available for us to direct a user out to the API portal? 
2. Does the team need to update any meta content that mentions CAM API? If so, should any mention of CAM API in the meta content be replaced with “APIs” or “CAMPD APIs”?

**Comment by tlageman-epa** [comment]
@JanellC 

1. @maheese should have the link to the CAM API portal
2. Yes, let's go ahead and update the meta content as you suggested.

**Comment by JanellC** [comment]
@tlageman-epa I updated the meta content for the CAMPD home page, Data Home page, and CAMPD About Page in the content documents. Let me know if you have any questions. Also, I will be on the look out for the link to the CAM API portal. Thanks

**Comment by JanellC** [comment]
TC540 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/afd0f293-d394-4446-88c1-09d6dd444b81)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/77830588-1a65-430b-a927-928e49955d5d)
