### ISSUE TITLE
Update CCD Helper Text 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2487]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want to access the quick start guide from the custom data download So that I can reference additional directions as needed  

## Acceptance Criteria
Given that a user has navigated to the custom data download 
When the helper text is displayed 
Then the helper text is consistent with the [Custom Data Download content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B07D28E24-6C3D-432B-B397-9DD1CD50A030%7D&file=2-%20Custom%20Data%20Download%20Content-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

Given that a user has navigated to the custom data download 
When the  Quick Start Guide link is selected 
Then the system opens a pdf file of the quick start guide in a new tab

### Development Notes
The scope of the ticket **does not** include giving the EPA the ability to update the helper text via the EASEY content repo 

Add two new lines of text to the helper text 
1. "For more help, view the Quick Start Guide (hyperlink to quick start guide)"
2. "Queries are limited to <number of records> records or about <time period> of hourly emissions data with no additional filters. For larger downloads, visit Bulk Data Files (hyperlink) ".  **- The text for this should be bolded** 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Custom Data Download content document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B07D28E24-6C3D-432B-B397-9DD1CD50A030%7D&file=2-%20Custom%20Data%20Download%20Content-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

Get Started Text in CDDT: 

We want to add one last bullet that says "For more help, view the Quick Start Guide (hyperlink to quick start guide)" 

[Quick Start Guide ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/3-Business%20Analysis/Artifacts/CustomDataDownload-QuickStartGuide.pdf)

## Testing
Test Case: [TC543](https://epacamd.testquality.com/project/11428/plan/23473/test/323293)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@JanellC based on the research Jason is doing re: download limits, we will want to include an additional bullet to preempt the download limit solution. Before work on this is completed let's make sure we touch base on that. thx

**Comment by JanellC** [comment]
TC543 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta
