### ISSUE TITLE
Create MDM Endpoints - Default Relationship Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2490]
Create MDM Endpoint for: /master-data-mgmt/relationships/defaults

Data will come from the view
camdecmpswks.vw_defaults_master_data_relationships

This effort is only for GET API endpoints

The api must return the following JSON object:

[
  {
    "parameterCode": string,
    "operatingConditionCode": string,
    "defaultUnitsOfMeasureCode": string,
    "defaultPurposeCode": string,
    "fuelCode": string,
    "defaultSourceCode": string
  }
]

**Comment by mosesdeeCVP** [comment]
![2490 Create MDM Endpoints - Default Relationship Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e52d3fc7-3590-463a-8148-cae960744730)

**Comment by mosesdeeCVP** [comment]
Test Case [TC545](https://epacamd.testquality.com/project/11428/plan/21902/test/324176)
Test Passed
