### ISSUE TITLE
Create MDM Endpoints - Formula Relationships Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2491]
Create MDM Endpoint for: /master-data-mgmt/relationships/formulas

Data will come from the view:
camdecmpswks.vw_formula_master_data_relationships

The api must return the following JSON object:

[
{
"parameterCode": string,
"formulaCode": string,
}
]

**Comment by mosesdeeCVP** [comment]
![2491 Create MDM Endpoints - Formula Relationships Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f8f8e78c-d2f5-4285-88f7-8c9b9358ede8)

**Comment by mosesdeeCVP** [comment]
Test Case [TC546](https://epacamd.testquality.com/project/11428/plan/20423/test/324177)
Test Passed
