### ISSUE TITLE
Create MDM Endpoints - Method Relationship Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2492]
Create MDM Endpoint for: /master-data-mgmt/relationships/methods

Dat will come from the view
camdecmpswks.vw_methods_master_data_relationships

The api must return the following JSON object:

[
  {
    "parameterCode": string,
    "monitoringMethodCode": string,
    "substituteDataCode": string,
    "bypassApproachCode": string,
  }
]

**Comment by mosesdeeCVP** [comment]
![2492 Create MDM Endpoints - Method Relationship Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e843334-f65a-4f5c-9306-488864f92fb5)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC549](https://epacamd.testquality.com/project/11428/plan/19352/test/324206)
Test Passed
