### ISSUE TITLE
Create MDM Endpoints - Span Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2493]
Create MDM Endpoint for: /master-data-mgmt/relationships/spans

Data will come from the view
camdecmpswks.vw_span_master_data_relationships

The api must return the following JSON object:

[
  {
    "componentTypeCode": string,
    "spanScaleCode": string,
    "spanMethodCode": string,
    "spanUnitsOfMeasureCode": string,
  }
]

**Comment by mosesdeeCVP** [comment]
![2493 Create MDM Endpoints - Span Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f164c040-bed2-4481-9dc5-1128f0c9c298)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC547](https://epacamd.testquality.com/project/11428/plan/20424/test/324178)
Test Passed
