### ISSUE TITLE
Create MDM Endpoints - MATS Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2494]
Create MDM Endpoint for: /master-data-mgmt/relationships/mats-methods

Data will come from the view
camdecmpswks.vw_matsmethods_master_data_relationships

The api must return the following JSON object:

[
{
   "supplementalMATSParameterCode": string,,
    "supplementalMATSMonitoringMethodCode":  string,
}
]

**Comment by mosesdeeCVP** [comment]
Test Case: [TC548](https://epacamd.testquality.com/project/11428/plan/19352/test/324187)
Test Passed

**Comment by mosesdeeCVP** [comment]
![2494 Create MDM Endpoints - MATS Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ce2efdb3-9702-4223-a4f4-ecd3640e4269)
