### ISSUE TITLE
Update Contact Us Success / Error Messages 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2497]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user  I want the contact us form to provide clear success/ error messages so that I am aware about the status of my submission 

## Acceptance Criteria

Given that a user has completely filled out the CAMPD Contact Us form 
When submit is selected 
Then the system displays the following message if the form was submitted successfully:  
Success! You will be sent a confirmation email within the next 24 hours. If you do not receive a notification, please resubmit your issue, reach out to the Clean Air Markets Division hotline at 202-343-9620, or email campd-support@camdsupport.com directly.

Given that a user has not filled out all the fields on the CAMPD contact us form 
When submit is selected 
Then the system displays the following message:  
All fields are required. Please fill in the form completely and try again. 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Yesterday 11:26 AM] Lageman, Travis
    

Vishnu Navuluri (Guest) janell coleman (Guest) Ibarra, Michelle I talked with Worley, Christopher and he is onboard to update these messages. I've attached draft messages for CAMPD. You will want to chat with chris about what the exact language will be on the ECMPS side. janell coleman (Guest) this is one last item that needs to be added to the backlog for 7.2. Happy to chat if there are any questions: 

Success Message: Success! You will be sent a confirmation email within the next 24 hours. If you do not receive a notification, please resubmit your issue or reach out to the Clean Air Markets Division hotline at 202-343-9620.

Failure Message: Error! (or whatever it may default to) An error is preventing submittal of your form. If you continue to have this error, please email campd-support@camdsupport.com directly. 

Incomplete Form Message: (This is already implemented, but wanted to include for completeness) 

(2 liked)Edited<https://teams.microsoft.com/l/message/19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype/1642091203163?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&amp;groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&amp;parentMessageId=1641852463906&amp;teamName=CAMD CVP Team&amp;channelName=General&amp;createdTime=1642091203163>

## Testing
Test Case:[ TC537](https://epacamd.testquality.com/project/11428/plan/21067/test/323192)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@junie-cvp just noticed that we should word this better. here is the updated message: Success! You will be sent a confirmation email within the next 24 hours. If you do not receive a notification, please resubmit your issue, reach out to the Clean Air Markets Division hotline at 202-343-9620, or email campd-support@camdsupport.com directly.

**Comment by JanellC** [comment]
TC537 passed @tlageman-epa . This ticket is ready for 508 testing @aprematta 
 ![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/07ee02a9-ae56-42b1-8adf-9fd6c3975158)
