### ISSUE TITLE
BUG: Endpoints not querying up until 2022 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2501]
### Actual Results

All emissions sub types and facility/ unit attributes should query up until the latest reporting quarter. Fix the UI validation so that the CDD query's up until the latest reporting quarter and update the error messages 

1.Fix the validation on the font end to query up until the latest reporting quarter for annual, ozone, and facility/unit attributes 

2. Update error messages for an out of range date on the front end for all emission sub types and facility/unit attributes   

3. Update error messages on the back end for  all emission sub types and facility/unit attributes   

4. Remove the  '  from the error messages. This is happening on the backend for hourly and daily emissions 

This issue is applicable to the following data types
- all emissions sub types (including the emissions filter logic endpoint) 
- facility/ unit attributes 
 
## Updated UI  Error Messages 

**UI error Messages for an out of range date:** 

1. Hourly Emissions: 
Enter dates between < insert valid range >  and the quarter ending on < insert valid range > 

2. Daily Emissions: 
Enter dates between < insert valid range >  and the quarter ending on < insert valid range > 

3. Monthly Emissions: 
Enter month(s) and year(s) between <  insert valid range > and the quarter ending on < insert valid range >

4. Quarterly Emissions: 
Enter quarter(s) and year(s) between <  insert valid range > and the quarter ending on <  insert valid range >

5. Ozone Season: 
Enter year(s) between 1995 and the quarter ending on <  insert valid range >

6. Annual Emissions: 
Enter year(s) 1980, 1985, 1990, or a year between 1995 and the quarter ending on <  insert valid range >

7. Facility/ Unit Attributes: 
Enter year(s) 1980, 1985, 1990, or a year between 1995 and the quarter ending on <  insert valid range >

## Updated API error messages
 **API error Messages for an out of range date**

1. Hourly Emissions 
Update the beginDate to a date between  <  insert valid range > and the quarter ending on <  insert valid range >
Update the endDate to a date between <  insert valid range > and the quarter ending on <  insert valid range >

2. Daily Emissions 
Update the beginDate to a date between  <  insert valid range > and the quarter ending on <  insert valid range >
Update the endDate to a date between <  insert valid range > and the quarter ending on <  insert valid range >

3. Monthly 
Update one or more years to a year between <  insert valid range > and the quarter ending on <  insert valid range >
Update one or more months to a month between  <  insert valid range > and the quarter ending on <  insert valid range >

4. Quarterly 
Update one or more years to a year between <  insert valid range > and the quarter ending on <  insert valid range >
Update one or more quarters to a quarter between  <  insert valid range > and the quarter ending on <  insert valid range  > 

5. Annual
 "Update one or more years to 1980, 1985, 1990, or to a year between 1995  and the quarter ending on <  insert valid range  > 

6. Ozone 
 Update one or more years to a year between 1995 and the quarter ending on <  insert valid range  > 

7. Facility/ Unit Attributes 
"Update one or more years to 1980, 1985, 1990, or to a year between 1995  and the quarter ending on <  insert valid range  >

**Comment by JanellC** [comment]
@tlageman-epa Based on the discussion during dsu on 1/20, I updated the error messages for an out of range date
for all emissions sub types and facility/unit attributes . Let us know if you have any comments/ concerns.

**Comment by tlageman-epa** [comment]
@JanellC  @sdhawan16 I think this looks fine but I think we'd run into an issue with ozone data? I'm assuming the < 
 insert valid range  > is the last reported quarter?  Ozone data is only between May 1st and Sept 30th. For example, once data is reported for the 1st quarter of this year, 2022 (Jan - Mar), the error message would say that you could enter in the year 2022, even though no data would exist yet. This is not an issue for annual data because it's value is updated with each reported quarter.

**Comment by JanellC** [comment]
@tlageman-epa For the ozone data error messages, the < insert valid range > is for the latest reporting quarter date. Right now, the way that the validation is working for the ozone API endpoint is that it queries up until the latest reporting quarter. Based on the information you provided, we would need to update the validation for the ozone API endpoint and the ozone data type on the cdd. 

We can proceed with updating the validation for ozone, but it would increase the estimate of this ticket and we would need some more clarification surrounding the requirements for ozone validation.  

For example, we are unclear when a user should be able to start querying for ozone data in the current year. Should the system provide an error message for the current year until May 1st?  or would the validation function similarly to the latest reporting quarter where the data wouldn’t be made available until after September 30th?

**Comment by tlageman-epa** [comment]
@JanellC Let's leave it as you have laid out above for now. We can address this specificity later. If a user has a question, we can field it thru the contact us form, but they should be able to understand that ozone season data for a given year won't be available until after ozone season data is reported.

**Comment by JanellC** [comment]
**API Calls:** 

Hourly Emissions 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/hourly?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&beginDate=2022-01-01&endDate=2022-01-01

Daily Emissions: 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/daily?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&beginDate=2022-01-01&endDate=2022-01-01

Monthly: 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/monthly?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&year=2022&month=01

Quarter: 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/quarterly?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&year=2022&quarter=01

Annual: 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/annual?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&year=2022

Ozone: 
https://api.epa.gov/easey/dev/emissions-mgmt/apportioned/ozone?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&year=2022

Facility/ unit attributes 
https://api.epa.gov/easey/dev/facilities-mgmt/facilities/attributes?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&page=1&perPage=1&year=2022


Emissions filter logic endpoint: 
https://api.epa.gov/easey/dev/facilities-mgmt/facilities/attributes/applicable?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&year=2022


**UI Error Messages:** 

Hourly Emissions: 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/73e3ebec-b668-40e1-aa87-aa292e93b08f)



Daily Emissions 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1b3d8ae2-f78d-4848-b320-61d41621c2a1)

Monthly Emissions 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/5e1b2f69-a461-492b-bd9d-80f5db2bdcbf)

Quarterly 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6c2639f5-d876-4ec9-8b2d-0535c31fbcce)

Ozone 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/085e3d71-feca-4577-a90f-cbcb68641f23)

Annual 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/afc20bb6-d743-4595-9be6-32720f36ddac)

Facility/ unit attributes 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e8891b51-7780-4124-99d2-97ec2e125223)

**Comment by JanellC** [comment]
Open defect in TestQuality [D105](https://web.testquality.com/site/epacamd/project/11428?defectId=9845)
- Test [Validation for Monthly Emissions API](https://web.testquality.com/site/epacamd/project/11428/runs/146637?resultId=2349644) in Run [Validation for Monthly Emissions API](https://web.testquality.com/site/epacamd/project/11428/runs/146637) (linked to Cycle [Monthly Emissions API/ UI](https://web.testquality.com/site/epacamd/project/11428/cycles/20143)).

**Comment by JanellC** [comment]
Defect D105 resolved @tlageman-epa
