### ISSUE TITLE
Limit file download by # records on the cdd

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2510]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the system to limit how many records that I can download on the tool So that I can successfully complete a download 

## Acceptance Criteria

Given that the data table is displayed 
When the total number of records returned is more than the configured limit 
Then the system displays a alert with the following message:  Your query exceeds the record limit of ####. Refine your query to further limit the number of records returned or visit the Bulk Data Files (hyperlink)
AND the download button is disabled (see context for wireframes) 

### Development Notes
- The scope of this ticket is for all data types 
- For testing purposes set the configured limit to 100,000
-hyper link to the bulk data files page on CAMPD. The bulk data files page should open in a new tab 
- This functionality will only be implemented for desktop sizes 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Wireframes: https://xd.adobe.com/view/5843045c-99a2-4c6e-b880-2f127f19796f-0d10/

## Testing
Test Case:[ TC542](https://epacamd.testquality.com/project/11428/plan/23473/test/323265)
Tester: @JanellC 

508 Testing: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@AllisonFrancis please share the wireframe designs when they are completed. thx!

**Comment by JanellC** [comment]
TC542 failed @tlageman-epa.  I logged Bug: Limit file download by # records on the cdd #2565 to track the changes

**Comment by JanellC** [comment]
Bug: Limit file download by # records on the cdd #2565  resolved @tlageman-epa . This ticket is ready for 508 testing @aprematta
