### ISSUE TITLE
Update EASEY spinners to be 508 compliant 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2518]
## User Story 

As the EPA I want a user to have the ability to stop the spinning motion on the spinner so that the spinner complies with 508 guidelines 

## Acceptance Criteria 
Given that an action is processing
When the spinner is displayed
Then the user has the option to stop the spinning motion

Given that the spinner is displayed
When the user stops the spinning motion
Then the spinner is replaced with a static image

Given an action is processing
When the action completes
Then the spinner/ static image disappears

## Development Notes 

- As soon as the spinner is displayed, the user will have the option to stop the spinning motion.
- Canceling an action is out of scope 
- Update the spinner and add it to the EASEY design system so that it can used on ECMPS and CAMPD
- The "Still Loading…” text should be perceivable to AT (assistive technology) 

## Context 

In order to comply with 508 guidelines, a user has to have the ability to stop, pause, or hide the motion of a spinner once its been displayed for longer than 5 seconds 

**508 Guideline:**  
See: https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-pause.html

[EASEY DESIGN SYSTEM ](https://www.figma.com/file/jLPVDOcuSlfeo85nD6ZJwv/EASEY-Design-System?node-id=318%3A82)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8565f0fe-3f78-452b-9e5e-3a919cb2f6a4)

**Comment by JorjaComer** [comment]
This ticket can be closed. When #2524 is complete the spinners will be updated in the design system and can be used by Datateers.
