### ISSUE TITLE
Increase Overall Unit Test Coverage - ECMPS UI - Data Tables

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2519]
Unit Test cases to address include:

src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.test.js (3.5% coverage)
src/components/datatablesContainer/DataTableConfigurations/DataTableAnalyzerRanges.test.js (4.9% coverage)
src/components/datatablesContainer/DataTableConfigurations/DataTableLMEQualifications.test.js (3.5% coverage)
src/components/datatablesContainer/DataTableConfigurations/DataTableQualifications.test.js (1.1% coverage)
src/components/datatablesContainer/DataTableConfigurations/DataTableFacilitiesData.test.js (61.5% coverage)

Note: Goal is to bring up the coverage of the individual components to 70%

- Track as part of #2550
src/components/datatablesContainer/DataTableConfigurations/DataTableLEEQualifications.test.js (3.6% coverage)

Ticket [2599](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2599) contains 4 additional tables that required coverage increase

**Comment by Qb10** [comment]
v![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/56f7f0b3-3440-4dad-80d9-c1469d20a222)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/597dbe59-98dd-4823-8c03-df81ea72e5a2)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/84932dba-8177-43ec-8598-62a87d48a4bd)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/7f29eab8-29e7-4505-9c47-e55b61b3090f)
