### ISSUE TITLE
Increase Overall Unit Test Coverage

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2520]
Unit Test cases to address include:

src/utils/selectors/monitoringPlanSystems.test.js
src/utils/api/easeyAuthApi.test.js
src/utils/api/monitoringPlansApi.test.js

**Comment by sanleyCVP** [comment]
src/utils/selectors/monitoringPlanSystems.test.js - 100%
src/utils/api/easeyAuthApi.test.js - 91.5%
src/utils/api/monitoringPlansApi.test.js - 100%

Approved for closing
