### ISSUE TITLE
MP Evaluation Report - Unit/Stack Information Missing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2521]
Information is missing/not populating under the 'Unit/Stack' column in the MP Evaluation Report

Example:
J H Campbell

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/cc96496f-8da3-45a9-9e47-42334f59a571)

**Comment by sanleyCVP** [comment]
Also Barry 5, MS5A, MS5B

https://easey-dev.app.cloud.gov/ecmps/workspace/monitoring-plans/MDC-725B0D3F956C4E0EB994536D286F9195/evaluation-report

**Comment by sanleyCVP** [comment]
Updated the View Definition, confirmed that for Barry 5, MS5A and MS5B all unit/stack details are displayed
![image.png](https://images.zenhubusercontent.com/6143891f8447a5585788734a/ad356908-968f-481f-93f2-b4fadc098444)

**Comment by mosesdeeCVP** [comment]
![2521 MP Evaluation Report - Unit-Stack Information Missing.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44e60b52-df73-4b4e-ab0f-46bb3ab2f043)

**Comment by mosesdeeCVP** [comment]
Bug fixed
