### ISSUE TITLE
Design for Limiting file download by # records on the cdd (Need by 1/24) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2522]
## Context 

The custom data download will limit how much data a user can download by assessing the number of records that is returned in a dataset. 

When the total number of records returned is more than the configured limit
Then the system displays a modal with the following message: Your query exceeds the record limit of ####. Refine your query to further limit the number of records returned or visit the Bulk Data Files (hyperlink)
AND the download button is disabled

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/34657359-369d-435a-87c9-3a7872d869e1)

## Design needs 
1. Will need design for the modal with the following message: Your query exceeds the record limit of ####. Refine your query to further limit the number of records returned or visit the Bulk Data Files (hyperlink)

2. Download button being disabled

**Comment by AllisonFrancis** [comment]
@tlageman-epa Here are the screens for Limiting the Data Download. https://xd.adobe.com/view/5843045c-99a2-4c6e-b880-2f127f19796f-0d10/
I used the "Alert component" that will appear letting the user know that they need to revise their filter selections before they are able to download. Let me know if you have questions.
