### ISSUE TITLE
ECMPS: Update EASEY spinners to be 508 compliant

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2524]
As an ECMPS user, I want the ability to stop the spinning motion on a spinner so that it complies with 508 guidelines 

## Acceptance Criteria 
Given that an action is in progress
When the spinner is displayed
Then the user has the option to stop the spinning motion

Given that the spinner is displayed
When the user stops the spinning motion
Then the spinner is replaced with a static image

Given an action is processing
When the action completes
Then the spinner/ static image disappears

Reference to the EASEY Design System for Spinners: https://zeroheight.com/37f47ceee/p/8562fc-spinner

**Comment by aprematta** [comment]
Need to find a way to have the spinner run for more than a couple seconds to properly evaluate. Having said that, on thing that needs to happen is the stop animation button needs to receive keyboard focus when it appears.

**Comment by aprematta** [comment]
Tested on CAMPD as it was easier to get the spinner to display longer and properly test..... no issues remain. Just make sure ECMPS is using the latest version of the spinners.
