### ISSUE TITLE
Provide EPA the ability to edit content on the Related Resources page 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2530]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As the EPA I want the ability to edit content on the Related Resources page so that the webpage is always up to date

## Acceptance Criteria
Given that a content manager has accessed the [EASEY Content Repo ](https://github.com/US-EPA-CAMD/easey-content)
When the functionality is displayed 
Then the content manager can edit static content on the Related Resources Page 

Given that a content manager has accessed the [EASEY Content Repo ](https://github.com/US-EPA-CAMD/easey-content)
When edits made to the Related Resources Page  are committed
Then the edits to the Related Resources Page  are displayed in the applicable environment  

### Development Notes

Scope includes the following: 
Update all of the content on the page
Update the text on the buttons
Provide new links
Update exit disclaimer to an image 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[Related Resources Content Document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BA90DEF68-CB16-4E0A-8D6E-33A43598DA4B%7D&file=Related%20Resources%20Content-%20EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true) 

## Testing
Test Case: [TC560 ](https://epacamd.testquality.com/project/11428/plan/23473/test/326025)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@JanellC  @addisgmichael Sorry, I thought I said yesterday in planning that this ticket was not a priority for me. I would prioritize any of the content update tickets in the sprint backlog pipeline over this as well as the #2533. I was not aware of 2533 and do not recall seeing that in the backlog yesterday, i thought that was already implemented and would definitely want that over related resources. Thx

**Comment by JanellC** [comment]
@tlageman-epa Thanks for letting me know. I removed this ticket from 7.3 and added #2533 to the sprint.

**Comment by JanellC** [comment]
TC560 passed @tlageman-epa
