### ISSUE TITLE
Mobile/ tablet break points CDD Filters/ Data Preview - 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2537]
## Context

Testing complete for 1465....... encountered the following 508 issues:

Activating data type button does not put focus on first focusable element on data type window

Activating Back or Cancel does not put focus back on data type button

Focus is not trapped in the Data Type window when active

Same Issues for the Filter button
The X option to clear the filter without having to open the filter window is not keyboard accessible

Not a 508 violation cause it affects all users, but if I get the following message 'Data Preview
No results match that search criteria. Please change the criteria and try again.' there is not a way to get back to the filters

**Comment by aprematta** [comment]
All above issues were addressed. Closing ticket, we will need to open 1 additional ticket to address the clear filter buttons
