### ISSUE TITLE
Unable to Create a Qualification Record

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2538]
Users unable to create a parent Qualification record. 

User clicks 'Create Qualificaion' record
On the create Qualification modal, add data for all the fields and Save
System throws the following error and Qualification record is not created

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d81016a9-5a7e-471f-9e6e-a33d58686f3a)

**Comment by mosesdeeCVP** [comment]
Test Passed
Test Case Run: [TCR6491
](https://epacamd.testquality.com/project/11428/plan/22483/run/154930/result/fullscreen/2647503)
