### ISSUE TITLE
Create MDM Endpoints - MP Load Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2542]
Create MDM Endpoint for: /master-data-mgmt/relationships/loads

Data will come from the view
camdecmpsmd.vw_load_master_data_relationships

The api must return the following JSON object:
[
  {
    "maximumLoadUnitsOfMeasureCode": string,
    "normalLevelCode": string,
    "secondLevelCode": string
  }
]

**Comment by mosesdeeCVP** [comment]
![2542 Create MDM Endpoints - MP Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b0f9c604-5059-419e-ad30-fb5dcb0abc8c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC568](https://epacamd.testquality.com/project/11428/plan/21921/test/326033)
Test Passed
