### ISSUE TITLE
Create MDM Endpoints - Unit Fuel Relationship Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2544]
Create MDM Endpoint for: /master-data-mgmt/relationships/unit-fuels

Data will come from the view
camdecmpsmd.vw_unitfuel_master_data_relationships

The api must return the following JSON object:
[
  {
    "fuelCode": string,
    "indicatorCode": string,
    "demGCV": string,
    "demSO2": string,
  }
]

**Comment by mosesdeeCVP** [comment]
![2544 Create MDM Endpoints - Unit Fuel Relationship Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e96bfa3c-be04-45b6-a40b-8ff7dc0ba774)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC579](https://epacamd.testquality.com/project/11428/plan/22363/test/326250)
Test Passed
