### ISSUE TITLE
Create MDM Endpoints - Unit Control Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2546]
Create MDM Endpoint for: /master-data-mgmt/relationships/unit-controls

Data will come from the view 
camdecmpsmd.vw_unitcontrol_master_data_relationships

The api must return the following JSON object:
[
  {
    "parameterCode": string,
    "controlCode": string,
  }
]

**Comment by mosesdeeCVP** [comment]
![2546 Create MDM Endpoints - Unit Control Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f1ca468b-afc6-4267-85aa-ad9c3d3a1b48)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC2546](https://epacamd.testquality.com/project/11428/plan/22363/test/326111)
Test Passed
