### ISSUE TITLE
Create MDM Endpoints - System Fuel Flow Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2548]
Create MDM Endpoint for: /master-data-mgmt/relationships/system-fuels

Data will come from the view
camdecmpsmd.vw_systemfuel_master_data_relationships

The api must return the following JSON object:

[
  {
    "systemFuelFlowUOMCode": string,
    "maximumFuelFlowRateSourceCode": string
  }
]

**Comment by mosesdeeCVP** [comment]
![2548 Create MDM Endpoints - System Fuel Flow Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a79d1367-333d-470b-ba45-a8ac6e1bca50)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC577](https://epacamd.testquality.com/project/11428/plan/20829/test/326155)
Test passed
