### ISSUE TITLE
Create MDM Endpoints - Qualification LEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2550]
Create MDM Endpoint for: /master-data-mgmt/relationships/lee-qualifications

Data will come from the view
camdecmpsmd.vw_quallee_master_data_relationships

The api must return the following JSON object:

[
  {
    "parameterCode": string,
    "qualificationTestType": string,
    "unitsOfStandard": string,
  }
]

**Comment by mosesdeeCVP** [comment]
![2550 Create MDM Endpoints - Qualification LEE Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ffcb15c3-87ae-4703-8bfd-c00c397e90e9)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC575](https://epacamd.testquality.com/project/11428/plan/22483/test/326104)
Test Passed
