### ISSUE TITLE
Create MDM Endpoints - System Component Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2552]
Create MDM Endpoint for: /master-data-mgmt/relationships/system-components

Data will come from the view
camdecmpsmd.vw_systemcomponent_master_data_relationships

The api must return the following JSON object:
[
  {
    "componentTypeCode": string,
    "sampleAcquisitionMethodCode": string,
    "basisCode": string,
  }
]

**Comment by mosesdeeCVP** [comment]
Test Case: [TC588](https://epacamd.testquality.com/project/11428/plan/19812/test/327644)

**Comment by mosesdeeCVP** [comment]
![2552 Create MDM Endpoints - System Component Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/86de1ce0-4fa9-467a-9ebd-d3a77801f6ee)

**Comment by mosesdeeCVP** [comment]
Test Passed
