### ISSUE TITLE
Remove Global View for a Logged in ECMPS User

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2554]
As an ECMPS user, I want to see and access only the workspace when I am logged in so the navigation between different screens and modules is straightforward

Acceptance Criteria:

Given I am an ECMPS user
When I log in to the application
Then I ONLY see the Workspace view

Reference Screenshot:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1c37f890-fd57-42fa-b5a7-370828fc630e)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC582](https://epacamd.testquality.com/project/11428/plan/19352/test/326676)

**Comment by mosesdeeCVP** [comment]
![2554 Remove Global View for a Logged in ECMPS User.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/375210f0-4d35-4ec7-9d26-60462a0781db)

**Comment by mosesdeeCVP** [comment]
Test Passed
