### ISSUE TITLE
SPIKE: Review the views, functions and procedures in the camdecmpswks schema

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2558]
- Some views belong in the camdecmpsmd schema and we would have to move those 
- Review functions and procedures that are out of sync in the GitHub Repo 

Requirements 
 

- [x] identify any views that may have to me moved and whether or not code needs to be updated 
- [x] identify all create scripts for functions, views and procedures, are properly reflected in github easey-db-scripts repository

**Comment by sanleyCVP** [comment]
Moving back to ready for development as I'll be out next week, and no progress will be made

**Comment by sanleyCVP** [comment]
**SCHEMA camdaux**
**Procedure**:  procedure_set_dm_emissions_user
- add CREATE SCRIPT in Github repo
**View**: vw_bulk_file_jobs_to_process 
- add CREATE SCRIPT in GitHub repo
**View**: vw_bulk_file_jobs_to_delete
- add CREATE SCRIPT in GitHub repo
**View**: vw_emissions_based_compliance_bulk_files_to_generate 
- calls only tables from camddmw suggest moving to camddmw schema 
- add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\EmissionsComplianceBulkDataFiles.cs
**View**: vw_allowance_transactions_bulk_files_to_generate 
- calls tables from camddmw suggest moving to camddmw schema
- add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\AllowanceTransactionsBulkDataFiles.cs
**View**: vw_allowance_based_compliance_bulk_files_to_generate 
- calls tables from camddmw suggest moving to camddmw schema
- add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\AllowanceComplianceBulkDataFiles.cs
**View**: vw_annual_facility_bulk_files_to_generate 
- calls tables from camd and camddmw suggest moving to camd or camddmw schema
- add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\FacilityAttributesBulkDataFiles .cs
**View**: vw_annual_emissions_bulk_files_per_state_to_generate 
- calls mostly tables from camdecmps suggest moving to camdecmps schema
- add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\ApportionedEmissionsBulkDataFiles.cs
**View**: vw_annual_emissions_bulk_files_per_quarter_to_generate 
- calls mostly tables from camdecmps suggest moving to camdecmps schema
-add CREATE SCRIPT in GitHub repo
- Code references: \easey-quartz-scheduler\admin\Jobs\BulkDataFiles\ApportionedEmissionsBulkDataFiles.cs

**Comment by sanleyCVP** [comment]
**SCHEMA camddmw**
**Procedure**: hour_unit_data_sync
- add CREATE SCRIPT in Github repo
**Procedure**: hour_unit_mats_data_sync
- add CREATE SCRIPT in Github repo
**View**: vw_quarter_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_ozone_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_month_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_hour_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_hour_unit_mats_data
- add CREATE SCRIPT in Github repo
**View**: vw_day_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_annual_unit_data
- add CREATE SCRIPT in Github repo
**View**: vw_emissions_submissions_received
- calls only tables from camdecmpsaux suggest moving to camdecmpsaux schema
- move CREATE SCRIPT in GitHub
- Code references: Not referenced in any API repository
**View**: vw_emissions_submissions_gdm
- calls mostly tables from camdecmps suggest moving to camdecmps schema
- move CREATE SCRIPT in GitHub
- Code references: Not referenced in any API repository
**View**: vw_emissions_submissions_expected
- calls tables from camdecmpsaux and camdecmpsmdsuggest moving to camdecmpsaux or camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references: Not referenced in any API repository

**Comment by sanleyCVP** [comment]
**SCHEMA camdecmpswks**
**Function**: check_session_init
-  add CREATE SCRIPT in Github repo
**Procedure**: check_session_completed
- remove script from GitHub repo
**Procedure**: check_session_failed
- remove script from GitHub repo
**Procedure**: check_session_init
- remove script from GitHub repo
**View**: vw_check_catalog_plugin
- calls tables from camdecmpsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references: \easey-quartz-scheduler\CheckEngine\CheckEngine\ResultCatalog.cs
**View**: vw_check_catalog_result
-  calls tables from camdecmpsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references: \easey-quartz-scheduler\CheckEngine\CheckEngine\ResultCatalog.cs
**View**: vw_cross_check_catalog_value
-  calls tables from camdecmpsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\Emissions\EmissionReport\EmissionsReportProcess.cs
\easey-quartz-scheduler\CheckEngine\LME\LMEGenerationProcess.cs
\easey-quartz-scheduler\CheckEngine\LME\LMEScreenProcess.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MonitorPlan.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MPScreenMain.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\OtherQAMain.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAMain.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAScreenMain.cs
**View**: vw_cross_check_parameter_cd_method_cd_sub_data_cd
- Remove from GitHub repo (Not used in DB)
**View**: vw_evem_emissions
-  calls tables from camdecmps suggest moving to camdecmps schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckEngine\GeneratedParameterClasses\DataRows.cs
\easey-quartz-scheduler\CheckEngine\Emissions\EmissionReport\EmissionsReportProcess.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MonitorPlan.cs
**View**: vw_program_parameter
-  calls tables from camdecmpsaux, camd, camdmd suggest moving to any other schema
- move CREATE SCRIPT in GitHub
- Code references: Not referenced in any API repository
**View**: vw_qa_supp_data
-  calls mostly tables from camdecmps, camdempsmd suggest moving to any other schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckEngine\GeneratedParameterClasses\DataRows.cs
\easey-quartz-scheduler\CheckEngine\Emissions\EmissionReport\EmissionsReportProcess.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MonitorPlan.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAMain.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAScreenMain.cs
**View**: vw_qa_test_summary
-  calls mostly tables from camdecmps, camdempsmd suggest moving to any other schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckEngine\GeneratedParameterClasses\DataRows.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MonitorPlan.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAMain.cs
\easey-quartz-scheduler\CheckEngine\QA\Processes\QAScreenMain.cs
**View**: vw_reporting_period
-  calls tables from camdempsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\LME\LMEGenerationProcess.cs
\easey-quartz-scheduler\CheckEngine\LME\LMEImportProcess.cs
\easey-quartz-scheduler\CheckEngine\LME\LMEScreenProcess.cs
**View**: vw_rule_check
-  calls tables from camdempsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameterBands.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameters__CheckEngine.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\ParameterizedCheck.cs
**View**: vw_rule_check_condition
-  calls tables from camdempsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameterBands.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameters__CheckEngine.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\ParameterizedCheck.cs
**View**: vw_rule_check_parameter
-  calls tables from camdempsmd suggest moving to camdecmpsmd schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameterBands.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\CheckParameters__CheckEngine.cs
\easey-quartz-scheduler\CheckEngine\CheckParameters\ParameterizedCheck.cs
**View**: vw_unit_program_exemption
- calls tables from camd and camdmd suggest moving to another schema
- move CREATE SCRIPT in GitHub
- Code references:
\easey-quartz-scheduler\CheckEngine\CheckEngine\GeneratedParameterClasses\DataRows.cs
\easey-quartz-scheduler\CheckEngine\MonitorPlan\Processes\MonitorPlan.cs
