### ISSUE TITLE
Spike: Research formatting subscripts in Markdown 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2560]
## Context 

On the CAMPD home page, the call out box contains subscripts. The team will need to research how to format the subscripts  in markdown so that the EPA will have the ability to edit the content in the call out box . This spike needs to be completed before the EPA will have ability to edit all the static content on the CAMPD home page

**Comment by AbuFofanah** [comment]
To write subscript in markdown, we can use the tag "<  sub ></  sub  >" around the characters that need to be in subscript. On the react side, we can use react-markdown v4.3.1 with the plugin remark-sub-super to render it properly.
