### ISSUE TITLE
MP Import (part 1) - Updating Configuration information

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2561]
**Monitor Plan & Monitor Locations** 

1. Obtain the fac_id with the ORISCode from file --> fac_id from camd.plant
2. Obtain all mon_plan_ids (camdecmpswks.monitor_plan) by fac_id from 1
3. For each location entry in the JSON file, obtain the associated mon_loc_id from the DB as follows
 3a. For Location.UnitID elements: fac_id from 1 --> unit_id from camd.unit --> mon_loc_id from camdecmpswks.monitor_location
  3b. For Location.StackPipeID elements: fac_id from 1 --> stack_pipe_id from camdecmpswks.stack_pipe --> mon_loc_id from camdecmpswks.monitor_location
**_The import process will trigger an error if there is not a monitor location associated to the facility for the given Stack/Unit_**
4. Obtain the mon_plan id for each mon_loc_id obtained in 3 from camdecmpswks.monitor_plan_location
5. All mon_plan_id from 4 must be the same and must match an active version of the mon_plan_ids identified in 2
**_Import process will trigger an error if there is a mismatch of mon_plan_ids in 5, or if the mon_plan_id being updated is inactive_**

**Monitor Plan Comment** - lookup mon_plan_comment_id by mon_plan_id, mon_plan_comment and begin_date. If no mon_plan_comment_id exists create a new record, else update [END_DATE], [USERID] when the end date has changed

Then update the following sections:
**_Stack_** 
Update the information of the stack if a match is found, if not trigger an error. Fields to update: [ACTIVE_DATE], [RETIRE_DATE], [USERID], [UPDATE_DATE] when active or retired date are different from DB

**_Unit Stack Configuration_**
- Update the configuration information if a match is found, if not trigger an error. Fields to update: [BEGIN_DATE], [END_DATE], [USERID], [UPDATE_DATE]  when begin or end date are different from DB

**_Unit_**
- Update the unit information when a location.unitId for the fac_id record is found. Fields to update: NON_LOAD_BASED_IND if different from the DB. Also update the Unit Capacity, Unit Control and Unit Fuel records by matching to the unit's DB Id

_unit capacity_ - lookup unit capacity record by unit_id and begin date (or end date if no match found for begin date). If no unit_cap_id found, insert new record, else update [BEGIN_DATE], [END_DATE], [MAX_HI_CAPACITY], [USERID], [UPDATE_DATE] where either begin date, end date, or max_hi_capacity values have changed

_unit control_ - lookup ctl_id by unit_id, ce_param, control_cd, install_date (or retired date if no match found for install date). If no ctl_id found insert new record, else update [ORIG_IND], [SEAS_IND], [OPT_DATE], [INSTALL_DATE=, [RETIRE_DATE], [USERID], [UPDATE_DATE] where of those values has changed

_unit fuel_ - Lookup uf_id by unit_id, fuel_cd, begin_date (or end date if no match found for begin date). If no uf_id found insert new record, else update DEM_GCV, DEM_SO2, BEGIN_DATE, END_DATE, INDICATOR_CD, OZONE_SEAS_IND, USERID, UPDATE_DATE where any of those values has changed

**Comment by SimeraHailu** [comment]
https://customervaluepartners-my.sharepoint.com/:u:/r/personal/conradsanley_cvpcorp_com/_layouts/15/Doc.aspx?sourcedoc=%7BA3E2B02B-7247-4810-B612-8A59EAEA4EC3%7D&file=MP%20Import%20Process.vsdx&wdOrigin=OFFICECOM-WEB.MAIN.REC&ct=1643815560219&action=default&mobileredirect=true&cid=8ea410ff-2a63-4418-b06b-ec43dedcc9c4
