### ISSUE TITLE
Increase Overall Unit Test Coverage - ECMPS UI - API Callers

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2570]
Unit Test cases to address include:

**API Callers**
src/utils/api/quartzApi.js  -  coverage at 20%
src/utils/api/facilityApi.js - coverage at  50.0%
src/utils/api/dataManagementApi.js - coverage at  52.4%
src/additional-functions/retrieve-dropdown-api.js -  coverage at 3.4%

**Comment by dionolympiaCVP** [comment]
Increased coverage for `retrieve-dropdown-api.js` to 98.6% and `dataManagementApi.js` to 95.7%, increasing branch coverage by 5.9%.

![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/95daf9d9-4141-45ef-8336-ecea24f88472)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/7742f525-8d55-4d2b-96a5-ed555ae7dd3d)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/6bae38d9-649c-4510-b17f-41bf4d740776)

**Comment by dionolympiaCVP** [comment]
Increased coverage for `quartzApi.js` to 92.3% and `facilityApi.js` to 100%, increasing branch coverage by 0.2%

![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/71db641d-33db-4768-97ab-9f2d9b027b48)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/4e72bf85-e398-4ef7-8841-090cce500ee0)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/ce04dc90-06d5-41aa-897c-c09be8b65306)
