### ISSUE TITLE
Increase Overall Unit Test Coverage - ECMPS UI - Supporting UI functions

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2571]
Unit Test cases to address include:

**Supporting UI Functions**
src/additional-functions/app-error.js -coverage at 29.4%
src/additional-functions/extract-user-input.js - coverage at 45.0%
src/additional-functions/dataTable-props.js - coverage at 50.0%
src/additional-functions/checkout.js - coverage at  55.0%
src/store/actions/monitoringPlans.js - coverage at 66.7%
src/store/reducers/dropdowns.js - coverage at 68.8%

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/0a8d3106-ebf7-4ba5-b4ca-311c84e683f8)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/0604b658-3b5b-4ce1-b99e-4ad5d4dfc125)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/6a3c63d5-1ec7-48d6-9ae7-fec9621b6957)
