### ISSUE TITLE
Export a Monitoring Plan - UI Design (2/7)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2581]
- We shall be using the same MP JSON Schema for export and import functionality
- Export a Monitoring Plan button shall be placed right next to the Import button on the left 
- Export is anticipated to be the less utilized functionality when compared to Import  
- Proposed Naming Convention for the File: Oris Code, Configuration Name - Date

**Comment by AllisonFrancis** [comment]
![image.png](https://images.zenhubusercontent.com/5f4e48d98a25459911b0c57e/d0828648-4f7f-4c78-9896-fa8df47511e5)

**Comment by AllisonFrancis** [comment]
@vishnunavuluri Above is the screen with the export and import buttons moved to below the tabs... to make it more clear to the user that these function only as related to the Monitoring Plan tab they are currently in/on :).

**Comment by AllisonFrancis** [comment]
@vishnunavuluri Here is the XD link to all the breaking point screens for button placement
https://xd.adobe.com/view/7ff8e312-639d-4006-9c1b-928f24050af3-2aab/
