### ISSUE TITLE
Bug: Account type filter logic 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2582]
## Test Case
Test Case[:TC470](https://epacamd.testquality.com/project/11428/plan/21762/test/312967)

## Steps to Reproduce
1. Navigate to the custom data download 
2.  Select allowance transactions 
3. Enter time period 1/1/ 2019 - 1/1/2020 
4. Apply surrender as a account type 
5. Select preview data 

Any time an account type grouping or an account type is applied all of the optional filters do not have data associated with them and are not disabled. However in the data preview, there is data associated with the filters. 

### Actual Results

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8d94ef44-cb3a-445c-b4d9-36801297f227)

**Comment by MaeganWood64** [comment]
Open defect in TestQuality [D107](https://web.testquality.com/site/epacamd/project/11428?defectId=9901)
- Test [Engage filter logic by account type - allowance sub types](https://web.testquality.com/site/epacamd/project/11428/runs/155307?resultId=2658869) in Run [TC_470_Allowance_Account_Type](https://web.testquality.com/site/epacamd/project/11428/runs/155307) (linked to Cycle [Filter Logic](https://web.testquality.com/site/epacamd/project/11428/cycles/21762)).

**Comment by JanellC** [comment]
Defect D107 resolved
