### ISSUE TITLE
Display download functionality and alert at 200% zoom - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2585]
## Context 

Testing complete for 2565, 2 issues:

1. The message 'Your query exceeds the record limit of 100000. Refine your query to further limit the number of records returned or visit the Bulk Data Files.' disappears when zoomed into 200%

2. At 175% magnification and above, the controls to download data as CSV or JSON files are no longer available.

Solution :will need to update the mobile/ tablet wireframes to display the download functionality and the cdd alert 

Wireframes 
[Data Preview Mobile Wireframes ](https://xd.adobe.com/view/121d4adc-4c31-403c-91c2-2fd3764fa4f3-474e/screen/77c369a4-4c55-42ab-a3cc-963f2cbe945e/) - slides 25, 26

[Data Preview Tablet Wireframes 
](https://xd.adobe.com/view/121d4adc-4c31-403c-91c2-2fd3764fa4f3-474e/screen/cfbd5567-a980-44f4-928c-0e3c2c78b049/) - slides 28,29

## Testing: 
- This ticket will require functional testing and 508 testing 

Tester: @JanellC 

508 Testing: @aprematta

**Comment by aprematta** [comment]
Testing complete - Both the alert and the download options are available at 200%
