### ISSUE TITLE
mobile/ tablet clear filter button - 508 issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2586]
## Context 

<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="window-close" class="svg-inline--fa fa-window-close fa-w-16 float-right clearfix" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" tabindex="0"><path fill="currentColor" d="M464 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm-83.6 290.5c4.8 4.8 4.8 12.6 0 17.4l-40.5 40.5c-4.8 4.8-12.6 4.8-17.4 0L256 313.3l-66.5 67.1c-4.8 4.8-12.6 4.8-17.4 0l-40.5-40.5c-4.8-4.8-4.8-12.6 0-17.4l67.1-66.5-67.1-66.5c-4.8-4.8-4.8-12.6 0-17.4l40.5-40.5c4.8-4.8 12.6-4.8 17.4 0l66.5 67.1 66.5-67.1c4.8-4.8 12.6-4.8 17.4 0l40.5 40.5c4.8 4.8 4.8 12.6 0 17.4L313.3 256l67.1 66.5z"></path></svg>

2.  aria-hidden="true" needs to be removed
3.  it also needs an aria label that relates it to the filter removal something like aria-label='Remove the <filter name> filter

**Comment by aprematta** [comment]
Looks good, issues have been fixed, closing ticket
