### ISSUE TITLE
Address Legacy Parameter Codes in the Defaults Master Data Relationship View

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2589]
## User Story
As a Monitoring Plan Check engine user 
I want to accurately be informed of which parameter codes are valid 
So that I can correctly submit a plan 

## Acceptance Criteria (if Development notes 2)
Given a user uses e a retired code (AKSF and SORX)
When they attempt  to submit 
Then they are given a message "RETIRED - DO NOT USE"

### Development Notes

1 - [X] Remove the AKSF and SORX parameter codes from the camdecmpsmd.vw_defaults_master_data_relationships view, or
2 - [ ] Update the  description for AKSF and SORX parameter codes to include "RETIRED - DO NOT USE", and tie the parameter codes to all available options for the other fields

## Testing
Test Case: confirm that the values below are not displayed in the Parameter Code drop down list for Defaul data iN ECMPS
AKSF - "Appendix K Sample to Stack Flow Scaling Factor"
SORX - "Maximum SO2 Emission Rate (lb/mmBtu)"

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by sanleyCVP** [comment]
Based on discussions with Chris W. we will move forward with removing the codes from the valid values, as there are no entries with these codes in the monitor_default  table of the camdecmps and  camdecmpswks schemas

**Comment by mosesdeeCVP** [comment]
![2589 Address Legacy Parameter Codes in the Defaults Master Data Relationship View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/063bdc5a-4a99-40ed-a632-a53b1581a3bd)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC569](https://epacamd.testquality.com/project/11428/plan/21902/test/326034)
Test Passed
