### ISSUE TITLE
Remove 'Import a Monitoring Plan' Button 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2591]
Currently, there is an 'Import a Monitoring Plan' button in the Workspace>Monitoring Plan>Select Configurations screen

**Action:** Remove this button

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/be0577f5-9b7a-4128-bb2d-a4c176c6ad2b)

Note: Import a Monitoring Plan button shall only be available on the individual Configurations tab

**Comment by mosesdeeCVP** [comment]
![2591 Remove 'Import a Monitoring Plan' Button .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d967e374-a6b8-48fe-ad69-1df696772198)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC590](https://epacamd.testquality.com/project/11428/plan/22924/test/327970)
Test Passed
