### ISSUE TITLE
BUG: Search Icon Missing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2593]
In ECMPS, when a user clicks on the EPA Menu to expand, the magnifying glass icon for Search in the Search Panel is missing.

Reference Image:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/98697e44-3305-4265-99a4-9b3b915e4a70)

**Comment by JanellC** [comment]
Bug Resolved 

**ECMPS** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/41e28960-3033-4b0d-a313-8406507620c3)

**CAMPD**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a97d3552-03bf-425e-80aa-5eb182868d54)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6f9d14b8-cd84-4c47-af10-a706595128c5)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/209678ea-0698-4ece-bc35-63aa50cf986e)
