### ISSUE TITLE
Contact Us Form - Add * to the Required Fields

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2594]
On the Contact Us form:

- Update **_All fields are required_** text to Required Fields are marked with an Asterix (*)
- Update the field names as below:
*Email
*Comment Types
*Comment
- Add aria-required="true" for all fields (Email, Comment Types, Comment)

**Comment by aprematta** [comment]
Text has been updated and * is on the labels. aria-required="true" was not added.

**Comment by aprematta** [comment]
aria-required="true" is now present
