### ISSUE TITLE
Add Aria Alert to the Login Window

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2595]
On the login window, add an aria-alert to the login validation error messages 

Add Aria live to:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ac331df0-e0e6-421b-a46e-900162d57c74)
 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5af52834-3a3c-4051-a604-a1acd7b8d97c)

**Comment by aprematta** [comment]
Alert is now in live region and screen reader announces the errors
