### ISSUE TITLE
Issue with View/Edit/Create - Rectangular Duct WAFs

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2597]
Steps to replicate:

Login as an ECMPS user
In the workspace, open any configuration tab and navigate to the Rectangular Duct WAFs section
Click View/Edit/Create options. Fails to open the respective modal.

Note: No pre-filtering is required on this section. Any UI work or creation of backend endpoints out of scope for this ticket

**Comment by mosesdeeCVP** [comment]
Bug Fixed
