### ISSUE TITLE
Add Data Caveat to Mats DATA - Need by 2/21

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2608]
## Context 

The EPA wants to include a data caveat on the custom data download for MATS data. The Note will say the following: MATS required that coal-fired electricity generating units (EGUs) start reporting hourly MATS emissions and operations data as early as April 2015, but provided extensions for many EGUs until April 2016 or 2017. Therefore, complete MATS data are not available until calendar year 2018.

**Examples from AMPD:** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c6f1ffab-107e-4e52-ba63-1da461b4cd78)

Add Data Caveat on MATS data: MATS required that coal-fired electricity generating units (EGUs) start reporting hourly MATS emissions and operations data as early as April 2015, but provided extensions for many EGUs until April 2016 or 2017. Therefore, complete MATS data are not available until calendar year 2018.

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1f2739ba-3d02-472a-a78a-fac383efe685)

**Comment by NadiaJL** [comment]
@JanellC @AllisonFrancis @tlageman-epa 
Updated Data Caveat to Mats DATA WFs- mobile, tablet, and desktop WFs - shared Xd document links with the requested edits as discussed during the PD meeting today, 2/22/22:

Data Caveat to Mats DATA - mobile -
https://xd.adobe.com/view/4853f38d-a5e3-4325-8aa4-7d50d7dc66aa-1d00/

Data Caveat to Mats DATA - Tablet -
https://xd.adobe.com/view/4111c69a-cf37-4a66-bbe8-485ca47523e5-1442/

Data Caveat to Mats DATA - Desktop 1024
https://xd.adobe.com/view/dac248cb-3232-42c0-b1f0-e9aa66f0bfcc-8f91/

Data Caveat to Mats DATA - Desktop 1200
https://xd.adobe.com/view/0cb919a9-bf20-42ee-b210-7073b367dd49-59ea/
