### ISSUE TITLE
Create Monitoring plan JSON schema for Import Validation

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2613]
- [ ] Create Monitoring plan JSON schema for monitoring plan json import validation using the **MonitoringPlan.xs**d as a basis

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/152d9628-c19c-46c2-8918-df64afc9127d/download](https://app.zenhub.com/files/287570343/152d9628-c19c-46c2-8918-df64afc9127d/download)

**Comment by MaeganWood64** [comment]
Basing JSON Schema on existing MP JSON Structure

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/c297b516-a3a2-461d-b5d8-0e0d46eb9f38/download](https://app.zenhub.com/files/287570343/c297b516-a3a2-461d-b5d8-0e0d46eb9f38/download)

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/6bc0eae9-b327-4bb7-a597-b438f128ef9e/download](https://app.zenhub.com/files/287570343/6bc0eae9-b327-4bb7-a597-b438f128ef9e/download)

**Comment by sanleyCVP** [comment]
1. **UnitStackConfiguration.unitId** should be defined as a string. The JSON import file will bring over the name of the Unit not the DB Id
2. **Location** should be limited to Id, UnitId and StackPipeId <-- **_IGNORE_**
3. **Location.unitId** should be defined as a string. The JSON import file will bring over the name of the Unit not the DB Id
4. **Missing section for Unit** with attribute nonLoadBasedIndicator (type number) and referencing the same arrays as Location - **_PENDING DISCUSSION_** 
5. **Missing section for StackPipe** with attributes activeDate (type date), retiredDate (type date) and referencing the same arrays as Location (minus unitControl, unitCapacity and unitFuel) - **_PENDING DISCUSSION_**
6. **Attribute.ductIndicator** should be number, possible values are only 0 or 1
7. **Attribute.bypassIndicator** should be number, possible values are only 0 or 1
8. **LocationComponent.hgConverterIndicator** should be number, possible values are only 0 or 1
9. **Default.endHour** should be number as beginHour (same values expected)
10. **Formula.endHour** should be number as beginHour (same values expected)
11. **Method.endHour** should be number as beginHour (same values expected)
12. **MatsMethod.endHour** should be number as beginHour (same values expected)
13. **LeeQualification.potentialAnnualMassEmissions** should be number
14. **LmeQualification.so2Tons** should be number
15. **Span.mpfValue** should be number
16. **Span.defaultHighRange** should be number
17. **Span.flowSpanValue** should be number
18. **Span.flowFullScaleRange** should be number
19. **Span.endHour** should be number as beginHour (same values expected)
20. **System.endHour** should be number as beginHour (same values expected)
21. **SystemComponent.endHour** should be number as beginHour (same values expected)
22. **SystemComponent** contains values that are related to **Components** - **_PENDING DISCUSSION_** 
23. **FuelFlow.endHour** should be number as beginHour (same values expected)

Review completed... update the issues listed above with the exception 4,5, and 22 which require additional discussion/clarification

**Comment by sanleyCVP** [comment]
Item 2.. **_IGNORE_**
No action needed for items 4,5, and 22. Leave as is

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/b7324ad1-3c37-44a2-863d-8e785f520156/download](https://app.zenhub.com/files/287570343/b7324ad1-3c37-44a2-863d-8e785f520156/download)

**Comment by sanleyCVP** [comment]
1. **MonitoringPlan**: id shouldn't be required
2. **Comment**: monitoringPlanComment and beginDate should be marked required
2. **Location**: unitId, StackPipeId, activeDate and nonLoadBasedIndicator are required
3. **Load**: add beginHour to required fields
4. **Method.endHour** should be number as beginHour (same values expected)
5. **SystemComponent.endHour** should be number as beginHour (same values expected)
6. **SystemComponent.potentialAnnualMassEmissions** should be number
7. **SystemComponent**: componentId, beginDate, beginHour are required

**Comment by sanleyCVP** [comment]
Updated schema attached

[https://app.zenhub.com/files/287570343/3c79c66f-0ca8-4226-8247-4edd30464071/download](https://app.zenhub.com/files/287570343/3c79c66f-0ca8-4226-8247-4edd30464071/download)
