### ISSUE TITLE
Remove Checkout capability from Inactive/Retired MP

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2614]
As an ECMPS user, I want the ability to check out ONLY the ACTIVE MP's so that I cannot make any updates to inactive/retired MPs

Acceptance Criteria:
Given I am an ECMPS user
When I access an inactive MP on the Select Configurations screen
Then I am only able to open it to view the MP (only see 'Open' under the Actions column)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c3715777-2ab2-436b-b77d-916371e926e8)

Given I am an ECMPS user
When I open an inactive MP for a specific Configuration
And I am on the individual tab for the Configuration
Then there is **NO** 'Check-Out/Check Back In' options available

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/319dadb8-bf13-47f9-8c59-6a5ad575b844)

**Comment by mosesdeeCVP** [comment]
![2614 Remove Checkout capability from Inactive-Retired MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/29729752-49e5-4f4c-959b-072dbdd79d5a)

**Comment by mosesdeeCVP** [comment]
![2614 Remove Checkout capability from Inactive-Retired MP - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/688c3ae1-7e49-4868-8a41-80cf48069a03)

**Comment by mosesdeeCVP** [comment]
Test Case [TC595](https://epacamd.testquality.com/project/11428/plan/19352/test/328275)

Test Passed
