### ISSUE TITLE
CDD Filters- EPA 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2615]
## Context 

At 175% magnification and above, a “Back” button is added to enable navigation to the data filters.  The wording is too vague and should convey the function of the button more clearly.

**Comment by JanellC** [comment]
@aprematta This ticket is ready for 508 testing

**Comment by aprematta** [comment]
Testing complete, back button now has a descriptive aria label aria-label="Back - Select to modify filter selections."
