### ISSUE TITLE
Select JSON Schema Validation Package 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2621]
- [ ]  Validate the file against the defined JSON schema 

Use one of the packages below to validate incoming JSON against schema
- original JSV package - https://www.npmjs.com/package/JSV
- fixed version of above JSV package - https://www.npmjs.com/package/jsv-fixed

If the file being imported fails to validate against the schema display the following message:
_[SCHEMA-FATAL-1] The file submitted doesn't match the structure/format for importing._ 

Add details if the package allows to do so

![image](https://user-images.githubusercontent.com/66504934/153472262-d131abb7-123e-449c-99c9-513e3627f777.png)

**Comment by sanleyCVP** [comment]
We need to specify where will the Schema be hosted for consumption during the validation
