### ISSUE TITLE
Update the field "parameterCode" to "controlEquipParamCode"

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2628]
- Update the field "parameterCode" to "controlEquipParamCode" for all Unit Controls endpoints (GET, POST and PUT) in the Monitoring Plan API
- Update the field "parameterCode" to "controlEquipParamCode" for the GET Unit Controls endpoint for relationships in the Master Data API

For Testing: Create and Edit modals for Unit Control data

Note: The above updates must be implemented for view vw_unitcontrol_master_data_relationships also

**Comment by mosesdeeCVP** [comment]
All Swagger pages are updates:
![2628 Update the field parameterCode to controlEquipParamCode.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dbb04991-5ff8-435f-a44b-2c572f57316a)

**Comment by dionolympiaCVP** [comment]
Worked with Conrad to update the column name in the unit controls relationship view and updated the MDM API to reflect the renamed column.

**Comment by mosesdeeCVP** [comment]
Tests ran: [TC424](https://epacamd.testquality.com/project/11428/plan/22363/test/308835) [TC425](https://epacamd.testquality.com/project/11428/plan/22363/test/308836)

Tests Passed
