### ISSUE TITLE
Select Mats data on the custom data download

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2635]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the ability to select MATS data so that I can create a customized dataset 

## Acceptance Criteria
Given that a user has navigated to the custom data download 
When the data type functionality is displayed 
Then the user has the option to select:  Mercury and Air Toxics Emissions

Given that a user has selected Mercury and Air Toxics Emissions as a data type
When the data sub type functionality is displayed 
Then the user has the option to select : Hourly Emissions

Given that a user has applied MATS data as data type 
When the functionality is displayed
Then the following filters are displayed: Time Period, State/ Territory, Facility, Unit Type, Unit Fuel Type, Control Technology 

Given a user has selected time period 
When a value is not entered for begin and end date
Then the ability to apply the filter is disabled

Given a user has entered a time period (not null)
When the user applies the filter
Then the system will ensure that the data is valid

Given that a user has selected time period
When the criteria is entered
Then the system ensures the date is in the MM/DD/YYYY format
And displays the appropriate error message if not: 

Given that a user has selected time period 
When the criteria is entered
Then the system ensures that that criteria is a valid range: : 01/01/2015- latest reporting quarter
And displays the appropriate error message if not: 

Given that a user has selected time period
When the criteria is entered
Then the system ensures that end date is equal to or greater than begin date
And displays the appropriate error message if not: 

Given a validation has failed
When the error message is displayed
Then the error message is displayed in accordance with the USWDS validation component

Given that a user has selected state
When the functionality is displayed
Then the results populate in a list
And are displayed in the full state name format

Given that a user has selected state
When the functionality is displayed
Then the user can select one or multiple state(s)

Given that a user has selected state
When the search is executed
Then the system conducts a case insensitive and begins with search

Given that a user has selected facility
When the search is executed
Then the system conducts a case insensitive and a contains search on Facility Name and ORIS Code

Given that a user has selected facility
When the search is executed and no results are found
Then the system notifies the user that “No facilities match your search.”

Given that a user has selected unit type
When the functionality is displayed
Then the user has the option to select from boiler, turbine,  Furnaces
And can select one or multiple unit types or unit type groupings

Given that a user has selected unit type
When the criteria are displayed
Then the user has the option to select/deselect all options with a group

Given that a user has selected control technology
When the functionality is displayed
Then the user has the option to select from SO2 Controls, Hg Controls, NOx Controls, Opacity Controls, and Other
And can select one or multiple control technology groupings

Given that a user has selected control technology
When the criteria are displayed
Then the user can select one or multiple unit types or unit type groupings

Given that a user has selected fuel type
When the criteria are displayed
Then the user has the option to select/deselect all options with a group

Given that a user has selected fuel type
When the functionality is displayed
Then the system displays a list of coal, gas, oil,  and other fuel types
And the user can select one or multiple fuel types

Given that a user has applied filter criteria 
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria 
When any facility criteria is cleared
Then the system clears the criteria from the filter and removes the filter tag 

### Development Notes

- [ ] data type selection
- [ ] data sub-type selection
- [ ] populate all fiters with respective data
- [ ] enable filter selection
- [ ] manage filter tags for MATs data
- [ ] add validation for the hourly mats time period filter 

### Requirements 

Data Type
Drop Down
Value: Mercury and Air Toxics Emissions, default blank
Required
Single Select

Data Sub Type:
Drop down
Value: Hourly Emissions
Required
Single Select

Time Period:
Date picker (USWDS date picker)
Format: MM/DD/YYYY
Required
Valid date range: 01/01/2015- latest reporting quarter
Operating hours only: selected by default

State/ Territory:
Optional
Combo box
Dynamic search
Search is a “begins with” search
Results populate in a list, parameters populates when a value is selected from the list
Results display the full state name (Texas, not TX)
Search is not case sensitive
Multi Select

Facility:
Optional
Combo box
Dynamic search
Contains search
Results are displayed in Facility Name (ORIS Code)
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No facilities match your search.”
Multi select

Unit Type
Optional
Check box component
Values: Boilers, Turbines, Furnaces
Multi Select

Unit Fuel Type
Optional
Check box component
Values: Coal, Gas, Oil, Other
Multi Select

Control Technology
OPTIONAL
Check box component
Values: SO2, NOX, PM, HG, other
check box component
Multi Select

**Filter Tags:** 

Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter in tag
If more than 1, show number of parameters
Tags will have a hover functionality to display the list of selections
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group

Time period show date range
If operating hours is selected shows separate tag

Filter Tags do not display until a user applies the selection
If a user clears out the operating hours filter tag, then the selected time period is retained
If a user clears out the time period filter tag, then the operating hours filter tag is automatically cleared out and the time period filter resets to its default state (blank and operating hours only checked)
If a user changes there data type and data subtype, their previous time period selections aren't retained

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC600 ](https://epacamd.testquality.com/project/11428/plan/23917/test/328336)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@JanellC @addisgmichael you may have already flagged this in testing, but I just noticed that the Program filter was included in this work. The program filter is not part of this ticket's a/c. The program filter is not applicable to MATS data since MATS is the specific program, therefore the filter should not be available in UI.

**Comment by JanellC** [comment]
Found a defect with this ticket. See: Bug: #2703. I added a meet after to further discuss the bug @tlageman-epa

**Comment by JanellC** [comment]
This ticket is ready for 508 testing @aprematta
