### ISSUE TITLE
Create Modal/Window for Import Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2638]
- User clicks on the 'Import a Monitoring Plan' button
- This action opens a modal where users can select the file to be imported 
Language to be used on this modal:
Please select a Monitoring Plan for 'Configuration Name' that you wish to import
- Once the user has made a selection for the JSON file, they click **Import** on the Modal
- The modal is updated with a spinner (all other fields are hidden) when the Import process is in progress
- Once the process completes, the spinner is hidden and the success/error message from the API is displayed in the modal 
- User can close the modal at any time using **X**

Success Message:
Your 'file name-.jason' has been successfully imported
- User can click on OK to close the Modal

Sample Errors:
Please select a valid file type (.JSON)
The Facility and the Configuration you selected for import do not exist. Please check
You do not have permission to update the selected Facility and Configuration. Please check

Spinner in the EASEY Design System: https://zeroheight.com/37f47ceee/p/8562fc-spinner

**Comment by NJLCVP** [comment]
Import>model select your JSON file>spinner-file is uploading>modal success "your -file name-.jason has been successfully uploaded - ok button>modal error - shows error message takes the user back to select a file

**Comment by NadiaJL** [comment]
Import>model select your JSON file>spinner-file is uploading>modal success "your -file name-.jason has been successfully uploaded - ok button>modal error - shows error message takes the user back to select a file

**Comment by NadiaJL** [comment]
ECMPS Import Monitoring plan pop-up modal WFs
https://xd.adobe.com/view/a6e86bca-668f-4047-b9e6-b2dfab8210aa-f3bb/

**Comment by AllisonFrancis** [comment]
Modal is fine for when there are no errors. We need and alternate that is larger for errors. There could be many... MANY errors 
So the solutions we're thinking:
The larger modal should be 75 or 80% of each screen size. And if there are more than one error (likely) we show some subset of errors in a scrollable window. Sample errors are below.

[1:11 PM] Conrad Sanley
You have reported a MonitorQualPercent record for a location with the Qualification Type Code not equal to "PK," "SK" or "GF." A MonitorQualPercent record should not be reported for qualification Codes other than "PK", "SK" or "GF".

[1:11 PM] Conrad Sanley
A value has been reported for SO2Tons for the Monitor Qualification LME record #[index of record]. This field should be blank

**Comment by NadiaJL** [comment]
Export-Import Buttons  - Shared Xd Link
https://xd.adobe.com/view/723aace9-e677-4706-9cb2-ad9600ebf883-2769/

Import Monitoring plan pop-up modal - Shared Xd Link
https://xd.adobe.com/view/a6e86bca-668f-4047-b9e6-b2dfab8210aa-f3bb/
