### ISSUE TITLE
Create 'Import Modal'

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2644]
As an ECMPS user, I want the ability to select a Monitoring Plan file from my local so that I can import it

Acceptance Criteria:

Given I am a logged in ECMPS user (workspace)
When I select and checkout a Configuration 
And click on the 'Import a Monitoring Plan' button (on the selected configuration tab)
Then the system opens a modal

Given I am on the 'Import a Monitoring Plan' modal
When I select a MP file to be imported
And click on **Import**
Then the import process is initiated and the spinner is displayed in the modal

Given I import a MP 
When the MP import is successful
Then I see the following success message: Your 'file name-.JSON' has been successfully imported
And I can click on OK on the modal to navigate back to the Configurations tab/close the modal

Note: Mock the API calls (as that is WIP)

Import Monitoring plan pop-up modal - Prototype:
https://xd.adobe.com/view/a6e86bca-668f-4047-b9e6-b2dfab8210aa-f3bb/
Updated/delta from the Mockup:
- Replace option that is displayed when a file is imported will read 'Change file'
- The mockup has 2 places where error messages are displayed. One in the header and one inside the box in the Modal. We will ONLY see the error message displayed in the header section now

**Comment by mosesdeeCVP** [comment]
Test Case: [TC609](https://epacamd.testquality.com/project/11428/plan/22924/test/328895)

**Comment by mosesdeeCVP** [comment]
![2644 Create 'Import Modal' - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f315356e-37db-4f61-b934-c46315ec20ac)

![2644 Create 'Import Modal' - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/94402c8f-5582-48dd-9d27-96ef3b90e3ab)

![2644 Create 'Import Modal' - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1efd51f1-1ee8-4ae0-a786-d23423867add)
