### ISSUE TITLE
Export a MP to JSON and API

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2646]
As an ECMPS user, I want the ability to access Monitoring Plan data JSON response so that I can review it offline

Acceptance Criteria:

Given I am a logged in ECMPS user 
When I select and checkout a Configuration
Then I can see a MP JSON response (Thru swagger link)

Create an export endpoint (GET) for the following data:
Defaults Data
Formula Data
Load Data
Location Attributes and Relationship Data
Method Data
Qualifications
Rectangular Duct WAFs
Span Data
System Data
Analyzer Ranges
System Component
System Fuel Flow
Unit Information

Note: 
- https://api.epa.gov/easey/dev/monitor-plan-mgmt/swagger/#/Plans%20%26%20Configurations/MonitorPlanController_getMonitorPlan
- Install the downloadjs package

**Comment by sanleyCVP** [comment]
@jeffreyaggrey @jwhitehead77 I see this export file doesn't contain sections for UnitData nor StackPipe data in the same fashion as the Import process expects it. Should we modify the output of the export or the input for the import?

**Comment by mosesdeeCVP** [comment]
Test Case: [TC612](https://epacamd.testquality.com/project/11428/plan/22924/test/329074)

**Comment by mosesdeeCVP** [comment]
Test Passed
