### ISSUE TITLE
Move 'Actions' Column on Configurations Tab

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2659]
Move the 'Actions' column in a data grid as the first column

**Current:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d7080d5c-cc8b-4a09-a02a-46a966260a86)

**Expected:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/fe569453-2340-430c-a8c1-32acf8c0056f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC602](https://epacamd.testquality.com/project/11428/plan/19352/test/328509)

**Comment by mosesdeeCVP** [comment]
![2659 Move 'Actions' Column on Configurations Tab.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9bc8081d-0ab9-419b-88ac-e86ac9643c59)

**Comment by mosesdeeCVP** [comment]
Test Passed
