### ISSUE TITLE
Import - Validate JSON File (UI)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2661]
As an ECMPS user, I want the system to validate the format of files being imported so that I can only import JSON files

Acceptance Criteria:

Given I am Importing a Monitoring Plan file
When I select a file format that is not JSON
And click on Import
Then I see an error message that reads: "Only JSON files may be submitted"

Given I am Importing a Monitoring Plan file
When I select a JSON file that contains invalid JSON
And click on Import
Then I see an error message that reads: "JSON file is invalid"

Given I see an error with the file format
When I want to select another file to import
Then I see the option "Change file" to change the existing file in the Import Modal

**Comment by dionolympiaCVP** [comment]
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/d11099c9-2752-47ac-a8f7-96cbc5641461)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/c9dd6c0e-3140-4709-8aa1-4a20a6475939)
![image.png](https://images.zenhubusercontent.com/61436db28447a55f1e8872de/7adb7e4f-a169-4c80-8c80-1ae85943bb63)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC608](https://epacamd.testquality.com/project/11428/plan/22924/test/328894)

**Comment by mosesdeeCVP** [comment]
![2644 Create 'Import Modal' - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6fbd2656-81f8-4c52-a621-df7e1a55f8ce)

![2644 Create 'Import Modal' - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c2f51811-95a7-4756-8418-c955d3d51eaa)

![2644 Create 'Import Modal' - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c10523bd-161c-4f94-8c1f-96cb77dc4dcd)

![2644 Create 'Import Modal' - 4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/067a5735-03b5-4537-834e-538fc4a1d46e)

![2644 Create 'Import Modal' - 5.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/79df0b03-7802-41ce-b173-f068ef7bf98d)

![2644 Create 'Import Modal' - 6.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ef260c85-cede-46cc-ada4-ce42e51dfb12)
