### ISSUE TITLE
Import - Handle API Error Messages

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2662]
Handle any errors from API checks

Modal sizing and other responsive efforts for when there are errors. The larger modal should be 75 or 80% of each screen size and if there are more than one error(s) we show some subset of errors in a scrollable window. 

API Endpoint: https://api.epa.gov/easey/dev/monitor-plan-mgmt/swagger/#/Plans%20%26%20Configurations/MonitorPlanController_getMonitorPlan

**Comment by vishnunavuluri** [comment]
@sanleyCVP Provide a list of error messages to mock the error modal

**Comment by mosesdeeCVP** [comment]
![2662 Import - Handle API Error Messages.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/83e83344-2161-4714-ac7b-ca137fb745b8)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC611](https://epacamd.testquality.com/project/11428/plan/22924/test/329072)
