### ISSUE TITLE
Add error handling for Content Manager Human/Input Error 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2663]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As the EPA I want the EASEY content management system to have error handling in place So that I don't break CAMPD when making updates to a JSON file 

## Acceptance Criteria
Given that a user has made an inaccurate update to a JSON file in  in the EASEY content management system
When the CAMPD functionality is displayed 
Then the system displays a USWDS alert with the Content Manager Human/Input Error (JSON file error): ([Refer to the CAMPD downtime document](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B33677C82-CD21-4DE2-B3EA-7FCE5907452A%7D&file=CAMPD%20Downtime%20Errors%20-%20EPA%20CAMD%20-%20v1.0.xlsx&action=default&mobileredirect=true) )

### Development Notes
- Utilize the blue informational alert from USWDS: https://designsystem.digital.gov/components/site-alert/

- Display the USWDS alert at the top of the CAMPD application like the [ECMPS](https://easey-dev.app.cloud.gov/ecmps) application 
Example on how the USWDS should be displayed on CAMPD: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/45a5c3c0-dae2-41e7-a4cb-e6aeabdc0a96)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

- Json files are edited improperly (missing comma, missing quotation mark) 

https://designsystem.digital.gov/components/site-alert/

See spike #2800 

https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B33677C82-CD21-4DE2-B3EA-7FCE5907452A%7D&file=CAMPD%20Downtime%20Errors%20-%20EPA%20CAMD%20-%20v1.0.xlsx&action=default&mobileredirect=true

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Per backlog refinement on 6/1, this functionality will not be included in the 1.1 release

**Comment by hamezene** [comment]
need more research

**Comment by ergjustin** [comment]
When I test API error banner, I found one issue that is in contact page email API shows **404 error** []()[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0l3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b0a45a85b88a0713914e8b63dee18f873761410/Contactus-Email-404-1.jpg)

**Comment by ergjustin** [comment]
**IN DEV ENVIRONMENT** When I test API error banner, I found one issue that is in contact page email API shows 404 error []()
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2d3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae05158188e729a1ae9e9fb5f7a99bf3054b72ac/Contactus-Email-404-1.jpg)

**Comment by ergjustin** [comment]
## PR 
https://github.com/US-EPA-CAMD/easey-campd-ui/pull/611
## Changes
Added Input error handling by using yup
## Step to test

1. easey-campd-ui connect to easey-content locally using REACT_APP_EASEY_CONTENT_API
2. Change the value of campd json file and test

**Comment by shahbazkhan1999** [comment]
@bchofor start to test this one need any help coordinate @ergjustin

**Comment by ergjustin** [comment]
**Developer test in dev env**
I made an input error in easey-content  /data/home.index.json (removing name) then throws error without app crushing and display `contentManager` error,
[contentManager Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2h3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3c46f99ee34bae5b4e4683249f4d65c38df6321/Input-validation-error-dev.PNG)

**Comment by tlageman-epa** [comment]
looks good in staging
