### ISSUE TITLE
Unable to View Relationship Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2664]
Steps to Reproduce:

- Select a Facility, Open, and Checkout a Configuration for the Facility 
- Select 'Location Attributes and Relationships' from the Sections dropdown on the Configurations tab
- Click on View for Relationships data
- Screen freezes and the user is unable to navigate or perform any actions on the screen

**Comment by mosesdeeCVP** [comment]
Test Case: [TC630](https://epacamd.testquality.com/project/11428/plan/22772/test/316518)
Test Passed
