### ISSUE TITLE
Updates from 2.22 ECMPS PD meeting

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2665]
Please make the following updates to the existing prototype:

- Remove the Import button from Mobile and Tablet screens 
- Remove the Export button from Mobile and Tablet screens 

Provide xd links for:
Export-Import Buttons - Shared Xd Link
https://xd.adobe.com/view/723aace9-e677-4706-9cb2-ad9600ebf883-2769/

Import Monitoring plan pop-up modal - Shared Xd Link
https://xd.adobe.com/view/a6e86bca-668f-4047-b9e6-b2dfab8210aa-f3bb/

**Comment by NadiaJL** [comment]
Export-Import Buttons - shared xd document link/WFs
https://xd.adobe.com/view/723aace9-e677-4706-9cb2-ad9600ebf883-2769/
