### ISSUE TITLE
Add Close option on MP Evaluation Report

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2669]
As an ECMPS user, I want an option to close the MP Evaluation Report so that I can navigate away when needed

Acceptance Criteria:

Given I access the MP Evaluation Report using the notification email URL
When I am on the Report screen
Then I see an option to Close Report

Given I am on the MP Evaluation Report using the notification email URL
When I click on the 'Close Report' option
Then the screen is closed after a successful API logout

Prototype for Reference:
https://xd.adobe.com/view/bdf8fe62-0af2-4fbd-8672-0b7959f8bb88-e8ab/

Note: This is NOT applicable to the MP Evaluation Report opened using the hyperlink from within the application

**Comment by mosesdeeCVP** [comment]
![2669 Add Close option on MP Evaluation Report.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a12cf9d9-bac8-409a-b932-0da42a5c05bb)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC640](https://epacamd.testquality.com/project/11428/plan/22924/test/330376)
Test Passed
