### ISSUE TITLE
MP - View Comments

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2671]
As an ECMPS user, I want the ability to view all available comments for a Facility at the selected Configuration Level so that I can make informed decisions

Acceptance Criteria:

Given I am an ECMPS user
When I click on 'View Comments' 
Then I see all available comments for the MP at the Configuration level (Individual Configurations tab)

Note: Styling effort for the Comment column is included in another ticket

Prototype: https://xd.adobe.com/view/04b8b6f9-d522-4016-9ac5-a777e8c533fa-51eb/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC635](https://epacamd.testquality.com/project/11428/plan/19352/test/330153)

**Comment by mosesdeeCVP** [comment]
![2671 MP - View Comments - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e026ba10-0c26-45ef-9880-8941015efdc8)

**Comment by mosesdeeCVP** [comment]
Test Passed
