### ISSUE TITLE
Comments Styling - View Comments Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2674]
Styling for the Comments column in the 'View Comments' modal

Prototype: https://xd.adobe.com/view/04b8b6f9-d522-4016-9ac5-a777e8c533fa-51eb/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC636](https://epacamd.testquality.com/project/11428/plan/19352/test/330157)

**Comment by mosesdeeCVP** [comment]
![2671 MP - View Comments - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cce00348-4543-4234-9313-32af6164d990)

**Comment by mosesdeeCVP** [comment]
![2671 MP - View Comments - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0b9ac08b-190d-40c1-983a-6ee3d9e10786)

**Comment by mosesdeeCVP** [comment]
![2671 MP - View Comments - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ede94a56-e826-4142-a7ab-30c6cb17e3fb)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Seconds have been removed
![2674 Comments Styling - View Comments Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aff314f5-9350-4e4c-9b89-0de1123a4ba2)

**Comment by mosesdeeCVP** [comment]
Test Passed
