### ISSUE TITLE
Add 'X' for Filter by Keyword 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2675]
As an ECMPS user, I want to ability to delete the keywords I entered at once so that I can enter a new value

Acceptance Criteria:

Given I am an ECMPS user on the Select Configurations screen
And I type in the 'Filter by Keyword' field
When I click on 'X'
Then I see that the characters I type in are deleted

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/489df098-de58-434c-a99e-809e04c62f89)

## Testing

Test Case: [TC1222](https://epacamd.testquality.com/project/11428/plan/21815/test/424884)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Filter X.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a52b523b-db06-46fe-bca2-c07dbfc2b93c)

**Comment by mosesdeeCVP** [comment]
Test Passed
