### ISSUE TITLE
Apply Import Validation Checks (DTO) for Monitor Location ATTR Data  to Import API

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2677]
**LOCATION ATTR Data Format Checks**
1. The value for DuctIndicator must be numeric, only options are 0 or 1
2. The value for BypassIndicator must be numeric, only options are 0 or 1
3. The value for GroundElevation must be numeric, and 5 digits max (no decimals)
4. The value for StackHeight must be numeric, and 4 digits max (no decimals)
5. The value for CrossAreaFlow must be numeric, and 4 digits max (no decimals)
6. The value for CrossAreaStackExit must be numeric, and 4 digits max (no decimals)
7. The value for BeginDate must be formatted as a date yyyy-mm-dd
8. The value for EndDate must be formatted as a date yyyy-mm-dd
9. If any of these fields do not contain valid values, it's an error. Error Message:
_[LOCATIONATTR-FATAL-A] The value for [fieldname] in the Monitoring Location Attributes record #[index of record] is not formatted properly_

**LOCATION ATTR Data Value Checks**
1. The value for MaterialCode must be string and limited to the results from (SELECT material_cd from camdecmpsmd.material_code)
2. The value of ShapeCode must be string and limited to the results from (SELECT shape_cd from camdecmpsmd.shape_code)
3. If any of these fields do not contain valid values, it's an error. Error Message:
_[LOCATIONATTR-FATAL-B] The value for [fieldname] in the Monitoring Location Attributes record #[index of record] is invalid_

**Testing**
Test Case: [TC668](https://epacamd.testquality.com/project/11428/plan/22772/test/337410)
Tester @mosesdeeCVP 

[Clean Monitoring Plan
](https://customervaluepartners.sharepoint.com/:w:/s/EPACAMD/EVVdfHwPBihImdC4fsX2t4cBKrLQTcbx2qErn0sx7HqQ7Q?e=mwQ46T)

**Comment by mosesdeeCVP** [comment]
![2677 Apply Import Validation Checks (DTO) for Monitor Location ATTR Data to Import API.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/deb876d8-d5ea-4653-994d-603843eadf01)

**Comment by mosesdeeCVP** [comment]
Test Passed
