### ISSUE TITLE
Apply Import Validation Checks (DTO) for System Data to Import API

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2682]
**SYSTEM Data Import Format Checks**
1. The value for MonitoringSystemID must be string with the following format: ^[A-Z0-9]{1,3}$
2. The value for BeginDate must be formatted as a date yyyy-mm-dd
3. The value for BeginHour must be numeric, within the range of 0 to 23 (no decimals)
4. The value for EndDate must be formatted as a date yyyy-mm-dd
5. The value for EndHour must be numeric, within the range of 0 to 23 (no decimals)
6. If any of these fields do not contain valid values, it's an error. Error Message:
_[SYSTEM-FATAL-A] The value for [fieldname] in the Monitoring System record #[index of record] is not formatted properly_

**SYSTEM Data Import Value Checks**
1. The value for SystemTypeCode must be string and limited to the results from (SELECT sys_type_cd FROM camdecmpsmd.system_type_code)
2. The value for SystemDesignationCode must be string and limited to the results from (SELECT sys_designation_cd FROM camdecmpsmd.system_designation_code)
3. The value for FuelCode must be string and limited to the results from (SELECT fuel_cd FROM camdecmpsmd.fuel_code where fuel_group_cd not in ('OTHER','COAL'))
4. If any of these fields do not contain valid values, it's an error. Error Message:
_[SYSTEM-FATAL-B] The value for [fieldname] in the Monitoring System record #[index of record] is invalid_

**Testing**
Test Case: [TC661](https://epacamd.testquality.com/project/11428/plan/19812/test/336584)
Tester @mosesdeeCVP 

[Clean Monitoring Plan
](https://customervaluepartners.sharepoint.com/:w:/s/EPACAMD/EVVdfHwPBihImdC4fsX2t4cBKrLQTcbx2qErn0sx7HqQ7Q?e=mwQ46T)

**Comment by mosesdeeCVP** [comment]
Test Passed
