### ISSUE TITLE
Apply Import Validation Checks (DTO) for RECT DUCT WAF Data to Import API

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2686]
**RECT DUCT WAF Data Import Format Checks**
1. The value for WAFDeterminationDate  must be formatted as a date yyyy-mm-dd
2. The value for WAFBeginDate  must be formatted as a date yyyy-mm-dd
3. The value for WAFBeginHour must be numeric, within the range of 0 to 23 (no decimals)
4. The value for WAFValue must be numeric, 6 digits max within the range of -99.9999 and 99.9999, only 4 decimals
5. The value for NumberOfTestRuns  must be numeric, 2 digits max, no decimals
6. The value for NumberOfTraversePointsWAF  must be numeric, 2 digits max, no decimals
7. The value for NumberOfTestPorts  must be numeric, 2 digits max, no decimals
8. The value for NumberOfTraversePointsRef  must be numeric, 2 digits max, no decimals
9. The value for DuctWidth  must be numeric, 5 digits max within the range of -9999.9 and 9999.9, only 1 decimal
10. The value for DuctDepth  must be numeric, 5 digits max within the range of -9999.9 and 9999.9, only 1 decimal
11. The value for WAFEndDate  must be formatted as a date yyyy-mm-dd
12. The value for WAFEndHour must be numeric, within the range of 0 to 23 (no decimals)
13. If any of these fields do not contain valid values, it's an error. Error Message:
_[RECTDUCTWAF-FATAL-A] The value for [fieldname] in the Rectangular Duct Waf record #[index of record] is not formatted properly_

**RECT DUCT WAF Data Import Value Checks**
1. The value for WAFMethodCode must be string and limited to the results from (SELECT waf_method_cd FROM camdecmpsmd.waf_method_code)
2. If any of these fields do not contain valid values, it's an error. Error Message:
_[RECTDUCTWAF-FATAL-B] The value for [fieldname] in the Rectangular Duct Waf record #[index of record] is invalid_

**Testing**
Test Case: [TC264](https://epacamd.testquality.com/project/11428/plan/22357/test/355937)
Tester @mosesdeeCVP 

[Clean Monitoring Plan
](https://customervaluepartners.sharepoint.com/:w:/s/EPACAMD/EVVdfHwPBihImdC4fsX2t4cBKrLQTcbx2qErn0sx7HqQ7Q?e=mwQ46T)

**Comment by mosesdeeCVP** [comment]
![2686 Apply Import Validation Checks (DTO) for RECT DUCT WAF Data to Import API.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7ed1f65e-6d70-400a-aa6b-cc076df66c96)

**Comment by mosesdeeCVP** [comment]
Test Passed
