### ISSUE TITLE
Apply Import Validation Checks (DTO) for Unit Fuel Data  to Import API

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2687]
**UNIT FUEL Import Data Format Checks**
1. The value for OzoneSeasonIndicator must be numeric, only options are 0 or 1
2. The value for BeginDate must be formatted as a date yyyy-mm-dd
3. The value for EndDate must be formatted as a date yyyy-mm-dd
4. If any of these fields do not contain valid values, it's an error. Error Message:
_[UNITFUEL-FATAL-A] The value for [fieldname] in the Unit Fuel record #[index of record] is not formatted properly_

**UNIT FUEL Import Data Value Checks**
1. The value for FuelCode must be string and limited to the results from  (SELECT distinct fuel_type_cd FROM camdecmpsmd.vw_unitfuel_master_data_relationships)
2. The value for IndicatorCode must be string and limited to the results from (SELECT distinct fuel_indicator_cd FROM camdecmpsmd.vw_unitfuel_master_data_relationships)
3. The value for DemGCV must be string and limited to the results from (SELECT distinct dem_gcv FROM camdecmpsmd.vw_unitfuel_master_data_relationships)
4. The value for DemSO2 must be string and limited to the results from (SELECT distinct dem_so2 FROM camdecmpsmd.vw_unitfuel_master_data_relationships)
5. If any of these fields do not contain valid values, it's an error. Error Message:
_[UNITFUEL-FATAL-B] The value for [fieldname] in the Unit Fuel record #[index of record] is invalid_

**Testing**
Test Case: [TC663](https://epacamd.testquality.com/project/11428/plan/22363/test/336832)
Tester @mosesdeeCVP 

[Clean Monitoring Plan
](https://customervaluepartners.sharepoint.com/:w:/s/EPACAMD/EVVdfHwPBihImdC4fsX2t4cBKrLQTcbx2qErn0sx7HqQ7Q?e=mwQ46T)

**Comment by mosesdeeCVP** [comment]
Test Passed
