### ISSUE TITLE
Apply Import Validation Checks (DTO) for Unit Control Data  to Import API

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2688]
**UNIT CONTROL Import Data Format Checks**
1. The value for OriginalCode must be string, max charcters 1, only options are 0 or 1
2. The value for InstallDate  must be formatted as a date yyyy-mm-dd
3. The value for OptimizationDate must be formatted as a date yyyy-mm-dd
4. The value for SeasonalControlsIndicator must be string, max charcters 1, only options are 0 or 1
5. The value for RetireDate  must be formatted as a date yyyy-mm-dd
6. If any of these fields do not contain valid values, it's an error. Error Message:
_[UNITCONTROL-FATAL-A] The value for [fieldname] in the Unit Control record #[index of record] is not formatted properly_

**UNIT CONTROL Import Data Value Checks**
1. The value for ParameterCode must be string and limited to the results from  (SELECT distinct controlequipparamcode FROM camdecmpsmd.vw_unitcontrol_master_data_relationships)
2. The value for ControlCode must be string and limited to the results from (SELECT distinct control_code FROM camdecmpsmd.vw_unitcontrol_master_data_relationships)
3. If any of these fields do not contain valid values, it's an error. Error Message:
_[UNITCONTROL-FATAL-B] The value for [fieldname] in the Unit Control record #[index of record] is invalid_

**Testing**
Test Case: [TC662](https://epacamd.testquality.com/project/11428/plan/22363/test/336830)
Tester @mosesdeeCVP 

[Clean Monitoring Plan
](https://customervaluepartners.sharepoint.com/:w:/s/EPACAMD/EVVdfHwPBihImdC4fsX2t4cBKrLQTcbx2qErn0sx7HqQ7Q?e=mwQ46T)

**Comment by mosesdeeCVP** [comment]
Test Passed
