### ISSUE TITLE
Enable File selection/download for bulk data files

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2698]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD bulk data files user I want to select and downloads files criteria so that I conduct analysis 

## Acceptance Criteria

Given that a user has selected one or multiple files in the data table 
When the functionality is displayed 
Then the system displays the number of files selected and the total size of the file(s)
And the functionality renders in accordance with the  [wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=2906%3A5283)

Given that a user has navigated to the bulk data files functionality 
When the download functionality is displayed 
Then the download is disabled until at least one file is selected 

Given that a user has selected at least one file 
When the download functionality is selected 
Then the system generates a file download of the selected file(s) 

Given that a user has selected one or multiple files 
When the file size exceeds the configurable limit 
Then the system displays an alert will the following message:  
Your file selection exceeds the download limit of 50 GB. Modify your selected files to reduce the total file size to proceed. 
And the download functionality is disabled (see context for wireframes) 

Given that a content manager has accessed the EASEY content management system 
When the functionality is displayed 
Then the content manager has the ability to edit the bulk data files download alert 

### Development Notes

- set configurable limit to 50 gb for testing purposes 

- for the total file size display the selected file size until the total reaches 1 GB then display the sum on the file size in GB 

- scope of this ticket includes giving the EPA the ability to edit the download alert in the EASEY content management system 

update the select all tool tip to display: "Selecting All" will select all files in all pages of the table

- update the select all functionality to select all files with in the data table. As a user selects files from page to page on the data table the selected files should be maintained 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

 [wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=2906%3A5283)

File Selection/ Download:

The system will display the number of file(s) a user has selected and the total file size

User will have the ability to select and download multiple files

No need for a Download manager. The system will generate multiple downloads

Download functionality will be disabled until at least one file is selected

If the number of files selected is greater than 50 gb (configurable limit) then the system will display an alert to notify the user that the number of files selected exceeds the download limit and the download functionality will be disabled

## Testing
Test Case: [TC649](https://epacamd.testquality.com/project/11428/plan/24093/test/335829)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
updated tooltip text: "Selecting All" will select all files in all pages of the table. @AbuFofanah

**Comment by JanellC** [comment]
TC649 passed @tlageman-epa  . For testing purposes we set the download limit to 5 gb. The download limit is now 50 gb. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6b0be510-c5f1-42dc-bedc-8764c33b3a28)


@aprematta this ticket is ready for 508 testing
