### ISSUE TITLE
Apply Import Validation Checks (DTO) for Unit Capacity Data to Import API

### ISSUE THREAD

**Issue by sanleyCVP** [US-EPA-CAMD/PI-1#2707]
**UNIT CAPACITY Import Data Format Checks**
1. The value for MaximumHourlyHeatInputCapacity must be numeric, 7 digits max within the range of -999999.9 and 999999.9, only 1 decimal
2. The value for BeginDate must be formatted as a date yyyy-mm-dd
3. The value for EndDate must be formatted as a date yyyy-mm-dd
4. If any of these fields do not contain valid values, it's an error. Error Message:
_[UNITCAPACITY-FATAL-A] The value for [fieldname] in the Unit Capacity record #[index of record] is not formatted properly_

**Testing**
[TC618](https://epacamd.testquality.com/project/11428/plan/23995/test/fullscreen/329179)
Tester: Maegan Wood

**Comment by MaeganWood64** [comment]
TC618 Passed
