### ISSUE TITLE
Allowance Transactions Bulk Data Files Quartz Process

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#2711]
## Allowance Transactions
Create a Quartz Job responsible for determining which datasets need to be generated/regenerated. This job will NOT be responsible for generating the files, instead, this process will schedule multiple instances of the BulkDataFile job that will actually stream the data to S3 storage.

### Implementation Details
In the easey-quartz-scheduler jobs folder create a class called AllowanceTransactionsBulkDataFiles that implements the Quartz IJob interface by implementing the Execute method of the interface.

### Groupings
One file per allowance program (ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, NBP, OTC, TXSO2)

### Frequency
Annually for active programs at the end of the 4th calendar quarter with checks for updates/changes to retired programs (ARE CHECKS NIGHTLY OR PER YEAR)

### Notes from ERG to be updated with more details
The current transaction data set job runs annually on January 15th.  New transaction data sets are generated annually with the data set for the previous year being generated.  There is also a mechanism built into the transaction data set process to manually force the regeneration of historical transaction data sets (via updates to the TRANSACTION_DATASET_QUEUE table combined with the manual execution of the transaction data set job).

May need to add last_updated_date to the transaction_fact & transaction_dim table in order to derive which files have changed since the last run and which ones need to be generated/regenerated.

**Comment by tlageman-epa** [comment]
I wanted to point out that the grouping is incorrect. It should be One file per program. That file will include all years.
