### ISSUE TITLE
Allowance Compliance Bulk Data Files Quartz Process

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#2712]
## Allowance Compliance
Create a Quartz Job responsible for determining which datasets need to be generated/regenerated. This job will NOT be responsible for generating the files, instead, this process will schedule multiple instances of the BulkDataFile job that will actually stream the data to S3 storage.

### Implementation Details
In the easey-quartz-scheduler jobs folder create a class called AllowanceComplianceBulkDataFiles that implements the Quartz IJob interface by implementing the Execute method of the interface.

### Groupings
One file per retired/active allowance programs (ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, NBP, OTC, TXSO2)

### Frequency
Annually for active programs at the end of the 4th calendar quarter with checks for updates/changes to retired programs (ARE CHECKS NIGHTLY OR PER YEAR)

### Notes from ERG to be updated with more details
The current compliance data set job runs monthly on the 15th of each month.  New compliance data sets are generated annually, with the ARP data sets generated on June 15th (for the prior year) and the the CSAPR/TXSO2 data sets being generated on August 15th (for the prior year).  The compliance data set job also regenerates historical compliance data sets for any program/year that has new/updated data created after the data set creation date (determined by comparing the ADD_DATE/UPDATE_DATE in ACCOUNT_COMPLIANCE_SS/NOX_COMP_PLAN_RESULT_SS to DATE_CREATED in COMPLIANCE_DATA_SET).

May need to add last_updated_date to the account_compliance_dim & unit_compliance_dim table in order to derive which files have changed since the last run and which ones need to be generated/regenerated.

**Comment by tlageman-epa** [comment]
The grouping should be one filer per program. each file will include all years.
