### ISSUE TITLE
Bug: Adjust data table column spacing on the cdd

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2717]
## Test Case
[TC621](https://epacamd.testquality.com/project/11428/plan/23473/test/329303)

## Steps to Reproduce
1. Navigate to the custom data download 
2. Select hourly emissions as a sub type 
3. Apply required criteria 
4. select preview data 
5. Select the columns on the data preview 

Some of the data elements with in the data table are cut off. The specified column width will need to be adjusted for each data elements that is cut off. This will need to be fixed for emissions, allowance, compliance, and facility sub types. As apart of the scope of this ticket, the column width for each data label with need to adjusted to accommodate for the additional icon that will be added to the data table at a later time. **See wireframes:** 

 For reference: [CDD column widths](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B6584165D-3037-4988-94B1-3CB4330F0A5E%7D&file=CDDcolumn%20widths-v2.0.xlsx&action=default&mobileredirect=true) 

Columns that need to be adjusted are highlighted in yellow/ and or have a note. Ensure, all of the columns are adjusted to accommodate for the additional icon that will be added. see:  [wireframes 
](https://xd.adobe.com/view/4eba0d3a-2cac-4a0f-9299-1b9233af7e2d-1be9/) Adjust all column widths to accommodate the additional icon that will be added to the data table 

### Actual Results

Some of the data elements with in the data table are cut off. See the screen shot below. 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/674fad42-e7bf-4af2-8a50-e287ee74b077)

[CDD column widths](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B6584165D-3037-4988-94B1-3CB4330F0A5E%7D&file=CDDcolumn%20widths-v2.0.xlsx&action=default&mobileredirect=true)

**Comment by JanellC** [comment]
Tested #2717. Data elements look fine. Let me know if you have any feedback @tlageman-epa

**Comment by tlageman-epa** [comment]
@JanellC  looks good to me thx
