### ISSUE TITLE
Update Plans & Configurations API endpoints

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2719]
For the following endpoints:
monitor-plan-mgmt/plans/{planId} (and workspace version)
monitor-plan-mgmt/plans/{orisCode}/configurations (and workspace version)
monitor-plan-mgmt/workspace/plans/{planId}/refresh
monitor-plan-mgmt/locations/relationships (and workspace version)

Update: "unitStackConfiguration": [
    {
      "unitId": 2,
      "stackPipeId": "MDC-CCB8D6D0D4E34D24A99C01DCD14078DF",
      "beginDate": "1995-01-01",
      "endDate": "2020-12-31",
      "id": "CAMD-18DD175CE7EF4256B78469865D84F576",
      "userId": "abcde",
      "addDate": "2009-02-20",
      "updateDate": "2009-02-20",
      "active": true,
      **"stackName": "string" <-- source: camdecmps.stack_pipe.stack_name (for workspace version DB is camdecmpswks)
      "unitName": "string" <-- source: camd.Unit.UnitId**
    }
  ],

 Verify: "locations": [
    {
      "unitId": null,  **<-- Need to verify the DB source of this attribute**
      "stackPipeId": "CS0AAN", **<-- Need to verify the DB source of this attribute**
      "activeDate": "1995-01-01",
      "retireDate": "2015-08-24",
      "nonLoadBasedIndicator": 1,
      "id": "5",
      "unitRecordId": 3, **<-- Need to verify the DB source of this attribute**
      "name": "CS0AAN", **<-- Need to verify the DB source of this attribute**
      "type": "stack",
      "active": true,
      ...
    }
]

For the monitor-plan-mgmt/locations/{locId} (and workspace version) endpoints perform the verification of Location data noted above

**Comment by vishnunavuluri** [comment]
Reference Tech Team Tasks:
[#2623](https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/us-epa-camd/easey-ui/2623)
[#2653](https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/us-epa-camd/easey-ui/2653)
[#2624](https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/us-epa-camd/easey-ui/2624)
[#2620](https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/us-epa-camd/easey-ui/2620)

**Comment by sanleyCVP** [comment]
After review of the current setup:
The unit-stack-configuration DTO will be updated to include unitName and populate the stackName attribute as indicated in the ticket

The monitor-location will be kept as is, since it's already loading the stackName and unitName under the name attribute, and the current DTO expects unitId and stackPipeId to be the actual names. DTO  validations will not be impacted under this setup

Update ticket #2701 and review IMPORT Checks related to unitStackCOnfigurations only

**Comment by mosesdeeCVP** [comment]
![2719 Update Plans & Configurations API endpoints - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04931e28-f323-4da8-9a57-9a94d07363b4)

**Comment by mosesdeeCVP** [comment]
Test Case [TC633](https://epacamd.testquality.com/project/11428/plan/22772/test/329917)
Test Passed
