### ISSUE TITLE
Outage Message - ECMPS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2720]
As an ECMPS beta user, I want to be informed when there is a system outage in ECMPS so that I understand that the functionality is not available due to maintenance activities 

Acceptance Criteria:

Given I am an ECMPS user accessing the application
When there is a maintenance activity in progress (beta deployment etc)
Then I see an informational message on the screen

'The background color for the banner is Light Blue'

**Informational Message:**
Please be aware that ECMPS shall be unavailable due to a scheduled maintenance activity starting Friday, March 4th at 11:30 am to Sunday, March 6th 9:00 am

Notes:
- Add a outagewindow.json folder on the Home page (https://github.com/US-EPA-CAMD/easey-content/tree/master/dev/ecmps/home)
- USWDS Site Alert Component: https://designsystem.digital.gov/components/site-alert/

**Comment by mosesdeeCVP** [comment]
![2720 Outage Message - ECMPS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5670877d-2e7a-4fe0-b9d1-f48dafd83223)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC638](https://epacamd.testquality.com/project/11428/plan/19352/test/330220)
Test Passed
