### ISSUE TITLE
Export a Monitoring Plan

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2721]
As an ECMPS user, I want the ability to export a MP so I can download and review it offline

Acceptance Criteria:

Given I am a logged in ECMPS user
When I select and checkout a Configuration
And click on the Export MP button
Then I see a MP JSON download 

**Naming Convention for the file:**
MP Export - Facility Name, Configuration Name (Date).json
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e1a1970c-617d-474f-816a-d602641810f1)

Dev Notes: Meet with Datateers to see how to implement the download
https://github.com/US-EPA-CAMD/easey-campd-ui/blob/develop/src/components/customDataDownload/DownloadFileType/DownloadFileType.js

Review JSON for the following data:
Defaults 
Formula
Load 
Location Attribute and Relationships 
Method 
Qualifications
Rectangular Duct WAFs
Span
System
Analyzer Ranges
System Component
System Fuel Flow
Unit Information

**Comment by mosesdeeCVP** [comment]
Naming Convention for the file:
MP Export - Facility Name, Configuration Name (Date).json

My Download:
MP Export - Astoria Generating Station, 20 (3-4-2022).json

**Comment by mosesdeeCVP** [comment]
Test Case: [TC620](https://epacamd.testquality.com/project/11428/plan/22924/test/329181)

**Comment by mosesdeeCVP** [comment]
Test Passed
