### ISSUE TITLE
Unable to View Relationship Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2725]
Steps to Reproduce:

**In Global View:**
Select a Facility, Open a Configuration for the Facility
Select 'Location Attributes and Relationships' from the Sections dropdown and click on it
The system throws an Unhandled Rejection Error

**In Workspace:** 
Select a Facility, Open, and Checkout a Configuration for the Facility
Select 'Location Attributes and Relationships' from the Sections dropdown and click on it
The system throws an Unhandled Rejection Error

**Comment by mosesdeeCVP** [comment]
Test Case: [TC510](https://epacamd.testquality.com/project/11428/plan/22772/test/316518)
Test Passed
