### ISSUE TITLE
Unable to Create System Component

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2727]
Steps to Reproduce:

In Workspace:
Select a Facility, Open, and Checkout a Configuration for the Facility
Select 'Systems' from the Sections dropdown and click on it
On any of the available rows, Click View/Edit
Locate and click on Add Component
Once you fill out all the required fields, click Add New Component

You will see that the new component is not created and the system displays the following error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ac07ce04-e33c-4093-a960-7aa0f928b2f2)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC357](https://epacamd.testquality.com/project/11428/plan/19812/test/299666)
Test Passed
