### ISSUE TITLE
Tab Order Incorrect - Configurations Tab

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2728]
Location: Monitoring Plans > Workspace > Individual Configurations Tab (Barry 4 etc)

Issue: Tab order of the filter elements above the data table does not follow a logical order.  At a minimum, the Locations and Sections elements should immediately precede the table section elements. 

Steps to reproduce:
In Workspace:

Open and checkout a configuration
Tab through all available options. You will see that the tab order is reversed for Import Export, Revert and Evaluate buttons

- Make sure the order is Location, Sections, Import, Export, Revert and Evaluate before the focus goes to the data table

**Comment by mosesdeeCVP** [comment]
Test Case: [TC639](https://epacamd.testquality.com/project/11428/plan/19352/test/330313)

**Comment by mosesdeeCVP** [comment]
Test Passed
