### ISSUE TITLE
Make Design Revisions to the CAMPD Data Home Page - Due 4/6

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2745]
## Context

Per product design meeting on 3/7, the Datateers PO discussed wanting to revise the design of the CAMPD Data home page. The PO would like to see the page laid out differently than just three blocks of text.   
Below, I have provided links to the data home page wireframes and the data home page on CAMPD.

Data Home Wireframes: https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A152&scaling=min-zoom&page-id=1%3A146

CAMPD Data Home Page: https://campd-dev.app.cloud.gov/data

Feedback back from Product Design on 3/14: 
PO likes the icons on the page . Like icons that are consistent with the home page 
concerned that the design may be too similar to the campd home page 
would like the text to be horizonal 
remove the image from the data home page 
provide other ways to organize the text content in the call out box

**Comment by NadiaJL** [comment]
@JanellC, @AllisonFrancis, & @tlageman-epa 
Here is a first draft for the Design Revisions to the CAMPD Data Home Page. There are 4 slightly different versions for consideration. i.e. images and icons.
CAMPD-EPA-Data Homepage - Desktop 1024

Figma interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1%3A146&node-id=3241%3A17854&viewport=294%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3241%3A17854

Figma file / dev inspect
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3241%3A17854

**Comment by JanellC** [comment]
@tlageman-epa Based on the discussion during the Product Design session on 3/ 14, Nadia ( @NJLCVP ) created more design options for the Data Home page. Please see the link below and let us know your feedback. 

https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3241%3A17854

Figma interactive prototype - web view:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1%3A146&node-id=3241%3A17854&viewport=294%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3241%3A17854

**Comment by tlageman-epa** [comment]
@JanellC  @NJLCVP  Thanks for the update. These are looking closer. We are more interested in something without a banner image (e.g., 4th and 7th examples starting from left). A couple other thoughts:

- I made some edits to the text/buttons in the content document. Can we replace the designs (#4 and 7) with that text so we get a better understanding of how it would display?
- Can we try #4 with cards for each data section like you did for 7?
- Can we try the above, but remove the blue box and just have title/text above the cards for each section?

Let me know if you have any questions. thx!

**Comment by NadiaJL** [comment]
@tlageman-epa - thank you for your feedback. I will make the requested changes and try to get something back to you for review by EOD tomorrow 3/17.

**Comment by NadiaJL** [comment]
@JanellC & @tlageman-epa 
Here are the updated Design Revisions to the CAMPD Data Home Page with the requested edits/redesign from 3/16/22.
There are 4 different layouts to choose from and any of these designs can be mixed and matched/edited as well. The layouts include the Page into text within a card and without.

Figma interactive prototype - desktop 1024
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1%[…]C48%2C0.1&scaling=min-zoom&starting-point-node-id=3270%3A17455

Figma file/dev inspect - As an FYI @tlageman-epa you may leave comments on this Figma file by selecting the comments icon from the actions menu (see screenshot for reference )
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146

![Screen Shot 2022-03-17 at 11.58.38 AM.png](https://images.zenhubusercontent.com/620142521e8674037a915879/8399a8b1-834a-47ce-809e-e3c5b55ef0db)

**Comment by NadiaJL** [comment]
@JanellC & @tlageman-epa here are the updated CAMPD-EPA-Data Homepage - Desktop 1024 WFs, with e requested edits from PD review today, 3/21/22.

Figma interactive prototype
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1%3A146&node-id=3341%3A18310&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3341%3A18310

Figma design file/dev inspect
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3341%3A18310

**Comment by JanellC** [comment]
Per PI planning we will be perusing the design option below. Will need the wireframes at all breakpoints @NadiaJL @AllisonFrancis 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/226e5a16-4a91-42c4-be41-87e8078e6deb)

**Comment by AllisonFrancis** [comment]
@JanellC @NadiaJL 
Here is the link to the Figma screens for Data breaking points 
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146
Let me know if you have any questions.

**Comment by NadiaJL** [comment]
Thanks Allison!

From: AllisonFrancis ***@***.***>
Date: Tuesday, March 29, 2022 at 8:28 PM
To: US-EPA-CAMD/easey-ui ***@***.***>
Cc: Nadia Lee ***@***.***>, Mention ***@***.***>
Subject: Re: [US-EPA-CAMD/easey-ui] Make Design Revisions to the CAMPD Data Home Page - Due 4/6 (Issue #2745)
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@JanellC<https://github.com/JanellC> @NadiaJL<https://github.com/NadiaJL>
Here is the link to the Figma screens for Data breaking points
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146
Let me know if you have any questions.
