### ISSUE TITLE
Spike: Improve ECMPS Performance Metrics

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2748]
As an ECMPS user, I want the transaction response timings in ECMPS to be optimal so that the performance is good

Acceptance Criteria:

Given I am an ECMPS performance tester
When I execute transactions in ECMPS including but not limited to Login; Checkout a Facility; Open a Configuration Tab etc
Then I see that the transaction response time is below 1 second

Areas to focus:
- S01_ECMPS_GMP_05_ClickOnFacilityTab
- S01_ECMPS_GMP_06_SelectSections
- S02_ECMPS_RMP_06_Tab
- S02_ECMPS_RMP_10_Saveclose

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9900bb77-41c9-491e-a041-17fa60c04941)

**Comment by vishnunavuluri** [comment]
Performance Test Report:
[https://app.zenhub.com/files/287570343/df41631b-b830-44be-85c6-f04eeb0bd1b1/download](https://app.zenhub.com/files/287570343/df41631b-b830-44be-85c6-f04eeb0bd1b1/download)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/b6eccfcd-52d7-4cad-9559-5628e884a877)
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/61120174-2e35-4ed0-9258-7a6d0d5051d2)
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/2b7ca567-33a1-4340-9043-54a1d6498f8c)

**Comment by Qb10** [comment]
concluded with Tech team that there are errors happening that causes the long time in the performance metrics. Can possibly be resolved once auth api is configured
