### ISSUE TITLE
508: Revise text on ECMPS Home Screen

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2749]
Do not use "here" as link text. Link text should describe the purpose of the link.

Expected: Update 'Draft beta monitoring plan instructions can be found here.' to Review draft beta monitoring plan reporting instructions for more information
- Also, hyperlink draft beta monitoring plan reporting instructions in the updated text. That should navigate the user to the Reporting Instructions screen

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/537d05d0-4708-4e62-9ae6-e3be9c34ba6a)

**Comment by aprematta** [comment]
Link and text has been updated to be fully 508 compliant
