### ISSUE TITLE
508: Uniquely identify 'Click to close' for Configuration tabs 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2752]
As configurations tabs are added, the Close elements are not uniquely identified ("Open Barry 4 tab" vs "Click to close tab")

Update to 'Click to close _________'(e.g., Click to close Barry 4)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/bf2fef38-5877-4722-b27c-55991b4df718)

**Comment by aprematta** [comment]
Issue has been fixed, closing ticket
