### ISSUE TITLE
Update Design System/Documentation (Due: 3/30/2022)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2757]
Update Design System/ any documentation with updates at the end of I & P Sprint

I & P Start and End Date: 3/16/2022 - 3/30/2022

**Comment by NadiaJL** [comment]
Finished 
EASEY Design System - Zeroheight
https://cvpcorp.zeroheight.com/styleguide/s/59398/p/81a343-easey-design-system

Figma Design / Dev inspect file
https://www.figma.com/file/jLPVDOcuSlfeo85nD6ZJwv/EASEY-Design-System?node-id=318%3A82

ECMPS-DESIGN ASSETS - Shared Xd Doc
https://xd.adobe.com/view/28ee8c47-fbcd-42c7-96de-c9ab2efd7e13-7dbd/
