### ISSUE TITLE
Determine how to update span indicator in the Component_type_code table

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2766]
- Provide Documentation on how to update span indicator in the Component_type_code table for following record 
component_type_cd  component_type_cd_description  span_indicator parameter_cd
"HF" |HF| Concentration Analyzer" |1|"HFC"

**Comment by sanleyCVP** [comment]
ERG discussed this Item with Chris and the CAMD ECMPS group and they indicated that the “HF” Component Type Code record should have a null Span Indicator.

The plan is to update CAMDBSP and CAMDBSS this week as well as our Development Database.

**Comment by jwhitehead77** [comment]
this has been updated in the NCC Oracle systems and cloud.gov env
