### ISSUE TITLE
Spike: Research enhancing search and adding filters to bulk data files 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2768]
## Context 

During backlog refinement on 3/9, the team discussed potentilly enhancing the search and adding additional filters to the the bulk data files page. As apart of the scope of this ticket 
 

- [ ] Research enhancing the search functionality. ex. ( If a user types "emissions pa" into the search bar, then system will return emissions files related to the state PA) 

- [ ] Research how complex it would be to add additional filters to filter the files on the bulk data files functionality (ex. adding a state filter)

**Comment by AbuFofanah** [comment]
For the search functionality, we decided to use filters, and keep the search itself simple.  Given that the items we are making filters for are received from the API in a consistent format, it will be simple to add additional filters.
