### ISSUE TITLE
Update CAMPD Data Home page

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2796]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to view the Data Home Page So that I can view the different ways to obtain data 

## Acceptance Criteria
Given that a user has accessed the data home page 
When the functionality is displayed 
Then the content is consistent with the[ content document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B1680B428-F051-43F5-91B6-6707EC2363F6%7D&file=1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true) 
AND the page renders in accordance with the[ wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146)

### Development Notes
Link to CAM API Portal: https://www.epa.gov/airmarkets/cam-api-portal
Link to the CAM API portal should open in a new tab 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [x] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[ wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1%3A146)

[Data Home Page Content Document ](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B1680B428-F051-43F5-91B6-6707EC2363F6%7D&file=1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&action=default&mobileredirect=true)

## Testing
Test Case: [TC673](https://epacamd.testquality.com/project/11428/plan/23473/test/352394)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
@JanellC  @addisgmichael this looks good, but noticed the Tutorials link doesn't have an underline which makes it hard to see it is a hyperlink. not sure if this needs to be fixed before it's closed or can be done after in the content repo. thx

**Comment by addisgmichael** [comment]
@tlageman-epa this update is merged and now available on dev.

**Comment by JanellC** [comment]
TC673 passed @tlageman-epa 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/010558ef-73a8-4600-aae2-5670fcd4ef2e)

This ticket is ready for 508 testing @aprematta
