### ISSUE TITLE
Update Filter Criteria for Component Data

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2797]
ERG created the table below to match the component group it Table 17 of the MP Reporting Instructions with the applicable component type codes and “Component Type and Basis to Sample Acquisition Method” crosscheck entries.

The table notes explain why two entries exist for “TANK” in the “Component Type and Basis to Sample Acquisition Method” crosscheck.  Essentially the two entries allow for “TANK” component records with either a null or “O” sample acquisition method code.  So both “TANK” rows are correct.

 ![image.png](https://images.zenhubusercontent.com/6143891f8447a5585788734a/bca05620-e1dd-41c7-97b2-959cc6f9d9ff)

Notes:

1. This component exists in the “Component Type and Basis to Sample Acquisition Method” crosscheck with an acquisition code but is not listed in MP RI Table 17 (“Sample Acquisition Method Codes for Components”) based on the component mapping in check COMPON-13.
2. “GFM” and “TANK” are Generic Component Types in the “Component Type and Basis to Sample Acquisition Method” crosscheck but are not actual component type codes and are not translated in COMPON-13.  I believe that the crosscheck entries are not currently used.
3. The “Component Type and Basis to Sample Acquisition Method” crosscheck entries with an empty (null) Sample Acquisition Method are used to indicate that the components are allowed to have null sample acquisition methods.
3a. “TANK” has an empty entry and one for “O”, which indicates that the source can report “TANKS” with a null or “O” sample acquisition code.
3b. “CALR”, “DP”, “FLC”, “GCH”, “MS”, “PRES” and “TEMP”, which are in the “Fuel Flowmeter Types” group, can also have a null sample acquisition code.
3c. “PRB”, which is in the “CEMS” group, can also have a null sample acquisition code.
3d. A null sample acquisition code is required for “DL” and “PLC”.

**Comment by sanleyCVP** [comment]
Updated the view to account for all possible options to display based on ERGs feedback. Attached is the latest version of the filtering master list for testing [https://app.zenhub.com/files/287570343/bac24ecc-afdf-4b3d-8831-63f6650e6c59/download](https://app.zenhub.com/files/287570343/bac24ecc-afdf-4b3d-8831-63f6650e6c59/download)

When testing against ECMPS UI, ensure that the values that allow for null do have a blank option in the drop down list

**Comment by jwhitehead77** [comment]
data has been corrected but I do not see where the reporting instructions have been updated with this information
