### ISSUE TITLE
Bulk Data Files Data Table- 508 Issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2798]
## Context 

Testing complete for 2695, couple issues found:
1.	The current aria label for the checkboxes in the first column just refer to the row number.....for example aria-label="select-row-26" ..... this should reference the file name. for the select/ deselect functionality the aria label could be "select/ deselect all file names"
2.	The data table lacks a programatic name, add an aria label on the div that contains role=table
3.	The state of the sort order is not programatically identified (ascending/descending)
4.	Table headers are not associated to data cells because they are coded with the role of 'gridcell' instead of 'cell'

**Comment by aprematta** [comment]
Looks like 3 of the 4 issues are fixed. Aria labels were adjusted for checkboxes, sort order is now programatically conveyed, and table cells have the role of cell. However ANDI is still saying the table has no programatic name. Looks like it has the aria labelled by of "data-table-title" but there is no element that has that id.

**Comment by aprematta** [comment]
Last issue has been resolved, closing ticket
