### ISSUE TITLE
Spike: Research instances where an informational alert will need to be displayed on CAMPD 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2800]
## Context 

Research where an error may occur on CAMPD and cause the need for an informational alert 

Identified Instances: 
- An error occurs with the EASEY content management system 

- Json files are edited improperly (missing comma, missing quotation mark) 
- want the message to give the user the CAMD support email/ phone number or direct the user to the contact us page 

https://easey-dev.app.cloud.gov/ecmps

https://designsystem.digital.gov/components/site-alert/

**Comment by junie-stigdon** [comment]
https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/4-Development/CAMPD%20Downtime%20Errors%20-%20EPA%20CAMD%20-%20v1.0.xlsx?d=w33677c82cd214de2b3ea7fce5907452a&csf=1&web=1&e=v1eNbT

**Comment by junie-stigdon** [comment]
Will discuss with product owners on 4/7/22
