### ISSUE TITLE
Determine a Location and Create Skeleton for CAMD Runbook 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2803]
Skeleton/Table of Contents:

- [ ] API Gateway
- Configuration
- Troubleshooting

- [ ] CORS Policy Administration
- Adding/Removing CORS policy
- Troubleshooting
- [x] Data Migration
- Change data capture
-  Job timing
-  Troubleshooting
- [ ] Quartz Job Scheduler
-  Bulk data files
- Check engine
-  Troubleshooting
- [ ] Cloud.gov
- Managing app resources (memory, instances)
- Databases
- S3 Buckets ** 
- Troubleshooting
- [ ] CI/CD Pipeline
- Operation
- Secrets
- Troubleshooting
- [x] Content Authoring**
- Editing content **
- "Deploying" content **
- Troubleshooting**

**Location: **
Requirements
- [ ] Create Private Easey-Documents Repository

**Comment by JorjaComer** [comment]
@MaeganWood64 Please send out link to runbook to Tech Team meeting invitees
