### ISSUE TITLE
Issue with Configurations Check Out

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2804]
**Issue:**

When a user checks out a Configuration, checks it back in -> looks like the Configuration is checked back in. However, when the user logout and logs in again, they see that the respective Configuration is still checked out to them.

Other user see that the Configuration is checked out

**Steps to Reproduce:**
- Login to ECMPS
- On the Select Configurations page, pick any Configuration and check it out
- Navigate to the Configuration tab that you just opened and Checked out
- Check it back in (with or without updates)
- Make sure that the Configuration is checked back in

- Logout of ECMPS
- Log into ECMPS
- Navigate to Select Configurations page
You will see that the Configuration you checked back in earlier is still checked out to you

**Comment by mosesdeeCVP** [comment]
Bug fixed
