### ISSUE TITLE
CAMPD 508 Testing PI-8

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2807]
## Epic Benefit
Issues that require 508 testing in PI 8   @aprematta 

## Context

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
Testing complete for 2698, 2696. Tested entire bulk data download page, found multiple issues:
1. There is no visual focus indicator (box) on the select all files checkbox (others have them)... it is getting keyboard focus.
2. Files Selected, Size text and values need to be in an aria live region so they are announced when updated
3. When clear all is activated, focus should be put back on the data type dropdown
4. "There are no records to display" needs to be in an aria live region so it is announced when filters are updated
5. There should be text or a tooltip saying that certain filter selections will display new filter options
6. Couldn't test the file selection limit of 50GB message.... make sure that is also in an aria live region
7. Filters disappear at 150% zoom

**Comment by aprematta** [comment]
Testing complete for 2697, the code of the hidden label and actual search input matches that of the search in the popup menu. To remedy, change the for and id attributes of the new search label/input so they are different from the one in the menu. I would also suggest changing the hidden label to be different, perhaps 'Search Bulk Data Files Table'

**Comment by aprematta** [comment]
No issues found with 2809

**Comment by aprematta** [comment]
Testing complete for 2835....... none of the new functionality is keyboard accessible. This will need to be added then reviewed again fully for 508 compliance. Unable to do any screen reader testing until keyboard accessibility is implemented.

**Comment by aprematta** [comment]
Testing complete for 2796..... 2 issues found:
1. The icons next to Data and Maps & Graphs in the main content can be considered decorative. Currently they have repetitive alt text alt="Data Icon" for example. Change both to the empty alt tag alt=""
2. The Data and Maps & Graphs content in the main section are now each contained in a layout table but their is data table markup. Either remove the layout tables and position in some other method, or add a role of "Presentation" to the table tag and change all TH cells to TD.

**Comment by aprematta** [comment]
No issues found for 3364

**Comment by aprematta** [comment]
Testing again for 2796.... only issue is the 3 icons next to the headings are decorative so they should have the empty alt tag "" instead of current: img src="/images/icons/cdd-icon.svg" alt="Custom Data Download Tool Icon"

**Comment by aprematta** [comment]
Testing complete for 3435, no issues found

**Comment by aprematta** [comment]
Testing complete for 2758, couple of issues found:
1. Tab order is incorrect, the tooltip for select all files comes before the Keyword search text box and search button. Need to adjust the order in the dom to put the search functionality above the tooltip.
2. When the filters button is selected, there is no focus shift. It needs to be put on the first focusable item in the filters window.
3. When the filters window is active, there is no keyboard trap, I should not be able to get to the other items on the web page until the window is dismissed.
4. When I hit the back or preview data buttons, focus is not shifted, it should be placed back on the filters button

**Comment by aprematta** [comment]
No issues found on 3405

**Comment by JanellC** [comment]
Testing complete for 3355, ANDI is indicating that there is an ARIA Hidden = True when the modal is active, hiding it from a screen reader. Looking at the code, I think it's this from the HTML:
div id="root" aria-hidden="true" data-modal-hidden=""

**Comment by aprematta** [comment]
Testing complete for 3356, no issues found

**Comment by aprematta** [comment]
Testing complete for 3357, no issues found

**Comment by aprematta** [comment]
Testing complete for 3420, same issue as the desktop view https://github.com/us-epa-camd/easey-ui/issues/3553

**Comment by JanellC** [comment]
Closing epic. Another 508 epic will be opened by @MaeganWood64 for PI 9
