### ISSUE TITLE
QA & Cert UI Design 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2811]

**Comment by NadiaJL** [comment]
EPA-ECMPS-QA Linearity WFs
Shared Xd Doc Link: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

ECMPS-QA Linearity - Workspace - side menu ex.
Shared Xd Doc Link:  https://xd.adobe.com/view/b0c830db-8df5-4c66-9e5c-52775350f7fe-e59b/
