### ISSUE TITLE
QA & Cert - Update Left-Hand Menu

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2820]
As an ECMPS user, I want the left-hand menu for the application to be updated with additional options so that I can access the new QA & Certification Data module

Acceptance Criteria:

Given I access ECMPS 
When I navigate to the left-hand menu
Then I see the available options updated according to the prototype provided (both the Global-View and the Workspace)

Note: The 3 options available under QA & Certifications are expanded by default and remain so at all times

Prototype for Reference (Use screen 3 of 14):
https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

**Comment by mosesdeeCVP** [comment]
Test Case:
[TC667](https://epacamd.testquality.com/project/11428/plan/24660/test/337203)

**Comment by mosesdeeCVP** [comment]
![2820 QA & Cert - Update Left-Hand Menu - Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8260d4cd-37ed-4b90-bee6-b9aa6b682031)

**Comment by mosesdeeCVP** [comment]
![2820 QA & Cert - Update Left-Hand Menu - Logged Out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6107f33d-a1fc-4342-b128-9b0a8fd2bcf7)

**Comment by mosesdeeCVP** [comment]
Test Passed
