### ISSUE TITLE
Add Select Configurations Screen

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2821]
As an ECMPS user, I want the ability to select a Facility from a list so that I can access QA & Certification data for it

Acceptance Criteria:

Given an ECMPS user accesses the left-hand menu
When they click on Test Summary Data under the QA & Certifications section
Then they can see the Select Configurations screen
And are able to see a list of Facilities

Given a user is on the Select Configurations screen
When the data is displayed
Then the user can see information on the Facility, Oris Code and State

Given a user chooses to search/filter
When the filter criteria is entered
Then the user may filter the facility data by ORIS Code, Facility Name, or State

Note:
- The Select Configurations screen will display the list of Facilities and all applicable Configurations under the Facilities (Similar to MP's Select Configurations screen)
- Users shall have the option to Open a Configuration. No Checkout functionality for QA & Certification data

Prototype: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/ (Screens 1, 2 of 14)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC709](https://epacamd.testquality.com/project/11428/plan/24660/test/367245)

**Comment by mosesdeeCVP** [comment]
![2821 Add Select Configurations Screen - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e943655-de3c-4b17-bef5-a5ff5e7f80f1)

![2821 Add Select Configurations Screen - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7b1e0171-f85d-4890-9dd6-5ec72ccd93ee)

![2821 Add Select Configurations Screen - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fa3581bf-d687-4356-bb84-2e4684dd2621)

**Comment by mosesdeeCVP** [comment]
Test Passed
