### ISSUE TITLE
Layout for Individual Configurations Tab

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2823]
As an ECMPS user, I want a separate screen for the individual Configurations selected so that I can review and update QA & Cert data for it

Acceptance Criteria:

Given I am an ECMPS user on the Select Configurations screen
When I open a Configuration tab
Then I see that the layout of the tab matches that in the prototype provided below 

Note: Import Test Data option is not available/not needed for Global-view

Prototype for Reference (Use screens 3, 4 of 14):
https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

**Comment by mosesdeeCVP** [comment]
![2823 Layout for Individual Configurations Tab- Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f1c225fb-4b08-4838-92a9-4d8d121a4e6e)

**Comment by mosesdeeCVP** [comment]
![2823 Layout for Individual Configurations Tab - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dd68a61b-8b18-4d14-b03c-5f54ddecfc81)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC727](https://epacamd.testquality.com/project/11428/plan/24660/test/367992)

**Comment by mosesdeeCVP** [comment]
Test Passed
