### ISSUE TITLE
Global & Workspace View: View Linearity Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2824]
## User Story
As an ECMPS user, I want a new QA - Linearity Summary Data section so that I can reference it when making updates

## Acceptance Criteria
Given a user selects **Linearity Summary** from the Test Type dropdown (Login for the Workspace)
When the Linearity Summary Data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Gas Level Code
Mean Measured Value
Mean Reference Value 
Percent Error 
APS Indicator

Given a user is viewing Linearity Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

Note: For the Global-view, it shall be a read-only version without the ability to edit or create
For the Workspace, the user shall have the ability to View and Edit Linearity Summary Data

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

Reporting Instructions (Page 32): https://ecmps.camdsupport.com/documents/ECMPS%20QA%20Reporting%20Instructions%202021%20Q4.pdf
Invision Board URL: https://projects.invisionapp.com/freehand/document/TdahPfbEb
**Reference Screenshots available in the comments section**

## Testing 
Test Case: [TC797 ](https://epacamd.testquality.com/project/11428/plan/25475/test/378332)
Tester: @JanellC

**Comment by NadiaJL** [comment]
ECMPS-QA Linearity - Desktop large - 1024 V3.0
Xd prototype: https://xd.adobe.com/view/40aa3540-d85f-4b68-9bf2-63f694bee243-15f9/screen/131433a5-8f5c-4d99-83ae-9cf7855a635d/

![QA Linearity - QA & Certification - QA-Cert test data - Location - Test type - Linearity - Test Summary Data - Desktop 1024 V2.1 – 3.png](https://images.zenhubusercontent.com/620142521e8674037a915879/32ae5b14-189b-42ce-b592-41d46bbb294f)

**Comment by JanellC** [comment]
TC797 passed 

Global 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f5490327-9638-42a3-9b01-e36465530b49)

Workspace 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3e8201b4-3fb1-4fb5-9951-db8531f51690)
