### ISSUE TITLE
Update custom data download to use proper filter logic endpoints

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2832]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the emissions sub type to utilize the emissions filter logic endpoint So that I can build a query 

## Acceptance Criteria
Given that a user made a GET request to the emissions filter logic endpoint 
When the request is executed 
Then the system returns the following data elements: 
year 
programcode 
facilityid 
statecode
unittypecode
fueltypecode
controlcode

Given that a user has applied an emissions sub type on the cdd
When the functionality is displayed
Then the user is required to apply filter criteria for time period first
AND the optional filters are greyed out until tine period criteria is applied

Given that a user has selected an emissions sub type on the cdd
When filter criteria is applied for time period 
Then the system displays a spinner until the filter logic is engaged

Given that the filter logic is engaged
When filter panel functionality is displayed
Then non applicable selections are removed from the combo box
AND grayed out from the check list

Given that the filter logic is engaged
When filter criteria is applied
Then the optional filters are narrowed based on the applied criteria

Given that the filter logic is engaged
When any filter criteria is removed (ex filter tags, filters)
Then the filters are narrowed based on the applied criteria

Given that a user has selected a time period where data is not available (dev environment)
When the time period criteria is applied
Then the system will display the following message: "Data is not available for the selected time period. Enter a new time period"
And require the user to apply a new time period

Given that the filter logic is engaged
When new filter criteria is applied for year
Then the system will display the warning message: Changing the year will clear out previously selected criteria. Do you want to proceed?
AND if the user choses to proceed then all previously selected criteria are cleared
AND the time period is updated

Given that the filter logic is engaged
When new filter criteria is applied for year
Then the system will display the warning message: Changing the year will clear out previously selected criteria. Do you want to proceed?
AND if the user choses to cancel then all previously selected criteria are maintained

Given that the filter logic is engaged
When new filter criteria is applied for the month, day, or quarter
Then all previously selected criteria are maintained

Given that the filter logic is engaged
When the time period filter tag is cleared
Then the system will display the warning message: Removing time period will clear out previously selected criteria. Do you want to proceed?
AND if the user choses to proceed then all previously selected criteria are cleared
and all the optional filters are greyed out until time period criteria is applied

Given that the filer logic is engaged
When the the checklist functionality is displayed
Then the user can not select or apply filter criteria for greyed out items

Given that the filter logic is engaged
When the "select all" functionality is selected on the checklist component
Then the system selects criteria that is not greyed out

Given that the filter logic is engaged
When the checklist functionality is displayed
Then the select all functionality is disabled for groupings that only contain greyed out criteria

### Development Notes
- Update ALL emissions sub types on the CDD to use the correct endpoint
- Conduct regression testing on all emissions sub types on the CDD 
- The Facility Unit Attributes should use the applicable/attributes in the Facilities API
- The Apportioned Emissions (hourly, daily, monthly, quarterly, annual, ozone) should use the applicable/attributes in the Emissions API
- The MATS Apportioned Emissions should use the mats/applicable/attributes in the Emissions API
- Also the filter logic on the MATS needs to change to be just like the Apportioned Emissions to filter by year instead of date

Change from using facilities-mgmt/facilities/attributes/applicable to emissions-mgmt/emissions/apportioned/attributes/applicable

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
- Current Emissions is using the facilities/attributes-applicible 
 Needs to change to use the Emissions/attributes-applicable endpoint

- Ensure that the emissions and facility attributes are performant to one another 

## Testing
Test Case: [TC899](https://epacamd.testquality.com/project/11428/plan/26079/test/375941)
Tester: Maegan Wood

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
Currently, the emissions data type on the cdd is hooked up to the filter logic endpoint in facilities API. This ticket is to ensure that the emissions data type on the cdd utilizes the filter logic endpoint in the Emissions API.  If the functionality in this ticket is not implemented, then the filter logic endpoint in the Emissions API will not be utilized anywhere in the CAMPD application.

**Comment by MaeganWood64** [comment]
@tlageman-epa TC899 Passed
