### ISSUE TITLE
Determine entities for data service 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#287]
- [x] Determine how many entities are needed

- [x] List of each fields in each entity identified

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/84745094-9a9d-4872-975f-573d86a6558b/download](https://app.zenhub.com/files/287570343/84745094-9a9d-4872-975f-573d86a6558b/download)

**Comment by SimeraHailu** [comment]
Next step:
1) Meet with team to discuss Identified Entities and Sub queries 
2) Create Entities  Models
