### ISSUE TITLE
Remove Calibration Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2897]
As an ECMPS user, I want the ability to remove Calibration Injection Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Calibration Injection data section
When I click on the 'Remove' option for Calibration Injection
Then I see that the relevant Calibration Injection data record is deleted

Given I chose to remove Calibration Injection Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Calibration Injection data section
When I select Cancel
Then I am returned to the landing screen for Calibration Injection Data

Reference Invision Board URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1069](https://epacamd.testquality.com/project/11428/plan/27529/test/406775)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
