### ISSUE TITLE
Global 'View' and Workspace 'Add': Calibration Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2900]
As an ECMPS user, I want to view Calibration Injection Data in the Global-View and add new Calibration Injection Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Calibration Injection from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Online Offline Indicator
Upscale Gas Level Code
Zero Injection Date 
Zero Injection Hour
Zero Injection Minute
Upscale Injection Date
Upscale Injection Hour
Upscale Injection Minute
Zero Measured Value 
Upscale Measured Value 
Zero APS Indicator
Upscale APS Indicator
Zero Calibration Error
Upscale Calibration Error 
Zero Reference Value 
Upscale Reference Value 

Given a user is viewing Calibration Injection Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Calibration Injection from the Test Type Group dropdown
When the user clicks on 'Add' for Calibration Injection Data
Then the system displays a modal
and the user can add new data for:

Online Offline Indicator (radio button)
Upscale Gas Level Code (Dropdown)
Zero Injection Date (Text & Datepicker)
Zero Injection Hour (Dropdown 1-23)
Zero Injection Minute (Dropdown 1-59)
Upscale Injection Date (Text & Datepicker)
Upscale Injection Hour (Dropdown 1-23)
Upscale Injection Minute (Dropdown 1-59)
Zero Measured Value (Text)
Upscale Measured Value (Text)
Zero APS Indicator (radio button)
Upscale APS Indicator (radio button)
Zero Calibration Error (Text)
Upscale Calibration Error (Text)
Zero Reference Value (Text)
Upscale Reference Value (Text)

Given the user has added Calibration Injection Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Calibration Injection Data record is reflected on the UI

Given the user has added a new Calibration Injection Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Calibration Injection data
And no updates are saved

Label on the UI: Calibration Injection

Reference Invision URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1071](https://epacamd.testquality.com/project/11428/plan/27529/test/406777)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Calibration Injection Data - View Official Table

![Calibration Injection Data - View Official Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aac78735-a955-4f61-a38f-cd88ac64acb1)

**Comment by mosesdeeCVP** [comment]
Calibration Injection Data - View Official Modal

![Calibration Injection Data - View Official Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f428de05-1d8f-4888-9eb0-c6f142173b83)

**Comment by mosesdeeCVP** [comment]
Test Passed
