### ISSUE TITLE
API Endpoint - Add Calibration Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2902]
Add an API Endpoint to create/add Calibration Injection Data

Testing Reference Only:
Online Offline Indicator (radio button)
Upscale Gas Level Code (Dropdown )
Zero Injection Date (Text & Datepicker)
Zero Injection Hour (Dropdown 1-23)
Zero Injection Minute (Dropdown 1-59)
Upscale Injection Date (Text & Datepicker)
Upscale Injection Hour (Dropdown 1-23)
Upscale Injection Minute (Dropdown 1-59)
Zero Measured Value (Text)
Upscale Measured Value (Text)
Zero APS Indicator (radio button)
Upscale APS Indicator (radio button)
Zero Calibration Error (Text)
Upscale Calibration Error (Text)
Zero Reference Value (Text)
Upscale Reference Value  (Text)

**Comment by mosesdeeCVP** [comment]
![Calibration Injection - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4ff80884-fce3-497c-b1d8-de81e3cf75a0)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1007](https://epacamd.testquality.com/project/11428/plan/27529/test/400559)
Test Passed
