### ISSUE TITLE
Create MDM Endpoint for Test Claim Code (Test Qualification Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2903]
Create MDM Endpoint for Test Claim Code (Test Qualification Data)

Testing Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9f97c9fa-9698-4018-9930-2c8672873e94)

## Testing 
Test Case: [TC937](https://epacamd.testquality.com/project/11428/plan/26541/test/393890)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Test Claim Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/34929e52-c344-45cc-89f8-0d4921f5b206)
