### ISSUE TITLE
API Endpoint - View Flow To Load Reference Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2909]
Create GET endpoints (4) for Flow To Load Reference Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:

RATA Test Number (Text)
Operating Level Code (Dropdown)
Average Gross Unit Load (Text)
Average Reference Method Flow (Text)
Reference Flow Load Ratio (Text)
Average Hourly Heat Input Rate (Text)
Reference Gross Heat Rate (Text)
Calculated Separate Reference Indicator (Radio button)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC995](https://epacamd.testquality.com/project/11428/plan/27145/test/400295)
Test Passed

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference - View Official

![Flow To Load Reference - View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b996f4b4-85a1-4b7a-be04-8ac04517feac)

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference - View Official with ID

![Flow To Load Reference - View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8cd37495-ad08-4403-baff-b769f63d47f7)

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference - View workspace

![Flow To Load Reference - View workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/be541ae1-dda2-44f0-b434-403ac328aadd)

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference - View workspace with ID

![Flow To Load Reference - View workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/632370d3-8d4c-4d97-a3be-0f5a94de3a8a)
