### ISSUE TITLE
Remove Flow To Load Reference Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2911]
As an ECMPS user, I want the ability to remove Flow To Load Reference Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Flow To Load Reference data section
When I click on the 'Remove' option for Flow To Load Reference 
Then I see that the relevant Flow To Load Reference record is deleted

Given I chose to remove Flow To Load Reference Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Flow To Load Reference data section
When I select Cancel
Then I am returned to the landing screen for Flow To Load Reference Data

Invision Board:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case:[ TC1130](https://epacamd.testquality.com/project/11428/plan/28123/test/411336)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
