### ISSUE TITLE
Global 'View' and Workspace 'Add': Flow To Load Reference Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2913]
As an ECMPS user, I want to view Flow To Load Reference Data in the Global-View and add new Flow To Load Reference Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Flow To Load Reference from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

RATA Test Number (Dropdown)
Operating Level Code
Average Gross Unit Load 
Average Reference Method Flow
Reference Flow Load Ratio
Average Hourly Heat Input Rate
Reference Gross Heat Rate
Calculated Separate Reference Indicator 

Given a user is viewing Flow To Load Reference Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Flow To Load Reference from the Test Type Group dropdown
When the user clicks on 'Add' for Flow To Load Reference data
Then the system displays a modal
and the user can add new data for:

RATA Test Number (Dropdown)
Operating Level Code (Dropdown)
Average Gross Unit Load (Text)
Average Reference Method Flow (Text)
Reference Flow Load Ratio (Text)
Average Hourly Heat Input Rate (Text)
Reference Gross Heat Rate (Text)
Calculated Separate Reference Indicator (Dropdown - Blank, 1, 0)

Given the user has added Flow To Load Reference Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Flow To Load Reference Data record is reflected on the UI

Given the user has added a new Flow To Load Reference Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Flow To Load Reference 
And no updates are saved

**Label on the UI: Flow To Load Reference** 

Reference Invision URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference View Official UI
![Flow To Load Reference View Official UI.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e0d0c049-8e6c-4ada-b57b-16f3d3a73183)

**Comment by mosesdeeCVP** [comment]
Add Flow To Load Reference
![Add Flow To Load Reference.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aed7a052-5123-4599-90c2-60c722aceeba)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1143](https://epacamd.testquality.com/project/11428/plan/28123/test/412657)
Test Passed

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference View Official UI
![Flow To Load Reference View Official UI.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/23340cf1-06dd-4ae0-8f47-16bad34b8560)

**Comment by mosesdeeCVP** [comment]
Add Flow To Load Reference
![Add Flow To Load Reference.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a0164b9c-e099-41c8-bf09-f9418933b1e8)
