### ISSUE TITLE
Remove Flow To Load Check Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2918]
As an ECMPS user, I want the ability to remove Flow To Load Check Data so that I can update it as needed

Acceptance Criteria:
Given I am in the Flow To Load Check data section
When I click on the 'Remove' option for Flow To Load Check Data
Then I see that the relevant data record is deleted

Given I chose to remove Flow To Load Check Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Flow To Load Check Data section
When I select Cancel
Then I am returned to the landing screen for Flow To Load Check Data

Reference Invision Board:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2YjNlbTFpMDFhMDNiNnljajh6cWM2dw%3D%3D

## Testing 
Test Case: [TC1034](https://epacamd.testquality.com/project/11428/plan/27645/test/402378)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
