### ISSUE TITLE
Global 'View' and Workspace 'Add': Flow To Load Check Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2919]
As an ECMPS user, I want to view Flow To Load Check data in the Global-View and add new Flow To Load Check data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Flow To Load Check from the Test Type Group dropdown 
When the Flow To Load Check data is displayed 
Then the user can see the data displayed as a separate table (see list below for columns and order)

Test Basis Code (Dropdown)
Bias Adjusted Indicator (Dropdown with values of 1, 2) 
Average Absolute Percent Difference (Text)
Number of Hours (Text)
Number of Hours Excluded for Fuel (Text)
Number of Hours Excluded for Ramping (Text)
Number of Hours Excluded for Bypass (Text)
Number of Hours Excluded Pre RATA (Text)
Number of Hours Excluded Test (Text)
Number of Hours Excluded for Main and Bypass (Text)
Operating Level Code (Dropdown)

Given a user is viewing Flow To Load Check data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Flow To Load Check from the Test Type Group dropdown
When the user clicks on 'Add' for Flow To Load Check data
Then the system displays a modal
and the user can add new data for:

Test Basis Code (Dropdown)
Bias Adjusted Indicator (Dropdown with values of 1, 2 or Blank)
Average Absolute Percent Difference (Text)
Number of Hours (Text)
Number of Hours Excluded for Fuel (Text)
Number of Hours Excluded for Ramping (Text)
Number of Hours Excluded for Bypass (Text)
Number of Hours Excluded Pre RATA (Text)
Number of Hours Excluded Test (Text)
Number of Hours Excluded for Main and Bypass (Text)
Operating Level Code (Dropdown)

Given the user has added Flow To Load Check data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Flow To Load Check data record is reflected on the UI

Given the user has added new Flow To Load Check data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Flow To Load Check data
And no updates are saved

Note: Flow To Load Check layout is similar to that of Fuel Flow to Load Data where it is nested under Test Data 

Reference Invision URL: 
Global-view: https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w4M2oxbHg0MDBycjNiNnlkNWRrbHpzeA%3D%3D
Workspace: https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2YjNlbTFpMDFhMDNiNnljajh6cWM2dw%3D%3D

## Testing 
Test Case:[ TC1030](https://epacamd.testquality.com/project/11428/plan/27645/test/402374)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1030 passed 

View Modal In Global 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f9ebda5d-4b24-4536-934f-ac853b940eb8)


Add modal 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/27d97014-df01-4662-9258-a884fe280d07)
Workspace
