### ISSUE TITLE
Identify VM specs and VDI Pro Set Up for data migration tools

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#292]
- [x] VM specs are documented and shared with Mike/NCC 

- [x] Request for tools to be installed submitted

**Comment by jwhitehead77** [comment]
The AWS SCT and Ora2Pg tools have interactive GUI interfaces that could be very useful and would be easier to install & configure on a windows server. Mike and I have discussed setting up a 4 core, 16 GB RAM, 500 GB storage windows VM.

**Comment by jwhitehead77** [comment]
VM specs have been identified above, however, not sure that we would get admin privs to install so we are now going down the path of requesting that the AWS SCT tool be installed on the VDI Pro VM pool. Request has been made and instructions sent to NCC group.
