### ISSUE TITLE
API Endpoint - View Online Offline Calibration Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2922]
Create GET endpoints (4) for Online Offline Calibration Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:

Online Zero Reference Value (Text)
Online Upscale Reference Value (Text)
Offline Zero Reference Value (Text)
Offline Upscale Reference Value (Text)
Online Zero Measured Value (Text)
Online Upscale Measured Value (Text)
Offline Zero Measured Value (Text)
Offline Upscale Measured Value (Text)
Online Zero Calibration Error (Text)
Online Upscale Calibration Error (Text)
Offline Zero Calibration Error (Text)
Offline Upscale Calibration Error (Text)
Upscale Gas Level Code (Dropdown )
Online Zero APS Indicator (Dropdown)
Online Upscale APS Indicator (Dropdown)
Offline Zero APS Indicator (Dropdown)
Offline Upscale APS Indicator (Dropdown)
Online Zero Injection Date (Text+Datepicker)
Online Upscale Injection Date (Text+Datepicker)
Offline Zero Injection Date (Text+Datepicker)
Offline Upscale Injection Date (Text+Datepicker)
Online Zero Injection Hour (Dropdown 1-23)
Online Upscale Injection Hour (Dropdown 1-23)
Offline Zero Injection Hour (Dropdown 1-23)
Offline Upscale Injection Hour (Dropdown 1-23)

**Comment by mosesdeeCVP** [comment]
Online Offline Calibration - Official

![Online Offline Calibration - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5b767794-0e63-4bf6-a6cf-c5abe06f0fd0)

**Comment by mosesdeeCVP** [comment]
Online Offline Calibration - Official with ID

![Online Offline Calibration - Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ed93965d-1ce2-4a9f-a58c-1383c258104d)

**Comment by mosesdeeCVP** [comment]
Online Offline Calibration - Workspace

![Online Offline Calibration - workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a01cd835-455c-4f29-9d2f-84e2b0cdb1c4)

**Comment by mosesdeeCVP** [comment]
Online Offline Calibration - Workspace with ID

![Online Offline Calibration - workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/051fbc92-16c1-447b-aeb2-c49983ff6bf0)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1045](https://epacamd.testquality.com/project/11428/plan/27608/test/403050)
Test Passed
