### ISSUE TITLE
API Endpoint - Add Online Offline Calibration Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2923]
Add an API Endpoint to create/add Online Offline Calibration Data

Testing Reference Only:

Online Zero Reference Value (Text)
Online Upscale Reference Value (Text)
Offline Zero Reference Value (Text)
Offline Upscale Reference Value (Text)
Online Zero Measured Value (Text)
Online Upscale Measured Value (Text)
Offline Zero Measured Value (Text)
Offline Upscale Measured Value (Text)
Online Zero Calibration Error (Text)
Online Upscale Calibration Error (Text)
Offline Zero Calibration Error (Text)
Offline Upscale Calibration Error (Text)
Upscale Gas Level Code (Dropdown)
Online Zero APS Indicator (Dropdown)
Online Upscale APS Indicator (Dropdown)
Offline Zero APS Indicator (Dropdown)
Offline Upscale APS Indicator (Dropdown)
Online Zero Injection Date (Text+Datepicker)
Online Upscale Injection Date (Text+Datepicker)
Offline Zero Injection Date (Text+Datepicker)
Offline Upscale Injection Date (Text+Datepicker)
Online Zero Injection Hour (Dropdown 1-23)
Online Upscale Injection Hour (Dropdown 1-23)
Offline Zero Injection Hour (Dropdown 1-23)
Offline Upscale Injection Hour (Dropdown 1-23)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1025](https://epacamd.testquality.com/project/11428/plan/27608/test/401529)

**Comment by mosesdeeCVP** [comment]
User is able to create Online Offline Calibration Data. There are 4 fields that are not showing up in the file and 4 that are being returned from the DB. This issue will be addressed in a bug ticket. 

Reporting Instructions:
Online Zero APS Indicator (Dropdown)
Online Upscale APS Indicator (Dropdown)
Offline Zero APS Indicator (Dropdown)
Offline Upscale APS Indicator (Dropdown)
   
Database:
"calculatedOnlineZeroCalibrationError" 
"calculatedOnlineUpscaleCalibrationError" 
"calculatedOfflineZeroCalibrationError" 
"calculatedOfflineUpscaleCalibrationError"
