### ISSUE TITLE
Remove Online Offline Calibration Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2924]
As an ECMPS user, I want the ability to remove Online Offline Calibration Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Online Offline Calibration data section
When I click on the 'Remove' option for Online Offline Calibration
Then I see that the relevant Online Offline Calibration data record is deleted

Given I chose to remove Online Offline Calibration Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Online Offline Calibration data section
When I select Cancel
Then I am returned to the landing screen for Online Offline Calibration Data

Invision Board URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case:[ TC1072](https://epacamd.testquality.com/project/11428/plan/27608/test/406778)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
