### ISSUE TITLE
Global 'View' and Workspace 'Add':  Online Offline Calibration Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2925]
As an ECMPS user, I want to view Online Offline Calibration Data in the Global-View and add new Online Offline Calibration Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Online Offline Calibration from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Online Zero Reference Value
Online Upscale Reference Value
Offline Zero Reference Value
Offline Upscale Reference Value
Online Zero Measured Value
Online Upscale Measured Value
Offline Zero Measured Value
Offline Upscale Measured Value
Online Zero Calibration Error
Online Upscale Calibration Error
Offline Zero Calibration Error
Offline Upscale Calibration Error
Upscale Gas Level Code
Online Zero APS Indicator
Online Upscale APS Indicator
Offline Zero APS Indicator
Offline Upscale APS Indicator
Online Zero Injection Date
Online Upscale Injection Date
Offline Zero Injection Date
Offline Upscale Injection Date
Online Zero Injection Hour
Online Upscale Injection Hour
Offline Zero Injection Hour
Offline Upscale Injection Hour

Given a user is viewing Online Offline Calibration Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Online Offline Calibration from the Test Type Group dropdown
When the user clicks on 'Add' for Online Offline Calibration Data
Then the system displays a modal
and the user can add new data for:

Online Zero Reference Value (Text)
Online Upscale Reference Value (Text)
Offline Zero Reference Value (Text)
Offline Upscale Reference Value (Text)
Online Zero Measured Value (Text)
Online Upscale Measured Value (Text)
Offline Zero Measured Value (Text)
Offline Upscale Measured Value (Text)
Online Zero Calibration Error (Text)
Online Upscale Calibration Error (Text)
Offline Zero Calibration Error (Text)
Offline Upscale Calibration Error (Text)
Upscale Gas Level Code (Dropdown)
Online Zero APS Indicator (Radiobutton, default selection is 1)
Online Upscale APS Indicator (Radiobutton, default selection is 1)
Offline Zero APS Indicator (Radiobutton, default selection is 1)
Offline Upscale APS Indicator (Radiobutton, default selection is 1)
Online Zero Injection Date (Text+Datepicker)
Online Upscale Injection Date (Text+Datepicker)
Offline Zero Injection Date (Text+Datepicker)
Offline Upscale Injection Date (Text+Datepicker)
Online Zero Injection Hour (Dropdown 1-23)
Online Upscale Injection Hour (Dropdown 1-23)
Offline Zero Injection Hour (Dropdown 1-23)
Offline Upscale Injection Hour (Dropdown 1-23)

Given the user has added Online Offline Calibration Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Online Offline Calibration Data record is reflected on the UI

Given the user has added a new Online Offline Calibration Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Online Offline Calibration Data
And no updates are saved

**Label for the section: Online Offline Calibration**

Reference Invision URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1074](https://epacamd.testquality.com/project/11428/plan/27608/test/406780)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Add Online Offline Calibration.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/eb357a63-e101-4638-80d8-79beb2df5760)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
View Online Offline Calibration

![View Online Offline Calibration.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5aa0ba81-2ac6-4d42-b304-abc80ea50bab)
