### ISSUE TITLE
API Endpoint - Add Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2934]
API Endpoint - Add Cycle Time Summary Data

Testing Reference Only:
Total Time (Text)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/270

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Official

![Cycle Time Summary - View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9ca66fae-f533-4b1d-9f25-0bcb039f3a3f)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Official with ID

![Cycle Time Summary - View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ce260c56-095c-4458-adbd-2ac84ec1c9e2)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Workspace

![Cycle Time Summary - View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fd49a439-df38-4626-994d-45217b5f0f87)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Workspace with ID

![Cycle Time Summary - View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44e2d8f7-474d-4525-910f-4c341bc68a3f)

**Comment by mosesdeeCVP** [comment]
![Cycle Time Summary - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8047ac06-f7ed-4879-93d0-0f3425a47a96)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1079](https://epacamd.testquality.com/project/11428/plan/27813/test/406926)
Test Passed
