### ISSUE TITLE
API Endpoint - View Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2935]
Create GET endpoints (4) for Cycle Time Summary Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Total Time

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/270

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Official
Dolet Hills Power Station (51)

![Cycle Time Summary - View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9ca66fae-f533-4b1d-9f25-0bcb039f3a3f)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Official with ID

![Cycle Time Summary - View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ce260c56-095c-4458-adbd-2ac84ec1c9e2)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Workspace

![Cycle Time Summary - View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fd49a439-df38-4626-994d-45217b5f0f87)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary - View Workspace with ID

![Cycle Time Summary - View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44e2d8f7-474d-4525-910f-4c341bc68a3f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1081](https://epacamd.testquality.com/project/11428/plan/27813/test/406925)
Test Passed
