### ISSUE TITLE
Remove Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2936]
As an ECMPS user, I want the ability to remove Cycle Time Summary Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Cycle Time Summary Data section
When I click on the 'Remove' option for Cycle Time Summary Data
Then I see that the relevant Cycle Time Summary data record is deleted

Given I chose to remove Cycle Time Summary data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Cycle Time Summary data section
When I select Cancel
Then I am returned to the landing screen for Cycle Time Summary

## Testing 
Test Case: [TC1108](https://epacamd.testquality.com/project/11428/plan/27813/test/411202)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
