### ISSUE TITLE
Edit Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2937]
As an ECMPS user (logged-in), I want to update Cycle Time Summary data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Cycle Time Summary from the Test Type Group dropdown
When the user selects 'Edit' for Cycle Time Summary 
Then the system displays the edit modal
And the user can edit Cycle Time Summary 

Total Time (Text)

Given the user has updated Cycle Time Summary Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Cycle Time Summary Data
And the updates are reflected in the Cycle Time Summary data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0a375b18-ee0c-434e-b7b6-b96dcc30fdec)

## Testing 
Test Case: [TC1106](https://epacamd.testquality.com/project/11428/plan/27813/test/411195)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Cycle Time Summary Data - Modal Edit Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7a217b08-b996-4c1b-9838-0c0a7338b330)
