### ISSUE TITLE
Add Cycle Time Summary Data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2938]
Add Cycle Time Summary data elements to Export Endpoint for both Official and Workspace views

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/273

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary Export Official

![Cycle Time Summary Export Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ce7eda44-185c-43df-8a23-4b3d7e3ebde6)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary Export Workspace

![Cycle Time Summary Export Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7ad3d584-b248-4c84-acea-e16775be048f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1087](https://epacamd.testquality.com/project/11428/plan/27813/test/407616)
Test Passed
