### ISSUE TITLE
Global 'View' and Workspace 'Add': Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2939]
As an ECMPS user, I want to view Cycle Time Summary Data in the Global-View and add new Cycle Time Summary Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Cycle Time Summary from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

Columns:
Total Time

Given a user is viewing Cycle Time Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Cycle Time Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Cycle Time Summary data
Then the system displays a modal
and the user can add new data for:

Total Time (Text)

Given the user has added Cycle Time Summary
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Cycle Time Summary record is reflected on the UI

Given the user has added a new Cycle Time Summary
When the user chooses to Cancel
Then the user is returned to the Landing screen for Cycle Time Summary
And no updates are saved

**Dev Note:** **This data section is at the second level of nesting (Test Data -> Cycle Time Summary)**

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0c839cd4-3136-490a-9fdb-4d2e3f913d32)

## Testing 
Test Case: [TC1107](https://epacamd.testquality.com/project/11428/plan/27813/test/411196)
Tester @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary Data - Table View Official
![Cycle Time Summary Data - Table View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8d0b2b4d-4742-477b-a58d-418c99681357)

Cycle Time Summary Data - Modal View Official
![Cycle Time Summary Data - Modal View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fde48dbb-c523-48ae-b3c3-2c012a63683c)

**Comment by mosesdeeCVP** [comment]
Cycle Time Summary Data - Table View Workspace
![Cycle Time Summary Data - Table View Work Space.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/063faa9b-9436-4f03-90b8-b9f18a8f7367)

Cycle Time Summary Data - Modal View Workspace
![Cycle Time Summary Data - Modal View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/afa9b0fd-6c9e-4956-9315-e8f818f1d778)

**Comment by mosesdeeCVP** [comment]
Test Passed
