### ISSUE TITLE
API Endpoint - Add Hg Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2940]
API Endpoint - Add Hg Injection Data

Testing Reference Only:
Injection Date (Datepicker and Text)
Injection Hour (Dropdown)
Injection Minute (Dropdown)
Measured Value (Text)
Reference Value (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1163](https://epacamd.testquality.com/project/11428/plan/28224/test/414117)

**Comment by mosesdeeCVP** [comment]
![HG Injection Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/72496e33-e464-4b96-83ca-274faffe1150)

**Comment by mosesdeeCVP** [comment]
Test Passed
