### ISSUE TITLE
API Endpoint - View Hg Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2941]
Create GET endpoints (4) for Hg Injection Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Injection Date (Datepicker and Text)
Injection Hour (Dropdown)
Injection Minute (Dropdown)
Measured Value (Text)
Reference Value (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1162](https://epacamd.testquality.com/project/11428/plan/28224/test/414116)

**Comment by mosesdeeCVP** [comment]
HG Injection View Official
![HG Injection View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/16197ce4-d949-4f43-a448-03055fd483fb)

**Comment by mosesdeeCVP** [comment]
HG Injection View Official with ID
![HG Injection View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a9b9c08c-57f8-4e9d-98f4-c66daa3519e0)

**Comment by mosesdeeCVP** [comment]
HG Injection View Workspace
![HG Injection View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04c50d91-2722-47d3-a8ce-8bc259f3c03e)

**Comment by mosesdeeCVP** [comment]
HG Injection View Workspace with ID
![HG Injection View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fb025db1-8fb0-4c77-8d3d-b60b7170026f)

**Comment by mosesdeeCVP** [comment]
Test Passed
