### ISSUE TITLE
Global 'View' and Workspace 'Add': Hg Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2943]
As an ECMPS user, I want to view Hg Injection Data in the Global-View and add new Hg Injection Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Hg Linearity and 3-level Summary from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

Columns:
Injection Date (Datepicker and Text)
Injection Hour (Dropdown)
Injection Minute (Dropdown)
Measured Value (Text)
Reference Value (Text)

Given a user is viewing Hg Injection Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [X] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Hg Linearity and 3-level Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Hg Injection Data
Then the system displays a modal
and the user can add new data for:

Testing Reference Only:
Injection Date (Datepicker and Text)
Injection Hour (Dropdown)
Injection Minute (Dropdown)
Measured Value (Text)
Reference Value (Text)

Given the user has added Hg Injection Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Hg Injection data record is reflected on the UI

Given the user has added a new Hg Injection Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Hg Injection Data
And no updates are saved

**Dev Note:** **This data section is at the third level of nesting (Test Data -> Hg Summary -> Hg Injection)**

## Testing 
Test Case:[ TC1177](https://epacamd.testquality.com/project/11428/plan/28224/test/415609)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Hg Injection View Table Official
![Hg Injection View Table Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/77bc0249-3ecd-4ea2-a603-6e22864fb18a)

**Comment by mosesdeeCVP** [comment]
Hg Injection View Modal Official
![Hg Injection View Modal Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/80e398c9-5d7d-47d9-bb83-6cef17e1e67b)

**Comment by mosesdeeCVP** [comment]
HG Injection Add
![HG Injection Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/71179a88-1c33-4d37-8117-7518acf76df2)
