### ISSUE TITLE
Edit Hg Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2944]
As an ECMPS user (logged-in), I want to update Hg Injection data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Hg Linearity and 3-level Summary from the Test Type Group dropdown
When the user selects 'Edit' for Hg Injection Data
Then the system displays the edit modal
And the user can edit Hg Injection Data

Injection Date (Datepicker and Text)
Injection Hour (Dropdown)
Injection Minute (Dropdown)
Measured Value (Text)
Reference Value (Text)

Given the user has updated Hg Injection Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Hg Injection Data
And the updates are reflected in the Hg Injection data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

## Testing 
Test Case: [TC1176](https://epacamd.testquality.com/project/11428/plan/28224/test/415607)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Edit Hg Injection .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e104010e-2652-4f8c-a5f4-4edc58e04216)

**Comment by mosesdeeCVP** [comment]
Test Passed
