### ISSUE TITLE
Add Hg Injection data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2945]
Add Hg Injection data elements to Import Endpoint

**Comment by mosesdeeCVP** [comment]
![HgInjectionData - Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/493799f9-3f16-4afa-9f14-813f31c703aa)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1186](https://epacamd.testquality.com/project/11428/plan/28224/test/415926)
Test Passed
