### ISSUE TITLE
API Endpoint - View Hg Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2946]
Create GET endpoints (4) for Hg Summary Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Gas Level Code _Dropdown (High, Mid, Low)
Mean Measured Value (Text)
Mean Reference Value (Text)
Percent Error (Text)
APS Indicator (Radiobutton)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1151](https://epacamd.testquality.com/project/11428/plan/28224/test/413664)

**Comment by mosesdeeCVP** [comment]
HG Summary API View 
![HG Summary API View .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1e12f8f9-6e80-43c6-8c59-5f4e5262f1e3)

HG Summary API View with ID
![HG Summary API View with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/de3ad908-7998-4a76-bb35-3e8dfddab548)

**Comment by mosesdeeCVP** [comment]
HG Summary API View Workspace
![HG Summary API View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/71d63951-c772-4d4b-ba90-5292e551dbd0)

HG Summary API View Workspace with ID
![HG Summary API View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e087164-f2d5-49a2-9bf7-280c404b9e60)

**Comment by mosesdeeCVP** [comment]
Test Passed
