### ISSUE TITLE
API Endpoint - Add Hg Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2947]
API Endpoint - Add Hg Summary Data

Testing Reference Only:
Gas Level Code (Dropdown - High, Mid, Low)
Mean Measured Value (Text)
Mean Reference Value (Text)
Percent Error (Text)
APS Indicator (Radiobutton)

**Comment by mosesdeeCVP** [comment]
![Hg Summary Data - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/711defb2-1643-4841-88de-c93053a4c4ab)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1146](https://epacamd.testquality.com/project/11428/plan/28224/test/413562)
Test Passed
