### ISSUE TITLE
Remove Hg Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2948]
As an ECMPS user, I want the ability to remove Hg Summary data so that I can update data as needed

Acceptance Criteria:
Given I am in the Hg Summary data section
When I click on the 'Remove' option 
Then I see that the relevant Hg Summary data record is deleted

Given I chose to remove Hg Summary data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Hg Linearity and 3-level Summary Data section
When I select Cancel
Then I am returned to the landing screen for Hg Linearity and 3-level Summary data 

## Testing
Test Case: [TC1172](https://epacamd.testquality.com/project/11428/plan/28224/test/415594)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
