### ISSUE TITLE
Add Hg Summary data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2949]
Add Hg Summary data elements to Import Endpoint

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1161](https://epacamd.testquality.com/project/11428/plan/28224/test/414115)

**Comment by mosesdeeCVP** [comment]
![HG Summary Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a5ea4674-8895-473e-a7aa-96bec2edf764)

**Comment by mosesdeeCVP** [comment]
Test Passed
