### ISSUE TITLE
Global 'View' and Workspace 'Add': Hg Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2951]
As an ECMPS user, I want to view Hg Linearity and 3-level Summary Data in the Global-View and add new Hg Linearity and 3-level Summary Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Hg Linearity and 3-level Summary from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

Columns:
Gas Level Code Dropdown
Mean Measured Value
Mean Reference Value
Percent Error
APS Indicator

Given a user is viewing Hg Linearity and 3-level Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Hg Linearity and 3-level Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Hg Summary Data
Then the system displays a modal
and the user can add new data for:

Gas Level Code (Dropdown - High, Mid, Low)
Mean Measured Value (Text)
Mean Reference Value (Text)
Percent Error (Text)
APS Indicator (Radiobutton)

Given the user has added Hg Linearity and 3-level Summary Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Hg Linearity and 3-level Summary record is reflected on the UI

Given the user has added a new Hg Summary data record
When the user chooses to Cancel
Then the user is returned to the Landing screen for Hg Linearity and 3-level Summary data
And no updates are saved

**Dev Note:** **This data section is at the second level of nesting (Test Data -> Hg Summary)**

## Testing 
Test Case: [TC1178](https://epacamd.testquality.com/project/11428/plan/28224/test/415610)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
HG Sum Official Table
![HG Sum Official Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1af0c2d4-b12d-4e11-856d-1fa1cdd14633)

**Comment by mosesdeeCVP** [comment]
HG Sum Official Modal
![HG Sum Official Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/212657dd-a81e-425a-8079-da69daaa7fce)

**Comment by mosesdeeCVP** [comment]
HG Sum Workspace Add
![HG Sum Workspace Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/80d830cb-ba6b-42f9-ba80-6630a0c1050c)

**Comment by mosesdeeCVP** [comment]
Test Passed
