### ISSUE TITLE
Create MDM Endpoint for Probe Type Code (RATA Traverse Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2952]
Create MDM Endpoint for Probe Type Code 

Testing Only: 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/89c3201b-48ff-49d4-b135-288d04e520e4)

## Testing 
Test Case: [TC925](https://epacamd.testquality.com/project/11428/plan/26541/test/393049)
Tester: @mosesdeeCVP

**Comment by billmiller13** [comment]
DB Table: camdecmpsmd.probe_type_code
DB Columns:  probe_type_cd, probe_type_cd_description

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Probe Type Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/27b33931-a99a-4fc8-bbd7-32583fb1185c)
