### ISSUE TITLE
API Endpoint - Add RATA Traverse Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2953]
Add an API Endpoint to create/add RATA Traverse Data

Testing Only:
Probe ID (Text)
Probe Type Code (Dropdown)
Pressure Measure Code (Dropdown)
Method Traverse Point ID (Text)
Velocity Calibration Coefficient (Text)
Last Probe Date (Text+Date Picker)
Avg Vel Diff Pressure (Text)
Avg Square Vel Diff Pressures (Text)
T Stack Temperature (Text)
Point Used Indicator (Dropdown? Possible values 1/Null)
Number of Wall Effects Points (Text)
Yaw Angle (Text)
Pitch Angle (Text)
Calculated Velocity (Text)
Replacement Velocity (Text)

## Testing 
Test Case: [TC943](https://epacamd.testquality.com/project/11428/plan/26541/test/395156)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Add Trav.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4fa84783-5584-442e-8cea-85c1fbc277cf)
