### ISSUE TITLE
Remove RATA Traverse Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2954]
As an ECMPS user, I want the ability to remove RATA Traverse Data so that I can update Relative Accuracy Data as needed

Acceptance Criteria:
Given I am in the RATA Traverse data section
When I click on the 'Remove' option for RATA Traverse Data
Then I see that the relevant RATA Traverse data record is deleted

Given I chose to remove RATA Traverse Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the RATA Traverse data section
When I select Cancel
Then I am returned to the landing screen for RATA Traverse Data

Invision Board:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2YXc0OThtMDBqaDNiNnlnanNjaWF4Mg%3D%3D

## Testing 
Test Case: [TC933](https://epacamd.testquality.com/project/11428/plan/26541/test/393066)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
