### ISSUE TITLE
Global 'View' and Workspace 'Add': RATA Traverse Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2955]
As an ECMPS user, I want to view RATA Traverse Data in the Global-View and add new RATA Traverse Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown and a RATA Traverse data record is available 
When the data is displayed 
Then the user can see RATA Traverse Data displayed as a separate table (see list below for columns and order)

Probe ID (Text)
Probe Type Code (Dropdown - MDM)
Pressure Measure Code (Dropdown - MDM)
Method Traverse Point ID (Text)
Velocity Calibration Coefficient (Text)
Last Probe Date (Text+Date Picker)
Avg Vel Diff Pressure (Text)
Avg Square Vel Diff Pressures (Text)
T Stack Temperature (Text)
Point Used Indicator (Dropdown - MDM)
Number of Wall Effects Points (Text)
Yaw Angle (Text)
Pitch Angle (Text)
Calculated Velocity (Text)
Replacement Velocity (Text)

Given a user is viewing RATA Traverse Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for RATA Traverse Data
Then the system displays a modal
and the user can add new data for:

Probe ID (Text)
Probe Type Code (Dropdown)
Pressure Measure Code (Dropdown)
Method Traverse Point ID (Text)
Velocity Calibration Coefficient (Text)
Last Probe Date (Text+Date Picker)
Avg Vel Diff Pressure (Text)
Avg Square Vel Diff Pressures (Text)
T Stack Temperature (Text)
Point Used Indicator (Dropdown)
Number of Wall Effects Points (Text)
Yaw Angle (Text)
Pitch Angle (Text)
Calculated Velocity (Text)
Replacement Velocity (Text)

Given the user has added RATA Traverse Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the RATA Traverse Data record is reflected on the UI

Given the user has added a new RATA Traverse data record
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA data
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2YXc0OThtMDBkcjNiNnliZWlsdnllYg%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2Z3IwMHZvMDFtcTNiN2k5NzQ4OWdodQ%3D%3D

## Testing 
Test Case: [TC931 ](https://epacamd.testquality.com/project/11428/plan/26541/test/393059)
Tester: @JanellC

**Comment by JanellC** [comment]
Traverse functionaility works as expected. Found an issue with how Traverse records are displayed on the UI see: Bug: Rata Traverse Improperly Displayed #4269
