### ISSUE TITLE
API Endpoint - View RATA Traverse Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2957]
Create GET endpoints (4) for RATA Traverse Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Only:
Probe ID (Text)
Probe Type Code (Dropdown)
Pressure Measure Code (Dropdown)
Method Traverse Point ID (Text)
Velocity Calibration Coefficient (Text)
Last Probe Date (Text+Date Picker)
Avg Vel Diff Pressure (Text)
Avg Square Vel Diff Pressures (Text)
T Stack Temperature (Text)
Point Used Indicator (Dropdown? Possible values 1/Null)
Number of Wall Effects Points (Text)
Yaw Angle (Text)
Pitch Angle (Text)
Calculated Velocity (Text)
Replacement Velocity (Text)

## Testing 
Test Case: [TC946](https://epacamd.testquality.com/project/11428/plan/26541/test/395312)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Both Rata Traverse endpoints on workspace work

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Rata Traverse Global View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1d980b6a-76a8-4eb2-9254-a701c66a13b7)

![Rata Traverse Global View - ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8fdfc183-2df8-4c2b-8e77-13ddf91d27a3)
