### ISSUE TITLE
Global 'View' and Workspace 'Add': Flow RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2960]
As an ECMPS user, I want to view Flow RATA Run Data in the Global-View and add new Air Emissions Testing data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown 
When the Flow RATA Run Data is displayed 
Then the user can see Flow RATA Run Data displayed as a separate table (see list below for columns and order)

Number of Traverse Points (Text)
Barometric Pressure (Text)
Stack Static Pressure (Text)
Percent CO2 (Text)
Percent O2 (Text)
Percent Moisture (Text)
Dry Molecular Weight (Text)
Wet Molecular Weight (Text)
Average Velocity without Wall Effects (Text)
Average Velocity with Wall Effects (Text)
Calculated WAF (Text)
Average Stack Flow Rate (Text)

Given a user is viewing Flow RATA Run Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Flow RATA Run Data
Then the system displays a modal
and the user can add new data for:

Number of Traverse Points (Text)
Barometric Pressure (Text)
Stack Static Pressure (Text)
Percent CO2 (Text)
Percent O2 (Text)
Percent Moisture (Text)
Dry Molecular Weight (Text)
Wet Molecular Weight (Text)
Average Velocity without Wall Effects (Text)
Average Velocity with Wall Effects (Text)
Calculated WAF (Text)
Average Stack Flow Rate (Text)

Given the user has added Flow RATA Run Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Flow RATA Run record is reflected on the UI

Given the user has added new Flow RATA Run Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA data
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2Z3E5cHJkMDBweTNiN2l4cmc1c2M4Nw%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2bnZtdnp3MDFnZTNiNnhrOGsydGFicw%3D%3D

## Testing 
Test Case: [TC923](https://epacamd.testquality.com/project/11428/plan/26541/test/392972)
Tester: @JanellC

**Comment by JanellC** [comment]
TC923 failed. See Bug: Rata Flow impropely displayed and view functionaility is broken #4268
