### ISSUE TITLE
Remove Flow RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2963]
As an ECMPS user, I want the ability to remove Flow RATA Run Data so that I can update Relative Accuracy Data as needed

Acceptance Criteria:
Given I am in the Flow RATA Run Data section
When I click on the 'Remove' option for Flow RATA Run Data
Then I see that the relevant data record is deleted

Given I chose to remove Flow RATA Run Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Flow RATA Run Data section
When I select Cancel
Then I am returned to the landing screen for Flow RATA Run Data

Invision Board:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2bnZtdnp3MDFnZTNiNnhrOGsydGFicw%3D%3D

## Testing
Test Case: [TC930](https://epacamd.testquality.com/project/11428/plan/26541/test/393058)
Tester: @JanellC

**Comment by JanellC** [comment]
TC930 passed. The system removes a rata flow record however an issue occurs where the other rata flow records in the table display as blank after removing a record see: Bug: Remove Rata Air emissions record#4239

**Comment by mosesdeeCVP** [comment]
Bug ticket was made to address issues with this ticket:

[Bug: Remove Rata Air emissions, Rata Flow, and Rata Traverse record #4239](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/4239)
