### ISSUE TITLE
Create MDM Endpoint for Run Status Code (RATA Run Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2964]
Create MDM Endpoint for Run Status Code (RATA Run Data):

Testing Reference Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4e4b4be6-c253-446a-92ee-19c8b1c4873a)

## Testing 
Test Case:[ TC905](https://epacamd.testquality.com/project/11428/plan/26541/test/388755)
Tester: @JanellC

**Comment by JanellC** [comment]
TC905 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e92eb8ce-b31c-4d22-86d7-4cd21e4e9bba)
