### ISSUE TITLE
Add API Endpoint - RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2965]
Add an API Endpoint to create/add RATA Run Data

Testing Reference Only:
Run Number (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute  Dropdown)
CEM Value (Text)
RATA Reference Value (Text)
Gross Unit Load (Text)
Run Status Code (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC888](https://epacamd.testquality.com/project/11428/plan/26541/test/388420)

Test Passed
