### ISSUE TITLE
Add RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2966]
As an ECMPS user (logged-in), I want to add RATA Run data so that I can add information to a test

Acceptance Criteria:

Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Run
Then the system displays a modal
and the user can add new data for:

Run Number (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute Dropdown)
CEM Value (Text)
RATA Reference Value (Text)
Gross Unit Load (Text)
Run Status Code (Dropdown)

Given the user has added RATA Run data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen for RATA Run data
And the Run Record is reflected on the UI

Given the user has added new 'Run Records' (RATA Summary)
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA 
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eWhoZjZ5MDE3OTNiNnlqNHF4d21vYQ%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eWd4NmthMDFldTNiN2diaThybG9uaQ%3D%3D

## Testing 
Test Cases: 
View [TC907](https://epacamd.testquality.com/project/11428/plan/26541/test/388761)
Tester:  @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
