### ISSUE TITLE
Global 'View' and Workspace 'Edit': RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2967]
As an ECMPS user, I want to view RATA Run data in the Global-View and update RATA Run data in the Workspace so that I can look at real-time data or make updates as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown and Run data record is available 
When the RATA Run data is displayed 
Then the data is displayed as a separate table (see list below for columns and order)

Run Number (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute Dropdown)
CEM Value (Text)
RATA Reference Value (Text)
Gross Unit Load (Text)
Run Status Code (Dropdown)

Given a user is viewing RATA Run Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Edit)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user selects 'Edit' for Run data
Then the system displays the edit modal
And the user can edit Run data (RATA) - See above for info on columns

Given the user has updated Run Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Run Data
And the updates are reflected in the Run Data section of RATA

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Invision:
**Global-View:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2bndramJ5MDJvaDNiNngxZjBydzN4ZQ%3D%3D
**Edit:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1azFkdGJhMDI1bDNiNnk4ZTl5NjhneQ%3D%3D

## Testing 
Test Cases: 
View [TC873](https://epacamd.testquality.com/project/11428/plan/26541/test/386750)
Edit [TC873](https://epacamd.testquality.com/project/11428/plan/26541/test/386751)
Tester:  @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
View Test Passes
Edit Test Fails (Bug ticket #4098 will track Edit)
