### ISSUE TITLE
View API Endpoint - RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2968]
Create GET endpoints (4) for RATA Run Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Run Number (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute Dropdown)
CEM Value (Text)
RATA Reference Value (Text)
Gross Unit Load (Text)
Run Status Code (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC886](https://epacamd.testquality.com/project/11428/plan/26541/test/388418)

Test Passed
