### ISSUE TITLE
Create MDM Endpoint for Operating Level Code (RATA Summary Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2970]
Create MDM Endpoint for Operating Level Code (RATA Summary Data):

Testing Reference Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1ee33bba-eaf1-47b5-9224-42b4b12dd713)

**Comment by subrataroyCVP** [comment]
Endpoint Already Exists in the MDM-Api.

![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/4a380e2f-f32f-4581-87a6-743c87b9da03)
