### ISSUE TITLE
Add API Endpoint - RATA Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2971]
Add an API Endpoint to create/add RATA Summary Data

Testing Reference Only:
Operating Level Code (Dropdown - L, M, H and N) - Pulled from the MDM endpoint
Average Gross Unit Load (Text)
Reference Method Code (Dropdown) - Pulled from the MDM endpoint
Mean CEM Value (Text)
Mean RATA Reference Value (Text)
Mean Difference (Text)
Standard Deviation Difference (Text)
Confidence Coefficient (Text)
T Value (Text)
APS Indicator (Radiobutton - Yes/No)
APS Code (dropdown) - Pulled from the MDM endpoint
Relative Accuracy (Text)
Bias Adjustment Factor (Text)
CO2 or O2 Reference Method Code (dropdown) - Pulled from the MDM endpoint
Stack Diameter (Text)
Stack Area (Text)
Number of Traverse Points (Text)
Calculated WAF (Text)

## Testing 
Test Case: [TC875](https://epacamd.testquality.com/project/11428/plan/26541/test/386752)
Tester:  @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
