### ISSUE TITLE
Remove RATA Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2972]
As an ECMPS user, I want the ability to remove RATA Summary Data so that I can update Relative Accuracy Data as needed

Acceptance Criteria:
Given I am in the RATA Summary Data section
When I click on the 'Remove' option
Then I see that the relevant RATA Summary Data record is deleted

Given I chose to remove RATA Summary Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the RATA Summary Data section
When I select Cancel
Then I am returned to the landing screen for RATA Summary Data

Invision Board:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1azFkdGJhMDI1bDNiNnk4ZTl5NjhneQ%3D%3D

## Testing 
Test Case: [TC869](https://epacamd.testquality.com/project/11428/plan/26541/test/386731)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
