### ISSUE TITLE
Global 'View' and Workspace 'Add': RATA Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2974]
As an ECMPS user, I want to view RATA Summary data in the Global-View and add new RATA Summary data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown and Summary data record is available 
When the Summary data (RATA) is displayed 
Then the data is displayed as a separate table (see list below for columns and order)

Operating Level Code (Dropdown - L, M, H and N) - Pulled from the MDM endpoint
Average Gross Unit Load (Text)
Reference Method Code (Dropdown) - Pulled from the MDM endpoint
Mean CEM Value (Text)
Mean RATA Reference Value (Text)
Mean Difference (Text)
Standard Deviation Difference (Text)
Confidence Coefficient (Text)
T Value (Text)
APS Indicator (Radiobutton - Yes/No)
APS Code (dropdown) - Pulled from the MDM endpoint
Relative Accuracy (Text)
Bias Adjustment Factor (Text)
CO2 or O2 Reference Method Code (dropdown) - Pulled from the MDM endpoint
Stack Diameter (Text)
Stack Area (Text)
Number of Traverse Points (Text)
Calculated WAF (Text)

Given a user is viewing RATA Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Summary
Then the system displays a modal
and the user can add new data for:

Operating Level Code (Dropdown)
Average Gross Unit Load (Text)
Reference Method Code (Dropdown)
Mean CEM Value (Text)
Mean RATA Reference Value (Text)
Mean Difference (Text)
Standard Deviation Difference (Text)
Confidence Coefficient (Text)
T Value (Text)
APS Indicator (Radiobutton - Yes/No)
APS Code (dropdown)
Relative Accuracy (Text)
Bias Adjustment Factor (Text)
CO2 or O2 Reference Method Code (dropdown)
Stack Diameter (Text)
Stack Area (Text)
Number of Traverse Points (Text)
Calculated WAF (Text)

Given the user has added RATA Summary data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen for RATA Summary data
And the Summary Record is reflected on the UI

Given the user has added new 'Summary Records' (RATA Summary)
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA Summary data
And no updates are saved

The scope of this ticket includes Add Summary records for all 4 Operating Level Codes (L, M, H, N)

Dev Notes:
Users shall be able to add data from scratch when there is no existing Summary Records

Reference Invision:
**Global-View:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2MnE1Z3ExMDAwYzNiNnk1NHN1cGYzOA%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2M3UzOTZoMDA1bDNiNzVxcmpyOHgzcQ%3D%3D
**Add:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eWZ6MWt4MDE5aDNiN2dkMm43aWFkOQ%3D%3D

**Note for Testing:**
Fields to show in the grid:

Operating Level Code (Dropdown)
Reference Method Code (Dropdown)
APS Indicator (Radiobutton - Yes/No)
APS Code (dropdown)
Relative Accuracy (Text)
CO2 or O2 Reference Method Code (dropdown)

## Testing
Test Case: [TC864](https://epacamd.testquality.com/project/11428/plan/26541/test/386559)
Tester: @mosesdeeCVP

**Comment by NadiaJL** [comment]
@vishnunavuluri  RATA Summary Tables have been updated on the EPA-ECMPS-RATA-Product Design inVision board 
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eWhjZGdpMDA5NTNiNnl2M3lmN2NmZw%3D%3D

**Comment by mosesdeeCVP** [comment]
Test Passed
