### ISSUE TITLE
Edit RATA Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2975]
As an ECMPS user (logged-in), I want to update RATA Summary data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user selects 'Edit' for Summary data
Then the system displays the edit modal
And the user can edit the Summary data (RATA)

Operating Level Code (Dropdown)
Average Gross Unit Load (Text)
Reference Method Code (Dropdown)
Mean CEM Value (Text)
Mean RATA Reference Value (Text)
Mean Difference (Text)
Standard Deviation Difference (Text)
Confidence Coefficient (Text)
T Value (Text)
APS Indicator (Radiobutton - Yes/No)
APS Code (dropdown)
Relative Accuracy (Text)
Bias Adjustment Factor (Text)
CO2 or O2 Reference Method Code (dropdown)
Stack Diameter (Text)
Stack Area (Text)
Number of Traverse Points (Text)
Calculated WAF (Text)

Given the user has updated Summary Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Summary Data
And the updates are reflected in the Summary Data section of RATA

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Invision:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1azFkdGJhMDI1bDNiNnk4ZTl5NjhneQ%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2ZjY0ZHQ4MDAyMjNiNnljZXJuZDBpcw%3D%3D

## Testing 
Test Case: [TC868](https://epacamd.testquality.com/project/11428/plan/26541/test/386729)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
