### ISSUE TITLE
API Endpoint - Add  Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2977]
API Endpoint - Add  Appendix E Correlation Summary Data 

Testing Reference Only:
Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

## Testing 
Test Case: [TC968](https://epacamd.testquality.com/project/11428/plan/27381/test/398102)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![3117 API Endpoint - Add Appendix E Correlation Test Run Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/420eb12e-d60a-4898-a8c7-8816c24909ef)

**Comment by mosesdeeCVP** [comment]
Test Passed
