### ISSUE TITLE
Add Appendix E Correlation Summary Data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2978]

**Comment by mosesdeeCVP** [comment]
Add Appendix E Correlation Summary Data elements to Import Endpoint - Official

![2978 Add Appendix E Correlation Summary Data elements to Import Endpoint - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/afcf5c4d-d784-4fbe-9508-d506e0bd36a4)

**Comment by mosesdeeCVP** [comment]
Add Appendix E Correlation Summary Data elements to Import Endpoint - Workspace

![2978 Add Appendix E Correlation Summary Data elements to Import Endpoint - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b9c40559-ab2d-432b-b9bb-3d5ae72bf801)

**Comment by mosesdeeCVP** [comment]
Test Case: [](url)

**Comment by mosesdeeCVP** [comment]
Test Case: [](url)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC988](https://epacamd.testquality.com/project/11428/plan/27381/test/398931)
Test Passed
