### ISSUE TITLE
Edit Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2979]
As an ECMPS user (logged-in), I want to update Appendix E Correlation Summary data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Appendix E Correlation Summary from the Test Type Group dropdown
When the user selects 'Edit' for Appendix E Correlation Summary 
Then the system displays the edit modal
And the user can edit Appendix E Correlation Summary 

Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

Given the user has updated Appendix E Correlation Summary data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Appendix E Correlation Summary data
And the updates are reflected in the Appendix E Correlation Summary data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

**Dev and Testing Note: Add Protocol Gas Data and Air Emission Testing to the UI as part of this ticket**

Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1012](https://epacamd.testquality.com/project/11428/plan/27381/test/400683)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
