### ISSUE TITLE
Create facility and location entities

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#298]
## Development Tasks
Creating the following entities:
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria
Entities exist in the repo with appropriate columns

**Comment by SimeraHailu** [comment]
Facility 
Location 
[https://app.zenhub.com/files/287570343/02c9f235-ffd6-4cf9-bc8b-369c3cc64d34/download](https://app.zenhub.com/files/287570343/02c9f235-ffd6-4cf9-bc8b-369c3cc64d34/download)
