### ISSUE TITLE
Global 'View' and Workspace 'Add': Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2980]
As an ECMPS user, I want to view Appendix E Correlation Summary Data in the Global-View and add new Appendix E Correlation Summary Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

Given a user is viewing Appendix E Correlation Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Appendix E Correlation Test Summary data
Then the system displays a modal
and the user can add new data for:

Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

Given the user has added Appendix E Correlation Summary
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Appendix E Correlation Summary record is reflected on the UI

Given the user has added a new Appendix E Correlation Summary
When the user chooses to Cancel
Then the user is returned to the Landing screen for Appendix E Correlation Summary
And no updates are saved

**Dev Note:** **This data section is at the second level of nesting (Test Summary -> Appendix E Summary)**
Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1002](https://epacamd.testquality.com/project/11428/plan/27381/test/400553)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Official Table View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bb46f6c2-0f28-4334-8eb4-a90c9aa72974)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Official Modal View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4e86aa3a-999d-43f3-9a28-77d4fcfb39e3)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Workspace Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fa6ed213-7a32-4822-a5cb-9aa398535751)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Workspace Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b5a2faf7-00e4-4eb7-ac60-47ee404d1bf8)

**Comment by mosesdeeCVP** [comment]
Test Passed
