### ISSUE TITLE
Remove Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2981]
As an ECMPS user, I want the ability to remove Appendix E Correlation Summary Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Appendix E Correlation Summary Data section
When I click on the 'Remove' option for Appendix E Correlation Summary Data
Then I see that the relevant Appendix E Correlation Summary data record is deleted

Given I chose to remove Appendix E Correlation Summary Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Appendix E Correlation Summary data section
When I select Cancel
Then I am returned to the landing screen for Appendix E Correlation Summary

Invision Board:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1010](https://epacamd.testquality.com/project/11428/plan/27381/test/400681)
Tester : @JanellC

**Comment by JanellC** [comment]
TC1010 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0914b835-68d4-47a1-b98b-1075993b698c)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/56461751-c1f7-4085-ac92-40ab4dff0b0c)
