### ISSUE TITLE
API Endpoint - View Appendix E Correlation Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2983]
Create GET endpoints (4) for Appendix E Correlation Test Run Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Run Number (Text)
Reference Value (Text)
Hourly Heat Input Rate (Text)
Total Heat Input (Text)
Response Time (Text)
Begin Date (Text+Date Picker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Date Picker)
End Hour (Dropdown)
End Minute (Dropdown) 

## Testing 
Test Case: [TC972](https://epacamd.testquality.com/project/11428/plan/27381/test/398362)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
API Endpoint - Add Appendix E Correlation Test Run Data - GET Global

![3117 API Endpoint - Add Appendix E Correlation Test Run Data - GET Global .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/90eeebd5-4dfd-4b0d-99a5-4a1f34441b3a)

**Comment by mosesdeeCVP** [comment]
API Endpoint - Add Appendix E Correlation Test Run Data - GET Global with ID

![3117 API Endpoint - Add Appendix E Correlation Test Run Data - GET Global with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f57ff654-603f-44e3-9140-cdccee0bad1b)

**Comment by mosesdeeCVP** [comment]
API Endpoint - Add Appendix E Correlation Test Run Data - GET Workspace

![3117 API Endpoint - Add Appendix E Correlation Test Run Data - GET Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6f936a26-a425-461b-9368-e63a3ba84482)

**Comment by mosesdeeCVP** [comment]
API Endpoint - Add Appendix E Correlation Test Run Data - GET Workspace with ID

![3117 API Endpoint - Add Appendix E Correlation Test Run Data - GET Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e36bfc60-847a-4963-9fc4-dcf5993df823)

**Comment by mosesdeeCVP** [comment]
Test Passed
