### ISSUE TITLE
Remove Appendix E Correlation Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2984]
As an ECMPS user, I want the ability to remove Appendix E Correlation Test Run Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Appendix E Correlation Test Run Data section
When I click on the 'Remove' option for Appendix E Correlation Test Run Data
Then I see that the relevant data record is deleted

Given I chose to remove Appendix E Correlation Test Run Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Appendix E Correlation Test Run data section
When I select Cancel
Then I am returned to the landing screen for Appendix E Correlation data

Invision Board:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1005](https://epacamd.testquality.com/project/11428/plan/27381/test/400556)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1005 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/69c20bcc-b6ee-4a53-b024-7de55857d5a2)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/09dc8a22-9b0c-4082-9f38-3845ee2a3461)
