### ISSUE TITLE
Global 'View' and Workspace 'Add': Appendix E Correlation Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2985]
As an ECMPS user, I want to view Appendix E Correlation Test Run Data in the Global-View and add new Appendix E Correlation Test Run Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has navigated to Appendix E Correlation Test Run data section 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Run Number (Text)
Reference Value (Text)
Hourly Heat Input Rate (Text)
Total Heat Input (Text)
Response Time (Text)
Begin Date (Text+Date Picker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Date Picker)
End Hour (Dropdown)
End Minute (Dropdown)

Given a user is viewing Appendix E Correlation Test Run Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Appendix E Correlation Test Run data
Then the system displays a modal
and the user can add new data for:

Run Number (Text)
Reference Value (Text)
Hourly Heat Input Rate (Text)
Total Heat Input (Text)
Response Time (Text)
Begin Date (Text+Date Picker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Date Picker)
End Hour (Dropdown)
End Minute (Dropdown)

Given the user has added Appendix E Correlation Test Run
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Appendix E Correlation Test Run record is reflected on the UI

Given the user has added a new Appendix E Correlation Test Run
When the user chooses to Cancel
Then the user is returned to the Landing screen for Appendix E Correlation Test Run
And no updates are saved

**Dev Note:** **This data section is at the third level of nesting (Test Summary -> Appendix E Summary -> Test Run)**
Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1004](https://epacamd.testquality.com/project/11428/plan/27381/test/400555)
Tester @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Official Table View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6b1b68b1-731a-4b30-b32f-5b97ad3ab7de)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Official Modal View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c843c15a-9cd8-40ef-8365-287aab95aff8)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Official Table View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c86e789c-91f0-4c6e-94b0-32b93973995b)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Workspace Modal Create.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/971f6c14-8fb3-414d-8915-f4e9142cc81c)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Global Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/91ce9f09-d86d-465b-bdd9-b0e4476f3e7b)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Test Run Data - Global Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d88bae09-523f-4f9d-b7df-1b0ae8ef7e64)

**Comment by mosesdeeCVP** [comment]
APS Saguaro Power Plant (118)
Location 1

**Comment by mosesdeeCVP** [comment]
Test Passed
