### ISSUE TITLE
Create MDM Endpoint for RATA Data (RATA Frequency Code)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2988]
Create MDM Endpoint for RATA Frequency Code (Test Level - RATA Data):

Testing Reference Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/610f0a87-732f-40b8-adaf-5a34b5f29428)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC851](https://epacamd.testquality.com/project/11428/plan/26541/test/384165)

**Comment by mosesdeeCVP** [comment]
Test Passed
