### ISSUE TITLE
Create contacts and monitoring plan entities

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#299]
## Development Tasks
Creating the following entities:

**Contacts:**
- [x] person
- [x] plant-person
- [x] unit-owner
- [x] contact-relation

**Monitoring Plan:**
- [x] monitor-plan
- [x] unit-stack-configuration
## Acceptance Criteria
Entities exist in the repo with appropriate columns

**Comment by SimeraHailu** [comment]
-Contacts
-Monitoring plan

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/159ae9a0-5307-4365-ab68-145bea26ab24/download](https://app.zenhub.com/files/287570343/159ae9a0-5307-4365-ab68-145bea26ab24/download)

**Comment by sdhawan16** [comment]
Completed entities, Will get them peer reviewed tomorrow before creating pull request

**Comment by sdhawan16** [comment]
Added additional entity contact-relation
