### ISSUE TITLE
Remove RATA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2990]
As an ECMPS user, I want the ability to remove RATA Data so that I can update Relative Accuracy Data as needed

Acceptance Criteria:
Given I am in the RATA data section
When I click on the 'Remove' option
Then I see that the relevant RATA data record is deleted

Given I chose to remove RATA Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the RATA data section
When I select Cancel
Then I am returned to the landing screen for RATA Data

API Endpoint: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Rata/RataWorkspaceController_deleteRata

Invision Board:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1azFkdGJhMDI1bDNiNnk4ZTl5NjhneQ%3D%3D

## Testing 
Test Case: [TC867](https://epacamd.testquality.com/project/11428/plan/26541/test/386571)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
