### ISSUE TITLE
Global 'View' and Workspace 'Add': RATA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2993]
As an ECMPS user, I want to view RATA data in the Global-View and add new RATA data in the Workspace so that I can look at real-time data or add to a test as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown and the RATA record is available 
When the RATA data is displayed 
Then the data is displayed as a separate table (see list below for columns and order)

Number of Load Levels 
Relative Accuracy
RATA Frequency Code
Overall Bias Adjustment Factor

Given a user is viewing RATA data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for RATA
Then the system displays a modal
and the user can add new data for:

Number of Load Levels (Dropdown - Value are 1, 2 and 3)
Relative Accuracy (Text)
RATA Frequency Code (Dropdown)
Overall Bias Adjustment Factor (Text)

Given the user has added RATA data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen for RATA data
And the RATA Record is reflected on the UI

Given the user has added new 'RATA' record
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA data
And no updates are saved

Reference Invision:
**View:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2MnE1Z3ExMDAwYzNiNnk1NHN1cGYzOA%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2M3UzOTZoMDA0eDNiNzU4N2hpbjh5Yg%3D%3D
**Add:** https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1azFkdGJhMDI1bDNiNnk4ZTl5NjhneQ%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eWRtNGZ1MDB1eTNiN2dmMDh3bnpyMA%3D%3D

## Testing 
Test Case:[ TC865](https://epacamd.testquality.com/project/11428/plan/26541/test/386560)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
