### ISSUE TITLE
API Endpoint - View Unit Default Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2994]
Create GET endpoints (4) for Unit Default Test Run Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Operating Level for Run (Text)
Run Number (Text)
Begin Date (Datepicker + Text)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Datepicker + Text)
End Hour (Dropdown)
End Minute (Dropdown)
Response Time (Text)
Reference Value (Text)
Run Used Indicator (Dropdown - 0, 1, Blank)

**Comment by billmiller13** [comment]
**View Many (Official)**
http://localhost:8070/qa-certification-mgmt/locations/3510/test-summary/TAI-LT3NDM-383F3D6DD1B94B1CBB04B680E52A290B/unit-default-tests/TAI-LT3NDM-77307878F4C54646850BBE5E86FFF950/unit-default-test-runs

**View One (Official)**
http://localhost:8070/qa-certification-mgmt/locations/3510/test-summary/TAI-LT3NDM-383F3D6DD1B94B1CBB04B680E52A290B/unit-default-tests/TAI-LT3NDM-77307878F4C54646850BBE5E86FFF950/unit-default-test-runs/TAI-LT3NDM-CB99BB86938342A5A231FCDB0DA5C5C1

**View Many (Workspace)**
http://localhost:8070/qa-certification-mgmt/workspace/locations/1873/test-summary/VMAEPHQAS1-F92002F16CB14A048D2013C72C15E98A/unit-default-tests/6c3e998e-9bb8-4ee7-a5f8-b9eede657f5b/unit-default-test-runs

**View One (Workspace)**
http://localhost:8070/qa-certification-mgmt/workspace/locations/1873/test-summary/VMAEPHQAS1-F92002F16CB14A048D2013C72C15E98A/unit-default-tests/6c3e998e-9bb8-4ee7-a5f8-b9eede657f5b/unit-default-test-runs/37620ee8-236d-416f-827a-58f7924656a3

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1167](https://epacamd.testquality.com/project/11428/plan/28118/test/414829)

**Comment by mosesdeeCVP** [comment]
View Unit Default Test Run Data - Workspace
![View Unit Default Test Run Data - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f74f5bed-f36e-4a51-9615-69685a59e808)

**Comment by mosesdeeCVP** [comment]
View Unit Default Test Run Data - Workspace with ID
![View Unit Default Test Run Data - Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4348fb52-6682-406a-8f2f-2263e7b25b67)

**Comment by mosesdeeCVP** [comment]
View Unit Default Test Run Data - Official
![View Unit Default Test Run Data - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6b9d38f7-cdfe-4e9b-bdf2-8ec1dcbecd1c)

**Comment by mosesdeeCVP** [comment]
View Unit Default Test Run Data - Official with ID
![View Unit Default Test Run Data - Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1c99b02d-8600-443e-8656-07e18265ced2)

**Comment by mosesdeeCVP** [comment]
Test Passed
