### ISSUE TITLE
API Endpoint - Add Unit Default Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2995]
API Endpoint - Add Unit Default Test Run Data

Testing Reference Only:
Operating Level for Run (Text)
Run Number (Text)
Begin Date (Datepicker + Text)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Datepicker + Text)
End Hour (Dropdown)
End Minute (Dropdown)
Response Time (Text)
Reference Value (Text)
Run Used Indicator (Dropdown - 0, 1, Blank)

**Comment by billmiller13** [comment]
![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/9e693628-a185-410e-a658-dc15fc6505a5)

**Comment by billmiller13** [comment]
![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/1ed08d87-78e5-4724-a70e-133ec54eafeb)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1168](https://epacamd.testquality.com/project/11428/plan/28118/test/414830)

**Comment by mosesdeeCVP** [comment]
![Add Unit Default Test Run Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6ff40470-255a-460f-8da1-1cb10165bc63)

**Comment by mosesdeeCVP** [comment]
Test Passed
