### ISSUE TITLE
Remove Unit Default Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2996]
As an ECMPS user, I want the ability to remove Unit Default Test Run data so that I can update data as needed

Acceptance Criteria:
Given I am in the Unit Default Test Run data section
When I click on the 'Remove' option for Unit Default Test Run Data
Then I see that the relevant Unit Default Test Run data record is deleted

Given I chose to remove Unit Default Test Run Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Unit Default Test data section
When I select Cancel
Then I am returned to the landing screen for Unit Default Test Data

## Testing 
Test Case: [TC1184](https://epacamd.testquality.com/project/11428/plan/28118/test/415917)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1184 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/2e9afe63-8c84-42d5-92f5-6124a62378b4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e780f6e9-0695-4f05-b052-6103dd7c8126)
