### ISSUE TITLE
Global 'View' and Workspace 'Add': Unit Default Test Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2998]
As an ECMPS user, I want to view Unit Default Test Run data in the Global-View and add new Unit Default Test Run data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Unit Default from the Test Type Group dropdown and a data record is available 
When the data is displayed for Unit Default Test Run 
Then the user can see data displayed as a separate table (see list below for columns and order)

Operating Level for Run
Run Number
Begin Date
Begin Hour
Begin Minute 
End Date
End Hour
End Minute
Response Time
Reference Value 
Run Used Indicator

Given a user is viewing Unit Default Test Run Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [X] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Unit Default from the Test Type Group dropdown
When the user clicks on 'Add' for Unit Default Test Run Data
Then the system displays a modal
and the user can add new data for:

Operating Level for Run (Text)
Run Number (Text)
Begin Date (Datepicker + Text)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Datepicker + Text)
End Hour (Dropdown)
End Minute (Dropdown)
Response Time (Text)
Reference Value (Text)
Run Used Indicator (Dropdown - 0, 1, Blank)

Given the user has added Unit Default Test Run
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Unit Default Test Run data record is reflected on the UI

Given the user has added a new Unit Default Test Run data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Unit Default Test Run
And no updates are saved

## Testing 
Test Case; [TC1180](https://epacamd.testquality.com/project/11428/plan/28118/test/415882)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Unit Default Test Run - View Official Table
![Unit Default Test Run - View Official Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b2dc43ac-00f8-41ee-9f3d-f9102540b85b)

**Comment by mosesdeeCVP** [comment]
Unit Default Test Run - View Official Modal
![Unit Default Test Run - View Official Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d6edd9ef-66bb-4b78-aae0-c265d16a07ef)

**Comment by mosesdeeCVP** [comment]
Unit Default Test Run - Add Table Workspace
![Unit Default Test Run - Add Table Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/94ec6260-f82f-4383-8166-49b316f59416)

**Comment by mosesdeeCVP** [comment]
Unit Default Test Run - Add Modal Workspace
![Unit Default Test Run - Add Modal Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b8b861d-9859-4a31-9f8c-c409711f7215)

**Comment by mosesdeeCVP** [comment]
Test Passed
