### ISSUE TITLE
Identify Features for Wire-frames for Datateers

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#3]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597336986580) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD
  
Acceptance Criteria:

- When the team begins to build the prepackaged prototype, the interface build will reflect collected UX research.

-

**Comment by JorjaComer** [comment]
Will be combined in to one epic for wireframes. Issue moved to other epic.
