### ISSUE TITLE
Determine Automated Testing Approach

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#30]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=017-1597185763547) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by JorjaComer** [comment]
See closed issues

**Comment by david-cvp** [comment]
Marking invalid, covered by #43
