### ISSUE TITLE
Create unit entities

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#300]
## Development Tasks
Creating the following entities:
- [x] unit
- [x] unit-fuel
- [x] unit-control
- [x] unit-capacity
- [x] unit-program
- [x] unit-generator
- [x] unit-boiler-type
- [x] unit-op-status

## Acceptance Criteria
Entities exist in the repo with appropriate columns

**Comment by SimeraHailu** [comment]
Units

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/f8ffe1f9-25cc-429c-874c-c44e70c3c01d/download](https://app.zenhub.com/files/287570343/f8ffe1f9-25cc-429c-874c-c44e70c3c01d/download)

**Comment by junie-stigdon** [comment]
Mapping out potential DTOs that could eliminate the need for certain entities.

**Comment by junie-stigdon** [comment]
Completed entities, waiting for peer review before submitting a merge request.
