### ISSUE TITLE
API Endpoint - View Unit Default Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3000]
Create GET endpoints (4) for Unit Default Test Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Fuel Code (Dropdown)
NOX Default Rate (Text)
Operating Condition Code (Dropdown - A, B, P)
Group ID (Text)
Number of Units in Group (Text)
Number of Tests for Group (Text)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/308

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1336](https://epacamd.testquality.com/project/11428/plan/28118/test/412007)
Test Passed

**Comment by mosesdeeCVP** [comment]
View Unit Default Test Data API - Official
![View Unit Default Test Data API - Official .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/434082f3-62d1-48be-93f8-da1dce2ff2d7)

View Unit Default Test Data API - Official with ID
![View Unit Default Test Data API - Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/db8929ca-ae8c-4567-b996-5fa0465457b2)

View Unit Default Test Data API - Workspace
![View Unit Default Test Data API - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2f137e91-c3e8-4a4b-b4ab-f6132e643d8d)

View Unit Default Test Data API - Workspace with ID
![View Unit Default Test Data API - Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4c3268d6-d024-4e72-b6da-9c755f9ab455)
