### ISSUE TITLE
API Endpoint - Add Unit Default Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3001]
API Endpoint - Add Unit Default Test Data

Testing Reference Only:
Fuel Code (Dropdown)
NOX Default Rate (Text)
Operating Condition Code (Dropdown - A, B, P)
Group ID (Text)
Number of Units in Group (Text)
Number of Tests for Group (Text)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/307

**Comment by mosesdeeCVP** [comment]
![Unit Default Test - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5d459df1-2a74-40c2-ab47-521451afaaf9)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1128](https://epacamd.testquality.com/project/11428/plan/28118/test/411333)
Test Passed
