### ISSUE TITLE
Global 'View' and Workspace 'Add': Unit Default Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3002]
As an ECMPS user, I want to view Unit Default Test Data in the Global-View and add new Unit Default Test Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Unit Default from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

Fuel Code 
NOX Default Rate
Operating Condition Code
Group ID
Number of Units in Group
Number of Tests for Group

Given a user is viewing Unit Default Test Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [x] Yes 
- [ ] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Unit Default from the Test Type Group dropdown
When the user clicks on 'Add' for Unit Default Test Data
Then the system displays a modal
and the user can add new data for:

Fuel Code (Dropdown)
NOX Default Rate (Text)
Operating Condition Code (Dropdown - A, B, P)
Group ID (Text)
Number of Units in Group (Text)
Number of Tests for Group (Text)

Given the user has added Unit Default Test Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Unit Default Test record is reflected on the UI

Given the user has added a new Unit Default Test Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Unit Default Test Data
And no updates are saved

**Dev Note:** **This data section is at the second level of nesting (Test Data -> Unit Default Test )**

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0c839cd4-3136-490a-9fdb-4d2e3f913d32)

**Comment by JanellC** [comment]
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6c5e9222-691c-4fb2-a72b-cb86a6fb0265)

**Comment by mosesdeeCVP** [comment]
Unit Default Test - View Modal Official
![Unit Default Test - View Modal Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/398946d0-b7e9-4d67-a223-b987e7d4de33)

**Comment by mosesdeeCVP** [comment]
Unit Default Test - Add
![Unit Default Test - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/79fcb824-860d-4781-91bb-60cae02d22db)

**Comment by mosesdeeCVP** [comment]
Unit Default Test - Operating Condition Code
![Unit Default Test - Operating Condition Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a8813b12-a9c7-46df-8170-39d07546237c)

**Comment by mosesdeeCVP** [comment]
Unit Default Test - View Table Official
![Unit Default Test - View Table Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6296f939-9a1c-4c0c-bc9d-a8a74928b923)

**Comment by mosesdeeCVP** [comment]
Unit Default Test - Add
![Unit Default Test - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cbb11f80-3c74-41b8-bad7-5700481a2a68)

**Comment by mosesdeeCVP** [comment]
The Operating Condition Code (Dropdown - A, B, P) does not filter. This will be worked on in a separate ticket.

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1144](https://epacamd.testquality.com/project/11428/plan/28118/test/413258)
Test Passed
