### ISSUE TITLE
Edit Unit Default Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3004]
As an ECMPS user (logged-in), I want to update Unit Default Test data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Unit Default Test from the Test Type Group dropdown
When the user selects 'Edit' for Unit Default Test Data
Then the system displays the edit modal
And the user can edit Unit Default Test Data

Fuel Code (Dropdown)
NOX Default Rate (Text)
Operating Condition Code (Dropdown - A, B, P)
Group ID (Text)
Number of Units in Group (Text)
Number of Tests for Group (Text)

Given the user has updated Unit Default Test Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Unit Default Test Data
And the updates are reflected in the Unit Default Test data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0a375b18-ee0c-434e-b7b6-b96dcc30fdec)

**Comment by mosesdeeCVP** [comment]
![Edit Unit Default Test.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d67599b2-922f-4042-8d79-524ffae7f563)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1148](https://epacamd.testquality.com/project/11428/plan/28118/test/413569)
Test Passed
