### ISSUE TITLE
Remove Unit Default Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3006]
As an ECMPS user, I want the ability to remove Unit Default Test Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Unit Default Test Data section
When I click on the 'Remove' option for Unit Default Test Data
Then I see that the relevant Unit Default Test data record is deleted

Given I chose to remove Unit Default Test Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Unit Default Test data section
When I select Cancel
Then I am returned to the landing screen for Unit Default Test

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1146](https://epacamd.testquality.com/project/11428/plan/28118/test/413568)
Test Passed
