### ISSUE TITLE
Global 'View' and Workspace 'Add': Appendix E Heat Input From Oil Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3007]
As an ECMPS user, I want to view Appendix E Heat Input From Oil Data in the Global-View and add new Appendix E Heat Input From Oil Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown and a Appendix E Heat Input From Oil data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Monitoring System ID
Oil Mass
Oil GCV
Oil GCV Units of Measure Code
Oil Heat Input
Oil Volume
Oil Volume Units of Measure Code
Oil Density
Oil Density Units of Measure Code

Given a user is viewing Appendix E Heat Input From Oil Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Appendix E Heat Input From Oil Data
Then the system displays a modal
and the user can add new data for:

Monitoring System ID (Dropdown to display all Monitoring System ID's assigned to the oil fuel flow of OILV or OILM)
Oil Mass (Text)
Oil GCV (Text)
Oil GCV Units of Measure Code (Dropdown)
Oil Heat Input (Text)
Oil Volume (Text)
Oil Volume Units of Measure Code (Dropdown)
Oil Density (Text)
Oil Density Units of Measure Code (Dropdown)

Given the user has added Appendix E Heat Input From Oil Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Appendix E Heat Input From Oil record is reflected on the UI

Given the user has added a new Appendix E Heat Input From Oil Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Appendix E Correlation Summary
And no updates are saved

**Dev Note:** **Nesting = Test Summary -> Appendix E Summary -> Run ->  Appendix E Heat Input From Oil Data)**
Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1039 ](https://epacamd.testquality.com/project/11428/plan/27381/test/402772)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Appendix E Heat Input From Oil Data - View Table

![Appendix E Heat Input From Oil Data - View Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4850636f-c91c-4be0-ad03-7e48ff7e7fe1)

**Comment by mosesdeeCVP** [comment]
Appendix E Heat Input From Oil Data - View Modal

![Appendix E Heat Input From Oil Data - View Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b6c450fc-b827-4d59-a9f2-432588cfdcdf)

**Comment by mosesdeeCVP** [comment]
Appendix E Heat Input From Oil Data - Add

![Appendix E Heat Input From Oil Data - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/86f501ca-6a4e-422c-b874-afc046d6c4ae)

**Comment by mosesdeeCVP** [comment]
Test Passed
