### ISSUE TITLE
Edit Appendix E Heat Input From Oil Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3008]
As an ECMPS user (logged-in), I want to update Appendix E Heat Input From Oil data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Appendix E Correlation Summary from the Test Type Group dropdown
When the user selects 'Edit' for Appendix E Heat Input From Oil data
Then the system displays the edit modal
And the user can edit Appendix E Heat Input From Oil data

Monitoring System ID (Not editable)
Oil Mass (Text)
Oil GCV (Text)
Oil GCV Units of Measure Code (Dropdown)
Oil Heat Input (Text)
Oil Volume (Text)
Oil Volume Units of Measure Code (Dropdown)
Oil Density (Text)
Oil Density Units of Measure Code (Dropdown)

Given the user has updated Appendix E Heat Input From Oil data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Appendix E Correlation Summary data
And the updates are reflected in the Appendix E Heat Input From Oil data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1038](https://epacamd.testquality.com/project/11428/plan/27381/test/402682)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Appendix E Heat Input From Oil Data - Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cda6b2c8-6fc8-4f07-8b4a-af82c8f36ee1)

**Comment by mosesdeeCVP** [comment]
Test Passed
