### ISSUE TITLE
Create Facility data DTOs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#301]
## Development Tasks
- [x] Create facility DTO
- [x] Create contacts DTO
- [x] Create units DTO
- [x] Create MP DTO
- [x] Create filters DTO

## Acceptance Criteria
DTOs exist with appropriate data and criteria

**Comment by junie-stigdon** [comment]
Drafting objects to be returned

**Comment by junie-stigdon** [comment]
### Created sub folders for DTOs:

#### filters
- facilities-filter.dto.ts
- mp-filter.dto.ts
- units-filter.dto.ts

#### units
- get-unit-by-id.dto.ts
- get-units.dto.ts
- unit-ce-param.dto.ts
- unit-fuel.dto.ts
- unit-program.dto.ts

**Comment by sdhawan16** [comment]
### Added additional sub folders for DTOs:

#### contacts

- contact-person.dto.ts
- contact-unit.dto.ts
- get-contacts.dto.ts

#### monitoring-plans

- get-monitoring-plans.dto.ts
- monitoring-plan-unit-stack.dto.ts
