### ISSUE TITLE
API Endpoint - View Appendix E Heat Input From Oil Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3012]
Create GET endpoints (4) for Appendix E Heat Input From Oil Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Monitoring System ID (Text)
Oil Mass (Text)
Oil GCV (Text)
Oil GCV Units of Measure Code (Dropdown)
Oil Heat Input (Text)
Oil Volume (Text)
Oil Volume Units of Measure Code (Dropdown)
Oil Density (Text)
Oil Density Units of Measure Code (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC978](3012 API Endpoint - View Appendix E Heat Input From Oil Data)
Test Passed
