### ISSUE TITLE
Edit Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3014]
As an ECMPS user (logged-in), I want to update Appendix E Heat Input From Gas data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Appendix E Correlation Summary from the Test Type Group dropdown
When the user selects 'Edit' for Appendix E Heat Input From Gas data
Then the system displays the edit modal
And the user can edit Appendix E Heat Input From Gas data

Gas GCV (Text) 
Gas Volume (Text)
Gas Heat Input (Text)

Given the user has updated Appendix E Heat Input From Gas data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Appendix E Correlation Summary data
And the updates are reflected in the Appendix E Heat Input From Gas data section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case: [TC1076](https://epacamd.testquality.com/project/11428/plan/27381/test/406782)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Appendix E Heat Input From Gas  - EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/32e0ff4d-73a5-4f3a-a9cb-495b16465ace)
