### ISSUE TITLE
Global 'View': Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3015]
As an ECMPS user, I want to view Appendix E Heat Input From Gas data in the Global-View so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown and a Appendix E Heat Input From Gas data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Gas GCV (Text)
Gas Volume (Text)
Gas Heat Input (Text)

Given a user is viewing Appendix E Heat Input From Gas data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [X] No

## Testing 
Test Case: [TC1003](https://epacamd.testquality.com/project/11428/plan/27381/test/400554)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC1003 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0c2a52b4-7780-4af3-b4fc-7477c4df24b1)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/60589fa9-b0a6-474b-b9ad-d9b152c47de1)
