### ISSUE TITLE
Remove Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3016]
As an ECMPS user, I want the ability to remove Appendix E Heat Input From Gas data so that I can update data as needed

Acceptance Criteria:
Given I am in the Appendix E Correlation Summary Data section
When I click on the 'Remove' option for Appendix E Heat Input From Gas data
Then I see that the relevant Appendix E Heat Input From Gas data record is deleted

Given I chose to remove Appendix E Heat Input From Gas data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Appendix E Correlation Summary data section
When I select Cancel
Then I am returned to the landing screen for Appendix E Correlation Summary

Invision Board:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing
Test Case: [TC1075](https://epacamd.testquality.com/project/11428/plan/27381/test/406781)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
