### ISSUE TITLE
API Endpoint - View Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3018]
Create GET endpoints (4) for Appendix E Heat Input From Gas Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

**Tesing Reference Only:**
Monitoring System ID
Gas GCV
Gas Volume
Gas Heat Input

**Comment by mosesdeeCVP** [comment]
Test Case: [TC974](https://epacamd.testquality.com/project/11428/plan/27381/test/398460)

**Comment by mosesdeeCVP** [comment]
All endpoints except Official record View work
locId: 5736
testSumId: LUVM-20014-D21EF337C0E642E498FF1A4ED054C95D
appECorrTestSumId: LUVM-20014-2038D2985EC64FF2BB87F14DF6A16ECB
appECorrTestRunId: LUVM-20014-6BB2C1C89C3A4759854B316F0DFEEA2F
id: LUVM-20014-ADC9BDC1B5744039A192D6C015792602

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1c8e6218-d1df-44e4-b57f-42368165dd33)

**Comment by vishnunavuluri** [comment]
Throwing a 500 error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ce1877c2-91e8-4339-be4e-5ed1d05d3956)

Throwing a 404 error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/f400ea7a-4d8a-4f1e-ad42-c5e24cc10fca)

**Comment by mosesdeeCVP** [comment]
Bug Ticket Created: [Bug: View Appendix E Heat Input From Gas Data #4337](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/4337)
