### ISSUE TITLE
API Endpoint - View Fuel Flow To Load Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3019]
Create GET endpoints (4) for Fuel Flow To Load Test Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:

Test Basis Code (Dropdown)
Average Difference (Text)
Number of Hours Used (Text)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

## Testing 
Test Case: [TC964](https://epacamd.testquality.com/project/11428/plan/27145/test/398096)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Fuel Flow To Load Test Data - GET Workspace

![Fuel Flow To Load Test Data - GET Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ed93990c-fe05-4f36-9820-40d2642d5c52)

**Comment by mosesdeeCVP** [comment]
Fuel Flow To Load Test Data - GET Workspace with ID

![Fuel Flow To Load Test Data - GET Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e216dfc2-176d-45dd-8e39-952eeb14f29e)

**Comment by mosesdeeCVP** [comment]
Fuel Flow To Load Test Data - GET Global

![Fuel Flow To Load Test Data - GET Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b17f250d-d41a-433b-937b-22886ddc77ca)

**Comment by mosesdeeCVP** [comment]
Fuel Flow To Load Test Data - GET Global with ID

![Fuel Flow To Load Test Data - GET Global with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8ca58453-9a08-427b-bf2f-f3cad4e89d9a)

**Comment by mosesdeeCVP** [comment]
Global View
Facility - Ocotillo Power Plant (116)
lodId 32
testSumId EPA-292384737EE4B7373E85FB06CAAA146C
id EPA-22A134B872D7E4A12D1DCB2EC3C6E7FE

**Comment by mosesdeeCVP** [comment]
Test Passed
