### ISSUE TITLE
STORY: Validate state for hourly apportioned emissions

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#302]
## User Story
As a user I want to enter valid filter criteria for state so that I can see results

## Acceptance Criteria

Given that a user has entered valid filter criteria for state (see below) 
When the API endpoint is executed
Then the system validates the criteria and displays the results

Given that a user has entered invalid filter criteria for state (see below)
When the API endpoint is executed
Then the system will return a validation error collection (FV-4)

## Testing
Test Case: [TC68](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268890)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R15](https://cvpcorp.testquality.com/project/11428/testcase/268890/requirement/11057). Do not remove or edit.

**Comment by junie-stigdon** [comment]
@tlageman-epa Added dev tasks to story:
- #601 Create State Entity and Repo
- #603  Add State Validation

**Comment by david-cvp** [comment]
began testing 12/28, will get test cases approved tomorrow 12/29

**Comment by david-cvp** [comment]
TC68 passes
