### ISSUE TITLE
Global 'View' and Workspace 'Add':  Fuel Flow To Load Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3020]
As an ECMPS user, I want to view Fuel Flow To Load Test Data in the Global-View and add new Fuel Flow To Load Test Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Fuel Flow To Load from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Test Basis Code (Dropdown)
Average Difference (Text)
Number of Hours Used (Text)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

Given a user is viewing Fuel Flow To Load Test Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Fuel Flow To Load from the Test Type Group dropdown
When the user clicks on 'Add' for Fuel Flow To Load Data
Then the system displays a modal
and the user can add new data for:

Test Basis Code (Dropdown)
Average Difference (Text)
Number of Hours Used (Text)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

Given the user has added  Fuel Flow To Load Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the  Fuel Flow To Load Data record is reflected on the UI

Given the user has added a new  Fuel Flow To Load Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for  Fuel Flow To Load Data
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing
Test Case: [TC1000](https://epacamd.testquality.com/project/11428/plan/27145/test/400549)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Global UI Table View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d9772b31-d230-4309-9c63-d0f73999acc6)

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Global UI Modal View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/158afae4-d871-4e26-b393-cb04b35f3e34)

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Workspace UI Table View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e7bc978-5832-4457-8119-412fa1a05554)

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Workspace UI Modal View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dccca83f-4722-41f8-942e-443f3497fec3)

**Comment by mosesdeeCVP** [comment]
Test Passed
