### ISSUE TITLE
Remove Fuel Flow To Load Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3022]
As an ECMPS user, I want the ability to remove Fuel Flow To Load Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Fuel Flow To Load data section
When I click on the 'Remove' option for Fuel Flow To Load
Then I see that the relevant Fuel Flow To Load data record is deleted

Given I chose to remove Fuel Flow To Load Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Fuel Flow To Load data section
When I select Cancel
Then I am returned to the landing screen for Fuel Flow To Load Data

Invision Board:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing
Test Case: [TC1008](https://epacamd.testquality.com/project/11428/plan/27145/test/400678)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC1008 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/06aa0417-7d1c-4906-b0f7-2232db581b25)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/bea81db7-2c4d-4b84-8e9f-6f0dea3f740d)
