### ISSUE TITLE
Create MDM Endpoint for Test Basis Code (Fuel Flow To Load Test Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3023]
Create MDM Endpoint for Test Basis Code 

Testing Reference Only:
Values: Q, H and Null/Blank

## Testing 
Test Case: [TC294](https://epacamd.testquality.com/project/11428/plan/27145/test/393048)
Tester: @JanellC

**Comment by billmiller13** [comment]
DB Table:  camdecmpsmd.test_basis_code
Columns: test_basis_cd, test_basis_description

**Comment by JanellC** [comment]
TC294 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c8426fc5-3ea0-4ce8-8dd7-f6490ac62fe9)
