### ISSUE TITLE
Global 'View' and Workspace 'Add': Fuel Flow To Load Baseline Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3027]
As an ECMPS user, I want to view Fuel Flow To Load Baseline Data in the Global-View and add new Fuel Flow To Load Baseline Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Fuel Flow To Load Baseline from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Accuracy Test Number
PEI Test Number 
Average Fuel Flow Rate
Average Load
Baseline Fuel Flow-to-Load Ratio
Fuel Flow-to-Load UOM Code
Average Hourly Heat Input Rate
Baseline GHR
GHR UOM Code 
Number of Hours Excluded Co-firing
Number of Hours Excluded Ramping
Number of Hours Excluded Low Range

Given a user is viewing Fuel Flow To Load Baseline 
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Fuel Flow To Load Baseline from the Test Type Group dropdown
When the user clicks on 'Add' for Fuel Flow To Load Baseline data
Then the system displays a modal
and the user can add new data for:

Accuracy Test Number (Text)
PEI Test Number (Text)
Average Fuel Flow Rate (Text)
Average Load (Text)
Baseline Fuel Flow-to-Load Ratio (Text)
Fuel Flow-to-Load UOM Code (Dropdown)
Average Hourly Heat Input Rate (Text)
Baseline GHR (Text)
GHR UOM Code (Dropdown)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

Given the user has added Fuel Flow To Load Baseline data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Fuel Flow To Load Baseline data record is reflected on the UI

Given the user has added a new Fuel Flow To Load Baseline record
When the user chooses to Cancel
Then the user is returned to the Landing screen for Fuel Flow To Load Baseline 
And no updates are saved

**Label for the section: Fuel Flow To Load Baseline**

Reference Invision URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1051](https://epacamd.testquality.com/project/11428/plan/27735/test/403229)
Tester @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Baseline - View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b025c800-0b3c-4206-a68c-7759212b1418)

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Baseline - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5d6440e7-3902-4d91-bcd0-7f6bfbaef754)

![Fuel Flow To Load Baseline - Add Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7875f7bb-d76c-4070-b570-4f155ea957c3)
