### ISSUE TITLE
Remove Fuel Flow To Load Baseline Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3028]
As an ECMPS user, I want the ability to remove Fuel Flow To Load Baseline data so that I can update data as needed

Acceptance Criteria:
Given I am in the Fuel Flow To Load Baseline data section
When I click on the 'Remove' option for Fuel Flow To Load Baseline 
Then I see that the relevant Fuel Flow To Load Baseline data record is deleted

Given I chose to remove Fuel Flow To Load Baseline Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Fuel Flow To Load Baseline data section
When I select Cancel
Then I am returned to the landing screen for Fuel Flow To Load Baseline Data

Invision Board URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing
Test Case: [TC1061](https://epacamd.testquality.com/project/11428/plan/27735/test/406148)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1061 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d6dbf0ba-3e51-482c-92f4-4e7eee83e6ef)
