### ISSUE TITLE
API Endpoint - View Fuel Flow To Load Baseline Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3029]
Create GET endpoints (4) for Fuel Flow To Load Baseline Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Accuracy Test Number (Text)
PEI Test Number (Text)
Average Fuel Flow Rate (Text)
Average Load (Text)
Baseline Fuel Flow-to-Load Ratio (Text)
Fuel Flow-to-Load UOM Code (Dropdown)
Average Hourly Heat Input Rate (Text)
Baseline GHR (Text)
GHR UOM Code (Dropdown)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC991](https://epacamd.testquality.com/project/11428/plan/27145/test/399979)
Test Passed

**Comment by mosesdeeCVP** [comment]
View Fuel Flow To Load Baseline Data

![3029 API Endpoint - View Fuel Flow To Load Baseline Data - Official .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f7ad5455-7fc2-4bc1-ab43-7bdee9324355)

**Comment by mosesdeeCVP** [comment]
View Fuel Flow To Load Baseline Data

![3029 API Endpoint - View Fuel Flow To Load Baseline Data - Official With ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c9047430-ff1e-4b85-8d1c-4f9a7fe78910)

**Comment by mosesdeeCVP** [comment]
View Fuel Flow To Load Baseline Data

![3029 API Endpoint - View Fuel Flow To Load Baseline Data - Workspace .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7d0771c9-c2f8-4da2-9412-ecdf9693d9ba)

**Comment by mosesdeeCVP** [comment]
View Fuel Flow To Load Baseline Data

![3029 API Endpoint - View Fuel Flow To Load Baseline Data - Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d56d67f8-9c01-4eb0-bec5-a3032a382314)
