### ISSUE TITLE
Global 'View' and Workspace 'Add': Transmitter Transducer Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3031]
As an ECMPS user, I want to view Transmitter Transducer Accuracy Data in the Global View and add new Transmitter Transducer Accuracy Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Transmitter Transducer Accuracy from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Low Level Accuracy
Low Level Accuracy Spec Code
Mid Level Accuracy 
Mid Level Accuracy Spec Code
High Level Accuracy 
High Level Accuracy Spec Code

Given a user is viewing Transmitter Transducer Accuracy Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Transmitter Transducer Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Transmitter Transducer Accuracy Data
Then the system displays a modal
and the user can add new data for:

Low Level Accuracy (Text)
Low Level Accuracy Spec Code (Dropdown)
Mid Level Accuracy (Text)
Mid Level Accuracy Spec Code (Dropdown)
High Level Accuracy (Text)
High Level Accuracy Spec Code (Dropdown)

Given the user has added Transmitter Transducer Accuracy Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Transmitter Transducer Accuracy Data record is reflected on the UI

Given the user has added a new Transmitter Transducer Accuracy Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Transmitter Transducer Accuracy Data
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1127](https://epacamd.testquality.com/project/11428/plan/27874/test/411332)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Add Transmitter Transducer Accuracy Data
![Add Transmitter Transducer Accuracy Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3640c8a0-29de-4b9f-a9bd-1ed7e13b22c3)

**Comment by mosesdeeCVP** [comment]
View Transmitter Transducer Accuracy Data - Table
![View Transmitter Transducer Accuracy Data - Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b2fe0419-a3a0-44ca-82b3-40616146b5cb)

View Transmitter Transducer Accuracy Data - Modal
![View Transmitter Transducer Accuracy Data - Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9bdb3208-3f28-4be8-8c83-869cb94a60ed)

**Comment by mosesdeeCVP** [comment]
Test Passed
