### ISSUE TITLE
Remove Transmitter Transducer Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3034]
As an ECMPS user, I want the ability to remove Transmitter Transducer Accuracy Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Transmitter Transducer Accuracy data section
When I click on the 'Remove' option for Transmitter Transducer Accuracy
Then I see that the relevant Transmitter Transducer Accuracy data record is deleted

Given I chose to remove Transmitter Transducer Accuracy Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Transmitter Transducer Accuracy data section
When I select Cancel
Then I am returned to the landing screen for Transmitter Transducer Accuracy Data

Invision Board:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

## Testing 
Test Case: [TC1117 ](https://epacamd.testquality.com/project/11428/plan/27874/test/411231)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
