### ISSUE TITLE
API Endpoint - View Transmitter Transducer Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3035]
Create GET endpoints (4) for Transmitter Transducer Accuracy Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:

- Low Level Accuracy (Text)
- Low Level Accuracy Spec Code (Dropdown)
- Mid Level Accuracy (Text)
- Mid Level Accuracy Spec Code (Dropdown)
- High Level Accuracy (Text)
- High Level Accuracy Spec Code (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1094](https://epacamd.testquality.com/project/11428/plan/27874/test/407901)

**Comment by mosesdeeCVP** [comment]
View Transmitter Transducer Accuracy - View Official

![View Transmitter Transducer Accuracy - View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/32f13909-1acd-45db-a5cb-9a8f750798b3)

**Comment by mosesdeeCVP** [comment]
View Transmitter Transducer Accuracy - View Official with ID

![View Transmitter Transducer Accuracy - View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2844258f-e3f4-42da-8492-908eddaaa52c)

**Comment by mosesdeeCVP** [comment]
View Transmitter Transducer Accuracy - View Workspace

![View Transmitter Transducer Accuracy - View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2000d84d-4148-4ae7-af5b-05d18245a26a)

**Comment by mosesdeeCVP** [comment]
View Transmitter Transducer Accuracy - View Workspace ID

![View Transmitter Transducer Accuracy - View Workspace ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/12c853e3-26c7-40bf-bfe6-e19490148f1e)

**Comment by mosesdeeCVP** [comment]
Test Passed
