### ISSUE TITLE
API Endpoint - Add Transmitter Transducer Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3036]
Add an API Endpoint to create/add Transmitter Transducer Accuracy Data

Testing Reference Only:

Low Level Accuracy (Text)
Low Level Accuracy Spec Code (Dropdown)
Mid Level Accuracy (Text)
Mid Level Accuracy Spec Code (Dropdown)
High Level Accuracy (Text)
High Level Accuracy Spec Code (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1095](https://epacamd.testquality.com/project/11428/plan/27874/test/407902)

**Comment by mosesdeeCVP** [comment]
![View Transmitter Transducer Accuracy - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/df3a996e-5d7b-46dc-9d3e-34f54c2cfb45)

**Comment by mosesdeeCVP** [comment]
Test Passed
