### ISSUE TITLE
API Endpoint - View Fuel Flowmeter Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3037]
Create GET endpoints (4) for Fuel Flowmeter Accuracy Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Accuracy Test Method Code (Dropdown)
Low Fuel Accuracy (Text)
Mid Fuel Accuracy (Text)
High Fuel Accuracy (Text)
Reinstallation Date (Datepicker+Text)
Reinstallation Hour (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1083](https://epacamd.testquality.com/project/11428/plan/27838/test/407263)
Test Passed

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy - Official

Fuel Flowmeter Accuracy (Official):
Facility: Smith Generating Facility (54)

![Fuel Flowmeter Accuracy - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/65c43c9d-ba2d-4848-a916-2dec2424371c)

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy - Official - with ID

![Fuel Flowmeter Accuracy - Official - with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4432238a-c02a-4562-90f6-fa4a707ef008)

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy - workspace

![Fuel Flowmeter Accuracy - workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/df8ef2f0-b4cd-4e50-b2c5-5b305c9191ce)

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy - workspace with ID

![Fuel Flowmeter Accuracy - workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0412d409-d036-4b87-93e8-0b577acaeb4f)
