### ISSUE TITLE
Global 'View' and Workspace 'Add':  Fuel Flowmeter Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3039]
As an ECMPS user, I want to view Fuel Flowmeter Accuracy Data in the Global-View and add new Fuel Flowmeter Accuracy Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Fuel Flowmeter Accuracy from the Test Type Group dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table (see list below for columns and order)

Accuracy Test Method Code 
Low Fuel Accuracy
Mid Fuel Accuracy
High Fuel Accuracy
Reinstallation Date
Reinstallation Hour

Given a user is viewing Fuel Flowmeter Accuracy Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Fuel Flowmeter Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Fuel Flowmeter Accuracy data
Then the system displays a modal
and the user can add new data for:

Accuracy Test Method Code (Dropdown)
Low Fuel Accuracy (Text)
Mid Fuel Accuracy (Text)
High Fuel Accuracy (Text)
Reinstallation Date (Datepicker+Text)
Reinstallation Hour (Dropdown)

Given the user has added Fuel Flowmeter Accuracy Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Fuel Flowmeter Accuracy Data record is reflected on the UI

Given the user has added a new Fuel Flowmeter Accuracy Data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Fuel Flowmeter Accuracy  
And no updates are saved

**Label on the UI: Fuel Flowmeter Accuracy** 
No mandatory fields

Reference Invision URL:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy Data Official View Table
![Fuel Flowmeter Accuracy Data Official View Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4112a590-6b55-4764-bfe8-6c0ffaee42f6)

Fuel Flowmeter Accuracy Data Official View Modal
![Fuel Flowmeter Accuracy Data Official View Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5848753d-5f9b-4a65-8134-8b23c9fd1235)

**Comment by mosesdeeCVP** [comment]
Fuel Flowmeter Accuracy Data Official Add
![Fuel Flowmeter Accuracy Data Official Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9e10c49f-3714-44f1-8aa1-aff5d44da858)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1134](https://epacamd.testquality.com/project/11428/plan/27838/test/411529)
Test Passed
