### ISSUE TITLE
Remove Fuel Flowmeter Accuracy Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3042]
As an ECMPS user, I want the ability to remove Fuel Flowmeter Accuracy Data so that I can update data as needed

Acceptance Criteria:
Given I am in the Fuel Flowmeter Accuracy data section
When I click on the 'Remove' option 
Then I see that the relevant Fuel Flowmeter Accuracy record is deleted

Given I chose to remove Fuel Flowmeter Accuracy Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Fuel Flowmeter Accuracy data section
When I select Cancel
Then I am returned to the landing screen for Fuel Flowmeter Accuracy Data

Invision Board:
https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2ZG45YWJsMDBkcTNiN3BocGZ4b2licg%3D%3D

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1124](https://epacamd.testquality.com/project/11428/plan/27838/test/411323)
Test Passed
