### ISSUE TITLE
Add Linearity Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3046]
As an ECMPS user (logged-in), I want to add Linearity Injection data so that I can add information to a test

Acceptance Criteria:

Given the user has selected Linearity Summary from the Test Type group dropdown
When the user clicks on 'Add' for Linearity Injection Data
Then the system displays a modal
and the user can add new data for:

Injection Date (Date Picker and Text)
Injection Hour (Dropdown 0-23)
Injection Minute (Dropdown 0-59)
Measured Value (Text)
Reference Value (Text)

Given the user has added Linearity Injection data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen for Linearity Summary data
And the Injection Record is reflected on the UI

Given the user has added new 'Injection Records' (Linearity Summary)
When the user chooses to Cancel
Then the user is returned to the Landing screen for Linearity Summary data
And no updates are saved

The scope of this ticket includes Add Linearity Injection records under all 3 Summary Levels (High, Mid and Low)

Dev Notes:
Users shall be able to add data from scratch when there is no existing Injection Records

Reference Screenshots:
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2NDBmaGFsMDAwMzNiNnk3Zzh0ZTlpNw%3D%3D
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2Y2FzMTc1MDAwMjNiNnlhcXFwNTk3eQ%3D%3D

## Testing 
Test Case: [TC836](https://epacamd.testquality.com/project/11428/plan/25475/test/383612)
Tester: @mosesdeeCVP

**Comment by NadiaJL** [comment]
Xd Prototype: https://xd.adobe.com/view/b00f424e-f5f1-4d4e-ae7f-c962310e17c4-e55c/screen/a9be651e-c8e7-4461-bc20-e50e3144bc5d/
