### ISSUE TITLE
Global View: Linearity Injection Data Table

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3048]
As an ECMPS user, I want to view Linearity Summary Injection data so that I can look at real-time data.

Acceptance Criteria
Given a user has selected Linearity Summary from the Test Type Group dropdown and a linearity injection data record is available
When the QA test summary linearity injection data is displayed
Then the data is displayed nested under the linearity summary table as a separate table (see list below for columns and order)

Injection Date
Injection Hour
Injection Minute
Measured Value
Reference Value

Given a user is viewing Linearity Injection Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

API Endpoint:
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Linearity%20Injection
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3f0bf54f-ab16-4865-ad81-4289a77b85ae)

Invision URL:
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2Y2FhczRzMDAwMjNiNnlxbWRjMWtycQ%3D%3D
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2Y2FhczU2MDAwMzNiNnlhY3FkZXdjYw%3D%3D

## Testing 
Test Case: [TC835](https://epacamd.testquality.com/project/11428/plan/25475/test/383608)
Tester @mosesdeeCVP

**Comment by NadiaJL** [comment]
LoFi WFs > InVision Board: https://projects.invisionapp.com/freehand/document/TdahPfbEb

**Comment by NadiaJL** [comment]
Xd Prototype: https://xd.adobe.com/view/40aa3540-d85f-4b68-9bf2-63f694bee243-15f9/screen/e67af277-4135-4f37-bbfc-112eb383e0cc/

**Comment by mosesdeeCVP** [comment]
![3048 Global View- Linearity Injection Data Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bf932017-38f4-4c2f-b9ab-2d46758003e0)

**Comment by mosesdeeCVP** [comment]
Test Passed
