### ISSUE TITLE
Remove Linearity Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3049]
As an ECMPs user, I want the ability to remove Linearity Summary data so that I can update QA Test Summary data as needed

Acceptance Criteria:

Given I am in the Linearity Summary Data section
When I click on the 'Remove' option
Then I see that the relevant Linearity Summary data record is deleted
And the Test Summary Data is updated accordingly

Given I chose to remove Linearity Summary Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
When I select Cancel
Then I am returned to the landing screen for the Linearity Summary section

Note: Scope of this ticket also includes refactoring 'Remove' functionality at the Test Summary Level (Retest 3776)

Swagger URl Reference: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Linearity%20Summary/LinearitySummaryWorkspaceController_deleteLinearitySummary

## Testing 
Test Case[: TC803](https://epacamd.testquality.com/project/11428/plan/25475/test/379688)
Tester: @JanellC

**Comment by JanellC** [comment]
Test Summary 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d42a184a-2227-49c8-a395-8ca70a216f8c)
TC803 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/22eb9746-6f1f-4b78-a23f-ed70890ae3c7)

Linearity Summary 
![image.png](https://ima![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9242e039-084e-4c81-aac4-07f206e585d7)ges.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ac9d535e-199f-4cba-8a9f-53f76dee5e31)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3dd05071-f38b-4694-af2a-b682cf387388)
