### ISSUE TITLE
API Endpoint - Remove QA Certification Events

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3052]
Create API Endpoint to remove/delete QA Certification Events

**Comment by mosesdeeCVP** [comment]
![Remove Cert Event.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/eba92e34-3c31-40de-80a9-f7cf47494fc5)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1194](https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/QA%20Certification%20Event/QaCertificationEventWorkshopController_deleteTestExtensionExemption)
Test Passed
