### ISSUE TITLE
API Endpoint - View QA Certification Events Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3053]
Create GET endpoints (4) for QA Certification Events Data

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

**Testing Reference Only:**
Unit or Stack Pipe ID (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
QA Cert Event Code (Dropdown)
QA Cert Event Date (Datepicker and Text)
QA Cert Event Hour (Dropdown)
Required Test Code (Dropdown)
Conditional Begin Date (Datepicker and Text)
Conditional Begin Hour (Dropdown)
Completion Test Date (Datepicker and Text)
Completion Test Hour (Dropdown)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1195](https://epacamd.testquality.com/project/11428/plan/28427/test/419436)

**Comment by mosesdeeCVP** [comment]
QA Certification Event View - Official
![QA Certification Event View - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d252fb69-9987-43ec-a338-886781e6c0a2)

**Comment by mosesdeeCVP** [comment]
QA Certification Event View - Official with ID
![QA Certification Event View - Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a30ff9f4-68cd-4776-b7d8-0a2aef999a10)

**Comment by mosesdeeCVP** [comment]
QA Certification Event View - Workspace
![QA Certification Event View - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c39f2bb4-67d8-4b5a-8d69-7552f841eda7)

**Comment by mosesdeeCVP** [comment]
QA Certification Event View - Workspace with ID
![QA Certification Event View - Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/646cea76-7b6f-4b13-82a9-ed23ef2baa9a)

**Comment by mosesdeeCVP** [comment]
Test Passed
