### ISSUE TITLE
API Endpoint - Add QA Certification Event Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3054]
Add an API Endpoint to create/add QA Certification Event Data

**Testing Reference Only:**
Unit or Stack Pipe ID (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
QA Cert Event Code (Dropdown)
QA Cert Event Date (Datepicker and Text)
QA Cert Event Hour (Dropdown)
Required Test Code (Dropdown)
Conditional Begin Date (Datepicker and Text)
Conditional Begin Hour (Dropdown)
Completion Test Date (Datepicker and Text)
Completion Test Hour  (Dropdown)

**Comment by mosesdeeCVP** [comment]
Facility - Zuni (478)
Unit ID: 1
locId: 276

![3054 API Endpoint - Add QA Certification Event Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f6ae9481-7b48-4c36-86b3-b9097ad3fc3e)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1189](https://epacamd.testquality.com/project/11428/plan/28427/test/416628)
Test Passed
