### ISSUE TITLE
API Endpoint - Remove QA Test Extensions Exemptions

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3057]
Create API Endpoint to remove/delete QA Test Extensions Exemptions

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1193](https://epacamd.testquality.com/project/11428/plan/28527/test/418647)
Test Passed

**Comment by mosesdeeCVP** [comment]
![Test Extensions Exemptions Data - Delete.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04ce201d-21cd-48e0-8d3e-ef1f309a203b)
