### ISSUE TITLE
API Endpoint - View QA Test Extensions Exemptions Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3058]
Create GET endpoints (4) for QA Test Extensions Exemptions Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

**Testing Reference Only:**
Unit or Stack Pipe ID (Dropdown)
Year (Dropdown)
Quarter (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
Hours Used (Text)
Span Scale Code (Dropdown)
Fuel Code (Dropdown)
Extension or Exemption Code (Dropdown)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/354

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1192](https://epacamd.testquality.com/project/11428/plan/28527/test/418646)
Test Passed

**Comment by mosesdeeCVP** [comment]
Test Extensions Exemptions Data - View - Workspace
![Test Extensions Exemptions Data - View - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aa1d9552-611a-4eba-ad58-0db07e859f45)

**Comment by mosesdeeCVP** [comment]
Test Extensions Exemptions Data - View - Workspace with ID
![Test Extensions Exemptions Data - View - Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/550e10fa-98b5-468f-bef8-067573f90cde)

**Comment by mosesdeeCVP** [comment]
Test Extensions Exemptions Data - View - Official
![Test Extensions Exemptions Data - View - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/70dc1d11-5f3c-45f5-aafd-cf3821995a4d)

**Comment by mosesdeeCVP** [comment]
Test Extensions Exemptions Data - View - Official with ID
![Test Extensions Exemptions Data - View - Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9865351d-3c87-4876-bf32-91791ff42f62)
