### ISSUE TITLE
API Endpoint - Add QA Test Extensions Exemptions Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3059]
API Endpoint - Add QA Test Extensions Exemptions Data

**Testing Reference Only:**
Unit or Stack Pipe ID  (Dropdown)
Year (Dropdown)
Quarter (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
Hours Used (Text)
Span Scale Code (Dropdown)
Fuel Code (Dropdown)
Extension or Exemption Code (Dropdown)

## Testing 
Test Case: [TC1190](https://epacamd.testquality.com/project/11428/plan/28527/test/416993)
Tester: @JanellC

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/348

**Comment by JanellC** [comment]
TC1190 paased 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e6b11d01-c801-40b1-9f8b-81e5afee91c2)
