### ISSUE TITLE
Remove QA Test Extension Exemption Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3060]
As an ECMPS user, I want the ability to remove QA Test Extension Exemption data so that I can update data as needed

Acceptance Criteria:
Given I am in the QA Test Extension Exemption data section
When I click on the 'Remove' option
Then I see that the relevant QA Test Extension Exemption data record is deleted

Given I chose to remove QA Test Extension Exemption data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the QA Test Extension Exemption Data section
When I select Cancel
Then I am returned to the landing screen for QA Test Extension Exemption Data

## Testing 
Test Case: [TC1202](https://epacamd.testquality.com/project/11428/plan/28527/test/419485)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1202 
System removes a TEE record 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9856c9b8-3267-4edf-b564-a6dfa81cd6e3)
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7edc8243-1f9b-4f9e-814e-aebacc3bbac2)
