### ISSUE TITLE
API Endpoint - View Calibration Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3067]
Create GET endpoints (4) for Calibration Injection Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Online Offline Indicator (radio button)
Upscale Gas Level Code (Dropdown )
Zero Injection Date (Text & Datepicker)
Zero Injection Hour (Dropdown 1-23)
Zero Injection Minute (Dropdown 1-59)
Upscale Injection Date (Text & Datepicker)
Upscale Injection Hour (Dropdown 1-23)
Upscale Injection Minute (Dropdown 1-59)
Zero Measured Value (Text)
Upscale Measured Value (Text)
Zero APS Indicator (radio button)
Upscale APS Indicator (radio button)
Zero Calibration Error (Text)
Upscale Calibration Error (Text)
Zero Reference Value (Text)
Upscale Reference Value (Text)

**Comment by mosesdeeCVP** [comment]
Calibration Injection - View Official

![Calibration Injection - View Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/546306ae-bf59-4bb3-9eec-e60b5a8693af)

**Comment by mosesdeeCVP** [comment]
Calibration Injection - View Official with ID

![Calibration Injection - View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6a9dbace-45b7-4b06-8ab6-07b4838ea998)

**Comment by mosesdeeCVP** [comment]
Calibration Injection - View Workspace

![Calibration Injection - View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3067dcc7-7da4-40f6-8a68-69f02eb8452c)

**Comment by mosesdeeCVP** [comment]
Calibration Injection - View Workspace with ID

![Calibration Injection - View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/288f8dfc-f92b-4b1b-84c3-dacb85137fd8)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1006](https://epacamd.testquality.com/project/11428/plan/27529/test/400558)
Test Passed
