### ISSUE TITLE
Add Cycle Time Summary data elements to Import Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3077]
Add Cycle Time Summary data elements to Import Endpoint

**Comment by JanellC** [comment]
For Planning prioritize export endpoint before the import endpoint is completed

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/273

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1088](https://epacamd.testquality.com/project/11428/plan/27813/test/407617)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Cycle Time Summary Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/38ea46fa-091a-4c2e-a5df-b3abbaf2f56d)
