### ISSUE TITLE
API Endpoint - Remove Cycle Time Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3078]
Create API Endpoint to remove/delete Remove Cycle Time Summary Data

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/271

**Comment by mosesdeeCVP** [comment]
![Cycle Time Summary - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7b617f71-9da1-4d80-9d77-c97b65ef1d7f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1081](https://epacamd.testquality.com/project/11428/plan/27813/test/406928)
Test Passed
