### ISSUE TITLE
API Endpoint - Edit Cycle Time Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3079]
Create API endpoint for Edit for Cycle Time Summary Data

Testing Reference Only:
Total Time

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/271

**Comment by mosesdeeCVP** [comment]
![Cycle Time Summary - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5e75d2df-5928-4d61-8fe3-6bb5f4a794bb)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1080](https://epacamd.testquality.com/project/11428/plan/27813/test/406927)
Test Passed
