### ISSUE TITLE
API Endpoint - Remove Hg Injection Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3081]
Create API Endpoint to remove/delete Hg Injection Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1164](https://epacamd.testquality.com/project/11428/plan/28224/test/414118)

**Comment by mosesdeeCVP** [comment]
![HG Injection Delete.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6fc88840-c178-4233-9e6b-05c1a7f0380d)

**Comment by mosesdeeCVP** [comment]
Test Passed
