### ISSUE TITLE
Add Hg Injection data elements to Export Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3082]
Add Hg Injection data elements to Export Endpoint for both Official and Workspace views

**Comment by mosesdeeCVP** [comment]
HG Injection Export Official
![HG Injection Export Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1707abbf-1967-4413-8459-59841dea7147)

**Comment by mosesdeeCVP** [comment]
HG Injection Export Workspace
![HG Injection Export Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a4582537-9cba-4af2-bfa3-e3df76e9a689)

**Comment by mosesdeeCVP** [comment]
Test case: [TC1169](https://epacamd.testquality.com/project/11428/plan/28224/test/414898)
Test Passed
