### ISSUE TITLE
Add Hg Summary data elements to Export Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3085]
Add Hg Summary data elements to Export Endpoint for both Official and Workspace views

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1160](https://epacamd.testquality.com/project/11428/plan/28224/test/414114)

**Comment by mosesdeeCVP** [comment]
HG Sum Official
![HG Sum Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4d6ea534-dbae-44ed-bfed-a3d95b262cbb)

**Comment by mosesdeeCVP** [comment]
HG Sum Workspace
![HG Sum Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c0937986-71f9-4b45-af20-ce86bb818b41)

**Comment by mosesdeeCVP** [comment]
Test Passed
