### ISSUE TITLE
API Endpoint - Remove Hg Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3086]
Create API Endpoint to remove/delete Hg Summary Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1150](https://epacamd.testquality.com/project/11428/plan/28224/test/413663)

**Comment by mosesdeeCVP** [comment]
![HG Summary API DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/364ddd2a-4f78-4fae-b201-eeac830db9b7)

**Comment by mosesdeeCVP** [comment]
Test Passed
