### ISSUE TITLE
API Endpoint - Remove RATA Traverse Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3089]
Create API Endpoint to remove/delete RATA Traverse Data

## Testing 
Test Case: [TC945](https://epacamd.testquality.com/project/11428/plan/26541/test/395158)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Both Rata Traverse endpoints on workspace work

**Comment by mosesdeeCVP** [comment]
Test Passed
