### ISSUE TITLE
API Endpoint - View Flow RATA Run Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3091]
Create GET endpoints (4) for Flow RATA Run Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Testing Reference Only:
Number of Traverse Points (Text)
Barometric Pressure (Text)
Stack Static Pressure (Text)
Percent CO2 (Text)
Percent O2 (Text)
Percent Moisture (Text)
Dry Molecular Weight (Text)
Wet Molecular Weight (Text)
Average Velocity without Wall Effects (Text)
Average Velocity with Wall Effects (Text)
Calculated WAF (Text)
Average Stack Flow Rate (Text)

## Testing 
Test Case: [TC951](https://epacamd.testquality.com/project/11428/plan/26541/test/395874)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Flow Rata Global View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/da498df6-42d1-4258-a116-575a2bbb71b8)

![Flow Rata Global View - ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1a2d15c9-7764-4828-815c-b1da9ce36617)
