### ISSUE TITLE
Edit API Endpoint - RATA Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3096]
Create API endpoint for Edit for RATA Summary Data:

Testing Reference Only:
Operating Level Code (Dropdown)
Average Gross Unit Load (Text)
Reference Method Code (Dropdown)
Mean CEM Value (Text)
Mean RATA Reference Value (Text)
Mean Difference (Text)
Standard Deviation Difference (Text)
Confidence Coefficient (Text)
T Value (Text)
APS Indicator (Radiobutton - Yes/No)
APS Code (Dropdown)
Relative Accuracy (Text)
Bias Adjustment Factor (Text)
CO2 or O2 Reference Method Code (Dropdown)
Stack Diameter (Text)
Stack Area (Text)
Number of Traverse Points (Text)
Calculated WAF (Text)

**Comment by mosesdeeCVP** [comment]
Test Passed
