### ISSUE TITLE
Edit API Endpoint - RATA Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3102]
Create API endpoint for Edit for RATA

Testing Reference Only: 
Number of Load Levels (Dropdown - Hardcode options to 1, 2 and 3)
Relative Accuracy (Text)
RATA Frequency Code (Dropdown)
Overall Bias Adjustment Factor (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC857](https://epacamd.testquality.com/project/11428/plan/26541/test/384664)

**Comment by mosesdeeCVP** [comment]
Test Passed
