### ISSUE TITLE
API Endpoint - Remove Unit Default Test Run Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3104]
Create API endpoint for Remove Unit Default Test Run Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1140](https://epacamd.testquality.com/project/11428/plan/28118/test/412370)

**Comment by mosesdeeCVP** [comment]
![3104 API Endpoint - Remove Unit Default Test Run Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/399609d3-53b5-4d95-b065-b582dc80dbe8)

**Comment by mosesdeeCVP** [comment]
Test Passed
