### ISSUE TITLE
API Endpoint - Remove Unit Default Test Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3107]
Create API Endpoint to remove/delete Unit Default Test Data

**Comment by mosesdeeCVP** [comment]
![3107 API Endpoint - Remove Unit Default Test Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b63ad2a8-fd0c-4fff-a1e0-5fa2d8bd2b87)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1135](https://epacamd.testquality.com/project/11428/plan/28118/test/412005)
Test Passed
