### ISSUE TITLE
API Endpoint - Edit Unit Default Test Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3108]
Create API endpoint for Edit for Unit Default Test Data

Testing Reference Only:
Fuel Code (Dropdown)
NOX Default Rate (Text)
Operating Condition Code (Dropdown - A, B, P)
Group ID (Text)
Number of Units in Group (Text)
Number of Tests for Group (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1140](https://epacamd.testquality.com/project/11428/plan/28118/test/412370)
Test Passed

**Comment by mosesdeeCVP** [comment]
![Unit Default - Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8be11b5a-7655-4aff-afd0-315f4dd61781)
