### ISSUE TITLE
Edit API Endpoint -  Appendix E Heat Input from Oil Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3111]
Create API endpoint for Edit for Appendix E Heat Input from Oil Data

Testing Reference Only:
Monitoring System ID
Oil Mass
Oil GCV
Oil GCV Units of Measure Code
Oil Heat Input
Oil Volume
Oil Volume Units of Measure Code
Oil Density
Oil Density Units of Measure Code

**Comment by mosesdeeCVP** [comment]
Test Case: [TC984](https://epacamd.testquality.com/project/11428/plan/27381/test/398604)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![3111 Edit API Endpoint - Appendix E Heat Input from Oil Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/47860150-3803-4a5a-b6f2-85e414dc9514)
