### ISSUE TITLE
Edit API Endpoint - Appendix E Heat Input from Gas Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3114]
Create API endpoint for Edit for Appendix E Heat Input from Gas Data

**Testing Reference Only:**
Monitoring System ID
Gas GCV
Gas Volume
Gas Heat Input

**Comment by mosesdeeCVP** [comment]
Test Case: [TC975](https://epacamd.testquality.com/project/11428/plan/27381/test/398461)

**Comment by mosesdeeCVP** [comment]
![3114 - Edit API Endpoint - Appendix E Heat Input from Gas Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc27e84f-fe53-4e8d-a7e4-5b4734e1fd12)

**Comment by mosesdeeCVP** [comment]
Test Passed
