### ISSUE TITLE
API Endpoint - Remove Appendix E Correlation Test Run Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3116]
Create API Endpoint to remove/delete Appendix E Correlation Test Run Data

## Testing 
Test Case: [TC971](https://epacamd.testquality.com/project/11428/plan/27381/test/398361)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![3117 API Endpoint - Add Appendix E Correlation Test Run Data - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1d5fa599-c243-4f5c-a43c-84fd7aa7c11e)

**Comment by mosesdeeCVP** [comment]
Test Passed
