### ISSUE TITLE
API Endpoint - View Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3118]
Create GET endpoints (4) for Appendix E Correlation Summary Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

**Comment by mosesdeeCVP** [comment]
Test case: [TC981](https://epacamd.testquality.com/project/11428/plan/27381/test/398467)
Test Passed
