### ISSUE TITLE
API Endpoint - Edit Appendix E Correlation Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3119]
Create API endpoint for Edit for Appendix E Correlation Summary Data

Testing Reference Only:

Operating Level for Run (Text)
Mean Reference Value (Text)
Average Hourly Heat Input Rate (Text)
F-Factor (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC981](https://epacamd.testquality.com/project/11428/plan/27381/test/398467)
Test Passed
