### ISSUE TITLE
API Endpoint - Remove Fuel Flow to Load Test Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3122]
Create API Endpoint to remove/delete Fuel Flow to Load Test Data

## Testing 
Test Case: [TC967](https://epacamd.testquality.com/project/11428/plan/27145/test/398099)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Test Data - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0308670f-4f9b-4f1b-9162-983392e06f4b)

**Comment by mosesdeeCVP** [comment]
Test Passed
