### ISSUE TITLE
API Endpoint - Edit Fuel Flow to Load Test Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3123]
Create API endpoint for Edit for Fuel Flow to Load Test Data

Testing Reference Only:

Test Basis Code (Dropdown)
Average Difference (Text)
Number of Hours Used (Text)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

## Testing 
Test Case: [TC966](https://epacamd.testquality.com/project/11428/plan/27145/test/398098)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Fuel Flow To Load Test Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f7df3c2f-a293-453d-9d99-aad58f00065c)

**Comment by mosesdeeCVP** [comment]
Test Passed
