### ISSUE TITLE
API Endpoint - Remove Transmitter Transducer Accuracy Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3125]
Create API Endpoint to remove/delete Transmitter Transducer Accuracy Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1097](https://epacamd.testquality.com/project/11428/plan/27874/test/407904)

**Comment by mosesdeeCVP** [comment]
![View Transmitter Transducer Accuracy - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ff4c9f81-ee73-4f77-aa2e-286556554d6c)

**Comment by mosesdeeCVP** [comment]
Test Passed
