### ISSUE TITLE
API Endpoint - Remove Fuel Flow to Load Baseline Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3128]
Create API Endpoint to remove/delete Fuel Flow to Load Baseline Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC994](https://epacamd.testquality.com/project/11428/plan/27145/test/399982)
Test Passed

**Comment by mosesdeeCVP** [comment]
![3128 API Endpoint - Remove Fuel Flow to Load Baseline Data - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5cbc6b4c-7141-4fd9-94c1-0407184afa66)
