### ISSUE TITLE
API Endpoint - Edit Fuel Flow to Load Baseline Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3129]
Create API endpoint for Edit for Fuel Flow to Load Baseline Data

Testing Reference Only:
Accuracy Test Number (Text)
PEI Test Number (Text)
Average Fuel Flow Rate (Text)
Average Load (Text)
Baseline Fuel Flow-to-Load Ratio (Text)
Fuel Flow-to-Load UOM Code (Dropdown)
Average Hourly Heat Input Rate (Text)
Baseline GHR (Text)
GHR UOM Code (Dropdown)
Number of Hours Excluded Co-firing (Text)
Number of Hours Excluded Ramping (Text)
Number of Hours Excluded Low Range (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC993](https://epacamd.testquality.com/project/11428/plan/27145/test/399981)
Test Passed

**Comment by mosesdeeCVP** [comment]
![3124 API Endpoint - Edit Fuel Flow to Load Baseline Data - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5ebaedb8-6be3-45e9-af0c-5d1ff5e055db)
