### ISSUE TITLE
API Endpoint - Remove Fuel Flowmeter Accuracy Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3131]
Create API Endpoint to remove/delete Fuel Flowmeter Accuracy Data

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1086](https://epacamd.testquality.com/project/11428/plan/27838/test/407553)
Test Passed

**Comment by mosesdeeCVP** [comment]
![Fuel Flowmeter Accuracy - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b33f4a1e-29ce-4444-8c3b-5870472f2aba)
