### ISSUE TITLE
Verify API Endpoints - Linearity Summary Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3134]
The scope of this ticket includes verification of the endpoints from the dev site, adding Unit Tests and testing the API endpoints for Add and Remove for Linearity Summary Data

Swagger URL: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ce35b1c7-0dbc-4017-a0a4-da172ae48ada)

**Comment by vishnunavuluri** [comment]
Verified POST, PUT and DELETE. Tests passed
