### ISSUE TITLE
Remove API Endpoint - Linearity Injection Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3137]
Scope includes Unit Testing and testing of the DELETE endpoint:
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Linearity%20Injection/LinearityInjectionWorkspaceController_deleteLinearityInjection

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0bb843e2-643e-4e39-9af9-eb69554ca31d)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC848](https://epacamd.testquality.com/project/11428/plan/26561/test/383919)

**Comment by mosesdeeCVP** [comment]
Test Passed
