### ISSUE TITLE
Edit API Endpoint - Linearity Injection Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3138]
Scope includes Unit Tests and Testing of the endpoint: (PUT only)
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Linearity%20Injection/LinearityInjectionWorkspaceController_updateLinearityInjection

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0cf1a40e-28aa-41cd-83cb-5939c9ee4df6)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC847](https://epacamd.testquality.com/project/11428/plan/26561/test/383918)

**Comment by mosesdeeCVP** [comment]
Test Passed
