### ISSUE TITLE
API Endpoint - Remove Online Offline Calibration Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3140]
Create API Endpoint to remove/delete Online Offline Calibration Data

**Comment by mosesdeeCVP** [comment]
![Online Offline Calibration - DELETE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9f93b4eb-dca9-4e68-8a83-a6671c28e5b4)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1053](https://epacamd.testquality.com/project/11428/plan/27608/test/403338)
Test Passed
