### ISSUE TITLE
API Endpoint - Edit Online Offline Calibration Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3141]
Create API endpoint for Edit forOnline Offline Calibration Data

Testing Reference Only:
Online Zero Reference Value (Text)
Online Upscale Reference Value (Text)
Offline Zero Reference Value (Text)
Offline Upscale Reference Value (Text)
Online Zero Measured Value (Text)
Online Upscale Measured Value (Text)
Offline Zero Measured Value (Text)
Offline Upscale Measured Value (Text)
Online Zero Calibration Error (Text)
Online Upscale Calibration Error (Text)
Offline Zero Calibration Error (Text)
Offline Upscale Calibration Error (Text)
Upscale Gas Level Code (Dropdown)
Online Zero APS Indicator (Dropdown)
Online Upscale APS Indicator (Dropdown)
Offline Zero APS Indicator (Dropdown)
Offline Upscale APS Indicator (Dropdown)
Online Zero Injection Date (Text+Datepicker)
Online Upscale Injection Date (Text+Datepicker)
Offline Zero Injection Date (Text+Datepicker)
Offline Upscale Injection Date (Text+Datepicker)
Online Zero Injection Hour (Dropdown 1-23)
Online Upscale Injection Hour (Dropdown 1-23)
Offline Zero Injection Hour (Dropdown 1-23)
Offline Upscale Injection Hour (Dropdown 1-23)

**Comment by mosesdeeCVP** [comment]
![Online Offline Calibration - Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8ba5d975-50e2-408d-bf2b-c7fddda386e2)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1052](https://epacamd.testquality.com/project/11428/plan/27608/test/403337)
Test Passed
