### ISSUE TITLE
Performance Testing for Bulk Data File Generation + Quartz Process 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3145]
- [ ] Utilize the Quartz process to generate as many files as possible as quickly as possible to find a performance benchmark 

**Requirements**

- [ ] Determine overall Testing Process for Quartz Job

- [ ] Determine how process will work in a non-prod environment 

- [ ] Determine timing of process (peak/submission window vs non-peak) 

- [ ] Determine Scenarios for Performance Tests 

- [ ] Support Scenarios with Data (CBS, etc) 

- [ ] Determine goals for scenarios (Determine Load Time when stressed and not stressed)

**Comment by MaeganWood64** [comment]
- Confer with ERG to get information on how long current processes take to run 
- Potentially Limit files to not overlap with NCC job

**Comment by MaeganWood64** [comment]
Dependent on Submission Window Logic for Bulk Process

**Comment by Kyle-Herceg** [comment]
One Year Bulk File Metrics
State
- Daily = 5 Minutes
- Hourly = 11 Minutes

Quarter 
- Daily = 1 Minute
- Hourly = 27 Minutes

One Year GAFTP Metrics
EDR - 2:06 Hours
EM - 3:06 Hours 
MP - 40 Minutes
