### ISSUE TITLE
Provide Compliance Data in JSON

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#319]
## Feature Benefit
Benefit: Users can download each of the following groupings for analysis in CSV format (Travis 9/28)

Allowance-Based Compliance (For each trading program)
NOx Averaging Compliance (ARP)

*need to determine if these groupings are appropriate

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by david-cvp** [comment]
Invalid, duplicate of #322
