### ISSUE TITLE
Modify deployment scripts to support rollback process for multiple environments

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#329]
- [x] Modify rollback process to support new repo structure
- [x] Test rollback process across multiple repos / environments
- [x] Change naming standard of tags / releases

#195 was an effort to define the rollback process in the context of a single environment using the starter kit repo. This ticket is to expand upon that process and make sure it supports repo restructuring (from mono repo to multiple repositories) and to test the process across new environments.

**Comment by srinivasaregeti** [comment]
Documented the rollback process and posted to CVP's google drive.

**Comment by JorjaComer** [comment]
Removed from sprint to support Kanban workflow.
