### ISSUE TITLE
Research Apportioned Emissions Resources 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#333]
- [x] Identify resources (list tables)

- [x] Understand data

**Comment by sdhawan16** [comment]
Completed preliminary research and determined that there are some differences in fields that are recorded for hourly and daily emissions data. Will identify tables used for each one and tables that are used for both.  Identified that scheduler job CAMDDMW.HRLY_DAILY_PPDS_SCP is being used to generate the emissions datasets. Will be looking into the sql code of the job to identify the data resources.

**Comment by sdhawan16** [comment]
Identified that the daily and hourly emissions data are stored in two separate tables: DAY_UNIT_DATA and HOUR_UNIT_DATA within the CAMDDMW schema.  This data is copied over from CAMDBSP to CAMDPUB (CAMDDMW schema) with the daily emissions pull process. Emissions data fields were mapped out to columns within these tables. Will now look into which table(s) the  data fields STATE, FACILITY_NAME, ORISPL_CODE, UNITID, UNIT_ID, and FAC_ID are stored in.

**Comment by sdhawan16** [comment]
All data fields within the hourly and daily emissions prepackaged datasets were mapped out to columns within the DAY_UNIT_DATA, HOUR_UNIT_DATA, and UNIT_FACT tables in the CAMDPUB database.  Currently determining which tables the data originates from in the CAMDBSP database before it is pulled over to the CAMDPUB database. Also identifying additional tables that are needed to create the prepackaged datasets in addition to the tables that store the data that is displayed.

**Comment by sdhawan16** [comment]
Mapped out all data fields to tables and columns where the data originates from in the CAMDBSP database before it is pulled over to the CAMDPUB database. Will continue identifying additional tables that don't contain the data displayed but are needed to generate prepackaged emissions datasets.

**Comment by sdhawan16** [comment]
Folder with both deliverables: 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/Daily%20and%20Hourly

Deliverable Summary: 
Deliverable 1 :  List of tables used for the generation of hourly and daily emissions prepackaged datasets 
Deliverable 2 :  Document with the jobs and resources that are associated with the hourly and daily emissions prepackaged datasets. Includes data fields mapped out to the corresponding table columns.
