### ISSUE TITLE
Identify Apportioned Emissions Relationships 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#334]
Dev Tasks
 Identify table relationships in CAMDBSP
 Document high-level ERD
Outcomes
ERD of CAMDBSP relationships

**Comment by JorjaComer** [comment]
change approved by Travis on 10/29 

[Customer Value Partners Mail - Changes Zenhub TASKS (ER diagrams) approval request.pdf](https://github.com/US-EPA-CAMD/PI-1/files/5461310/Customer.Value.Partners.Mail.-.Changes.Zenhub.TASKS.ER.diagrams.approval.request.pdf)

**Comment by sdhawan16** [comment]
Completed ERD for daily and hourly emissions: 
PDF - https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/Daily%20and%20Hourly/ERD%20for%20Prepackaged%20Data%20-%20Daily%20and%20Hourly%20Emissions%20-%20EPA%20CAMD%20-%20v1.2.pdf

Raw File -https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/Daily%20and%20Hourly/ERD%20for%20Prepackaged%20Data%20-%20Daily%20and%20Hourly%20Emissions%20-%20EPA%20CAMD%20-%20v1.2.drawio

Link to folder that contains the ERD files linked above: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/Daily%20and%20Hourly
