### ISSUE TITLE
Research Compliance Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#336]
- [x] Identify resources (list tables)
- [x] Understand data

**Comment by SimeraHailu** [comment]
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=7Q3hB9&cid=19c0555f%2D3fa1%2D45ec%2Db470%2D8c5c01389f7d&FolderCTID=0x012000B4ABB0EF9635994FA680705355892410&viewid=18eab565%2D03ba%2D4600%2Da594%2D5eb27c0d799a&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2FEASEY%2DOUT%2FData%20Relationships%2FCompliance%20Data
