### ISSUE TITLE
Create UI Design for bookmark functionality - Need by 4/18

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3361]
## Context 

will need to give users the ability to bookmark their query on the custom data download 
will need to add a bookmark button to the cdd- need UI design
once the bookmark button is selected then the system will display an alert/ pop up/ banner with the bookmark link

**Comment by NadiaJL** [comment]
@JanellC here is the first draft of EPA CAMD CDD Content - Bookmark (Desktop grid) 1024 WFs

Figma doc/Dev Inspect:
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343

Figma interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3545%3A17236&viewport=241%2C48%2C0.04&scaling=min-zoom&starting-point-node-id=3545%3A17236&show-proto-sidebar=1

**Comment by NadiaJL** [comment]
@JanellC Here is the updated CDD Content - Bookmark (Desktop grid) 1024 WFs with the updates as discussed today, 4/14/22.

Figma File/Dev Inspect:
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3545%3A17236

Figman interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3545%3A17236&viewport=241%2C48%2C0.21&scaling=min-zoom&starting-point-node-id=3545%3A17236&show-proto-sidebar=1

**Comment by NadiaJL** [comment]
@JanellC here are the  CDD Content - Bookmark Screen breaks Mobile through Desktop Wide 1400 WFs

Figma file / dev inspect
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343

Mobile interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3545%3A17236&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3674%3A19868

Tablet interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3687%3A23100&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3687%3A23100&show-proto-sidebar=1

Desktop 1024 interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3545%3A17236&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3545%3A17236&show-proto-sidebar=1

Desktop 1200 interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3687%3A26349&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3687%3A26349&show-proto-sidebar=1

Desktop 1400 interactive prototype:
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=1422%3A4343&node-id=3695%3A25015&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=3695%3A25015&show-proto-sidebar=1

**Comment by NadiaJL** [comment]
@JanellC here is the updated Custom Data Download - Bookmark functionality WFs Mobile>Desktop Wide 1400.  -Please let me know if any further edits are required

Figma File/Dev Inspect
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343

Interactive Figma Prototypes
CDD Content - Bookmark (Desktop grid) 1024
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=14[…]-zoom&starting-point-node-id=3545%3A17236&show-proto-sidebar=1

CDD Content - Bookmark (Desktop grid) 1200
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=14[…]-zoom&starting-point-node-id=3687%3A26349&show-proto-sidebar=1

CDD Content - Bookmark (Desktop grid) 1400
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=14[…]-zoom&starting-point-node-id=3695%3A25015&show-proto-sidebar=1

CDD Content - Bookmark - mobile
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=14[…]-zoom&starting-point-node-id=3674%3A19868&show-proto-sidebar=1

CDD Content - Bookmark - Tablet
https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?page-id=14[…]-zoom&starting-point-node-id=3687%3A23100&show-proto-sidebar=1
