### ISSUE TITLE
Bulk Data Files Page- 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3362]
## Context 

Testing complete for 2698, 2696. Tested entire bulk data download page, found multiple issues:
1.	There is no visual focus indicator (box) on the select all files checkbox (others have them)... it is getting keyboard focus.
2.	Files Selected, Size text and values need to be in an aria live region so they are announced when updated
3.	When clear all is activated, focus should be put back on the data type dropdown
4.	"There are no records to display" needs to be in an aria live region so it is announced when filters are updated
5.	There should be text or a tooltip saying that certain filter selections will display new filter options
6.	Couldn't test the file selection limit of 50GB message.... make sure that is also in an aria live region

## Dev Notes 

For action item #5 display tool tip to the right of "Data Type". 
The tool tip should display the following message: "Certain filters selections will cause other filters to display."

**Comment by aprematta** [comment]
Items 1-5 pass, was not able to test item 6, closing ticket
