### ISSUE TITLE
HiFi Wireframe Updates

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3363]
Updates to be made to the prototype: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

[https://app.zenhub.com/files/287570343/5540260d-66c6-48cc-9048-35cb98110efb/download](https://app.zenhub.com/files/287570343/5540260d-66c6-48cc-9048-35cb98110efb/download)

**Comment by NadiaJL** [comment]
@vishnunavuluri here are the updated ECMPS-EPA-Responsive-QA Linearity V1.3 WFs with the updates as requested on 4/8/22.
Shared Xd Link: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

**Comment by NadiaJL** [comment]
ECMPS-QA Linearity - Workspace - side menu ex.
Shared Xd Doc Link:  https://xd.adobe.com/view/b0c830db-8df5-4c66-9e5c-52775350f7fe-e59b/
