### ISSUE TITLE
Bulk data files search-508 issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3367]
## Context 

Testing complete for 2697, the code of the hidden label and actual search input matches that of the search in the popup menu. To remedy, change the for and id attributes of the new search label/input so they are different from the one in the menu. I would also suggest changing the hidden label to be different, perhaps 'Search Bulk Data Files Table'

**Comment by aprematta** [comment]
Testing complete, issues have been addressed!
