### ISSUE TITLE
QA & Cert - Update Left-Hand Menu

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3370]
As an ECMPS user, I want the left-hand menu for the application to be updated with additional options so that I can access the new QA & Certification Data module

Acceptance Criteria:

For Global-View (Already implemented and is good)
Given I access ECMPS
When I navigate to the left-hand menu
Then I see the available options updated according to the prototype provided (Screen X of 14 from prototype)

For Workspace (update according to screen 2/3 of 3 in prototype)
Given I access ECMPS
When I navigate to the left-hand menu
Then I see the available options updated according to the prototype provided (Screen Y of 14 from prototype)

Note: The 3 options available under QA & Certifications are expanded by default and remain so at all times

Prototype: https://xd.adobe.com/view/b0c830db-8df5-4c66-9e5c-52775350f7fe-e59b/screen/bc06d4e6-7383-43b8-b08a-69c372083927/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC667](https://epacamd.testquality.com/project/11428/plan/24660/test/337203)

**Comment by mosesdeeCVP** [comment]
![3370 QA & Cert - Update Left-Hand Menu.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e0d213c-bc64-468c-bc64-8b109be0729b)

**Comment by mosesdeeCVP** [comment]
Test Passed
