### ISSUE TITLE
Research Allowance Holding  Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#339]
- [x] Identify resources (list tables)
- [x] Understand data

**Comment by junie-stigdon** [comment]
Looking to combine this estimate with #340 . Once we determine the effort needed for Emissions, we will discuss how to distribute the work among the team and whether or not we can bring in Compliance Data into this sprint.

**Comment by junie-stigdon** [comment]
After researching the data sets, we concluded that Allowance Holdings and Allowance Transactions do not need to be separate. The estimate was lowered from 5 to 2, the efforts are combined with #340 .

**Comment by junie-stigdon** [comment]
Identified the tables that are called by the scheduler jobs that generate the prepackaged data sets. These tables reside in the CAMDPUB database; the data is copied over from the CAMDBPS database.

Currently mapping out where the data originates from in CAMDBPS.

**Comment by junie-stigdon** [comment]
Completed identifying all tables associated with Holdings in both CAMDPUB and CAMDBSP. Will close out ticket once #340 is completed.

**Comment by junie-stigdon** [comment]
Tables identified per schema: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data/Tables%20for%20Prepackaged%20Data%20-%20Allowance%20Data%20-%20EPA%20CAMD%20-%20v1.3.pdf?csf=1&web=1&e=UuoakR

**Comment by junie-stigdon** [comment]
Jobs and Resources (CAMDPUB tables and columns and CAMDBSP origin): https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data/Prepackaged%20Datasets%20Jobs%20and%20Resources%20-%20Allowance%20Data%20-%20EPA%20CAMD%20-%20v1.2.pdf?csf=1&web=1&e=b32DLj

**Comment by junie-stigdon** [comment]
Folder with both deliverables: https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data?csf=1&web=1&e=7Q3hB9
