### ISSUE TITLE
Move EDR & XML files from SFTP to S3

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#3407]
We need a process that will take a folder from an SFTP site as input and copy the contents of that folder including folder structure from the SFTP to cloud.gov bulk files S3 bucket and attached all the necessary metadata to each file.

**Facility Information**
Use the 1st 6 digits of the filename to get the facility id and lookup the facility from the database or use the facilities api to get the facility name an state. The facility id here refers to the oris_code column in the database NOT the fac_id column.

**Tag each file with the same metadata as the bulk file generation processes that are applicable** datatype, datasubtype, year, quarter, statecode, facilityname, facilityid, description

## [EDR files](https://gaftp.epa.gov/DMDnLoad/edr/)
Group by year & quarter starting with the year 1995 to 2008
Description: Electronic data reporting (EDR) file submitted by facility ID `<facility ID>` for Part 75 reporting for `<year>` quarter `<quarter>`
DataType: EDR
![image](https://user-images.githubusercontent.com/66504934/163483140-1a5cd1d2-2593-4194-87a3-94a057e64d2a.png)
![image](https://user-images.githubusercontent.com/66504934/163483029-df505aa8-eebf-4c2d-b75e-9b0be1fe0a55.png)

## [MP XML files](https://gaftp.epa.gov/DMDnLoad/xml/mp)
Description: Monitoring plan file submitted by facility ID `<facility ID>` under Part 75
DataType: XML
DataSubType: MP
![image](https://user-images.githubusercontent.com/66504934/163482961-70340c3e-d25e-4c68-b40f-ac3fa9bcf3af.png)

## [QA XML files](https://gaftp.epa.gov/DMDnLoad/xml/qa)
Group by year & quarter starting with the year 2008 to current
Description: Quality Assurance file submitted by facility ID `<facility ID>` for `<year>` quarter `<quarter>` under Part 75
DataType: XML
DataSubType: QA
![image](https://user-images.githubusercontent.com/66504934/163483008-4dde9565-8fee-478c-a5e4-0f879ddb8654.png)
![image](https://user-images.githubusercontent.com/66504934/163483029-df505aa8-eebf-4c2d-b75e-9b0be1fe0a55.png)

## [EM XML files](https://gaftp.epa.gov/DMDnLoad/xml/em)
Group by year & quarter starting with the year 2006 to current
Description: Emissions file submitted by facility ID `<facility ID>` for `<year>` quarter `<quarter>` under Part 75
DataType: XML
DataSubType: EM
![image](https://user-images.githubusercontent.com/66504934/163483545-6cf65b2e-3831-49de-8f31-06f648e0efdc.png)
![image](https://user-images.githubusercontent.com/66504934/163483029-df505aa8-eebf-4c2d-b75e-9b0be1fe0a55.png)

## [ARP Initial Allocations](https://gaftp.epa.gov/DMDnLoad/allowances)
Description: Acid Rain Program (ARP) Initial Allowance Allocations Data
DataType: Allowance
ProgramCode: ARP

**Comment by MaeganWood64** [comment]
- Adding section in runbook regarding client token
