### ISSUE TITLE
QA & Cert Module Screens - Resolutions above Tablet

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3408]
As an ECMPS user I want the QA & Cert Module Test Summary Screens built at all resolutions up to 1024 (except Tablet and Phone) so that I can access the application without any issues

**Comment by NadiaJL** [comment]
@vishnunavuluri here are the WFs for ECMPS-QA Linearity - Desktop Wide - 1400
Shared Xd Doc: https://xd.adobe.com/view/62212046-b608-4178-bc97-da3c5d3a43f1-3772/
