### ISSUE TITLE
Unable to update (Create/Edit) MP info for Configurations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3410]
Issue: When a user wishes to create/edit a Configuration, system throws a validation error on the screen and prevents the record from being created

Steps to Reproduce:

- Login to ECMPS
- On the Select Configurations screen, open and checkout a Configuration under a Facility
- Select any one option from the Sections dropdown, click Create and enter information as needed. Click Create
- System throws an error (sample below)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/56c8755d-1a0b-4e06-b8cc-d6d548a3b0c3)

**Comment by mosesdeeCVP** [comment]
Defaults - Pass
Formula - Pass
Load - Pass
Location Attributes - Pass
Methods - Pass
Supplemental Methods - Pass
WAFs Rectangular Duct - Pass
Spans - Pass
Systems - Pass
Analyzer Ranges - Pass

Qualifications - **Fail** (Creates, but when user clicks on View/Edit the UI crashes)
    *Qual Percent - Unable to test due to Qualifications bug
    *Qual LEE - Unable to test due to Qualifications bug
    *Qual LME - Unable to test due to Qualifications bug

System Component - **Fail**. UI shows the API Error

Fuel Flow - **Fail** (Does create, but UI shows error "undefined Internal server error". Edit is fine)

Unit Information - **Fail** (Section does not load and UI no longer works. 
       *Unit Fuels, Unit Controls, Unit Capacity - Unable to test due to loading bug)

**Comment by mosesdeeCVP** [comment]
Remaining issues will be cleared in the below tickets:

[Unable to update (Create/Edit) MP info for Configurations (2)#3432](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/3432)
[ECMPS: Issue with Refresh and MP data creation#3433](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/3433)
