### ISSUE TITLE
Add selected criteria to bookmark pop up 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3411]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want the bookmark pop up to display my selected criteria So that I know the criteria that I selected as apart of my bookmarked query 

## Acceptance Criteria
Given that a user has selected the bookmark functionality 
When the pop up is displayed 
Then the pop up displays ALL of the applied filter criteria 
AND the pop up is displayed in accordance with the [Wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3545%3A17236)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context

[Book Mark Wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3545%3A17236)

**Pop Up Enhancement Requirements**
Pop up displays the data type and data sub type. As apart of this enhancement add additional applied filter criteria to the pop up.
Functionality will be consistent with the filter tags. 

The system will display the full criteria name for a filter if only one was applied. The system will display the number of criteria applied for a filter if more than one is applied.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
12/4/2023 - there hasn't been any feedback supporting this ticket. therefore, recommend against implementation.
