### ISSUE TITLE
Error messages are not presented to AT

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3414]
**Functionality:**
- Import a Monitoring Plan

**Issue:**
After a user submits an invalid value in a form, an error message appears either dynamically or on a new page but is not presented to assistive technology. This issue is a violation of WCAG 2.1 Success Criterion 4.1.3.

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d6ec8981-84d5-4e92-bb2b-88c445197ca7)

**Suggested Resolution:**
Add Aria Live to announce the error message to assistive technology. For assistance see:
W3 - ARIA Technique #19
W3 – User Notification Tutorial
W3 – Live Region Roles
Webaim – Form Validation
Deque – Non Modal Dialog

**Comment by aprematta** [comment]
Testing complete, issue has been fixed
