### ISSUE TITLE
Implement Error Output Format for MP 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#3424]
Return errors from schema validation in standard error message format

**Comment by jwhitehead77** [comment]
@MaeganWood64 @JorjaComer @vishnunavuluri moving to monthly backlog as this is not ready for development and needs to be discussed further. There is not really enough information to truly understand the ask. We also really do not have much control over the formatting of JSON schema validation errors as we use a 3rd party JSON schema validation package. All 3rd party JSON schema validation packages follow a universal standard as to how to indicate the errors and where in the file the error occurred and reformatting the results would be a large LOE.

**Comment by MaeganWood64** [comment]
- No Longer Needed as of 6/23/22
