### ISSUE TITLE
CAMPD Home Page-508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3431]
## Context 

Testing complete for 2796..... 2 issues found:
1.	The icons next to Data and Maps & Graphs in the main content can be considered decorative. Currently they have repetitive alt text alt="Data Icon" for example. Change both to the empty alt tag alt=""
2.	The Data and Maps & Graphs content in the main section are now each contained in a layout table but their is data table markup. Either remove the layout tables and position in some other method, or add a role of "Presentation" to the table tag and change all TH cells to TD.

**Comment by aprematta** [comment]
Both issues have been addressed, closing ticket
