### ISSUE TITLE
Unable to update (Create/Edit) MP info for Configurations (2)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3432]
Issue: When a user wishes to create/edit a Configuration, the system throws a validation error on the screen and prevents the record from being created

Steps to Reproduce:

Login to ECMPS
On the Select Configurations screen, open and checkout a Configuration under a Facility
Select any one option from the Sections dropdown, click Create and enter information as needed. Click Create
System throws an error (sample below)
image.png

Bug valid for the following sections:
Qualifications - Fail (Creates, but when user clicks on View/Edit the UI crashes)
*Qual Percent - Unable to test due to Qualifications bug
*Qual LEE - Unable to test due to Qualifications bug
*Qual LME - Unable to test due to Qualifications bug

System Component - Fail. UI shows the API Error

Unit Information - Fail (Section does not load and UI no longer works.
*Unit Fuels, Unit Controls, Unit Capacity - Unable to test due to loading bug)

**Comment by mosesdeeCVP** [comment]
Original Ticket:
[Unable to update (Create/Edit) MP info for Configurations #3410](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/3410)

**Comment by mosesdeeCVP** [comment]
Bugs Fixed
