### ISSUE TITLE
ECMPS: Issue with Refresh and MP data creation

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3433]
**Issue:**

- User logs in and selects and opens a Configuration
- Selects a Section from the Sections dropdown and click Create in order to create MP data for the selected Configuration
- Fill out all the information as needed and click Create. 

Note: This scenario happens when there is no existing data for the Configuration -> Section that you selected
The app freezes

Data is still created and saved, however user can only see that once they refresh the entire app

**Comment by mosesdeeCVP** [comment]
Original Ticket:
[Unable to update (Create/Edit) MP info for Configurations #3410](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/3410)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
