### ISSUE TITLE
HiFi Wireframe Updates (Sprint 8.3)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3449]
Updates to be made to this version of the prototype: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

Updates to be made:

- Update the left-hand menu (Screens 1 and 2)
- Remove Expand option from Screens 5,6,7,8,11 and 13)
- Add the Test Summary Section
- Add scroll bars to enable users to scroll through the entire data

[https://app.zenhub.com/files/287570343/597711c9-f3ad-4d5f-a0fe-e2970cf74cf4/download](https://app.zenhub.com/files/287570343/597711c9-f3ad-4d5f-a0fe-e2970cf74cf4/download)

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/89800e34-cc4e-44dd-a86b-5e6c4dcd10d1/download](https://app.zenhub.com/files/287570343/89800e34-cc4e-44dd-a86b-5e6c4dcd10d1/download)

**Comment by NadiaJL** [comment]
XD prototype: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/
