### ISSUE TITLE
Research MATS Emissions Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#345]
- [x]  Identify resources (list tables)

- [x]  Understand data

**Comment by sdhawan16** [comment]
Identified CAMDPUB tables/columns and CAMDBSP tables/columns that correspond to the data fields in the MATS emissions datasets. Will work on compiling list of all tables needed to generate MATS hourly emissions datasets.

**Comment by sdhawan16** [comment]
Compiled list of all tables needed to generate MATS hourly emissions datasets. Will review and refine the list of jobs and procedures.

**Comment by sdhawan16** [comment]
Tables for MATS Emissions :  
https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS/Tables%20for%20Prepackaged%20Data%20-%20MATS%20Emissions%20-%20EPA%20CAMD%20-%20v1.1.pdf?csf=1&web=1&e=8Ktgkn

MATS Emissions Jobs and Resources:
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS/Prepackaged%20Datasets%20Jobs%20and%20Resources%20-%20MATS%20Emissions%20-%20EPA%20CAMD%20-%20v1.0.pdf

Folder for both MATS Emissions deliverables: 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS
