### ISSUE TITLE
Reimplement Contact Us Content Page  

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3454]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the system to have a contact us endpoint So that I can submit a help ticket 

## Acceptance Criteria
Given that a user has navigated to the contact us page on CAMPD 
When the functionality is displayed
Then the system renders in accordance with the  [wireframes](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=577%3A2186) (see context)

Given that a user has filled out all the required fields on the CAMPD contact us form 
When the form is submitted 
Then the system returns the success message : Success! You will be sent a confirmation email within the next 24 hours. If you do not receive a notification, please resubmit your issue, reach out to the Clean Air Markets Division hotline at 202-343-9620, or email campd-support@camdsupport.com directly.

Given that a user has entered an incorrect email format into the form
When submit is selected
Then the system displays the following message:
"The email you provided is not a valid address. Please enter a valid email address" 

Given that a user has made a POST request to the contact us endpoint 
When the system does not detect data in the body 
Then the system returns the following error message: FV-106 <insert property> should not be null, undefined, or empty  ([Error message repo ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={E95CEE6E-3EC6-4619-A8C9-CEEA00ECD464) )

Given that a user has filled out all the required fields on the contact us form and selected submit 
When the form is not submitted due to a notifications api error 
Then the system displays the following message: An error occurred while submitting your comment. Please resubmit your information; or call the Clean Air Markets Division hotline 202-343-9620; or email campd-support@camdsupport.com.

### Development Notes
- The endpoint will not be available on swagger. The endpoint can be added to swagger for development but will need to be removed afterwards 
- All of the links on CAMPD will need to route to the contact us page in the application 
- for testing will need to test on CAMPD and on Postman 

Links to the contact us form that need to be updated:

CAMPD home page whats new box
Tutorials page
FAQs page (submit a help ticket)
contact us link in the utility nav

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Dependency: The security token needs to finalized before this can be completed.  

 [wireframes](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=577%3A2186) (see context)

([Error message repo ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={E95CEE6E-3EC6-4619-A8C9-CEEA00ECD464) )

API Validations: 
Validate that all the required fields have data associated with it 

## Testing
Test Case: [TC849](https://epacamd.testquality.com/project/11428/plan/26079/test/fullscreen/383928)
Tester: Maegan Wood

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
Let's edit the success message to: 

Success! You will be sent a confirmation email within the next 24 hours. If you do not receive confirmation, you can: resubmit your information; or email campd-support@camdsupport.com; or call the Clean Air Markets Division hotline 202-343-9620.”

For the empty values error message, looks like this is what was implemented before so let's maintain that message: ![e2e900db-1c58-4136-ba3e-88526202da14.jpg](https://images.zenhubusercontent.com/5f3fd6e5a36605390ed80be4/fb021a7c-b460-40bf-a200-a32297b3899f)

For the invalid email message, let's use: "The email provided is not a valid address. Please enter a valid address."

The error message due to a notifications api error can be maintained. Thanks! @MaeganWood64 @AbuFofanah

**Comment by MaeganWood64** [comment]
@tlageman-epa TC849 Passed
