### ISSUE TITLE
Bulk Data files Filters- mobile/tablet breakpoints- 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3456]
## Context 
Testing complete for 2758, couple of issues found:
1.	Tab order is incorrect, the tooltip for select all files comes before the Keyword search text box and search button. Need to adjust the order in the dom to put the search functionality above the tooltip.
2.	When the filters button is selected, there is no focus shift. It needs to be put on the first focusable item in the filters window.
3.	When the filters window is active, there is no keyboard trap, I should not be able to get to the other items on the web page until the window is dismissed.
4.	When I hit the back or preview data buttons, focus is not shifted, it should be placed back on the filters button

**Comment by MaeganWood64** [comment]
@aprematta This issue is ready for testing!

**Comment by aprematta** [comment]
Looks good, all 4 issues have been addressed
