### ISSUE TITLE
QA HiFi Wireframe Updates (Version 2 - Sprint 8.3)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3457]
Updates to be made to this version of the prototype: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

Updates to be made:
1. Screen 1 of 19: Remove duplicate vertical scroll bar
2. Screen 2 of 19: Remove the sort icon from the 'Actions' column
3. Screen 5 of 19 and onwards:

**Test Summary Data - Fields applicable:**
- Unit or Stack Pipe ID
- Test Type Code
- Component ID 
- Span Scale Code 
- Test Number
- Test Reason Code
- Test Result Code
- Begin Date
- Begin Hour
- Begin Minute
- End Date
- End Hour
- End Minute
- Grace Period Indicator 
- Test Comment

**Linearity Summary Data - Fields applicable:**
- Gas Level Code (dropdown)
- Mean Measured Value (Text)
- Mean Reference Value (Text)
- Percent Error (Text)
- APS Indicator (dropdown)

**Linearity Injection Data - Fields applicable:**
- Injection  Date (Text/Date Picker)
- Injection Hour (Text)
- Injection Minute (Text)
- Measured Value (Text)
- Reference Value (Text)

**Protocol Gas Data - Fields applicable:**
- Gas Level Code (dropdown)
- Gas Type Code (dropdown)
- Cylinder ID (Text)
- Vendor ID (Text)
- Expiration Date (Text/Date Picker)

Note: Include the ability to add/update 3 records under Protocol Gas Data

**Comment by NadiaJL** [comment]
Referring to 
1. Screen 1 of 19: Remove duplicate vertical scroll bar - this is something weird with this particular Xd prototype. If you do see an "extra" scroll bar while interacting with these WFs please advance or go back one page/screen and return to the page you were just viewing and the "extra" scroll bar should be removed. 
The "extra" scrollbars are not on the actual Xd design file.

**Comment by NadiaJL** [comment]
@vishnunavuluri & @acollad1 Here is the updated ECMPS-EPA-Responsive-QA Linearity V1.6 WFs with the requested edits from today 5/3/22
Xd Doc Link: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

**Comment by NadiaJL** [comment]
@vishnunavuluri & @acollad1 Here is the updated ECMPS-EPA-Responsive-QA Linearity V1.6 WFs with the requested edits from today 5/4/22
Xd Doc Link: https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

Please let me know if/when these WFs are final and I can start working on Desktop 1024 & 1400
ZenHub #3408: https://app.zenhub.com/workspaces/roadmap-5f96fc2121b1e50016c7acce/issues/us-epa-camd/easey-ui/3408
