### ISSUE TITLE
Add security feature to the bookmark functionality on the cdd

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3458]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As the EPA I want the bookmark functionality to have a security feature so that the system is secured 

## Acceptance Criteria
Given that a user has selected the bookmark functionality on the cdd
When the system detects a CAMPD specific token
Then the system generates a bookmark url 

Given that a user has selected the bookmark functionality  on the cdd
When the system DOES NOT detect a CAMPD specific token
Then the system DOES NOT generate a bookmark url 

### Development Notes
- Note: Work on this ticket after all of the work for the bookmark functionality is complete 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

For testing:
1. put an incorrect token in place so that the bookmark url is not generated 
2. Put the correct token in place so the system generates the bookmark url 

## Testing
Test Case:  [TC765](https://campd-dev.app.cloud.gov/data/custom-data-download?bookmarkId=1164)
Tester: Maegan Wood

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by MaeganWood64** [comment]
@kstetsyuk [TC765](https://campd-dev.app.cloud.gov/data/custom-data-download?bookmarkId=1164) has passed
