### ISSUE TITLE
Identify MATS Emissions Relationships

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#346]
- [x] Identify relationships

 

- [x] Document ERD

**Comment by sdhawan16** [comment]
**ERD Documentation**

PDF: 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS/ERD%20for%20Prepackaged%20Data%20-%20MATS%20Emissions%20-%20EPA%20CAMD%20-%20v1.0.pdf

Raw File: 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS/ERD%20for%20Prepackaged%20Data%20-%20MATS%20Emissions%20-%20EPA%20CAMD%20-%20v1.0.drawio

Link to folder that contains the ERD files linked above:
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/MATS
