### ISSUE TITLE
Add Data Caveat to the CDD Data Preview 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3461]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CDD user I want the system to notify me when my customized data set contains a data caveat So that ........

## Acceptance Criteria

Given that a user has previewed their data set 
When a facility in their customized has a data caveat 
Then the system displays an alert above the data preview with the following message: 

### Development Notes
- Display the alert above the data preview like the download limit alert
- Link to wireframes for the[ download limit alert ](https://xd.adobe.com/view/5843045c-99a2-4c6e-b880-2f127f19796f-0d10/screen/7b7904fd-ce7a-4395-a244-dc95bfe06e7f/)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Background: 

During PI-8, the Datateers PO discussed adding functionality to the cdd that notifies users when their customized dataset contains a facility that has a data caveat. Caveats may include facility name changes and unit ID changes, for example.

Next Steps: 
 - Continue to discuss requirements and technical implementation. May need to have a product design meeting. 

Implementation Details:
This is probably around a 21 story point feature all together...

The following tables would be required...
- camd.plant_alias
- camd.unit_alias
- camd.unit_logical_move
- camd.unit_physical_move

High level Details...
- These tables will need to be added to the camdbsp nightly CDC job so that cloud.gov stays in sync with oracle.
- Add views necessary for Informatica to handle the sync similar to other camd tables being synced (ex. plant).
- Create views on the cloud.gov side that presents data in similar fashion as the UNIT_HISTORY_SS and MV_DATA_LOG_ALIAS materialized views in oracle.
- Modify all paginated api endpoints used to preview data on custom data download page to check if caveats exists and provide a flag, either in header or response, as to whether caveats exist or not
- Create api endpoint that would take a list of units/facilities and return the caveat data based on that list.
- Add a mechanism to download the caveats data to the campd ui on the custom data download page.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by NadiaJL** [comment]
@MaeganWood64  @tlageman-epa -epa here is the Figma WFs doc for the Data Caveat message - I will update the message text when I receive the correct wording from Travis
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3549%3A19933

**Comment by tlageman-epa** [comment]
@NadiaJL these look good thx! Here is draft language for the data caveat message where "Data Caveats File" would be the hyperlinked file.

The query has returned records with one or more data caveats which can be downloaded through the following link: Data Caveats File.

Also, I noticed that the WFs for the screensizes other than 1024 desktop still reflect the old flow where the bookmark feature was available prior to previewing data. Since that is no longer the case, can we put a note with each screensize that explains that and references the 1024 flow as the correct one. That way if we ever reference this in the future there is no confusion. I don't need you to spend time fixing all of them, so I think a quick note would suffice. Thx!

**Comment by NadiaJL** [comment]
@tlageman-epa @MaeganWood64 I have updated the Data Caveat message language and the bookmark functionality on screens 1200-1400 desktop. (I believe in the previous flow where the bookmark feature was available prior to previewing data, we had decided to just update the screens/WFs for 1024 - but all screen resolutions reflect this change now.)
https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=4102%3A27368
