### ISSUE TITLE
Identify SMOKE Emissions Relationships

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#347]
- [x] Identify relationships

 

- [x] Document ERD

**Comment by junie-stigdon** [comment]
PDF: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE/ERD%20for%20Prepackaged%20Datasets%20-%20SMOKE%20-%20EPA%20CAMD%20-%20v1.0.pdf?csf=1&web=1&e=ItUY4f

Draw.io: https://usepa.sharepoint.com/:u:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE/ERD%20for%20Prepackaged%20Datasets%20-%20SMOKE%20-%20EPA%20CAMD%20-%20v1.0.drawio?csf=1&web=1&e=xKOl9i

Folder with SMOKE Prepackaged Datasets deliverables: https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE?csf=1&web=1&e=qYoiOL
