### ISSUE TITLE
QA & Cert Module Screens - Resolutions above Tablet (v.2)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3473]
As an ECMPS user I want the QA & Cert Module Test Summary Screens built at all resolutions up to 1024 (except Tablet and Phone) so that I can access the application without any issues

**Comment by NadiaJL** [comment]
@vishnunavuluri Here is the updated draft of ECMPS-QA Linearity - Workspace - Desktop 1200
Shared Xd Link: https://xd.adobe.com/view/b0c830db-8df5-4c66-9e5c-52775350f7fe-e59b/

& the updated draft for ECMPS-QA Linearity - Desktop Wide - 1400
Shared Xd Link: https://xd.adobe.com/view/62212046-b608-4178-bc97-da3c5d3a43f1-3772/

**Comment by NadiaJL** [comment]
@vishnunavuluri Here is the updated draft of ECMPS-QA Linearity - Workspace - Desktop 1024
Shared Xd Link: https://xd.adobe.com/view/1b1c20cc-1c07-483f-b424-660fe5c36afa-4e4f/

**Comment by NadiaJL** [comment]
ECMPS-QA Linearity - Workspace - Import - Desktop large - 1024 V3.1
Xd Prototype: https://xd.adobe.com/view/b1185d82-f64f-40f8-a670-28b7b07dfcb5-e44b/

ECMPS- QA Global-View: ‘View’ Test Summary Data - Desktop large - 1024 V1.0 
Xd Prototype: https://xd.adobe.com/view/40aa3540-d85f-4b68-9bf2-63f694bee243-15f9/
