### ISSUE TITLE
Research SMOKE Resources

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#348]
- [x] Identify resources (list tables)

- [x]  Understand data

**Comment by junie-stigdon** [comment]
Identified CAMDPUB tables. Working on mapping the data back to CAMDBSP.

**Comment by junie-stigdon** [comment]
Tables for SMOKE: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE/Tables%20for%20Prepackaged%20Data%20-%20SMOKE%20Emissions%20-%20EPA%20CAMD%20-%20v1.1.pdf?csf=1&web=1&e=7E3dff

SMOKE Jobs and Resources: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE/Prepackaged%20Datasets%20Jobs%20and%20Resources%20-%20SMOKE%20-%20EPA%20CAMD%20-%20v1.2.pdf?csf=1&web=1&e=isuPfu

Folder for both SMOKE deliverables: https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Emissions%20Data/Prepackaged%20Datasets/SMOKE?csf=1&web=1&e=AnZ9bw
