### ISSUE TITLE
Spike: hourly Aggregation endpoints not returning the correct record count 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3481]
## Steps to Reproduce
1. Navigate to the emissions swagger page 
2. Make a GET request to the hourly emissions unit level endpoint for 2019-01-01 
3. Make A GET request to the hourly emissions facility level endpoint for 2019-01-01

In the response header for the unit level endpoint, the system returns  x-total-count: 96528  number of records. The system returns  x-total-count: 96528  for the facility level endpoint as well. The facility level endpoint should not contain the same amount of records as the unit level endpoint. The accurate number of records is needed for the aggregation endpoints so that the data preview for aggregation reflects the correct amount of records.

 The scope of this ticket is for the hourly aggregation endpoints. 

For testing, compare the total number of records to the unit level aggregation endpoint. Ensure that the number of records are not the same. Also, limit the time period when making get request to the endpoints, Limit the query to one day worth of data. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/adf42693-885a-46e8-bcc3-0093e489f556)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0bcb0874-71dc-4330-90a6-6639fe9cd3e9)

**Comment by sdhawan16** [comment]
The outcome of the spike:  Create views for each aggregation level and pull data from the view so the count is accurately determined

**Comment by sdhawan16** [comment]
Update: The view solution would not allow filtering and aggregating the data as expected. We will instead use create an additional query that returns the count value.  Ex. `query = this.createQueryBuilder('aud').select('COUNT(*) OVER() as count');`
