### ISSUE TITLE
Retest Only: CDD add/ remove data elements - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3489]
## Context 

1.	I can tab to the arrows used to sort the columns, but when I hit enter, nothing happens, the columns do not adjust to sort by ascending or descending.
12.	After making the customize column selection, I can tab to the select all and deselect all links, but when I hit enter, nothing happens.
13.	Select all and deselect all links need to be underlined

**Comment by aprematta** [comment]
Testing complete, these issues are now working in dev
