### ISSUE TITLE
Spike: lagging with the spinner 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3515]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user (CDD) I want the spinner to display right away so that I know an action is processing 

## Acceptance Criteria
Given that the filter logic is engaged 
When an action is processing 
Then the system displays the spinner right away 

Given that an action is processing 
When the action finishes processing 
Then the spinner disappears 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
- [ ] The Spinner on the UI does not engage right away and has lag, causing performance issues. Research is needed to find the root cause of this issue. 

- [ ] Issue seems to be more prevalent outside of Emissions Datatype (especially hourly) 

**Use cases** 
As for use cases where i encounter the UI lag here are the instances I took in the dev env. Please let me know if you need anything else:

	
Pick Allowance Holdings, then choose the following 4 facilities IDs: 3, 10, 26, 56 and preview
	
After that, I went to Allowance Transactions. When I click apply, the noticeable lag occurs. I put in the same 4 facilities and preview the query.
	
I then change to Allowance Compliance and hit apply and notice the same lag. When I added in the 4 facilities again and hit apply, I noticed another lag.
	
After that I decided to try a daily emissions query, and when I changed the data type/subtype to daily emissions and hit apply, I noticed the lag again.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by AbuFofanah** [comment]
There is a delay when redux updates the loading state before the API calls and when the custom data download component is re-rendered to show the spinner. The delay can be eliminated by managing the loading state locally.
