### ISSUE TITLE
Identify Allowance Relationships

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#352]
Dev Tasks
 Identify table relationships in CAMDBSP
 Document high-level ERD
Outcomes
ERD of CAMDBSP relationships

**Comment by JorjaComer** [comment]
Change approved by Travis on 10/29

[Customer Value Partners Mail - Changes Zenhub TASKS (ER diagrams) approval request.pdf](https://github.com/US-EPA-CAMD/PI-1/files/5461314/Customer.Value.Partners.Mail.-.Changes.Zenhub.TASKS.ER.diagrams.approval.request.pdf)

**Comment by junie-stigdon** [comment]
Completed ERD for Allowance Data.

PDF: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data/ERD%20for%20Prepackaged%20Data%20-Allowance%20Data%20-%20EPA%20CAMD%20-%20v1.2.pdf?csf=1&web=1&e=1DTRNH

Raw draw.io: https://usepa.sharepoint.com/:u:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data/ERD%20for%20Prepackaged%20Data%20-Allowance%20Data%20-%20EPA%20CAMD%20-%20v1.2.drawio?csf=1&web=1&e=Pnb8Aq

Link to Folder for Allowance Data: https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/Data%20Relationships/Allowance%20Data?csf=1&web=1&e=4hA0bU
