### ISSUE TITLE
ECMPS: Error accessing Facilities-Configurations 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3528]
**Issue:**
When a user opens a Configuration under Global View>Facility, the app throws an Unhandled Error
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/dad51602-54fb-4edd-83f6-954cc6794b38)

Steps to recreate:
- Navigate to Monitoring Plans in the left-hand menu (Global View)
- Click on Monitoring Plans, on the Select Configurations screen - Select a Facility and click Open for a Configuration underneath
- The App throws an error

**Comment by mosesdeeCVP** [comment]
Bug Fixed
