### ISSUE TITLE
Issue with Evaluation - UI

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3530]
Issues:

- When a MP that needs Evaluation is Evaluated, it is not showing the actual Evaluation Status, instead reverts the Status back to Needs Evaluation. But users still receive the notification email and the Evaluation Report
- The color on 'Needs Evaluation' Evaluation Status is wrong (Gray). It should be Yellow

**Comment by mosesdeeCVP** [comment]
![3530 Issue with Evaluation - UI - Pass.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/771a0759-11c5-451e-9738-2a0ae915a148)

**Comment by mosesdeeCVP** [comment]
![3530 Issue with Evaluation - UI - Critical Errors.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6c212de4-4270-45ab-bbf6-23196a1c8bf9)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
