### ISSUE TITLE
Layout for Individual Configurations Tab - Workspace

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3533]
As an ECMPS user, I want a separate screen for the individual Configurations selected so that I can review and update QA & Cert data for it

Acceptance Criteria:

Given I am an ECMPS user on the Select Configurations screen
When I open a Configuration tab
Then I see that the layout of the tab matches that in the prototype provided below

Workspace screen shall have Import option

Prototype for Reference (Use screens 3, 4 of 14):
https://xd.adobe.com/view/c103c998-65ff-432a-b1f9-c586ebbceafa-9450/

**Comment by mosesdeeCVP** [comment]
Test Case: [TC727](https://epacamd.testquality.com/project/11428/plan/24660/test/367992)

**Comment by mosesdeeCVP** [comment]
![3533 Layout for Individual Configurations Tab - Workspace - Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8c5a1e1f-9d6a-405b-9be7-b1e4fac7a5c9)

**Comment by mosesdeeCVP** [comment]
![3533 Test Only- Layout for Individual Configurations Tab - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e9290bb4-0636-4d09-836b-e5a68a81f885)

**Comment by mosesdeeCVP** [comment]
Test Passed
