### ISSUE TITLE
QA: Linearity Summary Data - Test Summary Data Section

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3534]
As an ECMPS user, I want to view the Test Summary Data for the Test Type 'Linearity Summary Data' so that I can use it as reference when making any updates

Acceptance Criteria:

Given a user selects 'Test Type - Linearity Summary' from the dropdown
When the Test Summary Data is displayed and is the first data table
Then the data is displayed in a single table (see list below for columns and order)

Unit or Stack Pipe ID
Test Type Code
Monitoring System Code
Component ID 
Span Scale Code
Test Number
Test Reason Code
Test Description
Test Result Code
Begin Date
Begin Hour
Begin Minute
End Date
End Hour
End Minute
Grace Period Indicator 
Year
Quarter
Test Comment
Injection Protocol Code

Given a user is viewing Test Summary Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [] Yes 
- [x] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Prototype:https://xd.adobe.com/view/3c5f7ecf-ee2b-4c23-954a-554e12a8f799-690c/
Reporting Instructions (Page 30): https://ecmps.camdsupport.com/documents/ECMPS%20QA%20Reporting%20Instructions%202021%20Q4.pdf

**Comment by mosesdeeCVP** [comment]
![2534 QA- Linearity Summary Data - Test Summary Data Section - Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0c87710a-2945-46e8-87b7-7ad72119de6d)

**Comment by mosesdeeCVP** [comment]
![2534 QA- Linearity Summary Data - Test Summary Data Section - Logged Out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ad8de832-f038-43f0-a4ef-a341d459012f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC748](https://epacamd.testquality.com/project/11428/plan/25475/test/370206)
