### ISSUE TITLE
Add Bookmark functionality to cdd res 1024+- 508 Issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3553]
## Context

Testing complete for 3355, ANDI is indicating that there is an ARIA Hidden = True when the modal is active, hiding it from a screen reader. Looking at the code, I think it's this from the HTML:
div id="root" aria-hidden="true" data-modal-hidden=""

This is also occurs for mobile breakpoints

**Comment by MaeganWood64** [comment]
@aprematta Issue is ready for 508 Testing!

**Comment by aprematta** [comment]
Looks good, I'm not getting the warning in ANDI and I don't see any aria hidden - true in the html
