### ISSUE TITLE
Bug: Include Aggregation on the custom data download

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3554]
## Test Case
Test Case: [TC702](https://epacamd.testquality.com/project/11428/plan/24503/test/366478)

## Steps to Reproduce

Issue 1: 
**System maintains applied time period criteria after clearing data preview** 
1. Navigate to the cdd 
2. Select Emissions as a data type 
3. Select an an emissions sub type 
4. Apply selections 
5. Apply any required filter criteria
6. Preview data 
7. Select clear all 
8. Open the  time period filter 

System maintains applied time period after clearing all filters 

Issue 2: 
Aggregation data preview is not working consistently 
 1. Navigate to the cdd 
2. Select Emissions as a data type 
3. Select hourly emissions as a sub type 
4. Select facility as a aggregation level 
5. Apply selections 
6. Apply time period criteria 
7. Select Preview data 

The system does not produce a data set.

### User Story
As a custom data download user I want to aggregate emissions data So that I can conduct analysis 

### Acceptance Criteria

Given that a user has navigated to the custom data download 
When Emissions is selected as a data type
Then the system displays the aggregation functionality in accordance with the [Wireframes 
](https://xd.adobe.com/view/523c938e-a55c-4475-8eae-72d4b842cd0e-076f/)
AND the aggregation functionality displays "Unit (No Aggregation)" by default
'
Given that a user has selected Emissions as a data type 
When the functionality is displayed 
Then data sub type and aggregation are required 

Given that a user has selected Emissions as a data type
When the aggregation functionality is displayed 
Then the options are:  Unit (No Aggregation), Facility, State, National 
And the user can select a single value 

Given that a user has applied Emissions as a data type on the custom data download 
When the functionality is displayed 
Then the system displays the users selected data type, data sub type, and aggregation level 

Given that a user has applied Emissions as a data type and applied filter criteria 
When the selected aggregation level is changed 
Then the system maintains the applied filter criteria 

Given that a user has previewed their Emissions dataset 
When data preview functionality is selected 
Then the system displays a data table 
AND the data elements are consistent with the selected aggregation level 

Given that a user has previewed their Emissions dataset 
When the selected aggregation level is changed 
Then the system clears the data preview 
AND maintains the applied filter criteria 

Initial Aggregation wireframes: 
[Wireframes 
](https://xd.adobe.com/view/523c938e-a55c-4475-8eae-72d4b842cd0e-076f/)

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=10622)
- Test [Include Aggregation on the custom data download](https://web.testquality.com/site/epacamd/project/11428/runs/161678?resultId=2826695) in Run [Include Aggregation on the custom data download](https://web.testquality.com/site/epacamd/project/11428/runs/161678) (linked to Cycle [Aggregation](https://web.testquality.com/site/epacamd/project/11428/cycles/24503)).

**Comment by MaeganWood64** [comment]
@kstetsyuk TC702 Passed
