### ISSUE TITLE
Update CAMPD home page for Maps and Graphs 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3555]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to access the Maps & Graphs section from the home page so that I can navigate the web page 

## Acceptance Criteria
Given that a user has accessed the CAMPD Home Page 
When the Maps & Graphs functionality is displayed 
Then the section **does not** contain  a coming soon label 

Given that a user has accessed the CAMPD Home Page 
When the Maps & Graphs title is selected 
Then system directs the user to the Maps & Graphs page 

Given that a user has accessed the EASEY content Repo 
When the functionality is displayed 
Then the user has the ability to edit the maps and graphs file in all environments 

**( should this include prod? maps and graphs is going out in 1.1?)** 

### Development Notes

**Dev Tasks** 
- Remove coming soon from the maps & graphs section on the home page 
- Maps & Graphs label on the home page should link to the MAPs and Graphs functionality 
- Ensure that the maps and graphs files in the easey content repo are replicated in all environments 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c3195199-4e67-428f-a4df-d1be44bfcfb5)

## Testing
Test Case: [TC829](https://epacamd.testquality.com/project/11428/plan/26079/test/382988)
Tester: Maegan Wood 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by MaeganWood64** [comment]
@tlageman-epa TC829 Passed

**Comment by MaeganWood64** [comment]
@aprematta This ticket is ready for 508 testing
