### ISSUE TITLE
Issue with Unit Stack Configuration 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3556]
Issue:

- Import is working but is only showing in the database, not in the corresponding report. So users will be unable to view the import.
- Should be able to view the unit relationship status under the Location Attributes and Relationships Section specifically under Relationships

- Relates to issue #3374

**Comment by mosesdeeCVP** [comment]
Bug fixed. A separate ticket will be made to fix the Unit Stack bug for the UI.
