### ISSUE TITLE
Create MDM Endpoint: Test Type Code (Test Summary Data-Linearity Summary) 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3569]
Create MDM Endpoint for Test Summary Data-Linearity Summary Data:

Test Type Code (Default to “LINE”)

**Comment by mosesdeeCVP** [comment]
![3569 Create MDM Endpoint- Test Type Code (Test Summary Data-Linearity Summary).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7333e1c6-4925-4ebb-94a8-966fae39fc7f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC743](https://epacamd.testquality.com/project/11428/plan/25413/test/369629)

Test Passed
