### ISSUE TITLE
Test Only: Add API Endpoint - Test Summary Data 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3570]
Endpoint to be verified:

https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Test%20Summary/TestSummaryWorkspaceController_createTestSummary

**Comment by mosesdeeCVP** [comment]
Test Case: [TC816](https://epacamd.testquality.com/project/11428/plan/26040/test/380788)

**Comment by mosesdeeCVP** [comment]
Test Passed
