### ISSUE TITLE
Add API Endpoint - Linearity Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3571]
The scope of the ticket includes Unit Testing and Testing the following endpoint:
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Linearity%20Injection/LinearityInjectionWorkspaceController_createLinearityInjection

**Comment by mosesdeeCVP** [comment]
Test Case: [TC846](https://epacamd.testquality.com/project/11428/plan/26561/test/383917)

**Comment by mosesdeeCVP** [comment]
Test Passed
