### ISSUE TITLE
Create MDM Endpoint:  'Test Reason Code' (Test Summary Data-Linearity Summary) #3569                                                                                          

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3574]
Create MDM Endpoint for Linearity Summary Data:

Test Reason Code

For Testing (Options for Test Reason Code) :

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a16c334c-0f17-4aac-bcc4-7e95861df03c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC742](https://epacamd.testquality.com/project/11428/plan/25413/test/369523)

**Comment by mosesdeeCVP** [comment]
![3569 Create MDM Endpoint- 'Test Reason Code' (Test Summary Data-Linearity Summary).png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fae4654d-b322-4107-b038-bfc9924e485b)

**Comment by mosesdeeCVP** [comment]
Test Passed
