### ISSUE TITLE
Create MDM Endpoints for Test Summary Data-Test Result Code Drop Down (Linearity Summary) #3569

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3575]
Create MDM Endpoint for Linearity Summary Data:

Test Result Code

For Testing (Options for Test Result Code) :
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/bf58f954-9063-4ad5-94ca-32011d03f085)

## Testing 

Test Case: [TC779](https://epacamd.testquality.com/project/11428/plan/26040/test/377982)
Tester: @JanellC

**Comment by JanellC** [comment]
TC779 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e0da944d-0e42-4f4f-abdb-6c1557a3bee0)

https://api.epa.gov/easey/dev/master-data-mgmt/test-result-codes?api_key=PXPWlQGB3wKXotkWN1PbSwbSoM7CoWW0ZMPWYtfc
