### ISSUE TITLE
Error when Exporting or Importing Qual PCT Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3579]
Issue:

When a user imports MP data with Qual data and Qual PCT data, then Qual PCT data is not getting updated even when parent Qual data is available

Steps to recreate:
- Select any Facility-Configuration.
- Checkout and Import data for it with a JSON that has both Qual data and Qual PCT data
- After the Import is successful, you will see that the Qual data is available, however the Qual PCT data cannot be seen

**Comment by mosesdeeCVP** [comment]
Bug Fixed [TC712](https://epacamd.testquality.com/project/11428/plan/22483/test/367830)
