### ISSUE TITLE
Unit Control: Equipment Param Code not showing values

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3580]
Issue 1:
Unit Information->Unit Control Data-> Equipment Parameter Code is not displaying the values/data even when they are available

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/300bae56-80ab-4a65-9d53-47301cefd01c)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/fdc94732-5c32-44b7-8f28-3cf1af0bcbe7)

When user tries to create Unit Control data from scratch, they see the following error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/46198622-daf4-4220-926d-558146ee7d7e)

- Update the field name 'Equipment Parameter Code' to 'Parameter Code' both in the data table for Unit Controls and the View/Edit/Create Modal

**Comment by mosesdeeCVP** [comment]
Bug fixed
