### ISSUE TITLE
Issue with End Date and End Hour

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3581]
Issue:

Users are able to enter End Hour without a value for End Date and vice versa

Solution: 
End Date and End Hour should go together at all times. Meaning, that when a user enters an End Date and no value for End Hour, OR enters a value for End Date and no End Date, then they should be unable to save the data until this issue is fixed

**Comment by mosesdeeCVP** [comment]
Bug Fixed
