### ISSUE TITLE
Heading levels Improperly Structured and/or Skipped

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3591]
**Issue:**

Location: ECMPS Home Page - Informational/Outage Banner
Heading tags have been implemented but heading levels were either skipped (for example, H2 to H4) or did not move down a level when a logical subsection was present. 

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/b508ada5-c46e-4d56-90da-ce8eb0bdcb7b)<h3 class="usa-alert__heading">Informational Message:</h3>

**Resolution:**
- Move the ECMPS banner to under the About ECMPS 2.0 Beta (Content Management). See screenshot below for reference:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/63947cbf-1f90-443b-9b81-71b776e4964b)
- Review the heading tags and adjust the structure so that subsections of previous headings use the next level, and that there are no heading level skips

**Comment by aprematta** [comment]
The only issue is on the home page. "About ECMPS 2.0 Beta" is currently at an H3...... it needs to be at an H2 because of the informational message is not present, then there will be a heading skip from H1 to H3

**Comment by subrataroyCVP** [comment]
@aprematta 

Issue resolved.

**Comment by aprematta** [comment]
About ECMPS 2.0 Beta is now an H2, no further issues
