### ISSUE TITLE
Form Fields Mislabeled on Create/Edit Modals

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3592]
**Issue:**
There is a label tag present with the form field(s), however it is not properly associated. The for= attribute of the label must match the id= attribute of the input tag. 

For all create/edit modals where the label name is more than one word, the for= does not match the id=:
<label for="Default Value">Default Value</label>
<input id="Default-Value" 

**Resolution:**
Properly associate a form label with all input elements for Create/Edit modals on:
Default
Formula
Load
Method
MATS
Qual, 
Rectangular Duct
Span
System
Unit Information

**Comment by aprematta** [comment]
Went through all the forms I could find..... all were properly labeled
