### ISSUE TITLE
Bug: Data preview not displaying consistently 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3600]
## Steps to Reproduce

1. Navigate to the [cdd in staging ](https://campd-stg.app.cloud.gov/data/custom-data-download)
2. Apply a data type/ sub type (ex. ozone season emissions) 
3. Apply any required filter criteria 
4. Select preview data 
5. Select home 
6. Navigate back to the cdd
7. Apply a data type/ sub type (ex. ozone season emissions) 
8. Apply any required filter criteria 
9. Select preview data 

Then the system displays the data preview and clears it on the second query the user makes. A user is required to select preview data twice in order to view their dataset. This is an issue in the staging environment but the bug is not happening in the dev environment.

**Comment by JanellC** [comment]
If you can't reproduce this bug in dev, tst, or perf then the bug has been fixed

**Comment by MaeganWood64** [comment]
Issue is no longer present
