### ISSUE TITLE
Emissions API Changes 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3614]
## Context 

CBS meeting on 6/2 
CVP will create a new set of methods to pass in a date and return all emissions data that have changed since that date, and the next date to use.  CVP to to backlog to add to CAMPD emission APIs

Next steps: Review the document Dwayne provided and evaluate if this ticket is still valid

**Comment by JanellC** [comment]
Per sprint planning on 6/7, this work will be completed by the tech team. @MaeganWood64 @JorjaComer

**Comment by JanellC** [comment]
Need to review the document that Dwayne provided in order to asses if this ticket is still needed

**Comment by MaeganWood64** [comment]
Work being handled on the emissions module side
