### ISSUE TITLE
Restructure automated tests to capture more use cases 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3618]
## Context 

During sprint 8.4 retro, the team discussed restructure automated tests to capture more use cases. Want to discuss how to approach this as we move closer to the 1.1 release.

**Comment by MaeganWood64** [comment]
- Want to both resturcture Frequency of automated test suite runs (to be tracked on TT side)
-Want to use user data to inform automated test cases
