### ISSUE TITLE
QA: Update Test Type Dropdown Options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3621]
- Update 'Fuel Flow to Load Test' to 'Fuel Flow to Load' 
- Fix the Typo in Test Qualification
- Update 'Unit Test' to 'Unit Default'

**Comment by mosesdeeCVP** [comment]
![Typos QA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/abefcb0b-629b-40ac-8948-72538904aa61)

**Comment by mosesdeeCVP** [comment]
Updates completed
