### ISSUE TITLE
Show Inactive Checkbox throws an Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3622]
Issue:
When a user selects/clicks 'Show Inactive' checkbox in the individual Configurations screen, the system throws the following error:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/648a9f5d-674c-4323-822e-b1ece0bed45b)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
