### ISSUE TITLE
MP Import - Fix Success Message Layout on the Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3623]
When a MP is imported successfully, then the Modal that displays the success message has some inconsistencies. See below:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c822b98f-6bde-4438-ac34-2ef4f38ef3aa)

**Expected:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/f74d37a7-8d2e-494d-ae49-9d8e3b9dcb6c)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
