### ISSUE TITLE
EASEY facilities Dependabot Alert 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3629]
## Context 

Issue found in the facilities api as of 6/6: 
As of 7/26, No fix available
[Crash in HeaderParser in dicer #7](https://github.com/US-EPA-CAMD/easey-facilities-api/security/dependabot/7)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a5a6bc45-23a1-41d1-9739-d7d243bbc407)

**Comment by JanellC** [comment]
Per planning on 6/7, the team can not remediate this issue until a patched version is available.

**Comment by MaeganWood64** [comment]
Ticket no longer needed
