### ISSUE TITLE
Bug: Crash when changing data type from Bookmark Link 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3634]
## Test Case
Test Case: [TC850 ](https://epacamd.testquality.com/project/11428/plan/24924/test/fullscreen/383929)
Tester: Maegan Wood

## Steps to Reproduce

**User cannot switch between data types when using bookmark url** 

1. Open the cdd using a bookmark link :https://campd-dev.app.cloud.gov/data/custom-data-download?bookmarkId=1169
2. Change the data type to  facility/ unit attributes 

The system does not load. The spinner keeps spinning and doesn't make the filters available . The same thing happens for emissions sub types and allowance transactions. 

**User cannot switch between data types when using bookmark url** 

1. Open the cdd using a bookmark link :https://campd-dev.app.cloud.gov/data/custom-data-download?bookmarkId=1169
2. Change the data type to  compliance emissions based 
3. Change the data type to compliance allowance based 

The system crashes.

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=10877)
- Test [Display selected filter tags from bookmark url](https://web.testquality.com/site/epacamd/project/11428/runs/162486?resultId=2842979) in Run [Display selected filter tags from bookmark url](https://web.testquality.com/site/epacamd/project/11428/runs/162486) (linked to Cycle [Bookmark functionality on CAMPD](https://web.testquality.com/site/epacamd/project/11428/cycles/24924)).

**Comment by MaeganWood64** [comment]
@tlageman-epa TC850 Passed
