### ISSUE TITLE
Hide bookmark button until data preview is displayed 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3635]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD User
I want to only be able to see the bookmark button when I have previewed my data
So that I am aware of the table that I am bookmarking

## Acceptance Criteria
Given that a user has previewed their dataset 
When the functionality is displayed 
Then the bookmark functionality is available 

Given that a user has removed the data preview (ex. remove/add filters)
When the functionality is displayed
Then the bookmark functionality is hidden 

### Development Notes
- On dekstop breakpoints Hide the bookmark button until a user previews their dataset. This functionality needs to be implemented in order to be 508 compliant 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
[Book Mark Wireframes ](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=3545%3A17236)

## Testing
Test Case: [TC854](https://epacamd.testquality.com/project/11428/plan/26079/test/384531)
Tester: Maegan Wood 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
This tickets needs to be completed so that there is not a 508 issue of a loss of functionality with the bookmark button

**Comment by MaeganWood64** [comment]
@tlageman-epa TC 854 Passed
