### ISSUE TITLE
Bug: Facility/ unit attributes not returning the correct amount of records 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3639]
## Context 
The number of records returned (both campd UI and API) does not align with what is in the database. Use Op year 2021 as an example case.

The issue with CAMPD api query.  The VW_FACILITY_UNIT_ATTRIBUTES had the inner join with CAMD.GENERATOR/CAMD.UNIT_GENERATOR.  So the result only contains unit associated with EIA generator.  The fix will be the left outer join with those tables instead of the inner join.

## Dev Tasks 

- [x] modify the view to use the left join will return the same amount of records as the unit_fact table.

**Comment by sdhawan16** [comment]
Change to the view has been made in dev and script for vw-facility-unit-attributes has been modified in easey-db-scripts

**Comment by JanellC** [comment]
Updated view. The system is now returning 4269 records for year 2021 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e1b6fc69-8f58-459b-9718-49a97eaf2b2e)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/210ec3e0-d791-46cd-9498-5f4eaf9320d3)
