### ISSUE TITLE
Bug: Download functionality  not working on bulk data files page 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3641]
## Test Case
Tester: Maegan Wood
Test Case: [TC800](https://epacamd.testquality.com/project/11428/plan/24093/test/379209)

## Steps to Reproduce

**Download not working on the bulk data files page** 
1. Navigate to the bulk data files page 
2. Select a file 
3. The download functionality remains disabled and a user can not download a file  

### Dev Notes 
- Will need to go in after Camel Casing is fixed and EDR & XML files are migrated from SFTP to S3 to ensure that nothing broken on the UI

**Comment by jwhitehead77** [comment]
Filename and File size has been fixed but the download needs more development

**Comment by MaeganWood64** [comment]
@kstetsyuk TC800
