### ISSUE TITLE
Bug: Added/ removed data elements appearing at the front of the data preview 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3642]
## Test Case
TC: [881](https://epacamd.testquality.com/project/11428/plan/26079/test/388397)
Tester: Maegan Wood

## Steps to Reproduce
1. Navigate to the cdd 
2. Select a data type/ sub type 
3. Apply an required filter criteria 
4. Preview Data 
5. Select component to remove/ add data elements 
6. remove or add data elements and apply selections 

The system displays the removed/ add data elements at the beginning of the data preview table. The expected functionality is to inject the column into the same location it was before.

**Comment by MaeganWood64** [comment]
@tlageman-epa TC881 Passed
