### ISSUE TITLE
Update QA Process UPDATE_ECMPS_STATUS_FOR_TEE_EVALUATION.

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3646]
- [ ] Use the existing UPDATE_ECMPS_STATUS_FOR_MP_EVALUATION (the MP Evaluation version) as a model.

- [ ] Any code that relates to emissions will need to be noted in a comment, but left out until emissions are worked on.

**Comment by ayang2017** [comment]
Finished and ready for test.
