### ISSUE TITLE
Bug: Aggregation Pagination endpoints returning 500 error when the system detects no results 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3655]
## Test Case
TC: [TC801](https://epacamd.testquality.com/project/11428/plan/20171/test/379418)
Tester; Maegan Wood
## Steps to Reproduce

1. Make a GET request to a pagination aggregation endpoint where the system does not return any results for the specified page and per page parameters 

 https://api.epa.gov/easey/dev/emissions-mgmt/emissions/apportioned/hourly/nationally?api_key=T8r7OW4f12XtWKLY7CPgKmKu1WoP3TVG0x4eqmlB&stateCode=al%20%20%7C%20%20FL%20&beginDate=2020-01-01&endDate=2020-01-14&page=10&perPage=250

The system returns a 500 internal server error. The system should return a 400 bad Request error, reading ""

## Context 

When a user runs a GET request for a pagination aggregation endpoint and the system does not return data for  the specified page and per page parameters then the system returns a 500 error. The system should return empty brackets. **This functionality will need to be fixed for all of the pagination aggregation endpoints**. This is not applicable to the streaming aggregation API endpoints. As apart of the scope of this ticket the team needs to fix and test the following endpoints : 

**List of endpoints to be fixed**
- All of the aggregation endpoints located in the emissions API

**Comment by MaeganWood64** [comment]
@kstetsyuk TC801 Passed
