### ISSUE TITLE
Bug: Allowance Transactions not producing data preview 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3658]
## Test Case
Test Case: [TC776](https://epacamd.testquality.com/project/11428/plan/26079/test/fullscreen/377929)
Tester: Maegan Wood

## Steps to Reproduce
Navigate to the cdd
select allowance transactions as a data type 
Apply a transaction date of 01/01/2019-01/01/2020
Apply the following transaction types: emissions adjustment deduction and emissions deduction 
Select Preview Data 

The system does not produce a data preview

**Comment by MaeganWood64** [comment]
@kstetsyuk TC776 Passsed
