### ISSUE TITLE
Bug: Compliance Allowance Based Data Preview inconsistency 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3659]
## Test Case
Test Case: [TC799](https://epacamd.testquality.com/project/11428/plan/26079/test/378334)
Tester: Maegan 

## Steps to Reproduce

1. Navigate to the cdd 
2. Select Compliance allowance based as a data type 
3. Apply Adams- Columbia electric cooperative as a owner/ operator 
4. Select data preview 

The data preview displays multiple years. However, if you select the year filter the year filter only displays 2020 as an option.

**Comment by MaeganWood64** [comment]
@kstetsyuk @sgillEPA TC799 passed
