### ISSUE TITLE
Add  "stackPipeRecordId" and "beginReportPeriodId" (Need by End of July)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3660]
Need to add the database keys for stack and unit records to the MP management API in the ECMPS 2.0 backlog. This data will be needed at the same time as the Reporting Frequency data.

Endpoint Info: 
- https://api.epa.gov/easey/dev/monitor-plan-mgmt/plans/3/configurations
- https://api.epa.gov/easey/dev/monitor-plan-mgmt/plans/MDC-1ABE8566A0314B8C821A9A92BB4C9530

Dev Notes:
- Include "stackPipeRecordId" in the "locations" records.
CVP to add database key for stack and unit records to emissioners backlog.  Need by same timeframe as reporting frequency item
- Include "beginReportPeriodId" in the root monitoring plan records.
CVP to add beginReportPeriodId to emissionsers backlog.  Need by same timeframe as reporting frequency item

Testing: Make calls to the endpoints thru POSTMAN and verify that they are available

**Comment by mosesdeeCVP** [comment]
Test Case: [TC821](https://epacamd.testquality.com/project/11428/plan/19352/test/381274)
Test Passed
