### ISSUE TITLE
Add the Missing unitStackConfiguration Records (Need by End of July)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3662]
Need to add the missing unitStackConfiguration records to the https://api.epa.gov/easey/dev/monitor-plan-mgmt/plans API. This data will be needed at the same time as the Reporting Frequency data.

Note: Jason to meet with Mark and Dwayne to show the UnitStack Config data from Export

**Comment by annalbrecht** [comment]
These records are present in 2.0.
