### ISSUE TITLE
Maps and Graphs PHP Proxy

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3666]
From CBS Integration Meeting ... 

EPA will determine the name that will be used for the proxy in the URL. https://campd.epa.gov/tools/app-name
EPA will determine who needs to be contacted to get the proxy set up in dev.
EPA to determine whether CVP or ERG will own proxy set up. EPA would like CVP to own the proxy setup.

**Comment by maheese** [comment]
Here's the repository that contains the proxy: https://github.com/thomascjohnson/cf-subpath-proxy

**Comment by MaeganWood64** [comment]
- Have to Transition Rshiny Proxy application from EPA devs to CVP.

**Comment by MaeganWood64** [comment]
@maheese @kstetsyuk TC804 Passed
