### ISSUE TITLE
QA & Cert: Test Summary & Linearity DTO Validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3670]
The following are Test Summary & Linearity checks that should be applied at the DTO property level using a validation decorators.

[General Test Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)
- [x] TEST-1	Test Begin Date Valid
- [x] TEST-2	Test Begin Hour Valid
- [x] TEST-3	Test Begin Minute Valid
  - The _If BeginDate is on or after ECMPS MP Begin Date_ part of the check will need to be a General Check as you need the Oris Code and Unit/Stack Location data for MP lookup. The rest can be done as a DTO validation.
- [x] TEST-4	Test End Date Valid
- [x] TEST-5	Test End Hour Valid
- [x] TEST-6	Test End Minute Valid
  - The _If EndDate is on or after ECMPS MP Begin Date_ part of the check will need to be a General Check as you need the Oris Code and Unit/Stack Location data for MP lookup. The rest can be done as a DTO validation. (Return Result C will be part of this ticket scope)
- [x] TEST-7	Test Dates Consistent
  - If this gets complicated as a DTO validation move to #3669 and implement as a general check
- [x] TEST-13	Test Number Valid
  - Shall be done at the Test Summary level for all Test Types

Note: The general tests are applied at the Test Summary level across the Test Types

**Comment by mosesdeeCVP** [comment]
Test Case: [TC775](https://epacamd.testquality.com/project/11428/plan/26040/test/376973)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by fanwari1** [comment]
Just wanted to note that TEST-7 was done as a general check in this ticket.
