### ISSUE TITLE
Import Test Summary Data from File

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3675]
## User Story 
As an ECMPS user I need the ability to import test data from a file so that I can use it to create new data

## Acceptance Criteria:

Given I am on the 'Import Test Data' modal 
When I select the 'Import from File' option
Then I can import test data from a file on my local

Note: 2 validations that show up when a user selects a file: 
- Only JSON files are allowed
- Format needs to be valid

Invision URL: https://projects.invisionapp.com/freehand/document/TdahPfbEb
Reference Screenshots:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4fd3f79d-ec4c-470f-a75e-52082cbf87a0)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c45ba057-7a0a-4aa7-88d3-8c01dc45a1f5)

## Testing 
Test Case: [TC767](https://epacamd.testquality.com/project/11428/plan/26040/test/375995)
Tester: @JanellC

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3675?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP

**Comment by vishnunavuluri** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3675?planning-poker) with ZenHub @JanellC

**Comment by JanellC** [comment]
TC767 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/41113023-3f05-42ae-9fb5-d871ab3b5e27)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ebd3f997-c437-4371-8fd4-5956b36c7d0b)
