### ISSUE TITLE
Manage 2.0 Emissions Data 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3679]
Required for Beta completeness:

View and Edit all Emissions data sections (see diagram below)
Import 
Export

![Capture.JPG](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/8b33531b-2fd3-44dc-b281-d02a9a7dccea)

**Comment by annalbrecht** [comment]
At the ECMPS 2.0 ticket refinement meeting held on 2/13/24, Chris instructed us to close Uber Epics.
