### ISSUE TITLE
Monitoring Plan UI Design

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#369]
## Tasks
- UI design discussions (information architecture work, draft wireframes, high-fidelity UI designs)
- Usability/user acceptance testing (test user experience with real users using wireframes/workflows/prototypes)

## Section Priority
- Methods
  - Method
  - Supplemental MATS
- Systems and Components
  - System Component
    - Analyzer Range
  - System Fuel Flow
- Formulas
- Spans
- Loads
- Defaults
- Qualifications
- Unit Characteristics _(will display if viewing a unit location)_
  - Unit Programs
  - Unit Capacity
  - Unit Control
  - Unit Fuels
- Stack/Pipe Attributes and Relationships _(will display if viewing a stack/pipe location)_
- Rectangular Duct WAFs

Sections shall display in alphabetic order.
Reporting Frequency will be on main MP page.
 "Monitor" shall be removed from MP section labels.

## Assets
- [One EPA Standalone Web App Template Options _(updated 2/26/2021)_](https://xd.adobe.com/view/08505c73-3291-4c0a-819f-982951ae417f-5d03/)
- [EASEY-In IA Monitoring Plans _(updated 2/26/2021)_](https://xd.adobe.com/view/c6cac0f6-e16b-42f0-b98b-cf429934000b-9399/)

**Comment by JorjaComer** [comment]
Future MP design work will be associated to the feature for which it's needed.
