### ISSUE TITLE
QA & Cert: Test Summary & Linearity DTO Validations (Data Import Checks)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3709]
The following are Test Summary & Linearity checks that should be applied at the DTO property level using a validation decorators.

[QA and Certification Data Import Checks](https://ecmps.camdsupport.com/documents/ECMPS%20Import%20Check%20Specifications%202018Q2.pdf)
- [x] IMPORT-24 - QA Facility Present in the Production Facility Table
- [x] IMPORT-34 - Inappropriate Year for Test
- [x] IMPORT-37 - Inappropriate Test End Date

## Testing 

Test Case: [TC787](https://epacamd.testquality.com/project/11428/plan/26040/test/378007)
Tester: @JanellC

**Comment by JanellC** [comment]
TC787 passed
