### ISSUE TITLE
Add Export to Left-Hand Menu

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3717]
As an ECMPS user, I want an export option in the left-hand menu so that I can use it to access the data download/export functionality

Acceptance Criteria:

Given I am an ECMPS user
When I review the left-hand menu in the Global-View
Then I see the 'Export' option

Given I am an ECMPS user
When I review the left-hand menu in the Workspace
Then I see the 'Export' option

Given I have located the export option for either of the views
When I click on it
Then I am navigated to the Select Configurations screen 

Note: An empty 'Select Configurations' screen and header would read Export Data
Testing to include both the Global-view and the workspace

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ae022b73-15c1-4182-b8ad-418f4a59c226)

**Comment by vishnunavuluri** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3717?planning-poker) with ZenHub @addisgmichael

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3717?planning-poker) with ZenHub @cw-cvp @fanwari1 @JanellC @jeffreyaggrey @subrataroyCVP @Qb10 @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Case: [TC758](https://epacamd.testquality.com/project/11428/plan/26040/test/375913)

**Comment by mosesdeeCVP** [comment]
![3717 Add Export to Left-Hand Menu.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0ad69b09-ff78-4651-a7e7-041ba1e7c8f4)

**Comment by mosesdeeCVP** [comment]
Test Passed
