### ISSUE TITLE
Select Configurations to Export

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3718]
As an ECMPS user, I want the ability to select a Facility from a list so that I can export data for it

Acceptance Criteria:

Given a user selects 'Export' from the left-hand menu
When they are navigated to the Select Configurations screen and data is displayed
Then the user can see information on the Facility, Oris Code and State

Given a user chooses to search/filter
When the filter criteria is entered
Then the user may filter the facility data by ORIS Code, Facility Name, or State

Given a user chooses to open a Facility->Configuration
When they select 'Open' for any Configuration
Then they are navigated to a separate tab 
And the user can see the Facility Name and Configuration at the top

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3718?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @JanellC @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP

**Comment by mosesdeeCVP** [comment]
Test Case: [TC759](https://epacamd.testquality.com/project/11428/plan/26040/test/375914)

**Comment by mosesdeeCVP** [comment]
Test Passed
