### ISSUE TITLE
Export Data: DataType Checkboxes & Reporting Period Filter

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3719]
## User Story 
As an ECMPS user, I want the ability to make selections so I can export data accordingly

## Acceptance Criteria:

Given a user is on the Export Data screen
When they select QA & Certifications and Emissions
Then the Year and Quarter options are available for selection

Given a user is on the Export Data screen
When they select only the Monitoring Plan
Then the Year, Quarter filters are disabled

Given I am on the Export Data screen
When the Year and Quarter filters are enabled
And I make a selection
Then the Reporting Period is automatically displayed
And
When I change my selection for the Year and Quarter
Then the Reporting Period gets updated automatically

Note: Preview option is only enable when the QA and Emissions checkboxes are selected

Given a user makes a selection on any Configuration
When they navigate away from the Configuration to another Configuration or module
Then the selections are retained

Invision Reference: https://projects.invisionapp.com/freehand/document/TdahPfbEb
Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/80542ddb-1370-41e9-9cc1-1206e2d497cc)

## Testing 
Test Case:[ TC761](https://epacamd.testquality.com/project/11428/plan/26040/test/375935)
Tester: @mosesdeeCVP

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3719?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @JanellC @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![3719 Export Data- DataType Checkboxes & Reporting Period Filter 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a0735bc9-162b-45d9-a23f-9382306dc689)

![3719 Export Data- DataType Checkboxes & Reporting Period Filter 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/be00cbdb-025e-4fda-b201-55ede873174f)

![3719 Export Data- DataType Checkboxes & Reporting Period Filter 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6ef5fc26-4c2e-46a0-8f42-3ae12ddddf66)
