### ISSUE TITLE
MDM Endpoint for Reporting Period

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3725]
Create MDM endpoint for Reporting Period

Only return data up to the Current Year and the Current Quarter
![image](https://user-images.githubusercontent.com/66504934/175112346-5ef4b5bf-b4c4-4916-9d8e-5cf43d772b62.png)

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3725?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @JanellC @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP

**Comment by mosesdeeCVP** [comment]
Test Case: [TC757](https://epacamd.testquality.com/project/11428/plan/26040/test/375347)
