### ISSUE TITLE
API Endpoint for Test Summary

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3727]
GET Endpoint for

Retrieve Test Summary from Global 
Retrieve Test Summary from WRKSPC

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1df6d80a-b3d2-457b-9a4c-8f3c3a87deb7)

**Comment by subrataroyCVP** [comment]
![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/d970e6ed-f234-4550-8d2d-108cbed4480b)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC772](https://epacamd.testquality.com/project/11428/plan/26040/test/376132)

**Comment by mosesdeeCVP** [comment]
Test Passed
