### ISSUE TITLE
EASEY Out Data Publishing User Research

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#374]
Compliance and Allowance Data User Research Study

**Comment by nsameerun** [comment]
12/15/2020 UX Weekly for Notes for AMPD 

https://usepa.sharepoint.com/:o:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/Datateers%20Notebook?d=webc3fb4dba1e45cbac7c095db55470fd&csf=1&web=1&e=bhZsbo

@areighar @tlageman-epa @kstetsyuk

**Comment by david-cvp** [comment]
See #391
