### ISSUE TITLE
Remove Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3741]
As an ECMPS user, I want the ability to remove Protocol Gas Data so that I can update Linearity Summary Data as needed

Acceptance Criteria:
Given I am in the Protocol Gas Data section
When I click on the 'Remove' option
Then I see that the relevant Protocol Gas Data record is deleted

Given I chose to remove Protocol Gas Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Linearity Summary data section
When I select Cancel
Then I am returned to the landing screen for the Linearity Summary Data

Invision Board:
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2bDZwZThtMDlobjNiN3BwczVhbXpmaw%3D%3D

## Testing 
Test Case: [TC839 ](https://epacamd.testquality.com/project/11428/plan/25475/test/383615)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
