### ISSUE TITLE
Add Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3742]
As an ECMPS user, I want the ability to create new Protocol Gas Data, so that I can add new data to the application

Acceptance Criteria:
Given the user clicks on 'Add' for Protocol Gas Data
When the user is on the 'Add Protocol Gas Data' modal
Then the system displays the fields applicable
And the user can enter new  Protocol Gas Data

Summary Type/Gas Level Code (Pre-populated/not editable)
Gas Type Code (dropdown)
Cylinder ID (Text)
Vendor ID (Text)
Expiration Date (Text+Date Picker)

Given the user added Protocol Gas Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Linearity Summary Data
And a new row for the Protocol Gas Data is added to the Linearity Summary Data section

Warning message to pop up when a user updates data and closes the modal without saving/clicks the back button/uses the bread crumb link
Warning message to read as a browser alert/browser pop-up alert: Closing this window will discard any unsaved changes

Dev Note: Make the Add button available with the section header even when there is no Protocol Gas Data available so user is able to add data

Note: The scope of this ticket includes Add Protocol Gas Data records under all 3 Summary Levels (High, Mid and Low)

Reference URL:
https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w2bDd4b3BoMGFvNjNiN3B5cG00MHI0dQ%3D%3D

## Testing 
Test Case: [TC841](https://epacamd.testquality.com/project/11428/plan/25475/test/383626)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
