### ISSUE TITLE
Global View: Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3746]
As an ECMPS user, I want to view Protocol Gas data so that I can look at real-time data.

Acceptance Criteria
Given a user has selected Linearity Summary from the Test Type group dropdown and a Protocol Gas data record is available 
When the Protocol Gas data is displayed 
Then the data is displayed as a separate table (see list below for columns and order)

Gas Level Code
Gas Type Code
Cylinder ID
Vendor ID
Expiration Date

Given a user is viewing Protocol Gas Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7dd8b132-a5ff-46db-8464-bc3503fbcdcc)

**Comment by NadiaJL** [comment]
ECMPS- QA Global-View: ‘View’ Linearity - Desktop large - 1024 V1.3
Xd Prototype: https://xd.adobe.com/view/40aa3540-d85f-4b68-9bf2-63f694bee243-15f9/screen/131433a5-8f5c-4d99-83ae-9cf7855a635d/

InVision board: https://projects.invisionapp.com/freehand/document/TdahPfbEb

**Comment by mosesdeeCVP** [comment]
![3746 Global View- Protocol Gas Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e9674114-a81a-43d0-a51a-c61e5f3eb4cb)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC856](https://epacamd.testquality.com/project/11428/plan/25475/test/384663)

**Comment by mosesdeeCVP** [comment]
Test Passed
