### ISSUE TITLE
Remove API Endpoint - Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3747]
Add API endpoint for Remove - Protocol Gas Data

DELETE endpoint url: /qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gas/{id}

Swagger Ref URL: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Protocol%20Gas

**Comment by mosesdeeCVP** [comment]
Test Case: [TC845](https://epacamd.testquality.com/project/11428/plan/26459/test/383872)

Test Passed
