### ISSUE TITLE
View API Endpoint - Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3748]
Add API Endpoint for Edit Protocol Gas Data (Scope includes both the Global view and the Workspace)

GET endpoint url: /qa-certification-mgmt/locations/{locId}/test-summary/{testSumId}/protocol-gases

For Testing Only:
Summary Type/Gas Level Code (Pre-populated/not editable)
Gas Level Code (dropdown)
Gas Type Code (dropdown)
Cylinder Identifier (Text)
Vendor Identifier (Text)
Expiration Date (Text+Date Picker)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC826](https://epacamd.testquality.com/project/11428/plan/26459/test/382321)

**Comment by mosesdeeCVP** [comment]
Test Passed
