### ISSUE TITLE
Edit API Endpoint - Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3749]
Create API endpoint for Edit - Protocol Gas Data 

PUT endpoint url: /qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gas/{id}

Swagger Ref URL: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Protocol%20Gas

For Testing Only:
Summary Type/Gas Level Code (Pre-populated/not editable)
Gas Level Code (dropdown)
Gas Type Code (dropdown)
Cylinder Identifier (Text)
Vendor Identifier (Text)
Expiration Date (Text+Date Picker)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC838](https://epacamd.testquality.com/project/11428/plan/26459/test/383614)

**Comment by mosesdeeCVP** [comment]
Test Passed
