### ISSUE TITLE
EASEY Out Sort/Filter UI Design

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#375]

**Comment by david-cvp** [comment]
@cvp-alexrobinson 
- Info Arch (create To Be)
- Validate IA with CVP and EPA
- Create wireframes
- Validate wireframes with CVP and EPA
- Validate wireframes with users
- Revise wireframes
- Create HF UI Design
- Update design library

**Comment by JanellC** [comment]
Epic completed. UI design will continued to be tracked in CAMPD Web Page Areas UI Design #1268
