### ISSUE TITLE
API Endpoints for Import Linearity - Test Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3752]
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4ecac42a-91e0-4741-8ea8-3f79702267a3)

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/3752?planning-poker) with ZenHub @addisgmichael @cw-cvp @fanwari1 @jeffreyaggrey @mosesdeeCVP @Qb10 @subrataroyCVP

**Comment by mosesdeeCVP** [comment]
Test Case: [TC774](https://epacamd.testquality.com/project/11428/plan/26040/test/376573)

**Comment by mosesdeeCVP** [comment]
Import is working
