### ISSUE TITLE
Export Functionality: Update Metadata Object 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3763]
Scope includes 

The purpose of this update is to change the descriptions of stackPipeId, testTypeCode, and testSummaryId

Stack Pipe ID: This is the alphanumeric code assigned by a source to identify a multiple or common stack or pipe at which emissions are determined 

- updating the metadata object 'easey-commons repo' to include property metadata
- Update the relevant excel document with the information
- Update description for parameters for the following endpoints:
/qa-certification-mgmt/export
/qa-certification-mgmt/workspace/export
/qa-certification-mgmt/locations/{locId}/test-summary
/qa-certification-mgmt/workspace/locations/{locId}/test-summary

Testing Notes: Review the update to the commons repo in the Export Swagger page

## Testing 
Test Case[: TC798](https://epacamd.testquality.com/project/11428/plan/26040/test/378333)
Tester: @JanellC

**Comment by JanellC** [comment]
TC798 passed
