### ISSUE TITLE
Testing Only: QA & Cert: Remove Import from the Global View

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3765]
Remove the 'Import Test Data' option from the Global-View
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a3aee69b-5755-4500-882d-446e2939e2cd)

**Comment by mosesdeeCVP** [comment]
![3765 QA & Cert- Remove Import from the Global View.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/709cf1aa-df84-4128-8ce5-f2b737431be0)

**Comment by mosesdeeCVP** [comment]
Changes Complete
