### ISSUE TITLE
Linearity Test Summary - Update Columns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3766]
## User Story 
As an ECMPS user, I want the Test Summary Data columns updated for the Test Type 'Linearity Summary Data' so that I only see data applicable to 'Linearity Summary'

## Acceptance Criteria:

Given a user selects 'Test Type - Linearity Summary' from the dropdown
When the Test Summary Data is displayed and is the first data table
Then I see the following data:

Unit or Stack Pipe ID
Component ID
Test Number
Test Reason Code
Test Result Code
End Date
End Hour
End Minute

## Testing 

Test Case: [TC781](https://epacamd.testquality.com/project/11428/plan/25475/test/377987)
Tester: @JanellC

**Comment by JanellC** [comment]
TC781 Passed 

**Global** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3a56e062-cb00-45ff-8f89-73831b4f133a)

**Workspace** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/aeb7ae06-a3ad-4f48-a171-0229fa86ec03)
