### ISSUE TITLE
QA Global-View: 'View' Linearity Test Summary Data 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3767]
As an ECMPS user, I want to view the details of Test Summary Data for the Test Type 'Linearity Summary Data' so that I can use it as reference 

Acceptance Criteria:

Given a user selects 'Test Type - Linearity Summary' from the dropdown
When the Test Summary Data is displayed 
And user clicks on 'View' next to it
Then the system opens a modal with the following information:

Unit or Stack Pipe ID
Test Type Code
Component ID
Span Scale Code
Test Number
Test Reason Code
Test Result Code
Begin Date
Begin Hour
Begin Minute
End Date
End Hour
End Minute
Grace Period Indicator
Test Comment

Dev Notes:
All the code tables are pulled from the Master Data Endpoints : 
https://api.epa.gov/easey/dev/master-data-mgmt/test-type-codes
https://api.epa.gov/easey/dev/master-data-mgmt/test-result-codes
https://api.epa.gov/easey/dev/master-data-mgmt/test-reason-codes

**Reference Screenshots included in the comments section**

Note: For the Global-view, it shall be a read-only version without the ability to edit or create
For the Workspace, the user shall have the ability to View and Edit Linearity Injection Data

## Testing 
Test Case: [TC782](https://epacamd.testquality.com/project/11428/plan/25475/test/378001)
Tester: @JanellC

**Comment by NadiaJL** [comment]
ECMPS- QA Global-View: ‘View’ Test Summary Data - Desktop large - 1024 V1.0 
Xd prototype: https://xd.adobe.com/view/40aa3540-d85f-4b68-9bf2-63f694bee243-15f9/


![QA Linearity - QA & Certification - QA-Cert test data - Location - Test type - Linearity - Test Summary Data - Desktop 1024 V2.1 – 2.png](https://images.zenhubusercontent.com/620142521e8674037a915879/9aac0ffc-b2cb-463a-9860-42a94b95748c)

![QA Linearity - QA & Certification - QA-Cert test data - Location - Test type - Linearity - Add Test Summary Data -  Desktop 1024 V2.1 – 2.png](https://images.zenhubusercontent.com/620142521e8674037a915879/65220e06-5f7d-4552-94ab-ae2bee257e12)

**Comment by JanellC** [comment]
TC782 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8f5396d8-8575-4035-8a19-1664a1e34de5)
