### ISSUE TITLE
QA & Cert: Test Summary & Linearity Data Validations (Result A Only)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3768]
The following are general Test Summary & Linearity checks that should be applied before creating, updating, or importing any and all QA Test Summary data.

[QA and Certification Data Linearity Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)
- [x] LINEAR-4 Identification of Previously Reported Test or Test Number for Linearity Check (Result A Only) 
        *** Result B and Result C blocked due to the unavailability of the column CAN_SUBMIT in the DB

Category: General Check

## Testing 

Test Case: [TC785](https://epacamd.testquality.com/project/11428/plan/26040/test/378005)
Tester: @mosesdeeCVP

**Comment by vishnunavuluri** [comment]
@JanellC Result B and Result C of this LINEAR-4 check will be implemented in a future ticket due to the unavailability of the column CAN_SUBMIT in the DB. Please verify Result A only for testing purposes

**Comment by mosesdeeCVP** [comment]
Test Passed
