### ISSUE TITLE
Review Architecture Diagram for Security SIA (Need By Last Week of July 7/25)

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3769]
- Review Diagram and edit for completeness/correctness for SIA 
- To be Reviewed by the last week of July 
[Link to File](https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Security%20Team/Security/Diagrams/EASEY%20-%20CAMPD%20Rel%201-1%20Diagram.drawio?isSPOFile=1)

**Comment by jwhitehead77** [comment]
@maheese I have reviewed the diagram and the only thing I see missing would be the Auth API where the token service is hosted. CAMPD uses that to get the client token for the camd services endpoints that are protected.

**Comment by maheese** [comment]
@jwhitehead77 Thanks!  I added the Auth API to the diagram.

**Comment by jwhitehead77** [comment]
I am good with this so closing
