### ISSUE TITLE
Bug: Fix Camel Casing in Bulk Data Files Response

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3770]
## Test Case
Test Case:
Tester: Maegan 
## Steps to Reproduce

1) Navigate to the Bulk Data Files API/ Bulk Data File JSON Response
2) Several of the value names are not in camel case format

### Actual Results
![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/810e6261-4d5a-4be8-9275-d49b1b626254)

## Requirements
- Fix the following response items: filename, datasubtype,datatype,description,quarter,s3path,statecode,

### User Story
As a CAMPD user, I want consistent rJSON responses for similar data types, so that I am able to keep track between data sets.
### Acceptance Criteria
Given a user is on the bulk data files page
When they download a JSON file
Then the download has the correct naming convention 

Notes: Bulk file generation process is generating the names. Change will require an update to the Quartz generation process. this ticket will need to be done before linked ticket.

**Comment by JorjaComer** [comment]
Moved from CAMPD backlog. See Notes above.
