### ISSUE TITLE
Create MDM Endpoints for Gas Level Code (Linearity Summary) 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3773]
Create MDM Endpoint for Linearity Summary Data for:

Gas Level Code

Reference:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6be96aba-e827-44df-861c-66bc63067b4d)

## Testing 

Test Case: [TC780](https://epacamd.testquality.com/project/11428/plan/26040/test/377986)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC780 passed 

https://api.epa.gov/easey/dev/master-data-mgmt/gas-type-codes?api_key=PXPWlQGB3wKXotkWN1PbSwbSoM7CoWW0ZMPWYtfc 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/953ccbc4-1239-4ecc-ab9c-1e9555e26fbf)
