### ISSUE TITLE
QA & Cert: 'Evaluate' and 'Evaluate All' options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3774]
As an ECMPS user I want the ability to evaluate one or more tests at once so that I can do my work efficiently

Acceptance Criteria:

Give I am on the QA Certification Test Data - Individual Configurations Tab
When I review all available buttons on the screen
Then I see 'Evaluate' and 'Evaluate All' options located as per the screenshot below

**Reference Screenshot (For location and Color of the button):**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e22344a3-70a0-4b5e-85d2-894fdf4e4167)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4f70c9bc-27bf-4186-889c-7ebc0baa530f)

## Testing 
Test Case: [TC796](https://epacamd.testquality.com/project/11428/plan/25475/test/378331)
Tester: @JanellC

**Comment by JanellC** [comment]
TC796 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1cf71a9b-8222-4ce6-9d58-0b400e89d96d)
