### ISSUE TITLE
Remove Test Summary Data (Linearity Summary)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3776]
As an ECMPS user, I want the ability to remove Test Summary data for Linearity Summary so that I can update QA Tests as needed

Acceptance Criteria:

Given I select the Linearity Summary Test Type
And am reviewing the Test Summary Data 
When I click on the 'Remove' option for Test Summary Data
Then I see that the relevant Test Summary data record is deleted

Given I chose to remove Test Summary Data for Linearity Summary
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
When I select Cancel
Then I am returned to the landing screen for the Linearity Summary section

Reference Screenshots:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4801fdf4-99f8-44d6-8b02-be2754fc99d1)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4abef193-b120-4526-b4c4-a5ba98cff148)

## Testing 
Test Case: [TC795](https://epacamd.testquality.com/project/11428/plan/25475/test/378330)
Tester: @JanellC

**Comment by JanellC** [comment]
TC795 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ea0e3f0b-7a56-45f2-add3-b89ba292d5b0)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/10615510-fd68-45ba-9700-0c0ff78d5937)
