### ISSUE TITLE
Design and Develop User Research Study

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#378]
- [x] Talk to product owner and team
- [x] Determine product owner research goals
- [x] Identify participant types
- [x] Identify and study instruments; wireframes, screen share, prototype
- [x] Develop a research plan

**Comment by nsameerun** [comment]
ECMPS PI2 UX Plan-EPA CAMD-v2.0

Presented: 11/23 at Weekly UX Emsissioners Meeting 

https://usepa.sharepoint.com/:p:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B403ECE13-93A2-4FA7-8B2C-C0710A7BD92D%7D&file=ECMPS%20PI2%20UX%20Plan-EPA%20CAMD-v2.0.pptx&action=edit&mobileredirect=true

**Comment by JorjaComer** [comment]
See attached plan for outcome
