### ISSUE TITLE
API: Update Test Summary filter parameter to allow multiple Test Type Codes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3782]
- Update Test Summary Controller GET endpoints to allow for multiple Test Type Codes by adding the following decorator...
`@ApiQuery({ style: 'pipeDelimited', name: 'TestTypeCode', required: false, explode: false, })`
![image](https://user-images.githubusercontent.com/66504934/179337255-aa3421f9-a9ba-4a99-a013-06e9951e1ad1.png)
- Update the Test Summary Params DTO Test Type Code property to be an array of strings and add the transform decorator
```
@ApiProperty({
    isArray: true,
    enum: TestTypeCodes,
    description: propertyMetadata.testTypeCode.description,
  })
  @IsValidCode(TestTypeCode, {
    message: 'Invalid Test Type Code',
  })
  @Transform(({ value }) => value.split('|').map((item: string) => item.trim()))
  testTypeCode?: string[];
```
- Update test-summary.querybuilder addTestTypeWhere function in utilities to allow for multiple values
`query.andWhere('ts.testTypeCode IN (:...testTypeCodes)', { testTypeCodes });`

## Testing 
Test Case: [TC809](https://epacamd.testquality.com/project/11428/plan/25475/test/380240)
Tester: @mosesdeeCVP

**Comment by JanellC** [comment]
This ticket does not have to completed as apart of sprint 9.2. The team will need to have additional conversation with the PO to uncover requirements. After discussing the requirements, this ticket can be bought into a future sprint. Need to estimate this ticket during backlog refinement on 7/13 after discussing with the PO. @vishnunavuluri

**Comment by mosesdeeCVP** [comment]
Test Passed
