### ISSUE TITLE
UI: Rename Test Type field and update options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3791]
As an ECMPS user, I want the Test Type (Test Type Group) Dropdown to be updated so that it includes additional options 

Acceptance Criteria:

Given I am on the individual configurations tab
When I review the fields available
Then I see a 'Test Type Group' dropdown (Rename Test Type to Test Type Group)

Given I am on the individual configurations tab
When I click on the Test Type Group dropdown
Then I see the following 2 options in addition to the existing ones

PEI 
Miscellaneous

**Full List should be:**
AppendixE Correlation Test Summary 
Calibration Injection 
Cycle Time Summary 
Flow to Load Check 
Flow to Load Reference 
Fuel Flow to Load 
Fuel Flow to Load Baseline 
Fuel Flowmeter Accuracy 
Hg Linearity and 3-level Summary 
Linearity Summary 
**Miscellaneous**
Offline Online Calibration 
**PEI**
RATA 
Test Qualification 
Transmitter Transducer Accuracy 
Unit Default

#### Development Notes:
The Test Type dropdown label should be changed to Test Type Group and display the descriptions of the Test Type Group Codes retrieved from the master data api endpoint https://api.epa.gov/easey/dev/master-data-mgmt/test-type-group-codes

## Testing 
Test Case: [TC810](https://epacamd.testquality.com/project/11428/plan/25475/test/380241)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![3791 UI- Rename Test Type field and update options.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a493ea46-0380-4df7-ad1f-75998c4f038a)
