### ISSUE TITLE
UI: Add Test Type Code column to Test Summary Data table

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3793]
As an ECMPS user, I want the Test Type Code information to be displayed in the Test Summary section for a Test Type so I can differentiate between Test Types when needed

Acceptance Criteria:

Given I am an ECMPS user on an individual Configuration tab
When I select a Test Type
And the Test Summary data is displayed for it
Then I see a Test Type Code column 

Reference Image:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/91ad5b34-ac2e-4616-9d54-5f414f0c6fad)

## Testing 
Test Case: [TC811](https://epacamd.testquality.com/project/11428/plan/25475/test/380242)
Tester @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![3793 UI- Add Test Type Code column to Test Summary Data table 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/496cade4-48fe-445b-bd2d-d681ef2de37f)

![3793 UI- Add Test Type Code column to Test Summary Data table 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/86194d0a-fc75-46de-84da-aca0d8508223)

**Comment by mosesdeeCVP** [comment]
Test Passed
