### ISSUE TITLE
UI: Update Test Summary Test Type Filter to pass multiple codes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3794]
Update the filtering at the Test Summary level to pass multiple Test Type Codes for Test Summary data

As an ECMPS user, I want the application to pass multiple Test Type Codes so that I can view test summary data for multiple Test Types based on the selected test type group

#### Acceptance Criteria:
Given I am an ECMPS user
When I select the option 'Hg Linearity and 3-Level Summary' from the Test Type Group dropdown
Then I see data displayed for the following Test Type Codes:
HGSI3
HGLINE

Given I am an ECMPS user
When I select the option 'Miscellaneous' from the Test Type Group dropdown
Then I see data displayed for the following Test Type Codes:
DAHS 
DGFMCAL 
MFMCAL 
TSCAL 
BCAL 
QGA 
LEAK 
OTHER 
PEMSAC

#### Development Notes:
- The Test Type dropdown label should be changed to Test Type Group and display the descriptions of the Test Type Group Codes retrieved from the master data api endpoint https://api.epa.gov/easey/dev/master-data-mgmt/test-type-group-codes
- When a selection is made from the Test Type Group dropdown use the group code to filter the list of Test Type codes retrieved from the master data api endpoint https://api.epa.gov/easey/dev/master-data-mgmt/test-type-codes
- Pass a pipe delimited list of Test Type codes as a filter parameter when retrieving test summary data from https://api.epa.gov/easey/dev/qa-certificaiton-mgmt/locations/{locId}/test-summary

## Testing 
Test Case: [TC812 ](https://epacamd.testquality.com/project/11428/plan/25475/test/380250)
Tester @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
