### ISSUE TITLE
Recruit Participants

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#380]

**Comment by nsameerun** [comment]
Recruit in process. Scheduling to be complete in 2.2
Contacted Caiti from MB on 11/23 to confirm her availability to recruit. 
11/23 Sent introductory email to Chris and Caiti to initiate participant recruit. 
No participant screener needed. 
Warm intro from Chris to a few participants (TBD). 
Caiti to schedule (TBD).

**Comment by JorjaComer** [comment]
moved to 2.2
