### ISSUE TITLE
Add Test Summary Data (Linearity Summary)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3822]
As an ECMPS user (logged-in), I want to add Test Summary Data for Linearity Summary so that I can add a new test

Scope: Functionality only and UI updates shall be covered in a separate ticket

Acceptance Criteria:

Given the user has selected Linearity Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Test Data
Then the system displays a modal
and the user can add new data for:

Test Type Code (Dropdown)
Unit or Stack Pipe ID (Text)
Component ID (Text)
Span Scale Code (Dropdown)
Test Number (Text)
Test Reason Code (Dropdown)
Test Result Code (Dropdown)
Begin Date (Date Picker and Text)
Begin Hour (Dropdown 0-23)
Begin Minute (Dropdown 0-59)
End Date (Date Picker and Text)
End Hour (Dropdown 0-23)
End Minute (Dropdown 0-59)
Grace Period Indicator (Radio-button)
Test Comment (Text)

Refer to page 30: https://ecmps.camdsupport.com/documents/ECMPS%20QA%20Reporting%20Instructions%202022%20Q2.pdf

Given the user has added Test Summary Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Test Summary table on the Configurations tab
And the updates are reflected in the Test Summary section

Given the user has added new 'Test Summary Data' (Linearity Summary)
When the user chooses to Cancel
Then the user is returned to the Test Summary table on the Configurations tab
And no updates are saved

Dev Notes:
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Test%20Summary/TestSummaryWorkspaceController_createTestSummary
All the code tables are pulled from the Master Data Endpoints :
https://api.epa.gov/easey/dev/master-data-mgmt/test-type-codes
https://api.epa.gov/easey/dev/master-data-mgmt/test-result-codes
https://api.epa.gov/easey/dev/master-data-mgmt/test-reason-codes

Reference Images:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/58546f82-6778-448b-8de6-2c08079e8e8d)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/45b6f8e6-6b61-46b6-9b08-ed9ac03755e6)

## Testing 
Test Case: [TC815](https://epacamd.testquality.com/project/11428/plan/22772/test/380783)
Tester: @mosesdeeCVP

**Comment by NadiaJL** [comment]
Xd Prototype: https://xd.adobe.com/view/b1185d82-f64f-40f8-a670-28b7b07dfcb5-e44b/screen/ecccdfd2-69d0-41ae-a798-e874ae7d7507/

**Comment by vishnunavuluri** [comment]
Testing Notes (7/29/2022):
- New Requirement: Add functionality for Test Data should be available at all times so user is able to add Test Data from scratch for a Location
- Remove 'Test Summary Section' Header as this conflicts with 'Test Data' header 
- Unit/Stack Pipe ID can be added when adding new Test Summary Data?
- Dropdown restriction for Test Type Code

**Comment by NadiaJL** [comment]
ECMPS-QA Linearity - Workspace - Evaluate -  Import - Desktop large - 1024 V3.3
Xd Prototype: https://xd.adobe.com/view/b00f424e-f5f1-4d4e-ae7f-c962310e17c4-e55c/screen/ecccdfd2-69d0-41ae-a798-e874ae7d7507

InVision: ECMPS-QA Linearity - Workspace - Import - Desktop large - 1024 V3.2 - Updated 8/01/22
https://projects.invisionapp.com/freehand/document/TdahPfbEb![ECMPS-QA Linearity - Workspace - Evaluate -  Import - Add Test Data - Desktop large - 1024 V3.3.png
![ECMPS-QA Linearity - Workspace - Evaluate -  Import - Add Test Data - Desktop large - 1024 V3 3](https://user-images.githubusercontent.com/98968911/182188753-0e38f0e9-02b1-4701-9718-5d882cb948dd.png)
](https://images.zenhubusercontent.com/620142521e8674037a915879/b3c9bfb8-ec1f-42c4-826e-6179e882bb45)

**Comment by mosesdeeCVP** [comment]
![3822 Add Test Summary Data (Linearity Summary) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bbe38829-7a0e-4866-94e9-be93f1935c8a)

**Comment by NadiaJL** [comment]
@mosesdeeCVP I accidentally deleted your comment! Sorry about that, I was trying to delete my own comment.

**Comment by mosesdeeCVP** [comment]
@NadiaJL No Worries

**Comment by mosesdeeCVP** [comment]
![3822 Add Test Summary Data (Linearity Summary) - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1d6b0501-9a56-4cd8-8dcb-063d97e79a2f)

**Comment by mosesdeeCVP** [comment]
Test Passed
