### ISSUE TITLE
Create MDM Endpoint for Gas Level Code

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3823]
Create MDM Endpoint for Gas Level Code

Testing Reference:
Values: HIGH, MID, or LOW

## Testing 
Test Case: [TC817](https://epacamd.testquality.com/project/11428/plan/22772/test/380789)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![3823 Create MDM Endpoint for Gas Level Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/753f5d2e-767b-4f4a-b377-f261b3083d5e)
