### ISSUE TITLE
Add Spinner to Revert to Official Record Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3827]
When reverting a MP back to the official copy it can take upwards of 20 to 30 seconds or more to complete (now that QA and Emission updates would be available). So the spinner needs to be engaged until the operation is complete

User Story:
As an ECMPS user, I want a spinner to be displayed when the Revert to Official Record action is in progress so that I know the updates are being reverted

Acceptance Criteria:

Given I am an ECMPS user
When I click Revert to Official Record
Then I see a spinner when the action is in progress

Note: Do we want to display a message informing the user that the action would take time to be completed?

## Testing
Test Case: [TC814 ](https://epacamd.testquality.com/project/11428/plan/22772/test/380782)
Tester: @JanellC

**Comment by JanellC** [comment]
TC814 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e6deb56e-e9af-4f3d-ac27-2ab708f1fe91)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7b8f3d72-4a85-46f4-b7b1-2a9a9ae9340a)
