### ISSUE TITLE
Prepare high-level executive summary

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#383]

**Comment by david-cvp** [comment]
@staceyrenner @MoAdeyoju @karenhwwoo 

User research executive summary can be found here:
https://teams.microsoft.com/l/file/8814D7A9-E4ED-4598-B2D9-A4088ED0851E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pptx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FUser%20Research%2FUser%20Research%2FEASEY-In%20User%20Research%20Reports%2FECMPS%20MP%20View%20Edit%20UXR%20Study%20.pptx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:2fb3e3c4e2b84887b99e84c907bf4ff4@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23

**Comment by nsameerun** [comment]
https://teams.microsoft.com/_#/files/UX?threadId=19%3A2fb3e3c4e2b84887b99e84c907bf4ff4%40thread.skype&ctx=channel&context=EASEY-Out%2520User%2520Research%2520Reports&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FUser%2520Research%252FUser%2520Research%252FEASEY-Out%2520User%2520Research%2520Reports
