### ISSUE TITLE
API: Create MDM endpoint for Test Type Group Codes

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#3832]
Return data from camdecmpsmd.test_type_group_code table
endpoint url: https://api.epa.gov/easey/dev/master-data-mgmt/test-type-group-codes

Test Type Group Codes
![image](https://user-images.githubusercontent.com/66504934/179338024-32822f8e-ff42-4c24-b6a0-0b79eddc4666.png)

## Testing 
Test Case:[ TC805](https://epacamd.testquality.com/project/11428/plan/25475/test/380211)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
