### ISSUE TITLE
API: Update MDM endpoint for Test Type Codes to include Test Type Group Code

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#3834]
Update test-type-codes endpoint to include group code property
endpoint url: https://api.epa.gov/easey/dev/master-data-mgmt/test-type-codes

Test Type Group Codes
![image](https://user-images.githubusercontent.com/66504934/179338024-32822f8e-ff42-4c24-b6a0-0b79eddc4666.png)

Test Type Codes
![image](https://user-images.githubusercontent.com/66504934/179338043-cb226243-f60b-4279-8412-c77e4a5eea35.png)
![image](https://user-images.githubusercontent.com/66504934/179338060-7d07107e-ada9-490f-a055-f07abf27110e.png)

## Testing 
Test Case: [TC808](https://epacamd.testquality.com/project/11428/plan/25475/test/380214)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
