### ISSUE TITLE
QA & Cert: Test Summary & Linearity Data Validations LINEAR-4 (Result B & C )

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3843]
The following are general Test Summary & Linearity checks that should be applied before creating, updating, or importing any and all QA Test Summary data.

[QA and Certification Data Linearity Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)
- [x] LINEAR-4 Identification of Previously Reported Test or Test Number for Linearity Check (Result A Only) 
        *** Result B and Result C blocked due to the unavailability of the column CAN_SUBMIT in the DB

UPDATE:
- When the check spec says "Locate an unassociated QASupp record..." that means look for another record in the qa_supp_data table with the same conditions but a different test_sum_id
- If CAN_SUBMIT in the QA Supp record is equal to "N"
```
when
   QA_SUPP_DATA.SUBMISSION_AVAILABILITY_CD IS NULL or 
   QA_SUPP_DATA.SUBMISSION_AVAILABILITY_CD in ('GRANTED', 'REQUIRE')
then 'Y'
else 'N'
```

Category: General Check

**Comment by mosesdeeCVP** [comment]
Test Case: [TC911](https://epacamd.testquality.com/project/11428/plan/25475/test/391778)

Test Passed
