### ISSUE TITLE
Remove Test Summary Data Label (Individual Configurations Screen)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3844]
As an ECMPS user I want the Test Summary Data label in the Configurations screen removed so that it doesn't confuse the users

Acceptance Criteria:
Given I am an ECMPS user reviewing Test Data in the individual Configurations tab
When I see the Test Data section
Then I see that the label Test Summary Data has been removed

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/843b64cc-e0d7-41d4-8fec-69f1fb897724)

**Comment by jordanfontainecvp** [comment]
![Uploading Test Summary Label Remove.png…]()

**Comment by jordanfontainecvp** [comment]
![Test Summary Label Remove](https://user-images.githubusercontent.com/112484102/213266163-1fd3e7a5-8b1f-4427-b934-0fbdfc109af2.png)

**Comment by mosesdeeCVP** [comment]
Test Summary Data Removed

**Comment by mosesdeeCVP** [comment]
Test Sum Removed Logged Out
![Test Sum Removed Logged Out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/214073c3-623a-4872-b185-0846a675cd3e)

**Comment by mosesdeeCVP** [comment]
Test Sum Removed Logged Out
![Test Sum Removed.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a5dbb5a8-01ed-4add-bde9-3a7487d53797)
