### ISSUE TITLE
Test Only: QA & Cert: Test Summary & Linearity Data Validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3845]
The following are general Test Summary & Linearity checks that should be applied before creating, updating, or importing any and all QA Test Summary data.

General Test Checks

 TEST-8 Test Span Scale Valid
 TEST-23 Injection Protocol Valid

## Testing 

Test Case: [TC791](https://epacamd.testquality.com/project/11428/plan/26040/test/378011)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

The criteria states that Result B response should be: "You did not identify an injection protocol (HGE or HGO), as required for a Hg CEMS Critical Error Level 1
seven day calibration or cycle time test."

Instead we are getting a DTO response: "You reported an invalid Injection Protocol Code of [A] in Test Summary record for Unit/Stack [51], Test Type Code [LINE], and Test Number [A05-Q3-2011-5]"

The end result is a validation asking user to check the entered data. If further changes are needed to the wording of the error message a new ticket will be created

**Comment by mosesdeeCVP** [comment]
Original Ticket: [QA & Cert: Test Summary & Linearity Data Validations #3715](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/3715)
