### ISSUE TITLE
Design and develop Compliance and Allowance Data user research study

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#385]
- [ ] Talk to product owner and team
- [ ] Determine product owner research goals
- [ ] Identify participant types
- [ ] Identify and study instruments; wireframes, screen share, prototype
- [ ] Develop a research plan

**Comment by areighar** [comment]
Ongoing in Sprint 2.2

**Comment by nsameerun** [comment]
Compliance and Allowance Data User Study
