### ISSUE TITLE
API Endpoint - Add 'Air Emissions Testing' Data (RATA)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3859]
Add an API Endpoint to create/add Air Emissions Testing Data

Testing Reference Only:
QI Last Name (Text)
QI First Name (Text)
QI Middle Initial (Text)
AETB Name (Text)
AETB Phone Number (Text)
AETB Email (Text)
Exam Date (Text/Date Picker)
Provider Name (Text)
Provider Email (Text)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC934](https://epacamd.testquality.com/project/11428/plan/27146/test/393270)

**Comment by mosesdeeCVP** [comment]
Test Passed
