### ISSUE TITLE
Develop moderator's guide

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#386]
- [ ] Become familiar with the study instruments (if applicable)

**Comment by areighar** [comment]
Draft beginning to move through review as of 12/220 (Sprint 2.2)

**Comment by nsameerun** [comment]
Compliance and Allowance Data User Study

**Comment by nsameerun** [comment]
12/15/2020
**UX Weekly Meeting.** 

- CVP (Nakia) will finalize EPA's initial draft of the moderator's guide. Due by 12/22

- EPA (Andrew) will be the primary moderator for interviews.

**Comment by nsameerun** [comment]
@areighar @tlageman-epa  @kstetsyuk 

Hey Team! Wanted to see if you guys will receive this notification. This ticket moved from (In Development to Peer Review) during our UX Weekly Meeting today, for Ming and Jeremery's final approval of the Moderator's Guide. Please comment, once you receive this message. Also, please link the updated moderator's guide in your comment. Thank you much and Happy Holidays!

**Comment by tlageman-epa** [comment]
Yes, received the notification. I'll let Andrew link the guide. Thanks Nakia!

**Comment by areighar** [comment]
Got the notification :) And I just submitted it for approval and gave a deadline of COB Dec 30th to have approval/comments back. Will post final version here. Thanks!

**Comment by nsameerun** [comment]
[https://app.zenhub.com/files/287570343/6a009e0b-1b1d-4af3-aeb0-a62727a2d144/download](https://app.zenhub.com/files/287570343/6a009e0b-1b1d-4af3-aeb0-a62727a2d144/download)


MS Teams Update: Approved Peer Review of the Moderator's Guide from Ming. Awaiting Jeremy's Peer Review. Jeremey will be back in the office on January 4, 2020. 

@areighar @tlageman-epa @kstetsyuk

**Comment by nsameerun** [comment]
@areighar @kstetsyuk @tlageman-epa 

The most recent version of the moderator's guide. Ming and Jeremy's peer review received.  

[https://app.zenhub.com/files/287570343/155bc66e-db7e-4a4f-aed2-041d2045f98f/download](https://app.zenhub.com/files/287570343/155bc66e-db7e-4a4f-aed2-041d2045f98f/download)

**Comment by nsameerun** [comment]
@areighar @tlageman-epa @kstetsyuk 

Moderator's Guide Peer Review finalized during UX Weekly Meeting 01/05/2021. 

Ticket closed 01/05/2021
