### ISSUE TITLE
API: Export Summary Value Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3866]
As the ECMPS application, I need to be able to successfully export Summary Value Data from the emissions module in order to support program goals

Given the export endpoint in both emission modules have been updated when summary value data is exported  then the data is within the year and quarter range the user provides

*Note: In order to test you need to look at the database to check if the reporting ID is within the year and quarter specified. This requires collaboration with the developers.

- [ ]  Add Summary Value data to the existing export endpoint in the emissions module
- [ ]  Implement logic to export Summary Value Data

- [ ] Applicable reporting IDs to test this ticket will be attached

**Comment by fanwari1** [comment]
To Test:
Export using the workspace export endpoint
Export using the non workspace endpoint. You cannot use swagger for this endpoint and have to use postman or a similar tool.

**Comment by AmandaMNelson** [comment]
Structure of data:

  id: string;
  reportingPeriodId: number;
  monitoringLocationId: string;
  calcCurrentRptPeriodTotal?: number;
  calcOsTotal?: number;
  calcYearTotal?: number;
  userId?: string;
  addDate?: Date;
  updateDate?: Date;
  stackPipeId?: string;
  unitId?: string;
  parameterCode: string;
  currentReportingPeriodTotal?: number;
  ozoneSeasonToDateTotal?: number;
  yearToDateTotal?: number;
