### ISSUE TITLE
API: Export Daily Emissions Data and Daily Fuel Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3867]
As the ECMPS application, I need to be able to successfully export Emissions Data and Daily Fuel Data from the emissions module in order to support program goals

Given the export endpoint in both emissions modules have been updated when Emissions Data and Daily Fuel Data is exported then the begin_date of the data is within the year and quarter range the user provides

For every emissions record, there can be 0 or more daily emissions records and for each daily emission, there can be 0 or more daily fuel records

 Add Daily Emissions Data to the existing export endpoint in the emissions module
 This will also include  Daily Fuel Data to the existing export endpoint in the emissions module controller
 Implement logic to export Daily Emissions Data and Daily Fuel Data

**Comment by eglove** [comment]
Adds dailyEmissionData and dailyFuelData to JSON under:

Root -> dailyEmissionData -> dailyFuelData

The data sould take this shape:

```
{
  "dailyEmissionData": [
    {
      "id": string
      "reportingPeriodId": number
      "monitoringLocationId": string
      "parameterCode": string
      "date": date
      "totalDailyEmissions": number or null,
      "adjustedDailyEmissions": number or null,
      "sorbentRelatedMassEmissions": number or null,
      "userId": string or null
      "addDate": date or null
      "updateDate": date or null
      "unadjustedDailyEmissions": number or null,
      "totalCarbonBurned": number or null,
      "calcTotalDailyEmissions": number or null,
      "calcTotalOpTime": number or null,
      "dailyFuelData": [
        {
          "id": string
          "reportingPeriodId": number
          "monitoringLocationId": string
          "dailyEmissionId": string
          "fuelCode": string
          "dailyFuelFeed": number or null
          "carbonContentUsed": number or null
          "fuelCarbonBurned": number or null
          "calcFuelCarbonBurned": number or null
          "userId": string
          "addDate": date
          "updateDate": date or null
        }
      ]
    }
  ]
}
```

**Comment by eglove** [comment]
Sample data for non-workspace endpoint. There is no export data available for workspace. but they share the same logic.

monitor plan id, quarter, year:

MDC-5FD7CFF6F24F4B42923F8C757C9360A5,1,2019
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,1,2020
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,1,2021
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,1,2022
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,2,2019
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,2,2020
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,2,2021
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,3,2019
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,3,2020
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,3,2021
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,4,2019
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,4,2020
MDC-5FD7CFF6F24F4B42923F8C757C9360A5,4,2021

SQL used to find test data:

```
select distinct monitorPlan.mon_plan_id,
                reportingPeriod.quarter,
                reportingPeriod.calendar_year
from camdecmps.daily_fuel as dailyFuel
         left join camdecmps.daily_emission as dailyEmission
                   on dailyFuel.daily_emission_id = dailyEmission.daily_emission_id
         left join camdecmps.monitor_location as monitorLocation
                   on dailyEmission.mon_loc_id = monitorLocation.mon_loc_id
         left join camdecmps.monitor_plan_location as monitorPlanLocation
                   on monitorLocation.mon_loc_id = monitorPlanLocation.mon_loc_id
         left join camdecmps.monitor_plan as monitorPlan on monitorPlan.mon_plan_id = monitorPlanLocation.mon_plan_id
         join camd.plant as plant on monitorPlan.fac_id = plant.fac_id
         left join camdecmps.emission_evaluation as emissionEvaluation
                   on monitorPlan.mon_plan_id = emissionEvaluation.mon_plan_id
         join camdecmpsmd.reporting_period as reportingPeriod
              on dailyEmission.rpt_period_id = reportingPeriod.rpt_period_id;
```
