### ISSUE TITLE
API: Import Sorbent Trap Data and Sampling Train Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3871]
As the ECMPS application, I need to be able to successfully import Sorbent Trap Data to the emissions module in order to support program goals

Given there is an import endpoint in the workspace emissions module controller when a file is imported then all Sorbent Trap Data records are added from the imported file

- [ ]  Add Sampling Train data to the existing import endpoint in the emissions module

- [ ] Add Sorbent Trap (Parent Level Data) to the existing import endpoint in the emissions module

- [ ]  Implement logic to import Sorbent Trap and Sampling Train Data

- [ ]  Applicable property names for import Sorbent Trap and Sampling Train Data added to this ticket

**Comment by eglove** [comment]
Tested with:

```
{
    "orisCode": 302,
    "year": 2017,
    "quarter": 2,
    "sorbentTrapData": [
        {
            "stackPipeId": "CS0001",
            "beginDate": "2017-04-20T18:56:58.075Z",
            "beginHour": 2,
            "endDate": "2017-04-20T18:56:58.075Z",
            "endHour": 2,
            "monitoringSystemId": "105",
            "pariedTrapAgreement": 0,
            "absoluteDifferenceIndicator": 0,
            "rataIndicator": 1,
            "samplingTrainData": [
                {
                    "componentId": "009",
                    "sorbentTrapSn": "anything"
                }
            ]
        }
    ]
}
```
