### ISSUE TITLE
Refactor Open Configurations/tabs Across Modules (Global-view & Workspace)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3887]
As an ECMPS user, I want to retain any configurations I open across modules so I can access them from anywhere

Scope:
- Retain the selections for any open Configuration tabs across the modules/options available in the left-hand menu (MP, QA, Emissions, Export etc.)
- Retain the selections made for any dropdowns (Locations, Sections, Test Type Group etc.)

Notes:
- User shall stay in the same Configuration/tab when navigating between different modules/functionality
- When user is navigating between modules/functionality, then the user shall remain on the same tab but the options/data applicable for the selected module shall be updated

**Comment by mosesdeeCVP** [comment]
Works as expected.

**Comment by JanellC** [comment]
This ticket is ready for testing and can be located in MP/ QA 508 Testing- PI 10 #4150 epic @aprematta
