### ISSUE TITLE
Analyze research findings

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#389]
Verbal debrief of initial impressions/findings after all user interviews conclude.

**Comment by nsameerun** [comment]
UX Weekly Meeting Notes: Tuesday, December 15, 2020

Verbal debrief of initial impressions/findings after all user interviews conclude. 

Date of Debrief: Tuesday, January 12, 2020, during UX Weekly Meeting . 
The meeting notes from the debrief are located [here](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28UX%20Meeting%20Notes.one%7C39f26e63-355a-434e-ac77-d9a3f3d8130a%2F1%5C%2F12%5C%2F2021%20UX%20Weekly%20for%20AMPD%7C842bd5ff-d56e-4fe2-87d8-1d2c786710d5%2F%29&wdorigin=703) 

@areighar @tlageman-epa  @kstetsyuk
