### ISSUE TITLE
Global View: View RATA Test Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3909]
As an ECMPS user, I want to view the details of Test Summary Data for RATA so that I can use it as a reference

Acceptance Criteria:
Given a user has selected Relative Accuracy from the Test Type Group dropdown
When the Test Summary Data is displayed
And user clicks on 'View' next to it
Then the system opens a modal with the following information:

Test Type Code (RATA by Default)
Unit or Stack Pipe ID 
Monitoring System ID 
Test Number
Test Reason Code 
Test Result Code 
Begin Date 
Begin Hour
Begin Minute
End Date
End Hour 
End Minute
Grace Period Indicator 
Test Comment

Note: For the Global-view, it shall be a read-only version without the ability to edit or create

Invision Reference:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2MnEwdWJ2MDAwNDNiNnk1MXMydDlpMQ%3D%3D
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7f344ab5-7440-48c0-8220-b4408ffb6c38)

## Testing 
Test Case: [TC842](https://epacamd.testquality.com/project/11428/plan/26541/test/383632)
Tester: @mosesdeeCVP

**Comment by NadiaJL** [comment]
ECMPS- QA Global-View: ‘View’ - RATA- Test Summary Data - Desktop large - 1024 V1.0 
inVision Board: https://projects.invisionapp.com/freehand/document/SrHrFhGQ3

**Comment by mosesdeeCVP** [comment]
![3909 - Global View- View RATA Test Summary Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/33c40a41-da91-4d85-b0f5-675ce5c75846)

**Comment by mosesdeeCVP** [comment]
Test Passed
