### ISSUE TITLE
Prepare final user research study report

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#391]
Quick-Study Report consisting of initial workflow findings and raw UX researcher notes

**Comment by nsameerun** [comment]
UX Weekly Meeting Notes: Tuesday, December 15, 2020

(Nakia and Stacey) Final Research Deliverable will consist of Raw Notes and Initial Insights. Initial Insights consist of the user's selections/choices/actions as they work through the tasks. 

Due Date: January 19, 2020 (Contingent on the final date/time user interviews conclude) 

@areighar @tlageman-epa  @kstetsyuk

**Comment by nsameerun** [comment]
Allowance and Compliance Quick-Turn Study Report delivered to EPA on Tuesday, January 19, 2020. 
Meeting Notes from high-level debrief was added to the report. 

Link to report on the MS Teams below: 
<iframe src="https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ac69adee-7522-4dbf-95e0-fcc49db6634c}&amp;action=embedview" width="476px" height="288px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> document, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>

@areighar @kstetsyuk @tlageman-epa Ticket Closed
