### ISSUE TITLE
Test Only: Add RATA Test Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3911]
As an ECMPS user (logged-in), I want to add Test Summary Data for RATA so that I can add a new test

Acceptance Criteria:
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Test Data
Then the system displays a modal
and the user can add new data for:

Test Type Code (Limit to RATA)
Unit or Stack Pipe ID (Text)
Monitoring System ID (Text)
Test Number (Text)
Test Reason Code (Dropdown)
Test Result Code (Dropdown)
Begin Date (Date Picker and Text)
Begin Hour (Dropdown 0-23)
Begin Minute (Dropdown 0-59)
End Date (Date Picker and Text)
End Hour (Dropdown 0-23)
End Minute (Dropdown 0-59)
Grace Period Indicator (Radiobutton Yes/No)
Test Comment (Text)

Refer to page 53: https://ecmps.camdsupport.com/documents/ECMPS%20QA%20Reporting%20Instructions%202021%20Q4.pdf

Given the user has added Test Summary Data
When the user chooses to save and close
Then the data is saved 
And the modal closes
And the user is returned to the Test Summary table on the Configurations tab
And the updates are reflected in the Test Summary section

Given the user has added new 'Test Summary Data' (RATA)
When the user chooses to Cancel
Then the user is returned to the Test Summary table on the Configurations tab
And no updates are saved

Reference Images:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1bXBuM3NkMDAwODNiNnlsa25sMnRmbA%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1bXBuM3M4MDAwNDNiNnl4cmZzZm03ZA%3D%3D

## Testing 
Test Case: [TC844](https://epacamd.testquality.com/project/11428/plan/26541/test/383634)
Tester:  @JanellC

**Comment by vishnunavuluri** [comment]
@addisgmichael @cw-cvp @mosesdeeCVP https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/3-Business%20Analysis/Test%20Data%20By%20Test%20Type%20Group.xlsx?d=waf4ed2ec4fca4b9aa5fc98b066be240a&csf=1&web=1&e=HGpvFY

**Comment by JanellC** [comment]
TC844 passed
