### ISSUE TITLE
Remove RATA Test Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3912]
As an ECMPs user, I want the ability to remove RATA Test Summary data so that I can delete a test when needed

Acceptance Criteria:

Given I am in the RATA - Test Summary Data section
When I click on the 'Remove' option
Then I see that the relevant RATA Test Summary data record is deleted
And the Test Summary Data is updated accordingly

Given I chose to remove RATA Test Summary Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
When I select Cancel
Then I am returned to the landing screen for RATA data

Invision Board Reference:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w1bXBuM3NiMDAwNzNiNnk1aWtyNHA1eQ%3D%3D

## Testing 
Test Case: [TC832](https://epacamd.testquality.com/project/11428/plan/26541/test/383573)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
