### ISSUE TITLE
API: Export Sorbent Trap and Sampling Train Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3914]
As the ECMPS application, I need to be able to successfully export Sorbent Trap Data from the emissions module in order to support program goals

Given the export endpoint in both emission modules have been updated when sorbent trap data is exported then the begin_date of the data is within the year and quarter range the user provides

Sorbent Trap id of the sampling train record matches the ID of the sorbent trap record. Each emission evaluation record can have 0 or more sorbent trap records. Each sorbent trap record should have 0 or more sampling train records 

- [ ]  Add SorbentTrap data to the existing export endpoint in the emissions module
- [ ]  This will also include sampling train data to the existing export endpoint in the emissions module controller
- [ ]  Implement logic to export sampling train data and sorbent trap data

**Comment by eglove** [comment]
Adds sorbentTrapData and samplingTrainData to JSON under:

Root -> sorbentTrapData -> samplingTrainData

The data should take this shape:

```
{
  "id": string,
  "monitoringLocationId": string,
  "reportingPeriodId": number,
  "beginDate": date,
  "beginHour": number,
  "endDate": date,
  "endHour": number,
  "monitoringSystemId": string,
  "pairedTrapAgreement": number or null,
  "absoluteDifferenceIndicator": number or null,
  "modcCode": string or null,
  "hgSystemConcentration": string or null,
  "calcPairedTrapAgreement": number or null,
  "calcModcCode": string or null,
  "calcHgConcentration": string or null,
  "userId": string or null,
  "addDate": date or null,
  "updateDate": date or null,
  "apsCode": string or null,
  "rataIndicator": number or null,
  "samplingTrainData": [
    {
      "id": string,
      "sorbentTrapId": string,
      "monitoringLocationId": string,
      "reportingPeriodId": number,
      "componentId": string or null,
      "sorbentTrapSn": string,
      "mainTrapHg": string or null,
      "btTrapHg": string or null,
      "spikeTrapHg": string or null,
      "spikeReferenceValue": string or null,
      "totalSampleVolumeDscm": number or null,
      "referenceSfsrRatio": number or null,
      "hgConcentration": string or null,
      "percentBreakthrough": number or null,
      "percentSpikeRecovery": number or null,
      "samplingRatioCheckResultCode": string or null,
      "postLeakCheckResultCode": string or null,
      "trainQaStatusCode": string or null,
      "sampleDamageExplanation": string or null,
      "calcHgConcentration": string or null,
      "calcPercentBreakthrough": number or null,
      "calcPercentSpikeRecovery": number or null,
      "userId": string or null,
      "addDate": date or null,
      "updateDate": date or null
    }
  ]
}
```

**Comment by eglove** [comment]
Sample data for non-workspace endpoint. Workspace and non-workspace endpoints for export share the same logic, tested with non-workspace due to data availability.

monitor plan id, quarter, year:

MDC-CA078A374DB04014AEB50EC406C538EA,2020,1
MDC-CA078A374DB04014AEB50EC406C538EA,2021,4
MDC-CA078A374DB04014AEB50EC406C538EA,2021,2
MDC-CA078A374DB04014AEB50EC406C538EA,2020,4
MDC-CA078A374DB04014AEB50EC406C538EA,2019,2
MDC-CA078A374DB04014AEB50EC406C538EA,2022,1
MDC-CA078A374DB04014AEB50EC406C538EA,2020,2
MDC-CA078A374DB04014AEB50EC406C538EA,2021,3
MDC-CA078A374DB04014AEB50EC406C538EA,2020,3
MDC-CA078A374DB04014AEB50EC406C538EA,2021,1

SQL used to find test data:

```
select distinct emission_evaluation.mon_plan_id, reportingPeriod.calendar_year, reportingPeriod.quarter
from camdecmps.sampling_train as samplingTrain
    left join camdecmps.sorbent_trap as sorbentTrap on samplingTrain.trap_id = sorbentTrap.trap_id
    left join camdecmps.monitor_location as monitorLocation on samplingTrain.mon_loc_id = monitorLocation.mon_loc_id
    left join camdecmps.monitor_plan_location as monitorPlanLocation on monitorLocation.mon_loc_id = monitorPlanLocation.mon_loc_id
    left join camdecmps.monitor_plan as monitorPlan on monitorPlan.mon_plan_id = monitorPlanLocation.mon_plan_id
    join camd.plant as plant on monitorPlan.fac_id = plant.fac_id
    left join camdecmps.emission_evaluation on monitorPlan.mon_plan_id = emission_evaluation.mon_plan_id
    join camdecmpsmd.reporting_period as reportingPeriod on emission_evaluation.rpt_period_id = reportingPeriod.rpt_period_id
where reportingPeriod.calendar_year >= 2019;
```
