### ISSUE TITLE
Refactor QA Test Summary Section 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3916]
Scope:

- Clean up the Test Data section and the sections underneath to remove any unneccessary files
- Refine components into reusable components
- Refactor API calls for QA Test Summary Data
- Clean up the console logs and warnings 

Testing Scope:
- Regression test the QA Test Summary Module including but not limited to View, Edit, Create and Remove

**Comment by mosesdeeCVP** [comment]
Testing Completed, there are some bugs. Tickets will be created to remedy the issues
