### ISSUE TITLE
CDC Change Data Capture for Apportioned Emissions Archive

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3928]
Add log tables and sync procedure for Informatica to ship all changes to log tables and then execute sync procedure to sync changes to the live tables.

See hour_unit_data_log and hour_unit_mats_data_log as these were originally done this way for better performance.

**CAMDDMW Schema**
- annual_unit_data
- quarter_unit_data
- month_unit_data
- day_unit_data

Need to setup CDC sync process for all archive tables
**CAMDDMW_ARCH Schema**
- annual_unit_data_a
- quarter_unit_data_a
- month_unit_data_a
- day_unit_data_a
- hour_unit_data_a
- hour_unit_mats_data_a

**Comment by jwhitehead77** [comment]
Placing in peer review until Informatica completes their work and ready to test
