### ISSUE TITLE
Add endpoint to MP API to retrieve configuration changes based on timestamp (Need by End of August) 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3930]
Create new endpoint similar to the following that will take a timestamp (as a query parameter) versus an oris code (remove oris code path parameter) and returns all the monitor plans & configurations (see tables below) that have changed since the timestamp that was provided. This should return the same json format as the configurations endpoints.
![image](https://user-images.githubusercontent.com/66504934/185022997-1534b8e4-5671-43b4-aedf-f2f81897d8b9.png)

**New Url:**
GET /monitor-plan-mgmt/plans/last-updated?timestamp=2022-08-15T12:00:00
Note: timestamp is required
![image](https://user-images.githubusercontent.com/66504934/185023227-7a253132-334b-4445-8bb7-afec4c50bbf6.png)

**Tables:**
- MONITOR_LOCATION
- MONITOR_PLAN
- MONITOR_PLAN_LOCATION
- STACK_PIPE
- UNIT_STACK_CONFIGURATION

**Acceptance Criteria**
- [ ] API accepts a timestamp and returns a timestamp for the next call.
- [ ] Payload would include the information returned by the current configurations endpoints (same format)
- [ ] Include unitStackConfigurations in response
- [ ] Returns a timestamp (latest timestamp data has changed) to use in next call

**Comment by JorjaComer** [comment]
Available in Dev "/monitor-plan-mgmt/plans/configurations/last-updated" is the endpoint

It is available on the swagger
