### ISSUE TITLE
Add Left Navigation for Emissions Module 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3959]
As an ECMPS user, I want to be able to navigate to hourly, daily, and MATS pages via the left navigation panel in the ECMPS browser.

- [ ] Add left-hand navigation items

- [ ] Similar to QA Cert and Test extension Menu items

Note: This ticket does not cover any view generation after clicking on one of the navigation buttons. The page does not exist will be displayed 

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/3c4ac49e-0e89-4971-9b54-302770f72b15)

**Comment by JanellC** [comment]
@aprematta Ticket 3959 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071
