### ISSUE TITLE
Add Select Configuration Screen for Daily Emissions 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3960]
As an ECMPS user, when I click on the Daily navigation item under the Emissions section, I want to be able to see a select configuration screen so that I can properly select the desired data.

- [ ] Add select configuration screen view for Daily navigation item

- [ ] Able to see the facility and configuration on the screens

Note: This ticket does not include the ability to open the tab 
![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/223e4944-81ad-4a6a-8a56-6b7e86ac3b92)

**Comment by JanellC** [comment]
@aprematta Ticket 3960 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071
