### ISSUE TITLE
Add Select Configuration Screen for Hourly Emissions 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3961]
As an ECMPS user, when I click on the Hourly navigation item under the Emissions section, I want to be able to see a select configuration screen so that I can properly select the desired data.

- [ ] Add select configuration screen view for Hourly navigation item

- [ ] Able to see the facility and configuration on the screens

Note: This ticket does not include the ability to open the tab

**Comment by JanellC** [comment]
@aprematta Ticket 3961 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071
