### ISSUE TITLE
Testing Only: Export RATA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3965]
As an ECMPS user, I need the ability to export RATA data from ECMPS so that I can review it offline

Acceptance Criteria:
Given a user is on the 'Export Data' screen
When they select QA from the options available and make selections for other required fields (Reporting Period, etc.)
And click on Preview
Then they get to see all QA data for the selected configuration available for Export

Given the user sees a preview based on their selections
When they make selections from the data displayed
And click on Export
Then they see a QA file downloaded

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0f5b5ca8-1c80-4751-bc42-cbc0ec604048)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC973](https://epacamd.testquality.com/project/11428/plan/26541/test/398459)
Test Passed
