### ISSUE TITLE
Issue with Export - Accept multiple Test Type Codes

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3973]
Issue:
When a user tries to export QA data, the UI displays a message 'No Records Found'

Resolution:
- Allow the Test Type Code field to pass multiple codes in the backend so the data can be displayed

**Comment by mosesdeeCVP** [comment]
Test Case: [TC852](https://epacamd.testquality.com/project/11428/plan/26541/test/384373)

**Comment by mosesdeeCVP** [comment]
Test Passed
