### ISSUE TITLE
QA & Cert: AET DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3975]
The following are Air Emissions Testing DTO Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] AETB-1 - Last Name Valid (Result A)
- [x] AETB-2- First Name Valid (Result A)
- [x] AETB-4 - AETB Name
- [x] AETB-5 - AETB Phone Number  (Result A)
- [x] AETB-6 - AETB Email Valid

## Testing 
Test Case: [TC1018](https://epacamd.testquality.com/project/11428/plan/27146/test/401260)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1018 passed 

**AETB-1 - Last Name Valid (Result A)**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b6ed3ebe-8eb7-4e9a-8ccc-e6f0844d2ee7)


**AETB-2- First Name Valid (Result A)**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f1af0a07-ee7f-49f3-adba-a05921cfe65d)


 **AETB-4 - AETB Name**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c41c7fe8-d69d-4c20-97a1-dc506206338e)

 AETB-5 - AETB Phone Number (Result A)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4746f4be-9907-49aa-b8d3-78a4c8a29527)

 AETB-6 - AETB Email Valid

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/bbcf94bd-77d8-4c39-bdc0-bdd27829be90)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e7abe798-5ef2-4128-bef3-e5f22392f900)
