### ISSUE TITLE
QA & Cert: RATA AET DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3976]
Implement the following RATA Air Emissions Testing DTO Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)
- [x] AETB-7 - Provider Name
- [x] AETB-8 - Provider Email Valid
- [x] AETB-9 - Exam Date Valid (Results A, B)

## Testing 
Test Case: [TC1019](https://epacamd.testquality.com/project/11428/plan/27146/test/401264)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1019 passed 

 AETB-7 - Provider Name

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/49f0fac7-58f6-443e-a600-9e7e01e7585d)

 AETB-8 - Provider Email Valid

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/57d40354-5c71-4134-849b-b30dbfb89d37)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3c589374-f78e-4e95-a1b1-d41e6acbf979)

 AETB-9 - Exam Date Valid (Results A, B)
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3b45e98a-4741-4c0d-8c05-f77e72e430fc)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a64b6710-d5d6-47b2-9149-56dd8a3c5795)
