### ISSUE TITLE
QA & Cert: RATA Test Qualification DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3977]
Implement the following RATA Test Qualification DTO Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-119 - Single-Level Claim Begin Date Valid
- [x] RATA-120 - Single-Level Claim End Date Valid

**Comment by subrataroyCVP** [comment]
Bug fix Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/284

**Comment by mosesdeeCVP** [comment]
RATA-118-A - Import

![RATA-118-A - Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b4d9a633-2edf-4265-9234-fbf113370ce1)

RATA-118-A - POST
![RATA-118-A - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93d17cee-a0d1-4c2a-b912-36ebde9aab05)

RATA-118-A - PUT
![RATA-118-A - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b7be5cfd-5778-46b4-b615-e6b47d18f327)

**Comment by mosesdeeCVP** [comment]
RATA-119-A - IMPORT
![RATA-119-A - IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8a90af2d-8e7b-491d-b67a-8393aaa859e8)

RATA-119-A - POST
![RATA-119-A - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/976f9edb-8eb7-4524-9100-07876cffb388)

RATA-119-A - PUT
![RATA-119-A - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/77a7a7c2-24f8-44d7-944e-f1e257ed959f)

**Comment by mosesdeeCVP** [comment]
RATA-120-A - IMPORT
![RATA-120-A - IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d667d529-b98a-43bc-80bf-7f34af664679)

RATA-120-A - POST
![RATA-120-A - POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/80d5fa52-6587-4b91-986d-91aff7f9ed58)

RATA-120-A - PUT
![RATA-120-A - PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/89d88513-34f6-4e4f-8b75-338152c962a8)

**Comment by mosesdeeCVP** [comment]
Test Passed: [TC1099](https://epacamd.testquality.com/project/11428/plan/26541/test/408402)
Test Passed
