### ISSUE TITLE
QA & Cert: RATA Test Qualification Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3978]
Implement the following RATA Test Qualification Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-9 - Single-Level Claim High Load Percentage Valid (Result A, B and E)
- [x] RATA-10 - Single-Level Claim Mid Load Percentage Valid (Result A, B and E)
- [x] RATA-11 - Single-Level Claim Low Load Percentage Valid (Result A, B and E)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1065](https://epacamd.testquality.com/project/11428/plan/26541/test/406192)
Test Passed

**Comment by subrataroyCVP** [comment]
Bug fix Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/284
