### ISSUE TITLE
QA & Cert: RATA Test Qualification Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3979]
Implement the following RATA Test Qualification Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-RATA-121 - Duplicate Test Claim

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/285

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1100](https://epacamd.testquality.com/project/11428/plan/26541/test/408712)
Test Passed
