### ISSUE TITLE
Story: View monitoring plan data

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#398]
## User Story
As a user I want to view production facilities data so that I can look at real time data. 

## Acceptance Criteria
Given a user has accessed EASEY In
When a user selects one and only one facility
Then the system displays, as a default, a list of the active monitoring plan for selected facility(s) in accordance with t[he wireframes  ](https://xd.adobe.com/view/e437f5dd-42bd-4e96-9da5-db61cb952e9f-b164/) (select Facilities) 
And provide an option to select inactive plans 

Given a user is viewing monitoring plans
When a user selects inactive plans
Then the system displays the inactive plans 

**Pagination AC**
Given the user has chosen to view Facilities data
When the page is displayed
Then by default all results are returned

Given the user has chosen to view Facilities data
When the page is displayed
Then the user has the option to limit results displayed on a page at a time to 100, 250, 500, or All
And the default pagination is 100

Given a user has chosen to limit results displayed on a page
When the user chooses a limit value
Then the system will limit results displayed on the page based on option selected

Given table rows exceed the page limit value selected
When the results are displayed
Then the user will have the option to select additional pages
And the system will display the total number of records returned
And the number of records on the current page 
**NEW**

**Search AC**
Given a user has accessed the facility data
When the data is displayed
Then the user has the ability to search

Given a user chooses to search
When the search criteria is displayed
Then the user may search the facility data by ORIS Code, Facility Name, or State

Given the user has entered search criteria
When the search is performed
The search matches results based on the most relevant match to the characters entered

Given at least one result is returned
When the results are displayed
Then the system will provide a way to navigate through results (e.g. scrolling)

Given no results are returned
When the user views the page
Then the system will display a message "No results match that search criteria. Please change the criteria and try again."

Dependency: Create instance in Cloud.gov, migrate data to new instance #102 and #103

Assumption: all facilities will be displayed by default until after user log in is implemented 

## Testing
Test Cases: [TC52](https://cvpcorp.testquality.com/project/11428/plan/19352/test/266393)
Tester: @mosesdeeCVP

**Comment by JorjaComer** [comment]
Prerequisite: 
Need data contracts for Facilities data completed, in progress in sprint 2.1 
Wireframes, expected completion in 2.1

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R4](https://cvpcorp.testquality.com/project/11428/testcase/266393/requirement/11021). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R5](https://cvpcorp.testquality.com/project/11428/testcase/266394/requirement/11022). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R6](https://cvpcorp.testquality.com/project/11428/testcase/266395/requirement/11030). Do not remove or edit.

**Comment by david-cvp** [comment]
BA/Tester meeting on 12/2 to confirm and approve test cases in TS26 test suite

**Comment by david-cvp** [comment]
Ready to test as of 12/8
https://easey-dev.app.cloud.gov/monitoring-plans

**Comment by david-cvp** [comment]
Closing #398 - development completed

Bugs added to backlog:
#538 
#539
#540
