### ISSUE TITLE
QA & Cert: RATA DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3981]
Implement the following RATA DTO Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-102 Number of Load Levels Valid (Result B,C)
- [x] RATA-103 Overall Relative Accuracy Valid
- [x] RATA-104 Overall BAF Valid
- [x] RATA-105 RATA Frequency Valid

**Comment by mosesdeeCVP** [comment]
Test Case: [TC890](https://epacamd.testquality.com/project/11428/plan/26541/test/388470)

**Comment by mosesdeeCVP** [comment]
Test Passed
