### ISSUE TITLE
Create MDM Endpoint for Reference Method Code (RATA Summary Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3983]
Create MDM Endpoint for Reference Method Code (RATA Summary Data):

Testing Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/eb4ac46b-1cad-42a5-a585-7516be8dda76)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/06c7a035-8779-4265-a42c-3a33796d79b8)

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a9e0c44f-2940-4cba-b775-4e0cfbe42197)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC876](https://epacamd.testquality.com/project/11428/plan/26541/test/387431)

**Comment by mosesdeeCVP** [comment]
Test Passed
