### ISSUE TITLE
View API Endpoint - Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3986]
Create GET endpoints for Protocol Gas Data:

Testing Only:
Should include GET endpoints for both Global View and Workspace to fetch one individual record

Swagger URL: https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Protocol%20Gas

Returns the same fields as the other GET protocol gas endpoints 

## Testing 
Test Case: [TC826](https://epacamd.testquality.com/project/11428/plan/26459/test/382321)
Tester:  @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
