### ISSUE TITLE
Story: View MP Location Attributes Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#399]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user access the page
When the Monitoring Plan Location Attributes data is displayed
Then the data is pulled from Cloud.gov ECMPS Schema (not the same endpoints as FACT API)

Given data is returned
When the data is displayed
Then it is displayed in accordance with the [business glossary (Location Attributes)](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/General/Analysis,%20User%20Research%20and%20Design/Analysis/EASEY%20In/Monitoring%20Plan%20Requirements%20Package/Monitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.1.xlsx?d=w6e9d9582d8a54c2ba1559189d1b15c33&csf=1&web=1&e=3WVH0I) and the wireframes (ADD LINK)

## Testing
Test Case:
Tester: @mosesdeeCVP

**Comment by JorjaComer** [comment]
Prerequisite: 
Need data contracts for MP data completed, in progress in sprint 2.1 
Wireframes, expected completion in 2.1

**Comment by karenhwwoo** [comment]
Closing because included in another MP section.

**Comment by JorjaComer** [comment]
Moved tickets to #1052
