### ISSUE TITLE
Pre-filter Test Type Code Dropdown

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3991]
As an ECMPS user I want the Test Type Code dropdown to display options based on my selection for Test Type Group so that I only see the applicable options

Acceptance Criteria:
Given I make a selection for the Test Type Group
When I open a modal to edit/add Test Data for the Test Type Group selected
Then I see that the options for Test Type Code are prefiltered based on my selection

**Comment by mosesdeeCVP** [comment]
Test Case: [TC862](https://epacamd.testquality.com/project/11428/plan/24660/test/386333)

**Comment by mosesdeeCVP** [comment]
Test Passed
