### ISSUE TITLE
Remove Duplicates from vw_check_catalog_result

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3994]
- [ ] There are duplicate values with composite keys: 
- check_type_code
- check_number
- check_result

**Comment by Kyle-Herceg** [comment]
Deleted 5849	"Mean CEM Value Valid"	"C"	"INFORM"	"Informational Message"	17	"RATA"	582	"You defined an invalid [fieldname] for [key].  This value must be greater than or equal to 0 and less than 20,000."	42298

**Comment by jwhitehead77** [comment]
--This should get the 3 records shown below...
SELECT * FROM camdecmpsmd.vw_check_catalog_result WHERE check_name = 'Mean CEM Value Valid'
![image](https://user-images.githubusercontent.com/66504934/185810007-5a7bb4c3-75fd-4e88-b403-b1a3a6e0ccda.png)

If duplicates return run the following...
DELETE camdecmpsmd.check_catalog_result where check_catalog_result_id MOT IN (953, 2067, 5855);
