### ISSUE TITLE
Display Test Data by Test Type Group

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3996]
As an ECMPS user I want the Test Data to be displayed based on my selection for the Test Type Group so that I only see data applicable to the selected Test Type

Acceptance Criteria:
Given I make a selection for the Test Type Group
When I review the Test Data displayed
Then I see that the Test Data is displayed based on the Test Type Group I made

Reference Document:
https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/3-Business%20Analysis/Test%20Data%20By%20Test%20Type%20Group.xlsx?d=waf4ed2ec4fca4b9aa5fc98b066be240a&csf=1&web=1&e=PS6Bgd

**Comment by mosesdeeCVP** [comment]
Test Case: [TC860](https://epacamd.testquality.com/project/11428/plan/24660/test/384884)

**Comment by mosesdeeCVP** [comment]
Test Passed (Linearity and Rata)
