### ISSUE TITLE
Develop Services to Display Account Data

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#4]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=019-1597186531562) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD
  

Acceptance Criteria:

- The account data service will be able to retrieve account data from the source and present it in a JSON format.

**Comment by JorjaComer** [comment]
This is covered by other epics. no longer needed
