### ISSUE TITLE
Story: View unit fuels and controls

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#400]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user access the page
When the Unit (fuels and controls) data is displayed
Then the data is pulled from Cloud.gov ECMPS Schema (not the same endpoints as FACT API)

Given data is returned
When the data is displayed
Then it is displayed in accordance with the business glossary (Unit information) and the wireframes (ADD LINK)

Dependency: data contract 

## Testing
Test Case:
Tester: @mosesdeeCVP

**Comment by JorjaComer** [comment]
Prerequisite: 
Need data contracts for Fuel/MP data completed, in progress in sprint 2.1 
Wireframes, expected completion in 2.1

**Comment by karenhwwoo** [comment]
Duplicate of #458?
