### ISSUE TITLE
API Export Derived Hourly Value Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4009]
- [x] Add Derived Hourly Value data to the existing export endpoint in the emissions module

- [x] Implement logic to export Derived hourly value data 

Each emissions record can have 0 or more hourly operating data records. Each hourly operating data record can have 0 or more derived hourly value data records. Derived hourly value data hourId should match the hourly operating data id. The list of data that should be returned is listed below.

Derived Hourly Value Data:
  parameterCode: string;
  unadjustedHourlyValue: number;
  adjustedHourlyValue: number;
  modcCode: string;
  monitoringSystemId: string;
  monitoringSystemRecordId: string;
  formulaIdentifier: string;
  percentAvailable: number;
  operatingConditionCode: string;
  segmentNumber: number;
  fuelCode: string;
  id: string;
  hourId: string;
  biasAdjustmentFactor: number;
  calcUnadjustedHrlyValue: number;
  calcAdjustedHrlyValue: number;
  diluentCapInd: number;
  userId: string;
  addDate: Date;
  updateDate: Date;
  calcPctDiluent: string;
  calcPctMoisture: string;
  calcRataStatus: string;
  calcAppeStatus: string;
  reportingPeriodId: number;
  monitoringLocationId: string;
  calcFuelFlowTotal: number;
  calcHourMeasureCode: string;

**Comment by mosesdeeCVP** [comment]
Test Case: [TC904](https://epacamd.testquality.com/project/11428/plan/26671/test/388653)

**Comment by mosesdeeCVP** [comment]
Test Passed
