### ISSUE TITLE
API: Export Hourly Fuel Flow and Hourly Parameter Fuel Flow Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4016]
As the ECMPS application, I need to be able to successfully export  Hourly Parameter Fuel Flow Data from the emissions module in order to support program goals

Each emissions record can have 0 or more hourly operating data records. Each hourly operating data record can have 0 or more  Hourly Fuel Flow data records.  Hourly Id Fuel Flow record should match the hourly operating data id. Each hourly fuel flow record can have 0 or more hourly parameter fuel flow records. The hourly fuel flow id should match the ID in the hourly fuel flow record. The list of data that should be returned is listed below:

- [ ] Add Hourly Parameter Fuel Flow data to the existing export endpoint in the emissions module

- [ ] This will also include hourly fuel flow data to the existing export endpoint in the emissions module controller
- [ ] Implement logic to export  hourly fuel flow data and Hourly Parameter Fuel Flow data

**Comment by eglove** [comment]
This adds hourlyFuelFlowData and hourlyParamaterFuelFlowData to the JSON on the export under.

Root -> hourlyOperatingData -> hourlyFuelFlowData -> hourlyParamaterFuelFlowData

Tested with:

`/emissions-mgmt/emissions/export?monitorPlanId=CPU1733-97DAE5341D864BC48553946E61C8D864&year=2020&quarter=3`

`/emissions-mgmt/emissions/export?monitorPlanId=CPU1733-778945451B18471699C6EC9B9A714465&year=2019&quarter=1`

The shape of the return data should have the same fields as HourlyFuelFlowData and HourlyParameterFuelFlowData here:
https://ecmps.camdsupport.com/documents/Emissions.xsd

To help find test data if needed in the future:

```
Select emission_evaluation.mon_plan_id, reporting_period.calendar_year, reporting_period.quarter
From 
     camdecmps.emission_evaluation
     Join camdecmpsmd.reporting_period on camdecmpsmd.reporting_period.rpt_period_id=camdecmps.emission_evaluation.rpt_period_id
     Join camdecmps.hrly_op_data on camdecmps.hrly_op_data.rpt_period_id=camdecmpsmd.reporting_period.rpt_period_id
     Join camdecmps.hrly_fuel_flow on camdecmps.hrly_fuel_flow.hour_id=camdecmps.hrly_op_data.hour_id
     Join camdecmps.hrly_param_fuel_flow on camdecmps.hrly_param_fuel_flow.hrly_fuel_flow_id=camdecmps.hrly_fuel_flow.hrly_fuel_flow_id
;
```

**Comment by AmandaMNelson** [comment]
Spoke with Ethan: the list of returned data should include the fields listed in the document linked in the comment above (below), but may also include additional database properties.

HourlyFuelFlowData:
FuelCode
FuelUsageTime
VolumetricFlowRate
VolumetricUnitsOfMeasureCode
SourceOfDataVolumetricCode
MassFlowRate
SourceOfDataMassCode
MonitoringSystemID
HourlyParameterFuelFlowData

HourlyParameterFuelFlowData:
ParameterCode
ParameterValueForFuel
FormulaIdentifier
SampleTypeCode
MonitoringSystemID
OperatingConditionCode
SegmentNumber
ParameterUOMCode
