### ISSUE TITLE
View MP Systems Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#402]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user has selected a facility
When the Monitoring Plan Systems data is selected 
Then it is displayed in accordance with the [business glossary (Monitoring Systems)](https://teams.microsoft.com/l/file/B181553F-E249-41A5-9BB8-8D075563054E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20In%2FMonitoring%20Plan%20Requirements%20Package%2FMonitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.2.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) and the [wireframes](https://xd.adobe.com/view/ccf2dda8-0f33-4df9-a581-6556fbdedeb9-99a1/screen/277d73d0-2982-4c78-a3d3-17d41d6c8454?fullscreen)

Dependency: Create MP data contract for system data 

Assumption: no keyword search and no pagination 

## Testing
Test Case: [TC116](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276363)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by JorjaComer** [comment]
Prerequisite: 
Need data contracts for MP data completed, in progress in sprint 2.1 
Wireframes, expected completion in 2.1

**Comment by mosesdeeCVP** [comment]
![402 View MP Systems Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1a1bf0a5-9b8d-48a1-801b-19ccbf09fc90)

**Comment by mosesdeeCVP** [comment]
There is a bug that is preventing the accordion table from appearing open by default. This is not specifically mentioned in the AC and the test are passing. The Product owner has accepted the story and thus it will be closed. A separate bug ticket will be created for the default open.

**Comment by mosesdeeCVP** [comment]
Bug ticket [994](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/994) was created for this story
