### ISSUE TITLE
View API Endpoint - RATA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4023]
Create GET endpoints for RATA Data:
The scope of this ticket includes creating all four GET endpoints 

Testing Only:
Should include GET endpoints for both Global View and Workspace to fetch one individual record and a collection of records

Swagger URL:
https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger/#/Rata

**Comment by mosesdeeCVP** [comment]
Test Case: [TC870](https://epacamd.testquality.com/project/11428/plan/26541/test/386735)

**Comment by mosesdeeCVP** [comment]
Test Passed
