### ISSUE TITLE
View MP Formula Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#403]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production MP Formula data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Formula** from the Sections dropdown
When the MP Formula data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Formula ID
Parameter 
Formula Code
Formula
Start Date
Start Time
End Date
End Time

Given a user is viewing MP Formula data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 62): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC390](https://epacamd.testquality.com/project/11428/plan/20423/test/303731)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Formula ID is missing from the display fields:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/bd22514c-32af-4168-bf60-c13e7dac2057)

**Comment by mosesdeeCVP** [comment]
![403 View MP Formula Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3741edb8-4df7-4eeb-ba2c-1d0e36255f0f)

**Comment by mosesdeeCVP** [comment]
Test Passed
