### ISSUE TITLE
View MP Load and operating info data from CAMDBSP/ECMPS Schema

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#404]
As a user I want to view production monitoring plan data in the MP Viewer so that I can look at real time data.

AC
Given a user access the MP viewer
When the Load and operating info data is displayed
Then the data is pulled from CAMDBSP/ECMPS Schema (not the same endpoints as FACT API)

Dependency: Create instance in Cloug.gov, migrate data to new instance

**Comment by david-cvp** [comment]
@karenhwwoo why is this one closed?

**Comment by david-cvp** [comment]
Marked invalid, was created in error
