### ISSUE TITLE
Spike: Compile a List of Missing Meta Data Properties

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4042]
- [x] Need to compile a list of the primary keys and other columns that we do not have descriptions and examples for in the emissions module. We need this in order to go back and decorate the DTOs

**Comment by sdhawan16** [comment]
Attached is a list of missing metadata properties and additional field discrepancies found during the spike. 
[Missing Metadata and Discrepancies - EPA CAMD - v1.0.xlsx](https://github.com/US-EPA-CAMD/easey-ui/files/9552023/Missing.Metadata.and.Discrepancies.-.EPA.CAMD.-.v1.0.xlsx)
