### ISSUE TITLE
Bug: Filter Daily Test Summary Data By Year and Quarter 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4043]
- [x] Modify Output so the Daily Test Summary Data is Filtering By Year and Quarter

- [x] Verify in the daily summary data has a date returning within the year and quarter specified 

Currently returning all daily test summary data and only filtering top-level daily test summary data. Need daily test summary data to be returning specified year and quarter selected

**Comment by mosesdeeCVP** [comment]
Bug fixed
