### ISSUE TITLE
Emissions Module View Updates

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4048]
Need to convert the following views located on the SQL Server client database to postgesql in the order in which they are listed below. Will split each group into smaller more manageable tickets.

From Group 1 #3790
- [ ] VW_MP_LOCATION_PROGRAM --Talk to dwayne [missing camd.unit_program.nox_group]
- [x] VW_MP_LOCATION_FUEL --sql server had fuel_cd which was changed to fuel_type to match unit_fuel host table

From Group 2 #3889
- [x] VW_MP_OP_SUPP_DATA --Waiting on tables 
- [x] VW_MP_QA_SUPP_ATTRIBUTE --Waiting on tables

From Group 3 #3890
- [x] VW_QA_SUPP_DATA_HOURLY_STATUS -- Query takes ~50 seconds

NOTES:
- Any view that references VW_CLIENT_REPORTING_PERIOD replace with camdecmpsmd.vw_reporting_period
- Any view that references VW_CROSS_CHECK_CATALOG_VALUE replace with camdecmpsmd.vw_cross_check_catalog_value
- VW_CROSS_CHECK_CATALOG --> use table directly as view does not do anything different
- VW_EVEM_REPORTING_PERIOD --> use camdecmpsmd.vw_reporting_period

**Comment by JanellC** [comment]
As of 9/22 this ticket should remain in the PI backlog until priotized when the team is ready to test emissions data through the check engine
