### ISSUE TITLE
View MP Load Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#405]
Definition of Ready

- [x] Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [x]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [x]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production monitoring plan data for Load so that I can look at real-time data.

## Acceptance Criteria
Given a user accesses the page
When the Monitoring Plan Load data is displayed
Then the data is pulled from Cloud.gov ECMPS Schema (not the same endpoints as FACT API)

Given a user has selected Load from the Sections dropdown
When the Monitoring Plan Load data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Maximum Load Value: Text
Maximum Load Units of Measure: drop-down
Lower Operation Boundary: Text
Upper Operation Boundary: Text
Normal Level: drop-down, required (Operating Level Code)
Second Level: drop-down, required (Operating Level Code)
Second Normal Indicator: Yes/No Radiobutton, required
Load Analysis Date: date picker, format mm/dd/yyyy
Begin Date: date picker, format mm/dd/yyyy
Begin Time: Text, format hh
End Date: date picker, format mm/dd/yyyy
End Time: Text, format hh

Given a user is viewing Monitoring Plan Loads
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [x] Yes 
- [ ] No

Filter by keyword?

- [x] Yes 
- [ ] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Refer to page 118 for values (https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

Testing
Test Case: @mosesdeeCVP 
Tester: [TC386](https://epacamd.testquality.com/project/11428/plan/21921/test/303714)

Definition of Done

- [x]  Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x]  Has the code been unit tested and peer reviewed?
- [x]  Have the functional tests been executed?
- [x]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x]  Has the user story been accepted by the Product Owner?
- [x]  Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![405 View MP Load Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/de2846ba-dca8-4bd5-b058-86b32a40aef9)

![405 View MP Load Data 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/22280bfb-30b6-48ed-a109-2d676248745d)

**Comment by mosesdeeCVP** [comment]
Test Passed
