### ISSUE TITLE
508 Issues : Export Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4050]
**Issue:**
1. Aria labels for individual checkboxes are non-specific in the test summary table. For example aria-label="select-row-TWCORNEL5-ED43ABD50CC846EE8263A66EBE2A8C0F" 

**Resolution:**
Need to tie to a unique characteristic of each row
Update to aria-label="select-row-Test Number" 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4ff90981-6836-48c8-9ad0-dbd3cd39e399)

2. The test summary data table has no programmatic name
Update to aria-label for Test Summary Data"
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/180ef36c-ec6f-4d61-a781-c977d1e5ce8a)

**Comment by aprematta** [comment]
Not seeing any changes on https://ecmps-dev.app.cloud.gov/export..... the issues still remain

**Comment by subrataroyCVP** [comment]
I can see them there. look at the screenshot. Try in Incognito.
![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/898cb6dc-3d54-413f-8ffb-8e2a0d0f7a3a)

**Comment by aprematta** [comment]
The aria label of 'test summary data' needs to be in the same div as the one that has role = table. For the row aria label, is that the Test number? If so I think we should change it to 'select row for Test Number -Test Number Value-

**Comment by subrataroyCVP** [comment]
Ok. I can change it. For the checkbox I have already changed it to 'select-row-Test Number Value'

**Comment by subrataroyCVP** [comment]
@aprematta Changes pushed. You can check them again.

**Comment by aprematta** [comment]
Table looks good. Sorry wasn't clear on the checkboxes. it should be "select row for Test Number 20200818134618CO2" as an example.

**Comment by subrataroyCVP** [comment]
@aprematta Sorry. I am little confused which one you want me to

`aria-label="select row for Test Number 201504060000AA4"`

or

`aria-label="select-row-for-Test-Number-201504060000AA4"`

**Comment by aprematta** [comment]
The first one is good, no need for the dashes

**Comment by subrataroyCVP** [comment]
Changes Merged.

**Comment by aprematta** [comment]
Looks good! Closing ticket
