### ISSUE TITLE
508 Issue: Import Historical Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4056]
**Issue:**
1. On the import historical test data modal, the preview summary table data cells have grid cells instead of cell
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/17734f4d-ab75-48ba-9c4d-f7fd53fc9e5a)

2. On the import historical test data modal, Aria labels for individual checkboxes are non-specific
Resolution: Put aria label, aria-label="select-row-Test Number" 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d33c8747-9220-4f63-9c99-dd6c6227267b)

**Comment by aprematta** [comment]
Testing complete, both issues have been fixed
