### ISSUE TITLE
508 Issue: QA Test Data Section

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4057]
**Issue:**
When closing the View modal for Test Data/Test Summary Data, focus does not return to the appropriate view and Edit button
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/64611bf2-17d4-44e1-8b3c-599b81284147)

Scope: This is applicable to View and Edit  buttons that open a modal, should return the focus to the respective view and edit button on Modal close.

**Comment by aprematta** [comment]
Focus now properly returns to view and edit buttons
