### ISSUE TITLE
508 Issue: Expand/Collapse Carat (+/_)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4058]
**Issue:**
1. In QA Test Summary Data, focus is lost when expanding/contracting a row

Resolution:
Focus should stay on the +/- element

2. The focus state of the +/- relies on the changing of the title attribute. Get rid of the title attribute and Aria should be expanded=true/false as applicable

**Comment by aprematta** [comment]
The focus is good but the 2nd item was not addressed. Aria expanded was not added

**Comment by aprematta** [comment]
Aria expanded has been confirmed
