### ISSUE TITLE
508 Issue: QA Test Data - View Option

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4059]
**Issue:**
Location: Test Data Section
There are multiple view links and they need additional programmatic description so they are unique

Resolution:
Add aria-label to include View for 'Test Number' (Test Number is unique to a given Location and Test Type Group)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7b7b0ef5-0684-4342-9e0d-c04065b1b201)

**Scope: for this ticket is to address the view button for test summary data ONLY**

**Comment by aprematta** [comment]
View buttons are now unique
