### ISSUE TITLE
View MP Defaults Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#406]
Definition of Ready
 
- [x] Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [x]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [x]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?

User Story
As an ECMPS user, I want to view production monitoring plan default data so that I can look at real-time data.

Acceptance Criteria
Given a user has selected Defaults from the Sections dropdown
When the Monitoring Plan Defaults data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Parameter: Drop-down
Default Value: Text
Units of Measure: dropdown
Purpose: dropdown
Fuel Code: dropdown
Operating Condition: dropdown
Source of Value: dropdown
Group ID: Text
Start Date: date picker, format mm/dd/yyyy
Start Time: Text, format hh
End Date: date picker, format mm/dd/yyyy
End Time: Text, required, format hh

MP Reporting Instructions (See page 92): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

Given a user is viewing Monitoring Plan Defaults
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [x] Yes 
- [ ] No

Filter by keyword?

- [x] Yes 
- [ ] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Testing
Test Case: [TC381](https://epacamd.testquality.com/project/11428/plan/21902/test/303537)
Tester: @mosesdeeCVP 

Definition of Done

- [ ]  Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ]  Has the code been unit tested and peer reviewed?
- [ ]  Have the functional tests been executed?
- [ ]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ]  Has the user story been accepted by the Product Owner?
- [ ]  Is the user story ready to be deployed to the test/staging environments?

**Comment by vishnunavuluri** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/406?planning-poker) with ZenHub @mosesdeeCVP

**Comment by vishnunavuluri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Emissioners-Scrum-Board-5f36cd263511ad001a777f8e/issues/US-EPA-CAMD/easey-ui/406?planning-poker) with ZenHub @Qb10 @mosesdeeCVP @jeffreyaggrey

**Comment by mosesdeeCVP** [comment]
![406 View MP Defaults Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c4f19370-265a-4fe1-8878-eaef1f0fbc6f)

![406 View MP Defaults Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dbd679f6-4335-4fb3-99e6-107680ea3136)

**Comment by mosesdeeCVP** [comment]
Test Passed
