### ISSUE TITLE
QA & Cert: Import from Historical Data Update

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4064]
When importing from historical data the data needs to be copied over exactly as is including all the primary keys of all records becasue this is how the user would resubmit an existing test. This import should not go through any of the screen checks or import checks and the API should just call a database function/procedure to copy the data from camdecmps to camdecmpswks.

LINEAR-31 needs to be updated to account for importing from historical data by changing the logic for the otherwise block of the check spec. When the check spec says "Locate an unassociated QASupp record..." that means look for another record in the qa_supp_data table with the same conditions but a different test_sum_id.

**Comment by mosesdeeCVP** [comment]
Import from Historical Data Update - Complete
LINEAR-31-A - Complete
LINEAR-31-B - Complete
