### ISSUE TITLE
QA & Cert: RATA DTO Checks (Test Summary)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4065]
Implement the following RATA DTO Checks

[QA and Certification Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-4   Test Reason Code Valid (should already be done as part of Test Summary checks when working on Linearity Test type)
- [x] RATA-100 Test Result Code Valid
- [x] RATA-117 System ID Valid 
- [x] RATA-123 APS Indicator ValidRATA Summary Check Service

**Comment by mosesdeeCVP** [comment]
Test Case: [TC884](https://epacamd.testquality.com/project/11428/plan/26541/test/388414)

**Comment by mosesdeeCVP** [comment]
Test Passed
