### ISSUE TITLE
View API Endpoint - Test Qualification Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4066]
Create GET endpoints (4) for Test Qualification Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Test Claim Code (Dropdown)
Begin Date (Date Picker & Text)
End Date (Date Picker & Text)
High Load Percentage (Text)
Mid Load Percentage (Text)
Low Load Percentage  (Text)

## Testing 
Test Case: [ TC903 ](https://epacamd.testquality.com/project/11428/plan/26922/test/388648)
Tester: @JanellC

**Comment by vishnunavuluri** [comment]
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2bnZtdnp3MDFlaTNiNnhsc3MxcHI0Yg%3D%3D

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9d0d369e-e2d0-4750-97c7-2c29de5cd75b)

**Comment by JanellC** [comment]
TC903 passed 

Global 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/346c05d0-24af-40f5-8a0a-908d25fc4e96)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a3f08855-cf8d-4429-b515-01f5f0c8e999)


Work Space: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/691981f3-5ef9-469a-865c-764b15920084)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ad317d46-51bf-4f4a-994c-3a9172b478fa)
