### ISSUE TITLE
Refactor Check Catalogue Result Messages

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4073]
- [x] Eliminate the need to have the constant file with all of the hard-coded messages for the following checks:

- Import-25 Check For Emissions Module
- Import-23 Check For Emissions Module
- Import-27 Check For Emissions Module
- Import-29 Check For Emissions Module
- Import-38 Check For Emissions Module

## Context 

For testing, complete regression testing on each import check to ensure each check is working as expected.

**Comment by mosesdeeCVP** [comment]
Regression test complete. Works as expected
