### ISSUE TITLE
Refactoring of the Tabs Select Configuration Screen 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4074]
- [x] Refactor the tabs to track across all modules 

- [x] When you open a tab up it's open across all modules refactoring the management of the state and storage.

- [x] You are able to switch between all modules without having to reopen the tabs

*Note: This will be a ticket worked with QA developers (coordinate with Quang and/or Adis)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC177](https://epacamd.testquality.com/project/11428/plan/20730/test/282810)
Test Passed
