### ISSUE TITLE
Refactor API Export MATS Derived Hourly Value Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4077]
- [x] Refactoring the service so that it can be reusable and consistent with the other data types

# Context
Conduct regression testing on MATS Derived Hourly Value to ensure it is still returning as expected

Each emissions record can have 0 or more hourly operating data records. Each hourly operating data record can have 0 or more MATS derived hourly value data records. MATS derived hourly value data hourId should match the hourly operating data id. The list of data that should be returned is listed below.

MATS Derived Hourly Value Data:
parameterCode: string;
unadjustedHourlyValue?: string;
modcCode?: string;
formulaIdentifier?: string;
id: string;
hourId: string;
calcUnadjustedHrlyValue?: string;
calcPctDiluent?: number;
calcPctMoisture?: number;
monitoringLocationId: string;
reportingPeriodId: number;
userId?: string;
addDate?: Date;
updateDate?: Date;

**Comment by mosesdeeCVP** [comment]
Test Case: [TC902](https://epacamd.testquality.com/project/11428/plan/26671/test/388644)
Test Passed
