### ISSUE TITLE
Increase Unit Test Coverage for Hourly Operating Module 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4080]
- [ ] Increase unit test coverage to at least 70% for: 
- Hourly Operating 40%
- Hourly Operating Workspace 40%

**Comment by fanwari1** [comment]
![image](https://user-images.githubusercontent.com/102816236/189994946-aecd2a86-8a88-48c6-83ba-16e45ab16129.png)
