### ISSUE TITLE
Restructure MP Configurations Tab

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4081]
Scope:

- Restructure the header section to move the Location next to Configuration Name
- Realign Check-out/Check Back In  buttons
- Move Revert to the Official Record option
- Move the Evaluation Status and the Submission Status options
- Move View Comments option (Refer to the reference)
- Add 'Monitoring Plan Audit Report' and 'Monitoring Plan Report'

Invision Reference: https://projects.invisionapp.com/freehand/document/F1HnXS75P?zoomToItems=Y2w3NjltMnc1MDByNzNiN29qa2hhOGtsZw%3D%3D

https://projects.invisionapp.com/freehand/document/F1HnXS75P?zoomToItems=Y2w3NjltMnc1MDB1MDNiN29jNGp4bDJubQ%3D%3D

## Testing 
Test Case[: TC914](https://epacamd.testquality.com/project/11428/plan/24660/test/392446)
Tester: @JanellC

**Comment by JanellC** [comment]
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/68f73a3b-24f4-473c-b3d4-0cbc8d444f6b)

TC914 passed 


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/78e0f66f-f9ce-491b-9cc6-dc54867feaef)

**Comment by JanellC** [comment]
@aprematta this ticket is ready for 508 testing and can be located in the MP/ QA 508 Testing- PI 10 #4150 epic
