### ISSUE TITLE
Restructure QA Configurations Tab - Options and Layout

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4082]
Scope:

- Restructure the header section to move the Location next to Configuration Name
- Realign Check-out/Check Back In buttons
- Add 'Revert to the Official Record' option
- Relabel 'Evaluate All' option to 'Evaluate'
- Move the Import Test Data and Evaluate options
- Move 'Test Data Report', 'Test History Report', and Evaluation Report 

Invision Board Reference:
https://projects.invisionapp.com/freehand/document/F1HnXS75P?zoomToItems=Y2w3ZjBnM2tzMDA3ZzNiN2w1Y2x0M2txbA%3D%3D

https://projects.invisionapp.com/freehand/document/F1HnXS75P?zoomToItems=Y2w3NTFjbWtmMDExcTNiN21wM3AzNDgzeQ%3D%3D

**Comment by mosesdeeCVP** [comment]
Test Case: [TC910](https://epacamd.testquality.com/project/11428/plan/24660/test/391388)
Test Passed
