### ISSUE TITLE
Bug: Bulk Data Files Maintaining Selections after switching between filter 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4085]
```
Wait! Most bugs should be entered in TestQuality. Proceed with caution. 
```
## Test Case
Test Case: [TC913](https://epacamd.testquality.com/project/11428/plan/24093/test/391913)
Tester: Maegan Wood

## Steps to Reproduce
1) Go to bulk data files and select any filter
2) Select a file within that filter
3) Change the filter that excludes the file selected 
4) The File still remains selected

### User Story
As a User, I want my selections for bulk data files to clear when I change the data type, so that I am able to start a new download 

### Acceptance Criteria
Given a User is on the Bulk Data Files Page
When the User Changes the Data Type
Then a Windox Box Appears, Reading "Changing the Data Type will clear out file and filter selections. Do you want to proceed?"

![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/a4de01bd-565e-4a78-a1eb-6f1467578537)

Given a User is on the Bulk Data Files Page
When the User Changes the Data Type
And they press "OK" on the window alert
Then the System Clears out File and Filter Selections

Given a User is on the Bulk Data Files Page
When the User Changes the Data Type
And they press "Cancel" on the window alert
Then the System retains the File and Filter Selections

**Comment by MaeganWood64** [comment]
@tlageman-epa TC913 passed

**Comment by tlageman-epa** [comment]
@MaeganWood64 @AbuFofanah The warning pop-up should not show up the first time the user visits the page and picks a data type. It should only show up if they are changing it. It doesn't make sense to get a warning when you first pick a data type since you aren't changing anything but rather making an initial selection.
