### ISSUE TITLE
Issue editing a System Component

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4091]
**Issue 1:**
- The Edit for System Component (MP) is throwing an error

Steps to recreate:
- Login and access the MP workspace
- Click on View/Edit for System and select any one of the Components
- Make updates and click on Save and Close
- User encounters the following 2 errors and the updates are not saved

When Basis Description is selected:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/b6e04f05-6050-4d47-8499-1dedfdfa4a45)

When no selection is made for the Basis Description:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9b0db1fc-f6c2-4e1e-8704-373bdaef25f0)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
