### ISSUE TITLE
QA: Datatable View Updates

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4095]
**Issue:**

The fields Protocol gas 'Vendor ID' and 'Cylinder ID' column in the data table view displays the values incorrectly. Currently, the Vendor ID is showing the value for the Cylinder ID and vice versa

Protocol Gas Data section can be found for Liearity Summary Data and RATA currently

Note: The View modal displays the values correctly

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/d6d617b9-a609-4ff9-bd41-45fdbd619e4d/download](https://app.zenhub.com/files/287570343/d6d617b9-a609-4ff9-bd41-45fdbd619e4d/download)

**Comment by mosesdeeCVP** [comment]
Bug fixed
