### ISSUE TITLE
Update Component MDM Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4096]
- Keep the MDM data within the local state/component as opposed to in the REDUX
- Minimize calling the same MDM endpoint multiple times. Update this to call the endpoint once as needed

Testing Scope:
- Test all the MDM dropdowns (Should work as expected)

**Comment by JanellC** [comment]
MDM Drop downs for test summary, Lineraity, and RATA data working as expected
