### ISSUE TITLE
Refactor Check Result Messages

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4097]
Refactor Check Result Messages to use the check catalogue service that pulls the results from the database

The query for the checks I showed...
select *
from camdecmpsmd.vw_qa_certification_api_check_catalog_results
where "checkTypeCode" = 'IMPORT'
and "checkNumber" = 14
order by "resultCode"

## Testing 

For regression testing Need to confirm that all of the Check Messages are correct for the following test types:
linearity-injection-checks
linearity-summary-checks
rata-checks
test-summary-checks

**Comment by mosesdeeCVP** [comment]
Errors are firing

**Comment by mosesdeeCVP** [comment]
Vishnu will put together a list to make more targeted tests to check. As per our discussion.
