### ISSUE TITLE
Issue with RATA Run Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4098]
**Issue:**

- User edits/updates RATA Run Data, clicks Save and Close
- System throws the following error even though Operating Level Code is not applicable to RATA Run Data
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d16e3230-42e5-40d9-8d96-4231287e46f6)

**Comment by JanellC** [comment]
Issue resolved. The system no longer displays the operating level code error for Rata run data
