### ISSUE TITLE
Emissions Module Stored Procedure and Function Conversion

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4100]

**Comment by SimeraHailu** [comment]
[https://app.zenhub.com/files/287570343/8855c201-b865-4a86-bdbd-6c7db4209123/download](https://app.zenhub.com/files/287570343/8855c201-b865-4a86-bdbd-6c7db4209123/download)

**Comment by ayang2017** [comment]
I finished 5 new views. In my list I also add notes for where condition when query it. Just for reference.
1. camdecmpswks.vw_component_op_supp_data (where mpl.MON_PLAN_ID = vMonPlanId)		
2. camdecmpswks.vw_MATS_Derived_Hourly_Value_Data(dbo.DB_ID_KEY, RptPeriodId dbo.ID_KEY, dat.PARAMETER_CD IN (PARAMETER_CD + 'RE', PARAMETER_CD + 'RH')	
3. camdecmpswks.vw_MATS_Monitor_Hourly_Value_Data( dbo.DB_ID_KEY, RptPeriodId dbo.ID_KEY, OR dat.PARAMETER_CD = PARAMETER_CD + 'C')
4. camdecmpswks.vw_MATS_Hourly_Gas_Flow_Meter_Record( monPlanId,rptPeriodId	)	
5. camdecmpswks.vw_monitor_qualification_percent_data (mpl.Mon_Plan_Id = monPlanid)

**Comment by ayang2017** [comment]
Update--Deleted the views as I previous listed. They are originally SQL table-valued functions with input parameter(s). So they are going to be converted to functions.
These are the ones I just finished:
camdecmpswks.component_op_supp_data
camdecmpswks.mats_Derived_Hourly_Value_Data
camdecmpswks.mats_Monitor_Hourly_Value_Data
camdecmpswks.mats_Hourly_Gas_Flow_Meter_Record
camdecmpswks.mats_Sampling_Train_Record

**Comment by ayang2017** [comment]
I'm still working on the two remaining functions for conversion. Here are the finished ones, which also included the ones I mentioned in last update.
camdecmpswks.component_op_supp_data
camdecmpswks.mats_Derived_Hourly_Value_Data
camdecmpswks.mats_Monitor_Hourly_Value_Data
camdecmpswks.mats_Hourly_Gas_Flow_Meter_Record
camdecmpswks.mats_Sampling_Train_Record
camdecmpswks.mats_Sorbent_Trap_record
camdecmpswks.mats_Sorbent_Trap_Supplemental_Data_record
camdecmpswks.monitor_qualification_Percent_Data
camdecmpswks.Mp_Location_NonLoad_Based_Indication
camdecmpswks.On_Off_Calibration_Test_All_Data
camdecmpswks.Reporting_Frequency_By_Location_Quarter
camdecmpswks.System_op_supp_data
camdecmpswks.check_date_hour
camdecmpswks.format_date_time
camdecmpswks.date_add

**Comment by ayang2017** [comment]
Work update-- all listed functions are converted, except for SynchronizationManagement, which we agree no longer needed. The same with the listed synonyms.

**Comment by SimeraHailu** [comment]
updates being made to UPD_SESSION_CALCULATED_QA 
-completed
