### ISSUE TITLE
UI: Implement Emissions Main View Layout 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4106]
As an ECMPs user, I want to be able to see the main emissions UI layout in the Emissions Data section so that I can ensure that I am viewing the relevant data I need to support program goals.

Given a user has navigated to the daily emissions section of the emissions module
When they open up the daily emissions page UI 
They will see the main emissions module layout 

- [ ] View Template dropdown will be populated by a call to the List of Views Emissions Module API 

 Emissions Module UI Layout 
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w3NjlxZnI1MDBiNzNiN2YwbWFxZXJxdA%3D%3D

Emissions Module UI Layout with dropdown examples 
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w3OTlya3BrMDAxbjNiN295bjgyNjdhag%3D%3D

https://xd.adobe.com/view/28ee8c47-fbcd-42c7-96de-c9ab2efd7e13-7dbd/

**Comment by NadiaJL** [comment]
Year/Quarter Dropdown Xd Prototype:

https://xd.adobe.com/view/4f578e7d-4548-4744-9098-5b8e944c7c9c-1a04/

Emissions Dropdown inVision Link: https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w5b2E0Y3NnMDBmMzNiNzVkODlrcjVyaw%3D%3D

**Comment by fanwari1** [comment]
To test this ticket, you can go to the page by

1. Logging in
2. Going to emissions on the side menu
3. Choosing a configuration and doing "open & checkout" (I usually just use barry)
4. Click on the tab that opened and you should be able to see the layout.

**Comment by acollad1** [comment]
@aprematta Ticket 4106 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071
