### ISSUE TITLE
Update CAMPD Error message banner 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4110]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want the error page banner to display as appropriate so that I know an error occurred with CAMPD 

## Acceptance Criteria
Given that a user has accessed CAMPD 
When the error message banner is displayed 
Then the  error message banner is displayed below the CAMPD sub header 

Given that a user has accessed a CAMPD web page 
When all of the page content is available 
Then the  error message banner is **NOT** displayed 

Given that an admin has accessed the EASEY Content Repo 
When the functionality is displayed 
Then the admin has the ability to edit the message on the error message banner 

### Development Notes

Admins will have the ability to edit the error messages displayed on the banner through the easey content repo. If the easey content repo is down then the system will display the following generic error message in the banner: All of the content on this page may not be available. If you continue to encounter this issue, contact CAMPD support: campd-support@camdsupport.com

The page error message banner should be displayed below the CAMPD sub header. see area highlighted in red below 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/da3005fe-8f20-459f-bea3-a0da368c8d36)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/73abc7cf-dac6-47df-b7d2-c0a8148b777f)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Testing
Test Case: [TC915](https://epacamd.testquality.com/project/11428/plan/26079/test/392629)
Tester: Maegan Wood

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by MaeganWood64** [comment]
@tlageman-epa tc915 passed
