### ISSUE TITLE
Update ECMPS Export Preview functionality 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4112]
## User Story 

As an ECMPS user I want to be able to export and preview QA data using the export page on the left navigation panel of the ECMPS application.

## Acceptance Criteria 

Given a user navigates to the export page of the ECMPS application
When a user selects Emissions or Monitoring Plan as a data type
Then the preview functionality  is disabled 
AND the user can export their file 

Given a user navigates to the export page of the ECMPS application
When a user select QA as a data type
Then the preview button is enabled 

Given that a user has selected QA as an export data type 
When preview is selected
Then the applicable QA data is displayed 

Given that a user has previewed their QA data 
When QA data is selected from the data table 
Then the export functionality is enabled 

 

## Dev Notes 

**Preview Functionality** 
 Preview will not be required to export Monitoring and Emissions and the preview button is only enabled for QA.

Are users still required to preview qa data? or can they just export the entire file?

**Comment by vishnunavuluri** [comment]
1/13/2023: The functionality seems to have been implemented in Dev already.
