### ISSUE TITLE
QA & Cert: RATA Traverse DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4113]
The scope of this ticket is to address the following RATA Traverse DTO Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-70 - Method Traverse Point ID Valid (Result A)
- [x] RATA-71 - Probe ID Valid
- [x] RATA-72 - Probe Type Valid (Result A)
- [x] RATA-73 - Pressure Measure Code Valid
- [x] RATA-74 - Velocity Calibration Coefficient Valid

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1060](https://epacamd.testquality.com/project/11428/plan/26541/test/406125)
Test Passed
