### ISSUE TITLE
QA & Cert: RATA Traverse DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4114]
The scope of this ticket is to address the following RATA Traverse DTO Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-75 - Last Probe Calibration Date Valid (Result A)
- [x] RATA-76 - Velocity Differential Pressure Valid
- [x] RATA-77 - Stack Temperature Valid
- [x] RATA-73 - Pressure Measure Code Valid
- [x] RATA-85 - Number of Traverse Points Valid (Results A, B)

**Comment by subrataroyCVP** [comment]
- RATA-73 - Pressure Measure Code Valid ** ( Completed in #4113)
- RATA-85 - Number of Traverse Points Valid (Results A, B) ** ( Completed on #4312 )

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1063](https://epacamd.testquality.com/project/11428/plan/26541/test/406160)
Test Passed
