### ISSUE TITLE
QA & Cert: Import Validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4118]
The scope of this ticket is to address the following Import Validations:

(https://ecmps.camdsupport.com/documents/ECMPS%20Import%20Check%20Specifications%202018Q2.pdf)

- [ ] IMPORT-19  - Inappropriate Children Record for RATA 
- [ ] IMPORT-30  - Extraneous RATA Summary Data Check

**Comment by mosesdeeCVP** [comment]
Bugs will be addressed in another ticket: [Bug: Import Validations IMPORT-19 and 30 #4275](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/4275)
