### ISSUE TITLE
QA & Cert: RATA Run Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4121]
The scope of this ticket is to address the following RATA Run Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-27 - CEM Value Valid (Result C)
- [x] RATA-29 - Run Status Code Valid (Results B, C)
- [x] RATA-33 - Reference Value Valid (Result C)

## Testing 
Test Case: [TC950](https://epacamd.testquality.com/project/11428/plan/26541/test/395873)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed
