### ISSUE TITLE
Add RATA data to Export endpoints

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4127]
Add the following data elements to the existing RATA EXPORT endpoints:

- RATA Data
- RATA Summary Data
- RATA Run

**Comment by mosesdeeCVP** [comment]
Test Case: [TC940](https://epacamd.testquality.com/project/11428/plan/26541/test/394866)

Test Passed

**Comment by mosesdeeCVP** [comment]
![RataData and RataSumData.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f8427496-1306-4607-b51a-f8726a957b09)

![RataRunData.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/11ac260b-ba6b-4d06-9ed9-1de09a2ec3bd)
