### ISSUE TITLE
API Endpoint - View 'Air Emissions Testing' Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4128]
Create GET endpoints (4) for Air Emissions Testing Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
QI Last Name (Text)
QI First Name (Text)
QI Middle Initial (Text)
AETB Name (Text)
AETB Phone Number (Text)
AETB Email (Text)
Exam Date (Text/Date Picker)
Provider Name (Text)
Provider Email (Text)

## Testing 
Test Case: [TC952](https://epacamd.testquality.com/project/11428/plan/26541/test/396075)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC952 passed 

Workspace 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9829b607-c710-4b81-bc2b-ec8a51bb94f8)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/cd49b64c-594e-4824-ab81-2cd0522196f7)

**Global:** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1197c8b0-061d-4335-8963-d331fe24ca46)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6bc1b3a2-06ff-467e-b841-942743a2079e)
