### ISSUE TITLE
Global 'View' and Workspace 'Add': Air Emissions Testing Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4131]
As an ECMPS user, I want to view Air Emissions Testing data in the Global-View and add new Air Emissions Testing data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Relative Accuracy from the Test Type Group dropdown and a RATA data record is available 
When the RATA data is displayed 
Then the user can see Air Emission (AET) data displayed as a separate table (see list below for columns and order)

QI Last Name (Text)
QI First Name (Text)
QI Middle Initial (Text)
AETB Name (Text)
AETB Phone Number (Text)
AETB Email (Text)
Exam Date (Text/Date Picker)
Provider Name (Text)
Provider Email (Text)

Given a user is viewing Air Emissions Testing Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Relative Accuracy from the Test Type Group dropdown
When the user clicks on 'Add' for Air Emission
Then the system displays a modal
and the user can add new data for:

QI Last Name (Text)
QI First Name (Text)
QI Middle Initial (Text)
AETB Name (Text)
AETB Phone Number (Text)
AETB Email (Text)
Exam Date (Text/Date Picker)
Provider Name (Text)
Provider Email (Text)

Given the user has added Air Emission data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the AET data record is reflected on the UI

Given the user has added a new 'AET' record
When the user chooses to Cancel
Then the user is returned to the Landing screen for RATA data
And no updates are saved

Dev Notes:
AET should be a reusable component (Applicable to App E and Unit Default). AET is at the same level as Protocol Gas data is for RATA

Reference Invision:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2YXc0OThtMDBkcjNiNnliZWlsdnllYg%3D%3D
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2Z3IwMHZvMDFtcTNiN2k5NzQ4OWdodQ%3D%3D

## Testing 
Test Case: [TC919](https://epacamd.testquality.com/project/11428/plan/26541/test/392964)
Tester: @JanellC

**Comment by JanellC** [comment]
TC919 failed. The system does not consistenly add an air emissions record see bug #4248

**Global - View** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e20ad863-5896-48fb-97d5-021c76e9918b)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/32c95099-6c89-4ad1-9717-4a567e786959)

**Workspace- Add** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b6cb0e04-28ba-4113-a7fc-9be8b3ca7e44)
