### ISSUE TITLE
Remove Air Emission Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4132]
As an ECMPS user, I want the ability to remove Air Emission Data so that I can update Relative Accuracy Data as needed

Acceptance Criteria:
Given I am in the Air Emission section
When I click on the 'Remove' option for Air Emission
Then I see that the relevant AET data record is deleted

Given I chose to remove Air Emission Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the Air Emission section
When I select Cancel
Then I am returned to the landing screen for Air Emission Data

Invision Board:
https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w2YXc0OThtMDBqaDNiNnlnanNjaWF4Mg%3D%3D

## Testing 
Test Case: [TC922 ](https://epacamd.testquality.com/project/11428/plan/26541/test/392970)
Tester:  @JanellC

**Comment by JanellC** [comment]
The system removes an air emissions data record however discovered a bug. See  bug #4239
