### ISSUE TITLE
Create MDM Endpoint for Pressure Measure Code (RATA Traverse Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4134]
Create MDM Endpoint for Pressure Measure Code

Testing Only:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/62a66324-2d64-4e84-aeb3-fb2c775c8730)

## Testing 
Test Case: [TC936](https://epacamd.testquality.com/project/11428/plan/26541/test/393889)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Pressure Measure Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/628bdd94-14c6-4a28-bc11-ececa69ac84c)
