### ISSUE TITLE
Add Protocol Gas Data to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4138]
Add Protocol Gas Data elements to the existing Export endpoint

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/b74061ed-2f80-4879-9790-3d104c5625db)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC955](https://epacamd.testquality.com/project/11428/plan/26459/test/396836)

**Comment by mosesdeeCVP** [comment]
Test Passed
