### ISSUE TITLE
Add Flow RATA Run data elements to Export

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4139]

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/46eb7c16-0e71-4bc9-a614-126570339d32)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC953](https://epacamd.testquality.com/project/11428/plan/26541/test/396834)

Test Passed
