### ISSUE TITLE
Add Flow RATA Run data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4140]

**Comment by mosesdeeCVP** [comment]
![rataRunData-Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/57dd271f-27a8-41cc-927f-99d5f3e09f3a)

**Comment by mosesdeeCVP** [comment]
![flowRataRunData-TR1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/770431ad-adeb-4fa8-aa5b-16fefa411e1e)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC957](https://epacamd.testquality.com/project/11428/plan/26541/test/396842)
Test Passed
