### ISSUE TITLE
Add Traverse Data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4141]
Add RATA Traverse Data elements to Export Endpoint

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d5f7e87a-1faa-4887-b9f4-dad5c89d67f7)

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0c89651f-dc56-4b32-b3f6-5c00baba0eba)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC954](https://epacamd.testquality.com/project/11428/plan/26541/test/396835)

Test Passed
