### ISSUE TITLE
Add Traverse Data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4142]

**Comment by mosesdeeCVP** [comment]
![rataTraverseData-Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6b9c58a5-1563-4114-980e-d2715c6b6505)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC958](https://epacamd.testquality.com/project/11428/plan/26541/test/396843)
Test Passed
