### ISSUE TITLE
Add Fuel Flow To Load Test Data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4145]
Add Fuel Flow To Load Test Data elements to Export Endpoint

**Comment by mosesdeeCVP** [comment]
Add Fuel Flow To Load Test Data elements to Export Endpoint - Workspace

![4145 Add Fuel Flow To Load Test Data elements to Export Endpoint - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0a9b32f6-29eb-44fe-b6a5-ded0737039e3)

**Comment by mosesdeeCVP** [comment]
![4145 Add Fuel Flow To Load Test Data elements to Export Endpoint - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f6f0c69f-c7d5-419e-90fc-039e92666761)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1027](https://epacamd.testquality.com/project/11428/plan/27145/test/401722)
Test Passed
