### ISSUE TITLE
Emissions Module View: Combined Parameters #1

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4157]
Current Template Name: All Parameters
New Name: Hourly Combined Parameters
Order in dropdown: #1

## Step #1:
Convert the following table in the SQL Server client database to Postgres.

**Table is in the ECMPS client SQL Server database**
- [dbo].[EMISSION_VIEW_ALL]

**Table will need to be in the camdecmps and camdecmpswks schemas**
camdecmps.emission_view_all
camdecmpswks.emission_view_all

## Step #2:
Convert the following procedure in the SQL Server client database to Postgres.

**Procedure is in the ECMPS client SQL Server database**
- [ViewEmissions].[GridData_ALL]

**Procedure will only need to be in the camdecmpswks schemas**
camdecmpswks.refresh_emission_view_all

## Step #3:
Load view definition into the camdaux.dataset, camdaux.datatable, & camdaux.datacolumn tables

**Run these on the ECMPS Sql Server client database to get view names & columns**
select * from [Emissions].[Grid]
select * from [Emissions].[GridColumn] where grid_id = <enter id> order by column_order

**This will extract columns into a sql statement that can be placed into load scripts...**
select '(datatableId, ' + cast(column_order as varchar)  + ', ''' + lower(column_key) + ''', ''' + column_name + '''),'
from [Emissions].[GridColumn] where grid_id = <enter id> order by column_order

**Comment by Kyle-Herceg** [comment]
![image](https://user-images.githubusercontent.com/88667379/195452757-13db8352-c0a6-4f88-be4c-a45ca094d2d6.png)

These should be numerics -- TODO: Get With Dwayne and figure out why not
