### ISSUE TITLE
Emissions Module View: Heat Input CEMS #2

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4158]
Current Template Name: Heat Input CEMS
New Name: Hourly Heat Input CEMS
Order in dropdown: #2

## Step #1:
Convert the following table in the SQL Server client database to Postgres.

**Table is in the ECMPS client SQL Server database**
- [dbo].[EMISSION_VIEW_HICEMS]

**Table will need to be in the camdecmps and camdecmpswks schemas**
camdecmps.emission_view_hicems
camdecmpswks.emission_view_hicems

## Step #2:
Convert the following procedure in the SQL Server client database to Postgres.

**Procedure is in the ECMPS client SQL Server database**
- [ViewEmissions].[GridData_HICEMS]

**Procedure will only need to be in the camdecmpswks schemas**
camdecmpswks.refresh_emission_view_hicems

## Step #3:
Load view definition into the camdaux.dataset, camdaux.datatable, & camdaux.datacolumn tables

**Run these on the ECMPS Sql Server client database to get view names & columns**
select * from [Emissions].[Grid]
select * from [Emissions].[GridColumn] where grid_id = <enter id> order by column_order

**This will extract columns into a sql statement that can be placed into load scripts...**
select '(datatableId, ' + cast(column_order as varchar)  + ', ''' + lower(column_key) + ''', ''' + column_name + '''),'
from [Emissions].[GridColumn] where grid_id = <enter id> order by column_order

**Comment by acollad1** [comment]
@jwhitehead77 @MaeganWood64 Testing tickets for every emissions module view let me know if you have any questions:
•	Test: View Other Daily Tests Data
easey-ui #3704
•	Test: View Hourly CO2 CEMS Data
easey-ui #3878
•	Test: View Hourly NOx Rate CEMS Data
easey-ui #3882
•	Test: View Hourly Heat Input CEMS
easey-ui #3808
•	Test: View Hourly Combined Parameters
easey-ui #3810
•	Test: View Daily Calibration Data
easey-ui #3811
•	Test: View Hourly SO2 CEMS
easey-ui #3813
•	Test: View Hourly NOx Mass CEMS
easey-ui #3881
•	Test: View NSPS4T Summary Data
easey-ui #4267
•	Test: View Mass Oil Calculation Data
easey-ui #4266
•	Test: View CO2 Calculation Data
easey-ui #4265
•	Test: View LME Data
easey-ui #4264
•	Test: View Long-Term Fuel Flow Data
easey-ui #4263
•	Test: View CO2 Daily Fuel Sampling Data
easey-ui #4262
•	Test: View Moisture Data
easey-ui #4261
•	Test: View MATS Sorbent Data
easey-ui #4260
•	Test: View MATS Weekly Data
easey-ui #4259
•	Test: View MATS SO3 Data
easey-ui #4258
•	Test: View MATS HF Data
easey-ui #4257
•	Test: View MATS HCl Data
easey-ui #4256
•	Test: View MATS Hg Data
easey-ui #4255
•	Test: View NOx Appendix E -- Unit-Level Fuel Curve Data
easey-ui #4254
•	Test: View NOx Appendix E -- Individual Fuel Curve Data
easey-ui #4253
•	Test: View Hourly CO2 Appendix D Data
easey-ui #4252
•	Test: View Hourly SO2 Appendix D Data
easey-ui #4251
•	Test: View Hourly Heat Input Appendix D Data
easey-ui #4250
•	Test: View Hourly Heat Input for Unit/Stack
easey-ui #4249
