### ISSUE TITLE
ECMPS Beta: Issue with Export/Import for CS Configurations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4199]
Scenario: When a user exports a JSON file for a configuration and uses the same file to Import a MP, then we see the following 2 scenarios:

1. For regular configurations, user is able to export a JSON file and reimport it without any issues
2. For any Common Stack configurations when a user uses the exported file for Import, then as soon as the file is added/dragged to the modal, then an error pop's up 'Invalid JSON file format'

**Comment by mosesdeeCVP** [comment]
Bug Fixed
