### ISSUE TITLE
Add RATA data to Import endpoints

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4201]
Add the following data elements to the existing RATA IMPORT endpoints:

RATA Data
RATA Summary Data
RATA Run

**Comment by mosesdeeCVP** [comment]
![rataData-Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aa473506-1044-4dae-9b63-3ee7e150ae0f)

![rataSummaryData-Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/129d9483-0cb5-4c8f-a982-10fb4e833838)

![rataRunData-Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/abc9601c-4245-4462-9e82-2c9953b003d1)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC959](https://epacamd.testquality.com/project/11428/plan/26541/test/396844)
Test Passed
