### ISSUE TITLE
Refactor Selected View API Endpoint for Workspace

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4202]
As the ECMPS system, I need to be able to call a selected view from the list of Emissions module views and display, so that users are able to view only the data that need to see.

Given the Selected View API Endpoint is created
When a view is selected from the list of emissions view in the API
Then the data from that view will be returned 

- [x] Refactor API so it is using the query builder and accepts year and quarter together as the reporting period 

- [x] This work is specifically for workspace view with url emissions-mgmt/workspace/emissions/views/{viewCode}

- [x] Verify quarter and range validation is still working 

- [x] Add formatting validation for year and quarter YYYY Q1| YYYY Q2| YYYY Q3| YYYY Q4

- [x] Add Validation Error Message "reportingPeriod must be specified in this format YYYY Q1"

**Comment by sdhawan16** [comment]
Sample parameters: 
viewCode - dailycal
monitorPlanId - GO619-E38--25E39413591C41A0B396309D03A7A207
unitIds - 1
reporting quarter - 2021 Q1
