### ISSUE TITLE
Spike: Verify Database Lookup for Component ID, System ID, and Formula ID

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4204]
As an ECMPS system, when data is imported I need to be able to look up the primary keys of the table, so the import will be successful 

Given the database lookup for Component ID, System ID, and Forumla ID have been created
When data is imported into the ECMPS system 
Then system identifiers should be able to pass in and successfully imported

- [ ] Valid identifiers needed to be added by developers to the ticket for testing

- [ ] Need to be able to save the datasets with the valid identifiers 

- [ ] Need to compile a list of data types this applies to

Testing Information:
May need to use the workspace endpoint or get parameters from developer sync.

**Comment by eglove** [comment]
All imports checked for values:

DailyTestSummary
- monitoringSystemId
- componentId

DerivedHourlyValue
- formulaId
- monSysId
- monitoringSystemId

MatsDerivedHourlyValue
- formulaId

HourlyFuelFlow
- monitoringSystemId

HourlyGasFlowMeter
- componentId

HourlyParameterFuelFlow
- monitoringSystemId
- formulaId

MatsMonitorHourlyValue
- componentId
- monitoringSystemId

MonitorHourlyValue
- componentId
- monitoringSystemId

SamplingTrain
- componentId

SorbentTrap
- monitoringSystemId

WeeklyTestSummary
- componentId
