### ISSUE TITLE
Refactor Check Result Messages for Linearity Injection Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4206]
Placeholder to refactor all the checks for Linearity Injection that resulted from #4097 for QA-Cert Api 

Change how we get the error messages for  lineraity injection to use the check catalog service

The scope of this ticket includes doing regression testing on the lineraity injection modals to ensure error messages are displaying as expected.

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/fa8cf14d-9b73-4dab-9a0a-216053bc1d26/download](https://app.zenhub.com/files/287570343/fa8cf14d-9b73-4dab-9a0a-216053bc1d26/download)

**Comment by mosesdeeCVP** [comment]
LINEAR-19, LINEAR-20 and LINEAR-21
![LINEAR-19, LINEAR-20 and LINEAR-21.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3eb4d4d5-8a82-4295-967f-c79d11f7e84a)

**Comment by mosesdeeCVP** [comment]
Regression testing on Valid screen checks complete.
