### ISSUE TITLE
Refactor Check Result Messages for Location Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4207]
Placeholder to refactor all the checks for Location that resulted from #4097 for QA-Cert Api

Change how we get the error messages for location to use the check catalog service

Notes: Refactor the import checks, go through all of the logic to make sure everything is functioning correctly, and make the checks more efficient
-Loop each import check through Location data

**Comment by JanellC** [comment]
Need clarification on location checks
