### ISSUE TITLE
Refactor Check Result Messages for Rata Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4209]
Placeholder to refactor all the checks for RATA that resulted from #4097 for QA-Cert Api

Change how we get the error messages for Rata to use the check catalog service

The scope of this ticket includes doing regression testing on the RATA modals to ensure error messages are displaying as expected. This includes testing all of the RATA levels

**Comment by billmiller13** [comment]
[https://app.zenhub.com/files/287570343/971bcc33-1e56-47ec-acde-3be1ec4c1a13/download](https://app.zenhub.com/files/287570343/971bcc33-1e56-47ec-acde-3be1ec4c1a13/download)

Confirmation of Check Result Messages received via API

**Comment by JanellC** [comment]
Regression testing will be performed with ticket Test Only: Regression Testing Refactored Checks for RATA  #4612
