### ISSUE TITLE
Refactor Check Result Messages for Test Summary Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4210]
Placeholder to refactor all the checks for Test Summary that resulted from #4097 for QA-Cert Api

Change how we get the error messages for test summary to use the check catalog service 

The scope of this ticket includes doing regression testing on the ALL the test summary modals to ensure error messages are displaying as expected.

**Comment by vishnunavuluri** [comment]
[](url)

**Comment by vishnunavuluri** [comment]
[https://app.zenhub.com/files/287570343/5bd2e328-ce0d-49e5-b169-df73d1478e42/download](https://app.zenhub.com/files/287570343/5bd2e328-ce0d-49e5-b169-df73d1478e42/download)

**Comment by billmiller13** [comment]
[https://app.zenhub.com/files/287570343/74743f8b-b8cb-4ecb-a316-38ce1e0747a2/download](https://app.zenhub.com/files/287570343/74743f8b-b8cb-4ecb-a316-38ce1e0747a2/download)

Confirmation of Check Result Messages received via API

**Comment by JanellC** [comment]
Regression testing will be completed apart of Test Only: Refactor Check Result Messages for Test Summary Checks #4644
