### ISSUE TITLE
API Endpoint - Add Appendix E Heat Input From Oil Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4222]
API Endpoint - Add Appendix E Heat Input From Oil Data

Testing Reference Only:

Monitoring System ID 
Oil Mass
Oil GCV
Oil GCV Units of Measure Code
Oil Heat Input 
Oil Volume
Oil Volume Units of Measure Code
Oil Density
Oil Density Units of Measure Code

**Comment by mosesdeeCVP** [comment]
Test Case: [TC979](https://epacamd.testquality.com/project/11428/plan/27381/test/398465)
Test Passed
