### ISSUE TITLE
API Endpoint - Add  Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4223]
API Endpoint - Add Appendix E Heat Input From Gas Data

Testing Reference Only:
Monitoring System ID
Gas GCV
Gas Volume
Gas Heat Input

**Comment by mosesdeeCVP** [comment]
Test Case: [TC976](https://epacamd.testquality.com/project/11428/plan/27381/test/398462)

**Comment by mosesdeeCVP** [comment]
Test Passed
