### ISSUE TITLE
Issues with Revert to Official Record Button

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4227]
**Issue 1:**
Revert to Official Record button showing up for global-view 

Steps to Recreate: (Global-view)
- Navigate to the Select Configurations screen
- Open any one of the selected Configurations
- Review the screen to locate the 'Revert to Official Record' button
'Revert to Official Record' button should not be available in the Global-view

**Issue 2:**
Revert to Official Record button is showing up even when a MP is not checked-out

Steps to Recreate: (Workspace)
- Navigate to the Select Configurations screen
- Open (**NOT** Open & Checkout) any one of the selected Configurations
- Review the screen to locate the 'Revert to Official Record' button
'Revert to Official Record' button should not be available when the MP is not checked out

**Comment by JanellC** [comment]
Issue resolved 
Global View: 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/63ae4309-3955-4b26-81b8-6d9c7f4995c2)

Workspace 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e1779cf5-afb6-4cf0-84d5-9bb201cdd059)
