### ISSUE TITLE
Evaluate option available on MP's not checked out

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4228]
**Issue:**
Evaluate button is showing up even when a MP is not checked-out. 

**Steps to Recreate:** 
- Login to ECMPS
- Select and open a Configuration (**NOT** Open & Checkout)
- Review the options on the UI to locate Evaluation Status and the Evaluate button available next to it

When a MP is not checked out, the Evaluation Status should say 'Needs Evaluation' and the Evaluate option should not be available

**Comment by JanellC** [comment]
Issue resolved 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/59066c31-dad0-42aa-ac82-5d1b433c3738)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/cace708b-7efe-40b8-bc93-1de73d0c5cbe)
