### ISSUE TITLE
Filter by Keyword not working

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4229]
**Issue:**
Filter on the select Configurations screen is not working

Steps to recreate:
- Navigate to the Select Configurations screen (MP/QA)
- Locate the Filter, enter a Facility or ORIS Code and click Filter
- Doesn't yield any results

**Comment by JanellC** [comment]
Filter by keyword is working as expected 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8f0041cb-785c-4d90-8ae7-ddba46ec8ca8)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/54748eb9-e21a-4749-86bb-c263d38d5f29)
