### ISSUE TITLE
Issue with the Configurations Tab

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4230]
**Issue:**
Closing a facility tab doesn't seem to close it universally

Steps to reproduce:
- Login to ECMPS
- Select and open a configuration in one of the modules (MP/QA?Emissions)
- Review that the same configurations is open in another module
- Close the tab in one of the module
This action should have close the tab universally, however it is only closing it for the specific module

**Comment by mosesdeeCVP** [comment]
Bug Fixed
