### ISSUE TITLE
Issue with Check Out (Universal)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4232]
Issue:
A MP checked out in the MP module isn't automatically checked out in the other modules

Steps to recreate:
- Checkout a MP configuration in the MP module
- Navigate to the QA module, access the configuration that was just checkedout
- Configuration doesn't show that it is checked out

Note: Implementation would be across al 3 modules (MP, QA and Emissions). Since screens are not available for Emissions yet, we will keep the solution in redux for future implementation

**Comment by mosesdeeCVP** [comment]
- When MP is checked out using the Checkout Button the system does not update to edit/create mode.

- When QA is not checked out it is not showing the View format of the table, but showing the checkout version instead.

**Comment by mosesdeeCVP** [comment]
Bug Fixed
