### ISSUE TITLE
Issue with the Evaluation Refresh Logic

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4233]
**Issue:**
The Evaluation Status of Passed and Error shouldn't be included in the logic for the refresh timer. Currently the 2 statuses are added to the code

Resolution: 
Logic should only account for the In Queue (INQ) and WIP statuses when considering the refresh for Evaluation. For any other status, the timer shouldn't be refreshed

Testing:
Use Network traffic and review the refresh statuses where it should only happen when the Evaluation is in Progress or In Queue (Refresh should happen every 5 seconds). Refresh shouldn't happen every 5 seconds for Evaluation Status = Informational Message/Passed/Critical Errors

**Comment by mosesdeeCVP** [comment]
Bug Fixed
