### ISSUE TITLE
Issue with Test Reason Code and Test Result Code

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4234]
Issue:
Test Reason Code and Test Result Code display Select a value in Global-view when the user has left it blank

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e5606beb-ab0c-4e24-a307-b386dc4c46b5)

**Comment by mosesdeeCVP** [comment]
![4234 Issue with Test Reason Code and Test Result Code - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/61e71116-3e18-4e70-8288-7bacea99af9e)

**Comment by mosesdeeCVP** [comment]
![4234 Issue with Test Reason Code and Test Result Code - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9d0387cb-380e-40fc-846a-9b20d3a5a16f)

**Comment by mosesdeeCVP** [comment]
![4234 Issue with Test Reason Code and Test Result Code - 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2d923c23-c32a-468e-8291-d07349b0c7c8)

**Comment by mosesdeeCVP** [comment]
Bug fixed
