### ISSUE TITLE
Show Inactive not working

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4235]
Issue:

Show Inactive checkbox in MP which should bring up/display hidden records with an end date is not working. The checkbox doesn't get activated when clicked upon

Other observations: Issue seems to be across the application with checkboxes. For instance. Export functionality

**Comment by JanellC** [comment]
MP show inactive 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/442e6ef1-ad0b-4260-ba14-6177bd7caf79)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/5aaa80a9-26c4-43e5-8c23-f59fdb5d8e21)
