### ISSUE TITLE
Issue with HG Converter indicator radiobutton

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4236]
Issue:
The HG Converter Indicator radio button should have one of the radio buttons selected by default. Currently no selection is made

**Testing Reference:**
Radio buttons can be found on the following screens:
- Loads - Second Normal Indicator
- Location Attributes - Duct Indicator, Bypass Indicator
- System Component - Hg Converter Indicator
- Analyzer Range - Dual Range Indicator

**Comment by mosesdeeCVP** [comment]
Bug Fixed
