### ISSUE TITLE
Issue with Scrollbar

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4238]
Issue:
When a user selects the "Location Attributes and Relationships" they don't see scrollbar and cannot access all the data in the table

Steps to recreate:
1.  Open and checkout unit 2-1
2.  Select "Location Attributes and Relationships"
3.  Try to scroll table to see "End Date".

Note: Applicable to all MP sections where the scroll bar is available (Spans, Location Attributes etc)

**Comment by JanellC** [comment]
Issuee resolved 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/24274bf0-f8c6-4055-82f7-2a9c158570e4)
