### ISSUE TITLE
Bug: Remove Rata Air emissions, Rata Flow, and Rata Traverse record

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4239]
## Test Case
[TC922 ](https://epacamd.testquality.com/project/11428/plan/26541/test/392970)

## Steps to Reproduce
1.Log into ECMPS 
2.Go to the QA module
3.Select Glen Lynn (3776) configuration 51  
4.Select Rata as a Test Type 
5. Add an air emissions record so that the test has more than one air emissons record 
6. Remove one air emissions record

When a user removes one air emissions record then the remaning air emissions records become blank. This issue needs to be checked for other rata levels as well since the issue was also spotted for rata flow.

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=12036)
- Test [Remove Air Emission Data](https://web.testquality.com/site/epacamd/project/11428/runs/168979?resultId=2969358) in Run [Remove Air Emission Data](https://web.testquality.com/site/epacamd/project/11428/runs/168979) (linked to Cycle [RATA Data- QA & Certifications](https://web.testquality.com/site/epacamd/project/11428/cycles/26541)).

**Comment by mosesdeeCVP** [comment]
Original Ticket:  [Remove Flow RATA Run Data #2963](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2963)

**Comment by JanellC** [comment]
Issue resolved
