### ISSUE TITLE
Bug: Blank screen when user navigates from one Test Type Code to Another

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4240]
**Issue:**
When a user is working on a Test Type in Test Data module, expands various data sections and wishes to navigate to a different Test Type Group, then the system crashes an displays a blank screen

Note: This issue is applicable to both the Global view and the Workspace

**Steps to Recreate:**
1. Log in to ECMPS and access the Test Data Module
2. Select and checkout a Configuration and select a Test Type Group with nesting
3. Click on + to expand the Test record sections
4. Now click on the Test Type Group dropdown and select a different Test Type
You will see that the screen turns blank at this point

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
Bug resolved in global and workspace
