### ISSUE TITLE
Configuration Number not being displayed on Tabs

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4242]
Issue:
Configuration # doesn't display in the tab, it displays the ORIS code. Select any configuration and the tab will not display the Configuration #. It is only displaying the ORIS code

Note: When there is a number tagged to a name, we display it as a Name and then we display the Configuration #

**Comment by mosesdeeCVP** [comment]
![4242 Configuration Number not being displayed on Tabs.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b8f8da09-3a16-4a90-b23b-bad238d88a4b)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
