### ISSUE TITLE
Error messages being retained

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4243]
**Issue:**
When an error message/validation is displayed and the user fixes the error, the message doesn't go away automatically. It has to be manually closed out by the user. 

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c013677c-66e9-4f63-95d0-519d63b00433)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
