### ISSUE TITLE
Issue with Begin/Start Hour and End Time/Hour when it is 0

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4244]
The scope of this ticket is for QA/MP

**Issue 1:**
- Issue with the Begin Date and Hour and End Time/Hour when it is 0

Steps to recreate:
- Navigate to Select Configurations screen and select and open a Configuration
- For MP, select Defaults from the Sections dropdown and for QA, select and review the Test Data section for RATA/Linearity Summary etc
- Locate any MP record with StartDate/Hour of o and review the same once you open the modal
- You will notice that 0 doesn't get populated in the modal, but any other number works as expected

Repeat the same steps for QA

Notes: Any hour with a "0" does not appear in the modals.  If you look at defaults the begin times appear in the main table but don't appear in the hour field when you open the modal.  This appears to be a problem across data elements with "hours" when the value is 0 not just defaults. And the functionality works fine when the value is any other number except 0.

**Issue 2: End Date/Hour**
ORIS 2511 unit 10.  Try to edit and save the current load record.  If user selects hour 0 the record doesn't save and gives no indication of the failure. Select hour 2 and the record updates correctly.  

Steps to recreate:
- Open any Configuration from the Select Configurations screen for Test Summary Data
- Checkout the Configuration and select RATA/Linearity Summary/Appendix E from the Test Type Group dropdown
- Click on Add Test Data and enter all the needed information and enter 0 for the End Hour
- Click Save and Close
You will notice that the data doesn't get saved but the system also doesn't display any error messages to inform the user as to what needs to be updated

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by vishnunavuluri** [comment]
10/13/2022: Happening again in beta where Start Time with a value of 0 is not showing up in the modals

**Comment by mosesdeeCVP** [comment]
Bug fixed. Cannot find any instances where the 0 is not showing up in the modal
