### ISSUE TITLE
Location ID missing from View Endpoint - Location Attributes and Relationships

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4245]
**Issue:**
{locid} path param is missing for the Official view - GET for Location Attributes and Relationships. See below:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/eef960b9-1e3f-4a4b-b702-428811802047)

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
![locId Relationships.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3eff8ec8-82d6-421b-8041-ea607645bb5d)
