### ISSUE TITLE
Issue with Check out and Refresh

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4247]
Issue:
When a user checks out a config, does a browser refresh, and opens the configuration again - then the user does not see the actions to add, edit, remove data etc

Steps to recreate:
"1. Log in to BETA env 
2. Open the following config: Glen lyn (3776) 51 
3. Check out config 51 
4. Refresh the browser 
5. Open Config 51

**Comment by vishnunavuluri** [comment]
Old Issue:
**Issue:**
Create and Edit options shouldn't be available for the users when the MP is not checked out. However, in the dev environment because the actions (Check out/Check back in) are not reflected automatically i.e. user has to manually refresh the screen after taking an action...they currently see the options when a MP is checked back in. And vice-versa

Steps to recreate:
- Check out a MP
- Review and make sure that you see View/Edit and Create options
- Check the MP back in
- Review the options available on the screen. You will see as below:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/cb5e2daf-5e5c-40e6-a783-31f2e3f248d5)

- Now refresh the screen and review if the same options are available. You will see that the user doesn't have View/Edit and Create options now and only View is available
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/85a9a525-7f81-4270-b025-35e22fe0c1e1)

And you can see the same happening with Check back in

**Comment by mosesdeeCVP** [comment]
Bug Fixed
