### ISSUE TITLE
Test Only: Add/Edit an air emissions record with out checking it out 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4248]
## Steps to Reproduce

**ADD**
1. Log in to ecmps 
2. Go to the QA module 
3. Select  Glen lyn (3776) configuration 51
4. Select Rata as a test type 
5. Attempt to add multiple air emissions records 

The system does not consistenly add an air emissions reocrd.  The reocrd will not be added and the system does not display an error message on why the record was not addded 

**Edit**
1. Log in to ecmps 
2. Go to the QA module 
3. Select  Glen lyn (3776) configuration 51
4. Select Rata as a test type 
5. Attempt to edit an air emissions record 

The edits are not saved. 

The system does not save edits or add records if a record is not checked out. Need to have discussion on this functionality. Should the add/edit/ remove buttons be hidden until a vconfiguration is checked out?

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=12049)
- Test [Global 'View' and Workspace 'Add': Air Emissions Testing Data](https://web.testquality.com/site/epacamd/project/11428/runs/169110?resultId=2971210) in Run [Global 'View' and Workspace 'Add': Air Emissions Testing Data](https://web.testquality.com/site/epacamd/project/11428/runs/169110) (linked to Cycle [RATA Data- QA & Certifications](https://web.testquality.com/site/epacamd/project/11428/cycles/26541)).
- Test [Edit Air Emissions Testing Data](https://web.testquality.com/site/epacamd/project/11428/runs/169142?resultId=2971622) in Run [Edit Air Emissions Testing Data](https://web.testquality.com/site/epacamd/project/11428/runs/169142) (linked to Cycle [RATA Data- QA & Certifications](https://web.testquality.com/site/epacamd/project/11428/cycles/26541)).

**Comment by vishnunavuluri** [comment]
Working as expected:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/31a6393b-f97f-4cb8-8978-b7b49742e7e4)
