### ISSUE TITLE
Bug: Issues with Rata Flow view and Edit 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4268]
## Test Case
Test Case: [TC923](https://epacamd.testquality.com/project/11428/plan/26541/test/392972)

## Steps to Reproduce

See: Global 'View' and Workspace 'Add': Flow RATA Run Data #2960  and Edit Flow RATA Run Data #2962 for orginial requirements 

**Issue 1:**  Dry Molecular is a date pickers instead of a text box

1. Log in to ECMPS 
2. Navgate to ECMPS under the QA module
3. Select Rata as a test type 
3.  Add a flow rata record 

When the modal is display then Dry Molecular is a date pickers instead of a text box

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8db7ee55-8c2a-47db-85a1-851b75515b26)

**Issue 2:**  Rata Flow view functionaility does not work 

1. Navgate to ECMPS under the QA module
2. Select Rata as a test type 
3.  Find the following configration: 
Facility: New Haven Harbor
Oris: 6156
Locations: NHB1
Test Number: BN4-Q1-2013-001 

4. Expand a Rata run record 
5. View a flow rata record 

The system does not display a modal with all of the flow rata feilds 

**Issue 3: Stack Static Pressure (Text) does not save**

1. Log into to ECMPS
2. Go to QA module 
3. Select RATA 
4. Add a flow rata record and save the changes 

The system does not save the input for  Stack Static Pressure and the data table displays an empty feild

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=12076)
- Test [Global 'View' and Workspace 'Add': Flow RATA Run Data](https://web.testquality.com/site/epacamd/project/11428/runs/169389?resultId=2975974) in Run [Global 'View' and Workspace 'Add': Flow RATA Run Data](https://web.testquality.com/site/epacamd/project/11428/runs/169389) (linked to Cycle [RATA Data- QA & Certifications](https://web.testquality.com/site/epacamd/project/11428/cycles/26541)).

**Comment by mosesdeeCVP** [comment]
Original ticket: [Edit Flow RATA Run Data#2962](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2962)

**Comment by mosesdeeCVP** [comment]
Issue 1 - Fixed
Issue 2 - Fixed
Issue 3 - Fixed
