### ISSUE TITLE
Bug: Rata Traverse Improperly Displayed 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4269]
## Test Case
Test Case: [TC931 ](https://epacamd.testquality.com/project/11428/plan/26541/test/393059)

## Steps to Reproduce

See Global 'View' and Workspace 'Add': RATA Traverse Data #2955 for original requirements 

**Issue 1: Rata Traverse improperly indented**

1. Navigate to ECMPS under the QA module
2. Select Rata as a test type
3. Find the following configration:
Facility: New Haven Harbor
Oris: 6156
Locations: NHB1
Test Number: BN4-Q1-2013-001

4. Expand a flow record

Traverse is indented under flow. According to the wireframes. Traverse and flow data should be on the same level. This issue occurs for the workspace as well.

**ECMPS system- global** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/06a2389c-aedf-4ba9-9c64-8729468925a1)

**ECMPS system- workspace** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/615be4eb-a63c-4b74-8652-19e2310d46d7)

**Wireframes**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/833b4af4-2db4-462a-8902-ec44488d0294)

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=12077)
- Test [Global 'View' and Workspace 'Add': RATA Traverse Data](https://web.testquality.com/site/epacamd/project/11428/runs/169391?resultId=2976093) in Run [Global 'View' and Workspace 'Add': RATA Traverse Data](https://web.testquality.com/site/epacamd/project/11428/runs/169391) (linked to Cycle [RATA Data- QA & Certifications](https://web.testquality.com/site/epacamd/project/11428/cycles/26541)).

**Comment by NadiaJL** [comment]
RATA-Workspace - FLOW/TRAVERSE - Desktop 1024
Xd Prototype: https://xd.adobe.com/view/55fdae85-2dcd-4c1b-b7e0-a65ac3f6b392-00ae/

inVision Board: https://projects.invisionapp.com/freehand/document/SrHrFhGQ3?zoomToItems=Y2w0eDZiYjVkMDAwazNiNnh1YWhobzZkaw%3D%3D

**Comment by esaber76** [comment]
Confirm if this is still an issue on dev and stg.

**Comment by lgiannini1** [comment]
Able to reproduce issue by viewing official/workspace Flow RATA for ORIS 47, unit 5 test number 400-39 on dev and tst. RATA Traverse Data is indented under RATA Flow Run Data.


![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/63416419/94eb11e3-a18b-4734-b52a-a0c15983509d)

**Comment by annalbrecht** [comment]
The structure was correct originally. The "Flow" title was wrong but has since been corrected (see Lane's screenshot). So, this is no longer an issue.
