### ISSUE TITLE
QA & Cert: RATA 16 (Reference Method Code Valid)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4270]
The scope of this ticket is to address the following RATA Summary DTO Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [ ] RATA-16 - Reference Method Code Valid (Results C, D and E)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1230](https://epacamd.testquality.com/project/11428/plan/26541/test/431585)
