### ISSUE TITLE
Test Only: Issue with Test Result Code for Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4281]
**Issue:**

When adding new Test Data or editing existing Test Data, the Test Result Code doesn't display any values to select in spite of selecting a value for the Test Reason Code. And user is not able to add Test Data as Test Result Code is needed for it. This also prevents a user from updating Test Data. See below:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7e6842bf-eb5f-4d67-a708-243c133fc49b)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
