### ISSUE TITLE
Enable Add/Edit functionality upon Check out for QA Module

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4283]
Users should check out a configuration in order to be able to Add/Edit QA data (linearity Summary/RATA)

The UI should replicate the View functionality from the global view when the Configuration is not checked out

List of actions/options that are not available when not checked out

**Comment by JanellC** [comment]
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/864fb000-1312-4832-89d0-bbfa5f17dc44)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/957c4683-1672-43c0-9fce-dd4461ff91fb)

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1a189d00-ca59-4d1c-a2fb-9b77637c9e81)

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1e4a9084-e554-4a67-bc0c-a5c7e4116299)
