### ISSUE TITLE
Update editable fields for System Component (Backend)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4285]
Manufacturer, Model or Version, Serial Number and dates are the only fields that should be editable. All other fields for System Component are read-only

**Comment by JanellC** [comment]
Updates addressed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/19b7d8f0-6f4e-4644-8274-27fce488492f)
