### ISSUE TITLE
Bulk Data Files: 508 Scan Issues

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4286]
- [x] The tagging for the table headers should reflect their function as sort buttons. In addition, current sort state is not conveyed correctly. A visual sort indicator is displayed on mouseover (but not on focus). These indicators do not reflect the current sort state of the column but rather the most recent sort used (defaults to ascending if no sort has been used.) Even when not visible, these are misread by JAWS - the software will announce that an unsorted column is "sorted ascending (or descending)". Adding the aria -label for column header to reflect sort status. 

- [x] The cells in the Bulk Data table lack programmatic associations with their corresponding column headers. Ensure that the same data file is used for the Bulk Data Files Page as for the rest of the application. (Document fix to be used for ECMPS as well)

**Comment by aprematta** [comment]
Testing complete, code causing the parsing error has been removed

**Comment by aprematta** [comment]
This looks good to me...... I asked Travis to have Brian take a look to see if it will pass his review. Closing ticket for now.
