### ISSUE TITLE
Custom Data Download: 508 Issues

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4287]
- [x] Do not use "here" as link text (caveats file download). Link text should describe the purpose of the link. Change to "Download Data Caveats File" With Data Caveats Filw Underlined. (Travis will handle through content docs) 

- [x] There is an aria-sort tag associated with the column headers, but they do not refresh when the column is sorted and continue to read as sort="none". div[role=column-header] needs to be set when the aria sort label changes

- [x] The button to change the data types is programmatically labelled only as "Change" - this is not sufficiently descriptive. Add aria-label="change-data-type" to Chagne Button

- [x] After the data types are applied, the form refreshes to display the filter selections and the focus shifts to the top of the page. Focus should instead shift to the “Change” button for data type

- [x] current sort state is not conveyed correctly. A visual sort indicator is displayed on mouseover (but not on focus). These indicators do not reflect the current sort state of the column but rather the most recent sort used (defaults to ascending if no sort has been used.) Even when not visible, these are misread by JAWS - the software will announce that an unsorted column is "sorted ascending (or descending)". (Should be covered by the aria label fixes for the header columns)  (Need to get further clarification for fix)

**Comment by aprematta** [comment]
This one for the sort is a little more complicated because the sort button is a separate control from the columnheader, I'm going to ask travis to have brian review as well.
