### ISSUE TITLE
Identify tables and data relationships for Monitoring Plan data check engine process

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#429]
## Task
- [x] Identify tables and data relationships to understand check engine process

## Outcomes
List of tables, schemas, stored procedures, data relationships

**Comment by SimeraHailu** [comment]
https://teams.microsoft.com/_#/files/TheEmissioners?threadId=19%3A56d336e3060849efa0557d379b78d9ca%40thread.skype&ctx=channel&context=Validation%2520Check%2520Engine%2520Analysis&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FTheEmissioners%252FValidation%2520Check%2520Engine%2520Analysis
