### ISSUE TITLE
Implement Emissions Module Export Button Functionality in Main UI

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4293]
As an ECMPS user, I want to be able to export emissions data using the export button in the emissions module so that I can view data outside of the application.

Given a user has navigated to the main emissions module UI
When the user clicks on the export button
Then the emissions file for the year and quarter and the configurations they selected will be exported as a JSON file

- [ ] This functionality should be available in the logged-in view and logged-out view of the UI in the emissions module

**Comment by NadiaJL** [comment]
Emissions Official(Global View) inVision board: https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w3ZzlxaXVlMDBzeDNiN28yYmlxbDJ0OA%3D%3D

Web browser: Official(Global) View - Emissions - V1.0 - Desktop 1024
Xd Prototype: https://xd.adobe.com/view/58ace728-03be-44d6-a29b-f7bf23fef4b0-0dff/

**Comment by AmandaMNelson** [comment]
TC failed; the export does not work when logged in. See bug ticket #4423 
![image](https://user-images.githubusercontent.com/110929222/197913153-320014be-6474-4846-a767-ac1e950acc05.png)
