### ISSUE TITLE
Spike: Testing Automation Preparation 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4295]
- [x] Take Udemy course on testing automation specifically JAVA

- [x] Set up any applicable software needed and get familiar 

- [x] Shadowing and knowledge transfer for front end and API work

**Comment by AmandaMNelson** [comment]
Software to Install:
- Visual Studio
- Java 8
- Maven
- ChromeDriver
- IntelliJ
- ChroPath

Shadowed Maegan Wood to cover API testing, and an intro to UI testing. Will need to follow up once I have everything installed.

Courses:
- Learn JavaScript (https://www.youtube.com/watch?v=PkZNo7MFNFg&list=PLWKjhJtqVAblfum5WiQblKPwIbqYXkDoC&index=5)
- Rest API Testing (https://www.udemy.com/course/rest-api-automation-testing-rest-assured/)
- Selenium WebDriver (https://www.udemy.com/course/selenium-real-time-examplesinterview-questions/)
