### ISSUE TITLE
Flow To Load Check data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4296]
## Testing 
Test Case: [TC1044](https://epacamd.testquality.com/project/11428/plan/27645/test/403049)
Tester: @JanellC

**Comment by JanellC** [comment]
Test Case TC1044 passed 
Global
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/91885f0c-051c-4a99-be8e-a5215694264d)

Workspace
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/28de6816-dd01-4e89-bd8a-4355d85427cd)
