### ISSUE TITLE
Add  Flow To Load Check data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4297]

**Comment by mosesdeeCVP** [comment]
Flow To Load Check data elements to Import Endpoint

![Flow To Load Check data elements to Import Endpoint .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/632e7c74-29ab-4fd6-964d-c8a42ff2a077)

**Comment by mosesdeeCVP** [comment]
Test Case:

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1048](https://epacamd.testquality.com/project/11428/plan/27645/test/403060)
Test Passed
