### ISSUE TITLE
Add Calibration Injection data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4302]
Scope: Implement export for both the Official and the workspace views

**Comment by mosesdeeCVP** [comment]
Calibration Injection data elements to Export Endpoint - Official

![Calibration Injection data elements to Export Endpoint - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/07102f06-8a3c-4ff2-930c-68877e75cf1a)

**Comment by mosesdeeCVP** [comment]
Calibration Injection data elements to Export Endpoint - Workspace

![Calibration Injection data elements to Export Endpoint - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b81a74d2-214e-4af3-87c6-4388f44e92c9)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1046](https://epacamd.testquality.com/project/11428/plan/27529/test/403058)
Test Passed
