### ISSUE TITLE
Add Calibration Injection data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4303]

**Comment by mosesdeeCVP** [comment]
![Calibration Injection data elements to Import Endpoint.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a044c750-9625-4fb5-9c81-6214ae044152)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1047](https://epacamd.testquality.com/project/11428/plan/27529/test/403059)
Test Passed
