### ISSUE TITLE
API Endpoint - Remove Calibration Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4304]
Create API Endpoint to remove/delete Calibration Injection Data

**Comment by mosesdeeCVP** [comment]
![4304 API Endpoint - Remove Calibration Injection Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ce857e4c-bebd-4235-aac1-af7e67d04702)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1024](https://epacamd.testquality.com/project/11428/plan/27529/test/401528)
Test Passed
