### ISSUE TITLE
Add Flow To Load Reference data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4305]

**Comment by mosesdeeCVP** [comment]
Flow To Load Reference data elements to Import Endpoint

![4305 Add Flow To Load Reference data elements to Import Endpoint.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/074ddb0e-2e57-4413-98ac-4f4b5b0523e6)

**Comment by mosesdeeCVP** [comment]
Will recheck once Export is working so I can confirm Data is being updated

https://api.epa.gov/easey/dev/qa-certification-mgmt/export?facilityId=26&stackPipeIds=CS0CAN&testTypeCodes=F2LREF

https://api.epa.gov/easey/dev/qa-certification-mgmt/export?facilityId=26&stackPipeIds=CS0CAN&testTypeCodes=F2LREF

**Comment by mosesdeeCVP** [comment]
{
  "orisCode": "26",
  "testSummaryData": [
    {
      "id": "TWCORNEL5-1F1A6E90547243AE8706BB7FEA4F30F4",
      "locationId": "81",
      "stackPipeId": "CS0CAN",
      "unitId": null,
      "testTypeCode": "F2LREF",
      "monitoringSystemID": "CA4",
      "componentID": null,
      "spanScaleCode": null,
      "testNumber": "201910010000CA4S",
      "testReasonCode": null,
      "testDescription": null,
      "testResultCode": null,
      "calculatedTestResultCode": "PASSED",
      "beginDate": null,
      "beginHour": null,
      "beginMinute": null,
      "endDate": "2020-01-01",
      "endHour": 1,
      "endMinute": 2,
      "gracePeriodIndicator": null,
      "calculatedGracePeriodIndicator": null,
      "year": null,
      "quarter": null,
      "testComment": null,
      "injectionProtocolCode": null,
      "calculatedSpanValue": null,
      "evalStatusCode": null,
      "userId": "bvick",
      "addDate": "10/25/2019, 1:09:24 PM",
      "updateDate": null,
      "reportPeriodId": 107,
      "flowToLoadReferenceData": [
        {          
  "id": "c97c99fa-7f34-4c90-8733-cb094b509414",
  "testSumId": "TWCORNEL5-1F1A6E90547243AE8706BB7FEA4F30F4",
  "rataTestNumber": "1",
  "operatingLevelCode": "H",
  "averageGrossUnitLoad": 0,
  "averageReferenceMethodFlow": 789,
  "referenceFlowToLoadRatio": 0,
  "averageHourlyHeatInputRate": 0,
  "referenceGrossHeatRate": 0,
  "calculatedSeparateReferenceIndicator": 0
        }
      ]
    }
   ]
  }

**Comment by mosesdeeCVP** [comment]
Updates work

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1056](https://epacamd.testquality.com/project/11428/plan/27145/test/403514)
Test Passed
