### ISSUE TITLE
Incorrect End Date Validation

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4335]
Issue:
When a user is updating existing Test Data or adding new Test Data, the system throws a validation error or check that the end year is not applicable even when the end year is within the applicable range of 1993-2022. This is happening even when the End Date is correct or within the specified range. See below for more information and screenshots:

Steps to recreate:
1. Log in to ecmps
2. Go to the QA module
3. Select Glen lyn (3776) configuration 51
4. Select Rata as a test type
5. Select a Test Data record you wish to update, make any updates and keep the End Date as is
6. Click Save and Close. Review the validation that is displayed about the Year

Scenario 2:
1. Log in to ecmps
2. Go to the QA module
3. Select Glen lyn (3776) configuration 51
4. Select Rata as a test type
5. Add a Test Data record. Make sure you add information correctly
6. Click Save and Close. Review the validation that is displayed about the Year

Screenshots:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3e90e294-4246-4677-8489-dd663bf442d9)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e2a0b597-da7f-4132-b2b7-2bc3c2d8f736)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/e75995f9-a3ef-4c45-9485-432b79924291)

![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/5a829162-d1fe-4662-8219-c7fc02dbcbd5)


backend issue. endDate in swagger is in correct format, but it is not picking up the payload

**Comment by mosesdeeCVP** [comment]
Bug Fixed
