### ISSUE TITLE
MP: Dropdowns not presenting any options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4341]
**Issue:** 
For many of the dropdown fields in MP and QA Modules, when a user clicks on the dropdown, it doesn't display any of the options that should be available. Some of such fields are Substitute Data Approach, Parameter (MATS), Units of Measure (Default)

Steps to recreate:
1. Login to the beta
2. Select a configuration, and navigate to MP Workspace
3. Select Method from the parameter dropdown
4. Review the dropdown options for Substitute Data Approach  
You will see that the dropdown is empty and shows none of the options

**Comment by mosesdeeCVP** [comment]
Bug fixed
