### ISSUE TITLE
MP: View Modals showing Select a Value for dropdowns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4342]
**Issue:**
When a user is reviewing data for MP/QA in the global view (View functionality), many of the dropdown fields display a value of Select a value. This is not correct

Steps to recreate:
1. Access ECMPS in beta
2. Navigate to Select Configurations 
3. After you select and navigate to a configuration, click on Defaults/Methods from the sections dropdown
4. Review the information by clicking on the View option for data

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4dbbdeb5-c7a7-4ba8-8904-729a595dcd8a)

**Comment by JanellC** [comment]
QA Dropdown is displaying a value instead of "Select a value" In dev. Needs to be retested once deployed to beta 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d2a2de78-625e-4c51-9517-8059c3c47575)

**Comment by mosesdeeCVP** [comment]
Bug Fixed and in Beta
