### ISSUE TITLE
QA: Issue with dropdowns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4343]
**Issue 1 - Global-view:** 
When a user is reviewing QA test data (View) in the global view, some of the dropdown fields display the value as 'Select a value'. It either needs to display the actual value or be left blank if the user chose to leave it blank. See below for the reference screenshot:

**Issue 2 - Workspace:** 
When a user wishes to select a value for a field with dropdown options, the dropdown is empty and not displaying any options.

**Comment by mosesdeeCVP** [comment]
Bug fixed
