### ISSUE TITLE
Determine Strategy to Store SonarCloud code scan rules in EPA environment 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#435]
Investigate possible ways to export rules from SonarCloud

Will need to be completed for ATO. Consider in early PI 3. 

Need security requirements - who requires this information?
Sonar Way code scan rules are public here:
https://sonarcloud.io/organizations/us-epa-camd/quality_profiles

**Comment by MaeganWood64** [comment]
Overcome by events, no longer needed
