### ISSUE TITLE
Update Arch. Diagrams to Reflect Data Migration Plan 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#437]
- [ ] Include Informatica server 
- [ ] Reflect SSH connection to Cloud.gov 

Jason to review Mike's updated architecture diagram

**Comment by david-cvp** [comment]
Blocked because we are waiting on the NCC/Informatica teams to determine whether we will have either
- A standalone VM to establish SSH tunnel, OR
- SSH tunnel established from the Informatica server

**Comment by david-cvp** [comment]
On 12/17 Mike said that we are using the SSH tunnel established from the Informatica server

**Comment by david-cvp** [comment]
Need this for

- ADC team
- ATO process
