### ISSUE TITLE
Unable to create, edit or remove QA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4372]
Issue:
Can not edit, add, or remove a QA record 

Steps to recreate:
1. Log into BETA 
2. Check out config Glen Lyn (3776) 51
3. Select Lineraity or Rata as a test type 
4. Attempt to add a record, remove an existing record, or edit a record 

The system doe not maintain the changes and displays the following error message: Request failed with status code 500

Other scenarios: When a user adds new Test Data and clicks, Save and Close - the modal closes but no new Test Data is added and no errors/validations are displayed

**Comment by billmiller13** [comment]
Test Summary, Linearity Summary, and Protocol Gas added

![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/abeec142-1aef-4c48-bdb4-bd7ebdf610be)

**Comment by billmiller13** [comment]
Test Summary, Linearity Summary, and Protocol Gas -- all showing edited values

![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/be90715a-154e-46d3-a70e-72799b8b43f8)

**Comment by billmiller13** [comment]
Linearity Summary and Protocol Gas records removed -- but had to close and re-open Glen Lyn (51) tab to see them removed from the Test Summary

![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/e4e3e0f8-8081-4c2f-be2f-58ecd89e3c77)

**Comment by mosesdeeCVP** [comment]
Bug fixed for Beta
