### ISSUE TITLE
Rectangular Duct WAFs: No Start Time & End Time

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4373]
Issue:
The rectangular Duct WAFs section displays the Start Time and End Time in the grid, but when you open the Create/Edit/View modal, there is no field to enter this data

Steps to recreate:
1. Login to ECMPS
2. Select a Configuration in the MP module
3. Checkout a configuration, navigate to the Sections dropdown and select Rectangular Duct WAFs
4. Review the information displayed and see that the grid has Begin Date and Time and End Date and Time
5. Click View/Edit and see that the 2 hour/time fields are missing
This is also applicable to Create

**Comment by JanellC** [comment]
Issue Resolved in Dev. Needs to be checked once deployed to BETA @vishnunavuluri @jwhitehead77 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9fc0bb49-85b6-4289-84a4-60f246b8025c)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/956e75c3-a8bd-41e0-ac6b-f6c4e12ed41f)

**Comment by mosesdeeCVP** [comment]
Bug Fixed and in Beta

**Comment by mosesdeeCVP** [comment]
![Duct Waf Time Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a87b01cd-4364-4a6f-9bd9-49711bb2c82a)
