### ISSUE TITLE
QA: Able to edit data for a Congiration checked-ou by a different User

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4374]
Issue:
Can edit data for  a config that is already checked out by another user 

Steps to recreate:
1. Login to beta
2. Go to the QA module 
3. Open a configuration that is already checked out by another user

The system displays the ability to add, edit, evaluate , remove, revert to offical, import, and evalute. This should not be displayed if the config is checked out by another user. The records should be view only

**Comment by mosesdeeCVP** [comment]
Bug Fixed
