### ISSUE TITLE
MP: Relationships not showing up in the UI

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4375]
Issue:

When a user selects Location Attributes and Relationships data from the Sections dropdown in the MP module, the Relationships data is not displayed even for the configurations when it is available

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/fe7a3ef5-dfe6-422b-83d4-d45f142404b7)

**Comment by mosesdeeCVP** [comment]
![Relationships Working in UI.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d2c5181a-a954-4a7d-8911-659740b47e1c)

**Comment by mosesdeeCVP** [comment]
UI bug fixed
