### ISSUE TITLE
Implement Responsiveness of Emissions Main UI Layout for Desktop Sizes 1024, 1200, 1400

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4376]
As an ECMPs user, I want to be able to see the main emissions UI layout in the Emissions Data section so that I can ensure that I am viewing the relevant data I need to support program goals.

Given a user has navigated to the daily emissions section of the emissions module
When they open up the daily emissions page UI 
They will see the main emissions module layout in 1024, 1200, 1400 

- [ ] View Template dropdown will be populated by a call to the List of Views Emissions Module API 

 Emissions Module UI Layout 1024
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w3NjlxZnI1MDBiNzNiN2YwbWFxZXJxdA%3D%3D

Emissions Module UI Layout 1200
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w4dWM0cW9qMDA0azNiNnlrOHJ0Y21jYQ%3D%3D

Emissions Module UI Layout 1400
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w4dDB3Z2d2MDA0dTNiNzVqMmJoOHVsaA%3D%3D

Emissions Module UI Layout with dropdown examples 
https://projects.invisionapp.com/freehand/document/4upRFvdZD?zoomToItems=Y2w3OTlya3BrMDAxbjNiN295bjgyNjdhag%3D%3D

https://xd.adobe.com/view/28ee8c47-fbcd-42c7-96de-c9ab2efd7e13-7dbd/

**Comment by fanwari1** [comment]
To test this ticket, you can go to the page by 
1. Logging in
2. Going to emissions on the side menu
3. Choosing a configuration and doing "open & checkout" (I usually just use barry) 
4. Click on the tab that opened and you should be able to see the layout.

To test the responsiveness, you can resize your browser window but to get some more precise testing at the sizes mentioned in the ticket, you can:
1. At the page, right click and click "Inspect Element"
2. Click on the marked button:
3. 
![image](https://user-images.githubusercontent.com/102816236/197608248-d30b26ad-d3b3-4362-bd40-c7a631fc16e6.png)
4. When you click there you should be viewing the page in any size you want. The sizes handled in this ticket are 1024, 1200, and 1400.
5. You can change the values here:
![image](https://user-images.githubusercontent.com/102816236/197608886-9c4b8edf-abf4-400d-8d44-531f2faa1a8b.png)

**Comment by acollad1** [comment]
@aprematta Ticket 4376 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071
