### ISSUE TITLE
Assign the appropriate stackPipe or unitId 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4377]
**Issue:**
When a user is updating existing Test Data or adding new Test Data, the system throws a validation error or check that the end year is not applicable even when the end year is within the applicable range of 1993-2022. This is happening even when the End Date is correct or within the specified range. 

Upon investigation, it was discovered that when creating a test summary record, the payload should have the appropriate stackPipe or unitId assigned. However it is currently only assigning unitId even though the location is a stackPipeId

**Comment by mosesdeeCVP** [comment]
Bug Fixed
