### ISSUE TITLE
API: Create Summary Value Emissions Data Endpoint 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4378]
As an ERG team member, I need to be able to access summary emissions data from the summary value table in order to support CBS, CSA, and the CAMD Oracle Jobs.

Given an Emissions Summary Value Endpoint is created
When the API calls the summary value endpoint 
Then summary Value emissions data based on a quarter range and ORIS codes is returned

Endpoint Parameters:
- ORIS Code 
- Begin Year 
- Begin Quarter 
- End Year 
- End Quarter 

This will only be for the official camdecmps schema and the url will be
/emissions-mgmt/emissions/summary-values

**Comment by eglove** [comment]
Adds endpoint: /emissions-mgmt/emissions/summary-values

Multiple ORIS codes can be specified in parameters:

?beginYear=2019&beginQuarter=1&endYear=2019&endQuarter=4&orisCode=3&orisCode=10

Returns list of summary values given a ORIS code and date range. The table below shows combinations that have summary values. For example, the ORIS code 3, should have summary values between beginYear 2019, beginQuarter 1 and endYear 2022, endQuarter 1 (and any combination of dates between those):

Year, Quarter, ORIS Code
2019,1,3
2019,2,3
2019,3,3
2019,4,3
2020,1,3
2020,2,3
2020,3,3
2020,4,3
2021,1,3
2021,2,3
2021,3,3
2021,4,3
2022,1,3
2019,1,7
2019,2,7
2019,3,7
2019,4,7
2020,1,7
2020,2,7
2020,3,7
2020,4,7
2021,1,7
2021,2,7
2021,3,7
2021,4,7
2022,1,7
2019,1,8
2019,2,8
2019,1,9
2019,2,9
2019,3,9
2019,4,9
2020,1,9
2020,2,9
2020,3,9
2020,4,9
2021,1,9
2021,2,9
2021,3,9
2021,4,9
2022,1,9
2019,1,10
2019,2,10
2019,3,10
2019,4,10
2020,1,10
2020,2,10
2020,3,10
2020,4,10
2021,1,10
2021,2,10
2021,3,10
2021,4,10
2022,1,10

**Comment by eglove** [comment]
Summary Value shape:

```
[
    {
        "id": string,
        "reportingPeriodId": number,
        "monitoringLocationId": string,
        "calcCurrentRptPeriodTotal": number or null,
        "calcOsTotal": number or null,
        "calcYearTotal": number or null,
        "userId": string or null,
        "addDate": date or null,
        "updateDate": date or null,
        "stackPipeId": string or null,
        "unitId": string or null,
        "parameterCode": string,
        "currentReportingPeriodTotal": number or null,
        "ozoneSeasonToDateTotal": number or null,
        "yearToDateTotal": number of null
    }
]
```

SQL to find reporting periods and plants that have summary values:

```
Select distinct reporting_period.calendar_year, reporting_period.quarter, plant.oris_code
From camdecmps.summary_value
         Left Join camdecmps.monitor_location
                   on camdecmps.monitor_location.mon_loc_id = camdecmps.summary_value.mon_loc_id
        left join camdecmps.monitor_plan_location on monitor_location.mon_loc_id = monitor_plan_location.mon_loc_id
        left join camdecmps.monitor_plan on monitor_plan_location.mon_plan_id = monitor_plan.mon_plan_id
         Left Join camd.plant on monitor_plan.fac_id = plant.fac_id
         Left Join camdecmpsmd.reporting_period
                   on camdecmpsmd.reporting_period.rpt_period_id = camdecmps.summary_value.rpt_period_id
order by plant.oris_code

```
