### ISSUE TITLE
API: Create Operating Supplemental Emissions Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4379]
As an ERG team member, I need to be able to access operating supplemental emissions data from the operating supplemental table in order to support CBS, CSA, and the CAMD Oracle Jobs

Given an Operating Supplemental Emissions Endpoint is created
When the API calls the operating supplemental endpoint 
Then operating supplemental emissions data based on a quarter range and ORIS codes is returned

If the location is not specified, then the system shall filter by the oris code and all of the locations for the oris code  are returned.
If loction and oris code are specified then the system shall filter by the location 

- [ ] The Endpoint is only for the global  view NOT the workspace

Endpoint Parameters:
- ORIS Code 
- Begin Year 
- Begin Quarter 
- End Year 
- End Quarter

This will only be for the official camdecmps schema and the url will be
/streaming-services/emissions/supplemental-operating

Notes: 2.	The current apportioned hourly emissions endpoint allows but does not require an ORIS code.  However, CBS, CSA and Oracle jobs would supply one or more ORIS codes when requesting Supplemental Operating emissions supplemental data.

https://usepa.sharepoint.com/:w:/r/sites/CAMDITLegacyReeng/Shared%20Documents/General/ECMPS%202.0%20Additional%20API%20Endpoints%20from%20ERG.docx?d=w742168a2451f4f839e683bb481d2059a&csf=1&web=1&e=YCXLP7

**Comment by JanellC** [comment]
Endpoint: /emissions-mgmt/emissions/supplemental/operating-data (CVP will determine the actual path)

**Comment by JanellC** [comment]
**Questions:** 
1. The system returns an error message that oris code is required. Swagger does not display oris code as a required parameter 
2. The requirments ask for operatingValue to be returned. API returns "opValue" should this be updated? This applies to opcode and rptPeriodIdentifier as well
3. location id and id are missing and are not returned from the api

**API returns the following data**
{
   "stackPipeId":null,
   "unitId":"5",
   "monLocIdentifier":"11",
   "fuelCode":null,
   "opTypeCode":"OPHOURS",
   "rptPeriodIdentifier":"114",
   "opValue":"2013.000",
   "userid":"bvick",
   "addDate":"2021-07-26T15:21:20.000Z",
   "updateDate":null
}


Requirements state that the following should be returned :

[ 

  { 

    “id”: “string”, 

    “locationId”: “string”, 

    “reportPeriodId”: number, 

    “operatingTypeCode”: “string”, 

    “fuelCode”: “string”, 

    “operatingValue”: number, 

    “userId”: “string”, 

    “addDate”: “string(date-time)”, 

    “updateDate”: “string(date-time)” 

  } 

]

**Comment by JanellC** [comment]
System works as expected 

End Point has the appropiete parameters: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnRiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37b3bf7521b438aeb786a3b23553e2287586d7e3/image.png)

The endpoint is returning the following data: 

{
      "id":"DESKTOP-EG-CEF3155D8A44445799F8A91114E215FE",
      "locationId":"5141",
      "reportPeriodId":113,
      "operatingTypeCode":"CO2M",
      "fuelCode":null,
      "operatingValue":503.9,
      "userId":"niseri",
      "addDate":"2022/07/22 18:16:31",
      "updateDate":null
   },
