### ISSUE TITLE
API: Create Hourly Operating Emissions Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4380]
As an ERG team member, I need to be able to access hourly operating emissions data from the hourly operating table in order to support emissions-loading jobs

Given an Hourly Operating Emissions Endpoint is created
When the API calls the Hourly Operating endpoint 
Then the API will return Hourly Operating Data emissions data based on a date range and a combination of ORIS codes and location names.  If no location names are specified, then all locations for the ORIS codes are returned. 

- [ ] This should be tagged under hourly operating data

- [ ] The Endpoint is only for the global  view NOT the workspace

This will only be for the official camdecmps schema 

Endpoint URL: /emissions-mgmt/emissions/hourly-operating-data

Parameters:
orisCode: number list (optional, | delimited)
locationName: string list (optional, | delimited)
beginDate: date string
endDate: date string

(updated endpoint url and parameters per Ethan's comment below)

**Comment by eglove** [comment]
Endpoint  URL: /emissions-mgmt/emissions/hourly-operating-data

Parameters:
- orisCode: number list (optional, | delimited)
- locationName: string list (optional, | delimited)
- beginDate: date string
- endDate: date string

Example: 
/emissions-mgmt/emissions/hourly-operating-data?orisCode=60|61&beginDate=2020-11-01T15:28:20.028Z&endDate=2022-11-01T15:28:20.028Z&locationName=2

Return shape:

```
{
  "id": string,
  "reportingPeriodId": number,
  "monitoringLocationId": string,
  "beginDate": date string,
  "beginHour": number,
  "operatingTime": number or null,
  "hourLoad": number or null,
  "loadRange": number or null,
  "commonStackLoadRange": number or null,
  "fcFactor": number or null,
  "fdFactor": number or null,
  "fwFactor": number or null,
  "fuelCode": string or null,
  "multiFuelFlg": string or null,
  "userId": string or null,
  "addDate": date string or null,
  "updateDate": date string or null,
  "loadUnitsOfMeasureCode": string or null,
  "operatingConditionCode": string or null,
  "fuelCdList": string or null,
  "mhhiIndicator": number or null,
  "matsHourLoad": number or null,
  "matsStartupShutdownFlag": string,
  "calcHourMeasureCode": string or null
}
```

Results from the below query (stackName or unitid is used as locationNames):

```
orisCode, calendarYear, quarter, stackName, unitid
60,2021,4,,1
60,2021,3,,2
60,2022,1,,2
60,2021,3,,1
60,2021,3,,2
60,2021,3,,1
60,2022,1,,2
60,2022,1,,2
60,2022,1,,1
6090,2022,1,CS1
6090,2021,2,CS1
6090,2020,2,CS1
6090,2020,2,CS1
6090,2021,3,CS1
6090,2021,2,CS1
6090,2021,1,CS1
6090,2020,3,CS1
6090,2021,4,CS1
```

Finding test data:

```
select plant.oris_code, reportingPeriod.calendar_year, reportingPeriod.quarter, stackPipe.stack_name, unit.unitid
from camdecmps.hrly_op_data as hourlyOp
         join camdecmps.monitor_location as monitorLocation on hourlyOp.mon_loc_id = monitorLocation.mon_loc_id
         left join camdecmps.stack_pipe as stackPipe on monitorLocation.stack_pipe_id = stackPipe.stack_pipe_id
         left join camd.unit as unit on monitorLocation.unit_id = unit.unit_id
         join camdecmps.monitor_plan_location as monitorPlanLocation
              on monitorLocation.mon_loc_id = monitorPlanLocation.mon_loc_id
         join camdecmps.monitor_plan as monitorPlan on monitorPlan.mon_plan_id = monitorPlanLocation.mon_plan_id
         join camd.plant as plant on plant.fac_id = monitorPlan.fac_id
         join camdecmpsmd.reporting_period as reportingPeriod on hourlyOp.rpt_period_id = reportingPeriod.rpt_period_id;
```
