### ISSUE TITLE
API: Create Derived Hourly Value Emissions Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4381]
As an ERG team member, I need to be able to access derived hourly value emissions data from the derived hourly value table in order to support emissions-loading jobs

Given the Derived Hourly Value Emissions Endpoint is created
When the API calls the Derived Hourly Value endpoint 
Then the API will return  Derived Hourly Value emissions data based on a date range and a combination of ORIS codes and location names.  If no location names are specified, then all locations for the ORIS codes are returned. 

- [ ] Should be completed under the derived hourly operating controller but tagged under hourly operating 
- [ ] The Endpoint is only for the global  view NOT the workspace

Endpoint Parameters:
- ORIS Code 
- Location Name 
- Begin Date
- End Date 

This will only be for the official camdecmps schema 

Endpoint URL: /emissions-mgmt/emissions/derived-hourly-value

Endpoint url updated per Ethan's comment below.

**Comment by eglove** [comment]
Endpoint URL: /emissions-mgmt/emissions/derived-hourly-value

Parameters:
- orisCode: number list (optional, | delimited)
- locationName: string list (optional, | delimited)
- beginDate: date string
- endDate: date string

Example:
/emissions-mgmt/emissions/derived-hourly-value?beginDate=2021-11-01T18:13:12.513Z&endDate=2022-11-01T18:13:12.513Z&locationName=**2&orisCode=7097|60

Return Shape:
```
{
  "id": string,
  "hourId": string,
  "monSysId": string or null,
  "monFormId": string or null,
  "parameterCode": string,
  "unadjustedHrlyValue": number or null,
  "applicableBiasAdjFactor": number or null,
  "calcUnadjustedHrlyValue": number or null,
  "adjustedHrlyValue": number or null,
  "calcAdjustedHrlyValue": number or null,
  "operatingConditionCode": string or null,
  "pctAvailable": number or null,
  "diluentCapInd": number or null,
  "segmentNum": number or null,
  "fuelCode": string or null,
  "userId": string or null,
  "addDate": date string or null,
  "updateDate": date string or null,
  "calcPctDiluent": string or null,
  "calcPctMoisture": string or null,
  "calcRataStatus": string or null,
  "calcAppeStatus": string or null,
  "rptPeriodId": number,
  "monitorLocationId": string,
  "calcFuelFlowTotal": number or null,
  "calcHourMeasureCode": string or null,
}
```
Results from the below query (stackName or unitid is used as locationNames):
```
orisCode, calendarYear, quarter, stackName, unitId
60,2021,4,,1
60,2021,3,,2
60,2022,1,,2
60,2021,3,,1
60,2021,3,,2
60,2021,3,,1
60,2022,1,,2
60,2022,1,,2
60,2022,1,,1
6090,2022,1,CS1,
6090,2021,2,CS1,
6090,2020,2,CS1,
6090,2020,2,CS1,
6090,2021,3,CS1,
6090,2021,2,CS1,
6090,2021,1,CS1,
6090,2020,3,CS1,
6090,2021,4,CS1,
6090,2022,1,CS1,
```
Finding test data:
```
select plant.oris_code, reportingPeriod.calendar_year, reportingPeriod.quarter, stackPipe.stack_name, unit.unitid
from camdecmps.hrly_op_data as hourlyOp
         join camdecmps.monitor_location as monitorLocation on hourlyOp.mon_loc_id = monitorLocation.mon_loc_id
         left join camdecmps.stack_pipe as stackPipe on monitorLocation.stack_pipe_id = stackPipe.stack_pipe_id
         left join camd.unit as unit on monitorLocation.unit_id = unit.unit_id
         join camdecmps.monitor_plan_location as monitorPlanLocation
              on monitorLocation.mon_loc_id = monitorPlanLocation.mon_loc_id
         join camdecmps.monitor_plan as monitorPlan on monitorPlan.mon_plan_id = monitorPlanLocation.mon_plan_id
         join camd.plant as plant on plant.fac_id = monitorPlan.fac_id
         join camdecmpsmd.reporting_period as reportingPeriod on hourlyOp.rpt_period_id = reportingPeriod.rpt_period_id;
```
