### ISSUE TITLE
MP: Unit Capacity fields not showing up in Create Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4383]
**Issue:**
Unit Capacity fields are not showing up in the Create Modal

See below for screenshot reference:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/dd84266d-65bd-4d5b-9f75-32d774913cc2)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/2d05fda0-de2a-49cd-8983-26b177ee4b5a)

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
![Create Unit Capacity.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/69a5cf18-e72b-4971-9a46-8ace5342409a)
