### ISSUE TITLE
QA & Cert: Duplicate RATA Check

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4384]
The scope of this ticket is to address the following RATA check
[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [ ] RATA-106 Duplicate RATA

**Comment by subrataroyCVP** [comment]
moved to 4650
