### ISSUE TITLE
Load QA Cert Test Detail Report Definition into database

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4390]
Need to define report sections for each QA Test Type...

## Updated report example supplied on 10/2:

https://usepa.sharepoint.com/:f:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%202.0/ECMPS%20Reports/Report%20Examples?csf=1&web=1&e=UCYzPc

**Completed**
- [x] CYCLE	"Cycle Time Test"
- [x] LINE	"Linearity Check"

**In Progress**
- [x] HGLINE	"Mercury Linearity"
- [x] FFACCTT	"Transmitter Transducer Test"
- [x] PEI	"Primary Element Inspection"
- [x] RATA	"Relative Accuracy Test"

**Need Report Examples**
- [x] APPE	"Appendix E NOx Rate Test" (need report example)
- [x] F2LCHK	"Flow-to-Load Ratio or GHR Test" (need report example)
- [x] F2LREF	"Flow-to-Load or GHR Reference Data" (need report example)
- [x] FF2LBAS	"Fuel Flow-to-Load Baseline Data" (need report example)
- [x] FF2LTST	"Fuel Flow-to-Load Test" (need report example)
- [x] FFACC	"Fuel Flowmeter Accuracy Test" (need report example)
- [x] HGSI3	"Three-Point Hg System Integrity Check" (need report example)
- [x] ONOFF	"On-Line/Off-Line Calibration" (need report example)
- [x] UNITDEF	"Unit-Specific Default NOx Rate Test" (need report example)

**MISC GROUP -  (need report examples for all)**
- [x] BCAL	"Barometer calibration (sorbent trap monitoring systems)"
- [x] DAHS	"DAHS Verification"
- [x] DGFMCAL	"Dry Gas Meter Calibration (Sorbent Trap Monitoring System)"
- [x] LEAK	"Leak Check"
- [x] MFMCAL	"Mass Flow Meter Calibration (Sorbent Trap Monitoring System)"
- [x] OTHER	"Other Test"
- [x] PEMSACC	"PEMS Accuracy Check"
- [x] QGA	"Quarterly Gas Audit (HCl and HF monitoring systems)"
- [x] TSCAL	"Temperature sensor calibration (sorbent trap monitoring systems)"

**Example Reports**
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000B4ABB0EF9635994FA680705355892410&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%202%2E0%2FECMPS%20Reports%2FQA%2DCert%20Test%20Detail%2Epdf&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%202%2E0%2FECMPS%20Reports

**Comment by JanellC** [comment]
Based on 9/19 refinement discussion need clarififcation on if we are doing this report

**Comment by JanellC** [comment]
@Kyle-Herceg confirmed and tested all test types. Functionality works as expected
