### ISSUE TITLE
QA - Test Data: Issue saving Monitoring System ID

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4411]
**Issue:**
When a user is creating Test Data and enters a value for the Monitoring System ID and clicks Save and Close then the value for Monitoring System ID is not being retained/saved even when the new Test Data record is created

Steps to recreate:
1. Login to ECMPS
2. Access the Test Summary Data from the left-hand navigation
3. Select and checkout a Configuration
4. Select RATA from the Test Type Group dropdown
5. Click on ADD for the Test Data and enter all the required information
6. Click Save and Close
You will see that the Test Data is added however the value for the Monitoring System ID has not been retained/is not displayed/is blank

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/71bb60d0-268b-4eb9-ae0b-99ffc7aa0621)

**Comment by billmiller13** [comment]
For Testing:

Create Test Summary:

locId = 66
payload = {
  "stackPipeId": null,
  "unitId": "1",
  "testTypeCode": "RATA",
  "monitoringSystemID": "BA1",
  "componentID": null,
  "spanScaleCode": null,
  "testNumber": "3",
  "testReasonCode": "DIAG",
  "testDescription": null,
  "testResultCode": "PASSED",
  "calculatedTestResultCode": null,
  "beginDate": "2022-11-03",
  "beginHour": 7,
  "beginMinute": 0,
  "endDate": "2022-11-03",
  "endHour": 7,
  "endMinute": 15,
  "gracePeriodIndicator": 0,
  "calculatedGracePeriodIndicator": null,
  "year": null,
  "quarter": null,
  "testComment": "BMILLER TEST",
  "injectionProtocolCode": null,
  "calculatedSpanValue": null,
  "evalStatusCode": "EVAL",
  "userId": "bmiller-dp",
  "addDate": "11/3/2022, 11:52:08 AM",
  "updateDate": "11/3/2022, 11:52:08 AM",
  "reportPeriodId": null
}


Update Test Summary:

locId = 66
id = [from previous create test]
payload = {
  "stackPipeId": null,
  "unitId": "1",
  "testTypeCode": "RATA",
  "monitoringSystemID": "BA6",
  "componentID": null,
  "spanScaleCode": null,
  "testNumber": "3",
  "testReasonCode": "DIAG",
  "testDescription": null,
  "testResultCode": "PASSED",
  "calculatedTestResultCode": null,
  "beginDate": "2022-11-03",
  "beginHour": 7,
  "beginMinute": 0,
  "endDate": "2022-11-03",
  "endHour": 7,
  "endMinute": 15,
  "gracePeriodIndicator": 0,
  "calculatedGracePeriodIndicator": null,
  "year": null,
  "quarter": null,
  "testComment": "BMILLER TEST",
  "injectionProtocolCode": null,
  "calculatedSpanValue": null,
  "evalStatusCode": "EVAL",
  "userId": "testuser",
  "addDate": "11/3/2022, 11:59:19 AM",
  "updateDate": "11/3/2022, 11:59:19 AM",
  "reportPeriodId": null
}

**Comment by mosesdeeCVP** [comment]
Bug is fixed for when the Monitoring System ID is correct for that configuration, when the Monitoring System ID is not a valid ID the Rata is still created with a blank Monitoring System ID. A future ticket will solve this problem by limiting the Monitoring System ID choices to only valid options
