### ISSUE TITLE
Workspace 'Add': Appendix E Heat Input From Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4413]
As an ECMPS user, I want to add new Appendix E Heat Input From Gas data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Appendix E Correlation Test Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Appendix E Heat Input From Gas data
Then the system displays a modal
and the user can add new data for:

Gas GCV (Text)
Gas Volume (Text)
Gas Heat Input (Text)

Given the user has added Appendix E Heat Input From Gas data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Appendix E Heat Input From Gas record is reflected on the UI

Given the user has added a new Appendix E Heat Input From Gas record
When the user chooses to Cancel
Then the user is returned to the Landing screen for Appendix E Correlation Summary
And no updates are saved

Reference Invision:
https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2ZjR5Mmw2MDBzdzNiN25ucHNoaHhkdg%3D%3D

## Testing 
Test Case:[ TC1077](https://epacamd.testquality.com/project/11428/plan/27381/test/406783)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Appendix E Heat Input From Gas - Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1c427188-7684-4eb6-94dc-a3e6d41225d3)
