### ISSUE TITLE
Incorrect Title on View Modals

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4416]
Issue:

All the View modals (Global-view) show the title of the pop-up as Edit instead of View. This needs to be corrected

Note: to be fixed and tested in both official and workspace views

Some of the Test Types with the issue:
RATA
Linearity Summary
Appendix E etc

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3d2bb93b-ec66-47f9-850b-32fccdd35b15)

**Comment by mosesdeeCVP** [comment]
Appendix E Correlation Heat Input from Gas 

![Appendix E Correlation Heat Input from Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/38450e68-f293-4dca-9ffc-f772f35c1fbc)

**Comment by mosesdeeCVP** [comment]
LINE Test Summary

![LINE Test Summary.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d2ec8d0d-8cfa-4275-9952-d4a94b9ccaab)

**Comment by mosesdeeCVP** [comment]
RATA Data

![RATA Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7dbc75d7-9b2a-4302-b5d1-f315c3170c6f)

**Comment by mosesdeeCVP** [comment]
Bug fixed
