### ISSUE TITLE
Create Selected View API Endpoint for Global [Official] View

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4421]
As an ECMPS system, I need to support the selected view template in the global [official] view of the emissions workspace, so that users can view data emissions data.

Given the Selected View API Endpoint is created
When a view is selected from the list of emissions view in the API
Then the data from that view will be returned

**Comment by AmandaMNelson** [comment]
Fails, will be resolved with bug ticket #4473

**Comment by sdhawan16** [comment]
Sample parameters:
viewCode - dailycal
monitorPlanId - GO619-E38--25E39413591C41A0B396309D03A7A207
unitIds - 1
reporting quarter - 2021 Q1
