### ISSUE TITLE
Test only Verify: Export Button not working in Logged In Emissions Module Workspace

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4423]
The purpose of this ticket is to verify if there is still a bug regarding the export button in the logged-in view of the emission module workspace

Steps to Recreate
User logs into the ECMPS system
Navigates to emissions module workspace
When a user clicks on the export button user gets an error

**Comment by AmandaMNelson** [comment]
![image](https://user-images.githubusercontent.com/110929222/199254353-64e3e72b-7113-48e0-ab98-ded64d436a21.png)
This is the error that is generated when a logged in user clicks on the Export button on the Emissions page.

**Comment by AmandaMNelson** [comment]
This error is still occurring.
Steps to recreate:
Navigate to ecmps-dev.app.cloud.gov/emissions
Log In (now on workspace site)
Select a configuration and click "Open & Checkout" (e.g. Barry)
Fill out the filter fields (e.g. Location: 1, View Template: Daily Calibration, Reporting Period(s): 2021 Q1) and apply
Click the "Export Data" button
The error message "undefined internal server error" appears, as seen in the screenshot above
