### ISSUE TITLE
Online Offline Calibration Data: Field discrepancies

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4425]
For Online Offline Calibration Data, some of the fields are different in the DB from what is provided in the Reporting Instructions. See below:

**Reporting Instructions:**
Online Zero APS Indicator (Dropdown)
Online Upscale APS Indicator (Dropdown)
Offline Zero APS Indicator (Dropdown)
Offline Upscale APS Indicator (Dropdown)

**Database:**
"calculatedOnlineZeroCalibrationError"
"calculatedOnlineUpscaleCalibrationError"
"calculatedOfflineZeroCalibrationError"
"calculatedOfflineUpscaleCalibrationError"

To do: Remove the calculated fields from the schema
Add the APS indicator fields as applicable for Online Offline Calibration Data

**Comment by mosesdeeCVP** [comment]
![4425 Online Offline Calibration Data- Field discrepancies.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fdc45c5d-57d4-4396-9d81-ada49f66e330)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1025](https://epacamd.testquality.com/project/11428/plan/27608/test/401529)
Test Passed
