### ISSUE TITLE
Update acceptable values for HG converter indicator 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4428]
As an ECMPS user, I need the ability to leave HG converter indicator field null/blank so that the value is correct for any new component except for that of Hg Analyzers

Acceptance Criteria:

Given I am an ECMPS user logged in
When I am creating a new System Component (System)
Then I have the option to pick from 1, 0 or null for HG converter indicator field

Note: Change the existing radio-button field to a dropdown for HG converter indicator field

## Testing
Test Case: [TC1050](https://epacamd.testquality.com/project/11428/plan/19812/test/403224)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC1050 passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1f89ea31-c7d6-4693-8878-2331cada648d)
