### ISSUE TITLE
MP: Remove/Hide View Audit Report

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4429]
BETA users are confused on why the view audit report button does not work. The scope of this ticket is to remove the Audit Reports buttons in the following locations (comment out the code for the view audit report button) :

- Global-view: Monitoring Plans - Individual Configurations Tab
- Workspace: Monitoring Plans - Individual Configurations Tab

**Comment by mosesdeeCVP** [comment]
Butten has been removed

**Comment by mosesdeeCVP** [comment]
Remove-Hide View Audit Report Logged In

![Remove-Hide View Audit Report Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d13386d6-155a-4857-9998-3a64e1688f2f)

Remove-Hide View Audit Report Logged Out

![Remove-Hide View Audit Report Logged Out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8904b331-c028-404c-9f27-0731b7c926e0)
