### ISSUE TITLE
Discuss Lock Icons on Tabs

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4431]
I checked out Barrett unit 10.  When I go and then open (not check out) unit 20 it shows the lock icon as well.  I know these are the same facility but I think the lock icon should only be for checked out configs. 

 ![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5126b884-ed70-40f5-97ba-12fe24df58f3)

Note: Need to have a larger discussion on locking a monitoring plan/facility. Will discuss at a future integration meeting.

**Comment by JanellC** [comment]
Per backlog refinement on 12/14, the team needs to have a loarger discussion with Jason W. on this ticket. The team will discuss this on Thursday 12/22
