### ISSUE TITLE
API Endpoint - Add Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4439]
API Endpoint - Add Cycle Time Injection Data

Testing Reference Only:
Gas Level Code  (Dropdown with values of High and Zero)
Calibration Gas Value (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute (Dropdown)
Injection Cycle Time (Text)
Begin Monitor Value  (Text)
End Monitor Value (Text)

**Comment by mosesdeeCVP** [comment]
![Add Cycle Time Injection Data - POST API.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44243823-c276-435b-a655-2b498db19c35)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1093](https://epacamd.testquality.com/project/11428/plan/27873/test/407900)
Test Passed
