### ISSUE TITLE
API Endpoint - View Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4440]
Create GET endpoints (4) for Cycle Time Injection Data:

Testing Note:
Should include GET endpoints for both Global View and Workspace to fetch one individual record or a collection of records

Testing Reference Only:
Gas Level Code (Dropdown with values of High and Zero) 
Calibration Gas Value (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute (Dropdown)
Injection Cycle Time (Text)
Begin Monitor Value (Text)
End Monitor Value (Text)

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection API View Official
![Cycle Time Injection API View Official .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/37e268f6-92d6-4769-848c-0f5f42fdc128)

Cycle Time Injection API View Official with ID
![Cycle Time Injection API View Official with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b134104b-2b92-4892-b74e-2b239e2e0987)

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection API View Workspace
![Cycle Time Injection API View Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/21b8f922-8d59-49a3-a824-2aa53dabd5ad)

Cycle Time Injection API View Workspace with ID
![Cycle Time Injection API View Workspace with ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fe77ebf8-f27f-49dd-8c92-2250d5537e54)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1133](https://epacamd.testquality.com/project/11428/plan/27873/test/411528)
Test Passed
