### ISSUE TITLE
API Endpoint - Edit Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4441]
Create API endpoint for Edit for Cycle Time Injection Data

Testing Reference Only:
Gas Level Code (Dropdown with values of High and Zero) 
Calibration Gas Value (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute (Dropdown)
Injection Cycle Time (Text)
Begin Monitor Value (Text)
End Monitor Value (Text)

**Comment by mosesdeeCVP** [comment]
![API Endpoint - Edit Cycle Time Injection Data 4441.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/61b4373c-d6a6-49d5-a2ba-e0ab9904b6fc)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1132](https://epacamd.testquality.com/project/11428/plan/27873/test/411527)
Test Passed
