### ISSUE TITLE
API Endpoint - Remove Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4442]
Create API Endpoint to remove/delete Cycle Time Injection Data

**Comment by mosesdeeCVP** [comment]
[Uploading... API Endpoint - Remove Cycle Time Injection Data Remove.png]

**Comment by mosesdeeCVP** [comment]
![API Endpoint - Remove Cycle Time Injection Data Remove.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e427586a-d5ac-4d92-bf7d-9e05c2423831)

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1131](https://epacamd.testquality.com/project/11428/plan/27873/test/411515)
Test Passed
