### ISSUE TITLE
Global 'View' and Workspace 'Add': Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4443]
As an ECMPS user, I want to view Cycle Time Injection data in the Global-View and add new Cycle Time Injection data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected Cycle Time Summary from the Test Type Group dropdown and a data record is available 
When the data is displayed for Cycle Time Injection
Then the user can see data displayed as a separate table (see list below for columns and order)

Gas Level Code
Calibration Gas Value 
Begin Date
Begin Hour
Begin Minute
End Date
End Hour
End Minute
Injection Cycle Time
Begin Monitor Value
End Monitor Value

Given a user is viewing Cycle Time Injection Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [X] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected Cycle Time Summary from the Test Type Group dropdown
When the user clicks on 'Add' for Cycle Time Injection Data
Then the system displays a modal
and the user can add new data for:

Gas Level Code (Dropdown with values of High and Zero) 
Calibration Gas Value (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute (Dropdown)
Injection Cycle Time (Text)
Begin Monitor Value (Text)
End Monitor Value (Text)

Given the user has added Cycle Time Injection 
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the Cycle Time Injection data record is reflected on the UI

Given the user has added a new Cycle Time Injection data
When the user chooses to Cancel
Then the user is returned to the Landing screen for Cycle Time Summary
And no updates are saved

**Dev Note:** **This data section is at the second level of nesting (Test Summary -> Cycle Time Summary -> Cycle Time Injection)**
Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d51d88de-e6c1-42ee-9390-1c98866c0363)

## Testing 
Test Case: [TC1109](https://epacamd.testquality.com/project/11428/plan/27873/test/411204))
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection - View Table Official 
![Cycle Time Injection - View Table Official .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d66227cc-20a1-4e2e-a986-1849808cafda)

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection - View Modal Official 
![Cycle Time Injection - View Modal Official .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93f33969-f454-4bd0-9159-3ebf008407ca)

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection - Add Modal
![Cycle Time Injection - Add Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ddce901a-144a-480f-8d68-94be289aa7e1)

**Comment by mosesdeeCVP** [comment]
Test Passed
