### ISSUE TITLE
Edit Cycle Time Injection Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4444]
As an ECMPS user (logged-in), I want to update Cycle Time Injection data so that I can add information to a test

Acceptance Criteria:
Given the user has selected Cycle Time Summary from the Test Type Group dropdown
When the user selects 'Edit' for Cycle Time Injection data
Then the system displays the edit modal
And the user can edit Cycle Time Injection data

Gas Level Code (Not editable)
Calibration Gas Value (Text)
Begin Date (Text+Datepicker)
Begin Hour (Dropdown)
Begin Minute (Dropdown)
End Date (Text+Datepicker)
End Hour (Dropdown)
End Minute (Dropdown)
Injection Cycle Time (Text)
Begin Monitor Value (Text)
End Monitor Value (Text)

Given the user has updated Cycle Time Injection data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing page for Cycle Time Injection data
And the updates are reflected in the Cycle Time Summary section

Warning message to pop up when a user updates data and closes the modal without saving (Cancel or clicks on X)
Warning message to read: Closing this window will discard any unsaved changes

## Testing 
Test Case[: TC1111](https://epacamd.testquality.com/project/11428/plan/27873/test/411208)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Passed

**Comment by mosesdeeCVP** [comment]
![Edit Cycle Time Injection Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/663e9272-e3c3-4d64-9c62-b168302fee11)
