### ISSUE TITLE
Add Cycle Time Injection data elements to Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4446]
Add Cycle Time Injection data elements to both export endpoints (global&workspace)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/305

**Comment by mosesdeeCVP** [comment]
Add Cycle Time Injection data elements to Export Endpoint - 4446 - Official
![Add Cycle Time Injection data elements to Export Endpoint - 4446 - Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/64c2f7bb-dde7-4695-a843-397096bb5032)

Add Cycle Time Injection data elements to Export Endpoint - 4446 - Workspace
![Add Cycle Time Injection data elements to Export Endpoint - 4446 - Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2800f811-3104-4805-a38c-f53180fec053)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1113](https://epacamd.testquality.com/project/11428/plan/27873/test/411225)
Test Passed
