### ISSUE TITLE
Add Cycle Time Injection data elements to Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4447]
Add cycle time injection data elements to import endpoint

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/305

**Comment by mosesdeeCVP** [comment]
![Add Cycle Time Injection data elements to Import Endpoint 4447 - Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/de38a4ae-73b5-489b-b053-be4e0f499bc3)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1114](https://epacamd.testquality.com/project/11428/plan/27873/test/411229)
Test Passed
