### ISSUE TITLE
Migrate Hourly Operating Endpoint to Streaming Services

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4449]
As an ERG team member, I need to be able to access hourly operating emissions data from the hourly operating table in order to support emissions-loading jobs

Given an Hourly Operating Emissions Endpoint is created
When the API calls the Hourly Operating endpoint
Then the API will return Hourly Operating Data emissions data based on a date range and a combination of ORIS codes and location names. 

If the location is not specified, then the system shall filter by the oris code and all of the locations for the oris code  are returned.
If loction and oris code are specified then the system shall filter by the location 

 This should be tagged under hourly operating data

 The Endpoint is only for the global view NOT the workspace

Endpoint Parameters:

ORIS Code
Unit ID
Stack ID
Begin Date
End Date

Parameter Logic 
If more than one oris code is provided the location is not provided (edited) 
If more than 1 location is provided only 1 oris code

This will only be for the official camdecmps schema and the url will be
/streaming-services/emissions/hourly/operating

https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Integration%20Coordination/ECMPS/ECMPS%202.0%20Additional%20API%20Endpoints%20from%20ERG.docx?d=w8b22ae209fa5457d9a3d4249ca42e68f&csf=1&web=1&e=xIAHxu

**Comment by JanellC** [comment]
System is not working as expected. See below. Changes will be tracked in #5595

**Questions:**
1.  I dont see id returned.
2. Requriements list that begin date should be returned twice. This isn't happening. 


The API is returning the following 

{
      "locationId":"LSYSGMX04X-761F51553F2E4447950FDB444A795B64",
      "reportPeriodId":109,
      "beginDate":"2020/01/07 00:00:00",
      "beginHour":2,
      "operatingTime":1,
      "hourLoad":271,
      "loadUnitsOfMeasureCode":"MW",
      "userId":"elamerso",
      "addDate":"2020/04/13 14:31:21",
      "updateDate":null
   },


The requirements ask for the following elements: 

  { 

    “id”: “string”, 

    “locationId”: “string”, 

    “reportPeriodId”: number, 

    “beginDate”: “string(date)” 

    “beginDateHour”: number 

    “operatingTime”: number 

    “hourLoad”: number 

    “loadUnitsOfMeasureCode”: “string” 

    “userId”: “string”, 

    “addDate”: “string(date-time)”,
