### ISSUE TITLE
Migrate Derived Hourly Value Emissions Endpoint to Streaming Services

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4450]
As an ERG team member, I need to be able to access derived hourly value emissions data from the derived hourly value table in order to support emissions-loading jobs

Given the Derived Hourly Value Emissions Endpoint is created
When the API calls the Derived Hourly Value endpoint
Then the API will return Derived Hourly Value emissions data based on a date range and a combination of ORIS codes and location names

If the location is not specified, then the system shall filter by the oris code and all of the locations for the oris code  are returned.
If loction and oris code are specified then the system shall filter by the location 

 Should be completed under the derived hourly operating controller but tagged under hourly operating
 The Endpoint is only for the global view NOT the workspace
Endpoint Parameters:

ORIS Code
Location Name
Begin Date
End Date

This will only be for the official camdecmps schema and the url will be
/streaming-services/emissions/hourly/derived-values

https://usepa.sharepoint.com/:w:/r/sites/CAMDITLegacyReeng/Shared%20Documents/General/ECMPS%202.0%20Additional%20API%20Endpoints%20from%20ERG.docx?d=w742168a2451f4f839e683bb481d2059a&csf=1&web=1&e=YCXLP7

**Comment by JanellC** [comment]
**Questions:** 
1. I dont see ID returned by the API 
2.  “adjustedHourlyValue" should be returned by the API. Is calcAdjustedHrlyValue the same thing? Is this labeled correctly? 
3.   Location id should be returned by the api. Is monitorLocationId the same as location id? is this labeled correctly? 
4.  reporting period is returned as  “reportPeriodId”. Is this correct should it be labeled this way? 



API returns the following values: 
[
   {
      "hourId":"LSYSFHBZLH-A7D8C010BD364EE98D3547B77CB68911",
      "applicableBiasAdjFactor":null,
      "calcUnadjustedHrlyValue":null,
      "calcAdjustedHrlyValue":"2767.0000",
      "diluentCapInd":null,
      "userId":"elamerso",
      "addDate":"2020-04-13T18:31:23.000Z",
      "updateDate":null,
      "calcPctDiluent":"8.2",
      "calcPctMoisture":null,
      "calcRataStatus":"IC",
      "calcAppeStatus":null,
      "rptPeriodId":"109",
      "monitorLocationId":"LSYSGMX04X-761F51553F2E4447950FDB444A795B64",
      "calcFuelFlowTotal":null,
      "calcHourMeasureCode":"MEASURE",
      "parameterCode":"HI",
      "modcCode":null,
      "unadjustedHrlyValue":null,
      "adjustedHrlyValue":"2767.0000",
      "monitoringSystemId":"4RC",
      "formulaId":"4H8",
      "pctAvailable":null,
      "operatingConditionCode":null,
      "segmentNum":null,
      "fuelCode":null
   }
]


Requirements states the follwing should be returned: 


[ 

  { 

    “id”: “string”, 

    “hourId”: “string”, 

    “parameterCode”: “string”, 

    “adjustedHourlyValue”: “string”, 

    “modcCode”: “string”, 

    “locationId”: “string”, 

    “reportPeriodId”: number, 

    “userId”: “string”, 

    “addDate”: “string(date-time)”, 

    “updateDate”: “string(date-time)” 

  } 

]

**Comment by JanellC** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Derived Hourly Value Emissions Endpoint - Response
![Derived Hourly Value Emissions Endpoint - Response.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/960c03f9-4b7e-4e29-a7dc-8a2f3b0005d4)

**Comment by mosesdeeCVP** [comment]
"id":"bvick-E4A4ECE344B4322DE05385E443862D12",
"hourId":"TWCORNEL5-969A42761E2C4903AD86B3E2233AC29F",
"parameterCode":"NOXR",
"adjustedHourlyValue":"0.1090",
"modcCode":"14",
"locationId":"84",
"reportPeriodId":118,
"userId":"bvick",
"addDate":"2022/07/25 13:02:31",
"updateDate":null

**Comment by mosesdeeCVP** [comment]
https://api.epa.gov/easey/dev/streaming-services/emissions/hourly/derived-values?orisCode=26&locationName=3&beginDate=2022-01-01&endDate=2022-02-01

"id":"jcocking-DB997BFA7B20A0C4E05385E443863D0C",
"hourId":"DP06374-C29566755ABF4263AD2993B1AEFD8998",
"parameterCode":"HI",
"adjustedHourlyValue":"1497.0000",
"modcCode":null,
"locationId":"115",
"reportPeriodId":117,
"userId":"jcocking",
"addDate":"2022/04/01 10:20:45",
"updateDate":null}

**Comment by JanellC** [comment]
System working as expected https://api.epa.gov/easey/dev/streaming-services/emissions/hourly/derived-values?beginDate=2021-01-01&endDate=2021-02-28
