### ISSUE TITLE
Migrate Summary Value Emissions Data Endpoint to Streaming Services

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4451]
As an ERG team member, I need to be able to access summary emissions data from the summary value table in order to support CBS, CSA, and the CAMD Oracle Jobs.

Given an Emissions Summary Value Endpoint is created
When the API calls the summary value endpoint
Then summary Value emissions data based on a quarter range and ORIS codes is returned

Endpoint Parameters:

ORIS Code
Begin Year
Begin Quarter
End Year
End Quarter

Parameter Logic
One or more ORIS codes are to be provided

This will only be for the official camdecmps schema and the url will be
/streaming-services/emissions/summary-values

https://usepa.sharepoint.com/:w:/r/sites/CAMDITLegacyReeng/Shared%20Documents/General/ECMPS%202.0%20Additional%20API%20Endpoints%20from%20ERG.docx?d=w742168a2451f4f839e683bb481d2059a&csf=1&web=1&e=YCXLP7

**Comment by JanellC** [comment]
**Questions:**
1. On Swagger oris code is not labeled as required but when you make a get request the system states that oris code is required 
2. Is unit id the same as location id? The requirements ask that location id is returned 
3. ID isn't returned from the api 
4. quarterly value isn't returned by the api 
5. is  "yearToDateTotal"the same as yearTotal? The requirements ask for yearTotal to be returned. Should this label be updated? This applied to ozoneSeasonToDateTotal as well 



API returns the following: 
{
   "stackPipeId":null,
   "unitId":"5",
   "parameterCode":"CO2M",
   "currentReportingPeriodTotal":"1385182.500",
   "ozoneSeasonToDateTotal":null,
   "yearToDateTotal":"2954171.200",
   "reportingPeriodId":"115",
   "monitoringLocationId":"11",
   "calcCurrentRptPeriodTotal":"1385182.500",
   "calcOsTotal":null,
   "calcYearTotal":"2954171.200",
   "userId":"bvick",
   "addDate":"2021-10-22T16:05:23.000Z",
   "updateDate"



**Requirements specify that the following should be returned:**  

[ 

  { 

    “id”: “string”, 

    “locationId”: “string”, 

    “reportPeriodId”: number, 

    “parameterCode”: “string”, 

    “quarterlyValue”: number, 

    “yearTotal”: number, 

    “ozoneSeasonTotal”: number, 

    “userId”: “string”, 

    “addDate”: “string(date-time)”, 

    “updateDate”: “string(date-time)” 

  } 

]

**Comment by JanellC** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
https://api.epa.gov/easey/dev/streaming-services/emissions/summary-values?orisCode=10|3&beginYear=2022&beginQuarter=1&endYear=2023&endQuarter=1


"id":"TWCORNEL5-D90E7212AA2C499A9889AB48B0F715E3",
"locationId":"17",
"reportPeriodId":117,
"parameterCode":"CO2M",
"quarterlyValue":66.6,
"yearTotal":66.6,
"ozoneSeasonTotal":null,
"userId":"bvick",
"addDate":"2022/04/26 14:49:23",
"updateDate":null

**Comment by mosesdeeCVP** [comment]
API call functions as expected
