### ISSUE TITLE
Easey-CAMPD-UI Dependabot Alerts (To be Addressed after ECMPS Beta Development Work is complete)

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4467]
- [ ] Critical: Prototype pollution in webpack loader-utils -> Cannot be fixed without upgrading react 

- [ ] Critical:xmldom allows multiple root nodes in a DOM -> Will attempt to force upgrade to 7.6 

- [ ] Critical: Withdrawn: Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') in @xmldom/xmldom and xmldom -> Will attempt to force upgrade to 7.6 

- [ ] High: minimatch ReDoS vulnerability 

- [ ] loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - > Cannot be fixed without upgrading to react 

- [ ] loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - Cannot be fixed without upgrading to React

**Comment by JanellC** [comment]
The issues noted above have been addressed with the REACT upgrade. Will log a seperate ticket for the new depenadabot issues
