### ISSUE TITLE
EASEY-ECMPS-UI Dependabot Alerts (To be Addressed after ECMPS Beta Development Work is complete)

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4469]
- [ ] Critical: Prototype pollution in webpack loader-utils 

- [ ] minimatch ReDoS vulnerability - > Cannot be fixed without updating react scripts 

- [ ] loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - > Cannot be fixed without updating react scripts 

- [ ] Prototype pollution in webpack loader-utils - Cannot be fixed without updating React Scripts

**Comment by JanellC** [comment]
The issues noted above have been addressed with the REACT upgrade. Will log a seperate ticket for the new depenadabot issues
