### ISSUE TITLE
508: Emissions Workspace UI Focus Issues

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4478]
- [ ] When a user hits the Select Configurations button with the keyboard, it should stay on that button

**Comment by aprematta** [comment]
I'm still seeing a loss of focus. for example if I have chikasaw open and active, then hit select configurations, focus is lost..... if I tab again its on the facility header

**Comment by sdhawan16** [comment]
@aprematta This ticket was accidentally moved to ready for testing earlier. It should have the updates now

**Comment by aprematta** [comment]
Just rechecked, looks good.... closing ticket
