### ISSUE TITLE
TEST ONLY Bug: Export Button in Emission UI Not Working 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4480]
Steps to recreate:
Navigate to ecmps-dev.app.cloud.gov/emissions
Log In (now on workspace site)
Select a configuration and click "Open & Checkout" (e.g. Barry)
Fill out the filter fields (e.g. Location: 1, View Template: Daily Calibration, Reporting Period(s): 2021 Q1) and apply
Click the "Export Data" button
The error message "undefined internal server error" appears, as seen in the screenshot above

**Comment by sdhawan16** [comment]
Data has been reloaded into the workspace table for Barry 2021. The steps to recreate this bug is no longer returning an error
