### ISSUE TITLE
QA Module: Pre-select Test Type Code in Test Data Section

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4486]
QA Test Summary Modal should pre-select Test Type if there is only 1 option in the dropdown

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4c3d76fd-9cf1-47d6-8ad1-47ea7c6ba610)

**Comment by mosesdeeCVP** [comment]
Test Type code is pre-selected by default when only 1 is available.
