### ISSUE TITLE
Pre-populate Unit/Stack ID options based on the Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4487]
Unit/Stack Id dropdown should be pre-populated with the applicable options based on the location dropdown from the main screen (Configurations tab). 

Note: Read-only pre-populated Unit/Stack Pipe ID field based on your selection from the Locations dropdown

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ca0f77ca-e183-4a5c-8281-e1d6719999e8)

## Testing 
Test Case:[ TC1104](https://epacamd.testquality.com/project/11428/plan/24660/test/410796)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Unit and Stack Pipe ID.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/97eeab76-cb20-49af-b176-5145f3a4f786)

**Comment by mosesdeeCVP** [comment]
Changes have been made

**Comment by mosesdeeCVP** [comment]
![Unit and Stack Pipe ID 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/87071f75-7f48-474f-bcde-8a2e47bc6d3a)

**Comment by mosesdeeCVP** [comment]
Changes have been made

**Comment by mosesdeeCVP** [comment]
Changes have been made
