### ISSUE TITLE
Pre-populate Monitor System Id's based on the Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4488]
Monitoring System Id should be a pre-populated for Test Data and only allow values based on the location dropdown from the main screen (Configurations Screen)

Utilize the following endpoint to get the systems: /monitor-plan-mgmt/workspace/locations/{locId}/systems

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/65a4fb0e-abf2-4212-91f0-4505ee9863e1)

## Testing 
Test Case:  [TC1105](https://epacamd.testquality.com/project/11428/plan/24660/test/410954)
Tester: @mosesdeeCVP

**Comment by subrataroyCVP** [comment]
Fixed the build issue. Ready for Testing at DEV.

**Comment by mosesdeeCVP** [comment]
![Mon Sys ID Dropdown.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/08a0ce02-dd3d-4643-a8b5-5b593962a77c)
