### ISSUE TITLE
Test Only: Pre-populate Component Id's basaed on the Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4489]
Component Id's shall be a dropdown and display only the values based on the location dropdown from the main screen (Configurations screen)
Utilize the following endpoint to get the component ID: /monitor-plan-mgmt/workspace/locations/{locId}/components

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/964cbfa8-146d-4710-a278-c12c6af5199f)

**Comment by mosesdeeCVP** [comment]
Component ID Filters based on Location

**Comment by mosesdeeCVP** [comment]
![Component ID location Filter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ba2a3d2c-a709-4b17-b200-9d60bfb962df)

![Component ID location Filter 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/89accf22-4a7d-43bb-a6f2-0dcfe644d502)
