### ISSUE TITLE
Address failing unit tests in Auth API repo

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4500]
FIx and Increase Unit Test Coverage for the following:
**src/utils/api/easeyAuthApi.test.js**

Easey Auth API › Can we refreshToken
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e8905b0a-f92e-4849-8163-f38b87849e7d)

Easey Auth API › Can we logOut
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/2f6f437a-18bd-4fb1-a691-d5054c843364)

**Comment by subrataroyCVP** [comment]
![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/4e7fbe51-1d95-43a6-a525-67edc9dce7fd)
