### ISSUE TITLE
Check Engine Testing App 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4508]
- Create automated test suite for Check Engine in its entirety (MP, QA, and Emissions) 

- [ ] Leverage ERG check engine scripts to load and test Check Engine

**Comment by MaeganWood64** [comment]
- to be completed after emissions conversion is done

**Comment by annalbrecht** [comment]
Closed ticket based on discussion with CAMD on 3/4/24. Before deployment there will be a scan performed and any issues will be remediated at that time.
