### ISSUE TITLE
508 Issue: Restructure MP Configurations Tab

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4512]
## Context 

Note: Previously the team discussed removing the revert to offical record from the QA module and only having the button under MP. The team may want to wait to address this issue until the revert to offical button is removed from QA 

**3 issues found for 4081:**

1. The revert to official record button has an incorrect tab order because the tabindex is set to 1 instead of 0
![image](https://user-images.githubusercontent.com/67421847/201791561-0208ac05-a45b-4a7f-91be-0dacbc6e8d1a.png)

2. The configuration is not part of the heading:
![image](https://user-images.githubusercontent.com/67421847/201792054-9c0acc4f-f238-4342-8ac4-fd11023d3301.png)

3. Heading levels for tables should be adjusted to H4 so it is hierarchy is under the Location/Configuration of H3. H3 at the level of Defaults in the screenshot below should be updated to H4
![image](https://user-images.githubusercontent.com/67421847/201792424-45a9ad1e-4082-42d3-8f33-552c1286ab9e.png)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4b9a7fca-a292-4145-8a60-8c4af70c394d)

**Comment by aprematta** [comment]
Issue 1 and 2 are fixed. For issue 3, it's still showing H3 instead of H4: 
![image](https://user-images.githubusercontent.com/67421847/205917765-7caea619-2baf-4e44-aaf3-f7b26cdca747.png)

**Comment by jordanfontainecvp** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/112484102/205999317-f6e9f4fc-885d-4b44-a072-19fee787034c.png)

**Comment by jordanfontainecvp** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/112484102/206008192-f6dec34a-2b60-424f-8490-ce6937899f74.png)

**Comment by aprematta** [comment]
Last issue resolved, headings confirmed to be at H4
