### ISSUE TITLE
Emissions Export: Automated Test Case Clean Up and Regression Testing 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4515]
As an ECMPS tester, I want to review and clean up emissions test cases so that I can start implementing automated test cases, as well as perform regression testing on the emissions export, to make sure all components are functioning as they should be and any new development has not introduced bugs.

**Comment by JanellC** [comment]
Clean up remaining Import/Export test cases will be addressed in #4521
