### ISSUE TITLE
Modify Facility DTO

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#452]
- [x] Modify Facility DTO per new contract
- [x] Add constructor for dummy data

API Url's
/facilities
/facilities/{id}

**Comment by sdhawan16** [comment]
Split ticket out - Monitor Plan DTOs now part of #506 (Will be part of the Monitor Plan API)

**Comment by sdhawan16** [comment]
Modified FacilityDTO and added LinkDTO based on the data contract. Added constructors to both files to use for dummy data.
