### ISSUE TITLE
Perform Audit of Streaming Service Unit Tests

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4520]
As an ECMPS developer, I want to review all existing unit tests to ensure they are all good well-written tests that serve a purpose. 

- [ ]  Remove/Modify any unit tests that the audit has determined are "bad" tests

- [ ] Comment in this ticket any files that have had unit tests removed as a result of this audit

**Comment by fanwari1** [comment]
All tests in the repo have been reviewed and found to be good tests.

There were no broken tests in the repo.
