### ISSUE TITLE
QA: Remove Revert to Official Button

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4523]
Remove the Revert to Official Record option from the QA screens

Invision Reference:
https://xd.adobe.com/view/6629a3fa-688f-4c99-9f80-d2e8abeffbaa-337a/

**Comment by mosesdeeCVP** [comment]
Button Removed

**Comment by mosesdeeCVP** [comment]
![Remove Revert to Official Button.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fdb0c78b-8c5c-447a-82c7-a3b52fe3d3da)
