### ISSUE TITLE
Test Only: Remove Test Qualification option from Test Type Group

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4524]
Remove the option 'Test Qualification' from the Test Type Group dropdown endpoint. 

Notes: Test Qualification is a sub-type applicable for RATA and should not be available as a separate Test Type Group 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/676a8261-cbda-4413-8500-a2002f21f6cb)

## Testing 
Test Case: [TC1103](https://epacamd.testquality.com/project/11428/plan/24660/test/410795)
Tester:  @JanellC

**Comment by subrataroyCVP** [comment]
The data for the Test Type Group dropdown is coming from the mdm-api endpoint `/master-data-mgmt/test-type-group-codes`. In order to remove `Test Qualification` Test type group, it needs to be deleted in the Database.

**Comment by JanellC** [comment]
TC1103 passed 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/54374af6-c136-480c-b7b5-d7d7d39c6391)
