### ISSUE TITLE
PI10 - QA Regression Testing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4525]
Complete regression testing for Add, Edit, View and Remove for the following Test Types:
Linearity Summary
Appendix E Correlation
Calibration Injection
Fuel Flow to Load
Flow to Load Check
Fuel Flow to Load Baseline
Online Offline Calibration

**Comment by JanellC** [comment]
Regression testing is completed. Bugs have been reported to @vishnunavuluri
