### ISSUE TITLE
Test Only 508: Download to CSV Focus Issue

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4533]
Visually, the Download to CSV button comes after the expand/collapse button. However, when tabbing through the page the Download to CSV button receives focus first. Adjust the positioning in the DOM to move the button after the heading:
image
![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/b0c469c7-a4c2-4a65-aaa1-177666ff10dd)

**Comment by aprematta** [comment]
The tab and programatic reading order are now correct
