### ISSUE TITLE
MP/QA Import not working

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4541]
Issue:

When a user uploads a file to import for MP/QA and clicks Import, then a spinner is displayed and it keeps spinning without any success.

**Comment by JanellC** [comment]
**MP**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f98dcdc0-c6fc-48e3-8aa6-9639810e1dba)

**Comment by JanellC** [comment]
Issue reamains for QA. The spinner keeps spinning and does not succesully import the file

**Comment by mosesdeeCVP** [comment]
The QA import does work, but the UI indicates there are some errors. This will be investigated in a different ticket. MP does not import as the UI is indicating there is an error. Will be investigated in a future ticket.
