### ISSUE TITLE
Pre-populate Component ID based on the Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4543]
Component ID should be pre-populated for Test Data and only allow values based on the location dropdown from the main screen (Configurations Screen)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ca926b26-9aa8-42c8-bc06-b2d4b679c970)

## Testing 
Test Case:[ TC1102](https://epacamd.testquality.com/project/11428/plan/24660/test/410792)
Tester: @JanellC

**Comment by JanellC** [comment]
Component ID is prepopulating in the edit and add modals based on the location
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a0bf8ab9-b538-4e1d-856d-def3a9435acd)
