### ISSUE TITLE
SPIKE: Knowledge Transfer Process for Runbook 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4547]
- The current state of the runbook is missing information regarding key features, functionality, and information on the project. Additional work is needed to develop a process that would fill in the knowledge gaps of completed features and properly document features once development work has been completed.

**Comment by JanellC** [comment]
Completed knowledge transfer process. Will add other tickets in the backlog to track the remaining work with the runbook
