### ISSUE TITLE
Account Name/Number Copy/Paste Bug

### ISSUE THREAD

**Issue by tlageman-epa** [US-EPA-CAMD/PI-1#4550]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a 
I want
So that

## Acceptance Criteria
Given a user inputs via copy/paste a set of account numbers separated by |
When the user hits enter
Then the filter should automatically search and pick the relevant account numbers and return an error message for those that do not exist

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
When inputting a vertical bar/pipe separated list of account numbers that include letters, the filter matching functionality does not work. For example, inputting 000003FACLTY | 000005FACLTY will return an error while 999900000002 | 999900000003 will work correctly selecting the matching accounts. This occurs in staging and dev. The functionality should work the same as it does in Facility Names/Ids in the facility filter except with account name/numbers instead of facility name/ids.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by acollad1** [comment]
Please use the link below to access the recording that reviews this ticket:
https://decisionpointcorp-my.sharepoint.com/personal/skhan_decisionpointcorp_com/_layouts/15/guestaccess.aspx?share=EcnurFMyQs1CmS5dgwPUumwBKZd7BIxxWo1OEI58M82pvA

**Comment by ergjustin** [comment]
PR: https://github.com/US-EPA-CAMD/easey-campd-ui/pull/609

**Comment by hamezene** [comment]
@tlageman-epa this has been merged to Dev, Please verify

**Comment by tlageman-epa** [comment]
@ergjustin do you know what date range of transaction data is available in dev? I can't test the account name/number filter in there unless i know what range of data is available to test since the data is date driven. Thx

**Comment by ergjustin** [comment]
@tlageman-epa Sorry, I don't know what date range of transaction data is available in dev. I don't believe that date range is necessary to test this ticket.

## Step to test

1. Navigate to https://campd-dev.app.cloud.gov/data/custom-data-download
2. Select Data Type as `Allowance` & Data Subtype as `Account Information` and `Apply`
3. In filter select `Account Name/Number` and copy paste `000003FACLTY | 000005FACLTY`  and press `Enter`
4. Check the values are accepting

**Comment by tlageman-epa** [comment]
I was able to check the transaction data streaming endpoint in dev and it looks like there is no data in there. I'm fine with accepting this ticket since I checked the other data types and they look good, but in the future I'd like to test everywhere possible regardless of if it is the same component,

**Comment by tlageman-epa** [comment]
looks good in staging

**Comment by ergjustin** [comment]
Production screenshot
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--477d3ca65f3d4d1042c62f84d40214fcdb55cfd7/accountNumber.PNG" alt="accountNumber.PNG" />
