### ISSUE TITLE
Unit/Stack Pipe ID: Display based on Location

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4556]
Unit/Stack Pipe ID is a dropdown field that currently displays all the values available in the Location dropdown. 

Scope: 
- Move the Unit/Stack Pipe ID as the first field in the modal
- It should be restricted to the option that the user has selected in the Location dropdown. Make the field a locked text field that a user is unable to update

See below:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/8397af74-77f6-4ced-8c73-0304304eb899)

## Testing 
Test Case: [TC114](https://epacamd.testquality.com/project/11428/plan/24660/test/411226)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Unit-Stack Pipe ID- Display based on Location 4556.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a19d0d79-072b-4aac-8050-60586059c914)

**Comment by mosesdeeCVP** [comment]
Test Passed
