### ISSUE TITLE
Test Reason Code and Test Result Code fields Disabled

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4557]
The Test Reason Code and the Test Result Code fields are dependent on a selection made in the Test Type Code field. Unless a user makes a selection for Test Type Code manually, the Test Reason and Result Code fields stay disabled. 

**Issue:** For Test Types where the Test Type Code is pre-populated (Linearity Summary, RATA, Flow to Load etc) in the Test Data section, the Test Reason Code and Result Code shall always remain disabled. User shall not be able to make a selection due to the dependency.

## Testing 
Test Case:[ TC1112](https://epacamd.testquality.com/project/11428/plan/24660/test/411219)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Test Reason Code and Test Result Code fields Disabled - 4557.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a0e806ba-2643-4d3f-924d-77d728372e66)

**Comment by mosesdeeCVP** [comment]
Test Passed
