### ISSUE TITLE
Bug: Test Summary Modal Displaying Invalid spanScaleCode error 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4560]
## Steps to Reproduce

1. Log in to ECMPS. 
2. Navigate to the QA Module of ECMPS
3. Select  Transmitter Transducer as a test type 
4. Add a test summary record 

The system displays an error stating that spanScaleCode is required for test Summary however, there is no spanScaleCode on this particular test type. (see below) 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f75dfc48-a056-43bb-98b3-a23d5d86ff52)

As apart of the scope of this bug, the spansScalecode error in the test summary modal needs to be removed for alll of the test summary records that do not contain spanScaleCode.

**Comment by mosesdeeCVP** [comment]
Bug fixed
