### ISSUE TITLE
Address Failing MP Unit Tests 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4573]
## Context 

src/components/MonitoringPlanTab/MonitoringPlanTab.test.js
src/components/MonitoringPlanHome/MonitoringPlanHome.test.js

**Comment by billmiller13** [comment]
![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/73274f80-b91f-46a3-9632-9fa091cca2f9)

![image.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/aa08f6e3-f842-4a3f-9aa1-3ef3ec1f1767)
