### ISSUE TITLE
Bug: Update vender id and cyclinder ID data label on the UI 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4581]
## Steps to Reproduce

Update  vender id and cyclinder ID to vender identifier and cyclinder identifier on the UI. These labels are displayed on the data tables and modals.  see below for an example. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/25601600-a34e-4841-bd9e-1e270196af19)

This change is applicable to the following test types: 
Linearity 
Appendix E
Rata 
Unit Default

**Comment by mosesdeeCVP** [comment]
![Cyl and Ven Identification.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/56d9b428-174c-426d-8c2f-42a8921c50ed)

![Cyl and Ven Identification Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4594f70d-4bfa-49cd-b3c6-d93bca601abd)

**Comment by mosesdeeCVP** [comment]
UI Bug fixed.
