### ISSUE TITLE
UI: Create Error Suppression Table Layout 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4587]
As an ECMPS admin, I want to see the error suppression table on the error suppression screen so that I can support program goals.

Given an EPA admin has logged into the ECMPS application
When the user navigates to the error suppression screen via the left-hand navigation
Then the user will see the error suppression table shell UI displayed with data

Note: This ticket only covers the UI layout not the functionality tables

https://projects.invisionapp.com/freehand/document/1dwq6maiy?zoomToItems=Y2xia3g3MHJvMDB4YzNiN203cG5tZ3Iwbw%3D%3D

**Comment by fanwari1** [comment]
Just a note that, some values in the api call were hard coded for this ticket, so that we can see data. The hard coded values will be removed once the ticket for apply filters button (4684) is done.

**Comment by fanwari1** [comment]
Also, the Critera column has been split into two columns, Match Data Criteria, and Match Time Criteria
