### ISSUE TITLE
API: Create GET Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4589]
As the ECMPS system, I need to have a "GET" endpoint implemented in order to support the functions of the error suppression module.

Check type code, number, and result equals check catalog result ID

**GET**        /camd-services/error-suppressions
Filter Parameters
- **checkTypeCode** (Required parameter)
- **checkNumber** (Required parameter)
- **checkResult** (Required parameter)
- severityCode (Drop-down in Swagger) 
- facilityId (orisCode)
- locations (Multi-select)
- reasonCode (Drop-down in Swagger) 
- beginDateHrQtr
- endDateHrQtr
- active

**Response** 
{
  “id”: int,
  “checkCatalogResultId”: int,
  “checkTypeCode”: string,
  “checkNumber”: int,
  “checkResultCode”: string,
  “severityCode”: string,
  “facilityId”: int, --this is the fac_id NOT the oris code
  “orisCode”: int,
  “locations”: string, --comma delimited list of location names
  “matchDataTypeCode”: string,
  “matchDataValue”: string,
  “matchTimeTypeCode”: string,
  “matchTimeBeginValue”: datetime,
  “matchTimeEndValue”: datetime,
  “matchHistoricalIndicator”: true or false,
  “reasonCode”: string,
  “note”: string,
  “active”: true or false,
  “userid”: string,
  “addDate”: datetime,
  “updateDate”: datetime
}

Date Range - mm-dd-YYYY
Hour Range - mm-dd-YYYY hh
Quarter Range – YYYY Q1

**Comment by sdhawan16** [comment]
Sample Required Parameters which have data:
checkTypeCode: QUAL,
checkNumber: 23,
checkResult: D
