### ISSUE TITLE
API: Create PUT Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4590]
As the ECMPS system, I need to have a "PUT" endpoint implemented in order to support the functions of the error suppression module.

**PUT**        /camd-services/error-suppressions/{id}
Note: No payload and only sets the record’s active column to false

**Response**
{
“id”: int,
“checkCatalogResultId”: int,
“checkTypeCode”: string,
“checkNumber”: int,
“checkResultCode”: string,
“severityCode”: string,
“facilityId”: int, --this is the fac_id NOT the oris code
“orisCode”: int,
“locations”: string, --comma delimited list of location names
“matchDataTypeCode”: string,
“matchDataValue”: string,
“matchTimeTypeCode”: string,
“matchTimeBeginValue”: datetime,
“matchTimeEndValue”: datetime,
“matchHistoricalIndicator”: true or false,
“reasonCode”: string,
“note”: string,
“active”: true or false,
“userid”: string,
“addDate”: datetime,
“updateDate”: datetime
}

**Comment by fanwari1** [comment]
To test, you can make  PUT request using an active error suppression record id. I've specifically set id=7 to be active so using the endpoint in this ticket, you can make this record inactive.

To do so, you first need to get a token from the Auth API by making a request that looks like:
```
curl --location --request POST 'https://api.epa.gov/easey/dev/auth-mgmt/authentication/sign-in' \
--header 'x-api-key: your api key' \
--header 'Content-Type: application/json' \
--data-raw '{
  "userId": "your user name",
  "password": "your password"
}'
```

Once you get the token you can make the following call to the endpoint that was added in this ticket:

```
curl --location --request PUT 'https://api.epa.gov/easey/dev/camd-services/error-suppressions/7' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-api-key: PXPWlQGB3wKXotkWN1PbSwbSoM7CoWW0ZMPWYtfc' \
--header 'Authorization: Bearer {enter your token}' \
--data-raw ''
```
