### ISSUE TITLE
API: Create POST Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4591]
As the ECMPS system, I need to have a "POST" endpoint implemented in order to support the functions of the error suppression module.

 **POST** /camd-services/error-suppressions
Request {
  “checkCatalogResultId”: int,
  “severityCode”: string,
  “facilityId”: int, --this is the fac_id NOT the oris code
  “locations”: string, --comma delimited list of location names
  “matchDataTypeCode”: string,
  “matchDataValue”: string,
  “matchTimeTypeCode”: string,
  “matchTimeBeginValue”: datetime,
  “matchTimeEndValue”: datetime,
  “matchHistoricalIndicator”: true or false,
  “reasonCode”: string,
  “note”: string,
}

- es_spec_id is auto generated by the database
- di is no longer needed and should default to null
- active_ind should default to 1

Match Time beginValue and endValue date time formats…
- Date Range -  YYYY-mm-dd 00:00:00
- Hour Range -  YYYY-mm-dd hh:00:00
- Quarter Range - YYYY-mm-dd 00:00:00 (use the quarter begin and end dates)

**Response**
{
  “id”: int,
  “checkCatalogResultId”: int,
  “checkTypeCode”: string,
  “checkNumber”: int,
  “checkResultCode”: string,
  “severityCode”: string,
  “facilityId”: int, --this is the fac_id NOT the oris code
  “orisCode”: int,
  “locations”: string, --comma delimited list of location names
  “matchDataTypeCode”: string,
  “matchDataValue”: string,
  “matchTimeTypeCode”: string,
  “matchTimeBeginValue”: datetime,
  “matchTimeEndValue”: datetime,
  “matchHistoricalIndicator”: true or false,
  “reasonCode”: string,
  “note”: string,
  “active”: true or false,
  “userid”: string,
  “addDate”: datetime,
  “updateDate”: datetime
}

**Comment by sdhawan16** [comment]
Sample Request: 
{
  "checkCatalogResultId": 656,
  "severityCode": "NONE",
  "facilityId": 846,
  "locations": "1,2",
  "matchDataTypeCode": "PARAM",
  "matchDataValue": "FLOW",
  "matchTimeTypeCode": "QUARTER",
  "matchTimeBeginValue": "2023-01-31T00:14:11",
  "matchTimeEndValue": "2023-01-31T00:14:11",
  "matchHistoricalIndicator": true,
  "reasonCode": "BUG",
  "note": "test"
}
