### ISSUE TITLE
Bug: QA Import from historical data not working 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4596]
## Steps to Reproduce
1. Login into ECMPS 
2. Navigate to the QA module 
3. Check out a config 
4. Select Import Data 
5. Select continue

The system defaults to the current year and quarter. Since there is no data associated with those the spinner keeps spinning. Additionally, the system displays an error message in the background. See below 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dcfa8021-2fa3-40db-9fad-25ff9f4cb655)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/02668c0c-d591-4f82-b293-9a82723a10d3)
 

**To fix this issue implement the following things:** 
1. Disable the preview button if the end date has not passed 
2. Do not call the API on load. DO not call the api until the user has selected preview

**Comment by subrataroyCVP** [comment]
Pull Request: 
https://github.com/US-EPA-CAMD/easey-mdm-api/pull/137
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/798

**Comment by mosesdeeCVP** [comment]
Bug fixed
