### ISSUE TITLE
Bug: MP export button not working 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4597]
## Steps to Reproduce

1. Log in to ECMPS 
2. Navigate to the MP module 
3. Check out a config 
4. Select the Export data button

When the user selects the export button under MP nothing happens.
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ad9aa8bf-b0bb-4859-9d27-fc399b4411bb)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
