### ISSUE TITLE
Bug: Format errors with QA modals

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4598]
## Steps to Reproduce
**Issue 1:** 

1. Log in to ECMPS 
2. Select a config 
3. Select Linearity Summary as a test type 
4. View a protocol gas record 

**The following issues are present In Modal view:** 
1. Expiration Date is showing "undefined/undefined/"
2. Remove Summary Type from in front of Gas Level Code under Protocol Gas Code section

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b90ed8e6-8ef2-4346-87c0-a45ab1a6d649)

**Issue 2:** 
The system is not showing the test type code. Instead, it is displaying select a value. This is happening for Fuel Flow to Load, Test Qualification, and Flow to Load Check

1. Log in to ECMPS 
2. Select a config 
3. Select Fuel Flow to Load, Test Qualification, or  Flow to Load Check as a test type 
4. View a record 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f2f54cb4-391c-4408-b958-31ffa34f45f1)

**Comment by vishnunavuluri** [comment]
1/5/2022: @JanellC @mosesdeeCVP Corey and I tried recreating the issue with the Expiration Date and Test Type Code. We couldn't in the dev env, but please ping us if you see it when testing. Thanks

**Comment by mosesdeeCVP** [comment]
Expiration Date and Test Type Codes are showing up fine. The Gas Type code is not showing up due to it having multiple codes. This will be resolved in a different ticket.

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
Test Type Code
![Test Type Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/014706af-9472-4c8c-b8cd-76750ed31109)

**Comment by mosesdeeCVP** [comment]
Protocol Gas
![Protocol Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a2850e1f-285e-4113-87da-2ccbe62739fa)
