### ISSUE TITLE
Unit default data missing air emissions and protocol gas??? 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4599]
## Context 
https://www.epa.gov/system/files/documents/2022-06/ECMPS_QA_Reporting_Instructions_0.pdf

According to the reporting instructions unit default data should have air emissions and protocol gas records. 
There weren't any tickets in the backlog for this. need to double check with the EPA

**Comment by vishnunavuluri** [comment]
Shall be added as part of UI tickets for Unit Default Test Data
