### ISSUE TITLE
Bug: Test Summary Modal displaying a minute field error 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4600]
## Steps to Reproduce

Login to ECMPS 
Navigate to the QA module 
Select Fuel Flow to Load Baseline  or Online/Offline as a test type 
Add a Test Summary record. 

**This is a backend issue.** The system is displays a minute feild error message when minute field is not on the modal. As apart of the scope of this ticket need to address this error for  Fuel Flow to Load Baseline  and Online/Offline test types. Also ensure this is not happening for any other test types 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/5970589c-6dfc-4d3a-a753-f84b879a1b66)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/af68c0ac-31e2-429e-8725-f7bd00e5fc0e)

**Comment by subrataroyCVP** [comment]
Pull Requests:
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/338
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/339

**Comment by mosesdeeCVP** [comment]
Bug Fixed
