### ISSUE TITLE
Increase Unit Test Coverage for Emissions API Part 3

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4603]
As an ECMPS developer, I want to increase Unit Test Coverage for Emissions API to at least 70% (aiming for 80%) 

- [ ] Aim to have every emission module to reach 80% unit test coverage 

The following modules need additional tests to reach 80% coverage:

monitor-system-workspace - 0%
nsps4t-summary - 59.09%
nsps4t-summary-workspace - 34.14%
sorbent-trap - 57.89%
sorbent-trap-workspace - 47.05%
summary-value-functions - 63.63%

**Comment by fanwari1** [comment]
Coverage info after the changes:
monitor-system-workspace - deleted as it was not being used by anything in the repo
nsps4t-summary - 100%
nsps4t-summary-workspace - 95.12%
sorbent-trap - 100%
sorbent-trap-workspace - 96.66%
summary-value-functions - 100%
