### ISSUE TITLE
Bug: Implement Multi Select on Gas Type code dropdown

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4606]
## Steps to Reproduce
1. Log in to ECMPS 
2. Select a config 
3. Select Linearity Summary as a test type 
4. View a protocol gas record 

**The following issues are present In Modal view:** 
Gas Type Code field is showing "-- Select a value --". Global logged out View.

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f4718695-83ff-4bea-baf7-81105f468317)

**Notes from refinement on 12/28: Gas type code shows select a value when there are multiple gas types. Will need to have further discussion with the EPA on making gas type code a multi select drop down**

**Comment by vishnunavuluri** [comment]
RATA - Global-view for Glen Lyn:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c1bcd97d-3f54-4e23-ad6d-e444e12b2154)

**Comment by vishnunavuluri** [comment]
RATA - Workspace for Glen Lyn:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/2d57e580-0660-4843-9cdc-8b0b2904e82b)

**Comment by vishnunavuluri** [comment]
RATA - Workspace for Glen Lyn - Add Protocol Gas Data:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e336e23d-5d5a-46f2-9094-afe05273827c)

**Note: Multi-select needs 508 testing**
