### ISSUE TITLE
Bug: Oris Code Format Inconsistent 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4607]
## Context 

The format of Oris Code is inconsistent between the the backend api and the UI. The backend api is formating oris code as a string ,but the UI is formatting oris code as a number.  Oris code should be a number. 

## Steps to Reproduce

**Issue 1;** 
1. Export a MP or a QA file using Postman or swagger (Oris code exports as a string) 
2. Import the MP or QA file on the ECMPS UI  

The system displays an error message for Oris Code. Postman is exporting the ORIS code as a a string when it should be a number. 

**Issue 2:** 
1. Export a MP or a QA file using the ECMPS UI (Oris code exports as a number) 
2. Import the MP or QA file using  Postman or swagger 

The system displays an error message for Oris Code. The UI is exporting ORIS code as a number.The UI is exporting oris code correctly however the backend api is looking for a string.

**Comment by subrataroyCVP** [comment]
Pull Request:
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/344

**Comment by mosesdeeCVP** [comment]
Backend and Front end are now in sync both Formatting as Number
