### ISSUE TITLE
Bug: QA Schema & Export Property names not aligned (Backend Update)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4609]
## Context 
There are discprencies between schema qa schema labels and an exported qa file. 

**Note: Please scroll to the end to review issue 2**

## Steps to Reproduce
1. Export a clean Qa file from ECMPS UI 
2. Import the QA file back into the UI 

The system displays the following errors. 

instance.testSummaryData[0].flowToLoadCheckData[0] requires property "avgAbsolutePercentDiff"
instance.testSummaryData[0].flowToLoadCheckData[0] requires property "numberOfHoursExcludedRamping"
instance.testSummaryData[0].flowToLoadCheckData[0] requires property "numberOfHoursExcludedBypass"
instance.testSummaryData[0].flowToLoadCheckData[0] requires property "numberOfHoursExcludedPreRATA"
instance.testSummaryData[0].flowToLoadCheckData[0] requires property "numberOfHoursExcMainBypass"
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b1e6838f-8fbb-4362-90af-1916dffc7bb6)

ECMPS 1.0 XML Schema
![image](https://user-images.githubusercontent.com/66504934/211907480-d07ffe3c-e754-4f72-ba43-c020a35539d9.png)

ECMPS 2.0 JSON Schema
"FlowToLoadCheck": {
      "title": "FlowToLoadCheck",
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "testBasisCode": {
          "type": [
            "string",
            "null"
          ]
        },
        "biasAdjustedIndicator": {
          "type": [
            "number",
            "null"
          ]
        },
        "avgAbsolutePercentDiff": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcludedForFuel": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcludedRamping": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcludedBypass": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcludedPreRATA": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcludedTest": {
          "type": [
            "number",
            "null"
          ]
        },
        "numberOfHoursExcMainBypass": {
          "type": [
            "number",
            "null"
          ]
        },
        "operatingLevelCode": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "testBasisCode",
        "biasAdjustedIndicator",
        "avgAbsolutePercentDiff",
        "numberOfHours",
        "numberOfHoursExcludedForFuel",
        "numberOfHoursExcludedRamping",
        "numberOfHoursExcludedBypass",
        "numberOfHoursExcludedPreRATA",
        "numberOfHoursExcludedTest",
        "numberOfHoursExcMainBypass",
        "operatingLevelCode"
      ]
    }

Export JSON
"flowToLoadCheckData": 
        {
          "testBasisCode": "string",
          "biasAdjustedIndicator": 0,
          "averageAbsolutePercentDifference": 0,
          "numberOfHours": 0,
          "numberOfHoursExcludedForFuel": 0,
          "numberOfHoursExcludedForRamping": 0,
          "numberOfHoursExcludedForBypass": 0,
          "numberOfHoursExcludedPreRata": 0,
          "numberOfHoursExcludedTest": 0,
          "numberOfHoursExcludedForMainAndBypass": 0,
          "operatingLevelCode": "string"
        }

**Issue 2: QA Import from file not working**
 
In the global view export a clean QA file (ex. Barry 1,2,CS0AAN year-2008 quarter-q1) 
Log into ECMPS 
Check out the config associated with the export file 
Select Import from file 
Import the clean QA file 

The system displays schema errors. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dddd4a82-2ff2-4aeb-ab33-87edafc45ae9)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/394

**Comment by JanellC** [comment]
System is not displaying schema validations when importing a clean QA file.  An additional issue was discovered with QA import where the backend api returns errors when a user imports a clean qa file.  @vishnunavuluri will track a bug in the backlog for the newly discovered issue
