### ISSUE TITLE
Update the Left-hand Menu

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4618]
As an ECMPS user, I need the left-hand menu options updated so I can access QA Cert Events data and QA Test Extension Exemption Data from the same screen

**Acceptance Criteria: Applicable to both the Global-view and the Workspace**

Given I am an ECMPS user reviewing the options in the left-hand menu
When I see under QA & Certifications section
Then I see the following sub-options:

- Test Data
- Cert Events, Extensions& Exemptions

Refer to the following reference lo-fi: https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2YjNjMDB4MDBvZjNiNnllNjAwZTk3MA%3D%3D

Given I am reviewing the options under the QA & Certifications section in the left-hand menu
When I click on Cert Events, Extensions& Exemptions
Then I am navigated to the Select Configurations screen
**Screen Title:** QA Cert Event Data & Test Extension Exemption Data

Given I am on the Select Configurations screen
When I select a Configuration and Open/Open & Checkout
Then I am navigated to the individual Configuration screen

Given I am on the individual Configuration screen
When I click on the Test Data dropdown
Then I see the following options:
- QA Certification Event 
- Test Extension Exemption 

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/836e9806-c892-4fba-b483-8f89402a7f0f)

## Testing: 
Test Case:[ TC1191](https://epacamd.testquality.com/project/11428/plan/28527/test/417163)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1191 failed. See  Bug: Update Left Nav #4643
