### ISSUE TITLE
Fix focus on the Import Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4619]
**Issue:**
When a user opens the Import modal, uploads a file and exits out of the modal/closes it - then the focus is lost

**Resolution:**
Once a user exists out of the Import modal or closes it, then the focus should not be lost and should be retained on the Import button/option

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/52ee4d05-9293-47e5-a1e8-8e9ed7f157e1)

**Comment by cw-cvp** [comment]
-focus is retained on "Import Data" button after closing at any point in the import process
-fixed "setUpdateRelatedTables is not a function" after closing success modal from importing There should be no error when closing with either the "x" button or the "Ok" button
![image.png](https://images.zenhubusercontent.com/629e4ba8bc6cd374484822a8/8da84fcc-d9ec-4f85-8e9b-0a6785d6abfe)

**Comment by aprematta** [comment]
Testing complete, focus is now placed on import in all scenarios
