### ISSUE TITLE
508: Emissions Main UI Focus Issues

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4623]
Given a user has navigated to the emissions module page either in logged in or logged out view
When the user selects and opens a specific configuration
Then the focus should remain on the configurations selected

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/ddad9cf9-b222-4f60-8b3b-28c3447c1207)

**Comment by acollad1** [comment]
@aprematta  Ticket 4623 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071. This also marks the last emissions development ticket we had planned so we are ready for the full 508 scan in the emissions module as well at your earliest convenience. Thanks!

**Comment by aprematta** [comment]
Testing complete, focus now stays on the configuration
