### ISSUE TITLE
Global 'View' and Workspace 'Add': QA Certification Events

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4627]
As an ECMPS user, I want to view QA Certification Event Data in the Global-View and add new QA Certification Event Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected QA Certification Event from the Test Data dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

**Columns:**
Unit or Stack Pipe ID
Monitoring System ID
Component ID
QA Cert Event Code
QA Cert Event Date
QA Cert Event Hour
Required Test Code
Conditional Begin Date
Conditional Begin Hour
Completion Test Date
Completion Test Hour 

Given a user is viewing QA Certification Event data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected QA Certification Event from the Test Data dropdown 
When the user clicks on 'Add' for QA Certification Event Data 
Then the system displays a modal
and the user can add new data for:

Unit or Stack Pipe ID (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
QA Cert Event Code (Dropdown)
QA Cert Event Date (Datepicker and Text)
QA Cert Event Hour (Dropdown)
Required Test Code (Dropdown)
Conditional Begin Date (Datepicker and Text)
Conditional Begin Hour (Dropdown)
Completion Test Date (Datepicker and Text)
Completion Test Hour (Dropdown)

Given the user has added QA Certification Event data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the QA Certification Event data record is reflected on the UI

Given the user has added a new QA Certification Event data
When the user chooses to Cancel
Then the user is returned to the Landing screen for QA Certification Event data
And no updates are saved

## Testing 
Test Case: [TC1196](https://epacamd.testquality.com/project/11428/plan/28427/test/419437)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
QA Certification Events Official View Table
![QA Certification Events Official View Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/21cb460a-fb09-45d4-bf4b-b1fdd63c0200)

**Comment by mosesdeeCVP** [comment]
QA Certification Events Official View Modal
![QA Certification Events Official View Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/768aa2ea-b5c3-4f8b-a19e-ef21313e1d38)

**Comment by mosesdeeCVP** [comment]
QA Certification Events Workspace Add
![QA Certification Events Workspace Add.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/36263d29-d29c-4521-9830-b64d110134ce)

**Comment by mosesdeeCVP** [comment]
Test Passed
