### ISSUE TITLE
Remove QA Certification Events Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4629]
As an ECMPS user, I want the ability to remove QA Certification Event data so that I can update data as needed

Acceptance Criteria:
Given I am in the QA Certification Event data section
When I click on the 'Remove' option
Then I see that the relevant QA Certification Event data record is deleted

Given I chose to remove QA Certification Events Data
When I click on the 'Remove' option
Then I see a message 'Are you sure you want to remove the selected data?'
And when I click Yes
Then the data is removed
And the update shall be reflected in the QA Certification Events data section
When I select Cancel
Then I am returned to the landing screen for QA Certification Event Data

## Testing 
Test Case: [TC1199](https://epacamd.testquality.com/project/11428/plan/28427/test/419440)
Tester:  @JanellC

**Comment by JanellC** [comment]
TC1199 Passed 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/20356deb-51ca-4de6-a8d8-09f5af0dd7c4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0874bbee-4892-41df-89e2-2be80bcd679d)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/60119fa8-2a8d-49f4-9d76-4c5fbdff29f8)
