### ISSUE TITLE
Add QA Test Extension Exemption data elements to the Export Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4630]
Add QA Test Extension Exemption data elements to the Export Endpoint (Global-view and workspace)

## Testing 
For testing purposes: Utilize Joliet 29 (Oris 384) CS7172 for testing. Has TEE Data in global 

Test Case:[ TC1208](https://epacamd.testquality.com/project/11428/plan/28527/test/421155) 
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
testExtensionExemptionData Official EXPORT
![testExtensionExemptionData Official EXPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ca1807f3-9bc4-4fe4-8d4f-f30c6f98e055)

**Comment by mosesdeeCVP** [comment]
testExtensionExemptionData Workspace EXPORT
![testExtensionExemptionData Workspace EXPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d1518988-793c-44db-82ae-423d07dca241)

**Comment by mosesdeeCVP** [comment]
Test Passed
