### ISSUE TITLE
Add QA Test Extension Exemption data elements to the Import Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4631]
Add QA Test Extension Exemption data elements to the Import Endpoint

**Comment by mosesdeeCVP** [comment]
testExtensionExemptionData Workspace Import
![testExtensionExemptionData Workspace Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e04e8fc4-bb13-474b-81ac-fea379e6cd9a)

**Comment by mosesdeeCVP** [comment]
![testExtensionExemptionData IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/adf7ef13-4613-439f-ba4b-b8056d2f4183)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1217](https://epacamd.testquality.com/project/11428/plan/28527/test/421627)
Test Passed
