### ISSUE TITLE
MP Evaluate throwing an Undefined Undefined Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4638]
Issue:

When a user clicks on Evaluate for a MP that is available for evaluation, then the application throws an Undefined error and the screens reverts to Evaluate again

Steps to recreate:
- Login o ECMPS
- Open and checkout any Configuration for a Facility where the MP is available for Evaluation
- Click on Evaluate

See screenshot below for the issue:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1d70f04d-1134-40a5-a0f4-1473184b242e)

**Comment by JanellC** [comment]
The system is no longer showing the undefined error. An additional bug has been logged on the tech team board for the evaluation status not properly updating @vishnunavuluri 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c9286bfc-d933-4b49-bd6a-1a3d78aff98f)
