### ISSUE TITLE
Streaming App Crash 499 Error

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4639]
- Starting in December, the streaming app crashed periodically with a 499 status code. Most resulted from the Freshping Monitor, but others were requests from the emissions api and the campd ui 

**Dev Notes**

- [ ] Look at and refactor Freshping streaming checks to ensure that request is not too large 

- [ ] revisit after deployment is updated to see if issue is resolved

**Comment by JanellC** [comment]
Will sit in PI backlog unless it becomes a PROD issue. Will not be able to estimate this issue until the team has a chance to look into it.

**Comment by ergjustin** [comment]
Is there any possible way to generate this issue again? I was not able to regenerate this bug in Dev environment.

**Comment by annalbrecht** [comment]
Not able to replicate. This may be resolved. Will open a new ticket if needed.
