### ISSUE TITLE
Bug: Update Left Nav

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4643]
## Test Case
[TC1191](https://epacamd.testquality.com/project/11428/plan/28527/test/417163)

## Steps to Reproduce
**Issue 1: opening a config in global**
1. In the global view, Select Cert Events, Extensions& Exemptions
2. Open a configuration 

The system crashes and does not open the configuration 

**Issue 2: Opening a config in Workspace** 

1. Log into ECMPS
2. Select Cert Events, Extensions& Exemptions
3. Attempt to open select a config 

The system does not display the option to open or checkout a config. See below 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/fe6d0f1e-a779-477e-87fb-6c2182820901)

## Requirements

As an ECMPS user, I need the left-hand menu options updated so I can access QA Cert Events data and QA Test Extension Exemption Data from the same screen

**Acceptance Criteria: Applicable to both the Global-view and the Workspace**

Given I am an ECMPS user reviewing the options in the left-hand menu
When I see under QA & Certifications section
Then I see the following sub-options:

- Test Data
- Cert Events, Extensions& Exemptions

Refer to the following reference lo-fi: https://projects.invisionapp.com/freehand/document/areRdzxWH?zoomToItems=Y2w2YjNjMDB4MDBvZjNiNnllNjAwZTk3MA%3D%3D

Given I am reviewing the options under the QA & Certifications section in the left-hand menu
When I click on Cert Events, Extensions& Exemptions
Then I am navigated to the Select Configurations screen
**Screen Title:** QA Cert Event Data & Test Extension Exemption Data

Given I am on the Select Configurations screen
When I select a Configuration and Open/Open & Checkout
Then I am navigated to the individual Configuration screen

Given I am on the individual Configuration screen
When I click on the Test Data dropdown
Then I see the following options:
- QA Certification Event 
- Test Extension Exemption 

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/836e9806-c892-4fba-b483-8f89402a7f0f)

**Comment by JanellC** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/epacamd/project/11428?defectId=13349)
- Test [Update the Left-hand Menu](https://web.testquality.com/site/epacamd/project/11428/runs/174461?resultId=3125013) in Run [Update the Left-hand Menu](https://web.testquality.com/site/epacamd/project/11428/runs/174461) (linked to Cycle [Test Extensions Exemptions Data](https://web.testquality.com/site/epacamd/project/11428/cycles/28527)).

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![Select Cert Events, Extensions and Exemptions - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c61099fc-b573-4e8c-a767-2da7b0aac1bb)

![Select Cert Events, Extensions and Exemptions - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/34d5882b-f752-449a-9d47-710065baa056)

![Select Cert Events, Extensions and Exemptions - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5a8c6072-1bed-4dce-bc3f-64544f1561ab)

![Select Cert Events, Extensions and Exemptions - 04.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/91eef3c5-9756-4a1a-9b45-cd3cc37d321c)
