### ISSUE TITLE
Test Only: Refactor Check Result Messages for Test Summary Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4644]
The scope of this ticket includes doing regression testing on the ALL the test summary modals to ensure error messages are displaying as expected.[https://app.zenhub.com/files/287570343/45d5dc88-0d7b-4819-a10d-d2fb149579b0/download](https://app.zenhub.com/files/287570343/45d5dc88-0d7b-4819-a10d-d2fb149579b0/download)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1197](https://epacamd.testquality.com/project/11428/plan/28527/test/419438)
Test Passed

**Comment by mosesdeeCVP** [comment]
[ECMPS QA/Cert Data Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

[ECMPS Import Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20Import%20Check%20Specifications%202018Q2.pdf)
