### ISSUE TITLE
QA Test Data - DTO Checks

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4647]
The scope of this ticket is to address the following DTO Checks:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] SEVNDAY-28 - 7-Day Calibration Test Result Code Valid
- [x] SEVNDAY-30 - 7-Day Calibration Test Component ID Valid
- [x] APPE-45 - Gas Monitoring System ID Valid
- [x] APPE-47 - Appendix E Monitoring System ID Valid
- [x] CYCLE-21 - Cycle Time Injection Gas Level Code Valid
- [x] CYCLE-22 - Component ID Valid

**Comment by mosesdeeCVP** [comment]
SEVNDAY-28 - 7-Day Calibration Test Result Code Valid

SEVNDAY-28-A Import
![SEVNDAY-28-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b00f40a5-4c75-4c88-88ef-31fad414e45d)

SEVNDAY-28-B Import
![SEVNDAY-28-B Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/066d57a0-d1ac-4b08-ae2f-5d833315ff5c)

SEVNDAY-28-C Import
![SEVNDAY-28-C Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/27a59473-7e06-4b34-a561-ee035213a836)

SEVNDAY-28-A POST
![SEVNDAY-28-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/166d6b4c-14ae-42b1-85ba-0c89415251e2)

SEVNDAY-28-B POST
![SEVNDAY-28-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dd465c3e-13a1-4c5f-b893-9d6fe85937cc)

SEVNDAY-28-C POST
![SEVNDAY-28-C POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/27f94b40-a392-4a04-aef5-6abfb5cf5182)

SEVNDAY-28-A EDIT
![SEVNDAY-28-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/22171c97-2a78-4f18-87fa-533bce0327c2)

SEVNDAY-28-B EDIT
![SEVNDAY-28-B EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ee805822-52a5-4852-a235-4c7bfc074a9d)

SEVNDAY-28-C EDIT
![SEVNDAY-28-C EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7d61e4e2-c482-44ce-a39c-4d3d5795ca4b)

**Comment by mosesdeeCVP** [comment]
SEVNDAY-28 - 7-Day Calibration Test Result Code Valid

**Comment by mosesdeeCVP** [comment]
SEVNDAY-30 - 7-Day Calibration Test Component ID Validations

SEVNDAY-30-A Import
![SEVNDAY-30-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e3a56734-9470-4010-84d7-c54c69c94285)

SEVNDAY-30-A POST
![SEVNDAY-30-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e9b2794c-f65f-4d4b-89ef-0090ffecfb44)

SEVNDAY-30-A EDIT
![SEVNDAY-30-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9bdbb92f-3aba-45cc-8338-d1875d394ba8)

**Comment by mosesdeeCVP** [comment]
7DAY  28 and 30
Test Case: [TC1213](https://epacamd.testquality.com/project/11428/plan/27529/test/421313)
Test Passed

**Comment by mosesdeeCVP** [comment]
APPE-47 - Appendix E Monitoring System ID Valid

APPE-47-A Import
![APPE-47-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/219e8ca8-d001-4136-a925-af51f63c4d26)

APPE-47-A POST
![APPE-47-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6f61cdc6-52c9-4625-b1f9-0b166dd14bf7)

APPE-47-A EDIT
![APPE-47-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/eac92ece-ab35-4caa-b6d8-060f2cacd606)

**Comment by mosesdeeCVP** [comment]
APPE-45 - Gas Monitoring System ID Valid

APPE-45-A Import
![APPE-45-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/48ed2749-28cb-485e-a37e-f235a36ba9f4)

APPE-45-A POST
![APPE-45-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a2616dbc-e266-47a6-93f4-1a8641d67b30)

APPE-45-A EDIT
![APPE-45-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cf4531ba-1f98-4b4e-a0a2-179c50e92972)

**Comment by mosesdeeCVP** [comment]
APPE-45-A
Test Case: [TC1214](https://epacamd.testquality.com/project/11428/plan/27381/test/421314)
Test Passed

**Comment by mosesdeeCVP** [comment]
CYCLE-21 - Cycle Time Injection Gas Level Code Valid

CYCLE-21-A POST
![CYCLE-21-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/788ecd16-42bb-446a-aacd-ba2569944f04)

CYCLE-21-A EDIT
![CYCLE-21-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/78b316ce-56cc-44f6-8432-6704a40ae8f4)

CYCLE-21-A Import
![CYCLE-21-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0f0712f7-f857-466a-b813-afc323ca5bbd)

CYCLE-21-B Import
The Import is not working properly so I cannot confirm this one. I have no reason to believe it does not work as all other are functioning properly. 

CYCLE-21-B POST
![CYCLE-21-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/020a5e2a-46a3-45ba-b5b5-0039564cb875)

CYCLE-21-B EDIT
![CYCLE-21-B EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e3205442-305b-44ee-ac2e-aa83a59b75c9)

**Comment by mosesdeeCVP** [comment]
CYCLE-21 - Cycle Time Injection Gas Level Code Valid

CYCLE-21-A POST
![CYCLE-21-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/788ecd16-42bb-446a-aacd-ba2569944f04)

CYCLE-21-A EDIT
![CYCLE-21-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/78b316ce-56cc-44f6-8432-6704a40ae8f4)

CYCLE-21-A Import
![CYCLE-21-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0f0712f7-f857-466a-b813-afc323ca5bbd)


CYCLE-21-B Import
The Import is not working properly so I cannot confirm this one. I have no reason to believe it does not work as all other are functioning properly.

**Comment by mosesdeeCVP** [comment]
CYCLE-21-B Import
The Import is not working properly so I cannot confirm this one. I have no reason to believe it does not work as all other are functioning properly.

**Comment by mosesdeeCVP** [comment]
CYCLE-22 - Component ID Valid

CYCLE-22-A Import
![CYCLE-22-A Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7c11f5a2-0945-4206-aeb7-8d29f2316be5)

CYCLE-22-A POST
![CYCLE-22-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fcf05fe4-3a67-46c0-b554-3d840e5df889)

CYCLE-22-A EDIT
![CYCLE-22-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b4e8d35d-7f8a-4d58-b300-b94c82e92633)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1215](https://epacamd.testquality.com/project/11428/plan/27813/test/421315)
Test Passed
