### ISSUE TITLE
QA Checks - Duplicate Test Summary

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4648]
The scope of this ticket is to address the following Check:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] F2LCHK-18 - Duplicate Flow to Load Check
- [x] TEST-19 - Duplicate Miscellaneous Test
- [x] F2LREF-14 - Duplicate Flow to Load Reference Data

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/397

**Comment by mosesdeeCVP** [comment]
F2LCHK-18-A POST
![F2LCHK-18-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/12a4faf0-d200-480f-8f74-7b42d36aa59e)

F2LCHK-18-A IMPORT
![F2LCHK-18-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dfe31287-8115-4146-8512-12908db5b196)

F2LCHK-18-B POST
![F2LCHK-18-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/95688549-54b6-48f5-8273-5ce3e2489e97)

F2LCHK-18-B IMPORT
![F2LCHK-18-B IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e46fc03-bab1-4c0f-8c5d-34a485ef6211)

**Comment by mosesdeeCVP** [comment]
TEST-19-A POST
![TEST-19-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c7334a54-1f12-40cb-b59c-7d7d3f9aad07)

TEST-19-A IMPORT
![TEST-19-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/011464f6-0787-40cc-9a31-d423765ea774)

TEST-19-B IMPORT
![TEST-19-B IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/995785f1-dd29-47f7-8d3f-973cd6d170c6)

TEST-19-B POST
![TEST-19-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d0de6cfc-eb52-42ac-b340-8470684d824a)

**Comment by mosesdeeCVP** [comment]
F2LREF-14-A POST
![F2LREF-14-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/96a8f6c3-1047-4ee0-a813-84c556a15be8)

F2LREF-14-A IMPORT
![F2LREF-14-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ef07d12b-b38e-40e1-94e0-2e52648e8b66)

F2LREF-14-B POST
![F2LREF-14-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4298ff7c-4d24-48a3-a5ea-8ea31584b2df)

F2LREF-14-B IMPORT
![F2LREF-14-B IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e6c8e4d6-ab37-4d24-8fc2-6866fc024258)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC2126](https://epacamd.testquality.com/project/11428/plan/23995/test/431174)
Test Passed
