### ISSUE TITLE
QA Checks - For Duplicate Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4649]
The scope of this ticket is to address the following Checks to verify any duplicate records being input:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] SEVNDAY-29 - Duplicate Calibration Test
- [x] APPE-46 - Duplicate Appendix E Test
- [x] APPE-48 - Duplicate Appendix E Summary
- [x] APPE-49 - Duplicate Appendix E Run
- [x] APPE-50 - Duplicate Appendix E Oil Record
- [x] APPE-51 - Duplicate Appendix E Gas Record
- [x] CYCLE-19 - Duplicate Cycle Time Test
- [x] CYCLE-20 - Duplicate Cycle Time Injection

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1219](https://epacamd.testquality.com/project/11428/plan/23995/test/421790)

**Comment by mosesdeeCVP** [comment]
SEVNDAY-29-A POST
![SEVNDAY-29-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/068d40aa-5e09-47a1-8830-c3aedf14e6d5)

SEVNDAY-29-A IMPORT
![SEVNDAY-29-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/abaf6653-ce33-4f2e-aee0-a78915432ea9)

**Comment by mosesdeeCVP** [comment]
APPE-46-A IMPORT
![APPE-46-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/28bd63c0-9b2b-440b-9992-120f578d6ba2)

APPE-46-A POST
![APPE-46-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ab11d17a-75a6-4298-bdd8-72c3f3c2c405)

**Comment by vishnunavuluri** [comment]
Closing and the rest of the checks shall be tested as part of 4709 and 4710
