### ISSUE TITLE
QA Checks - Duplicate Records (2)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4650]
The scope of this ticket is to address the following Checks to verify any duplicate records being input:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] TEST-19 - Duplicate Miscellaneous Test
- [x] LINEAR-31 - Duplicate Linearity
- [x] ONOFF-38 - Duplicate Online Offline Calibration Test
- [x] FFACCTT-13 - Duplicate Transmitter Transducer Test
- [x] UNITDEF-28 - Duplicate Unit Default Test
- [x] RATA-106 Duplicate RATA

**Comment by subrataroyCVP** [comment]
Pull Request: 
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/373

**Comment by mosesdeeCVP** [comment]
LINEAR-31-A IMPORT
![LINEAR-31-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/99113714-3dc8-4eaf-974b-1b84528c86e4)

LINEAR-31-A POST
![LINEAR-31-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2987c2e8-d445-48dc-b805-c27bd44b28a2)

**Comment by mosesdeeCVP** [comment]
ONOFF-38-A IMPORT
![ONOFF-38-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9179eb65-e25f-4877-94e1-559f41907ee6)

ONOFF-38-A POST
![ONOFF-38-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aff5a4d1-f748-45e1-8b82-fe5fd5dc08f3)

**Comment by mosesdeeCVP** [comment]
FFACCTT-13-A IMPORT
![FFACCTT-13-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93c0ebd7-0480-4108-ac67-feea3a0dd63e)

FFACCTT-13-A POST
![FFACCTT-13-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c7df4770-dedc-4076-bff2-e9720fe8421a)

**Comment by mosesdeeCVP** [comment]
UNITDEF-28-A IMPORT
![UNITDEF-28-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/634220b6-cdc4-4e7e-9d19-307b653eea7d)

UNITDEF-28-A POST
![UNITDEF-28-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fcc39d4f-182f-4dc3-ab9f-fadae8a9e384)

**Comment by mosesdeeCVP** [comment]
RATA-106-A IMPORT
![RATA-106-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4f01dd59-49aa-4398-91bd-3a10cb82f3b3)

RATA-106-A POST
![RATA-106-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e1f1264c-e774-4d54-be69-54f3d5bb3592)

**Comment by mosesdeeCVP** [comment]
TEST-19-A POST
![TEST-19-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9b5bdb19-0d0c-4087-adf2-9c020ef37512)

TEST-19-A IMPORT
![TEST-19-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fdb23cc1-2de7-49ea-9965-5bd9ac8e367f)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1218](https://epacamd.testquality.com/project/11428/plan/23995/test/421633)
Test Passed

**Comment by mosesdeeCVP** [comment]
Only Result A was tested for this ticket.
