### ISSUE TITLE
QA Checks - DTO Validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4651]
The scope of this ticket is to address the following Screen Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [ ] PGVP-8 - Protocol Gas Record Consistent with Test
- [ ] PGVP-9 - Gas Type Code Valid

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1216](https://epacamd.testquality.com/project/11428/plan/25475/test/421593)

**Comment by vishnunavuluri** [comment]
Shall be tested as part of #4711
