### ISSUE TITLE
Resolve Contact Us Email Validation Error 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4652]
- [x] Currently, the Contact Us page is not accepting email addresses with "." before the @ sign, which needs to be modified to accept this format.

- [ ] Email address must meet the email format validation

**Comment by JanellC** [comment]
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/2ff7f11d-fa04-4971-94da-58067a1434a4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9ec964f8-13df-48a2-b585-950fd44ff799)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0840c5bd-2bb9-4d4f-958d-888aa825ea4a)
