### ISSUE TITLE
Resolve Bulk Download Extensions Issue in Chrome

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4654]
- [x] Currently when a user attempts bulk download in chrome the download package extension is missing and due to this system does not know how to open the file.

**Comment by JanellC** [comment]
- Spinner displays when the system is loading after filter criteria is applied 
- Able to download a bulk data file on chrome 
**State** 
On bulk data files page
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/48578a43-0c06-4451-8032-f0a407ec4afc)
On campd home page 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/2977ecc8-81eb-4c36-bff2-7d19dc6ac430)
