### ISSUE TITLE
QA Checks - LINEAR-32, 33

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4663]
The scope of this ticket is to address the following Checks:
[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] LINEAR-32 - Duplicate Linearity Summary
- [x] LINEAR-33 - Duplicate Linearity Injection

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1229](https://epacamd.testquality.com/project/11428/plan/25475/test/431581)

**Comment by mosesdeeCVP** [comment]
LINEAR-32-A and LINEAR-33-A IMPORT
![LINEAR-32-A and LINEAR-33-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5854d897-d1e3-437c-8eff-4f392d341fe0)

LINEAR-32-A POST
![LINEAR-32-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/470b880b-9eb7-406e-992e-0d28b2740e08)

LINEAR-33-A POST
![LINEAR-33-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f7e5e464-ed67-427d-abad-8a731cfdb788)

**Comment by mosesdeeCVP** [comment]
Test Passed
