### ISSUE TITLE
Bug: Unit Name and Stack Pipe Name not populating for MP Relationships Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4669]
Issue:
When a user is reviewing MP Relationships information, then the Unit Name and Stack Pipe Name are not being populated

Steps to Reproduce:
- Navigate to the Monitoring Plan section in ECMPS
- Select and open 'Barry 1,2,CS00N' on the Select Configurations screen
- Select 'Location and Relationships Attributes' from the Sections dropdown on the individual Configurations screen
- Click on View for Relationships data and review information for Unit Name and the Stack Pipe Name
They are empty

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/cebf9e4b-20a3-425c-a9b4-cd758fefc068)
![Relationships](https://user-images.githubusercontent.com/112484102/214649077-fae43901-d3de-4cf4-aa25-53282a61c45e.png)

**Comment by JanellC** [comment]
Global:
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1a2ca8da-02ba-4d51-9027-75211c865a22)

Bug resolved
