### ISSUE TITLE
Bug: Component Type dropdown creates a blank screen

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4672]
**Issue:**
When a user selects an option from the Component Type dropdown (MP->System->Create New Component), then the system is displaying a blank screen

Steps to Reproduce:
- Login to ECMPS and navigate to the MP Module
- Select, Check-out, and open a Configuration
- Select Systems from the Sections dropdown
- Click View/Edit for any of the rows
- Locate 'Add Component' option and click on it
- On the Add Component screen, select Create New Component 
- On the Create Component screen, click on the Component Type dropdown 

System displays a blank screen

**Comment by JanellC** [comment]
System is displaying the create componenet modal. Bug is resolved 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1fc43666-7de7-4c1c-aaba-199089f246e6)
