### ISSUE TITLE
API:Implement Validation for the Error Suppression GET Endpoint 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4687]
As the ECMPS system, I need to have validation for the error suppression GET endpoint so that all required parameters are chosen: 

GET /camd-services/error-suppressions
Filter Parameters

- [x] checkTypeCode (Required parameter)
- [x] checkNumber (Required parameter)
- [x] checkResult (Required parameter)
- [x] severityCode (Drop-down in Swagger) Validation against the database We will reuse 
- [x] facilityId (orisCode) We will reuse this one 
- [x] reasonCode (Drop-down in Swagger) Validation against the database We will reuse
- [x] beginDateHrQtr Validation that it's one of the three formats below
- [x] endDateHrQtr Validation that it's one of the three formats below
Date Range - YYYY-mm-dd 
Hour Range - YYYY-mm-dd hh
Quarter Range – YYYY Q1
- [x] Create validation for if a user enters an endDateHrQtr then a beginDateHrQtr needs to be entered as well 

Error Messages: 

[ ] The (property) is not valid refer to the list of available (properties)  for valid values (For code properties)
[ ] The checkTypeCode should not be null, undefined, or empty 
[ ] The checkNumber should not be null, undefined, or empty 
[ ] The checkResult should not be null, undefined, or empty 
[ ] The facilityId is not valid refer to the list of available facilities for valid values
[ ]  Ensure beginDateHrQtr/endDateHrQtr are in the following formats Date Range - YYYY-mm-dd /Hour Range- YYYY-mm-dd hh/Quarter Range – YYYY Q1 
beginDateHrQtr cannot be null, undefined, or empty if endDateHrQtr is filled

**Comment by JanellC** [comment]
@acollad1 

1) Based on 4/18 refinement need clarification on the difference bewteen the following error messages:
The (filter parameter) is not valid
The (property) is not valid refer to the list of available (properties) for valid values (For code properties)

2) Need an error message for Create validation for if a user enters an endDateHrQtr then a beginDateHrQtr needs to be entered as well

**Comment by mosesdeeCVP** [comment]
severityCode - errors
![severityCode - errors.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c357989e-f38c-4898-97ec-8209954a3e72)

severityCode - Dropdown
![severityCode - Dropdown.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/12656423-2ed9-4dfa-8ad6-5a199af20a83)

**Comment by mosesdeeCVP** [comment]
reasonCode - error
![reasonCode - error.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fd343f28-ab0a-4545-ae79-655ae01a76a3)

reasonCode - Dropdown
![reasonCode - Dropdown.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/83177720-33c1-4ebc-a2a9-e023da558415)

**Comment by mosesdeeCVP** [comment]
orisCode - error
![orisCode - error .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7a2595d3-1162-45d6-9b81-da14aee58142)

**Comment by mosesdeeCVP** [comment]
endDateHrQtr - error
![endDateHrQtr - error.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/57f8cf28-0fd3-4c76-833b-7284c30db246)

**Comment by mosesdeeCVP** [comment]
beginDateHrQtr and endDateHrQtr - Error messages
![beginDateHrQtr and endDateHrQtr - Error messages.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cfc3b7b3-6b02-42f7-9b78-ab9bb21d3ac0)

**Comment by mosesdeeCVP** [comment]
[checkTypeCode should not be null
![checkTypeCode should not be null.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/234f9544-e94b-4263-9e58-0c3326879ad3)

checkTypeCode - Required parameter
![checkTypeCode - Required parameter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/41034e29-c615-4caa-8447-a9f28ad161ff)

checkResult should not be null
![checkResult should not be null.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f5584ad5-061e-4279-8b7e-c9bbaccc342b)

checkResult - Required parameter
![checkResult - Required parameter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/568d7ee7-dd14-4270-ad0e-212e7f222c2d)

checkNumber should not be null
![checkNumber should not be null.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9a6a0d3d-9f0f-49f8-8862-b775203eb1d8)

checkNumber - Required parameter
![checkNumber - Required parameter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7a3a7f59-3e67-447c-bca6-56e168532c80)

**Comment by mosesdeeCVP** [comment]
Validations have been implemented.
