### ISSUE TITLE
Restrict Test Reason and Result Code Dropdown Options for Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4697]
As an ECMPS user, I want the options in the Test Reason and Result Code dropdown restricted so that I can choose from applicable options

Acceptance Criteria:
Given I am creating Test Data for any of the Test Data types in the attached document
I want the Test Reason Code and Test Result Code dropdown options restricted to the applicable options

[https://app.zenhub.com/files/287570343/22315a08-c8d2-4c8b-800e-8e006fe24986/download](https://app.zenhub.com/files/287570343/22315a08-c8d2-4c8b-800e-8e006fe24986/download)

Note: Check that we are using the relationships API endpoint for Reason and Result Code (Test Summaries Relationship API)

Extension & exemption codes mdm endpoint:
https://api.epa.gov/easey/dev/master-data-mgmt/extension-exemption-codes

## Testing 
Test Case: [TC1221](https://epacamd.testquality.com/project/11428/plan/24660/test/424872)
Tester:  @JanellC

**Comment by JanellC** [comment]
**Linearity** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8f5770ff-a469-42b5-b4bc-28df7275b370)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d76e0ba2-8ebd-44bb-a102-9b13c43541d9)

**RATA**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c3f75bfe-6cff-4c3b-aa39-a42739c1af1e)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e060a18d-ef7f-42a3-b561-9d8b77003c83)


**7-DAY**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/bffe1e58-6e33-4a9c-bcd0-b81ae23ae8fa)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6f3aac2a-9e4c-44dd-9cef-905391458bb0)


**CYCLE**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/670de3e5-6de0-47a6-bf21-de2bdaa73c3f)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/60da9850-52c8-4e00-af53-4f62f8c1945c)

**HGLINE**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/aa7148fd-0dac-4e89-9fa6-b6ceedc2f8e4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dbd848c4-d0c9-4077-a217-72d1793a2692)

**F2LCHK**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c9c4292d-3b2c-470d-be89-08a3b759d366)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9367eabc-f80e-4997-9fbc-613df15e8843)

**ONOFF**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e0d7048e-91dc-4cee-856d-4b4cc8190c77)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b4c6fdd9-a39f-4ce1-a2e0-4bb6d26a286d)

**APPE**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/60103474-6c61-4913-9231-17a04d7d7fe3)

**FFACC**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ee12f3f4-1a75-464c-a79c-4bd64fd5f7c9)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/77692e51-9644-4d1a-b3f5-e2f0bbc4b7b8)

**FFACCTT**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/762dc52a-78bf-4283-a625-8b29bc1597e8)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/43a5832e-295b-4504-8cc4-d2b02218c98b)

**FF2LTST**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f844a076-d4ee-4e00-991e-323b9ccfe5a4)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/67255026-0b3e-4672-9a7d-1c02296b2908)

**UNITDEF**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f13d35db-ebda-4a49-adbb-6fbc1e8c35b3)

**Miscellaneous**
Displaying Test Reason Code and Test Result Code as expected

**Comment by JanellC** [comment]
QA Reporting Instructions for Misc. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/401bf3b6-2fc2-454c-afba-ac2505cf1c06)


**Leak** 
- missing QA test reason  
- Should not have initial 
- Should not have Recert 

**Other Test** 
- Missing QA test reason 

**Pems**
- missing qa test reason

Dry Gas Meter
- Missing QA test reason 


Mass flow meter: 
- Missing Qa test reason 


Barometer calibration 
- missing qa test reason 


Quaterly gas audit 
- missing qa test reason 

Temperature sensor 
- missing qa test reason
