### ISSUE TITLE
Modify Submissions endpoint to Support CROMMER Submissions

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4699]
## Context 

- Modify the submissions API endpoint to support CROMMER will be producing their own signign ceremony, but work needs to be done to allow for submission through our endpoint

**Comment by MaeganWood64** [comment]
- Not needed for March Beta or May Conference

**Comment by JanellC** [comment]
Will work on this ticket after the reports are completed
