### ISSUE TITLE
Discuss Testing QA checks

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4704]
## Context 

Need to have additional discussion on how to test the checks below 

Original Tickets: 4649, 4650
TEST-19 - Duplicate Miscellaneous Test - Test B
LINEAR-31 - Duplicate Linearity - Test B
ONOFF-38 - Duplicate Online Offline Calibration Test - Test B
FFACCTT-13 - Duplicate Transmitter Transducer Test - Test B
UNITDEF-28 - Duplicate Unit Default Test - Test B
RATA-106 Duplicate RATA - Test B
SEVNDAY-29 - Duplicate Calibration Test - Test B
APPE-46 - Duplicate Appendix E Test - Test B
CYCLE-19 - Duplicate Cycle Time Test - Test B

**Comment by billmiller13** [comment]
[https://app.zenhub.com/files/287570343/ed27f9b5-0d04-489d-8fce-6cff87e56f4d/download](https://app.zenhub.com/files/287570343/ed27f9b5-0d04-489d-8fce-6cff87e56f4d/download)

Attached file contains test data to achieve Result B Duplicate checks for all Test Type Codes in this ticket (valid as of 2/6/23)

**Comment by mosesdeeCVP** [comment]
TEST-19-B
![TEST-19-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3281a898-a1dd-4ee1-864e-ba22581bcd30)

LINEAR-31-B
![LINEAR-31-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/82308260-bc76-4ba8-a97b-176437138955)

ONOFF-38-B
![ONOFF-38-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/98523bf9-183b-47dd-92b6-8a7d56f58c65)

FFACCTT-13-B
![FFACCTT-13-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0ef20a74-d912-40c6-87ab-d57ade85103b)

UNITDEF-28
![UNITDEF-28-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/aac453ca-1956-4607-be36-40a1c56d345e)

RATA-106-B
![RATA-106-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/370554d1-b3ea-40e6-9d90-2bc50f1e83ab)

SEVNDAY-29-B
![SEVNDAY-29-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/412250e9-158a-46c7-9da2-aa08472c07a7)

APPE-46-B
![APPE-46-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4d01c8f0-8cf5-4bb1-a5e5-415017e57e66)

CYCLE-19-B
![CYCLE-19-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/38b6b1c0-917f-449b-a4c8-33508454c66c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1219](https://epacamd.testquality.com/project/11428/plan/23995/test/421790)
Test Passed
