### ISSUE TITLE
Bug: QA Import from Historical not working 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4705]
**Issue:**
QA - Import from historical is not working as expected. See the steps below to reproduce the bugs. 

## Steps to Reproduce
1. Navigate to the QA test data module 
2. Check out  a config 
3. Select import 
4. Select import from historical data 
5. Select data 
6. Select Import 
The system does not import the data. 

**Context:**
Currently, when a user clicks Import from Historical data and imports data, the user doesn't see the success message at times even though the import is successful. This is because the Import is not specific to a Test Type Group and will only update the Test Type Groups that had data for that particular location. For instance, a user selects Linearity Summary and imports historical data, if that location only had data for RATA, user will never see an update to Linearity Summary data. They have to navigate to the RATA data to see the imported data.

**Resolution:** We have implemented a fix where the system shall only import data for a Test Type Group from which the user takes the action (Import from Historical) data. If there is no data for that Test Type Group, user shall not see any updates

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/854

**Comment by JanellC** [comment]
Able to import from historical. 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4c34d9ac-22c7-431d-b23b-979ef799e351)
