### ISSUE TITLE
Bug: Test Reason Code not Populating on UI 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4707]
## Steps to Reproduce
Navigate to the QA test data section in the global view 
Select AES Alamitos (315). Location 3. 
Select Test type Transmitter Transducer

The Test reason code is blank in the data table and in the modal. According to the reporting instructions test reason code is a required field. 
**Note: Working as expected in the workspace**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c9ea3143-7d0c-4c44-9115-dcc55c2a136b)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b59e7338-178b-4721-9b00-3a805465c8ff)

### Actual Results

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/84b24609-9817-42bf-92ef-51337e0ad0a4)

**Comment by cw-cvp** [comment]
AES Alamitos (315). Location 3, Test type Transmitter Transducer has null value for Test Reason code.

**Comment by mosesdeeCVP** [comment]
Bug resolved. The Test Reason Code is not available coming from the database. There are no issue with API and UI
