### ISSUE TITLE
Test Only: QA Checks - For Duplicate Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4709]
The scope of this ticket is to address the following Checks to verify any duplicate records being input:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [ ] APPE-48 - Duplicate Appendix E Summary
- [ ] APPE-49 - Duplicate Appendix E Run
- [ ] APPE-50 - Duplicate Appendix E Oil Record
- [ ] APPE-51 - Duplicate Appendix E Gas Record
- [x] CYCLE-19 - Duplicate Cycle Time Test
- [x] CYCLE-20 - Duplicate Cycle Time Injection

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1219](https://epacamd.testquality.com/project/11428/plan/23995/test/421790)

**Comment by mosesdeeCVP** [comment]
APPE-48-A POST
![APPE-48-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b6e47c12-ba83-41da-9c15-148734e56f66)

APPE-49-A POST
![APPE-49-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0324acf9-5d9a-4f63-aa13-2b0c10eceb09)

APPE-50-A POST
![APPE-50-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d454848f-562e-461f-b285-cbc9c4c574a2)

APPE-51-A POST
![APPE-51-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e6d1bd1-80b4-458c-b9d8-2efb7968b6f8)

**Comment by mosesdeeCVP** [comment]
CYCLE-19-A IMPORT
![CYCLE-19-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d0783ef1-a716-4408-935d-c4fe2ea574a6)

CYCLE-19-A POST
![CYCLE-19-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c4613244-fe30-48f1-9987-b8c8af97b8af)

**Comment by mosesdeeCVP** [comment]
CYCLE-20-A POST
![CYCLE-20-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bcaaca7b-7cb3-42f1-9f08-c781c3ffd454)

**Comment by mosesdeeCVP** [comment]
Rest of bugs fixed via:

[Bug: QA Checks - For Duplicate Records #4710](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/4710)
