### ISSUE TITLE
Bug: QA Checks - For Duplicate Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4710]
Issue: When creating a new/duplicate record, if the user enters 0, then the system reads it as null and the user is able to create duplicate data. This issue is happening for the following checks:

- [x] APPE-48 - Duplicate Appendix E Summary
- [x] APPE-49 - Duplicate Appendix E Run
- [x] APPE-50 - Duplicate Appendix E Oil Record
- [x] APPE-51 - Duplicate Appendix E Gas Record

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
APPE-48-A POST
![APPE-48-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/971ed38a-a3aa-4155-846c-ecd97669e26c)

APPE-49-A POST
![APPE-49-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/38532b81-aa58-43b4-ac3d-b645edc3b32f)

APPE-50-A POST
![APPE-50-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b6760220-d4e0-4f46-8667-492e9f3398ee)

APPE-51-A POST
![APPE-51-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0d629e02-5b47-4d71-9675-6febe679a67a)
