### ISSUE TITLE
Test Only: QA Checks - DTO Validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4711]
[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] PGVP-8 - Protocol Gas Record Consistent with Test
- [ ] PGVP-9 - Gas Type Code Valid

**Comment by mosesdeeCVP** [comment]
PGVP-8-A POST
![PGVP-8-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e8120ff6-9436-4743-ba53-d785f63ba5cb)

PGVP-8-A IMPORT
![PGVP-8-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/85e6cb82-1de8-4ca4-8633-a4d9ba277347)

**Comment by mosesdeeCVP** [comment]
![PGVP-8-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e8120ff6-9436-4743-ba53-d785f63ba5cb)

**Comment by mosesdeeCVP** [comment]
PGVP-9-A IMPORT
![PGVP-9-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d1504ab3-3d40-4812-b176-13f46a047be7)

PGVP-9-A POST
![PGVP-9-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/975fdcff-684a-48dc-9195-635e55517aaf)

PGVP-9-A EDIT
![PGVP-9-A EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ccccc069-4442-4276-aefe-7b10fc789afc)
