### ISSUE TITLE
Bug: Stack Pipe Name & Unit Name displaying incorrect info

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4714]
**Issue:**

The Stack Pipe Name column is displaying the Stack Pipe ID

It should be the actual stack_name. We are showing the database's primary key record id. This also should be the same for the unit name

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/78b28f9e-39af-4449-86a0-4892b1e24774)

**Steps to Recreate:**
- Login to ECMPS and access the MP module
- Check out a Configuration on the Select Facility screen and Select Location Attributes and Relationships from the Sections dropdown
- Review the Relationships data section for the Stack Pipe Name and Unit Name

**Comment by JanellC** [comment]
Tested in Global...Stack pipe is no longer showing the db primary key 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4ea712d4-6aed-470e-8b72-9d0fdde4ac49)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/15893d93-d66f-4e92-a29c-aeaa05137903)
