### ISSUE TITLE
Test Only QA: Move any errors/validations to inside the Modal 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4715]
When a user is working on QA Test data and an error/validation is displayed (API Errors), the modal needs to be closed to review the error or in some cases is closed automatically 

User loses the data since it is not saved at this point

Resolution: Display the validations inside the create/view/edit modals

**Comment by mosesdeeCVP** [comment]
![Errors in Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8d99ce1a-6188-4bc4-95f3-f7f9e31cbe72)

**Comment by mosesdeeCVP** [comment]
![Errors in Modal EDIT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e37ddfe5-035d-4c81-8a6f-4a54ae2a3684)

**Comment by mosesdeeCVP** [comment]
Changes Made
