### ISSUE TITLE
Bug: Monitoring SYS ID and Component ID not populating when Editing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4727]
For QA Test Data (QA Cert and TEE Data), when a user is editing Test Data, then the Monitoring SYS ID and Component ID updates are not getting saved

Steps to Recreate:

- Login to ECMPS
- Click on QA Cert Event Data & Test Extension Exemption Data and checkout any Configuration
- Select any Test Data Type  
- Click on Edit for existing Test Data
- Review the Monitoring Sys ID and the Component ID values (If available) or add a value
- Click Save and Close

**Observe that the update is not reflected in the grid**

**Comment by subrataroyCVP** [comment]
Pull Request: 
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/413
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/862
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/866

**Comment by JanellC** [comment]
Bug resolved user is able to edit Monitoring Sys ID and the Component ID
