### ISSUE TITLE
Bug: Fix TEST-7 Check

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4729]
The scope of this ticket is to address a bug with the following Check:

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] TEST-7 - Test Dates Consistent

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/405

**Comment by mosesdeeCVP** [comment]
TEST-7-A IMPORT
![TEST-7-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1ca89771-abae-44c1-aacd-4dc0cc619b8f)

TEST-7-A POST
![TEST-7-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4137b724-9e93-4309-a4d1-012040014d1e)

TEST-7-A PUT
![TEST-7-A PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b83e917f-afbd-43d9-be1c-87d92d9036bf)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1225](https://epacamd.testquality.com/project/11428/plan/23995/test/428853)
Test Passed
