### ISSUE TITLE
Bug: Bias Adjusted Indicator showing --Select a value-- instead of null

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4737]
**Location/Functionality:** 
QA – Flow to Load Check - Global view

**Issue 1:**
The Flow to Load Check has the Bias Adjusted Indicator field which displays the value –Select a value—in the modal when the value in the is 0

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/f14c8a07-ad63-4579-b9ae-64eac0eeb259) 

**Location/Functionality:** 
QA – Flow to Load Check - Workspace

**Issue 2:**
The Flow to Load Check has the Bias Adjusted Indicator field which displays the value accurately for an existing record. If a user however is adding a new Flow to Load Check data, then the value entered doesn't get saved

Note: Works fine for Edit

**Comment by JanellC** [comment]
Global:
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d1d313cc-5cc9-4665-ad11-eab8f8ed2262)

Workspace:
Bias Adjusted Indicator feild is saving in workspace
