### ISSUE TITLE
Spike: Refactor MP Checks - Fuel Flow

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4746]
**MP Check Specifications Document:** https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Check%20Specifications%202022%20Q1.pdf

**Comment by cw-cvp** [comment]
- [ ] FUELFLW-2
A - `isNotEmpty in DTO`
B - `isNotNegative in DTO`

- [ ] FUELFLW-3
A - `isNotEmpty in DTO`
B - `IsInDateRange in DTO`

- [ ] FUELFLW-4
A - `IsNotEmpty in DTO`
B - `IsInRange in DTO`

- [ ] FUELFLW-5
A - `IsNotEmpty and IsInDateRange in DTO`

- [ ] FUELFLW-6
A - `IsNotEmpty and IsInRange in DTO`

- [ ] FUELFLW-7
A, B, C - `Needs to be done in checks service`

- [ ] FUELFLW-8
A - `IsNotEmpty in DTO`
B - `IsValidCode custom pipe in DTO`

- [ ] FUELFLW-10
A - `IsNotEmpty in DTO`
B, C - `Needs to be done in checks service`

- [ ] FUELFLW-17
A - `Needs to be done in checks service`

- [ ] FUELFLW-18
A - `Needs to be done in checks service`

- [ ] FUELFLW-19
A - `Needs to be done in checks service`
