### ISSUE TITLE
Spike: Refactor MP Checks - Qualification

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4753]
**MP Check Specifications Document:** https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Check%20Specifications%202022%20Q1.pdf

**Check Engine Checks: 13**
- [ ] **QUAL-1**
 `This should be handled by checkEngine.`
- [ ] **QUAL-3**
 `This should be handled by checkEngine.`
- [ ] **QUAL-5**
 `This should be handled by checkEngine.`
- [ ] **QUAL-11**
 `This should be handled by checkEngine.`
- [ ] **QUAL-12**
 `This should be handled by checkEngine.`
- [ ] **QUAL-14**
 `This should be handled by checkEngine.`
- [ ] **QUAL-16**
 `This should be handled by checkEngine.`
- [ ] **QUAL-23**
 `This should be handled by checkEngine.`
- [ ] **QUAL-24**
 `This should be handled by checkEngine.`
- [ ] **QUAL-34**
 `This should be handled by checkEngine.`
- [ ] **QUAL-38**
 `This should be handled by checkEngine.`
- [ ] **QUAL-39**
 `This should be handled by checkEngine.`
- [ ] **QUAL-46**
 `This should be handled by checkEngine.`

**DTO Checks: 5**
- [ ] **QUAL-25**
A - `use formatResultMessage to return error message for @IsNotEmpty;`
B - `use formatResultMessage to return error message for @IsInRange;`

- [ ] **QUAL-29**
A - `use formatResultMessage to return error message for @IsNotEmpty;`
B - `use formatResultMessage to return error message for @IsInRange;`

- [ ] **QUAL-41**
A - `use formatResultMessage to return error message for @IsNotEmpty;`
B - `use formatResultMessage to return error message for @IsInRange;`

- [ ] **QUAL-44**
A - `use formatResultMessage to return error message for @IsNotEmpty;`
B - `use formatResultMessage to return error message for @IsInRange;`

- [ ] **QUAL-45**
A - `use formatResultMessage to return error message for @IsNotEmpty;`
B - `use formatResultMessage to return error message for @IsNotEmpty;`
      `use formatResultMessage to return error message for @IsInRange`

**CheckService Level Checks: 15**
- [ ] **QUAL-7**
`A - use formatResultMessage to return error message for @IsNotEmpty `
`B - use formatResultMessage to return error message for @IsInRange;`

- [ ] **QUAL-8**
`A - use formatResultMessage to return error message for @IsNotEmpty `
`B - use formatResultMessage to return error message for @IsInRange;`
`C - Should be done in checkService`

- [ ] **QUAL-18**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - Should be done in checkService`

- [ ] **QUAL-19**
`A - add @validateIf enddate !== null`
`A - add @IsInDateRange`

- [ ] **QUAL-20**
`A - Should be done in checkService`

- [ ] **QUAL-22**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - should be done in checkService`

- [ ] **QUAL-27**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - Should be done in checkService`
`C - Should be done in checkService`
`D - Should be done in checkService`
`E - Should be done in checkService`

- [ ] **QUAL-28**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - add @IsInDateRange`
`B - Should be done in checkService`

- [ ] **QUAL-35**
 `Duplicate Monitoring Qualification Record`

- [ ] **QUAL-36**
`Duplicate Monitoring Qualification Record`

- [ ] **QUAL-37**
`Duplicate Monitoring Qualification Record`

- [ ] **QUAL-40**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - Should be done in checkService`
`C - Should be done in checkService`

- [ ] **QUAL-42**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - add @IsInDateRange('1990-01-01', false, false, false)`
`C - Should be done in checkService`

- [ ] **QUAL-43**
`A - use formatResultMessage to return error message for @IsNotEmpty;`
`B - Should be done in checkService`
`C - Should be done in checkService`

- [ ] **QUAL-47**
`A - Should be done in checkService`
`B - Should be done in checkService`

**Comment by billmiller13** [comment]
[https://app.zenhub.com/files/287570343/44bb2fa6-e101-49d3-a26a-d03360754e19/download](https://app.zenhub.com/files/287570343/44bb2fa6-e101-49d3-a26a-d03360754e19/download)

Summary of checks that need to be implemented in API and which are left to Check Engine
