### ISSUE TITLE
 API: Modify Error Suppression Response to Include Facility Name and ORIS Code

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4757]
As an ECMPS system, I need the error suppression response to have the facility name in it when called to support admin functionality 

- [x]  Modify the GET endpoint to add the facility name to the response

- [x] Verify Error Suppression UI includes facility name and ID. Format of return: facilityName(ORIScode)

**Comment by mosesdeeCVP** [comment]
![Modify Error Suppression Response to Include Facility Name and ORIS Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/737aa15a-0fb2-49a0-a9f6-a02390277947)

**Comment by mosesdeeCVP** [comment]
The GET API has been updated to contain the facilityName and orisCode in the response
