### ISSUE TITLE
API: Modify Location Filter in GET Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4758]
As an ECMPS system, I need the error suppression GET endpoint to accept special characters via the location filter to support admin functionality 

- [ ] Modify GET endpoint to update the location filter to accept special characters

**Comment by sdhawan16** [comment]
Sample Parameters:

checkTypeCode: QUAL
checkNumber: 23
checkResult: D
locations: **2, 1, **ST1
