### ISSUE TITLE
UI:Create Error Suppression 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4759]
As an ECMPS user, I want to be able to create an error suppression via the error suppression module in order to perform admin needs

Given a user has navigated to the error suppression module
When a user clicks to add or clone and saves the details in the pop up
Then an error suppression is created and will be viewed in the error suppression table

**Comment by mosesdeeCVP** [comment]
Add Suppression
![Add Suppression.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fb88203b-875b-4179-9bc8-3db078a0c01b)

**Comment by mosesdeeCVP** [comment]
Add Suppression Clone
![Add Suppression Clone.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/edc0f88f-dcea-4d90-8ece-ff080fc9bcc4)

**Comment by mosesdeeCVP** [comment]
User is able to Add and Clone an Error Suppression via the UI
