### ISSUE TITLE
Error Suppression UI: Change Status Check box to Drop Down 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4760]
As an ECMPS user, I want to be able to select the status of an error suppression via the drop-down in the filter section 

Given a user has navigated to the error suppression screen
When they want to filter by status
Then the filter will be a drop-down 

- [x] Change the status check box in the filter section to drop down and move it to the left of the reason drop down 
- [x] Drop down options would be Active and Inactive 
- [x] Default option should be nothing selected (---) which means both active and inactive records will be shown in the table

EPA-CAMD-Administration- Cat Utility-Error Suppression- Desktop 1024 WFs
Xd Prototype: https://xd.adobe.com/view/96db9ac9-f9a6-4427-9c8b-f057858d6776-c388/

**Comment by mosesdeeCVP** [comment]
![Change Status Check box to Drop Down.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5270ec9a-ae02-491d-8176-8e4b96444ca0)

**Comment by mosesdeeCVP** [comment]
Changes have been made to the UI
