### ISSUE TITLE
SPIKE: Missing Files for Bulk Data 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4765]
CAMPD User recently ran into issues with the Bulk-Data API where hourly emissions data was not available for the following states in 2010.

- MA
- ME
- MS
- NC
- NE
- NJ
- OH
-R\I

Currently, files without data are not being generated. Further research is required to figure out if there is data for these queries and/or if there is an underlying issue/generation error. 

**Will not address this issue until directed to do so.**

**Comment by tlageman-epa** [comment]
After checking both the bulk files API and CAMPD Bulk Data Files UI, all of the above states have hourly emissions files for 2010, therefore this issue was inaccurate or no longer exists.
