### ISSUE TITLE
508: Emissions Page Focus

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4779]
Results when a user is logged in and Logged out:
APPLICATION WIDE

When the page first loads, focus is on select configurations, which should really be at the top of the page (occurs on other pages as well)
This needs to be resolved in all configuration screens accessible from the left-hand navigation panel:

- [x]  Monitoring Plan
- [x] QA Test Data
- [x] QA Cert Data
- [x] Emissions 
- [x] Export

**Comment by aprematta** [comment]
Testing complete, when the url is pasted into the browser, focus stays at the top of the page, closing ticket
