### ISSUE TITLE
508: Menu Pop Out

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4780]
Results when a user is NOT logged in:
https://ecmps-tst.app.cloud.gov/emissions

There is no visible label for search on the Menu pop out, the default text does not count in 508. Easiest solution is to change the magnifying glass icon into a button that says 'Search' [EASY DESIGN SYSTEM CHANGE]

**Comment by jwhitehead77** [comment]
fixed in easey design system and deployed to production with CAMPD 1.1 Release
