### ISSUE TITLE
508: Sort Arrows in Table Headers

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4782]
The following issues were flagged on the CAMPD 508 scan by EPA. All tables throughout the website should mirror the behavior of the table on https://campd.epa.gov/data/bulk-data-files

Logged in and Logged Out:

Table headers do not have up/down arrow visible on focus only on mouseover

**Comment by aprematta** [comment]
Tested the tables in emissions, they now have the arrow visible on keyboard focus
