### ISSUE TITLE
508: Focus box visibility on Table Column Headers

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4783]
The following issues were flagged on the CAMPD 508 scan by EPA. All tables throughout the website should mirror the behavior of the table on https://campd.epa.gov/data/bulk-data-files

Logged in and Logged Out:
APPLICATION WIDE

The focus box does not stay visible when sorting column headers

This needs to be resolved in all of the March Beta Release Tables:
- [ ]  Monitoring Plan
- [ ] QA Test Data
- [ ] QA Cert Data
- [ ] Emissions 
- [ ] Export

**Comment by acollad1** [comment]
@aprematta Ticket 4783 is ready for 508 testing and has been added to the Emissions Module 508 Testing Epic #4071 thanks!

**Comment by aprematta** [comment]
Testing complete, went through all the tables and the focus now stays visible on the sortable header cells
