### ISSUE TITLE
Spike: Address Failing Unit Tests for MP Module (UI)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4788]
Add a list of failing Unit Tests for MP Module (UI) that need to be fixed. We shall address them in a future sprint

**Comment by Qb10** [comment]
src/components/datatablesContainer/DataTableMats/DataTableMats.js
src/components/ImportModal/ImportModal.js
src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.js
src/components/datatablesContainer/DataTableRectangularDucts/DataTableRectangularDucts.js
src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.js
src/components/HeaderInfo/HeaderInfo.js
src/components/datatablesContainer/DataTableConfigurations/DataTableConfigurations.js
src/components/ModalAddComponent/ModalAddComponent.js
src/components/datatablesContainer/DataTableMethod/DataTableMethod.js
src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
