### ISSUE TITLE
Spike: Address Failing Unit Tests for QA Module (UI)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4789]
Add a list of failing Unit Tests for QA Module (UI) that need to be fixed. We shall address them in a future sprint

**Comment by Qb10** [comment]
src/components/QADataTableRender/QADataTableRender.js
src/components/HeaderInfo/ImportHistoricalDataModal.js
src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
src/components/QACertEventHeaderInfo/QACertEventHeaderInfo.js
src/components/QAImportHistoricalDataPreview/QAImportHistoricalDataPreview.js
src/components/QACertTestSummaryTabRender/QACertTestSummaryTabRender.js
