### ISSUE TITLE
508: Add Label for the Search Icon in the Menu

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4794]
**Location:** Search icon in the Menu
**Issue:** There is no visible label for search on the Menu pop out, the default text does not count in 508. 

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/62738463-8535-4f8f-b088-59bfbf4af853)

**Comment by jwhitehead77** [comment]
fixed in easey design system and deployed to production with CAMPD 1.1 Release
