### ISSUE TITLE
508: Update the Heading level for What's New

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4795]
**Location:** What's New Box - ECMPS Home Page
**Issue:** 
What's new should be a heading (h3), currently it's a div

**Note:** Review if the header level can be updated from the content repo or needs a code change

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/755ff7d8-c9f5-4c2f-bc2b-ee2c88645856)

**Comment by aprematta** [comment]
What's new is now in an H3
