### ISSUE TITLE
508: Issue with Table Headers and Focus

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4796]
**Locations:** Any tables/grid in ECMPS
**Issues:** 
1. Table headers do not have an up/down arrow visible on focus only on mouseover (Select Configurations Screen: Tab to the Header and the Sort arrow needs to be visible)

The fix needs to be implemented for both Logged-in and Global-view and across ECMPS (MP, QA, Emissions, Export etc wherever we have tables with Sort)

**Comment by aprematta** [comment]
Checked tables throughout the application, all now have the arrow displayed when the sortable header has keyboard focus
