### ISSUE TITLE
508: Fix focus in MP table/grid with multiple sections

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4797]
**Locations:** 
- Location Attributes and Relationships
- Methods
- Qualifications
- Unit Information

**Issue:** 
When a user collapses then expands the lower sections of the grid (Supplemental Methods), the focus goes to the top most section (methods)

**Comment by aprematta** [comment]
Testing complete, focus now stays on the collapsible elements
