### ISSUE TITLE
508: Incorrect Heading on the View MP Printout report

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4799]
**Location:** MP View Printout Report
**Issue:** 
On the View printout report, headings like Facility Information should be at an H2

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d6e66b04-2846-415e-b702-acd997483e18)

**Comment by aprematta** [comment]
Testing complete, headings are now in an h2 tag
