### ISSUE TITLE
Bug: QA Module - Global-view

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4801]
**Issue:** 
- When I select a configuration, focus shifts to the first view button, it should stay put

Note: Address this issue for both the Global-view and the Workspace (Configuration not checked-out)

**Steps:** When tabbing through a Configuration and Test Type Group with nesting, when a user gets to the expand/collapse option and tabs, then the focus jumps around and doesn't stay on the option. It should stay on the expand/collapse option. When I expand, focus shifts to the view button. Sometimes the one underneath, sometimes the previous view button

**Comment by aprematta** [comment]
Testing complete, focus now stays on the expand/collapse buttons
