### ISSUE TITLE
Bug: QA Module - Test Types

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4802]
**Location:** QA Module - All Test Types
For both Test Data and QA Cert and TEE

**Issue:**
- Aria Label for first level tables is "Datatable Aria label missing" instead of a unique label (observed on all test types)

**Label:** Test Summary Data for the selected Test Type Group

**Comment by aprematta** [comment]
Testing complete, all tables now have the correct aria label
