### ISSUE TITLE
Bug: PGVP-12, 13

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4805]
Fix the failing Unit Tests for these checks and complete testing

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] PGVP-12 - Gas Type Code Component List Valid
- [ ] PGVP-13 - Protocol Gas Parameter Consistent with Gas Component List

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1233](https://epacamd.testquality.com/project/11428/plan/25475/test/434076)

**Comment by mosesdeeCVP** [comment]
PGVP-12-A
![PGVP-12-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9c502d78-693c-4df2-b112-e5cef7186e7f)

**Comment by mosesdeeCVP** [comment]
PGVP-12-B, PGVP-12-F
![PGVP-12-B, PGVP-12-F.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/22997860-0b23-4717-9076-8a379b6d1316)

**Comment by mosesdeeCVP** [comment]
PGVP-12-C
![PGVP-12-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1e3f2911-1e9f-4f50-8af1-d15293dc292d)

**Comment by mosesdeeCVP** [comment]
PGVP-12-D, PGVP-12-C
![PGVP-12-D, PGVP-12-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bbc9c54b-76c2-47e0-9ad9-5b36ae9868ea)

**Comment by mosesdeeCVP** [comment]
PGVP-12-E
![PGVP-12-E.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/13273a09-7421-4ce1-baee-065bdfda2053)

**Comment by mosesdeeCVP** [comment]
PGVP-12-G
![PGVP-12-G.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9c5c9b26-b968-4485-a6df-0219317ae355)
