### ISSUE TITLE
508: Aria Sort in Table Column Headers

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4806]
The following issues were flagged on the CAMPD 508 scan by EPA. All tables throughout the website (MP, QA, Emissions, Export etc) should mirror the behavior of the table on https://campd.epa.gov/data/bulk-data-files

Logged in and Logged Out:

Don't put aria sort until it is sorted by ascending/descending (so remove aria sort=none, only set aria sort when the column is set to ascending or descending)

**Comment by aprematta** [comment]
Scanned the tables, aria sort - none is no longer present and aria sort - ascending/descending is correctly set
