### ISSUE TITLE
508: Aria Label in Table Column Headers

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4807]
The following issues were flagged on the CAMPD 508 scan by EPA. All tables (MP, QA, Emissions, Export etc) throughout the website should mirror the behavior of the table on https://campd.epa.gov/data/bulk-data-files

Logged in and Logged Out:

Give an aria-label to the headers 'click to sort by the **column name**

**Comment by aprematta** [comment]
Scanned the tables, all encountered now have the correct aria label
