### ISSUE TITLE
Prototype Pollution in JSON5 via Parse Method 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4809]
The parse method of the JSON5 library before and including version 2.2.1 does not restrict parsing of keys named __proto__, allowing specially crafted strings to pollute the prototype of the resulting object.

This vulnerability pollutes the prototype of the object returned by JSON5.parse and not the global Object prototype, which is the commonly understood definition of Prototype Pollution. However, polluting the prototype of a single object can have significant security impact for an application if the object is later used in trusted operations.

**Comment by jwhitehead77** [comment]
fixed or no longer an issue as I do not see it in any of the api's or ui repos anymore
