### ISSUE TITLE
Add Test Data: Default Test Type Code dropdown 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4814]
As an ECMPS user, I want the Test Type Code dropdown to display the applicable default option so that I know which Test Data I am adding 

Acceptance Criteria:
Given I am an ECMPS user adding Test Data
When I click on 'Add' for Test Data
Then I see that the Test Type Code dropdown displays the default applicable option (Based on what Test Type Code screen the user is on)

**Comment by mosesdeeCVP** [comment]
![4814 Add Test Data- Default Test Type Code dropdown.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3388d139-3547-471d-9ba8-5bfaf0a72d7c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1234](https://epacamd.testquality.com/project/11428/plan/24660/test/434674)
Test Passed
