### ISSUE TITLE
Bug: Add for Flow to Load Reference not working

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4816]
**Issue:**
User is unable to add Flow to Load Reference data

**Steps to Recreate:**
- Log into ECMPS
- Check out a config (ex. Barry 1,2,CS0AAN)
- Select Flow to Load Reference Test Type Group
- Expand a test summary
- Click on Add for Flow to Load Reference data

The system doesn't open the Add modal

**Comment by mosesdeeCVP** [comment]
![4816 Bug- Add for Flow to Load Reference not working.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/31ac55b7-0ab6-488b-863b-ced1756161e0)

**Comment by mosesdeeCVP** [comment]
Bug fixed
