### ISSUE TITLE
Bug: RataSummary ( RATA-18 and Others ) DTO checks & use CheckCatalogService 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4818]
**Issue:**

1. The logic for DTO check RATA-18 B is currently incorrect and needs to be fixed. 
2. Also, this check currently doesn't use the Check Catalogue Service. We need to implement that as well

**Comment by subrataroyCVP** [comment]
Changes Effect following Checks:

- [ ] RATA-112-A
- [ ] RATA-112-B
- [ ] RATA-23-A
- [ ] RATA-23-B
- [ ] RATA-17-A
- [ ] RATA-18-A
- [ ] RATA-18-B
- [ ] RATA-19-A
- [ ] RATA-20-A
- [ ] RATA-21-A
- [ ] RATA-22-A
- [ ] RATA-123-A
- [ ] RATA-131-C
- [ ] RATA-24-A
- [ ] RATA-24-B
- [ ] RATA-55-C
- [ ] RATA-17-B

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/428

**Comment by mosesdeeCVP** [comment]
![RATA-18-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4b602230-9d92-4aa9-b14e-3c78e832e645)

**Comment by mosesdeeCVP** [comment]
![RATA-18-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bc6b2725-6c59-4f74-9511-bbba48b81ab2)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
Test Only ticket for changed checks:
[Test Only: DTO Checks Logic Change #4827](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/4827)
