### ISSUE TITLE
Review DTOs to return error messages through CheckCatalogService

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4819]
Review all the QA-Cert-API DTOs verify all error messages are being returned through CheckCatalogService/ if not then make necessary update to return the error message through CheckCatalogService.

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/430

**Comment by mosesdeeCVP** [comment]
Affected checks are working.

**Comment by mosesdeeCVP** [comment]
TEST-1-A, TEST-2-A, TEST-3-A, TEST-4-A
![CheckCatalogService TEST-1-A, TEST-2-A, TEST-3-A, TEST-4-A, TEST-5-A, TEST-6-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7e5e4ad-53e2-4074-aedf-0286802dbd89)

**Comment by mosesdeeCVP** [comment]
TEST-2-B, TEST-3-C, TEST-5-B, TEST-6-C
![CheckCatalogService TEST-2-B, TEST-3-C, TEST-5-B, TEST-6-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f9c60355-0baf-4078-bf1e-6890beb4c8bc)

**Comment by mosesdeeCVP** [comment]
TEST-17-A
![CheckCatalogService TEST-17-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3c5b5339-5886-44e8-a0dc-ccc41e717e8b)

**Comment by mosesdeeCVP** [comment]
TEST-13-A
![CheckCatalogService TEST-13-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b5d3f2e7-9003-4faa-acb1-f3d23bc8bc0f)

**Comment by mosesdeeCVP** [comment]
TEST-1-B, TEST-4-B
![CheckCatalogService TEST-1-B, TEST-4-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/21d10741-4113-4a7b-9803-4ca47e9d7966)
