### ISSUE TITLE
Bug: Issue with Check CYCLE-21-B

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4822]
**Issue:**
Cycle Time Injection: The Gas level code dropdown for Cycle Time Injection includes options High, Mid, Low, and Zero however, only Zero and High are accepted according to CYCLE-21-B. 

Resolution:

According to the Reporting Instructions, only High and Zero are the applicable options for Cycle Time Injection - Gas level code. Hence display only High and Zero in the dropdown moving forward

**Comment by JanellC** [comment]
Bus resolved 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6b757fd6-2457-4971-af64-3a3caa9dbf89)
