### ISSUE TITLE
Bug: Unable to add/Edit Flow To Load Check

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4823]
**Issue:**
For 'Flow To Load Check' values for **Average Absolute Percent Difference, Number of Hours Excluded for Ramping, Number of Hours Excluded for Bypass, Number of Hours Excluded Pre RATA, and Number of Hours Excluded for Main and Bypass** are not saving when users Add's or Edit's data

**Comment by mosesdeeCVP** [comment]
Bug fixed
