### ISSUE TITLE
Bug: RATA-31 (Rata Run Check)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4825]
It is throwing error even endTime is after beginTime.

**Comment by mosesdeeCVP** [comment]
Am able to create a Rata Run with errors
![4825 Bug- RATA-31 Rata Run Check.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a000c96b-db29-4c4e-8623-0f9d13a3bb55)

**Comment by mosesdeeCVP** [comment]
RATA-31-A Working as expected.
![RATA-31-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/40c749ae-ab1b-4e80-b48d-1516c440c98e)

**Comment by mosesdeeCVP** [comment]
RATA-31-B Working as expected.
![RATA-31-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/df15bc9d-1b3f-4469-8d5f-31bf4eedc072)

**Comment by mosesdeeCVP** [comment]
Bug fixed
