### ISSUE TITLE
Bug: PEI Test Data displays an invalid Validation/Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4826]
Issue:

When a user is adding Test Data for Primary Element Inspection (PEI), it displays a Span Scale Required validation which does not apply to PEI data

Steps to Reproduce:
- Login to ECMPS
- Navigate to Test Data and Open and Check-out a Configuration
- Select PEI from the Test Type Code dropdown
- Click Add for Test Data, enter data for all fields and click on Save and Close
- System displays the following error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3c8267cc-6191-4b8e-8312-98b506754bcd)
 Span Scale is not an applicable field for PEI hence this error should never be displayed

**Comment by mosesdeeCVP** [comment]
Bug fixed
