### ISSUE TITLE
Bug: Issue with UnitID for RATA Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4828]
Issue: 
****UnitId type mismatch for RATA Data. So numeric values are working only, string values are not working.

**Comment by mosesdeeCVP** [comment]
![4828 Bug- Issue with UnitID for RATA Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a7714221-0065-4eb0-8606-72b59880ebe6)

**Comment by mosesdeeCVP** [comment]
Bug fixed
