### ISSUE TITLE
MP and QA Module: Remove Evaluate Button

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4829]
Remove Evaluate button from the following screens:

1. **MP-> Configuration Tab** 
Screen Level Button 
Note: Keep the Evaluation Status as is

2. **- Test Data-> Configuration Tab**
Screen Level Button 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/68783c11-2a07-4d31-8f76-c019487b15ca)

3. **- Test Data-> Configuration Tab-> Evaluate for Individual Records**
Screen Level Button 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/cb68cc9b-92a0-4f09-bb74-7afe2663a640)

4. **- QA Cert & TEE Data -> Configuration Tab**
Screen Level Button 

5. **- QA Cert & TEE Data -> Configuration Tab-> Evaluate for Individual Records**
Screen Level Button

**Comment by mosesdeeCVP** [comment]
QA Eval Remove on Line
![QA Eval Remove on Line.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ea8777d0-567c-4e33-b1c6-2f67424d40af)

**Comment by mosesdeeCVP** [comment]
QA Eval Remove for Cert Event
![QA Eval Remove for Cert Event.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f55ae1f1-d6a6-423c-9e51-a7f7e4e27248)

**Comment by mosesdeeCVP** [comment]
QA Eval Remove for TEE
![QA Eval Remove for TEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/92c4f766-f3a6-4263-9580-e703f8e6a156)

**Comment by mosesdeeCVP** [comment]
QA Eval Remove for Flow to Load Ref
![QA Eval Remove for Flow to Load Ref.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c0d4e5c0-8379-4718-ae61-254add0090b2)

**Comment by mosesdeeCVP** [comment]
QA Eval Remove for RATA
![QA Eval Remove for RATA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1bffdddd-24fd-4e5f-9796-61ed804a594a)

**Comment by mosesdeeCVP** [comment]
MP Eval Remove
![MP Eval Remove .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8ec496ce-ac09-4c30-aa8f-06e7d6114069)

**Comment by mosesdeeCVP** [comment]
Eval Button has been removed
