### ISSUE TITLE
Test only: Bug: Issue with Test Type Code value in Global View (Flow to Load Reference Data)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4830]
Issue:
In the Global view for Flow to Load Reference Data when a user views Test Data the Test Type Code value says Select a value which is incorrect

Steps to Reproduce:
- In ECMPS, navigate to QA Test Data
- Select and open a Configuration
- Click on View for the Flow to Load Reference Data (Test Type Group dropdown)
- In the view modal you will see that the Test Type Code displays 'Select a value'. This needs to be fixed

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c63bcb28-9725-47d0-a4a9-c0261dd29c8a)

**Comment by mosesdeeCVP** [comment]
![Test Type Code.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/249e286a-8262-499a-b2d4-def3e3a392f1)

**Comment by mosesdeeCVP** [comment]
Bug fixed
