### ISSUE TITLE
508: Export Configuration Tab - Update header level

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4832]
Issue:
Configuration is not in the H3 (for example, glen lyn is, but 51 is in its own div)

Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c6b62641-0055-4f48-ae66-a6d26d32118c)

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d6f77e41-6aae-4f8c-98af-5399b5dfe96b)

**Comment by aprematta** [comment]
This looks fixed on other pages but is not fixed on the Export page

**Comment by aprematta** [comment]
On the export page the configuration is now in a heading 3 tag but it's in a separate h3 tag than the facility. It should be in the same H3 tag. Use the html in monitoring plans and emissions as an example

**Comment by aprematta** [comment]
They are now in the same heading, closing ticket
