### ISSUE TITLE
508: QA Data Edit, Remove links are not Unique

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4833]
Issue:
For QA Test Data and QA Cert Events and TEE Data: Edit, and Remove links are not unique. Seems consistent with every test type group

**Note:**
- Unique value for Test Data: Edit data for 'Test Number', Remove data for 'Test Number'
- Unique value for QA Cert Event: Edit data for 'QA Cert Event Code', Remove data for 'QA Cert Event Code'
- Unique value for TEE: Edit data for 'Extension or Exemption Code', Remove data for 'Extension or Exemption Code'

**Comment by aprematta** [comment]
Edit and Remove labels have been updated
