### ISSUE TITLE
508: QA Module - Low contrast on Add button

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4834]
Issue:
When add buttons have focus in the QA Module (Test Data and QA Cert and TEE Data), text color changes to black, and the contrast is low

Note: Update similar to contrast on the Edit buttons

**Comment by aprematta** [comment]
This looks to be fixed when the add buttons have the mouse over them, but the text still turns black on keyboard focus. To reporduce, use the tab key to go through the links/buttons until the Add button has keyboard focus

**Comment by aprematta** [comment]
Text now stays white when the buttons have keyboard focus, closing ticket
