### ISSUE TITLE
508: Update Focus in the Create/Edit/View Method

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4835]
Issue:
MP Workspace - Create/Edit Modal - Making a parameter select shifts focus to the close button instead of keeping focus where it is.

Stepps to Recreate:
- Login to ECMPS, navigate to MP an Select, checkout and open a Configuration
- From the Section dropdown, Select Method
- Click on View/Edit or Create Method to open the modal
- Make a selection in the Parameter dropdown
Observe that the focus immediately goes to X. It should stay on the selection made for Parameter

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e68ce1a8-f4db-494d-8ae5-7855046b49ed)

**Comment by aprematta** [comment]
Testing complete, focus is now staying on the parameter dropdown
