### ISSUE TITLE
508: Focus incorrect on View Comments

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4836]
Issue:
When a user closed the 'View Comments' modal the focus does not return to the button

Steps to Recreate:

- Login to ECMPS, navigate to MP an Select, checkout and open a Configuration
- Click on View Comments and open the modal
- Close the modal and observe that the focus does not return to the View Comments button

**Comment by billmiller13** [comment]
Cannot reproduce.  Testing on DEV, the focus returns to the View Comments button as expected when closing the modal.

**Comment by aprematta** [comment]
Testing complete, focus now returns to view comments when the modal is closed

**Comment by aprematta** [comment]
There's a browser alert that pops up now that says View comments when you close the window..... not sure why that's there...

**Comment by aprematta** [comment]
testing complete, focus now returns directly to the view comments button
