### ISSUE TITLE
Add exception handling to pipeline deployments

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#485]
- [x] Modify CI/CD pipeline to handle deployment errors
- [x] Update scripts to check for deployment tags

Outcome:
If a valid tag name contains the wrong build number, where a package doesnt exist, the pipeline will exit out and give a meaningful error message

**Comment by srinivasaregeti** [comment]
Used aws s3 api call to check for the existence of the object in S3

`aws s3api  head-object --bucket $ARTIFACTS_STORAGE --key $PACKAGE.zip`

Following error message appears in the workflow logs when a valid TAG with wrong build# is provided

```
Retrieving package from deployment artifacts...

An error occurred (404) when calling the HeadObject operation: Not Found

Error: Package "easey-facilities-api.v0.0.12.zip" doesnt exist on S3 @ Tue Dec  1 23:44:27 UTC 2020
Exiting deployment stage @ Tue Dec  1 23:44:27 UTC 2020
Error: Process completed with exit code 1.
```

**Comment by srinivasaregeti** [comment]
Used aws s3 api call to check for the existence of the object in S3

`aws s3api  head-object --bucket $ARTIFACTS_STORAGE --key $PACKAGE.zip`

Following error message appears in the workflow logs when a valid TAG with wrong build# is provided

```
Retrieving package from deployment artifacts...

An error occurred (404) when calling the HeadObject operation: Not Found

Error: Package "easey-facilities-api.v0.0.12.zip" doesnt exist on S3 @ Tue Dec  1 23:44:27 UTC 2020
Exiting deployment stage @ Tue Dec  1 23:44:27 UTC 2020
Error: Process completed with exit code 1.
```

**Comment by srinivasaregeti** [comment]
Updated the error message based on the feedback from Jason

`Error: Package "easey-facilities-api.v0.0.12.zip" doesn't exist in the deployment artifacts @  Thu Dec  3 04:00:10 UTC 2020
`
