### ISSUE TITLE
Remove MP and QA UI Reports 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4860]
Remove the following Reports from the UI:

**Global-view:**
1. _Monitoring Plan Module_:
- View Printout Report
2. _QA Test Data Module_:
- Test Data Report
- Test History Report
3. _QA Cert Events and TEE Data Module_:
- Test Data Report
- Test History Report

**Workspace:**
1. _Monitoring Plan Module_:
- View Printout Report
2. _QA Test Data Module_:
- Test Data Report
- Test History Report
- Evaluation
3. _QA Cert Events and TEE Data Module_:
- Test Data Report
- Test History Report
- Evaluation

**Comment by mosesdeeCVP** [comment]
Global View:

Global View - View Printout Report
![Global View - View Printout Report.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7424127c-1bc7-4a79-a998-5df47766590e)


Global View - QA Test Data Module
![Global View - QA Test Data Module.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fa5e4afb-1ab5-41d5-b316-529d3231f7f4)


Global View - QA Cert Events and TEE Data Module
![Global View - QA Cert Events and TEE Data Module.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f9edb45c-159a-438c-8343-e645daae8801)

**Comment by mosesdeeCVP** [comment]
Global View:


Workspace - View Printout Report
![Workspace - View Printout Report.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/48a8640f-a65e-43e7-ae04-d54cfda0190b)


Workspace - QA Test Data Module
![Workspace - QA Test Data Module.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2f9d6401-a340-474f-b0de-cf2efab7a32b)


Workspace - QA Cert Events and TEE Data Module
![Workspace - QA Cert Events and TEE Data Module.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b469b828-7512-47ef-ac13-0e2a01117a38)

**Comment by mosesdeeCVP** [comment]
MP and QA UI Reports have been removed.
