### ISSUE TITLE
Bug: Unit Capacity section not loading (Test Automation)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4863]
Issue: 
When a user tries wishes to review (Global-view) or Add/Edit (Workspace) data for Unit Capacity, the Unit Capacity section doesn't load. The spinner keeps going

**Comment by JanellC** [comment]
Bug resolved. Cann view unit capacites in global and the workspace 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/5ae0b179-ba4a-4502-be13-d45e52217b98)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d53dd0ee-87a3-4ae3-ab9e-b43b28156fcf)
