### ISSUE TITLE
Bug: Issue with RATA-130

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4864]
**Issue:**
There is a discrepancy between Result A in the Check Specifications document and the actual check. The actual check verifies a difference of 4 minutes for the Run and the Result compared against 5 minutes

Resolution:
The check need to be updated to verify what the Result says i.e. 5 mins

**Comment by subrataroyCVP** [comment]
@vishnunavuluri @chrisgitsit 
So, If we implement as per the Result message, then User wont be able to import/Create/Update a Rata Run record with less than 5 min (B) or 21 min (B), 
It does not care whether its a Historical Record or New Record.

**Comment by subrataroyCVP** [comment]
Discussed with chris. He will be looking into that more deeply and let us know what to do.

**Comment by mosesdeeCVP** [comment]
![RataRun 5 Min.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/84e0fe8f-01ed-4810-90ca-dea664f306a3)

**Comment by mosesdeeCVP** [comment]
Bug fixed
