### ISSUE TITLE
Implement Status and View Refresh 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4865]
- [ ] When a file is imported into the emission module and emission file is created the top level record needs its status set to "needs evaluation"

- [ ] When the file is completely imported then the store procedure refresh_emission_views in the CAMD workspace schema needs to be called to tell the system to refresh all 27 views in the order of Monitoring plan ID, Year, and Quarter

**Comment by fanwari1** [comment]
@AmandaMNelson For this one, you'll have to work with me to test it as this is something that comes in the background and there's no way to tell that it ran unless you query the db directly. Feel free to slack me whenever you test this one.
