### ISSUE TITLE
UI: Add QA Cert Events and TEE Data to Import Functionality 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4866]
As an ECMPS user, I want the ability to Import QA Cert Events and TEE Data from Historical Data so I can use the data for analysis

Acceptance Criteria:
Given I am logged into ECMPS 
When I select a Configuration and click Import Data
Then I am able to import data from a file for QA Cert Events and TEE Data

Given I am using the 'Import from Historical Data' functionality
When I select a Configuration and there is data available for QA Cert Events and TEE Data
Then I am able to select and Import the data

**Comment by mosesdeeCVP** [comment]
![Add QA Cert Events and TEE Data to Import Functionality.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3e926edd-90a6-48ce-a095-48f41eb4878b)

**Comment by mosesdeeCVP** [comment]
Successful Import from file

**Comment by mosesdeeCVP** [comment]
Another ticket will be made for Import from Historical
