### ISSUE TITLE
QA & Cert: RATA 16 (Reference Method Code Valid)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4867]
The scope of this ticket is to address the following RATA Summary DTO Checks

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] RATA-16 - Reference Method Code Valid (Results C, D and E)

**Comment by mosesdeeCVP** [comment]
RATA-16-A
![RATA-16-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/68847640-61c5-4b2a-ab15-eb37024d7d03)

RATA-16-B
![RATA-16-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9d2cd552-bcb0-4aa5-91f2-ad7a14d7c078)

RATA-16-C
![RATA-16-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/385ec859-963f-495f-9d93-9a04745fd603)

RATA-16-D 1
![RATA-16-D 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/54a8cbbf-abb7-4942-a252-8bd51f2a8f5a)

RATA-16-D 2
![RATA-16-D 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b70b68ac-d8d0-4297-8023-d77ecf9f2360)

RATA-16-E
![RATA-16-E.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/55a2dace-7832-4a01-997b-c4a45d47929b)

**Comment by mosesdeeCVP** [comment]
RATA-16 Works as expected
