### ISSUE TITLE
Bug: PGVP-13

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4869]
Fix the failing Unit Tests for these checks and complete testing

[QA and Certification Data Checks](https://ecmps.camdsupport.com/documents/ECMPS%20QA%20and%20Cert%20Check%20Specifications%202022%20Q1.pdf)

- [x] PGVP-13 - Protocol Gas Parameter Consistent with Gas Component List

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/441

**Comment by subrataroyCVP** [comment]
https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/442

**Comment by mosesdeeCVP** [comment]
Bug Fixed

**Comment by mosesdeeCVP** [comment]
PGVP-13-A IMPORT
![PGVP-13-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5b249970-a105-4594-ab34-db7f6780f7ee)

PGVP-13-B IMPORT
![PGVP-13-B IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f6f892ee-7f8a-4c8a-a2aa-4e1c88579589)

PGVP-13-C IMPORT
![PGVP-13-C IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f6d20308-7dd8-49e7-8ea7-a986a56a49cc)

PGVP-13-D IMPORT
![PGVP-13-D IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8750d41b-d037-4ec7-a3c7-ba0271320550)
