### ISSUE TITLE
QA Module: Add Evaluation Status Column

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4870]
As an ECMPS user I want to see the Evaluation Status for a QA Test record so that I can understand its submission readiness

Acceptance Criteria:

Given I am logged into ECMPS and have a Configuration checked out for Test Data, QA Cert Events and TEE Data
When I review the Test Data section
Then I see the column 'Evaluation Status'

Given the status of Evaluation is Passed/Informational Errors/Critical Errors
When I click on the status
Then it navigates me to the UI Evaluation Report

Note: The evaluation Report is not available yet. So we won't be testing the navigation as part of this ticket

**Note: Evaluation Status is the last column in the Test Data section**

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4a00912a-9d6e-4183-ad96-98c2117cbe2d)

**Comment by mosesdeeCVP** [comment]
![Eval Status Test Data Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c186f07c-36f4-4d91-b959-e91630961e8a)

**Comment by mosesdeeCVP** [comment]
![Eval Status QA Cert Event Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4fd46a6e-9916-44a0-8432-7f634abb3f8e)

**Comment by mosesdeeCVP** [comment]
![Eval Status QA TEE Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ee901102-8289-4352-acaa-717925b092a4)

**Comment by mosesdeeCVP** [comment]
![Eval Status QA TEE Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ee901102-8289-4352-acaa-717925b092a4)

**Comment by mosesdeeCVP** [comment]
![Eval Status MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/25159d67-eec7-4611-b2f9-041c88aeed4c)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1248](https://epacamd.testquality.com/project/11428/plan/22924/test/437057)
Test Passed
