### ISSUE TITLE
Sustain active/last tab when navigating between modules

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4871]
Issue:
When a user opens multiple tabs and is actively working in one tab -> upon navigation to another module or option from the left-hand menu, the focus automatically goes to the tab that was opened last even when it might not be the one that the user was working in

Scenarios to test:
1. When user opens multiple tabs, and navigates away to another module then the user should be on the last tab/Configuration opened
2. When a user opens multiple tabs, clicks on any one of them, and navigates to a different module, then the focus should be retained on the tab that the user was on.

**Comment by JanellC** [comment]
Bug resolved
