### ISSUE TITLE
Add Views for Emissions Evaluation

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4873]
- Views were missing from the initial Emissions conversion that are required for Mass Eval. 

- Simera to Send list 3/2

**Comment by SimeraHailu** [comment]
vw_mp_monitor_hrly_value_so2cvw_mp_monitor_default_so2xvw_evem_reporting_period

**Comment by SimeraHailu** [comment]
vw_mp_monitor_hrly_value_so2cvw_mp_monitor_default_so2xvw_evem_reporting_period
