### ISSUE TITLE
Test Only: DTO Checks Logic Change

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4876]
The below checks had a change is logic. The affected checks need to be re-tested:

- [x] RATA-55-C

**Comment by mosesdeeCVP** [comment]
![co2OrO2ReferenceMethodCode error message.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a5f2dcea-007f-4cba-a7f3-669c0deebdf9)

**Comment by mosesdeeCVP** [comment]
RATA-55 is not a screen check. Generic error message shows the user that the CO2OrO2ReferenceMethodCode that was entered is wrong when it is not in the database.
