### ISSUE TITLE
MP Checks - Default-52, 53, 78, 79 80

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4891]
The scope of this ticket is to address the following Checks:

[ECMPS Monitoring Plan Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Check%20Specifications%202022%20Q1.pdf)

- [x] DEFAULT-52 - Default Source Code Valid (Results A)
- [x] DEFAULT-53 - Default Fuel Code Valid (Results A)
- [x] DEFAULT-78 - Rectangular Duct WAF Duct Width at Test Location Valid (Results A, B)
- [x] DEFAULT-79 - Rectangular Duct WAF Duct Depth at Test Location Valid (Results A, B)
- [x] DEFAULT-80 - Rectangular Duct WAF Value Valid (Result A, D)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1253](https://epacamd.testquality.com/project/11428/plan/21902/test/438278)

**Comment by mosesdeeCVP** [comment]
DEFAULT-52-A

DEFAULT-52-A IMPORT
![DEFAULT-52-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6028fc35-03da-4305-9c9e-d6862c5925d0)

DEFAULT-52-A POST
![DEFAULT-52-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04b3f061-33a4-4d50-9983-cdb80f9a2cf9)

DEFAULT-52-A PUT
![DEFAULT-52-A PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e105783-6aa7-4fc2-a9c2-038b71a68288)

**Comment by mosesdeeCVP** [comment]
DEFAULT-53-A

DEFAULT-53-A IMPORT
![DEFAULT-53-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a97234eb-b72c-49a6-93ea-98c3c42c596e)

DEFAULT-53-A POST
![DEFAULT-53-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f93a17e9-86f3-4835-a456-318663ceb95e)

DEFAULT-53-A PUT
![DEFAULT-53-A PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ff0d99df-4287-4041-9a5f-237cec9d0fbd)

**Comment by mosesdeeCVP** [comment]
DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A IMPORT
![DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d8b940a8-9aca-4c0f-a33b-0ca358c5c647)

DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A POST
![DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b1b27c6-de60-4573-9cff-82b3797b2b38)

DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A PUT
![DEFAULT-78-A, DEFAULT-79-A, DEFAULT-80-A PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/564d8b93-8e80-4358-8307-5c1977206087)

DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D IMPOR
![DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c29204c3-c55f-4c8c-88b7-d58eed5be374)

DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D POST
![DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a599dee6-9594-4951-9257-e42ecd028b49)

DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D PUT
![DEFAULT-78-B, DEFAULT-79-B, DEFAULT-80-D PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/11d60498-bc89-4dbb-923d-dcfabf1ff1d3)

**Comment by mosesdeeCVP** [comment]
Test Passed
