### ISSUE TITLE
Modify facilities endpoints with random static data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#490]
- [x] Modify facilities endpoint stubs with random static data

**Comment by junie-stigdon** [comment]
Created static data for endpoint "GET /facilities." The return data is compliant to the API Design we agreed on. Working on endpoint "GET /facilities/{id}."

**Comment by junie-stigdon** [comment]
Merged with develop branch in easey-facilities-api
https://easey-dev.app.cloud.gov/api/facility-mgmt/swagger/

- added static data for facilities endpoints: "GET /facilities/" and "GET /facilities/{id}." 
- these endpoints return link headers and total-count in the response header. 
- includes pagination 
- orderBy sort facID, orisCode, state, and name 
- filter by state
- unit tests
