### ISSUE TITLE
Filters not maintained when switching emissions aggregation BUG

### ISSUE THREAD

**Issue by tlageman-epa** [US-EPA-CAMD/PI-1#4903]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a 
I want
So that

## Acceptance Criteria
Given that a user has run an emissions query with certain criteria and previewed the data
When the aggregation is changed
Then the criteria are maintained and a modal pops-up informing users that they should review their filter criteria when changing the emissions aggregation level.

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
Performing the following query: Ozone emissions, unit level aggregation, 2022, CSOSG3, preview data. Then switching aggregation to national level, the filter criteria appear to be maintained but upon previewing the data the data is not accurate. Pulling up the program filter reveals the the filter was not actually maintained but the time period filter was. 

This appears to occur for any switch in aggregation type among all emissions data subtypes. The filter criteria should be maintained so long as the time period does not change. However, a warning as described in the a/c above should display so that users can review their filters when changing between aggregations. For example, a 2022 unit-level emissions query for CSOSG3 is only for certain states. If a users changes that to national level and nothing else, they should remember that it is only for CSOSG3 states, not all states.

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by acollad1** [comment]
Please use the link below to access the recording that reviews this ticket:
https://decisionpointcorp-my.sharepoint.com/personal/skhan_decisionpointcorp_com/_layouts/15/guestaccess.aspx?share=EcnurFMyQs1CmS5dgwPUumwBKZd7BIxxWo1OEI58M82pvA

**Comment by ergjustin** [comment]
1. Navigate to http://localhost:3000/data/custom-data-download
2. Select Data Type as `Emissions` & Data Subtype as `Daily Emissions` and `Apply`
3. Enter Time Period (eg: Start Date `01/01/2019` & End Date `01/01/2019`) and `Apply Filter`
4. Select Program (eg: Acid Rain Program (ARP)) and `Apply Filter`
5. Press `Change` button (left top) 
6. Select Aggregation as `Facility` and `Apply`
7. Check selected Program are still checked.

**Comment by bchofor** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDNUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--64614a1c73d3f66ecf3327a74b113048ead9fc04/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55a9a150d3b96d467b88976584683308782f89b0/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW5UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4170e4390921b285a50f941c37f65862cfc65b48/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamZUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a92aac77f869dbbf0a5f0fe65430623a5741f1aa/image.png)

**Comment by bchofor** [comment]
I have tested the parameters in this ticket, and it is working as expected.

**Comment by ergjustin** [comment]
PR: https://github.com/US-EPA-CAMD/easey-campd-ui/pull/606

**Comment by hamezene** [comment]
@tlageman-epa this has been merged to Dev, Please verify

**Comment by tlageman-epa** [comment]
looks good to me. thx! @ergjustin @hamezene

**Comment by tlageman-epa** [comment]
looks good in staging

**Comment by ergjustin** [comment]
production screenshot
<img width="1233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2771cfa247fc91e79c424c6d730ad518979b3716/filter.PNG" alt="filter.PNG" />
