### ISSUE TITLE
Test: View Monitoring Methods 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#491]
## User Story
As a user I want to view monitoring methods for a particular facility so that I can view the methods the facility is using to monitor. 

## Acceptance Criteria
Given a user has selected a facility 
When the facility info is displayed 
Then the system displays, as a default, a list of the configurations in alpha numeric order in accordance with the wireframes (power plants) and [business glossary](https://teams.microsoft.com/l/file/2033BA1D-E9C8-48CD-A9E6-3B311619246B?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20In%2FMonitoring%20Plan%20Requirements%20Package%2FMonitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) (methods) 

Given a user has selected a configuration
When the locations are displayed
Then the system provides the option to select a location based off the selected configuration

Given a location has been selected
When the methods are displayed 
Then provides the option to select monitoring methods (all)

Note: Display units that start with alpha characters first, then display units that start with numeric characters 

## Testing
Test Case: [TC55](https://cvpcorp.testquality.com/project/11428/plan/19352/test/267704)
Tester @mosesdeeCVP

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R7](https://cvpcorp.testquality.com/project/11428/testcase/267704/requirement/11031). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R8](https://cvpcorp.testquality.com/project/11428/testcase/267705/requirement/11032). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R9](https://cvpcorp.testquality.com/project/11428/testcase/267706/requirement/11033). Do not remove or edit.

**Comment by mosesdeeCVP** [comment]
Test has passed. TCR368
491 View monitoring methods
