### ISSUE TITLE
Bug: SPAN-17-B

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4912]
Testing error logging for SPAN-17-B and addressing associated bugs.

Bugs
1. Case where the FlowFullScaleRange is equal to the FlowSpanValue not addressed.
2. Address issue with trailing space in the check_result_data value that throws and error for this check.

**Comment by mosesdeeCVP** [comment]
IMPORT
![SPAN-17-B IMPORT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/496932e3-3bb2-4624-b3be-d9294c721bee)

PUT
![SPAN-17-B PUT.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/25ff175e-7d82-422d-a674-65224f3b9cb7)

POST
![SPAN-17-B POST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ba4afa43-9edf-4fad-bd21-b47a7b115619)

**Comment by mosesdeeCVP** [comment]
Bug fixed
