### ISSUE TITLE
Bug: Make Error Suppression Facility Dropdown Update when Searching

### ISSUE THREAD

**Issue by AmandaMNelson** [US-EPA-CAMD/PI-1#4913]
#4776 allowed for searching, but when a user types in the search box, the list of displayed facilities in the dropdown does not change. The first entry with matching characters is highlighted, but if it is not in the first few, the user must scroll down to see it which deselects it.

Given a user has navigated to the error suppression page,
When they type in the Facility dropdown,
The list of facilities displayed in the dropdown will change to match the typed text.

https://projects.invisionapp.com/freehand/document/1dwq6maiy?zoomToItems=Y2xka2VhdDhwMDExMDNiNzRlMGUyb2w4Mw%3D%3D

**Comment by mosesdeeCVP** [comment]
![Make Error Suppression Facility Dropdown Update when Searching.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e9f99a32-dc99-44e3-a102-6e8d6dce2ef7)

**Comment by mosesdeeCVP** [comment]
Error Suppression Facility Dropdown Updates when Searching
