### ISSUE TITLE
Test Only: Bug: Undefined Error when Uploading Emissions Data from File 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4917]
When a user navigates to the Emissions page,
Then clicks the Import Data button,
Then selects "Import from File" from the dropdown,
A red error banner appears that reads "undefined undefined".

[Uploading... image.png]

Note: Kyle is investigating this issue an may turn into a testonly

**Comment by JanellC** [comment]
Issue resolved
