### ISSUE TITLE
Regression Test MP Method

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4923]
The scope of this ticket shall be regression testing the following functionality for MP Method (Both Global-view and Workspace):

- Import
- Export 
- Evaluate
- Create
- View
- Edit

Include testing for MATS

**Comment by billmiller13** [comment]
Was able to successfully VIEW a Methods and a Supplemental Methods (MATS) record from Global View, Also successfully exported monitor plan and confirmed Methods and Supplemental Methods records were there.

Was able to successfully CREATE and EDIT a Methods and a Supplemental Methods record from the Workspace View.  Also successfully imported a Methods and Supplemental Methods record, exported the monitor plan, and confirmed the Methods and Supplemental Method records were in the export file.
