### ISSUE TITLE
Regression Test MP Rectangular Duct WAF's

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4925]
The scope of this ticket shall be regression testing the following functionality for MP Rectangular Duct WAF's (Both Global-view and Workspace):

- Import
- Export 
- Evaluate
- Create
- View
- Edit

**Comment by mosesdeeCVP** [comment]
There seems to be a problem with the WAF Value (DEFAULT-80-D). It keeps firing even though the criteria is correct.
