### ISSUE TITLE
Regression Test MP System

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4927]
The scope of this ticket shall be regression testing the following functionality for MP System (Both Global-view and Workspace):

- Import
- Export 
- Evaluate
- Create
- View
- Edit

**Comment by billmiller13** [comment]
Successfully VIEWED Systems, System Components, Analyzer Ranges, and Fuel Flows records in Global view, and confirmed those records were in the MP Export file.

Successfully IMPORTED a System, System Component, Analyzer Range, and Fuel Flow record into Workspace view.  Confirmed export file from workspace included these new records.  Confirmed ADD and EDIT worked for all of these records types with one exception:  Cannot edit an Analyzer Range record - always returns  error COMPON-54-A (Another Analyzer Range record already exists ....).  A bug issue will be opened for this.
