### ISSUE TITLE
Story: Filter Monitoring Plan Methods by Keyword

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#493]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### Acceptance Criteria

As a user, I want to be able to filter MP methods data, so that I can narrow my results. 

Acceptance Criteria:
Given a user is viewing monitoring methods 
When the user enters a keyword to filter by
Then the system will display methods data, if any, matching the keyword.

NOTE: Will get feedback on preferred filter methods before this story is finalized. @chrisgitsit will determine filter method and follow up. 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the staging/integration environment?

**Comment by JorjaComer** [comment]
Need to add UI design ticket and link dependency

**Comment by karenhwwoo** [comment]
Will reopen if requested.
