### ISSUE TITLE
Regression Test Appendix E Correlation Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4931]
The scope of this ticket shall be regression testing the following functionality for Appendix E Correlation Test Data (Both Global-view and Workspace):

- Import (Import from File and Import from Historical)
- Export 
- Evaluate
- Add
- View
- Edit
- Remove

Note: Test both Heat Input from Oil and Gas separately

**Comment by billmiller13** [comment]
Completed regression testing and reported few bugs found for new tickets
