### ISSUE TITLE
Regression Test Cycle Time Summary Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4933]
The scope of this ticket shall be regression testing the following functionality for Cycle Time Summary Test Data (Both Global-view and Workspace):

- Import (Import from File and Import from Historical)
- Export 
- Evaluate
- Add
- View
- Edit
- Remove

**Comment by vishnunavuluri** [comment]
3/20/2023: [#4978](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/4978)

**Comment by subrataroyCVP** [comment]
03/22/2023 : [#4992](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/4992)
