### ISSUE TITLE
Regression Test RATA Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4944]
The scope of this ticket shall be regression testing the following functionality for RATA Test Data (Both Global-view and Workspace):

- Import (Import from File and Import from Historical)
- Export 
- Evaluate
- Add
- View
- Edit
- Remove

Test all 5 levels of RATA and include PGD, AED, and Test Qualification Data

**Comment by cw-cvp** [comment]
For configuration Curtis H Stanton Energy Station:
Import from historical 2022 Q2 has the following errors
Import from file (after exporting from 2021 Q2) has the same errors
![image.png](https://images.zenhubusercontent.com/629e4ba8bc6cd374484822a8/fcfd7c62-6a60-45fd-93af-7eee0a897605)
