### ISSUE TITLE
Regression Test - TEE Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4948]
The scope of this ticket shall be regression testing the following functionality for TEE Data (Both Global-view and Workspace):

- Import (Import from File and Import from Historical)
- Export 
- Evaluate
- Add
- View
- Edit
- Remove

**Comment by JanellC** [comment]
Completed regression testing on TEE. Found a bug with the add functionaility. See Bug: System is not properly adding TEE Data #5002
