### ISSUE TITLE
Bug: MP Systems (View/Edit) - Issue with Save and Close

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4949]
**Issue:**
When a user is View/Editing System data, the Save and Close option is greyed out/stays disabled

## Steps to Reproduce

1. Log in to ECMPS
2. Access MP Module and checkout a Facility-Configuration
3. Select System from the Sections dropdown
4. Click View/Edit for an existing data record
5. Update system information
6. You will see that the Save and Close option is greyed out/remains greyed out

Resolution: Shall remain Active at all times

**Comment by JanellC** [comment]
Bug resolved save button remains enabled 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/002dc680-006b-4614-a929-65422789da64)
