### ISSUE TITLE
Bug: QA Test Data Screen - Issue with Sort

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4951]
**Issue:**
Data table sort for end hour and end minute does not seem to be working properly 

Steps to Reproduce:
1. In global, select Barry 1,2 CS00AN
2. Select  a test type 
3. Sort the Begin Date, Hour and Minute/end hour, end date, and end minute column 

The system does not seem to sort the columns correctly

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by JanellC** [comment]
Functionality has been overidden by #4965 and #4966
