### ISSUE TITLE
Bug: MP Export/Import Discrepancy

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4952]
**Issue:**
When importing a clean MP file the system returns errors. Users should be able to successfully import MP data

**Steps to Recreate:**
1. In the Global view export a clean MP file (ex. Platte 1)
2. Log into ECMPS and import the same MP file that you exported

The system returns errors. A user should be able to successfully import a clean MP file 

Observation: Initially I thought this was happening because of old data (Last Updated Date is old) in the Global-view, so exported data as a logged-in user (Last Updated Date of 2023) and Imported it. Same error is being displayed

**Comment by subrataroyCVP** [comment]
[#4981](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/4981)

**Comment by JanellC** [comment]
Sucessfully imported MP for (ex. Platte 1)
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/04fd59b3-40f7-4f87-b426-efed50094d94)
