### ISSUE TITLE
TEST ONLY Bug: Protocol Gas Data Record - Issue with PGVP-12-B

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4956]
**Issue:**
When a user is editing/adding a Protocol Gas record, then they receive the following error message when selecting a gas type:  You reported a [gasTypeCode] that is not in the list of valid values. This is one of the options available for the users to select from the Gas Type Code dropdown

**Steps to Recreate:**
1. Navigate to ECMPS 
2. Select Test Data under the QA module 
3. check out a config 
4. Select linearity as a test type 
5. Add protocol gas record 
6. Fill out the fields in the modal and select zero air material as a gas type 
7. Select save 

The system returns the following errors: 
You reported a [gasTypeCode] that is not in the list of valid values.
You reported the values ([ZAM]), in the field [gasTypeCode] for [Protocol Gas], which are not in the list of valid values.

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/957

**Comment by JanellC** [comment]
4956 has a blocker that is going to be worked out by Jason and Chris before it can be worked on further

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1kyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce5940695a043cd79bccbcaa9d0f5b3ffbb26ce3/ZAM.png)

**Comment by mosesdeeCVP** [comment]
ZAM is no longer allowed as a valid selection, thus is grayed out.
