### ISSUE TITLE
Bug: MP System Component (Create/View/Edit) - Issue with Save and Close

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4963]
**Issue:**
When a user is View/Editing System component data, the Save and Close option is greyed out/stays disabled
Facilities with the issue: Dolet Hills Power Station, Yucca Power Plant 1

## Steps to Reproduce

1. Log in to ECMPS
2. Access MP Module and checkout a Facility-Configuration
3. Select System from the Sections dropdown
4. Click View/Edit for an existing data record and access the Create or View/Edit for Component Data
5. Update information
6. You will see that the Save and Close option is greyed out/remains greyed out

Resolution: Shall remain Active at all times

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/963

**Comment by JanellC** [comment]
Bug resolved. Save button is enabled 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/db2e0e67-512a-4d39-a64b-4d7e44029e4e)
