### ISSUE TITLE
Bug: MP System Fuel Flow (Create/View/Edit) - Issue with Save and Close

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4964]
**Issue:**
When a user is Creating/View/Editing System Fuel Flow data, the Save and Close option is greyed out/stays disabled
Facilities to Test: Pittsburg Generating Station CA (5), Irvington Generating Station (3)

## Steps to Reproduce

1. Log in to ECMPS
2. Access MP Module and checkout a Facility-Configuration
3. Select System from the Sections dropdown
4. Click View/Edit for an existing data record
5. Update information for Fuel Flow in the Modal
6. You will see that the Save and Close option is greyed out/remains greyed out

Resolution: Shall remain Active at all times

**Comment by subrataroyCVP** [comment]
Pull request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/966

**Comment by JanellC** [comment]
Bug resolved. Save button is enabled 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/280c2d27-5f47-4487-b8ac-1109610b7595)
