### ISSUE TITLE
QA Cert Data: Display Date and Time Together

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4965]
For QA Cert Events Data, the grid displays the Event Date, Hour; Begin Date, Hour and End Date and Hour as separate columns. Update the format for these fields as follows:

- QA Cert Event Date and Time
- Conditional Begin Date and Time
- Completion Test Date and Time

Format: YYYY/MM/DD H 

Note: If end date is not available and hours/mins are, it should just leave it blank

**Comment by mosesdeeCVP** [comment]
QA Cert Data- Display Date and Time Together 4965 Logged In
![QA Cert Data- Display Date and Time Together 4965 Logged In.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fd37aa8a-6c18-46fc-9897-06c656109e7c)

QA Cert Data- Display Date and Time Together 4965 Logged Out
![QA Cert Data- Display Date and Time Together 4965 Logged Out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44e2b8b0-8feb-4f57-aa44-c43b816722ce)

**Comment by mosesdeeCVP** [comment]
Updates completed
