### ISSUE TITLE
QA Test Data: Display Date, Hour and Minute Together

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4966]
For QA Test Data, any grid that displays Date, and Time (Hour and Minutes) as separate columns, update the format for these fields as follows:

Date and Time (Begin Date and Time; End Date and Time etc)

Where we have Hour and Minute columns being displayed as time then format them as YYYY/MM/DD HH:MM

Note: If end date is not available and hours/mins are, it should just leave it blank

**Comment by mosesdeeCVP** [comment]
Appendix E
![Appendix E.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f97bde76-1ad2-43cb-8f03-4553f0c90c4f)

Calibration Injection
![Calibration Injection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/502972c4-a869-49ed-a81b-afe4630d152e)

Cycle Time
![Cycle Time.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/18f35da6-d4d8-4061-a468-42ca71519aca)

Flow to Load Reference
![Flow to Load Reference.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fbdacd64-aadb-4703-b257-3397b4ae2ec8)

Fuel Flowmeter Accuracy
![Fuel Flowmeter Accuracy.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/61f17184-177c-4c1c-8232-c27e750c358d)

HG Line
![HG Line.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5786b046-270c-4f3c-8535-0ffa77e3e164)

Line Sum
![Line Sum.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/459e100a-2e36-4fea-8d29-828a7957999a)

Primary Elem Inspection
![Primary Elem Inspection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3ab0b746-fdea-47eb-8670-2036789e2673)

RATA
![RATA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9f7fc062-21ed-4b52-a41e-4a0e9adc1c26)

Transmitter
![Transmitter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b9996e5f-525d-4af7-bacb-f7d33b85e7fa)

Unit Default
![Unit Default.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e16fc237-f227-4b89-8d3d-6b043fbde81e)

**Comment by mosesdeeCVP** [comment]
Updates Completed
