### ISSUE TITLE
MP Module Screens - Update Date Format

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4967]
1. Update the MP Date format as below where we have the Date and Time displayed as one column in the grid

Format: YYYY/MM/DD H
Note: If end date is not available and hours/mins are, it should just leave it blank

**Sections to be reviewed:**
Default
Formula
Load
Method
Rectangular Duct WAF's
Span
System
Unit Information (Unit Fuel)

2. Update the MP Date format as below:
Format: YYYY/MM/DD

**Sections to be reviewed:**
Location Attributes and Relationships
Unit Information (Unit Control, Unit Capacities)
Qualification
Qualification LEE

**Comment by mosesdeeCVP** [comment]
Update Date Format - Logged Out - Default
![Update Date Format - Logged Out - Default.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9b91e2b5-39dd-498f-853e-45b6ac2458ef)


Update Date Format - Logged Out - Formula
![Update Date Format - Logged Out - Formula.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8664ece0-f22e-4e39-a171-625606b6ea57)


Update Date Format - Logged Out - Load
![Update Date Format - Logged Out - Load.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f9785c71-607f-481b-9bde-f5f82641ea52)


Update Date Format - Logged Out - Method
![Update Date Format - Logged Out - Method.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5830bbf7-1b9b-4e44-8c87-b627205ccec0)


Update Date Format - Logged Out - Rectangular Duct WAF's
![Update Date Format - Logged Out - Rectangular Duct WAF's.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/62cb8b4e-b9cf-49ce-a94a-5bde85b8a0ea)


Update Date Format - Logged Out - Span
![Update Date Format - Logged Out - Span.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5f7b26b5-558e-4e42-88f5-a58f7aeebd43)


Update Date Format - Logged Out - System
![Update Date Format - Logged Out - System.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9f9959e8-058a-4a8f-b0e5-302c2af3c88d)


Update Date Format - Unit Information
![Update Date Format - Unit Information.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d48d9b2c-4fb5-4c00-a778-c2eb2a6b0a83)


Update Date Format - Location Attributes and Relationships Data
![Update Date Format - Location Attributes and Relationships Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d6992117-e641-4615-b0b0-b463363fa70a)


Update Date Format - Qualification LEE
![Update Date Format - Qualification LEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/06710995-5c8c-45fe-a955-961b8a9850db)

**Comment by mosesdeeCVP** [comment]
Update Date Format - Logged In - Defaults
![Update Date Format - Logged In - Defaults.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b075fb72-26ac-4477-8cbb-ad3ba595750d)

Update Date Format - Logged In - Formulas
![Update Date Format - Logged In - Formulas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f8b1c16b-a103-4381-b0ef-c3fc3d450e66)

Update Date Format - Logged In - Loads
![Update Date Format - Logged In - Loads.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c33b8631-3ff5-4880-9a82-22970bdecf8e)

Update Date Format - Logged In - Location Attributes
![Update Date Format - Logged In - Location Attributes.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b838b159-9a10-4b51-93df-901c00f1cbc1)

Update Date Format - Logged In - Methods and Supplemental Methods
![Update Date Format - Logged In - Methods and Supplemental Methods.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/03b6cbde-fcca-422a-ae50-c7aef82e60df)

Update Date Format - Logged In - WAFs Rectangular Duct
![Update Date Format - Logged In - WAFs Rectangular Duct.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4c19bcdc-3166-41cd-8608-3206da1782e1)

Update Date Format - Logged In - Spans
![Update Date Format - Logged In - Spans.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1b1c2ec9-f824-4b5f-b0c5-3ad48cae7277)

Update Date Format - Logged In - Systems
![Update Date Format - Logged In - Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4c5b0e0e-8a03-4737-a3c8-e485c2874868)

Update Date Format - Logged In - Unit Information
![Update Date Format - Logged In - Unit Information.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2f2a9669-ef05-496e-9c8d-6c94c03f02fe)

Update Date Format - Logged In - Qualification LEE
![Update Date Format - Logged In - Qualification LEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d8a89085-c725-48b2-9f0d-0c083852e167)

**Comment by mosesdeeCVP** [comment]
Qualifications Date Format Logged In
![Qualifications Date Format Logged In](https://user-images.githubusercontent.com/72424107/227353057-a0bf338f-00e2-4bc2-989d-450deccd6d44.png)

Qualifications Date Format Logged Out
![Qualifications Date Format](https://user-images.githubusercontent.com/72424107/227353209-367166b4-45f2-4f2e-9f84-4ebf61f48d62.png)

**Comment by mosesdeeCVP** [comment]
Date Format Updated
