### ISSUE TITLE
Bug: Issue with QA Test Data Export and Reporting Period

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4969]
Issue: When there are Test Summary Data records without a Begin Date and Reporting Period ID, then these Records don't show up on the Export screen. User is thus unable to Export data for these records

**Comment by JanellC** [comment]
Oris code 564, 2005, Q2 displays  a flow to load reference test summary which previously didn't appear
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/307e26a8-0aa1-41c9-81a6-7deb34384a1d)
