### ISSUE TITLE
Address errors in the Emissions and QA-Cert JSON schemas

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4970]
**Issue to be addressed for Emissions:**
- Rename hourlyGfmData property to hourlyGFMData
- Change the following type definitions names:
    - MatsMonitorHourlyValue -> MATSMonitorHourlyValue
    - MatsDerivedHourlyValue -> MATSDerivedHourlyValue
    - HourlyGfm -> HourlyGFM
    - Nsps4tSummary -> NSPS4TSummary
    - Nsps4tCompliancePeriod -> NSPS4TCompliancePeriod
    - Nsps4tFourthQuarter -> NSPS4TFourthQuarter

**Issue to be addressed for QA-Cert:** 
- Correct 'nmberOfTraversePoints' in the json schema which is misspelled

## Testing 
Tester: @JanellC

**Comment by billmiller13** [comment]
Updated schemas can be viewed here:

Emissions
https://api.epa.gov/easey/dev/content-mgmt/ecmps/reporting-instructions/emissions.schema.json

QA / Cert
https://api.epa.gov/easey/dev/content-mgmt/ecmps/reporting-instructions/qa-certification.schema.json

**Comment by JanellC** [comment]
Qa and Emissions schema updated as expected
