### ISSUE TITLE
Bug: Issue Importing Import Flow To Load Reference Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4971]
### **Issue:**
file containing flowToLoadReferenceData don't import on the front end only generating errors "instance.testSummaryData[0].flowToLoadReferenceData[0] requires property "referenceFlowLoadRatio""
"instance.testSummaryData[0].flowToLoadReferenceData[0] requires property "calcSeparateReferenceIndicator""

The 2 values in the front end and backend don't match the correct schema name

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/df41bb99-5cb7-4939-9cb8-b4a5008dd733)

### **Steps to Reproduce** 

1. Export a Flow To Load Reference record (ex. Curtis H. Staton 2005-Q2) 
2. Update the test number in the file 
3. Log into ECMPS and checkout a config that corresponds with the exported file
4. Import the exported file 

The system was returning the following errors: 

file containing flowToLoadReferenceData don't import on the front end only generating errors "instance.testSummaryData[0].flowToLoadReferenceData[0] requires property "referenceFlowLoadRatio""
"instance.testSummaryData[0].flowToLoadReferenceData[0] requires property "calcSeparateReferenceIndicator""

**Upon the remediation of this bug the system shall import the exported file without errors**

**Comment by JanellC** [comment]
Bug resolved
