### ISSUE TITLE
Bug: Unable to create Default Record for SO2 Hourly Emission Rate

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4972]
**Issue:**
The user wants to create a MP Default record with the **Parameter SO2 Hourly Emission Rate**. When this selection is made for Parameter, the Purpose field doesn't display any options for selections thus preventing the user from creating a Default Record for SO2 Hourly Emission Rate

Steps to Recreate:
1. Login to ECMPS and access the MP Module
2. Select, Open, and Check-out a Configuration under a Facility (Gadsden 1, 2, CS0BAN)
3. Select Default from the Sections dropdown and click on Create Default
4. Select 'SO2 Hourly Emission Rate' from the Parameter dropdown and review the options available for the Purpose field
It doesn't display any options for selection, however when Creating a Default record, there is a screen check which mandates the selection of Purpose

There are older records in the system which doesn't have a value for the field 'Purpose', however the record was created successfully

**Reference Screenshot:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c599e3cb-369d-434b-a071-71eff0884069)

**Comment by mosesdeeCVP** [comment]
User in now able to create Default Record for SO2 Hourly Emission Rate
