### ISSUE TITLE
Bug: MP MATS Method not loading

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4974]
Issue:
Mats Methods are not loading. [Could be an issue with useMemo not recalculating correct data]

Steps to Recreate:
1. Login to ECMPS and navigate to MP Module and checkout a Configuration
2. Click 'Create MATS Method'
3. Enter all the information needed 
4. Click Create MATS

Observe that no new record is created and no error is displayed

**Comment by mosesdeeCVP** [comment]
Was able to create a MATS Method
<img width="690" alt="Supplemental Methods" src="https://user-images.githubusercontent.com/72424107/227289298-1607f330-0b9e-47f8-b0ab-1eccdd2aeac9.png">
