### ISSUE TITLE
Bug: Create MP Method - Substitute Data Approach and Bypass Approach fields do not display options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4975]
Issue:
When a user wishes to create Methods Data, the Substitute Data Approach and Bypass Approach fields do not display options for selection

Steps to Recreate:
1. Login to ECMPS and navigate to MP Module and checkout a Configuration
2. Click 'Create Method'
3. Enter all the information needed
4. Observe that Substitute Data Approach and Bypass Approach fields do not display options at all times

Note: Access a MP Method data record that has a value for the above 2 fields and click View/edit. You will see values for the Substitute Data Approach and Bypass Approach fields. Pick the same values and try creating a new Method, you will see that there are no options displayed for Substitute Data Approach and Bypass Approach

**Comment by JanellC** [comment]
Bug resolved. Able to see options for Substitute Data Approach and Bypass Approach field using glen lyn
