### ISSUE TITLE
Bug: End Date and End Time should always be added together (MP Formula)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4976]
**Issue:**
When a user is creating/View/Edit Formula data, they are able to enter the End Time without entering the End Date. Currently, there is a validation that gets displayed when End Date is entered without End Time. It should be implemented for End Time as well

Resolution:
When user enters only End Date or only End Time, then display the following error message: **Must enter in both End Date and End Time**

**Comment by mosesdeeCVP** [comment]
Bug fixed
