### ISSUE TITLE
Bug: Issue with Dates - MP Module 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4977]
**Issue 1:**
For MP Formula, a user is able to create a record without adding the Begin Date and Time which is not the expected behavior. The system should display an error message mandating the user to add the Begin Date and Time. This is also applicable to editing the record

Note: This issue is seen with Formula, Loads, WAFs Rectangular Duct, Span, System, Defaults, Location Attributes and Relationships, Methods, Unit Information, Qualifications

**Issue 2:**
For MP Formula, when a user doesn't make a selection (Create/Edit) for the Begin Time (Leave it as 'Select a value'), then the system saves and displays it as 0 which is not the same as Null

Expected Behavior: Begin Time is a mandatory field and goes together with the Begin Date. 
- When a user doesn't make a selection for Begin Date and Time, then the system should display the applicable error message
- When a user makes a selection for either Begin Date or Begin Time, then it should display the following message: Must enter in both Begin Date and Begin Time

Note: This issue is seen with Formula, Loads, WAFs Rectangular Duct, Span, System, Defaults, Location Attributes and Relationships, Methods, Unit Information, Qualifications

**Example from Default:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/229344ee-efeb-44b5-ae81-0071fc7e368b)

**Comment by mosesdeeCVP** [comment]
I am unable to create any records without a Start Date and Time as expected

**Comment by mosesdeeCVP** [comment]
Load
![Date and Time error Load.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0e9bd92a-9475-444f-9e89-5c545abb19ac)

WAF
![Date and Time error WAF.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7f898437-8087-4e43-af6f-521317d0671a)

Span
![Date and Time error Span.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/04773b07-9943-4250-b387-a1564dafed45)

Default
![Date and Time error Default.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4758ccf3-f322-4463-806b-f2c78e4d4aa3)

Location Attribute
![Date and Time error Location Attribute.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e81529c3-7c39-42f1-8d86-c131191350cf)

Methods
![Date and Time error Method.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4ff4e1f2-bec1-44c2-8d05-a49e79611d4d)

Unit Fuel
![Date and Time error Unit Fuel.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1479d4dd-4990-44fc-bd41-5ac95618f4b3)

Unit Capacity
![Date and Time error Unit Capacity.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4fad85ba-d52f-487c-9be6-00fa2ff75fec)

Qualification
![Date and Time error Qualification.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6adc0ad0-da9c-467b-81e3-3958c04a7a83)

System
![Date and Time error System.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/71b504cb-6be8-482d-981b-3ec38750a72f)

MATS
![Date and Time error MATS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a6c0d956-eee0-4521-9684-04b94b9ea6f6)
