### ISSUE TITLE
Test Only: QA Test Data - Issue with Component ID

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4978]
**Issue:**
When is user is adding Test Data for Cycle Time Summary Data, then the validation Test-8D is getting displayed even when it is not applicable. This is seen when a user is creating Test Data with a Component ID i.e. a number (numeric values - 008). Working as expected when it is a string  

**Steps to Recreate:**
1. Login to ECMPS
2. Navigate to Test Data, select, open, and check out a Configuration (e.g., Platte 1)
3. Select Cycle Time Summary from the Test Type Group dropdown
4. Click Add for Test Data
5. Enter all the required information. For Component ID, pick any number from the available options (006, 001 etc.)
6. Click Save and Close

The system displays the following error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9d39019a-057a-4530-84bc-c026c25ed2ad)

The above error is not applicable for Cycle Time Summary when appropriate selections are made for Span Scale Code. But it is still being displayed

**Observation:** When a user selects a number for the Component ID especially with 0's at the beginning, then the system excludes the 0's while saving in the backend (Saving as a number). It needs to be saved as a string value

**Comment by mosesdeeCVP** [comment]
![Cycle Time.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0fe0a576-8009-4af5-9cbf-f260b45371d3)

**Comment by mosesdeeCVP** [comment]
Works as expected. Was able to create Cycle Time Data
