### ISSUE TITLE
Bug: Test Summary Data - Cannot save Component ID 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4986]
Issue:

When adding Test Summary Data for QA Tests, when a user selects a value for the Component ID from the available options and creates the records, the selection is not saved. The selection when saved needs to be displayed both in the Test Data grid as well as the Edit modal, but currently, these are empty

Reference Screenshots:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6db60f86-dffc-440e-a949-8d17c608cf9b)
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/66a3415a-0742-4f3b-890e-a15bd585dfb5)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![Test Summary Data - Cannot save Component ID 4986.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0c47bda3-cb70-4430-b67e-9ff4f6e709de)
