### ISSUE TITLE
Bug: Correct cycle-time-Injection property type when Exporting

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4992]
Issue:
Correct cycle-time-Injection property type when exporting. Currently, it is being returned as a string. Needs to be a Number

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/447

**Comment by mosesdeeCVP** [comment]
![cycle-time-Injection property.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/888f9a53-119f-4751-9149-406963a81d4f)

**Comment by mosesdeeCVP** [comment]
Bug fixed
