### ISSUE TITLE
Bug: Span-17B check displayed when Importing a clean file

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4994]
Issue:
When importing a clean MP file, the SPAN  -17B is being displayed preventing the Import process from being completed. This check is not valid for the data being imported

Steps to Recreate:
1. Export a MP file for Charles R Lowman
2. Login to ECMPS and Import the file that you exported for Charled R Lowman
3. System displays a SPAN-17B check. This is not supposed to be displayed as we are importing a clean file

**Comment by JanellC** [comment]
Bug resolved, Can import  Charles R Lowman MP
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/67015108-edd9-4954-b770-59cc2cb8ff56)
