### ISSUE TITLE
Bug: Issue with Error Report when evaluating F2LCHK Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4997]
Issue:
When a user evaluates a F2LCHK record under Test Summary Data and the Evaluation is successful and the Evaluation Status = Error, then the Evaluation Report opens a blank screen when opened

Steps to Recreate:
1. Login to ECMPS
2. Locate the Evaluation tab and open the following Facility/Configuration: Harrison Power Station (3944) - 2 or Facility 667
3. Select the check box for QA & Certification and Apply filters
4. Evaluate Test Summary data records (Make sure there is a F2LCHK record available)
5. Once the Evaluation is done, click on ERR for F2LCHK records
You will see that the system opens a blank report

**Comment by jwhitehead77** [comment]
put a check in place to handle special chars in check results

**Comment by vishnunavuluri** [comment]
Resolved
