### ISSUE TITLE
Bug: Make fields in Unit Capacity Read-Only

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4998]
**Issue:**
When a user is creating Unit Capacity records, then the fields: 
- Commercial Operation Date
- Operation Date
- Boiler/Turbine Type
- Boiler/Turbine Begin Date
- Boiler/Turbine End Date should be read-only values derived from the Unit and Boiler Type. These should not be editable when Creating/View/Edit

**Steps to Recreate:**
1. Login to ECMPS
2. Open and checkout a Configuration and select Unit Information from the Sections dropdown
3. Click Create Unit Capacity
You will notice that the fields mentioned above in the issue are editable and use is able to enter information for it. These are read-only when editing/viewing which should be the same for Creating

**Comment by mosesdeeCVP** [comment]
Unit Capacity Edit
![Unit Capacity Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2141ada6-fea1-4b8a-a478-0a9ca91486f6)

Unit Capacity Create
![Unit Capacity Create.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0c5866d0-293d-41dd-b55b-c00f2387d68d)

**Comment by mosesdeeCVP** [comment]
Bug fixed
