### ISSUE TITLE
Bug: Import functionality shows a blank screen (Montville, 5)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4999]
**Issue:**
When a user exports a file in the global-view and import the same after logging in, the application displays a blank screen

**Steps to Recreate:**
1. Navigate to MP Module in ECMPS and access the global-view
2. Select Montville, 5 in the Select Configurations screen and Export the MP
3. Now login to ECMPS, Select Montville, 5 in the Select Configurations screen and check-out
4. Click Import and try importing the Mp that you exported earlier

You will see that the screen turns blank

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![Montville Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/521d7954-e65b-49de-a706-828d5b2ee829)
