### ISSUE TITLE
Bug: Emissions Import/Export Mismatch 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5001]
Currently, there is a mismatch between what a user exports out and what is expected when the user imports back the file back in pertaining to the indicator fields. 

- [ ] Need to update the typing on indicator fields in the JSON schema in the easy-content repo so that the type is a number for indicators and not a string

**Comment by fanwari1** [comment]
To test, you an checkout Smith Generating Facility and export data from non logged in view. Then log in and import that same file. You shouldn't see schema validation errors pertaining to the indicator fields needing to be a number or the indicator fields being null.
