### ISSUE TITLE
Bug: System is not properly adding TEE Data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5002]
## Context 

When adding TEE data the system displays the following error:  [EXTEXEM-8-A] - Another [Test Extension Exemption] record already exists with the same [extensionOrExemptionCode, reportPeriodId, monitoringSystemId, componentId, fuelCode

But despite the error the newly added TEE data is added to the TEE Data table 

## Steps to Reproduce

1. Log in to ECMPS and Navigate to Cert events, extensions, and exemptions section
2. Check out a config 
3. Select Test Extension Exemption data in the drop down 
4. Add a TEE record and select save 

The system displays the following alert: [EXTEXEM-8-A] - Another [Test Extension Exemption] record already exists with the same [extensionOrExemptionCode, reportPeriodId, monitoringSystemId, componentId, fuelCode

However the newly enetered data is added to the TEE table. Need to look into why the error is displaying and why the system is adding the data despite the error.

**Comment by mosesdeeCVP** [comment]
Bug fixed. Only the original was added. After the error, the duplicate was not added.
