### ISSUE TITLE
Bug: Issue with Revert to Official for Platte, 1

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5003]
Issue:
For Platte, 1 when you 'Revert to Official Record' then the system throws the below error:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4476aa3a-0cb3-43b5-b21a-5cbde29fd522)

Steps to Recreate:
1. Login to ECMPS and access the MP Module
2. Select and checkout a Configuration
3. Make updates to any existing records or add a new data record for any of the Sections
4. Once the updates are saved, click Revert to Official Record
Once the spinner stops, you will see the error in the screenshot above

**Comment by jwhitehead77** [comment]
we where loading a child table before the parent, switched the order and now working

**Comment by vishnunavuluri** [comment]
Resolved and no longer shows the error
