### ISSUE TITLE
Bug: Validations for Begin Date and Hour not showing up in the modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5004]
Issue:
For Supplemental Methods, when a user tries to add a record without a Start Date or Start Hour, then the modal closes without displaying any errors/validations. 

Note: Data isn't saved which is the expected behavior but it needs to display the Date and Hour validations

**Comment by mosesdeeCVP** [comment]
![Begin Date Begin Hour Error.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/818ac1ab-b4c6-418a-950c-93ce6aef72b7)

**Comment by mosesdeeCVP** [comment]
Bug fixed
