### ISSUE TITLE
Bug: Create System - Isssue with Start Date and Start Time

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5005]
Issue:
When a user tries to create a Systems record without the Start Date and Start Time, then the app throws an error prompting the user that those fields are required. However, when the user enters information for these fields and clicks Create System, then the new data is not saved and the modal is not closed

Steps to Recreate:
1. Login to ECMPS and access the MP Module
2. Select and checkout a Configuration
3. Select System from the Sections dropdown and click Create Systems
4. Enter all the information as needed except for the Start Date and Start Time
5. Click Create System
You will observe that the app displays the needed validations around the Date and Hor
6. Now select information for Start Date and Start Time, and click Create System
You will see that the modal stays open and doesn't save the data and the errors are still displayed in the modal and the background

**Expected Behavior:** Once the user makes a selection for all the required fields, the system should save the data and close the modal

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/269f7dff-ca93-41a2-9a1a-1ce8800de1e9)

**Comment by mosesdeeCVP** [comment]
Bug fixed
