### ISSUE TITLE
Bug: Test Data - Issue adding Miscellaneous Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5006]
**Issue:**
When adding Miscellaneous data the system displays an error for missing Span Scale Code selection. Span Scale Code is not an applicable field for Miscellaneous Data

**Steps to Reproduce**
1. Log in to ECMPS and navigate to Test Data Module
2. Check out a config and select Miscellaneous from the Test Type Group dropdown
3. Click Add for Test Data, enter all the information needed, and click 'Save and Close'

You will see the following check displayed which is not applicable to Miscellaneous Test Data:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a129b80b-e0fd-420f-8b56-e772cf79dcb8)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
