### ISSUE TITLE
Bug: Test Data - Issue creating Online Offline Calibration Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5007]
**Issue:**
When user is creating an Online Offline Calibration Data, then the system displays a validation that Begin Minute is required to create the data and that is not true. Online Offline Calibration data doesn't have Begin Minute so the validation is not applicable here

**Steps to Reproduce**
1. Log in to ECMPS and navigate to Test Data Module
2. Check out a config and select Online Offline Calibration from the Test Type Group dropdown
3. Click Add for Test Data, enter all the information needed, and click 'Save and Close'

You will see the following validation displayed which is not applicable to Online Offline Calibration data:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/972bb351-89b3-4f59-bcdb-13013d566306)

**Comment by mosesdeeCVP** [comment]
Bug fixed
