### ISSUE TITLE
TEST ONLYBug: Issue with Gas Type Code in Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5008]
**Issue:**
When creating/editing PGD records, not all Gas Type Code options available in the Gas Component Code table are available in the Gas Type Code table to be displayed on the UI for user selection

**Steps to Recreate:**
1. Login to ECMPS and access the Test Data module
2. Select and checkout a Configuration with Protocol Gas Data for Appendix E/RATA/Linearity Summary or Unit Default Test Type Code (GlenLyn)
3. Locate an existing Protocol Gas Data record with 'BALN' as a value for Gas Type Code
4. Open the edit modal for the same record and try to select BALN from the Gas Type Code dropdown

You will see that it is not an available option for selection. This is trues for other values too. Not all values available in the Gas Component Code table are available in the Gas Type Code table for selection on the UI

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/17976371-a54c-41fa-b334-521cd7c38fbe)

**Comment by JanellC** [comment]
Need to have additional discussion about this ticket before it can be bought into a sprint

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMncyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e28e3435447fb80b235d31c9e0aa2f42f5538336/BALN.png)

**Comment by mosesdeeCVP** [comment]
BALN is available for selection. Record with BALN is available in Official Record under Barry > RATA> Test Number: 201306021836AA2
