### ISSUE TITLE
Bug: Issue with Error Report when evaluating Unit Default Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5009]
**Issue:**
When a user evaluates a UNITDEF record under Test Summary Data and the Evaluation is successful and the Evaluation Status = Error, then the Evaluation Report opens a blank screen when opened

Steps to Recreate:
1. Login to ECMPS
2. Locate the Evaluation tab and open the following Facility/Configuration: **Montpelier Electric Gen Station (55229) - G4CT2**
3. Select the check box for QA & Certification and Apply filters
4. Evaluate Test Summary data records (Make sure there is a UNITDEF record available)
5. Once the Evaluation is done, click on ERR for UNITDEF records
You will see that the system opens a blank report

ERR Report is working for other Facility-Configurations. The one with the issue is **Montpelier Electric Gen Station (55229) - G4CT2**

**Comment by jwhitehead77** [comment]
put a check in place to handle special chars in check results

**Comment by vishnunavuluri** [comment]
Resolved
