### ISSUE TITLE
Requirements: Users able to add multiple records for the same Gas Level Code in Protocol Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5010]
- Discuss the checks or requirements around how many records can be added at any Gas Level Code 
- If the decision is to restrict the number, then what checks need to be implemented

**Comment by alangmaid** [comment]
Please update this with info about how 1.0 handles this use case.

**Comment by annalbrecht** [comment]
> Please update this with info about how 1.0 handles this use case.

ECMPS 1.0 allows this. Closing this ticket.
