### ISSUE TITLE
Bug: Import Success Modal Displaying Drag a file 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5011]
## Context 

The import success modal is displaying: **Drag a file here or choose from folder** . As apart of the scope of this bug ensure the import success modal does not display  **Drag a file here or choose from folder** in **ALL**modules **(MP, QA, Emissons)**  

## Steps to Reproduce

1. In the global view export a MP file 
2. Log into ECMPS and check out a config 
3. Import the MP file 

The systems displays a success message and the modal has  **Drag a file here or choose from folder**.  **Drag a file here or choose from folder** needs to be removed 

 As apart of the scope of this bug ensure the import success modal does not display  **Drag a file here or choose from folder** in **ALL**modules **(MP, QA, Emissons)**  

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e2e26c69-49c6-4879-b991-1db540ba07a3)

**Comment by mosesdeeCVP** [comment]
Import Successful QA
![Import Successful QA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d0220ba8-74d5-466e-b439-38a1a24fd7c1)

Import Successful MP
![Import Successful MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93bffbc6-3eae-414b-ade6-3a646a7bff8f)

**Comment by mosesdeeCVP** [comment]
Import Successful QA
![Import Successful QA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d0220ba8-74d5-466e-b439-38a1a24fd7c1)

**Comment by mosesdeeCVP** [comment]
Bug fixed. Emissons Import has a separate but causing the UI to crash. This will be taken care of on the Emissons side
