### ISSUE TITLE
Bug: Import Weekly System Integrity Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5013]
Importing weekly system integrity data is throwing an error 

- [ ] Need to modify the weekly system integrity JSON schema from and object to an array of objects 

![image](https://user-images.githubusercontent.com/67170657/228558803-2380a9a1-6c2d-405d-8b1e-dbc820becee6.png)

**Comment by fanwari1** [comment]
To test, add the attached json file to an import. You don't have to actually import the file, you may see other errors but you should no longer see the error about WeeklySystemIntegrityData
[Emissions _ Export - Allen S King (1)  (1).zip](https://github.com/US-EPA-CAMD/easey-ui/files/11173082/Emissions._.Export.-.Allen.S.King.1.1.zip)
