### ISSUE TITLE
Bug: Appendix E Correlation Test Run Data creation throws an Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5016]
**Issue:**
When creating a Test Run Data record under Appendix E Correlation data, the system throws an internal server error. Looks like the Test Run Number isn't being saved

Steps to Reproduce:
1. Login to ECMPS
2. Access and checkout a Configuration for Test Data 
3. From the Test Type Group dropdown, select Appendix E Correlation (Dolet Hills Power Station)
4. Expand the Test Data section and click Add for Appendix E Correlation Run data. Enter all the information needed and click Save and Close.

The system throws an internal server error
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6b165f67-4f13-4db1-8a71-b7e10903cfe1)

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Run data created.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/36e6924d-0a5b-4b81-a329-7ea0579c25d8)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![Appendix E Correlation Run data created Oil.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc2860ec-9427-4d33-ad27-a38586644785)
