### ISSUE TITLE
Bug: Date, and Time need to be combined for Test Types

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5017]
**Issue:**
For Unit Default Test Run, the Date, Hour, and Min are still displayed in separate columns. They need to be combined as Date and Time to be consistent with the recent update throughout ECMPS

Also, implement the update for the following Test Types:
- Cycle Time Injection
- RATA Run Data
- Appendix E Correlation Run
- Unit Default Test Run
- Linearity Injection (Injection Date/Hour/Minute)

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/746d7b39-756f-4fa1-b863-3275a03ad3a4)

**Comment by mosesdeeCVP** [comment]
Cycle Time Injection
![Cycle Time Injection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d2194fa8-a568-4b27-a36d-1c8bd8349871)

RATA
![RATA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6130279d-0612-46d3-a94d-c477ffc51b5f)

Appendix E Correlation Run
![Appendix E Correlation Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f3b317b0-d42b-4e8b-9c03-f2139771fa32)

Unit Default Test Run
![Unit Default Test Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/433c2770-b15c-49c1-846c-f5894788d6ec)

Linearity Injection
![Linearity Injection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f3652e7e-c2c9-4ac0-808c-c64f00dfa8da)

**Comment by mosesdeeCVP** [comment]
Bug fixed
