### ISSUE TITLE
Bug: Issue with Expiration Date in Protocol Gas Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5018]
**Issue:**
When creating a Protocol Gas Data, the Expiration Date field isn't getting saved

**Steps to Recreate:**
1. Login to ECMPS
2. Access and checkout a Configuration under the Test Data section (Platte, 1)
3. Navigate to RATA Data and click on Add for Protocol Gas Data
4. Add data to all the fields, pick an Expiration Date and click Save and Close
You will notice that the Expiration Date is not saved

**Comment by billmiller13** [comment]
Could not recreate bug.  Successfully created a Protocol Gas with expiration date saved in Platte - 1 and E C Gaston - 1, 2, CS0CAN 

![ZenHub-5018.png](https://images.zenhubusercontent.com/62f3bc25cca3fb78227f8f0e/265f70a6-7de9-403f-819b-864696da0da5)

**Comment by mosesdeeCVP** [comment]
Protocol Gas is working as expected
![Protocol Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2849ef19-051c-40af-b3d0-a5dd346ec4c1)
