### ISSUE TITLE
Bug: Cannot create or edit MP Formula Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5026]
Issue:
When a user wishes to create or edit MP Formula data and enters information and clicks on Save and Close, then the system displays a validation 'Must enter in both End Date and Time' even when no selections are made for those fields

Steps to Recreate:
1. Login to ECMPS and access the MP Module
2. Select and checkout a Configuration and pick Formula from the Sections dropdown
3. Click Create/View/Edit for an existing Formula record and enter information for fields except for End Date and End Time
4. Click Save and Close
You will notice that the system displays a validation for End Date and End Time even though no selection has been made for these fields

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5db8ce79-e8b3-4ee2-bd14-3021b6eb5a2e)

**Comment by mosesdeeCVP** [comment]
Bug fixed
