### ISSUE TITLE
Bug: Unable to create Rectangular Duct WAF's due to an invalid validation

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5028]
**Issue:** 
When creating or editing Rectangular Duct WAF's data record, the system displays a validation that won't get cleared up even when the data is corrected. Also, it displays a validation for Defaults in Rectangular Duct WAF's

Steps to Recreate:
1. Login to ECMPS
2. Access the MP Module, select and check out a Configuration (Dolet Hills Power Station (ORIS Code 51)
3. Select Rectangular Duct WAFs from the Sections dropdown
4. Click Create and enter all the information as needed

You will see that the system displays the following validations and these validations do not get cleared even after the data has been corrected:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e7f8c73a-ad67-4fbe-a3eb-233905c050f4)

**Comment by mosesdeeCVP** [comment]
Bug fixed
