### ISSUE TITLE
RETEST: QA Cert Event and TEE Modals do not disappear once record created

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#5029]
Once user creates a new QA Cert Event or TEE and selects save, the record is created but the modal does not disappear. (Is in Dev)

**Comment by alangmaid** [comment]
Please confirm that this bug still exists on dev.

**Comment by mxtomoto1** [comment]
Bug seems to have been resolved on dev and test. QA Cert Events and TEEs were successfully created, and the modal will disappear upon Save and Exit, Cancel, or X.
<img width="960" alt="t_d3" src="https://github.com/US-EPA-CAMD/easey-ui/assets/94564355/2a3e9bc4-7596-403f-ad1d-056720cb1753">
