### ISSUE TITLE
ECMPS 508 Scan in TST Env

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5031]
Ticket to track any 508 bugs/issues as a result of 508 testing in the TST Env

**Comment by aprematta** [comment]
Results so far:
https://ecmps-tst.app.cloud.gov
- There's a link named 'here' in the what's new section, needs to be updated to something that's more descriptive
- When zoomed in at 200%, the top nav disappears and is replaced with a hamburger menu that does not function when 
- When zoomed in at 200%, the left nav is replaced with a top nav that does not function

https://ecmps-tst.app.cloud.gov/help-support
- When the API communication error is thrown, the X does not have an accessible name

**Comment by aprematta** [comment]
https://ecmps-tst.app.cloud.gov/monitoring-plans
Focus is not returned to the view link when the modal is closed, for example on Methods, select view, then close the modal

**Comment by aprematta** [comment]
https://ecmps-tst.app.cloud.gov/workspace/monitoring-plans
- Create/cancel loses focus when creating a new record - focus should go back to create button
- On the configurations page, there looks to be an extra empty H4 (h4 class="margin-top-5 text-bold mobile:font-body-xl mobile:text-bold">/h4)
- Some error messages don't match the label input, for example error message says begin date and screen states start date
- On the create modals, fields overlap when zoomend into 200% (ex create method)

https://ecmps-tst.app.cloud.gov/workspace/qa-cert-event
- On the last column of tables, Eval links are not unique, all say 'Eval'

https://ecmps-tst.app.cloud.gov/workspace/emissions
- Check back in, Revert to official record buttons overlap when zoomed into 200%

https://ecmps-tst.app.cloud.gov/workspace/export
- Select all rows not unique.... add test summary and qa certification events to the aria labels
- aria labels do not seems to relate to te fields that are on screen, for example 'aria-label="select row for Test Number EPA-3B010323454391EA1053F91178DE1528"'

https://ecmps-tst.app.cloud.gov/workspace/evaluate
- Expandable/collapsible elements are not keyboard accessible
- Checkboxes lack labels (label tags exist but they are empty)

https://ecmps-tst.app.cloud.gov/workspace/error-suppression
- Focus not returned to Add button when closing the modal
- Calendar selectors not unique, they should be related to the field label

Throughout application
When on the create modal, there is no required indication for the fields that are required (provide * in label and the text at top * = required..... or use aria required=true
