### ISSUE TITLE
Bug: Schema validation error with Historical Data Import (7 Day Calibration Injection)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5032]
**Issue:**
When a user imports a clean file for QA & Certification, then the system is displaying schema validations. They are not applicable to a clean file being imported

**Steps to Recreate:**
1. Login to ECMPS and access the Test Data Module
2. Select and checkout a configuration and click Import from File (SJRR Power Peaking Facility (CT1, CT2, CP1)
3. Select a clean file for the configuration and click Import
You will see the following validations:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ea639861-f908-45f3-8647-eccbe573e5a3)

**Comment by mosesdeeCVP** [comment]
OnlineOffline Json Schema is fixed
![OnlineOffline Json Schema is fixed.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1946b1eb-052b-4006-8a9a-f1e43caa4f8a)
