### ISSUE TITLE
Bug: Unit Control Original Code and Seasonal Controls Indicator issue

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5033]
**Issue:**
When a user is entering data for Unit Controls in MP Module, upon entering a Seasonal Controls Indicator or Control Code and saving, the user receives the following error 'The value for 0 (or 1) in the Unit Control (or Seasonal Controls Indicator) record original code must be string value of "0" or "1"'

Steps to Recreate:
1. Log in to ECMPS and access the MP Module
2. Navigate to and check out Dolet Hills Power Station (ORIS Code 51)
3. Select Unit Information from the Sections dropdown
4. Add or Edit a Unit Control data record
Upon entering a Seasonal Controls Indicator or Control Code and submitting, you will receive errors that state The value for 0 (or 1) in the Unit Control (or Seasonal Controls Indicator) record original Code must be string value of "0" or "1"

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/479e50ca-4c5b-4066-9b17-073eb8309943)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![Unit Controls .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/97718006-3cdf-4bf2-a3b2-2ba1e446ddff)
