### ISSUE TITLE
 Bug: ECMPS UI Error Handling

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5034]
4/28 Most recently this happened when in the emissions import module when the import failed 

The ECMPS UI is not handling errors from the api's properly. 

The issue
Currently there are occasions where an error has happened in the app but no error message is displayed in the UI and the screen goes blank

Expected Results

The app should always render something even if there is an error. An error at the top of the content section and display the actual error to the user. 

**Steps to Reproduce**
1) Revert #50 widows creek
2) export
3) import
![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/d9bb6d43-844a-4235-80f4-3b6f2d77ec41)

**Comment by vishnunavuluri** [comment]
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/5eb01a40-173b-44b1-b197-00d73a4aff19)
