### ISSUE TITLE
Bug: Import Errors when importing multiple Test Data (Mix of Component and System Based)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5035]
**Issue:**
When a user imports QA Test Data from the historical database for 2022 Q3, then the system throws Import errors even though they are not applicable

**Steps to Recreate:**
1. Log in to ECMPS and access the QA Test Data Module
2. Select and checkout a Configuration (SJRR Power Peaking Facility, CT1, CT2, CP1
3. Click on Import Data and select Import from Historical Data
4. Select the Reporting Year as 2022 and Quarter as Q3 and click Import
The system throws the following Import errors:
Import-14-A for 2NO
Import-15-A for 2NA
Import-15-A for 2O2

Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/55663210-8eba-43d4-bbbb-cac0674c457b)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/459

**Comment by mosesdeeCVP** [comment]
![SJRR Power Peaking Facility Success Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/302fa20b-b090-4fb1-922f-cc98847ea5d9)

**Comment by mosesdeeCVP** [comment]
Bug fixed
