### ISSUE TITLE
Bug: UI Links in the Home Page 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5036]
Links for QA and Emissions buttons on the home page need to be updated. Currently, the links lead to nowhere but they need to go to the QA and Emissions module pages respectively.

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/ba423f8f-73d7-4e24-9244-a0899e32ca48)

**Comment by AmandaMNelson** [comment]
For QA, goes to first sub-category on left side (Test Data)
