### ISSUE TITLE
Bug: ONOFF Import error when importing historical QA Test Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5038]
Issue:
When user imports an Official QA Test Data record, the system throws an Import error for ONOFF

Steps to Recreate:
1. Login to ECMPS and access the QA Test Data Module
2. Select and checkout a Configuration (Mariposa Energy Project, GT-2), and click Import
3. Import an Official Data record and see that the system displays the following Import error

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/850162ac-8578-474b-bbf9-5eda87914f19)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/467

**Comment by mosesdeeCVP** [comment]
![ONOFF Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e504d5bf-c3b4-4911-b980-88e0d5a8000f)

**Comment by mosesdeeCVP** [comment]
Import was successful. Bug fixed
