### ISSUE TITLE
Bug: Issue creating Test Extension Exemption Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5042]
**Issue:**
When a user wishes to create Test Extension Exemption data and clicks on Save and Close after adding all the needed data, the focus jumps to the Close/X button

The modal should be closed if the data is saved and if not maintain the focus on Save and Close and display the applicable validation

**Steps to Recreate:**
1. Login to ECMPS and access the QA Cert Events and TEE Module
2. Select and checkout a Configuration and click on Add for TEE Data
3. Enter all the information as needed and click on Save and Close
You will observe that the first click doesn't do anything and upon clicking again, the focus goes to the X. When you click again, then any applicable validations get displayed (BARRY CS0AAN)

**Comment by mosesdeeCVP** [comment]
Bug fixed
