### ISSUE TITLE
Bug: TEE - Add button keeps moving

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5043]
**Issue:**
When a user wishes to create a new TEE data record and clicks on Add, then the Add button keeps moving

**Steps to Recreate:**
1. Login to ECMPS
2. Access the QA Cert Events, Extension and Exemptions, select and checkout a Configuration, and select Test Extension Exemption from the Test Data dropdown
3. Click on Add and you will notice the button jumps

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d916e17c-7a22-4803-8a25-4a6fba780ba1)

**Comment by mosesdeeCVP** [comment]
Bug fixed
