### ISSUE TITLE
Test Only: Mon Sys ID and Comp ID dropdown not displaying options

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5045]
**Issue:**
When a user wishes to add Test Data under the QA Module, then the Mon Sys ID and the Component ID dropdowns are not displaying any options for selection

**Steps to Recreate:**
1. Login to ECMPS
2. Access the QA Test Data Module, select and checkout a Configuration (E C Gaston)
3. Click on Add for any of the Test Data Type and review the Mon Sys ID and Component ID dropdowns
You will notice that there are no options to select from

**Reference Screenshot:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a86ffd08-f41e-4317-b915-2010f896a11b)

**Comment by JanellC** [comment]
Bug resolved. Mon Sys ID and the Component ID drop downs are displaying options

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3e4e629b-5d9f-4035-87ae-f98e59e235c3)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4593b2f2-caf0-44e9-bc08-277d628e1db7)
