### ISSUE TITLE
Bug: Updates to the Run Number field not saved

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5050]
**Issue:**
When a user wishes to edit Appendix E Correlation Test Run Data, and makes updates to the Run Number the updates are not saved.

**Steps to Recreate:**
1. Login to ECMPS and access the QA Test Data Module
2. Select and checkout a Configuration and select Appendix E from the Test Type Group dropdown
3. Make sure it has data through Appendix E Correlation Run level
4. Update an existing Run Number and click Save and Close
Observe that it doesn't save the updates

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/709d075a-c5a5-4fda-85e2-f2aec3a7920c)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
