### ISSUE TITLE
Bug: Unable to edit an Analyzer Range record under Systems

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5051]
**Issue:**
When a user wishes to update information for an Analyzer Range record, then it constantly throws a _[COMPON-54-A] - Another [Analyzer Range] record already exists with the same [componentID,beginDate,beginHour,endDate,endHour]._

This only happens when trying to update an existing Analyzer Range record, not with creating one

Steps to Recreate:
1. Login to ECMPS
2. Open and checkout a Configuration and select Systems from the Sections dropdown
3. For any existing Systems record, click View/Edit 
4. In the View/Edit modal, locate a Systems Component record and open it (View/Edit)
5. Pick any existing Analyzer Range record or create a new one
6. Try editing any information for the record (Add End Date and Time)
You will see the following validation:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/065b2072-8fc1-43f5-a891-91a392deca5a)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
Bug Fixed
