### ISSUE TITLE
Bug: QA & Certification Export in Workspace calling Official Endpoint

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5052]
**Issue:**
When you are logged in to ECMPS, access the Export, and select QA & Certification option to Preview, then it is calling the official/non-workspace endpoint to retrieve export data instead of the workspace endpoint. 

**Steps to Recreate:**
1. Login to ECMPS
2. Access the Export functionality from the left-hand menu and open a Configuration
3. Select QA & Certification and click Preview
Note that it calls the Official/non-workspace endpoint to retrieve data for Export instead of the Workspace Endpoint

**Comment by mosesdeeCVP** [comment]
Export Workspace
![Export Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/920f6630-6557-44c0-a2a8-858962ab4952)

Export Global
![Export Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/10f0e26e-2592-4fdb-8909-c3529247b68b)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by vishnunavuluri** [comment]
Reopened due to fixes being reverted to prevent additional bugs. Will be fixed and retested before closing

**Comment by subrataroyCVP** [comment]
While testing make sure Import from Historical (logged in) is also working as expected.

**Comment by mosesdeeCVP** [comment]
Export MP Global
![Export MP Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c42d34e1-e6ad-4db1-8268-3c480966f1db)

Export MP Workspace
![Export MP Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/198aee38-dc03-4794-aed2-daa33f377a34)

**Comment by mosesdeeCVP** [comment]
Export QA Workspace
![Export QA Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93ecd95a-9699-4095-9d5a-564d3f13e0d0)

Export QA Global
![Export QA Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/966aea32-a304-432b-809e-7f9bb5437c57)

Export QA Historical Workspace
![Export QA Historical Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5f23f3be-a097-4b3a-bef0-3b8e94c27f7b)

**Comment by mosesdeeCVP** [comment]
Export Em Global
![Export Em Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1dcd712c-0386-416f-8b2d-f366333bbfd9)

Export Em Workspace
![Export Em Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/11b1b916-8bb6-4da4-b561-060deed3ddb0)

**Comment by mosesdeeCVP** [comment]
Bug fixed
