### ISSUE TITLE
Test Only: Unable to Create QA Cert Event Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5053]
**Issue:**
When a user wishes to create QA Certification Event Data, then it throws a validation that QA Cert Event Code must be a string

Note: Might be related to **5049**

**Steps to Recreate:**
1. Login to ECMPS and access the Cert Event and TEE Module
2. Select and checkout a Configuration and click on Add for Certification Event Data
3. Enter all the needed data and click Save and Close
You will observe the following validation displayed:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/89b74e66-f4ed-4717-adb4-2232d10335e7)

Note: Also happens for a lot of other fields in Test Data (Component ID etc)

**Comment by mosesdeeCVP** [comment]
![New Cert Event Record.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6e7ce134-e5d0-4ff1-b37d-ff0b4b1deb0c)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
