### ISSUE TITLE
Bug: Creating AET under Unit Default throws an Internal Server Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5055]
**Issue:**
When a user wishes to create Air Emissions Testing data for Unit Default Test, upon Save and Close it is throwing an Internal Server Error

**Steps to Recreate:**
1. Login to ECMOS
2. Access the Test Data module, select and check out a Configuration
3. Select Unit Default from the Test Type Group dropdown, select an existing record and try adding AET data for it (Grand River Dam Authority)
4. Click Save and Close. You will observe that the system throws an Internal Server Error

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/12902ce5-b13b-4f96-8455-1b23ea2841a6)

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
Bug resolved

Sucessfully added a AET record under Unit Default for  facility Grand River Dam Authority. Bug resolved.

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/11446585-864d-42be-b08f-5404164408ce)
