### ISSUE TITLE
Bug: TEE Data - Update default display for 'Quarter'

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5056]
**Issue:**
When a user wishes to create TEE Data in the QA Module, then the Quarter field by default displays the option 1 instead of 'Select a value'

**Steps to Recreate:**
1. Login to ECMPS and access the Cert Event and TEE Module
2. Select and checkout a Configuration and click on Add for TEE data
You will notice that the selection for Quarter has been defaulted to 1 instead of Select a value

**Comment by mosesdeeCVP** [comment]
![TEE Quarter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/67d61437-dc3c-4c4c-b763-a184269777b7)

**Comment by mosesdeeCVP** [comment]
Bug fixed
