### ISSUE TITLE
Bug: Issue sorting Evaluation Status

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5057]
**Issue:**
When a user wishes to sort Test Data or Test Extension and Exemption records on the Evaluation Status, it is not working

**Steps to Recreate:**
1. Login to ECMPS
2. Select and checkout a Configuration either under any of the Test Type Groups in Test Data or the Test Extension and Exemption data
3. Sort on the Evaluation Status
You will notice that the sort is not working as intended

Note: The fix needs to be implemented for all Test Type Groups under Test Data as well as for Test Extension and Exemption Data. Certification Event has been fixed

**Comment by mosesdeeCVP** [comment]
![Sort TEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d9396114-acc6-46f2-9b74-383e69db7c32)

**Comment by mosesdeeCVP** [comment]
Sort AppE
![Sort AppE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/15c31bfb-9e8f-4e9b-8d75-8d1d441f1cc5)

Sort Cal Inj
![Sort Cal Inj.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7991c00d-054d-4a7b-af78-dcf569ab9839)

Sort Cyc Time Sum
![Sort Cyc Time Sum.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/093360e3-201c-42ea-b6ea-fdc35e4b29f3)

Sort F2LCHK
![Sort F2LCHK.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c193e6c5-3c85-4aa7-be9c-9dbffc0ef73c)

Sort F2LREF
![Sort F2LREF.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e8811705-1f17-4a64-8527-f7bc752f451a)

Sort FF2L
![Sort FF2L.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/573ee630-8c00-4f39-9fb4-c392b9d06b14)

Sort FF2LBAS
![Sort FF2LBAS.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9246dfc8-f219-4db7-adf8-0316549e51c6)

Sort FFA
![Sort FFA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cf5cb13e-0c8e-4efc-8a8e-a6671f537b12)

Sort HG LINE
![Sort HG LINE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/861e003f-b270-4316-8cea-9ee2083b5f15)

Sort LINE
![Sort LINE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a3db90f2-c762-48bf-bd07-421db9e7f8d4)

Sort Misc
![Sort Misc.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/52cb99fc-a54d-41be-b2ef-2c58be66fdad)

Sort OnOff
![Sort OnOff.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cf44f59f-ba96-4581-a33c-4e15c10832ac)

Sort PEI
![Sort PEI.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c900c6d9-e3e3-4c79-9a13-bbd63f812966)

Sort RATA
![Sort RATA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a2443fcc-6249-4ca8-ab2a-23486012937f)

Sort TTA
![Sort TTA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ab927988-f62e-4aa2-b075-f766f6c4622e)

Sort Unit Default
![Sort Unit Default.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8cc0e980-f0e9-4e3b-b1a7-51945aa410bb)

**Comment by mosesdeeCVP** [comment]
All QA Elav sections sort properly
