### ISSUE TITLE
Bug: Test Qualification Data and Air Emission Testing Data missing in Import and Export (RATA)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5059]
**Issue:**
The data elements for Test Qualification Data and Air Emission Testing Data are not available in the Import and Export endpoints. We need to add those
- Add data elements to Export endpoints in both the Global and the workspace. Import is for Workspace only
- Test Qualification Data is applicable to RATA only
- AET data is applicable to RATA, and Unit Default

**Steps to Recreate:**
1. Login to ECMPS
2. Navigate to the Test Data module, select and check out a Configuration and locate a RATA record
3. Create Test Qualification and Air Emissions Testing Data and save
4. Now navigate to Export and for the same Configuration, locate the RATA record and export
You will notice that the AET and TQ data are missing in the export. The same behavior is observed when you Import data for RATA with Test Qualification Data and Air Emission Testing Data

**Comment by mosesdeeCVP** [comment]
testQualificationData Rata Workspace
![testQualificationData Rata Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/879b2ddc-ce91-48e5-8fbf-8c2002d54b8b)

testQualificationData Rata Global
![testQualificationData Rata Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3a8ba6e2-7c89-4a97-b616-69f5770507aa)

airEmissionTestingData Rata Global
![airEmissionTestingData Rata Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/58bedc58-7f90-448f-85f9-726ae016c6df)

airEmissionTestingData Rata Workspace
![airEmissionTestingData Rata Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c6804dad-c8a5-47a5-bf80-50b898f163a9)

**Comment by mosesdeeCVP** [comment]
airEmissionTestingData UNITDEF Workspace
![airEmissionTestingData UNITDEF Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/92970fce-e180-4bd2-9a87-13675384c0f4)

airEmissionTestingData UNITDEF Global
![airEmissionTestingData UNITDEF Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3692237b-9cfa-4414-9b0e-fc83d7b064e4)

**Comment by mosesdeeCVP** [comment]
airEmissionTestingData UNITDEF Workspace
![airEmissionTestingData UNITDEF Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/92970fce-e180-4bd2-9a87-13675384c0f4)

**Comment by mosesdeeCVP** [comment]
Bug fixed
