### ISSUE TITLE
Bug: Evaluation Reports not showing up-12.4

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5060]
Issue:
MP and QA Evaluation Reports are not working

Steps to Recreate:
1. Login to ECMPS 
2. Access the QA Module
3. Select and checkout a Configuration. Locate a data record where the Evaluation Status of PASS, ERR or Informational is available
4. Click on the status
You will notice that the spinner keeps on going and the Report is never displayed

For testing, request the Batch ID on the check session column to be dropped for the 500 error to show up

Note: Test for both MP and QA

**Comment by jwhitehead77** [comment]
Fixed
![image](https://user-images.githubusercontent.com/66504934/235576723-2f435c9f-2085-4041-a402-bfbd4f3d6575.png)
![image](https://user-images.githubusercontent.com/66504934/235576766-2e453143-cb0e-49db-afb3-09e057ebb261.png)
![image](https://user-images.githubusercontent.com/66504934/235576820-ece40ca1-9108-4d93-a3dc-484c37eaf66c.png)
