### ISSUE TITLE
Bug: Update Date and Time Display and Label in ECMPS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5062]
1. Update the Labels as below and the format as YYYY-MM-DD HH:MM:
Begin Date and Time to Begin Date/Time **AND** End Date and Time to End Date/Time 
**MP:**
- Defaults
- Formulas  
- Loads
- Methods
- Supplemental Methods
- Rectangular Duct WAF
- Spans
- System
- Component
- Analyzer Range
- Fuel Flow

End Date to End Date/Time
 **Test Data:**
- Appendix E
- Calibration Injection
- Cycle Time Summary
- Cycle Time Summary
- Flow to Load Reference
- Fuel Flow to Load Baseline
- Fuel Flowmeter Accuracy
- Hg Linearity and 3-level Summary
- Miscellaneous
- Linearity Summary
- Online Offline Calibration
- Primary Element Inspection
- Relative Accuracy
- Transmitter Transducer Accuracy
- Unit Default

**Export Functionality:**
For Test Summary data, update the label Begin Date/Hr/Min to Begin Date/Time **AND** End Date/Hr/Min to End Date/Time

**Evaluate Functionality:**
For Test Summary data, update the label Begin Date/Hr/Min to Begin Date/Time **AND** End Date/Hr/Min to End Date/Time
For QA Certification Events data, update QA Cert Event Date/Hr to QA Cert Event Date/Time;  Conditional Date/Hr to Conditional Date/Time; and 
Completion Date/Hr to Completion Date/Time
Update the format for Last Modified Date to be consistent with the other dates in the application

**Comment by mosesdeeCVP** [comment]
Monitoring Plan:

**Comment by mosesdeeCVP** [comment]
Monitoring Plan:

Defaults Global
![Defaults Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4e2ff3b0-0eb6-4d7a-82ef-fdf8bf465210)

Defaults Workspace
![Defaults Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f3dbdf07-106e-41b5-be45-423ff44ecaf0)

Formulas Global
![Formulas Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/37084fcd-b524-4cee-97aa-e862e1e4e151)

Formulas Workspace
![Formulas Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ed3a1736-0b09-4ae2-8e58-531e0e320b83)

Loads Global
![Loads Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/903ef956-7387-4d50-a21a-29151a854fc8)

Loads Workspace
![Loads Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/19a468e5-08a4-4fd8-b3c0-40ccd61f4355)

Methods and Mats Global
![Methods and Mats Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a9ee7cb7-461e-41e1-a4f6-da9b013509ca)

Methods and Mats Workspace
![Methods and Mats Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7871d864-24bd-465d-902d-fd3e3fa50185)

Spans Global
![Spans Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5f8e8940-81b3-4fa0-9e6d-5b38aea99238)

Spans Workspace
![Spans Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/01da59ff-9463-4c4c-9278-6b1b22e138c1)

Systems Global
![Systems Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/24971358-7bf1-499f-8e38-b9cf9f87c446)

Systems Workspace
![Systems Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5b3cb070-077d-47ba-841f-b17a9a45373d)

Components Global
![Components Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/13377599-aaf2-46f6-a644-292d14fa126f)

Components Workspace
![Components Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8e49801c-4b4f-4ffa-9da9-f32ec4c8d342)

Duct Wafs Global
![Duct Wafs Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5c4e75f0-6246-4613-bd0d-9888334a12a9)

Duct Wafs Workspace
![Duct Wafs Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/089db5eb-701b-4c66-b2a2-32c7d0587459)

Fuel Flows Global
![Fuel Flows Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/127c1fad-ef76-448f-b7d4-7b3a8bda73e0)

Fuel Flows Workspace
![Fuel Flows Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1b2c7d15-c55d-4bc0-8944-b4dccad82efb)

Analyzer Ranges Global
![Analyzer Ranges Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/91ff897d-c6fc-4e8c-a073-a54ea638fd6b)

Analyzer Ranges Workspace
![Analyzer Ranges Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/64a5c38b-2164-469f-9358-6c8c58f6ce14)

**Comment by mosesdeeCVP** [comment]
QA

Unit Default Workspace
![Unit Default Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ec6f5e94-d24d-41f0-8be9-c89b2ac717ca)

Unit Default Global
![Unit Default Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d3d90015-2ba1-4a1b-b7d1-c961ab0aaa7f)

Transmitter Transducer Accuracy Workspace
![Transmitter Transducer Accuracy Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/08703e13-6994-4abf-a7cb-65ac0367e6f9)

Transmitter Transducer Accuracy Global
![Transmitter Transducer Accuracy Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/26ef6960-573d-45fb-a88d-625d64440bbb)

Protocol Gas Workspace
![Protocol Gas Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9d0baee5-7117-4d3a-8cc5-0b008622b29d)

RATA Workspace
![RATA Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f9333ee7-1cda-49b7-b2b7-92b73476fedc)

RATA Global
![RATA Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/37b595eb-d83b-4029-a3f0-4317e6f7ae80)

Primary Element Inspection Workspace
![Primary Element Inspection Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1408abc9-66d7-4bae-b37a-0ac746cb0586)

Primary Element Inspection Global
![Primary Element Inspection Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/206ed23f-fbc4-41ec-ad11-4d08de8a567d)

On-Off Workspace
![On-Off Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e35af27a-290e-4eef-9be4-1615c1c448c2)

On-Off Global
![On-Off Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/868baaed-3c24-4011-95d7-7b30f3c93299)

Linearity Summary Workspace
![Linearity Summary Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f5ee6e96-7da4-4592-af99-246b2b51b0e2)

Linearity Summary Global
![Linearity Summary Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/765bc1ee-09c7-4950-a0f9-31b6e0805385)

Misc Workspace
![Misc Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d9a8c1f8-0cfa-4f0a-b45e-48983c12a80f)

Misc Global
![Misc Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/03b5d760-c30c-4ccb-bcb8-4603c3e51bab)

Hg Linearity and 3-level Summary Workspace
![Hg Linearity and 3-level Summary Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5ea95f32-2f15-4579-9afb-e63229769184)

Hg Linearity and 3-level Summary Global
![Hg Linearity and 3-level Summary Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d66c1de6-e9bc-4fde-8fda-dfcc7046c017)

Fuel Flowmeter Accuracy Workspace
![Fuel Flowmeter Accuracy Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e43862b3-b14c-4e76-8141-130ee177e6eb)

Fuel Flowmeter Accuracy Global
![Fuel Flowmeter Accuracy Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7e56fd3a-36d4-4d38-a448-23a0d6b40be6)

Fuel Flow to Load Baseline Workspac
![Fuel Flow to Load Baseline Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/70cf16de-a24d-4d11-974d-54b6a5f96d04)

Fuel Flow to Load Baseline Global
![Fuel Flow to Load Baseline Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0c6bf549-99e3-406d-8366-2cd2e58d64a8)

Flow to Load Reference Workspace
![Flow to Load Reference Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/59f3814f-8454-4fa7-9258-74a414b9af71)

Flow to Load Reference Global
![Flow to Load Reference Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/031f4203-662b-4094-9216-b53a54fda180)

Cycle Time Summary Workspace
![Cycle Time Summary Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d5f53a71-ad50-493d-af15-7710ed757409)

Cycle Time Summary Global
![Cycle Time Summary Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/366984f1-a466-4ed5-b89d-b1f7072ec5b2)

Calibration Injection Workspace
![Calibration Injection Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/96b6bbaa-027c-4f01-8b30-4d6971893433)

Calibration Injection Global
![Calibration Injection Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9c11b6e5-821b-46c8-9b13-a0004fdc2715)

AppE Workspace
![AppE Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4ded3903-1931-4aa9-895d-bac77abf55e4)

AppE Global
![AppE Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5cbc7ca2-af25-48a0-978e-7683462e1371)

**Comment by mosesdeeCVP** [comment]
Eval Workspace
![Eval Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dd2db91a-ed9a-4c43-b79f-b56fe9d2056c)

Export Workspace
![Export Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3a3bf3a6-ae86-4d4c-869a-1870df4f8811)

Export Global
![Export Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f3b7f06e-386d-48d6-b4b6-cc776015a53d)

**Comment by mosesdeeCVP** [comment]
A couple minor bugs were found. Dev team has been informed

**Comment by subrataroyCVP** [comment]
New Pull Request for fixes: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1041

**Comment by mosesdeeCVP** [comment]
Date and Time Eval - Mon Plan, Test Data QA Cert Events
![Date and Time Eval - Mon Plan, Test Data QA Cert Events.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e7b4a853-7cef-4895-a8f5-2d0c28d52e5b)

Date and Time Eval - Test Data, QA Cert Events and TEE
![Date and Time Eval - Test Data, QA Cert Events and TEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/db5fab58-e82b-486d-bb19-d990e21cc4f1)

**Comment by mosesdeeCVP** [comment]
Updates to Date/Time Labels and Formats have been made.
