### ISSUE TITLE
Bug: Unable to import historical App-E Heat Input from Gas and App-E Heat Input from Oil

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5064]
**Issue:**
When a user Imports QA data from Historical, they are unable to import historical App-E Heat Input from Gas and App-E Heat Input from Oil

Steps to Recreate:
1. Login to ECMPS
2. Access the Test Data Module, select and check out a Configuration (T H Wharton, "orisCode": 3469)
3. Click on Import and select Import from Historical and make selections. Click Import
You will notice that the data cannot be imported

**Comment by mosesdeeCVP** [comment]
Bug fixed. Historical Import working as expected.

App E Gas from Historical
![App E Gas from Historical.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2619dc34-05aa-48f6-aa3e-ba119b329361) 

App E Gas from Historical Table
![App E Gas from Historical Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cde06366-2074-4aa1-bf79-4390f50afe9f)

App E Oil from Historical
![App E Oil from Historical.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/69c2d2ce-3e1e-4077-87c7-8210f92d2045)

App E Oil from Historical Table
![App E Oil from Historical Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0bfe8c03-9fb0-45f1-bdae-e605c59e3f79)
