### ISSUE TITLE
Bug: Data being cutoff when a Configuration has multiple Locations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5065]
**Issue:**
When a user opens a Facility-Configuration with multiple locations, then the information is not formatted correctly in the tab

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/158dcf90-9a1f-4f20-9fa6-e1bacf495536)

**Resolution:** 
Display as many locations as the Configuration tab can fit without being cutoff followed by '.......' for the rest. When a user hovers over they shall be able to review the entire list

**Comment by mosesdeeCVP** [comment]
![5065 Data being cutoff when a Configuration has multiple Locations.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/287bb3a6-9bf6-4239-88ac-8e00b1213f91)

**Comment by mosesdeeCVP** [comment]
Bug fixed
