### ISSUE TITLE
Bug: Quarter displays 'Select a value' for TEE when viewing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5074]
**Issue:**
When a user is viewing TEE data, then the Quarter dropdown displays 'Select a value' when the value is Null. It should just be blank

Steps to Recreate:
1. Access Cert Event and TEE Module, select and open a Configuration
2. Select Test Extension and Exemption from the 'Test Data' dropdown
3. Pick a Record where there is no selection made for the Quarter and review how it is being displayed. You will notice that it shows 'Select a value' instead of being blank

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/b4b0f764-3b34-41de-b604-086c22904e82)

**Comment by mosesdeeCVP** [comment]
![TEE Quarter.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc1db3eb-4ef4-46c7-a584-72b9c4a8ffd4)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
