### ISSUE TITLE
Retest Only: Bug: Not able to Import Historical Data for QA Test Types

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5075]
**Issue:**
Users are unable to Import from historical data even when there is data available

**Steps to Recreate:**
1. In the Global view, navigate to the QA Test Data module and pick a Configuration that has data available
2. Now login to ECMPS and access the QA Test Data module. Select and checkout a Configuration
3. Click on Import and select Import from Historical. Make selections for the fields for the same Configuration that you reviewed in the Global-view and try to preview information
You will notice that the system doesn't being up any historical data to be imported

Configuration Used: Cholla

**Comment by mosesdeeCVP** [comment]
Import from Historical is working. Some individual bugs exist and will be addressed in other tickets.
