### ISSUE TITLE
Bug: Formatting Issues with the Configuration Tab

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5079]
## Context 

Note: This is a cosmetic issue and it does not impact the systems functionaility 

**Need to discuss if this bug needs to be fixed before the May BETA. If this bug must be fixed before the BETA release it must be resolved before the end of 12.4.**  

The formatting of the configuration tab changed. The facilities locations text is under the tab line the text is cut off.  Additionally, the pencil icon that appears when a user checks out a config is under the facility name when it used to appear next to the facility name. The issue happens in the global and workspace for all modules (emissions, mp, and qa) 

## Steps to Reproduce

**Global** 

1. Navigate to the mp, qa, or emissions module 
2. open a config and look at the config tab

The formatting of the configuration tab changed.

**Workspace** 

1. Login to to ECMPS 
2. Navigate to the mp, qa, or emissions modules
3. Check out a config and look at the config tab 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c26cdbe5-aac5-400b-9828-711b1b5bc693)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/613784ad-5c89-460b-a2b7-f4f6c9a107d0)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/bdf1fffe-0dd0-480c-8b64-9655b794934b)

**Comment by vishnunavuluri** [comment]
Duplicate
