### ISSUE TITLE
Bug: Issues with Creating and Editing Appendix E data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5080]
## Context 
**Need to discuss if this bug needs to be fixed before the May BETA. If this bug must be fixed before the BETA release it must be resolved before the end of 12.4.**  

Multiple issues are occuring with Appendix E data. See below 

### **Issue 1: Appendix E data is not saving to the correct test type** 

1. Log into ECMPS and navigate to the QA module
2. Check out a config 
3. Select a any test type that is not appendix e (ex. Rata) 
4. Select Appendix E as a test type 
5. Add test summary data to appendix e 

The data is not saved to appendix e but the data is saved to the test type the user first selected. This issue has been happening randomly and cannot always be replicated. 

## **Issue 2: Appendix E Heat input from gas returns false error message about duplicate records** 
1. Log into ECMPS and navigate to the QA module
2. Check out a config 
3. Select Appendix E as a test type 
4. Edit a  Heat input from gas record 
5. Save changes 

The system returns an error message about duplicate records but this error message is false. 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/946733a3-2dc9-4b4f-956c-d94bcf5dd876)

**Comment by mosesdeeCVP** [comment]
Bugs fixed
