### ISSUE TITLE
Test Only: MP systems Modal improperly handles editing and creating data

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5081]
### **Issue 1: Cannot create a systems record after fixing an error** 
1. Log into ECMPS 
2. Navigate to MP and check out a config 
3. Select systems as a section
4. Select create system 
5. Fill out all of the fields in the modal and leave start time blank 
6. Select save 
7. The system prompts the user to enter a value for start time 
8. Enter in a value for start time and select save

The system does not save the changes and continues to display an error message despite the user making updates 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7731227b-13b5-412d-a57e-b0e4e4847041)

**Comment by vishnunavuluri** [comment]
The issue has been addressed. Able to create a Systems record successfully:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/185fd292-6091-4d86-b4cb-a1e09de99e57)
