### ISSUE TITLE
Bug: Fuel Flows label Imporpely displayed

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5082]
## Context 

Note: This is a cosmetic issue that does not impact functionailtiy 

**Need to discuss if this bug needs to be fixed before the May BETA. If this bug must be fixed before the BETA release it must be resolved before the end of 12.4.** 

The MP Fuel Flows Label is impropely displayed in the modal. The label has additional padding and is not aligned like the other labels. This issue was spotted in the workspace and should be confirmed that it is not happening in global. 

## Steps to Reproduce

1. Login into ECMPS 
2. Navigate to the MP module 
3. Select systems as a section 
4. Select view/edit and scroll down 

The Fuel flow label has more padding than other labels. 

**Fuel Flow Label Display** 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/abafd0c1-7ed0-48fc-9506-208886429998)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1507d99d-259e-4c9a-b0bf-7e44e06d5916)

**Comment by mosesdeeCVP** [comment]
![Fuel Flow label.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c19135af-55eb-4826-8b67-06407c966f4f)

**Comment by mosesdeeCVP** [comment]
Bug fixed
