### ISSUE TITLE
Bug: Issue with adding '0' for Time

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5085]
**Issue:**
When a user selects '0' for End time when adding MP information, then the system has various issues:
1. It doesn't display the validation to prompt the user that Both the End Date and Time must be entered together. It saves the record with just the end time
2. When a user enters both the End Date and En Time (but 0 for End Time), then the system throws the validation 'Must enter in both End Date and End Time
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/7e2c4b2b-858b-428b-a786-e25747ddda56)

**Steps to Recreate:**
1. Login to ECMPS
2. Access the MP module and select and check out a Configuration
3. Select any of the options (Method, Default etc.) from the Sections dropdown
4. Click Create, and add all the needed information
5. Add only the End Time as '0' and click Save
You will notice that the record is created and saved but with no end date
6. Now select an End Date and leave the End Time at '0'
7. Click Save
You will notice that the system doesn't recognize that we made a selection for the End Time and displays the validation 'Must Enter in both Ed Date and End Time'

**Comment by mosesdeeCVP** [comment]
Bug fixed
