### ISSUE TITLE
Bug: AET and PGD sections missing for APP-E Test Type

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5086]
**Issue:**
User is unable to add Air Emissions Testing Data and Protocol Gas Data for Appendix-E Test Type

**Steps to Recreate:**
1. Login to ECMPS 
2. Access the Test Data module, select and check out a Configuration
3. Select Appendix-E from the Test Type Group dropdown 
Review the Sections underneath. The Air Emissions Testing Data and Protocol Gas Data are not seen

Prototype Ref:
Global: https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w4YnFuMTUxMDJsaDNiNnlkeWo5Z2FyZg%3D%3D
Workspace: https://projects.invisionapp.com/freehand/document/38vmVWIc0?zoomToItems=Y2w2bnk2NnI2MDByeTNiN211eTYwemk5ZQ%3D%3D

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
AET and PGD sections missing for APP-E Workspace
![AET and PGD sections missing for APP-E Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e818274e-6fdd-49f6-b1ae-888765c64147)

AET and PGD sections missing for APP-E Global
![AET and PGD sections missing for APP-E Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8ac7f993-db77-45b9-8963-d7186fe57d35)
