### ISSUE TITLE
ECMPS Global-view: Update Export Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5087]
**Global-view: Make the following updates to the Export functionality:**

1. Remove the need to Preview data for QA & Certification Data
Notes: Currently, when a user select QA & Certification data for Export, we don't provide the ability to directly export it. Users have to click Preview to see what data is available for Export, make selections and the Export button becomes available. We want to update it so that when a user selects QA & Certification checkbox and makes a selection for the Year and Quarter, we load data available for Export. 
- Updating the Year and Quarter selection shall refresh the data being displayed for Qa & Certification
- The Export button becomes Active once a user makes a selection for MP, QA and/or Emissions
- When a user checks multiple modules for export and no QA & Certifications data is selected from the data loaded, then we should not generate a QA file

2. Add an 'Export' button at the top of the screen (Currently we have the button only at the bottom and users need to scroll when there is a lot of data available for selection)

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
1. Remove the need to Preview data for QA & Certification Data

The preview buttons has been removed and the export functionaility works in alignment with requirements. This change is reflected in the worksapce and global view 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3483db82-0940-47c7-b7d2-1e4cc6eef7ca)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3156c30e-7f36-4bb3-a2dd-0223636d6558)
