### ISSUE TITLE
No Space Left on Device

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#5090]
Currently occuring in the emissions endpoint. 
Error Message: 

LoggingException: could not write to file "base/pgsql_tmp/pgsql_tmp25924.22": No space left on device

**Comment by hamezene** [comment]
Need to debug

**Comment by ergjustin** [comment]
Video about this ticket: 
https://decisionpointcorp-my.sharepoint.com/personal/skhan_decisionpointcorp_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Fskhan%5Fdecisionpointcorp%5Fcom%2FDocuments%2FRecordings%2FCVP%20will%20assign%20cases%20to%20the%20team%2D20230829%5F081323%2DMeeting%20Recording%2Emp4&ga=1
Start time : 38.15
End time 39.03


@jwhitehead77 Can you please confirm Is there any work to be done to me in this ticket?

**Comment by jwhitehead77** [comment]
I have not seen this issue in a while and I think this is an old ticket and we have made significant changes in the api since Apr when it was logged but there is no coding to be done specifically for this. We would just add more allocated space to the database
