### ISSUE TITLE
value.split is not a function 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#5092]
**Steps to Reproduce**
1) Navigate to the Emissions Management Swaggar page
2) Craft a request that has two year parameters/two repeated parameters. EX:
https://api.epa.gov/easey/dev/streaming-services/emissions/apportioned/quarterly?year=2020&year-2021&quarter=1&exclude=countOpTime
3) System returns a 500 response code

**Comment by acollad1** [comment]
Needs to be revalidated before proceeding with developement

**Comment by bchofor** [comment]
Navigate to CAMD dev environment HOME.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0d12075316836d918a0af1390115acd9e6d594c/image.png)

Scroll down and click on " Start your data query"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b09d00a98555e2f6004ad1d2840cf8a889efe28/image.png)

Set data type to EMISSIONS and sub data type to QUARTERLY EMISSIONS then click apply
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc2d8431098248c7a6e4e295d5a69d55582765a9/image.png)

Click on TIME PERIOD and enter 2020 then select Q1 and click "apply filter"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2521827262a50e3465d84383e1be6c7472151df9/image.png)

Click "preview data"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63e0598a319090a403717af57d5bdfb76d03ee5e/image.png)

Click the 3 dots edit button next to OPERATING COUNT then click on customize columns scroll down and uncheck OPERATING TIME COUNT then click on APPLY.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b05dde397493e56e9ff73438046d1fc3e8fc141/image.png)
Click on Download. This should download without any errors.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d7617eae7af559f87f902b50862c3f28d1fb38a/image.png)

**Comment by bchofor** [comment]
This completes the test and the ticket has passed.

**Comment by tlageman-epa** [comment]
this also looks good in the campd ui and when i try the api directly. however, same issue with dev swagger page freezing. @bchofor

**Comment by tlageman-epa** [comment]
this also looks good in the campd ui and when i try the api directly. however, same issue with dev swagger page freezing. @bchofor

**Comment by shahbazkhan1999** [comment]
@tlageman-epa I've fixed the issue in this repo you can test it now
US-EPA-CAMD/easey-streaming-services#97

**Comment by tlageman-epa** [comment]
looks good in staging re: api call, but same swagger page issue i mentioned in dev. See email comments
