### ISSUE TITLE
response.List.map is not a function

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#5093]
**Steps to Reproduce** 

1) Navigate to Postman/CAMPD Swaggar page 
2) Execute a request using the exclude parameter, EX:
https://api.epa.gov/easey/dev/streaming-services/emissions/apportioned/quarterly?year=2020&quarter=1&exclude=countOpTime
3) System returns a 500 Status Code

**Comment by shahbazkhan1999** [comment]
@bchofor test this on dev

**Comment by bchofor** [comment]
Navigate to CAMD dev environment HOME.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9291943c679500f27f3252df5eb17cc728bfe58b/image.png)
 
Scroll down and click on " Start your data query"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8109ca6bae78a236f98388226f43250513e7377c/image.png)

Set data type to EMISSIONS and sub data type to QUARTERLY EMISSIONS then click apply

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc2b52c6c62b62f21141ed8af8249cd933939282/image.png)

Click on TIME PERIOD and enter 2020 then select Q1 and click "apply filter"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65399c18e96432b0a0af476fd04951a0bca58a50/image.png)

Click "preview data"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da00aa020599017cf2b50ef941f4e27a2143656e/image.png)
Click the 3 dots edit button next to OPERATING COUNT then click on customize columns scroll down and uncheck OPERATING TIME COUNT then click on APPLY.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b690a0e0621f513d93a119a36fcd2efdc83c120a/image.png)

Click on Download. This should download without any errors.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ppQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ada534bd60f2f43c9fb09aca9bf5182cec18931/image.png)

**Comment by bchofor** [comment]
This completes the test and the ticket has passed.

**Comment by tlageman-epa** [comment]
this looks good when hitting the API directly or using the campd interface. However, the dev swagger page crashes (freezes) when I try this using the swagger page. I'm not sure if you are experiencing that or it is just me? @bchofor

**Comment by shahbazkhan1999** [comment]
@tlageman-epa I've fixed the issue in this repo
https://github.com/US-EPA-CAMD/easey-streaming-services/pull/97

**Comment by tlageman-epa** [comment]
looks good in staging re: api call, but same swagger page issue i mentioned in dev. See email comments
