### ISSUE TITLE
Bug: Unable to Create QA Cert Event Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5094]
**Issue:** 
When a user wishes to create QA Cert Event Data, the system displays the following validation:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/12440728-3f39-4485-a322-ecdb1101596b)

The Unit ID is available 

**Steps o Recreate:**
1. Login to ECMPS and access the Cert Events, Ext and Exemptions Module
2. Select and check out a Configuration
3. Click on Add for QA Certification Event data
4. Once you enter all the information needed and click Save and Close, you will see the above validation displayed

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
![New Cert Event Record.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b0f55062-14a1-4248-a3b0-5108fa2f31e4)
