### ISSUE TITLE
Bug: Hard coded links in QA module (To be tested in TST and Beta)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5097]
## Context 
There are hard coded references in the QA module. Urls should not be harded and should utilize the configurations services. This issue was spotted for the flow to load reference test type. As apart of the scope of this ticket, need to ensure EVERY test type in the QA module does **NOT** contain hard coded urls. 

## Steps to Reproduce
Log into the Test Env
Navigate to the QA module 
Check out a config 
Select Flow to load Reference as a test type 
Add Test Summary data 
Add a second level of data 

The user can not add a second level of data. When you inspct the code, the url is pointing to the dev site. rls should not be harded and should utilize the configurations services.  As apart of the scope of this ticket, need to ensure EVERY test type in the QA module does **NOT** contain hard coded urls.

**Comment by mosesdeeCVP** [comment]
Once code is deployed to TST it will be confirmed and tested there

**Comment by JanellC** [comment]
Tickcer will be tested in Bug: Test Only: Hard coded links in QA module (Test In BETA and Test Env) #5104 during 12.5
