### ISSUE TITLE
Identify testing frameworks 

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#51]
- [x]  Meet with tech team to identify how to set up testing frameworks
- [x] Identify language for testing framework
- [x] Identify testing tools 

Assignee:
Yefim

**Comment by YefimAbramsonCVP** [comment]
The testing framework will be written in the Java Language, using a Maven packager, TestNG as the testing engine, and Selenium/Rest Assured as the Automation Engine. Github Runners will be the remote VM to run the tests for the Pipeline.
