### ISSUE TITLE
Test Only: Format "Expiration Datemm/dd/yyyy" in Protocol Gas Data Modals

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5100]
Add space between 'Expiration Date' and 'mm/dd/yyyy' in the Protocol Gas Data Modals

Protocol Gas Data is applicable to the following Test Types:
- Linearity Summary
- Relative Accuracy
- Appendix-E
- Unit Default

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/6e6453e4-9fdd-4eed-a348-e68833ae7dd8)

**Comment by mosesdeeCVP** [comment]
Edit Protocol Gas
![Edit Protocol Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/db109fc4-df75-4136-9f42-65f420700ad5)

Add Protocol Gas
![Add Protocol Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b5d8a06-ed27-4cf2-ac28-6e6dda4b1f43)

Add  Rata Test Summary Data
![Add  Rata Test Summary Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bc9d6965-18f2-4dc5-a0ba-7bad00743cd5)

Edit Rata Test Summary Data
![Edit Rata Test Summary Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/81dfd684-2616-4a05-a1e7-ccca1ca7d320)

Edit Linearity Injection
![Edit Linearity Injection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/018d9b11-905c-41f2-8421-88ce26873951)

Add Linearity Injection
![Add Linearity Injection.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5bda1b91-94c4-42c1-87f6-5354420b4330)

Add Appendix E Correlation Run
![Add Appendix E Correlation Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8db52ded-4ac5-4c2d-a242-3008a807e139)

Edit Appendix E Correlation Run
![Edit Appendix E Correlation Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ca03fbd9-5707-4e07-aea2-295501c69a68)

Add Unit Default Test Run
![Add Unit Default Test Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/77993566-d596-4aee-adbc-fdbab516bb7b)

Edit Unit Default Test Run
![Edit Unit Default Test Run.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2b023d60-b7b4-4190-b194-5c4b415d3de2)

**Comment by mosesdeeCVP** [comment]
Bug fixed
