### ISSUE TITLE
Test Only: Create MP Defaults throws invalid validations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5101]
**Issue:**
Adding a new MP Default record throws the following validations:
"The value for [defaultValue] for [Monitor Default] must be within range of -9999999999.99 and 999999999.99. "
"The value for [defaultValue] for [Monitor Default] is allowed only four decimal place" where the value met the requirement (SO2 Rate value with four decimal place.  There is no selection list or options to enter data in "Purpose" box."

**Steps to Recreate:**
1. Create Default record:  choose Parameter "SO2 Hourly Emission Rate (lb/mmBtu), enter the following:  Default Value: 0.0123, Units of Measure: select Pounds/mmBtu, Purspose: <selection list is not populated>, Fuel Code: Natural Gas, Operating Condition: Base Load Hour, Source of Value: Default Value from Part 75, Group ID: Null, Start Date - mm/dd/yyyy: 04/18/2023, Start Time: 15
2. Click Create

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/4e269c25-39dc-4951-b8f8-3f457bba9edb)

**Comment by vishnunavuluri** [comment]
Test in TST and Beta once deployment is complete

**Comment by mosesdeeCVP** [comment]
Am able to create a MP Default

![Created Default.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9aa00cff-69f1-46b6-acb3-9d1787e19815)


![Created Default Edit.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e48dd0a3-f083-4112-b765-1b0d01557417)
