### ISSUE TITLE
Bug: Test Only: Hard coded links in QA module (Test In BETA and Test Env) 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5104]
## Context 
There are hard coded references in the QA module. Urls should not be harded and should utilize the configurations services. This issue was spotted for the flow to load reference test type. As apart of the scope of this ticket, need to ensure EVERY test type in the QA module does **NOT** contain hard coded urls. 

## Steps to Reproduce
Log into the Test Env
Navigate to the QA module 
Check out a config 
Select Flow to load Reference as a test type 
Add Test Summary data 
Add a second level of data 

The user can not add a second level of data. When you inspct the code, the url is pointing to the dev site. rls should not be harded and should utilize the configurations services.  As apart of the scope of this ticket, need to ensure EVERY test type in the QA module does **NOT** contain hard coded urls.

**Comment by mosesdeeCVP** [comment]
BUG: Hard Coded link to module
![Hard Coded link to module. Test Only.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b520895-8578-4592-b630-b72fdb32a555)

**Comment by mosesdeeCVP** [comment]
No more Hard coded links in QA module TST
![No more Hard coded links in QA module TST.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/51337742-f30f-47e6-9842-d69e8aed0b6f)

**Comment by mosesdeeCVP** [comment]
No more Hard coded links in QA module BETA
![No more Hard coded links in QA module BETA.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5188954a-d3b9-4be8-870e-8d23711bebf5)
