### ISSUE TITLE
Bug: 403 Error When accessing Evaluate and Submit Functionality (Test In BETA and Test Env)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5108]
Issue: 403 Error when accessing Evaluate and Submit Functionality due to missing content. The content is currently available in dev and needs to be pushed to TST and Beta

1. Login to workspace
2. Navigate to the Evaluate section

Ref Notes:
Even after applying program in CDX, I receive a 403 error from https://api.epa.gov/easey/beta/content-mgmt/ecmps/workspace/evaluate-submit/ endpoint but can still choose a facility and evaluate

**Comment by vishnunavuluri** [comment]
Test post-deployment to TST and Beta
