### ISSUE TITLE
Bug: Fix tab styling for Configurations Tabs when checked out

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5110]
**Issue:**
When a user opens a Facility-Configuration, then the information is not formatted correctly in the tab. We need to fix the tab styling so the information is contained and readable

Note: The styling issue is seen only when a Configuration is checked out. It is fine otherwise

**Expected Styling:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3f48954b-2075-4016-985f-61712d01c2cd)

**Configuration Checked out:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/158dcf90-9a1f-4f20-9fa6-e1bacf495536)

## Testing 
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Tab styling for Configurations Tabs when checked out - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e56b8034-27aa-4fec-b209-6fd4c0b140b6)

![Tab styling for Configurations Tabs when checked out - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/854c9f79-3015-49ae-afa7-a2b0f0592a24)

**Comment by mosesdeeCVP** [comment]
Styling is fixed

**Comment by mosesdeeCVP** [comment]
![Tab styling for Configurations Tabs when checked out - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e3221b72-efb0-44e2-8cad-ae82e80c0b51)


![Tab styling for Configurations Tabs when checked out - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/29308dfc-2355-4190-9f52-32a3b2605abf)


![Tab styling for Configurations Tabs when checked out - 03.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0782a7ad-c53a-4a79-8747-a6bbac7f533c)
