### ISSUE TITLE
Add Mon Sys ID dropdown to App E Correlation Heat Input from Gas

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5113]
Currently, App E Correlation Heat Input from Gas doesn't have the Mon Sys ID field. Add the field similar to App E Correlation Heat Input from Oil. See below for reference:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/278a629b-db9c-4956-ae49-35c1a643824e)

**Comment by mosesdeeCVP** [comment]
![Sys ID In AppE Gas.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/33fc36a5-3d66-4fcd-9234-c9a8363d36be)

**Comment by mosesdeeCVP** [comment]
Field Added
