### ISSUE TITLE
Bug: MP MATS Method - Invalid validation for End Date

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5115]
**Issue:**
When a user wishes to create MATS Method data with an End Time of 0, then the system throws a validation that shouldn't be displayed

**Steps to recreate:**
1. Login to ECMPS
2. Access the MP module and select and check out a Configuration
3. Select  the 'Methods' option from the Sections dropdown
4. Click 'Create MATS' under 'Supplemental Methods' and add End Time as '0'
5. Add all other informatio and click 'Save'
The following error is returned even though 'End Date' is provided: [MATSMTH-4-C] - You have reported a Supplemental MATS Compliance Method End Date that is invalid.

Note: This bug likely comes from easey-monitor-plan-api in the file 'mats-method-checks.service.ts' on line ~55 in function matsMethod3And4Check where !matsMethod.endHour is used to check the endHour

**Comment by mosesdeeCVP** [comment]
![MATS Methods 0.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1663a715-0f32-4637-bcbf-b164a45847e3)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
