### ISSUE TITLE
Test Only: Evaluate throwing an Undefined Error in TST and Beta (TST after Deployment)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5117]
**Issue:**
When a user clicks on the Evaluate functionality from the left-hand menu, then the system throws an Undefined Error. This happens in TST and Beta but dev is working as expected

Test after the code has been deployed to TST and Beta post 12.4

**Comment by mosesdeeCVP** [comment]
Was able to Evaluate in TST and BETA with no Undefined Errors
