### ISSUE TITLE
Bug: Issue with Total Time for Cycle Time Summary Data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5123]
**Issue:**
The Total Time field for Cycle Time Summary Data throws a series of validations when a user enters time that is 3 or more digits. We need to add an error message (DTO check) to inform the user that the fields only accepts values from 0-99

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
bug resolved 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/70b90f99-9d7c-4788-99c5-682cbcad93a3)
