### ISSUE TITLE
Bug: Incorrect data saved for SPAN Records

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5124]
**Issue:**
Adding new Span record => Error message: "[SPAN-56-B] - You have reported an MPC Value for [Monitor Span], but an MPCValue is not appropriate for this ComponentTypeCode and SpanScaleCode. [SPAN-57-A] - You did not report an MECValue for [Monitor Span].  This value is required in a non-flow low-scale-span record." where the MPC value is required for component CO2.  **However, the changes were accepted after changing the Span Scale from Low to High.**

**Test Data:**
Create Span record: Component Type: CO2 concentration, Span Scale: Low, Span Method: Historical Data, MEC Value: leave blank, MPC Value: 12, MPF Value: leave blank, Span Value: 21, Full Scale Range: 21, Span Units of Measure: Percentage, Scale Transition Point: leave blank, Default High Range: leave blank, Flow Span Value: leave blank, Flow Full Scale Range: leave blank, Start Date - mm/dd/yyyy: 04/18/2023, Start Time: 13

**Comment by mosesdeeCVP** [comment]
SPAN-56-A
![SPAN-56-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b7318290-a78b-43e3-b376-55a0e77fd0d7)

SPAN-56-B
![SPAN-56-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b049c712-026b-40c0-b6ad-3eeaadb05b76)

SPAN-56-C
![SPAN-56-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/37f7056e-5fb3-4601-8b46-0f8d20384fae)

**Comment by mosesdeeCVP** [comment]
SPAN-57-A
![SPAN-57-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/47d5876c-201e-457f-af8d-945e8371b98e)

SPAN-57-B
![SPAN-57-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/03c4753a-c484-4734-9cea-ada5c10745c1)

SPAN-57-C
![SPAN-57-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2dd58e7b-afe3-485e-85c1-7c3e82ddcf97)

SPAN-57-D
![SPAN-57-D.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2b6b80b3-2d1e-4b8f-8806-53b8efde80db)

**Comment by mosesdeeCVP** [comment]
Checks work properly
