### ISSUE TITLE
Update display of MP Sections Dropdown

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5125]
The MP Sections dropdown has various options which currently are only partially displayed when the user makes a selection. Update this to make it wide enough to read the entire label

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/ef23f33b-5879-4a81-ba02-c8c397650b60)

**Reference Hi-fi's:**
https://xd.adobe.com/view/a78bc3a4-ac12-4586-9dfb-e2f452b51286-f2d8/

**Comment by mosesdeeCVP** [comment]
Sections Field Global
![Sections Field Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b8029c0a-009e-4885-88f3-ec48ec7665b3)

Sections Field Workspace
![Sections Field Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0be52a9c-13f2-4072-91d3-6e37dbcf1c3c)

**Comment by mosesdeeCVP** [comment]
UI updates completed
