### ISSUE TITLE
Export Test Data - Update Logic for Filtering on Reporting Period

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5128]
**Issue:**
Currently, for exporting the Test Summary Data records, the Reporting Period is filtering based on the Begin Date for the records. This login needs to be updated

Update the logic to filter the Test Data records when their End Date falls within the Reporting Period or filter based on the Year and Quarter that falls within the Reporting Period
For instance, if the user selection for the Reporting Period is 2023 Q1, then any records with an End Date and Time between Jan 1, 2023 thru March 31st, 2023 shall be displayed
OR 
Any records with Year and Quarter falling within the Reporting Period shall be displayed

**Comment by mosesdeeCVP** [comment]
The export reporting period filter uses the end date to filter which facilities to select
![Export by endDate logic.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6a43a404-523a-4f8d-879a-1c1f3d112164)
