### ISSUE TITLE
Feature: Single Select Prototype API for Hourly Apportioned Emissions Data in JSON

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#513]
## Feature Benefit
(What is this feature's benefit hypothesis? Proposed measurable benefit to the end-user or business)

## Scope
As a user, I want to access data through a UI, so that I may filter and sort the data based off different criteria.
As a user, I want to access data through an API, so that I may receive my data without going through a UI.

This prototype API serves two parts:
- Support #172 prototype UI by providing data for the UI
- Provide data to the end-user through a publicly accessible API

**Display only 5 years of data (2015-2019)**
**Display data for all US states - including Alaska, Hawaii, Puerto Rico, District of Columbia**

### Filter Criteria
- Date (custom date range, no hour range)
- State
- Facility (Filter by facility name AND/OR by ORIS code)
- Unit type
- Unit fuel type
- Control technologies
- Operating hours only (if selected, return only operating hours. If not selected, return all data), OP Time greater than 0

Filtering will use "AND" condition - find results that match all criteria, not any criteria
Filter criteria will be in a multi select for all options (not in scope for 2.3) 

Sorting by any criteria is out of scope for 2.3

### Data Elements
The prototype will include Hourly emissions (no aggregation at unit level)
Include all data elements currently in FTP hourly emissions data EXCEPT for FAC_ID and UNIT_ID

Results will be displayed in a preview in table format
Each data element will be a column
Table limited to 50 results in preview (Showing 50 of XXXX records) 
Will provide option to download data results

Query results will include:
`
STATE |
FACILITY_NAME |
ORISPL_CODE |
UNITID |
OP_DATE |
OP_HOUR |
OP_TIME |
GLOAD (MW) |
SLOAD (1000lb/hr) |
SO2_MASS (lbs) |
SO2_MASS_MEASURE_FLG |
SO2_RATE (lbs/mmBtu) |
SO2_RATE_MEASURE_FLG |
NOX_RATE (lbs/mmBtu) |
NOX_RATE_MEASURE_FLG |
NOX_MASS (lbs) |
NOX_MASS_MEASURE_FLG |
CO2_MASS (tons) |
CO2_MASS_MEASURE_FLG |
CO2_RATE (tons/mmBtu) |
CO2_RATE_MEASURE_FLG |
HEAT_INPUT (mmBtu) |
PRIMARY_FUEL_INFO |
SECONDARY_FUEL_INFO |
UNIT_TYPE_INFO |
SO2_CONTROL_INFO |
PART_CONTROL_INFO |
NOX_CONTROL_INFO |
HG_CONTROL_INFO
`

## Test Automation:
#624

**Comment by david-cvp** [comment]
1. Design API, contracts, entities - Meet to design the API (identify contracts, entities, and end points) - size:5
#529
2. Set up service repo - tasks: scaffold, set up controller services, and repo classes - size: 2
#527 
3. Convert schemas - tech team - see migrate MP data - size: 3 - Jason
#532 
4. Extract and load data in database (cloud.gov) -  tech team - size: 5 - Jason
#531 
5. Build contracts, entities Size: 3
#528 
6. Build repo, develop query logic - size: 5
#533

**Comment by david-cvp** [comment]
Next steps:

1. Validate date range
2. Validate state
3. Validate unit type
4. Validate unit fuel type
5. Validate control technologies
6. Validate facility
7. Validate ORIS code

**Comment by JorjaComer** [comment]
Split this feature to be only for the single select API option. Will create a new feature for the multiple select option (including validation updates) and will move the new feature to PI 3.

**Comment by JorjaComer** [comment]
See feature #639
