### ISSUE TITLE
Export QA Cert Event & TEE Data - Update Logic for Reporting Period

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5130]
**Issue:**
Currently, when exporting the QA Cert Event and TEE Data and filtering on the Reporting Period, there is no relationship between Reporting Period and any dates available for the specific module (Event Date etc.)

Update the logic to filter the QA Cert Event Data records when their Event Date/Time falls within the Reporting Period
For instance, if the user selection for the Reporting Period is 2023 Q1, then any records with an Event Date/Time between Jan 1, 2023 thru March 31st, 2023 shall be displayed

For TEE data filter on the Reporting Period

**Comment by subrataroyCVP** [comment]
## Found a Bug, UI making frequent calls without cancelling the previous call on the Export view reporting period dropdown changes.

## New Bug ticket created [#5135](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/gh/us-epa-camd/easey-ui/5135)

**Comment by subrataroyCVP** [comment]
## Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/488

**Comment by mosesdeeCVP** [comment]
TEE Year was set to 2022 and Quarter to 1. TEE is showing up properly as part of the Reporting Period of 2002/Q1

QA Cert Event Event Date is reporting properly as shown in screen shot

![Cert Event and TEE Reporting Period Logic.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/445e0e22-9537-49e0-b28f-3459b2092ea2)

**Comment by mosesdeeCVP** [comment]
Reporting Period for QA Cert Event and TEE is reporting properly.
