### ISSUE TITLE
UI: Test Data and TEE Data_Export Functionality - Add Year and Quarter columns

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5132]
**For Test Data:**
Add Year/Quarter before the Begin Date/Time column  (For both Global and Workspace)

Add the new column Year/Quarter before FuelCode

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1048

**Comment by mosesdeeCVP** [comment]
Year and Quarter Global
![Year and Quarter Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0cde2132-7bf1-4e0f-bb9d-a132eb4298cd)

Year and Quarter Workspace
![Year and Quarter Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4dd9d2d1-76b6-48fc-a41b-30ed29087f2a)

**Comment by mosesdeeCVP** [comment]
Year and Quarter added to Global and Workspace in Export
