### ISSUE TITLE
Bug: Test Summary Test Qualification Data with a valid endDate can't be imported

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5133]
**Issue:**
Test Summary - Test Qualification Data with a valid endDate can't be imported

**Steps to Reproduce:**
1. Navigate to and check out Dolet Hills Power Station (ORIS Code 51)
2. Import a record with Test Qualification Data that contains a valid endDate
3. You will receive an error stating "instance.testSummaryData[0].testQualificationData[0].endDate is not of a type(s) number,null"

**Comment by mosesdeeCVP** [comment]
![testQualificationData Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1f29f1e1-a2dc-44fc-b8f0-17701e017d3a)

**Comment by mosesdeeCVP** [comment]
Import with end date successful
