### ISSUE TITLE
Bug: Export Functionality - Combine the Year and Quarter Dropdowns to display Reporting Periods

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5135]
Update the UI for Export functionality to combine the Year and Quarter dropdown to a display similar to what you see in the screenshot below:

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/28d284fe-0ba1-47cf-b274-e3cf25e1ffdb)

This display is currently available for Evaluate and Submit

**Comment by MaeganWood64** [comment]
![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/0266098e-f628-40d7-952b-e1138c48046c)
