### ISSUE TITLE
Bug: Issue loading Configurations Tab in Global-view ECMPS (For MP & Emissions)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5137]
**Issue:**
When a user opens a Configuration tab in the Global-view of ECMPS for MP or Emissions, then the header section doesn't load and the spinner keeps going

**Steps to Recreate:**
1. Access MP Module or Emissions Module in ECMPS global-view
2. Select and open a Configuration
You will notice that the header section doesn't load and the spinner keeps going

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/01e40fcb-2c55-4288-9ae8-a65c306ed111)

**Comment by mosesdeeCVP** [comment]
Header section working as expected

**Comment by mosesdeeCVP** [comment]
MP Header Section
![MP Header Section.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/079f845e-58b6-4936-8a57-620fefa58124)

EM Header Section
![EM Header Section.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fe96bc8f-b029-45db-bb69-5a9fb13fa842)
