### ISSUE TITLE
Bug: Issue with End Date and Time validations when editing Systems

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5139]
**Issue:**
When editing a Systems record, if you enter End Time without End Time or End Time with out End Date, then the modal closed upon Save and close. When you edit/view the same record again, then you will see the 'Must Enter in both End Date and Time' validation

**Steps to Recreate:**
1. Login to ECMPS and select and checkout a Configuration
2. Select System from the Sections dropdown
3. Click Edit/View and add either the End Date or Time
4. Click Save and Close
View/Edit the same record and observe that you will see the validation at the top of the screen and the data is also not saved

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1061c27f-8b79-4f96-8f90-815262413bfd)

**Comment by mosesdeeCVP** [comment]
Bug fixed
