### ISSUE TITLE
Prototype Static Dataset for Hourly Apportioned Emissions Data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#514]
## Feature Benefit
(What is this feature's benefit hypothisis? Proposed measurable benefit to the end-user or business)

## Context
[Refer to MVP list for more info ](https://teams.microsoft.com/l/entity/0d820ecd-def2-4297-adad-78056cde7c78/_djb2_msteams_prefix_3687621406?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype%22%7D&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

If we do not have test data for certain states, an empty file will be generated

### Data Groupings
Hourly Emissions:
- All states and units by quarter (example: Hourly2020Q1)
- All emissions for a state by year (example: AlabamaHourly2020)

Facility Attributes:
- A single file of facility attributes data per year, including all facilities and units (including retired)

### Data Elements
Hourly Emissions:
The prototype will include Hourly emissions (no aggregation at unit level)
Include all data elements currently in FTP hourly emissions data EXCEPT for FAC_ID and UNIT_ID
`
STATE |
FACILITY_NAME |
ORISPL_CODE |
UNITID |
OP_DATE |
OP_HOUR |
OP_TIME |
GLOAD (MW) |
SLOAD (1000lb/hr) |
SO2_MASS (lbs) |
SO2_MASS_MEASURE_FLG |
SO2_RATE (lbs/mmBtu) |
SO2_RATE_MEASURE_FLG |
NOX_RATE (lbs/mmBtu) |
NOX_RATE_MEASURE_FLG |
NOX_MASS (lbs) |
NOX_MASS_MEASURE_FLG |
CO2_MASS (tons) |
CO2_MASS_MEASURE_FLG |
CO2_RATE (tons/mmBtu) |
CO2_RATE_MEASURE_FLG |
HEAT_INPUT (mmBtu)
`

Facility Attributes:
Includes all data elements in the AMPD Facility Attributes data set 
Data set should include data dictionaries provided by EPA
`
State |
Faciity Name |
Facility ID (ORISPL) |
Unit ID |
Associated Stacks |
Year |
Program(s) |
EPA Region |
NERC Region |
County |
County Code |
FIPS Code |
Source Category |
Facility Latitude |
Facility Longitude |
Owner |
Operator |
SO2 Phase |
NOx Phase |
Unit Type |
Fuel Type (Primary) |
Fuel Type (Secondary) |
SO2 Control(s) |
NOx Control(s) |
PM Control(s) |
Hg Control(s) |
Commercial Operation Date |
Operating Status |
Max Hourly HI Rate (MMBtu/hr)
`

**Comment by tlageman-epa** [comment]
We need to remove the Primary and Secondary Representative data elements from Facility Attributes.

**Comment by JorjaComer** [comment]
Static data sets are out of scope for the 1st CAMPD release. These will be accessed via the FTP site.

**Comment by JorjaComer** [comment]
No longer needed
