### ISSUE TITLE
Update Duplicate Checks when Importing a QA/Cert data

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5140]
Update the validations that check for Duplicate records when importing a QA/Cert

Notes:
When a user is importing a QA/Cert that is a duplicate, we will no longer prevent it from being imported by displaying the Duplicate Import Checks. In the future, we shall delete an existing record when a duplicate record is being imported.

The duplicate validations shall only be displayed/applicable when a user is manually creating a record

The scope of this ticket is for the below validations:
- APPE-4: Identification of Previously Reported Test or Test Number for Appendix E Test
- CYCLE-5: Identification of Previously Reported Test or Test Number for Cycle Time Test
- F2LCHK-14: Identification of Previously Reported Test or Test Number for Flow to Load Check
- F2LREF-2: Identification of Previously Reported Test or Test Number for Flow to Load Reference Data
- FFACC-3: Identification of Previously Reported Test or Number for Fuel Flowmeter Accuracy Test
- FFACCTT-4: Identification of Previously Reported Test or Number for Transmitter Transducer Test
- FF2LBAS-2: Identification of Previously Reported Test or Test Number for FuelFlow to Load Baseline Data
- FF2LTST-2: Identification of Previously Reported Test or Test Number for FuelFlow to Load Test
- LINEAR-4: Identification of Previously Reported Test or Test Number for Linearity Check
- ONOFF-23: Identification of Previously Reported Test or Test Number for Online Offline Calibration Test
- RATA-49: Identification of Previously Reported Test or Test Number for RATA
- SEVNDAY-5: Identification of Previously Reported Test or Test Number for 7-Day Calibration Test
- TEST-20	: Identification of Previously Reported Test or Test Number for Miscellaneous Test
- UNITDEF-6: Identification of Previously Reported Test or Test Number for Unit Default Test

NOTE FOR TESTER:
Of the checks on this list, only the LINEAR-4 check was implemented so only the LINEAR-4 check needs to be tested

**Comment by mosesdeeCVP** [comment]
When Importing the check does not fire as expected. When adding the data manually I do get the check as expected.
