### ISSUE TITLE
Bug: Rata-17-b and Rata-18-b checks Incorrect

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5141]
**Issue:**
Rata-17-b and Rata-18-b checks are following the logic of the error messages instead of the specifications logic (All checks should follow the specifications logic regardless of what the error message says)

**Comment by mosesdeeCVP** [comment]
RATA-17

RATA-17-A
![RATA-17-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0d6c26aa-3dcf-434c-a08f-ba23c1c35039)

RATA-17-B
![RATA-17-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6f832e1e-5131-40a2-9b1c-74914e53803c)

RATA-17-C
![RATA-17-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7545bb75-61b7-4fbe-a787-22be706d122a)

**Comment by mosesdeeCVP** [comment]
RATA-18

RATA-18-A
![RATA-18-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cd58a89b-4f19-4f9a-9770-5f9ead2a2de0)

RATA-18-B
![RATA-18-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f33c14b5-a116-472a-9eb3-a78d9751a17a)

**Comment by mosesdeeCVP** [comment]
Checks working properly
