### ISSUE TITLE
Bug: System displays a blank screen when creating a New Component

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5143]
**Issue:**
When a user wishes to create a new component under a MP system record, then a blank screen is displayed

**Steps to Recreate:**
1. Login to ECMPS and access the MP module
2. Select and checkout a Configuration (E C Gaston)
3. Select System from the Sections dropdown and click View/Edit to open an existing record
4. Click Add Component and in the Add Component modal, click Create New Component
5. Add the all needed information and click 'Create New Component'
The screen turns blank at this point 

Note: The Hg Converter Indicator dropdown doesn't present any options for selection
 Reference Screenshot:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/55f7785a-576a-4632-b01f-3342cd71017f)

## Testing 
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![Component Created.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0ed46a12-29ae-4764-bbe0-a6f0373f0132)

**Comment by mosesdeeCVP** [comment]
Component was able to be created without issue
