### ISSUE TITLE
Bug: RATA-120 logic is incorrect

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5144]
**Issue:**
Looks like RATA-120-C's logic is incorrect and it is preventing a user from a successful Import for Test Qualification

**Steps to Recreate:**
1. Login to ECMPS and access the Export functionality
2. Select and export QA & Certification file for the Configuration: Ames
3. Now navigate to Test Data module, access and checkout the same Configuration: Ames
4. Click Import and select Import from File. Add the file you previously imported which has Test Qualification data with correct dates.
5. Click Import: You will notice that the system displays RATA-120-C validation even though it is not applicable

**Comment by mosesdeeCVP** [comment]
RATA-120-A
![RATA-120-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/51795cad-0f46-4091-8148-0098e9594712)

RATA-120-B
![RATA-120-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f3125427-355e-4a7a-86ee-cb2c31f07a01)

RATA-120-C
![RATA-120-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a52baf9d-0315-4c2e-851f-5494f2d9694f)

**Comment by mosesdeeCVP** [comment]
Bug fixed
