### ISSUE TITLE
Update the Evaluation Status and Submission Status Display 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5145]
- Remove the 'Evaluation Status' and the 'Submission Status' fields from the frontend/UI for **QA Test Data (Data Table Column), QA Cert Data (Data Table Column), QA TEE Data, and Emissions Data**
**Note:** Keep the statuses as is for MP

The 'Evaluation Status' and the 'Submission Status' need to be displayed consistently across all modules in ECMPS. Update the Evaluation Functionality screens and the Submit Functionality screens to display the Description instead of the Codes. See below for the Descriptions:
**Note:** Jason shall change the 5 views to return the status code & description

**Evaluation Status:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/1699907d-e35b-47c2-a8fc-351d82d9b75e)

**Submission Status:**
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/35e19cfc-3e87-4de5-9808-da70c78bdbe3)

**Comment by mosesdeeCVP** [comment]
Eval MP
![Eval MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cfd674ca-93ab-420b-811a-5bc1a96b44e0)

No Eval Emissions
![No Eval Emissions.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4e0c4e3d-a707-41c4-92b3-a6b726ba78eb)

No Eval Cert Event
![No Eval Cert Event.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e5a0c6e6-6e1f-4069-82dc-ea5bf87bf1a8)

No Eval TEE
![No Eval TEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7a48b2d-5de3-4758-8551-815657cec4ad)

No Eval QA Cert Data
![No Eval QA Cert Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/757e6e59-6715-4625-a8ff-61da79b0ba8c)

**Comment by mosesdeeCVP** [comment]
Updates Completed
