### ISSUE TITLE
Emissions UI Dropdown Layout 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5148]
As an ECMPS user, I want to see the reporting period multi-select as the first option in the Emissions UI 

- [ ] The Reporting Period multi-select should be moved to before the location and view template drop downs

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/a58ded03-49d4-45dc-b789-40758be8ea4c)

**Comment by MaeganWood64** [comment]
![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/96188939-4fa2-4c44-8b5d-38be805a0556)
