### ISSUE TITLE
Bug: Mon SYS ID not presenting options for APP E HIF Gas and HIF Oil

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5149]
**Issue:**
When a user wishes to create App E Heat Input from Oil and Heat Input from Gas, the Monitoring System ID dropdown is not displaying any options to select from. It just says 'Select a value'

**Steps to Recreate:**
1. Login to ECMPS
2. Access the Test Data module and select and check out a Configuration (Cross, 1)
3. Select 'App E Correlation Test Summary' from the Test Type Group dropdown
4. Navigate to any record with data and click on Add or HIF Gas or Oil
You will notice that the Mon Sys ID dropdown doesn't present any options
Also when you try to create the data without Mon SYS ID, the system throws validations that it is a required field (Correct validations)

[Uploading... image.png]

**Comment by jordanfontainecvp** [comment]
This ticket is working as expected. Dropdowns work as expected when there is a monitoring system with OILV or OILM as the System Type Code
