### ISSUE TITLE
Remove "Revert Record" Button From Emissions UI 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5150]
Emissions UI should not have the "Revert Record" button in the logged in Emissions workspace UI

**Comment by MaeganWood64** [comment]
![image.png](https://images.zenhubusercontent.com/60e852f1b32c48306fa0dd84/c1c4a362-eec0-40f1-89c9-1b3d0320b48d)

Revert Record has been removed
