### ISSUE TITLE
Bug: Evaluation Statuses Displaying

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5151]
Evaluation status should not be displayed when selections made have no data or emissions file:
![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/ddc4f4d9-d5d1-4eb3-a323-132c9e79b562)

**Comment by mosesdeeCVP** [comment]
No eval status is displayed when selections made have no data or emissions file
![Evaluation Statuses Displaying 5151.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b60390bb-38ea-4673-8a6a-cd3d2f5dd042)
