### ISSUE TITLE
Minimize Database Connections for Emissions Bulk Load Import

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5153]
The emissions bulk load import is bulk loading each table per parent record creating thousands of connections/trips to the database. Refactor to prep data and push all records to an array per table and then bulk load each table once for all records in the file being imported

**Comment by JanellC** [comment]
Addressed in separate tickets in the emissions module backlog . Will close ticket once emissions module tickets are completed and tested
