### ISSUE TITLE
Bug: Expanding multiple configurations causing a blank screen

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5154]
**Issue:**
Expanding multiple configurations in MP, Test, etc and selecting a configuration from the first location causes a blank screen

Steps to reproduce:
Go to monitoring plans, QA, Cert and TEE, evaluations, or export.
Expand Barry and then expand Chickasaw
Selecting a configuration from Barry produces a blank screen

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
Bug resolved. Able to expand multiple configs
