### ISSUE TITLE
Bug: QA Certifications Event and TEE Module is not available

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5155]
**Issue:**
When a user is trying to access the QA Certifications Event and TEE Module in the dev env, it says the screen is not available
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/a15712e2-0667-45a8-8b03-1b7da1f4fa7d)

**Note:**
The URL needs to be updated for both the Global and the Workspace. Update qa-cert-event with /qa-qce-tee

**Comment by jwhitehead77** [comment]
Fixed to be available on /qa-qce-tee route

![image](https://user-images.githubusercontent.com/66504934/235576490-c05ee660-c8f0-435f-8860-8fcf5dd85e58.png)
