### ISSUE TITLE
Bug: Data not sorting in the Mon Sys ID and Component ID when new Systems and Components are added

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5156]
**Issue:**
The sort on Mon Sys ID and componentID dropdowns in Test Data are not working when a new System or component is added

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/8f27562b-e57b-4cfc-891f-d2f4ff5e1da4)

Resolution: The options in the Mon System ID should be sorted correctly at all times

**Comment by mosesdeeCVP** [comment]
![Mon System ID Alphanumeric Order.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/03f5297d-f7df-43a7-b658-aed7eda09f14)

**Comment by mosesdeeCVP** [comment]
Mon System ID Alphanumeric Order implemented
