### ISSUE TITLE
Bug: Emissions Module Identifiers

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5157]
The following identifiers are sporadically not populating in the emissions table when they are supposed to:

- [ ] components
- [ ] monitorFormulas
- [ ] monitoringSystems

**Comment by AmandaMNelson** [comment]
Currently working when there is only one location for the configuration; the bug is appearing when there are multiple locations for a configuration (like the first Barry option). Make sure that these are being populated in the export, and are not just null.
