### ISSUE TITLE
Bug: MP Import doesn't match Records correctly (SPAN)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5159]
**Issue:**
MP Import is not matching SPAN records correctly and needs to be addressed ASAP as this causes check engine evaluation errors.

**Steps to Recreate:**
1. Access the Export functionality in the Global-view for Gadsden, 1,2,CS0BAN/E C Gaston, 5, MS5A, MS5B
2. Select MP data and Export the files
3. Login to ECMPS and access the MP module
4. Select and checkout a Configuration that you used in Step 1
5. Click on 'Revert to Official Record' and once it is complete, click Import
6. Import the file you exported earlier and once it is successfully Imported, access the Evaluate functionality and Evaluate this MP
You will notice that the data isn't being matched up correctly hence causing Check Engine Evaluation errors

Notes:
**Gadsden                              1,2,CS0BAN**

https://ecmps-dev.app.cloud.gov/workspace/reports?reportCode=MP_EVAL&facilityId=7&monitorPlanId=MDC-613AD75BF31C4B9EA561E42E38A458DE

OFFICIAL BEFORE IMPORT
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d9fc9afe-894f-4928-bca9-a526a5167ff9)

AFTER IMPORT
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/3532016a-2c32-4827-b54c-cdde3a904221)

**E C Gaston                          5, MS5A, MS5B**

https://ecmps-dev.app.cloud.gov/workspace/reports?reportCode=MP_EVAL&facilityId=26&monitorPlanId=TWCORNEL5-2DC6306895774CE79178478330CD5921

OFFICIAL BEFORE IMPORT
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/818b4790-3b20-4a22-8541-140e2b0cec2e)

AFTER IMPORT
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/9beaca17-33c9-4608-932c-f1125da74c9e)

**Comment by vishnunavuluri** [comment]
Notes from Jason:
Here is the matching logic that should be followed…
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/d55113cc-2e9d-4d3e-af75-5d3ff27ef21f)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/436

**Comment by mosesdeeCVP** [comment]
MP Spans exported from global, imported and evaluated. All data stayed consistent throughout the process. Evaluation Passed.

**Comment by mosesdeeCVP** [comment]
Gadsden, CS0BAN MP Original
![Gadsden, CS0BAN MP Original.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/88e816cd-a3e6-44b6-b763-ca6b9d30e1a3)

Gadsden, CS0BAN MP After Import
![Gadsden, CS0BAN MP After Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e6741349-af4b-4945-a8ae-a1a797cd92e5)

Spans In Eval Report
![Spans In Eval Report.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4483935e-d305-4d15-ab5a-a874f8039cf2)

Span/MP Eval Pass
![Span Eval Pass.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6b778048-adc0-49b8-b93a-cbb5aeca6927)
