### ISSUE TITLE
Bug: Fix the Spinner for Export Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5161]
**Issue:**
When you make selections to Export and data is loading, the Spinner needs to be located properly. It needs to be in a pop-up similar to other functionality and should appear on the data being loaded. Currently, the sections are jumping and the spinner creates an empty space at the top of the screen

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/8acb4470-aff0-4da9-9bca-b6dbf0f36a9a)

**Steps to Recreate:**
1. Access Export functionality (Global or workspace)
2. Select and open a Configuration
3. Make selections as needed and click Export

**Comment by mosesdeeCVP** [comment]
Spinner Modal appears when user exports
