### ISSUE TITLE
Bug: Spinner is missing for MP Import Functionality

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5162]
**Issue:**
When a user Imports a data file, then the Spinner that is supposed to be displayed is missing

Steps to Recreate:
1. Login to ECMPs
2. Access MP module, select and checkout a Configuration
3. Click Import and look for the Spinner to be displayed. You will notice that it is missing

**Comment by mosesdeeCVP** [comment]
![MP Upload Spinner.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/32506932-8920-4876-a3a4-cc644daea8d9)

**Comment by mosesdeeCVP** [comment]
Spinner fixed
