### ISSUE TITLE
Bug: Contact Us under Help/Support throws an Undefined Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5163]
**Issue:**
When a user wishes to submit a query using the Contact Us section on the Help/Support page, it displays the Success Message and throws an Undefined Error. This need to be fixed so users are able to submit the requests successfully

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
Bug resolved. The system displays an success message without an error 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/66795cb9-114f-4bef-ade8-186ce8810fbd)
