### ISSUE TITLE
Refactor: Emissions Import Module Part 1

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5167]
Update the emissions parent records to build a summary list of injection records: 

- [ ] Summary Value Data
- [ ] Weekly Test Summary 
- [ ] Daily Emissions

**Comment by sdhawan16** [comment]
[5167 Sample Parameter For Testing.xlsx](https://github.com/US-EPA-CAMD/easey-ui/files/11410790/5167.Sample.Parameter.For.Testing.xlsx)

**Comment by fanwari1** [comment]
To test weekly test summary and summary value, you can export 
Facility: Dan E Karn
Config: 1
Reporting Period: 2018 Q3

Te test daily emissions and weekly test summary you can use 
Facility: Moss Landing Power Plant
Config: 4A
Reporting Period: 2022 Q4

As long as you can export from global and reimport to workspace, it should be working.
