### ISSUE TITLE
Refactor: Emissions Import Module Part 2

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5168]
Update the emissions parent records to build a summary list of injection records: 

- [ ] Long Term Fuel Flow
- [ ] Sorbent Trap
- [ ] NSPS4T Summary

**Comment by sdhawan16** [comment]
Since not every facility has these data types I've compiled a list of all oris codes and reporting periods with these data types to help with testing: 


[#5156 Sample Parameters for Testing.xlsx](https://github.com/US-EPA-CAMD/easey-ui/files/11410686/5156.Sample.Parameters.for.Testing.xlsx)
