### ISSUE TITLE
Update qa-cert to remove rpt period column and match based on end date 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#5173]
- Update qa-cert endpoint to remove reporting period and replace the connection with end date instead 

Make updates to the three endpoints listed below: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7fd13591-b8db-4471-b40e-2ae595e995d1)

## Testing 
Tester: @JanellC

**Comment by JanellC** [comment]
System working as expected
