### ISSUE TITLE
Update Submit Screen Buttons based on Permissions

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#5175]
Currently, Users can see a checkboxes even if they do not have permission to submit. If a user does not have permissions, then the checkbox should be changed to a view button so that the users can view the plan they are attempting to submit. 

**Acceptance Criteria** 
Given a user has accessed the Submit Page
and the user does not have submit permissions
When the user opens the dropdown
Then the checkbox is a "View" button to select the file for submission

Given a user has accessed the Submit Page
and the user does have submit permissions
When the user opens the dropdown
Then the checkbox is a "checkbox to select the file for submissions

**Comment by JanellC** [comment]
Submissions filtered based on permissions
