### ISSUE TITLE
Bug: QA Cert & TEE Data - Add informational text to the Import Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5177]
When a user selects Import from a File for QA Cert Data or TEE Data, then we don't have the informational text that prompts them to select a JSON file. Add the text: Upload QA JSOn File

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/60426d57-f6fc-4440-809b-5f7707490948)

**Comment by mosesdeeCVP** [comment]
Text has been added
![Upload QA Json File.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/087fd0b4-1bd2-438b-bef0-14c735c97e63)
