### ISSUE TITLE
Test Only: QA Test Data - Issues Importing from Historical

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5179]
**Issue:**
Import Historical RATA prompted sucessfully but data is not loaded - This is part of the larger issue where the tool returns a successful message yet no data is loaded. 

**Steps to Recreate:**
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?noAuthRedirect=1&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2FParadise%20Unit%20PCC1%2DImport%20RATA%20test%2Emp4&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing

**Comment by subrataroyCVP** [comment]
There are 2 issues actually.
- IMPORT error is not getting displayed.
- RATA-16 is implemented incorrectly. Need to Revisit RATA-16. New ticket created to work on this #5180

**Comment by mosesdeeCVP** [comment]
User is getting no errors importing RATA records.
