### ISSUE TITLE
Bug: RATA-16 Check is implemented Incorrectly

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5180]
**Issue:**
RATA-16 check is displayed when we import clean QA Test Data

**Steps to Recreate:**
1. Login to ECMPS
2. Export data for a select Configuration
3. Save the JSON file
4. Access the QA Test Data module and select and check out the same Configuration you assessed earlier
5. Click Import and import the file you exported earlier
You will notice that the system displays RATA-16 even when we just imported clean data

**Additional Notes from EPA Testers:** RATA-16-D is always returned if this is not a flow rata.  This is incorrect.  Please review the spec for RATA-16. (https://github.com/US-EPA-CAMD/easey-qa-certification-api/blob/55e640d57af70c21cea7dc2d8dea07d133db60d9/src/rata-summary-workspace/rata-summary-checks.service.ts#L171)

Testing Info:
Faciltiy (ORIS Code): 260
Configuration: 3A

**Comment by mosesdeeCVP** [comment]
RATA-16-A
![RATA-16-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/774d01cf-9a2e-4a65-bf66-88531f0680b1)

RATA-16-B
![RATA-16-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d68c6d67-7f0e-4278-95a6-b4235992331e)

RATA-16-C
![RATA-16-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9816b7f8-87a9-42d7-8a2b-7fd1e378aba9)

RATA-16-D
![RATA-16-D.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/56594c3c-383e-4340-a072-27511e2e10a9)

RATA-16-E
![RATA-16-E.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7d5c4dcb-1968-470d-8ece-7f3c9e16ae31)

**Comment by mosesdeeCVP** [comment]
Was able to Import Rata with no issues

**Comment by mosesdeeCVP** [comment]
Flow RATA

RATA-16-A FLOW
![RATA-16-A FLOW.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3e4fb2cc-3e63-4f09-83e2-1c4a0b6be57a)

RATA-16-B FLOW
![RATA-16-B FLOW.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/62c15d9b-087a-4eda-96a8-dced4a2dc7c0)

RATA-16-C FLOW
![RATA-16-C FLOW.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ea98beb2-f8ac-4698-a178-92859a2ddd08)
