### ISSUE TITLE
Emissions Regression Testing: Import and Data Types

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5181]
- [ ] Perform more granular testing of the emissions import module with focusing on more edge cases

**Comment by fanwari1** [comment]
[EmissionsImportsForAllDTOs.zip](https://github.com/US-EPA-CAMD/easey-ui/files/11489447/EmissionsImportsForAllDTOs.zip)

The attached file has facilities, configurations, and quarters that if all are imported, then all of the emissions data are hit.
