### ISSUE TITLE
Bug: View for Flow to Load Reference throwing an Error

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5184]
**Issue:**
In the Global-view, when a user accesses Flow to Load Reference and clicks on View for an available record, then the system throws an error

Steps to Reproduce:
1. In ECMPS, access Test Data, select and open a Configuration (Charles R Lowman, CS004)
2. Select Flow to Load Reference from the Test Type Group dropdown
3. Expand the Test Data and click on View for the Flow to Load Reference Data
You will see that the system throws a user security token error

Reference Screenshots:
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/39607365-ecdb-445d-ba35-cae02a753cd2) 
![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/0d6541bf-061a-46ac-97d9-93ab0027e73b)

**Comment by mosesdeeCVP** [comment]
Flow to Load Ref Global is working as expected
