### ISSUE TITLE
Bug: MP Module - Fix unnecessary API calls

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5185]
**Issue:**
MP Module is calling emission module APIs. These calls need to be removed/addressed

**Comment by mosesdeeCVP** [comment]
The calls have been removed from MP. The COUNTS that can be seen in Emissions are no longer seen in MP

**Comment by mosesdeeCVP** [comment]
Emission API Calls
![Emission API Calls .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/186c0023-8fcf-4aff-a082-5ddc3e34e8f3)

No Emission API Calls in MP
![No Emission API Calls in MP.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3a09dcdf-9eb6-4222-a46d-25ed2db63cc9)
