### ISSUE TITLE
Bug: Fix logic for Import-18 Check

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5190]
Issue:
The logic for Import-18 is not written correctly, hence it is displayed even when the data is correct and this preventing a user from Importing QA Data

https://ecmps.camdsupport.com/documents/ECMPS%20Import%20Check%20Specifications%202018Q2.pdf

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/511

**Comment by mosesdeeCVP** [comment]
All checks are working

**Comment by mosesdeeCVP** [comment]
IMPORT-18-A
![IMPORT-18-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ba7ff961-cc99-4c71-8b0f-802a5a23b91f)

**Comment by mosesdeeCVP** [comment]
IMPORT-18-B 1
![IMPORT-18-B 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3e0af16e-c804-487e-a798-0a0bd7304210)

IMPORT-18-B 2
![IMPORT-18-B 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ec20c46e-b04e-4f93-8c3b-6010eab5f2ea)

IMPORT-18-B 3
![IMPORT-18-B 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7fb35531-14ae-45ba-acdf-eda7715d8232)

IMPORT-18-B 4
![IMPORT-18-B 4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/53ed6e65-7a95-46fc-b14c-9d26656a77a6)

IMPORT-18-B 5
![IMPORT-18-B 5.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5d0899ac-a7b7-4d98-8261-4286ecee490e)

**Comment by mosesdeeCVP** [comment]
IMPORT-18-C
![IMPORT-18-C.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d36b1479-d19e-4c5f-97a3-9e539d16ad10)

**Comment by mosesdeeCVP** [comment]
IMPORT-18-D 1
![IMPORT-18-D 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/85ab7f4c-66f7-4a43-983b-d0ec1c65ea08)

IMPORT-18-D 2
![IMPORT-18-D 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/54b9ced9-fa6a-42c4-913d-a0bbe061a580)

IMPORT-18-D 3
![IMPORT-18-D 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/45161607-ea5e-4da3-88f2-ea2fb520f7eb)

IMPORT-18-D 4
![IMPORT-18-D 4.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44fa0e5f-f55e-4208-93c4-ec7855fe134c)

**Comment by mosesdeeCVP** [comment]
IMPORT-18-E
![IMPORT-18-E.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c4be90f7-f4cb-46aa-9e65-4312f5d66c73)

**Comment by mosesdeeCVP** [comment]
IMPORT-18-F
![IMPORT-18-F.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dadfcbb5-5e76-4af0-b0c1-3cb5698817b0)
