### ISSUE TITLE
Bug: End Date Validation Erorr

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5191]
User is getting Error msg: "Must enter in both End Date/Time" when trying to create:
 
- New Unit Fuel, Fuel Type: Coal, Indicator Code: Primary, Start Date: 5/9/2023
- New Unit Capacity, Max. Hourly HI Capacity: 2400, Start Date: 5/09/2023

- [ ] Need to look into why there is a validation for the end date being required

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/a1c3560a-966e-4e11-8923-3b5b7609ffa2)

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/50c6c700-c825-47d9-bfdd-eefc5b8428a9)

**Comment by mosesdeeCVP** [comment]
Bug is fixed
