### ISSUE TITLE
Bug: Rectangular Duct WAF record

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5193]
Issue: Not able to create Rectangular Duct WAF record. User receives error [Default-82-B] You reported a [undefined] of [undefined], which is outside the range of acceptable values for this date for [Rectangular Duct Waf

Steps to Recreate: Select Rectangular Duct WAF, Create Rectangular Duct WAF, WAF Method: Default, WAF Value: 0.9345, Number of Test Runs: 1, Number of Traverse Points WAF: 1, Number of Test Ports: 1, Number of Traverse Points Reference: 1, Duct Width: 100, Duct Depth: 30, WAF Determination Date: 5/2/2023, Start Date: 5/9/2023, Start Time: 17

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/ceae3760-5041-4593-8091-4e44417e8d9c)

**Comment by mosesdeeCVP** [comment]
Am able to create Duct Wafs in Dev, TEST and BETA environments.
