### ISSUE TITLE
Bug: MP Import Error - Hg convertor indicator required when it wasn't previously

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5195]
User Received the following error: locations.0.components.8.[COMPON-81-A] - You did not provide [hgConverterIndicator], which is required for [Component].

Steps to Recreate:
1. Login in to test.
2. Navigate to the MP module
3. Search for Boswell and open config #3
4. Click the Export data button
5. Check out the configuration
6. Click the Import Data button and import the MP file
7. The location component error still appears.

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/55f8d98d-258b-486a-a4b7-789106aaf010)

**Comment by mosesdeeCVP** [comment]
MP Imports successfully as expected
