### ISSUE TITLE
Remove RATA-101 Check

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5196]
- [x] Need to Remove RATA-101-B check to resolve RATA import issues

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/513

**Comment by mosesdeeCVP** [comment]
CEMValue and RATAReferenceValue accept 0
![CEMValue and RATAReferenceValue accept 0.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8b0dc11c-1f44-40cb-94f2-aa3f7fa01791)

CEMValue and RATAReferenceValue is greater than 0 and is not rounded to the nearest 1000 - Is FLOW
![CEMValue and RATAReferenceValue is greater than 0 and is not rounded to the nearest 1000 - Is FLOW.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7f7ae882-92f1-4b59-849c-8076df31324b)

**Comment by mosesdeeCVP** [comment]
Check has been removed
