### ISSUE TITLE
Document Testing Approach

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#52]
- [x] Discuss approach with team 
- [x] Testing approach is documented
- [x] Testing approach is reviewed 

Assignee:
- Yefim

**Comment by YefimAbramsonCVP** [comment]
Testing approach as it relates to the CI/CD is stored in the diagrams at: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTech%2FDevOps
