### ISSUE TITLE
Modify Emission API to Export Date Fields in ISO Format

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5200]
- [ ] Modify Emissions API to export all Date and DateTime (Timestamp) fields in ISO Format

 Date:  YYYY-MM-DD

DateTime:  YYYY-MM-DDTHH:MI:SS.000Z

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-emissions-api/pull/364

**Comment by mosesdeeCVP** [comment]
Emissions API to export Date and DateTime (Timestamp) fields have been updated
