### ISSUE TITLE
Modify Monitoring Plan API to Export Date Fields in ISO Format

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5201]
- [ ] Modify Monitoring Plan API to export all Date and DateTime (Timestamp) fields in ISO Format

 Date:  YYYY-MM-DD

DateTime:  YYYY-MM-DDTHH:MI:SS.000Z

**Comment by mosesdeeCVP** [comment]
Monitoring Plan API Date and DateTime (Timestamp) fields are in ISO Format
