### ISSUE TITLE
Modify QA /Cert API to Export Date Fields in ISO Format

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5202]
- [ ] Modify QA/Cert API to export all Date and DateTime (Timestamp) fields in ISO Format

 Date:  YYYY-MM-DD

DateTime:  YYYY-MM-DDTHH:MI:SS.000Z

**Comment by mosesdeeCVP** [comment]
![Modify QA -Cert API to Export Date Fields in ISO Format 5202.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c438af53-d580-4d38-8d58-de4aa3715c16)
