### ISSUE TITLE
Bug Emissions Import: No Error Message for File with No Data 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5204]
As an ECMPS user when importing from file or historical in the emissions workspace I want the system to throw a clear error on the UI that explains if there is no date for that reporting period 

Expected Behavior

Given a user has logged into the emissions workspace
When they try to import a file or from historical with no data
Then the system will throw an error and they will receive a UI error message stating that "There is no data in the emissions file for the reporting period you selected"

**Note: Backend only another ticket has been created to handle the UI side**

**Comment by fanwari1** [comment]
The following JSON without children data should give a message:
{
"orisCode": 3393,
"monitorPlanId": "NOTSET-779D28047AB74B7F8010406AD390498D",
"reportingPeriodId": 120,
"year": 2022,
"quarter": 4,
"submissionComment": null,
"lastUpdated": "2023-01-20T11:54:16.000Z",
"updatedStatusFlg": null,
"needsEvalFlag": null,
"chkSessionId": null,
"submissionId": 1566876,
"submissionAvailabilityCd": "UPDATED",
"dailyEmissionData": [],
"weeklyTestSummaryData": [],
"summaryValueData": [],
"dailyTestSummaryData": [],
"hourlyOperatingData": [],
"longTermFuelFlowData": [],
"sorbentTrapData": [],
"nsps4tSummaryData": []
}

The "There is no data in the emissions file for the reporting period you selected", is an error message for the UI and will a part of the other UI ticket.
