### ISSUE TITLE
Bug: MP - future date stamped in the "Last udpated by" field.

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5205]
Steps to Reproduce:
1. Login in to test.
2. Navigate to the MP module
3. Search for Comanche and open config #1
4. Click the Export data button
5. Check out the configuration
6. Check the configuration back in.

**Comment by mosesdeeCVP** [comment]
![Last updated by.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7db39b99-6019-45e3-910a-457c8feebb22)

**Comment by mosesdeeCVP** [comment]
Last updated by now reflects the current date
