### ISSUE TITLE
Bug: Emissions UI Unselected Reporting Period display

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5212]
Steps to Recreate: 
1. Login to the tst env
2. Navigate to Emissions on the left side menu
3. Use the search filter, type Comanche
4. Open the configuration # 1
5. Select the Reporting period of 2022 Q4
6. Click the Check Out button
7. The Reporting Period displays the 2022 Q4 period and an unselected Reporting Period (2023 Q1)

**Comment by mosesdeeCVP** [comment]
Bug has been fixed
