### ISSUE TITLE
EM Submission Access API: Create POST Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5217]
As the ECMPS system, I need to have a "POST" endpoint implemented in order to support the functions of the EM Submission Access screen.

**POST** /camd-services/admin/em-submission-access

**Request**
{
“monitorPlanId”: string,
“reportingPeriodId”: int,
“openDate”: date,
“closeDate”: date,
“submissionTypeCode”: string,
“resubExplanation”: string,
“emissionStatusCode”: string,
“submissionAvailabilityCode”: string
}

**Response**
{
“id”: int, (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer (rpt_period_id)
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string (see note below)
“lastWindow”: string, (skip for now)
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
“submissionStatus”: string, (skip for now)
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
“submissionDate”: datetime, (skip for now)
“submissionTypeCode”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd),
“representative”: string, (skip for now)
“analyst”: string, (skip for now)
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}

**Comment by mosesdeeCVP** [comment]
![EM Submission Access API- Create POST Endpoint.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fc5df790-b2cd-4365-9b82-d361f78c4298)

**Comment by mosesdeeCVP** [comment]
User is able to create an EM Submission Access via the API
