### ISSUE TITLE
EM Submission Access API: Create PUT Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5218]
As the ECMPS system, I need to have a "PUT" endpoint implemented in order to support the functions of the EM Submission Access screen.

**PUT** /camd-services/admin/em-submission-access /{id}

Extend: closeDate (access_end_date) is updated
Close: emissionStatus is set to received, Question for EPA: What do other columns default to (em_sub_type)?
Approve: emissionStatus (em_status_cd) is changed from pending to approved

**Request**
{
“closeDate”: date,
“submissionTypeCode”: string,
“resubExplanation”: string,
“emissionStatusCode”: string,
“submissionAvailabilityCode”: string
}

**Response**
Response
{
“id”: int, (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer (rpt_period_id)
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string 
**“lastWindow”: string, (skip for now)**
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
**“submissionStatus”: string, (skip for now)**
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
**“submissionDate”: datetime, (skip for now)**
“submissionTypeCode”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd),
**“representative”: string, (skip for now)**
**“analyst”: string, (skip for now)**
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}

**Comment by mosesdeeCVP** [comment]
![EM Submission Access API- Create PUT Endpoint.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/169c58d2-0c47-41f3-9901-c8de08a1dfac)

**Comment by mosesdeeCVP** [comment]
User is able to edit EM Submission Access API
