### ISSUE TITLE
EM Submission Access API: Create Get Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5219]
As the ECMPS system, I need to have a "GET" endpoint implemented in order to support the functions of the EM Submission Access screen.

**GET** /camd-services/admin/em-submission-access

**Filter Parameters**
• facilityId (orisCode)
• monitorPlanId
• year
• quarter
• status (Drop down in swagger: Closed, Open, Pending)

**Table**: camdecmpsaux.em_submission_access

**Response**
{
“id”: int, (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer (rpt_period_id)
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string (see notes below)
**“lastWindow”: string, (skip for now)**
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
**“submissionStatus”: string, (skip for now)**
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
**“submissionDate”: datetime, (skip for now)**
“submissionTypeCode”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd),
**“representative”: string, (skip for now)**
**“analyst”: string, (skip for now)**
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}

**Comment by sdhawan16** [comment]
There is data for 2012 Q1 and 2019 Q4 and facilityId=3

**Comment by mosesdeeCVP** [comment]
![Em Submission Access - GET.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/78c19081-fc8e-4fa4-83f8-b8ea6aef345f)

**Comment by mosesdeeCVP** [comment]
Em Submission Access GET API contains all of the appropriate fields. Filters work as expected.
