### ISSUE TITLE
UI: Create Open Submission Pop Out 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5220]
As an ECMPS admin, I want to see the submission pop out in the EM Submission module so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to EM submission screen
Then there will see an Open submission button

Given an ECMPS admin user navigates to the em submission screen
When they click on the Open  button
Then the open pop-out will open and will have all fields as shown in the wireframe below

- [ ] Open Date Field will default to the current date 
- [x] The closed Date field will populate to the last day of the current month
- [ ] The closed date field is editable and can be pushed out but the user cannot make the closed date earlier than the last day of the current month 

https://projects.invisionapp.com/freehand/document/1dwq6maiy?zoomToItems=Y2xkbTM5ejRuMDF3dDNiNnhpdWh6c2M0bw%3D%3D

**Comment by subrataroyCVP** [comment]
Pull request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1135
