### ISSUE TITLE
UI: Create Extend Submission Pop Out Layout

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5222]
As an ECMPS admin, I want to see the extend pop out in the EM Submission module so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to EM submission screen table
Then there will see an extend submission button

Given an ECMPS admin user navigates to the em submission screen table
When they click on the extend button
Then the open pop-out will open and will have all fields as shown in the wireframe below

https://xd.adobe.com/view/5f899592-74d7-4284-9fbf-c500c91134b8-0ada/screen/39517508-849b-4614-8219-f70ce6a9427f/

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1135
