### ISSUE TITLE
UI: Create Approve Submission Popout Layout

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5224]
As an ECMPS admin, I want to see the approve pop out in the EM Submission module so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to EM submission screen table
Then there will see an approve submission button

Given an ECMPS admin user navigates to the em submission screen table
When they click on the approve button
Then the open pop-out will open and will have all fields as shown in the wireframe below

https://xd.adobe.com/view/5f899592-74d7-4284-9fbf-c500c91134b8-0ada/screen/e4e4da15-6753-4124-b5e2-29662c21af85/

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1135
