### ISSUE TITLE
QA & Cert Wireframe Revisions (Due: 2/7)

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#523]
Notes - 1/25/20222 Product Design Meeting:

**Confirmed Requirements:**

- Global-View is not available when a user is logged in. Logged in users shall be able to review and update data in the Workspace only
- Navigation from one module (Monitoring Plans/QA/Emissions) to another shall retain Configurations (tabs) that are already open 

**Updates:**
- When the user adds a 'Test', the system automatically adds the Summary records underneath (auto-populated)
- When the user opens/expands the 'Test row', all the 'Summary' sections (High/Mid/Low) are expanded by default. Users can collapse the Summary rows individually or the entire Test row
- When there are no injection records under a Summary row, 'Add Record' is available (until all 3 injection records are added)
- Adding records (Test/Summary/Injection) is through Modals
- 'Edit Record' lets a user update an existing injection record. This opens in a modal

- Remove the 'Add Summary' button
- Remove the 'Save and Add Summary' button
- Remove the 'Save and Add Injection' button
- When a user clicks Add Record under a Summary row (High/Mid/Low), the 'Gas Level Code/Summary Type' field in the _Add Summary Data/Injection Record_ modal is pre-populated. Not a dropdown field

**Comment by AllisonFrancis** [comment]
https://xd.adobe.com/view/4cf46fe4-8974-482c-8fc6-f50fa02341f6-19a7/
