### ISSUE TITLE
UI: Implement Open Submission Record API Call

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5231]
As the ECMPS system, I need a call made to the EM submission API to open a submission access record

Given a user has selected only one record and clicks the open button
When the user enters the relevant information in the open pop-up and clicks save/close
Then the information will be saved on the backend and the record's information updated in the view table

- [ ] Implementing the open submission pop-out clones the selected record and creates a new record
- [ ] If Require Subsequent Quarter box is checked then records will be created for the subsequent quarters of the current calendar year 

https://projects.invisionapp.com/freehand/document/1dwq6maiy?zoomToItems=Y2xkbTM5ejRvMDF4bzNiNnhlNXphb3BpOQ%3D%3D

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1146
