### ISSUE TITLE
UI: Implement Approve Submission Access Record API Call 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5234]
As the ECMPS system, I need a call made to the EM submission API to approve a submission access records

Given a user has selected one or more records with the status of open (*tested with status pending; all records with status of open are already approved) and clicks the approve button
When the user enters the relevant information in the approve pop-up and clicks save/close
Then the information will be saved on the backend and the record(s) information updated in the view table

- [ ] Emissions status code is updated to "APPRVD" when a user uses the approved action

**Comment by sdhawan16** [comment]
Created pending records for testing - 
On UI filter by:
Facility Name/ID - Barry (3)
Configuration - Barry - 6A
Status - Pending Approval

Once the files are approved they will no longer be present when filtered by status pending approval and the em status code will change from PENDING to APPRVD
