### ISSUE TITLE
UI: Create Require Resubmission Pop Out Layout

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5239]
As an ECMPS admin, I want to see the Require Resubmission QA/Cert Data Pop Out in the QA/Cert Data Maintenance screen so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to the QA/Cert Data Maintenance screen table
Then there will see a  Require Resubmission button

Given an ECMPS admin user navigates to the QA/Cert Data Maintenance screen table
When they click on the  Require Resubmission button
Then the open pop-out will open and will have all fields as shown in the wireframe below

**Comment by mosesdeeCVP** [comment]
Wireframes:

https://xd.adobe.com/view/3bae4b9c-7093-4ec5-93dc-402ed7fa1797-6efd/screen/d1a2813d-9ac2-4eb2-ba07-26c16d8b8723/

**Comment by mosesdeeCVP** [comment]
![Require Resubmission popup.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/e133a990-cba4-489e-8e8a-d2cdbdd95c58)

**Comment by mosesdeeCVP** [comment]
Pop-out has been implemented.
