### ISSUE TITLE
UI: Create QA/Cert Maintenance View Pop Out Layout

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5241]
As an ECMPS admin, I want to see a view QA/Cert Data Pop Out in the QA/Cert Data Maintenance screen so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to the QA/Cert Data Maintenance screen table
Then there will see a view button

Given an ECMPS admin user navigates to the QA/Cert Data Maintenance screen table
When they click on the view button
Then the open pop-out will open and will have all fields as shown in the wireframe below

View Popup will have the following info depending on type selected:
**Static**
Facility ID/Name
MP Location(s)
Severity Level
**Test Summary**
Unit Stack
System/Component ID
Test Number
Test Type Code
Reporting Period
Begin Date/Time
End Date/Time
Submission Availability Description
Severity Description
**Cert Events**
Unit Stack
System/Component ID
Cert Event Code
Event Date/Time
Required Test Code
Conditional Date/Time
Last Completed Date/Time
Submission Availability Description
Severity Description
**Test Extension Exemption**
Unit Stack
System/Component ID
Fuel Code
Extension Exemption Code
Hours Used
Span Scale Code
Submission Availability Description
Severity Description

**Comment by mosesdeeCVP** [comment]
Create QA-Cert Maintenance View Pop Out Layout - Test Summary
![Create QA-Cert Maintenance View Pop Out Layout - Test Summary.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/5bff918c-6a60-427c-84e7-a3debfc429f4)

**Comment by mosesdeeCVP** [comment]
Create QA-Cert Maintenance View Pop Out Layout - Cert Events
![Create QA-Cert Maintenance View Pop Out Layout - Cert Events.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/68a52d53-7b03-4c5a-b85f-c1fc464a200f)

**Comment by mosesdeeCVP** [comment]
Create QA-Cert Maintenance View Pop Out Layout - Test Extension Exemption
![Create QA-Cert Maintenance View Pop Out Layout - Test Extension Exemption.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/418b98ad-bded-4ed7-aac0-50abeff48edb)

**Comment by mosesdeeCVP** [comment]
View Pop Out Layout has been implemented for the UI
