### ISSUE TITLE
QA/Cert Data Maintenance API: Create DELETE Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5242]
As the ECMPS system, I need to have all "DELETE" endpoints implemented in order to support the functions of the QA/Cert Data Maintenance screen.

DELETE _/camd-services/admin/qa-maintenance/cert-events/{id}_
Delete QA Cert Event records from camdecmps.qa_cert_event

DELETE _/camd-services/admin/qa-maintenance/test-summary/{id}_
Delete QA test records from camdecmps.test_summary, camdecmps.qa_supp_data, camdecmpswks.qa_supp_data

DELETE _/camd-services/admin/qa-maintenance/extension-exemptions/{id}_
Delete Test Extentions and Exemptions records from camdecmps.test_extention_exemption

The deletes will be done as raw queries so no entities need to be brought in

**Comment by mosesdeeCVP** [comment]
test-summary
![Data Maintenance API- Create DELETE Endpoint - test-summary.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a31d877d-f065-42c0-8a69-154c56402d52)

**Comment by mosesdeeCVP** [comment]
cert-events
![Data Maintenance API- Create DELETE Endpoint - cert-events.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4fd9920a-b70d-4a5d-b312-992137b07cf0)

**Comment by mosesdeeCVP** [comment]
extension-exemptions
![Data Maintenance API- Create DELETE Endpoint - extension-exemptions.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/639c7993-0eb5-4c25-960c-c48f0dd4ca68)

**Comment by mosesdeeCVP** [comment]
Delete functions work as expected
