### ISSUE TITLE
QA/Cert Data Maintenance API: Create PUT Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5243]
As the ECMPS system, I need to have a "PUT" endpoint implemented in order to support the functions of the QA/Cert Data Maintenance screen.

ENDPOINT: PUT /camd-services/admin/qa-maintenance

parameters:
certEventId: string
testExtensionExemptionId: string
testSumId: string

This PUT request updates the submission status of cert_event_data, test_extention_exemption, and qa_supp_data to be resubmitted. This is done by changing the column "submission_availability_cd" to "Required". cert_event_data, test_extention_exemption tables have this columns and needs to be updated in the global tables and qa_supp_data table have this columns and needs to be updated in the workspace and global tables.

**Comment by mosesdeeCVP** [comment]
PUT Endpoint testSumId
![PUT Endpoint testSumId.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c80200e7-01fe-4e59-aa37-686d2aea3cff)

PUT Endpoint testExtensionExemptionId
![PUT Endpoint testExtensionExemptionId.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a1890eca-874b-4c48-b32e-7300e7197e72)

PUT Endpoint certEventId
![PUT Endpoint certEventId.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3af6a6ac-d8b5-4cc6-9434-4975696f7257)

**Comment by mosesdeeCVP** [comment]
The PUT API is updating the submissionAvailabilityCode from 'Updated' to 'Required'.
