### ISSUE TITLE
UI: Implement Select Function in Table

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5245]
As an ECMPS user, I want to be able to select one or more records from the QA/Cert Data Maintenance view table and perform actions

Given a user has navigated to the  QA/Cert Data Maintenance view table
When a user selects one or more records in the table using the select buttons
Then they will be able to perform actions on the selected records

**Comment by mosesdeeCVP** [comment]
![Implement Select Function in Table 5245.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ca9b6331-866e-4c16-b18f-b2971cb73b0b)

**Comment by mosesdeeCVP** [comment]
User is able to select one or more records from the QA/Cert Data Maintenance
