### ISSUE TITLE
UI: Implement Apply Filter and Clear Buttons

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5246]
As an ECMPS user, I want to be able to apply all filter parameters I have selected to the QA/Cert Data Maintenance view table so I am only seeing applicable data and clear out those filters when I want to edit the parameters

Given a user has selected all desired filter parameters in the QA/Cert Data Maintenance screen
When the user clicks on the apply filter button
Then those selected filters will be applied to the QA/Cert Data Maintenance screen table and the user will view only data that falls into the selected parameters

Given a user has selected filter parameters in the QA/Cert Data Maintenance UI
When the user selects the clear button
Then all selected filter parameters will be reset and there will be no data in the table until filters are reapplied

Table Column Names ( The columns header will change based on the type selected in the filter drop-down, but the ones listed under Static will appear regardless of the type filter)
**Static**
Facility ID/Name
MP Location(s)
Severity Level
**Test Summary**
Unit Stack
System/Component ID
Test Number
Test Type Code
Reporting Period
Begin Date/Time
End Date/Time
Submission Availability Description
Severity Description
**Cert Events**
Unit Stack
System/Component ID
Cert Event Code
Event Date/Time
Required Test Code
Conditional Date/Time
Last Completed Date/Time
Submission Availability Description
Severity Description
**Test Extension Exemption**
Unit Stack
System/Component ID
Fuel Code
Extension Exemption Code
Hours Used
Span Scale Code
Submission Availability Description
Severity Description

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/81d3577e-768b-48fc-96ba-72f1c4bd871f)

**Comment by Qb10** [comment]
![image.png](https://images.zenhubusercontent.com/5f4562d2bbc8950ee86f5460/a2ad759b-d62f-42a7-9002-1df19d6b7415)

**Comment by mosesdeeCVP** [comment]
Implement Apply Filter and Clear Buttons - Test Summary
![Implement Apply Filter and Clear Buttons - Test Summary.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fe2d6845-6619-4ede-bfcc-914e66f039ac)

**Comment by mosesdeeCVP** [comment]
Implement Apply Filter and Clear Buttons - Cert Events
![Implement Apply Filter and Clear Buttons - Cert Events.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bb1e2d57-2293-4725-aac0-f250e49bf909)

**Comment by mosesdeeCVP** [comment]
Implement Apply Filter and Clear Buttons - Test Extension Exemption
![Implement Apply Filter and Clear Buttons - Test Extension Exemption.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6fccc5c6-8cca-44f7-b8ab-1f5b008d5b65)

**Comment by mosesdeeCVP** [comment]
Clear Function works as expected
