### ISSUE TITLE
Bug: Emission UI Historical Import Reporting Period Dropdown 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5249]
Issue:

The reporting period dropdown in the historical import pop-up is not displaying the current reporting period in the logged-in view

Expected Behavior:
Given a user is in the logged-in view of the ECMPS system
When the user navigates the Emissions module UI
Then the reporting period drop-down will be populated with the current quarter

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1122

**Comment by mosesdeeCVP** [comment]
![Emission UI Historical Import Reporting Period Dropdown .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b460483a-f0b7-43fd-9718-0c5e250832c6)

**Comment by mosesdeeCVP** [comment]
The current reporting period is displayed in the Emissiosn UI Historical Import
