### ISSUE TITLE
Bug: ECMPS Application UI Top Menu

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5250]
Issue:
When the browser window is smaller, the left side navigation menu moves to the top of the page. The top menu options seems to be an outdated though (Monitoring Plans, QA & Certifications, Emissions, Error Suppression, Workspace) and does not match the options on the left menu. Further, when I click a link, it doesn't navigate to that page, but displays a blank blue box under the menu.  A user can't access those pages when using a narrow window.
This happens in both global and workspace, in dev and test.

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/d899f482-13ce-4093-b3b1-e0dc28d23e66)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a72e45895241768fd33080306b09e20210d4199/ECMPS%20Application%20UI%20Top%20Menu%20-%20Global.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--857fff7e30be66d774007725b85826b15c9effe1/ECMPS%20Application%20UI%20Top%20Menu%20-%20Workspace.png)

**Comment by mosesdeeCVP** [comment]
User is now able to access all of the functionality from a small screen when the left side navigation menu moves to the top of the page.
