### ISSUE TITLE
Bug: QA-Cert Export API throwing 500 error

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5251]
Issue: 

The export API is throwing a 500 error 
`/qa-certification-mgmt/export?facilityId=3&stackPipeIds=CS0AAN`

Resolution: due to a type mismatch at the entity, it’s unable to map from entity to dto. update the correct entity type

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/519

**Comment by mosesdeeCVP** [comment]
Bug fixed
![QA-Cert Export API throwing 500 error 5251.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3d985cfe-e044-4033-a488-8c97d2632995)
