### ISSUE TITLE
Bug: Monitor Plan API - Change entity column type

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5253]
Monitor Plan API - Change entity column type to timestamp for addDate and updateDate

As apart of the scope for testing this ticket Make sure Export is working as expected for all datatypes.

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/452

**Comment by mosesdeeCVP** [comment]
All MP datatypes are available in the Export file
