### ISSUE TITLE
Bug: MP Relationships Data Missing

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5255]
Issue:

User observed that in the logged in  MP workspace view the Relationships Data is missing in the Workspace. There is data when viewing in the global. This has been confirmed on Barry and Greene County Facilities

**Comment by mosesdeeCVP** [comment]
Official record and Workspace do not match:

Official
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGJGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--753ffaa2286cd131a6c963c8d3b211bb0172a1b9/Official.png)

Workspace
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--93d50f7caaa7d33d361f7545e34ce2191337566e/Workspace.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFBUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--623ea9711624c9137e9483880db4445231ae1f9c/Relationships%20logged%20out.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFRUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--123747122613c6f7b4cb63eb19dd771aece61e01/Relationships%20logged%20in.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed. User is able to see Relationship data
