### ISSUE TITLE
Review and Identify Columns for EM Submission Access Endpoints

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5264]
As an ECMPS user, I need to have the columns for the EM Submission Access endpoints identified so we know what needs to be returned and validated.

Table: EM Submission Access in ECMPS AUX Schema

**Comment by sdhawan16** [comment]
### EM Submission Access

**GET** /camd-services/admin/em-submission-access 
Filter Parameters
•	facilityId (orisCode) 
•	monitorPlanId 
•	year
•	quarter
•	status (Drop down in swagger: Closed, Open, Pending)

Table: camdecmpsaux.em_submission_access

**Response**
{
“id”: int,  (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer  (rpt_period_id) 
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string (see notes below)
**“lastWindow”: string, (skip for now)**
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
**“submissionStatus”: string, (skip for now)**
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
**“submissionDate”: datetime,  (skip for now)**
“submissionTypeCode”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd), 
**“representative”: string, (skip for now)**
**“analyst”: string, (skip for now)**
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}



**Notes:**
1.)	Status column is determined by the em_status_cd and sub_availability_cd.
Open: em_status_cd is APPRVD and sub_availability_cd is REQUIRE or GRANTED
Pending: em_status_cd is PENDING
Closed: em_status_cd is RECVD
**Question for EPA:** What is the status if em_status_cd is APPRVD and sub_availability_cd is not REQUIRE or GRANTED?

2.)	**Question for EPA:** What are the lastWindow, submissionStatus, and submissionDate columns and where are they coming from? 
3.)	**Question for EPA:** Do we need severityLevel, representative, and analyst columns? Adding those will require extra tables to be pulled over and extra work. 

**POST** /camd-services/admin/em-submission-access

**Request** 
{
“monitorPlanId”: string, 
“reportingPeriodId”: int,
“openDate”: date,
“closeDate”: date,
“submissionTypeCode”: string,
“resubExplanation”: string,
“emissionStatusCode”: string,
“submissionAvailabilityCode”: string
}

**Response**
{
“id”: int,  (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer  (rpt_period_id) 
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string (see note below)
**“lastWindow”: string, (skip for now)**
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
**“submissionStatus”: string, (skip for now)**
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
**“submissionDate”: datetime,  (skip for now)**
“submissionTypeCode”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd),
**“representative”: string, (skip for now)**
**“analyst”: string, (skip for now)**
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}

**PUT** /camd-services/admin/em-submission-access /{id}

Extend: closeDate (access_end_date) is updated
Close: emissionStatus is set to received, **Question for EPA:** What do other columns default to (em_sub_type)?
Approve: emissionStatus (em_status_cd) is changed from pending to approved

**Request** 
{
“monitorPlanId”: string, 
“reportingPeriodId”: int,
“openDate”: date,
“closeDate”: date,
“submissionTypeCode”: string,
“resubExplanation”: string,
“emissionStatusCode”: string,
“submissionAvailabilityCode”: string
}

**Response**
{
“id”: int,  (em_sub_access_id)
“facilityId”: int, (camd.plant fac_id)
“orisCode”: int, (camd.plant oris_code)
“monitorPlanId”: string, (mon_plan_id)
“state”: string, (camd.plant state)
“locations”: string, (configuration for monitor plan)
“reportingPeriodId”: integer  (rpt_period_id) 
“reportingFrequencyCode”: string (camdecmps.monitor_plan_reporting_freq report_freq_cd)
“status”: string (see note below)
**“lastWindow”: string, (skip for now)**
“openDate”: date, (access_begin_date)
“closeDate”: date, (access_end_date)
“emissionStatusCode”: string, (em_status_cd)
“submissionAvailabilityCode”: string, (sub_availability_cd)
**“submissionStatus”: string, (skip for now)**
“lastSubmissionId”: int (camdecmps.emission_evaluation submission_id)
**“submissionDate”: datetime,  (skip for now)**
“submissionType”: string, (em_sub_type_cd)
“severityLevel”: string (camdecmpsmd.severity_code severity_cd_description - join on camdecmpsaux.check_session table severity_cd), 
**“representative”: string, (skip for now)**
**“analyst”: string, (skip for now)**
“userid”: string, (userid)
“addDate”: datetime, (add_date)
“updateDate”: datetime (update_date)
}

**Comment by JanellC** [comment]
Based on discussions during DSU on 5/30 Chris W will follow up with Dwayne on the questions listed in the ticket. Will follow up once additional information is recieved

**Comment by jwhitehead77** [comment]
@sdhawan16 the following fields do not need to be in the PUT & POST request payload
- “userid”: string,
- “addDate”: datetime,
- “updateDate”: datetime,
The user security token tells you who the user is and the addDate and updateDate should be set by the api using the currentDateTime
