### ISSUE TITLE
Filter Organization Roles by Role Status

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5274]
Filter the returning role set from cdx based on the roles status code. Only show roles that are currently active. 

In order to test this ticket need to
- create a new CDX account that is not sponsored. 
- when a user logs into ECMPS without a sponsored cdx account the user can ONLY view the ECMPS home page.

**Comment by JanellC** [comment]
Preparer sponser and submitter shall have permissions to see the workspace 
System admin shall see the system admin screens 
Anaylst shall be able to see the reports ( this has not been developed yet)

**Comment by JanellC** [comment]
Based on requirements left-nav functionality works as expected. Will log another ticket to ensure a non sponsered user can not access the work space using any links 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e802b061-589b-4358-94bf-75919005b2be)
