### ISSUE TITLE
Bug: Error Suppression GET Endpoint 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5280]
Issue:
Currently, the error suppression GET request has a field that is called "active". It should filter out between true/false. This does not work at all. 

- [x] Need to modify to make sure the user can filter "active" options

**Comment by mosesdeeCVP** [comment]
![Error Suppression GET Endpoint - active.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/cc26d606-8c2e-473e-9125-6fafe99b8834)

**Comment by mosesdeeCVP** [comment]
active filter works as expected
