### ISSUE TITLE
Bug: Evaluation Discrepancies -- instance.weeklyTestSummaryData.weeklySystemIntegrityData is not of a type(s) array

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5286]
## Context 

This issue will be addressed with Bug: Update MP, emissons, and qa-certification schema format discrepancies #5287. This is ready to test once 5287 is ready for testing

Users are experiencing issue in the ECMPS BETA ENV with the emissions module Schema. See Below: 

The following issue was raised by one of our BETA testing customers.
 
Error Message:
instance.weeklyTestSummaryData.weeklySystemIntegrityData is not of a type(s) array
 
According to the JSON Emissions schema downloaded from the ECMPS 2.0 website on 05/25/2023, this node should be of type "object".
 
The JSON Emissions file (generated by SV 7.3 BETA) which the customer evaluated with ECMPS 2.0 represents that data as an "object" type - not "array" type.
 
**However, ECMPS 2.0 returned an error message indicating the expected type is an "array" 

**As apart of the scope of this ticket change instance.weeklyTestSummaryData.weeklySystemIntegrity from an array to an object** 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f2fff2ce-dc65-46bd-a56d-3da67eb0e6a5)

**Comment by JanellC** [comment]
Jason W. needs time to look into this ticket before it can be esitmated or picked up

**Comment by jwhitehead77** [comment]
We originally had the WeeklySystemIntegrityData as an object since it only allows 1 record but was switched to an array for some reason. Just need to switch it back to an object in the schema and update the emissions api to expect an object vs an array.

**Comment by JanellC** [comment]
WeeklySystemIntegrityData  should be an array of objects.

**Comment by JanellC** [comment]
Per PD design meeting on 8/28, WeeklySystemIntegrityData  will be kept as an array with a limit of one. This ticket will be ready for testing once the schema changes have been implemented and tested on the prod team

**Comment by JanellC** [comment]
@jwhitehead77 @chrisgitsit 

https://github.com/US-EPA-CAMD/easey-content/blob/master/dev/ecmps/reporting-instructions/emissions.schema.json

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU9tIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9fef418033ab322698871509232f5f45b22bbf00/image.png)

WeeklySystemIntegrityData is of type array and has a min and max of 1
