### ISSUE TITLE
TestOnly: Bug: Update MP, emissons, and qa-certification schema format discrepancies

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5287]
## Context 
BETA users are experiencing the following issues with the QA and Emissions Schemas:
1. There are fields that are listed as a string or null that should be listed as a numeric or another value 
2. There are instances were values are listed as a string value but in another place the same value shows that the data should be numeric 

### **Issue 1:  There are fields that are listed as a string or null that should be listed as a numeric or another value** 

Below are all the data we have found in the JSON Schema Files which we *think* might be of the wrong “Type”:

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e00aabbb-9716-4a2b-9e66-7ada3ca437ad)

 
 	 	 	 

### **Issue 2: There are instances were values are listed as a string value but in another place the same value shows that the data should be numeric** 

For example, one place in JSON schema, unadjustedHourlyValue shows it is expected the data to be string:
 
 ![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/f897c16f-5060-4a68-890b-2df5689105ee)
 
But in another place, the same data shows the data should be number:
 
 ![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/97e28bc9-6924-4a21-b8f9-37dc71c8c991)
 
This is inconsistent.
 
We tried either way when doing our testing:
 
• If we used string data and uploaded the report to ECMPS beta web site, it passed the data validation, but when tried to click Import button, the web page crashed. 
• If we tried to use float data and uploaded the report to ECMPS beta web site, it did not even pass the data validation.

**Comment by JanellC** [comment]
Based on discussion durin 6/7 need to look into this issue to confirm if the fields need to be updated. Will follow back

**Comment by jwhitehead77** [comment]
All the emissions properties noted here are typed correctly in the JSON schema matching the XML schema. Those properties are ScientificNotationType which is defined as a string
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/7437f039-70d6-436d-bf86-2bb016531d3f)

The QA Protocol Gas Gas Type Code is also correctly typed as a string because it takes a comma delimited list of gas type codes & gas component codes

**Comment by JanellC** [comment]
@jwhitehead77 The scientificationnotation type should be a alphanumeric value

**Comment by JanellC** [comment]
Based on 9/5 refinement discussion, this is a test only ticket. The ticket can be tested once the schema changes have been implemented and tested on the prod team.

**Comment by JanellC** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanVuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e15c419abbd78ff01d1015ef99679ea763f7d53/image.png)

**Comment by JanellC** [comment]
Need to cofirm I am testing the ticket correct;ly and if items in the data table are right 

https://github.com/US-EPA-CAMD/easey-content/blob/master/dev/ecmps/reporting-instructions/emissions.schema.json

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb21uIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--484648dfcfd08a64810f9dbfc194c18cf708194a/image.png)

**Comment by JanellC** [comment]
There isn't anything to test with this ticket. Additional testing will be completed on the PROD team side, with import/export tickets
