### ISSUE TITLE
UI: EM Submission Access Component Setup/Design 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5288]
As the ECMPS system, I need all of the EM submission access components to be set up to ensure that UI development can proceed efficiently.

**Comment by AmandaMNelson** [comment]
Dropdowns for Facility Name/ID, Configurations, Reporting Period, and Status as well as Clear and Apply Filter(s) buttons function and match the wireframe (https://projects.invisionapp.com/freehand/document/1dwq6maiy?).
