### ISSUE TITLE
UI: QA/Cert Data Maintenance Component Setup/Design 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5289]
As the ECMPS system, I need all of the QA/Cert Data Maintenance components to be set up to ensure that UI development can proceed efficiently.

**Comment by mosesdeeCVP** [comment]
![QA-Cert Data Maintenance Component Setup-Design - 5289.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ee3c7483-c82f-49e5-940a-5a1c50ed6d50)

**Comment by mosesdeeCVP** [comment]
![QA-Cert Data Maintenance Component Setup-Design.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0380dd06-a5d3-47f5-bd4d-a61b8fb0111b)

**Comment by mosesdeeCVP** [comment]
QA/Cert Data Maintenance components have been set up in UI
