### ISSUE TITLE
Design Emissions API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#529]
- [x] Developers meet to design API, contracts, entities

**Comment by junie-stigdon** [comment]
Created a draft for the data contract for Emissions API. Will review with Jason tomorrow and submit final version once revised.

**Comment by junie-stigdon** [comment]
Updated return value formatting for date and delimited lists

**Comment by junie-stigdon** [comment]
Emissions API Design: https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/EASEY-IN%20API%20Design/API%20Design.xlsx?d=wb199e6f1786d4d4598a135893d2833ed&csf=1&web=1&e=0XkTOj

**Note:** This is currently in the same document as the Facilities and MP API Design. At the moment, the folder is located in EASEY-IN, but will most likely be moved to the Tech folder. At the moment, we'd like to keep all the API designs together for ease of access, but will later separate them to their proper locations.
