### ISSUE TITLE
SPIKE: QA Test Child Records 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5295]
Issue:
Under Test Data the user is unable to expand the child records
Go to Barry > CS0AAN > Test Data > RATA. Try and expand. System crashes
This occurs in both Global and Workspace

**Comment by Qb10** [comment]
QAExpandableRowsRender.js is not getting data from the selected row after it is expanded. this causing the app to crash. due to update to react 18 and update in the react data table library. 

need to refactor to similar format of SelectFacilitiesDataTable.js when it expands DataTableConfigurations
