### ISSUE TITLE
Document initial Visual Representation of CI/CD Pipeline 

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#53]
- [x] Meeting to discuss the high level workflow of CI/CD Pipeline 
- [x] Identify stages
- [x] Identify triggers
- [x] Identify Testing Types 
- [x] Document Exists 

Assignee:
- Srinivas

**Comment by srinivasaregeti** [comment]
Met with Jason and Yefim and discussed the DRAFT version of the proposed CI/CD pipeline. Proposed version of the pipeline uses GitHub Tags to trigger various stages of the pipeline. However based on the feedback received using the TAGs may complicate the pipeline especially promoting the application across multiple environments. 

I plan to update the pipeline to keep it simple and have Dev, Test, Stage and Prod as different stages of the pipeline and perform tests at different stages. 

Will work with Yefim on integrating his Testing framework documentation with the pipeline diagram.

**Comment by srinivasaregeti** [comment]
[https://app.zenhub.com/files/287570343/0fe8222a-00ee-432e-8b7e-a2caa5f7e7db/download](https://app.zenhub.com/files/287570343/0fe8222a-00ee-432e-8b7e-a2caa5f7e7db/download)
