### ISSUE TITLE
508 Bug: 'Here" Link Description

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5300]
https://ecmps-tst.app.cloud.gov

There's a link named 'here' in the what's new section, needs to be updated to something that's more descriptive

Additionally when a user selects the here link it doesn't render any content. Need to have some discussion on what the here link should point to. 

- [ ] Here Link Description:

In the What’s New box, go ahead and change the sentence and make the hyperlink the “CDX Start Guide” text.

From: To view a list of functionality and how to get started go here.
To: View the CDX Start Guide.

**Comment by acollad1** [comment]
Chris to send us a description to update in content API

**Comment by subrataroyCVP** [comment]
@acollad1  As per [#5569](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5569), the here link already updated for all the environments.

**Comment by aprematta** [comment]
Testing complete, link is now unique
