### ISSUE TITLE
508 Bug: Focus Issue MP

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5303]
https://ecmps-tst.app.cloud.gov/monitoring-plans
Focus is not returned to the view link when the modal is closed, for example on Rectangular, Defaults, Formula , select view, then close the modal

Note: Systems and Methods is not experiencing this isssue

- [ ] Check the data table assert file

**Comment by aprematta** [comment]
Testing complete, focus is now being returned to the correct view link
