### ISSUE TITLE
508 Issue: MP Configurations Page

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5305]
https://ecmps-tst.app.cloud.gov/workspace/monitoring-plans

On the configurations page, there looks to be an extra empty H4 (h4 class="margin-top-5 text-bold mobile:font-body-xl mobile:text-bold">/h4)

**Comment by subrataroyCVP** [comment]
Pull request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1127

**Comment by subrataroyCVP** [comment]
**Update Description:**

go to https://ecmps-dev.app.cloud.gov/monitoring-plans and open the tab for Barry 1, 2, CS0AAN, you'll find it under Supplemental Methods and right above `<p>No data currently present.</p>` in the html

![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/ea273be0-cb88-4348-b58b-e05bf8d3e6cc)

**Comment by aprematta** [comment]
Testing Complete, h4 has been removed
