### ISSUE TITLE
508 Bug: Export Page

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5310]
https://ecmps-tst.app.cloud.gov/workspace/export

- Select all rows not unique.... add test summary and qa certification events to the aria labels
- Aria labels do not seems to relate to te fields that are on screen, for example 'aria-label="select row for Test Number EPA-3B010323454391EA1053F91178DE1528"'

**Comment by aprematta** [comment]
Does not look like any change in dev

**Comment by aprematta** [comment]
Testing complete, labels are now unique and accurate
