### ISSUE TITLE
Server-Side Request Forgery in Request

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5316]
## Context 

Moderate Dependabot Issue located in easey-campd-ui and easey-ecmps-ui. **Note: No patched version is available** 

CAMPD
https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot/43'

ECMPS:
https://github.com/US-EPA-CAMD/easey-ecmps-ui/security/dependabot/36

CAMPD 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4eccdba9-64df-4bde-b4ec-bc00046578e8)

ECMPS
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7d24b29e-be8b-433e-91af-13990fedb2f5)

**Comment by jwhitehead77** [comment]
no fix as we do not allow http so there would be no cross-protocol redirect
