### ISSUE TITLE
Refactor CAMPD Time Period unit tests 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5322]
## Context 

Update the following unit tests for CAMPD: 

./src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.test.js
./src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.test.js
./src/components/filterCriteria/timePeriod/TimePeriodFullDate/TimePeriodFullDate.test.js

**Comment by bchofor** [comment]
I have tested the items listed on the this and they have all passed.

**Comment by hamezene** [comment]
@jwhitehead77  Please peer review and move to Ready for Testing

**Comment by shahbazkhan1999** [comment]
All the test cases have already been passed

**Comment by hamezene** [comment]
@tlageman-epa this has been merged to Dev, Please verify
