### ISSUE TITLE
Refactor CAMPD unit test 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5325]
## Context 

./src/components/Layout/Layout.test.js
./src/components/Markdown/Markdown.test.js
./src/components/MultiSelectCombobox/MultiSelectCombobox.test.js
./src/components/NotFound/NotFound.test.js

**Comment by JanellC** [comment]
CAMPD is above 70% coverage. Need to revist if the remainder of CAMPD unit test tickets are needed

**Comment by bchofor** [comment]
I performed a test on the items listed on this ticket and they all passed.

**Comment by hamezene** [comment]
@jwhitehead77 Please peer review and move to Ready for Testing

**Comment by shahbazkhan1999** [comment]
All the test cases have already been passed

**Comment by hamezene** [comment]
@tlageman-epa this has been merged to Dev, Please verify
