### ISSUE TITLE
Develop query logic

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#533]
- [x] Build repo and develop query logic for Emissions API

**Comment by junie-stigdon** [comment]
- Merged "feature/564-emissions-map-and-response-headers" into "feature/533-query-logic."

**Comment by sdhawan16** [comment]
- Added repository with query logic
- Modified the service and module files so it is importing the repository and changed the files as needed
- Modified controller to add request parameter

Will test the repository once the data is pulled over and fix any errors before creating a PR.

**Comment by junie-stigdon** [comment]
Data has been migrated to cloud.gov. Fixed a few bugs with the query logic. Will continue testing and add unit tests.

**Comment by sdhawan16** [comment]
- Fixed bugs with filtering by adding some filter logic to the service
- Changed date to mm/dd/yyyy format
- Added Unit tests 
- Created Pull Request

**Comment by junie-stigdon** [comment]
Ready to Test: https://easey-dev.app.cloud.gov/api/emissions-mgmt/swagger/

**Note:** Testing is best done with Postman. Swagger doc tends to timeout.
