### ISSUE TITLE
Refactor CAMPD Unit tests 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5330]
## Context 

Update unit tests for the following files: 

./src/utils/constants/filterTagsDict.test.js
./src/utils/ensure-508/rdt-table.test.js
./src/utils/hooks/useFocusTrapWithRef.test.js
./src/utils/selectors/filterLogic.test.js
./src/utils/selectors/timePeriodQuery.test.js

**Comment by bchofor** [comment]
I have tested the items listed on the this and they have all passed.

**Comment by hamezene** [comment]
@jwhitehead77 Please peer review and move to Ready for Testing

**Comment by shahbazkhan1999** [comment]
All the test cases have already been passed

**Comment by hamezene** [comment]
@tlageman-epa this has been merged to Dev, Please verify

**Comment by tlageman-epa** [comment]
There is nothing that I personally would check with this. not sure if @maheese has anything. if not, i think these refactoring tickets are good to go
