### ISSUE TITLE
Bug: Error Suppression UI Clone Record

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5331]
Issue:
User filtered by using Check Type: Air Emission Testing, -> Check Number: 1 -> Check Result A and tried to clone one of the records but the facility dropdown didn't get prepopulated and the Test Number dropdown didn't get populated on the add screen

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1133
