### ISSUE TITLE
Limit open Facility tabs within page width

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#534]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to open a Facility tab, so that I can view the Facility's MP data.

## Acceptance Criteria
Given a user opens a Facility tab
When the Facility name is too long to fit in the tab
Then the system will provide ellipses to the end of the Facility name
And will make the full name available via hover. 

Given the maximum open tab limit (calculated based on screen size) for Facilities has been reached
When the user attempts to open a new tab
Then the system will display the message, "Please close one of the open Facility tabs, in order to open a new tab."

Give the screen accommodates multiple open tabs
When the user enlarges the screen
Then the system dynamically provides more room to open tabs calculated based on screen size.
And when the user makes the screen smaller
Then the system dynamically provides less room to open tabs.

NOTE: Repurposed this ticket to accommodate change in functionality.  The original ticket for Monitoring Plan tab overflow navigation has been moved to #878.

## Testing
Test Case: [TC98](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/275619)
Tester: @mosesdeeCVP 

### Issue Requester:
Requester: 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by cvp-alexrobinson** [comment]
### Tab Overflow UI Example

https://images.zenhubusercontent.com/287570343/3543e7ed-ffcc-4d45-80fe-ee43cade1aa5/tab_overflow_navigation.mov

@karenhwwoo @JorjaComer @MoAdeyoju @addisgmichael @jwhitehead77

**Comment by karenhwwoo** [comment]
To be discussed on 3/1.

**Comment by david-cvp** [comment]
Will discuss further on Monday 3/8

May change requirements to instead limit to a certain number of tabs open at a given time OR limit to container width

**Comment by mosesdeeCVP** [comment]
![534 Limit open Facility tabs within page width 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/71673212-8484-4eb9-95f9-786c3620165d)

**Comment by mosesdeeCVP** [comment]
![534 Limit open Facility tabs within page width 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8f51e6c0-cf0f-4215-ba2b-57bd5324a2cd)

**Comment by mosesdeeCVP** [comment]
Product Owner has approved the story – Ticket closed.
