### ISSUE TITLE
API: Update POST and PUT EM Submission Endpoints 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5388]
Remove the submission type code from the POST and PUT payloads for EM Submissions Endpoints 
Default submission type code to RQRESUB when creating a record

**Comment by mosesdeeCVP** [comment]
POST EM Submission Endpoints
![Update POST EM Submission Endpoints 5388.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/998507f8-2f25-4afd-ba23-b0c23ed3199f)

**Comment by mosesdeeCVP** [comment]
PUT EM Submission Endpoints
![Update PUT EM Submission Endpoints 5388.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/328639f9-2d00-4696-9d26-d90ead241387)

**Comment by mosesdeeCVP** [comment]
submission type code has been POST and PUT. 
Default submission type code is RQRESUB when creating a record
