### ISSUE TITLE
Discuss Site to Site Connection Plan

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#54]
- [x]  Reach out to ODSTA to determine who needs to be invited to meeting
- [x] Meet to discuss options and possibilities for site to site connection plan 
- [x] Document options
- [x] Review with team 

Assignees:
@faqir-cvp 
@maheese
@jwhitehead77

**Comment by faqir-cvp** [comment]
8/25 - attended cloud.gov office hrs, they said they don't support site to site (cloud.gov to epa ncc data center) vpn or direct connect, therefore we have to use endpoint to endpoint integration via https. this will require meeting with epa and update to our design and will require more VMs that sit on the EPA side for exporting and importing data via our ETL process(es)

**Comment by MoAdeyoju** [comment]
8/27 - update from Faqir

1. Met with jason and mike and mo to discuss our site to site connectivity options (cloud.gov <-> ncc datacenter)
2. Working on 2 options and diagrams for review with other EPA teams next week

**Comment by davidkwartler** [comment]
Diagrams for two options to proceed:

[Option 1
](https://usepa.sharepoint.com/:u:/r/sites/CAMDCVPTeam/Shared%20Documents/Tech/Tech/EPA%20CAMD%20site%20to%20site%20option%201-v1.0.drawio?csf=1&web=1&e=YUzYeb)
[Option 2](https://usepa.sharepoint.com/:u:/r/sites/CAMDCVPTeam/Shared%20Documents/Tech/Tech/EPA%20CAMD%20site%20to%20site%20option%202-v1.0.drawio?csf=1&web=1&e=38VZBa)

Next steps: #120
