### ISSUE TITLE
Modify MP Export to support Reported Values Only

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5400]
## Context 

 Remove all the additional properties from the exports so that the exported data json exactly matches what would be imported 

Refer to the Emissions export for how to handle this

- [x] Test that the default behavior is all fields are returned and when that parameter is set to True only reported values are return

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Updated have been made. There are a few fields that still need to be updated. These will be handled in another ticket [#5690](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5690)
