### ISSUE TITLE
Modify Emissions Export to support Reported Values Only

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5403]
## Context 

remove all the additional properties from the exports so that the exported data json exactly matches what would be imported 

### For testing: 
go to postman and make a call to the emissions export endpoint 
set reported values flag to true and the exported file should make the import schema

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by JanellC** [comment]
Functionality is not working as expected. Bug: DailyFuelData, WeeklySystemIntegrityData, DailyBackstopData export file not consistent with import file #5620 has been logged to track changes
