### ISSUE TITLE
Create Daily Backstop Emissions View 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5406]
##  Context

Create a new view definition in the database for daily backstop data 

This can not be completed until import/export is done for Daily Backstop Emissions 

When you go to the Emissions module, select Reporting Periods and Locations, you then select a "View Template".  This ticket would be for creating that View Template for Daily Backstop Data.

**Comment by JanellC** [comment]
Note: @JanellC follow up with @billmiller13 on getting additional infromation on this ticket.

**Comment by jwhitehead77** [comment]
Daily Backstop view has been added and can be tested in the official view in ECMPS dev using
Barry 1,2,CS0AAN
2023 Q1-Q2
2022 Q1-Q4
Export these periods and import them into the workspace to then test the workspace view as well as the export/import process.

**Comment by JanellC** [comment]
System works as expected. Exported data from global, imported it into the system
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUFoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--927edbf448e65728199185035fde4052221bdeb6/image.png)

**Comment by JanellC** [comment]
Need 5582 to resolve the issue
