### ISSUE TITLE
UI: Implement Require Resubmission API Call

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5407]
As the ECMPS system, I need a call made to the QA/Cert Data Maintenance API to require resubmission of a record

Given a user has selected one or more records and clicks the require resubmission button
When the user enters the relevant information in the extend pop-up and clicks save/close
Then the information will be saved on the backend and the record(s) information updated in the view table

**Comment by mosesdeeCVP** [comment]
Implement Require Resubmission API Call 5407 - Test Summary
![Implement Require Resubmission API Call 5407.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ebcc780a-47c9-4a27-aac8-6ae311b55d54)

**Comment by mosesdeeCVP** [comment]
Resubmission functionality has been implemented in the UI

**Comment by mosesdeeCVP** [comment]
Implement Require Resubmission API Call 5407 - Cert Event
![Implement Require Resubmission API Call 5407 - Cert Event.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44a9214c-9c8e-439e-82ec-21b0c55a3e00)

**Comment by mosesdeeCVP** [comment]
Implement Require Resubmission API Call 5407 - Test Extension Exemption
![Implement Require Resubmission API Call 5407 - Test Extension Exemption.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2f859df4-71d2-4475-b678-8f14ba6b33f5)
