### ISSUE TITLE
UI: Implement Delete API Call

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5408]
As the ECMPS system, I need a call made to the QA/Cert Data Maintenance API to delete a record

Given a user has selected one or more records and clicks the delete button
When the user enters the relevant information in the extend pop-up and clicks save/close
Then the information will be saved on the backend and the record(s) information updated in the view table

**Comment by AmandaMNelson** [comment]
Confirmed that records can be successfully deleted from UI.
