### ISSUE TITLE
Story: Implement active/inactive filter logic for configurations, locations, and methods

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#541]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to view active and inactive Monitoring Plans, so that I can view all MPs assigned to facility per [the wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/).

Split from #491

## Acceptance Criteria
Given a user selects a monitoring plan configuration
When options are displayed
Then options are available based off the logic below with active only as default 

If an active configuration is selected, then the system will display only active locations, and only active monitoring methods.

If an inactive configuration is selected, then the system will display both active and retired locations, and both active and inactive monitoring methods.

Please see SQL for Active/Inactive MP Logic: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/ActiveInactive%20MP%20Logic.msg

The logic in in the following stored procedure in the ECMPS Client Database. 
•	ECMPS.[dbo].[UPDATE_MON_PLAN_CONFIGURATION]

## Testing
Tester: @mosesdeeCVP 
Test Case: [TC81](https://cvpcorp.testquality.com/project/11428/plan/19813/test/273498)

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by JorjaComer** [comment]
Will need updated wireframes for active/inactive toggle

**Comment by mosesdeeCVP** [comment]
Created a Test Case: 
[TC81](https://cvpcorp.testquality.com/project/11428/plan/19813/test/273498) 541 Implement active/inactive filter logic for configurations, locations, and methods

**Comment by mosesdeeCVP** [comment]
![541 Story Implement active - inactive filter logic for configurations, locations, and methods 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9b02e22b-8ddc-45f0-8b83-2aeb4fbb2566)

**Comment by mosesdeeCVP** [comment]
![541 Story Implement active - inactive filter logic for configurations, locations, and methods 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9db72a6a-dfe6-4a2d-b8d8-74a1aa0221e5)

**Comment by mosesdeeCVP** [comment]
![541 Story Implement active - inactive filter logic for configurations, locations, and methods 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7573e184-4dcd-4666-9d24-4a91c6f32293)

**Comment by mosesdeeCVP** [comment]
https://cvpcorp.testquality.com defect [D11](https://cvpcorp.testquality.com/project/11428/result/2261170/defect/7510). Do not remove or edit.

**Comment by mosesdeeCVP** [comment]
Defect discovered:

In Chickasaw (Oris 5) among other the Configurations, Locations, Sections and Show Inactive fields are not visible. This may be due to it having no Inactive configurations at all, so the UI is not recognizing it. 

![Chickasaw bug Screenshot 2021-02-16 113443.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/4117efd4-ff93-4522-afce-f81ae2b817e4)

**Comment by mosesdeeCVP** [comment]
The team reached a consensus that the Acceptance Criteria was met as was written, thus the ticket was closed. Bug ticket [805](https://app.zenhub.com/workspaces/pi-3-planning-board-5f96fc2121b1e50016c7acce/issues/us-epa-camd/easey-ui/805) will have its own User Story in order to enhance the functionality further.
