### ISSUE TITLE
@nestjs/core vulnerable to Information Exposure via StreamableFile pipe

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5412]
## Context 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/780228dd-5de3-4589-b804-f66113903ae3)

Moderate issue in the the following repos: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ab3cbb2a-c6e6-456d-aa53-11ec8d9ea222)

**Comment by JanellC** [comment]
Will hold off on this because it will require upgrading to nest js 9

**Comment by annalbrecht** [comment]
This has been resolved.
