### ISSUE TITLE
Bug: facilityId filter in the EM Submission Access GET endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5416]
Issue:

The validation on the EM Submission Access GET Endpoing  is validating against the fac_id which is the primary key and not the orisCode. So it returns back a false validation error when a valid orisCode is passed in. 

- [x] Need to swap out that validation for orisCode and rename the parameter on the API side from facilityId to orisCode 
- [x] Implement Facility ID and Configuration as required fields that need to be selected in order to apply filters to EM Submission View Table

**Comment by mosesdeeCVP** [comment]
![facilityId filter in the EM Submission Access GET endpoint 5416.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/715dea82-b523-4e3a-9a42-4156ee8f25a6)

**Comment by mosesdeeCVP** [comment]
Facility ID and Configuration is implemented as required fields.
