### ISSUE TITLE
Bug: Update Inactvity Timer styling 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5424]
## Context 

The inactvity  timer countdown component does not have any styling. Need to update the timer 
## Steps to Reproduce

1. Log into ECMPS 
2. Remain inactive to activate the inactivity timer 

The timer  countdown component does not have any styling. Need to update the timer 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9f9812ea-b64c-4dfa-8d17-253599b68c20)

**Comment by JanellC** [comment]
Styling was broken during the REACT upgrade. The timer is still functional. Adding this ticket to General backlog until it is prioritized

**Comment by jwhitehead77** [comment]
package is not compatible with React 18 so we can not style the circle. the time works and the styling currently is fine so closing
