### ISSUE TITLE
Prototype pollution in webpack loader-utils

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5427]
## Context 
Critical issue spotted in multiple repos 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/03cdcde7-ec9c-4307-b011-5d1c7183d0d5)

This issue impacts the following repos: 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/d770f223-998c-4ba6-85e6-e827499d6357)

**Comment by sdhawan16** [comment]
Resolved in easey-design-system
