### ISSUE TITLE
Prototype Pollution in JSON5 via Parse Method

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5429]
## Context

High severity issue located in multiple repos see below for the repos:
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/87ebecd5-fdd8-43b1-bcc4-9c3ff94d10fe)

The following repos are impacted 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9ba33b4e-4a4c-436e-a46a-2be1d0169cfe)

**Comment by sdhawan16** [comment]
Resolved in easey-design-system
