### ISSUE TITLE
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5431]
## Context 

High issue located in multiple repos 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/21628604-7ed9-470a-9292-93454371b9da)

The issue is located in the following repos: 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/9df18e1c-9001-46d6-9d4a-916077192eb1)

**Comment by sdhawan16** [comment]
Resolved in easey-design-system
