### ISSUE TITLE
Story:  Filter and view hourly apportioned emissions data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#544]
## User Story
As a user, I want to enter filter criteria and see results, so that I can verify results

## Acceptance Criteria
Given that a user has entered filter criteria (see below) 
When the API endpoint is executed
Then the system displays the results (containing data elements below)

Unit type, fuel type, control technologies will be a list of values to select from

States will be displayed in abbreviated format (TX for Texas)

### Filter Criteria
Date (custom date range, no hour range)
State
Facility by ORIS code
Unit type
Unit fuel type
Control technologies
Operating hours only (if selected, return only operating hours. If not selected, return all data), OP Time greater than 0
Filtering will use "AND" condition - find results that match all criteria, not any criteria

### Data Elements
The prototype will include Hourly emissions (no aggregation at unit level)
Include all data elements currently in FTP hourly emissions data EXCEPT for FAC_ID and UNIT_ID

Results will be displayed in a preview in table format
Each data element will be a column
Table limited to 50 results in preview (Showing 50 of XXXX records)
Will provide option to download data results

Query results will include:
`
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO
`

## Testing
Test Case: [TC65](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268419)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R10](https://cvpcorp.testquality.com/project/11428/testcase/268419/requirement/11043). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R14](https://cvpcorp.testquality.com/project/11428/testcase/268420/requirement/11047). Do not remove or edit.

**Comment by david-cvp** [comment]
BA/tester meeting on 12/15 to finalize test cases for this story

**Comment by david-cvp** [comment]
12/16 removed ability to filter by facility name from the requirements

Also updated my test case to remove that test step

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R19](https://cvpcorp.testquality.com/project/11428/testcase/268675/requirement/11061). Do not remove or edit.

**Comment by junie-stigdon** [comment]
Ready to Test: https://easey-dev.app.cloud.gov/api/emissions-mgmt/swagger/

**Note:** Testing is best done with Postman. Swagger doc tends to timeout.

**Comment by david-cvp** [comment]
12/18 began functional testing

**Comment by david-cvp** [comment]
TC65 fails because pagination is required 

12/21 Travis said this was okay, next steps are to either
- make pagination not required, OR
- include a message in Swagger UI that pagination is required

TC66 passes, we are able to get data with all filter criteria and the results include all of our test data and the required data elements

Performance results:

API performance for Dev-Int with 1gb memory:
Request for all data = 223,536 total count of records
Request for 10k records = 7.5 seconds, 6 MB
Request for 50k records = 8.5 seconds, 35 MB
Request for 75k records = 13 seconds, 50 MB
Request for 100k records times out after 12 seconds

API performance for Dev-Int with 2gb memory:
Request for 100k records = 15 seconds, 66MB
Request for 200k records times out after 30 seconds
