### ISSUE TITLE
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5449]
## Context 
High issue spotted in multiple repos 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/cabff0a2-8691-4af6-a602-0528bee66b72)

This issue exists in the repos listed below: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/39a14853-3c83-4037-9cc6-1a788883ff49)

**Comment by sdhawan16** [comment]
Resolved in easey-design-system
