### ISSUE TITLE
minimatch ReDoS vulnerability 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5453]
## Context 

High severity issue in multiple repos 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/127b67d2-c711-4d8a-ac2b-0ca6de00b078)

This issue impacts the repos listed below:

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/7b5959c1-5c93-42a3-a40d-aa35968cb2df)

**Comment by sdhawan16** [comment]
Resolved in easey-design-system
