### ISSUE TITLE
Bug: QA Test Child Records

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5456]
Issue:
Under Test Data the user is unable to expand the child records
This was resolved for the RATA test type but this bug is still affecting the other sections:

'Test Data - Flow to Load Check'
'Test Data - Fuel Flow to Load'
'Test Data - Fuel Flow to Baseline'
'Test Data - Fuel Flowmeter Accuracy'
'Test Data - HG 'Linearity...'
'Test Data - Miscellaneous'.
'Test Data - Online/Offline'.
'Test Data - Primary Element Inspection'.
'Test Data - Unit Default'
'Test Data - Calibration Injection'

'Under Linearity - Linearity Injection'.
'Under Cycle Time Summary - Cycle Time Injection'.
'Under Flow to Load Reference - Flow to Load Reference'
'Under Transmitter Transducer Accuracy - Transmitter Transducer Accuracy data'
'Under Rata > Flow - Rata Traverse'

**Comment by mosesdeeCVP** [comment]
Note how to reach Rata Traverse: 
Ames (1122) Unit 7
Select Rata Test Number (702-202208021248)
Then the first Rata Data and keep expanding the first line until you reach Rata Traverse

**Comment by mosesdeeCVP** [comment]
Bug fixed. The expand option is an option even when it should not. This bug will be addressed in a different ticket.
