### ISSUE TITLE
API: Modify EM Submission POST Endpoint Validations

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5458]
- [x] Modify EM submission POST endpoint so that the closed date cannot be before the open date 

Error Message: closeDate can not be a date before the entered openDate

**Comment by subrataroyCVP** [comment]
@acollad1 Can the closeDate be same as openDate?

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-camd-services/pull/132

**Comment by mosesdeeCVP** [comment]
![Modify EM Submission POST Endpoint Validations 5458.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2b6e9f01-4421-49a3-bd8c-3d25ee8eb077)

**Comment by mosesdeeCVP** [comment]
![Modify EM Submission POST Endpoint Validations 5458.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8411de72-454e-4ca4-94c4-6258cdf7f6d4)

**Comment by mosesdeeCVP** [comment]
EM submission POST endpoint has been modified so that the closed date cannot be before the open date. Error message fires as expected.
