### ISSUE TITLE
Bug: QA RATA Summary 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5483]
Issues:
When editing 'RATA Summary' the user gets many API validation errors (RATA 12, 17, 18, ....)

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/bd2dd60c-7650-48f1-b046-74377e4cc639)

**Comment by subrataroyCVP** [comment]
Pull request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1195

**Comment by mosesdeeCVP** [comment]
Am able to edit the RATA Summary without encountering the errors
