### ISSUE TITLE
Bug: Air Emissions and Test Qualifications 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5484]
Issue:
Air Emissions and Test Qualification seem to have disappeared. I looked Rata (Oris 1122) Test Number (702-202208021248) and was unable to find any records. When I try and create Air Emissions, Test Qualification and Protocol Gas I get an Internal Server Error. Protocol Gas should be found under Copper Station (9) Test Number (N10-Q3-2018-001)

- [x] TESTING NOTE: The scope of this ticket includes all CRUD operations for Protocol gas, Air emissions and Test qualifications

**Comment by mosesdeeCVP** [comment]
View - Protocol gas, Air emissions and Test qualifications
![View - Protocol gas, Air emissions and Test qualifications.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/93189065-8dc4-45ff-81ec-48278863cdbd)

**Comment by mosesdeeCVP** [comment]
Create and Edit Protocol gas and Air emissions
![Create and Edit Protocol gas and Air emissions.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/dc273b1d-2de3-42fe-a16f-4295d8c5da3e)

**Comment by mosesdeeCVP** [comment]
Create and Edit Test Qualification
![Create and Edit Test Qualification.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/01265472-6184-4518-aa8e-2a9c7afc9246)

**Comment by mosesdeeCVP** [comment]
Remove works as expected as well
