### ISSUE TITLE
UI: Disable EM Submission Action Buttons 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5494]
Given a user has navigated to the EM Submission page
When a user tries to use a table action button (extend, approve, close, open) without selecting a record first 
Then they will be disabled and greyed out

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/aafb1ee8-25a7-4488-b70b-48401b2db5f9)
