### ISSUE TITLE
Evaluate and configure Ora2Pg and SCT for data migration

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#55]
- [x] Meet with Cloud.gov architecture team (Chris McGowan) to determine options supported
- [x] Configuration of Ora2Pg
- [x] Installation of Oracle CPA DB Package
- [x] Installation of the CPA for perl scripts
- [x] Installation and testing of schema conversion tool for schema migration

Assignees:
@jwhitehead77 
@visocvp

**Comment by davidkwartler** [comment]
Epic: Determine data migration strategy

Tasks:
Evaluation and configuration of Ora2PG and SCT for data migration (3) - Done
-Met with Cloud.gov architecture team (Chris McGowan) to determine options supported
-Configuration of Ora2Pg
-Installation of Oracle CPA DB Package
-Installation of the CPA for perl scripts
-Installation and testing of schema conversion tool for schema migration

Configuration file for data migration (1) - In progress

Create RDS oracle instance in AWS (1) - Sprint backlog
 
Obtain SQL dumps from On-Premise Oracle DB and load into CVP AWS RDS Oracle (2) - Sprint backlog (external dependencies)

Schema migration from AWS RDS Oracle to Cloud.gov Postgres through SCT (2) - Sprint backlog
- generate assessment reports

Data migration from AWS RDS Oracle to Cloud.gov Postgres through ORA2PG (2) - Sprint backlog
