### ISSUE TITLE
Spike: Size Requirement Implementation

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5511]
Research and investigate the apprporiate way to implement a size requirement for the MATS bulk file submission and determine what the size requirement threshold should be for the modal

**Comment by fanwari1** [comment]
For a single file, the upload limit should be **30MB**. This may change in the future. It may be best to implement this limit as an environment variable. This limit should be implemented in both the ui and the api. The Api endpoint will accept a single file so the UI the should make multiple calls using each of the files in the bulk upload. 

Code similar to the following can be used to determine filesize in UI:
```
<!DOCTYPE html>
<html>
<head>
	<title>File Validation-1</title>
</head>

<body>
	<p>
		<input type="file" id="file"
			onchange="Filevalidation()" />
	</p>

	<p id="size"></p>

	<script>
		Filevalidation = () => {
			const fi = document.getElementById('file');
			// Check if any file is selected.
			if (fi.files.length > 0) {
				for (const i = 0; i <= fi.files.length - 1; i++) {
		
					const fsize = fi.files.item(i).size;
					const file = Math.round((fsize / 1024));
					// The size of the file.
					if (file >= 4096) {
						alert(
						"File too Big, please select a file less than 4mb");
					} else if (file < 2048) {
						alert(
						"File too small, please select a file greater than 2mb");
					} else {
						document.getElementById('size').innerHTML = '<b>'
						+ file + '</b> KB';
					}
				}
			}
		}
	</script>
</body>
</html>

```

For the backend, we can use native nestjs classes to limit the file size and it would look something like this (note that maxSize is in bytes):
<img width="696" alt="image" src="https://github.com/US-EPA-CAMD/easey-ui/assets/102816236/fbeb9c0a-f8dd-4a74-8356-f45d377d7dbf">
