### ISSUE TITLE
UI: Display Resubmission Reason in Data Table 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5516]
As an ECMPS Admin, when I select a record to require resubmission I want any notes written in the reason box to be saved and displayed in the corresponding record row of that table.

Given a user has selected a record to require resubmission
When a user enters notes in the require resubmission pop out and clicks save
Then the note will be displayed in the read only view pop out of the corresponding record

**Comment by mosesdeeCVP** [comment]
Display Resubmission Reason in Data Table Test Summery
![Display Resubmission Reason in Data Table.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/36c6c404-1929-49bf-b7a7-651b18b9835c)

**Comment by mosesdeeCVP** [comment]
Display Resubmission Reason in Data Table Cert Event
![Display Resubmission Reason in Data Table Cert Event.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/0328adc6-9226-41b9-97f8-6e4e9292dfac)

**Comment by mosesdeeCVP** [comment]
Display Resubmission Reason in Data Table TEE
![Display Resubmission Reason in Data Table TEE.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1e846723-fca4-4e3c-b246-652c6db6af22)
