### ISSUE TITLE
Bug: EM Submission Access Filters

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5517]
Issue:
The EM submission GET endpoint has Facility ID' and 'Configuration'  implemented as required. Since 'Reporting Period' and 'Status' are not required the data can be looked up. When the user adds the filters the data is filtered appropriately. The bug appears when the user then changes the filter back to the default 'Select' option. The UI shows that the 'Reporting Period' and 'Status' are now required, The UI will not accept the filter until the criteria is met or it is refreshed.

- [ ] disable Apply filter button when Facility ID and Configuration drop-downs have not been selected 

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/1531934b-95e9-44e1-941c-558ca337da48)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1186

**Comment by mosesdeeCVP** [comment]
Bug fixed
