### ISSUE TITLE
Bug: Emissions API Import Error [2490 CT0001]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5520]
Steps to recreate:
1. Login and checkout 2490 CT0001
2. Import 2490_CT0001_2023Q2_EM.json  (File accessible via link below)

https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/download.aspx?UniqueId=3f75168493194e858b40609870e085dd&e=7OMU0p

- [x] Resolve API error 

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/8cebd4a9-c4c1-47b8-81cc-fe3bc2c42517)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEFQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f153054eddf7f8c18335b398f8416ef930a0765d/Emissions%20API%20Import%20Error%20%5B2490%20CT0001%5D%20%235520.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
