### ISSUE TITLE
Bug: Emissions API Import Error [6071 1]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5522]
Steps to recreate:
1. Login and checkout 6071 1
2. Import TC_TC1_Emissions_EDR_01012019_TO_01012019.json  (Link to JSON file below)

https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/download.aspx?UniqueId=5cbf757e29c04d6987086f9fbb4f2de5&e=N4KKLz

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/f6f6c598-d052-48b6-be14-0b61ab8edce2)

**Comment by billmiller13** [comment]
The attached file used for import contains a field named hourlyGfmData which should be hourlyGFMData.  The capitalization for this field was changed in the emissions schema in on 3/16/23.
