### ISSUE TITLE
Bug: QA Test Data UI 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5526]
1. Global view Navigate to 55233 EU-1A, EU-1B, EU-2A, EU-2B, EU-3A, EU-3B, EU-4A, EU-4B, EU-5A, EU-5B, CP100
2. Navigate to Test Data 
3. Select EU-3A Unit Default
4. Click the + expand button on the test number 2017 record in the table
5. Keep Expanding

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/2fe2a9db-ef9d-4c59-b52b-0b78a53d72a2)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVVQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b2eabe74cc4e7df14e9b58c1747c7d3bfe947cdf/QA%20Test%20Data%20UI%20%235526.png)

**Comment by mosesdeeCVP** [comment]
No errors occur when accessing the requested data. All data shows up as expected.
