### ISSUE TITLE
Bug: QA Test Data Import Error 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5527]
Steps to Recreate: 
1. Login and checkout  55233 EU-1A, EU-1B, EU-2A, EU-2B, EU-3A, EU-3B, EU-4A, EU-4B, EU-5A, EU-5B, CP100
2. Import from historical all under 2017 Q1

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/eefc23b8-7c53-4163-b671-7c42b1b92f9e)

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/528

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Bug is fixed. Data is imported as expected
