### ISSUE TITLE
Bug: Monitoring Plan Formula Code

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5530]
1. Login and checkout 3131 3,4,CS1 
2. Export monitoring plan
3. Import monitoring plan

Note:The user posted screenshots of the valid formula codes in the reporting instructions and D-15 was valid

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/81a3776d-3a5b-41dc-a738-e8adbbe966e8)

**Comment by subrataroyCVP** [comment]
**MP Check Specification:**
https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Check%20Specifications%202022%20Q1.pdf

**Comment by subrataroyCVP** [comment]
**CHECKS IMPLEMENTED**

- [x] FORMULA-7-A 
- [x] FORMULA-7-B 
- [x] FORMULA-8-A
- [x] FORMULA-8-B  
- [x] FORMULA-9-A
- [x] FORMULA-9-B

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/471

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Am able to export and import as expected with out errors
![Monitoring Plan Formula Code #5530 - Export and Import.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3b8187a5-13ee-4c59-8ca1-d5e5a391b1cb)

**Comment by mosesdeeCVP** [comment]
FORMULA-8-A and FORMULA-9-A
![FORMULA-8-A and FORMULA-9-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/af018da6-a9e8-449d-b70a-3b3e46e01712)

**Comment by mosesdeeCVP** [comment]
FORMULA-7-A
![FORMULA-7-A.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/59156549-60c8-4174-be97-8fb0a8c3d2ec)

**Comment by mosesdeeCVP** [comment]
FORMULA-8-B
![FORMULA-8-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ab66cfef-2f4f-4e2c-ad23-5cf29d0f1899)

**Comment by mosesdeeCVP** [comment]
FORMULA-9-B
![FORMULA-9-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/f2ee2868-5636-4c67-a9d6-b1a0b70d440b)

**Comment by mosesdeeCVP** [comment]
FORMULA-7-B
![FORMULA-7-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3c1006e5-e27f-4e16-994b-b18d9196063d)

**Comment by mosesdeeCVP** [comment]
FORMULA-7-B
![FORMULA-7-B.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b51bfcf0-85bc-42f0-8d8b-5c3c2e8cb74b)

**Comment by mosesdeeCVP** [comment]
Exporting and then importing works as expected
