### ISSUE TITLE
TEST ONLY Bug Monitoring Plan: UI Error St Johns River Power (207)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5532]
Believe this issue has been resolved prior to start of sprint but would like a tester to confirm as well that below is no longer an issue
Issue:
Create existing component, view/edit errors "Cannot read properties of undefined (reading data) at DataTableAnalyzerRanges.js:47:25"

https://usepa.sharepoint.com/:v:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/St%20Johns%20River%20Power%20-%20unit%202%20-%20Systems%20Components%20issue.mp4?csf=1&web=1&e=gp3x39

**Comment by acollad1** [comment]
The developer could not reproduce the issue via instructions from user so moving to test to be confirmed by tester

**Comment by mosesdeeCVP** [comment]
Went through the steps and was unable to reproduce the error. Ticket will be closed.
