### ISSUE TITLE
Bug Monitoring Plan: Unit Controls Error

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5533]
Issue:
User cannot close out a control record even though the record did not have installation date. Error "[CONTROL-5-A] - You did not provide [installDate], which is required for [UnitControl]"

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/cde00fe9-a587-4330-9d81-d2cc8050a467)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0FOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a074d5e4240d5dcece6777acbc0b9e3fe52db278/Unit%20Controls.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
