### ISSUE TITLE
Bug: QA Test Data Cycle Time Injection Date

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5534]
Issue:
Date validation issue.  End date in new cycle time injection record prior to begin date is saved without error.

Steps to Recreate:
1. Add Cycle time summary
2. Add component id 202
3. Add test number 2345
4. Add test reason DIAG
5. Add test result FAILED
6. Add begin date time 6/14/2023 3:50
7. Add end date time 6/14/2023 3:15
8. Add Cycle Time Summary Total time 10
9. Add Cycle time injection

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![QA Test Data Cycle Time Injection Date #5534.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/8fbf21a1-7894-4703-a9be-53fe1c9da33a)

**Comment by mosesdeeCVP** [comment]
End Date Cycle Time Injection record prior to begin date causes error as expected.
