### ISSUE TITLE
Migrate Prod applications to cflinuxfs4 stack - Need Before End of Sept

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5537]
## Context 

During 7/19 Planning discussed that Cloud. Gov will no longer support cflinuxfs3. Need to migrate applications to cflinuxfs4. The scope of this ticket is to **Migrate the prod applications to cflinuxfs4** since Migrate applications to cflinuxfs4 - Pre Prod Applications only #5519 has been completed 

Will plan to migrate campd to cflinuxfs4 during the prod release. If that attempt does not work will work on this ticket later in august. **Must be completed before the end of Sept**

**Comment by jwhitehead77** [comment]
There was an issue getting the prod stacks changed so the apps will need to be deleted & repushed. There is also an issue with the existing packages so a pipeline was created to rebuild & package them from the existing artifacts. Will get with NCC to redeploy next week.

**Comment by jwhitehead77** [comment]
Run the following on each cflinuxfs3 app left...
cf target -o epa-easey -s prod && cf change-stack account-api cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack auth-api cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack campd-tools-proxy cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack emissions-api cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack facilities-api cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack mdm-api cflinuxfs4
cf target -o epa-easey -s prod && cf change-stack ssh-tunnel cflinuxfs4

If any of these fail to change the stack then...
- Modify the deploy-list.txt in devops repo removing the apps where the stack successfully change to cflinuxfs4
- Delete the app from the prod space in cloud.gov
- Redeploy by running the deploy-all.sh per normal production deployment

**Comment by acollad1** [comment]
Please use the link below to access the recording that reviews this ticket:
https://decisionpointcorp-my.sharepoint.com/personal/skhan_decisionpointcorp_com/_layouts/15/guestaccess.aspx?share=EcnurFMyQs1CmS5dgwPUumwBKZd7BIxxWo1OEI58M82pvA

**Comment by JanellC** [comment]
Decision Point is taking on this ticket.

**Comment by JanellC** [comment]
Based on 9/19 refinement discussion, DPC/ERG will add details to the comment of this ticket and close it out

**Comment by shahbazkhan1999** [comment]
Attached  are the documents that are essential during the deployment process.
[PDFen.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdSsyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20a189157e55f73e3fa1942df79d68983a5d9498/PDFen.pdf)

[RE_ EASEY CDC - DB test failed (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkMyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fd7b46199cc9628644e6b04928cc6ec29031b894/RE_%20EASEY%20CDC%20-%20DB%20test%20failed%20%281%29.pdf)

[RE_ EASEY CDC - DB test failed (2).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdksyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26cb8776a97a6fab99a6ef8577be12c11b8e7649/RE_%20EASEY%20CDC%20-%20DB%20test%20failed%20%282%29.pdf)
