### ISSUE TITLE
API: Create DTO for New QA Test Types

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5538]
- [ ] Implement response (example value/schema) for the QA Cert Events and Test Extenstion and Exemption GET and PUT endpoints 
- [ ]  Implement response (example value/schema) for the QA Cert Events and Test Extenstion and Exemption DELETE endpoints 
- [ ] Response should match what the endpoint is returning

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-camd-services/pull/149

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/12ff223c-dcb6-40d4-88af-5697da1af55b)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/49a4fba6-711e-4e4c-be64-5c707417cd57)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/3caef0d9-0bac-43f9-804f-31aacf73689c)
