### ISSUE TITLE
API: Implement Response for EM Submission Access Endpoints

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5539]
- [ ] Implement response (example value/schema) for POST and PUT EM Submission endpoints
- [ ] Response should be the same at the EM Submission GET endpoint

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-camd-services/pull/148

**Comment by subrataroyCVP** [comment]
![Screenshot 2023-08-02 172818.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/c9a02eef-acfb-4d84-af49-faf339e41cc6)

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/fb89a737-e5b7-4482-8308-e2bf395625ae)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/d5c1d805-d329-4229-8d25-7a615b1980ff)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/ba8d1080-d19c-4bee-af15-ed5734557959)
