### ISSUE TITLE
Code QL scanning alert

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5545]
## Context 

High Code Scan alert in the MDM repo 

https://github.com/US-EPA-CAMD/easey-mdm-api/security/code-scanning/3

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8fcef324-c157-4ef3-8095-57249d5dca2d)

Will take a look into the issue but may not need to fix it since we control the data that the "replace" function. Once the team has taken a look into the issue will notify Karina.

**Comment by JanellC** [comment]
@kstetsyuk This issue can be closed out this is not much of a security issue. The team can discuss with you more if you have any questions.

**Comment by kstetsyuk** [comment]
Thanks for looking into this and the update! @JanellC
