### ISSUE TITLE
Bug: EM Submission Extend Action

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5550]
Extend button should only be enabled and work on open window status records

**Comment by subrataroyCVP** [comment]
![image.png](https://images.zenhubusercontent.com/6241dbcae8a2b862aec6868b/bdc93648-0670-4208-ac26-7aebac1075c0)

Added 2 Open records for Testing.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Extend is not active for Closed Status
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGNhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fae43913c2e02f94f9b9d3e3def96bf086c09927/Extend%20is%20not%20active%20for%20Closed%20Status.png)

**Comment by mosesdeeCVP** [comment]
Extend is active for Opened Status
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGthIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--09271f406ffa40cb76cbbe9e3d549e3da126c4e1/Extend%20is%20active%20for%20Opened%20Status.png)

**Comment by mosesdeeCVP** [comment]
Extend is not active for unselected Status
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHNhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2e69a00bb4f03576e2f2f2b267e770303bf46277/Extend%20is%20not%20active%20for%20unselected%20Status.png)
