### ISSUE TITLE
508: Admin Module- Sprint 14.2 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5552]
- [x] Perform 508 testing on admin module which included EM Submission, Error Suppression, and QA Data Maintenance

**Comment by aprematta** [comment]
Here are the results of the 508 testing, if you need any clarifications let me know:

https://ecmps-dev.app.cloud.gov/admin/qa-maintenance

- Facility Name/ID field not keyboard accessible
- ID on Type label/Input is a duplicate ID
- View buttons in the tables are generic, tie to something unique such as the test number
- Labels for the select checkboxes are empty
- When closing the View module, focus does not return to the View button
- Table Header cells are missing aria labels and sort attributes
- Table does not have an accessible name


https://ecmps-dev.app.cloud.gov/admin/error-suppression

- The error suppression left nav item is not keyboard accessible
- When attempting to Add, I left note blank. The modal was closed and I got an error message that note should not be null, undefined or empty. 2 issues with this per 508:
   1. Required fields must be indicated they are required with either aria-required=true or an asterisk in the label. This occurs on other add/edit windows
   2. The modal should not be closed and the values already entered should remain
- Table Header cells are missing aria labels are sort attributes
- Table does not have an accessible name
- View buttons in the tables are generic, tie to something unique (may need to use multiple column headers)
- Labels for the select checkboxes are generic, all have an aria label that says 'select'
- When closing the View module, focus does not return to the View button
- When closing the Clone module, focus does not return to the Clone button
- When closing the Deactivate module, focus does not return to the Deactivate button

https://ecmps-dev.app.cloud.gov/admin/em-submission-access

- Facility Name/ID field not keyboard accessible
- ID on Reporting Period and Status is a duplicate ID
- View buttons in the tables are generic, tie to something unique (may need to use multiple column headers)
- Labels for the select checkboxes are empty
- When closing the View module, focus does not return to the View button
- Table Header cells are missing aria labels are sort attributes
- Table does not have an accessible name
- When closing the Close module, focus does not return to the Close button
- When closing the Open module, focus does not return to the Open button
      - Date picker button labels are not unique, change to Toggle Calendar for <field>
      - Date fields look to be mislabeled, the output is the actual date instead of the text label such as 'Open Date)
- When closing the Extend module, focus does not return to the Extend button
      - Date fields look to be mislabeled, the output is the actual date instead of the text label such as 'Open Date)
- When closing the Approve module, focus does not return to the Approve button
