### ISSUE TITLE
Bug: Emissions Import Issue Northport Facility 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5554]
Issue: 
The user attempted to import the below file into the emission workspace and received an Import error "HTTP 500"

Login and check out Northport UGT001
Emissions: Import data / Import from file

JSON File:
https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/download.aspx?UniqueId=895015096ba24f33814cac73d8a9379d&e=moPreM

**Comment by sdhawan16** [comment]
Bug was resolved with https://github.com/US-EPA-CAMD/easey-emissions-api/pull/386
