### ISSUE TITLE
Bug: Evaluation MP

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5556]
Issue:
Error occurred while validating the user's security token

**Steps to Reproduce:**

1. Login and check out Roxboro 4A,4B,CS004A
2. Evaluate Monitoring plan

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af384b7634d108b75a48f6494d84903efa4e1033/image.png)

**Comment by JanellC** [comment]
This issue has been resolved
