### ISSUE TITLE
Bug: Import Error QA Test

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5558]
Issue:
The user is getting the following import error "instance.testSummaryData[0] is not any of [subschema 0],[subschema 1]
Steps to Reproduce:
Login and check out Barry 7A
Select QA Test/Linearity Summary/Import

**Comment by subrataroyCVP** [comment]
2022 Q4
Imported from Historical and Exported and Import the same. (FFACCTT, LINE, RATA, QACERT)

Unable to find any issues. Moving it to `Ready for Testing`, so testers can test it further.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Was able to import from all the below with no issues:


7DAY
CYCLE
LINE
ONOFF
FFACCTT
PEI
RATA
QA Cert
