### ISSUE TITLE
Implement View Pop Out in Error Suppression 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5561]
As an ECMPS admin, I want to see the view pop out in the Error Suppression Screen so that I can support program goals.

Given an ECMPS admin user logs in
When they navigate to the Error Suppression screen table
Then there will see a view submission button

![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/8e6917a0-dfce-4756-b789-e61de60d6b3d)

Given an ECMPS admin user navigates to the Error Suppression screen table
When they click on the view button
Then the open pop-out will open and will have all fields as shown in the wireframe below

https://xd.adobe.com/view/96db9ac9-f9a6-4427-9c8b-f057858d6776-c388/screen/b28c5de7-ef05-469a-a925-360317e84f67/

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWszIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a2675647f71d0519992c66b826135c7760e8c2f0/Error%20Suppression%20pop%20up.png)

**Comment by mosesdeeCVP** [comment]
View Pop Out in Error Suppression is updated
