### ISSUE TITLE
Implement Screen Responsiveness for EM Submission Access 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5563]
As an ECMPS Admin, I want the EM Submission Access screens to be responsive to the below screen sizes and layout consistent with linked wireframes depending on the screen size.

Desktop 1024
https://xd.adobe.com/view/5f899592-74d7-4284-9fbf-c500c91134b8-0ada/
Desktop 1200
https://xd.adobe.com/view/b3f833fd-4a7d-4e02-a70a-cb434f9a6304-e6ab/
Desktop 1400
https://xd.adobe.com/view/765bee30-f90d-41c2-9100-c78f2fca665e-2308/

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Responsiveness for EM Submission Access 1024
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3M5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--acce469cc0b7b08a19156b61c2d152336d4aac9b/Responsiveness%20for%20EM%20Submission%20Access%201024.png)

**Comment by mosesdeeCVP** [comment]
Responsiveness for EM Submission Access 1200
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3c5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10a8cb2200bc11adb093e107b6ec6a77700b5fe5/Responsiveness%20for%20EM%20Submission%20Access%201200.png)

**Comment by mosesdeeCVP** [comment]
Responsiveness for EM Submission Access 1400
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczA5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff898c24f9e67f14a9ba16faff18a306c1a7d7f2/Responsiveness%20for%20EM%20Submission%20Access%201400.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkJFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe6dcc27298d357e0591d14fa8fef5eb6ac98fcb/Open%20Submission%20Access%201024.png)

**Comment by mosesdeeCVP** [comment]
Responsiveness work has been completed
