### ISSUE TITLE
Implement Screen Responsiveness for QA Cert Data Maintenance 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5564]
As an ECMPS Admin, I want the QA Cert Data Maintenance  screens to be responsive to the below screen sizes and layout consistent with linked wireframes depending on the screen size.

Desktop 1024
https://xd.adobe.com/view/3bae4b9c-7093-4ec5-93dc-402ed7fa1797-6efd/
Desktop 1200
https://xd.adobe.com/view/de838d61-586b-4b25-8377-d12defa52e9c-8bd0/
Desktop 1400
https://xd.adobe.com/view/28084716-4675-42a9-b368-cef8a1e4b60e-7d5b/

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18e20bf5a984db8b7f392aa9688ffe9ed3e30ed3/QA-Cert%20Data%20Maintenance%201024.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkpFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b145371e3b79e50b37ae36b2f7ed7d5e957b28a/Responsiveness%20for%20QA%20Cert%20Data%20Maintenance%201024%20-%20Require%20Subsmission.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk5FIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b015ac48193e6730fe3cd9bfeb07ab0f315e68c/Responsiveness%20for%20QA%20Cert%20Data%20Maintenance%201024%20-%201.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlJFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c8f98e6e5e1a9ffefc4192333e4bbcc55cb0a870/Responsiveness%20for%20QA%20Cert%20Data%20Maintenance%201024%20-%202.png)

**Comment by mosesdeeCVP** [comment]
Responsiveness work has been completed
