### ISSUE TITLE
Bug: "Here" Link Not Working 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5569]
Issue:

Currently, the "here" link on the home page is not working. The user is taken to the below screenshot when clicking on the link
![image.png](https://images.zenhubusercontent.com/6228dda1d205100b36ed2f43/093e6368-1e60-45f4-85a9-466e98a81391)

- [x] URL does not have a file extension only path so no content is showing 
- [x] https://www.epa.gov/system/files/documents/2023-05/CDX-Start-Guide-Updated-04-28-2023.pdf

**Comment by mosesdeeCVP** [comment]
Was able to access the provided link after clicking the 'here' link in the home page

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3dhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad9e4e8f83da7521aa590481988d309f7ac99fe3/Here%20-%20Link%20Not%20Working%20.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczRhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3a44bd942857c4d8c46eea4685359928a1cf1bf/here%20link.png)
