### ISSUE TITLE
Bug: Unit Control API

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5580]
Issue:
Unit Controls API is looking for a String in originalCode and possibly seasonalControlsIndicator. When the User creates in the UI the UI is returning an int. Thus triggering CONTROL-5-A when it should be successfully created.

Notes: This bug was found during work on ticket #5533

**Comment by mosesdeeCVP** [comment]
Bug Fixed. Was able to create Unit Controls setting Original Code to Yes and leaving Install Date as blank with no issue
