### ISSUE TITLE
Bug: Modify Emissions API Endpoint- Sprint 14.2

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5581]
Issue:

The Emissions export funtionality is firing off too many connections and causing the application to crash. As apart of the scope of this ticket need to resolved the issue with emissions export. 

For testing this ticket, the tester shall conduct regression testing on the emissions export to ensure that export is no longer crashing the system and functionality is still working as intended

**Comment by JanellC** [comment]
In the global and workspace view could export emissions data for Barry Q2 2022 without the system crashing
