### ISSUE TITLE
Bug: Emissions Export

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5582]
Emissions data for daily backstop view 2023 Q1-Q2 was added, but when the user tried to export for those reporting periods there is no data in the exports

**Comment by subrataroyCVP** [comment]
Due to non presence of 2023 Q1-Q2 in the emissions evaluation table. Export is returning empty object.

I have made Jason aware of that. As soon as he brings those data to dev or respective environment we should be able to get data for export.

**Comment by JanellC** [comment]
Invalid. System works as expected. 2023 data has not been loaded yet.
