### ISSUE TITLE
Re-Test: QA Import

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5584]
Issue:

The user is experiencing an error for the QA import module. When user attempted to import an exported QA test file from Barry (6A) they experience an error

**Comment by jwhitehead77** [comment]
Not able to reproduce and I exported and import both from historical and to and from file for all of 2022 tests

**Comment by mosesdeeCVP** [comment]
Imported from 2020 Q1 to 2022 Q4. From file and historical. Did not see any error. System works as expected
