### ISSUE TITLE
Bug: UI Home Upper Menu 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5585]
Issue:

The top menu option headers are overlapping with the expand dropdown buttons:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmNtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50386e221e9ebd7c63523a05697fab45a5bf6934/image.png)

The carrot icon needs to be changed to white to meet 508 standards.

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1234
