### ISSUE TITLE
Front End: QA Schema Updates

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5587]
- [ ] Once all schema/DTO/property name updates have been made for QA then the front end will need to be updated as well as seen in the file below:

- [ ] https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B742C08F5-ECF8-4A5A-B3BA-AA21FE2D579B%7D&file=EPA%20XML-JSON-DTO%20Audit.xlsx&action=default&mobileredirect=true

**Comment by mosesdeeCVP** [comment]
Ticket will be tested in this testing only ticket: [#5627](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5627)
