### ISSUE TITLE
Bug: Error Handling for Data Night Job 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5589]
## Context 

During The CAMPD OM sync meeting. The team discussed a bug with the custom data download (CDD) and the filters not working properly due to the Data Night Job

**Comment by acollad1** [comment]
The responsibility falls on informatica for this ticket. Reach out to Paul Dutrow & Dhontula, Vamshikrishna

**Comment by acollad1** [comment]
Please use the link below to access the recording that reviews this ticket:
https://decisionpointcorp-my.sharepoint.com/personal/skhan_decisionpointcorp_com/_layouts/15/guestaccess.aspx?share=EcnurFMyQs1CmS5dgwPUumwBKZd7BIxxWo1OEI58M82pvA

**Comment by hamezene** [comment]
Shahbaz will be meeting with the Informatica team on 9/28 at 5pm to fix the issue.

**Comment by lgiannini1** [comment]
@shahbazkhan1999 What change was made for this ticket? I'm unable to access the recording file on the ticket.

**Comment by annalbrecht** [comment]
Blocked by #6101

**Comment by annalbrecht** [comment]
This will be handled via #6109.
