### ISSUE TITLE
Enable PG cron extension & turn on auto vacuuming in production 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5590]
## Context 

Get pg crom scheduler pushed to production and turning on auto vaccuming. This is a low priority item can be completed when the team gets a chance.

**Comment by JanellC** [comment]
@jwhitehead77 will work with DPC on this task. FYI- @shahbazkhan1999

**Comment by hamezene** [comment]
More research needs to be done.  Find information on cloud.gov on hour cron extension is enabled.

**Comment by jwhitehead77** [comment]
@hamezene CVP has already done this research and have enabled the pg_cron extension in non-prod env. This ticket is to get it done in prod and here is the cloud.gov info on it https://cloud.gov/docs/services/relational-database/#setting-optional-parameters-1

**Comment by ergjustin** [comment]
[DOCUMENT](https://www.alibabacloud.com/help/en/analyticdb-for-postgresql/latest/use-the-pg-cron-plug-in-to-configure-scheduled-tasks#:~:text=You%20can%20connect%20to%20the,the%20pg_cron%20extension%20is%20installed.)
As per this above document, we can be able to find the pg_cron extension installed or not by using `SELECT * FROM pg_extension;` (I tried in PG ADMIN)
When I tried in dev environment unfortunately, I am unable to find pg_cron extension.
Our plan is learning how it was implemented in dev; then implement in production.

**Comment by ergjustin** [comment]
[Database image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ttQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef25a9c81426f08d65125bf3af868fb79fda86c3/database.PNG)
