### ISSUE TITLE
MP Schema Updates for Import/Export

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5596]
Update monitor plan schema in content repo to address inconsistencies in property naming convention, validations, and align closer with the current XML schema structure. Please follow the changes outlined in the XML/JSON/DTO Audit Document linked at the bottom.

**Monitor Plan JSON Schema**
- [ ] rename orange highlighted properties per linked document
- [ ] update the required list for all property name changes
- [ ] add version property in schema definition to depict the version of the schema
- [ ] add lastUpdated property in schema definition to show the date the version was modified
- [ ] change all range validation minimums to 0
- [ ] change groundElevation minimum to allow negative based on the numeric data type scale & precision specified
- [ ] apply regex pattern to all unitId properties
  - RegEx: ^[A-z0-9\\-\\*#]{1,6}$
- [ ] apply regex pattern to all stackPipeId properties
  - RegEx: ^(C|c|M|m|X|x)(S|s|P|p)[A-z0-9\\-]{1,6}$
- [ ] apply regex pattern to all componentId properties
  - RegEx: ^[A-Z0-9]{1,3}$
- [ ] apply regex pattern to all monitoringSystemId properties
  - RegEx: ^[A-Z0-9]{1,3}$
- [ ] apply regex pattern to all formulaId properties
  - RegEx: ^[A-Z0-9\\-]{1,3}$

**Example Regex pattern in JSON schema**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0pHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--608b9df8a081c0d7b04cf1b332c253c1ccabbaf6/image.png)

**XML/JSON/DTO Audit Document**
https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%202.0/4-Development/EPA%20XML-JSON-DTO%20Audit.xlsx?d=w742c08f5ecf84a5ab3baaa21fe2d579b&csf=1&web=1&e=DDlY5Z

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Ticket will be tested in this testing only ticket: [#5628](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5628)
