### ISSUE TITLE
MP API Updates due to MP Schema Updates for Import/Export

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5597]
Update monitor plan api dtos to address inconsistencies in property naming convention, validations, and align with the JSON schema structure. Please follow the changes outlined in the XML/JSON/DTO Audit Document linked at the bottom.

- [ ] rename orange highlighted properties per linked document

**XML/JSON/DTO Audit Document**
https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%202.0/4-Development/EPA%20XML-JSON-DTO%20Audit.xlsx?d=w742c08f5ecf84a5ab3baaa21fe2d579b&csf=1&web=1&e=DDlY5Z

**Comment by mosesdeeCVP** [comment]
Ticket will be tested in this testing only ticket: [#5628](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5628)
