### ISSUE TITLE
MP API DTO Validation Updates

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5598]
Update monitor plan api dtos to address inconsistencies in validations, and align with the JSON schema validations. Please follow the changes outlined in the XML/JSON/DTO Audit Document linked at the bottom.

**General**
- [ ] change all numeric range validation minimums to 0
- [ ] change groundElevation minimum to allow negative based on the numeric data type scale & precision specified
- [ ] apply regex pattern to all unitId properties
  - RegEx: ^[A-z0-9\\-\\*#]{1,6}$
- [ ] apply regex pattern to all stackPipeId properties
  - RegEx: ^(C|c|M|m|X|x)(S|s|P|p)[A-z0-9\\-]{1,6}$
- [ ] apply regex pattern to all componentId properties
  - RegEx: ^[A-Z0-9]{1,3}$
- [ ] apply regex pattern to all monitoringSystemId properties
  - RegEx: ^[A-Z0-9]{1,3}$
- [ ] apply regex pattern to all formulaId properties
  - RegEx: ^[A-Z0-9\\-]{1,3}$

**Example Regex validation**
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/d9972e50-c758-4fc4-9e0d-d33be92e05d7)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/e1fd8aad-c1d0-4639-996c-6d3687936e32)

**XML/JSON/DTO Audit Document**
https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%202.0/4-Development/EPA%20XML-JSON-DTO%20Audit.xlsx?d=w742c08f5ecf84a5ab3baaa21fe2d579b&csf=1&web=1&e=DDlY5Z

**Comment by mosesdeeCVP** [comment]
Ticket will be tested in this testing only ticket: [#5628](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5628)

**Comment by subrataroyCVP** [comment]
PR: https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/479
