### ISSUE TITLE
Document Environment Needs

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#56]
- [x]  Mike and Jason to discuss how to manage Cloud.gov environments 
- [x] Determine immediate needs 
- [x] Determine future needs 

Assignees:
@maheese
@jwhitehead77

**Comment by jwhitehead77** [comment]
Short term we will need dev and test environments
Staging and Production environments will be needed around mid 2021
Longer term there will need to be prod break fix dev & test environments however these can be spun up on demand and tore back down and then the release would go into the normal staging environment just before production
