### ISSUE TITLE
Bug: QA Expanding a Record

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5607]
Issue:
Expanding QA Miscellaneous child records in the workspace leads to a blank page. 
Steps to recreate: 
Log in --> QA & Cert Test Data --> Barry, 1, 2, CS0AAN --> Check Out --> Locations: 1, Test Type Group: Miscellaneous --> Click Plus symbol on data line

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDlmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--646a4563217b1ef3871cd2bef89e6ae63766b76d/QA%20Expanding%20a%20Record%205607%20Logged%20Out.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUJmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd709832c5527fcb77ff29abc430ebc6f2368b9d/QA%20Expanding%20a%20Record%205607%20Logged%20In.png)

**Comment by mosesdeeCVP** [comment]
The extra expand option is no longer available as expected
