### ISSUE TITLE
Bug: Reporting Period Styling Issue 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5612]
Issue:

The reporting period styling is off displaying black text instead of white which makes it difficult to read

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzFWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9bbed7def346278f79d79d4a438a6b4301cee6ce/Reporting%20Period.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c0b0028ab47051bc37432a87b7eab6a64635595b/Evaluate.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzlWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a7381548c9e34e71cd30541ae66a50132d44e418/Submit.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEJWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--776231143ef48f922f466a02e4273fd164589ce5/Drop%20Down%20Carets.png)

**Comment by mosesdeeCVP** [comment]
The locations that used to have black text or black icons are now in white
