### ISSUE TITLE
UI: Modify Protocol Gas

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5615]
- [x] Modify UI to use the master data gas-component-codes endpoint that will return gas type & gas component codes combined. Records marked with group = 'GCC' are gas component codes. Records marked with group = 'GTC' are gas type codes. Gas Type codes are legacy and only there in order to show historical data. When creating/editing disable/remove the GTC records and do not allow them to be selected, however, the GTC codes need to be in the list to show the data on the screen in order to view/change it.
- [x] Modify Vendor ID field to be a standard drop-down so that users can select from a list of valid ids 
- [x]  Modify Gas Type field to be a multi-select dropdown that produces a comma-delimited list stored in that field. 

![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/970e5138-5822-43be-bb44-6cb50f6d61ef)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2pNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0d46c3f1d0a4b37df3e5288c546386b98338d648/image.png)

**Comment by mosesdeeCVP** [comment]
Protocol Gas dropdowns - Gas Type Code legacy codes grayed out.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--008675fbdda7dcf269ca03d40d3b10986ba5b52e/Protocol%20Gas%20dropdowns%20-%20Gas%20Type%20Code%20legacy%20codes.png)
