### ISSUE TITLE
Bug: MP Export 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5616]
Expected Behavior:
After following the steps below user should be able to successfully export a monitoring plan 
Steps to Reproduce:
Log into ECMPS workspace
Navigate to the export module
Select Configurations
Export selected monitoring plan
User receives "Cannot set properties of undefined (setting 'locations')" and does not get an export 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDFyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--80512d21bbad59124010ca18e38964a55c7714da/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4989cff0dd96f098e8acf6a031b238774a3e9c1/image.png)

**Comment by JanellC** [comment]
@bchofor will shadow during the testing of this ticket

**Comment by mosesdeeCVP** [comment]
Export is working as expected. Official and Workspace

**Comment by mosesdeeCVP** [comment]
Official
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkNnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ccdb463c986373ef4a6d6baa1c618d9f0ccf43a5/MP%20Export%20Official.png)

**Comment by mosesdeeCVP** [comment]
Workspace
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdktnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a9ad0865dec39d60ea0823cd91bd908556a60d35/MP%20Export%20Workspace.png)
