### ISSUE TITLE
Campd Bulk Data Files Prod Issue

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5618]
## Context 

It looks like the bulk data files may not be updating in CAMPD. After looking into the issue the following is causing the problem: 

1) The .netcore 6 update seems to have changed the way dates are read so we are formatting the hourly and daily quarter file url’s with the wrong date format causing an error

2) The state file below was not regenerated because we do not see the Feb 24 submission record.

Based on discussion decision point will remediate this issue.

**Comment by alangmaid** [comment]
@tlageman-epa Circling back to confirm that this ticket is completely unrelated to [RT ticket #72708](https://rt.camdsupport.com/rt/Ticket/Display.html?id=72708). 

The RT ticket is related to the XML files generated by the legacy application, whereas this Zenhub ticket pertains to emissions files that are part of the CAMPD system. 

There will be traffic on RT related to 72708. The current status is that Mark H. is finishing up his work today and has been in contact with Dave G. to coordinate implementing the necessary changes tomorrow morning. The XMLs will likely start showing up in CAMPD this Friday.

**Comment by acollad1** [comment]
Kyle and Shahbaz fixed the view handling the .net core issue
