### ISSUE TITLE
Bug: QA Cert Import 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5619]
Issue: 
There is a backend error when importing a payload file into the QA Cert Events Module. Payload file attached to ticket 
User receives the below error

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUp5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ced3ea4abfa665ff1c23e7f8dba63e8f558a47b8/image.png)

Expected Results:
Users can successfully import into the cert/event module 

[payload.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd91aff593417904c21f955741b18bcfa43b9119/payload.txt)

**Comment by billmiller13** [comment]
The payload file attached to this ticket appears to be an out-of-date export as some fields do not match the current formatting.  Once those errors were fixed I was unable to reproduce the reported bug.  Closing this ticket as non-reproducible.
