### ISSUE TITLE
Bug: DailyFuelData, WeeklySystemIntegrityData, DailyBackstopData export file not consistent with import file

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5620]
## Context 
The 3 below sections need to be updated to reflect the import. When you export the data types listed below it is not consistent with the import file.   **When testing ensure you are testing the global and workspace.** 

- dailyFuelData
- weeklySystemIntegrityData
- dailyBackstopData

The following is being returned when you export dailyFuelData, weeklySystemIntegrityData, and dailyBackstopData. The items bolded need to be remvoed. 

"dailyFuelData": [
                {
                    "fuelCode": "PNG",
                    "dailyFuelFeed": 973714.2,
                    "carbonContentUsed": 73.4,
                    "fuelCarbonBurned": 714706.2,
                    **"monitoringLocationId"**: "3915"
                }
            ]

"weeklySystemIntegrityData": [
                {
                    "gasLevelCode": "HIGH",
                    "referenceValue": 5.5,
                    "measuredValue": 5.4,
                    "apsIndicator": 0,
                    "systemIntegrityError": 1.8,
                    **"monitoringLocationId"**: "TWCORNEL5-FE94F8D858344DF694EE4469D856A9E8"
                }
            ]

"dailyBackstopData": [
        {
            **"id**": "365",
            "unitId": "1",
            **"monitoringLocationId"**: "6",
            **"userId":** "jwhitehead",
            **"addDate": "**2023-08-18T03:08:39.374Z",
            **"updateDate":** "2023-08-18T03:08:39.374Z",
            **"reportingPeriodId":** 118,
            "date": "2022-04-01",
            "dailyNOxEmissions": 59309135,
            "dailyHeatInput": 28655730.9,
            "dailyAverageNOxRate": 646.935,
            "dailyNOxExceedence": 59309135,
            "cumulativeOSNOxExceedence": 74242895720
        }
]

### Requirements from original ticket #5403

Modify Emissions Export to support Reported Values Only #5403

Context
remove all the additional properties from the exports so that the exported data json exactly matches what would be imported

For testing:
go to postman and make a call to the emissions export endpoint
set reported values flag to true and the exported file should make the import schema

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by JanellC** [comment]
System export works as expected 

**Daily Fuel Data (Workspace Moss Landing 4A 2022 Q1)** 

{
					"fuelCode": "PNG",
					"dailyFuelFeed": 842342.3,
					"carbonContentUsed": 73.2,
					"fuelCarbonBurned": 616594.6
				}


**weeklySystemIntegrityData (Limestone worspace LIM1 2022 Q4)**

"weeklySystemIntegrityData": [
				{
					"gasLevelCode": "MID",
					"referenceValue": 5.8,
					"measuredValue": 3.4,
					"apsIndicator": 0,
					"systemIntegrityError": 41.4
				}


**weeklySystemIntegrityData (Barry offical 4  2021 Q3)**

"weeklySystemIntegrityData": [
				{
					"gasLevelCode": "HIGH",
					"referenceValue": 5.2,
					"measuredValue": 5,
					"apsIndicator": 0,
					"systemIntegrityError": 3.8
				}
**dailyBackstopData (Barry 1,2,CS0AAN 2022 Q4 workspace)** 

"dailyBackstopData": [
		{
			"unitId": "1",
			"addDate": "2023-10-14T18:50:22.000Z",
			"date": "2022-10-01",
			"dailyNOxEmissions": 65747201.9,
			"dailyHeatInput": 35998193.4,
			"dailyAverageNOxRate": 749.033,
			"dailyNOxExceedence": 6530069.8,
			"cumulativeOSNOxExceedence": 64053674784.1
		},
