### ISSUE TITLE
Add G2E program code to program filter in the custom data download tool

### ISSUE THREAD

**Issue by kstetsyuk** [US-EPA-CAMD/PI-1#5623]
## Context  

CAMPD Production issue. Add new program to the CDD. Adding the new program to swagger will be addressed in a seperate ticket. 

   "programCode": "CSOSG2E",

    "programDescription": "Cross-State Air Pollution Rule NOx Ozone Season Program Expanded Group 2",

    "compParameter": "NOX",

    "programGroupCode": "CSAPR",

    "programGroupDescription": "Cross-State Air Pollution Rule",

    "ozoneIndicator": true,

    "annualIndicator": false,

    "emissionsUIFilter": true,

    "allowanceUIFilter": true,

    "complianceUIFilter": false,

    "retiredIndicator": false,

    "tradingEndDate": null

**Comment by JanellC** [comment]
DPC will work on this issue. Whoever on DPC is fixing this issue will work with Jason W.

**Comment by tlageman-epa** [comment]
please coordinate with @jwhitehead77 . He is ready to assist and says this should be quick. if possible, i'd like for this to be completed today. please let me know when it is complete. thx

**Comment by shahbazkhan1999** [comment]
After discussion with @jwhitehead77 we are good to close out 5623 as the only table in production right now is the program code table and the other tables will be added with ecmps 2.0 but not yet in production
