### ISSUE TITLE
Add CSOSG2E code to program filter in APIs

### ISSUE THREAD

**Issue by tlageman-epa** [US-EPA-CAMD/PI-1#5625]
Add CSOSG2E program code to program filter in swagger production API pages to match the change made in the UI (see ticket #5623).

Link to swagger pages (https://www.epa.gov/power-sector/cam-api-portal#/documentation)

**Comment by hamezene** [comment]
This is left over work from Ticket 5623 - 

Clean Air markets API Portal - 

Match was was done on the previous ticket to the API

**Comment by shahbazkhan1999** [comment]
Need to discuss with @jwhitehead77

**Comment by shahbazkhan1999** [comment]
Need to discuss with @jwhitehead77

**Comment by shahbazkhan1999** [comment]
@tlageman-epa  you can test this

**Comment by tlageman-epa** [comment]
@shahbazkhan1999 there are a number of endpoints missing the CSOSG2E program code in the programCodeInfo filter of the swagger pages. I believe it is missing for the following after reviewing the dev swagger pages:
- All Streaming Services API endpoints except "Apportioned Hourly MATS Emissions" and "Emissions" where it is not applicable
- In the Facilities Management API the "facilities/attributes" endpoint. (I am not sure if the "workspace/facilities/attributes" also needs the update. I believe that is for ECMPS 2.0, so please check with CVP if it should be updated as the "facilities/attributes" endpoint or not and let me know. Thx!)
- In the Account Management API the "allowance-holdings", "allowance-transactions", "accounts/attributes", and "allowance-compliance" endpoints

Additionally, while I see it has been added to the Emissions Management API, it should be added in correct order. CSOSG2E should be added after CSOSG2 and before CSOSG3. Please make sure that order is followed in all the endpoints filters as well as parameter description of available values. Thanks and let me know if you have questions!

**Comment by shahbazkhan1999** [comment]
To complete ticket 5625 DPC/ERG made changes to the "easy-common" package that is used for CAMPD and ECMPS repos. These changes were made to a more recent version of the package than what is currently supporting CAMPD production (version 11) and according to Jason W. the more recent version of the package should not be deployed. To complete 5625 Jason is implementing the necessary changes to version 11, at which point DPC/ERG will move ticket 5625 to "Ready for Testing - UAT".

 like 1

**Comment by shahbazkhan1999** [comment]
@ergjustin 
 https://github.com/US-EPA-CAMD/easey-account-api/pull/154  please review this pull request and merge thanks!

**Comment by ergjustin** [comment]
@shahbazkhan1999 Resolve conflicts. Before you request a review from a reviewer, please make sure that your work meets the quality standards and follows the guidelines.

**Comment by ergjustin** [comment]
@shahbazkhan1999 
Staging testing result

Have CSOSG2E code
- [account-mgmt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6ba705e48ac01faed1ffd16da30d6729aabdb94/Swagger1.PNG)
- [streaming-services](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8250ad5dd5ce944bbfb3f0ad85b71fa30bd00418/swagger2.PNG)

- [facilities-mgmt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d0501a3275379b3ffe55ac0e76a3f6446b59b74/swagger3.PNG)

<hr>

<ins>**Missing**</ins>
CSOSG2E code is missing in emissions-api
- [emissions-mgmt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5865d847ca1ebbbff213ecac6eb1370e7aaa30b7/swagger4.PNG)

**Comment by ergjustin** [comment]
CSOSG2E code updated in emissions-api 
[emissions-api ](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5fcf6af5d15f3e5382f1e47d7ffc5668bbfb197/swagger5.PNG)

**Comment by tlageman-epa** [comment]
looks good!
