### ISSUE TITLE
Modify Get Relation Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5630]
After work was done to complete tickets 5603 and 5609, a needed change was identified for the getRelationships endpoint https://api-easey-dev.app.cloud.gov/master-data-mgmt/swagger/#/Relationships/RelationshipsController_getRelationships

- [x] UOM will need to be changed to unitsofmeasure

**Comment by mosesdeeCVP** [comment]
Defaults
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0RVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca4cc69a26867e5d9aa34e7196440d540adbbc5f/Defaults%20UOM.png)

Loads
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0hVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6448324f031355383afc9eb176fd000f8c3ccb32/Loads%20UOM.png)

Spans
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0xVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--708f0e5ae0299ca6cb10441e6b95a51f075a47fd/Spans%20UOM.png)

**Comment by mosesdeeCVP** [comment]
UOM has been updated to unitsofmeasure
