### ISSUE TITLE
UI: Implement New Layout/Format on Export Screen

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5631]
As an ECMPS user, I want a screen where I am able to select different types of data from a specific reporting period to export and/or view an associated report in order to support program goals

Given a user has navigated to the ECMPS application
When they look a the left-hand panel
Then they will see an option for the "Export/Report" screens

Given a user has navigated to the "Export/Report" screens via the left-hand panel
When they select a configuration on the initial screen
Then they will be able to open the configuration tab leading them to the main export/report page

- [x] Print Button will be added in the companion ticket 

- [x] The main export/report page layout will adhere to the design laid out in the below wireframe:

https://projects.invisionapp.com/freehand/document/TdahPfbEb?zoomToItems=Y2w0b2JldTBjMDA4aTNiN20yNWRha2tjMg%3D%3D

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2l1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19e278c94cc154b7f58a69b4791dfae89d41f124/Implement%20New%20Layout-Format%20on%20Export%20Screen%205631.png)

**Comment by mosesdeeCVP** [comment]
Updates have been made
