### ISSUE TITLE
Bug: MP Pop-out Scroll Bar

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5633]
Steps to Recreate:
Log into the ECMPS workspace
Go to the monitoring plan module
Open up a configuration
Select Monitoring Plan Systems
Open up System Components
User unable to use the internal scroll bar 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2lWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a63d95325ebb485bf14f5f9b7d259b77a1918806/image.png)

**Comment by cw-cvp** [comment]
[Fixes ](https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1261)for Systems pushed alongside changes for ticket [5650](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5650)

**Comment by mosesdeeCVP** [comment]
I am able to use the scroll bar to scroll through the System Components. Bug fixed
