### ISSUE TITLE
Spike: 508 Error Suppression Required Field

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5636]
Issue:
When attempting to Add, the left note blank. The modal was closed and user got an error message that note should not be null, undefined or empty. 2 issues with this per 508:
Required fields must be indicated they are required with either aria-required=true or an asterisk in the label. This occurs on other add/edit windows
The modal should not be closed and the values already entered should remain

- [ ] Need to review the application modals and log all the required fields. Then we will be able to apply error messaging within the modals so that users get an indication of what are the required fields without the modal closing/values being cleared out

**Comment by cw-cvp** [comment]
Add required condition to relevant input fields in AddErrorSuppressionModa.js and perform validation check after submission. If validation check passes then close modal
Or edit ErrorSuppression to use modalViewData and pass in arguments such as controlInput and mdmData.
