### ISSUE TITLE
508: Error Suppression Table Name

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5638]
Table does not have an accessible name

- [x] Need to put in an aria label

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0tXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--205c3e9ef8fa30a119b8c32e95efc47ea5189e66/image.png)

**Comment by aprematta** [comment]
Testing complete, the error suppression table no has a programmatic name
