### ISSUE TITLE
508: Error Suppression Check Box Labels

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5640]
Labels for the select checkboxes are generic, all have an aria label that says 'select'

- [ ] Add Record ID to check box label

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcStXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3515de5c1945d86af55139f691fd50f132f35b17/image.png)

**Comment by aprematta** [comment]
Testing complete, chekboxes now have unique aria labels
