### ISSUE TITLE
508: Error Suppression View/Clone/Deactivate Pop-out Focus

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5643]
When closing the View/Clone/Deactivate module, focus does not return to the View/Clone/Deactivate buttons

**Comment by aprematta** [comment]
In testing....  Add, Clone and Deactivate buttons have the focus correct.... but the View ones do not

**Comment by aprematta** [comment]
The view ones are now working, but the add, clone and deactivate buttons are going to the view buttons. Add needs to go to add, Clone to clone, etc.

**Comment by aprematta** [comment]
Focus is now working properly on all 4 buttons, closing ticket
