### ISSUE TITLE
Bug: Unable to Open Facilities

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5645]
Issue:

In global, logged-in, or local when a user tries to open a facility in any module they get a white screen. See screenshot below 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEdXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--78fc82e8834b86df5db693e3b86bec3e428ca7c7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbCtXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aac0dd1cd19c5d5a71c82d7e782026fef6712507/image.png)

**Comment by mosesdeeCVP** [comment]
Global
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm1nIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1c63bb76a7eea13364ce8214302e272a9fd914e/Unable%20to%20Open%20Facilities%20-%20Global.png)

**Comment by mosesdeeCVP** [comment]
Workspace
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnFnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5373adc27bdcc47e018fa994b2c1caa6b2a5931/Unable%20to%20Open%20Facilities%20-%20Workspace.png)

**Comment by mosesdeeCVP** [comment]
Bug has fixed
