### ISSUE TITLE
Add Record ID to Error Suppression Table

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5648]
## Context 

- [x] Add the record ID as a column to the error suppression table 
- [x] Additionally, there is  an issue with Error suppression page where when you select a facility name/ID field, a run time error is thrown because of the schema updates. See snippet blow - error is shown in console but does not crush the app, and instead does not enable user to select Location Name which is derived from facility selection.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakdZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--720464be2e126002f6bb566d9ab21fde5e942fab/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3loIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9e90bdf668d6ecf01da58903614dac71b984e928/Error%20Suppression%20table%20update.png)

**Comment by mosesdeeCVP** [comment]
Record Id was added to the Error Suppression table. There were no errors selecting the Location Name
