### ISSUE TITLE
Sonar Cloud Bug: QA Certification API 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5655]
- [ ] Remediate sonar cloud bug in QA certification API

https://sonarcloud.io/organizations/us-epa-camd/projects

- [ ] Resolving promises reference:
promises.push( new Promise((resolves, rejects) => {}) ) -> Needs to become promises.push(async function signature)

**Comment by hamezene** [comment]
@shahbazkhan1999 will do peer review

**Comment by bchofor** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cadb6bbe7ad79df85700259808b2c85cd54d296/image.png)


Sonar Cloud Bug: QA Certification API #5655 has been passed.
