### ISSUE TITLE
Bug: MP Export Error Handling 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5660]
Issue:
Currently the MP export error handling for when an incorrect monitor plan id is very unclear to the user what the error means and it was making it seem like the bug was never fixed:

"Cannot set properties of undefined (setting 'locations')"

- [ ] Change message to: "The reported monitorPlanId is invalid"

**Comment by esaber76** [comment]
Confirm if still a bug on dev and stg.

**Comment by alangmaid** [comment]
Unable to confirm this as an issue.
