### ISSUE TITLE
API: Evaluation and Submission Statuses

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5662]
As an ECMPS system, I need to make sure that the evaluation and submission statuses are updated appropriately on the backend so that all modules function properly

- [x] Need to make sure that whenever data is changed in any module [QA, MP, EM] on the backend the 

- Need Evaluation Flag is set to (Y)
- Evaluation Status Code is set to "EVAL"
- Submission Availability Code is set to "REQUIRE"

**Comment by mosesdeeCVP** [comment]
Was able to activate the Eval on all Sections

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb25HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--854280b2924f8a859cba231bcdee61dc0f5560dc/Evaluation%20and%20Submission%20Statuses%20MP%2C%20QA%20Test%20Data%20and%20QA%20Cert.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86fd9d0ff4ff80218996515de222390ea3d7546b/Evaluation%20and%20Submission%20Statuses%20EM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3ZHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eca80e8c2ea10f501620a8024de643f448c164e7/Evaluation%20and%20Submission%20Statuses%20TEE.png)
