### ISSUE TITLE
Add system alerts/notices to CAMPD (including Custom Data Download and Bulk Data pages)

### ISSUE THREAD

**Issue by tlageman-epa** [US-EPA-CAMD/PI-1#5664]
EPA or designated contractor should be able to manually enable or disable a USWDS style alert banner that would appear on all pages of CAMPD. If possible, the color of banner (https://designsystem.digital.gov/components/alert/) should be configurable by EPA staff. If not possible, the color should be blue. Also, the content of the alert banner should be customizable/editable by EPA staff using the content repo (https://github.com/US-EPA-CAMD/easey-content) similar to other content in CAMPD.

**Comment by shahbazkhan1999** [comment]
@ergjustin will research on this today and ask questions if have any.

**Comment by ergjustin** [comment]
@tlageman-epa 
May I know the position of the banner is okay or need to replace somewhere else?
At this position it will visible for all CAMPD pages.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlA3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19106bc7428032fba88d7edf97655b5c31795243/CAMPD-AlertBanner.PNG)

**Comment by tlageman-epa** [comment]
yes, that looks good. Will we be able to configure the style (color) of the banner? @ergjustin

**Comment by ergjustin** [comment]
@tlageman-epa  Yes, we can able to change the color, content, icon, heading from `easey-content`
| Variable| type    |     |
| :---:   | :---: | :---: |
| enable | Boolean   |    |
| type | String   | info, warning, error, success   |
|icon | Boolean | |
|content | String |  |
|slim | Boolean | |
|heading | String, Boolean | |
|headingLevel | String | h4, h3 |

**Comment by tlageman-epa** [comment]
great!

**Comment by ergjustin** [comment]
PR: https://github.com/US-EPA-CAMD/easey-content/pull/174 & https://github.com/US-EPA-CAMD/easey-campd-ui/pull/610

**Comment by ergjustin** [comment]
@shahbazkhan1999 I am just informing that easy-content PR was merged 
## Step to test

1. easey-campd-ui connect to easey-content locally using REACT_APP_EASEY_CONTENT_API
2. Change the value of /campd/data/alert-banner/index.json and test the changes of CAMPD UI

**Comment by ergjustin** [comment]
Changed the alert-banner path, now in dev/camps/alert-banner.json.

PR: https://github.com/US-EPA-CAMD/easey-content/pull/175 & https://github.com/US-EPA-CAMD/easey-campd-ui/pull/610

**Comment by shahbazkhan1999** [comment]
@bchofor test this on dev

**Comment by ergjustin** [comment]
Developer test in dev env
I enabled the alert banner in dev env by using easey-content
[Alert-Banner-dev-env](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0Z3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--049f7450cd038ff79b6265104e8d5cf078af0b6f/Alert-Banner-dev.PNG)

**Comment by tlageman-epa** [comment]
looks good in staging

**Comment by ergjustin** [comment]
production screenshot 
<img width="1898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5ZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c70385948529e31401f4556e20acdb8f908d9e6/banner.PNG" alt="banner.PNG" />
