### ISSUE TITLE
Modify Export Page Name in Navigation Panel

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5665]
Given a user is in the ECMPS application [official and workspace]
When the user looks at the navigation panel 
Then they will see an option for Export&Report

- [x] Export & Report option should be placed in the navigation panel as seen in the screenshot below 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzZ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2d063ccac2b27011284414bfbbf02dcd8840cff/image.png)

**Comment by subrataroyCVP** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ecmps-ui/assets/102534033/0d0abbfe-5a93-4bbf-87ab-22cfe28495df)

@Qb10 What about the Page title? Don't we need to change that?

**Comment by Qb10** [comment]
@subrataroyCVP ticket doesnt say anything about it so im not quite sure

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5de34d3a19e626b649fa86fd043fbdf2cc55e39/Export%20and%20Report%20Workspace.png)

**Comment by mosesdeeCVP** [comment]
Updates to the UI have been completed.
