### ISSUE TITLE
508: QA Maitenance Facility Name/ID

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5668]
- Facility Name/ID field not keyboard accessible

**Comment by subrataroyCVP** [comment]
This should be already resolved by [#5617](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5617)

Moving it to Ready for Testing.

**Comment by subrataroyCVP** [comment]
@aprematta Its Ready for Testing.

**Comment by aprematta** [comment]
Form is now keyboard accessible
