### ISSUE TITLE
RETEST 508: QA Maintenance Type label/Input

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5669]
- ID on Type label/Input is a duplicate ID

- [ ] Willl look into and verify with Anthony as needed
- [ ] Believe the issue is based on resolution and we are hiding/showing based on resolution

**Comment by aprematta** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/67421847/732df645-371c-4fb6-b276-ecc33d2aad73)

**Comment by aprematta** [comment]
Found the duplication in the html.... see screenshot. The duplicate id's are highlighted.

**Comment by JanellC** [comment]
@aprematta ticket is ready for testing

**Comment by aprematta** [comment]
Testing complete, there is no error for duplicate id's on this page anymore
