### ISSUE TITLE
RETEST 508: EM Submission Access Duplicate ID

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5675]
- ID on Reporting Period and Status is a duplicate ID
 - [ ] Willl look into and verify with Anthony as needed
 - [ ] Believe the issue is based on resolution and we are hiding/showing based on resolution

**Comment by aprematta** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/67421847/b8c731b6-2eb0-4298-95b9-44bf000852c1)

**Comment by aprematta** [comment]
found the duplication in the html. See screenshot with the highlighted id's

**Comment by JanellC** [comment]
@aprematta ticket is ready for testing

**Comment by aprematta** [comment]
Testing complete, there is no error for duplicate id's on this page anymore
