### ISSUE TITLE
508: EM Submission Access Pop Out Module Focus

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5678]
- When closing the View module, focus does not return to the View button
- When closing the Close module, focus does not return to the Close button
- When closing the Open module, focus does not return to the Open button
- When closing the Extend module, focus does not return to the Extend button
- When closing the Approve module, focus does not return to the Approve button

**Comment by aprematta** [comment]
Testing complete, focus order is now correct for all 5 buttons
