### ISSUE TITLE
508: EM Submission Access Pop Out Module Date Fields and Pickers

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5681]
Open Module:
- Date picker button labels are not unique, change to Toggle Calendar for ""
- Date fields look to be mislabeled, the output is the actual date instead of the text label such as 'Open Date)

Extend Module:
- Date fields look to be mislabeled, the output is the actual date instead of the text label such as 'Open Date)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWUwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84bed0f95d351d75278b2033eab3d494d2ae8fc0/image.png)

**Comment by aprematta** [comment]
testing complete, date fields and pickers are now appropriately labeled
