### ISSUE TITLE
Bug: Checkout Button on Configurations Page Missing

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5683]
Issue:

The checkout button is sometimes not visible on the configuration page in the logged-in view. When the user opens the configuration they see the checkout button in the workspace. In the logged-in view, the checkout button should always be visible on the configuration page for active configurations of any of the data type modules.

- [ ] This happens when you log in through the modal instead of the main homepage 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkxnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d0b1cd17b990fccf0c220e992b61554adbf2dcc2/image.png)

**Comment by fanwari1** [comment]
I cannot seem to link the ticket to the PR:

https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1287

**Comment by AmandaMNelson** [comment]
Works - can see Open & Checkout link when logging in through either the homepage or a modal.
