### ISSUE TITLE
Add Role Guard to Endpoints 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5687]
## Context 

Modify role guard to endoints to support admin checks. This is applicable to the error suppression endpoints. 

For testing: 
- Will need to coordinate with Kyle

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFg0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--966609e67f693e1148486c795367df7cbc0d3dfb/Add%20Role%20Guard%20to%20Endpoints%20%235687.png)

**Comment by mosesdeeCVP** [comment]
This guard is in place for all of the System Admin functionality.
