### ISSUE TITLE
Implementation Front End Error Handling 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5689]
This implementation ticket is an output of Spike ticket 5647 https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5647

 

- [x] Implement Error Boundary Component to handle the potential global errors

- [x]  Fall Back UI Error Message: "An error has occurred. If the problem persists please contact the help desk"

- [x]  https://designsystem.digital.gov/components/alert/

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakRVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c3a6afa034b358ae680d87b6e74212ab98300bc/Implementation%20Front%20End%20Error%20Handling.png)

**Comment by mosesdeeCVP** [comment]
Error is handled. Once the user closes the module the system returns the user back to the QA Cert Select Config page
