### ISSUE TITLE
Bug: Modify MP Export to support Only the Reported Values

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#5690]
There are a few more fields that need modification in MP.

(Further details will be added)

Original Ticket: [Modify MP Export to support Reported Values Only #5400](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5400)

**Comment by mosesdeeCVP** [comment]
Is it ok to have the field "active" for the below:
(The "active" is not available in the Import schema)

monitoringPlanCommentData
"analyzerRangeData"
"monitoringLocationAttribData"
"monitoringDefaultData"
"monitoringLoadData"
"rectangularDuctWAFData"
"monitoringFormulaData"
"monitoringLoadData"
supplementalMATSMonitoringMethodData
monitoringMethodData
monitoringQualificationData
monitoringSpanData
monitoringSystemData
monitoringSystemComponentData
monitoringSystemFuelFlowData
unitCapacityData
unitControlData
unitFuelData

**Comment by mosesdeeCVP** [comment]
This has extra fields that need to be removed
supplementalMATSMonitoringMethodData
 
Official:

                {
                    "id": "MELISSARHO-FD768B60E4D343158F7AD52EFD704D0E",
                    "locationId": "5770",
                    "supplementalMATSParameterCode": "TNHGM",
                    "supplementalMATSMonitoringMethodCode": "QST",
                    "beginDate": "2016-04-16",
                    "beginHour": 0,
                    "endDate": null,
                    "endHour": null,
                    "userId": "mmathews",
                    "addDate": "2016-02-23T19:39:14.000Z",
                    "updateDate": null,
                    "active": true
                },


Import example:


      "supplementalMATSMonitoringMethodData": [
        {
          "supplementalMATSParameterCode": "QST",
          "supplementalMATSMonitoringMethodCode": "TNHGM",
          "beginDate": "2016-04-28",
          "beginHour": 1,
          "endDate": "2020-04-28",
          "endHour": 23
        }

**Comment by mosesdeeCVP** [comment]
Why are these two so different:

Official Export:



            "unitCapacityData": [
                {
                    "id": "30396",
                    "unitRecordId": 65,
                    "commercialOperationDate": "1981-06-05",
                    "operationDate": null,
                    "boilerTurbineType": "T",
                    "boilerTurbineBeginDate": "1981-06-05",
                    "boilerTurbineEndDate": null,
                    "maximumHourlyHeatInputCapacity": 6858,
                    "beginDate": "1981-06-05",
                    "endDate": null,
                    "userId": "kbelknap",
                    "addDate": "2008-11-17T22:47:04.000Z",
                    "updateDate": "2009-01-23T20:24:14.000Z",
                    "active": true
                },


Import Schema example:

      "unitCapacityData": [
        {
          "maximumHourlyHeatInputCapacity": 2322.1,
          "beginDate": "2009-01-01",
          "endDate": null
        }

**Comment by mosesdeeCVP** [comment]
Official:

            "unitControlData": [
                {
                    "id": "16874",
                    "unitRecordId": 65,
                    "parameterCode": "PART",
                    "controlCode": "B",
                    "originalCode": "0",
                    "installDate": "2008-04-01",
                    "optimizationDate": "2008-06-15",
                    "seasonalControlsIndicator": "0",
                    "retireDate": null,
                    "userId": "kbelknap",
                    "addDate": "2008-11-17T22:47:04.000Z",
                    "updateDate": "2009-10-19T17:11:42.000Z",
                    "active": true
                }


Import example:

      "unitControlData": [
        {
          "controlCode": "SNCR",
          "originalCode": "0",
          "installDate": "2005-01-01",
          "optimizationDate": "2006-06-01",
          "seasonalControlsIndicator": "0",
          "retireDate": null,
          "parameterCode": "string"
        }

**Comment by mosesdeeCVP** [comment]
Official:

            "unitFuelData": [
                {
                    "id": "106",
                    "unitRecordId": 65,
                    "fuelCode": "C",
                    "indicatorCode": "P",
                    "ozoneSeasonIndicator": 0,
                    "demGCV": null,
                    "demSO2": null,
                    "beginDate": "1990-11-15",
                    "endDate": null,
                    "actualOrProjectCode": "A",
                    "sulfurContent": null,
                    "userId": "PQAQ4",
                    "addDate": "2008-11-17T22:47:04.000Z",
                    "updateDate": null,
                    "active": true
                }

Import example:

      "unitFuelData": [
        {
          "fuelCode": "C",
          "indicatorCode": "P",
          "ozoneSeasonIndicator": 0,
          "demGCV": "GGC",
          "demSO2": "SGC",
          "beginDate": "1995-01-01",
          "endDate": "2015-03-30"
        }

**Comment by JanellC** [comment]
@jeffreyaggrey @mosesdeeCVP Please coordinate and provide an estimate on this bug.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
<img width="996" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0b70b6beb4a1d1c4e9ae2605fc5ddd5b28b0399/supplementalMATSMonitoringMethodData.png" alt="supplementalMATSMonitoringMethodData.png" />

**Comment by mosesdeeCVP** [comment]
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6526469c5a1b8658f81aa5b2051a9e10ec8439ea/unitCapacityData.png" alt="unitCapacityData.png" />

**Comment by mosesdeeCVP** [comment]
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9ffc8d2244e9e8552a97af9b256a29f3bac6ae1/unitControlData.png" alt="unitControlData.png" />

**Comment by mosesdeeCVP** [comment]
<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ffe905ae74f2e14eb6aea699a6ff4b9f6b00001/unitFuelData.png" alt="unitFuelData.png" />

**Comment by mosesdeeCVP** [comment]
Updates have been made successfully
