### ISSUE TITLE
Bug: MP System Components 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5691]
Issue:

When a user navigates to MP either in global or logged in. When the user selects systems and opens it up the whole component does not load:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczI3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81f60a313e5a1175cc790e9de89e4f4060aaa017/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEM3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--70f650e6099d9be3ccbbf4070413f664be37c292/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0M4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ccd273989df38266620deb13ccff87bc6692414/System%20Components.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEc4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57f62a3f904bbb9411ad62f76577042498f92888/System%20Components%20Workspace.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
