### ISSUE TITLE
Bug: MP Qualifications Horizontal Scroll Bar

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5692]
Issue:
The horizontal scroll bar in the MP qualification section pop-out is not working. Clicking on it is not working, but the shift scroll wheel currently works

**Comment by mosesdeeCVP** [comment]
Original Ticket: Bug: [Monitoring Plan Qualifications Scroll Bar #5650](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5650)

**Comment by mosesdeeCVP** [comment]
All MP Qualifications Horizontal Scroll Bars work as expected.
