### ISSUE TITLE
BUG: Transaction Records missing from CAMPD data outputs

### ISSUE THREAD

**Issue by tlageman-epa** [US-EPA-CAMD/PI-1#5694]
As a result of new programmatic actions, two new transaction types were created and used. However, the associated transaction records are not returning in CAMPD's data outputs (APIs and Custom Data Download Tool Queries). Potentially the transaction types need to be added to the database so they are returned in the output, but it is unclear if that is the reason why they aren't returning. This is a production issue and needs to be addressed immediately. @ergjustin @shahbazkhan1999 

The following transaction type codes and descriptions are:
•	REMGNP (Remove for Good Neighbor Plan Reissuance)
•	REISGNP (Distribute Revintaged Allowances for Good Neighbor Plan)

We should be seeing in the data the following transaction types for the conversions performed on 9/19:
•	“Remove for Good Neighbor Plan Reissuance” transaction type of 2017-2022 CSOSG2 allowances from a bunch of facility and general accounts to CSAPR Retirement for Reissuance Account (CSAPR0000310)
•	“Remove for Good Neighbor Plan Reissuance” transaction type of 2021-2022 CSOSG3 allowances from KY and LA facility accounts to CSAPR Retirement for Reissuance Account (CSAPR0000310)
•	“Distribute Revintaged Allowances for Good Neighbor Plan” transaction type of 2023 CSOSG3 allowances from CSAPR Revintage Account (CSAPR0000005) to a bunch of facility and general accounts
•	“Distribute Revintaged Allowances for Good Neighbor Plan” transaction type of 2023 CSOSG2E allowances from CSAPR Revintage Account (CSAPR0000005) to KY and LA facility accounts

**Comment by tlageman-epa** [comment]
@ergjustin @shahbazkhan1999  please coordinate with @jwhitehead77 as to why this wouldn't be returning in CAMPD. thx!

**Comment by tlageman-epa** [comment]
@shahbazkhan1999 @ergjustin I just emailed Hiwot, but I wanted to emphasize that all other work should be paused until this is remedied. I will be available from 3 - 4:30pm and am OOO tmrw.

**Comment by shahbazkhan1999** [comment]
resolved the issue
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnJHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0ed2acccc8032d5c90b2144ca82c52629b872b40/image.png)
