### ISSUE TITLE
Bug: Unable to Import

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5695]
Issue:

While regression testing in the testing environment it was observed that users were unable to import a monitoring plan that was exported from the workspace 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3ZEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a084e80f788738df5eb34b3a656f2641c88b506e/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0RNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55f086f6a7e54c345b20975213131c70a56cd164/Import%20Monitoring%20Plan%20Data%201.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0hNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b690c3f6ce09d52274ae3af8a0a904df622a6c47/Import%20Monitoring%20Plan%20Data%202.png)

**Comment by mosesdeeCVP** [comment]
Bug is fixed
