### ISSUE TITLE
Add locationName to Apportioned Emissions HOUR_UNIT_DATA

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5696]
Add the ability to sort based on locationName to streaming-services hourly emissions endpoint

**Comment by JanellC** [comment]
/streaming-services/emissions/apportioned/quarterly endpoint does not have a location name filter

**Comment by JanellC** [comment]
The hourly emissions streaming endpoint contains a location name filter and a user can filter by the location
