### ISSUE TITLE
RETEST Bug: MP Schema and DTOs

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5698]
While testing ticket #5628 a few issues have been found that need to be addressed:

There are some discrepancies between the excel and Reporting Document (**SPAN-3**). 

- [ ] The excel says must be within the range of 0 and 9999999999. The reporting document says must be within the range of 500000 and 9999999999. The current error message says this as well. I believe the schema example and excel need to be updated to reflect the document.
 monitoringSpanData > mpfValue
**_[Jason W] Separated into ticket #5702_** Note: This ticket has been **closed**.

- [ ] ["monitoringLocationData.0.rectangularDuctWAFData.0.[DEFAULT-80-D] - The [wafValue] for [Rectangular Duct Waf] is not within the range of valid values.  This value must be greater than 0 and less than 1." ],
Excel: Min 0 - Max 99.9999
**_[Jason W] correct excel/schema/dto to allow min 0 & max 1_**
**_[Ann] Separated into ticket #6029_** 

- [ ] Error message is not appropriate for error. It is correct for negative, but not larger than acceptable amount of digits. Also does not show what the user is expected to enter:
 monitoringSystemFuelFlowData > maximumFuelFlowRate
**_[Jason W] need more context on this one and please provide the error_**

**Comment by acollad1** [comment]
Pending schema updates so will need to retest after

**Comment by esaber76** [comment]
Confirm if still a bug on dev and stg.

**Comment by alangmaid** [comment]
@lgiannini1 please test to determine if 3rd reported issue persists. If it does, create new ticket and close this one.

**Comment by lgiannini1** [comment]
Third issue still exists on dev and tst. Created ticket #6240 and closing this ticket.
