### ISSUE TITLE
Review Emissions Data Model and Relationships with ERG 

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#57]
- [x] Meet internally to determine questions to send to ERG
- [x] Meeting with ERG to understand emissions data relationships

**Comment by jwhitehead77** [comment]
Meet with ERG for overview of data model and nightly ETL jobs.

See documentation here
https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/AMPD/Data%20and%20Databases/AMPD%20Data%20Overview.docx?d=wda62e369c03743229a6be9590b5ae0e0&csf=1&web=1&e=8cjfEu
