### ISSUE TITLE
STORY: Validate date range for hourly apportioned emissions

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#570]
## User Story
As a user I want to be able to enter valid filter criteria for date so that I can see results

## Acceptance Criteria
Given that a user has entered valid filter criteria for date (see below)
When the API endpoint is executed
Then the system validates the criteria and displays the results

Given that a user has entered a date is not in the format YYYY-MM-DD
When the API endpoint is executed
Then the system displays an error message (FV-5)

Given that a user has entered a date is not valid  (example: 2015-15-45)
When the API endpoint is executed
Then the system displays an error message (FV-11)

Given that a user has entered a date range where the end date is not equal to or greater than start date
When the API endpoint is executed
Then the system displays an error message (Fv-6)

Given that a user has entered a year is outside of range
When the API endpoint is executed
Then the system displays an error message (FV-7

Given the system has detected any error conditions for date
When the error messages are returned
Then the system returns the first encountered error message

- Format
- Valid date
- Everything else

## Testing
Test Case: [TC69](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268891)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R16](https://cvpcorp.testquality.com/project/11428/testcase/268891/requirement/11058). Do not remove or edit.

**Comment by sdhawan16** [comment]
@tlageman-epa Added Dev Tasks: #600 and #602

**Comment by david-cvp** [comment]
TC69 passes
