### ISSUE TITLE
Campd Bulk Data Files Prod Issue

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5701]
It looks like the bulk data files may not be updating in CAMPD. After looking into the issue the following is causing the problem:

The state file below was not regenerated because we do not see the Feb 24 submission record.

- Upon further investigation: dm_emission records are not being updated correctly from the informatica process. This is currently being looked into from the informatica side. These dm_emissions records are what drives the file generation. 

- [ ] Related to ticket 5618

**Comment by tlageman-epa** [comment]
@shahbazkhan1999 if you haven't already, can you reach out to the informatica team to find out what the latest is ahead of our meeting this afternoon? I'd like to see how soon we can resolve this, and make sure the informatica team knows that this is a prod issue so we want to resolve it asap. thx!

**Comment by jwhitehead77** [comment]
Vamshi, Shabaz, and I truncated the dm_emissions table and reloaded it 9/29/2023 to sync the data between oracle and coud.gov. The bulk files that needed to be regenerated were completed that night after the nightly runs.
