### ISSUE TITLE
Modify MP Schema & DTO validation for Spans

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5702]
Pulled in from ticket #5698

While testing ticket #5628 a few issues have been found that need to be addressed:
There are some discrepancies between the excel and Reporting Document (SPAN-3). 

- [x] The excel says must be within the range of 0 and 9999999999.999. The reporting document says must be within the range of 500000 and 9999999999. The current error message says this as well. I believe the schema example and excel need to be updated to reflect the document.

Modify schema and DTO validation to allow span_value to have a min value = 0 and max value = 9999999999.999. Checks may limit the min and max value based on component type.

Here are the counts in production and there are records less than 500,000
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG5OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--46cb07bbb3d53c12d9cc0743fca2c94c9667d0a1/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGpwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b6a07e45aaf8eb9f06d04250ffc623e901f57dd4/MP%20unitsofStandard%20Test.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2JwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b97829632b5174755fec9fc9aa626d3a7bd8a2c8/spanValue.png)

**Comment by mosesdeeCVP** [comment]
spanValue has been updated.
