### ISSUE TITLE
Modify QA Schema & DTO validation to allow negative values

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5703]
The following tables contain existing data with negative values so we need to modify excel/schemas/dtos to allow negatives. The min value should match the max value but allow negative.

CALIBRATION_INJECTION		ZERO_REF_VALUE
CALIBRATION_INJECTION		UPSCALE_CAL_ERROR
CALIBRATION_INJECTION		UPSCALE_MEASURED_VALUE
CALIBRATION_INJECTION		ZERO_MEASURED_VALUE
CYCLE_TIME_INJECTION		        BEGIN_MONITOR_VALUE
CYCLE_TIME_INJECTION		        END_MONITOR_VALUE
FLOW_RATA_RUN				PERCENT_MOISTURE
FUEL_FLOWMETER_ACCURACY	MID_FUEL_ACCURACY
FUEL_FLOWMETER_ACCURACY	HIGH_FUEL_ACCURACY
FUEL_FLOWMETER_ACCURACY	LOW_FUEL_ACCURACY
FUEL_FLOW_TO_LOAD_CHECK	AVG_DIFF
HG_TEST_INJECTION			MEASURED_VALUE
LINEARITY_INJECTION			MEASURED_VALUE
LINEARITY_SUMMARY			MEAN_MEASURED_VALUE
LINEARITY_SUMMARY			PERCENT_ERROR
ON_OFF_CAL					ONLINE_ZERO_MEASURED_VALUE
ON_OFF_CAL					ONLINE_UPSCALE_MEASURED_VALUE
ON_OFF_CAL					OFFLINE_ZERO_MEASURED_VALUE
RATA_RUN					CEM_VALUE
RATA_RUN					GROSS_UNIT_LOAD
RATA_RUN					RATA_REF_VALUE
RATA_SUMMARY				MEAN_DIFF
RATA_SUMMARY				AVG_GROSS_UNIT_LOAD
RATA_SUMMARY				STND_DEV_DIFF
RATA_TRAVERSE				CALC_VEL
RATA_TRAVERSE				PITCH_ANGLE
RATA_TRAVERSE				AVG_SQ_VEL_DIFF_PRESSURE
RATA_TRAVERSE				YAW_ANGLE

NOTE: Audit spreadsheet has been updated with green highlight cells

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
7DAY
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1B4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99ff8d8f8e7e017ef278d48a75adfa7a1419c887/7DAY.png)

**Comment by mosesdeeCVP** [comment]
CYCLE
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzd4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc8f888bcce00b1ee903138ee5f8712e1d0c2d26/CYCLE.png)

**Comment by mosesdeeCVP** [comment]
FLOW RATA
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcER4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--252a403f3e7dce5cfc7ce59d7af7b765fcbc7915/RATA%20FLOW.png)

**Comment by mosesdeeCVP** [comment]
FFACC
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHp4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0edd23c12c16e9ab93ab86e162d61803a9bdcc68/FFACC.png)

**Comment by mosesdeeCVP** [comment]
FF2LTST
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXJ4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89a5d9f10e8a010247948f716fe8a0bf9fff6196/FF2LTST.png)

**Comment by mosesdeeCVP** [comment]
HGLINE 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--197d32ee732eb90aad4e9842a434ca9d812003d8/hgInjectionData.png)

**Comment by mosesdeeCVP** [comment]
LINE
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnp4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73f73671fb3ea50fcd9ce5d08499b5eadda0522e/LINE.png)

**Comment by mosesdeeCVP** [comment]
ONOFF
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ255IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d06c418e8f11f1d2e91fcaf883f997ec4504eb2/ONOFF.png)

**Comment by mosesdeeCVP** [comment]
RATA

Under RATA> rataSummaryData > rataRunData> (CEMValue & RATAReferenceValue) I am able to add any amount of decimals

Under RATA> rataSummaryData > (meanDifference & standardDeviationDifference) I am able to add any amount of decimals

There is a bug that is out of our control due to a bug in the package/library that allows more that the allotted decimal places. The coding logic is in place if and when the package/library is updated.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8595536b2c356e6bf561c5198e8df1fd1dcc6e24/RATA%20cemValue%20-%20rataReferenceValue%20-%20meanDifference%20-standardDeviationDifference.png)

**Comment by subrataroyCVP** [comment]
**Checks have modified, need regression testing for these following checks: ⬇️**

- RATA-26
- RATA-27
 - RATA-28
- LINEAR-18
- RATA-130

** Checks will only be fired on POST and PUT endpoints. When imported these checks should not be fired, Any errors should be caught by Check Engine.

**Comment by subrataroyCVP** [comment]
`HgInjection` and `UnitDefaultTestRun` dto validations/checks was not firing at all. Please test all the checks for these.

**Comment by mosesdeeCVP** [comment]
Updates have been completed
