### ISSUE TITLE
vm2 Sandbox Escape vulnerability- Dependabot 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5707]
## Context 

Critical dependabot issue 

https://github.com/US-EPA-CAMD/easey-camd-services/security/dependabot/40

https://github.com/US-EPA-CAMD/easey-camd-services/security/dependabot/39

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaS9jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5ee75ea69e32e1f3aa362d957c329ad4698af31/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakxjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79578568ec9a0930a4a7f9548d1552b98b4f7c51/image.png)

**Comment by jwhitehead77** [comment]
no patch available at this time

**Comment by JanellC** [comment]
Duplicate of (Critical) vm2 Sandbox Escape vulnerability #5816. DPC will remediate
