### ISSUE TITLE
@nestjs/core vulnerable to Information Exposure via StreamableFile pipe #22

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5708]
## Context 

Moderate dependabot issue 

https://github.com/US-EPA-CAMD/easey-camd-services/security/dependabot/22

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanZjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9bddeb6b2036f600b69a741d0ef6c190cb3950bf/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanpjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--449a8b4d73fb4c12c656185234f0d10139ec4209/image.png)

**Comment by annalbrecht** [comment]
Has been resolved.
