### ISSUE TITLE
graphql Uncontrolled Resource Consumption vulnerability

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5709]
## Context 
Moderate dependabot issue 

https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot/53

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0xjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a6339e7f9a747e9fba7e3864f6630bd472eaf914/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1RjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--42f1f377f5f7f03439e374d12b2dcaf8843010ba/image.png)

**Comment by jwhitehead77** [comment]
no longer showing up or has been resolved
