### ISSUE TITLE
STORY: Validate ORIS code for hourly apportioned emissions

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#571]
## User Story
As a user I want to be able to enter valid filter criteria for ORIS code so that I can see results

## Dev Tasks
- [x]  Create custom validation pipe
- [x] Transform data in DTO
- [x] Add validation header in DTO

## Acceptance Criteria
Given that a user has entered valid filter criteria for ORIS code (see below)
When the API endpoint is executed
Then the system validates the criteria and displays the results

Given that a user has entered invalid filter criteria for ORIS code (see below)
When the API endpoint is executed 
Then the system returns a validation error collection (FV-9):
"ORIS code not valid. Refer to the list of available ORIS codes for valid values [placeholder for link to Facilities endpoint]"

ORIS code format:
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits
no leading 0s (EX: 000670 in valid, 67000 is valid)

## Testing
Test Case: [TC70](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268892)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R17](https://cvpcorp.testquality.com/project/11428/testcase/268892/requirement/11059). Do not remove or edit.

**Comment by sdhawan16** [comment]
@tlageman-epa Added dev task #605

**Comment by sdhawan16** [comment]
Added validation pipe and validation and transformation headers for orisCode in DTO
Need to check if number should be positive integer or generic number before creating PR

**Comment by sdhawan16** [comment]
Changed acceptance criteria to say valid format is "**positive whole** numeric value of no more than 6 digits"
Created PR

**Comment by david-cvp** [comment]
TC70 passes
