### ISSUE TITLE
@adobe/css-tools Regular Expression Denial of Service (ReDOS) while Parsing CSS

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5710]
## Context 

https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot/52

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2ZjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d5dbe4e304bffd4daffda0433654122cd29a8901/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2pjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da0ad18e6c3225e1239d6675ef753e275230a622/image.png)

**Comment by jwhitehead77** [comment]
no longer showing up or has been resolved
