### ISSUE TITLE
Bug: MP View Fuel Flow

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5711]
Issue: 
The system does not display a view modal for fuel flow

Steps to Reproduce:
Navigate to MP Module In global
Select Barry 1,2,CS0AAN
Select systems from the dropdown
Select view
Scroll down
View a fuel flow record
Nothing happens and  the system does not display a fuel flow modal

Note: Confirmed this happened in the global and workspace views

- [ ] Suspect that this is a prefilter MDM endpoint issue

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3da1bade136ebddbde8397d7a05550bb98de1ba2/image.png)

**Comment by cw-cvp** [comment]
MDM endpoint getRelationships for code system-fuel-flows now returns unitsOfMeasure instead of UOM

**Comment by AmandaMNelson** [comment]
Can View Fuel Flow in Global and Workspace 
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/79f15cfb-4967-4f92-bb92-6fc1fc32d444)
