### ISSUE TITLE
Bug: QA UI Calendar Icon Cutoff

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5712]
Issue:
Test Summary module calendar icon is cut off 

Steps to Recreate:
Log in
Check out a facility (exGlen Lyn (3776) 51)  under Test Data
Select any test type 
Add a test summary record 
The calendar icon is cut off 

- [x] Testing note: Screen Resolution should be 1024

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3pnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--14fc0f51fd08cc3a3ab9582404e483a4603811ae/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVF0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed6af503f4f9017a499ca4a8c947e7f8167b5ac7/Add%20Test%20Summary%20Data%20Calendar.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
