### ISSUE TITLE
Investigate and Remediate Bug: QA Cert and TEE

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5714]
Issue:
Unable to complete CRUD activity of the QA Cert and TEE functionality
500 Internal Server Error / Does not show up in the UI. The UI does nothing to show the error. This needs to be fixed in addition to the CRUD error problems
Steps to Recreate:
Select a Facility > Select in the left-hand side under Cert Event and TEE. Open and Checkout Config. Add or edit QA Cert or TEE

- [ ] Reach out to Alex if this is verified so that we can get a ticket in and estimation for resolution

**Comment by subrataroyCVP** [comment]
Due to schema change, property name mismatched in entity and dto, throwing the 500 error from DB.

Increasing the Estimate to 2 work on the fix for the Bug.

**Comment by AmandaMNelson** [comment]
Can Add and Edit
