### ISSUE TITLE
Bug: MP Qualification LEE Unit of Standard Error

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5720]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d6b461cb8f8754894e303aa3b99ccb13493ffa5/image.png)

Issue:

The below file caused the above error

 "id": "MDC-06E0EF07C31F490581112B509CE336A1",
    "facId": 16,
    "facilityName": "Cholla",
    "configTypeCode": null,
    "lastUpdated": "2023-05-30T18:52:38.417Z",
    "updatedStatusFlag": "Y",
    "needsEvalFlag": "N",
    "checkSessionId": "1752b612-6662-77f8-e970-2889209d5a95",
    "orisCode": 113,
    "name": "4",
    "beginReportPeriodId": 9,
    "endReportPeriodId": null,
    "active": true,
    "monitoringPlanCommentData": [],
    "pendingStatusCode": null,
    "evalStatusCode": null,
    "unitStackConfigurationData": [],
    "reportingFrequencies": [
        {
            "id": "MDC-B0CD0DBA5D46402B938482E2A3AF5767",
            "reportFrequencyCode": "Q",
            "beginReportPeriodId": 9,
            "endReportPeriodId": null,
            "userId": "kbelknap",
            "addDate": "2009-01-23T20:24:47.000Z",
            "updateDate": null
        }
    ],
    "monitoringLocationData": [
        {
            "id": "116",
            "unitRecordId": 65,
            "unitId": "4",
            "stackPipeRecordId": null,
            "stackPipeId": null,
            "name": "4",
            "type": "unit",
            "active": false,
            "activeDate": null,
            "retireDate": null,
            "nonLoadBasedIndicator": 0,
            "monitoringLocationAttribData": [],
            "unitCapacityData": [],
            "unitControlData": [],
            "unitFuelData": [],
            "monitoringMethodData": [],
            "supplementalMATSMonitoringMethodData": [],
            "monitoringFormulaData": [],
            "monitoringDefaultData": [],
            "monitoringSpanData": [],
            "rectangularDuctWAFData": [],
            "monitoringLoadData": [],
            "componentData": [],
            "monitoringSystemData": [],
            "monitoringQualificationData": [
                {
                    "id": "07a09fa9-8c4e-44b2-8821-a21ad099a335",
                    "locationId": "116",
                    "qualificationTypeCode": "COMPLEX",
                    "beginDate": "2023-05-25",
                    "endDate": "2023-05-30",
                    "userId": "mddee-dp",
                    "addDate": "2023-05-25T18:35:49.727Z",
                    "updateDate": "2023-05-30T18:52:15.000Z",
                    "active": false,
                    "monitoringQualificationLEEData": [],
                    "monitoringQualificationLMEData": [],
                    "monitoringQualificationPercentData": [],
                    "monitoringQualificationCPMSData": []
                },
                {
                    "id": "bbb1dbd6-26e8-4e8e-b919-49ff0884b538",
                    "locationId": "116",
                    "qualificationTypeCode": "GF",
                    "beginDate": "2023-05-30",
                    "endDate": null,
                    "userId": "mddee-dp",
                    "addDate": "2023-05-25T18:35:40.923Z",
                    "updateDate": "2023-05-30T18:52:38.000Z",
                    "active": true,
                    "monitoringQualificationLEEData": [
                        {
                            "id": "5155724e-12db-498f-9256-9c371ba3fbc0",
                            "qualificationId": "bbb1dbd6-26e8-4e8e-b919-49ff0884b538",
                            "qualificationTestDate": "2023-05-24",
                            "parameterCode": "HCL",
                            "qualificationTestType": "INITIAL",
                            "potentialAnnualMassEmissions": 1,
                            "applicableEmissionStandard": 37,
                            "unitsofStandard": "LBMMBTU",
                            "percentageOfEmissionStandard": 76.8,
                            "userId": "mddee-dp",
                            "addDate": "2023-05-25T17:52:25.000Z",
                            "updateDate": "2023-05-25T18:12:06.000Z"
                        }
                    ],
                    "monitoringQualificationLMEData": [],
                    "monitoringQualificationPercentData": [],
                    "monitoringQualificationCPMSData": []
                }
            ]
        }
    ],
    "userId": "kherceg-ds",
    "addDate": "2008-11-17T23:35:27.000Z",
    "updateDate": "2023-07-31T18:26:55.000Z",
    "submissionId": 1339443,
    "submissionAvailabilityCode": "UPDATED",
    "lastEvaluatedDate": "2023-07-31T18:08:05.665Z"

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDdwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc79a66cbff5d00958bd61b116e2cf66d7b6547d/MP%20unitsOfStandard%20Test.png)

**Comment by mosesdeeCVP** [comment]
The API has been updated, Import, Export and UI. Bug is fixed
