### ISSUE TITLE
Implement Logging Error Stack Trace

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5721]
- [ ] When the run-a-time code error occurs the error boundary should be sending the error stack to a logging service, but this is currently not happening. Need to implement this response.
- [ ] Additionally, when the error occurs we want a unique identifier for the error so that we can trace it back that will be displayed to the user

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/ded18d44-6fae-46e4-b76a-cd4fcc684664)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/888c0ebd-e3e8-415a-8048-8c020cab59a0)
