### ISSUE TITLE
log data from production is not draining to Splunk

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5722]
log data from production is not draining to Splunk from some of the production applications.  It looks like the log drain service was unbound from the apps with the new deployment.  We need to rebind the service and restart the apps

There were 3 apps that the change stack did not work for and we had to delete and redeploy using the existing package which did not have the log-drain service bound in the manifest since it was not there at the time of that deployment. We just need to use the cf cli to bind it back at this point but we also need to update the manifest file to bind the log drain service  in all the apps or this will happen again

Here are the commands to run on production environment to restart services

cf bind-service emissions-api log-drain
cf bind-service facilities-api log-drain
cf bind-service account-api log-drain
cf bind-service camd-services log-drain
cf bind-service streaming-services log-drain
cf bind-service campd-ui log-drain
cf bind-service facility-map log-drain

**Comment by shahbazkhan1999** [comment]
@jwhitehead77 I've run all the commands on the production environment to restart services can you please check now

**Comment by jwhitehead77** [comment]
@shahbazkhan1999 I have verified that the log drain service has been rebound to the apps listed above

**Comment by hamezene** [comment]
@tlageman-epa @maheese All commands have been run on Prod, Please verify

**Comment by maheese** [comment]
@hamezene working as expected.  Go ahead and close.
