### ISSUE TITLE
Add shutdown language into the RT auto-reply for the CAMPD support

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5723]
This ticket is to add a shutdown language in bold into the RT auto-reply for the CAMPD support. 

Greetings,

This message has been automatically generated in response to the creation of a trouble ticket regarding Webform submission from: Contact Us About Clean Air Markets Program Data, a summary of which appears below.

There is no need to reply to this message right now. Your ticket has been assigned an ID of [CAMPD Support ######].

**Due to the shutdown, some tickets may not be acted on until the government reopens. We appreciate your understanding during this time and would like to remind you of CAMPD’s additional Help/Support resources. The Data Glossary defines all data fields by data type, FAQs provide answers to common questions, and Tutorials includes data guides and other resource documents.**

Please include the string [CAMPD Support ######] in the subject line of all
future correspondence about this issue. To do so, you may reply to this
message.

Thank you,
campd-support@camdsupport.com

**Comment by tlageman-epa** [comment]
This ticket can be closed and labeled invalid as the shutdown is no longer happening.

**Comment by esaber76** [comment]
No action taken. Shutdown averted.
