### ISSUE TITLE
Bug: Evaluate Critical Error Adjusted Value

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5731]
Issue: When a user logs in, imports from a historical file back, and then evaluates the user receives critical errors regarding the adjusted value
Steps to Recreate:
Log in 
Import form historical Q4 2022 Limestone
Evaluate the file
User gets critical errors regarding adjusted value

Link to evaluation report:
https://ecmps-tst.app.cloud.gov/reports?reportCode=EM_EVAL&facilityId=298&monitorPlanId=MDC-D4D7F122FD8F488F8B09A87DF926020E&year=2022&quarter=4

**Comment by jwhitehead77** [comment]
#5731, #5732 and #5759 are all the same problem where adjustedHourlyValue was not being read in on import. These have all been addressed with changes from #5759

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b6fb64ee308bfb5c9cc1c173f3a28fc62a70bb4/Evaluate%20Critical%20Error%20Adjusted%20Value%20%235731.png)

**Comment by mosesdeeCVP** [comment]
Evaluated without Critical Error
