### ISSUE TITLE
Test Only: Evaluate Critical Error Op Supp Data record 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5733]
Issue: When a user logs in, imports from a historical or file, and then evaluates the user receives critical errors: "the Op Supp Data record for this parameter is missing"
Steps to Recreate:
Log in
Import form historical or file 2022 Q2/3 Potter
Evaluate the file
User gets critical errors regarding Op Supp Data record missing 

Link to the evaluation report
https://ecmps-tst.app.cloud.gov/reports?reportCode=EM_EVAL&facilityId=1660&monitorPlanId=MDC-CBB6D71CA2224D999CC764C6771F4BA4&year=2022&quarter=2

**Comment by jwhitehead77** [comment]
I have tested this out in both dev and test and not seeing these errors anymore. We fixed the procedure that was deleting supplemental data when importing emissions files.

**Comment by mosesdeeCVP** [comment]
Have not gotten any Critical Errors. I got Informational Message after evaluating.
