### ISSUE TITLE
Bug: QA Cert Event Dropdown

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5736]
Issue:
 The Add/Edit "QA Cert Event Code" dropdown is not populating (or rather, it's populating with a bunch of blank, unreadable selections)

This is because the master data property has changed and the UI needs to be updated to match 

Steps to Reproduce:
Navigate to QA Cert Event, Extensions, & Exemptions on left-hand menu
Open & Check Out a Configuration (found bug with Ocotillo Power Plant, GT6)
Click Add button or Edit button next to a Cert Event
Click to expand QA Cert Event Code dropdown

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ed296f071586d36f61b11952d688386120af990/QA%20Cert%20Event%20Code%20available%20in%20UI.png)

**Comment by mosesdeeCVP** [comment]
QA Cert Event Code dropdown works as expected
