### ISSUE TITLE
Re-Test: QA Import

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5737]
Issue
When importing from a historical file user receives the below error:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlg4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--78ebbb122098bf162807d0d0d5a46bab1137d0df/image.png)
Steps to Recreate

EC Gatson 2022 Q2

**Comment by jwhitehead77** [comment]
Not able to reproduce and I imported from historical all 2022 Q2 tests for all 3 mp's under EC Gaston and was able to evaluate them.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
No import errors. System works as expected
