### ISSUE TITLE
Bug: QA Import from Historical [EC Gaston]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5738]
When trying to import from historical E C Gaston 2022 Q2
5, MS5A, MS5B2022 Q2 user gets the below error

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVQ5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4ef7b868636b1dd22eb486afdb199d712828e4ff/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Was able to successfully import all the data from E C Gaston 5, MS5A, MS5B 2022 Q2
