### ISSUE TITLE
Test & Verify:  QA Data Validation 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5741]
Issue: 
Based on recent issues with critical errors in the evaluation report and continuing issues with import/export we need to perform data validation for all modules. 

This can be performed by any team member with DB access:

- [ ] Export QA (official data) and verify the export is correct against data from official db tables
- [ ] Import QA and verify the import read data into the workspace tables properly
- [ ] Evaluate QA which should be a clean eval

**Comment by fanwari1** [comment]
Export works as expected.
Import works as expected. Data is recorded in the DB properly.
Evaluates successfully.
