### ISSUE TITLE
Test & Verify:  QA Cert Event Data Validation 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5742]
Issue: 
Based on recent issues with critical errors in the evaluation report and continuing issues with import/export we need to perform data validation for all modules. 

This can be performed by any team member with DB access:

- [x] Export QCE (official data) and verify the export is correct against data from official db tables
- [x] Import QCE and verify the import read data into the workspace tables properly
- [x] Evaluate QCE which should be a clean eval

**Comment by subrataroyCVP** [comment]
**Files exporting and importing correctly as expected. File data and database record data matches completely after the import, no alteration is happening. The official records imported has passed the evaluation successfully during dev testing.**

**Comment by subrataroyCVP** [comment]
Moving this to `Ready for Testing` so tester can do more testing.

**Comment by fanwari1** [comment]
Working as expected. Looks fine in DB. Evaluated fine as well.
