### ISSUE TITLE
Test & Verify:  TEE Data Validation 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5743]
Issue: 
Based on recent issues with critical errors in the evaluation report and continuing issues with import/export we need to perform data validation for all modules. 

This can be performed by any team member with DB access:

- [x] Export TEE (official data) and verify the export is correct against data from official db tables
- [x] Import TEE and verify the import read data into the workspace tables properly
- [x] Evaluate TEE which should be a clean eval

**Comment by AbuFofanah** [comment]
The exported data matches the database, and the import and evaluation work as expected.

**Comment by fanwari1** [comment]
Export works as expected.
Import works as expected. Data is recorded in the DB properly.
Evaluates successfully.
