### ISSUE TITLE
Test only: QA MATS Import dropdowns not populating

### ISSUE THREAD

**Issue by AmandaMNelson** [US-EPA-CAMD/PI-1#5744]
MATS Import modal Test Type and Test Number dropdowns are not populating when they should.

Steps to recreate:
Navigate to QA & Certifications --> Test Data
Open and Checkout a configuration
Click Import Data button
Select MATS PDF/XML from the dropdown
Select a location from the Location dropdown

The Test Type dropdown should populate once a location is selected
The Test Number dropdown should populate once a test type is selected

## Context 
During DSU on 10/5 discussed that this may be a non issue. Need to verify if this is truly a bug

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDB1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--412000d9c3033cdc77ec054ef02eff3c5bb893e8/Import%20MATS%20PDF-XML%20Data%20-%20Dropdowns.png)

**Comment by mosesdeeCVP** [comment]
All of the dropdowns and the selection of the hierarchy works as expected and a similar manner as the rest of the application.
