### ISSUE TITLE
Facility Configuration View Formatting 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5746]
Issue:
Because Gowanus has such a long configuration name pages where it's used have formatting issues.  Can this be limited to a specific character length (maybe 25?) and add ellipses with hover over text?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd69ac35dbe498ae2ea7eb3c80246757335c1cfc/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Work completed

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0kxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3383f6e125950ca8a39673786e9cef4267b08620/Facility%20Configuration%20View%20Formatting%20%235746%20-%20Logged%20Out.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL00xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57116293d3ff12acd34a6fda10e3732cd68121aa/Facility%20Configuration%20View%20Formatting%20%235746%20-%20Logged%20In.png)
