### ISSUE TITLE
Bug: QA Export 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5749]
Issue:
When user imports all test data into the workspace for Q4 2022 and exports one test user is also getting all of the certification event data and the text exemption data.

Steps to Reproduce:
1. In QA Cert/Test Data, Checkout Baldwin (889), configuration 2

2. Import from historical for Q4 2022 every test

3. Go to export and export one test

4. Open the file in an editor and view the cert events and test exemption data present in the file

**Comment by AmandaMNelson** [comment]
certificationEventData and testExtensionExemptionData do not have data in the JSON when exporting a single QA/Cert - Test Data test.
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/331825fd-4fec-45fc-9a9c-5b6be3bb8ecf)
