### ISSUE TITLE
TEST Only Bug: MP Formula ID 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5750]
Issue:
Formula code dropdown not fully populated on create new formula

Steps to recreate: 
1. Create formula 
2. Enter formula ID (112)
3. Enter Parameter (Heat Input Total)
4. Want to add formula code 'D-15' but only one option in drop-down list is available
5. Can only access additional formulas if you save and then edit the formula record
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8ad4f8cd99ddedaa2e55bdee738e84719118bb3/image.png)

**Comment by acollad1** [comment]
Chris needs to chat with Mike about this one so kicking it back for now

**Comment by acollad1** [comment]
11/7 refinement Need to retest as not sure if this is still an actual issue

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
From what I can tell the dropdown works as expected.

Heat Input Total only has 1 element in the dropdown.

**Comment by mosesdeeCVP** [comment]
Reporting Instructions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd094QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e728aecbf0357b3dc0abac95f86d414fb33804b/HIT%20Rep%20Instructions.png)

**Comment by mosesdeeCVP** [comment]
The Relationships on Swagger
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1d4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62980c1977e29e829145f3d2a064f89ce5343aa7/HIT%20Relationships.png)

**Comment by mosesdeeCVP** [comment]
What we see in the UI
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2F4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb57d3f75bfe04c991fc95faa8ce457f7d900138/HIT%20UI.png)

**Comment by mosesdeeCVP** [comment]
'D-15' is Heat Input Rate

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3F4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--479d86a21d426d95f1e516a5a1b5c497b52c3737/Heat%20input%20rate%20Rep%20Instructions.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEd4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2243033f740c7869d7133565f10f6c4eefc3acf3/Heat%20input%20rate%20Rep%20Instructions.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caddf4e5932661e495485fce6f0272bce208de60/Heat%20input%20rate%20UI.png)

**Comment by mosesdeeCVP** [comment]
All fields seem to be working as expected based on the documentation above. The AC is comparing two different results with the dropdowns. From what I can tell each Parameter matches what is expected in Formula Code
