### ISSUE TITLE
Bug: QA Import from Historical 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5752]
Issue: When trying to import from historical for Baldwin facility error message is thrown

Note: This seems to be universal as this also happening for Handsome Lake facility Cholla

Steps to Recreate:
1.  In QA test data checkout Baldwin Energy Complex.  
2. Import from historical test number 2022Q41HG
3. Get the below error message

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb84ae8aa68f3d05a0c55afa70db2d6bc959b757/image.png)

**Comment by mosesdeeCVP** [comment]
Was able to successfully Import all 2022Q41HG options. They were Miscellaneous BCAL, DGFMCAL and TSCAL
