### ISSUE TITLE
mats pdf / xml Import not working as expected 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5753]
## Context

The scope of this bug has two issues for importing MATS data. See below

### Issue 1:  The test type and test number drop downs are not populating for MATS import 

1. Log into ECMPS
2. Navigate to Test data 
3. Check Out any config 
4. Select Import 
5. Import Mats pdf/xmal 

The test type and test number drop downs are not populating and preventing the import of a mats pdf/xml file 
 Populate the dropdowns on the mats pdf / xml import. Right now it is pulling back only test nums from the workspace, it needs to be both from global as well

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12675b5098d05b8af66d7642568bd31fddec3e93/image.png)

### Issue 2: MATS import modal not giving the expected message 

1. Log into ECMPS
2. Navigate to Test data 
3. Check Out any config 
4. Select Import 
5. Import Mats pdf/xmal 
6. Import an MATS pdf file (if you dont have a mats pdf file you can import an empty pdf file. The import does not have checks) 
7. Select filters for config, test type, and test number
8. Import the file 
The sysem displays a "Success", but when you click "Okay" it will pop up a warning that says "All unsaved changes will be discarded, are you sure you want to cancel"

The should not display the  "All unsaved changes will be discarded, are you sure you want to cancel" when a user sucessfully imports a file.  Issue 1 may need to be completed before this issue can be fixed.

**Comment by AmandaMNelson** [comment]
Works as expected
