### ISSUE TITLE
 MP Formula: Parameter and Formula code dropdown bug

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5755]
Steps to reproduce:
1. Login and checkout a monitoring plan (e.g. Glen Lyn), open Formulas section.
2. Create new formula and select value for parameter (e.g. CO2 Concentration)
Formula code should be populated with options based on selected parameter.
3. Close modal and view/edit existing formula.
Formula code dropdown options are based on selected parameter from previous modal, not current parameter in active modal.
4. Select a new parameter
Formula code dropdown options now display all options, not just ones specific to selected parameter

Expected behavior:
When opening a modal the formula code dropdown options should correspond to selected parameter if it exists or after a selection is made

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2JBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8897ca0fdb0124194f5f5f157d25b23870b96e03/Parameter%20and%20Formula%20code%20dropdown%20bug%20%235755.png)

**Comment by mosesdeeCVP** [comment]
Expected Formula Code dropdown options match the Parameter code when editing.
