### ISSUE TITLE
UI: Official Emissions View Changes

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5756]
**Workspace Emissions** View Template dropdown should continue to function as is and show a distinct list of views that have a record in the view count with a count > 0 for the provided mp, location, report period, & view code.

**Official Emissions** View Template dropdown filter logic needs to change to show a distinct list of views that do not have a record in the view count or has a record with a count > 0 for the provided mp, location, reprt period, & view code.

A record present in the view count with count = 0 means the view has been refreshed and does not contain data, therefore the view does not need to be in the dropdown.

No record present in the view count means the view has NOT been refreshed and the user can request data for the view which will refresh the view populating then data if available.

If a user requests a view and no data is returned then show a message in the alert banner (use yellow/orange style) and refresh the dropdown to remove the view from the list (should have a count record with count = 0).
**Message:**
"The ${viewName} view does not contain data for ${yearQtr} location ${unitStack}"
**Example:** 
"The Hourly Combined Parameters view does not contain data for 2022 Q3 location CS0AAN"

**Emissions View Datatable**
Remove the Error Codes columns (Hourly Errors, Daily Errors, Weekly Errors, Test Errors) at the end of the datatable
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/7ea45bdb-2f9a-4b96-9ddc-192671f99548)

If the Error Codes property is 'Y' or not null then place a "View Errors" link in the very 1st column linking to the Error Detail Report (open in another window just like Eval & Submit)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/9d278641-876e-43d7-bef0-ac4639eadd66)

**Error Detail Report**
Official - https://ecmps-dev.app.cloud.gov/reports
Workspace - https://ecmps-dev.app.cloud.gov/workspace/reports
Query Parameters - reportCode=EM_ERR&facilityId=3612&monitorPlanId=D006020-86CBCB5ED2CE48DC94C135E6E2861F73&year=2022&quarter=3&date=2022-07-01&hour=15
_NOTE: facilityId is the oris code & parse the Date/Hr property to get the date & hour parameter to format the report url_

**Comment by AmandaMNelson** [comment]
All changes outlined above have been made
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/5f6853de-630e-4444-bb2f-4c5f16bf214b)
