### ISSUE TITLE
API: Official Emissions View Changes

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5757]
Modify the GET endpoint that retrieves official emissions view data to check if the count view contains a record for the provided mp, location, report period, & view code. If a record is not present then execute the camdecmps.refresh_emission_view_${viewCode} procedure and return the data from the view.

Example: if user is requesting the Hourly Combined parameters view which is view code ALL
execute CALL camdecmps.refresh_emission_view_all($1, $2);
$1 = monitorPlanId
$2 = rptPeriodPlanId
passing the parameters in an array to the execute query method

NOTE: this is only for the official endpoint
NO CHANGES TO WORKSPACE

**Comment by AmandaMNelson** [comment]
Verified through UI testing of #5756 .
