### ISSUE TITLE
UI: Modify MP Qualification Add/Edit Pop Out

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5758]
Expected Behavior:
Given a user navigates to the MP qualifications sections
When a user selects a qualification type code from the drop-down
Then the record creation should only be able to exist under the corresponding table 

- [x] User should not see all Qualification tables in pop-out after a type code has been selected. The type code drop-down select should drive which qualification can be created

Restrict the Qualification Type Code dropdown to Qual Types that have a group of PCT, LEE, LME, or CPMS only.

Qualifications should be restricted to PCT, LEE, LME, & CPMS based on the Qualification Type Code dropdown.

**Group to Qual Type Mapping**
- LEE = LEE
- CPMS = CPMS
- PCT = PK,SK,GF
- LME = LMEA, LMES

If the Qualification Type is LEE then LEE quals are the only records that can be created/edited
If the Qualification Type is CPMS then CPMS quals are the only records that can be created/edited
If the Qualification Type is LMEA or LMES then LME quals are the only records that can be created/edited
If the Qualification Type is PK, SK, or GF then PCT quals are the only records that can be created/edited

NOTE: Once the qualification record is created the qual type cannot be changed. You can edit other data but cannot change the qual type

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Qualification LEE
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa145446a57f085bb903dcc8ad887c4c30d5f3f5/Qualification%20LEE.png)

**Comment by mosesdeeCVP** [comment]
Qualification CPMS
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzlXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e859b42faa18722ad11a32411a6c4cfeaf10933d/Qualification%20CPMS.png)

**Comment by mosesdeeCVP** [comment]
Qualification LMEA
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c863a2d81e46d4fb523f7cf48efe280a3a9ea80/Qualification%20LMEA.png)

Qualification LMES
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9646035b00f6e8512f96d90cba786fefdd4d0a17/Qualification%20LMES.png)

**Comment by mosesdeeCVP** [comment]
Qualification Percent - PK
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5XQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64badfc380a82b0630480a64c57b2763e18ba748/Qualification%20Percent%20-%20PK.png)

Qualification Percent - SK
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a05019730d3c000324c00e3107aea49c91c7e717/Qualification%20Percent%20-%20SK.png)

Qualification Percent - GF
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53cc59be14e975d44c44d1ce7ab711b7cd1a8333/Qualification%20Percent%20-%20GF.png)

**Comment by mosesdeeCVP** [comment]
MP Qual Dropdowns

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9a812f30701429db76461a0101796378ff3ad65/Create%20Qualification%20Dropdown.png)

**Comment by mosesdeeCVP** [comment]
Work has been completed
