### ISSUE TITLE
Bug: Emissions Import/Export Adjusted hourly values

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5759]
Issue:
Adjusted hourly values are null for SO2C and Flow when I import from global where they should have a value.

Steps to Recreate:
1. Checkout Wygen III, 001 emissions
2. Import from historical for Q2 2022
3. Export this file and inspect the SO2C for 4/20/2022 11AM.  The adjusted hourly value is null.  It should be "0".  Compare this with the same export from the global workspace.

_**PLEASE SPECIFY DATA SECTION IN FILE**_

**Comment by jwhitehead77** [comment]
It would really help to specify the data section in the file becasue a number of sections have adjustedHourlyValue

**Comment by jwhitehead77** [comment]
I will be working this as I already a couple changes locally to address these import issues. Will push up by EOD Thu 10/12

**Comment by jwhitehead77** [comment]
#5731, #5732 and #5759 are all the same problem where adjustedHourlyValue was not being read in on import. These have all been addressed with changes from #5759

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3ed3f73e9517482df0f25cefbfb071e65185861/Emissions%20Import-Export%20Adjusted%20hourly%20values%20%235759.png)

**Comment by mosesdeeCVP** [comment]
Adjustments have been made Workspace export is updated and functioning as expected.
