### ISSUE TITLE
Set up SonarCloud for easey-testing repo

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#576]
- [x] Add Sonar project properties file to configure SonarCloud

**Comment by srinivasaregeti** [comment]
Worked with Yefim and seeing the following error in the logs when running sonar scan:


```
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@1877ab81
/home/runner
Invalid file: '/home/runner/work/Testing/Testing/src/main/resources/sample/SampleStarterAPITestData.csv', enter a valid one
java.io.FileNotFoundException: /home/runner/work/Testing/Testing/src/main/resources/sample/SampleStarterAPITestData.csv (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
```

Yefim mentioned that the repository is out of date and he will be updating it. After the update, this issue should be resolved.

**Comment by david-cvp** [comment]
@srinivasaregeti to update quality gate to require 0% coverage

**Comment by david-cvp** [comment]
Jason modified quality gate to accept 0% coverage

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/4e0d8481-ae01-4375-9fc1-f6375496204f)
