### ISSUE TITLE
Test Only Bug: QA Import from Historical [Indian River]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5760]
Issue:
Import from historical 2018 Q3 Unit Specific Default Nox Rate test I receive this error message "testSummaryData.0.unitDefaultTestData.0.The value of [0.245] for [noxDefaultRate] is allowed only 1 decimal place."

Steps to Recreate:
1. Checkout QA Test Data for Indian River 10
2. Import from historical for 2018 Q3
3. Select the one test that appears and import

**Comment by jwhitehead77** [comment]
#5760 and #5762 are the same issue regarding Unit Default. We need to change the schema and dto range checks to allow the min and max values based on the XML schema and then allow the check service and check engine to take care of situations where that changes based on conditions

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFA0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--061ccbfbb469ba26d22a16c4d57ffc704c87a2a0/Test%20Only%20Bug-%20QA%20Import%20from%20Historical%20-Indian%20River-%235760.png)

**Comment by mosesdeeCVP** [comment]
Import from historical was successful with no error messages.
