### ISSUE TITLE
Bug: MP Import [WS Lee]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5761]
Issue:
Import error: Formula-9 result A check critical error. The Check looks to see that either the formula cd is there OR the formula text is there, but the check is failing when there's only formula text, which should be valid. Maybe the formula text isn't making it to the check engine? 
Step to create:
Login and check out WS Lee (3264) unit 7C
Export
Import

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--852e117291335758003060dd7199b68ac4fd984c/image.png)

**Comment by jwhitehead77** [comment]
FORMULA-9-A DTO check needs to change to NOT require formulaCode or formulaText but ensure that 1 of them are reported. May need to move the check to the check service or use ValidateIf on the formulaCode and formulaText properties to see if that will work.

Could see if these would handle the condition of 1 of these needing to be reported
ValidateIf(p => p.formulaCode !== null || p.formulaText === null)
formulaCode: string

ValidateIf(p => p.formulaCode === null && p.formulaText !== null)
formulaText: string

**Comment by mosesdeeCVP** [comment]
Was able to successfully Export and Import with no issues.
