### ISSUE TITLE
Test Only Bug: QA Import from Historical [Handsome Lake]

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5762]
Issue:
User received import error when trying to import from historical 
Steps to Recreate:
1. Login and checkout  55233 EU-1A, EU-1B, EU-2A, EU-2B, EU-3A, EU-3B, EU-4A, EU-4B, EU-5A, EU-5B, CP100
2. Import from historical all under 2017 Q1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9478257a81cbba94a84423a86a8295bdc4d23e7/image.png)

**Comment by acollad1** [comment]
This will be resolved when we review all DTOs and remove min/max conditionals. Make sure that these are not done on import

**Comment by jwhitehead77** [comment]
According to Chris we really should not be importing any historical data beyond the last 4 or 5 years. Rules have changed and data that far back is most like not going to pass checks

**Comment by jwhitehead77** [comment]
#5760 and #5762 are the same issue regarding Unit Default. We need to change the schema and dto range checks to allow the min and max values based on the XML schema and then allow the check service and check engine to take care of situations where that changes based on conditions

**Comment by billmiller13** [comment]
This has been fixed and I was able to import successfully:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHoxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8478d88e56c20d2a4aabae12edeaf44a39c080e/image.png)
