### ISSUE TITLE
Bug: QA Test Data Discrepancy 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5765]
Issue:
Data discrepancy between test and dev environment

Steps to Recreate:
Log in. 
Select Smith-SCT1.
 Navigate to Qa Test Data. 
Select "Appendix E Correlation Test Summary".
 6 records are shown in dev - none in test

**Comment by jwhitehead77** [comment]
why are we logging data differences between env as a bug. This is going to happen as developers and testers work tasks. Also the test env is now pointing to the CDC database which has a full production data load and the dev env data is old and only has a small subset of data (2022 only)

**Comment by JanellC** [comment]
This is a non issue
