### ISSUE TITLE
Add Summary Value Emissions Views

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5771]
Per Email from Chris:

I think this would be a good development ticket to assign to ERG/DP we can talk about it next week. I think there are two maybe three tasks that may be better as separate tickets. First is to add a data summary view in the emissions module that mirrors the functionality in ECMPS 1.0 (first screen shot). Second task is to review the emissions views and general and see if we can speed up the load and view.  Third is to create a summary tables view shown in the second screen shot – this is dynamic and depends on the tab selected above.  The third task is a lower nice to have priority.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlU2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da8146d3dcb2599a6b187b96acec03f38a6ef3e7/image.png)

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmM2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbb4e2f2fd6716157f935fa2f011d1a386b8970d/image.png)

**Comment by acollad1** [comment]
[Add Emissions Quarterly Summary View.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjA2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c483f556d5d6833dc54b536af80ebb2abfa9151/Add%20Emissions%20Quarterly%20Summary%20View.pdf)

**Comment by annalbrecht** [comment]
Discuss with Chris

**Comment by annalbrecht** [comment]
Chris said to close this.
