### ISSUE TITLE
Bug: UI QA Protocol Gas

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5773]
Issue:
In the UI under Protocol Gas there is an option to add another Protocol Gas under it as if it was a child record. There should be no Protocol Gas child Record under Protocol Gas

Steps to Recreate:
Logged in and Logged Out > Select a Facility > Select a Config > Select Test Data to the left-hand side > Select RATA... > Select Add/View under Test Data > Add the required information > Under newly created TD Add/View Protocol Gas. Notice that it will have an option to expand. Under the first Protocol Gas the user will see an option to add another one

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5PQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb70d0acd0a6154d3755ca0f5d4eefce4f10d84f/UI%20QA%20Protocol%20Gas%20%235773%201.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8c33b3d841100c3b9feecf810d7bc88b3a5ee62/UI%20QA%20Protocol%20Gas%20%235773%202.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
