### ISSUE TITLE
UI: Fix Table Headers in All Modules

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5775]
- [ ] Implement a solution to wrap all of the table headers across all data tables in all of the ECMPS modules so they look like the table headers in the screen shot below 
- 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05FQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc26df97c3d150cfe81951ef411d3f46c15a45c3/image.png)

**Comment by fanwari1** [comment]
Note to Tester: Please check tables across the entire site and make sure they look okay.
