### ISSUE TITLE
Bug: Evaluate Report File Name Discrepancy 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5778]
Issue:
The file name in Download Report did not reflect the facility name. It picked up the oris code as the facility ID in the url.

Steps to Recreate:
1. Select Evaluate from the left panel
2. Select facility/oris  126
3. Select Configurations 3
4. Click Apply Filters
5. Click View Report
Note: This was also observed in the following facilities as well Barry, Gadsden, Dolet Hills, Widows Creek
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3hFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70f3d21d9b20e330f939414b83835cb1eec59b38/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea8f21f85b9ccbe2ca2dfad90bcdc8d495689ce1/Evaluate%20Report%20File%20Name%20Discrepancy%20%235778%20MP.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
