### ISSUE TITLE
Add CodeQL scan to CI/CD pipelines

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#578]
- [x] CodeQL scan runs in parallel (just like SonarCloud)

CodeQL results are found in the Security tab
Need a way of tracking security issues

**Comment by srinivasaregeti** [comment]
- [x] easey-emissions-api
- [x] easey-testing
- [x] easey-ui
- [x] easey-monitor-plan-api
- [x] easey-facilities-api
- [x] easey-dtos
- [x] easey-db-entities
- [x] easey-shared
- [x] check-engine
- [x] devops

**Comment by david-cvp** [comment]
- [x] easey-allowance-api
- [x] easey-campd-ui
