### ISSUE TITLE
Bug: QA Import 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5780]
Issue:
Import QA test errors from both Historical and File
Steps to Recreate:
1. Check out Kyger Creek oris 2876
2. Go to QA test section
3. Click on Import
4. Choose Import from Historical data
5. Select 2022 q1
Note: This was also observed in Clifty Creek 1,2,3 2022 Q4
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7fca9844bb8e63f9a51518b7143e91f35366ba/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Was able to successfully Export and Import files and from Historical from both Kyger Creek and Clifty Creek for the specified year and quarter.
