### ISSUE TITLE
Bug: MP Analyzer Ranges

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5781]
Issue:

- An analyzer range can be created for a GFFM component. In ECMPS 1.0 there is no option to create an analyzer range record for GFFM components.
- Only the following component type should have analyzer range data - (NOx, Hg, HCl, HF, SO2, CO2, and O2)

Steps to Recreate:
1. Go to Systems > View/Edit System 110
2. Click View/Edit Component P01
3. Create New Analyzer Range

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
No Analyzer Range option as expected for the items not listed above in the ticket.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ea03d9bac683a8ddff6fb45f039f40a6e83a7da/As%20expected.%20No%20option%20to%20create%20MP%20Analyzer%20Ranges.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - CO2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80827a842fc0dc0513cd060fcb75058ffeaf2ecb/Analyzer%20Range%20-%20CO2.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - HCL
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b86821da3be47db094d4e38f00f3815d8a2d320/Analyzer%20Range%20-%20HCL.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - HF
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e85135d99cd17da850e282be01d32d2726c977a9/Analyzer%20Range%20-%20HF.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - HF
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e85135d99cd17da850e282be01d32d2726c977a9/Analyzer%20Range%20-%20HF.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - HG
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXBjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d2b72f1fd2e4652cfa409e3cd7ed9b7b592df36/Analyzer%20Range%20-%20HG.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - NOX
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9569fa9951989901c288800afc755f0e8e1ac7e/Analyzer%20Range%20-%20NOX.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - O2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f28b049bc4bacbe5cabd9e17af9c8e2127ccc126/Analyzer%20Range%20-%20O2.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range - SO2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57e2738a586775fd3307fc7d2b6beb041557a4ec/Analyzer%20Range%20-%20SO2.png)

**Comment by mosesdeeCVP** [comment]
Analyzer Range updates have been completed for this ticket.
