### ISSUE TITLE
Bug: QA Cert Event Code Dropdown

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5784]
Issue:
The QA Cert Event Code dropdown does not include the actual QA Cert Event Code, only the Code description
Steps to Recreate:
Barry (3) 1, 2, CS0AAN
1. Select a configuration from the QA Cert Event Data & Test Extension Exemption Data screen
2. Add/ Edit a QA Cert Event

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--922767313413063cdcb7fd48d70942b9e713bbd0/QA%20Cert%20Event%20Code%20Dropdown%20%235784.png)

**Comment by mosesdeeCVP** [comment]
QA Cert Event Code Dropdown has been updated
