### ISSUE TITLE
Bug: QA Cert Test Code Dropdown 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5785]
Issue:
The Required Test Code dropdown does not include the actual QA  Test Code, only the Code description
Steps to Recreate:
Barry (3) 1, 2, CS0AAN
1. Select a configuration from the QA Cert Event Data & Test Extension Exemption Data screen
2. Add/ Edit a QA Cert Event

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dc5a61fbee24957972368ed422571f389c710f8/Required%20Test%20Code.png)

**Comment by mosesdeeCVP** [comment]
QA Test Code added to the Required Test Code dropdown along side the Code description
