### ISSUE TITLE
TEST-ONLY/BUG: QA Test Data Incorrect Error Message

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5787]
Issue:
When attempting to save a null Component ID on a linearity, the error message pop up says "componentID must be a string" instead of a check.
Steps to Recreate:
Barry (3) 1, 2, CS0AAN
1. Import a linearity test for a configuration
2. Click Edit on a Linearity Test Summary Data record
3. Leave the Component ID null and save

**Comment by subrataroyCVP** [comment]
#5789[](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5789)

Will resolve the issue.

Changeing it to Test only.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01efb806f9855cefa07057978c07aa037465e0d4/QA%20Test%20Data%20Incorrect%20Error%20Message%20%235787.png)

**Comment by mosesdeeCVP** [comment]
Works as expected
