### ISSUE TITLE
Bug: QA Test Summary Record Error Message

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5789]
Issue:
When attempting to save a Test Summary Data record with a null Test Number, error message states "The value for [null] in the Component record [testNumber] must not exceed 18 characters for [Test Summary]". This is not the correct error message for this situation. The user should receive a null value error message.

Steps to Recreate:
Login and select a configuration for QA Test Data
Add a linearity summary record
Leave Test number blank

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejE5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b05ef113a36cef2197da68d26f36d9b19516aea4/QA%20Test%20Summary%20Record%20Error%20Message%20%235789.png)

**Comment by mosesdeeCVP** [comment]
Other error messages are showing up and are showing up in the Test Summary Modal
