### ISSUE TITLE
Bug: QA Protocol Gas Record Required Field

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5790]
Issue:
When saving a Protocol Gas Record, you can save a null Vendor Identification field. 

Steps to Recreate:

Log in and check out Barry(3) 1,2,CS0AAN for QA Test Data
Select Lineartiy Summary
Expand to get to Protacl Gas records
Add/Edit a protocol gas record
Leave Vendor Id blank
Save and close
No error is displayed stop the user from performing this action

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Bug still persists. Development work still required.

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGZaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a807223ecdf1353f236f588b4721ec1e3dc89b82/vendorIdentifier.png)

**Comment by mosesdeeCVP** [comment]
Bug Fixed
