### ISSUE TITLE
 Backend updates for Updating Evaluate/Submit Module Filtering (blocker)

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5792]
## Context 

- Create new endpoints for updating the filtering. 
- One MP endpoint
- 3 QA endpoints 
- 1 Emissions endpoint

Each endpoint shall pull back all of the evaluate/submit data based on the facility(ies) a user has access to. 
- Each endpoint will not have filters

**Comment by JanellC** [comment]
During 10/18 discussed that this ticket is a low priority and should not be worked on until EPA gives the ok

**Comment by annalbrecht** [comment]
Ask Chris for more information.

**Comment by annalbrecht** [comment]
Chris said to close this ticket out.
