### ISSUE TITLE
Bug: QA Test Missing Traverse Point Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5797]
Issue: 
Traverse point data that was successfully imported is not showing up in the QA test data table. There should be 48 traverse records under run 2 in the below config. Despite this, you can not see any additional child records and this is also causing the evaluation to throw critical errors.

- [ ] Need to look at the RATA endpoint to see why its not showing up
- [ ] Missing traverse point data has been observed in Kyger Creek and Lime stone

Steps to Recreate:
1. Check out Kyger Creek (2876) 1,2,CS12
2. Select QA & Cert / Test Data
3. Click on Import Data
4. Select Import Historical Data
5. Select 2022 Q4 Reporting Periods
6. Click Preview
7. Check all boxes on RATA test
8. Click Import
Test number 1RF-20221018-0845 
Another Example: 
1. Select Limestone (298) LIMI1
2. Select QA Test from left side panel
3. Select Relative Accuracy from Test Type Group
4. Click on View of test number VFX-Q2-2023-002

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--213d7a9e928ee3bc53ba6dee3114e8257ad2929e/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemQyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52b7a51817e5264a7eb6b5a9bffc0f66dcc2160b/RATA%20Flow%20Run%20Data.png)
