### ISSUE TITLE
Bug: Emissions Data Export and Import from Historical 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5799]
Issue:
Errors when importing from historical and export from global with this message: "bind message has 4352 parameter formats but 0 parameters"

Steps to Recreate:
1. Select Gowanus only active location
2. Either in global view attempt export 2022 Q1 or import historical 2022 Q1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1pPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--256b79ac36166dd800c75093243866c18c738dbc/image.png)

**Comment by AmandaMNelson** [comment]
Gowanus, 2022 Q1 export is successful
