### ISSUE TITLE
Create API Project Starter Kit

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#58]
- [x] Create project
- [x] Add sample endpoints 
- [x] Integrate swagger implementation 
- [x] Review with team

Assignees: 
@jwhitehead77 
@SimeraHailu 
@junie-cvp 
@sdhawan16

**Comment by jwhitehead77** [comment]
@SimeraHailu, @junie-cvp, @sdhawan16 - I have uploaded the starter kit to the starter kit folder in PI-1 repo. Please use this and feel free to add, modify, do whatever needs to be done for PI-1 tasks.

**Comment by junie-cvp** [comment]
Created a branch for feature: add sample unit tests.

Submitted pull request for review.
