### ISSUE TITLE
Bug: Critical Error Report Blank

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5800]
Issue:
Select the Evaluation option for configuration below, received Critical Errors after running the evaluation but not showing on the report. The report only shows system/component has an informational message.

Related to issue https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5799

Steps to Recreate
1. Check out Kyger Creek (2876) 1,2,CS12
2. Select QA & Cert / Test Data
3. Click on Import Data
4. Select Import Historical Data
5. Select 2022 Q4 Reporting Periods
6. Click Preview
7. Check all boxes on RATA test
8. Click Import
9.  Select Evaluation
10.  Click on Critical Errors Eval Status

**Comment by JanellC** [comment]
Bug remediated. The system no longer displays critical error message. The system displays informational message
