### ISSUE TITLE
Bug: QA Import Flow to Load Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5801]
Issue:
When user exports and reimports, then evaluates user gets this error  Flow-to-Load Check records " AverageAbsolutePercentDifference" data was not stored after an Import from File

Steps to Recreate:
1. Check out Clifty Creek configuration 1,2,3,CS013
2.  Select Export & Reports from the left panel
3. Select 2022 Q4 reporting periods
4. Click on Apply Filters
5. Select Flow to Load Check (F2LCHK)
6. Click on Export
7. Select QA test in workspace
8. Select Import/Import from File/choose exported file from step 6
9. Go to Evaluate on Clifty Creek config 1,2,3,CS013
10. Select 2022 Q4 reporting periods
11. Select all Test Data
12. Click on Evaluate

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXBPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc8d2985f96a48a647d6299fca948dfeca0db74a/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2w5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbf7585861ad24b3de2a31b2ce387a34aea1612b/QA%20Import%20Flow%20to%20Load%20Data%20%235801.png)

**Comment by mosesdeeCVP** [comment]
Evaluated:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzU5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2ed4e2f50794d0d2f542a2829710b3fc63633bf/QA%20Import%20Flow%20to%20Load%20Data%20%235801%20-%20Evaluated.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
