### ISSUE TITLE
Bug: QA Test RATA Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5804]
Issue:
Received error msg:  [RATA-79-A] - You did not provide [pitchAngle], which is required for [RATA Traverse]

Steps to Recreate:
1. Check out Limestone (298) LIMI1
2. Select QA Cert Test
3. Select Relative Accuracy Test Type 
4. Click on Import Data
5. Select 2022 Q2 Reporting Period
6. Click on Preview
7. Select RATA test number VFX-Q2-2022-001
8. Click Import button

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5PQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2724b42901ff18406d74e43550305243d152c130/image.png)

**Comment by AmandaMNelson** [comment]
Able to import the test number above without issue
