### ISSUE TITLE
Bug: Admin QA/Cert Data Delete Functionality 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5805]
Issue:
Delete button is not working 
Steps to Recreate:
QA/Cert Maintenance 
1. Select Paradise 1378
2. Select configuration PCC1
3. Select test summary
4. Select test 573-Q4-2016-1
5. Select delete, confirm delete. 
6. Test is still there.

**Comment by AmandaMNelson** [comment]
Deleted tests and confirmed that they were removed from the table
