### ISSUE TITLE
Bug: EM Submission Window Open Functionality 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5806]
Issue:
Fails to create valid window
Steps to Recreate:
Maintain EM submission access
1. Select Paradise 1378
2. Select configuration PCC1
3. Select reporting period 2022 Q1
4. Select Filter
5. Click the left hand check box
6. Select open 
7. Enter test comment and change the data to 11/30/2023, save.
8. New record is created, but “Status”, “Emission status”, and “Submission Availability” are same as existing record. Status should be “apprvd” and “require”.

Another Example:
Issue:
Cannot open emissions submission window

Steps to Recreate:

Log into ecmps with a user that has admin access
Apply filter to pull up Holcomb, SGU1, 2022Q4
Select the submission window that appears in the results and click open
Fill out a reason in the modal and click save
Another submission window entry appears in the results but is also closed
https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/stream.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D17%20Screenshots%2FHolcomb%20Submission%20Window%20Issue%2Emp4

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05b1101bc257979db9e3f26ef6d7cb9c1ef4a6c3/Maintain%20EM%20Submission%20Access%205806.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed
