### ISSUE TITLE
Bug: Admin QA/Cert Data Require Resubmission Functionality 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5807]
Issue:
User receives an error when trying to require a resubmit "Records with id undefined not found error"
Steps to Recreate:
1. Select Paradise 1378
2. Select Test Number
O2D-Q3-2019-2
3. Select Require resubmission
4. Enter test comment 
5. Select save and close
6. Error generates and no change in data.

**Comment by AmandaMNelson** [comment]
tested with Paradise and test number O2D-Q3-2019-1
