### ISSUE TITLE
Retest only: Bug: Expand Button Logic on RATA Run Records

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5808]
Expected Behavior

Users  can add as many traverse points as they want to any of the flow runs

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Update screenshot once UI updates are completed:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba410abff25f4357b8e7ebc28f03c5f0eacbc8e6/RATA%20Traverse%20Data.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTYrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcb7c0038281d23f02b3b6e4d638ad1540a91725/RATA%20Traverse.png)

**Comment by mosesdeeCVP** [comment]
User is able to create Rata Traverse as under any Rata Flow needed
