### ISSUE TITLE
(Critical) Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

### ISSUE THREAD

**Issue by kstetsyuk** [US-EPA-CAMD/PI-1#5811]

**Comment by kstetsyuk** [comment]
Repos:
https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot
https://github.com/US-EPA-CAMD/easey-emissions-api/security/dependabot
https://github.com/US-EPA-CAMD/easey-facilities-api/security/dependabot
https://github.com/US-EPA-CAMD/easey-account-api/security/dependabot
https://github.com/US-EPA-CAMD/easey-mdm-api/security/dependabot
https://github.com/US-EPA-CAMD/easey-streaming-services/security/dependabot
https://github.com/US-EPA-CAMD/easey-camd-services/security/dependabot
https://github.com/US-EPA-CAMD/easey-auth-api/security/dependabot

**Comment by shahbazkhan1999** [comment]
@ergjustin plz review these
https://github.com/US-EPA-CAMD/easey-campd-ui/pull/614
https://github.com/US-EPA-CAMD/easey-emissions-api/pull/430
https://github.com/US-EPA-CAMD/easey-facilities-api/pull/153
https://github.com/US-EPA-CAMD/easey-account-api/pull/145
https://github.com/US-EPA-CAMD/easey-mdm-api/pull/172
https://github.com/US-EPA-CAMD/easey-streaming-services/pull/93
https://github.com/US-EPA-CAMD/easey-camd-services/pull/197
https://github.com/US-EPA-CAMD/easey-auth-api/pull/160

**Comment by ergjustin** [comment]
@shahbazkhan1999 
I don’t believe that it’s necessary to install "@babel/traverse": "^7.23.2" package to fix the Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code. **It was already fixed 4 days before**. 

1. easey-emissions-api:- https://github.com/US-EPA-CAMD/easey-emissions-api/security/dependabot/29
[Image ](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--311efb429e1710a915bbb3e67d0b0c2855faf0a8/emmission.PNG)
2. easey-facilities-api:- https://github.com/US-EPA-CAMD/easey-facilities-api/security/dependabot/25 
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9a24115ce348909d6240ffd00b10730969174ee/fes.PNG)
3. easey-account-api:-  https://github.com/US-EPA-CAMD/easey-account-api/security/dependabot/28
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99ca7ee0fafde0de6266e77049ce65c24eabb5bb/account-api.PNG)
4. easey-mdm-api: https://github.com/US-EPA-CAMD/easey-mdm-api/security/dependabot/31
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5bf4c1b17e638776b8f8191a029bff82a79b6c6/mdm.PNG)
5. easey-streaming-services:- https://github.com/US-EPA-CAMD/easey-streaming-services/security/dependabot/19
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d42ceeae4d57db193d6afb18c654b0cc29c29c4/streaming.PNG)
6. easey-auth-api : -  https://github.com/US-EPA-CAMD/easey-auth-api/security/dependabot/33
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6843fc9c1378bf49317ed54c1d19e594d7e31081/auth-api.PNG)

Can you please recheck this issue?

**Comment by ergjustin** [comment]
@shahbazkhan1999 
Revert "Babel vulnerable" changes that you did.
There is no need for code change.

**Comment by ergjustin** [comment]
Already issue solve. so, code riveted
