### ISSUE TITLE
(Critical) vm2 Sandbox Escape vulnerability

### ISSUE THREAD

**Issue by kstetsyuk** [US-EPA-CAMD/PI-1#5816]

**Comment by kstetsyuk** [comment]
Repo:
https://github.com/US-EPA-CAMD/easey-camd-services/security/dependabot

**Comment by shahbazkhan1999** [comment]
@ergjustin please review this https://github.com/US-EPA-CAMD/easey-camd-services/pull/196

**Comment by ergjustin** [comment]
@shahbazkhan1999 
merge to develop or release branch ?

**Comment by ergjustin** [comment]
@shahbazkhan1999 
I don’t believe that it’s necessary to install `"vm2": "^3.9.19"`
Please refer this ticket https://app.zenhub.com/workspaces/tech-team-kanban-board-5f36c9f5ad78a3000f8d20af/issues/gh/us-epa-camd/easey-ui/5707

**Comment by ergjustin** [comment]
`Vm2 is not a direct dependency of the application.  It is required by NestJS/Mailer.  Further, there is no fixed version of vm2 as the maintainers have discontinued the project.  There is a pull request on the NestJS/Mailer that removes the vm2 dependency but a release has not be planned yet.` (10/25 - Michael email)
