### ISSUE TITLE
Workspace Test Data is not exporting properly 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5817]
## Conetext 

When a user is logged into the system and exports data from the export module. The system exports from the offical endpoint instead of the workapce endpoint

## Steps to Reproduce 

1. Log in to ECMPS
2. Navigate to the Export & Report Module 
3. Select a config 
4. Apply filter criteria 
5. Export Test Data 

When a user exports test data while logged into the system, the system is calling the offical endpoint. Files that are exported while a user is logged in should call the workspace endpoint.  

For testing this ticket, testers can make a change to any test record, then export and confirm their change is in the export file

**Comment by AmandaMNelson** [comment]
Changed info in Greene County, CT10, 2022 Q2, Mon Plan, Location Attributes and confirmed the change in the Print-out Report and Exported JSON
