### ISSUE TITLE
Bug: UI Spacing in Configuration and Export Page

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5819]
Issue:
The spacing in the configuration and export/report table 
Steps to Recreate:
Navigate to select configuration and/or export/report table
Select Gowanas facility which has a large number of configurations
Observe in the table that the Actions column is pushed out all the way to the right side of the table 
The Status column should be in alignment with the oris header and actions column with the state header

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejljQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec9cf91dd0f1b27032e73df35a4914850ab3ddc0/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGQ0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5410df3eec4da888b1022e8451ab9dd438136df0/UI%20Spacing%20in%20Configuration%20and%20Export%20Page%20%235819.png)

**Comment by mosesdeeCVP** [comment]
Status header is in alignment with Oris Code

**Comment by mosesdeeCVP** [comment]
Should we be able to see so many Configurations? As in meeting
