### ISSUE TITLE
Update Submission Critical Error Process

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5829]
10/31 Per Refinement Chris gave the go-ahead for CVP to pick up this work 

- [x] Submit copy of record, but do not move the data
- [x] Need to add messaging 
- [x] When submitting with critical errors evaluation report is sent along
- [x] Not changing status flags

The submission process needs to be modified to allow the submission of eval status: CRIT files.

Modify the front end to allow sending of CRIT files: EvaluateAndSubmit/DataTables.js

Modify the backend submission process to submit the copy of record, but not perform any of the sql transactions to copy the data over: Camd-Services - Submission/SubmissionProcess.ts

During stand-up 10/23 Chris confirmed that updates will need to be made regarding what happens to the critical errors on a submission. DPC will pick up this work.

**Comment by JanellC** [comment]
Tested and verified with Kyle. The system has the ability to submit with critical errors
