### ISSUE TITLE
 Rata Traverse Fields Not Importing or Saving 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5831]
## Contest 

The  Rata Traverse fields probeId, averageVelocityDifferencePressure, and averageSquareVeolictyDifferencePressure e are not being saved when a user imports data or add it manually.  

## Steps to reproduce 

**Import Rata Traverse**

1. Login into ECMPS 
2. Navigate to the test data module 
3. Check out a facility 
4. Select Import 
5. Select Import from file 
6. Import RATA data (the imported file must contain Rata Traverse) 
7. View imported rata data in the data tables 

The fields probeId, averageVelocityDifferencePressure, and averageSquareVeolictyDifferencePressure fields of Rata Traverse are not being saved on import.  The system should display the imported data for Rata Traverse. 

**Add Rata Traverse**

1. Login into ECMPS 
2. Navigate to the test data module 
3. Check out a facility 
4. Select RATA as a test type  
5. Add Rata traverse data (may need to add other rata data types before you can add rata traverse data) 

When a users manually adds Rata traverse data the fields probeId, averageVelocityDifferencePressure, and averageSquareVeolictyDifferencePressure are not being saved.

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfbc1d4d465769b40f9daa08da553f269f240647/QA%20Import%20from%20Historical%20%235852%20RATA%20Traverse%20Data.png)

**Comment by mosesdeeCVP** [comment]
Rata Traverse is Importing
