### ISSUE TITLE
Bug: MP Stack Flow Analyzer

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5832]
Issue:
Unable to create Component Type "Stack Flow Analyzer" due to inability to select the "Basis Code". The System is requiring  a Basis Code, but there are is no data in the Basis Code dropdown to select
Error: ["[COMPON-14-A] - You did not provide [basisCode], which is required for [Component]."]
Steps to Recreate:
Log In
Go to MP Systems
Select View/Edit to System record
Select Create Component
In the Comonent Type dropdown select "Stack Flow Analyzer" and then fill other info as needed.
Try and Save.
Systems says that a Basis Code is needed, but the user is anable to select Basis code as there are no options in the dropdown.

**Comment by AmandaMNelson** [comment]
Running into an issue with Component ID 
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/af4cff95-f99f-4e3b-a000-4183f4d0cbb4)

**Comment by AmandaMNelson** [comment]
Can save new component successfully
