### ISSUE TITLE
Bug: MP Import Issues

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5833]
Issues: 
Users have been experience several schema validation errors exporting and importing for the following
monitoringLocationData.0.monitoringQualificationData.0.monitoringQualificationPercentData.0.averagePercentValue
monitoringLocationData.1.monitoringQualificationData.0.monitoringQualificationPercentData.1.yr1PercentageValue
monitoringLocationData.0.monitoringQualificationData.0.monitoringQualificationPercentData.0.yr2PercentageValue
monitoringLocationData.0.monitoringQualificationData.0.monitoringQualificationPercentData.0.yr3PercentageValue
monitoringLocationData.6.nonLoadBasedIndicator must be an integer number
monitoringLocationData.6.nonLoadBasedIndicator should not be empty

- Believe these errors are due to schema changes made from number to integer in this previous ticket https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/504

Steps to Recreate:
1. Check out 55276 Ceredo Station location 01, 02, 03....
2. Export Monitoring plan
3. Import Monitoring plan

**Comment by mosesdeeCVP** [comment]
No import/export errors occurring for PCT, LEE and LMA
