### ISSUE TITLE
Bug: Evaluation QA Test Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5834]
Issue:
Received CRIT1 error on Traverse Point data imported from historical data
Steps to Recreate:
1. Check out Limestone unit LIMI1
2. Import 2022 Q2 QA Test from historical data
3. Evaluate 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a6e7987528557867ad4282518744be7d3384c0b/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Am getting an import error. Speak with developers about it.

Curtis H. Stanton Energy Center
1
2022 Q2
Rata

testSummaryData.0.rataData.0.rataSummaryData.1.rataRunData.0.flowRataRunData.0.rataTraverseData.0.The value of [W-4] for [methodTraversePointId] must be 1 to 3 characters and only consist of upper and lower case letters, numbers for [RATA Traverse].

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3Q4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40679c7c62c551b99bb70bfa44850c96a71c6061/Evaluation%20QA%20Test%20Data%20%235834.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzE4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23afe707bf7b28cd6fd705a66d73522388d3f2a2/Evaluation%20QA%20Test%20Data%20%235834.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed. Am not getting an Informational Message instead of Critical Error
