### ISSUE TITLE
Bug: MP Import Errors

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5836]
Issue: 
User is receiving import errors (see screen shot below) for MP 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2b912f38dbb9773c401860881b8c7aec3c9cdaa/image.png)

Step to Recreate:
1. Check out Irvington config 4
2. Export MP
3. Import MP

**Comment by Qb10** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9DQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fccba28ba34658d64afeea77ce712e9dfb47dded/image.png)

data is from 1999 and is not able to pass current checks due to it missing defaultSourceCode

**Comment by JanellC** [comment]
Retest only: non issue
