### ISSUE TITLE
Bug: UI QA Test Data Naming Convention 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5837]
Issue:
The child record on RATA currently labeled as "Flow" needs to be RATA Flow Run Data to stay consistent with the other titles 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjlqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dd78bf4e980c6ca6daaf5f3e3dd24f4488df579/image.png)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
RATA Flow Run Data can be found under the below:
Curtis H. Stanton Energy Center
1
Rata
130-Q2-2022-1

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3QxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77d5c3280087ef8768cdef33e22956b8694ef697/RATA%20Flow%20Run%20Data.png)

**Comment by mosesdeeCVP** [comment]
Update has been made
