### ISSUE TITLE
Bug: MP Submission Report 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5839]
Issue:
Submission Report is missing the facility info
Steps to Recreate:
1. Successfully submit a MP report for this facility+config combo.
2. Navigate and login to your test CDX account.
3. Navigate to the Submission History.
4. Select and open the submission package that was submitted successfully.
5. Select and save the Submission HTML file.
6. Open the HTML report file (i.e., 470_MP_MDC-75702FF835394F518216D79BEDE6EFA6.html) and you will see the facility info is incorrect (it's a completely different facility in Nebraska, not Nevada).

Note:
You will see this error from the submission package submitted on 10/23/2023 at 2:39pm. The submission ID is: _9d28aaa3-48b3-49d8-8a1b-9f7796cb3b6d   
The file name is 470_MP_MDC-75702FF835394F518216D79BEDE6EFA6.html

**Comment by JanellC** [comment]
Verified bug with @Kyle-Herceg. The Submissions report is displaying the correct facility
