### ISSUE TITLE
Bug: MP Submission Report Wrong Facility Name

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5840]
Issue:
Submission Report has the wrong facility info
Steps to Recreate:
1. Successfully submit a MP report for this facility+config combo.
2. Navigate and login to your test CDX account.
3. Navigate to the Submission History.
4. Select and open the submission package that was submitted successfully.
5. Select and save the Submission HTML file.
6. Open the HTML report file (i.e., 55841_MP_MDC-8C67D7FDFD384C5EA2C016135A82C75E.html) and you will see the facility info is missing

Note:
You will see this error from the submission package submitted on 10/23 4:38:05pm. The submission ID is: _6f7cd208-3239-48ec-b740-802a8f4030f2
The file name is 55841_MP_MDC-8C67D7FDFD384C5EA2C016135A82C75E.html .

**Comment by JanellC** [comment]
Tested with @Kyle-Herceg with Bug: MP Submission Report #5839. System works as expected
