### ISSUE TITLE
Bug: Global Export and Report Download

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5841]
Issue:
Download Report did not work (see image)
Steps to Recreate:
1. Click on Export & Report  Anderson (7336)
2. View Print-out Report

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3h1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ead59114a1b6bfcdb60f00383f593ef43bf8ee54/image.png)

**Comment by JanellC** [comment]
The system is downloading the MP print out report in global and worksapce.
