### ISSUE TITLE
TEST ONLY Bug: MP Evaluate

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5842]
Issue:
API Communication errors.  Evaluation finished on Monitoring Plan but kept loading something in other sections
Steps to Recreate:
1. Check out 7336 config ACT1
2. Go to Export & Report section
3. Export to file
4. Import from file
5. Go to Evaluation
6. Select Anderson/Config ACT1
7. Apply filters
8. Check Monitoring Plan box
9. Click on Evaluation

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEp1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc4edd4929743aa43e0456a879765c225473e62e/image.png)

**Comment by addisgmichael** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/68253641/205eaeeb-f23c-4ed8-9c55-a920ddebf549)
The errors do not seem to appear anymore. 
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/68253641/1d700cf9-69c4-42d1-ad04-7c474565b7cf)

**Comment by addisgmichael** [comment]
The issue does not seem to exist anymore.
