### ISSUE TITLE
Bug: QA Test Evaluate 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5843]
Issue:
Received CRIT1 error on 2019 Q1 QA/Cert Test evaluation (check code TEST-22-B)
Steps to Recreate:
1. Check out Anderson config ACT1
2. Import 2019 Q1 QA Test from historical
3. Go to Evaluation
4. Select Anderson config ACT1
5. Select 2019 Q1 Reporting Period
6. Apply Filter
7. Select QA Test
8. Click on Evaluation

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFp1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc45974902e75c33d753ea0b7b77031915ebe110/image.png)

**Comment by subrataroyCVP** [comment]
No changes needed. Needs Retesting.

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1634dcfad964ef9ed9575d85efdb953e9a0e2b44/QA%20Test%20Evaluate%20%235843.png)

**Comment by mosesdeeCVP** [comment]
Evaluation successful. Evaluated as Informational Message
