### ISSUE TITLE
Node version update (v16>v20) part 1

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#5845]
For Release v1.3 these APIS will be updated to v20:
facilities-api 
account-api 
emissions-api 
streaming-services

**Comment by ergjustin** [comment]
@shahbazkhan1999 
Please review pull request https://github.com/US-EPA-CAMD/easey-emissions-api/pull/435

**Comment by ergjustin** [comment]
Node version Updated screenshot 
- [easey-account-api](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31b00ae1ba1cb551541e5a62b77f1b25093fbafa/easey-account-api.PNG)
- [easey-facilities-api](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eac41c0df9a6eb89f3dc183cd0b79d22c3f167e9/fes.PNG)
- [easey-emissions-api](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c167889fef04e058210a75812689046c7199dea/emission-api.PNG)
- [easey-streaming-services](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc4b68e73f36119294d99e2b4ee93e9c9db26b25/stream.PNG)

**Comment by hamezene** [comment]
@ibarra-michelle

**Comment by ibarra-michelle** [comment]
All prod apps have been updated to use the cflinuxfs4 stack: <img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3g1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab7ef5ecc7a49a365543f868a71fa663fa33bded/image.png" alt="image.png" />
