### ISSUE TITLE
Bug: EM Submission Access (Lamar)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5846]
Issue:
The user receives an error when trying to use the Lamar Power Plant facility configuration in the em submission access screen 
Steps to Recreate:
1. Log in with admin role
2. Navigate to em submission screens
3. Select Lamar Power Plant (1) configuration and apply filter
4. Recieve the below error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEp3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e78e72ad46ec5411067f3a72b87dc4863aa58c6/image.png)

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/7a9eb1fe-cd2b-4aff-ae5a-872b9cbc42d6)
