### ISSUE TITLE
Custom data download tool UI.- Error Message- "there is no data available After selecting reporting time period filter 

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5847]
Annual and Ozone season emissions are not working in the custom data download tool UI. it says there is no data available once you enter a date in the time period filter

This is also happening for all emissions data types. 

Steps to recreate: 

on CAMPD production site
1. **Select Data Type**  - Emission
2. **Select Sub data type** - Ozon Season Emissions
3. **Select Aggregation** - Any (State, National, Unit, Facility)
4. Click Apply
5. Type in  Time Period 
6. Click apply filter and observe error message "**there is no data available After selecting reporting time period filter**" display. 

Please see screenshots[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHgyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc29e5af7a3ba1b71df4df5235ed0342d7a6ff1c/Custom%20Data%20Download%20-%20error%20-%20Data%20is%20not%20available%20-%20Emissions%20-%20Hourly%20emissions.PNG)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c1ec9a62f6b2b808680251a4ddbe716ff336587/Custom%20Data%20Download%20-%20error%20-%20Data%20is%20not%20available%20-%20Emissions%2C%20Ozon%20Season.PNG)

**Comment by hamezene** [comment]
Issue found: 
the night jobs took longer than usual and overlapped so the shh tunnel got closed by one job which then caused the other job to abort. 

Since the job was aborted, there was no email notification.

**Comment by hamezene** [comment]
This issue has been resolved by re running the overnight job that was aborted.

**Diff report for the refresh:** 


#SchemaName,TableName,Oracle_Counts,PG_Counts,Counts_Difference
"camddmw","account_compliance_dim",95944,95944,0
"camddmw","account_fact",23711,23711,0
"camddmw","account_owner_dim",32413,32413,0
"camddmw","allowance_holding_dim",586923,586923,0
"camddmw","control_year_dim",181713,181713,0
"camddmw","fuel_year_dim",174614,174614,0
"camddmw","owner_display_fact",102038,102038,0
"camddmw","owner_year_dim",202605,202605,0
"camddmw","program_year_dim",273332,273332,0
"camddmw","rep_year_dim",870081,870081,0
"camddmw","transaction_block_dim",1432195,1432195,0
"camddmw","transaction_fact",537108,537108,0
"camddmw","transaction_owner_dim",1315432,1315432,0
"camddmw","unit_compliance_dim",20782,20782,0
"camddmw","unit_fact",130647,130647,0
"camddmw","unit_type_year_dim",129184,129184,0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEIzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48a13afdc045d66725a0482245f5221155bc3bb7/custom%20data%20download%20-%20fixed.PNG)

**Comment by tlageman-epa** [comment]
clsoing this ticket as the issue has been resolved.
