### ISSUE TITLE
Bug: Emissions Import (Anderson)

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5848]
Issue:
Received error message when there is no data for the selected reported period.
Steps to Recreate:
1. Check out Anderson ACT1
2. Go to Emissions
3. Click on Import
4. Select 2023 Q1 from Import Historical Data

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3g4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b95c6888c501f01c373bfde38d2e75ce9b581858/image.png)

**Comment by JanellC** [comment]
Invalid...System is working as expected
