### ISSUE TITLE
Bug: QA Test Data Evaluate 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5849]
Issue:
PGVP-14-A result has a severity level of NONE

- [ ] This RATA does not receive the PGVP-14-A check result in ECMPS 1.0 when evaluating.

Steps to Recreate:
Go to the QA Test Data screen, import from historic data RATA test number NS7-Q2-2022-001, and evaluate

**Comment by subrataroyCVP** [comment]
Facility: Kyrene Generating Station
Oris: 147
Config: K-7
Reporting Period: 2022 Q2
Test Number: NS7-Q2-2022-001
TestTypeCode: RATA

**Comment by subrataroyCVP** [comment]
As confirmed by Chris, We would not be showing `NONE` errors, Since it does not show `NONE` errors in ECMPS 1.0.

Tech Team needs to work on this.

**Comment by jwhitehead77** [comment]
We removed/filtered out the NONE records

**Comment by JanellC** [comment]
System no longer returns PGVP-14-A result that has a severity level of NONE. 
System provides an informational message after evaluation 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek92QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37449820c37276f6617dff7b8494fa2be26e3c3c/image.png)
