### ISSUE TITLE
Bug: MP Evaluate 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5850]
Issue:
QUAL-38-C 
You have not reported all the required Monitor Qualification Percent records for QualificationTypeCode PK BeginDate 1/1/2000.
Steps to Recreate:
1. Export from Official  Anderson ACT1
2. Login and import exported file.
3. Evaluate the MP record.
4. Return `Critical Errors`

**Comment by billmiller13** [comment]
This critical error was correct - it is not a bug.  The data exported from Official did not have a Monitor Qualification Percent record for 2023 which would be required according to Check Specification QUAL-38.  Adding a valid Monitor Qualification Percent record for 2023 and then importing and evaluating gets a Passing result.
