### ISSUE TITLE
Bug: QA Import from Historical

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5852]
Issue:
User received 288 Import Errors

Note: Might just be an issue with rata traverse files
Steps to Recreate:
1. Check out Brandon Shores 1
2. Revert Brandon Shores 
3. Go To Import Historical QA
4. Import 2022 Q4 All Tests 
5. 288 Import Errors Generated

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b34088ac3e6a974b8572d7dba4f07b11661b4500/QA%20Import%20from%20Historical%20%235852%20RATA%20Traverse%20Data.png)

**Comment by mosesdeeCVP** [comment]
Received no Import errors
