### ISSUE TITLE
Bug: QA Cert Event

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5853]
Issue:
When creating QA Cert Event trying to save with an empty Event Hour returns an error but displays no error message
When editing saving with empty Event Hour returns error but closes the edit modal  with no error message
Steps to Recreate:
1. Check out a configuration
2. Create/Edit QA Cert Even
3. Fill in information except "QA Cert Event Hour"
4. Save and close

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16d95f40c2cdf6fa91bb1345e996c2c6f87a988c/QA%20Cert%20Event%20%235853.png)

**Comment by mosesdeeCVP** [comment]
UI now shows the error message as expected
