### ISSUE TITLE
Update Codes & Cross Checks for MATS 2.0/GNP

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5857]
Dwayne sent changes regarding MATS 2.0/GNP codes and cross checks that need to be updated in the database and easey-db-scripts per below...

Finished the updating the [MATS 2.0 & GNP Cross Check and Lookup Table Updates for MP.docx](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Integration%20Coordination/ECMPS/MATS%202.0%20%26%20GNP%20Cross%20Check%20and%20Lookup%20Table%20Updates%20for%20MP.docx?d=w8e17b3d38d3c40708db97d09c141b2fe&csf=1&web=1&e=VcLDUq) with additional changes.

The changes occur under the following:
- Lookup Tables
  - Component Type Code:
    - PM Description Update.
- Cross Check Tables
  - Method Parameter to Method to System Type Cross Check Table: (Cross Check Id: 8)
    - Add NOx/Calc row.
  - Program Parameter to Method Parameter Cross Check Table: (Cross Check Id 85)
    - Update Method Parameter Lists where Program Parameter Cd equals HCL, HF, HG, PM, and NOX.
    - Add row for Program Parameter Cd equals "MATS".
  - System Type to Formula Parameter Check Table: (Cross Check Id 17)
    - Add row for PM/PMRE.
    - Add row for PM/PMRH.
- Other Tables
  - CAMDECMPSMD.PARAMETER_METHOD_TO_FORMULA
    - Add NOX/CALC row.

**Comment by jwhitehead77** [comment]
@djw4erg can you please verify these changes in DEV and good to go

**Comment by djw4erg** [comment]
> @djw4erg can you please verify these changes in DEV and good to go

Everything looked okay except the Formula List for NOX/CALC in CAMDECMPSMD.PARAMETER_METHOD_TO_FORMULA contains spaces.  Jason, removed the spaces yesterday and all the changes look correct.
