### ISSUE TITLE
Sort Emissions Evaluations By Quarter

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5858]
The current emissions evaluation process does not run emissions from different quarters in any particular way. This needs to be changed to run earlier emission quarters from the same monitor plan first. 

This was causing an issue in the emissions evaluations, because all prior workspace quarters must be evaluated first to ensure the later records pass.

**Comment by JanellC** [comment]
Evaluted multiple emissions records. The system evaluted  the files based on year quarter in chronological order
