### ISSUE TITLE
Submission checkboxes are not available after a submission

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5859]
Currently the submission checkboxes are hidden after a user completes one successful submission.

Steps to recreate:

1. Navigate to submission
2. Submit an available portion of data [SUB_AVAIL_CD = REQUIRE or GRANTED, EVAL_STATUS_CD = INFO or PASS]
3. Complete CROMERR process and Submit 
4. Click 'Ok' on Submission complete notification 
5. Files that can be submitted no longer have the checkbox [Can leave the module and re-enter to fix]

**Comment by JanellC** [comment]
Tested and verified with Kyle. The system has checkboxes
