### ISSUE TITLE
STORY: Cumulative API Validation 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#586]
## User Story
As a user I want to view the final API call outcome so that I can know the call was completed.

## Acceptance Criteria
Given a user has called the API
When validations are run
Then the system will run all validations 

Given the system has detected a validation failure
When the failures are displayed
Then the system will display to the user all validations detected

Given all validations were successful
When the system returns data
Then the system returns confirmation message (200 code)

## Testing
Test Case: [TC76](https://cvpcorp.testquality.com/project/11428/plan/19464/test/269535)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R20](https://cvpcorp.testquality.com/project/11428/testcase/269535/requirement/11079). Do not remove or edit.

**Comment by david-cvp** [comment]
![available values.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/da0acc48-239f-4de1-97c3-c6bc45f478d2)

**Comment by david-cvp** [comment]
TC76 passes

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/6ba77d71-f5b8-4c4d-999d-4412d4f24844)

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/2486c2e4-4a7b-4a40-9bef-1faa82782bbc)
