### ISSUE TITLE
Eval / Submit / Export Emissions endpoint is returning multiple em_sub windows

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5860]
Currently the endpoint to pull back emissions top level data for evaluate, submit, and export & report is using a view which pulls back multiple em_sub_access records. This needs to be changed to only bring back the most recent em_sub_access window.

**Comment by JanellC** [comment]
Ticket addressed the system only returns one emissions record when evaluating or submitting.
