### ISSUE TITLE
Eval Report Critical Is Blank

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5861]
The Emissions Eval report for the following emissions record is not populating after an evaluation. Most likely the result of a check engine error.

[
    {
        "orisCode": 298,
        "facilityName": "Limestone",
        "monPlanId": "MDC-D4D7F122FD8F488F8B09A87DF926020E",
        "configuration": "LIM1",
        "evalStatusCode": "ERR",
        "evalStatusCodeDescription": "Critical Errors",
        "submissionAvailabilityCode": "GRANTED",
        "submissionAvailabilityCodeDescription": "Permission to Resubmit Granted",
        "userid": null,
        "updateDate": null,
        "windowStatus": null,
        "periodAbbreviation": "2022 Q2"
    }
]

**Comment by JanellC** [comment]
Evaluation report is populating 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFc0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5480b6119c3b1e5dc81ee6de136fc0b0f21d7d25/image.png)
