### ISSUE TITLE
Retest Only: Export & Report MP Selection Delayed 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5862]
## Context 
When a user is logged into the system, navigates to the report and export module, and attempts to select a monitoring plan the selection is delayed. This may be a timing thing If you hit that page then wait 10 seconds it works well.  **As apart of the scope of this ticket fix this delay and ensure that this is not happening for any other section besides MP** 

## Steps to Recreate 
1. Log into ECMPS 
2. Navigate to the Export & Report Module 
3. Select a facility 
4. Select the MP displayed in the Monitor Plan table 

When a user selects the MP it takes a couple of clicks before the user can select the Moniotring Plan. This may be a timing thing If you hit that page then wait 10 seconds it works well.  **As apart of the scope of this ticket fix this delay and ensure that this is not happening for any other section besides MP** 

For testing: this issue was spotted for the workspace however when testing ensure that this issue is not happening for global (logged out) view as well

**Comment by subrataroyCVP** [comment]
I was not able to reproduce the error. Could be a system specific. Moving the ticket for Testing.

**Comment by mosesdeeCVP** [comment]
Did not experience this issue. I tried several different systems and still unable to reproduce the bug. Ticket Closed.
