### ISSUE TITLE
MP Schema Discrepancies 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5863]
Issue:
Recently, one of our Software Developers noticed the following two inconsistencies in the latest Monitoring Plan JSON schema, which might be indicative of a bug.

 

Element monitoringDefaultData has a property groupID  (with capital “D”)
This was previously called groupId (with lower-case “d”)
This property is still called groupId in the “required” section of the schema
I suspect this property should still be called groupId (lower-case “d”)
 

Element unitControlData, properties originalCode and seasonalControlsIndicator
These are defined as strings with enumerated values null, “0”, and “1”
Other similar “indicator” fields are numeric with values null, 0, and 1
I suspect these fields should be numeric as well

**Comment by jwhitehead77** [comment]
Unit Control properties originalCode and seasonalControlsIndicator are defined as strings in the database so the schema is correct
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/99576bc1-a3bd-4770-9264-06799046f930)

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkxOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c11fd8bc0c0086b412577d3063810f3c5cf80f68/monitoringDefaultData%20-%20groupId.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlBOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a25050380f578c7f7933480f1973fe4532671251/groupId%20-%20monitoringDefaultData.png)

**Comment by mosesdeeCVP** [comment]
groupId is correctly formatted with a lowercase 'd'

**Comment by mosesdeeCVP** [comment]
The elements under unitControlData are correct to be a 'String' as this in an exception. No changes were made as it is ok the way it is.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3d1cef4d18c8a5935bb1a534bbdba167a13fe04/unitControlData.png)
