### ISSUE TITLE
Bug: Emissions Evaluate

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5864]
Issue:
CRIT1 check code 'HOURGEN-12-B'. 

To fix this issue the developer will need to debug this in the Test env. Data for 2023Q1 is not available in the dev env

Steps to Recreate:
1. Check out Irvington config 3
2. Import 2023Q1 Emissions
3. Go to Evaluation
4. Select Irvington config 3
5. Select 2023Q1 Reporting Period
6. Check Emissions box and click Evaluate button

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70f85b7644bb2a60d1f3eaecf9f9bffb3b3c01b4/image.png)

**Comment by subrataroyCVP** [comment]
@acollad1  Is this happening in dev?

I am not able to import due to there are no data available. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3daa77c486b4cdef459f7027dfe35d69d334f02/image.png)

**Comment by JanellC** [comment]
During DSU decided that this issue will be worked on by the tech team. Tech team will troubleshoot and and see if any additional functionality needs to be addressed

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ArQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9318bf4063037a181b4c94d3913a31dd391358b7/Emissions%20Evaluate%20%235864.png)

**Comment by mosesdeeCVP** [comment]
No errors occurred for this. The Import and Eval were successful and Evaluated as a Pass
