### ISSUE TITLE
Bug: Submission Report 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5865]
Issue:
QI name is blank in report
Steps to Recreate:
1.  Checkout QA Test Data for Potter config 3
2.  Import test file 2023-Potter-1660-3-RATA-fe8a5a6f-5f42-472c-83dd-67d2a4ec7dd3.json
3.  Evaluate and Submit
4.  View report in CDX Submission History (the QI Name is blank)

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots%2F1660%5FTEST%5FDETAIL%2Ehtml&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots

**Comment by JanellC** [comment]
QI name is displayed 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXEvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eaa2a0e99c63044b4d80dd65c252d2b4b74f042c/image.png)
