### ISSUE TITLE
Bug: Monitoring Plan "Systems" Modal Inaccuratly Displaying Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5866]
## Context 

As apart of the scope of this bug need to fix the following two bugs see below: 

**Issues to be fixed as apart of this bug :**
1. The system is displaying the incorrect data in the MP systems modal. After a user views a system modal for one record, the data is repeated and displayed in all of the following system modals, 
2. The padding in the system modal needs to be updated. In the Modal the "System>component" label is too close to the edge of the modal and isn't clear for a user to see. Update padding

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e3ca96ac254d66aedc74886c0e531a322851529/image.png)

## Steps to reproduce 

1. Log into ECMPS
2. Navigate to the MP module 
3. Check out a configuration 
4. Select systems from the sections drop down 
5. Select "view/edit" for a record (make note of the data displayed in the modal) 
6. Close the record modal 
7. Select "view/edit" for a  different record 

In the second modal, the system is displaying data for the previously viewed record. Need to ensure that the system is displaying the correct data in the modal. Also, at the top of the modal "System>component" label is too close to the edge of the modal and isn't clear for a user to see.

See recording
https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/stream.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots%2FOdyssey%20Energy%2050815%20unit%20ENG101%2DComponentViewIssue%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview

**Comment by jwhitehead77** [comment]
Why is this considered a bug? Each of those records have different start and end dates and 1 of them has a start date but no end date which is valid. Here is the same data in TEST and BETA env
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/a4379436-8714-4431-b349-07ea853e638c)

**Comment by JanellC** [comment]
@cw-cvp will stop working on this issue until we ha ve further discussion

**Comment by JanellC** [comment]
Discussed this ticket during DSU on 11/2. I have updated the ticket with more information to capture the essence of the bug. Development on this ticket can continue

**Comment by cw-cvp** [comment]
The [changes](https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1370) will only affect System Components and Fuel Flows and will not affect other datatables/modal views.
