### ISSUE TITLE
Bug: MP Forbidden Resources

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5867]
Issue:
Forbidden Resources
Steps to Recreate:
1. Check out Odyssey config ENG101
2. Select Systems from Monitoring Plan section
3. Click View/Edit System ID N11
4. Click View/Edit System Components 121

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/50815uENG101-ViewComponentForbiddenResource.png?csf=1&web=1&e=v7PB6U&cid=2d0574b1-3194-4c1f-9591-667e8eaaf5d6

**Comment by AmandaMNelson** [comment]
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/110929222/e65a95b4-509e-4576-bde2-3f25dd785206)
