### ISSUE TITLE
Bug: Submission Permissions

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5868]
Issue:
Able to submit with a user who only has the prepare role and no relationship to the facility
Steps to Recreate:
1.  Prepare a record for submission
2.  Go to the submit queue and select the record for submission
3.  When the authentication dialog appears authenticate with a valida CDX user who only has the prepare role and follow the rest of the certification process

**Comment by JanellC** [comment]
Issue has been addressed 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK20vQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9ce8892f5c75ee827ff82553ec92a4ca046d780/image.png)
