### ISSUE TITLE
Bug: Emissions Evaluate Status

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5869]
Issue:
Import from historical hangs for almost 5 minutes. When attempting to evaluate, it goes to "in queue" to "needs evaluation" even after selecting evaluate.
Steps to Recreate:
1. Checkout 2494 only active config
2. Emissions Import from historical 2022 Q2
3. Attempt to evaluate this emissions data

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Bug fixed. The evaluation completed successfully.
