### ISSUE TITLE
Retest: Bug: QA/Cert Forbidden Resource

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5871]
Issue:
User receives forbidden resource status error
Steps to Recreate:
1. Check out Odyssey config ENG101
2. Select Cert Events, Extensions and Exemptions
3. Click Add
4. Select System ID N11
5. Select Component ID 121
6. Select 1 (DAHS Vendor Change)
7. Select 99 Other test Required Test Code
8. Select 10/28/2023 Hour 15 QA Cert Date Hour
9. Select 10/30/2023 Hour 13 Completion Test Hour

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/50815uENG101-AddCertEventsForbiddenResource.png?csf=1&web=1&e=vvbaOx&cid=ebaaacd5-e85a-40eb-9257-299432eadc16

**Comment by subrataroyCVP** [comment]
I am able to successfully create a record. in the DEV environment. 

By looking at the screenshot, The reason user could have got that error due to session/token expired. By Logging out and starting a new session may resolve the issue.

Passing it to Tester for testing.

**Comment by mosesdeeCVP** [comment]
Was able to create the record successfully with no issues or errors.
