### ISSUE TITLE
Bug: QA Test Submission data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5872]
Issue:
AETB and Protocol Gas data are not saved to the global view after a successful QA submission
Steps to Recreate:
1. Checkout 564 config CCB
2. Import attached file into QA test workspace
3. Run Evaluation
4. Run Submit after Sign and Certify
5. Look for the latest record in global view

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots%2FTEST%5FDETAIL%5FCurtis%20H%2E%20Stanton%20Energy%20Center%5F564%2Ehtml&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots

**Comment by JanellC** [comment]
@Kyle-Herceg tested and verified this issue
