### ISSUE TITLE
Bug: QA Protocol Gas Data

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5874]
Issue:
Protocol Gas is missing from the historical RATA in global - view print-out report
Steps to Recreate:
1. Select 564 config CCB from global view
2. Go to Export and Report
3. Select 2022 Q2 Reporting Period
4. Select RATA test
5. View Print-out Report

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots%2FTEST%5FDETAIL%5FCurtis%20H%2E%20Stanton%20Energy%20Center%5F564%2D2022q2%2Ehtml&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots

**Comment by subrataroyCVP** [comment]
We do not have Protocol Gas Report added for RATA. Chris confirmed to add the Protocol Gas Report. 

As I talked with @Kyle-Herceg . This needs to added in the DB-SCRIPTS. So, Transferring over to `Tech Team` @Kyle-Herceg

**Comment by JanellC** [comment]
Protocol Gas added to report  
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCt3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd7bb7f3f66dee13cc68d879eabcadff2f5eccaa/image.png)
