### ISSUE TITLE
Bug: Submission History Link

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5875]
Issue:
The link in the Submission Confirmation Report email to cdx submission history is linked to the wrong environment (it's linked to cdx dev when it should be linked to test). Need to make sure this is pointed to the correct place for beta
Steps to Recreate:
1. Submit any files to cdx

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/SubmissionHistoryLinkIssue.png?csf=1&web=1&e=fsZhgY&cid=9b720fe8-8f2d-488f-a7f8-b07c41ba0640

**Comment by JanellC** [comment]
@Kyle-Herceg tested and verified this ticket
