### ISSUE TITLE
Bug: Emissions Import

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5880]
Issue:
Import emissions file says success although there's an error and no data is loaded into the workspace. The error in the file is a bad MODC code that I changed to 99 seen in the screenshot
Steps to Recreate:
1. Attempt to import Emissions _ Export - Hot Spring Energy Facility (CT-1)  - 2023 - Q4.json
2. You'll see the import is successful, but the console has errors and no data is loaded 

https://usepa.sharepoint.com/:i:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/55418_EM_BadMODC_json.png?csf=1&web=1&e=NIbVPc

https://usepa.sharepoint.com/:i:/r/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/55418_EM_BadMODC_json.png?csf=1&web=1&e=NIbVPc

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8620814245f5720ca2ab2517272444734820144/You%20reported%20an%20invalid%20modcCode%20of%2099..png)

**Comment by mosesdeeCVP** [comment]
The system does not allow the file to be imported and error pops up advising the user that the data is bad
