### ISSUE TITLE
Bug: MP Default Section 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5881]
Issue:
Missing NFS from Create Default Select Fuel Code list
Steps to Recreate:
1. Check out 564 config CCB
2. Select Default from MP section
3. View/Edit NOXR
4. Add 10/31/2023 hour  9
5. Save and Close
6. Click Create Default
7. Select NOxR
8. Select Fuel Code

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/564uCCB-MissingNFSfromDefaultFuelCodeSelect.png?csf=1&web=1&e=LiaH9a&cid=bad4e5a7-8f83-45c5-8825-29d5ed74ca54

**Comment by jwhitehead77** [comment]
@cw-cvp per Chris Worley please remove the restriction on fuel code and show all fuel codes in the dropdown using master data. We will remove the fuel code column from the relationship data once this is done.

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d0a7f5752f94e858963ea97e8b8223cd558de77/MP%20Default%20Section%20%235881.png)

**Comment by mosesdeeCVP** [comment]
NFS is available for selection in MP Default Section
