### ISSUE TITLE
Bug: Emissions Evaluate Status Stuck

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5882]
Issue:
Evaluate stuck on "in progress" 
Steps to Recreate:
1. Check out 55418 CT-1
2. Import emissions file: Emissions _ Export - Hot Spring Energy Facility (CT-1)  - 2023 - Q4_pctavailerror.json
3. Attempt to evaluate this file

**Screen Shot:** 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/55418_EM_Badpctavail_json.png?csf=1&web=1&e=rB9XCB&cid=928d6891-eac9-47cc-b27c-dc214f6ab0ff

**Link to File to Reproduce Error:** 
https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/download.aspx?UniqueId=9d4d9e6293fd4c7eab9f8c723e3f7780&e=hEjMOf

**Comment by JanellC** [comment]
@j-tafoya I checked the following folder but didn't see the actual file you used for this bug. Can you point me to the file? I only saw screenshots of the data 

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000B4ABB0EF9635994FA680705355892410&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots&viewid=18eab565%2D03ba%2D4600%2Da594%2D5eb27c0d799a

**Comment by j-tafoya** [comment]
> @j-tafoya I checked the following folder but didn't see the actual file you used for this bug. Can you point me to the file? I only saw screenshots of the data
> 
> https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000B4ABB0EF9635994FA680705355892410&id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots&viewid=18eab565%2D03ba%2D4600%2Da594%2D5eb27c0d799a

@JanellC  Here is the link directly to the file: https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/download.aspx?UniqueId=9d4d9e6293fd4c7eab9f8c723e3f7780&e=hEjMOf

**Comment by subrataroyCVP** [comment]
@j-tafoya 

I was able to import and evaluate the file successfully. It took 3-4 min for the evaluation process and return errors.
Here is the Report in PDF ➡️ [EM_EVAL_Hot Spring Energy Facility_55418.html.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--150c8a933f70d5270b4121f0b35d633958465a7b/EM_EVAL_Hot%20Spring%20Energy%20Facility_55418.html.pdf)


Please Let me know if you have any issues/questions.


https://ecmps-dev.app.cloud.gov/reports?reportCode=EM_EVAL&facilityId=55418&monitorPlanId=MDC-23D120FD628A473299BA0D0EF4A4AC03&year=2023&quarter=4

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
The evaluation completed the process successfully. Evaluated as 'Critical Error' 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79db240e6560368f4ad3cb26fd75a98a132f7fa/Emissions%20Evaluation.png)

**Comment by mosesdeeCVP** [comment]
Emissions Evaluation Report
https://ecmps-dev.app.cloud.gov/workspace/reports?reportCode=EM_EVAL&facilityId=55418&monitorPlanId=MDC-23D120FD628A473299BA0D0EF4A4AC03&year=2023&quarter=4

**Comment by mosesdeeCVP** [comment]
Emissions Printout Report
https://ecmps-dev.app.cloud.gov/workspace/reports?reportCode=EM&facilityId=55418&monitorPlanId=MDC-23D120FD628A473299BA0D0EF4A4AC03&year=2023&quarter=4
