### ISSUE TITLE
Bug: Evaluation Email Report

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5883]
Issue:
There are no details about the crititcal errors from link to Critical Errors in email 
Steps to Recreate:
1. Checkout 2493 config 60
2. Import 2023 Q1 QA test
3. Expand Linearity
4. Add Protocol Gas
5. Add High on Gas Level Code
6. Add Nitrogen Balance Gas, Carbon Dioxide, Nitric Oxide, Total Oxides of Nitrogen Gast Type Code
7. Add CC1234567 in Cylinder Identifier
8. Select Airgas USA, LLC, an Air Liquide Componany (NC)
9. Add 10/31/2026 in Expiration Date
10. Run evaluation on QA test
11. View notification email

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots%2FTEST%5FEVAL%5FEast%20River%5F2493%2Ehtml&parent=%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FECMPS%20Beta%20Testing%2F2023%2D10%2D27%20Screenshots

**Comment by JanellC** [comment]
Based on discussion during DSU on 11/6, this issue is invalid
