### ISSUE TITLE
Bug: Emissions Import from Historical

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5884]
Issue:
Error importing historical data "duplicate key value violates unique constraint "pk_emission_view_lme"
Steps to Recreate:
1. Check out 55276 01,02,03,04,CP01
2. In Emissions module, import from historical 2022 Q1

https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-10-27%20Screenshots/55276_ImportHistoricalError.png?csf=1&web=1&e=OJNTNG&cid=4272bea7-230e-4780-9bc5-bc1c107e1628

**Comment by billmiller13** [comment]
Could not re-create this bug in DEV or TEST environments.  In both, the Emissions import was successful with no issues.  Closing ticket.

**Comment by billmiller13** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG10QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--795b1c9ffd1bab65d5a75b3fcf2e587dfc14dfe6/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12371473de5ce34f72ae589336d81854e433351a/image.png)
