### ISSUE TITLE
Retest Only: Files exported from BETA do not follow file naming convention 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5891]
## Context 
When a file is exported from the BETA enviornment the Filename is random characters and is not consistent with the file naming convention followed in the dev and test enviornment. As apart of the scope of this ticket need to ensure that ALL files (MP,QA,Em, etc)  exported from BETA are consistent with the file naming convention followed in the dev and test enviornments. Ensure this is completed for files exported in the workspace and global views.

## Steps To Reproduce 

1. Navigate to the BETA enviornment 
2. Navigate to Export and Report Module 
3. Export any file (MP,QA, or Emissions) 

When the file is exported the Filename is random characters and is not consistent with the file naming convention followed in the dev and test enviornment. 

See the following image to see how files are named when exported from BETA: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/ECMPS%20Beta%20Testing/2023-11-01%20Screenshots/Export_FilenameIssue.png?csf=1&web=1&e=xjG44n&cid=10617bf6-0258-4cc6-a9b9-e62077835136

**Comment by JanellC** [comment]
Google Tag manager addressed this issue. Ticket needs to be retested to verify

**Comment by mosesdeeCVP** [comment]
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Global
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2U0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ff8c34a84d830f80ff26d2ab03b439e5929645e/Files%20exported%20from%20BETA%20do%20not%20follow%20file%20naming%20convention%20%235891%20%28Global%29.png)

**Comment by mosesdeeCVP** [comment]
Workspace
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0M1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67fca7fd5d0e6c3539b530f2d7ac7a62d43aac60/Files%20exported%20from%20BETA%20do%20not%20follow%20file%20naming%20convention%20%235891%20%28Workspace%29.png)

**Comment by mosesdeeCVP** [comment]
Files are being exported identically from one environment to another.
