### ISSUE TITLE
MP Systems Component ID giving improper error

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5893]
## Context 

MP Systems Component ID giving an error even when a user has entered values that meet the required format . 

## Steps to Reproduce 

1. Log in
2. Go to MP and select Systems from the dropdown
3. Select View/Edit for a System record
4. Select Add Component
5. Select Create Component

When entering a Component ID with three letters, the user receives an error message ststing that the component ID must contain three alphanumeric characters. The ID is accepted if it is composed of three numbers, or two letters and then a number. However, if the formatting is more specific (three letters are not acceptable), the error message should be updated to reflect that.

**Comment by cw-cvp** [comment]
Component ID only accepts uppercase alphanumeric characters.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--897b885a8c2745dc516d5bfe8acfd8bd2e5affc6/image.png)
