### ISSUE TITLE
Bug: UI Homepage Top Menu

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5900]
Issue:
EPA Search bar in top right-hand side menu is cut off, and search button does not show any explanatory text 
Steps to Recreate:
open Menu (top right)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3UyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7db28f379cd95a4a233f38776a01cd954187a7fc/image.png)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHZMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95916a75be119084bff90fbf12d5747d1e2e6874/UI%20Homepage%20Top%20Menu%20%235900.png)

**Comment by mosesdeeCVP** [comment]
Bug fixed.

No text will be in the search box as of now as there are 508 concerns with it. Any further updates would be handled in a future ticket
