### ISSUE TITLE
Clean Air Markets Program Data (CAMPD) v1.3 - API Issues found during 4 API scans

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5901]
From: Smoot, Durrell <Smoot.Durrell@epa.gov> 
Sent: Friday, November 10, 2023 11:25 AM
To: Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Subject: Clean Air Markets Program Data (CAMPD) v1.3 - API

Good day,

While performing the 4 API scans of the CAMPD application, we noticed that the scanner returned 404 for all the endpoints. Scan has been set back to pending.

“The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.”

Accounts API – 
 

Emissions API –
 

Facilities API –
 

Streaming API –

**Comment by hamezene** [comment]
From: Smoot, Durrell <Smoot.Durrell@epa.gov> 
Sent: Friday, November 10, 2023 11:25 AM
To: Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Subject: Clean Air Markets Program Data (CAMPD) v1.3 - API

Good day,

While performing the 4 API scans of the CAMPD application, we noticed that the scanner returned 404 for all the endpoints. Scan has been set back to pending.

“The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.”

Accounts API – 
 

Emissions API –
 

Facilities API –
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f14e521900deca7e4f0ec0b28067677d08c8e5fd/Emissions%20API%20%E2%80%93.png)

 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2731b487a4298944abcb4c7ae164f00d1fe0852b/Facilities%20API%20%E2%80%93.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b46c7c56d5eeba0679ed96767c7d4bd3423c80fc/screen%20grabs%20Accounts%20API.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0hMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--518843d8493b6aefdc94bab6ecf4d2231ec192ac/Streaming%20API%20%E2%80%93.png)

**Comment by ergjustin** [comment]
**Accounts API** 

1. staging/account-mgmt/allowance-holdings/owner-operators - line number 233
[allowance-holdings/owner-operators - 404](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d652021f8584266f06b326151884fb2e7482e9d4/233.PNG)
[allowance-holdings/owner-operators - 200](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f72b0187a9fcd58ef53e5b5302f021d4bd742d8/233-answer.PNG)

**Comment by ergjustin** [comment]
Emissions-API:- I tried with year=100 its returns 400 Bad Request    
[emissions/apportioned/attributes/applicable?year=100](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98aedc58c31ef84329acf45714669492d76517d8/Year_100_badRequest.PNG)

**Comment by ergjustin** [comment]
I'm confused, they are using multiple time `/easey/staging` in the URL. 
Eg: [https://api.epa.gov:443/easey/staging/easey/staging/account-mgmt/accounts](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5165e5096aeb0b43c838d4d251a6ecdf3f501eb/237.PNG)
