### ISSUE TITLE
Bug: QA Data Appendix E Correlation Heat Input

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5907]
Issue: 
Appendix E Correlation Heat Input from Gas and Appendix E Correlation Heat Input from Oil Add/Edit modal does not populate Monitoring System ID - hence the screen does not allow to add/edit a record.

**Comment by mosesdeeCVP** [comment]
Am able to Add and edit 'Appendix E Correlation Heat Input from Gas'. Am unable to test Oil due to a but. This will be tested in future ticket related to the fixing of the Oil bug
