### ISSUE TITLE
Monitoring Plan Schema Issue - GroupID

### ISSUE THREAD

**Issue by maheese** [US-EPA-CAMD/PI-1#5912]

**Comment by maheese** [comment]
In the Monitoring Plan Schema in element monitoringDefaultData there is a property groupID  (with capital “D”).  In all other uses of "Id" in the schema the "d" is lower case.  groupID needs to be changed to groupId so it's consistent with other uses in the schemas.  Note: the code will also need to be updated to properly handle this name change of this property.

This was reported by an industry tester in Request Tracker ticket [73082](https://rt.camdsupport.com/rt/Ticket/Display.html?id=73082)

**Comment by acollad1** [comment]
This has been already fixed in dev part of CVP's effort to resolve schema issues

**Comment by chrisgitsit** [comment]
This was handled in another MP schema ticket 5863:  https://app.zenhub.com/workspaces/roadmap-5f96fc2121b1e50016c7acce/issues/gh/us-epa-camd/easey-ui/5863
