### ISSUE TITLE
Bug: QA Protocol Gas

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5914]
Issue: UI not remembering the selected data under Protocol Gas - Gas Type Code.
Steps to Recreate:
1. Log into ECMPS
2. Go to Test Data
3. Select Rata
4. Create a Rata
5. Create Protocol Gas
6. Add neccessary data including "Gas Type Code", but leave "Vendor Identification" blank. Then Save.
7. An error will occure, but the "Gas Type Code" also shows a blank. The previously selected option should still show up. 
8. This only occures in Create as far as I can tell

**Comment by mosesdeeCVP** [comment]
Bug fixed
