### ISSUE TITLE
Change API date format to YYYY-MM-DD

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#593]
## User Story
As a user, I want to view dates in the ISO format YYYY-MM-DD, so that dates are understandable to all users.

## Dev Tasks
- [x]  Change date format in maps file

## Acceptance Criteria
Given I perform a GET request to the Emissions API
When the API returns a response
Then all dates are in YYYY-MM-DD format

## Testing
Test Case: [TC74](https://cvpcorp.testquality.com/project/11428/plan/19464/test/269151)
Tester: @davidkwartler

**Comment by sdhawan16** [comment]
Changed response date format to YYYY-MM-DD

Decided to keep original acceptance criteria with opDate returning only the date (YYYY-MM-DD).  Will check with Mike and Jason on whether we want to include time as well as part of opDate when they are back and make any changes as needed following that decision in the future.

**Comment by david-cvp** [comment]
TC74 passes

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R24](https://cvpcorp.testquality.com/project/11428/testcase/269151/requirement/11085). Do not remove or edit.
