### ISSUE TITLE
Bug: Emissions Import

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5938]
Issue: When in emissions workspace importing from historical 2023 Q1 for Indeck-Yerkes (50451), configuration 1.  The import appears to be successful but I’m getting these “Cannot read properties of undefined (reading 'includes')”.  The screenshot below shows the log from the associated emissions API call.  I also see errors when I’m on the evaluation page after import but I’m assuming it’s the same problem.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ccc31390b62a7dcb0909c64aa7e9eedd478a2b8/image.png)

**Comment by mosesdeeCVP** [comment]
Am able to import without any errors and the system evaluates as "Informational Message". Bug is fixed
