### ISSUE TITLE
Bug: Import Paradise PCC1 2023 Q2 Invalid CO2 Emission Rate UOM Code

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#5946]
Importing from historical creates the following error...

![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/8e023575-d64b-4a73-81a3-f6ed3bf515c6)

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ceafdf96904dcb401fc2a6b78ef1cc7cf5455d47/Import%20Paradise%20PCC1%202023%20Q2%20Invalid%20CO2%20Emission%20Rate%20UOM%20Code%20%235946.png)

**Comment by mosesdeeCVP** [comment]
Was able to Import Historical data with no issues or errors
