### ISSUE TITLE
Filters not enabled for Compliance, Emissions Based data type

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#5947]
On stage filters are not enabled: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33429125ceee5da2daa9590cb446f8487651d9a3/image.png)

On dev and prod, filters are enabled:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8b95d781ba62027b75bf0b5ecc8c650f316fa67/image.png)

**Comment by ergjustin** [comment]
The reason why the filters are is in disabled, there is no applicable data in staging database to filter.
[applicable query - browser](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26378f0cd9640a489c3546ff97898d08443ae06f/applicable.PNG)
[staging database](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFloQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b891fb416fa34f04543802ed72ad06708b62e7fb/database.PNG)

**Comment by alangmaid** [comment]
Am closing this ticket because data have been loaded to test and the filters are enabled.
