### ISSUE TITLE
STORY: Validate Unit fuel Type 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#595]
## User Story
As a user I want to be able to enter valid filter criteria for unit fuel type so that I can see results

## Dev Tasks

- [x] Create an entity for fuel_type_code
- [x] Ensure enums match entries in fuel_type_code
- [x] Create a custom decorator to validate 
- [x] Add decorator to DTO

## Acceptance Criteria
Given that a user has entered invalid filter criteria for unit fuel type
When the API endpoint is executed
[Then the system displays the error message FV-2
](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC73](https://cvpcorp.testquality.com/project/11428/plan/19464/test/269150)
Tester: @davidkwartler 

### Issue Requester:
Requester:

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R21](https://cvpcorp.testquality.com/project/11428/testcase/269149/requirement/11082). Do not remove or edit.

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R23](https://cvpcorp.testquality.com/project/11428/testcase/269150/requirement/11084). Do not remove or edit.

**Comment by david-cvp** [comment]
TC73 passed

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/bb0ecd89-5457-48db-b807-f532649cfac8)
