### ISSUE TITLE
Emissions API refactoring & regression test

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#596]
- [x] Junie to refactor Emissions API code
- [x] David to perform regression testing to ensure #544 still works

**Comment by junie-stigdon** [comment]
Updated _hourly-apportioned-emissions.service.ts_: 
- Refactored repetitive code. 
- Made it cleaner and easier to read. 

Branch: https://github.com/US-EPA-CAMD/easey-emissions-api/tree/code-clean-up

**Comment by junie-stigdon** [comment]
Branch merged into develop. David currently testing functionality.

**Comment by david-cvp** [comment]
TC66 passes, we are able to get data with all filter criteria and the results include all of our test data and the required data elements
