### ISSUE TITLE
UI: Error ID in Error Messaging 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5963]
Background:
Need implement backend error ids in all front end error messaging

**Comment by annalbrecht** [comment]
Need to determine if we are storing error messages anywhere. Messages should be in a message store (lookup table?) so that we can ID them and we can update them as needed. 

The intent is to improve debugging and support.

**Comment by ibarra-michelle** [comment]
@annalbrecht , could we discuss this ticket at the next stand up meeting? Thanks.

**Comment by ibarra-michelle** [comment]
@annalbrecht could you change the priority from Low to High? We'd like to further discuss this ticket at the next meeting.

This ticket appears to be tracking two separate issues (12/01/2023 and 03/26/2024 comments). Also, EPA is reviewing additional requirements related to this topic and may need to add/modify the requirements.

**Comment by annalbrecht** [comment]
Discussed with EPA on 6/7/24. This will be covered by other tickets in the future. Closing.
