### ISSUE TITLE
Bug: Emissions API pagination

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#597]
## Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Navigate to EASEY Out Emissions API</p><br><p>Swagger UI: <br /><br><a href="https://easey-dev.app.cloud.gov/api/emissions-mgmt/SWAGGER/">https://easey-dev.app.cloud.gov/api/emissions-mgmt/SWAGGER/</a></p><br><p>Postman direct API link:<br /><br><a href="https://easey-dev.app.cloud.gov/api/emissions-mgmt/emissions/apportioned/hourly">https://easey-dev.app.cloud.gov/api/emissions-mgmt/emissions/apportioned/hourly</a>| Swagger UI is displayed with a "GET" option| Pass |
| 2| Expand the "GET" option and click "Try it out"| Option expands and user is able to enter text| Pass |
| 3| Click "Execute" to call the API endpoint with no filter criteria| The response is displayed as response body and response headers| Fail |
| 4| Perform a "GET" request with<br /><br>"page":1<br /><br>"perPage":50| The response is displayed as response body and response headers. Body will contain 50 results. Headers will contain page numbers and total number of results.| Fail |

### Actual Results
Step 3 failed because the API will not return any data unless "page" and "perPage" parameters are used

**Expected Result**
API should return data without using pagination

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com defect [D9](https://cvpcorp.testquality.com/project/11428/result/2196630/defect/7428). Do not remove or edit.

**Comment by david-cvp** [comment]
New test case: 
[TC78](https://cvpcorp.testquality.com/project/11428/plan/19464/test/269901)

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com requirement [R25](https://cvpcorp.testquality.com/project/11428/testcase/269901/requirement/11093). Do not remove or edit.

**Comment by sdhawan16** [comment]
Created PR: 
- Ensured pagination is no longer required to send a request 
- Modified code to simplify
- Added unit test for when pagination is not provided

**Comment by david-cvp** [comment]
TC78 passes
