### ISSUE TITLE
Nod Version upgrade for CAMPD API

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5973]
Upgrade the following API to node 20

Master Data
CAMPD Services
Auth API

**Comment by ergjustin** [comment]
For camd-services, in staging and production have only one API that is 'camd-services/bulk-files'

Staging : https://api.epa.gov/easey/staging/camd-services/swagger/

Production : https://api.epa.gov/easey/camd-services/swagger/



As per the release document ([LINK](https://github.com/US-EPA-CAMD/easey-ui/issues/5818)) need to create a release branch from the main branch. 


When I ran the main branch locally, I got 10 APIs. If I go forward as per the document 9 new APIs will be deploying in the staging and production. I am attaching the screenshot of main branch code run locally. 
![campd-service](https://github.com/US-EPA-CAMD/easey-ui/assets/108369391/0622d906-487e-4786-9d72-3d11f100c766)

**Comment by ergjustin** [comment]
<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a34b84b40245130131ab8c447bdf1633096b3a01/auth-api.PNG" alt="auth-api.PNG" />
<img width="1037" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ptQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18ad8284683fa78d836ca5feb029664341ef7c26/camd-services.PNG" alt="camd-services.PNG" />
<img width="973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05tQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5859850f056a8d86c8b19958d9155277443c58f9/master-api.PNG" alt="master-api.PNG" />

**Comment by ergjustin** [comment]
As per 12/13/2023 conversation ([link](https://teams.microsoft.com/l/message/19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype/1702510446217?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&parentMessageId=1702505996478&teamName=CAMD%20CVP%20Team&channelName=CAMPD&createdTime=1702510446217))
I changed the hiddenness of logging and bookmark APIs in staging

**Comment by hamezene** [comment]
@ibarra-michelle

**Comment by ibarra-michelle** [comment]
After running the cf audit-stack command, I can confirm all of the apps have been updated to use the cflinuxfs4 stack.
