### ISSUE TITLE
Facility ID search copy/paste functionality

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#5975]
From RT 73386: The copy/paste functionality of the facility Id into the facility filter in CAMPD UI is not working. You should be able to put in a list like "3|4|5|10" and it should pull back all matches and identify mismatches. This functionality worked properly before the deployment. Please make sure this is not another branching issue. I'm hoping it will be addressed by the fix from the emissions API that we are testing today. Please let me know if you have any questions.
<img width="888" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a971078d0c2a9be87ca476f18d21bfdc17b46cb1/image.png" alt="image.png" />

**Comment by alangmaid** [comment]
Fix verified on staging. When I enter "7|10" and apply filter, results display.
<img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--108b7341ffe4c5eaf1c518214028d4a0c336991f/image.png" alt="image.png" />

**Comment by ergjustin** [comment]
Verified in production  When I enter "3|7|10" and apply filter, results display.
<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dee65f9ceaa76665ef1af3aa726e204160532c58/facilityId.PNG" alt="facilityId.PNG" />
