### ISSUE TITLE
Bad Request when downloading CSV File - Exclude- Unit ID 

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5977]
From RT 73384: I just received a ticket from a user unable to perform an hourly emissions query in the custom data download tool. I confirmed the issue and it seems to be happening to an emissions query. The criteria are as follows: hourly emissions, unit level aggregation, any time period, any other filter and you get a 400 error. I tried the api directly in the browser and get this error. If i remove the exclude parameter it works. Please investigate immediately.

<img width="1505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28f556b714bbfd2a1b12188b75e4df6893cd8a25/MicrosoftTeams-image%20%281%29.png" alt="MicrosoftTeams-image (1).png" />
<img width="1650" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c03b76ec7c0a9bd755140982fd9fd63212b8f1a/MicrosoftTeams-image.png" alt="MicrosoftTeams-image.png" />

**Comment by alangmaid** [comment]
Here is a screengrab from staging confirming the fix.
<img width="1259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c49d7d73f6f4816dadb34862b1973bf28e31545/image.png" alt="image.png" />

**Comment by ergjustin** [comment]
Verified download. Attaching screengrab from production.
<img width="1693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8516b58cc05f83b58a1bcc372753f050a6e71735/download.PNG" alt="download.PNG" />
