### ISSUE TITLE
 Clean Air Markets Program Data (CAMPD) v1.3 - API - Swagger Changes

### ISSUE THREAD

**Issue by hamezene** [US-EPA-CAMD/PI-1#5982]
From: Heese, Michael <Heese.Michael@epa.gov> 
Sent: Tuesday, December 12, 2023 11:00 AM
To: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov>; Hiwot Amezene <hamezene@decisionpointcorp.com>; Adam.langmaid@erg.com
Cc: Shahbaz Khan <skhan@decisionpointcorp.com>; Justin Joseph <justin.joseph@erg.com>; Ibarra, Michelle <Ibarra.Michelle@epa.gov>; Stetsyuk, Karina (she/her/hers) <Stetsyuk.Karina@epa.gov>; jasonwhitehead@cvpcorp.com; Alex Collado <alexcollado@cvpcorp.com>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

CUI//ISVI

Travis – I’ve looked at the information below and there is a problem with how the Authorization Schemes are defined in the swagger file.  When the scan team is validating the swagger JSON file against the spec it’s failing.  We defined the ClientToken with a scheme of “bearer” and added the “in” and “name” parameters but these parameters are only applicable to the “apiKey” scheme.  Further, there’s a warning that two of the defined schemes are not used.  However, I think they are defined for services that are not published in the swagger file because the services are not intended for public consumption.  For the scan we need to provide a swagger file that contains everything so it get’s scanned properly.  I think the most expedient when to resolve this is to bring CVP and DPC/ERG together to talk through a solution.

Hiwot - I’m cc’ing your team on this email.  We need to look for a time, preferably this afternoon, to get the teams together to discuss a path forward. 

Thanks,
Mike

Controlled by U.S. Environmental Protection Agency
From: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov> 
Sent: Tuesday, December 12, 2023 8:17 AM
To: Heese, Michael <Heese.Michael@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

CUI//ISVI

For reference. Here is what I submitted

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

Controlled by U.S. Environmental Protection Agency
From: Lageman, Travis (he/him/his) 
Sent: Tuesday, December 12, 2023 8:12 AM
To: Smoot, Durrell <Smoot.Durrell@epa.gov>; Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>; Heese, Michael <Heese.Michael@epa.gov>
Cc: Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

Thanks Durrell, I’m looping in Mike to troubleshoot.

Thanks!

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

From: Smoot, Durrell <Smoot.Durrell@epa.gov> 
Sent: Monday, December 11, 2023 10:15 PM
To: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov>; Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Cc: Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

CUI//ISVI

Master data API returned 200s, so it appears the API key works after all!
Now we just need updated API files for the 2 other APIs.

By the way the  UI scan is complete with no Highs.

Controlled by U.S. Environmental Protection Agency
From: Smoot, Durrell <Smoot.Durrell@epa.gov> 
Sent: Monday, December 11, 2023 7:34 PM
To: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov>; Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Cc: Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

CUI//ISVI

Curl screenshot:
 

Controlled by U.S. Environmental Protection Agency
From: Smoot, Durrell 
Sent: Monday, December 11, 2023 7:13 PM
To: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov>; Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Cc: Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

Good evening team,

In preparation to get your APIs completed I checked them against our json validator and came back with the following issues:
In addition, can you please verify that the API key provided is accurate, it looks similar to the key used for the last scans. 

Key:
 

Auth mgmt:
 

 

From: Lageman, Travis (he/him/his) <Lageman.Travis@epa.gov> 
Sent: Monday, December 11, 2023 5:00 PM
To: Miller, Tamu <Miller.Tamu@epa.gov>; App Scan <App_Scan@epa.gov>
Cc: Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Clean Air Markets Program Data (CAMPD) v1.3 - API

CUI//ISVI

Awesome. Thanks so much for the help Tamu! 

Have a great evening!

Travis Lageman
Environmental Policy Analyst
Clean Air Markets Division
U.S. Environmental Protection Agency
P: 202-564-0520

**Comment by shahbazkhan1999** [comment]
working on this and when releasing a new package 
<img width="1343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--162db47d71d892ac7f032fd625cfbdd8e052d496/image.png" alt="image.png" />

**Comment by shahbazkhan1999** [comment]
fixed all the issues and deployed to staging environment now we can test the changes on stage and also fixed the spelling mistake for "Authentication".
<img width="1639" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baf6f2c58727d645b8b78b9c7d6cd3fa546f344d/image.png" alt="image.png" />

<img width="1892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a036e8686e6a3d6a843dd8a396b3c8c5c46b1bea/image.png" alt="image.png" />

**Comment by shahbazkhan1999** [comment]
fixed all the issues and deployed to staging environment now we can test the changes on stage and also fixed the spelling mistake for "Authentication".
<img width="1639" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baf6f2c58727d645b8b78b9c7d6cd3fa546f344d/image.png" alt="image.png" />

<img width="1892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a036e8686e6a3d6a843dd8a396b3c8c5c46b1bea/image.png" alt="image.png" />

**Comment by hamezene** [comment]
@ibarra-michelle
