### ISSUE TITLE
Schema issues with AETB data

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#5985]
Found during regression testing in ecmps-tst.app.cloud.gov v2.0.90.

Logged in as saber_ds (Submitter) and imported RATA test from historical. Exported test to json file, re-imported and re-evaluated and received a critical 2 AETB-10-A error.

The exported data has "airEmissionTestingData" and "airEmissionTestData" fields with the AETB data located in "airEmissionTestingData".

The schema includes "airEmissionTestData". "airEmissionTestingData" is also defined in the MP Reporting Instructions.

Per 12/14/2023 regression testing review meeting with EPA, update the schema to "airEmissionTestingData". The export should only include "airEmissionTestingData".

The export of submitted AETB data also includes the following database fields. Is there a reason for this?

- id
- testSumId
- userId
- addDate
- updateDate

This affects APPE, RATA, and UNITDEF QA test exports.

**Comment by annalbrecht** [comment]
Closing this ticket. Description added to #5992.
