### ISSUE TITLE
RETEST: Update SPAN-17-A import/screen checks

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#5993]
Found during regression testing in ecmps-tst.app.cloud.gov v2.0.90.

Logged in as saber_ds (Submitter), exported MP to json for ORIS 50282, CSPR06 and attempted to reimport.

Received SPAN-17-A import error for null flow full scale range on inactive and very old flow span records.

Checking on inactive records should not happen for this check. 

Note: these records were updated in tst to continue with submission verification. If the data is not refreshed before this is worked on, the issue can be created in the json file to produce the problem.

ORIS 10464, CS-1 is another example with an inactive record for a flow component with a null for flow full scale range.

**Comment by ergjustin** [comment]
Hopefully this pull request has resolved this issue. https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/524

**Comment by esaber76** [comment]
After discussion with Justin, this issue appears to be resolved already. There was an update by CVP to skip checking on inactive records for this around the time this ticket was created. The change was likely already on dev, but not tst yet and during the regression testing effort.

An analyst should reconfirm this on dev and tst with a couple of examples and close the ticket if it is no longer an issue in either environment.

**Comment by mxtomoto1** [comment]
On dev and test, this is confirmed no longer an issue.

Steps taken to test:
1. Check out the listed configurations, and look for null Flow Full Scale Ranges for inactive Span records.
2. Export MP, reimport
3. Evaluate

All exports, reimports, and evaluations were successful.

**Comment by mxtomoto1** [comment]
On dev and test, this is confirmed no longer an issue.

Steps taken to test:
1. Check out the listed configurations (ORIS 50282, CSPR06; ORIS 10464, CS-1), and look for null Flow Full Scale Ranges for inactive Span records.
2. Export MP, reimport
3. Evaluate (evaluation not available on dev due to bypass)

All exports, reimports, and evaluations were successful.
