### ISSUE TITLE
Research: Unable to view/edit units with no monitoring plans

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#5996]
ECMPS 2.0 appears to only display units that have submitted monitoring plans. This affects the ability to see new/future units and build MP's from scratch and/or import a json file for a new MP.

This also affects the ability to create MP's for operating units that have never submitted MP's (ex. MATS-only Hawaii units that historically have only been submitting PDF files).

**Comment by annalbrecht** [comment]
From #6221:
 
See Request tracker ticket #[72607](https://rt.camdsupport.com/rt/Ticket/Display.html?id=72607).

What is being done in ECMPS 1.0 to support the submission of MATS performance tests and quarterly compliance reports for facilities that do not have monitoring plans? For example, ORIS codes 764, 765, and 766 do not have Part 75 monitoring plans.
How are we supporting this scenario in ECMPS 2.0?
As of 04/24/24, I searched for tickets in the Product Backlog and was unsuccessful at identifying tickets related to this scenario.

We need to:

Prioritize this work (Phase 1, P-1B, other)
Gather requirements accordingly.

**Comment by ergjustin** [comment]
In ORIS code 764 has don’t have monitoring plan but it has units. My question is without monitoring plan how we can checkout/open the monitoring plans.

**Comment by djw4erg** [comment]
## Research Results

1. Ticket (https://github.com/US-EPA-CAMD/easey-ui/issues/5995) will allow a user to create a MP for a unit that is not in an MP.
2. For MATS File submissions, a MP is not actually needed, but the import and submission of the files are currently limited to locations in an MP.
   - I suggest that as part of (https://github.com/US-EPA-CAMD/easey-ui/issues/6242) should pull the MATS Submission Data import and submission into a single module.
     - The list of locations for which a file can be imported and submitted should include all location for the facility, regardless of whether it is in an MP.
     - Will need to determine whether multiple files can be import before a submission occurs.
     - The files eligible for submission must include those for locations that are not in an MP.
     - This should cover the issue in https://github.com/US-EPA-CAMD/easey-ui/issues/6221.#6201 
   - **Need to confirm this approach.**

**Comment by djw4erg** [comment]
## Closing Comment

Moving to done since https://github.com/US-EPA-CAMD/easey-ui/issues/5995 and https://github.com/US-EPA-CAMD/easey-ui/issues/6221 handle the issues raised by this ticket.
