### ISSUE TITLE
Create State Entity and Repo

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#601]
- [x] Create state_code entity
- [x] ~~Create state repository~~
  - No longer needs state-code.repository 
  - EntityManager can be used in place of a repository

**Comment by junie-stigdon** [comment]
Pull request [easey-emissions-api/13](https://github.com/US-EPA-CAMD/easey-emissions-api/pull/13) contains both feature/601 and feature/ #603.

- created state-code.entity.ts
- ~~created state-code.repository.ts~~
  - No longer needs state-code.repository: 
  - EntityManager can be used in place of a repository
- updated hourly-apportioned-emissions.module.ts to import StateCode repo
