### ISSUE TITLE
v1.3 scan: Auth Mgmt Med 2

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#6014]
[CampDv1.3APIupdate.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFIrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af924b402aedcfa1d4e23c4a4ce0bc2cbed2f585/CampDv1.3APIupdate.xlsx)

DNS Rebinding allows a malicious host to spoof or redirect a request to an alternate IP address,
potentially allowing an attacker to bypass security authentication or authorization.  DNS resolution
on its own does not properly constitute a valid authentication mechanism.  Servers should validate that
the Host header of the request matches the expected hostname of the server.  In cases where the hostname
is missing or does not match the expected value, the server should return a 400.  The X-Forwarded-Host 
header is sometimes used instead of the Host header in cases where the request is being forwarded.  In
these cases, the X-Forwarded-Host header should also be validated if it is being used to determine the 
Host of the original request.

DNS Rebinding on 'https://api.epa.gov/easey/staging/auth-mgmt/tokens/client/validate'

**Comment by shahbazkhan1999** [comment]
If we validate that the Host header of the HTTP request matches the expected hostname of the server and If the application uses the X-Forwarded-Host header, we validate that it matches the expected hostname.
This step is crucial for cases where requests are forwarded through proxies.

**Comment by spetros-do** [comment]
False Positive. Approved reclassification on 3/4/2024
