### ISSUE TITLE
Validate End date is after Start Date

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#602]
~~- [ ] Create a custom validation pipe~~
~~- [ ] Add the validation and error message to DTO~~
Edit: The tasks above are no longer applicable.

- [x] Validate endDate in the service
- [x] Return proper response and error message

**Comment by junie-stigdon** [comment]
Submitted Pull Request 

- Added validation in the service to check if endDate is greater than or equal to beginDate
- Added a unit test to ensure BadRequestException is being thrown properly
