### ISSUE TITLE
Research - "Create Test Script to Import/Export all MP"

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6021]
- Currently researching on deeply understanding the ECMPS system.
- More specifically on its dependencies, data structures/handling requirements & APIs. 
- Codebase [https://github.com/US-EPA-CAMD/easey-ui/issues/5571] was started with Jason - currently reviewing/analyzing its interfacing with DB [PostgreSQL] and on ECMPS API, focusing on data validation, synchronization & error logging.
--
--
The Original Request dated 08/15/2023: 
-
Context
Create scripts to identify issues with import/export in ECMPS. Jason W. has started some of the work for this. The work Jason has completed is in the EASEY task runner repo. https://github.com/US-EPA-CAMD/easey-task-runner
On 10/18, it was decided that Jason will stop working on this and DPC will looking into continuing the work.
-
Requirements
- Shall create a script that exports clean files from all of the facilities and then successfully imports the files back into the system.
- The script shall have the ability to log errors. This should capture what file failed/when it failed/ why it failed.
- Can execute this by creating a task runner or a cron job
- Can log errors using Kibana or Splunk
- Next Steps: need to have further technical design discussion on how to implement this

----

```

**Comment by annalbrecht** [comment]
Associated with #5571.

**Comment by spetros-do** [comment]
Closing this as a duplicate of #5571
