### ISSUE TITLE
RETEST: CBS Submission Documents not Appearing in CDX Submission History

### ISSUE THREAD

**Issue by mark-hayward-erg** [US-EPA-CAMD/PI-1#6022]
Submissions made from the CBS application (via the EASEY Auth API signature ceremony endpoints) do not result in the submissions documents appearing in the CDX submission history (as happens for submissions made from ECMPS 2.0).

On the CBS side, successful calls are made to the /auth-mgmt/sign/authenticate endpoint, the /auth-mgmt/sign/validate endpoint and the /auth-mgmt/sign endpoint.

We will need to investigate to see what (if any) documents have successfully made it to EASEY and what is happening to them after that.

**Comment by spetros-do** [comment]
Have we identified if the issue is at the submission or retrieval end? As you know, this could help us identify if submissions are being received but not displayed due to config. issues at settings, failed processing or mismatch of data format/validation checks;

**Comment by annalbrecht** [comment]
Need to retest after the ICAM stuff is in place.

**Comment by mark-hayward-erg** [comment]
Cannot be retested until submission logic is completed in CBS.  (CBS currently has a bypass on for submissions.)

Moving to Sprint 6.

**Comment by annalbrecht** [comment]
OBE due to EASEY-368.
