### ISSUE TITLE
Received [RATA-114C] after import QA test from historical data

### ISSUE THREAD

**Issue by ntknguyen** [US-EPA-CAMD/PI-1#6023]

**Comment by ntknguyen** [comment]
Got import errors "[RATA-114C] - You identified [Flow RATA Run] as a run to be used in the calculation of a wall effects adjustment factor, but you did not report a [averageVelocityWithWallEffects]" 
Step to reproduce:
1. Check in Roxboro config 4A,4B,CS004A
2. Import all QA cert test in reporting period 2023Q3

**Comment by annalbrecht** [comment]
Most likely, the stored procedure is missing some of the data that needs to be imported.

**Comment by annalbrecht** [comment]
This is being closed and will be handled via #6024.
