### ISSUE TITLE
Add State Validation

### ISSUE THREAD

**Issue by sdhawan16** [US-EPA-CAMD/PI-1#603]
- [x] Create state validation class and inject repository into class
- [x] Write logic to validate against database 
- [x] Add validation and error message to DTO

**Comment by junie-stigdon** [comment]
- added src/pipes/state-validation.pipes.ts
- added validation to DTO parameter
- updated hour-unit-data.repository to allow state inputs to be lowercase (previously if a state was lowercase, it would return an empty list)

Currently testing before submitting a pull request.

**Comment by junie-stigdon** [comment]
Submitted pull request [easey-emissions-api/13](https://github.com/US-EPA-CAMD/easey-emissions-api/pull/13)
