### ISSUE TITLE
Research: Random refreshes of emissions data

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#6042]
When viewing emissions data, the filter and emissions areas of the screen randomly refresh. We should research why this is occurring and if it was intentional for some reason.

1. Determine what is causing the refresh.
2. Potentially with the team, evaluate why the refresh is occurring and whether it was intentional.
3. Determine needed changes, if any, and generate ticket.

**Comment by ergjustin** [comment]
I couldn't find a random refresh on the emission module. The loading spinner runs when the APIs are in the load state. May be this refresh issue was fixed due to [view template change](https://github.com/US-EPA-CAMD/easey-ui/issues/5945).

**Comment by alangmaid** [comment]
Unable to recreate in dev.
