### ISSUE TITLE
Log drain dropped in lower environments

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#6047]
[FW FYI - FW Missing epa-easey log drain .txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3d67bdb222c02a5603b28a4aa90a7e0ec178e68/FW%20FYI%20-%20FW%20Missing%20epa-easey%20log%20drain%20.txt)

**Comment by alangmaid** [comment]
See attached email for specifics

**Comment by spetros-do** [comment]
Key issue:
- log drain service was unfortunately dropped during re/deployment process of the 1.3 release branch.   
Proposed solution(s): 
- run the required commands in each repository (log drain service bound in the manifest).
- test to ensure log drain service is functioning as expected. 
- add the log configuration to the 'manifrest.yml' files of the affected applications in the release 1.3 branch. This will ensure that log drain service is included in future deployment and maintain strict version control moving forward.

**Comment by kstetsyuk** [comment]
@spetros-do keep me in the loop. I'll take care of the facility-map. Thx!

**Comment by spetros-do** [comment]
@kstetsyuk - confirming will do. Thx!

**Comment by spetros-do** [comment]
Update have been completed. except for **facility-map** application. 
What's left is to check if the log is visible on the log files. Will request support on this from EPA/DRG team.  
cmd used: 
- cf bind-service [target application name] log-drain (for each "Space Name" that was missing the service)

**Comment by maheese** [comment]
@spetros-do I checked Splunk and everything is there.  Thanks!

**Comment by kstetsyuk** [comment]
Everything is working in lower environments for the facility map. I added the service to the manifest it's ready to go for the next deployment to prod. @spetros-do @maheese
