### ISSUE TITLE
Annual Task: Generate CAMDDMW Year Based Partitions for 2025

### ISSUE THREAD

**Issue by djw4erg** [US-EPA-CAMD/PI-1#6065]
Generate the **2025** year based partitions for the following tables using the CAMDDMW.CREATE_PARTITIONS procedure.

- ALLOWANCE_HOLDING_DIM: [EASEY-UI #6030](https://app.zenhub.com/workspaces/dpcerg-scrum-board-5f36cc8dfed6db0022b0f4db/issues/gh/us-epa-camd/easey-ui/6030) will add this table to the procedure.  **Note that for this table the partitions are required through 30 years in the future.**
- ANNUAL_UNIT_DATA
- CONTROL_YEAR_DIM
- DAY_UNIT_DATA
- FUEL_YEAR_DIM
- HOUR_UNIT_DATA
- HOUR_UNIT_MATS_DATA
- MONTH_UNIT_DATA
- OZONE_UNIT_DATA
- PROGRAM_YEAR_DIM
- QUARTER_UNIT_DATA
- REP_YEAR_DIM: [EASEY-UI #6030](https://app.zenhub.com/workspaces/dpcerg-scrum-board-5f36cc8dfed6db0022b0f4db/issues/gh/us-epa-camd/easey-ui/6030) will add this table to the procedure.
- UNIT_FACT
- UNIT_TYPE_YEAR_DIM

**Comment by szintgraff** [comment]
Updated Status to New Tickets and Added to P1-B to bring this back to attention.

**Comment by annalbrecht** [comment]
Blocked by #6030

**Comment by mark-hayward-erg** [comment]
Completed on staging and prod.
