### ISSUE TITLE
Research: ECMPS 2.0 Events and Emails

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#6071]
During regression testing, we were unable to test many of the functions that were previously handled by CAT_MAINTENANCE. For example, creation of pending windows, creation of new submission windows, etc.

Per 1/22/2024 meeting with EPA, Chris would like DPC/ERG to do a thorough review of the quartz jobs that CVP developed. 

We need to identify what still needs to be developed and tested in relation to ECMPS 2.0 events.

**Comment by alangmaid** [comment]
blocked by review of Quartz job #6063, #5910, #5826, and #6183

**Comment by annalbrecht** [comment]
We think everything is covered by other tickets. Closing this one.
