### ISSUE TITLE
ZenHub Export of Data Sets/Issue Tickets

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6090]

**Comment by spetros-do** [comment]
Research ZenHub's current offerings for Issue Tickets visualization capabilities.
Since ZenHub uses Boards (Kanban-style) and Reports to visualize the workflow of issue tickets & PR directly within GitHub, the goal is to:
- Identity and map-out the scope of data available 
- Format(s) the data can be exported based
- What plug-ins are currently available to make this process seamless
- Have the export data set available on CSV format  
- Moving forward, to identify & map-out key fields needed for JIRA Pilot project that will be used as target data source

**Comment by spetros-do** [comment]
Zenhub not functional to support data migration for the following reasons: 
- Very limited import/export functionality
- Does not support RESTAPI any longer; only connection allowed is via GraphQL with literally no documentation. 
- Major issues with Access Permissions, Workspace Complexity and more...
- Decided to pursue via GitHub & scripting and was able to migrate issue tickets with serval filters that could be customized further based on user request. As a sample, I have attached 2 csv dumps for reference that goes back to 3 years. 
- Only suggestion I have is for a validation via a different user to make sure issue numbers match exactly on the GUI side. @Zenhub Workspace. 
- 
[CAMP_UI_GitHub Issues.csv](https://github.com/US-EPA-CAMD/easey-ui/files/14222842/CAMP_UI_GitHub.Issues.csv)
[ECMPS_UI_GitHub Issues.csv](https://github.com/US-EPA-CAMD/easey-ui/files/14222843/ECMPS_UI_GitHub.Issues.csv)

**Comment by annalbrecht** [comment]
We need an export of:

- all repos
- all time
- open only

- ticket #
- title
- label
- created by
- description
- comments

**Comment by spetros-do** [comment]
Completed

**Comment by jasonflaherty** [comment]
@spetros-do , just curious, we are trying to export ZenHub data to csv. _"Decided to pursue via GitHub & scripting and was able to migrate issue tickets with serval filters that could be customized further based on user request."_ Did you do this utilizing GitHub actions or the like, or directly in GH which doesn't even look at ZenHub, but just the issues in GH?

**Comment by spetros-do** [comment]
Hi Jason,

I used GitHub & scripting to fetch the data...you are correct, it doesn't even look at ZenHub.


Warm regards,

Samuel Petros

Program Manger / Sr. Software Developer

DecisionPoint Corporation

702 Russell Avenue Suite 312 | Gaithersburg, MD 20877

11911 Freedom Drive Suite 610 | Reston, VA 20190

c: 913-249-9343

***@***.******@***.***>

www.decisionpointcorp.com<http://www.decisionpointcorp.com/>

[A picture containing text, sign  Description automatically generated]

[cid:4f8ee70a-19c5-47eb-bf6a-2a16b3d72bb4]

The contents of this email message and any attachments are confidential and intended solely for the use of the addressee(s) or entity to which they are addressed. If you are not the intended recipient of this message, please notify the sender immediately. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.



________________________________
