### ISSUE TITLE
Bug: emissions api crash after importing an emissions file

### ISSUE THREAD

**Issue by j-tafoya** [US-EPA-CAMD/PI-1#6100]
When importing the attached emissions file with a duplicate value, ECMPS 2.0 beta says it was imported successfully, but it silently crashes in the backend.

The API should not attempt to insert the value if it's a duplicate and the successful message should only appear after successfully importing the data into the table.

Steps to reproduce: 
1. Check out ORIS: 55233 Configuration: EU-1A, EU-1B, EU-2A, EU-2B, EU-3A, EU-3B, EU-4A, EU-4B, EU-5A, EU-5B, CP100
2. Navigate to the emissions module
3. Import json file

[Emissions _ Export - Handsome Lake Energy (EU-1A, EU-1B, EU-2A, EU-2B, EU-3A, EU-3B, EU-4A, EU-4B, EU-5A, EU-5B, CP100)  - 2023 - Q2.json](https://github.com/US-EPA-CAMD/easey-ui/files/14451724/Emissions._.Export.-.Handsome.Lake.Energy.EU-1A.EU-1B.EU-2A.EU-2B.EU-3A.EU-3B.EU-4A.EU-4B.EU-5A.EU-5B.CP100.-.2023.-.Q2.json)

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/65174118/a37b0a47-1e5c-4efe-a564-3d3c3c553f36)

**Comment by shahbazkhan1999** [comment]
Fixed by [#453](https://github.com/US-EPA-CAMD/easey-emissions-api/pull/453).
Resolved by removing duplicates from `emissionImports.summaryValue` which violated `uq_summary_value` constraint on `camdecmpswks.summary_value` table.
Further improvements suggested:

- Upload JSON data file as multipart/form-data.
- Use SSE to report the progress of uploaded file which will also prevent ConnectionTimeout on huge files.

**Comment by mxtomoto1** [comment]
Emissions file was imported successfully according to the UI on dev, but I do not have backend access.

**Comment by annalbrecht** [comment]
It seems as if the duplicate record is now just being ignored. The previous changes need to be rolled back. Duplicate records should cause an error to be generated saying there is a duplicate and the file should not be imported.

This should be reviewed universally to make sure it is working properly in all areas.

In ECMPS 1.0 this is a FATAL import error.

**Comment by annalbrecht** [comment]
@mxtomoto1 In CHET, identify where we are doing duplicate import checks now and provide a list.

**Comment by mxtomoto1** [comment]
Import checks that address duplicates:

- IMPORT-20: This check is to identify duplicate tests reported by Location ID, TestTypeCode and TestNumber.
- IMPORT-21: This check is to identify duplicate checks by Test Number containing different data than in the Test in the file to be imported.
- LME-46: Checks the LME Hourly Op import rows to determine whether duplicate rows exist.

**Comment by annalbrecht** [comment]
- In these situations, the user should receive an error saying there is a duplicate record and the file cannot be imported. Need technical requirements.
- If an API crash or exception occurs, the user should be notified and told to contact support.
- Long term, we may want specific import checks for the different EM records.

For now, create 3 new tickets for these changes and then move this ticket to Done and Close it.

**Comment by mxtomoto1** [comment]
Creation of subsequent tickets #6202, #6203, #6204 to follow up.
