### ISSUE TITLE
Datamart nightly job failed to Update Tables (RT 74078)

### ISSUE THREAD

**Issue by shahbazkhan1999** [US-EPA-CAMD/PI-1#6105]
CAMPD is having a production issue (RT 74078). A user reported this early this morning. It appears the emissions data is saying there is no data available regardless of what date you put in. You are unable to get past picking the year. I have also tried this directly in the APIs and got a response with no data. This appears for all of the emission types, not just hourly. 

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/136729393/cb768dbe-5a5b-4699-b427-8805297059be)

Issue was traced to the fact that the nightly Datamart CDC job failed with the following error:

```
Message: Database driver error...
CMN_1022 [truncate camddmw.unit_fact cascade
 
FnName: Execute Direct -- [Informatica][ODBC PostgreSQL Wire Protocol driver]Socket closed., SQLSTATE [08S01]
]
```

**Comment by mark-hayward-erg** [comment]
Vamshi will be re-running the Datamart CDX job and will report back when it has completed.

**Comment by mark-hayward-erg** [comment]
Additionally, pending changes to the Datamart nightly job that are in the CDC development environment include updates to the email 
notification logic to include additional people in error notifications.

**Comment by shahbazkhan1999** [comment]
Vamshi  re-run the Datamart CDX job and now we can see the Data


![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/136729393/26d35446-0919-426d-9b43-6c1ba23e1fae)

**Comment by alangmaid** [comment]
Linked with #6109

**Comment by annalbrecht** [comment]
This will be handled by #6109, so closing this ticket.
