### ISSUE TITLE
FEATURE: Update MP UI to New Template 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#611]
## Feature Benefit
Bring UI up to date with new "go wide" template 

Original estimate: 21 
## Context

[Updated wireframes](https://xd.adobe.com/view/ccf2dda8-0f33-4df9-a581-6556fbdedeb9-99a1/) (2/26)

Implement Go wide template (does not included mobile)

1. Account management will appear but not be functional
2. Profile not active 
3. CAMD Apps not active
4. Emissions and QA links not active 
5. Implement new header and footer (included menu options in header/footer. Content available on current EPA website). Includes official website banner. 
6. Search in header only searches EPA.gov content, search results are displayed via redirect to EPA.gov content 

Relabel Import MP button
Add Select Facilities section label
Tab Navigation
508 Updates  (visual updates will be covered by updated wireframes, may need "behind the scenes" updates)
Address MP business glossary and wireframes discrepancies 

@cvp-alexrobinson, @addisgmichael, @Qb10, @mosesdeeCVP, and @davidkwartler
The approach going forward is as follows:
1. Any term reported as a code should have the compact version displayed with a hover feature showing the expanded version.
2. Any non-code term should be spelled out, like states.
3. Row and column headers should be spelled out.

| Wireframe Term | Wireframe Format  | Business Glossary Format | BG Cell Location | Required Format  |
|----:|----:|----:|----:|----:|
| Facility | Gas Now | N/A | N/A | Follow Wireframe Format |
| State  |Florida   | N/A  |   N/A|  Follow Wireframe Format |
|Parameter |CO2 Mass (ton)  |CO2, CO2M, H2O |  G105 | Display BG Format; Use Wireframe Format as hover text  |
|Methodology |Low Mass Emissions, Exempt |AD, CEM, EXP  | G89  | Display BG Format; Use Wireframe Format as hover text |
|Substitute Data Approach  |Maximum Rated Hourly Input Rate  | FSP75, FSP75C, SPTS, MHHI  | G131 | Display BG Format; Use Wireframe Format as hover text |
|Evaluation Status  |12/8/2020, 3:45pm EST | N/A | N/A  |MM/DD/YYYY HH:MM Hours are displayed in military time (ex: 23:00) Minutes are displayed when they are available in the source data (not all source data will be tracked down to the minute)|
| Bypass Approach | N/A | BYMAX, BYMAXFS | G26 |  X |
| Begin Date and Time | 05/16/2000: 12 | N/A | N/A (BG Format separates date and time) |  Follow Wireframe Format |
| End Date and Time | 05/16/2000: 12 | N/A | N/A (BG Format separates date and time) |  Follow Wireframe Format |
| System ID | XX# | XX# | F133 |  They are the same |
| System Type | SO2 Concentration | SO2 Concentration | F135 |  They are the same. BG includes a compact version based on Table 20: System Type Codes and Descriptions. Display compact version and use expanded as hover text. |
| System Designation | Primary | Primary | F132 |  They are the same. BG includes a compact version based on Table 21: System Designation Codes and Descriptions. Display compact version and use expanded as hover text. |
| Fuel Type | Non-Fuel Specific | Non-Fuel Specific | F72 |  They are the same. BG includes a compact version based on Table 56: Monitoring Default Fuel Codes and Descriptions. Display compact version and use expanded as hover text. |

**Comment by davidkwartler** [comment]
@addisgmichael 
https://search.epa.gov/epasearch/?querytext=test

**Comment by JorjaComer** [comment]
All issues prioritized for work in PI 3 are complete. Moved 508 issue to #1045. #994 , #885 , and #874 were moved from the feature and added to PI 4 as stand alone issues.
