### ISSUE TITLE
Research: Identify MATS bulk file functionality missing from 2.0

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6114]
Using 1.0 as the model, identify any MATS bulk file functionality that needs to be added or modified in 2.0.

The MATS PDF/XML/JSON file module shows metadata for standard QA tests, not the tests that get submitted for bulk files. This is wrong and needs to be fixed. 

Document_submission_log in the DB will have the XML. Or review the MATS XSD.

**Comment by lgiannini1** [comment]
MATS Data Submission Functionality from 1.0 missing in 2.0:

- Averaging Group Dropdown. Options should be:
     - The EGU(s) or monitored common stack is/are not in an emissions averaging group
     - The EGU(s) or monitored common stack is/are in a 30-boiler operating day averaging group
     - The EGU(s) or monitored common stack is/are in a 90-boiler operating day averaging group
- The Test Type dropdown in 2.0 needs to be updated to show the following tests. In 1.0, this field is called the Report Type:
     - RATA of an HCl, HF, SO2, or Hg Monitoring System
     - RCA of a PM CEMS
     - RRA of a PM CEMS
     - 30-Day Rolling Averages (for PM CEMS, PM CPMS, and HAP metals CEMS only)
     - Compliance Report
     - Notification of Compliance Status
     - Quarterly or Annual Performance Stack Test
     - LEE Qualification Test
     - LEE Ongoing Demonstration Test
     - PM CEMS PS-11 Correlation Test
- Pollutant Selections. User should be able to select one or more at a time.
     - Filterable Particulate Matter
     - Hydrogen Chloride
     - Hydrogen Fluoride
     - Mercury
     - Sulfur Dioxide
     - Antimony (Sb)
     - Arsenic (As)
     - Beryllium (Be)
     - Cadmium (Cd)
     - Chromium (Cr)
     - Cobalt (Co)
     - Lead (Pb)
     - Manganese (Mn)
     - Nickel (Ni)
     - Selenium (Se) 
- Test Method Selections. User should be able to select one or more at a time.
     - Method 1
     - Method 2
     - Method 2A
     - Method 2C
     - Method 2F
     - Method 2G
     - Method 2H
     - Method 3
     - Method 3A
     - Method 3B
     - Method 4
     - Method 5
     - Method 5B*
     - Method 5D
     - Method 5I
     - Method 6C
     - Method 17
     - Method 19
     - Method 26
     - Method 26A
     - Method 29
     - Method 30B
     - Method 320
     - Method CTM-041
     - ASTM- D6348-03
     - ANSI/ASME PTC19.10-1981
     - ASTM D6784-02- (Ontario Hydro Method)
- Facility Address, Facility City, Facility State, and Facility Zip Code text fields
- Test Date field
- Test Comment text field

**Comment by lgiannini1** [comment]
Created development ticket #6242 to add the features from the comment above. Closing this ticket.
