### ISSUE TITLE
Research: Update Response Catalog Messages (EC-3962)

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6120]
Update Response Catalog rows to correct the following issues:

Review message containing references to the: “Client”, “Host”, “Download”, “Upload” or “Retrieve” “synchronize” “software” “local/local database” “login, logging in, log into”

Other messages that are ECMPS-specific

Message does not clearly identify the data item with the problem when it results from an import check instead of a screen check. ~2000 to review

Look for messages that appear to not provide enough information to identify what the record is. 

LOE Identify messages: 16 hours. Generate spreadsheet of problematic messages.  

LOE Make text changes: in EC-3963.

**Comment by annalbrecht** [comment]
Term Query Template:

```
select  rsp.RESPONSE_CATALOG_ID,
        rsp.RESPONSE_CATALOG_DESCRIPTION,
        lst.SEARCH_TERM,
        rsp.RESPONSE_TYPE_CD
        , rsp.*
  from  (
            select 'host' SEARCH_TERM union all
            select 'download' SEARCH_TERM union all
            select 'upload' SEARCH_TERM union all
            select 'retrieve' SEARCH_TERM union all
            select 'synchronize' SEARCH_TERM union all
            select 'software' SEARCH_TERM union all
            select 'local' SEARCH_TERM  union all
            select 'login' SEARCH_TERM 
        ) lst
        join RESPONSE_CATALOG rsp on upper(rsp.RESPONSE_CATALOG_DESCRIPTION) like upper(concat('%', lst.SEARCH_TERM, '%'))
 order
    by  rsp.RESPONSE_CATALOG_ID,
        lst.SEARCH_TERM
```

**Comment by lgiannini1** [comment]
Spreadsheet containing the results from the above query are attached. There are also a few messages that mention CAMD that need to be updated. 

[response_catalog_202405091226.xlsx](https://github.com/US-EPA-CAMD/easey-ui/files/15275407/response_catalog_202405091226.xlsx)

**Comment by lgiannini1** [comment]
Created ticket #6255 and closing this ticket.
