### ISSUE TITLE
Mid-Season Ozone Season (OS) Start (non-GNP/MATS checks from 1.0)

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6122]
## Overview
Some checks not associated with GNP & MATS have been added/updated in 1.0 but have not yet been incorporated into 2.0. These need to be moved over.

**CAPD (Charlie Frushour) indicated in the June 13, 2024 ECMPS Support Meeting that we should delay this change indefinitely.**

### Affected ECMPS 1.0 Tickets

- [**EC-3923**: Updates to Handle New OS Programs that Begin Mid-Season](https://camddevelopment.atlassian.net/browse/EC-3923)
- [**EC-3955**: Add CSOSG2E to ECMPS.Lookup.PROGRAM_CODE](https://camddevelopment.atlassian.net/browse/EC-3955): Already included in ECMPS 2.0.

#### Background

[EC-3923](https://camddevelopment.atlassian.net/browse/EC-3923) was implemented in the 2023 Q2 ECMPS 1.0 Release.  Its purpose was to allow the C-SAPR NOx OS Group 3 (CSOSG3) Program to begin in the middle of the 2023 ozone season (OS) for Minnesota, Nevada and Utah.  These three states were not previously affected by OS programs, and unlike other OS programs or states, CSOSG3 would have began in the middle of the OS for these three states.  To allow for this, ECMPS 1.0, which was built on the understanding that OS programs would not start in the middle of OS, was changed to allow mid-season starts.

Based on a July 7th, 2023 email from Chris Worley, Minnesota and Nevada received stay orders for CSOSG3 that results in sources for both states not needing to report for 2023.  

### Acceptance Tests

[Acceptance Test Comment](https://github.com/US-EPA-CAMD/easey-ui/issues/6122#issuecomment-2161750997)

### Proposed Resolution

Because mid-season OS starts are not currently needed, ERG proposes that CAPD suspends or delays the implementation of the [EC-3923](https://camddevelopment.atlassian.net/browse/EC-3923) changes in ECMPS 2.0.

Because [EC-3955](https://camddevelopment.atlassian.net/browse/EC-3955) has already been implemented in ECMPS 2.0, _suspending or delaying [EC-3923](https://camddevelopment.atlassian.net/browse/EC-3923) would result in either closing this ticket or moving it 2025 or beyond._

**CAPD (Charlie Frushour) indicated in the June 13, 2024 ECMPS Support Meeting that we should delay this change indefinitely.**

### 2023 Q2 ([EC-3923](https://camddevelopment.atlassian.net/browse/EC-3923): CSOSG3)

- **Check Changes**
  - **EMGEN**: 1, 5, 7, 8 and 9.
  - **HOURAGG**: 12, 14, 15 and 16.
  - **HOURAPP**: 3 and 4.
  - **HOURCV**: 7 and 16.
  - **HOURDHV**: 40 and 44.
  - **HOURGEN**: 1 and 2.
  - **HOUROP**: 1
  - **LME**: 42
- **Net Changes**
  - CheckEngine/**CheckData**.cs
  - CheckEngine/GeneratedParameterClasses/**EmGenerationParameters**.cs
  - Emissions/EmissionReport/**EmissionsReportProcess**.cs
  - Emissions/EmissionReport/Checks/**HourlyAggregationChecks**.cs
  - Emissions/EmissionReport/Checks/**HourlyApportionmentChecks**.cs
  - Emissions/EmissionReport/Checks/**HourlyCalculatedDataChecks**.cs
  - Emissions/EmissionReport/Checks/**HourlyDerivedValueChecks**.cs
  - Emissions/EmissionReport/Checks/**HourlyGeneralChecks**.cs
  - Emissions/EmissionReport/Checks/**HourlyOperatingDataChecks**.cs
  - LME/LMEChecks.cs
  - Emissions/NonOperatingEmissionGeneration/**cGenerationChecks**.cs
  - Emissions/NonOperatingEmissionGeneration/**cGenerationParameters**.cs
- **Database Data Changes**
  - [CHECK_CATALOG](https://github.com/US-EPA-CAMD/easey-ui/issues/6122#issuecomment-2161577267)
  - [CHECK_CATALOG_PARAMETER](https://github.com/US-EPA-CAMD/easey-ui/issues/6122#issuecomment-2161629932)
  - [CHECK_PARAMETER_CODE](https://github.com/US-EPA-CAMD/easey-ui/issues/6122#issuecomment-2161669229)

### 2023 Q3 ([EC-3955](https://camddevelopment.atlassian.net/browse/EC-3955): CSOSG2E)

- **Database Changes**
  - PROGRAM_CODE (CSOSG2E)

**Comment by djw4erg** [comment]
### CHECK_CATALOG Rows

#### Rows to Delete

| Primary Key | Check Code | Check Name |
| ---: | :--- | :--- |
 | 10439 | HOURAGG-12 | April_NOX_Mass_Calculated_Accumulator_Array | REQ | 2131 | 2832
 | 10460 | HOURAGG-14 | April_HI_Calculated_Accumulator_Array | REQ | 2133 | 2829
 | 10470 | HOURAGG-15 | April_Op_Time_Accumulator_Array | REQ | 2134 | 2834
 | 10489 | HOURAGG-16 | April_Op_Hours_Accumulator_Array | REQ | 2135 | 2835

#### Rows with Changes

| Primary Key | Check Code | Check Name |
| ---: | :--- | :--- |
 | 2336 | EMGEN-1 | Initialize Emissions Generation for Location | 
 | 2340 | EMGEN-5 | Generate NOx Mass YTD and OS Values | 
 | 2342 | EMGEN-7 | GenerateTotal Heat Input YTD and OS Values | 
 | 2343 | EMGEN-8 | Generate Operating Time YTD and OS Values | 
 | 2344 | EMGEN-9 | Generate Operating Hours YTD and OS Values | 
 | 2131 | HOURAGG-12 | Compare NOx Mass YTD and OS Values | 
 | 2133 | HOURAGG-14 | Compare Total Heat Input YTD and OS Values | 
 | 2134 | HOURAGG-15 | Compare Operating Time YTD and OS Values | 
 | 2135 | HOURAGG-16 | Compare Operating Hours YTD and OS Values | 
 | 1732 | HOURAPP-3 | Calculate Apportioned or Summed Heat Input Rate | 
 | 2029 | HOURAPP-4 | Calculate NOx Mass Rate from Apportioned or Summed Heat Input Rate | 
 | 821 | HOURCV-7 | Calculate Heat Input | 
 | 814 | HOURCV-16 | Calculate NOx Mass Emissions | 
 | 2140 | HOURDHV-40 | Determine Fuels Burned for LME Unit | 
 | 2146 | HOURDHV-44 | Calculate NOX Mass for LME Unit | 
 | 1702 | HOURGEN-1 | Initialize Accumulators, Dictionaries and Lists | 
 | 1815 | HOURGEN-2 | Reporting Period Details | 
 | 535 | HOUROP-1 | Validate Single Operating Data record for hour | 
 | 2137 | LME-42 | Check LTFF Total Heat Input |

**Comment by djw4erg** [comment]
### CHECK_CATALOG_PARAMETER Rows with Changes

| Primary Key | Check Code | Parameter Name | Usage | Check Catalog Key | Check Param Key |
| ---: | :--- | :--- | :--- | ---: | ---: |
 | 16652 | EMGEN-1 | Location_Program_Records | REQ | 2336 | 301
 | 16653 | EMGEN-1 | OS_Active_Program_Earliest_UMCBD | OUT | 2336 | 4747
 | 16654 | EMGEN-5 | OS_Active_Program_Earliest_UMCBD | REQ | 2340 | 4747
 | 16655 | EMGEN-7 | OS_Active_Program_Earliest_UMCBD | REQ | 2342 | 4747
 | 16656 | EMGEN-8 | OS_Active_Program_Earliest_UMCBD | REQ | 2343 | 4747
 | 16657 | EMGEN-9 | OS_Active_Program_Earliest_UMCBD | REQ | 2344 | 4747
 | 16642 | HOURAGG-12 | OS_Active_Program_Earliest_UMCBD | REQ | 2131 | 4747
 | 16623 | HOURAGG-12 | OS_NOXM_Calculated_Accumulator_Array | REQ | 2131 | 4743
 | 16647 | HOURAGG-12 | OS_NOXM_Calculated_Quarterly_Value | OUT | 2131 | 4748
 | 16637 | HOURAGG-12 | OS_Reporting_Period_Begin_Date | REQ | 2131 | 4746
 | 16643 | HOURAGG-14 | OS_Active_Program_Earliest_UMCBD | REQ | 2133 | 4747
 | 16617 | HOURAGG-14 | OS_HIT_Calculated_Accumulator_Array | REQ | 2133 | 4742
 | 16648 | HOURAGG-14 | OS_HIT_Calculated_Quarterly_Value | OUT | 2133 | 4749
 | 16638 | HOURAGG-14 | OS_Reporting_Period_Begin_Date | REQ | 2133 | 4746
 | 16644 | HOURAGG-15 | OS_Active_Program_Earliest_UMCBD | REQ | 2134 | 4747
 | 16631 | HOURAGG-15 | OS_Op_Time_Calculated_Accumulator_Array | REQ | 2134 | 4745
 | 16649 | HOURAGG-15 | OS_OPTIME_Calculated_Quarterly_Value | OUT | 2134 | 4750
 | 16639 | HOURAGG-15 | OS_Reporting_Period_Begin_Date | REQ | 2134 | 4746
 | 16645 | HOURAGG-16 | OS_Active_Program_Earliest_UMCBD | REQ | 2135 | 4747
 | 16630 | HOURAGG-16 | OS_Op_Hours_Calculated_Accumulator_Array | REQ | 2135 | 4744
 | 16650 | HOURAGG-16 | OS_OPHOURS_Calculated_Quarterly_Value | OUT | 2135 | 4751
 | 16640 | HOURAGG-16 | OS_Reporting_Period_Begin_Date | REQ | 2135 | 4746
 | 16616 | HOURAPP-3 | OS_HIT_Calculated_Accumulator_Array | REQ | 1732 | 4742
 | 16618 | HOURAPP-3 | OS_Reporting_Period_Begin_Date | REQ | 1732 | 4746
 | 16624 | HOURAPP-4 | OS_NOXM_Calculated_Accumulator_Array | REQ | 2029 | 4743
 | 16625 | HOURAPP-4 | OS_Reporting_Period_Begin_Date | REQ | 2029 | 4746
 | 16619 | HOURCV-7 | OS_HIT_Calculated_Accumulator_Array | REQ | 821 | 4742
 | 16620 | HOURCV-7 | OS_Reporting_Period_Begin_Date | REQ | 821 | 4746
 | 16626 | HOURCV-16 | OS_NOXM_Calculated_Accumulator_Array | REQ | 814 | 4743
 | 16627 | HOURCV-16 | OS_Reporting_Period_Begin_Date | REQ | 814 | 4746
 | 16621 | HOURDHV-40 | OS_HIT_Calculated_Accumulator_Array | REQ | 2140 | 4742
 | 16622 | HOURDHV-40 | OS_Reporting_Period_Begin_Date | REQ | 2140 | 4746
 | 16628 | HOURDHV-44 | OS_NOXM_Calculated_Accumulator_Array | REQ | 2146 | 4743
 | 16629 | HOURDHV-44 | OS_Reporting_Period_Begin_Date | REQ | 2146 | 4746
 | 16611 | HOURGEN-1 | OS_HIT_Calculated_Accumulator_Array | OUT | 1702 | 4742
 | 16612 | HOURGEN-1 | OS_NOXM_Calculated_Accumulator_Array | OUT | 1702 | 4743
 | 16613 | HOURGEN-1 | OS_Op_Hours_Calculated_Accumulator_Array | OUT | 1702 | 4744
 | 16614 | HOURGEN-1 | OS_Op_Time_Calculated_Accumulator_Array | OUT | 1702 | 4745
 | 16636 | HOURGEN-2 | Current_Reporting_Period_Begin_Date | REQ | 1815 | 4630
 | 16635 | HOURGEN-2 | Current_Reporting_Period_End_Date | REQ | 1815 | 4631
 | 16641 | HOURGEN-2 | OS_Active_Program_Earliest_UMCBD | OUT | 1815 | 4747
 | 16615 | HOURGEN-2 | OS_Reporting_Period_Begin_Date | OUT | 1815 | 4746
 | 16632 | HOUROP-1 | OS_Op_Hours_Calculated_Accumulator_Array | REQ | 535 | 4744
 | 16633 | HOUROP-1 | OS_Op_Time_Calculated_Accumulator_Array | REQ | 535 | 4745
 | 16634 | HOUROP-1 | OS_Reporting_Period_Begin_Date | REQ | 535 | 4746
 | 16659 | LME-42 | OS_HIT_Calculated_Accumulator_Array | REQ | 2137 | 4742

**Comment by djw4erg** [comment]
### CHECK_PARAMETER_CODE Rows with Changes

Note that the **Source Table** column is null for these rows.

| Primary Key | Name / Description / Display Name | Data Type | Param Type | Object Type |
| ---: | :--- | :--- | :--- | :--- |
| 4742 | `OS_HIT_Calculated_Accumulator_Array` / `Array containing ozone season HIT accumulated value for each location.` / `OS HIT Calculated Accumulator Array` | OBJECT | AGGARRY | decimal?[] |
| 4749 | `OS_HIT_Calculated_Quarterly_Value` / `The recalculated ozone-season quarterly value for total heat input.` / `OS HIT Calculated Quarterly Value` | DECIMAL | OUTPUT |  |
| 4743 | `OS_NOXM_Calculated_Accumulator_Array` / `Array containing ozone season NOXM accumulated value for each location.` / `OS NOXM Calculated Accumulator Array` | OBJECT | AGGARRY | decimal?[] |
| 4748 | `OS_NOXM_Calculated_Quarterly_Value` / `The recalculated ozone-season quarterly value for NOx Mass.` / `OS NOXM Calculated Quarterly Value` | DECIMAL | OUTPUT |  |
| 4744 | `OS_Op_Hours_Calculated_Accumulator_Array` / `Array containing ozone season Op Hours accumulated value for each location.` / `OS Op Hours Calculated Accumulator Array` | OBJECT | AGGARRY | int?[] |
| 4745 | `OS_Op_Time_Calculated_Accumulator_Array` / `Array containing ozone season Op Time accumulated value for each location.` / `OS Op Time Calculated Accumulator Array` | OBJECT | AGGARRY | decimal?[] |
| 4751 | `OS_OPHOURS_Calculated_Quarterly_Value` / `The recalculated ozone-season quarterly value for total operating hours.` / `OS OPHOURS Calculated Quarterly Value` | INTEGER | OUTPUT |  |
| 4750 | `OS_OPTIME_Calculated_Quarterly_Value` / `The recalculated ozone-season quarterly value for total operating time.` / `OS OPTIME Calculated Quarterly Value` | DECIMAL | OUTPUT |  |
| 4746 | `OS_Reporting_Period_Begin_Date` / `When OS Reporting Required is true, the date to use as the beginning of OS reporting in the emission report.  Usually the first date of the quarter, but if the earliest UMCBD for an associated OS program is in the quarter, then it is that date.` / `OS Reporting Period Begin Date` | DATE | OUTPUT |  |

**Comment by djw4erg** [comment]
## Acceptance Tests

_Copied from EC-3923_

- [ ] HOURAGG-12
  - [ ] Confirm some example results fire/don’t fire as expected
    - [ ] Result C
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result G
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result H
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result I
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
- [ ] HOURAGG-14
  - [ ] Confirm some example results fire/don’t fire as expected
    - [ ] Result C
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result G
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result H
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result I
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
- [ ] HOURAGG-15
  - [ ] Confirm some example results fire/don’t fire as expected
    - [ ] Result C
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result F
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result G
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result H
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
- [ ] HOURAGG-16
  - [ ] Confirm some example results fire/don’t fire as expected
    - [ ] Result C
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result F
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result G
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
    - [ ] Result H
      - [ ] Fires as expected
      - [ ] Doesn’t fire as expected
- [ ] HOURAPP-3
  - [ ] Run example file through **_OS HIT Calculated Accumulator Array_** for this location = **_OS HIT Calculated Accumulator Array_** for this location + ( **_HI Calculated Apportioned Value_** * **_Apportionment OpTime Array_** for this Location ) _path 1_ and confirm no issues
  - [ ] Run example file through **_OS HIT Calculated Accumulator Array_** for this location = **_OS HIT Calculated Accumulator Array_** for this location + ( **_HI Calculated Apportioned Value_** * **_Apportionment OpTime Array_** for this Location ) _path 2_ and confirm no issues
  - [ ] Run example file through **_OS HIT Calculated Accumulator Array_** for this location = **_OS HIT Calculated Accumulator Array_** for this location + ( **_HI Calculated Apportioned Value_** * **_Apportionment OpTime Array_** for this Location ) _path 3_ and confirm no issues
  - [ ] Run example file through **_OS HIT Calculated Accumulator Array_** for this location = **_OS HIT Calculated Accumulator Array_** for this location + ( **_HI Calculated Apportioned Value_** * **_Apportionment OpTime Array_** for this Location ) _path 4_ and confirm no issues
  - [ ] Run example file through **_OS HIT Calculated Accumulator Array_** for this location = **_OS HIT Calculated Accumulator Array_** for this location + ( **_HI Calculated Apportioned Value_** * **_Apportionment OpTime Array_** for this Location ) _path 5_ and confirm no issues
- [ ] Submission and synchronization of Q3 OS totals for HITOS, NOXMOS, OSHOURS and OSTIME (needed to properly calculate Q4 OS totals for affected MN, NV and UT units in this 1st year of CSOSG3 program)
  - [ ] Example MN, NV or UT unit
  - [ ] Existing OS affected unit not affected by CSOSG3 updates
- [ ] Non- [ ]operating files for MN, NV, and UT units
- [ ] General LME testing and LME Utility (**see comment for further details**)
- [ ] Run examples with CSOSG3 beginning mid ozone season in Q2 instead of Q3
- [ ] Test CSOSG2 to CSOSG3 example where G2 ends 8/3 and G3 begins 8/4 (this is scheduled to occur for other states affected by GNP)
- [ ] Super Evals

**Comment by djw4erg** [comment]
### Closing Ticket

CAPD (Charlie Frushour) indicated in the June 13, 2024 ECMPS Support Meeting that we should delay this change indefinitely.
