### ISSUE TITLE
Update READMEs for APIs

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#617]
- [x] Update README documentation for Emissions API
- [x] Update README documentation for Facilities API
- [x] Update README documentation for Monitoring Plan API

**Comment by sdhawan16** [comment]
### Endpoint information to include in Monitor Plan API README Documentation: 

### **Monitor Plan Management API**
**API Endpoints**
GET /api/monitor-plan-mgmt/monitor-plans/{orisCode}/configurations
GET /api/monitor-plan-mgmt/monitor-locations
GET /api/monitor-plan-mgmt/monitor-locations/{id}/methods
GET /api/monitor-plan-mgmt/monitor-locations/{id}/Supplementalmethods

----------------------

**Monitor Plan -** 
GET /api/monitor-plan-mgmt/monitor-plans/{orisCode}/configurations
Gets all monitor plans for the facility with the specified orisCode.

Parameters: 
Name | Required | Type | Path/Query
-- | -- | -- | --
orisCode | required | number | path

--------------------------------------
**Monitor Locations -** 
GET /api/monitor-plan-mgmt/monitor-locations
Gets all monitor locations.

--------------------------------------

**Monitor Methods -** 
GET /api/monitor-plan-mgmt/monitor-locations/{id}/methods
Gets all monitor methods for the specified monitor location. 

Parameters:
Name | Required | Type | Path/Query
-- | -- | -- | --
id | required | string | path

--------------------------------------

**Supplemental Methods –**
GET /api/monitor-plan-mgmt/monitor-locations/{id}/Supplementalmethods
Gets all supplemental methods for the specified monitor location. 

Parameters: 
Name | Required | Type | Path/Query
-- | -- | -- | --
id | required | string | path

--------------------------------------

**Comment by sdhawan16** [comment]
### Endpoint information to include in Emissions API README Documentation:

### Emissions Management API
**API Endpoints**
GET /api/emissions-mgmt/apportioned/hourly

--------------------------------------

**Hourly Apportioned Emissions –** 
GET /api/emissions-mgmt/apportioned/hourly
Gets all hourly apportioned emissions data including associated unit characteristics. 

Parameters:

Name | Required | Type | Path/Query
-- | -- | -- | --
page | optional | number | query
perPage | optional | number | query
orderBy | optional | string | query
beginDate | optional | date | query
endDate | optional | date | query
state | optional | string | query
orisCode | optional | number | query
unitType | optional | string | query
unitFuelType | optional | string | query
controlTechnologies | optional | string | query
opHoursOnly | optional | boolean | query

--------------------------------------

**Comment by sdhawan16** [comment]
### Endpoint information to include in Facility API README Documentation: 

### Facility Management API
**API Endpoints**
GET /api/facility-mgmt/facilities
GET /api/facility-mgmt/facilities/{id}
GET /api/facility-mgmt/facilities/{id}/units

--------------------------------------

**Facilities -** 
GET /api/facility-mgmt/facilities
Gets all facilities. 

Parameters:
Name | Required | Type | Path/Query
-- | -- | -- | --
page | optional | number | query
perPage | optional | number | query
orderBy | optional | string | query
state | optional | string | query
region | optional | string | query

--------------------------------------

GET /api/facility-mgmt/facilities/{id}
Gets facility by specified id. 

Parameters:
Name | Required | Type | Path/Query
-- | -- | -- | --
id | required | number | path

--------------------------------------

GET /api/facility-mgmt/facilities/{id}/units
Gets all units for specified facility. 

Parameters:

Name | Required | Type | Path/Query
-- | -- | -- | --
id | required | number | path

--------------------------------------

**Comment by junie-stigdon** [comment]
Created a pull request for changes to the emissions API README:

- Brief summary of the API's purpose 
- Added more detail to installing instructions
- Overview of the endpoints
- Added a Built With and License section

Waiting for review before submitting facilities and mp READMEs (in case there needs to be changes)

**Comment by junie-stigdon** [comment]
- Added environment variable and ssh tunnel instructions

**Comment by junie-stigdon** [comment]
Created a pull request for changes to the Facilities API README

**Comment by sdhawan16** [comment]
Created a pull request for changes to the Monitor Plan API README

**Comment by junie-stigdon** [comment]
Changes after review:

- Updated environment variables section
- Included links to cloud.gov docs for log in instructions
- Added more descriptive CLI instructions
- Removed API Endpoint tables and replaced it with the swagger doc link
