### ISSUE TITLE
Fix code scanning alert - Unvalidated dynamic method call

### ISSUE THREAD

**Issue by mark-hayward-erg** [US-EPA-CAMD/PI-1#6173]
Tracking issue for:
- [ ] https://github.com/US-EPA-CAMD/easey-ecmps-ui/security/code-scanning/152

**Comment by annalbrecht** [comment]
Max D. will investigate to see if this is an issue.

**Comment by maxdiebold-erg** [comment]
I've investigated this alert and determined that it is not an issue. User-controlled parameters are indirectly responsible for indexing into the array of functions, which will, at worst, result in a value of `undefined`, but the following line protects against a type error by exiting early in the case of `undefined`.

The alert can safely be ignored.
