### ISSUE TITLE
monitor_hrly_value is slow

### ISSUE THREAD

**Issue by renaemyers** [US-EPA-CAMD/PI-1#6174]
Functions and views that rely on table camdecmps.monitor_hrly_value are very slow, especially compared to derived_hrly_value, which has more rows. monitor_hrly_value appears to have appropriate indexes, all of which have recently been refreshed.

**Comment by djw4erg** [comment]
### **Research Notes**:

1. Last Auto-Analyzed and Last Analyzed from PG_STAT_ALL_TABLES are null for MHV table as well as DHV and HOD tables.
2. Explain Plans for **test query** indicates a high cost mainly due to merge join.
3. Running **test query** took more than 20 minutes in EASEY database.
4. Running **test query** took less than 4 minutes on the CAMDBSP database.
5. EASEY and CAMDBSP have comparable indexes.
6. Manually analyzed the HOD, DHV and MHV tables which resulted in the **test query** taking less than 4 minutes.
7. Although running ANALYZE significantly helped, the **test query** does not work well with the current indexes.
8. This seems to be a table statistics problem.

**Test Query**
```
select  ems.mon_plan_id ,
        prd.calendar_year ,
        prd.quarter ,
        ems.rpt_period_id 
  from  camdecmps.MONITOR_FORMULA frm
        join camdecmps.HRLY_OP_DATA hod
          on hod.mon_loc_id = frm.mon_loc_id 
         and hod.Begin_Date between frm.begin_date and coalesce( frm.end_date, hod.Begin_Date)
        join camdecmps.DERIVED_HRLY_VALUE dhv
          on dhv.hour_id = hod.hour_id 
         and dhv.parameter_cd = 'NOX'
        join camdecmps.MONITOR_HRLY_VALUE mhv
          on mhv.hour_id  = dhv.hour_id 
         and mhv.parameter_cd = 'FLOW'
        join camdecmps.MONITOR_PLAN_LOCATION mpl
          on mpl.mon_loc_id = hod.mon_loc_id 
        join camdecmps.emission_evaluation ems
          on ems.mon_plan_id = mpl.mon_plan_id 
         and ems.rpt_period_id = mhv.rpt_period_id
        join camdecmpsmd.REPORTING_PERIOD prd  
          on prd.rpt_period_id = ems.rpt_period_id 
 where  frm.equation_cd like 'F-26%'
 group 
    by  ems.mon_plan_id ,
        prd.calendar_year ,
        prd.quarter ,
        ems.rpt_period_id;

```

**Comment by djw4erg** [comment]
### **Conclusions**:
1. Analyzing the HOD, DHV and MHV tables seems to have resolved the problem.
2. Need to assess effects of analyzing HOD, DHV and MHV on Emission View procedures in [#5793](https://github.com/US-EPA-CAMD/easey-ui/issues/5793).

### **Additional Thoughts and Actions**:
1. The bulk loading of any tables should have been followed by analyzing the tables.
3. We should Analyze any table for which the **PG_STAT_ALL_TABLES** **Last Auto-Analyzed** and **Last Analyzed** values are null, particularly emission tables.
4. We need to develop a plan for tuning Auto Analyzing and Auto Vacuuming to prevent slowness and bloating issues.  Tuning and developing the plan will be an ongoing process and may require different rules for reporting months.
5. Review [PostgreSQL VACUUM and ANALYZE Best Practice Tips](https://www.enterprisedb.com/blog/postgresql-vacuum-and-analyze-best-practice-tips)

**Comment by djw4erg** [comment]
### **Not Analyzed Query**:

```
select  schemaname, 
        relname,
        last_autoanalyze, 
        last_analyze, 
        last_vacuum,
        last_autovacuum
  from  pg_stat_all_tables
 where  schemaname like 'camd%'
   and  last_autoanalyze is null
   and  last_analyze is null
 order 
    by  schemaname, 
        relname;
```

**Comment by renaemyers** [comment]
Analyzed all emissions tables; emissions refreshes seem to be much faster now
