### ISSUE TITLE
Reporting Instructions- initial release

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6179]
We need to finalize the MP/QA/EM reporting instructions for the initial release of 2.0.

Question for @chrisgitsit: Since we aren’t fully implementing MATS for the initial release, we are wondering if we need to remove all the QA/EM information that has been added to the reporting instructions so that it doesn't confuse people. 

**From Thuy:** On page 248, the Parameter Type table for Conversion Parameters on page 248 still refers the table as 89 when the actual table is 92. https://rt.camdsupport.com/rt/Ticket/Display.html?id=72778

**Comment by alangmaid** [comment]
There will be 2 sets of reporting instructions. Current and future state.

**Comment by annalbrecht** [comment]
Meeting with Chris on 3/28/24-- he wants to discuss internally whether the MATS data should be removed from the documents. The elements would also need to be removed from the Json schema.

Meeting with CAPD on 5/2: Instead of removing anything, we will update the RI to reference the MATS FAQs.

**Comment by annalbrecht** [comment]
Meeting with CAPD on 5/2: Instead of removing anything, we will update the RI to reference the MATS FAQs.

**Comment by ibarra-michelle** [comment]
@annalbrecht could we discuss changing this priority from Low to High? 

Also, should #6220 be associated with this ticket #6179?
Answer - info from #6220 has been added to #6179 and #6220 has been closed.

**Comment by mark-hayward-erg** [comment]
@annalbrecht Has this ticket effectively been replaced by other tickets (e.g., #6340)?

**Comment by annalbrecht** [comment]
Closing this ticket since individual tickets were created for the different docs.
