### ISSUE TITLE
STORY: Update ORIS Validation 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#618]
## User Story
As a user
I want to enter leading 0s
So that the ORIS code is what I am familiar with 

## Acceptance Criteria
Given that a user has entered invalid filter criteria for ORIS code (see below)
When the API endpoint is executed
[Then the system displays error message FV-9](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

ORIS code format:
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC70](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268892)
Tester: @davidkwartler 

### Issue Requester:
Requester:

**Comment by junie-stigdon** [comment]
Created pull request and waiting for review:

- Created custom decorator and moved validation logic from the pipe
- Updated regex so the validation will accept leading 0s 
  - 000612 will pass and search for orisCode 612
- Updated DTO to use the custom decorator instead of pipe
- Error message now in DTO

**Comment by junie-stigdon** [comment]
Renamed files for consistency:

- src/pipes/date-validation.pipes.ts -> src/pipes/date-validation.pipe.ts
- src/pipes/oris-code-validation.pipes.ts -> src/pipes/is-oris-code.pipe.ts
- src/pipes/state-validation.pipes.ts -> src/pipes/state-validation.pipe.ts

**Comment by david-cvp** [comment]
TC70 passed
