### ISSUE TITLE
Displaying data issues in the emissions workspace

### ISSUE THREAD

**Issue by ntknguyen** [US-EPA-CAMD/PI-1#6181]
The calculated value and report errors are not displaying in the workspace view template. However they are displaying in the global view.
Example:

Import 2023 Q3 emissions from historical for oris 8906, CP30, 31RH, 31SH
Select Hourly NOx Rate CEMS view for 31RH and apply filter
There is no data displaying in the Report Errors and Calculated columns

**Comment by annalbrecht** [comment]
Need to document what should be happening.

**Comment by ntknguyen** [comment]
> Need to document what should be happening.

The EPA Calculated values are showing in the Global view but not in the workspace. Should it be the opposite?

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/2ef00020-d16f-43ce-aa1f-014033e59ced)
![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/40d07d4f-e6a3-4359-a54b-1f8890231f05)

**Comment by annalbrecht** [comment]
### Requirements
Requirement 1: For calculated values, the only time a file wouldn't have calculated values is if you import from JSON or from historical and have not yet evaluated.
Requirement 2: The only time Report Errors should be populated is if a file is imported from JSON or from historical and subsequently evaluated. Just importing from historical should not show Report Errors.

There are multiple calculated value fields that need to be checked to make sure they are being returned.

**Comment by ergjustin** [comment]
- Unable to view calc_fuel_flow data in workspace (before evaluation )

`select * from camdecmpswks.emission_view_hiappd where mon_plan_id = 'CAMERON-EA8AEA9E6FA04471A401BAD5F09D6E99'`
![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/108369391/5fd7c6a4-e144-4f6b-a770-ef8217c531c9)
<hr>



- After evaluation I could see the `calc_fuel_flow` data.

![6181-afterealuate](https://github.com/US-EPA-CAMD/easey-ui/assets/108369391/fed0fff1-53dd-44d7-872a-52889734d582)

**Comment by annalbrecht** [comment]
@maheese @ibarra-michelle 

- EPA needs to determine if the Calculated Values should show up for the public. If this information needs to be removed, when should that be completed?
- EPA also needs to determine when the Report Errors column needs to be removed for public users.

New tickets will be created based on the answers, and this ticket closed.

**Comment by maheese** [comment]
@annalbrecht this should be removed but it is very low priority and does not have to be done for the first release.

**Comment by annalbrecht** [comment]
Closing this ticket. The agreed upon work will be handled in #6307.
