### ISSUE TITLE
Upgrade to Node.js 20

### ISSUE THREAD

**Issue by maxdiebold-erg** [US-EPA-CAMD/PI-1#6187]
Several repositories (`easey-design-system`, `easey-ecmps-ui`, `easey-campd-ui`, and `devops`) are using Node.js version 16: this version is no longer maintained, and its use is causing compatibility issues among the organization's repositories. They should be updated to Node.js version 20.

**Comment by yonatan-dp** [comment]
- upgraded  easey-design-system
	- New version is 1.35.0
	- upgrade workflows to use node 20 (also v4 actions)
	- branch 1.x 
	- Merged to master (for package release)
	
- upgraded ecmps UI
	- New version is 2.2
	- upgraded version of dependency easey-design-system to 1.35.0
	- upgraded workflows to use node 20 (also v4 actions)
	- branch fix/6187-upgrade-node-20, pushed but not merged to develop

- upgraded easey-campd-ui
	- New version is 1.4
	- upgraded version of dependency easey-design-system to 1.35.0
	- upgraded workflows to use node 20 (also v4 actions)
	- branch fix/6187-upgrade-node-20, pushed but not merged to develop
	
- upgraded devops
	- upgraded workflows to use node 20 (also v4 actions)
	- branch fix/6187-upgrade-node-20, pushed but not merged to develop

Changes for ecmps UI, campd-ui, and devops not merged to develop. Waiting on sprint 5/6 changes to be pushed to the test env before merging to develop.

**Comment by mark-hayward-erg** [comment]
No specific testing required.
