### ISSUE TITLE
Research spike to understand active/inactive MP logic

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#620]
## Tasks 
- [x] Review stored procedure
- [ ] Determine plan to implement active/inactive MP logic

Please see SQL for Active/Inactive MP Logic: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/ActiveInactive%20MP%20Logic.msg

The logic in in the following stored procedure in the ECMPS Client Database.
• ECMPS.[dbo].[UPDATE_MON_PLAN_CONFIGURATION]

## Outcomes 
Plan to implement active/inactive MP logic

**Comment by david-cvp** [comment]
@SimeraHailu Can you add a link to the deliverable in Teams? Thank you!

**Comment by SimeraHailu** [comment]
https://teams.microsoft.com/l/file/71519486-BE8C-45A0-B2D8-262A0D41661F?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2FEASEY-IN%20API%20Design%2FActive-inactive%20MP%20logic%20-%20FACT%20API%20-%20EPA%20CAMD%20-%20v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23
