### ISSUE TITLE
If an API crash or exception occurs on import, the user should be notified and told to contact support.

### ISSUE THREAD

**Issue by mxtomoto1** [US-EPA-CAMD/PI-1#6202]
Refer to #6100 for context- importing duplicate EM record causes a crash. The user should be notified that the import was not successful and told to contact support for assistance. Currently, the import indicates that it was successful.

Message:

This file could not be imported. Please contact [ECMPS User Support](https://github.com/orgs/US-EPA-CAMD/projects/2/views/ecmps-beta@camdsupport.com) for assistance.

**Comment by annalbrecht** [comment]
Closing this-- it will be handled in #6203.
