### ISSUE TITLE
STORY: Make beginDate and endDate required fields for Emissions API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#621]
## User Story
As a user, I want beginDate and endDate to be required, so that I can specify when I want data for.

## Acceptance Criteria
Given a user has queried the API
When the API is executed
Then the API will ensure that beginDate and endDate have values

Given that a user has not entered beginDate and endDate
When the API is executed
[Then the system displays the error message for FV-10](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Given that a user has not entered either beginDate or endDate
When the API is executed
Then the system will not execute any other date validations for the null date

## Dev Tasks
- [x] Remove @IsOptional decorator in DTO for beginDate and endDate
- [x] Create custom decorator to ensure endDate is >= beginDate
- [x] Add custom decorator to DTO
- [x] Ensure that if beginDate or endDate do not exist, the other date validations errors will not display

## Testing
Test Case: [TC69](https://cvpcorp.testquality.com/project/11428/plan/19464/test/268891)
Tester: @davidkwartler

**Comment by JorjaComer** [comment]
@davidkwartler or @junie-cvp Please make sure to enter the error message text in the ticket or in the error message doc
https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23

**Comment by junie-stigdon** [comment]
## Pull Request

- Made beginDate and endDate required
- Commented out date-validation.pipe.ts and replaced it with custom decorators:
  - is-iso-format.pipe.ts
  - is-valid-date.pipe.ts
  - is-in-date-range.pipe.ts
- Removed "endDate >= beginDate" validation from the service and replaced it with a custom decorator:
  - is-date-greater.pipe.ts
- If user enters invalid format, invalid date, or a date that is out of range, the system shall return a list of all the date validation errors it failed 
  - Previously it would only return one date validation error with the priority being format>valid date>range
  - But now all three validations will be checked (and not short circuited) 
- If the user does not input a beginDate or endDate, the system shall only return this error message:
  - "**[insert property]** should not be null or undefined" 
  - It will not return the format, valid date, or range error messages, as there is no value provided to validate

**Comment by junie-stigdon** [comment]
- updated date-range decorator to accept a min and max date
- updated error messages per requirements

**Comment by junie-stigdon** [comment]
- added swagger plugin

**Comment by david-cvp** [comment]
Updated acceptance criteria on 1/15 to make the null date validation more clear

TC69 passes

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/b1c8dbf7-3ccd-4a42-92f9-513034a28123)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/0dff9b0a-0fa4-4d47-bc93-d95bd6b8f437)
