### ISSUE TITLE
Fixing table reference typo in the qa reporting instructions

### ISSUE THREAD

**Issue by ntknguyen** [US-EPA-CAMD/PI-1#6220]
On page 248, the Parameter Type table for Conversion Parameters on page 248 still refers the table as 89 when the actual table is 92. https://rt.camdsupport.com/rt/Ticket/Display.html?id=72778

**Comment by ibarra-michelle** [comment]
@annalbrecht Should this ticket #6220 be associated with ticket #6179?

**Comment by annalbrecht** [comment]
Moved the contents of this ticket into #6179. Closing this ticket.
