### ISSUE TITLE
RETEST:  Beta environment: Submissions are not processing

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#6250]
While testing #5892, I did submissions for ORIS 404. The submissions are stuck in the "Submitted, Host Update Pending" status. This is in the Beta environment.

We need to figure out the underlying cause of this and fix it or put in logic to have the job restart on its own.

![image](https://github.com/US-EPA-CAMD/easey-ui/assets/46533513/a87fd232-2101-437a-b8eb-0c9f15ed9cd2)

**Comment by maxdiebold-erg** [comment]
In #6108, this was remedied by restarting the **Submission Job Queue** job.

**Comment by mark-hayward-erg** [comment]
Will monitor submission data during beta testing to determine if this is still an issue.

**Comment by ibarra-michelle** [comment]
FYI @esaber76, @mark-hayward-erg, @maheese.

Summary: After successfully evaluating a QA Test Data file, the QA Test Data file Submission Status changed to "Updated on Host." The QA record was visible in the submission module, however, I was not able to select the QA test data record to Sign & Submit.  

**Steps to recreate the issue:**
1. Login to the test environment as a data submitter and select the following config: ORIS 404, Location 1.
2. Navigate to the MP module, export & import the MP data.
3. Navigate to the QA > Test Data module, click the import button, select Import from historical data, then select 2022 Q4, click the preview button.
4. Select the Test with the test number: 20224GFFM:112T1
5. In the QA Cert module UI, click the Test Type Group dropdown and select "Primary Element Inspection."
6. Click the Edit button for the record with the test #: 20224GFFM:112T1 to modify the Test Summary Data
7. Modify the Test Summary Data:
-  Modify the Test number to 20234GFFM:112T1
-  Modify the End Date to 03/02/2023
- Append the existing Test comment with the word "test."

8. Click the Save & Close button.
9. Navigate to the Emissions module, import 2023Q1 emission data from historical.
10. Before evaluating the QA and Emissions data, an admin must go into the System Admin module to allow the resubmission of test number 20234GFFM:112T1 and reopen the 2023Q1 Emissions submission window for the ORIS 404 Location1.
11. After the Admin tasks have been completed, the data submitter user should navigate to the Evaluation module, select the ORIS 404, Location 1, and 2023Q1 as the filter options, and click "Apply Filters."
13. After applying the filter, select the MP, QA Test Data, and Emissions records to evaluate.  
14. The evaluation status for each of the MP, QA, and Emissions records will result in the following (see the screenshot below):

**Different Evaluation Status**
1. MP: Premission to Resubmit Granted
16. QA: Updated to Host
17. Emissions: Resubmission Required 

![image](https://github.com/user-attachments/assets/c7b45a9f-9c6b-4efb-8fd2-5844896a3674)

**Comment by alangmaid** [comment]
Closing this ticket based on the understanding that beta testing will generate specific bugs to act on. New ticket #6360 created to capture bugs
