### ISSUE TITLE
STORY: Re-label UI Elements 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#626]
As a user I want the UI to be easy to understand so that i know what actions to take. 

Given a user has accessed the facilities list
When the Ui is displayed
Then UI will display:

- The filter by keyword section [as displayed in the wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/) 
- The actions column per the wireframes
- the open button label as per the wireframes

**Comment by mosesdeeCVP** [comment]
TCR517 626 Re-label UI Elements - Pass

![626_Re-label_UI_Elements_20210114.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/22fa2a70-93ce-4978-8cf2-0d49d572c1ef)
