### ISSUE TITLE
STORY: Update Tab Functionality 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#627]
As a user I want to know that I cannot select a monitoring plan section for a facility so that I will not have multiples of the same section open at a time. 

Given a user has opened tabs for a particular facility
When the list of facilities is displayed
Then facilities with tabs already open may not be selected ([refer to wireframes for more info](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/))

**Comment by mosesdeeCVP** [comment]
TCR509 627 Update Tab Functionality - Pass

![627_Update_Tab_Functionality_20210114.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/3236eb3a-b2e7-4168-8115-eead236cfeaa)
