### ISSUE TITLE
Prep Initial ECMPS security scan

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#6276]
Develop instructions for the ECMPS 2.0 Security Scans.  The instructions should include any prep that needs to occur in the environment prior to submitting the scan request (e.g. turn on CDX bypass, increase token timeout, backup data, etc.) and specific instructions for the scan team.  The scan team instructions should include:

- The list of URLs to be scanned.  For APIs this should also include the URL for the swagger JSON file.
- Instructions on how to obtain credentials for any authenticated features (API key, username/password, client Id/secret)
- Technologies used including OS, programming language, DBMS.  For our systems this will probably be Linux, JavaScript/Typescript, Postgres.

Here's an example of the instructions that were put together for the CAMPD scans on how to obtain a token using a client Id and secret.  https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/CAMPD/CAMPD%20API%20Scanning%20Instructions.docx?d=wa666a92d116f454b987a932541575bd9&csf=1&web=1&e=BPeg0G

ERG also has examples of instructions that were put together for the CBSI scans.

- Need to make sure that swagger pages are not suppressing any endpoints in the dev, test, staging, and PERF environments.

**Comment by yonatan-dp** [comment]
# Instructions for Performing Security Scans on EASEY Applications

## Introduction

This document provides instructions for conducting security scans on the EPA's EASEY applications, which include multiple backend APIs and a frontend application. The instructions are divided into two sections targeting:

1. **Security Scan Team**: Instructions on how to perform security scans against the backend APIs and the frontend app.
2. **EPA Easey Team**: Specific instructions for preparing the API environment for a security scan.

---

## Section 1: Instructions for the Security Scan Team

### Overview

This section provides step-by-step guidance on accessing the APIs, obtaining authentication tokens, and understanding the technologies involved. Each backend API is listed with specific instructions to assist you in performing comprehensive security scans.

### General Instructions

- **Authentication**: Most backend APIs require an authentication token (bearer token), either an auth token for user-based API access or a client token for app-to-app API communication.
- **Swagger Documentation**: Use the provided Swagger URLs to explore API endpoints, parameters, and responses.
- **Headers**: All API calls must include an `x-api-key` header. Use the value provided by the EPA Easey Team for the `x-api-key` header.
- **Technologies Used**:
  - **Backend APIs**: Linux, TypeScript, PostgreSQL
  - **Frontend App**: Linux, JavaScript, React

### Prerequisites

- **Test Credentials**: Contact the EPA Easey Team to obtain:
  - `username` for obtaining bearer tokens, and with proper permissions for invoking API endpoints.
  - `clientId` and `clientSecret` for obtaining client tokens for App to App calls. 
- **API Key**: Contact the EPA Easey Team to obtain:
  - `x-api-key` header value, to be included in each and every API call 
  
---

### Authorization Overview

All API endpoint invocations during a security scan require security tokens and an API Key as part of the request headers: 

1. **API Key**: Supplied via the `x-api-key` header, required for all API requests.
2. **Authorization Token**: A bearer token required for user-based operations.
3. **Client Token**: A bearer token for app-to-app communication, required for certain API endpoints.

Each token type and its associated usage are described below.

---

## Obtaining a Bearer Token for User-Based API Access

This bearer token is used for API requests that require user authentication and is obtained through a login action. 

### Steps to Obtain a Bearer Token from `easey-auth-api`

1. **Access the Swagger Documentation**:
   - URL: [https://api.epa.gov/easey/perf/auth-mgmt/swagger/](https://api.epa.gov/easey/perf/auth-mgmt/swagger/)

2. **Locate the `/sign-in` Endpoint**:
   - Method: `POST`
   - Endpoint: `/sign-in`

3. **Prepare the Request**:
   - **URL**: `https://api.epa.gov/easey/perf/auth-mgmt/sign-in`
   - **Headers**:
     - `Content-Type`: `application/json`
     - `x-api-key`: Obtain this from the EPA Easey Team.
   - **Request Body (JSON)**:
     ```json
     {
       "sessionId": "scanUser1"
     }
     ```
   - `sessionId`: Use the value `scanUser1` or as provided for the EPA Easey team.

4. **Send the Request**:

5. **Receive the Response**:
   - A successful response will include a `token`, `tokenExpiration`, and `refreshToken`.
     ```json
     {
       "userId": "scanUser1",
       "firstName": "abc",
       "email": "scanUser1@scanUser1.com",
       "roles": ["Sponsor", "Preparer", "Submitter", "ECMPS Analyst", "ECMPS Admin", "Initial Authorizer"],
       "token": "dXNlcklkPVlPTkNEWC1TVUJNSVRURVImc2Vzc2lvbklk...",
       "tokenExpiration": "11/19/2024, 10:42:22 AM",
       "refreshToken": "",
       "facilities": [...],
       "missingCertificationStatements": false
     }
     ```
   - **Note**: Some information in the response has been redacted for brevity.

6. **Extract the Token**:
   - Save the `token` field. This is the bearer token for subsequent API requests (referred to as auth_token in example usage below).
   - **Token Expiration**: Note the `tokenExpiration` field to know when the token will expire.
   - **Refresh Token**: The refresh token value will be empty when obtaining tokens for security scans (with bypass on).

### Using the Bearer Token
- Include the `Authorization` header in your API requests:
```
Authorization: Bearer [auth_token]
```
---

## Obtaining a Client Token for App-to-App Communication

The client token is used for backend-to-backend API communication, when a logged in user is not availble in the call context. 

### Steps to Obtain a Client Token from `easey-auth-api`

1. **Prepare the Request**:
 - **URL**: Construct the URL using the following pattern:
   ```
   https://api.epa.gov/easey/perf/auth-mgmt/tokens/client
   ```
 - **Headers**:
   - `Content-Type`: `application/json`
   - `x-api-key`: Obtain this from the EPA Easey Team.
 - **Request Body (JSON)**:
   ```json
   {
     "clientId": "[YourClientId]",
     "clientSecret": "[YourClientSecret]"
   }
   ```
   - Replace `[YourClientId]` and `[YourClientSecret]` with the values provided by the EPA Easey Team.

2. **Send the Request**:

3. **Receive the Response**:
   - A successful response will include a `token` and `expiration`.
   ```json
   {
     "token": "eyJhbGciOiJIUzI1NiIsInR...",
     "expiration": "11/19/2024, 11:00:00 AM"
   }
   ```

4. **Extract the Token**:
 - Save the `token` field. This is the client token for use in app-to-app API requests (referred to as client_token in example usage below).
 - **Token Expiration**: Note the `expiration` field to know when the token will expire.

### Using the Client Token
- Include the `Authorization` header in your API requests:
```
Authorization: Bearer [client_token]
```

---

## API Key (x-api-key)

The `x-api-key` is a mandatory header for all API requests.

### Example of Including the API Key
- Add the following header to every request:
x-api-key: [APIKey]
- Replace `[APIKey]` with the value provided by the EPA Easey Team.

---
## Client ID (x-client-id)

The `x-client-id` header must be included in the request whenever a `client_token` is used as a bearer token. This will also be indicated in the swagger documentation for that endpoint.

### Example of Including the Client ID
x-client-id: [ClientID]
- Replace `[ClientID]` with the value provided by the EPA Easey Team.

---

## Summary of Headers

| Header            | Purpose/When to Use                                       |
|-------------------|-----------------------------------------------------------|
| `x-api-key`       | Mandatory for all requests                                |
| `Authorization`   | User-based operations (`Bearer [auth_token]`)             |
| `Authorization`   | App-to-app communication (`Bearer [client_token]`)        |
| `x-client-id`     | App-to-app communication, whenever `client_token` is used as a bearer token |

Use the appropriate headers depending on the endpoint’s requirements. Refer to the Swagger documentation for endpoint-specific authorization needs.

### Scanning the Backend APIs

For each backend API, follow the instructions below.

---

#### 1. EASEY Auth API

- **App Name**: `easey-auth-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/auth-mgmt/swagger/](https://api.epa.gov/easey/perf/auth-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/auth-mgmt/swagger-json](https://api.epa.gov/easey/perf/auth-mgmt/swagger-json)
- **Purpose**: Authentication services for obtaining access tokens.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - All endpoints listed in the Swagger documentation, including `/login`, `/refresh`, `/logout`, etc.
- **Authentication**:
  - While `/login` may not require a token, other endpoints might.
  - Use the `token` obtained from the `/login` endpoint as a bearer token (referred to as `auth_token` in the example usage below. 
- **Headers**:
```
Authorization: Bearer [auth_token]
```

---

#### 2. EASEY CAMD Services

- **App Name**: `easey-camd-services`
- **Swagger URL**: [https://api.epa.gov/easey/perf/camd-services/swagger/](https://api.epa.gov/easey/perf/camd-services/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/camd-services/swagger-json](https://api.epa.gov/easey/perf/camd-services/swagger-json)
- **Purpose**: Provides Clean Air Markets Division services.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Refer to the Swagger documentation for a list of endpoints such as `/emissions`, `/allowances`, etc.
- **Authentication**:
  - Required for most endpoints.
  - Include the `Authorization` header with the `auth_token`.
- **Headers**:
`Authorization: Bearer [auth_token]`



---

#### 3. EASEY Monitor Plan API

- **App Name**: `easey-monitor-plan-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/monitor-plan-mgmt/swagger/](https://api.epa.gov/easey/perf/monitor-plan-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/monitor-plan-mgmt/swagger-json](https://api.epa.gov/easey/perf/monitor-plan-mgmt/swagger-json)
- **Purpose**: Manages emissions monitoring plans.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Key endpoints include `/monitor-plans`, `/monitor-locations`, etc.
- **Authentication**:
  - Required for all endpoints.
- Use the `Authorization` header with the `auth_token`.

---

#### 4. EASEY MDM API

- **App Name**: `easey-mdm-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/master-data-mgmt/swagger/](https://api.epa.gov/easey/perf/master-data-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/master-data-mgmt/swagger-json](https://api.epa.gov/easey/perf/master-data-mgmt/swagger-json)
- **Purpose**: Master Data Management services.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Include `/reference-data`, `/codes`, etc.
- **Authentication**:
  - Some endpoints may be public; others require authentication.

---

#### 5. EASEY Emissions API

- **App Name**: `easey-emissions-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/emissions-mgmt/swagger/](https://api.epa.gov/easey/perf/emissions-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/emissions-mgmt/swagger-json](https://api.epa.gov/easey/perf/emissions-mgmt/swagger-json)
- **Purpose**: Manages emissions data.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Key endpoints include `/emissions-data`, `/submission`, etc.
- **Authentication**:
  - Required.

---

#### 6. EASEY Facilities API

- **App Name**: `easey-facilities-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/facilities-mgmt/swagger/](https://api.epa.gov/easey/perf/facilities-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/facilities-mgmt/swagger-json](https://api.epa.gov/easey/perf/facilities-mgmt/swagger-json)
- **Purpose**: Manages facility information.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Include `/facilities`, `/units`, etc.
- **Authentication**:
  - Required.

---

#### 7. EASEY Account API

- **App Name**: `easey-account-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/account-mgmt/swagger/](https://api.epa.gov/easey/perf/account-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/account-mgmt/swagger-json](https://api.epa.gov/easey/perf/account-mgmt/swagger-json)
- **Purpose**: Manages user accounts and permissions.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Key endpoints include `/accounts`, `/permissions`, etc.
- **Authentication**:
  - Required.

---

#### 8. EASEY QA Certification API

- **App Name**: `easey-qa-certification-api`
- **Swagger URL**: [https://api.epa.gov/easey/perf/qa-certification-mgmt/swagger/](https://api.epa.gov/easey/perf/qa-certification-mgmt/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/qa-certification-mgmt/swagger-json](https://api.epa.gov/easey/perf/qa-certification-mgmt/swagger-json)
- **Purpose**: Quality Assurance and certification processes.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Include `/qa-tests`, `/certifications`, etc.
- **Authentication**:
  - Required.

---

#### 9. EASEY Streaming Services

- **App Name**: `easey-streaming-services`
- **Swagger URL**: [https://api.epa.gov/easey/perf/streaming-services/swagger/](https://api.epa.gov/easey/perf/streaming-services/swagger/)
- **Swagger JSON**: [https://api.epa.gov/easey/perf/streaming-services/swagger-json](https://api.epa.gov/easey/perf/streaming-services/swagger-json)
- **Purpose**: Provides streaming data services.
- **Technologies**: Linux, TypeScript, PostgreSQL

**Instructions**:

- **Endpoints to Scan**:
  - Include streaming endpoints as specified in the Swagger documentation.
- **Authentication**:
  - Required.

---

### Frontend Application: EASEY ECMPS UI

- **App Name**: `easey-ecmps-ui`
- **App URL**: [https://ecmps-perf.app.cloud.gov/](https://ecmps-perf.app.cloud.gov/)
- **Purpose**: User interface for ECMPS.
- **Technologies**: Linux, JavaScript, React

**Instructions**:

- **Accessing the Application**:
  - Navigate to the provided URL.
  - Use the test `username` provided by the EPA Easey team to login. 

---

## Section 2: Instructions for the EPA Easey Team

### Overview

This section outlines the necessary steps to prepare the API environment for the security scan.

### Preparatory Steps

1. **Enable CDX Login Bypass**:
    - Temporarily enable the CDX login bypass to allow the security scan team to authenticate without going through CDX login.
      - Set ```EASEY_CDX_BYPASS_ENABLED=true```
	  
2. **Provide Test Credentials**:
    - Add ```scanUser1``` to the ```EASEY_CDX_BYPASS_USERS``` variable in the scan environment (PERF)
    - Add ```scanUser1``` in the ```Mock Permissions``` file with the right permissions (PERF)
	- Share the user name with the security scan team.

3. **Provide Client Id and Client Secret**:
    - Provide ```clientId``` and ```clientSecret``` to the scan team for app-to-app calls.

4. **Provide an x-api-key value**:
    - Provide ```x-api-key``` value to the scan team for making API calls.
    - The x-api-key that is provided needs to have the default rate limit lifted or the scanner will flood the system with requests and hit the limit.
	- The scan team can use ```easey_zap.api_key@epa.gov``` as ```x-api-key``` value as this key has been set up for this purpose. 
5. **Increase Token Timeout**:
    - Extend the token expiration time to accommodate long-running security scans.
    - Coordinate with the security scan team to determine an appropriate timeout duration.

6. **Backup Data**:
    - The scans can change and delete data. To avoid this, a full backup of the databases can be performed prior to the scan.

7. **Whitelist Security Scan IPs**:
    - If there are IP-based access controls, whitelist the IP addresses of the security scan team to prevent blocking and rate limiting.

8. **Set Up Monitoring and Alerts**:
    - To monitor the scan and analyze the result, access the logging portal in cloud.gov located here: https://logs.fr.cloud.gov 

### Post-Scan Actions

1. **Revert Configuration Changes**:
    - After the scan, disable CDX login bypass and restore authentication mechanisms to their original state.
    - Reset token timeouts to default values.

2. **Data Restoration**:
    - Restore backup of the database.

3. **Review Scan Results**:
    - The scan team can provide scan results in two ways: 
      - A spreadsheet format that does not lend itself to easy analysis
      - The file ```gl-dast-report.json``` generated by the scanner that provides detailed information of the scan findings. Furthermore, this file can be converted into a human readable format using this tool https://github.com/USEPA/gl-dast-scan-report-generator.	  
	- For reviewing results, often the scanner will flag things that are false positives. The EPA scan team has a process for re-classifying a finding to a false positive.  The scan team will provide a template to request reclassification.  The justification needs to be specific to the finding and include the actual code or a demonstration of why finding should be re-classified.
	- Any high or critical findings need to be reclassified/remediated prior to deployment.

4. **Update Documentation**:
    - Update Swagger and the Run Book based on findings.

---

**Contacts for Assistance**:

- **EPA Easey Team**:
    - Name: Mike Heese / Mark Hayward
    - Email: heese.michael@epa.gov / mark.hayward@erg.com

- **Security Scan Team**:
    - Email: App_Scan@epa.gov

---

### This instruction document is attached below in Markdown format for ease of sharing.
[ECMPS2-Scan-Instructions.md](https://github.com/user-attachments/files/17850732/ECMPS2-Scan-Instructions.md)

**Comment by maheese** [comment]
@yonatan-dp Looks good!  Here are some comments:

1.  Add a link to the swagger JSON file.  This needs to be provided in the request to the scan team.  The scan tool uses the JSON file to perform the scan. (eg. https://api.epa.gov/easey/perf/emissions-mgmt/swagger-json)
2.  The x-api-key that is provided needs to have the default rate limit lifted or the scanner will flood the system with requests and hit the limit.  The key for easey_zap.api_key@epa.gov has been set up for this purpose.  If another key is used the limit will need to be lifted in the API gateway. 
3.  At this point, the best place to monitor the scan, and analyze what occurred afterwards, is through the logging portal in cloud.gov located here: https://logs.fr.cloud.gov (you will need to have access to the space where the scan was performed to see the records).  Cloud.gov is working on updating the logging portal with alerts but this will not be available for a few months.
4. The scan team has historically provided the results in a spreadsheet that is not very useful.  Request that they provide the file gl-dast-report.json generated by the scanner.  This file provides detailed information of the scan findings. This can be converted into a human readable format using this tool https://github.com/USEPA/gl-dast-scan-report-generator.
5. For reviewing results, often the scanner will flag things that are false positives.  The EPA scan team has a process for re-classifying a finding to a false positive.  The scan team will provide a template to request reclassification.  Any high or critical findings need to be reclassified/remediated prior to deployment. 

When this is all finished I'd like to get these instructions as its on md file in easey-docs.

**Comment by yonatan-dp** [comment]
@maheese , thanks for the feedback Mike. I have updated the instructions per your comments. Once I get @mark-hayward-erg feedback, I will add to easey-docs. I assume from your comment that you want it as a standalone document in easey-docs, as opposed to adding it as a section in the the run book.
