### ISSUE TITLE
View System Details Components Modal

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#628]
## Adjusted Estimate

Actual: 8
Original: 5

Reason: 508 implementation & testing

### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Story 1 - 5
Given a user has selected a system
When the user chooses to view a system
Then the system displays a modal window  (labels, cancel, save and close, X)

## Testing
Test Case: [TC117](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276365)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by mosesdeeCVP** [comment]
![628 View System Details Components Modal.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/77708cee-9c0f-43bb-8e87-cec326de3b0f)

**Comment by mosesdeeCVP** [comment]
Test Case - Passed

**Comment by mosesdeeCVP** [comment]
Re Test - Passed

**Comment by mosesdeeCVP** [comment]
Product Owner has approved the story – Ticket closed.
