### ISSUE TITLE
View Monitoring Span Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#629]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production monitoring span data for Non-Flow and Flow Spans so that I can look at real-time data

## Acceptance Criteria
Given a user selects **Span, Range and Formulas** from the Sections dropdown
When the Monitoring Plan Non-Flow Spans and Flow Spans data is displayed
Then the data is displayed in a single table (see list below for columns and order)

Component Type: dropdown
Span Scale: dropdown
Span Method: dropdown
Span Units of Measure: dropdown
Start Date: date picker, required, format mm/dd/yyyy
Start Time: Text, required, format hh
End Date: date picker, required, format mm/dd/yyyy
End Time: Text, required, format hh

Given a user is viewing Monitoring Span data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [x] Yes 
- [ ] No

Filter by keyword?

- [x] Yes 
- [ ] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

## Context

Reporting Instructions (Page 105): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/e4d554c0-fc58-4f41-b26d-42153fc17573)

## Testing
Test Case: [TC376](https://epacamd.testquality.com/project/11428/plan/20424/test/303520)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![629 View Monitoring Span Data - 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/430261c0-13f8-4f14-a543-df2e6f558e9c)

![629 View Monitoring Span Data - 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/99803557-4fa5-4ab5-9992-f89db810d423)

**Comment by mosesdeeCVP** [comment]
Test Passed
