### ISSUE TITLE
Review "Last Modified"/ "Updated" data for logged in and public view is accurate

### ISSUE THREAD

**Issue by ibarra-michelle** [US-EPA-CAMD/PI-1#6296]
Holistically, the "Last Submitted/Modified"  and "Updated" dates in the logged in and public view and database need to be reviewed for accuracy. It is not clear whether this field is working properly in all the affected areas in the logged in and public views.

Should tickets #6251, #6253, #5208, #6254 be associated with this high-level ticket?

FYI @annalbrecht

**Comment by annalbrecht** [comment]
Everything should be covered by the existing tickets.
