### ISSUE TITLE
View MP Location Attributes and Relationships Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#630]
Definition of Ready

- [x] Does this meet the INVEST criteria?
- [x]  Does this have a clearly defined user?
- [x]  Does this have an estimate?
- [x]  Does this have acceptance criteria?
- [x]  Does this have sufficient context (wireframes, business rules, etc.)?
- [x]  Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production MP Location Attributes and Relationships Data so that I can look at real-time data.

## Acceptance Criteria
Given a user accesses the page
When the MP Location Attributes and Relationships Data is displayed
Then the data is pulled from Cloud.gov ECMPS Schema (not the same endpoints as FACT API)

Given a user has selected **Location Attributes and Relationships** from the Sections dropdown
When the Location Attributes and Relationships data is displayed
Then the data is displayed as below:

**Monitoring Location Attributes:**
Duct Indicator
Bypass Indicator
Ground Elevation
Stack Height
Material Code
Shape Code
Cross Area Flow
Cross Area Stack Exit
Start Date
End Date

**Stack/pipes and Unit Relationships:** (Unit Stack Configuration Data)
Stack Pipe Name
Unit ID
Start Date
End Date

Given a user is viewing MP Location Attributes and Relationships Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Refer to page 6, 24 for values (https://www.epa.gov/sites/default/files/2021-06/documents/ecmps_monitoring_plan_reporting_instructions.pdf)

Testing
Test Case: @mosesdeeCVP 
Tester: [TC510](https://epacamd.testquality.com/project/11428/plan/22772/test/316518)

Definition of Done

- [x]  Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x]  Has the code been unit tested and peer reviewed?
- [x]  Have the functional tests been executed?
- [x]  Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x]  Has the user story been accepted by the Product Owner?
- [x]  Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![630 View MP Location Attributes and Relationships Data 1.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1be7a9d3-2a56-45b2-8564-352dbc243b31)

**Comment by mosesdeeCVP** [comment]
![630 View MP Location Attributes and Relationships Data 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/880d2646-0115-47be-ae7f-4ac692b6d8f0)

**Comment by mosesdeeCVP** [comment]
![630 View MP Location Attributes and Relationships Data 3.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a8608bfc-b8c0-4ea4-936a-b88b92985a10)

**Comment by mosesdeeCVP** [comment]
Test Passed
