### ISSUE TITLE
View MP Rectangular Duct WAFs Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#631]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As an ECMPS user, I want to view production Rectangular Duct WAFs data so that I can look at real-time data.

## Acceptance Criteria
Given a user selects **Rectangular Duct WAFs** from the Sections dropdown
When the Rectangular Duct WAFs data is displayed
Then the data is displayed in a single table (see list below for columns and order)

WAF Determination Date
WAF Start Date
WAF Start Time
WAF Method
WAF Value
Number of Test Runs
Number of Traverse Points WAF
Number of Test Ports
Number of Traverse Points Reference
Duct Width
Duct Depth
WAF End Date
WAF End Time

Given a user is viewing Rectangular Duct WAFs data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

Reporting Instructions (Page 115): https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Reporting%20Instructions%202021%20Q2.pdf

## Testing
Test Case: [TC411](https://epacamd.testquality.com/project/11428/plan/22357/test/308140)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![631 View MP Rectangular Duct WAFs Data.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/6c1d3d9b-b373-4c18-bd7b-767758e9aaf7)

**Comment by mosesdeeCVP** [comment]
Test Passed
