### ISSUE TITLE
Sprint 7 - Test Automation Research Ticket

### ISSUE THREAD

**Issue by IkeC-dpc** [US-EPA-CAMD/PI-1#6318]
- **Obtain access to the “Performance Environment”.**
- **Start creating sample automation scripts for ECMPS.**
- **Troubleshoot scripting issues/ continue research on BlazeMeter.**

**Comment by mark-hayward-erg** [comment]
Test development tickets have been added for Sprint 8

#6320 
#6321 
#6322 
#6323
