### ISSUE TITLE
Long running database queries

### ISSUE THREAD

**Issue by maheese** [US-EPA-CAMD/PI-1#6335]
At 11:46AM on 7/25 a CAMPD user executed a query from the CAMPD UI.  It's now 5:04PM and I can see that the query is still running in Postgres and its impacting overall database performance.  At this point we've used up about 340GB of temp file space on the server and it continues to grow.  Why is this query taking so long to execute?  Why wasn't the query aborted when the HTTP connection was aborted?  The API gateway will kill a connection after 15 minutes of inactivity.

Here's the query:

SELECT "hud"."state" AS "stateCode", "hud"."facility_name" AS "facilityName", "hud"."orispl_code" AS "facilityId", "hud"."op_date" AS "date", "hud"."op_hour" AS "hour", SUM("hud"."gload") AS "grossLoad", SUM("hud"."sload") AS "steamLoad", SUM("hud"."so2_mass") AS "so2Mass", SUM("hud"."co2_mass") AS "co2Mass", SUM("hud"."nox_mass") AS "noxMass", SUM("hud"."heat_input") AS "heatInput" FROM "camddmw"."vw_hour_unit_data" "hud" WHERE "hud"."op_date" >= $1 AND "hud"."op_date" <= $2 GROUP BY "hud"."state", "hud"."facility_name", "hud"."orispl_code", "hud"."op_date", "hud"."op_hour" ORDER BY "hud"."orispl_code" ASC, "hud"."op_date" ASC, "hud"."op_hour" ASC LIMIT 100  

There are a few other queries that have been executing for long periods of time.  I'm attaching the list to this issue.  You can obtain this information from Postgres using this SQL:

SELECT
	pid,
	APPLICATION_NAME,
	BACKEND_START,
	QUERY_START,
	NOW() AS CURRENT_TIME,
	NOW() - QUERY_START AS QUERY_DURATION,
	QUERY
FROM
	PG_STAT_ACTIVITY
WHERE
	APPLICATION_NAME LIKE '%api'
ORDER BY
	QUERY_START ASC;

You can view the temp files and temp file size with these queries:

SELECT
	*
FROM
	PG_LS_TMPDIR();

SELECT
	PG_SIZE_PRETTY(SUM(SIZE))
FROM
	PG_LS_TMPDIR();

Here's the list of queries that were running.

[data-1721941306489.csv](https://github.com/user-attachments/files/16383879/data-1721941306489.csv)

**Comment by mark-hayward-erg** [comment]
I did a quick test to confirm that modifying vw_hour_unit_data to change UNION to UNION ALL will increase performance.  Using UNION ALL is preferred because it will not apply an implicit distinct to the query.   HOUR_UNIT_DATA and HOUR_UNIT_DATA_A do not contain overlapping years (except briefly during the annual archive process - see note below), so a distinct is not necessary.

- Existing logic (with UNION) takes ~6 minutes to return 100 rows for one year of data
- Query with UNION ALL instead of UNION takes ~4 minutes to return 100 rows for one year of data
- Query with UNION ALL instead of UNION _AND_ one instance of UNIT_FACT takes ~3 minutes to return 100 rows for one year of data

NOTE: A permanent changes to using UNION instead of UNION ALL will require to addition of a table (similar to the VALID_YEAR table that exists on CAMDPUB) to indicate which years are archived and exist in HOUR_UNIT_DATA_A.  This is necessary to handle the brief period of time that the archive process is occurring, during which the year(s) being archived will exist in both tables.

This test was done prior to analyzing the tables and gathering statistics in the prod database.

**Comment by mark-hayward-erg** [comment]
Forcing an analyze on HOUR__UNIT_DATA did not improve performance.

However, after adding an index on UNIT_ID+OP_YEAR on HOUR_UNIT_DATA:

- Existing logic (with UNION) takes ~2.5 minutes to return 100 rows for one year of data
- Query with UNION ALL instead of UNION takes ~40 seconds to return 100 rows for one year of data

**Comment by mark-hayward-erg** [comment]
The check to determine if the results exceed the record limit of 1,000,000 appears to occur after (or at least simultaneous to) the gathering of the first 100 preview rows.
- For this example that is only filtering on date (and no facility/unit attributes), executing a simple count query against HOUR_UNIT_DATA (without joining in UNIT_FACT) takes 12 seconds to get the record count of 12,546,363

**Comment by mark-hayward-erg** [comment]
Added indexes on UNIT_ID+OP_YEAR to:

- HOUR_UNIT_DATA
- HOUR_UNIT_DATA_A
- DAY_UNIT_DATA
- DAY_UNIT_DATA_A

The month, quarter, and annual tables are already indexed on unit+year.

**Comment by maheese** [comment]
@mark-hayward-erg I was able to get a query to timeout at the gateway in test and I can see that its still running in the database session.

I used this query in the campd-ui at 

/easey/test/emissions-mgmt/emissions/apportioned/hourly/by-facility?page=1&perPage=100&beginDate=2009-01-01&endDate=2023-01-31&operatingHoursOnly=true

If you let it run in the browser the api gateway will timeout after 5 mins however the database session is still there processing the query.  Also I've noticed that the UI appears to retry this query 3 times before finally giving up.  So you can have three database sessions processing the same query.  Eventually when the UI gives up you do see this:

![Image](https://github.com/user-attachments/assets/d4de44fb-2492-40cc-ae05-cba2d81e571d)

The gorouter reports this:

17:21:39.336: [RTR.6] api-easey-tst.app.cloud.gov - [2024-07-29T21:16:39.189752379Z] "GET /emissions-mgmt/emissions/apportioned/hourly/by-facility?page=1&perPage=100&beginDate=2009-01-01&endDate=2023-01-31&operatingHoursOnly=true HTTP/1.1" 499 0 22 "https://campd-tst.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "127.0.0.1:36164" "10.10.2.11:61002" x_forwarded_for:"134.67.29.73, 127.0.0.1, 134.67.29.73, 52.222.122.97, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"3dd4b76c-e6e9-4e77-5031-25ba7581b947" response_time:300.146410 gorouter_time:0.000088 app_id:"f4317c57-a6c1-4894-a889-32f7e1b4b622" app_index:"0" instance_id:"bd255f74-7acd-4572-7a17-2d34" x_cf_routererror:"endpoint_failure (context canceled)" x_b3_traceid:"3dd4b76ce6e94e77503125ba7581b947" x_b3_spanid:"503125ba7581b947" x_b3_parentspanid:"-" b3:"3dd4b76ce6e94e77503125ba7581b947-503125ba7581b947"

When the database session is cancelled in pg_admin this is what's output to the application logs:

17:31:33.905: [APP/PROC/WEB.0] [Nest] 144  - 07/29/2024, 5:31:33 PM   ERROR [/emissions-mgmt/emissions/apportioned/hourly/by-facility?page=1&perPage=100&beginDate=2009-01-01&endDate=2023-01-31&operatingHoursOnly=true] terminating connection due to administrator command
17:31:33.905: [APP/PROC/WEB.0] QueryFailedError: terminating connection due to administrator command
17:31:33.905: [APP/PROC/WEB.0]     at PostgresQueryRunner.query (/home/vcap/deps/0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
17:31:33.905: [APP/PROC/WEB.0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:31:33.905: [APP/PROC/WEB.0]     at async SelectQueryBuilder.loadRawResults (/home/vcap/deps/0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2007:25)
17:31:33.905: [APP/PROC/WEB.0]     at async SelectQueryBuilder.getRawMany (/home/vcap/deps/0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:599:29)
17:31:33.905: [APP/PROC/WEB.0]     at async HourUnitDataRepository.getEmissionsFacilityAggregation (/home/vcap/app/dist/apportioned-emissions/hourly/hour-unit-data.repository.js:71:19)
17:31:33.905: [APP/PROC/WEB.0]     at async HourlyApportionedEmissionsService.getEmissionsFacilityAggregation (/home/vcap/app/dist/apportioned-emissions/hourly/hourly-apportioned-emissions.service.js:42:21)

When the request is cancelled by the gateway the application is not cancelling the query.

**Comment by mark-hayward-erg** [comment]
Added #6337 to modify CAMPD emissions views to remove use of UNION (replacing with UNION ALL).
