### ISSUE TITLE
Bug: Imported files with removed componentId data still display the removed data

### ISSUE THREAD

**Issue by ibarra-michelle** [US-EPA-CAMD/PI-1#6349]
**Description:** Configurations with imported files that were modified to add then remove new componentId data still display the removed componentId data in ECMPS 2.0. Files to reproduce the issue are at the end of this comment.
- This issue appears in two different configurations:
  - ORIS 470 Location 1 (when testing #6309  ) 
  - ORIS 3 Location 6A (when testing #6217 )

**Steps to reproduce the issue**
1. Login to to the ECMPS 2.0 test environment as a Data Submitter.
2. Navigate to the MP module, select the following configuration, and click Open & Checkout: ORIS 470 Location1
3. Click the "Revert to the Official Record," button.
4. Click the, "Export Data," button and save the file.
5. Open the exported file and in the componentData and monitoringSystemData section, modify, and dave the data (see file titled, "add-compId-321....json"):
- copy & paste the componentId 117 data, modify the iD from 117 to 321, modify the startDate and start hour
- modify the componentId 117 to add an endDate and endHour; 
6. Import the saved file, navigate to the Sections dropdown, select Systems, click the View/Edit link for the System ID 117, and then view the new componentId data 321 and modified componentId 117 with the endDate and endHour.
7. Import the original export file that does not have the new componentId data.
8. After a successful import, in the Systems view when viewing System ID 117, the user will still see the componentId data 321 and modified componentId 117 without and endDate and endHour, and the componentId 117 with only a startDate and startHour.

![Image](https://github.com/user-attachments/assets/c1e896f9-5e7d-4132-af04-06ec405df495)

**Files to reproduce the issue:**
[add-compId-321-MP Export - Comanche (470), undefined (8-6-2024) (1).json](https://github.com/user-attachments/files/16515120/add-compId-321-MP.Export.-.Comanche.470.undefined.8-6-2024.1.json)
[MP Export - Comanche (470), undefined (8-6-2024) (1).json](https://github.com/user-attachments/files/16515121/MP.Export.-.Comanche.470.undefined.8-6-2024.1.json)
[add-compId-XY1-MP Export - Barry, undefined (8-6-2024).json](https://github.com/user-attachments/files/16515122/add-compId-XY1-MP.Export.-.Barry.undefined.8-6-2024.json)
[MP Export - Barry, undefined (8-6-2024).json](https://github.com/user-attachments/files/16515119/MP.Export.-.Barry.undefined.8-6-2024.json)

FYA @bryanramirez1 and @maheese

**Comment by alangmaid** [comment]
Reported issue is app feature, not a bug.
