### ISSUE TITLE
Performance Test Execution in BlazeMeter - Emissions - Export and Open Submission Window

### ISSUE THREAD

**Issue by IkeC-dpc** [US-EPA-CAMD/PI-1#6359]
**1. Performance Test Execution in BlazeMeter:**
   - Upon creation of a successful script for Emissions - Export and Open Submission Window
   - Execute the script with multiple users (e.g., 5 to 10 users).
   - Monitor the performance and gather results.

**2. Purpose:**
If we have a successful script, then we can leverage this and maybe the Developers can come up with a “Stored Procedure” that can load up all the necessary files before start testing in Perf environment.

**3. Related Ticket:** https://github.com/US-EPA-CAMD/easey-ui/issues/6358

**Comment by annalbrecht** [comment]
Moved to sprint 14 since finishing this ticket is dependent on resolution of tickets in sprint 14.

**Comment by IkeC-dpc** [comment]
This ticket [6359] will be obsolete once #6455 and #6460 both are successfully completed.

**Comment by alangmaid** [comment]
Replaced by #6460
