### ISSUE TITLE
Beta Bug: Axios Error with status code 400

### ISSUE THREAD

**Issue by ibarra-michelle** [US-EPA-CAMD/PI-1#6411]
The industry beta tester reported in RT#75470 that they received two different error messages approximately 30-minutes being logged in and while working. Two screenshots of the error messages can also be found below. 

**Error messages:**
1. Axios 400 error 
2. Internal issue error. 

**Additional Details:** 
1. **Date/time of the Error:** This has happened 9/26/2024 and 9/27/2024 anywhere from 8am CDT to 1pm CDT.
2. **ORIS code and configuration**:  Valley WEPCO 4042 1, 2, CS1 and Valley WEPCO 4042 3. 4, CS2
3. **Reporting year & quarter**: 2024 Q3
4. **Modules error was experience in**: MP, EM, Eval

**Screenshot 1**: Axios error message
![Image](https://github.com/user-attachments/assets/31e39c8c-5169-45d5-a737-c72bdf5f7656)

**Screenshot 2**
![Image](https://github.com/user-attachments/assets/f9c5708d-b9de-42c3-80be-e58737e9d488)

**Comment by annalbrecht** [comment]
We are going to wait and see if other users report the same error before working on this.

**Comment by annalbrecht** [comment]
Error has not reoccurred, so marking this as invalid for now.
