### ISSUE TITLE
Input Validation for CAMPD v1.5 API - `easey-account-api`

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6416]
```markdown
Overview
The easey-account-api has been identified as lacking sufficient input validation. This ticket focuses on implementing input 
validation to ensure that all user inputs are correctly sanitized and parameterized to prevent injection attacks and invalid data submissions.

 Key Tasks
- Add input validation for account-related endpoints to ensure all inputs are properly sanitized and validated.
- Use decorators to enforce type validation (e.g., string or number) on all incoming data.
- Apply parameterized queries to mitigate the risk of SQL injection.
- Must write unit tests to validate that inputs are properly sanitized and verified.

 Acceptance Criteria
- All inputs must be validated for type, length, and content.
- Invalid inputs should trigger a `400 Bad Request` response with detailed error messages.
- SQL injection prevention should be enforced through parameterized queries.
- Unit tests must confirm that validation logic is correctly implemented across all inputs.

**Comment by lgiannini1** [comment]
- The following account management endpoints have input validation and return a 400 error when invalid inputs are entered
     - emissions-compliance
          - [x] stateCode
          - [x] facilityId
          - [ ] ownerOperator (the ownerOperator field is a simple string and has no validation)
          - [x] year
          - [x] page
          - [x] perpage
     - allowance-compliance
          - [x] stateCode
          - [x] facilityId
          - [ ] ownerOperator (the ownerOperator field is a simple string and has no validation)
          - [x] year
          - [x] page
          - [x] perpage
     - allowance-transactions
          - [x] accountType
          - [x] accountNumber
          - [x] facilityId
          - [x] stateCode
          - [x] programCodeInfo
          - [ ] ownerOperator (the ownerOperator field is a simple string and has no validation)
          - [x] transactionBeginDate
          - [x] transactionEndDate
          - [x] transactionType
          - [x] vintageYear
          - [x] page
          - [x] perPage
     - allowance-holdings
          - [x] accountType
          - [x] accountNumber
          - [x] facilityId
          - [x] stateCode
          - [x] vintageYear
          - [ ] ownerOperator (the ownerOperator field is a simple string and has no validation)
          - [x] programCodeInfo
          - [x] page
          - [x] perPage
     - accounts/attributes
          - [x] accountType
          - [x] accountNumber
          - [x] facilityId
          - [x] stateCode
          - [ ] ownerOperator (the ownerOperator field is a simple string and has no validation)
          - [x] programCodeInfo
          - [x] page
          - [x] perPage

**Comment by szintgraff** [comment]
Mike and I discussed the remaining items that don't have input validation above. Lets add a ticket to the back log and move forward with these as is.

**Comment by szintgraff** [comment]
The UI functionality was tested and I used Karina's API-examples to run test queries in staging and the data pulls looked normal I triggered a few 400 errors successfully as well. Moving to ready to deploy. Great work everyone!

**Comment by spetros-do** [comment]
```markdown

Summary of changes: 
The goal is to improve input validation logic, error handling, debugging & logging.
Files impacted include: 

1. check-catalog.service.ts
	-- Logic: manages catalog checks using a static array. 
	-- Target: To format msgs dynamically using plugins. 

2. interface.index.ts
	-- Logic: It defines 'ts' interfaces for db lookup validations
	-- Target: To support options for numeric validation, ignore empty values & custom find functions. 
	
3. validator-options.interface.ts
	-- Logic: It defines 'ts' inferfaces to standardize config's for db validation.
	-- Target: To facilitate validation workflows. 
	
4. db-lookup.pipe.ts
	-- Logic: Decorator function for validating db lookups. 
	-- Target: To ensure dynamic configuration of validation logic. 
	
5. db-lookup.validator.spec.ts
	-- Logic: Unit tests for DbLookupValidator. 
	-- Target: To mock EntityManager to isolate test scenarios. 
	
6. db-lookup.validator.ts
	-- Logic: Validation of values against db entities via TypeORM.
	-- Target: To ensure input values are valid db records b/f processing further. 
	
7. is-valid-codes.validator.ts
	-- Logic: Validates multiple codes against db entities, splits and filters input strings for validation.
	-- Target: To ensure validation results match input count and handle inputs with delimiters like & |.
