### ISSUE TITLE
Input Validation for CAMPD v1.5 API - `easey-emissions-api`

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6418]
```markdown
 Overview
The easey-emissions-api is critical for handling emissions data, but it currently lacks robust input validation. This ticket focuses on implementing input validation to safeguard against improper inputs, particularly for emissions data submissions.

 Key Tasks
- Validate all input parameters for emissions data, including date ranges, numeric values, and file inputs.
- Implement type-checking decorators to enforce proper data types (e.g., dates, numbers, strings).
- Add input sanitization to protect against SQL injection and ensure data integrity.
- Write unit tests to confirm the validation logic and error handling for all endpoints.

 Acceptance Criteria
- All inputs must be validated and sanitized to ensure no harmful data can be submitted.
- Incorrect data formats should return a `400 Bad Request` response with appropriate error messages.
- SQL injection vulnerabilities must be mitigated through parameterized queries and sanitization techniques.
- Test coverage must confirm that all validation and error handling logic works as expected.

**Comment by lgiannini1** [comment]
The following account management endpoints have input validation and return a 400 error when invalid inputs are entered
- emissions/apportioned/hourly
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [ ] operatingHoursOnly
     - [x] page
     - [x] perPage
- emissions/apportioned/hourly/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [ ] operatingHoursOnly
     - [x] page
     - [x] perPage
- emissions/apportioned/hourly/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [ ] operatingHoursOnly
     - [x] page
     - [x] perPage
- emissions/apportioned/hourly/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [ ] operatingHoursOnly
     - [x] page
     - [x] perPage
- emissions/apportioned/daily
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [x] page
     - [x] perPage
- emissions/apportioned/daily/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [x] page
     - [x] perPage
- emissions/apportioned/daily/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [x] page
     - [x] perPage
- emissions/apportioned/daily/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] beginDate
     - [x] endDate
     - [x] page
     - [x] perPage
- emissions/apportioned/monthly
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] month
     - [x] page
     - [x] perPage
- emissions/apportioned/monthly/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] month
     - [x] page
     - [x] perPage
- emissions/apportioned/monthly/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] month
     - [x] page
     - [x] perPage
- emissions/apportioned/monthly/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] month
     - [x] page
     - [x] perPage
- emissions/apportioned/quarterly
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] quarter
     - [x] page
     - [x] perPage
- emissions/apportioned/quarterly/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] quarter
     - [x] page
     - [x] perPage
- emissions/apportioned/quarterly/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] quarter
     - [x] page
     - [x] perPage
- emissions/apportioned/quarterly/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] quarter
     - [x] page
     - [x] perPage
- emissions/apportioned/annual
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] page
     - [x] perPage
- emissions/apportioned/annual/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] page
     - [x] perPage
- emissions/apportioned/annual/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] page
     - [x] perPage
- emissions/apportioned/annual/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [x] year
     - [x] page
     - [x] perPage
- emissions/apportioned/ozone
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [ ] year
     - [x] page
     - [x] perPage
- emissions/apportioned/ozone/by-facility
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [ ] year
     - [x] page
     - [x] perPage
- emissions/apportioned/ozone/by-state
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [ ] year
     - [x] page
     - [x] perPage
- emissions/apportioned/ozone/nationally
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] programCodeInfo
     - [ ] year
     - [x] page
     - [x] perPage
- emissions/apportioned/mats/attributes/applicable
     - [x] year
- emissions/apportioned/mats/hourly
     - [x] stateCode
     - [x] facilityId
     - [x] unitType
     - [x] unitFuelType
     - [x] controlTechnologies
     - [x] beginDate
     - [x] endDate
     - [ ] operatingHoursOnly
     - [x] page
     - [x] perPage

**Comment by lgiannini1** [comment]
@spetros-do the operatingHoursOnly field in the apportioned/hourly or apportioned/mats/hourly endpoints don't seem to have any validation on them. Same with the year field in the apportioned/ozone endpoints.

**Comment by szintgraff** [comment]
The UI functionality was tested and I used Karina's API-examples to run test queries in staging and the data pulls looked normal I triggered a few 400 errors successfully as well. Moving to ready to deploy. Great work everyone!

**Comment by spetros-do** [comment]
```markdown

Summary of changes: 
The goal is to improve input validation logic, error handling, debugging & logging.
Files impacted include: 

1. check-catalog.service.ts
	-- Logic: manages catalog checks using a static array. 
	-- Target: To format msgs dynamically using plugins. 

2. interface.index.ts
	-- Logic: It defines 'ts' interfaces for db lookup validations
	-- Target: To support options for numeric validation, ignore empty values & custom find functions. 
	
3. validator-options.interface.ts
	-- Logic: It defines 'ts' inferfaces to standardize config's for db validation.
	-- Target: To facilitate validation workflows. 
	
4. db-lookup.pipe.ts
	-- Logic: Decorator function for validating db lookups. 
	-- Target: To ensure dynamic configuration of validation logic. 
	
5. db-lookup.validator.spec.ts
	-- Logic: Unit tests for DbLookupValidator. 
	-- Target: To mock EntityManager to isolate test scenarios. 
	
6. db-lookup.validator.ts
	-- Logic: Validation of values against db entities via TypeORM.
	-- Target: To ensure input values are valid db records b/f processing further. 
	
7. is-valid-codes.validator.ts
	-- Logic: Validates multiple codes against db entities, splits and filters input strings for validation.
	-- Target: To ensure validation results match input count and handle inputs with delimiters like & |.
