### ISSUE TITLE
Define bug triage process

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#644]

**Comment by mosesdeeCVP** [comment]
Task Completed and available on Teams:

https://teams.microsoft.com/l/file/D9C017B2-0F72-473B-BD8E-5EA7E18E695A?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pptx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FGeneral%20Project%20Documents%2FTesting%2FDefect%20Triage%20Process%20-%20EPA%20CAMD%20-%20v1.2.pptx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23
