### ISSUE TITLE
Address unit test coverage for Emissions API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#646]
Update unit tests to reach at least 70% code coverage.

**Comment by junie-stigdon** [comment]
## Pull Request

- Estimated SonarCloud Coverage: 82.2%
- Added npm package _Sinon v9.2.3_ to devDependencies 
  - Made mocking EntityManager easier
- Added dto/hourly-apportioned-emissions.params.dto.spec.ts 
  - Able to get 100% coverage on validation pipes
- Used Format Document Prettier on controller.spec file
- Added tests to service.spec
- 100% coverage on Controller, Service, and Repository
- gitignore: test-report.xml
