### ISSUE TITLE
Address unit test coverage for Monitoring Plan API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#647]
Update unit tests to reach at least 70% code coverage.

**Comment by sdhawan16** [comment]
Wrote unit tests for monitor-method and supplemental-methods and it is now at 100% coverage
Will continue working on monitor-plan unit tests

**Comment by junie-stigdon** [comment]
Unit tests for monitor-location are at 100%

**Comment by sdhawan16** [comment]
Created PR https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/14

Updated unit tests to reach at least 70% code coverage

- Estimated SonarCloud Coverage: 72%
- 100% coverage on Controller, Service, and Repository for monitor-plan, monitor-location, monitor-method, and supplemental-methods
- gitignore: test-report.xml
- Capitalized class name of supplemental methods controller and updated name within module

**Comment by sdhawan16** [comment]
PR merged into develop branch of easey-monitor-plan-api  (US-EPA-CAMD/easey-monitor-plan-api#14)
SonarCloud coverage is 72%
