### ISSUE TITLE
Client token validation for workspace endpoint

### ISSUE THREAD

**Issue by ergjustin** [US-EPA-CAMD/PI-1#6474]
Workspace endpoints calls are only from ecmps-ui and cannot be called directly from anywhere else. For that client token needs to be validated 

**Note:** After implementing ECMPS offline feature, all API request headers contains x-client-token and x-client-id.

**Comment by annalbrecht** [comment]
Create 5 tickets, one for each API.

**Comment by ergjustin** [comment]
Created tickets for Add client token validation for workspace endpoint #6489 , #6490, #6491, #6492, #6493.
Hoping this ticket #6474 for create a decoration in easey-common for clientValidation

**Comment by annalbrecht** [comment]
With the creation of the new tickets, this ticket is OBE.
