### ISSUE TITLE
Create a new ZAP Security Scan Workflow for ECMPS 2.0

### ISSUE THREAD

**Issue by yonatan-dp** [US-EPA-CAMD/PI-1#6480]
Create a GitHub Actions workflow that performs automated security scans on ECMPS 2.0 API endpoints using OWASP ZAP (Zed Attack Proxy). 
Model the workflow after "API Full Zap Scan" workflow. 
The new workflow should be generic and maintainable, supporting different APIs without hardcoded configurations.

**Acceptance Criteria**

- The workflow successfully scans a given backend API for security vulnerabilities

**Comment by maheese** [comment]
This is complete.  We can use the "API Security Scan with Selectable Token" in the DevOps repo to run a ZAP scan against any of the APIs.
