### ISSUE TITLE
508 review of initial EASEY-OUT sort/filter UI wireframes

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#649]
- [ ] Anthony to perform 508 compliance review

**Comment by aprematta** [comment]
[EPA CAMPD Wireframe Review.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6031015/EPA.CAMPD.Wireframe.Review.docx)

**Comment by aprematta** [comment]
Attaching review of the wireframes and closing the ticket.
