### ISSUE TITLE
Add client token validation for emissions-mgmt's workspace endpoint

### ISSUE THREAD

**Issue by ergjustin** [US-EPA-CAMD/PI-1#6490]
Workspace endpoint calls are from ecmps-ui and cannot be called directly from anywhere else. Listed endpoints require client token validation.

| Method | API  |
| :---: | --- |
| | $\textsf{\color{#8250df}{Emissions}}$|
| $\textsf{\color{#61affe}{GET}}$ | emissions-mgmt/workspace/emissions/export |
| $\textsf{\color{#49cc90}{POST}}$ |  emissions-mgmt/workspace/emissions/import |
| $\textsf{\color{#61affe}{GET}}$ | emissions-mgmt/workspace/emissions | 
| | $\textsf{\color{#8250df}{Emissions Views}}$ |
| $\textsf{\color{#61affe}{GET}}$  | emissions-mgmt/workspace/emissions/views|
| $\textsf{\color{#61affe}{GET}}$  | emissions-mgmt/workspace/emissions/views/|{viewCode}|

**Comment by mark-hayward-erg** [comment]
Based on the client token discussion12/16, this ticket is considered invalid.
