### ISSUE TITLE
Add client token validation for facilities-mgmt's workspace endpoint

### ISSUE THREAD

**Issue by ergjustin** [US-EPA-CAMD/PI-1#6491]
Workspace endpoint calls are from ecmps-ui and cannot be called directly from anywhere else. Listed endpoints require client token validation.
| Method | API  |
| :---: | --- |
| | $\textsf{\color{#8250df}{Facilities}}$|
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities |
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities/attributes | 
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities/attributes/applicable |
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities/{id} |
| | $\textsf{\color{#8250df}{Units}}$|
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities/{orisCode}/units |
| | $\textsf{\color{#8250df}{Stacks  Pipes}}$|
| $\textsf{\color{#61affe}{GET}}$ | facilities-mgmt/workspace/facilities/{orisCode}/stack-pipes |
| | $\textsf{\color{#8250df}{Unit Stack Configurations}}$|
| $\textsf{\color{#61affe}{GET}}$ |facilities-mgmt/workspace/facilities/{orisCode}/unit-stack-configurations |

**Comment by mark-hayward-erg** [comment]
Based on the client token discussion12/16, this ticket is considered invalid.
