### ISSUE TITLE
Add client token validation for camd-services's workspace endpoint

### ISSUE THREAD

**Issue by ergjustin** [US-EPA-CAMD/PI-1#6492]
Workspace endpoint calls are from ecmps-ui and cannot be called directly from anywhere else. Listed endpoints require client token validation.
| Method | API  |
| :---: | --- |
| | $\textsf{\color{#8250df}{Reports}}$|
| $\textsf{\color{#61affe}{GET}}$ | camd-services/workspace/reports/list |
| $\textsf{\color{#61affe}{GET}}$ | camd-services/workspace/reports |
| | $\textsf{\color{#8250df}{Copy of Record}}$|
| $\textsf{\color{#61affe}{GET}}$ | camd-services/workspace/copy-of-record |
| | $\textsf{\color{#8250df}{Evaluation}}$|
| $\textsf{\color{#49cc90}{POST}}$ |  camd-services/evaluate |
| | $\textsf{\color{#8250df}{MATs File Upload}}$ |
| $\textsf{\color{#61affe}{GET}}$  | camd-services/mats-file-upload/{monPlanId}/{locId}/{testGroupCode}/{testNumber}/import |
| | $\textsf{\color{#8250df}{QA Cert Event Maintenance}}$ |
| $\textsf{\color{#fca130}{PUT}}$  | camd-services/admin/qa-maintenance/extension-exemptions/{id} |
| $\textsf{\color{#f93e3e}{DELETE}}$  | camd-services/admin/qa-maintenance/extension-exemptions/{id} |
| | $\textsf{\color{#8250df}{QA Test Extension Exemption Maintenance}}$ |
| $\textsf{\color{#fca130}{PUT}}$  | camd-services/admin/qa-maintenance/extension-exemptions/{id} |
| $\textsf{\color{#f93e3e}{DELETE}}$  | camd-services/admin/qa-maintenance/extension-exemptions/{id} |
| | $\textsf{\color{#8250df}{QA Test Data Maintenance}}$ |
| $\textsf{\color{#fca130}{PUT}}$  | camd-services/admin/qa-maintenance/test-summary/{id} |
| $\textsf{\color{#f93e3e}{DELETE}}$  | camd-services/admin/qa-maintenance/test-summary/{id} |
| | $\textsf{\color{#8250df}{Submission}}$ |
| $\textsf{\color{#49cc90}{POST}}$  | camd-services/submission/queue |
| $\textsf{\color{#49cc90}{POST}}$  |  camd-services/submission/process |

**Comment by mark-hayward-erg** [comment]
Based on the client token discussion12/16, this ticket is considered invalid.
