### ISSUE TITLE
Determine security vulnerability triage process

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#672]
- [ ] Determine triage process for security findings (Dependabot, SonarCloud, OWASP ZAP, CodeQL), along with EPA NCC security scans
- [ ] Determine how to address security changes that require code updates
- [ ] Determine who reviews results
- [ ] Determine who captures issues in the backlog 
- [ ] Document the process 

Also need to maintain sync with the security control implementation process

Build off @mosesdeeCVP defect triage process

**Comment by MaeganWood64** [comment]
Determine middle person to triage security bugs as they come up
