### ISSUE TITLE
Design and develop Sort/Filter UI user research study

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#686]
- [ ] Talk to product owner and team
- [ ] Determine product owner research goals
- [ ] Identify participant types
- [ ] Identify and study instruments; wireframes, screen share, prototype
- [ ] Develop a research plan

**Comment by nsameerun** [comment]
- [ ] Talk Team to identify Research Goals 

UX Designer: To discover content hierarchy, basic page interaction, and navigation for sort and filter queries to inform wireframes. 

- [ ] Research Objectives 

Inform design and development-- 
Query; sort and filter

- [ ] Identify Participant Types:  

- Data is necessary to perform their role 
- Power Users who design a custom query
- Hourly Apportioned Emissions Data users
- Potential Influencers/Advocates


- [ ] Identify study instruments:

Wireframes, Screen-share, Moderator’s Guide  

- [ ] Type of Study

Quick-Turn, Usability, Qualitative, 1-1
 EPA: Approval (1/26/2021) during Weekly UX Meeting
@areighar @tlageman-epa @kstetsyuk
