### ISSUE TITLE
Debrief of research findings

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#689]
The notes from the debrief on 2/16 can be found [here ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28UX%20Meeting%20Notes.one%7C39f26e63-355a-434e-ac77-d9a3f3d8130a%2F2%5C%2F16%5C%2F2021%20UX%20Weekly%20for%20AMPD%7Cb4b7aa80-5160-4a92-8848-f3c15a088c62%2F%29) .

**Comment by nsameerun** [comment]
- [ ] Informal verbal conversation following the conclusion of interviews 

- [ ] Collective verbal analysis and interpretation of initial finding  during UX Weekly Meeting of the  key learnings and insights from the study

- [ ] EPA/CVP: Review and Consensus

- [ ] EPA: Approval 

@areighar @tlageman-epa @kstetsyuk

**Comment by nsameerun** [comment]
Debrief was during UX weekly meeting on Tuesday, February 16, 2020.  Meeting notes were delivered on Wednesday, February 17, 2020. 

@areighar @tlageman-epa @kstetsyuk
