### ISSUE TITLE
Prepare final user research study (Notes)

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#690]

**Comment by nsameerun** [comment]
- [ ] Provide ppt summary on findings and insights (if requested/TBD)

- [ ] Identify Next Steps, recommended new research opportunities resulting from findings

- [ ] EPA/CVP: Review and Consensus

- [ ] EPA: Approval 

@areighar @tlageman-epa @kstetsyuk

**Comment by nsameerun** [comment]
EPA doesn't require a final user research report for the Query Filter & Sort Study
