### ISSUE TITLE
SPIKE: Research adding cloud.gov sandbox environment to all dev/test/staging APIs

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#722]
Research task to figure out how we might be able to accomplish story #508 

@jwhitehead77 and @maheese will discuss Swagger UI implementation

**Comment by karenhwwoo** [comment]
Plan design around documentation site once API gateway is figured out.

**Comment by jwhitehead77** [comment]
Cannot modify NestJs Swagger UI to include a banner, however, we can use the setDescription method on the Swagger Documentation object and custom css options to display an equivalent banner. This will require changes to the app config, cloud.gov deployment manifest files, and CI/CD pipelines to support the version and published date env variables and to minimize maintenance of these configuration settings.
