### ISSUE TITLE
SPIKE: Research 508 Changes Needed 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#723]
Research any behind the scenes work needed to make UI 508 compliant. See #563 for 508 feedback and guidance  

Need to consider tab navigation for #534 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

**Comment by Qb10** [comment]
https://docs.google.com/document/d/1yv-SnumCEiBeW24N2OrKSjEfzb2QUByffvmpD1OQsYY/edit?usp=sharing
