### ISSUE TITLE
STORY: Implement EPA Search 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#724]
## User Story
As a 
I want
So that

## Acceptance Criteria
Given
When
Then

## Context
Need service integration info from @maheese 

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

**Comment by david-cvp** [comment]
@addisgmichael @Qb10 EPA search link is on line 48

Thanks @ibarra-michelle for the link:

https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/master/index.html

**Comment by david-cvp** [comment]
Covered by #725
