### ISSUE TITLE
STORY: Implement Updated Footer

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#726]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### Acceptance Criteria
As the EPA I want the updated footer to be displayed so that it is compliant with the updated template 

Given a user has accessed the EASEY In functionality
When the application is displayed
Then it is displayed [with the updated footer](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/screen/0f4ebdca-2340-44dd-9ca6-49e02661b7f4)

Developer link for the wide template: https://xd.adobe.com/view/08505c73-3291-4c0a-819f-982951ae417f-5d03/specs/ (open the code tab "</>" to view downloadable assets, EPA Logo an EPA Seal, both available as SVG, PNG, and PDF)

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by mosesdeeCVP** [comment]
![726 Implement Updated Footer.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d2326e20-3738-427d-8a2a-125b308ca1c6)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC94](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274713) - Passed

**Comment by mosesdeeCVP** [comment]
Product Owner has accepted the story - Closed
