### ISSUE TITLE
Shift Content and Add Nav Display 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#728]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

### Acceptance Criteria
As a user I want the MP content to be displayed in the updated template so that I can use more screen area 

Given a user has accessed the facilities and MP methods functions
When the content is displayed
Then it is displayed [in the updated template  ](https://xd.adobe.com/view/e1a73023-0085-4e20-aa61-73e0e85cb064-b4f4/)

Given a user has accessed the EASEY In functionality
When the application is displayed
Then a navigation menu is displayed

Given the navigation bar is displayed
When Monitoring Plan is selected
Then the Monitoring Plan is displayed 

Given the navigation bar is displayed
When Workspace is displayed
Then the Workspace can be expanded or collapsed 

Given the navigation bar is displayed
When an inactive link is selected
Then the "page not found" is displayed 

Account management not active
Profile not active
CAMD Apps not active
Emissions and QA links not active
Nav bar does not collapse
Typography, font, and icons may not be the same as in wireframes 

## Testing
Test Case: [TC97](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/275618)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by mosesdeeCVP** [comment]
![728 Shift Content and Add Nav Display.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ec56eef1-ae51-48b1-9e41-3dcfeda0670d)

**Comment by mosesdeeCVP** [comment]
![728 Shift Content and Add Nav Display 2.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9500b33a-42d5-4c18-a1a4-566177d19de1)

**Comment by mosesdeeCVP** [comment]
Product Owner has approved the story – Ticket closed.
