### ISSUE TITLE
SPIKE: MP Systems and Components Design 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#731]
Determine design for displaying systems and component data 

Need Mike H, Jason W, Chris W, Alex R, Addis G, Quang B, Karen W, Nada A, Anthony P, Moses D, Jeremey S, Simera H

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

**Comment by david-cvp** [comment]
Plan: Alex will work on wireframes, due 2/19
