### ISSUE TITLE
SPIKE: MP systems/Comp API Design 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#732]
Understand data tables, UI, and determine API design 

tables for system and components
camdecmps.component
camdecmps.compnent_op_supp_data
camdecmps.monitor_system
camdecmps.monitor_system_compnent

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

**Comment by SimeraHailu** [comment]
https://teams.microsoft.com/l/file/B199E6F1-786D-4D45-98A1-35893D2833ED?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2FEASEY-IN%20API%20Design%2FAPI%20Design.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23
