### ISSUE TITLE
Implement Multi select for ORIS code 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#734]
## User Story 
As a user I want to enter filter criteria for multiple ORIS codes so that I can see results for multiple ORIS codes in one query 

NO validation 

## Acceptance Criteria
Given that a user has entered multiple ORIS codes
When the API endpoint is executed
Then the system displays the results for multiple ORIS codes (containing data elements below)

##  Data Elements 

Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO

## Testing
Test Case: [TC82](https://cvpcorp.testquality.com/project/11428/plan/19811/test/273590)
Tester: @davidkwartler

**Comment by junie-stigdon** [comment]
## Pull Request

**Implemented multi select for ORIS code**
- updated the parameter DTO accept an array of numbers for the orisCode
- commented out the validation decorator @IsOrisCode
- updated the repository query to search for all the listed orisCodes
- added ApiQuery in controller and set explode to false

**Other changes**
- removed console.log statements in typerorm.config.ts
- made validation pipes global in main.ts and updated controller

**Comment by junie-stigdon** [comment]
sonar-project.properties now excludes config.ts, module.ts, routes.ts, and main.ts

**Comment by david-cvp** [comment]
TC82 passed

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=3000&beginDate=2019-01-01&endDate=2019-01-31&orisCode=127,612

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/9022dfd4-24f5-496a-8da0-4031c3d29552)
