### ISSUE TITLE
Implement multi select for Unit type 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#736]
## User Story 
As a user I want to enter filter criteria for multiple unit types so that I can see results for multiple unit types in one query

NO validation

## Acceptance Criteria

Given that a user has entered multiple unit types without white space(s) before or after the delimiter 
When the API endpoint is executed
Then the system displays the results for multiple unit types (containing data elements below)
 

Given that a user has entered multiple unit types with white space(s) before or after the delimiter 
When the API endpoint is executed
Then the system displays the results for multiple unit types (containing data elements below)

##  Data Elements 
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO

## Testing
Test Case: [TC84](https://cvpcorp.testquality.com/project/11428/plan/19811/test/273592)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
TC84 passed

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=3000&beginDate=2019-01-01&endDate=2019-01-02&unitType=Dry%20bottom%20wall-fired%20boiler,Combined%20cycle

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/b4c3f359-b616-4058-96a9-6cdfe696e43e)
