### ISSUE TITLE
STORY: Implement multi select for Fuel Type 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#737]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a user I want to enter filter criteria for multiple fuel types so that I can see results for multiple fuel types in one query 

## Scope
Send multiple fuel types
Will need to accept primary and secondary types (comma delin. list)
will make case insensitive 
Return data for multiple values
NO validation
When entering multiple values the API will allow comma separated list of values including one or more whitespace(s) before and after the delimiter but will not require whitespace
Contained search 

## Acceptance Criteria 
Given that a user has entered multiple fuel types in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the results for multiple fuel types (containing data elements below)

Given that a user has entered multiple fuel types without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple fuel types (containing data elements below)

Given that a user has entered multiple fuel types with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple fuel types (containing data elements below)

## Data Elements 
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO

## Testing
Test Case: [TC85](https://cvpcorp.testquality.com/project/11428/plan/19811/test/274208)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by sdhawan16** [comment]
Created PR
Implemented multiselect for unitFuelType

- Updated paramsDTO to account for multiselect
- Removed logic for unitFuelType from service
- Updated repository query to search for all unitFuelTypes in the provided list
- Added APIQuery for unitFuelType to controller
- Updated unit tests to reflect multiselect criteria

**Comment by sdhawan16** [comment]
Need to move pagination from service to repo

**Comment by sdhawan16** [comment]
Moving the pagination to the repository would require additional testing since it requires us to change the current query. We decided on keeping the pagination in the service for now and will bring in additional work in the future to move the pagination to the repository and to perform regression testing.

**Comment by david-cvp** [comment]
TC85 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=3000&beginDate=2019-01-01&endDate=2019-01-31&unitFuelType=coal|%20wood

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/12890656-3855-4ea5-b1a2-8d6eefed14dd)
