### ISSUE TITLE
STORY: Implement multi select for Control Tech 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#738]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a user I want to enter filter criteria for multiple control technologies so that I can see results for multiple control technologies in one query 

## Scope
Send multiple control tech 
Will make case insensitive 
Return data for multiple values
NO validation
When entering multiple values the API will allow comma separated list of values including one or more whitespace(s) before and after the delimiter but will not require whitespace
Contained search 

## Acceptance Criteria 
Given that a user has entered multiple control technologies in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the results for multiple control technologies (containing data elements below)

Given that a user has entered multiple control technologies without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple control technologies(containing data elements below)

Given that a user has entered multiple control technologies with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple control technologies(containing data elements below)

## Data Elements 
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO

## Testing
Test Case: [TC86](https://cvpcorp.testquality.com/project/11428/plan/19811/test/274209)
Tester: @davidkwartler 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the staging/integration environment?

**Comment by junie-stigdon** [comment]
Collaborated with @sdhawan16 and discussed how to move the controlTechnology query logic from the service to the repo using regex.

**Comment by junie-stigdon** [comment]
## Pull Request

- Updated DTO to account for multiselect
- Removed controlTechnologies logic from the service and moved to the repo
- Updated controller to use pipe delimiter
- Unit tests

**Comment by david-cvp** [comment]
TC86 passed not including partial filter criteria

Will discuss in Monday's DSU

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly?page=1&perPage=500&beginDate=2019-01-01&endDate=2019-03-01&controlTechnologies=Baghouse|Wet%20Limestone

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/6b372fc4-5c0b-4109-8ff9-d7fec4dd7fc9)

**Comment by david-cvp** [comment]
Removed partial filter acceptance criteria
