### ISSUE TITLE
STORY: Validate multiple values for Unit Type

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#741]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a CAMPD user I want to enter valid filter criteria for multiple unit types so that I can see results for multiple unit types in one query  

## Acceptance Criteria 
Given a user has entered an invalid parameter for unit type 
When the error message is displayed
Then the error messages contain a url to the end point to find the correct data 
One or more unit types are not valid. Refer to the list of available unit types for valid values [placeholder for link to endpoint] fv-1

## Context 
Send valid and invalid values
Validate the values
If ANY invalid value, give error message for each invalid value and query stops
If ALL values are valid, return results

NOTE: Need confirmation from Travis L and EPA on error message format

##  Data Elements 
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO| PRG_CODE_INFO| ASSOC_STACKS

## Testing 
Test Case:  [TC105](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275770)
Tester:  @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by david-cvp** [comment]
TC105 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/dd14d6c9-03d2-46cc-acd3-c125c0b3a59c)
