### ISSUE TITLE
STORY: Validate multiple values for Fuel Type

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#743]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a CAMPD user I want to enter valid filter criteria for multiple fuel types so that I can see results for multiple fuel types in one query 

## Acceptance Criteria 
Given a user has entered one or more invalid values for fuel type
When the error message is displayed
Then the error messages contain a url to the end point to find the correct data
"One or more unit fuel types are not valid. Refer to the list of available unit fuel types for valid values [placeholder for link to endpoint] [FV-2](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Context 
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Send valid and invalid values
Validate the values
If ANY invalid value, give error message for each invalid value and query stops
If ALL values are valid, return results

NOTE: Need confirmation from Travis L and EPA on error message format

##  Data Elements 

Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO| PRG_CODE_INFO| ASSOC_STACKS

## Testing 
Test Case:  [TC106](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275771)
Tester:  @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by sdhawan16** [comment]
Created PR : 

Implemented multi-select unit fuel type validation

- Added @IsUnitFuelType validation decorator along with message to  HourlyApportionedEmissionsParamsDTO 
- Updated @IsUnitFuelType decorator to be case insensitive

**Comment by david-cvp** [comment]
TC106 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/7852a45c-a5ea-4a57-87e2-ff7a207671e3)
