### ISSUE TITLE
STORY: Create Endpoint for Unit Type

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#745]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a user I want to see a list of valid unit types so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return unit type records in JSON format
And for each record will display: 

- Unit Type Code
- Unit Type Description 
- Sort Order (values may be blank)

## Context
Will be in the Master data service 

(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Dev Tasks
- [x] Create UnitTypeCode entity
- [x] Create UnitTypeCode DTO
- [x] Create BaseMap
- [x] Create UnitTypeCodeMap
- [x] Create Module 
- [x] Create Controller and add endpoint
- [x] Create Service to return UnitTypeCode data to the Controller
- [x] Unit tests

## Testing
Test Case: [TC87](https://cvpcorp.testquality.com/project/11428/plan/19811/test/274210)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by junie-stigdon** [comment]
## Pull Request

- removed app.controller and app.service (they were for scaffolding only)
- Created UnitTypeCodeModule
- Updated app.module to use UnitTypeCodeModule
- Created UnitTypeCodeDTO
- Created UnitTypeCode entity
- Created BaseMap
- Created UnitTypeCodeMap
- Created a __routes.ts__ file
- Created GET endpoint in controller ( /unit-type-code )
- Created service to return valid unit types to controller
- Created a UnitTypeCodeRepository in order to use repository.find in service
- Unit Tests

**Comment by junie-stigdon** [comment]
Updated file and class names from UnitTypeCode to UnitTypes where necessary 
GET /unit-types

**Comment by david-cvp** [comment]
TC87 passed

@tlageman-epa 

https://easey-dev.app.cloud.gov/api/master-data-mgmt/unit-types

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/b6740e7e-5692-40ac-96a2-c74165b8a59c)
