### ISSUE TITLE
STORY: Create Endpoint for Fuel Types

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#746]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to see a list of valid fuel types so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return unit type records in JSON format
And for each record will display:

- Fuel Type Code
- Fuel Group Code
- Fuel Type Description 

## Context
Will be in the Master data service 
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Dev Tasks
- [x]  Create FuelTypeCode entity
- [x]  Create FuelTypeCode DTO
- [x]  Create BaseMap
- [x]  Create FuelTypeCodeMap
- [x]  Create Module
- [x]  Create routes.ts file
- [x] Create Repository
- [x]  Create Controller and add endpoint
- [x]  Create Service to return FuelTypeCode data to the Controller
- [x]  Unit tests

## Testing
Test Case: [TC88](https://cvpcorp.testquality.com/project/11428/plan/19811/test/274211)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by sdhawan16** [comment]
Finished writing unit tests, need to change some file names to match convention before creating PR

**Comment by sdhawan16** [comment]
Created PR

Created a Fuel Types endpoint that returns data from the fuel_type_code table

-  Created FuelType entity
-  Created FuelTypeDTO
-  Created FuelTypeMap
-  Created FuelTypesModule
-  Created FuelTypes Controller and added GET endpoint (/fuel-types)
-  Created FuelTypesRepository
-  Updated routes.ts file with fuel-types route
-  Created FuelTypesService to return fuel types to the controller
-  Updated app.module to use FuelTypesModule
-  Unit tests

**Comment by sdhawan16** [comment]
Request URL for Fuel Types : https://easey-dev.app.cloud.gov/api/master-data-mgmt/fuel-types

**Comment by david-cvp** [comment]
TC88 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/060b4b2d-d3b5-4b55-86e7-7b72936288bf)
