### ISSUE TITLE
STORY: Create Endpoint for Control Tech

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#747]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to see a list of valid control technologies so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return control tech records in JSON format
And for each record will display:

- Control Code
- Control Description
- Control Equip Param Code 

## Context
Will be in the Master data service 
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Dev Tasks
- [x] Create ControlCode entity
- [x] Create ControlTech DTO
- [x] Create ControlTechMap
- [x] Create ControlTechModule 
- [x] Create Controller and add endpoint
- [x] Create Service to return ControlTech data to the Controller
- [x] Create repo to use repository.find in service
- [x] Unit tests

## Testing
Test Case: [TC89](https://cvpcorp.testquality.com/project/11428/plan/19811/test/274212)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by junie-stigdon** [comment]
## Pull Request

- Created a module for control technologies and added it to app.module
- Created ControlTechnology entity
- Created ControlTechnology DTO
- Created ControlTechnology Map
- Added control-technologies to the routes.ts file
- Created GET endpoint in controller ( /control-technologies )
- Created service to return valid control technnologies to controller
- Created ControlTechnologiesRepository in order to use repository.find in service
- Unit Tests

**Comment by david-cvp** [comment]
TC89 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/master-data-mgmt/control-technologies

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/ebc34430-eede-4ea2-820e-af1ef92b2c14)
