### ISSUE TITLE
TASK: Set Up MDM API for error message endpoints

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#748]
- [x] Create an MDM API so that the end points can be displayed in error messages. 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by sdhawan16** [comment]
Set up basic scaffolding for MDM API to return "hello masterDataManagement"
Need to work on how to establish connection with the database

**Comment by sdhawan16** [comment]
Created PR:
PR in EASEY-mdm-api repo (task/748 MDM API scaffolding 1)

Created MDM API Scaffolding

- Created project using NEST CLI
- Set up controller, service, and module to return dummy data "Hello masterDataManagement!"
- Updated Readme file
- Added .github folder with the workflows
- Added manifest files
- Added sonar-project properties file

**Comment by sdhawan16** [comment]
Added unit tests so sonar cloud would run 

Created PR for unit tests :
https://github.com/US-EPA-CAMD/easey-mdm-api/pull/2
Added Unit Tests
