### ISSUE TITLE
Send Query Using Multiple Values for Multiple Parameters 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#749]
As a user I want to send a query that has multiple values in multiple parameters so that I can retrieve all data needed at once

If multiple parameters are sent in a single query (TX, coal), then only values that match all parameters will be returned (AND)
If multiple values are sent for a single parameter (e.g. TX, MD), then all data that matches the values is returned (OR).
If ANY value in ANY parameter is invalid, then the query stops and displays an error message 

Building off #586 cumulative validation for single select

Test case: [TC111](https://cvpcorp.testquality.com/project/11428/plan/19811/test/276283)
Tester @davidkwartler

**Comment by david-cvp** [comment]
TC111 passed @tlageman-epa

All validations work properly in combination

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?beginDate=2019-01-01a&endDate=2019-01-31a&orisCode=127|Invalid&state=MA|Invalid&unitType=Dry%20bottom%20wall-fired%20boiler|Invalid&unitFuelType=Coal|Invalid&controlTechnologies=Wet%20Limestone|Invalid&program=ARP|Invalid

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/f0c78bde-1e4b-4204-8c5f-d19a40e8da20)
