### ISSUE TITLE
TASK: Test Multiple Valid Values Only 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#750]
Ensure that the API will except multiple values in multiple parameters that are valid 

## Testing
Test Case: [TC96](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275494)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
TC96 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?beginDate=2019-01-01&endDate=2019-01-31&unitFuelType=Coal|Wood&controlTechnologies=Wet%20Limestone|Baghouse

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?beginDate=2019-01-01&endDate=2019-01-31&unitType=Dry%20bottom%20wall-fired%20boiler|Combined%20cycle&state=TX|FL
