### ISSUE TITLE
SPIKE: Hourly Apportioned Emissions Static Dataset Design 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#751]
Understand how the delta/changes will be detected
Meet with Informatica to understand how database updates
Determine the plan to generate the data sets (node/core process)
Determine requirements for public S3 bucket on cloud.gov
Determine required test data for static datasets

Jason will do the initial research near the beginning of the PI. Will further refine tasks/spikes/stories after initial research. 

See add'l docs here

https://teams.microsoft.com/_#/files/19%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype?threadId=19%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype&ctx=channel&context=AMPD%2520Data%2520Processing&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FDatateers%252FAMPD%2520%2526%2520CAMD%2520Business%2520Suite%2520Architecture%252FData%2520and%2520Databases%252FAMPD%2520Data%2520Processing

**Comment by jwhitehead77** [comment]
Prototype & Demo code located at https://github.com/US-EPA-CAMD/easey-job-scheduler-demo

The plan is to use Postgres to store the job details and when the process starts all jobs will be pulled from the db and scheduled according to their cron schedule using the Quartz.Net scheduling library. The files generated will be stored in S3 and a UI created to provide the ability to explore, filter, and download.
