### ISSUE TITLE
 Implement filter/sort for Account Info Data

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#754]
Original estimate: 40
PI 6 Estimate: 5

**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

- User research 
- Screen Mockups/UI Design 
- Data conversion 
- System requirements 

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
1. Provide Account Info data via API so the API returns all data needed for the CAMPD Release

2. Validate Account Info API parameters to ensure that the request is valid

3. Provide front-end user interface to access Account Info data 

## Context
[Refer to EASEY Out Production List ](https://teams.microsoft.com/l/entity/0d820ecd-def2-4297-adad-78056cde7c78/_djb2_msteams_prefix_3687621406?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype%22%7D&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7)

### **Questions** 

1.  Will owner/ operator and account number/ account name filter on buyer/ seller accounts? 
 Answer: No. The search should be a contains search on all account name/numbers or all account owner/operators for the respective filter.

### **Assumptions** 

- Blank parameter values will return all records
- If multiple parameters are selected in a single query (TX,General Account), then only values that match all parameters will be returned (AND)
- If multiple values are sent for a single parameter (e.g. TX, MD), then all data that matches the values is returned (OR).
- API criteria inputs should not be case sensitive
- API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”)
- Pagination should be optional for APIs
- The API will not accept facility name as filter criteria. It will only accept Facility ID (ORIS code).
- Download limits for the UI will be implemented in future and are out of scope for initial development
- User must select data type and data subtype on the UI before all fields are available
- The site will be responsive

### **API Parameters** 

- Program: Optional, multiple values allowed, active and inactive allowance programss: ARP, CSNOX, CSSO2G1, CSSO2G2, TXSO2, CAIRSO2, CAIRNOX, CSOSG1, CSOSG2, CSNOXOS, CAIROS, NBP, OTC
- Account Type: Optional, multiple values allowed, , values: Facility Account, Unit Account, General Account, Reserve Account, Surrender Account, ALL (UI only)
- Account Number: Optional, multiple values allowed, query will return all records that match Account Number
- Facility ID: Optional, multiple values allowed, query will return all records that match Facility Number (ORIS code)
- Owner/ Operator: Optional, multiple values allowed, query will return all records that match owner OR operator specified
- State: Optional, multiple values allowed, 2 letter postal abbreviation for  the 50 states plus Puerto Rico.

### **UI Parameters**

**Data Type**
Button/ drop down 
Required 
Single select 
Value: Emissions, Allowance, Compliance, default blank 

**Data Sub-Type** 
Drop down 
Required 
Single Select 
Value: :Allowance Holdings,  Allowance Transactions, Account Information, default blank

**Program** 
Drop down, default blank 
Optional 
Multi select 
Value: ARP, CSNOX, CSSO2G1, CSSO2G2, TXSO2, CAIRSO2, CAIRNOX, CSOSG1, CSOSG2, CSNOXOS, CAIROS, NBP, OTC (active/inactive allowance programs)

**Account Type**
Drop down, default blank 
Optional 
Multi Select 
Value: Facility Account, Unit Account, General Account, Reserve Account, Surrender Account, ALL

**Account** 

Account Number
Dynamic search
Search is a contains search on all account numbers 
Results are displayed in Account Name (Account Number) format
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive

If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

Account Name
Dynamic search
Search is a contains search on all account names 
Results are displayed in Account Name (Account Number) format
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

**Facility** 
Facility ID
Dynamic search
Search is a contains search
Results populate in a list, parameters populates when a value is selected from the list
Results are displayed in Facility Name (ORIS Code) format
If no results are found, the system will indicate so. “No facilities match your search.”
Multi Select

**Facility Name** 
Dynamic search
Search is a contains search
Results are displayed in Facility Name (ORIS Code)
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No facilities match your search.”
Multi select

Owner 
Dynamic search
contains search search on all owners

Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

Operator 
Dynamic search
contains search search on all operators 
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select

**State** 
Dynamic search
Search is a “begins with” search
Results populate in a list, parameters populates when a value is selected from the list
Results display the full state name (Texas, not TX)
Multi Select

**_Change Criteria_**
The user will have the ability to clear one, many, or all filter criteria
If the user changes data type or sub data type, then:

- The filter criteria displayed updates accordingly 
- No previously entered filter criteria is retained 

If a user changes data type or sub data type, then filter criteria is cleared 
If the user chooses to clear one or more filter criteria before preview is selected, then the system clears the criteria from the filter and updates any remaining dependent criteria accordingly.
If the user chooses to clear one or more filter criteria after preview is selected, then the system clears the criteria from the filter AND download is disabled until data is previewed.

### **Validations**

**Program:**

1. Validate that the value matches a valid program

Error Message: One or more <   insert property    > are not valid. Refer to the list of available <   insert 
Property   > for valid values [ placeholder for link to endpoint ] FV-100

**Account Type:**
1. Validate that the value matches a valid account type
Value: Facility Account, Unit Account, General Account, Reserve Account, Surrender Account, ALL (UI Only)

Error Message: Error Message: One or more < insert property > are not valid. Refer to the list of available <    insert property   > for valid values [ placeholder for link to endpoint ] FV-100

**Account Number:**
1. Validate that the account number is 12 alphanumeric characters long

Error Message: Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [ placeholder for link to endpoint ] FV-100

**Facility (ORIS Code) :**
1. Validate that the format is correct:

positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message: Error Message: One or more <   insert property   > are not valid. Refer to the list of available < insert property   > for valid values [placeholder for link to endpoint] FV-100

**Owner/Operator:**
1. No Validations

**State:**
1. Validate that value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC

Error Message: One or more states are not valid. Use the two letter postal abbreviation (use TX, not Texas). FV-101

### **Data Preview/ Results:** 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by PRG_CODE> ACCOUNT_NUMBER

ACCOUNT_NUMBER
ACCOUNT_NAME
PRG_CODE
ACCOUNT_TYPE
ORISPL_CODE
UNITID
OWN_DISPLAY
OPR_DISPLAY*
STATE
EPA_REGION
NERC_REGION

* There is an identical data element in the UNIT_COMPLIANCE_DIM table that is not the correct one. It has owner/operator combined; this one is the operator only.

**Data Labels** 

Refer to the CAMPD_DataLables_Allowance_5_12_2021 [here ](https://teams.microsoft.com/l/file/C57F5045-F938-472B-AE6E-51BF711FFA12?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FCoding%20%26%20Error%20Standards%2FCAMPD_DataLables_Allowance_5_12_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Results will display total record count (Viewing the first 100 of X records)
Results in preview are limited to the first 100 records
Results in preview will have a scroll functionality to show all columns/rows
Results columns are are sortable in ascending and descending order (alphanumeric order) . Sort is limited to the original 100 results

**File Selection**
Trigger: The user has at least one record that matches the search criteria, and has previewed the results
The user has the option to select the file output in JSON or CSV format. CSV is the default file type
API will provide the data in the requested format based on user selection in UI

**Download**
Trigger: The user has selected a file output type
When the user selects the option to download, the system creates a file in the format specified containing all records that match the parameters and downloads the file
After a user has chosen to download data, then the system will display the preview of the downloaded results.

**Comment by tlageman-epa** [comment]
@JanellC to answer your questions above. No, buyer/seller is not applicable here. These are not transactions, this is data on every allowance account in each of the programs. The search should be a contains search on all account name/numbers or all account owner/operators for the respective filter.

**Comment by JanellC** [comment]
Completed core functionality. account information functions on the custom data download with end to end functionality. Removed tickets  #2110, and #2089 and from this epic. The removed issues remain on the PI 6 backlog
