### ISSUE TITLE
Create Monitoring Plan data service

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#76]
- [ ] Create model and DTO 
- [ ] Create controller
- [ ] Create data repository 
- [ ] Create module 

AC:
Valid response is returned in Swagger
Verify API is documented correctly in Swagger UI

Notes: Service will use dummy data. Will not have database available.

**Comment by JorjaComer** [comment]
No longer needed. Will be handled by Manage Monitoring Plan Data epic

**Comment by david-cvp** [comment]
@JorjaComer is this truly invalid? I thought we refined this on Wednesday

**Comment by JorjaComer** [comment]
@davidkwartler Since we moved this out to PI 2, we don't need the issue. I would prefer to do the work as part of an actual stories when we decompose the feature for PI 2.
