### ISSUE TITLE
Implement filter/sort for Compliance (Emissions based) Data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#762]
Original Estimate: 40
PI 6 Estimate: 8

**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

- User research (not needed)
- Screen Mockups/UI Design (review for differences, re-use AH)
- Data conversion (needed)
- System requirements (in progress) 

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
1. Provide Compliance (Emissions based) data via API so the API returns all data needed for the EASEY Out Release

2. Validate Compliance (Emissions based) API parameters to ensure that the request is valid

3. Provide front-end user interface to access Compliance (Emissions based) data

## Context
[Refer to EASEY Out Production List ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28MVP.one%7C614ec76c-68a2-4733-aba0-fec44a85f292%2FEASEY%20Out%20Production%20List%7Cc8cb4d3b-e98e-4a0c-9425-69e90352227d%2F%29)

## Compliance (Emissions Based) System Requirements

**Assumptions:** 

1. Blank parameter values will return all records 
2. If multiple parameters are selected in a single query (TX,General Account), then only values that match all parameters will be returned (AND)
3. If multiple values are sent for a single parameter (e.g. TX, MD), then all data that matches the values is returned (OR).
4. API criteria inputs should not be case sensitive
5. API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 
6. Pagination should be optional for APIs
7. The API will not accept facility name as filter criteria. It will only accept Facility ID (ORIS code). 
8. Download limits for the UI will be implemented in future and are out of scope for initial development 
9. User must select data type and data subtype on the UI  before all fields are available
10. The site will be responsive to different desktop screen sizes (not mobile compatible) 

###  Public API Requirements

**API Parameters** 

- Year: Optional, multiple values allowed, Format: YYYY, Range: 1996 to current year, Allow indiv. Years, ranges, and comma sep. list 
- Facility ID (ORIS code): Optional, multiple values allowed
- Owner/Operator:  Optional, multiple values allowed, query will return all records that match owner OR operator specified
- State:  Optional, multiple values allowed, 2 letter postal abbreviation 

### UI Requirements

**UI Parameters**

Data Type
Required
Button/ Drop down 
Value: Emissions, Allowance, Compliance, default blank 
Single Select 

Sub-Type 
Required 
Drop down 
Single select 
Value:  Compliance (Allowance based), Compliance (Emissions Based), default blank  

Year
Text field. Allows ranges and individual years (YYYY-YYYY, YYYY, YYYY)
Format: YYYY 
Optional
Valid date range: 1996 to current year
Multi select (multiple 2019,2020, range 2017-2020, and indiv. Years 2015) 

**Facility** 

Facility ID
Dynamic search
Search is a contains search
Results populate in a list, parameters populates when a value is selected from the list 
Results are displayed in Facility Name (ORIS Code) format
If no results are found, the system will indicate so. “No facilities match your search.”

Facility Name
Dynamic search
Search is a contains search
Results are displayed in Facility Name (ORIS Code)
Results populate in a list, parameters populates when a value is selected from the list  	(results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No facilities match your search.”
Multi select 

**Owner/ Operator** 

Owner
Dynamic search
Search is a contains search on all unit owners/operators.
Results populate in a list, parameters populates when a value is selected from the list 	(results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select 

Operator
Dynamic search
Search is a contains search on all unit owners/operators.
Results populate in a list, parameters populates when a value is selected from the list 	(results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No accounts match your search.”
Multi select 

**State**
Dynamic search
Search is a “begins with” search
Results populate in a list, parameters populates when a value is selected from the list  	
Results display the full state name (Texas, not TX)
Multi Select

**Change Criteria**
The user will have the ability to clear one, many, or all filter criteria
If the user changes data type or sub data type, then:

The filter criteria displayed updates accordingly
No previously entered filter criteria is retained

If a user changes data type or sub data type, then filter criteria is cleared

If the user chooses to clear one or more filter criteria before preview is selected, then the system clears the criteria from the filter and updates any remaining dependent criteria accordingly.

If the user chooses to clear one or more filter criteria after preview is selected, then the system clears the criteria from the filter AND download is disabled until data is previewed.

**Data Preview**
Trigger: A user has entered, at a minimum, the required parameters, and selected the option to preview data.
For each record that matches the criteria, the system will display in a tabular format in the following order:

**Results (applicable to API and UI):** 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by  PRG_CODE > OP_YEAR > ORISPL_CODE > UNITID:

OP_YEAR
FACILITY_NAME
ORISPL_CODE
UNITID
OWN_DISPLAY
OPR_DISPLAY
STATE
COMP_PLAN_TYPE_CD
AVG_PLAN_ID
EMISS_LIMIT_DISPLAY
ACT_EMISS_RATE
AVG_PLAN_ACT_EMISS_RATE
IN_COMPLIANCE

Results will display record count
Results are limited to 100 records
Results in preview will have a scroll functionality to show all columns/rows
NOTE: NEED TO ID COLUMNS FOR HOVER TEXT AND DISPLAY TEXT
OUT OF SCOPE: Results may be sorted in alphabetical ascending and descending order
CAN THEY BE FILTERED? IF SO BY WHAT CRITERIA? - no additional filtering
OUT OF SCOPE: Results are paginated

**Data Labels-** 
Refer to the CAMPD_DataLables_Compliance_5_12_2021 file [here ](https://teams.microsoft.com/l/file/2BC5AF44-1343-4EEF-AE9C-FDEDEFBF4FB6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FCoding%20%26%20Error%20Standards%2FCAMPD_DataLables_Compliance_5_12_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

**File Selection**
Trigger: The user has at least one record that matches the search criteria, and has previewed the results
The user has the option to select the file output in JSON or CSV format.  CSV is the default file type 

**Download**
Trigger: The user has selected a file output type
When the user selects the option to download, the system creates a file in the format specified  containing all records that match the parameters and downloads the file 
After a user has chosen to download data, then the system will display the preview of the downloaded results.

**Validations:** 

**Year:** 

Validate that the date is in the format YYYY
Validate that all years are equal to or greater than 1995

Error Message 2: One or more < insert property > are not in the < insert format >. Ensure all are in the < insert format > FV-102
Error Message 3: Update one or more < insert property > to < insert valid range > FV-105

**Facility ID (ORIS code):**

Validate that the value is a number 
If the value is a number, validate that the format is correct
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**Owner/Operator:** 

No Validations 

**State:**

Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC

Error Message: One or more states are not valid. Use the two letter postal abbreviation (use TX, not Texas). FV-101

**Results (applicable to API and UI):** 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by  PRG_CODE > OP_YEAR > ORISPL_CODE > UNITID:

OP_YEAR
FACILITY_NAME
ORISPL_CODE
UNITID
OWN_DISPLAY
OPR_DISPLAY
STATE
COMP_PLAN_TYPE_CD
AVG_PLAN_ID
EMISS_LIMIT_DISPLAY
ACT_EMISS_RATE
AVG_PLAN_ACT_EMISS_RATE
IN_COMPLIANCE

New FC = 3 (0)
Existing FC = 1 (4)
Preview = 2
Filter Tags = 1
Download = 3
API = 13

**Comment by tlageman-epa** [comment]
@JanellC for owner/operator there should be no mention of buyer/seller accounts here as well. search is a contains search on all unit owners/operators. should be the same as what was done for emissions and also will be done for facility/unit attributes

**Comment by JanellC** [comment]
Completed core functionality. Compliance (emissions based) functions on the custom data download with end to end functionality. Removed tickets #1999 , #2110, and #2089 and from this epic. The removed issues remain on the PI 6 backlog

**Comment by JanellC** [comment]
Epic completed
