### ISSUE TITLE
Implement API gateway for Emissions API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#765]
- Standardize URL convention for services, both the internal service URL and the publicly exposed API gateway URL
- Implement policy so that users cant query the API directly without going through the API gateway
- Investigate if caching would be beneficial for our APIs

**Comment by jwhitehead77** [comment]
**Setup and configured**
https://api.epa.gov/DEV/testtm/emissions/apportioned/hourly?beginDate=2019-01-01&endDate=2019-03-31

- we need to have a discussion regarding the URL format and api prefixes
- probably need to request dev, test, stg prefixes specific to the EASEY systems
- also need to have version included in the url so something like /dev/emissions/v1/
