### ISSUE TITLE
Add QA Cert Events Data elements to Export Endpoint

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#771]
Add QA Cert Events Data elements to Export Endpoint (Both Official and workspace)

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-qa-certification-api/pull/360

**Comment by mosesdeeCVP** [comment]
Test Case: [TC1204](https://epacamd.testquality.com/project/11428/plan/28427/test/420816)

**Comment by mosesdeeCVP** [comment]
Cert Event Export Official
![Cert Event Export Official.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/44896e29-c32d-4875-b0c1-432a3117bc17)

**Comment by mosesdeeCVP** [comment]
Cert Event Export Workspace
![Cert Event Export Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d5304605-b73e-49b5-8273-6043aeb89363)

**Comment by mosesdeeCVP** [comment]
Test Passed
