### ISSUE TITLE
Global 'View' and Workspace 'Add': QA Test Extension Exemption Data

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#772]
As an ECMPS user, I want to view QA Test Extension Exemption Data in the Global-View and add new QA Test Extension Exemption Data in the Workspace so that I can look at real-time data or add test information as needed

**Acceptance Criteria: (Global-view)**
Given a user has selected QA Test Extension Exemption from the Test Data dropdown and a data record is available 
When the data is displayed 
Then the user can see data displayed as a separate table 

**Columns:**
Unit or Stack Pipe ID 
Year
Quarter
Monitoring System ID 
Component ID
Hours Used
Span Scale Code 
Fuel Code 
Extension or Exemption Code

Given a user is viewing QA Test Extension Exemption Data
When the data is displayed in a table
Then the default sort order is alphanumeric descending by the contents in the 1st column
And the user will have the option to sort the columns in ascending or descending alphanumeric order

- [x] The fields and their order specified

Pagination?

- [ ] Yes 
- [x] No

Filter by keyword?

- [ ] Yes 
- [x] No

Columns are sortable? 

- [x] Yes 
- [ ] No

Nested rows, expandable? 

- [ ] Yes 
- [x] No

**Acceptance Criteria: (Workspace - Add)**
Given the user has selected QA Test Extension Exemption from the Test Data dropdown
When the user clicks on 'Add' 
Then the system displays a modal
and the user can add new data for:

Unit or Stack Pipe ID (Dropdown)
Year (Dropdown)
Quarter (Dropdown)
Monitoring System ID (Dropdown)
Component ID (Dropdown)
Hours Used (Text)
Span Scale Code (Dropdown)
Fuel Code (Dropdown)
Extension or Exemption Code (Dropdown)

Given the user has added QA Test Extension Exemption Data
When the user chooses to save and close
Then the data is saved
And the modal closes
And the user is returned to the Landing screen 
And the QA Test Extension Exemption data record is reflected on the UI

Given the user has added a new QA Test Extension Exemption data
When the user chooses to Cancel
Then the user is returned to the Landing screen for QA Test Extension Exemption data
And no updates are saved

## Testing 
Test Case: [TC1200](https://epacamd.testquality.com/project/11428/plan/28527/test/419483)
Tester: @JanellC

**Comment by JanellC** [comment]
TC1200 Passed. Logged an enhacement to track the year range. See 4702 @vishnunavuluri 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/e622fe16-5b8a-4c3c-820f-1c0ea763a3bb)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/10e58e10-3db2-4a5f-a8bf-b1b3d26bb634)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/502fd2b8-1f73-463f-a3ce-5b9d98f731a7)
