### ISSUE TITLE
FEATURE: Implement API for Apportioned Daily Emissions Data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#773]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [x] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Has a clearly defined user
- [x] Has an estimate
- [x] Has acceptance criteria
- [x] Has sufficient context, such as

- User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)

- [x] Traceable to feature, epic or PI
- [x] Dependencies are identified
- [x] Component reusability assessed

## Feature Benefit

1. Provide Apportioned Daily Emissions data via API so the API returns all data needed for the EASEY Out Release

2. Validate Apportioned Daily Emissions API parameters to ensure that the request is valid

ASSUMPTIONS:
Parameters will not be validated against each other (e.g. the system will not validate that Account name is valid for the ORIS code). The system will just return data for the parameters specified. 
Blank parameter values will return all records
If multiple parameters are sent in a single query (TX, Coal), then only values that match all parameters will be returned (AND)
If multiple values are sent for a single parameter (e.g. TX, MD)  then all data that matches the values is returned (OR).
API criteria inputs should not be case sensitive
API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 
Pagination should be optional for APIs

Begin Date: Required, single value, ISO standard format, 1995-curent
End Date: Required, single value, ISO standard format, 1995-current
Facility: Optional, multiple values allowed, query will return all records that match Facility Name OR Facility Number (ORIS code) - OrIS only for API 
State: Optional, multiple values allowed, 2 letter postal abbreviation for the 50 states plus Puerto Rico.
Unit Type: Optional, multiple values allowed
Unit Fuel Type: Optional, multiple values allowed, query will filter on both primary and secondary fuel type 
Control technologies: Optional, multiple values allowed 
Program: Optional, multiple values allowed, excludes MATS

Validations

Begin Date: 
Validate that one, and only one, value exists for the parameter
Validate that the date is in the format YYYY-MM-DD
Validate that the date is valid (example: 2015-15-45) Error Message: Please enter the <insert property> in the YYYY-MM-DD format FV-5
End Date: 
Validate that one, and only one, value exists for the parameter
Validate that the date is in the format YYYY-MM-DD
Validate that the date is valid (example: 2015-15-45)
Error Message: Please enter the <insert property> in the YYYY-MM-DD format FV-5

Facility:
If the value is a text string, validate that the text matches a valid facility name
Error Message: "Facility name is not valid. Refer to the list of available facilities for valid values [placeholder for link to endpoint]" FV-15

If the value is a number, validate that the format is correct
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits
Error Message: ORIS code not valid. Refer to the list of available ORIS codes for valid values [placeholder for link to Facilities endpoint] FV-8 
State: 
Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC
Error Messages: The state is not valid. Please enter a valid state using the two letter postal abbreviation (use TX, not Texas). FV-4

Unit Type:
1. Validate that the value matches a valid unit type 

Error Message: One or more unit types are not valid. Refer to the list of available unit types for valid values [placeholder for link to endpoint] fv-1

Unit Fuel Type: 
1. Validate that the value matches a valid fuel type 

Error Message: "One or more unit fuel types are not valid. Refer to the list of available unit fuel types for valid values [placeholder for link to endpoint] FV-2

Control Technologies: 
1. Validate that the value matches a valid control technology 

Error Message: One or more control technologies are not valid. Refer to the list of available control technologies for valid values [placeholder for link to endpoint]"Fv-3

Program: 
1. Validate that the value matches a valid program code

Error Message: "One or more programs is not valid. Refer to the list of available programs for valid values [placeholder for link to endpoint] FV-12  This error message may need to be tweaked to be more specific since the parameter only accepts the program code and not the full program name. 

Results: 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Date > Hour (same as hourly)
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

Task: Refactor hourly emissions API, regression test- Junie, 3

1. set up daily emissions - Junie, 2
- update controller
-update service
- update routes.ts
- return DTO
- param DTO

Can send multiple criteria/parameters and get hello world, no data, no validation 

2. Repo - Junie, 5
- day-unit entity
- update unit-fact entity
- day-unit repo
- day-unit map
- update service

Can send multiple parameters and get data, valid parameters only. 

3. Validation- Junie, 5 

Can send parameters, parameters are validated, data returned or error messages

**Comment by JorjaComer** [comment]
Split feature. See #1010. Removed API from PI 4

**Comment by JorjaComer** [comment]
Per the 3.4 sprint demo, the feature is complete.
