### ISSUE TITLE
FEATURE:  API for Apportioned Monthly Emissions Data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#775]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [x] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Has a clearly defined user
- [x] Has an estimate
- [x] Has acceptance criteria
- [x] Has sufficient context, such as

- User journeys
- Screen Mockups/UI Design
- Architectural drawings (where applicable)
- Business Rules (where applicable)
- Data object(or resource) identification

- [x] Traceable to feature, epic or PI
- [x] Dependencies are identified
- [x] Component reusability assessed

## Feature Benefit
1. Provide Apportioned Monthly Emissions via API so the API returns all data needed for the EASEY Out Release

2. Validate Apportioned Monthly Emissions API parameters to ensure that the request is valid
Public API Requirements

Parameters

Question: 
How will the Time period parameter function? Will this be similar to the vintage year parameter in the allowance holdings API? (ex. a single field)   - user can pick one or multiple years, and one or multiple months within the years. If not all months are selected, then the selected months apply to all years in the query (e.g. Jan-Apr for 2020 and 2015) 
Assumptions: 
Parameters will not be validated against each other (e.g. the system will not validate that Account name is valid for the ORIS code). The system will just return data for the parameters specified. 
Blank parameter values will return all records
If multiple parameters are sent in a single query (TX, Coal), then only values that match all parameters will be returned (AND)
If multiple values are sent for a single parameter (e.g. TX, MD)  then all data that matches the values is returned (OR).
API criteria inputs should not be case sensitive
API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 
Pagination should be optional for APIs
The API will not accept facility name as filter criteria. It will only accept Facility ID (ORIS code).

Year: Required multiple values allowed, Format: YYYY,1995-current quarter 
Month: Required multiple values allowed, Format: month number, 01-12 (2 or 1 digit)
Facility ID (ORIS Code): Optional, multiple values allowed
State: Optional, multiple values allowed, 2 letter postal abbreviation for the 50 states plus Puerto Rico.
Unit Type: Optional, multiple values allowed
Unit Fuel Type: Optional, multiple values allowed, query will filter on both primary and secondary fuel type 
Control Technologies: Optional, multiple values allowed 
Program: Optional, multiple values allowed, excludes MATS

Validations

Time Period: Review if not required, or string 
Year:
Validate that at least one, value exists for the parameter
Validate that the date is in the format YYYY
Validate that the year is greater than ot equal to 1995 
Month:
Validate that at least one, value exists for the parameter
Validate that the date is in the format MM (1or 2 digit month code) 
**Validate that the month is between 1 and 12, error message TBD**

Facility ID (ORIS Code): 
Validate that the format is correct
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message: ORIS code not valid. Refer to the list of available ORIS codes for valid values [placeholder for link to Facilities endpoint] FV-8 

State: 
Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC
Error Messages: The state is not valid. Please enter a valid state using the two letter postal abbreviation (use TX, not Texas). FV-4

Unit Type: 
1. Validate that the value matches a valid unit type 

Error Message: One or more unit types are not valid. Refer to the list of available unit types for valid values [placeholder for link to endpoint] fv-1

Unit Fuel Type: 

1. Validate that the value matches a valid fuel type 

Error Message: "One or more unit fuel types are not valid. Refer to the list of available unit fuel types for valid values [placeholder for link to endpoint] FV-2

Control Technologies: 

1. Validate that the value matches a valid control technology 

Error Message: One or more control technologies are not valid. Refer to the list of available control technologies for valid values [placeholder for link to endpoint]"Fv-3

Program: 

1. Validate that the value matches a valid program code

Error Message: "One or more programs is not valid. Refer to the list of available programs for valid values [placeholder for link to endpoint] FV-12 

Results: 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year > Month 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
YEAR
MONTH
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

## Context
[Refer to EASEY Out Production List ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28MVP.one%7C614ec76c-68a2-4733-aba0-fec44a85f292%2FEASEY%20Out%20Production%20List%7Cc8cb4d3b-e98e-4a0c-9425-69e90352227d%2F%29)

**Comment by JorjaComer** [comment]
All issues complete
