### ISSUE TITLE
Allow White Space(s) Before or After the Delimiter When Entering Multiple Parameters for State

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#789]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to enter filter criteria for multiple states so that I can see results for multiple states in one query
NO validation

## Acceptance Criteria
Given that a user has entered multiple states without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple states 

Given that a user has entered multiple states with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple states 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC83](https://cvpcorp.testquality.com/project/11428/plan/19811/test/273591)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by sdhawan16** [comment]
Created PR: Altered API to allow whitespaces before or after the delimiter when entering multiple state values

**Comment by david-cvp** [comment]
TC83 passed again

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&beginDate=2009-01-01&endDate=2021-01-31&state=ca%20%20,%20%20ne

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/b920f23d-8476-4647-b611-0d4c64e6e00f)

@tlageman-epa
