### ISSUE TITLE
Identify required FACT API endpoints for Facilities 

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#79]
- [x] Meet with @faqir-cvp to determine document template
- [x] Identify endpoints in FACT API that are required to display Facilities data in Monitoring Plan Viewer

A/C:
Single document of all identified endpoints uploaded to EPA Sharepoint

**Comment by junie-stigdon** [comment]
Met with Faqir and Jason to discuss how we want to format endpoints. Started on the documentation.

Simera to work on monitoring plan tab, and Sejal and Junie to work on locations, contacts, and units.

**Comment by junie-stigdon** [comment]
Identified endpoints needed for facilities data. Will meet internally to review before closing out this ticket. 


While working on #79 we realized that #194 endpoints might be part of the facilities end points.

**Comment by junie-stigdon** [comment]
Changed story point value from 3 to 5 because we included the work from #194 .

**Comment by junie-stigdon** [comment]
Identified Endpoints: https://usepa.sharepoint.com/:b:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/EASEY-OUT/API%20Endpoints/Identified%20API%20Endpoints%20-%20Facilities%20-%20EPA%20CAMD%20-%20v1.1.pdf?csf=1&web=1&e=ZZIfOu

**Comment by david-cvp** [comment]
Next steps #226
