### ISSUE TITLE
Support DNS configuration

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#791]
- [ ] Support EPA with any necessary tasks for new subdomains (such as campd.epa.gov)
- [ ] Ensure their subdomain format will work with our development approach

https://cloud.gov/docs/management/custom-domains/

Dependencies: Need to work with EPA, Datateers, Cloud.gov, ADC

Outcomes: Will result in additional tickets to actually configure the subdomains

**Comment by MaeganWood64** [comment]
Ticket no longer needed, will add additional DNS tickets as necessary
