### ISSUE TITLE
Enhance search on unit characteristics(search by group)  

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#795]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want get results for all unit characteristics groups (unit, fuel, control tech)
So that I can get results for all data that matches a given group of parameters

Need to update unit char. search to be a contains search see below for examples 
Examples ... 

Sending "gas" as a parameter will return: 
Natural gas 
Other gas 
Pipeline gas 
Process gas 

Sending "turbine" as a parameter will return: 
Combined cycle 
Combustion cycle 
Integrated gasification combined cycle 
Other turbine 

## Acceptance Criteria
Given that a user has entered partial filter criteria for multiple unit types 
When the API endpoint is executed it conducts a contained search
Then the system displays the results for multiple unit types captured in the contained search 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the staging/integration environment?

**Comment by JorjaComer** [comment]
Per 3.3 planning: Not needed for public API. Revisit if needed when UI design is confirmed.

**Comment by JorjaComer** [comment]
Moved to Phase 2 Enhancements feature
