### ISSUE TITLE
Identify group two tables and convert schemas for data migration

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#797]
- Identify allowance and compliance group two tables necessary for Datateers & Emissioners development and prepare for data migration by preparing the staging environment Postgres DB

Datateers:
Further emissions data
Allowance holdings and transactions

Emissioners: 
Remaining monitoring plan sections (including fuel flows)

**Comment by jwhitehead77** [comment]
CAMDDMW tables needed to support the rest of PI-3 and PI-4 development. See ticket #673 for Informatica data migration
1-ACCOUNT_FACT
1-TRANSACTION_FACT
2-ACCOUNT_COMPLIANCE_DIM
2-ALLOWANCE_HOLDING_DIM
2-TRANSACTION_BLOCK_DIM
2-ANNUAL_UNIT_DATA
2-DAY_UNIT_DATA
2-MONTH_UNIT_DATA
2-OZONE_UNIT_DATA
2-QUARTER_UNIT_DATA
