### ISSUE TITLE
Replace HTML breaks with a comma delimiter in camddmw.unit_fact

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#798]
We have discovered a data transform that we need done. The following fields in the table below contain html `<br>` due to the way that data is being used on the current AMPD website. However, the new system does not need that so can you please replace the `<br>` with a comma to create a comma separated list of values in those fields.

**camddmw.unit_fact**
- so2_control_info
- nox_control_info
- part_control_info
- hg_control_info

Example:
Current value: "Additives to Enhance PAC and Existing Equipment Performance`<br>`Untreated PAC Sorbent Injection"
New value: "Additives to Enhance PAC and Existing Equipment Performance`,`Untreated PAC Sorbent Injection"

**Comment by david-cvp** [comment]
@vkdontula Hello, this task is ready for development

**Comment by jwhitehead77** [comment]
this has been completed in staging and we will be running the Informatica process in dev over the weekend or performing a backup restore from staging to dev
