### ISSUE TITLE
Informatica data migration of additional group one tables

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#799]
## Four tables
- [ ] camd.unit_op_status
- [ ] camdmd.operating_status_code
- [ ] camdecmps.analyzer_range
- [ ] camdecmpsmd.analyzer_range_code

**Comment by david-cvp** [comment]
@vkdontula Hello, this task is ready for development

**Comment by vkdontula** [comment]
Working on both.  I will update you when ready.

**Comment by jwhitehead77** [comment]
this has been completed in staging and we will be running the Informatica process in dev over the weekend or performing a backup restore from staging to dev
