### ISSUE TITLE
Implement filter/sort for Facility/ Unit Attributes

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#800]
Original estimate: 40
PI 6 Estimate: 13

**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

- User research 
- Screen Mockups/UI Design 
- Data conversion 
- System requirements 

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
1.Provide facility data via API so the API returns all data needed for the CAMPD Release

2.Validate facility API parameters to ensure that the request is valid

3.Provide front-end user interface to access facility data

## Context

[Refer to EASEY Out Production List ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28MVP.one%7C614ec76c-68a2-4733-aba0-fec44a85f292%2FEASEY%20Out%20Production%20List%7Cc8cb4d3b-e98e-4a0c-9425-69e90352227d%2F%29)

#### **Questions:**

1.  What is the order by for for facility/ unit attributes data elements? Will it be ordered by Facility > Unit > Year like Annual Emissions ?

2. What are the values for Source Category ?

 

#### **Assumptions:** 

1. Blank parameter values will return all records 
2. If multiple parameters are selected in a single query (TX,General Account), then only values that match all parameters will be returned (AND)
3. If multiple values are sent for a single parameter (e.g. TX, MD), then all data that matches the values is returned (OR).
4. API criteria inputs should not be case sensitive
5. API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 
6. Pagination should be optional for APIs
7. The API will not accept facility name as filter criteria. It will only accept Facility ID (ORIS code). 
8. Download limits for the UI will be implemented in future and are out of scope for initial development 
9. User must select data type and data subtype on the UI  before all fields are available
10. The site will be responsive 

#### **API Parameters** 

- Year: Required, multiple values allowed, Format: YYYY, Range:  1995- latest reporting quarter, Allow indiv. Years, ranges, and comma sep. list

- Facility ID (ORIS code):  Optional,  multiple values allowed 

- State : Optional, multiple values allowed, 2 letter postal abbreviation for the 50 states plus Puerto Rico.

- Unit Type : Optional, multiple values allowed 

- Unit Fuel Type: Optional, multiple values allowed,  query will filter on both primary and secondary fuel type

- Control Technology: Optional, multiple values allowed 

- Source Category: Optional, multiple values allowed 

- Program : Optional, multiple values allowed 

#### **UI Parameters** 

**Data Type** 
Button/drop down
Value: Emissions, Allowance, Compliance, default blank,
Required
Single select

**Data Sub Type** 
Drop down
Value: Hourly Emissions, Daily Emissions, Monthly Emissions, Quarterly Emissions, Ozone Season Emissions, Annual Emissions, Facility/Unit Attributes, default blank
Required
Single select

**Time Period** 
Year
Required
Range: 1995- latest reporting quarter,
Text field. Allows ranges, individual years, and multiple years (YYYY-YYYY, YYYY, YYYY)
multiple values allowed,
Format: YYYY

 
**Facility** 

Facility Name
Dynamic search
Search is a contains search
Results are displayed in Facility Name (ORIS Code) format
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
If no results are found, the system will indicate so. “No facilities match your search.”
Multi select

ORIS Code
Dynamic search
Search is a contains search
Results populate in a list, parameters populates when a value is selected from the list
Results are displayed in Facility Name (ORIS Code) format
If no results are found, the system will indicate so. “No facilities match your search.”
Multi Select

**State**
Dynamic search
Search is a “begins with” search
Results populate in a list, parameters populates when a value is selected from the list
Results display the full state name (Texas, not TX)
Multi Select

**Unit Characteristics** 

Unit Type 
Drop down  default blank 
Values: Boiler, Turbine, Furnaces, default blank
Optional
Multi select
Unit types will be listed in the unit type (unit type code) format 

Unit Fuel Type 
Drop down, default blank 
Values: Coal, Gas, Oil, Other, default blank
Optional
Multi select
Fuel types will be listed in fuel type (fuel type code) format 
Search is performed on Primary and Secondary fuel types NOTE: Add "?" text to inform user this is how search works

Control Technology 
Drop down, default blank 
Values: SO2 Controls, Hg Controls, NOx Controls, PM Controls, default blank
Optional
Multi Select
Control technologies will be listed in control technology (control tech code) format

**Unit Classification**
Source Category 
Optional , default blank 
dynamic search 
combo box
contains search
Values: values are located in CAMDBSP SOURCE_CATEGORY_CODE under the owner CAMDMD
Multi Select 

**Program** 
Drop down, default blank 
Optional  
Values: All active and inactive programs (MATS is excluded) 
Multi select 
Programs will be listed in program (program code) format 

**_Change Criteria_**
The user will have the ability to clear one, many, or all filter criteria
If the user changes data type or sub data type, then:

- The filter criteria displayed updates accordingly 
- No previously entered filter criteria is retained 

If a user changes data type or sub data type, then filter criteria is cleared 
If the user chooses to clear one or more filter criteria before preview is selected, then the system clears the criteria from the filter and updates any remaining dependent criteria accordingly.
If the user chooses to clear one or more filter criteria after preview is selected, then the system clears the criteria from the filter AND download is disabled until data is previewed. 

### **Validations** 

**Year:** 

Validate that at least one value exists for the parameter
Validate that the year is in the YYYY format
Validate that the year is greater than or equal to 1995  (Range:  1995- latest reporting quarter)

Error Message 1: <   insert property    > should not be null or undefined FV-106

Error Message 2: One or more < insert property > are not in the < insert format >. Ensure all are in the < insert format > FV-102

Error Message 3: Update one or more < insert property > to < insert valid range > FV-105

**Facility ID (ORIS code):** 

Validate that the value is a number
If the value is a number, validate that the format is correct
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**State :** 

Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC

Error Message: One or more states are not valid. Use the two letter postal abbreviation (use TX, not Texas). FV-101

**Unit Type :**

1. Validate that the value matches a valid unit type

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**Unit Fuel Type:** 
1. Validate that the value matches a valid fuel type

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**Control Technology:** 

1. Validate that the value matches a valid control technology

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**Source Category:** Dependency: will need source category endpoint 

1. Validate that the value matches a valid source category 

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

**Program** : 

1. Validate that the value matches a valid program code

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100

### ** Data Preview/ Results** 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility ID> Unit ID > Year

STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_YEAR
PRG_CODE_INFO
EPA_REGION
NERC_REGION
COUNTY
COUNTY_CODE
FIPS_CODE
SOURCE_CAT
LATITUDE
LONGITUDE
OWN_DISPLAY
OPR_DISPLAY
SO2_PHASE
NOX_PHASE
UNIT_TYPE_INFO
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
SO2_CONTROL_INFO
NOX_CONTROL_INFO
PART_CONTROL_INFO
HG_CONTROL_INFO
COMR_OP_DATE
OP_STATUS_INFO
CAPACITY_INPUT (mmBtu/hr)
NAMEPLATE_CAPACITY
GENID (Generator ID)
REPORT_FREQ*

*REPORT_FREQ in PROGRAM_YEAR_DIM

**Data Labels-** 
Refer to the CAMPD_DataLabels_FacilityAttributes_4_2_2021 file[ here ](https://teams.microsoft.com/l/file/AA12A78C-B7BA-4E76-B694-71985AAE42A6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FCoding%20%26%20Error%20Standards%2FCAMPD_DataLabels_FacilityAttributes_4_2_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Results will display total record count (Viewing the first 100 of X records)
Results in preview are limited to the first 100 records
Results in preview will have a scroll functionality to show all columns/rows
Results columns are are sortable in ascending and descending order (alphanumeric order) . Sort is limited to the original 100 results

**File Selection**
Trigger: The user has at least one record that matches the search criteria, and has previewed the results
The user has the option to select the file output in JSON or CSV format. CSV is the default file type 
API will provide the data in the requested format based on user selection in UI

**Download**
Trigger: The user has selected a file output type
When the user selects the option to download, the system creates a file in the format specified  containing all records that match the parameters and downloads the file 
After a user has chosen to download data, then the system will display the preview of the downloaded results.

**Comment by tlageman-epa** [comment]
@JanellC 

1. Yes, that order is fine. but want to clarify that it is facility ID, Unit ID, then Year
2. Those values are located in CAMDBSP SOURCE_CATEGORY_CODE under the owner CAMDMD

**Comment by JanellC** [comment]
epic complete
