### ISSUE TITLE
 Add build version number and date to Emissions API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#802]
Add build version number and date to the API web page footer

![last-updated.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/e2494cf5-d13a-47e8-bdae-f0b7647f4c5f)

Tech Team #634 will provide the environment variable

**Comment by JorjaComer** [comment]
Discussed during 3.2 planning. This work has tech team dependencies before this work can be done for the APIs. Not ready to be worked, yet.
