### ISSUE TITLE
System/Components Wireframe Updates

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#806]
### 💼 Assets
- [Wireframes (latest from Allison)](https://xd.adobe.com/view/9a4c5deb-be48-44f8-89df-8ff70ad1c39d-cf1f/)
- [Wireframes](https://xd.adobe.com/view/ccf2dda8-0f33-4df9-a581-6556fbdedeb9-99a1/screen/277d73d0-2982-4c78-a3d3-17d41d6c8454?fullscreen)

### 🧑‍💼 Stakeholders
@MoAdeyoju @JorjaComer @karenhwwoo @jwhitehead77 @chrisgitsit @staceyrenner

**Comment by karenhwwoo** [comment]
To be discussed on 3/1.

**Comment by AllisonFrancis** [comment]
Updated Wireframes to include add component and create component screens and changes.

https://xd.adobe.com/view/9a4c5deb-be48-44f8-89df-8ff70ad1c39d-cf1f/
