### ISSUE TITLE
SPIKE: Design Monitoring Plan tab overflow navigation

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#810]
Per video in #534, approach will mimic Adobe Photoshop behavior.

1. A drop-down menu becomes available for capturing all open tabs.
2. When the user selects from open tabs menu, the appropriate tab receives focus.
3. The range of visible open tabs is driven by:
   -- The first tab matches the most recent selection from the drop-down menu, representing the beginning of the range
   -- The last tab matches the most recent selection from the drop-down menu, representing the end of the range

## Acceptance Criteria
Questions to answer:

Is there an indicator for the newly opened tab (animation, color change, etc.) 
What happens when tab is opened? Go to tab or open in line and stay on current? 
How does tab navigation look? How does it behave when tabs fit? How does it behave when tab don't fit? When is overflow navigation active/inactive? 
How will this functionality be impacted when editing is available? 

Jason W, Addis, Quang, Alex, Chris, Anthony, Moses, Karen, Nada, Stacey 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by karenhwwoo** [comment]
Close per reqts elicitation discussion on 3/2/21.
