### ISSUE TITLE
STORY: EPA Menu in Header 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#811]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want view the EPA menu 
So that I can access EPA resources for the system 

## Acceptance Criteria
Given a user has accessed the EPA menu
When the menu is displayed
Then the following links are displayed(includes sub topic):

- Environmental Topics
- Laws & Regulations
- About EPA

Given a user has selected a link from the menu
When a link is selected
Then the system opens the link on the EPA website in a new tab

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC91](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274710)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test Case: [TC91](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274710) - Passed

**Comment by mosesdeeCVP** [comment]
Product Owner has accepted the ticket. - Closed
