### ISSUE TITLE
STORY: EPA Search in Header 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#812]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want search the EPA website
So that access EPA resources form the system 

## Acceptance Criteria
Given a user has chosen to search the EPA website
When the search is executed
Then the system opens the link on the EPA website in a new tab to view the results

Assumption: Search results are controlled by the EPA website and search service and are out of scope for this story 

From MI, EPA search link is one line 48: https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/master/index.html

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC92](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274711)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test case [TC92](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274711) - Passed

**Comment by mosesdeeCVP** [comment]
Product Owner has accepted the ticket - Closed
