### ISSUE TITLE
STORY: Footer Menu 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#813]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to view the EPA footer menu 
So that I can access EPA resources from the system 

## Acceptance Criteria
Given the updated footer is implemented
When the footer is displayed
Then it contains the EPA standard menu 
And provides the ability to close the menu 

Given a user has accessed the EPA menu
When the menu is displayed
Then the system displays the following links:

- Accessibility
- Privacy
- Privacy and Security Notice

Given the menu is displayed
When a link is selected
Then the system opens the link on the EPA website in a new tab (see [EPA.gov](https://www.epa.gov/) for links) 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [813](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274714)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
Test case #[813](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/274714) - Passed

**Comment by mosesdeeCVP** [comment]
Product Owner has approved the story – Ticket closed.
