### ISSUE TITLE
Monitoring Plan API updates

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#815]
Simera to refactor some code for the Monitoring Plan API

@mosesdeeCVP to perform a regression test

**Comment by mosesdeeCVP** [comment]
This ticket was regression tested and all test cases passes. The following test cases were run:

[TC55](https://cvpcorp.testquality.com/project/11428/plan/19352/test/fullscreen/267704)
[TC56](https://cvpcorp.testquality.com/project/11428/plan/19352/test/fullscreen/267705)
[TC57](https://cvpcorp.testquality.com/project/11428/plan/19352/test/fullscreen/267706)
[TC81](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/273498)

**Comment by mosesdeeCVP** [comment]
![815 Reg Test 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/9ef2f394-eb55-49d5-be20-5d4ffbc04eda)

**Comment by mosesdeeCVP** [comment]
![815 Reg Test 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/b99c2688-bf70-427d-85d4-82452da2db7a)

**Comment by mosesdeeCVP** [comment]
Testing completed and passed - Ticket Closed
