### ISSUE TITLE
CAMPD Initial Wireframes 508 Review

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#821]
🤹 Tasks
- [x] Walkthrough current filter/sort CAMPD wireframes with @aprematta (scheduled for 2/22/21, 1:30 PM-2:00 PM)
- [x] @aprematta will provide any 508 recommendations for design (with the caveat that these are wireframes), functionality (with the caveat that this is just an XD prototype), and development as a Word document within the [Datateers\508 and Accessibility Teams folder](https://teams.microsoft.com/_#/files/Datateers?threadId=19%3Af4349e2ba95e43f3b29e8208bc8f5d5f%40thread.skype&ctx=channel&context=508%2520and%2520Accessibility&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FDatateers%252FUI%2520Design%252F508%2520and%2520Accessibility)

🥅 Goals
- Nip any 508 issues in the bud early

📇 Stakeholders
@MoAdeyoju @JorjaComer @karenhwwoo @kstetsyuk @tlageman-epa @aprematta

**Comment by cvp-alexrobinson** [comment]
@aprematta — For what it's worth, posting my notes from our 508 call...

**Fields**
- Make sure "clear/X" buttons are descriptive of the individual fields they're actually clearing.

**Dropdowns**
- User a modal pattern instead of dropdowns. This will open up more real estate inside of each filter field while being much easier to develop in a 508 compliant way. 
- Include an "apply filter" button within each dropdown/modal for a more accessible and actionable experience.

**Time Period** 
- Use the [USWDS date picker](https://designsystem.digital.gov/form-controls/05-date-picker/) pattern.
- Include labels above each date picker field.

**State/Territory and Facility**
- Separate search field from results.
- Include text indicating the state or facility results are filtered and why. E.g. "Showing only facilities in North Dakota."

**Unit Characteristics**
- Include labels above each dropdown

**Preview**
- Include text that clearly communicates that the results will appear below after clicking the "preview/update data" button. It's bad practice to have a page change unexpectedly.

**Comment by kstetsyuk** [comment]
Thanks for these. In addition to the updates in #550, please make necessary changes for 508 compliance. 

One question I do have is for the indicating text in the State/Territory and Facility fields. Would our update in #550 (having the number of facilities and states selected appear in the field, e.g. "(4) facilities selected") solve this issue?

@cvp-alexrobinson @tlageman-epa @areighar

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — I believe so! Anthony will followup with a more thorough report but I just wanted to get my notes down before I lost them.

**Comment by aprematta** [comment]
I added a report in my original ticket https://github.com/US-EPA-CAMD/easey-ui/issues/649 and here
[EPA CAMPD Wireframe Review.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6031033/EPA.CAMPD.Wireframe.Review.docx)
