### ISSUE TITLE
STORY: Update Unit Type, State, and ORIS Code to Require a Pipe Delimiter 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#831]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to enter filter criteria for multiple unit types, states, and ORIS codes so that I can see results in one query

## Acceptance Criteria
Given that a user has entered multiple unit types without white space(s) before or after the pipe delimiter
When the API endpoint is executed
Then the system displays the results for multiple unit types 

Given that a user has entered multiple unit types with white space(s) before or after the pipe delimiter
When the API endpoint is executed
Then the system displays the results for multiple unit types 

Given that a user has entered multiple states without white space(s) before or after the pipe delimiter
When the API endpoint is executed
Then the system displays the results for multiple states

Given that a user has entered multiple states with white space(s) before or after the pipe delimiter
When the API endpoint is executed
Then the system displays the results for multiple states 

Given that a user has entered multiple ORIS codes separated by a pipe delimiter 
When the API endpoint is executed
Then the system displays the results for multiple ORIS codes (containing data elements below)

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Cases: [TC82, TC83, TC84](https://cvpcorp.testquality.com/project/11428/plan/19811/test/273590)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by sdhawan16** [comment]
Created PR

Updated unitType, State, and orisCode to use a pipe delimiter

- Added "style: 'pipeDelimited'" to the ApiQuery in the controller
- Split list by '|'

**Comment by david-cvp** [comment]
TC82, TC83, TC84 passed @tlageman-epa 

API using pipe delimiter:
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/8a8a9a61-53c2-4303-802b-b16c8ec0670b)
