### ISSUE TITLE
Update MP UI Labels

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#835]
Implement labeling updates:
1. Relabel Import MP button
2. Add Select Facilities section label

[Updated wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/)

**Comment by mosesdeeCVP** [comment]
Test case created [TC109](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/275971)

**Comment by mosesdeeCVP** [comment]
![835 Update MP UI Labels.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c9e2bf41-2aa2-4cd8-9f37-77d5c6dd4eec)

**Comment by mosesdeeCVP** [comment]
Test Case Passed
