### ISSUE TITLE
Create Monitor Plan API endpoint for Location Components

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#855]
endpoint that will accept a locId and return all components for the specified location

endpoint uri
/api/monitor-plan-mgmt/locations/{loc-id}/components

**Comment by mosesdeeCVP** [comment]
Test Case [TC113](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276285) - Passed

**Comment by mosesdeeCVP** [comment]
[Uploading... 855 Create Monitor Plan API endpoint for Location Components.png]

**Comment by mosesdeeCVP** [comment]
![855 Create Monitor Plan API endpoint for Location Components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/281728d1-1f18-44e5-a416-89ac17350642)
