### ISSUE TITLE
508 accessibility review of header and footer

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#856]
@aprematta to perform 508 compliance review for the header and footer of the new go-wide template

**Comment by aprematta** [comment]
[EPA Header and Footer Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/6086657/EPA.Header.and.Footer.Accessibility.Report.docx)

**Comment by aprematta** [comment]
Adding accessibility report. Let me know if you need a meeting to discuss the issues, specifically with the Menu buttons in the header and footer.
