### ISSUE TITLE
Add Program to Hourly Emissions Public API Filter Criteria 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#858]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user 
I want retrieve program data
So that I can analyze it 

## Acceptance Criteria
Given that a user has entered one or more program codes in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more program codes without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more program codes with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more invalid programs
When the API endpoint is executed
Then the returns the message FV-12
"One or more programs is not valid. Refer to the list of available programs for valid values [placeholder for link to endpoint]

--

## Dev Tasks

- [x] Create entity
- [x] Create program enum
- [x] Add program to params DTO
- [x] Update controller to use pipe delimiter for program multiselect
- [x] Update repo 
- [x] Validate program parameter
- [x] Unit tests

## Context
will use program codes, excludes MATS
Send multiple control tech
Will make case insensitive
Return data for multiple values
When entering multiple values the API will allow pipe separated list of values including one or more whitespace(s) before and after the delimiter but will not require whitespace
Contains search
MATS data is excluded from results 
Out of scope: adding program results returned 

Data Elements
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO| PRG_CODE_INFO| ASSOC_STACKS 

## Testing
Test Case: [TC100](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275765)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- Created ProgramCode entity
- Created Program enum 
- Updated paramsDTO to include multiselect for program
- Updated repo to check for program filter criteria
- Created Regex class in order to remove repeated code, cleaning up the repo
- Created IsProgram validator
  - Includes a constraint parameter _property_: a string array that specifies programs to exclude from validation (in this case MATS)
- Created ApiConfigService:
  - Get HOST environment variable 
  - Get MDM base uri
- Updated formatting in controller
- Unit tests

**Comment by david-cvp** [comment]
TC100 passed @tlageman-epa

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/0f3fb195-f7e5-4330-b1e9-ab24910da54a)

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?beginDate=2019-01-01&endDate=2019-01-31&program=txso2%20|%20CSOSG2
https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?beginDate=2019-01-01&endDate=2019-01-31&program=ARP|Invalid

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/cec77a90-df09-4a3f-b731-f66d215e0144)
