### ISSUE TITLE
Add Additional Elements to Hourly Emissions API Query Results  

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#860]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want retrieve associated stack and program data in my query 
So that I can analyze it 

## Acceptance Criteria
Given a user queries the hourly emissions public API
When records match the criteria
Then the results include PRG_CODE_INFO and ASSOC_STACKS data elements

## Context
Additional Fields to return in the result outputs:  PRG_CODE_INFO, ASSOC_STACKS

## Testing
Test Case: [TC101](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275766)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
Just clarifying the A/C:

Given a user queries the hourly emissions public API
When records match the criteria
Then the results include PRG_CODE_INFO and ASSOC_STACKS data elements **in addition to the already returned data elements**

**Comment by david-cvp** [comment]
TC101 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/8da08701-c710-4cba-8e40-e9aca9ba6d47)
