### ISSUE TITLE
TASK: Hourly Emissions Data Limit Testing  

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#861]
Goal: 
Need to know the maximum amount of data that can be downloaded from the UI,
SO that we can restrict a user's ability to select too much data

Context:
First release of CAMPD UI will not limit data. The user may select too much data and experience a connection timeout.

Questions:
- How much data in terms of time period can we retrieve for all facilities?

- How much data in terms of time period can we retrieve for just the state of Texas?
Note: Texas has many facilities, the average state has about 78 units. Look into testing other states as well.
Rough average of 3 units per facilities = 25 facilities per state.

- How much data in terms of time period can we retrieve for a single facility? (Barry)

- How does different internet speeds affect download time and limits?
Note: BrowserStack offers testing of different connection speeds

- How much data is a certain number of records (for op hours vs rows with nulls)

Possibly incorporate this limit testing into our performance / load testing for release readiness

**Comment by david-cvp** [comment]
Action items
1. Mike to ask Informatica to run scripts to pull data from production DB
2. Informatica to load data into our EASEY Staging database
3. Jason eventually move data from Staging to Dev-Int (or Informatica run again to load data to EASEY Dev-Int DB)

**Comment by MaeganWood64** [comment]
- Not Needed
