### ISSUE TITLE
STORY: Create Endpoint for Program

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#862]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to see a list of valid programs so that I can include the correct data for my query

## Acceptance Criteria
Given a user has selected the url
When the url is executed
Then the system will return all the program records in JSON format
And for each record will display:
- Program Code
- Program Description
- Comp Parameter Code 
- Program Group Code

Given the request contains exclusion parameters
When the request is executed
Then the system will exclude any values in the exclusion parameter from the results  

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Dev Tasks
- [x] Create Program entity
- [x] Create Program DTO
- [x] Create ProgramMap
- [x] Create Module
- [x] Create Repository
- [x] Create Controller and add endpoint
- [x] Create Service to return program data to the Controller
- [x] Update routes.ts and app.module.ts files
- [x] Exclude MATS
- [x]  Unit tests

## Testing
Test Case: [TC102](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275767)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
Not sure why the user story has unit type in it? IS this just a copy paste error? @JorjaComer

**Comment by sdhawan16** [comment]
Created endpoint that returns program data, will work on unit tests on Monday
Need to confirm MATS should not be included in results and if so remove it

**Comment by sdhawan16** [comment]
Discussed with Jason that we want to add an 'exclude' parameter which can take in any program code. This will allow all programs to be returned if it's needed on the EASEY-IN side and will allow the capability to filter out certain program codes elsewhere. For instance, we would include 'programs?exclude=MATS' in the error message URL so that it links out to all programs except MATS. This approach allows the endpoint to be more robust.  Need to confirm in DSU if changing the AC to reflect this is Ok.

**Comment by sdhawan16** [comment]
Created PR: 

Created programs endpoint that returns data from the program_code table
-  Created Program code entity, ProgramDTO, ProgramMap, ProgramsRepository, and ProgramsModule
-  Created ProgramsController and added GET endpoint (/programs)
-  Updated routes.ts and app.module to account for programs
-  Updated main.ts to use global validation pipe
-  Created ProgramsService to return programs to the controller
-  Implemented multi select parameter exclude by creating program enum and ProgramParamsDTO and updating the controller and service
-  Added Unit tests

**Comment by david-cvp** [comment]
TC102 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/1a93cb97-32bd-467c-9afb-37d5129689f2)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/d99231ba-eea0-4d31-b222-3476669d49d3)
