### ISSUE TITLE
Design and develop Allowance Holdings user research study

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#866]

**Comment by nsameerun** [comment]
Allowance Holdings User Research Scenarios
[https://app.zenhub.com/files/287570343/5816cc87-6994-4559-b460-b5830a41c5c0/download](https://app.zenhub.com/files/287570343/5816cc87-6994-4559-b460-b5830a41c5c0/download)

@areighar @tlageman-epa @kstetsyuk
