### ISSUE TITLE
Debrief of research findings

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#867]

**Comment by JanellC** [comment]
The team held the allowance holdings study debrief on 4/12/2021. Notes from the debrief can be found[ here ](https://usepa.sharepoint.com/:o:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7Bebc3fb4d-ba1e-45cb-ac7c-095db55470fd%7D&action=edit&wd=target(UX%20Meeting%20Notes.one%7C39f26e63-355a-434e-ac77-d9a3f3d8130a%2F4%5C%2F12%5C%2F2020%20Allowance%20Holdings%20Study%20Debrief%7C5be3d829-93ad-4341-9817-29b0741c4630%2F))
