### ISSUE TITLE
Develop participant screener

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#869]

**Comment by nsameerun** [comment]
@areighar @tlageman-epa @kstetsyuk 


Allowance Holding UXR Study Participant Screener in development 03/03/21.

**Comment by nsameerun** [comment]
1st Draft delivered on 3/5/21 on MS Teams 
@areighar @kstetsyuk @tlageman-epa

**Comment by nsameerun** [comment]
@areighar @kstetsyuk @tlageman-epa 

03/10/2021- Finalized email to recruit participants for Allowance Holdings Study.

**Comment by nsameerun** [comment]
03/11/2021- Finalized Participant Screener and Pre-screener Email. Sent to Caiti. Closing Ticket. 

@areighar   @tlageman-epa  @kstetsyuk
