### ISSUE TITLE
Bug: Pagination extended response time & 500 error in Public API

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#875]
## Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Perform a GET request using pagination</p><br><p><a href="https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=10&beginDate=2019-01-01&endDate=2019-01-31">https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=10&beginDate=2019-01-01&endDate=2019-01-31</a>| API returns back 10 of 4.464 results sorted by:<br /><br>Facility &gt; unit &gt; date &gt; hour| Pass |
| 2| Perform a GET request using pagination for 5k records</p><br><p><a href="https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=5000&beginDate=2019-01-01&endDate=2019-01-31">https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=50000&beginDate=2019-01-01&endDate=2019-01-31</a>| API returns back 5k results sorted by:<br /><br>Facility &gt; unit &gt; date &gt; hour| Fail |

### Actual Results
When using pagination, large numerical values (over 100) for perPage result in extended response times, which can ultimately lead to the API timing out, failing to return data, and instead returning a 500 error code.

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/d9f13061-663a-4a9e-9e5d-8dc9d56b5405)

**Comment by david-cvp** [comment]
https://cvpcorp.testquality.com defect [D13](https://cvpcorp.testquality.com/project/11428/result/2301991/defect/7548). Do not remove or edit.

**Comment by JorjaComer** [comment]
Bug in the 3rd party software. Per 3/10 refinement, will not work this issue at this time. Can limit the number of records in pagination to mitigate if 3rd party dos not resolve.

**Comment by JanellC** [comment]
As of 5/19/22, need to look into this bug to see if this is still valid. Requirements for pagination have changed.

**Comment by tlageman-epa** [comment]
Closing since pagination was updated to 500 records per page.
