### ISSUE TITLE
Create Monitor Plan API endpoint for Systems 

### ISSUE THREAD

**Issue by SimeraHailu** [US-EPA-CAMD/PI-1#876]
endpoint that will accept a locId and return all systems for the specified location

endpoint uri
/api/monitor-plan-mgmt/locations/{loc-id}/systems

**Comment by mosesdeeCVP** [comment]
![876 Create Monitor Plan API endpoint for Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7ffaba2-8973-4316-b45e-057e082a5511)

**Comment by mosesdeeCVP** [comment]
Test Case [TC115](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276287) - Passed

**Comment by mosesdeeCVP** [comment]
Case Closed

**Comment by mosesdeeCVP** [comment]
Ticket re reopened in order to be updated. The beginHour and  endHour was added.

**Comment by mosesdeeCVP** [comment]
Re tested - Passed

**Comment by mosesdeeCVP** [comment]
![876 Create Monitor Plan API endpoint for Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/df05eb92-8ac1-4ff4-a2a6-7d498de488f7)

**Comment by mosesdeeCVP** [comment]
![876 Create Monitor Plan API endpoint for Systems.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/05c6d433-2083-4fd6-bff8-be1b34993f61)

systemIdentifier field was added and systemType data now reflects more accurately its data in the UI wireframes

**Comment by mosesdeeCVP** [comment]
Re tested - Passed
