### ISSUE TITLE
Monitoring Plan tab overflow navigation

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#878]
## User Story
As a user, I want to open a Facility tab, so that I can view the Facility's MP data.

## Acceptance Criteria
Given multiple open tabs for Facilities populate more than the width of the Facilities table
When the user chooses to view additional tabs
Then the system will provide the option to view additional tabs

Given a user has chosen to view additional tabs
When the user selects a tab from the option
Then the selected tab becomes active

Given the user has multiple tabs open
When the tabs fit within the window
Then the overflow tab navigation will not appear

Given a user has tabs open
When the user chooses to open a new tab
Then the new tab will appear to the right of the active tab

**Comment by JorjaComer** [comment]
Tabs are limited to 10. No longer needed
