### ISSUE TITLE
Create Monitor Plan API endpoint for System Components

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#879]
endpoint that will accept a locId and systemId and return all components for the specified location and system

endpoint uri
/api/monitor-plan-mgmt/locations/{loc-id}/systems/{system-id}/components

**Comment by mosesdeeCVP** [comment]
Test Case [TC114](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276286) - Passed

**Comment by mosesdeeCVP** [comment]
![879 Create Monitor Plan API endpoint for System Components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/69029830-b3e1-4e19-9357-df2425b373b2)

**Comment by mosesdeeCVP** [comment]
![879 Create Monitor Plan API endpoint for System Components.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2d8e97a6-ec92-4daf-9ade-c165ec9eebba)
