### ISSUE TITLE
Select Data Sub Type 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#884]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to select a data sub type
So that I can limit the data in my query 

## Acceptance Criteria
Given a user has selected a data type
When the filter criteria page is displayed
Then the user has the option to select a data sub type
And the options are Hourly Emissions, Daily Emissions, Monthly Emissions, Quarterly Emissions, Ozone Season Emissions, Annual Emissions, Facility/Unit Attributes 

Given a user has selected hourly emission sub type
When the user applies the selection
Then the filter criteria is displayed 

- Time Period
- Program
- Facility
- State
- Unit Type
- Fuel Type
- Control Technologies 

Given a user has selected hourly emission sub type
When filter criteria is selected
Then the filter criteria window(fly out) is displayed 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC135](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277181)
Tester: @JanellC  

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC135 passed @tlageman-epa 

Bug: Custom Data Download Select Data SubType #1085 resolved
