### ISSUE TITLE
Retain values across multiple open Facilities 

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#885]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to navigate among open Facilities, so that I can compare them per [the wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/).

## Acceptance Criteria
Given a user has multiple Facilities open
When the user switches from one Facility to another
Then the system retains the Facility's configuration and location values.

Given a user has selected the "Show Inactive" checkbox for multiple open Facilities
When the user switches from one Facility to another
Then the system retains the checked "Show Inactive" checkbox.

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Resolved by previous work
