### ISSUE TITLE
Create Monitor Plan API endpoint for Component Analyzer Ranges

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#886]
Endpoint returns data analyzer ranges for a particular component

**Comment by mosesdeeCVP** [comment]
## Testing
Test Case: [TC118](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276369)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
Test Case - Passed

**Comment by mosesdeeCVP** [comment]
![886 Create Monitor Plan API endpoint for Component Analyzer Ranges.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/2488d4c6-e4f4-42b0-9c62-0d2759ded063)
