### ISSUE TITLE
Create Monitor Plan API endpoint for System Fuel Flows

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#887]
Endpoint returns fuel flow data for a particular system

**Comment by mosesdeeCVP** [comment]
## Testing
Test Case: [TC119](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/276370)
Tester: @mosesdeeCVP

**Comment by mosesdeeCVP** [comment]
![887 Create Monitor Plan API endpoint for System Fuel Flows.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/251d41f2-2163-4392-95bc-110be9bbbb23)

**Comment by mosesdeeCVP** [comment]
Test Case - Passed
