### ISSUE TITLE
Filter Custom Data Download By Time Period 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#888]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I am required to enter filter criteria for time period so that my query is concise 

## Acceptance Criteria
Given that a user has selected hourly emissions
When the filter criteria page is displayed
Then the user must select time period (not null)
And has the option select operating hours only (default, selected)

Given a user has not entered a value in begin and end date 
When the filter is displayed
Then the ability to apply the filter is disabled

## Context
https://xd.adobe.com/view/afebee4f-e68e-4e10-ab99-d1f24fad0ca0-fab8/screen/78588963-3cef-4cdf-8318-e0bd6dc94e37?fullscreen

Date picker (USWDS date picker), formatted to be accepted by API and using global state from redux 
User may type or click dates in picker
Out of scope:
Format: MM/DD/YYYY
Valid date range: 01/01/1995 to current quarter
Only one date range may be selected at a time (annual data from 1980, not included in hourly query)

## Testing
Test Case: [TC140](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277187)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
USWDS date picker:

https://designsystem.digital.gov/components/date-range-picker/

**Comment by david-cvp** [comment]
TC140 passed @tlageman-epa

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/f3efe496-2ee7-430b-aad5-7405f09e270e)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/c9be3813-4445-4ff1-b93b-3b7207cefa59)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/43b630d6-9f71-4f7b-8ee1-7fecba3d6ad9)
