### ISSUE TITLE
Filter Custom Data Download By Program 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#889]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to enter filter criteria for program so that my dataset includes my desired program(s) 

## Acceptance Criteria
Given that a user has selected a data type and sub type
When the filter criteria page is displayed
Then user has the option to select program 

Given that a user has selected program 
When the functionality is displayed
Then the user has the option to select from active and inactive programs (MATS is excluded)	
And can select one or multiple programs 

Given that a user has applied filter criteria for program 
When any program criteria is cleared
Then the system clears the criteria from the filter 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Drop down, default blank
Values: All active and inactive programs (MATS is excluded)	
Optional
Multi select 

Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter in tag
Tag will remain fixed width, if parameters text exceeds fixed width, then full name is displayed in hover text/Tool tip
If more than 1, show number of parameters
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group

API Update #1002 

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Implemented as part of #1227
