### ISSUE TITLE
Integrate Sonar Scan with CI/CD Pipeline

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#89]
- [x] Dashboard report exists

**Comment by srinivasaregeti** [comment]
Started a feature branch to start working on integrating the Sonarscanner.

**Comment by srinivasaregeti** [comment]
Sonar scan dashboard after the pipeline runs:
https://sonarcloud.io/dashboard?id=US-EPA-CAMD_PI-1
