### ISSUE TITLE
Filter Custom Data Download By Fuel Type 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#894]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

NOTE: will provide the ability to select granular fuel types based on top level fuel type choice. Need to understand what the values are and how the UI will present the choice. 

## User Story
As a CAMPD custom data download user I want to enter filter criteria for fuel type so that my dataset includes data for my desired fuel type(s) 

## Acceptance Criteria
Given that a user has selected a data type and sub type
When the filter criteria page is displayed
Then user has the option to select fuel type 

Given that a user has selected fuel type
When the functionality is displayed
Then the user has the option to select from coal, gas, oil, and other 
And can select one or multiple fuel type groupings 

Given that a user has selected fuel type 
When the criteria are displayed
Then the user has the option to select/deselect all options with a group

Given that a user has selected fuel type 
When the functionality is displayed
Then the system displays a list of coal fuel types
And the user can select one or multiple coal fuel types

Given that has selected fuel type
When the functionality is displayed
Then the system displays a list of gas fuel types
And the user can select one or multiple gas fuel types

Given that a user has selected fuel type
When the functionality is displayed
Then the system displays a list of oil fuel types
And the user can select one or multiple oil fuel types

Given that a user has selected fuel type
When the functionality is displayed
Then the system displays a list of other fuel types
And the user can select one or multiple other fuel types

Given that a user has applied filter criteria for fuel type 
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria for fuel type 
When any fuel type criteria is cleared
Then the system clears the criteria from the filter

Given a user has selected filter criteria
When they select Preview Data
Then the filter criteria is reflected in the results

## Context 

[Wireframes ](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/c6d6ac0e-88ec-4467-a19f-e4281b973a3b/?hints=off) (NOTE: select All option will display next to group title not below)

For each fuel type, the select all option will be displayed in the group header (e.g. move All Coal up next to Coal)
Tags
Fuels type should be listed in the Fuel type name (Fuel Type code) format

From [Yesterday 3:45 PM] Nguyen, Theresa
 

 Junie Senthilkumar (Guest) - The analysts need time to work on the 'OTHER' fuel grouping before making changes in the database.  For now, please include 'Coal refuse' and 'Petroleum coke' in the 'COAL' grouping.

**Filter Tags**
Populates filter tag on Apply Filter
if 1 parameter is selected, then show parameter in tag
Tag will remain fixed width, if parameters text exceeds fixed width, then full name is displayed in hover text/Tool tip
If more than 1, show number of parameters
Clicking x in tag clear filter
Click on the tag opens filter in panel
Will provide the option to clear all filters in tag group
Tags will have a hover functionality to display the list of selections
The tool tip will display the fuel type code 

**Data Preview**

Refer to [CAMPD_DataLabels_HourlyEmissions_2_17_2021](https://teams.microsoft.com/l/file/A716F0AE-8006-4C66-9E19-1522779CBB16?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FCAMPD_DataLabels_HourlyEmissions_2_17_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) for column display names 

Trigger: A user has entered, at a minimum, the required parameters, and selected the option to preview data.
For each record that matches the criteria, the system will display in a tabular format:

STATE| FACILITY_NAME| ORISPL_CODE| UNITID | ASSOC_STACKS | OP_DATE |OP_HOUR| OP_TIME | GLOAD | SLOAD | SO2_MASS | SO2_MASS_MEASURE_FLG | SO2_RATE | SO2_RATE_MEASURE_FLG | NOX_MASS | NOX_MASS_MEASURE_FLG | NOX_RATE | NOX_RATE_MEASURE_FLG | CO2_MASS | CO2_MASS_MEASURE_FLG | CO2_RATE | CO2_RATE_MEASURE_FLG | HEAT_INPUT| PRIMARY_FUEL_INFO| SECONDARY_FUEL_INFO | UNIT_TYPE_INFO| SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO | PRG_CODE_INFO

Results will display total record count (Viewing the first 100 of X records)
Results are limited to 100 records (Hourly Emissions API is ordered by Facility > Unit > Date > Hour)
Results in preview are limited to the first 100 records
Results in preview will have a scroll functionality to show all columns/rows
Results columns are are sortable in ascending and descending order (alphanumeric order) . Sort is limited to the original 100 results 

## Testing
Test Case: [TC172](https://cvpcorp.testquality.com/project/11428/plan/20058/test/281049)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- updated store:
  - added fuelType to initialState
  - added actionsTypes LOAD_EMISSIONS_FUEL_TYPES_SUCCESS and HOURLY_EMISSIONS.UPDATE_FUEL_TYPE_SELECTION
  - updated actions/reducers
- added FuelType
  - updated FlyOutPanel as needed
- updated UnitTypeRenderer to UnitCheckboxRenderer (unit type, fuel type, and control tech can all use this)
- updated CheckBoxGroup for "select all" logic
- added fuelType to emissionsApi query
- moved some helper functions into a general file
- unit tests

**Comment by JanellC** [comment]
TC172 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/23d7a4bd-f9f7-4c91-a8e8-6f95e1d6751f)
