### ISSUE TITLE
Update data table to be 508 compliant

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/PI-1#895]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to view Monitoring Plan data tables in a way so that they are 508 compliant.

## Acceptance Criteria
Given the user views a Monitoring Plan data table,
When the user is viewing the table,
Then the table is compliant with 508 standards.

## Context
Correct, pagination in general will need care in keyboard accessibility and coding. See https://www.a11ymatters.com/pattern/pagination/ for an example. Right now one problem is that if a keyboard user activates a pagination page, 3 for example, visually the table is shifted, but when tabbing back, it goes to the last row of the table.
Other Notes

The dropdown with the active/inactive collapsible elements will be tricky, I'd suggest changing it to a checkbox outside that filters the dropdown values
Sortable tables need to be keyboard accessible and coded so that screen readers know if the column is sorted by ascending or descending, examples https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html, https://dequeuniversity.com/library/aria/table-sortable

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by aprematta** [comment]
Much improved, the data table is now keyboard accessible and has aria labels to let a screen reader know if the column is sorted by ascending or descending. Passes 508 review.
