### ISSUE TITLE
View an MP System's Fuel Flows Data in Modal Window

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#898]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user accesses a Facility's Monitoring Plan Systems 
When the user selects an individual System to view 
Then the System's Fuel Flows data (if it exists) is displayed in a modal window in accordance with the [business glossary (Fuel Flow)](https://xd.adobe.com/view/9a4c5deb-be48-44f8-89df-8ff70ad1c39d-cf1f/) and the [wireframes](https://xd.adobe.com/view/9a4c5deb-be48-44f8-89df-8ff70ad1c39d-cf1f/screen/897626c4-1c79-4cce-94b7-8855781335fd/)

In 1st modal, show Fuel Code, Type Code, Begin/End Dates 
Show all other fields on 2nd modal window (after selecting view)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC189](https://epacamd.testquality.com/project/11428/plan/20829/test/fullscreen/285616)

**Comment by mosesdeeCVP** [comment]
One of the steps has failed testing. The Fuel Code is not showing the correct data it is showing the Unit of Measure Code instead.

![898 View an MP Systems Fuel Flows Data in Modal Window - 01.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/1da532ca-f0ae-4ef4-b716-0c0544aff0f9)

![898 View an MP Systems Fuel Flows Data in Modal Window - 02.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/7ba9dd48-64a8-41ea-a2c2-05e224368b4e)

**Comment by mosesdeeCVP** [comment]
A bug ticket was opened: [1487](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1487)

**Comment by mosesdeeCVP** [comment]
Bug ticket is assigned to developer to be worked on.
