### ISSUE TITLE
Design BRE system for validating Monitoring Plan data

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#901]
Design system following research spike #900 to support PI 4 and PI 5 development

**Comment by david-cvp** [comment]
https://github.com/US-EPA-CAMD/diagrams/blob/develop/EPA%20CAMD%20BRE%20Check%20Engine.pdf

**Comment by jwhitehead77** [comment]
Meet with ERG and received a spreadsheet of all the MP checks with details regarding categories and order of processing. Have look through existing check engine get familiar with the process and reviewed check specifications.

**High Level Architecture**
https://github.com/US-EPA-CAMD/diagrams
https://github.com/US-EPA-CAMD/diagrams/blob/develop/EPA%20CAMD%20BRE%20Check%20Engine.pdf

**Built preliminary UI for Rule Authoring**
https://easey-dev.app.cloud.gov/admin/rules

**Built preliminary API for Rule Authoring**
https://github.com/US-EPA-CAMD/easey-rules-api

**Built preliminary Scheduling & Evaluation process**
https://github.com/US-EPA-CAMD/easey-job-scheduler
