### ISSUE TITLE
View System Component Data in Second-Level Modal Window

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#903]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user accesses the first-level modal listing the System's Components 
When the user selects an individual Component to view 
Then the Component's data is displayed in a second-level modal in accordance with the [business glossary (Components)](https://teams.microsoft.com/l/file/B181553F-E249-41A5-9BB8-8D075563054E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20In%2FMonitoring%20Plan%20Requirements%20Package%2FMonitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.2.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) and the [wireframes](https://xd.adobe.com/view/9a4c5deb-be48-44f8-89df-8ff70ad1c39d-cf1f/screen/d2f0231f-94a6-4a98-9840-576ab77e125d/)

**Comment by mosesdeeCVP** [comment]
Test Case: [TC188](https://epacamd.testquality.com/project/11428/plan/19812/test/fullscreen/285372)

**Comment by mosesdeeCVP** [comment]
Test Passed. All functionality is working.

**Comment by mosesdeeCVP** [comment]
Bug ticket [1478](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1478) was created for the typo

Bug ticket [1479](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/1479) was created for the DateFormat

**Comment by mosesdeeCVP** [comment]
![903 View System Component Data in Second-Level Modal Window.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/229267ca-8d87-45bf-83ed-b80f4404b049)
