### ISSUE TITLE
Change Selected Data Type and Sub Type 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#906]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to edit my selected data type so that my data set includes my desired data type 

## Acceptance Criteria
Given that a user has selected a data type 
When they select change 
Then the option to select emissions, allowance, and compliance data is displayed 

Given a user has selected a data type
When the data sub type is not selected
Then the Apply option is disabled 

Given a user has opted to change the data type or sub type
When values are not changed from original selection 
Then the option to apply is disabled 

Given a user has opted to change the data type or sub type
When no new selections are made (either cancel or apply with same values)
Then filter criteria and any selected values for the criteria are retained 

Given a user has selected change 
When the functionality is displayed 
Then the user has the option to cancel 

Given a user has selected a new data type
When the sub data type and filters are displayed
Then they are displayed in accordance with the [CAMPD Filter Criteria by Data Type](https://teams.microsoft.com/_#/files/General?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&threadId=19%3A6f05dfa026c84672a2cc1bfa72c58f14%40thread.skype&ctx=channel&context=EASEY%2520Out&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FGeneral%252FAnalysis%252C%2520User%2520Research%2520and%2520Design%252FAnalysis%252FEASEY%2520Out) 

## Context
Select change
If a data type and sub data type were already selected, then data type and sub data type retain currently selected options
If a new data type is selected, then data sub type is cleared
User must select a data sub type 
If a new sub type is selected, then filter criteria updates upon Apply 
If a user chooses to cancel, then no changes are applied 

[Wireframe](https://xd.adobe.com/view/374836c9-1159-4586-9094-f79554057bfa-621b/) 

## Testing
Test Case: [TC162](https://cvpcorp.testquality.com/project/11428/plan/20058/test/279648)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

#### DataTypeSelectorRender
- Moved the change button to only show once both data type and data sub type are selected
- Added the drop down to change data type
- Added disabled logic to the apply button
- Added a cancel button
  - Will only show up if the user selects the change button  

#### ManageDataDownload
- Added dispatchers:
  - updateSelectedDataTypeDispatcher
  - removeAppliedFiltersDispatcher
- Added handler for the data type dropdown
- Updated handler for the apply button
- Added handler for cancel button
- Added  useEffect hook to control the logic for disabling/activating the apply button

#### ManageDataPreview
- Added Allowance and Compliance to the mapDataPreview

#### actions/customDataDownload && reducers/customDataDownload 
- Added the removeAppliedFilter function

#### Constants
- Separated constant files
  - customDataDownload
  - emissions
  - allowances
  - compliances

**Comment by JanellC** [comment]
TC162 passed @tlageman-epa @kstetsyuk 

https://easey-dev.app.cloud.gov/campd/select-data-type
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/96437017-b810-4684-b225-b3e9f66dd80d)
