### ISSUE TITLE
Implement model testing framework

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/PI-1#91]
- [x] Integrate test libraries
- [x] Set up page object model
- [x] Set up base utility framework (base functions, error handling)
- [x] Upload to GitHub repository

A/C:
Initial testing model implemented
Base functions, page objects created, test cases, error handling

**Comment by YefimAbramsonCVP** [comment]
Integrated TestNG and Selenium Libraries
Set-up base structure for Page Object Model
Defined a few of the base methods for ui navigation

**Comment by YefimAbramsonCVP** [comment]
Added basic API methods
Uploaded to https://github.com/US-EPA-CAMD/Testing/ repository
