### ISSUE TITLE
Validate multiple values for Program in AH API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#913]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to enter valid filter criteria for multiple programs  so that I can see results 

## Acceptance Criteria
Given that a user has entered one or more program codes in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more program codes without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more program codes with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more invalid programs
When the API endpoint is executed
Then the returns the message FV-12
"One or more programs is not valid. Refer to the list of available programs for valid values [placeholder for link to endpoint]

## Context
will use program codes, excludes MATS
Will make case insensitive
Return data for multiple values
When entering multiple values the API will allow pipe separated list of values including one or more whitespace(s) before and after the delimiter but will not require whitespace
Contains search
MATS data is excluded from results 

## Data Elements
Query results will include:
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION
OWN_DISPLAY
ACCOUNT_TYPE

## Testing
Test Case: 
Tester: @davidkwartler 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17 the team decided to complete the AH API by creating tickets #972, #973, #974, #975
