### ISSUE TITLE
Validate multiple values for owner in AH API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#926]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to enter valid filter criteria for multiple owners so that I can see results

## Acceptance Criteria
Given that a user has entered filter criteria for owner
When the API endpoint is executed
Then the system validates:
TBD

Given that a user has entered one or more owners in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more owners without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more owners with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered an invalid parameter for owner
When the API endpoint is executed
Then the system displays error message TBD

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Data Elements 
Query results will include:
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION
OWN_DISPLAY
ACCOUNT_TYPE

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17 the team decided to complete the AH API by creating tickets #972, #973, #974, #975
