### ISSUE TITLE
Validate multiple values for vintage year in AH API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#928]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user 
I want to enter valid filter criteria for vintage year
So that I can see results 

## Acceptance Criteria
[Error message repo ](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)
Given that a user has entered a date is not in the format YYYY
When the API endpoint is executed
Then the system displays an error message (FV-5)

Given that a user has entered a date is not valid (example: 2015-15-45)
When the API endpoint is executed
Then the system displays an error message (FV-11)

Given that a user has entered a date range where the end date is not equal to or greater than start date
When the API endpoint is executed
Then the system displays an error message (Fv-6)

Given that a user has entered a year is outside of range (1995-current year)
When the API endpoint is executed
Then the system displays an error message (FV-7

Given the system has detected any error conditions for date
When the error messages are returned
Then the system returns the first encountered error message

Format
Valid date
Everything else

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Data Elements
Query results will include:
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION
OWN_DISPLAY
ACCOUNT_TYPE

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17 the team decided to complete the AH API by creating tickets #972, #973, #974, #975
