### ISSUE TITLE
Validate date in DE API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#934]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to ensure my filter criteria for begin date and end date is valid So that I can get accurate results 

## Acceptance Criteria
Given that a user has entered a date is not in the format YYYY-MM-DD
When the API endpoint is executed
Then the system displays an error message (FV-5)

Given that a user has entered a date is not valid (example: 2015-15-45)
When the API endpoint is executed
Then the system displays an error message (FV-11)

Given that a user has entered a date range where the end date is not equal to or greater than start date
When the API endpoint is executed
Then the system displays an error message (Fv-6)

Given that a user has entered a year is outside of range (1995-CURRENT YEAR)
When the API endpoint is executed
Then the system displays an error message (FV-7

Given the system has detected any error conditions for date
When the error messages are returned
Then the system returns the first encountered error message

Format
Valid date
Everything else

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17, the team decided to complete the DE API by creating tickets #967, #968, #969, #970
