### ISSUE TITLE
Validate ORIS Code in DE API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#936]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want to enter valid filter criteria for ORIS codes so that I can see results 

## Acceptance Criteria
Given that a user has entered filter criteria for ORIS code
When the API endpoint is executed
Then the system validates:
That the format is correct

- positive integer (no negative numbers, not 0)
- whole numeric value (no letters or special characters)
- no more than 6 digits
- leading 0s are accepted
- It matches a valid facility number (ORIS code)

Given that a user has entered an invalid parameter for ORIS code
When the API endpoint is executed
Then the system displays error message with a url to the end point to find the correct data fv-8
Error Message: ORIS code not valid. Refer to the list of available ORIS codes for valid values [placeholder for link to Facilities endpoint] FV-8

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17, the team decided to complete the DE API by creating tickets #967, #968, #969, #970
