### ISSUE TITLE
Validate control tech in DE API

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#944]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want enter valid filter criteria control technologies so that I can see results for my specified control technologies 

## Acceptance Criteria
Given that a user has entered one or more control technologies in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more control technologies without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more  control technologies with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given a user has entered an invalid parameter for control technology
When the error message is displayed
Then the error messages contain a url to the end point to find the correct data
fv-3 One or more control technologies are not valid. Refer to the list of available control technologies for valid values [placeholder for link to endpoint]"

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Send valid and invalid values
Validate the values
If ANY invalid value, give error message for each invalid value and query stops
If ALL values are valid, return results

## Data Elements
Results:
When the system identifies at least one record that matches the criteria, then for each record the system will display:
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO
 
## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
During sprint planning on 3/17, the team decided to complete the DE API by creating tickets #967, #968, #969, #970
