### ISSUE TITLE
UI design and content layout for responsiveness 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#947]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a 
I want
So that

## Acceptance Criteria
Given
When
Then

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

At the UX weekly for CAMPD on 3/16, the team decided to move forward by providing the front-end developer with the break points for different device and prioritizing the desktop view for the May demo. This ticket serves as a reminder for the team to discuss the content layout UI design for CAMPD on tablets, mobile devices, and etc.  

UX- Notes from the UX weekly for CAMPD on 3/16 can be found[ here](https://usepa.sharepoint.com/:o:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7Bebc3fb4d-ba1e-45cb-ac7c-095db55470fd%7D&action=edit&wd=target(UX%20Meeting%20Notes.one%7C39f26e63-355a-434e-ac77-d9a3f3d8130a%2F3%5C%2F16%5C%2F2021%20UX%20Weekly%20for%20CAMPD%7Ca1437f7d-0c9a-4455-8dfb-6fe9c1e32c83%2F))

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Per 3.4 sprint planning part 2, team will focus on desktop content and layout at this time

**Comment by JorjaComer** [comment]
https://xd.adobe.com/view/0d66fc88-4098-434f-a84d-63b15ed6ef9f-5835/flow
