### ISSUE TITLE
Mobile device and tablet breaks

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#948]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want the site to be compatible with my electronic device (mobile, tablet, and desktop) so that I can access the site's content 

## Acceptance Criteria
Given that a user has navigated to the custom data download on a desktop, mobile device, or a tablet 
When the functionality is displayed 
Then the site adheres to USWDS breakpoint guidelines and renders appropriately

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
https://designsystem.digital.gov/utilities/layout-grid/

## Testing
Test Case:
Tester: @davidkwartler 

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
PEr 3.4 sprint planning part 2, team will focus on desktop content only at this time

**Comment by JorjaComer** [comment]
Will be handled via #1460
