### ISSUE TITLE
View System Component's Analyzer Range Data in Second-Level Modal Window

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#949]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Acceptance Criteria
Given a user accesses the first-level modal window listing the System's Components 
When the user selects an individual Component to view 
Then the Component's Analyzer Range data, if applicable, is displayed in a second-level modal window in accordance with the [business glossary (Analyzer Range)](https://teams.microsoft.com/l/file/B181553F-E249-41A5-9BB8-8D075563054E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20In%2FMonitoring%20Plan%20Requirements%20Package%2FMonitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.2.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) and the [wireframes]https://xd.adobe.com/view/dccab567-3abe-484a-bff7-844d701cd4eb-8999/)

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case: [TC251](https://epacamd.testquality.com/project/11428/plan/19812/test/295565)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![949 View System Component's Analyzer Range Data in Second-Level Modal Window.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/bc0cbce0-162f-46d6-86e9-384504f82a2c)

**Comment by mosesdeeCVP** [comment]
Test Case Passed
