### ISSUE TITLE
Set Up Unit Testing Framework 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#96]
- [x] Tools in place for testing and configured (Jest)
- [x] Unit tests trigger from pull request

**Comment by YefimAbramsonCVP** [comment]
Updated the unitTest.sh bash script to run the jest suite for task-api. Will need to set-up the jest api for the web app and the post-api projects. Will also need to coordinate with one of our repo admins to configure the branch protection to block pull requests.

**Comment by david-cvp** [comment]
Will set up branch protection at a later date once Sonarcloud is configured
