### ISSUE TITLE
View System Details 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#961]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to view system details
So that I can see the MP data for that system 

## Acceptance Criteria
Given a user has selected a system
When the user chooses to view a system
Then the system displays the system details:
System ID
System Designation
System Type
Fuel Type 
Start Date
End Date 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
[Wireframes](https://xd.adobe.com/view/ccf2dda8-0f33-4df9-a581-6556fbdedeb9-99a1/screen/277d73d0-2982-4c78-a3d3-17d41d6c8454?fullscreen)

## Testing
Test Case: [TC132](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/277032)
Tester: @mosesdeeCVP 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by mosesdeeCVP** [comment]
![961 View System Details.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/49196ef2-df69-4bc8-bae9-d8856dd1de10)

**Comment by mosesdeeCVP** [comment]
Test Case: Passed
