### ISSUE TITLE
View System Components 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#962]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user
I want to view components
So that I can review system data 

## Acceptance Criteria
Given a user has selected a system
When the user chooses to view a system
Then the system displays the components for that system's details
And provide the option to view a particular system component 

- Component ID
- Component Code
- Start Date/Time
- End Date/Time

## Context
[Wireframes](https://xd.adobe.com/view/ccf2dda8-0f33-4df9-a581-6556fbdedeb9-99a1/screen/277d73d0-2982-4c78-a3d3-17d41d6c8454?fullscreen)
Add Component option is visible, but disabled 
Show Inactive check box is out of scope 
All active/inactive shown by default 

Fill out fields in accordance with [business glossary](https://teams.microsoft.com/l/file/B181553F-E249-41A5-9BB8-8D075563054E?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20In%2FMonitoring%20Plan%20Requirements%20Package%2FMonitoring%20Plan%20Business%20Glossary-EPA%20CAMD-v2.2.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Testing
Test Case: [TC133](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/277033)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
TC133 passed

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/67c1adcc-d656-4c51-b687-27fd564a9594)
