### ISSUE TITLE
Task:  Refactor hourly emissions API

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#967]
## Goal 
Refactor the hourly emissions API to support code reusability

## Dev Tasks 

- [x] refactor repository: create a query builder helper function
- [x] rename hourly-apportioned-emissions files to apportioned-emissions
- [x] update routes.ts
- [x] update variables in controller
- [x] update variables in service
- [x] update variables in modules
- [x] ensure unit tests still pass

 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

**Comment by junie-stigdon** [comment]
## Pull Request

- refactored repository
  - created a query builder helper function
- renamed hourly-apportioned-emissions files to apportioned-emissions
- updated routes.ts
  - added '/hourly' in the GET function for getHourlyEmissions
- updated variables in controller
- updated variables in service
- updated variables in modules
- unit tests

**Comment by david-cvp** [comment]
All test cases passed

TC82, TC83, TC84, TC85, TC86, TC96, TC100, TC103, TC104, TC105, TC106, TC107, TC111

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/99b50fe3-7102-4448-99a3-896130bc6a0c)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/af999475-4bff-4226-af05-2b31701208d0)
