### ISSUE TITLE
Send multiple daily emissions parameters and return dummy data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#968]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want send filter criteria to the daily emissions API so that I can see results 

## Acceptance Criteria
Given that a user has entered one or more values for all the parameters (see parameters below) 
When API endpoint is executed 
Then the system returns "hello world" as a result 

## Dev Tasks 

- [x] update controller
- [x] update service
- [x] update routes.ts
- [x] return DTO
- [x] param DTO
- [x] unit tests

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Can send multiple criteria/parameters and get hello world, no data, no validation 
  
## Parameters 
Begin Date
End Date
ORIS code
State
Unit Type
Unit Fuel Type
Control technologies
Program

## Testing
Test Case: [TC120](https://cvpcorp.testquality.com/project/11428/plan/20059/test/fullscreen/276452)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- refactored DTOs
  - ApportionedEmissionsDTO
  - HourlyApportionedEmissionsDTO (extends ApportionedEmissionsDTO)
  - DailyApportionedEmissionsDTO (extends ApportionedEmissionsDTO)
  - ApportionedEmissionsParamsDTO
  - HourlyApportionedEmissionsParamsDTO (extends ApportionedEmissionsParamsDTO)
- added getDailyEmissions to controller
- added getDailyEmissions to service
- unit tests

**Comment by david-cvp** [comment]
TC120 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/daily?beginDate=2019-01-01&endDate=2019-01-31&unitType=Cyclone%20boiler&unitFuelType=Coal%20Refuse&program=CAIRNOX|CAIROS

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/33dca15c-7be2-4a92-bd35-efd2b0ba578b)
