### ISSUE TITLE
Send multiple daily emissions parameters and return data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#969]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want to send filter criteria to the daily emissions API so that I can see results

## Acceptance Criteria
Given that a user has entered one or more valid values for all the parameters (see parameters below)
When API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more valid values for all the parameters in an upper case or lower case format 
When API endpoint is executed
Then the system displays the records that match the criteria 

Given that a user has entered one or more valid values for all the parameters without white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria 

Given that a user has entered one or more valid values for all the parameters with white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Can send multiple parameters and get data, valid parameters only. 
can send single and multiple parameters
white spaces allowed before and after delimiter 
case insensitive 

## Dev Tasks
- [x] day-unit entity
- [x] update unit-fact entity
- [x] day-unit repo
- [x] day-unit map
- [x] update service
- [x] unit tests

## Data Elements 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Date 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

## Parameters 
Begin Date
End Date
ORIS code
State
Unit Type
Unit Fuel Type
Control technologies
Program

## Testing
Test Case: [TC122](https://cvpcorp.testquality.com/project/11428/plan/20059/test/276455)
Tester: @davidkwartler @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by junie-stigdon** [comment]
## Pull Request

- created DayUnitData entity
- added table relationship between DayUnitData and UnitFact
- created DayUnitDataRepository
- created ApportionedEmissionsMap (extends BaseMap)
- updated HourlyApportionedEmissionsMap (extends ApportionedEmissionsMap)
- created DailyApportionedEmissionsMap (extends ApportionedEmissionsMap)
- updated service to map DayUnitData entities to DTOs
- updated controller to return daily apportioned emissions data
- updated module imports and providers
- unit tests

**Comment by david-cvp** [comment]
TC122 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/6c504c1c-78e9-4763-881e-9d7d2f284d09)
