### ISSUE TITLE
Validation for Daily Emissions API 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#970]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user I want to send valid filter criteria to the daily emissions API so that I can see results 

## Acceptance Criteria
Given that a user has entered one or more values for all the parameters (see parameters below)
When API endpoint is executed
Then the system displays the records that match the criteria (containing data elements below)

Given that a user has entered one or more values for all the parameters in an upper case or lower case format
When API endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered one or more values for all the parameters without white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered one or more values for all the parameters with white space(s) before or after the delimiter
When API endpoint is executed
Then the system displays the records that match the criteria

Given that a user has entered one or more invalid values for a  parameter
When the API endpoint is executed
Then the system displays the appropriate error message ([see error message repo)](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) 

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Can send parameters, parameters are validated, data returned or error messages 
can send single and multiple values 
case insensitive 
white spaces allowed before and after the delimiter 

## Data Elements 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
OP_DATE
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

## Parameters 
Begin Date
End Date
ORIS code
State
Unit Type
Unit Fuel Type
Control technologies
Program

## Testing
Test Case: [TC127](https://cvpcorp.testquality.com/project/11428/plan/20059/test/276539)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
Would like to reduce estimate & confirm with Jorja + Janell before testing this. So far, looks good:

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/d547afcb-fbba-4e2a-902c-96a6f64bd5f0)

**Comment by david-cvp** [comment]
TC127 passed @tlageman-epa 

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/daily?beginDate=invalid&endDate=invalid&state=invalid&orisCode=invalid&unitType=invalid&unitFuelType=invalid&controlTechnologies=invalid&program=invalid
