### ISSUE TITLE
Send Required Allowance Holdings Parameters 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#973]
## Adjusted Estimate

Actual: 3
Original: 5

Reason: Learned from Emissions API setup so the Allowance API setup was simpler 
The query logic to return allowance data was not particularly complex, just pulling from tables

### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want send filter criteria to the allowance holdings  API so that I can see results

## Acceptance Criteria
Given that a user has entered filter criteria for vintage begin year and vintage end year  
When the API end point is executed 
Then the system displays the records that match the criteria (containing data elements below)

## Dev Tasks 
- [x] Create Repo
- [x] Create DTO
- [x] Create ParamsDTO
- [x] Create maps
- [x] Add QueryBuilderHelper
- [x] Create entities (allowance_holding_dim and account_fact)
- [x] Modify service and controller to return allowance data 
- [x] Unit tests

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Can send required fields (dates), returns data (includes account type, program in results)

## Parameters 
Vintage Begin Year: Required
Vintage End Year: Required

## Data Elements 
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION (2 digit number)
OWN_DISPLAY
ACCOUNT_TYPE

## Testing
Test Case: [TC126](https://cvpcorp.testquality.com/project/11428/plan/20060/test/276472)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by sdhawan16** [comment]
Create PR:
Added functionality to send required allowance holdings parameters (vintageBeginYear and vintageEndYear) to return allowance holdings data elements

- Added DTO and ParamsDTO
- Added entities (allowance_holding_dim and account_fact)
- Added BaseMap and AllowanceHoldingsMap
- Added QueryBuilderHelper class 
- Added Repository
- Modified module, service and controller to return allowance data
- Modified unit tests

**Comment by david-cvp** [comment]
TC126 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/c72aa121-04c2-4b12-8088-220ac64e568a)
