### ISSUE TITLE
Create parameters for primary fuel type and secondary fuel type in hourly emissions API 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#976]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want send filter criteria for primary fuel type and/ or secondary fuel type so that results contain my desired fuel type 

## Acceptance Criteria
Given 
When
Then

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

During requirements elicitation on 3/17, the team discussed splitting the hourly emission API fuel type parameter into two parameters (ex. primary fuel type and secondary fuel type) 

 
## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
Per PI 4 planning, not doing at this time
