### ISSUE TITLE
SPIKE: Determine the best method to retrieve active programs for allowance holdings API

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#979]
## Background 

During sprint planning on 3/17, the team discussed needing a research spike for the program parameter  

## Acceptance Criteria
Given
When
Then

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

Program: optional, multiple values allowed, active allowance only, values:  ARP, CSNOX, CSOSG1/2, CSSO2G1/2, TXSO2 

## Testing
Test Case:
Tester:

**Comment by JorjaComer** [comment]
Will create a script to add a trading end date to CSNOXOS. Work will be handled via tech team backlog for dev environment. Will also need to update prod database (ERG). @tlageman-epa will coordinate with ERG for update.
