### ISSUE TITLE
SPIKE: Determine the best method to retrieve account type for allowance holdings API 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#980]
## Background 
During sprint planning on 3/17, the team discussed needing a research spike for the account type  parameter  

## Acceptance Criteria
Given
When
Then

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Testing
Test Case:
Tester:

**Comment by JorjaComer** [comment]
Spike no longer needed. Work to accomplish the desired functionality will be handled in the tech team backlog.
