### ISSUE TITLE
Add program parameter to allowance holdings public API 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#981]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD API user I want enter filter criteria for program so that I can conduct analysis on my desired program(s) 

## Acceptance Criteria
Given that a user has entered one or more program codes in an upper-case or lower case format
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more program codes without white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more program codes with white space(s) before or after the delimiter
When the API endpoint is executed
Then the system displays the results for multiple programs

Given that a user has entered one or more invalid programs
When the API endpoint is executed
Then the returns the message FV-12
"One or more programs is not valid. Refer to the list of available programs for valid values [placeholder for link to endpoint]

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
Program: optional, multiple values allowed, active allowance only, values: ARP, CSNOX, CSOSG1/2, CSSO2G1/2, TXSO2

## Testing
Test Case:
Tester:

## Data Elements 
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION (2 digit number)
OWN_DISPLAY
ACCOUNT_TYPE

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
included in #974
