### ISSUE TITLE
Filter Active and Inactive Systems

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#984]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?
## User Story
As a user, I want to be able to view active and inactive systems, so that I can view all systems assigned to a monitoring location 

## Acceptance Criteria
Given a user has selected a configuration and location
When the user chooses to view Systems data
Then the system displays Active systems for the given location

Given a user has selected a configuration and location
When the user chooses to view Systems data and has checked the "Show Inactive" checkbox
Then the system displays both Active and Inactive systems for the given location

Active systems are systems with no end date/hr and the location is active
Inactive systems are systems with an end date/hr or no end date/hr and the location is inactive

**Comment by JorjaComer** [comment]
OBE by new editing flow
