### ISSUE TITLE
Hourly Emissions Date Validations 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#987]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to enter valid filter criteria for time period so that I can generate a customized dataset 

## Acceptance Criteria
Given a user has entered a time period (not null)
When the user applies the filter
Then the system will ensure that the data is valid 

Given that a user has selected time period 
When the criteria is entered 
Then the system ensures the date is in the MM/DD/YYYY format
And displays VF-16 if not 

Given that a user has selected time period 
When the criteria is entered 
Then the system ensures that begin date is equal to or greater than the end date 
And displays error message [FV-6 ](https://teams.microsoft.com/l/file/24F21292-7E8D-4118-9BFF-83816A2C6CEC?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FError%20Messages-EPA%20CAMD-v1.0.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) if not 

Given a validation has failed
When the error message is displayed
Then the error message is displayed in accordance with the [USWDS validation component ](https://designsystem.digital.gov/components/validation/)

## Context
https://designsystem.digital.gov/components/validation/

## Testing
Test Case: [TC141](https://cvpcorp.testquality.com/project/11428/plan/20058/test/277188)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
TC141 failed

New bug #1086 created

**Comment by david-cvp** [comment]
TC141 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/fbd74f74-ca2f-41d3-b50b-fb00cee2a5f5)
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/28bc59d3-8ba0-4f30-a904-b10509a741b3)

**Comment by davidkwartler** [comment]
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/28bc59d3-8ba0-4f30-a904-b10509a741b3)
