### ISSUE TITLE
Preview Hourly Emissions Data 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#988]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to preview my dataset so that I can confirm it contains my desired data 

## Acceptance Criteria

Given that a user has selected all the required fields 
When the functionality is displayed  
Then the preview data functionality is enabled 

Given that a user has selected preview data 
When the functionality is displayed 
Then the system will display the dataset's total record count

Given that a user has selected preview data 
When the functionality is displayed 
Then the system displays a data table containing the data elements below (limited to the first 100 records)
And the data table contains a scroll functionality to show all columns/rows

## Context
Scope:
For required filters only (time period) 

[Wireframes ](https://xd.adobe.com/view/3bd31746-18a9-4282-82ec-292ad7708767-6e80/)

Refer to [CAMPD_DataLabels_HourlyEmissions_2_17_2021](https://teams.microsoft.com/l/file/A716F0AE-8006-4C66-9E19-1522779CBB16?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FCAMPD_DataLabels_HourlyEmissions_2_17_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) for column display names 

Data Preview
Trigger: A user has entered, at a minimum, the required parameters, and selected the option to preview data.
For each record that matches the criteria, the system will display in a tabular format:

STATE| FACILITY_NAME| ORISPL_CODE| UNITID | ASSOC_STACKS | OP_DATE |OP_HOUR| OP_TIME | GLOAD | SLOAD | SO2_MASS | SO2_MASS_MEASURE_FLG | SO2_RATE | SO2_RATE_MEASURE_FLG | NOX_MASS | NOX_MASS_MEASURE_FLG | NOX_RATE | NOX_RATE_MEASURE_FLG | CO2_MASS | CO2_MASS_MEASURE_FLG | CO2_RATE | CO2_RATE_MEASURE_FLG | HEAT_INPUT| PRIMARY_FUEL_INFO| SECONDARY_FUEL_INFO | UNIT_TYPE_INFO| SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO | PRG_CODE_INFO

Results will display total record count (Viewing the first 100 of X records)
Results are limited to 100 records (Hourly Emissions API is ordered by Facility > Unit > Date > Hour)
Results in preview are limited to the first 100 records
Results in preview will have a scroll functionality to show all columns/rows
Results columns are are sortable in ascending and descending order (alphanumeric order) . Sort is limited to the original 100 results 

## Testing
Test Case: [TC148](https://cvpcorp.testquality.com/project/11428/plan/20058/test/278043)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by tlageman-epa** [comment]
EPA provided a list of data labels for each of the data elements that will be returned in the hourly emissions data. Please make sure to reference those so that the data preview and download has the correct data labels. @JorjaComer

**Comment by tlageman-epa** [comment]
@JorjaComer @addisgmichael I want to make sure that the development on this is using the [high fidelity designs](https://xd.adobe.com/view/3bd31746-18a9-4282-82ec-292ad7708767-6e80/screen/ae06d28f-bab7-4d37-8e53-ab3db4dcac07/) Alex just shared. I believe the link to the wireframes in the ticket goes to the black/white version used in the UX study. Let me know if there are any questions. Thanks!

**Comment by JorjaComer** [comment]
See updated link for WF

**Comment by tlageman-epa** [comment]
Morning, @addisgmichael , I see you are making some good progress. I know that you are working still so I'm sure this will be sorted out but wanted to make sure about a few things.

1. The data column headers (labels) in the preview must match what were in linked in the spreadsheet above. I noticed a number of them were not matching. (e..g, Fuel Type (Primary) vs. Primary Fuel Type)

2. Also, only some data labels have white spaces between the units and parentheses (e.g., Heat Input (mmBtu) vs. Heat Input(mmBtu) ). They should all have a white space between the label and associated units in parentheses. 

3. Additionally, I noticed that a number of data columns are missing but assuming that is because you are still working. 

4. I realized that two of the labels (Associated Stacks and Program) are not included in the data labels spreadsheet linked, but are in the Facility/Unit Attributes data labels spreadsheet linked [here](https://teams.microsoft.com/l/file/AA12A78C-B7BA-4E76-B694-71985AAE42A6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FCAMPD_DataLabels_FacilityAttributes_4_2_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23).

Let me know if you have any questions, and keep up the good work.

**Comment by addisgmichael** [comment]
> Morning, @addisgmichael , I see you are making some good progress. I know that you are working still so I'm sure this will be sorted out but wanted to make sure about a few things.
> 
> 1. The data column headers (labels) in the preview must match what were in linked in the spreadsheet above. I noticed a number of them were not matching. (e..g, Fuel Type (Primary) vs. Primary Fuel Type)
> 2. Also, only some data labels have white spaces between the units and parentheses (e.g., Heat Input (mmBtu) vs. Heat Input(mmBtu) ). They should all have a white space between the label and associated units in parentheses.
> 3. Additionally, I noticed that a number of data columns are missing but assuming that is because you are still working.
> 4. I realized that two of the labels (Associated Stacks and Program) are not included in the data labels spreadsheet linked, but are in the Facility/Unit Attributes data labels spreadsheet linked [here](https://teams.microsoft.com/l/file/AA12A78C-B7BA-4E76-B694-71985AAE42A6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=xlsx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FGeneral%20Overview%2FCAMPD_DataLabels_FacilityAttributes_4_2_2021.xlsx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23).
> 
> Let me know if you have any questions, and keep up the good work.

@tlageman-epa Hi Travis, thanks for your feedback. I just pushed in updates reflecting your concerns for the data-preview. Also I've removed the "Continue" button in the CDD landing page (select data type page). Please have a look. The Styling updates as per high fidelity design are to be addressed in a separate ticket by Tony and will be in shortly.
