### ISSUE TITLE
Select Download File Type for Hourly Emissions 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#989]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to select a file type so that my customized dataset is in my desired file format 
## Acceptance Criteria

Given that a user has previewed their dataset 
When the data preview functionality is displayed  
Then it includes the option to select a CSV or JSON file type (CSV is the default) and download

## Context
[See 8 of 10 ](https://xd.adobe.com/view/3bd31746-18a9-4282-82ec-292ad7708767-6e80/screen/ae06d28f-bab7-4d37-8e53-ab3db4dcac07/)

The download button will not be functional. 

## Testing
Test Case: [TC167](https://cvpcorp.testquality.com/project/11428/plan/20058/test/280934)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JorjaComer** [comment]
rolled into download

**Comment by junie-stigdon** [comment]
## Pull Request

- created DownloadFileType component
- adjusted DataPreviewRender
  - added DownloadFileType component to it
  - display flex
  - updates to scss files
- unit tests
- updated sonar-project.properties to exclude config files in coverage

**Comment by JanellC** [comment]
TC167 passed @tlageman-epa 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/91a12526-001b-46a3-8468-33be4e45fd15)

**Comment by tlageman-epa** [comment]
@JanellC @junie-cvp is testing look at all browsers? I'm getting a weird display on firefox no matter the zoom level. The image below is @100%. It appears to be working on chrome just fine, but curious if this is a bug or my computer is causing the issue. The ticket can stay closed, but I want to check if we have a bug to address later on. Thanks!

![image.png](https://images.zenhubusercontent.com/5f3fd6e5a36605390ed80be4/2aae58f6-f3a9-4bcc-a174-b4e859c26cc2)

**Comment by junie-stigdon** [comment]
Hi @tlageman-epa , thanks for bringing this to my attention. I'll look into it and report back to you!

**Comment by JanellC** [comment]
Hi @tlageman-epa, thank you for bringing this to our attention.  I logged Bug: Select Download File Type for Hourly Emissions #1377 to the backlog for this issue ,and I added a meet after topic to tomorrows DSU so we can discuss this further.
