### ISSUE TITLE
Download Data for Apportioned Emissions 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#990]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD custom data download user I want to download my customized dataset so that I can conduct analysis 

## Acceptance Criteria
Given that a user has selected a file type 
When the download is executed 
Then the system creates a file in the format specified containing all records that match the parameters and downloads the file

Given that a user has downloaded their dataset
When the functionality is displayed 
Then the system display the preview of the downloaded results.

Given that a user has applied filter criteria  and has previewed their dataset
When any filter criteria is cleared
Then the system clears the criteria from the filter AND the download functionality is disabled until the dataset is previewed again

## Context
Scope: This ticket will implement download functionality for hourly, daily, and monthly emissions

[Wireframes ](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/screen/cb933da9-aeb1-46b7-be2f-ac5aa8f8278a?hints=off)

Included selecting file type - update AC 

Download
Trigger: The user has selected a file output type
When the user selects the option to download, the system creates a file in the format specified containing all records that match the parameters and downloads the file

After a user has chosen to download data, then the system will display the preview of the downloaded results.

## Testing
Test Case: [TC178](https://cvpcorp.testquality.com/project/11428/plan/20058/test/283515)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC178 passed @tlageman-epa 


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/dd076200-5809-40cd-a519-fb5a7169d54d)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4bebc5a3-0523-4dc5-9973-dc8810cdeb8e)


![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/42b9441e-4544-4f71-b2a6-fe13c814422f)

**Comment by tlageman-epa** [comment]
@JanellC @junie-cvp On firefox I am noticing a missing/incorrect content type in the response header which is not displaying the appropriate file format in the browser download pop up. (Note: text document from blob) This may be confusing to some users using Firefox. Please address this and see image below. It is happening for both json and csv, but looks good on Chrome. Thx!

![image.png](https://images.zenhubusercontent.com/5f3fd6e5a36605390ed80be4/6feb588f-9413-4395-af87-af556bac4825)

**Comment by JanellC** [comment]
Hi @tlageman-epa I logged Bug: Download Data for Apportioned Emissions #1485 for this.
