### ISSUE TITLE
Systems table open by default

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#994]
As a user I want to see the Systems table open by default

This is a bug from [402](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/402)

**Comment by karenhwwoo** [comment]
Chris W. agreed during refinement on 3/24/21 that this can be pushed to PI4.

**Comment by karenhwwoo** [comment]
Can be closed, included in #1087.
