### ISSUE TITLE
Create Active/Inactive Flag for Component

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#999]
If a Monitoring Location is inactive or a Component has an end date, Component should be inactive. Show in API.

**Comment by mosesdeeCVP** [comment]
Test case created: [TC130](https://cvpcorp.testquality.com/project/11428/plan/19812/test/fullscreen/277030)

**Comment by mosesdeeCVP** [comment]
Test case: Passed

**Comment by mosesdeeCVP** [comment]
![999 Create Active-Inactive Flag for Component.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/ab159dc4-ae18-4a35-8e36-1df7ce17a6cd)
